### ISSUE TITLE
Table links numbering

### ISSUE THREAD

**Issue by uskka** [openstax/cnx-recipes#1000]
Table links in webview should be numbered with only table number without chapter number like in the PDF. 
https://katalyst01.cnx.org/contents/_VPq4foj@8.4:VYbyR_vl@10/2-4-Fitting-Linear-Models-to-Data

Webview

<img width="871" alt="Screenshot 2019-04-10 at 15 41 28" src="https://user-images.githubusercontent.com/40228918/55883772-377b3c00-5ba7-11e9-9bbf-4af49d13f706.png">

PDF 

<img width="691" alt="Screenshot 2019-04-10 at 15 41 19" src="https://user-images.githubusercontent.com/40228918/55883775-377b3c00-5ba7-11e9-9bff-e0c7002814f3.png">

**Comment by uskka** [comment]
Looks good. Tested on katalyst01.

<img width="975" alt="Screenshot 2019-04-16 at 12 50 36" src="https://user-images.githubusercontent.com/40228918/56203818-400bc080-6046-11e9-9304-e8f38d4b545e.png">

<img width="1217" alt="Screenshot 2019-04-16 at 12 49 38" src="https://user-images.githubusercontent.com/40228918/56203753-1f436b00-6046-11e9-8ff6-a91029857c69.png">

**Comment by MartaSztuka** [comment]
Looks good, Tested on katalyst01.
![Screenshot from 2019-04-18 15-25-22](https://user-images.githubusercontent.com/47241114/56364219-52286300-61ee-11e9-9a01-0747053d90ce.png)
