### ISSUE TITLE
Bad page break in C O N C E P T S I N P R ACT I C E feature in Financial Accounting

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1002]
# What happened?

Everything after the title of a feature box in Financial Accounting is kicked to the next page. It may have to do with a table in the box, but there are a couple paragraphs before it that should be on the same page with the title.

# Reproducibility Details

- **Does this happen in one place, a few places, or everywhere?**: just one.

# Environment:

- **Book(s)**: Financial Accounting
- **URL/Server**: https://legacy.cnx.org/content/m67914/latest (production)
- **Location (page number, chapter/section)**: 13.2 folio page 828
- **Suggested nearby searchable text**: Bond Ratings

# Screenshots

<img width="596" alt="Screen Shot 2019-04-10 at 3 39 47 PM" src="https://user-images.githubusercontent.com/1895432/55916658-93978d80-5bb2-11e9-8786-b5121e7c9257.png">
<img width="588" alt="Screen Shot 2019-04-10 at 3 39 52 PM" src="https://user-images.githubusercontent.com/1895432/55916674-998d6e80-5bb2-11e9-937f-3c1416f25bc3.png">

**Comment by openstaxalina** [comment]
Issue moved to [openstax/oer.exports #3903](https://github.com/openstax/oer.exports/issues/3903) via [**ZenHub**](https://www.zenhub.com/)
