### ISSUE TITLE
Numbering in Section Exercises, Review Exercises and Practice Test

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1003]
https://katalyst01.cnx.org/contents/yqV9q0HH@13.3:ddc_1utP@13.3/Review-Exercises
https://katalyst01.cnx.org/contents/CImQfPDv@3.19:RavexchO@3.19/Review-Exercises
https://katalyst01.cnx.org/contents/AndhM9Sd@4.13:j63wVwt-@4.13/Practice-Test

In PDF
Exercises in each Chapter (Section Exercises, Review and Practice test) have continuous numbering within chapter. Starts over in the begining of each chapter.

In webview
numbering in Section Exercises and EOC is independent:
In Section exercises numbering starts in first section
and continuous till the end of chapter.

![review](https://user-images.githubusercontent.com/47241114/55945857-df4a4580-5c4b-11e9-91a2-1b43a189ebfc.jpeg)

**Comment by Adrianltd** [comment]
Issue no longer exists, because the https://github.com/openstax/cnx-recipes/pull/987 no longer affects `dev-math` books. @MartaSztuka please rebake `dev-math` books from the `master` branch.
