### ISSUE TITLE
Cases for various element cases in recipes + internationalization work

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1011]
The Polish recipe for University Physics needs tables to support cases in order to be merged. This is the ground work needed to convert our recipes to support different languages. We should implement some of the logic and file structure that would support future work in enabling a more comprehensive approach to localization and different languages support. Some of that work has been started in https://github.com/openstax/cnx-recipes/pull/377, should be extracted and resolved in a separate PR.

**Comment by openstaxalina** [comment]
The goal is to implement such that only the Polish recipe is affected, **none of the other files**.  If this will impact other files, we need to discuss the test load.

**Comment by brittweinstein** [comment]
We need @aiwenar's documentation before work can begin.

**Comment by openstaxalina** [comment]
@paulinaszczucinska will discuss with @aiwenar.  If we could receive at least the first part of the documentation, that could allow Natalia and others to work on getting the Polish University Physics recipe merged.

**Comment by helenemccarron** [comment]
We should focus on removing any hard coded values and order assumptions from the mixins first. This will allow for the Polish recipe to be completed. 

Later, we can reassess the config files's structure and consider moving variables but we should complete the mixin's refactor first.

**Comment by brittweinstein** [comment]
Natalia's Documentation: https://docs.google.com/document/d/1O14g4C2PIOp1M3SFis5bxE867VcVvg6z8J_4d2VwhJY/edit#heading=h.fejamw5qncxb

**Comment by openstaxalina** [comment]
Went with the bare minimum of changes, to recipes only and should not have any impact on currently baked content (all OpenStax books).  cc @helenemccarron and @Stackblocks in case I misstated anything.

**Comment by brittweinstein** [comment]
@wilkus27 this seems to be ready to be merged and go to testing. Is this the case?

**Comment by wilkus27** [comment]
@brittweinstein Yes, I've just merged it.

**Comment by wilkus27** [comment]
**Summary**: problem with order assumption is resolved by https://github.com/openstax/cnx-recipes/pull/1187. There are created new mixins which allow to change order of elements in titles and captions of figures and tables. This solution is an option for future textbooks, so is not implemented to any existing book at this moment.

Here is an example how it could be implemented in future: https://github.com/openstax/cnx-recipes/pull/1187/commits/54127417eedced091724fa0b5e26e5f33469de09.

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/_VPq4foj@10.62:th6Mz08o@10/9-4-Partial-Fractions
Tested on random book (Precalculus) No changes in titles, figure captions or tables.

**Comment by brittweinstein** [comment]
@MartaSztuka per Natalia, we can close this! :)
