### ISSUE TITLE
EShip Recipe Fix to accomodate glossary

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#1012]
# What happened?

Entrepreneurship didn't fully bake because recipe doesn't look for "div[data-type="glossary"]" 

# Environment:

- **Book(s)**: Entrepreneurship
- **URL/Server**: Production
- **Browser**: google chrome

**Comment by Stackblocks** [comment]
Appears to be fully baked using Thomas's fix. 

**Previously (_from discussion w/ Theresa_)**
![image](https://user-images.githubusercontent.com/12678235/58263941-9c978500-7d42-11e9-93d7-1872cf460ef5.png)


**Currently**
![image](https://user-images.githubusercontent.com/12678235/58264039-c3ee5200-7d42-11e9-9746-a01037d4a691.png)
