### ISSUE TITLE
Create symlink, enable dropdown for Cal and Precal Trio AW

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1018]
We need to do all the steps so that there is a dropdown parameter available for the following recipes:

**Calculus with recipe**
(_Calculus Volumes 1-3_)

**Precalculus with recipe**
(_Precalculus, Algebra & Trigonometry, College Algebra_)

The goal is for the content managers to be able to adjust the parameters in the Legacy collection editor, in order to bake and regression test these the week of May 13.

**Comment by helenemccarron** [comment]
Addressed in PR https://github.com/openstax/oer.exports/pull/3916
