### ISSUE TITLE
Leading too wide in Exercises

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1027]
https://katalyst01.cnx.org/contents/oxzXkyFi@3.7:yhpfq5F1@5/1-1-Parametric-Equations
![lead](https://user-images.githubusercontent.com/47241114/56582475-a7da8200-65d7-11e9-8596-f5853679eb72.jpeg)

**Comment by openstaxalina** [comment]
@MartaSztuka does this occur only one time?

**Comment by MartaSztuka** [comment]
@openstaxalina yes, I didn't find any other cases.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #776](https://github.com/openstax/content-managers/issues/776) via [**ZenHub**](https://www.zenhub.com/)
