### ISSUE TITLE
[Resolve with Baked PDF] Accounting - Dropping MathML text in PDF

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/cnx-recipes#1029]
Production Server, as seen in M03
GLOBAL - Known Issue

MathML text is dropped in the PDF output of M03. This did _not_ occur in the Staging version of the title, and does not occur in webview. Opening this issue to flag for manual correction and to document in case this instance is unique, although the issue generally is a known Prince bug.

Staging
[Pages from OSC_Acct_ChM03_col10033_MW_KC2-2.pdf](https://github.com/openstax/cnx-recipes/files/3109055/Pages.from.OSC_Acct_ChM03_col10033_MW_KC2-2.pdf)

Production
[Pages from ManagerialAccounting-OP.pdf](https://github.com/openstax/cnx-recipes/files/3109059/Pages.from.ManagerialAccounting-OP.pdf)

**Comment by brittweinstein** [comment]
Let's come back to this after work on the Corn theme to see if this is resolved.

**Comment by lwtchu** [comment]
![Screen Shot 2021-03-02 at 12 03 09 PM](https://user-images.githubusercontent.com/11299125/109693454-49757780-7b4f-11eb-98f6-c8ec715bd538.png)
fixed with new pipeline
