### ISSUE TITLE
Trash abstract from Preface

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1031]
Issue https://github.com/openstax/cnx-recipes/issues/762 shows that there used to be additional part at the beginning of the Preface in **Anatomy.** Previously, it was resolved by release flag **trash-abstract-in-preface**. To standardized the way of resolving problems with trashing selected elements in different books, this issue should be resolved as in https://github.com/openstax/cnx-recipes/pull/967.

This is how it used to be:

![image](https://user-images.githubusercontent.com/40228854/56640352-16205280-6673-11e9-9a17-d1b07a4e6a25.png)

**Comment by MartaSztuka** [comment]
Tested on katalyst01.
No unwelcome changes were found.
![Screenshot from 2019-05-20 16-37-56](https://user-images.githubusercontent.com/47241114/58030488-ea33a800-7b1e-11e9-8756-39fb2409a0d2.png)
