### ISSUE TITLE
Trash part of Check Your Understanding

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1032]
In **University Physics** title of the **Check Your Understanding** is hardcoded. Because of that, after baking this note has two the same titles. This is how it's resolved now:

![image](https://user-images.githubusercontent.com/40228854/56640988-972c1980-6674-11e9-8107-08eb9d105477.png)

It's a screenshot from **_config.scss** file for u-physics.

This problem should be resolved as in https://github.com/openstax/cnx-recipes/pull/967.

**Comment by MartaSztuka** [comment]
All 3 books tested on katalyst01
Proposed solution did not cause any unwelcome changes.
![Screenshot from 2019-05-20 16-38-53](https://user-images.githubusercontent.com/47241114/58030370-b8224600-7b1e-11e9-8ba3-9634975039f5.png)
