### ISSUE TITLE
Alien table titles in Astronomy appendices

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1037]
# What happened?

Magic alien text appears on top of many tables in Astronomy appendices where it doesn't belong. There is only one table that should have the title "The Cosmic Haystack Problem: Some Questions about an Extraterrestrial Message", and it is in 30.4. I downloaded the book in neb, and this text is only present in the content in its proper place, which means that the recipe may somehow be generating it.

# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: This error appears with every table in the appendices; specifically it can be found twice in Appendix D, twice in Appendix E, four times in Appendix F, once in Appendix G, twice in Appendix H, once in Appendix I, once in Appendix K, and once in Appendix L.

# Environment:

- **Book(s)**: Astronomy
- **URL/Server**: production appendices
- **Location (page number, chapter/section)**: for example, https://cnx.org/contents/LnN76Opl@21.1:_eJEiQMX@11/D-Units-Used-in-Science
- **Suggested nearby searchable text**: The Cosmic Haystack Problem: Some Questions about an Extraterrestrial Message
- **Browser**: Firefox

# Screenshots

<img width="600" alt="Screen Shot 2019-04-24 at 1 52 43 PM" src="https://user-images.githubusercontent.com/1895432/56685757-49290d00-6698-11e9-9778-4360940552cd.png">

**Comment by oscryan** [comment]
This problem is not present in unbaked content, as seen in this prior version we unbaked for testing on Jan 8 https://cnx.org/contents/LnN76Opl@17.1:_eJEiQMX@10/Units-Used-in-Science

**Comment by oscryan** [comment]
It is not present in this Dec revision with notes "span-all to top-titled" https://cnx.org/contents/LnN76Opl@14.33:_eJEiQMX@10/Units-Used-in-Science but it is there in every baked version after that.

**Comment by openstaxalina** [comment]
Yes, agree I am seeing this in all baked versions of Astronomy, starting with the first version that was released on January 22.

**Comment by openstaxalina** [comment]
I also see this issue on staging: https://staging.cnx.org/contents/LnN76Opl@21.1:_eJEiQMX@11/D-Units-Used-in-Science

**Comment by brittweinstein** [comment]
@tomjw64 please put points on this when you can

**Comment by Stackblocks** [comment]
Alien messages have been redacted, the secret is safe again.

![image](https://user-images.githubusercontent.com/12678235/56813658-0a639600-6803-11e9-9893-fe1e85d70e85.png)
