### ISSUE TITLE
Change request: Support para titles in the recipe

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1046]
# Scenario
It has come for us to support `<title>` tags in `<para>`. They should be treated like a title. 
Please look at scenario 1 & 2 in this long issue: https://app.zenhub.com/workspaces/content-5c86d8c40b66e07993f45cfa/issues/openstax/content-managers/758

# Impact

* **Severity**: [x] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [x] High [ ] Medium  [ ] Low

# Test Plan 
These will be most prevalent in Examples. Please see locations in the issue linked above.

# Acceptance Criteria
Titles in paragraphs are targetable and style-able.

**Comment by openstaxalina** [comment]
**Tentative decision:** no recipe change, style the `<span data-type="title">`.  Test this in the framework to ensure this is sustainable moving forward.
