### ISSUE TITLE
Organizational Behavior: Quote Attribution to be aligned RIGHT

### ISSUE THREAD

**Issue by clteam18** [openstax/cnx-recipes#1048]
**Chapter 1 – m10895**

**XML Markup**

![image](https://user-images.githubusercontent.com/39794953/57178053-a2f3b900-6e88-11e9-82a4-f4f40f157217.png)

**WEB View**

![image](https://user-images.githubusercontent.com/39794953/57178054-aab35d80-6e88-11e9-8471-a1fecfb1797a.png)

**Comments:** Quote attribution should be left aligned, please advise for the markup.

**Comment by openstaxalina** [comment]
@marcjeannott could you take a look at this when you get the chance?  Perhaps an` align="right"` attribute would work?

**Comment by marcjeannott** [comment]
The only way we could get this is by creating unnumbered unlabeled tables with empty cells and a set cell width.

**Comment by openstaxalina** [comment]
Confirmed with Mike Roche that the display above is acceptable.  No further changes needed.  Closing cc @clteam18
