### ISSUE TITLE
Organizational Behavior: Markup for small-caps element

### ISSUE THREAD

**Issue by clteam18** [openstax/cnx-recipes#1049]
**Chapter 8 – m10950**

**WEB**

![image](https://user-images.githubusercontent.com/39794953/57178066-ea7a4500-6e88-11e9-9a0e-8013eb61dc05.png)

**Comments:** Bold faced **A.M.** and **P.M.** should be originally in small-caps instead of bold formatting. But there is no element available for small-caps in complete cnxml tag list. Please advise to code for small-caps.

**Comment by openstaxalina** [comment]
@marcjeannott could you take a look at this when you get a chance?  We may not be able to support small caps.

**Comment by marcjeannott** [comment]
There is no way to do this in CNXML. Maybe some styling changes?

**Comment by openstaxalina** [comment]
Yep agreed.  I'll ask Mike about this on tomorrow's call.

**Comment by openstaxalina** [comment]
Per Mike Roche - it is okay to set these as normal text, so that the display is:

8:00-9:00 A.M
12:30-1:30 P.M. 

etc.

@clteam18 please review and confirm you are able to set these as normal text.

**Comment by clteam18** [comment]
@openstaxalina Yes, we will set this as normal text. Closing this now.
