### ISSUE TITLE
WAITING CE DISCUSSION: Scripts Improvements: Exploration

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1054]
# Scenario

The Books developers will take over some of the script improvements for the Baked PDF CLI.  This is a card to capture the explorations for that work.

# Steps to Reproduce

* **How many times were you able to reproduce the issue?** 

* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)

# Environment:

* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org  
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact

* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan 

# Acceptance Criteria

**Comment by brittweinstein** [comment]
Books and CNX will meet to discuss on June 10.
