### ISSUE TITLE
Chapter intro order change

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#1064]
# What happened?
To implement the introduction  in Lisa's design, we need a recipe change: 
 1. `div .os-figure` (splash image) needs to be the first visible child of `.introduction`
 2.  All `p` should be placed in their own div.
 3.  The `p` container  and the `.os-chapter-outline`  the container should be placed in a `div` together (eg `os-intro-body`)

# Environment:

- **Book(s)**:
- **URL/Server**: 
- **Location (page number, chapter/section)**:
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots

(_attach here (please clearly label what environment each screenshot came from)_)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by helenemccarron** [comment]
We might want to discuss this, based on Lisa's template, it looks like this is the page's name

**Comment by openstaxalina** [comment]
Moving into the current milestone to remind us to discuss this (needs/timeline, etc.)

**Comment by brittweinstein** [comment]
We need to figure out what kind of infrastructure we will need to support in order to link design templates and recipe features together. A MANIFEST.

**Comment by brittany-johnson** [comment]
Decision: 
To begin moving towards recipes and styles being coupled together, we will begin to move recipe mixins that are related to a particular element requiring a recipe change due to design into a new file. This is so that we can eventually have a more component-based design in cnx-recipes.

Steps that will be taken relating to this specific issue: 
1. Create a variable in the book file that will specify which template the book should use 
2. Create a new file that will hold the mixins related to the recipe change
3. Extract the related mixin(s) from their original location and place them in the newly created file 
4. In the newly created file, add the new logic related to the recipe change in a new mixin
5. In the file where you extracted the mixin, add logic that will use mixinA if templateX is used and else mixinB

**Comment by openstaxalina** [comment]
@brittany-johnson to add a feature flag

**Comment by brittany-johnson** [comment]
<img width="1772" alt="Screen Shot 2019-08-08 at 8 49 46 AM" src="https://user-images.githubusercontent.com/24909007/62708714-8d2aee00-b9b9-11e9-9470-f4c92b12ccdc.png">

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code. 

Chapter outline and intro text are now in a div called `intro-body` and below the splash image.
(Alignment of chapter outline being handled in another issue.)

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1412669e-5127-44bc-837d-49c06cac914b)
