### ISSUE TITLE
APUSH Recipe

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1068]
# Scenario

It has come time to create a recipe for APUSH (_U.S. History for AP® Courses_).  This could be based on the existing recipe `American Government with recipe`, as this is the "placeholder" recipe we've been using during testing.

Here are the things we know about this recipe:
- It should **not** have an Answer Key.
- There should be **no** end of chapter collation. (There may be classes, such as "review-questions", on content sections.  Tutor will use these.  However, the recipe should ignore these.)
- There should be one end of book collating item: the Index.
- `<exercise>` numbering should restart at "1" with each section.  (Using [this content](https://content05.cnx.org/contents/CmIfJ6vh) as an example, the numbering starts at "1" with the first item encoded as an exercise in the "Chapter Introductory Essay", and the exercise numbering should restart at "1" again in the section "Native People".)
- Three classes will be used on art:
(a) `scaled-down` - should display at 60% of the viewport
(b) `scaled-down-30` - should display at 30% of the viewport
(c) NEW `full-width` - should display at 100% of the viewport
- Exercise styling needs the three tweaks described in the screenshot:
![APUSHExerciseTweaks](https://user-images.githubusercontent.com/7863733/57953699-7727f880-78b6-11e9-8f7b-266d93600d62.png)

# Environment:

* **Medium**: [ ] REX [ ] PDF  [x] cnx.org  

## Books title:
- _U.S. History for AP® Courses_ 

### Collections: 
Chapter One Sample: https://content05.cnx.org/contents/CmIfJ6vh

### Checklist
- [ ] Update/create book map
- [x] Update books.txt with new book’s UUID
- [x] Create all notes config entries
- [x] Create all EOC config entries
- [x] Create all EOB config entries
- [ ] Create all book specific config entries
- [ ] Create all styleguide snippets
- [x] Update books.txt RECIPE_DESC with the new book’s description
- [x] Update manifest.json with the new book entry
- [x] Request a symlink to be created in OER.exports (+ verify it’s working before release)
- [ ] Finalize book map to match recipe (include any change that might have been decided while developing the recipe)

**Comment by openstaxalina** [comment]
Tutor is the primary destination platform for this content.  

We will not create an oer.exports PDF for this title.  Eventually, we will implement the baked PDF styles (likely the Mad Men/Humanities theme) if a PDF output is needed.

**Comment by openstaxalina** [comment]
Sample content is here: https://content05.cnx.org/contents/CmIfJ6vh

**Comment by openstaxalina** [comment]
Discussed with @Stackblocks - please test against the display here, which Wisewire and BRI (authors) are fairly happy with.  We don't want the display in webview to change significantly (except for the specific items noted above), as this could also trigger display differences when the content is ingested in Tutor.

**Comment by openstaxalina** [comment]
@oscryan and @lwtchu would be good contacts if questions come up about this while I am out (week of June 10).

**Comment by brittweinstein** [comment]
@tomjw64 will share what he can with @oscryan and iterate from there.

**Comment by brittweinstein** [comment]
Next step: @Stackblocks will move this to easyvm5 for testing on webview.

**Comment by Stackblocks** [comment]
Content at https://easyvm5.cnx.org/contents/Yqi4rV04@2.1:18R1WAF1@1/1-2-Chapter-Introductory-Essay

**Comment by openstaxalina** [comment]
Decision: we will merge this for the June 21 code freeze.  We can continue to iterate on this recipe once more requirements are known, if bugs are found, etc.

**Comment by Stackblocks** [comment]
Questions didn't import to the dev environment correctly with the content so they'll need to be tested on staging. Answer key is still generating but may be related to this. Will need to be retested / fixed if the behavior is the same when the questions are in place.

New tags displaying as specified with updated version of content / code.

---
## scaled-down
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/42937d76-8ff2-4e37-a635-14d6b6405a02)

---
## scaled-down-30
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e958932d-5f3c-43ec-89d9-d942e609f8e8)

---
#full-width

Can't find in test content, applied manually and it appears to work fine. 

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/bd40f1b7-7046-48ec-bfc7-748ea2c62979)

**Comment by openstaxalina** [comment]
Created issue to migrate content to staging for more testing: https://github.com/openstax/content-managers/issues/913

**Comment by openstaxalina** [comment]
Tested here: https://staging.cnx.org/contents/KC8KeLYF@2.1:nx-LSZj6@5/1-1-%F0%9F%93%8E-Inquiry-Organizer

- confirmed no answer key
- confirmed no end of chapter collation
- confirmed Index is present
- confirmed the word "Exercise" has been removed


did not pass testing:
- exercise numbering does not restart at 1 with each section.  I will open an issue for this. 
- exercise is written on the line below the number.  I will open an issue for this.

**Comment by Stackblocks** [comment]
Work specific to the new problems to be tracked in the issues marked above. Closing this issue.
