### ISSUE TITLE
carnival theme: table of contents styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1070]
![Screen Shot 2019-05-20 at 1 49 34 PM](https://user-images.githubusercontent.com/11299125/58044734-23135300-7b06-11e9-8d9c-82c94d4968a5.png)
**see below comment for design specs for sans unit**
Title "Contents": IBM Plex Sans Light, 4.3rem (if 1rem = 10px), NO SHADING, 3rem padding under

Base font (module, preface, appendix, glossary, index, answer key, etc): Alegreya (modules) or IBM Plex Sans (preface/appendix/etc), 1.2rem

Unit and number: Title, color (book specific), IBM Plex Sans, 1.44rem
Stroke under the unit number: 0.5px (0.05rem) 
If there is no units, the unit and number and stroke shouldn't be there.

Chapter and number: all caps, Muli Black, 1.2rem

Chapter title: IBM Plex Sans Medium, 2.074rem

Module titles and number: #.# Title - Alegreya, 1.44rem

Appendix: Appendix # is bold and next to the title

Page numbers: 3rem from the text 

Reference https://drive.google.com/drive/folders/1pzlxZ6q2UhP3b47AqkvNc_iBBRbgdsVa

**Comment by brittweinstein** [comment]
We need info on how this should look if there are not units.

**Comment by openstaxalina** [comment]
We asked Lisa for a ToC design without units -- she will send it to us this week.

**Comment by openstaxalina** [comment]
https://github.com/openstax/cnx-recipes/issues/1134 is related

**Comment by lwtchu** [comment]
![Screen Shot 2019-07-19 at 3 43 35 PM](https://user-images.githubusercontent.com/11299125/61565818-cbc72b80-aa3f-11e9-8c13-b466f6e5a3f8.png)

Title "Contents": IBM Plex Sans Light, 4.3rem (if 1rem = 10px), NO SHADING, 3rem padding under

Chapter title: IBM Plex Sans Medium, 2.074rem

Base font (module, preface, appendix, glossary, index, answer key, etc): Alegreya (modules) or IBM Plex Sans (preface/appendix/etc), 1.2rem

Chapter Number: Muli Black, all caps, 1.2 rem

Appendix: Appendix # is bold and next to the title

Page numbers: 3rem from the text
Page numbers for Chapter are right aligned with a dotted line connecting the title with the page number.

**Comment by tomjw64** [comment]
Spacing under preface and each chapter block : 2rem

**Comment by Stackblocks** [comment]
90% of the way complete. The majority of styling is complete, but the Chapter Titles are in bolded `Muli` instead of `IBM Plex Sans`, while the connecting line and number on the chapter title line are in `IBM Plex Sans`.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a8612a1e-bb75-4a1f-9467-2a50a835daf3)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c4e7500b-53d4-4c28-a7ba-6a190cabf87a)

Issues with the page numbering will be handled with a recipe change in an upcoming sprint.

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/efbb3b6c-d155-42dc-9d40-19a530a8a96d)

**Comment by wilkus27** [comment]
Additional/updated specs: 

Title "Contents": stroke 5px width, solid, color book specific

Chapter Number: color book specific
Chapter Title: black (as on the first screenshot)

Appendix Number: Muli, bolder, not all caps
