### ISSUE TITLE
carnival theme: preface styling 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1073]
![Screen Shot 2019-05-20 at 2 48 26 PM](https://user-images.githubusercontent.com/11299125/58047697-5a85fd80-7b0e-11e9-96ca-0f72b7903c61.png)
![Screen Shot 2019-05-20 at 2 48 29 PM](https://user-images.githubusercontent.com/11299125/58047698-5a85fd80-7b0e-11e9-8a3a-c65d1177c787.png)

Preface: IBM Plex Sans, Bold, all caps, 2.448rem, 2rem padding under
Stroke: 0.1rem (1pt?) stroke, 2em padding under
Body text: should be the same as the typography specs specified in another card #1072  
Body color: should match the color chosen in book specs (example for chemistry please reference #1086)

**Comment by openstaxalina** [comment]
@lwtchu please review and confirm this has the info you want for the *preface*.

**Comment by richelleyy** [comment]
THE PDF SHOULD LOOK LIKE THIS：
<img width="996" alt="Screen Shot 2019-07-15 at 3 18 16 PM" src="https://user-images.githubusercontent.com/50836449/61246210-efbf0000-a713-11e9-8bc5-002df51aa422.png">

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/fcf19660-4cef-467a-b275-7b8802ef3b8b)

## QA Breakdown
### Pass
- IBM Plex Sans font displaying

### Fail
-  Headers not bolded
-  Title not all-caps
-  Font sizes are off 
-  Stroke missing

### Notes
- According to the typography chart for a 10px rem, 2.488 would be 18.66pt font, neither the page title nor the headers align to this where one should

**Comment by richelleyy** [comment]
It looks like this with fonts applied:
<img width="1002" alt="Screen Shot 2019-07-17 at 3 56 05 PM" src="https://user-images.githubusercontent.com/50836449/61412285-187afd00-a8ae-11e9-8f61-8bf0992e78c7.png">

**Comment by Stackblocks** [comment]
All but one issue has been resolved, section headers in the preface are still Times New Roman while the module title in the preface and section titles in the rest of the book are IBM Plex Sans.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/745b914f-a2ba-490e-bfce-8d582e02ad76)

---

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d94c65c1-17a9-4608-810b-c4c7887579fe)
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a7a2aef9-8321-460c-9e40-724420e74aaa)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ee7dd2af-8d0f-4ce8-8ca6-5e9c3479b547)

**Comment by Stackblocks** [comment]
Reopening for cleanup

**Comment by helenemccarron** [comment]
@lwtchu and @Stackblocks the Preface page in the PDF found here https://drive.google.com/drive/folders/1gXs4VUFDNWzvxFvU7cDEw9qtllzJjVRX looks like this:
![2019-08-09_10-48-24](https://user-images.githubusercontent.com/8514591/62791759-7062e900-ba93-11e9-8a7a-4810499cf19a.png)

This is vastly different from the screenshots provided for the appendices. Are we not using the treatment provided in the design?

**Comment by lwtchu** [comment]
@helenemccarron we're not. lisa's design uses a different font scale for headers for the preface and more colors, so in order to reduce the amount of colors for the palette in one book, i decided to use the appendices style treatment

**Comment by Stackblocks** [comment]
Marking as resolved.

![2019-08-15_12-06-09.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5a0a3321-5f5e-4942-bf39-5a3df546e585)
---
![2019-08-15_12-06-24.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/888b4e3c-a5e6-4d20-bd9c-92273995b1a4)
---
![2019-08-15_12-07-11.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b42a4080-3684-45e3-b668-aac724ed9dd3)
