### ISSUE TITLE
carnival theme: color band for end of book and end of chapter material

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1074]
![Screen Shot 2019-05-20 at 3 40 50 PM](https://user-images.githubusercontent.com/11299125/58050694-aab48e00-7b15-11e9-9c7b-44b26f914aef.png)
See band color on the left

2.5 rem + standard 0.125in bleed, color book level (should match block on splash)

If band can't be targeted to just EOC material, it can span the whole page.

**Comment by openstaxalina** [comment]
Have tried this a few ways, but having trouble getting this working with Prince.  

Maybe try a background color on the page.  

Another option would be a 1 height pixel.

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/335f534f-9c87-4b6c-bdb7-151e5319dec8)

**Comment by Stackblocks** [comment]
Side question, this _is_ supposed to alternate sides for the purposes of being on the outside when printed, yes?

**Comment by lwtchu** [comment]
@Stackblocks yes - when you close the book you should see the blue on the spine and you can find EOC/EOB content easier
