### ISSUE TITLE
carnival theme: splash image

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1075]
![Screen Shot 2019-05-20 at 3 42 01 PM](https://user-images.githubusercontent.com/11299125/58050750-d46db500-7b15-11e9-9f35-adce9ee61a9c.png)

Size of the entire object: full page width (8.5in) plus 0.125in bleeds on top, left and right
Color bar color: determined on book level
Color bar size: Can it be full page width plus bleeds and the image can sit on top and left aligned? 
Photo: Left aligned with a 0.125in bleed
Grey box for caption: #EEEAE0, 1rem top-bottom padding inside box; 2rem padding after

Styling for Chapter number: Muli Black, 2.074rem; 0.75rem padding under
Styling for Chapter title: IBM Plex Light; 3.583rem; 0.75rem padding under 
This font stuff is also mentioned in #1072

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a2b5d94e-e50c-43cd-826f-8e6b59269ec7)

---

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/fb6dd0d4-7c0b-4bd4-ac85-e3cd9755d8d3)

---

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3637e70d-1bcc-4a98-ad85-73651abe21bd)
