### ISSUE TITLE
carnival theme: chapter outline treatment

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1076]
![Screen Shot 2019-05-20 at 3 52 15 PM](https://user-images.githubusercontent.com/11299125/58051242-45619c80-7b17-11e9-94c0-ac949dec1971.png)

This is a floating box on the side and should align to the first paragraph in the introduction.
Color should match splash box color (per book)
1.5em padding, 0.125in bleed to the right, sits within a 2in margin
Approx a 15.6rem width 

Font: IBM Plex Sans Medium
Size: Base font size (approx 9pt)

[Source PDF](https://drive.google.com/file/d/1jSPXqXNsVIEht8F0BtJzDZPi-vR-M_jB/view)

**Comment by openstaxalina** [comment]
@brittany-johnson could you put points on this when you get a chance?

**Comment by brittany-johnson** [comment]
Can't get the text inside of the chapter outline to change, need to fix that later

![Screen Shot 2019-08-08 at 10 23 19 AM](https://user-images.githubusercontent.com/24909007/62716883-7e980300-b9c8-11e9-91e6-44cb2510ee5b.png)

**Comment by Stackblocks** [comment]
Showing up in the PDF, but getting cut off on the right side. Spacing needs to be adjusted. (Possibly related to V/H alignment updates.)

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/59a3d4fe-30ff-4576-ba4d-e272cea5a9f4)

**Comment by Stackblocks** [comment]
SOMEbody forgot to put the Font and Size specs, but it got resolved. Pushing back to backlog for rework.

**Comment by lwtchu** [comment]
@Stackblocks idk what u are talkinga bout cause i edited the main content of the issue and it LOOKS like it's been there all along :joy:

**Comment by brittany-johnson** [comment]
Updated font and font size

<img width="566" alt="Screen Shot 2019-08-13 at 11 47 50 AM" src="https://user-images.githubusercontent.com/24909007/62960410-34e05b80-bdc0-11e9-8346-25cdf71a0d68.png">

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4e6d0427-331b-494e-9573-0ef5449fa84a)

**Comment by kswanson33** [comment]
![image](https://user-images.githubusercontent.com/26280712/125141654-a5df3980-e0e3-11eb-8702-c53fb3471068.png)
Specs added for version 2:
- no margin/padding between objective items
- `margin-bottom: 0.5rem` for "Chapter Outline" title
- `padding-bottom: 0.5rem` to pad the lower border line
