### ISSUE TITLE
carnival theme: learning objectives

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1077]
![Screen Shot 2019-05-20 at 3 58 23 PM](https://user-images.githubusercontent.com/11299125/58051567-26173f00-7b18-11e9-872c-e1c7470939cd.png)

"By the end of this section, you will be able to" styling
IBM Plex Sans Medium, italicized (color is book specific)
List font: Muli, regular, base font size
Bullets match the book specific color

**Comment by openstaxalina** [comment]
The attached PR modifies the new `styles` files.  It only creates files inside of the `styles` folder.  No product that we are using at this time uses those files.  

Therefore, we will include this in today's (June 21) code freeze.

**Comment by openstaxalina** [comment]
Devs and Alan need to meet next to go over the test procedure.

**Comment by brittweinstein** [comment]
@Stackblocks based on the meta info above, I'm thinking this is ready to be retested? Please let me know if that is not the case.

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a8561575-fbbf-4adc-a440-d5bea24f1809)

**Comment by Stackblocks** [comment]
Closing this issue and spinning off an issue for the font fix.

**Comment by helenemccarron** [comment]
Updated the font size to be  font-scale(1) for the learning objective titles and list items (originally set to values bigger than base font size but not in the scale)

**Comment by Stackblocks** [comment]
Something broke this since the closing of the issue. Re-opening for fix.

## State as of 2019-08-15 T 12:00-06
![image](https://user-images.githubusercontent.com/12678235/63111865-4f4b3e00-bf54-11e9-8d98-a1394e5b70d5.png)

**Comment by Stackblocks** [comment]
Fonts were being imported incorrectly and the styling was spilling over into the list text. Resolved.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4eac75ba-dd1a-47da-a097-5dd30b43c46f)
