### ISSUE TITLE
carnival theme: introduction module title

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1078]
![Screen Shot 2019-05-20 at 3 52 15 PM](https://user-images.githubusercontent.com/11299125/58053548-7c3ab100-7b1d-11e9-9860-015b04308995.png)

HELLO ALAN. When you are testing this, this is for the word INTRODUCTION that is the title of the first module in the chapter.

Bold, Alegreya 1.44rem all caps (see the first introduction word in the paragraph in the screenshot)

Note:  If it's a complete nightmare to deviate styling for one module title, please let me know.

**Comment by brittany-johnson** [comment]
![Screen Shot 2019-08-08 at 10 23 19 AM](https://user-images.githubusercontent.com/24909007/62715852-df264080-b9c6-11e9-94e1-424362348927.png)

**Comment by Stackblocks** [comment]
Font is IBM Plex Sans instead of Alegreya

![2019-08-12_12-44-46.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/37d8dc1a-1424-4135-bf6b-c01651218a45)
