### ISSUE TITLE
carnival theme: examples

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1079]
![Screen Shot 2019-05-20 at 4 41 51 PM](https://user-images.githubusercontent.com/11299125/58053793-303c3c00-7b1e-11e9-957d-772643086961.png)

Color: #C31427 
Example #.# text: Muli Black, All caps, 1.44rem
Title:  IBM Plex Sans bold, 1.44em (Sometimes they won't have a title)
Title for Problem, Solution, Analysis/etc text: IBM Plex Sans, caps, bold, 1.44rem
Icon: Bottom of icon sits 3px (0.3rem) below the bottom stroke
Stroke: .2rem (1.5pt = 2px = 0.2 rem?)

Icon: https://drive.google.com/open?id=16IZ-M4-fsrDr4iPwHCEm1AEPrdQIsjd9 
Icon size: 3.5rem H&W

**Comment by Stackblocks** [comment]
Displaying in the xhtml as of 2019-07-15, need to resolve with the team if this completes the definition of done or if they need to make it into the PDF in this step as well.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7de52ca5-be33-4ddb-bb29-c478d278de41)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7642e75e-8624-4a3e-aa4e-ef2521061198)
