### ISSUE TITLE
carnival theme: top-titled tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1080]
![Screen Shot 2019-06-26 at 4 00 11 PM](https://user-images.githubusercontent.com/11299125/60214649-81310580-982b-11e9-9e5b-bb086ab6de9d.png)

PDF output available in the carnival theme assets folder: https://drive.google.com/drive/folders/1zA3DPstc7Cx1BqtdMYCEB_NGXn1D0XXw

For the number and captions, we can move to below the table.
SOME books have titles on the top and some have titles on the bottom. 
Please use this design for `top-titled` classes. 

Lightweight lines for in between cells (horizontal and vertical): 0.025rem (0.25px)
Header row line weight: 0.1rem top and bottom
Header row font: muli bold
Color for header row font: can we match the header fonts that are book specific? (in screenshot it's #1E9475)
Header column line weight: 0.1rem left and right
Header column font: muli bold
Footer rows: 0.1rem at the top
Caption font: Same as base font
Table body font: alegreya base font size
Header body font: Muli (bold) base font size

Class: `top-titled`

**Comment by lwtchu** [comment]
Investigating some stuff first: #1174

**Comment by brittany-johnson** [comment]
<img width="747" alt="Screen Shot 2019-08-13 at 10 17 43 AM" src="https://user-images.githubusercontent.com/24909007/62953724-a665dd00-bdb3-11e9-868c-e3550310dc85.png">

**Comment by brittany-johnson** [comment]
Table with no class: 
<img width="738" alt="Screen Shot 2019-08-13 at 10 20 45 AM" src="https://user-images.githubusercontent.com/24909007/62953963-212ef800-bdb4-11e9-93eb-548d06f2588d.png">

Table with class `.unnumbered .medium`
<img width="799" alt="Screen Shot 2019-08-13 at 10 20 01 AM" src="https://user-images.githubusercontent.com/24909007/62953988-3572f500-bdb4-11e9-87ad-48ae085316c3.png">

**Comment by brittany-johnson** [comment]
Connected to PR https://github.com/openstax/cnx-recipes/pull/1288

**Comment by Stackblocks** [comment]
Mostly looking good with the exception of 2.14 which @brittany-johnson is investigating.

# Good
![2019-08-14_15-16-32.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ce045a48-2ba4-4c66-8814-301bba8a52a2)

![2019-08-14_15-16-20.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e1daf494-04d5-41c3-b792-b18c96a5561b)
# Bad
## PDF
![2019-08-14_15-12-50.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d04b20e5-0dc0-4ce4-9552-f046dcb030eb)
## Markup
![2019-08-14_15-18-35.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/33a076d5-a514-42b5-84b9-6a89dcd1b3c5)

**Comment by brittany-johnson** [comment]
![Screen Shot 2019-08-15 at 3 01 14 PM](https://user-images.githubusercontent.com/24909007/63123153-fc7e8000-bf6d-11e9-9d07-3786679fd614.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d878bd83-0497-49ba-a933-484f647c5bc1)

**Comment by ajluk** [comment]
@lwtchu I was reviewing Kendra's PR fixing figure/tables in carnival and have one question: should the tables have bottom stroke in this theme as well? I'm asking because there was a problem in the past with these borders in carnival and because of if it we removed them completely there. But Natalia fix it in cosmos theme. I saw your comment here and wasn't sure what was the conclusion: 
![image](https://user-images.githubusercontent.com/55203598/125303627-39f01180-e32d-11eb-9410-ae59d2fc5e46.png)

**Comment by lwtchu** [comment]
@ajluk oh i didn't know it was fixed. i think we should have it! do you think it's doable

**Comment by ajluk** [comment]
@lwtchu Thank you! Yes, I think so. But should the stroke be added just for anthropology for now? Kendra is working on tables for that book and I'm doing the review but I'm not sure if want to make such wide change within her PR. The colors for the bottom strokes are book specific and should be set for each book separately in the `book.scss` files. We need to also grab all the book specific colors for every book to do this. Do you think a better idea could be to do that within a separate issue and PR. It will also demand a lot of testing.  Let me know what are your thoughts :)

**Comment by kswanson33** [comment]
@ajluk Thanks so much for pointing out the cosmos fix. Confirmed with @lwtchu that the change should be theme-wide (I think a lot of these recent anthropology changes have ended up impacting the rest of the theme, so testing load is already ... high-ish 🙃).
