### ISSUE TITLE
carnival theme: link to learning design

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1082]
<img width="367" alt="Screen Shot 2019-05-20 at 8 06 54 PM" src="https://user-images.githubusercontent.com/11299125/58061204-d5650d80-7b3a-11e9-8950-59b44994c644.png">
<img width="557" alt="Screen Shot 2019-05-20 at 8 18 28 PM" src="https://user-images.githubusercontent.com/11299125/58061603-74d6d000-7b3c-11e9-92bf-54a1304a7a8a.png">

'
Class: `link-to-learning`
Green color: #78B042 
Stroke: 0.2rem 
Padding: 1.5rem between line and feature text
Text: left align to margin and NOT at the icon (see check your understanding feature)
Feature title: Muli Black, 1.44rem, all caps, breaks into two lines (if possible)
Icon: https://drive.google.com/open?id=1jm3US-spU6F3BwURhHDY5Emxpe5vmyOr
Icon size: 25px H & W (2.5rem)

Please try to stack link to learning title like the check your understanding icon with the text like the following:

LINK TO 
LEARNING

If LINK TO LEARNING text cannot be stacked, it is perfectly okay if they are in line.

**Comment by lwtchu** [comment]
Based on what Chris showed me June 27: Try reducing line height. And reduce font size to 1rem.

**Comment by Stackblocks** [comment]
Displaying in the xhtml as of 2019-07-15, need to resolve with the team if this completes the definition of done or if they need to make it into the PDF in this step as well.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/db719d9b-d9c6-4d28-bce3-8e28318b0f5b)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code. Image sizes to be addressed in a later fix.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a62a3593-c706-40ac-b96e-c986b801bfb5)
