### ISSUE TITLE
library wide: unnumbered unstyled tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1084]
any unnumbered and unstyled tables `class="unnumbered unstyled"` should have NO LINES and just the base font style. 1 rem padding all around inside the cell

should not have any caption/figure number styling as there should be no caption/figure number

NOTE TO TESTERS & CONTENT TEAM: if there is a table that has this class, but should be styled a different way, it needs to be assigned a new class (currently not an issue in Chemistry & A&P)

**Comment by MartaSztuka** [comment]
Unnumbered, unstyled tables in Microbiology looks as in description.
![Screenshot from 2019-09-02 16-30-11](https://user-images.githubusercontent.com/47241114/64121623-af890f00-cd9f-11e9-85aa-543a761c4a23.png)
![Screenshot from 2019-09-02 16-33-07](https://user-images.githubusercontent.com/47241114/64121632-b57ef000-cd9f-11e9-89a0-f3d371b17dda.png)
