### ISSUE TITLE
chemistry: color palette & general notes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1086]
![image](https://user-images.githubusercontent.com/11299125/58062624-95088e00-7b40-11e9-90a0-ed5d619abb24.png)

Chapter title, chapter number, H1, H2, H3, etc: #00829B
Splash image bar, chapter outline, box color: #00829B
Learning objectives text color: #00829B

End of Chapter Sections
- Contains Key terms (uses `<glossary>`), key equations (`key-equations`), chapter review (`summary`), exercises (`exercises`)
*Need to do content change for key equations
Exercises: Separated by module, continuous numbering, might contain images or lists or tables, resets after each chapter

End of Book
Appendices
Answer Key: Broken up by chapter (could possibly do by module), one column
Index

**Comment by openstaxalina** [comment]
@wilkus27 had some questions about this; I think we should wait to confirm those / close this until @lwtchu is back: https://openstax.slack.com/archives/CBW9DFKGF/p1568643427004300

**Comment by openstaxalina** [comment]
questions were addressed via Slack; closing this issue
