### ISSUE TITLE
chemistry: chemistry in everyday life (boxed features specs in here)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1087]
<img width="446" alt="Screen Shot 2019-05-20 at 8 53 47 PM" src="https://user-images.githubusercontent.com/11299125/58062797-6343f700-7b41-11e9-9322-43e645ea1573.png">

CLASS: `class="chemistry everyday-life"`

Boxed feature style:
Stroke: 0.2rem (1.5pt = 2px = 0.2 rem?) 
Padding inside: 1em 
CHANGE FROM ABOVE DESIGN: Entire feature title `Chemistry in Everyday Life`: muli bold, all caps, color #00829B, 1.44em
~Rest of the title: muli; 1.44em~
Styling/treatment for word: CHEMISTRY
Dotted stroke: 0.1rem under feature title, color goes with the stroke color 
Specific title: IBM Plex Sans, bold, 2.074rem

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code. Font issues to be resolved on a separate tracker.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e5dfe990-cf24-4f7e-a74f-61f7c5023ce2)

**Comment by openstaxalina** [comment]
baked styles testing -- woohoo!! 🎉
