### ISSUE TITLE
chemistry: how sciences interconnect (icon feature specs in here)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1088]
<img width="383" alt="Screen Shot 2019-05-20 at 9 02 02 PM" src="https://user-images.githubusercontent.com/11299125/58063122-891dcb80-7b42-11e9-8e3b-4e003d63f5d7.png">
<img width="419" alt="Screen Shot 2019-05-20 at 9 06 10 PM" src="https://user-images.githubusercontent.com/11299125/58063291-1d882e00-7b43-11e9-994b-d33780247332.png">

Class: `class="chemistry sciences-interconnect"`
Stroke of line is 0.2rem (1.5pt=0.2rem?); top and bottom ( see second screenshot)
Color of line and icon: #F37541 
Bottom of the icon sits 3px=0.3rem below the middle of the bottom stroke
Feature title: Muli Black, 1.44rem, all caps, breaks into two lines (if possible)
Icon size: 3.5rem H&W
Icon: https://drive.google.com/open?id=1vHfVTuvWhcO8mBCERaYm3w7lp_LZnY3A
^^ icon is different based on feedback

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6c18b0db-c519-4f79-b338-c2208fb416f0)

**Comment by helenemccarron** [comment]
Per Larissa, the label for figures in icon notes should be following the default for features in the book (whatever color it is outside of notes)
