### ISSUE TITLE
chemistry: portrait of a chemist

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1089]
Similar to #1087 except the word "PORTRAIT" gets the color treatment

Class: `class="chemistry chemist-portrait"`
Color: #78B042

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/afa46c1d-c698-456d-ba2b-f2b5dba986f7)
