### ISSUE TITLE
chemistry: note nested in examples

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1090]
Note with the title: Answer. It's in a note currently to right align it in the PDF. I checked with Anthony and he said there wasn't a real urgent need for it to be right aligned. 

In my opinion, we should style it like the rest of the example and have it be left aligned. See #1079 for Example specs

Is there a non-painful way to style this like the rest of the note. We can also opt to do a content fix if there is not a non-painful way to style this.

SAMPLE CNXML

```<example>
  <title>Title of Example</title>
  <para>Example text.</para>
  <para>
    <title>Solution</title>
    Solution text.
  </para>
  <para>
    <title>Check Your Learning</title>
    Check your learning text.
  </para>
  <note>
    <title>Answer</title><label/>
    <para>answer text</para>
  </note>
</example>```

**Comment by brittweinstein** [comment]
@lwtchu we will do a styling fix here--no content fix needed.

**Comment by Stackblocks** [comment]
Appears to be displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/817439a9-ab59-4f98-956e-1603eda659f0)
