### ISSUE TITLE
anatomy & physiology: boxed features

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1092]
See #1087 for styling specifications

Title: Diseases of the... 
Treatment: Diseases
Class: `anatomy diseases`
Color: #00819A

Title: Disorders of the...
Treatment: Disorders
Class: `anatomy disorders`
Color: #B10069

Title: Aging and the...
Treatment: Aging
Class: `anatomy aging`
Color: #B05E36

Title: Everyday Connection
Treatment: Everyday
Class: `anatomy everyday`
Color: #00819A

**Comment by clee1060** [comment]
<img width="794" alt="Screen Shot 2019-07-25 at 11 01 06 AM" src="https://user-images.githubusercontent.com/16073667/61889758-a452e180-aecb-11e9-9261-2847a17b7c6a.png">
<img width="797" alt="Screen Shot 2019-07-25 at 11 01 33 AM" src="https://user-images.githubusercontent.com/16073667/61889759-a452e180-aecb-11e9-9583-dffe675dd507.png">
<img width="804" alt="Screen Shot 2019-07-25 at 11 01 42 AM" src="https://user-images.githubusercontent.com/16073667/61889760-a452e180-aecb-11e9-8372-b6dd55d2fd97.png">
<img width="799" alt="Screen Shot 2019-07-25 at 11 01 56 AM" src="https://user-images.githubusercontent.com/16073667/61889761-a452e180-aecb-11e9-8ad2-34c49855c260.png">

**Comment by Stackblocks** [comment]
Coloration of the box and title displaying correctly, but getting some intermittent breakages in the stroke on the bottom left/right of the boxed content and a couple of instances of bad page breaks in the boxed content. These can be be broken out into separate issues if needs be.

# Diseases of the...
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ed39de23-2533-4f99-828f-ea1277168838)

# Disorders of the...
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c537e478-91e0-4926-a11e-ff9cdebde34b)

# Aging and...
## Closeup
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8400ad92-071d-4097-9903-ed160321fe00)

## Broken Box Example
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b1ea395f-ed7e-428c-b7d1-9981ffd90ef4)

## Solid Box Example
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/613dd4cb-529e-42ed-adce-4d7fde56f925)


# Everyday Connection
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/75dac474-fbd2-4317-af82-95db1f8b6839)

**Comment by Stackblocks** [comment]
Additionally this may be an issue with generating the PDF via the `prince` command instead of the docker `build-pdf` command, which becomes a "definition of done" conversation.

**Comment by Stackblocks** [comment]
Thomas ID'ed the issue with the odd gaps, it's a Prince 11.4 vs Prince 12 backcompat issue. 🎉
