### ISSUE TITLE
anatomy & physiology: iconned feature 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1093]
See #1088 for specifications

Title: Career Connection
Class: `anatomy career`
Color: #B05E36
Icon: https://drive.google.com/open?id=1wyg5JjWNYEwJ3WuwXV6Xqfymkj4aluXV

Title: Homeostatic Imbalances
Class: `anatomy homeostatic`
Color: #F37541 
Icon: https://drive.google.com/open?id=1QcGT9PL74lxrlBQrbPvjCfxIpgHxPbl_

**Comment by clee1060** [comment]
<img width="809" alt="Screen Shot 2019-07-25 at 10 30 18 AM" src="https://user-images.githubusercontent.com/16073667/61887453-42907880-aec7-11e9-959d-a4dfbf71873b.png">
<img width="795" alt="Screen Shot 2019-07-25 at 10 30 36 AM" src="https://user-images.githubusercontent.com/16073667/61887455-42907880-aec7-11e9-86e4-a97a93d5dc19.png">

**Comment by Stackblocks** [comment]
Encountered some issues with the iconned features in Anatomy & Physiology. As before, this may be a symptom of the developing PDF generation pipeline and can be verified by a third party.

# Career Connection
- Icon floating above top stroke (bottom of the icon should sit 3px=0.3rem below the middle of the stroke)
![2019-07-25_18-49-30.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1a4b7006-6844-4e85-a03a-9c131c77f824)

# Homeostatic Imbalance
- Missing upper stroke

![2019-07-25_18-54-09.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/62d59c5e-d1a4-459b-86ab-5f8311d482e3)

**Comment by helenemccarron** [comment]
Solved by https://github.com/openstax/cnx-recipes/pull/1356

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0c06bab4-71a3-41a8-aabc-cc6c9ab60dab)

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c1de5b55-a023-4286-bc04-d8ef025372e7)

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f2476a3c-e86c-4168-a64d-195b54b4d30f)
