### ISSUE TITLE
Calculus vol 1 Index Subscripts not rendering

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1098]
# What happened?

A term with subscripts appears in the index of webview without the subscript formatting.

# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: just the index

# Environment:

- **Book(s)**: Calculus vol 1 
- **URL/Server**: https://staging.cnx.org/contents/i4nRcikn@9.1:Cr9RgAOV@9.1/Index
- **Location (page number, chapter/section)**: Index
- **Suggested nearby searchable text**: fave
- **Browser**: Firefox

# Screenshots

<img width="1214" alt="Screen Shot 2019-05-28 at 3 23 49 PM" src="https://user-images.githubusercontent.com/1895432/58509698-c8f53c00-815c-11e9-8a86-0020a6d5f9ea.png">

**Comment by theresamasciale** [comment]
Note: this also occurs in Calculus Vol. 2 

https://staging.cnx.org/contents/HTmjSAcf@5.1:ok1-6ouj@5.1/Index

**Comment by brittweinstein** [comment]
@wilkus27  the Books team discussed this morning and realized that the scope of regression testing here is too large to get done while we have the Precalc regression testing going on. Therefore, we will move this back to the backlog.

**Comment by brittweinstein** [comment]
Let's come back to this after work on the Corn theme to see if this is resolved.
