### ISSUE TITLE
Calculus vol 1 italics do not render in Index

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1099]
# What happened?

Terms with enclosing italics formatting are not italic in the collated webview Index.

# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: Index

# Environment:

- **Book(s)**: Calculus volume 1
- **URL/Server**: https://staging.cnx.org/contents/i4nRcikn@9.1:Cr9RgAOV@9.1/Index
- **Location (page number, chapter/section)**: index
- **Suggested nearby searchable text**: aphelion
- **Browser**: Firefox

# Screenshots
<img width="553" alt="Screen Shot 2019-05-28 at 3 55 23 PM" src="https://user-images.githubusercontent.com/1895432/58511737-065bc880-8161-11e9-9f0f-2910c0b4ae81.png">

**Comment by openstaxalina** [comment]
This appears to be an issue anytime italics are used in the Index, in any baked book.
