### ISSUE TITLE
Calculus vol 1 Index math rendering improperly in webview

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1100]
# What happened?

Instead of one math-font letter, the Index has a duplicating plaintext letter in Calculus Vol 1.

# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: index

# Environment:

- **Book(s)**: Calculus, Precal 
- **URL/Server**: https://staging.cnx.org/contents/i4nRcikn@9.1:Cr9RgAOV@9.1/Index
- **Location (page number, chapter/section)**: index
- **Suggested nearby searchable text**: decreasing on the interval
- **Browser**: Firefox

# Screenshots
<img width="708" alt="Screen Shot 2019-05-28 at 3 58 59 PM" src="https://user-images.githubusercontent.com/1895432/58511958-884bf180-8161-11e9-8aaf-d9202d5ad283.png">
<img width="735" alt="Screen Shot 2019-05-28 at 3 58 41 PM" src="https://user-images.githubusercontent.com/1895432/58511959-884bf180-8161-11e9-97ee-df63a2bae13d.png">

**Comment by openstaxalina** [comment]
This might be occurring because the term is marked up as text **and** MathML:
![Screen Shot 2019-05-31 at 12 44 52 PM](https://user-images.githubusercontent.com/7863733/58724344-eebf5280-83a1-11e9-9c44-48742a343285.png)

@oscryan what would you think of making "e" italics instead of MathML?

**Comment by brittweinstein** [comment]
Let's come back to this after work on the Corn theme to see if this is resolved.

**Comment by brittweinstein** [comment]
This appears to have been resolved.
