### ISSUE TITLE
Superscript on two different levels under the square root symbol.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1101]
# What happened?

Power number is styled in two different ways.

# Reproducibility Details

- **Does it also happen in an incognito window?**: Yes
- **Does this happen in one place, a few places, or everywhere?**: Table of Integrals
- **Book(s)**: Calculus vol 3
![styl](https://user-images.githubusercontent.com/47241114/58568695-01684900-8235-11e9-9feb-9b7edc628944.jpeg)

- **URL/Server**: https://staging.cnx.org/contents/oxzXkyFi@5.1:ETQP7eZj@10/A-Table-of-Integrals
- **Location (page number, chapter/section)**: Table of integrals
- **Suggested nearby searchable text**: Integrals Involving a2 + u2, a > 0
- **Browser**: Chrome

# Screenshots

(_attach here (please clearly label what environment each screenshot came from)_)

**Comment by paulinaszczucinska** [comment]
@MartaSztuka please provide us with PDF screenshot. Paste it next to the webview picture.

**Comment by openstaxalina** [comment]
I'm not sure this can be resolved, or it may be a bug in MathJax.  I suggest closing this but would like to get the team's thoughts first.
