### ISSUE TITLE
Q&A College Algebra feature says QA instead

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1103]
# What happened?

The recipe header for the Q&A feature just says QA in baked webview.

# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: everywhere

# Environment:

- **Book(s)**: College Algebra
- **URL/Server**: https://staging.cnx.org/contents/mwjClAV_@12.1:GDS8ZHCU@15/1-3-Radicals-and-Rational-Exponents
- **Location (page number, chapter/section)**:Q&Aa
- **Suggested nearby searchable text**: QA
- **Browser**: Firefox

# Screenshots

<img width="1104" alt="Screen Shot 2019-05-30 at 10 34 12 AM" src="https://user-images.githubusercontent.com/1895432/58644364-b434b780-82c6-11e9-9e52-bc5c12714e86.png">

**Comment by MartaSztuka** [comment]
In Algebra&Trigonometry same issue occurs, I'll add label.
![q a](https://user-images.githubusercontent.com/47241114/58796353-5b825900-85fd-11e9-9739-74a9c76dfa24.jpeg)

**Comment by MartaSztuka** [comment]
Tested on katalyst01.
![Screenshot from 2019-06-12 12-45-49](https://user-images.githubusercontent.com/47241114/59345287-17373d00-8d10-11e9-9449-9c0579d2c1b5.png)
![Screenshot from 2019-06-12 12-47-07](https://user-images.githubusercontent.com/47241114/59345366-3afa8300-8d10-11e9-9a62-edbdf5457a0c.png)
![Screenshot from 2019-06-12 12-47-59](https://user-images.githubusercontent.com/47241114/59345418-56fe2480-8d10-11e9-97b1-6738109e8c3f.png)
