### ISSUE TITLE
Precal trio footnotes restart by module in webview

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1105]
# What happened?

Footnote numbering does not match the pdf because it restarts at every module.

# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: every footnote

# Environment:

- **Book(s)**: College Algebra
- **URL/Server**: https://staging.cnx.org/contents/mwjClAV_@12.1:dGtL5139@12/6-3-Logarithmic-Functions for example
- **Location (page number, chapter/section)**: footnotes
- **Suggested nearby searchable text**: earthquake.usgs
- **Browser**: Firefox

# Screenshots
<img width="1116" alt="Screen Shot 2019-05-30 at 11 25 22 AM" src="https://user-images.githubusercontent.com/1895432/58647732-cbc36e80-82cd-11e9-9ff6-d007ed820ea2.png">
<img width="1108" alt="Screen Shot 2019-05-30 at 11 25 12 AM" src="https://user-images.githubusercontent.com/1895432/58647733-cbc36e80-82cd-11e9-870c-d27f94a4233d.png">

**Comment by rosemaryyang** [comment]
On PDF version: 
Preface has a footnote that is in Roman numerals. 
![image](https://user-images.githubusercontent.com/50595077/58821596-09d8cf00-85fb-11e9-8fc7-569d033b31bd.png)

Footnote numbering does not restart with every chapter.
![image](https://user-images.githubusercontent.com/50595077/58822536-61783a00-85fd-11e9-8642-4b166b23e05d.png)

**Comment by openstaxalina** [comment]
@rosemaryyang thank you!  So footnote numbering is continuous throughout the entire book (after the preface)?  Could you confirm it never restarts?

**Comment by rosemaryyang** [comment]
Yes, the numbering never restarts.

**Comment by wilkus27** [comment]
@openstaxalina doing the investigation I noticed some differences between precal trio. 

In **Algebra and Trigonometry** on webview exist footnote like in PDF and I can change the numbering for that in recipe.

webview

![image](https://user-images.githubusercontent.com/40228854/59275126-04fbc700-8c5c-11e9-82e5-5bfe2add7ee3.png)

![image](https://user-images.githubusercontent.com/40228854/59275161-11801f80-8c5c-11e9-86b0-6b484322ef31.png)

PDF

![image](https://user-images.githubusercontent.com/40228854/59275731-33c66d00-8c5d-11e9-907c-026a08d445a4.png)

![image](https://user-images.githubusercontent.com/40228854/59275767-42148900-8c5d-11e9-8ed6-7485d2d83705.png)


But in **Precalculus** and **College Algebra** footnotes in Preface don't exist on webview. 

**Precalculus**:

webview

![image](https://user-images.githubusercontent.com/40228854/59275416-91a68500-8c5c-11e9-87a9-3fc17e7fb000.png)

PDF

![image](https://user-images.githubusercontent.com/40228854/59275518-bb5fac00-8c5c-11e9-82e4-841556d1a5a6.png)

**College Algebra**:

webview

![image](https://user-images.githubusercontent.com/40228854/59275557-d3373000-8c5c-11e9-8273-afbb1d771677.png)

PDF

![image](https://user-images.githubusercontent.com/40228854/59275612-ef3ad180-8c5c-11e9-8122-bfb68788ae66.png)

This is probably content issue.

**Comment by openstaxalina** [comment]
@wilkus27 thanks so much for the investigation!  I've copied this issue into the content-managers repo, specifically for the footnote fix in _Precalculus_ and _College Algebra_ **prefaces**: https://github.com/openstax/content-managers/issues/881

**Comment by helenemccarron** [comment]
@wilkus27 Thomas' PR https://github.com/openstax/cnx-recipes/pull/1138 should solve your Travis issue.

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code. Footnotes are now continuous throughout the book.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/9e1e63d8-82a4-4636-9ab9-6cad45f6feac)

**Comment by openstaxalina** [comment]
The expected behavior is that footnotes are in arabic numerals, continuous throughout the book in both the PDF and webview (if baked on staging after Monday 6/24).
Also, the prefaces in all three titles should have a footnote that is in roman numerals.
