### ISSUE TITLE
Note titles are forcing allcaps in College Algebra

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1106]
# What happened?

The whole titles of notes in College Algebra are being capitalized, including variables which must be lowercase,
THUS COMPROMISING PEDAGOGY
*pushes glasses up nose* -@lwtchu
# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: everywhere

# Environment:

- **Book(s)**: College Algebra
- **URL/Server**: https://staging.cnx.org/contents/mwjClAV_@12.1:_tqWoaDz@19/6-7-Exponential-and-Logarithmic-Models
- **Location (page number, chapter/section)**: notes
- **Suggested nearby searchable text**: characteristics
- **Browser**: Firefox

# Screenshots

<img width="1005" alt="Screen Shot 2019-05-30 at 12 54 23 PM" src="https://user-images.githubusercontent.com/1895432/58653202-cddffa00-82da-11e9-8941-4e1c3a34fde5.png">

**Comment by wilkus27** [comment]
Could be resolved on webview. Move to this repo.

**Comment by wilkus27** [comment]
Issue moved to [openstax/webview #2256](https://github.com/openstax/webview/issues/2256) via [**ZenHub**](https://www.zenhub.com/)
