### ISSUE TITLE
Supporting Features styling in Preface.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1107]
# What happened? 

Icons of 'Try it', 'Q&A' etc. are different than PDF, also different than in Chapters.

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: Preface > Pedagogical Foundations and Features > Supporting Features

# Environment: 
- **Book(s)**: Algebra and Trigonometry
- **URL/Server**: https://staging.cnx.org/contents/mwjClAV_@12.1:iKCx0cHP@7/Preface
- **Location (page number, chapter/section)**: Preface
- **Browser**: Chrome

# Screenshots
![stag](https://user-images.githubusercontent.com/47241114/58713965-03acdd80-83c4-11e9-8c4a-96371114d56c.jpeg)

(_attach here (please clearly label what environment each screenshot came from)_)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment]
We should remove the images from the content, as they were not used in the XYZ PDFs and will not be used in baked styles.  Moving to content manager repo.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #864](https://github.com/openstax/content-managers/issues/864) via [**ZenHub**](https://www.zenhub.com/)
