### ISSUE TITLE
Online Homework is missing

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1108]
# What happened?
In Additional Resources 'Online Homework' paragraph is gone.

# Reproducibility Details:
Preface > Additional Resources > 3th paragraph

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: only in Preface

# Environment:

- **Book(s)**: Algebra and Trigonometry
- **URL/Server**: https://staging.cnx.org/contents/E6wQevFf@15.1:qlu7EQLj@6/Preface
- **Location (page number, chapter/section)**:
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots
![al tri](https://user-images.githubusercontent.com/47241114/58715424-1bd22c00-83c7-11e9-91db-9e848dc33563.jpeg)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment]
This is acceptable as-is.  We do not want to list specific homework partners in the Preface, as this list would need to be constantly maintained.

We can leave both the PDF and the web as-is.
