### ISSUE TITLE
About Our Team vs About the Authors

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1109]
# What happened?

In PDF the list of contributing Authors is right after title page, with 'About Our Team' headline.
In webview same list is as the last one paragraph of Preface, after Additional Resources with 'About the Authors' headline. 

# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: only there

# Environment:

- **Book(s)**: Algebra and Trigonometry
- **URL/Server**: https://staging.cnx.org/contents/E6wQevFf@15.1:qlu7EQLj@6/Preface
- **Location (page number, chapter/section)**: Preface (2 last paragraphs)
- **Suggested nearby searchable text**: About Our Team
- **Browser**: Chrome

# Screenshots
![team](https://user-images.githubusercontent.com/47241114/58716564-98fea080-83c9-11e9-9255-69e312d98e96.jpeg)

(_attach here (please clearly label what environment each screenshot came from)_)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment]
No change - we can leave both the PDF and webview as-is.

The webview follows the most recent OpenStax Preface boilerplate.  (The PDF does not follow the boilerplate, but that is acceptable as we are not updating the PDF at this time.)
