### ISSUE TITLE
Gulp Exploration and Training

### ISSUE THREAD

**Issue by tomjw64** [openstax/cnx-recipes#1110]
# Looking For
Incremental build/task handling
Parallel builds
Ability to cleanly make shell calls AND read the output of those calls
Ability to create custom tasks
Ability to pass arguments to cli commands

# Training Tasks
Hopefully completing all these tasks will confirm all the above desired capability is feasible
## CLI Echo (CLI arguments, run shell cmd)
Command: `gulp echo -m "message"`
This should echo out the message after -m
Output: `I got: 'message'`

## Cat File (Using streams)
Command: `gulp cat`
This should output the contents of a `cat.txt` in the project directory
Output: Whatever is in your `cat.txt` file

## Concurrent Delay (Parallel builds)
Command: `gulp delay`
This should start 10 separate tasks that sleep for 1s
Output: `Finished 'delay' after x`, where x is < 10s

## Print and Replace PWD (read output of shell cmd)
Command: `gulp pwd`
This will echo out the pwd but replace all 'o' characters with '0' with a JS regex
Output: Something similar to `/h0me/th0mas/c0de/0penstax/sandb0x/gulp-test`

**Comment by brittweinstein** [comment]
(No code, here)
