### ISSUE TITLE
Coordinate System illustration is mismatched

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1112]
# What happened?
In Complex plane frame coordinate system (Figure 3) is different in webview and in PDF.

# Reproducibility Details
Chapter 2 > Section 2.4 > complex plane

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: one place

# Environment:

- **Book(s)**: Algebra and Trigonometry
- **URL/Server**: https://staging.cnx.org/contents/E6wQevFf@15.1:Sqk1HAGf@11/2-4-Complex-Numbers#Figure_02_04_004
- **Location (page number, chapter/section)**: 2.4 Complex Numbers
- **Suggested nearby searchable text**: Plotting a Complex Number on the Complex Plane
- **Browser**: Chrome

# Screenshots
![complex plane](https://user-images.githubusercontent.com/47241114/58795701-a307e580-85fb-11e9-81fe-d0ba873c57db.jpeg)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment]
Thank you, @MartaSztuka! We have a content issue open to locate these discrepancies and resolve them when necessary for pedagogy: https://github.com/openstax/content-managers/issues/823.

I am going to close this issue.
