### ISSUE TITLE
Numbers are where ABC should be.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1113]
# What happened?
In Example#, Solution 'abc' is replaced with 1., 2. etc. In question is still 'abc' though.

# Reproducibility Details
Section 2.4 > Example 3 > Solution

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: In every Example where question consist of a., b., c.  

# Environment:

- **Book(s)**: Algebra and Trigonometry
- **URL/Server**: https://staging.cnx.org/contents/E6wQevFf@15.1:Sqk1HAGf@11/2-4-Complex-Numbers#Figure_02_04_004
- **Location (page number, chapter/section)**: 
- **Suggested nearby searchable text**: Solution
- **Browser**: Chrome

# Screenshots
![abc](https://user-images.githubusercontent.com/47241114/58797260-d51b4680-85ff-11e9-8f7d-9ff2d9448ed7.jpeg)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment]
I think this may be content related:
![Screen Shot 2019-06-03 at 9 28 06 AM](https://user-images.githubusercontent.com/7863733/58809638-e9e8e180-85e1-11e9-9f2b-8239b6e0057f.png)

Will park this with the devs.

**Comment by openstaxalina** [comment]
Confirmed this is content driven.  Move to content-managers repo.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #870](https://github.com/openstax/content-managers/issues/870) via [**ZenHub**](https://www.zenhub.com/)
