### ISSUE TITLE
Missing Equation

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1114]
# What happened?
Equation in Chapter 2 Practice Test is missing.

# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: one place

# Environment:

- **Book(s)**: Algebra and Trigonometry
- **URL/Server**: https://staging.cnx.org/contents/E6wQevFf@15.1:xyY2OzMS@15.1/Practice-Test
- **Location (page number, chapter/section)**: Chapter 2 > Practice Test > see task no 2
- **Suggested nearby searchable text**: 
- **Browser**: Chrome

# Screenshots

![find](https://user-images.githubusercontent.com/47241114/58803728-71e5e000-8610-11e9-8cd0-e483b41ab1e4.jpeg)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment]
Thank you, @MartaSztuka - I am moving this to the content repo for resolution.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #865](https://github.com/openstax/content-managers/issues/865) via [**ZenHub**](https://www.zenhub.com/)
