### ISSUE TITLE
Appendix is mismatched

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1115]
# What happened?

1. Some elements of Appendix are missing and some were added.
2. Order of elements differs from PDF.
3. This effects tables and figures numbering.

# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: all over Appendix

# Environment:

- **Book(s)**: Algebra and Trigonometry
- **URL/Server**: https://staging.cnx.org/contents/E6wQevFf@15.1:lP3tJSPA@7/A-Proofs-Identities-and-Toolkit-Functions
- **Location (page number, chapter/section)**: End of the Book, A | Proofs, Identities, and Toolkit Functions
- **Suggested nearby searchable text**: 
- **Browser**: Chrome

# Screenshots

![eob](https://user-images.githubusercontent.com/47241114/58881438-7aa2e880-86da-11e9-94f0-f48a8531ba2c.jpeg)

![figu](https://user-images.githubusercontent.com/47241114/58882201-010bfa00-86dc-11e9-9c04-62472923474f.jpeg)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by brittweinstein** [comment]
@openstaxalina do we want to get this in this sprint since this is an XYZ title?

**Comment by openstaxalina** [comment]
This is most likely content driven.  The content managers and content development interns are gathering all numbering-related differences now.  I will move this to the content managers' milestone.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #868](https://github.com/openstax/content-managers/issues/868) via [**ZenHub**](https://www.zenhub.com/)
