### ISSUE TITLE
Index differences

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1117]
# What happened?

Index in webview starts differently than PDF's.

# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: one place

# Environment:

- **Book(s)**: Algebra and Trigonometry
- **URL/Server**: https://staging.cnx.org/contents/E6wQevFf@15.1:8EgMc1pO@15.1/Index
- **Location (page number, chapter/section)**: Index
- **Suggested nearby searchable text**: Symbols
- **Browser**: Chrome

# Screenshots

![aaas](https://user-images.githubusercontent.com/47241114/58886582-74196e80-86e4-11e9-8c63-81a7631f3aed.jpeg)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment]
Move to content-managers repo.
