### ISSUE TITLE
Summary expand arrow not rendering in FireFox

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#1121]
# Scenario
Expand arrow not rendering in FireFox for "Summary" at top of each section 

# Steps to Reproduce
On any normal module across the precal trio, use firefox to view the "Summary" at the top of the page. 
This persists on all 
* **How many times were you able to reproduce the issue?** 
All chapters on all three books

* **Images or Screenshots Included:** [ X] Yes  [ ] No  (_attach below_)
![Screen Shot 2019-06-06 at 1.11.00 PM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/a0ae7c27-8d03-4516-a91d-270375892132)

# Environment:

* **Medium**: [ ] REX [ ] PDF  [ X] cnx.org  
* **Instance**: [ X] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ X] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ X] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact

* **Severity**: [ ] High [ X] Medium  [ ] Low
* **Frequency of Occurrence**: [ X] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan 

# Acceptance Criteria

**Comment by brittweinstein** [comment]
@openstaxalina, I'm assigning to you for prio.

**Comment by openstaxalina** [comment]
This will be resolved when the Precal trio is released in Assignable Webview.  The recipe moves the summary into the content itself.  You can see an example under "Learning Objectives" here:
https://staging.cnx.org/contents/E6wQevFf@17.1:0KhpF2RH@28/1-1-Real-Numbers-Algebra-Essentials

(and you can confirm that it is the same content that was previously listed under the summary: https://cnx.org/contents/E6wQevFf@14.2:0KhpF2RH@29/Real-Numbers-Algebra-Essentials)
