### ISSUE TITLE
Complete an internationalization framework to support more than English and Polish languages

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1122]
In #1011 we started cleaning up mixins to remove any language specific logic within the mixins framework. https://github.com/openstax/cnx-recipes/issues/726 will implement the Polish recipe after that work is done. When those two are done, we should revisit the internationalization framework concepts and discuss the config file structure in order to support more than English and Polish languages.

**Comment by brittweinstein** [comment]
Closing -- This is represented elsewhere.
