### ISSUE TITLE
Add classes to the xhtml tags for better readability in styling: Table of Contents

### ISSUE THREAD

**Issue by clee1060** [openstax/cnx-recipes#1134]
# What happened?

Currently it's hard to only style certain parts of the Table of Contents (e.g. preface, appendix, eob), and I feel like the style code would be easier to write and easier to understand in hindsight if we added classes to these different parts. Thus, we could use selectors with names that make logical sense to select those tags.

# Reproducibility Details

We just have to add this to different "groupings" of tags in the html.

# Environment:

the xhtml files

# Additional notes

For the table of contents:
Appendix: toc-appendix
etc.

**Comment by openstaxalina** [comment]
connected with #1070

**Comment by clee1060** [comment]
Also, the "Check Your Understanding/Learning" sections are all inside of the "example" div. However, it's indistinguishable from the other tags inside example, making it pretty hard to style just those tags.

**Comment by openstaxalina** [comment]
@clee1060 does your comment above pertain to #1137 ?

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![2019-08-13_13-24-57.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f213d246-ab3e-4205-887c-baa7442dc5cd)
---
![2019-08-13_13-28-46.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/01d9569f-6bbf-4824-9a28-ebb022bb7fdb)
