### ISSUE TITLE
Add classes to the xhtml tags for better readability in styling: Examples

### ISSUE THREAD

**Issue by clee1060** [openstax/cnx-recipes#1137]
# What happened?

Currently it's hard to only style certain parts of the Examples (e.g. check your...), and I feel like the style code would be easier to write and easier to understand in hindsight if we added classes to these different parts. Thus, we could use selectors with names that make logical sense to select those tags. Also, the "Check Your Understanding/Learning" seems to always be inside of the container for the example, and I feel like it should have different selectors to style it differently.

# Reproducibility Details

We just have to add this to different "groupings" of tags in the html.

# Environment:

the xhtml files

**Comment by openstaxalina** [comment]
@lwtchu is confirming the current markup and also the design requirements.

**Comment by lwtchu** [comment]
<img width="872" alt="Screen Shot 2019-06-18 at 12 23 44 PM" src="https://user-images.githubusercontent.com/11299125/59705436-f7968d80-91c3-11e9-906c-58d352b0b9b1.png">
The 'Check Your Learning' in the notes are NOT intended to be styled like the Check Your Understanding in Lisa's designs. They should function like a regular header with the paragraph. I'm not sure why it's in a Note.

**Comment by brittweinstein** [comment]
Decision: This is not needed ATM, will reopen if needed.
