### ISSUE TITLE
carnival theme: answer key styling

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1151]
![Screen Shot 2019-05-20 at 2 48 26 PM](https://user-images.githubusercontent.com/11299125/58047697-5a85fd80-7b0e-11e9-96ca-0f72b7903c61.png)
![Screen Shot 2019-05-20 at 2 48 29 PM](https://user-images.githubusercontent.com/11299125/58047698-5a85fd80-7b0e-11e9-8a3a-c65d1177c787.png)

Title: IBM Plex Sans, Bold, all caps, 2.448rem, 2rem padding under
Stroke: 0.1rem (1pt?) stroke, 2em padding under
Body text: should be the same as the typography specs specified in another card #1072  
Body color: should match the color chosen in book specs (example for chemistry please reference #1086)

**Comment by openstaxalina** [comment]
@lwtchu please review and confirm this has the info you want for the **answer key**.

**Comment by lwtchu** [comment]
confirmed

**Comment by clee1060** [comment]
<img width="823" alt="Screen Shot 2019-07-25 at 9 26 04 AM" src="https://user-images.githubusercontent.com/16073667/61882497-47046380-aebe-11e9-8d68-3f930423d93d.png">

**Comment by Stackblocks** [comment]
Aesthetics now match but header font size is larger than its peers

---

![2019-08-01_10-32-52](https://user-images.githubusercontent.com/12678235/62306961-66fccf80-b448-11e9-9548-466b3d6f894a.png)

---

![2019-08-01_10-33-22](https://user-images.githubusercontent.com/12678235/62306970-682dfc80-b448-11e9-9a3d-214452b5f575.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8f4148b0-3353-4d4e-acde-54b0394b57c6)

**Comment by openstaxalina** [comment]
The subtitles (which are the chapter headers) should be styled as H2s:

![AKH2Styling](https://user-images.githubusercontent.com/7863733/63527123-23850680-c4c6-11e9-9215-4b06251580e0.png)

**Comment by wilkus27** [comment]
Ready for testing. Resolved by https://github.com/openstax/cnx-recipes/pull/1313

**Comment by MartaSztuka** [comment]
Chapter headers styling in Answer Key matches styling in Appendix headers.
![Screenshot from 2019-08-27 12-52-49](https://user-images.githubusercontent.com/47241114/63765663-d4761180-c8c9-11e9-805a-14dbbd86ae04.png)
