### ISSUE TITLE
carnival theme: Anatomy: references styling

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1152]
![Screen Shot 2019-05-20 at 2 48 26 PM](https://user-images.githubusercontent.com/11299125/58047697-5a85fd80-7b0e-11e9-96ca-0f72b7903c61.png)
![Screen Shot 2019-05-20 at 2 48 29 PM](https://user-images.githubusercontent.com/11299125/58047698-5a85fd80-7b0e-11e9-8a3a-c65d1177c787.png)

Title: IBM Plex Sans, Bold, all caps, 2.448rem, 2rem padding under
Stroke: 0.1rem (1pt?) stroke, 2em padding under
Body text: should be the same as the typography specs specified in another card #1072  
Body color: should match the color chosen in book specs (example for chemistry please reference #1086)

REFERENCE/ENDNOTES ONLY: Base text: alegreya, 1.2rem and should have hanging indents

**Comment by openstaxalina** [comment]
@lwtchu please review and confirm this has the info you want for the **references**.

**Comment by lwtchu** [comment]
Confirmed

**Comment by helenemccarron** [comment]
Per Natalia, the specs for references do not match Anatomy specs, reopening so we can examine the requirements.

**Comment by wilkus27** [comment]
Yes, that's how it looks currently:

![image](https://user-images.githubusercontent.com/40228854/64419187-9c768780-d09c-11e9-9316-0c17119c90cd.png)

**Comment by helenemccarron** [comment]
- [ ] Refactor `$ReferencesContainerComponent: ( _name: "Container"`, to target `os-references-container`
- [ ] Create a reference component

**Comment by wilkus27** [comment]
Update: main title should be styled as specified here: https://github.com/openstax/cnx-recipes/issues/1290

**Comment by MartaSztuka** [comment]
This is how it's styled now.
![Screenshot from 2019-09-11 13-11-20](https://user-images.githubusercontent.com/47241114/64692578-c9a8a880-d495-11e9-944c-32eea396c10d.png)

**Comment by MartaSztuka** [comment]
baked pdf
![Screenshot from 2019-09-11 17-23-37](https://user-images.githubusercontent.com/47241114/64710834-ef937480-d4b8-11e9-847c-87440d475c31.png)
