### ISSUE TITLE
carnival theme: index styling

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1153]
![Screen Shot 2019-05-20 at 2 48 26 PM](https://user-images.githubusercontent.com/11299125/58047697-5a85fd80-7b0e-11e9-96ca-0f72b7903c61.png)
![Screen Shot 2019-05-20 at 2 48 29 PM](https://user-images.githubusercontent.com/11299125/58047698-5a85fd80-7b0e-11e9-8a3a-c65d1177c787.png)

Title: IBM Plex Sans, Bold, all caps, 2.448rem, 2rem padding under
Stroke: 0.1rem (1pt?) stroke, 2em padding under
Body text: should be the same as the typography specs specified in another card #1072  
Body color: should match the color chosen in book specs (example for chemistry please reference #1086)

INDEX ONLY: entries should be 3 column

**Comment by openstaxalina** [comment]
@lwtchu please review and confirm this has the info you want for the **Index**.

**Comment by lwtchu** [comment]
confirmed

**Comment by philschatz** [comment]
The screenshots in this Issue seem to show an Appendix, **not** the Index

**Comment by openstaxalina** [comment]
(Per discussion in planning - the Index will use very similar styling as the Index; see the specifications below the screenshots.  The screenshots are intended as a rough guide for testing.)

**Comment by clee1060** [comment]
<img width="546" alt="Screen Shot 2019-07-10 at 2 43 24 PM" src="https://user-images.githubusercontent.com/16073667/60999580-1d293980-a321-11e9-86a6-3e7f7954f8a4.png">

**Comment by Stackblocks** [comment]
Styling displaying as specified with updated version of content / code.

Spinning off related issues to be handled separately:
cnx-recipes#1220 - Module links in A and K headers in the index
cnx-recipes#1221 - Line spacing
