### ISSUE TITLE
carnival theme: appendix/appendices styling

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1154]
![Screen Shot 2019-05-20 at 2 48 26 PM](https://user-images.githubusercontent.com/11299125/58047697-5a85fd80-7b0e-11e9-96ca-0f72b7903c61.png)
![Screen Shot 2019-05-20 at 2 48 29 PM](https://user-images.githubusercontent.com/11299125/58047698-5a85fd80-7b0e-11e9-8a3a-c65d1177c787.png)

Appendix #: IBM Plex Sans, Bold, all caps, 2.448rem, 2rem padding under
Stroke: 0.1rem (1pt?) stroke, 2em padding under
Appendix Title:  Muli, 3.583rem, color, 3em padding under
Body text: should be the same as the typography specs specified in another card #1072  
Body color: should match the color chosen in book specs (example for chemistry please reference #1086)

**Comment by openstaxalina** [comment]
@lwtchu please review and confirm this has the info you want for the **appendix/appendices**.

**Comment by lwtchu** [comment]
confirmed

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d7107d93-e80f-48b0-aaf5-32175fb95034)
