### ISSUE TITLE
Generate ePubs for Study Edge

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1162]
# Scenario

(This is the task card for the project we discussed on Thursday 6/20.)

We need to generate ePubs - with up-to-date content - for our ecosystem partner, Study Edge, so they can ingest our content into an OpenStax-Study Edge app.  We decided to use staging.cnx.org for this purpose, as content was refreshed there on Thursday, June 20.

[This spreadsheet](https://docs.google.com/spreadsheets/d/14GLK8wnYo4SHTZdvFjJWYHlqdBjXCxfqZnXsjxa6emo) has the list of titles, with their UUIDs and versions, for the ePubs that need to be created.

Here are the steps for generating an ePub:
1) SSH into the server.
2) Run a command based on the UUID provided.
3) Wait for the command to complete.
4) Download the file.
5) Delete the ePub-only content.
6) Rename the index file to `index.html`.
7) Zip the folder with the proper file name.
8) Upload to [this Google Drive folder](https://drive.google.com/drive/folders/1lw9BfhIcOG0gFdWz9ZgY3yLfXpaJ8ef0).
9) Use @cm in the #books-and-candles channel to alert content managers that an ePub is ready for QA.
10) Delete the collection that was generated in the Home folder.

Repeat the process until all ePubs have been generated.

# Environment:

* **Medium**: [ ] REX [ ] PDF  [x] cnx.org  
* **Instance**: [ ] production  [ ] qa  [x] staging  [ ] dev  [ ] content

# Test Plan 
- Alert @cm in the #books-and-candles channel to alert content managers that an ePub is ready for QA
- CMs will open issues in this repo for any files that do not pass testing.

# Acceptance Criteria
- All books on the spreadsheet have had ePubs uploaded to the [folder](https://drive.google.com/drive/folders/1lw9BfhIcOG0gFdWz9ZgY3yLfXpaJ8ef0).

**Comment by openstaxalina** [comment]
Waiting for Alina/Rosemary - finish updating spreadsheet and confirm staging.cnx.org can be blocked from deploys while this work is happening.

**Comment by openstaxalina** [comment]
@clee1060 - I noticed I was still assigned on this, so I unassigned myself and added you, instead.  Could you move this to In Progress if you've started it?  cc @brittany-johnson

**Comment by clee1060** [comment]
All epubs have been generated

**Comment by Stackblocks** [comment]
Verified.
