### ISSUE TITLE
college physics & ap physics: phet explorations feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1165]
iconned feature, following these specs: #1088

However, due to the collaborative nature of this feature, we'll need to feature their full logo. Please refer to screenshot.

![Screen Shot 2019-08-16 at 4 29 04 PM](https://user-images.githubusercontent.com/11299125/63199286-00300680-c043-11e9-93cf-2e62d3a12ca4.png)

Title: PhET Explorations
Class: `"phet­explorations-embedded"`
Color: #0DC0DC
Icon: https://drive.google.com/open?id=1gB9IElvz-AAznrR44B52hMtjZuBbgcBT 
PhET Logo: https://drive.google.com/open?id=13STH1-DQohT4YPK6Nn21Gv65lg6iH7yI
Logo postition: 2px from the bottom stroke; left aligned

NOTE FOR AP PHYSICS: THERE IS NO CLASS FOR THESE. THERE'S A CARD FOR A CM TO ADD CLASSES https://app.zenhub.com/workspaces/content-management-5c86d8c40b66e07993f45cfa/issues/openstax/content-managers/1075

**Comment by brittweinstein** [comment]
@lwtchu please provide more info on the content itself. We do not understand if this is a screenshot of the sim and will need a new screenshot per phet.

**Comment by lwtchu** [comment]
@brittweinstein Sorry for the confusion. The screenshot of the PhET is just to show where the PhET would go. In the PDF it will be a link. And on REX (eventually) it will look like that screenshot.

**Comment by wilkus27** [comment]
This will be solved by https://github.com/openstax/cnx-recipes/issues/1588 where style is added, but for proper display of this note some changes in recipes and in content are needed.

Issue for recipe: https://github.com/openstax/cnx-recipes/issues/1700
Issue for content: https://github.com/openstax/content-managers/issues/1272

**Comment by helenemccarron** [comment]
Larissa will add the classes to AP physics, based on https://github.com/openstax/cnx-recipes/issues/1588 this is completed from a developer's perspective, we will test again during the 100% regression testing, this should be considered a known issue for the 80% version of all the concerned books.
