### ISSUE TITLE
carnival theme: no class tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1166]
Starts occurring in College Physics where the title is in the `<title>` tag.

![Screen Shot 2019-06-26 at 4 29 19 PM](https://user-images.githubusercontent.com/11299125/60216405-91e37a80-982f-11e9-9b1e-8ff4d5a92cf3.png)

PDF: https://drive.google.com/open?id=1CF_JEE_zjqlS3RK-FEyoWfXKo2GW8o6W 
Specs for the table itself should be the same as this: #1080
Specs for caption should be the same as this: #1081 

Colors shown here are #1E9475 but can we match the header? If not we can use #1E9475

**Comment by lwtchu** [comment]
Investigating some stuff first: #1174

**Comment by brittany-johnson** [comment]
no class table
<img width="738" alt="Screen Shot 2019-08-13 at 10 20 45 AM" src="https://user-images.githubusercontent.com/24909007/62954479-19238800-bdb5-11e9-9ab9-018bc728f264.png">

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b643d44a-bebd-45f1-b4a4-a2d74591ec72)

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/aaf14ecd-233e-4c0d-a38f-cdcb70adfda7)
