### ISSUE TITLE
Rename spaces and subspaces with shapes and subshapes

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#1167]
# What happened?
In the [style framework](https://docs.google.com/document/d/16GcclCetD-Wjx4hFuouEsfsMLzaGWiY2BqCZbtNvtsw/edit#heading=h.v9tce34hcz1g): 
- Rename superspace -> shape and space -> subshape
- Also, rename nullable and not nullable to optional and required
- Rename any other files/directories that used old terminology

**Comment by Stackblocks** [comment]
# Shape
﻿![205797.gif](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ab49006b-4352-4097-baf2-ecab99c32ba7)

# Subshape
![1200px-Papa_class_submarine_2.jpg](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/2360602b-bc73-47a7-a2ad-cd2e45c055a8)
