### ISSUE TITLE
APUSH Exercise Numbering: Should Restart at "1" with Each Assessment Type in Each Section

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1170]
# Scenario

We need to make some adjustments to the schemas for numbering `<exercise>`s in APUSH.

Exercise numbering should restart with each section **and** with each exercise type.

For example, in this module: https://staging.cnx.org/contents/KC8KeLYF@2.1:w01bi3xv@2/1-2-%F0%9F%93%96-Chapter-Introductory-Essay...
![FreeResponseStartOver](https://user-images.githubusercontent.com/7863733/60371105-e7e62880-99bd-11e9-8846-cda129e37642.png)

- Known exercise types:
Review Questions
Free Response
Historical Reasoning
Sourcing Questions
Comprehension Questions
AP Practice Questions

# Environment:

* **Medium**: [ ] REX [ ] PDF  [x] cnx.org  

# Test Plan 

# Acceptance Criteria

**Comment by openstaxalina** [comment]
Query here: https://docs.google.com/document/d/1geD7kVo6Mn-Ipy3y1OIkRiJXK0W9rI6gK5fxNQImYt0/edit#bookmark=id.wbxfazrh9hg1

**Comment by openstaxalina** [comment]
Query: do we need a class on each exercise `<section>` to restart at "1"?  Or can there be a rule that anytime` <section><exercise>` occurs, the numbering restarts at "1"?

**Comment by openstaxalina** [comment]
Discussed with Thomas - he will have exercise numbering start over each time a new section begins.  This is not dependent on the classes.

**Comment by Stackblocks** [comment]
Numbering is restarting by section following the update.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/464b912c-43f3-474c-83aa-c601d42994ce)

**Comment by mwest-WWprod** [comment]
For posterity: this issue is connected to escalated issues about (1) numbering appearing in some views and not in others; (2) numbering tied to ancillary Instructor Answer Guide.
