### ISSUE TITLE
APUSH: Move Exercise Text onto the Line with Its Number

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1171]
# Scenario

The text of any exercise should be in line with its number, **not** on the line below.

For example, in [this module](https://staging.cnx.org/contents/KC8KeLYF@2.1:nx-LSZj6@5/1-1-%F0%9F%93%8E-Inquiry-Organizer)...
![APUSHExerciseTxtSameLine](https://user-images.githubusercontent.com/7863733/60372824-afe1e400-99c3-11e9-97b3-ff3c6ab963e6.png)

# Environment:

* **Medium**: [ ] REX [ ] PDF  [x] cnx.org  

# Test Plan 

# Acceptance Criteria
-Exercise text appears on the same line as the exercise number.

**Comment by tomjw64** [comment]
This is a styling issue, not a recipe issue. Reassigning to @brittany-johnson

**Comment by openstaxalina** [comment]
Issue moved to [openstax/webview #2266](https://github.com/openstax/webview/issues/2266) via [**ZenHub**](https://www.zenhub.com/)
