### ISSUE TITLE
Staging needs an update: Exercises not Being Pulled in from Exercises

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1172]
# Scenario

[need to confirm if this is server-specific once code is on production July 1.]

For example, in [this module](https://staging.cnx.org/contents/KC8KeLYF@2.1:dRxv9huA@2/1-3-%F0%9F%94%8E-Native-People)...
![Screen Shot 2019-06-28 at 4 47 04 PM](https://user-images.githubusercontent.com/7863733/60373060-6776f600-99c4-11e9-9233-73314d99e2f6.png)

# Environment:

* **Medium**: [ ] REX [ ] PDF  [x] cnx.org  
* **Instance**: [ ] production  [ ] qa  [x] staging  [ ] dev  [ ] content
* **OS**: [x] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [x] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact

* **Severity**: [x] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [x] High [ ] Medium  [ ] Low

# Test Plan 

# Acceptance Criteria

- exercises pull from Exercises to display on cnx instance.

**Comment by openstaxalina** [comment]
Per @helenemccarron - this is almost definitely a server issue.  The recipes do not change how the exercises are pulled in.

**Comment by oscryan** [comment]
Fixed https://content05.cnx.org/contents/CmIfJ6vh@28.1:CtEXAR4u@11/1-3-%F0%9F%94%8E-Native-People

**Comment by openstaxalina** [comment]
Thank you, I will move this into the backlog so eventually we can get whatever code we need on staging so we'll be able to test Exercises being pulled in.

**Comment by brittweinstein** [comment]
@openstaxalina can we close?

**Comment by openstaxalina** [comment]
@brittweinstein yep - closing!
