### ISSUE TITLE
epub content out of order

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#1175]
# What happened?

Content displaying out of order

# Reproducibility Details

Appears to be an issue for every clinical focus feature in the first module of each chapter. 

# Environment:

- **Book(s)**: Microbiology
- **URL/Server**: ePUB/prod
- **Location (page number, chapter/section)**: first section of each chapter

# Screenshots

![ss.jpg](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/98ab9f46-794a-49a1-98ac-f6689f7fe6f3)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment]
This feature "snaps" to the bottom of the page in the PDF only.  In webview, it should appear in the same place as it does in the ePub.  The discrepancy is acceptable; closing.

See related issue: https://github.com/openstax/cnx-recipes/issues/816#issuecomment-460681191
PDF vs Assignable Webview discrepancy is documented here: https://docs.google.com/spreadsheets/d/1dVpPsE2wTIZyoC4n8GnooqpntC2IZDTjcSdNMPycfB0/edit#gid=233364321
