### ISSUE TITLE
tables not rendering in epub 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#1176]
# What happened?

It appears that tables do not render in the epub version 

# Reproducibility Details

everywhere 

# Environment:

- **Book(s)**: Introductory Statistics +
- **URL/Server**:  epub/prod pdf
- **Location (page number, chapter/section)**:  Chapter 4 introdution, for example 
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots

![Screen Shot 2019-07-01 at 12.07.28 PM.jpg](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/06ae4976-01f3-4223-87c0-0aaf9bfcb5dc)

# Additional notes

**Comment by helenemccarron** [comment]
@openstaxalina this looks like a non-issue, the zip files do not have any styles, can we close this?

**Comment by openstaxalina** [comment]
@helenemccarron yes we can close this; because of the lack of styles, tables with blank cells looked particularly strange (as if they were missing), but we did alert Study Edge to resolve this on their platform by adding the necessary styles.
