### ISSUE TITLE
epub ToC is numbered ontop of hardcoded numbering in

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#1178]
# What happened?

In the ToC of the epubs, ```<ol>``` tags are generating numbering on top of the hardcoded numbering that was already present in chapter titles. 

# Reproducibility Details

- This is present both in an html view as well as when it is converted to an epub. 

# Environment:

- **Book(s)**: all 
- **URL/Server**: epub
- **Location (page number, chapter/section)**: table of contents
- **Browser**: Firefox

# Screenshots

![Screen Shot 2019-07-01 at 11.06.13 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/92d08e18-8fa8-4f92-921a-3afe217a775b)

# Additional notes

This may be something that is being fixed by hand

**Comment by brittweinstein** [comment]
@openstaxalina can we close?
