### ISSUE TITLE
Carnival Theme: Learning Objective Fonts

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#1180]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a8561575-fbbf-4adc-a440-d5bea24f1809)

Based on Larissa's specifications from #1077, coloration is correct and text is italicized, but the fonts need to be updated. 

- Font is DejaVu Serif instead of IBM Plex Sans Medium.
- List font is DejaVu Serif instead of Muli

**Comment by helenemccarron** [comment]
![2019-08-14_13-48-52](https://user-images.githubusercontent.com/8514591/63047711-97a62580-be9a-11e9-8a56-3755665ee7ee.png)

**Comment by Stackblocks** [comment]
Fonts were being imported incorrectly and the styling was spilling over into the list text. Resolved.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4eac75ba-dd1a-47da-a097-5dd30b43c46f)
