### ISSUE TITLE
biology for ap courses: boxed features

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1191]
See #1087 for specs

Has one from Biology (#1157)
- Everyday Connection (`class="everyday"`)

New boxed feature for AP Biology
Title: Everyday Connection for AP® Courses
Class: `ap-everyday`
Color: #B05E36

** Please make sure the registered trademark symbol is in superscript.

**Comment by brittweinstein** [comment]
assigning to @openstaxalina for prio

**Comment by brittweinstein** [comment]
@tomjw64 I think we can go ahead and merge?

**Comment by helenemccarron** [comment]
- [ ] add features to book.scss
- [ ] add specs to the spreadsheet https://docs.google.com/spreadsheets/d/1vW0EHvn8fZgvTxZIm9xQXsqsnIDcolqwt5rWKtx4JEY/edit#gid=1663003137

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6e15ed9e-b4d1-4193-a66c-d3d961fde7db)
