### ISSUE TITLE
biology for ap courses: header column tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1192]
Please test header column tables. One can be found in 1.1 The Science of Biology:
![Screen Shot 2019-07-10 at 4 43 37 PM](https://user-images.githubusercontent.com/11299125/61007233-ec9dcb80-a331-11e9-857d-ecfa87840d38.png)

The basic table design in the carnival theme should be able to give header treatments to the columns.
It has a crazy class on it: `unnumbered no-title column-header ost-reading-discard` 

<img width="828" alt="Screen Shot 2019-10-17 at 11 19 03 AM" src="https://user-images.githubusercontent.com/11299125/67027883-fd4ba380-f0cf-11e9-8587-086c05a27c11.png">

The font specs should be the same as the header rows.

**Comment by MartaSztuka** [comment]
Styled
![Screenshot from 2019-10-30 12-45-48](https://user-images.githubusercontent.com/47241114/67856104-16af0f80-fb14-11e9-8e71-30aab0a27ce0.png)
