### ISSUE TITLE
biology for ap courses: exercises from exercises.openstax.org

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1194]
Prevalent in Review Questions. Make sure these aren't styled wildly different.

Sample CNXML:
```<exercise class="os-exercise">
<problem> 
<para>
<link class="os-embed" url="#ost/api/ex/apbio-ch01-ex015" />
</para>
</problem>
</exercise>
<exercise class="os-exercise">
<problem> ```

**Comment by MartaSztuka** [comment]
Review Questions looks ok.
![Screenshot from 2019-11-27 14-01-29](https://user-images.githubusercontent.com/47241114/69725944-b1087000-111f-11ea-87e0-c8b7b019840c.png)
