### ISSUE TITLE
Slug URL is missing chapter # 

### ISSUE THREAD

**Issue by kjdav** [openstax/cnx-recipes#1200]
# What happened?

End of chapter content like this page https://rex-web.herokuapp.com/books/astronomy/pages/2-review-questions do not get correct slugs from the new cnx slug functionality. This means that all of the end-of-chapter content has the same URL, regardless of the chapter.

The issue happens nested items within a chapter. (Eg. please see screenshot. All items under "Exercises" are missing the chapter number)

# Reproducibility Details

- **Does it also happen in an incognito window?**: 
- **Does this happen in one place, a few places, or everywhere?**:

# Environment:

- **Book(s)**:
- **URL/Server**: 
- **Location (page number, chapter/section)**:
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots
![Screen Shot 2019-07-09 at 3.26.17 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/9a24362a-07a5-44d9-8151-a92dc34bcfaa)
(_attach here (please clearly label what environment each screenshot came from)_)

# Acceptance

GIVEN the page Astronomy / 2 / Exercises / Review Questions
THEN the url should be “/books/astronomy/pages/1-review-questions”

previous acceptance for the slug URL's should all also pass with this change, copied below

GIVEN the page “College Physics / Viscosity and Laminar Flow; Poiseuille’s Law”
THEN the URL should be “books/college-physics/pages/12-4-viscosity-and-laminar-flow-poiseulles-law”

GIVEN the page “College Physics / 1 Introduction: The Nature of Science and Physics / Problems & Exercises”
THEN the url should be “books/college-physics/pages/1-problems-exercises”

GIVEN the page “Biology 2e / 1.1 The Science of Biology”
THEN the url should be “books/biology-2e/pages/1-1-the-science-of-biology”

GIVEN the page Biology 2e / Preface
THEN the url should be “books/biology-2e/pages/preface”

**Comment by openstaxalina** [comment]
Issue moved to [openstax/cnx #595](https://github.com/openstax/cnx/issues/595) via [**ZenHub**](https://www.zenhub.com/)
