### ISSUE TITLE
Fixes to the Icons to (Hopefully)

### ISSUE THREAD

**Issue by clee1060** [openstax/cnx-recipes#1202]
# What happened?

When @Stackblocks tried to build the pdf, the icons for example and link to learning were messed up so hopefully this changed it.

# Screenshots

![Screen Shot 2019-07-11 at 11.45.37 AM.png](https://images.zenhubusercontent.com/5bafc0774b5806bc2bea85be/f3dfd950-caa4-4f76-9d83-a659f89956df)

**Comment by Stackblocks** [comment]
Helene's base font size fix is applied, but i'm still not seeing the icons. Do I need to do anything outside of the stated instructions on the cnx-recipes repo to get the images to load?

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/02b16b5b-e600-47f7-a8d5-36f0f180efa5)

**Comment by Stackblocks** [comment]
Changing from `url("../designs/carnival/resources/carnival-linktolearning.svg") no-repeat top left` to `url("../../styles/designs/carnival/resources/carnival-linktolearning.svg") no-repeat top left` seems to have resolved the issue, please do the needful.

**Comment by Stackblocks** [comment]
@clee1060 It looks like `example`and `link to learning` got updated, but `how sciences interconnect` did not. Please do the needful.
