### ISSUE TITLE
library wide: no emphasis term tags

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1205]
Term tags with `class="no-emphasis"`should still show up in the index but should not be bolded in the text.

**Comment by openstaxalina** [comment]
Putting a 1 on this per Hélène's comment in our Tuesday morning meeting.  Feel free to increase if needed!

**Comment by Stackblocks** [comment]
@tomjw64 Can you comment on what happened in this issue and what the decided / implemented solution was?

**Comment by tomjw64** [comment]
We didn't have bolded terms to begin with, so I bolded all terms except those with a class of no-emphasis

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/69d672e8-3425-4152-9b2c-641eda81c6bd)

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5f140778-8df0-466a-8235-a86bdbb33efd)
