### ISSUE TITLE
Docker build-pdf command not working correctly

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#1208]
# Scenario
Given the same fetched data run through the same steps to assemble, bake, and mathify the content, using the `docker-compose` command to generate the PDF results in an output that is not styled properly.

Running the `prince` command to output a PDF outputs a correctly styled PDF. Since we recommend the docker-compose commands in the repo readme this should be fixed.

# Steps to Reproduce

1. Run `docker-compose run --rm fetch-book --with-resources chemistry` to download the cnxml from the server.
2. Run `docker-compose run --rm assemble-book chemistry` to create the single-file HTML for the book.
3. Run `docker-compose run --rm bake-book chemistry` to convert the single-file HTML locally into the "baked" book.
4. Run `docker-compose run --rm mathify-book chemistry` to convert all the math to svg.
5. Run `docker-compose run --rm build-pdf chemistry` to create the pdf.
6. Run `prince data/chemistry/collection.mathified.xhtml -o test.pdf` and compare the results against the output from step 5.

* **How many times were you able to reproduce the issue?** 

Consistently reproducable

* **Images or Screenshots Included:** [ x ] Yes  [ ] No  (_attach below_)

# Environment:

* **Medium**: [ ] REX [ X ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content [ x ] local
* **OS**: [ x ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android

# Impact

* **Severity**: [ x ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ x ] High [ ] Medium  [ ] Low

# Acceptance Criteria
Building a PDF with the commands outlined in the cnx-recipe repo instructions outputs a complete and styled PDF if possible.
---

## Docker build
![image](https://user-images.githubusercontent.com/12678235/61237690-a0230900-a700-11e9-9de3-c0a59a84f2cb.png)

## Prince build
![image](https://user-images.githubusercontent.com/12678235/61237708-aca76180-a700-11e9-9995-8da6ef59da21.png)

**Comment by openstaxalina** [comment]
@karenc This is the issue we were talking about in the Katalyst channel this morning.  Would you be able to take a look when you get a chance?
