### ISSUE TITLE
Mysterious Module links in Chemistry Index

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#1220]
# What happened?

Mysterious module links in the `A` and `K` header rows 

# Reproducibility Details

- **Does it also happen in an incognito window?**: 
- **Does this happen in one place, a few places, or everywhere?**: In the Index of Chemistry, made using `prince -s styles/output/chemistry-pdf.css data/chemistry/collection.mathified.xhtml -o test.pdf` and chemistry content from ezvm5

# Environment:

- **Book(s)**: Chemistry
- **URL/Server**: easyvm5.cnx.org
- **Location (page number, chapter/section)**: Index

# Screenshots

﻿﻿![2019-07-19_14-04-46.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/04cc8f20-46a5-4ec4-8f8d-91ca974b512f)

**Comment by Stackblocks** [comment]
PDF generated with freshly fetched content generated with the prince command is still showing the links on A and K title rows.

Steps taken:

- Run `docker-compose run --rm fetch-book --with-resources chemistry` to download the cnxml from the server.
- Run `docker-compose run --rm assemble-book chemistry` to create the single-file HTML for the book.
- Run `docker-compose run --rm bake-book chemistry` to convert the single-file HTML locally into the "baked" book.
- Run `docker-compose run --rm mathify-book chemistry` to convert all the math to svg.
- Run `prince -s styles/output/chemistry-pdf.css data/chemistry/collection.mathified.xhtml -o test.pdf` to create the pdf.

## Screenshots
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/195f979d-3c15-4942-802d-fd6272d0b569)
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/dd8f0fec-cdb7-4aae-b549-400cc373563f)

**Comment by openstaxalina** [comment]
This is happening because the content on easyvm5 has single-letter index terms, which were removed on production.  Need to refresh content on easyvm5.

**Comment by openstaxalina** [comment]
Content was refreshed on easyvm5.  @Stackblocks would you be able to retest and close if this is resolved?

**Comment by Stackblocks** [comment]
Still getting the A & K links with new content

![image](https://user-images.githubusercontent.com/12678235/62496816-bff99a00-b79f-11e9-8b19-86726a8503a7.png)

![image](https://user-images.githubusercontent.com/12678235/62496814-ba9c4f80-b79f-11e9-89be-317cb798df63.png)

**Comment by oscryan** [comment]
No single-letter terms in content on production. The updated content is not getting to easyvm5.

**Comment by openstaxalina** [comment]
https://openstax.slack.com/archives/C0FU3MARF/p1565101035195300

**Comment by Stackblocks** [comment]
Resolved by setting books.txt to fetch Chem 2e instead of Chem 1e.
