### ISSUE TITLE
Update on-boarding/ training documentation 

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#1222]
# What happened?

*Will add more details later* :) 

# Reproducibility Details

- **Does it also happen in an incognito window?**: 
- **Does this happen in one place, a few places, or everywhere?**:

# Environment:

- **Book(s)**:
- **URL/Server**: 
- **Location (page number, chapter/section)**:
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots

(_attach here (please clearly label what environment each screenshot came from)_)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment]
Starting this sprint with a goal to complete this next sprint.

**Comment by openstaxalina** [comment]
This will be needed to onboard the new Katalyst developer (mid-August/early September).

**Comment by brittany-johnson** [comment]
Waiting until chemistry is done

**Comment by brittweinstein** [comment]
@brittweinstein move to P.P.

**Comment by openstaxalina** [comment]
@helenemccarron created this document: https://docs.google.com/document/d/1QYVnjS_WZxe84Prh6_Ay-MG5ui9gNkmeZmhLRObrY7U

**Comment by helenemccarron** [comment]
We should move the contents of the google doc to the wiki https://github.com/openstax/cnx/wiki
