### ISSUE TITLE
fs-to-json does not preserve alphabetic filename order

### ISSUE THREAD

**Issue by clee1060** [openstax/cnx-recipes#1237]
# Scenario
Seems like this is only on Mac OS, repeating "npm run build:web-styles && cat styles/output/_web-styles.json" gives a different order of textbooks.

# Steps to Reproduce
Run the above command several times, observe potentially different results?

* **How many times were you able to reproduce the issue?** 
Too many times

# Environment:
Mac OS

# Temporary Solution
Repeatedly run the command until the textbooks are in alphabetical order.

**Comment by tomjw64** [comment]
partially addressed in #1245 in that this file is no longer included in CI diff tests

**Comment by openstaxalina** [comment]
@helenemccarron @tomjw64 I put this in the Baked Styles backlog, but please let me know if this should/is being included in releasing the chemistry styles for testing.

**Comment by brittweinstein** [comment]
@brittany-johnson will this be resolved with the clean up work?
