### ISSUE TITLE
DOCUMENTATION: library wide: table issue to end all table issues 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1241]
Piggy backing on this format: https://github.com/openstax/oer.exports/issues/3399 

**Designs should be theme specific, but these are *ALL* the possible table combinations in all of humanity. Screenshots are only for a functional reference ONLY!!!!**

# The Basics: text alignment, merged cells, fixed widths and forced styling
From here on out, text alignment and styling (bold, italic, bold italic, all caps, etc) should be dictated by the content. Here are possible alignment options: 
- **align = left, right, center, justify, char (aligns to an attribute)** 
- **valign = top, middle bottom**

Merged cells are also a thing that exists. If you don't know what a merged cell is, please contact an adult. or look at the example below! 
![Screen Shot 2019-07-25 at 4 47 01 PM](https://user-images.githubusercontent.com/11299125/61911044-df6d0900-aefb-11e9-9982-2d75758ff3ee.png)

On that note, empty cells also exist! 

## Fixed width tables
- Example in https://cnx.org/contents/LZQauaxb@5.7:uxtmS7FY@2/8-2-Techniques-of-Performance-Appraisal
![Screen Shot 2019-08-01 at 9 34 10 AM](https://user-images.githubusercontent.com/11299125/62302195-8e02d380-b43f-11e9-91bc-b58aa461057a.png)

# Unnumbered unstyled tables (NAME: `unstyled`)
- `class="unnumbered unstyled"`
- Design specs are here: #1084
- The `unstyled` part should unstyle the table and `unnumbered` should function as it should like in other objects.

### Example 
![Screen Shot 2019-07-24 at 11 17 16 AM](https://user-images.githubusercontent.com/11299125/61810309-a2721b00-ae04-11e9-95ba-7dd57eb32f37.png)

### Notes
This design is the only version of table where there are no lines or no special treatment. They are usually unnumbered. No header row or columns should be applied for these tables. 

Standard: should use the base font for the theme/book/design and should have about 1rem padding in cells 

# Basic, no class tables, default table style (NAME: `default table`)
These tables have no class ! 

Could have `<caption>` or `<title>` that goes below the table. May have table headers, footers, etc. but nothing gets moved anywhere. 

## No header
<img width="671" alt="Screen Shot 2019-07-25 at 10 39 45 AM" src="https://user-images.githubusercontent.com/11299125/61888117-92bc0a80-aec8-11e9-8543-586622cff876.png">

## One header
<img width="653" alt="Screen Shot 2019-07-25 at 10 42 02 AM" src="https://user-images.githubusercontent.com/11299125/61888273-dca4f080-aec8-11e9-82a4-92ce290b2505.png">

## Two header
<img width="644" alt="Screen Shot 2019-07-25 at 10 43 47 AM" src="https://user-images.githubusercontent.com/11299125/61888434-1b3aab00-aec9-11e9-8376-680d2500ed9e.png">

## *x* header
In theory, one could add an infinite amount of headers into the header rows. This is possible but most books will probably cap out at 3.

# Fake top title (`class="top-titled"`)  (NAME: `fake header title` FOR NOW. Need to revisit later.) 
- Carnival theme specific: #1080

Any table with a class `top-titled` will have a "fake title" in the header row. The first header row should be targeted and styled like a title (i.e. no borders and styled)

## Version 1: Fake title + no header
There's only one row in the header row. 
### Example
![Screen Shot 2019-07-24 at 11 19 36 AM](https://user-images.githubusercontent.com/11299125/61810470-f0871e80-ae04-11e9-97ed-af4d6e4f825d.png)

## Version 2: Fake title + 1 header
There's two rows in the header row. The first one should be a fake title and the second should start getting styling treatment!
### Example
![Screen Shot 2019-07-24 at 11 32 25 AM](https://user-images.githubusercontent.com/11299125/61811287-ccc4d800-ae06-11e9-9460-6f3484f29a9d.png)

## Version 3: Fake title + 2 headers
Has 3 headers but first header serves as a title. Second and third would get styling.
### Example
<img width="651" alt="Screen Shot 2019-07-25 at 11 02 59 AM" src="https://user-images.githubusercontent.com/11299125/61889866-d6644380-aecb-11e9-9b2b-5732af92c1d4.png">

# Header columns (`column-header`) (NAME: `column header`)
In addition to header rows, there are also header columns! They should match the styling of header rows unless noted otherwise. They could have fake titles or not. Here are some examples. 

They are the DEFAULT table with header styling on the column.

- Note: In _Biology for AP Courses_ these appear with the `column-header` class.

## Version 1: Header column only
- These are present in Chemistry.
<img width="637" alt="Screen Shot 2019-07-25 at 12 34 44 PM" src="https://user-images.githubusercontent.com/11299125/61895579-9e173200-aed8-11e9-9a50-e7a24a8f0de5.png">

## Version 2: Header column and row
![Screen Shot 2019-07-26 at 3 19 39 PM](https://user-images.githubusercontent.com/11299125/61979195-d1c98900-afb8-11e9-82e7-df79ca6daa43.png)
- These are common for tables like multiplication tables. 

## Version 3: Header column and a `top-titled` table
- I haven't encountered this yet but it's a possibility.
![Screen Shot 2019-07-26 at 4 09 32 PM](https://user-images.githubusercontent.com/11299125/61981630-cded3500-afbf-11e9-8d3a-916725ccb52b.png)

# Footer rows
- Footer rows will exist and typically just have additional reference data that goes with the table.
![Screen Shot 2019-07-26 at 4 16 44 PM](https://user-images.githubusercontent.com/11299125/61981956-d6923b00-afc0-11e9-9afa-863fd374c7cc.png)

# `text-heavy` tables
- Introduced in the Business Series and a part of the Business (box? cardboard cutout?idk) theme. These tables have a very minimal design to accommodate lots of text. 
- Could be combined with `top-titled`
https://user-images.githubusercontent.com/11299125/36122397-cd2d2c80-100e-11e8-8760-819bd350c47d.png

# bottom lined only tables
- These exist in the developmental math series to accommodate for the stepwise math instructions.
- It is currently using the `unnumbered unstyled` class and will need another class when the time comes.

**Comment by lwtchu** [comment]
![IMG_1396](https://user-images.githubusercontent.com/11299125/67103690-3e54be00-f18b-11e9-8b25-3d61f959e4f6.jpg)
![IMG_1397](https://user-images.githubusercontent.com/11299125/67103692-3eed5480-f18b-11e9-8776-5c7bb8a29fe9.jpg)
Notes from Oct 17

**Comment by ajluk** [comment]
In AP Biology there are occurring tables with class `.unnumbered no-title` (without `.unstyled `).  After consulting it with Larissa they have been given the "basic table styling". Issue: #1528

**Comment by lwtchu** [comment]
Just to reference here: the `no-title` class will be removed when we're ready to do baked styles content changes (https://app.zenhub.com/workspaces/content-management-5c86d8c40b66e07993f45cfa/issues/openstax/content-managers/1200)

**Comment by lwtchu** [comment]
Documentation: Carnival theme design: https://github.com/openstax/cnx-recipes/issues/1080

**Comment by brittweinstein** [comment]
@lwtchu can this be updated with corn theme specs?

**Comment by lwtchu** [comment]
Oops a few months late but
Corn theme: #2204

**Comment by lwtchu** [comment]
Cardboard: #2741

**Comment by lwtchu** [comment]
not sure why open 🤔 closing
