### ISSUE TITLE
New empty self-closing tags are added on cnx-recipes on baking

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#1249]
@therealmarv commented on [Thu Jul 25 2019](https://github.com/openstax/cnx/issues/614)

# Description

Raw transformed HTML has no self-closing tags.
After baking new self-closing tags are sometimes discovered.

The following tags have so far be seen added through cnx-recipes (list to be updated..)
```
span
sub
em
iframe
h3
```

referencing issue https://github.com/openstax/webview/issues/2268

## Acceptance criteria

Tools in https://github.com/openstax/ce-scripts have xpath search and w3c validator inside.

XPath search should not return any self-closing tags for baked books from the list above.

Additional: w3c validator check should not return any self-closing tags. See for details here https://openstax.slack.com/archives/C0LA54Q5C/p1563565571480900

**Comment by therealmarv** [comment]
First examples of empty `em` and empty `sub` are found here in this spreadsheet which covers two chemistry books:
https://openstax.slack.com/archives/C0LA54Q5C/p1564417650480500

Because staging is currently rebaking I will update this issue with more examples after rebaking.

**Comment by therealmarv** [comment]
This are the newest results for baked books 2019-07-31 CSV:
https://drive.google.com/open?id=13O50wBqZ0NU-AN_hXFshdU-JSa_WyjUY

they are most of the times empty spans which are added by cnx-recipes.
