### ISSUE TITLE
CLEAN UP:  typograpy imports

### ISSUE THREAD

**Issue by tomjw64** [openstax/cnx-recipes#1259]
![fonts](https://user-images.githubusercontent.com/1285308/62387392-1658a580-b520-11e9-978e-c54da1ee5829.png)
We need to remove duplicates and remove unnecessary comments. This should be a low estimate for devs, but regression testing may yield a higher estimate on this.

**Comment by openstaxalina** [comment]
@tomjw64 when is this needed? I'm going to place this in the backlog but please let me know if this is needed to release chemistry styles for full-book testing.

**Comment by ajluk** [comment]
@brittweinstein I guess the file has been already cleaned up : 
![image](https://user-images.githubusercontent.com/55203598/76311858-1f89cc00-62d2-11ea-9ca6-ee5117eaa029.png) @helenemccarron could you advise?
