### ISSUE TITLE
Get uniform PDF generation using the CLI 

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1261]
This is a list of all the tasks required to ensure that all developers and QA are using the same local environment. 

- [x] prince image needs to have volume with styles and icons
- [x] push css data/ fix
- [x] venv still gets owned by root
- [x] pulling and assembling with neb at same time yields content with different checksums

**Comment by brittweinstein** [comment]
@brittweinstein move to P.P.

**Comment by brittweinstein** [comment]
When content is pulled from the same source at the exact same time, check sums are coming back different.

**Comment by brittweinstein** [comment]
@Bkblodget someone on the CE Tech team should look at the check sums on assembled books.

**Comment by m1yag1** [comment]
If there are issues with things we should urge people to create a card describing the problem and posting the link in chat and linking this card with the issue. CC: @brittweinstein @Bkblodget @helenemccarron

**Comment by karenc** [comment]
> pulling and assembling with neb at same time yields content with different checksums

The `assemble-book` command includes auto generated ids that are based on random numbers.  The ids have to be unique in the book and that's why we did it that way...  If it's necessary, we could possibly set a seed for the random number generation so the numbers will always follow the same pattern :thinking:

**Comment by tomjw64** [comment]
@brittweinstein I think we are save to close this based on the investigation by @karenc .

**Comment by brittweinstein** [comment]
WELL DONE, TEAM!
