### ISSUE TITLE
library wide: text alignment

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1277]
The default alignment for text is ~justified text~ LEFT ALIGNED throughout body text and within notes/features/examples/exercises. We will use something like `<emphasis class="centered-text">` or whatever we used for Accounting to do custom alignment.

It should be content driven alignment for tables. Please do not touch the text in tables!!

**Comment by lwtchu** [comment]
acooke [10:05 AM]
Re: justified text vs. accessibility
- https://webaim.org/techniques/textlayout/
- https://accessibility.huit.harvard.edu/design-readability
- http://www.zaetric.com/pdf/White%20Paper%20-%20Readability%20Legibility%20and%20Text%20Justification.pdf
- https://mediaaccess.org.au/accessibledocumentservice/2015/08/text-justification-is-a-key-accessibility-issue-in-documents/
- https://accessible-digital-documents.com/blog/justified-text/
- https://uxmovement.com/content/6-surprising-bad-practices-that-hurt-dyslexic-users/ (edited)

**Comment by lwtchu** [comment]
DECISION: make everything left aligned unless noted otherwise. see centered text in accounting

**Comment by tomjw64** [comment]
The decision above makes this a non-issue for this release, since text is left aligned by default.

**Comment by lwtchu** [comment]
@tomjw64 COOL. just documenting decision then. i'mma close this
