### ISSUE TITLE
APUSH: "Hover" Does Not Work Properly on Comprehension Questions

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1279]
@openstaxalina commented on [Tue May 28 2019](https://github.com/openstax/tutor/issues/443)

### Description

There is a "hover" functionality on questions in Primary Sources for APUSH.  It is working properly on tutor-qa.  However, when the same content is imported on tutor-content, the hover does not work.

Screenshot from tutor-qa:
<img width="883" alt="Screen Shot 2019-05-24 at 1 20 26 PM" src="https://user-images.githubusercontent.com/7863733/58507137-a6602480-8156-11e9-8ade-ad8bd0f9da31.png">

Screenshot from tutor-content (where the authors review): 
<img width="1147" alt="Screen Shot 2019-05-24 at 1 22 55 PM" src="https://user-images.githubusercontent.com/7863733/58507127-9fd1ad00-8156-11e9-9d53-d36b1419ac5f.png">

**To Reproduce**
Steps to reproduce the behavior are
1. Go to 'https://tutor-content.openstax.org/book/88/section/1.12' (ContentTeam login)
2. Click on 'That in the said island there shall be founded three or four towns, situated in the most convenient places, and that the settlers who are there be assigned to the aforesaid places and towns.'
3. Notice that, in the bottom left corner, some content that ends in `How were towns to be populated in Columbus’s plan for colonies?` displays.  However, this should appear as a "hover" or pop-up, as shown in the first screenshot (the one from tutor-qa).

Related Slack thread: https://openstax.slack.com/archives/C3PLC5NP7/p1558722227022400

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

---

@carlycurran commented on [Wed May 29 2019](https://github.com/openstax/tutor/issues/443#issuecomment-497027746)

Per the following, I am closing this card: 
Ryan Stickney [10:55 AM]
Yes, I've confirmed the template was set to CCAP American Government instead of American Government (with recipe). I changed it back and reimported; the figures are correctly numbered now, as are the links' autogenerated anchor text.

---

@openstaxalina commented on [Wed May 29 2019](https://github.com/openstax/tutor/issues/443#issuecomment-497118530)

@carlycurran unfortunately, the hover is still not working.  Ryan was referring to the links to figures (such as "Figure 1.1" that links to Figure 1.1).  I will reopen this!

---

@nathanstitt commented on [Tue Jul 30 2019](https://github.com/openstax/tutor/issues/443#issuecomment-516458045)

@openstaxalina I've **finally** investigated this properly, sorry for the delay.

It looks to me like both QA and content are not working properly currently.    Perhaps QA was in the past but it's now been updated to content that's also invalid.

The popovers work by matching the href of the link to an id in the content.   Popovers in APUSH are broken because the tag's href is not a valid selector, mainly because it often has invalid characters like a `?`.  Even if it was valid, I don't see any ids that look anything like the given href.   This is causing both clicks and the popovers to be broken.  

As an example on the "That in the said island..." link in section 1.12 has a href of `#fs-idm389806400%20How%20did%20Columbus%20propose%20that%20a%20%E2%80%9Cgold%20rush%E2%80%9D%20be%20prevented%20on%20the%20island?%20Why%20might%20a%20gold%20rush%20be%20bad?`

other books have a much simpler href like `#import-auto-id1381492` and then elsewhere in the content there's a `p` tag with a matching id.

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/1b8033ef-8adb-4527-b6d3-10f02dde8ead)

I tested as:

*  `contentteam` on content at: https://tutor-content.openstax.org/book/88/page/89609
* `teacher01` on qa at: https://tutor-qa.openstax.org/book/2723/page/105420
* And for an example of working popovers in physics as teacher01 at: https://tutor-qa.openstax.org/book/2757/page/101275

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://tutor-content.openstax.org/book/88/page/89609">OpenStax Accounts</a></strong></div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://tutor-qa.openstax.org/book/2723/page/105420">OpenStax Accounts</a></strong></div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://tutor-qa.openstax.org/book/2757/page/101275">OpenStax Accounts</a></strong></div></blockquote>

---

@openstaxalina commented on [Wed Jul 31 2019](https://github.com/openstax/tutor/issues/443#issuecomment-516966865)

@nathanstitt thank you so much!  Based on the above, this does look like a content issue.  @oscryan could you see if the production team is encoding hover links/text the way we advised in the tagging legend?  Here is the collection: https://content05.cnx.org/contents/CmIfJ6vh

<blockquote><div><strong><a href="https://content05.cnx.org/contents/CmIfJ6vh">OpenStax CNX</a></strong></div></blockquote>

---

@oscryan commented on [Wed Jul 31 2019](https://github.com/openstax/tutor/issues/443#issuecomment-517076577)

The markup is correct; the link is to the exercise whose text should pop up. Is the problem that the ID is to the whole exercise instead of to the problem element of it, or to the paragraph nested in the problem? Does hover not read nesting?
<img width="588" alt="Screen Shot 2019-07-31 at 7 56 48 PM" src="https://user-images.githubusercontent.com/1895432/62257886-6a06aa00-b3cd-11e9-8411-3a1b728fc34a.png">
<img width="591" alt="Screen Shot 2019-07-31 at 7 56 59 PM" src="https://user-images.githubusercontent.com/1895432/62257889-6d9a3100-b3cd-11e9-872c-7d734b3e02d0.png">

---

@oscryan commented on [Wed Jul 31 2019](https://github.com/openstax/tutor/issues/443#issuecomment-517077049)

The gold rush example also has the same markup, in case you were concerned about the link being "simpler"; that bizarre sentence-long link is not a content problem.
<img width="416" alt="Screen Shot 2019-07-31 at 8 00 37 PM" src="https://user-images.githubusercontent.com/1895432/62258016-fdd87600-b3cd-11e9-95e9-5a8af728e2b6.png">
<img width="353" alt="Screen Shot 2019-07-31 at 8 00 43 PM" src="https://user-images.githubusercontent.com/1895432/62258022-03ce5700-b3ce-11e9-9d23-edd1bdb742e0.png">

---

@openstaxalina commented on [Tue Aug 06 2019](https://github.com/openstax/tutor/issues/443#issuecomment-518783238)

@nathanstitt - @oscryan looked into the content and posted information above.

Could there be another cause besides the markup itself?  cc @carlycurran 

---

@openstaxalina commented on [Tue Aug 06 2019](https://github.com/openstax/tutor/issues/443#issuecomment-518784085)

actually, I think the additional content is somehow being added during baking, I'll talk with @helenemccarron + team about this soon to try to get an idea of what might be going on.

https://content05.cnx.org/contents/CmIfJ6vh@30.1:rYtSijjh@8/1-12-%E2%9C%92%EF%B8%8F-Columbus-s-Letter-to-Ferdinand-and-Isabella-of-Spain-1494

<img width="1071" alt="Screen Shot 2019-08-06 at 1 14 30 PM" src="https://user-images.githubusercontent.com/7863733/62565362-3a7ff380-b84c-11e9-84a3-fe6ad54fcce4.png">

<blockquote><div><strong><a href="https://content05.cnx.org/contents/CmIfJ6vh@30.1:rYtSijjh@8/1-12-%E2%9C%92%EF%B8%8F-Columbus-s-Letter-to-Ferdinand-and-Isabella-of-Spain-1494">OpenStax CNX</a></strong></div></blockquote>

**Comment by brittweinstein** [comment]
@brittweinstein put in P.P. sprint--may slide to Q.Q.

**Comment by brittweinstein** [comment]
@brittweinstein put in SS Sprint

**Comment by openstaxalina** [comment]
This is markup-related.  It appears the markup was changed after the screenshot above was posted.  The links contained the full text of the question rather than just the ID.  @oscryan providing Matt with instructions for correcting the markup.
