### ISSUE TITLE
DISCUSSION ONLY: Determine Best Path for Art Sizing on the Web 

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1283]
# Scenario

[Document](https://docs.google.com/document/d/1gAzOAyNPWQR_IeWchiTL-xEPN-QJiAqxgVRpz9RfnQQ)

The goal of this work is to understand our goals with art sizing, identify any options we should consider other than those in the doc (if applicable), and determine what work is needed to implement a solution for resizing art for the web.

**Comment by brittweinstein** [comment]
@brittweinstein move to P.P.

**Comment by brittweinstein** [comment]
Closing b/c this meeting happened.
