### ISSUE TITLE
library wide: pdf margins

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1285]
1inch left-right
0.8inch top-bottom (bottom won't be exact due to content on page)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/eea66f64-bbb4-4817-8e16-231c76a3528f)
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8a359ed9-61c6-4767-b761-92c75243d30e)
