### ISSUE TITLE
carnival theme: module headers

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1286]
<img width="745" alt="Screen Shot 2019-08-12 at 12 18 04 PM" src="https://user-images.githubusercontent.com/11299125/62884153-6b07d780-bcfb-11e9-99e6-587cbd9970af.png">
Ignore the red shading on the "By the end of this section"

font should be 18 pt (currently H2 in the typography scale)
font color should be whatever is stiuplated as the header colors: example: #1086 
Padding between line adn text: 1rem
Line weight: 0.5px

**Comment by Stackblocks** [comment]
Hi @wilkus27! Please take a look at this and work on making sure that Chemistry module titles meet these standards. If you have any questions please feel free to send me a message via slack or comment here.

**Comment by Stackblocks** [comment]
Closing / resolved per result of font parking lot 2019-08-15. 

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4f10c93e-cf43-41be-bd7d-f71a7ac34a1e)
