### ISSUE TITLE
CLEAN UP: Find a home for utility functions such as grid or typography (maybe a new folder)

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#1304]
Verify that folio goes in the same area.

**Comment by brittweinstein** [comment]
@brittweinstein put in SS Sprint.

**Comment by openstaxalina** [comment]
@Stackblocks and @helenemccarron to meet to discuss the work needed here.

**Comment by brittany-johnson** [comment]
Work completed in another issue
