### ISSUE TITLE
Answer key clean up 

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#1309]
Answer key:
Remove l6-9 in components and matching settings
l27 , 30 and 31 can be removed from settings, 42, 45, 47 in components

**Comment by lwtchu** [comment]
Specs updated in #1151

**Comment by MartaSztuka** [comment]
Changes in Answet key: headline colour, size and font, text size (as mentioned in PR #1313).
No further changes detected.
![pp1](https://user-images.githubusercontent.com/47241114/63759950-b0610300-c8be-11e9-9b61-18ec67695a7e.jpeg)
