### ISSUE TITLE
Update Theme Design Specs Doc

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#1318]
# What happened?

~https://docs.google.com/spreadsheets/d/1vW0EHvn8fZgvTxZIm9xQXsqsnIDcolqwt5rWKtx4JEY/edit#gid=1247903971~

NEW URL: https://docs.google.com/spreadsheets/d/1vW0EHvn8fZgvTxZIm9xQXsqsnIDcolqwt5rWKtx4JEY/edit#gid=1663003137

# Reproducibility Details

- **Does it also happen in an incognito window?**: 
- **Does this happen in one place, a few places, or everywhere?**:

# Environment:

- **Book(s)**:
- **URL/Server**: 
- **Location (page number, chapter/section)**:
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots

(_attach here (please clearly label what environment each screenshot came from)_)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by brittany-johnson** [comment]
- Book sections are indicated by bold large font with a colored background:
    - Intro content (table of contents, preface)
    - Main content
    - EOC
    - EOB
- Find the class for each element by opening the collection.baked.xhtml and inspecting the element
- The setting name is found in cnx-recipes/styles/templates/template1/parts/${_partname}_settings.scss and/or in cnx-recipes/styles/designs/carnival/parts/${_partname}-components.scss
    - Values are also found in these two files
- One possible workflow:
    1. Open cnx-recipes/styles/designs/carnival/parts/
    2. Starting at the top of the directory, open ${_partname}-components.scss
    3. Check each component’s _name property
        - You will know it is a component because the first like is named as such ${Part}Component
    4. Write each _name property’s value in the spreadsheet under column A (which should be an unlabeled column) and the column labeled Setting Name
        - The text under the Setting Name column should read exactly as it does in the code file, but the text under column A should be adjusted. Example: Column A - Top Titled Tables || Setting Name - TopTitledTables
    5. While checking each component for it’s _name property, also check the _properties property of the component. Is there anything written? If so:
        - Is the value of the css property a enum? If so move on to the next css property until you read the end of the list
        - If the value of the css property is not an enum, write the css property in the values column in the spreadsheet. It should be written one property per line and in a key:value format.
    6. After you are done writing all of the setting names from one file, open the file ${_partname}-shapes.scss.
        - It should correspond to the component part that you were just looking at
        - This file will show you how the different elements are nested
        - Nested elements in the spreadsheet should be indicated with the top most parent element aligned to the left in the spreadsheet and all children of the top most parent aligned to the right of the cell in the spread sheet
        - Only one level of nesting is necessary to display for the purpose of the spreadsheet
    7. Now we will get the rest of the css properties that were not written in the component file.        
        - Open cnx-recipes/styles/templates/template1/parts/${_partname}_settings.scss
        - All styled components are named as they were in the components file
        - Copy all of the css from each component and paste it in the corresponding row in the spreadsheet under the Values column

**Comment by openstaxalina** [comment]
Per discussion in scrum today, @helenemccarron, @lwtchu and I will review the documentation and close the issue once we confirm the documentation is complete.

I'll make a note to park this at our Tuesday 10/22 parking lots meeting!

**Comment by brittweinstein** [comment]
@brittweinstein these will be assigned to the Katalyst team.

**Comment by openstaxalina** [comment]
@lwtchu did you have any feedback/changes for this document (link at the top of the card)?  If not, please close this card.

**Comment by lwtchu** [comment]
EEP i forgot about this card. 

Only feedback:

Is there a place where the sizing chart/scale lives? Cause when it says v grid (1) i'm not sure what 1 means. I'm probably just missing it somewhere

**Comment by openstaxalina** [comment]
@lwtchu thanks for providing that feedback.  That is documented on the "Dropdowns" tab: https://docs.google.com/spreadsheets/d/1vW0EHvn8fZgvTxZIm9xQXsqsnIDcolqwt5rWKtx4JEY/edit#gid=685009727

We did notice that the link at the top of the issue went to the old Carnival Theme tab.  Could you review one more time with the updated link, just to confirm we can close this issue?

**Comment by lwtchu** [comment]
beautimous thank you
