### ISSUE TITLE
Regression test A&P full PDF

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1320]
@brittweinstein commented on [Mon Jul 08 2019](https://github.com/openstax/oer.exports/issues/3927)

---

@staxly[bot] commented on [Mon Jul 08 2019](https://github.com/openstax/oer.exports/issues/3927#issuecomment-509328397)

The maintainers of this repository would appreciate it if you could provide more information.

**Comment by brittweinstein** [comment]
This should be a page by page review.
