### ISSUE TITLE
Recipes & Styles make sure the text is generated in recipes, not in styles

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#1323]
Modify recipes to add os-divider, remove style component and shape AppendixMainDividerComponent

Modify recipes to add the word Appendix, remove AppendixTitleTextComponent in the sytles

**Comment by Stackblocks** [comment]
Some fallout from the change, needs further inspection.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b8b99037-11c4-427a-9bff-323490e3a40f)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7b77146b-a97a-4c7f-8b71-de4ad5dcf63b)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7afa9dbb-2a0a-4495-aac3-e0ab59545c7d)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b1b35919-44ad-4293-96af-5a0efe595e79)

**Comment by Stackblocks** [comment]
Resolved with latest update.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4c2873df-e665-4a38-a591-a206cc25e8ec)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7e134191-08c5-48f6-807a-493f9bf22279)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3f14a217-20ad-42df-a8f9-33b1f12d46ba)
