### ISSUE TITLE
Implement  full-width and full bleed in PDF 

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1331]
Implement functions for the full-width and full bleed in PDF common, so they can be used throughout the designs

This needs to be implemented in Carnival and then it will be available for all themes going forward.

**Comment by brittweinstein** [comment]
@brittweinstein put in SS Sprint.

**Comment by brittweinstein** [comment]
This will be for every title--in Carnival theme and beyond.

**Comment by openstaxalina** [comment]
We will implement the bleeds the same way this was done in the business series - example screenshot below.

This will scale the images up, **_proportionally_** (images will be expanded both vertically and horizontally).  

We know that this may necessitate some images to be replaced.  Therefore, when this issue is complete, we will do a targeted test of all splash images for all Carnival Theme books, and we will catalog images that are not suitable for the proportional expansion described above.  We will then source replacement for such images.  

(We also know that, even before this change, Katalyst has already identified some splash images for replacement.  If Katalyst prefers to discontinue testing/opening issues related to splash images until this bleeds issue is resolved, that is acceptable.) 

![Screen Shot 2019-11-25 at 11 34 07 AM](https://user-images.githubusercontent.com/7863733/69563871-8c719400-0f77-11ea-806f-6cfa6021e28e.png)

**Comment by lwtchu** [comment]
Adding additional notes here: Any color bar that hits the edge of the page should be expanded to be 0.025in off the page as well for bleeds. Chapter outline, the beige splash image caption, EOC ribbons, etc will need to be a little larger for the bleeds.

I think the images don't necessarily have to be expanded but placed 0.025in off the edge of the page until we settle on a standard splash image size.

**Comment by helenemccarron** [comment]
@wilkus27 Here is a screenshot inspecting the PDF elements and stretching them crudely to give you an idea of what we are trying to do. I hope this helps.
![2020-02-11_15-58-48](https://user-images.githubusercontent.com/8514591/74283704-f7fe0e80-4ce7-11ea-9464-d555929b3a8b.png)

**Comment by lwtchu** [comment]
Might I add that, we can refrain from stretching the image, by simply _placing it_ off the page a little.

**Comment by wilkus27** [comment]
FINAL DECISION: use streched image

**Comment by wilkus27** [comment]
### Changes to provide to Theme Design Specs

#### Shape: `ChapterIntroShape`

_Component:_ `Outline`
_Properties:_ 
```
 margin: 0 -1.2rem 0 0,
```
_Component:_ `SplashImg`
_Properties:_ 
```
 width: 8.15in,
```
_Component:_ `SplashImgMedia`
_Properties:_ 
```
 width: 7.65in,
```
_Component:_ `SplashFigureBg`
_Properties:_ 
```
 width: 8.65in;
 margin-left: -1.15in;
```
_Component:_ `SplashCaptionBg`
_Properties:_ 
```
 width: 8.8in;
 margin-left: -1.15in;
```

#### Shape: `ChapterIntroWithObjectivesShape`

_Component:_ `SplashImg`
_Properties:_ 
```
 width: 8.15in,
```
_Component:_ `SplashImgMedia`
_Properties:_ 
```
 width: 7.65in,
```
_Component:_ `SplashFigureBg`
_Properties:_ 
```
 width: 8.65in;
 margin-left: -1.15in;
```
_Component:_ `SplashCaptionBg`
_Properties:_ 
```
 width: 8.8in;
 margin-left: -1.15in;
```

#### Shape: `FullWidthChapterIntroShape`

_Component:_ `SplashImg`
_Properties:_ 
```
 width: 8.15in,
```
_Component:_ `SplashImgMedia`
_Properties:_ 
```
 width: 7.65in,
```
_Component:_ `SplashFigureBg`
_Properties:_ 
```
 width: 8.65in;
 margin-left: -1.15in;
```
_Component:_ `SplashCaptionBg`
_Properties:_ 
```
 width: 8.8in;
 margin-left: -1.15in;
```

**Comment by wilkus27** [comment]
I think there is no settings in Theme Design Specs related with bands in EOC and in EOB. So I add here setting from Chemistry. In other books they are the same, except color, which is book specific.

### EOC left 
 **left middle** 
```
    content: " ";
    border-left: 3.7rem solid #00829B;
    padding: 1.2rem 0 1.2rem 1.2rem;
    margin: -1.2rem 0 -1.2rem -1.2rem; 
```
 **top-left-corner** 
```
    content: " ";
    border-left: 3.7rem solid #00829B;
    padding: 1.2rem 0 1.2rem 1.2rem;
    margin: -1.2rem 0 -1.2rem -1.2rem; 
```
  **bottom-left-corner** 
```
    content: " ";
    border-left: 3.7rem solid #00829B;
    padding: 1.2rem 0 1.2rem 1.2rem;
    margin: -1.2rem 0 -1.2rem -1.2rem; 
```
  **left-bottom** 
```
    content: " ";
    border-left: 3.7rem solid #00829B;
    padding: 1.2rem 0 1.2rem 1.2rem;
    margin: -1.2rem 0 -1.2rem -1.2rem; 
```
  **left-top** 
```
    content: " ";
    border-left: 3.7rem solid #00829B;
    padding: 1.2rem 0 1.2rem 1.2rem;
    margin: -1.2rem 0 -1.2rem -1.2rem; 
```

### EOC right 
  **right-middle** 
```
    content: " ";
    border-right: 3.7rem solid #00829B;
    padding: 1.2rem 1.2rem 1.2rem 0;
    margin: -1.2rem -1.2rem -1.2rem 0; 
```
  **top-right-corner** 
```
    content: " ";
    border-right: 3.7rem solid #00829B;
    padding: 1.2rem 1.2rem 1.2rem 0;
    margin: -1.2rem -1.2rem -1.2rem 0; 
```
  **bottom-right-corner** 
```
    content: " ";
    border-right: 3.7rem solid #00829B;
    padding: 1.2rem 1.2rem 1.2rem 0;
    margin: -1.2rem -1.2rem -1.2rem 0; 
```
  **right-bottom** 
```
    content: " ";
    border-right: 3.7rem solid #00829B;
    padding: 1.2rem 1.2rem 1.2rem 0;
    margin: -1.2rem -1.2rem -1.2rem 0; 
```
  **right-top** 
```
    content: " ";
    border-right: 3.7rem solid #00829B;
    padding: 1.2rem 1.2rem 1.2rem 0;
    margin: -1.2rem -1.2rem -1.2rem 0; 
```

### EOC blank 
  **left-middle** 
```
    content: none;
    border: none; 
```
  **top-left-corner** 
```
    content: none;
    border: none; 
```
  **bottom-left-corner** 
```
    content: none;
    border: none; 
```
  **left-bottom** 
```
    content: none;
    border: none; 
```
  **left-top** 
```
    content: none;
    border: none; 
```
  **right-middle** 
```
    content: none;
    border: none; 
```
  **top-right-corner** 
```
    content: none;
    border: none; 
```
  **bottom-right-corner** 
```
    content: none;
    border: none; 
```
  **right-bottom** 
```
    content: none;
    border: none; 
```
  **right-top** 
```
    content: none;
    border: none; 
```

The same settings for **Appendix** and **EOB**.

**Comment by lwtchu** [comment]
@wilkus27 i couldn't find ChapterIntroWithObjectivesShape on the theme doc - do you need me to add it?

**Comment by wilkus27** [comment]
Yes, please. This shape is used only in Anatomy.

### Shape: `ChapterIntroWithObjectivesShape`

_Component:_ `SplashFigureWrapper`
_Properties:_
```
margin-bottom: 2rem,
```
_Component:_ `SplashFigure`
_Properties:_
```
position: relative,
margin: 0,
```
_Component:_ `SplashFigureBg`
_Properties:_
```
  content: '';
  background-color: #00819A;
  position: absolute;
  height: 100%;
  width: 8.65in;
  margin-left: -1.15in;
  z-index: -1;
  box-sizing: border-box;
  padding: inherit;
  top: 0; 
```
_Component:_ `SplashImgMedia`
_Properties:_
```
  line-height: 0;
  height: 100%;
  display: flex;
  width: 7.65in;
  justify-content: flex-end;
```
_Component:_ `SplashImg`
_Properties:_
```
  width: 8.15in;
```
_Component:_ `SplashCaption`
_Properties:_
```
        position: relative,
        padding-top: 1rem,
        padding-bottom: 2rem,
```
_Component:_ `SplashCaptionBg`
_Properties:_
```
  content: '';
  background-color: #EEEAE0;
  position: absolute;
  height: 100%;
  width: 8.8in;
  margin-left: -1.15in;
  z-index: -1;
  box-sizing: border-box;
  padding: inherit;
  top: 0; 
```
_Component:_ `FigureNum`
_Properties:_
```
  font-family: Muli;
  font-weight: bold;
  color: #C31427;
```
_Component:_ `FigureLabel`
_Properties:_
```
  font-family: Muli;
  font-weight: bold;
  color: #C31427;
```
_Component:_ `FigureTitle`
_Properties:_
```
 font-family: Muli;
 font-weight: bold;
```
_Component:_ `Caption`
_Properties:_
```
 font-family: IBM Plex Sans, sans-serif; 
```
_Component:_ `NoPropIntroBody`
_Properties:_
```
 empty
```
_Component:_ `Objectives`
_Properties:_
```
 empty
```
_Component:_ `ObjectivesTitle`
_Properties:_
```
        font-family: Muli;
  font-weight: bold;
  text-transform: uppercase;
  font-size: 1.44rem;
  line-height: 1.5rem;
  color: #00819A;
```
_Component:_ `ObjectivesPara`
_Properties:_
```
  color: #00819A;
  font-family: IBM Plex Sans, sans-serif;
  font-size: 1.2rem;
  line-height: 1.5rem;
  font-style: italic;
```
_Component:_ `ObjectivesList`
_Properties:_
```
        margin-bottom:v-grid(2),
        margin-left: h-grid(2),
        padding-left: 0,
        font-size: font-scale(0),
        line-height: line-height(0),
```
_Component:_ `ObjectivesListItem`
_Properties:_
```
  color: #000000;
  font-family: Muli, sans-serif;
  padding: 0;
```
_Component:_ `ObjectivesListDot`
_Properties:_
```
  color: #00819A;
```
_Component:_ `IntroContent`
_Properties:_
```
  empty
```
_Component:_ `IntroContentHeader`
_Properties:_
```
  float: left;
  font-size: 12px;
  text-transform: uppercase;
  margin: 0 0.5rem 0 0;
  font-weight: 700;
```

**Comment by lwtchu** [comment]
Added. Thanks~

**Comment by lwtchu** [comment]
![Screen Shot 2020-02-20 at 11 43 19 AM](https://user-images.githubusercontent.com/11299125/74962810-40978500-53d6-11ea-9c10-9a606510f6a7.png)
![Screen Shot 2020-02-20 at 11 43 05 AM](https://user-images.githubusercontent.com/11299125/74962812-41301b80-53d6-11ea-95e7-236488bd4688.png)
![Screen Shot 2020-02-20 at 11 42 58 AM](https://user-images.githubusercontent.com/11299125/74962813-41301b80-53d6-11ea-9fd1-9d57a7899e44.png)
![Screen Shot 2020-02-20 at 11 42 52 AM](https://user-images.githubusercontent.com/11299125/74962814-41301b80-53d6-11ea-8983-5bcf73f78439.png)
![Screen Shot 2020-02-20 at 11 42 49 AM](https://user-images.githubusercontent.com/11299125/74962815-41c8b200-53d6-11ea-9b8f-39659ab36425.png)
![Screen Shot 2020-02-20 at 11 42 45 AM](https://user-images.githubusercontent.com/11299125/74962816-41c8b200-53d6-11ea-81d7-de25bc2e7fe2.png)
![Screen Shot 2020-02-20 at 11 34 20 AM](https://user-images.githubusercontent.com/11299125/74962818-41c8b200-53d6-11ea-98b0-4380041b7f15.png)

VERIFIED
