### ISSUE TITLE
microbiology: boxed features

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1340]
See #1087 for specs

Title: Clinical Focus (opener)
Class: `microbiology clinical-focus-opener` ** we'll need to see if we still need it to "snap" to the bottom of the page.
Color: #0074BC

Title: Clinical Focus
Class: `microbiology clinical-focus`
Color: #0074BC 

Title: Eye on Ethics
Class: `microbiology eye-on-ethics`
Color: #00829B
Icon in the bottom right corner of feature with 0.5rem padding: https://drive.google.com/open?id=1CXCYLiPiv3xgh9Hz_P9NL9ma92B_TTqp 

Title: Disease Profile
Class: `microbiology disease-profile`
Color: #1E9575 

** Please make sure the registered trademark symbol is in superscript.

**Comment by brittany-johnson** [comment]
<img width="1792" alt="Screen Shot 2019-09-25 at 1 24 21 PM" src="https://user-images.githubusercontent.com/24909007/65628814-d51cc900-df97-11e9-88d1-5298fcf83131.png">
<img width="1792" alt="Screen Shot 2019-09-25 at 1 23 19 PM" src="https://user-images.githubusercontent.com/24909007/65628815-d51cc900-df97-11e9-9eb9-d75bb189f28b.png">

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/08c29702-15e0-42db-a759-ce89f1621020)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6158ff5d-adf0-45d0-8ca2-44e9a51df7ec)
