### ISSUE TITLE
microbiology: iconned features

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1341]
See #1088 for specifications

Title: Micro Connections
Class: `microbiology micro-connection`
Color: #0DC0DC
Icon: https://drive.google.com/open?id=1z3nm9jswlV-pNb5v7UOlFwXZIAY1SKbZ

Microbiology also has Link to Learning (`microbiology link-to-learning`) & Check Your Understanding (`microbiology check-your-understanding`) which should be the same as it is in the other carnival theme titles. 

@helenemccarron no answer needed now - but let us know when you're ready for us to remove the words microbiology from the class in the Link to Learning and Check Your Understanding features.

**Comment by brittany-johnson** [comment]
<img width="1792" alt="Screen Shot 2019-09-25 at 1 00 33 PM" src="https://user-images.githubusercontent.com/24909007/65627222-828ddd80-df94-11e9-8785-ef9d9c336d83.png">

**Comment by lwtchu** [comment]
TWO SMOL THINGS:
Can it be
CHECK YOUR
UNDERSTANDING 
the your with the check

and thent he list inside check your understanding, the bullet should be within the feature.

**Comment by brittany-johnson** [comment]
<img width="741" alt="Screen Shot 2019-10-14 at 1 09 54 PM" src="https://user-images.githubusercontent.com/24909007/66773126-f7fa1900-ee83-11e9-95cd-585d6f40c64e.png">

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1dc4c99e-b44f-477f-bf82-a8a1335206cb)

Getting the bullet within the feature and the "Check Your" grouped together over "Understanding", but the icon and color have changed for the feature. Was that intentional, @brittany-johnson ?
