### ISSUE TITLE
college success: change exhibit to figure

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1345]
<img width="914" alt="Screen Shot 2019-09-03 at 2 41 17 PM" src="https://user-images.githubusercontent.com/11299125/64203392-eb33df80-ce58-11e9-827b-fd7388f091e4.png">

For figures, please change `Exhibit` to `Figure`.

**Comment by brittany-johnson** [comment]
"exhibit" was in the intro business template, once a new recipe was applied, didn't have to do anything (yay!)
![Screen Shot 2019-10-18 at 1 56 22 PM](https://user-images.githubusercontent.com/24909007/67120532-17a87e80-f1af-11e9-9c51-c3059c38d06b.png)
![Screen Shot 2019-10-18 at 1 56 12 PM](https://user-images.githubusercontent.com/24909007/67120533-17a87e80-f1af-11e9-9bf0-44798f0a87ae.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/12f04727-ef96-4f95-99de-e519050353fd)
