### ISSUE TITLE
college success: icon notes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1348]
### Notes
FOLDER FOR ALL ICONS: https://drive.google.com/drive/u/0/folders/19aQqJYvdG3BQssTR3py-EbMzGhbUtcAA

- Please upload BOTH the .ai and .svg file into the folder linked above.
- The file names should correspond with the feature names. 
- Color palette is noted here #1346 
- All existing business icons can be seen here for aesthetic references, scroll all the way down: https://docs.google.com/document/d/1TBAsWe2rsI97QpE6iHWo_vlsFIL1NeEbjGGjQ0COfy0/edit# 

### Feature specs for features with icon changes ** ~NEED UX WORK~ 
Title: What Students Say
Class: `what-students-say`
Color of the bar: #D34D32
Color of the text for feature title: #000000
Color of the box: #D6D9DD
Icon description: 3 people with a with a lightbulb
Link to Icon: https://drive.google.com/open?id=1cVNMwtvflHmSD0KwbhmZGUPur0SJiniz
~Changes for the icon: Change the guy's shirt color to #344456, change the lightbulb to a speech bubble. Does he have dimples - if so please try to remove?~ DONE

Title: Activity
Class: `activity` ** SHOULD WE MAKE THIS CLASS TWO WORDS ** 
Color of the bar: #D34D32
Color of the text for the feature title: #000000
Color of the box: #D6D9DD
Icon description: woman with paper behind her and she's saying a recycle symbol
Link to icon: https://drive.google.com/open?id=1_Tq-b-YfNiNtZoVvOJnYmtVw0e_KxfPM
~Changes for the icon: Change the girl's shirt to #24739E, remove the recycle symbol out of the speech bubble~ DONE

### Feature specs for features without icon changes (reuses from other business titles)
Title: Get Connected
Class: `get-connected`
Existing business feature: `expanding-around-globe`
Icon description: globe 
Link to icon if you need it: https://drive.google.com/open?id=1Lx-xt_fATDmu2CbY0w0ZIeZeXpht79DU

Title: Analysis Question
Class: `analysis-question`
Existing business feature: `ethics-in-practice`
Icon description: man at a forked road
Link to icon if you need it: https://drive.google.com/open?id=1uOmSGM3ocVpYm7egdszd3rj8wQjdvNm6

Title: Application
Class: `application` ** SHOULD WE MAKE THIS TWO WORDS??? **
Existing business feature: `concept-check`
Icon description: a checkmark in a circle
Link to icon if you need it: https://drive.google.com/open?id=1K6aMpeEg0i_KxtVvu4NoEi2_VROXCI7V

**Comment by victoria-cooke** [comment]
@lwtchu Design updates have been made and dropped into the folder. Didn't see any dimples on the gentleman below. If I missed them, please circle them so I can update.

![activity](https://user-images.githubusercontent.com/45772258/65061414-7d4ee400-d93f-11e9-8d2d-52aa14a3a5e1.jpg)
![what-students-say](https://user-images.githubusercontent.com/45772258/65061416-7d4ee400-d93f-11e9-8028-bbeb3043649e.jpg)

**Comment by lwtchu** [comment]
@victoria-cooke looks good thank you ~

**Comment by openstaxalina** [comment]
closing since this seems to be done.  cc @victoria-cooke @lwtchu

**Comment by lwtchu** [comment]
If you are looking for the TBD card, it is here #1415
