### ISSUE TITLE
college success: student profile note

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1349]
<img width="960" alt="Screen Shot 2019-09-03 at 3 46 37 PM" src="https://user-images.githubusercontent.com/11299125/64207334-0a833a80-ce62-11e9-99de-49fb2c7ac202.png">

- Reusing the  `exploring-business-careers` feature
- Change the title to `Student Profile`
- New class: `student-profile`
- Enjoy the troll

**Comment by brittany-johnson** [comment]
<img width="1678" alt="Screen Shot 2019-10-23 at 1 58 41 PM" src="https://user-images.githubusercontent.com/24909007/67425224-3f2b8c80-f59d-11e9-99c7-de210fdfe927.png">

**Comment by Stackblocks** [comment]
I dislike looking at this troll, but the student profile is working correctly. 

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ff5b2bb9-dfec-4548-89ff-473312198a60)
