### ISSUE TITLE
college success: end of chapter sections

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1353]
End of Chapter collating sections:

Title: Chapter Summary
Class: `section-summary`
Icon description: 3 pages of notes in a stack
Reuses icon from EOC section: `section-summary`
Changes: Change the title from "Summary of Learning Outcomes" to "Section Summary"

Title: Career Connection
Class: `career-connection`
Icon description: magnifying glass over two pieces of paper
Reuses icon from EOC section: `ethics-activity` 

Title: Rethinking
Class: `rethinking` 
Icon description: lit (it's lit!) lightbulb
Reuses icon from EOC section: `critical-thinking` 

Title: Where do you go from here?
Class: `where-go`
Icon description: mountain with arrow
NEW ICON: https://drive.google.com/open?id=1jfgkq76Yfg-BnbvczVPMoCCPy0RZxXHl

Title: TBD (???)
Class: ??? 
Icon description: multiple choice questions selection
Reuses icon: `multiple-choice`
Icon link: https://drive.google.com/open?id=1KcgEIubfUfQomYbwheNy3ujwJxMZjIZM

**Comment by brittany-johnson** [comment]
Section Summary: 
![Screen Shot 2019-10-18 at 1 30 24 PM](https://user-images.githubusercontent.com/24909007/67118900-84ba1500-f1ab-11e9-877e-36436625707a.png)

Where do you go from here?: 
![Screen Shot 2019-10-18 at 1 41 17 PM](https://user-images.githubusercontent.com/24909007/67119530-fcd50a80-f1ac-11e9-85a7-d15319eda21a.png)


Career Connection
![Screen Shot 2019-10-18 at 1 34 38 PM](https://user-images.githubusercontent.com/24909007/67119098-0dd14c00-f1ac-11e9-90b8-5482f95ac45f.png)

Rethinking
![Screen Shot 2019-10-18 at 1 40 26 PM](https://user-images.githubusercontent.com/24909007/67119479-dd3de200-f1ac-11e9-9189-f03c6ca994aa.png)

**Comment by brittany-johnson** [comment]
https://github.com/openstax/cnx-recipes/pull/1478

**Comment by Stackblocks** [comment]
Formed as specified with updated version of content / code, further styling to come.

![2019-10-21_13-37-53.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/9fd0fe40-fff2-4a75-83d0-401fcad2dbfa)
