### ISSUE TITLE
college success: chapter/splash opener doodad

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1354]
![Screen Shot 2019-09-04 at 1 23 28 PM](https://user-images.githubusercontent.com/11299125/64280673-3d3b3a80-cf17-11e9-9866-7104792f5b01.png)

New doodad for this thing for _College Success_

Existing doodad is around: 48 px x 127.5 px

### To do for TBD
- [ ] Replace existing doodad with the new one: https://drive.google.com/open?id=18wQDFwiYf0cYpUESmuD6xsZqorupthK9

From Anthony: icon should be something that conveys a college - so college-like buildings etc

Existing references: https://drive.google.com/drive/u/0/folders/19aQqJYvdG3BQssTR3py-EbMzGhbUtcAA 

### To do for UX
- [x] Merge the two existing references
- [x] Remove the scales in the circle
- [x] Maybe add a flag on the colosseum looking building 
- [x] Make the other rectangular buildings a little shorter
- [x] Add trees
- [x] This one can be more colorful and robust. We had to do something boring for business series due to the ~ seriousness of the title.
- [x] Please put .ai and .svg icon into the folder above when you're done

**Comment by victoria-cooke** [comment]
@lwtchu Let me know if this is what you had in mind:

![college-success-splash](https://user-images.githubusercontent.com/45772258/65078869-8fdb1480-d963-11e9-8bcc-77290b9d9e2e.jpg)

**Comment by lwtchu** [comment]
@victoria-cooke sent to Anthony for some initial feedback first.

**Comment by lwtchu** [comment]
@victoria-cooke can you make the buildings on the right a little more uniformed in color with the other two large buildings? think rice and all of their beige bricks. and that should be it!

**Comment by victoria-cooke** [comment]
@lwtchu Let me know if this works:

![college-success-splash-2](https://user-images.githubusercontent.com/45772258/65532869-3bcfb300-dec2-11e9-8f04-9624a8ccdd0e.jpg)

**Comment by lwtchu** [comment]
@victoria-cooke this looks good~ upload away! thank you for all of your help.

**Comment by victoria-cooke** [comment]
@lwtchu Uploaded. No problem!

**Comment by openstaxalina** [comment]
closing since this seems to be done.  cc @victoria-cooke @lwtchu

**Comment by lwtchu** [comment]
If you are looking for the TBD card it is here #1414
