### ISSUE TITLE
 Equations

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1359]
Some of equations look messy (pdf was mathified).
![Screenshot from 2019-09-06 14-43-56](https://user-images.githubusercontent.com/47241114/64428829-00a54580-d0b5-11e9-9d8c-2dda773b569f.png)
![Screenshot from 2019-09-06 13-48-05](https://user-images.githubusercontent.com/47241114/64428835-04d16300-d0b5-11e9-9b8f-f05b12e6b6e6.png)
![Screenshot from 2019-09-06 12-46-01](https://user-images.githubusercontent.com/47241114/64428881-1b77ba00-d0b5-11e9-8778-cfe8bdc94e57.png)

**Comment by brittweinstein** [comment]
@MartaSztuka could you please take another look at this and confirm that it is still occurring?

**Comment by MartaSztuka** [comment]
@brittweinstein Some of equations are still looking weird or cutting lines.
![Screenshot from 2019-09-24 09-51-46](https://user-images.githubusercontent.com/47241114/65492639-8dbc0d00-deb1-11e9-82c6-20038cbb1eae.png)

![Screenshot from 2019-09-24 09-54-31](https://user-images.githubusercontent.com/47241114/65492503-58afba80-deb1-11e9-9b98-c07c3bba1bbd.png)
![Screenshot from 2019-09-24 09-56-46](https://user-images.githubusercontent.com/47241114/65492683-a7f5eb00-deb1-11e9-9912-0b6b62a49399.png)

**Comment by brittweinstein** [comment]
@MartaSztuka could you check if the 'mathify' process has been run and see if this is still happening?

**Comment by MartaSztuka** [comment]
@brittweinstein Yes, it was mathified, issue still occurs.

**Comment by MartaSztuka** [comment]
@brittweinstein Yes, it was mathified, issue still occurs.

**Comment by wilkus27** [comment]
@brittweinstein As I understand at this moment PDFs are generated from files `baked.xhtml` not from `mathified.xhtml` files, so we can't see repaired equations  in PDF.  @helenemccarron am I right?

![image (12)](https://user-images.githubusercontent.com/40228854/67387388-13a5a380-f597-11e9-82bc-66518b0c0cba.png)

**Comment by MartaSztuka** [comment]
Book was mathified, following Alan's instructions.
![Screenshot from 2019-10-29 10-04-01](https://user-images.githubusercontent.com/47241114/67753252-bb5a2000-fa34-11e9-9a51-36476e24c39c.png)
![Screenshot from 2019-10-29 10-03-45](https://user-images.githubusercontent.com/47241114/67753253-bbf2b680-fa34-11e9-877e-bfd2c9610a6f.png)
![Screenshot from 2019-10-29 10-03-34](https://user-images.githubusercontent.com/47241114/67753255-bbf2b680-fa34-11e9-8185-e235cae41715.png)

**Comment by openstaxalina** [comment]
@brittany-johnson could you clarify what markup CMs need to investigate here?

**Comment by brittany-johnson** [comment]
If I'm remembering correctly, I think we wanted to see if the letters in front of the equations could be created differently. Right now, the letter (a), equation, and a span with the class newline are all in a para tag. The letter (a) is not in its own tag and for equations that differ in height, like in the first screenshot from chapter 15 in the answer key, we have no way to align it to the letter without affecting all other equations in the answer key.

I *think* this is along the lines of what we discussed.

**Comment by openstaxalina** [comment]
CMs will try removing `equation` in 1 or 2 places on katalyst01 ask BrittanyJ generate a baked styles PDF with the updated markup.  See if this resolves the issue.   If this does not work, we need to determine what kind of tag we could put "a" in.

**Comment by brittweinstein** [comment]
Let's not test this until the math work goes out later this sprint--it may be resolved.

**Comment by brittweinstein** [comment]
@MartaSztuka could you see if this is still occurring after all of the math fixes were done last month?

**Comment by MartaSztuka** [comment]
Equations look way better now.
Chemistry 2e
![Screenshot from 2020-02-07 11-11-51](https://user-images.githubusercontent.com/47241114/74021012-0cb26d80-499b-11ea-92dd-df370fdfd33e.png)
![Screenshot from 2020-02-07 11-11-14](https://user-images.githubusercontent.com/47241114/74021015-0de39a80-499b-11ea-9134-755bb020aa34.png)
Chemistry af
![Screenshot from 2020-02-07 11-31-49](https://user-images.githubusercontent.com/47241114/74022376-ab3fce00-499d-11ea-9926-8f50f3a0bb59.png)

**Comment by lwtchu** [comment]
<img width="789" alt="Screen Shot 2020-02-11 at 3 43 51 PM" src="https://user-images.githubusercontent.com/11299125/74282189-54136380-4ce5-11ea-90e8-2cd59f1c4b1c.png">

Just a question - is the 3rd answer (3. There is no change. A solid has an activity of 1) is not starting on a new line. Can that be fixed? I have a screenshot from teh current oer.exports pdf

**Comment by brittweinstein** [comment]
@MartaSztuka would you be able to take a look and see if Larissa's comment above is still occurring?

**Comment by MartaSztuka** [comment]
@brittweinstein Yes it does.
![Screenshot from 2020-02-12 17-18-16](https://user-images.githubusercontent.com/47241114/74354494-bccd0f80-4dbb-11ea-855a-a4ff561f7560.png)

**Comment by paulinaszczucinska** [comment]
@MartaSztuka please check if it still occurs and update the issue

**Comment by MartaSztuka** [comment]
It's still an issue
![Screenshot from 2020-03-18 17-08-47](https://user-images.githubusercontent.com/47241114/76981702-403dcb80-693b-11ea-9d4b-29ceb1b89ea8.png)

**Comment by wilkus27** [comment]
The question is what exactly we want to change. Those equations have two lines and list items display at the center of the equation:

![image](https://user-images.githubusercontent.com/40228854/77325052-ee6cbb00-6d17-11ea-8eaf-9c91f737d335.png)

@lwtchu those equations should display next to each other or maybe like now, but start at the same line as list item or in some another way?

**Comment by lwtchu** [comment]
They should be on their own line.  The answers currently appear one after the other.

**Comment by wilkus27** [comment]
@lwtchu this is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/77412731-90df7980-6dbe-11ea-96d3-c13bdf477406.png)

Is it ok? I'm afraid about one think, after those changes book has 16 more pages.

**Comment by lwtchu** [comment]
@wilkus27 i think for this title we can't have the answer key bundled up due to the nature of the solutions. it gets really confusing. this is fine

**Comment by MartaSztuka** [comment]
Chemistry 2e
![Screenshot from 2020-04-16 10-53-45](https://user-images.githubusercontent.com/47241114/79435936-905a8d00-7fd0-11ea-985b-6019964d2e58.png)
Chemistry AF
![Screenshot from 2020-04-16 11-16-14](https://user-images.githubusercontent.com/47241114/79438382-be8d9c00-7fd3-11ea-9f1c-af6fcb3e683d.png)
