### ISSUE TITLE
library wide: links/url styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1360]
I don't think there's a card that capture this. 

Color: #027eb5
Treatment: bottom border

In a shaded note (only Business Series!): #026aa1 with bottom border

**Comment by MartaSztuka** [comment]
Link's colour changed.
![Screenshot from 2019-09-20 16-18-51](https://user-images.githubusercontent.com/47241114/65334281-6966e480-dbc2-11e9-8d5c-d5beb95e1fdd.png)
