### ISSUE TITLE
Refactor the EOC components and shapes

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1365]
@helenemccarron commented on [Fri Sep 06 2019](https://github.com/openstax/oer.exports/issues/3939)

- [x] Remove all the repeating components such as $Keyterm_Container:(...) and replace them with a new generic container component and nesting the shapes for the named EOC components inside of it in the shapes
- [ ] Rework the component for key equations to match a table markup, not a list (see Larissa's related issue)
- [x] Properly nest components in shapes
- [x] Remove extra padding, use margin whenever possible

**Comment by tomjw64** [comment]
Verification: No significant visible changes. Padding between sections being smaller is acceptable if it occurs

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8afb85ba-a862-4058-bce1-30fad31ef729)
