### ISSUE TITLE
Clean up Index

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1366]
- [ ] Clean up required/optional/hard coded
- [ ] Remove `pointer-events: none`
- [ ] Look into font-weight: normal everywhere, is it necessary? Should it be removed

**Comment by MartaSztuka** [comment]
Tested on Chemistry, looks ok.
![Screenshot from 2019-10-10 11-25-15](https://user-images.githubusercontent.com/47241114/66557515-4d67ba80-eb52-11e9-9351-f10073ee8a42.png)
