### ISSUE TITLE
Clean up tables

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1369]
- [ ] Fix all REQUIRED/OPTIONAL, most should be required to allow for maximum component re-usability, few should be optional if they need to be omitted.
- [ ] Remove unused CaptionText component

**Comment by helenemccarron** [comment]
@brittany-johnson can you also verify that tables have v-grid(1) applied to them as per https://github.com/openstax/cnx-recipes/issues/1344?

**Comment by brittany-johnson** [comment]
The tables **should** look the same 
fingers crossed

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ea50ea93-6abe-4f71-812d-80010ddd8e0c)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5b1ec007-7663-47bf-8bd7-9230a427115b)
