### ISSUE TITLE
Add polish translation for table of contents string

### ISSUE THREAD

**Issue by tomjw64** [openstax/cnx-recipes#1374]
Depends on https://github.com/openstax/cnx-recipes/pull/1373. Related config option is `$Config_TocTitleWord` in `recipes/locale/pl/_common-stuff.scss`

**Comment by wilkus27** [comment]
For now release flag `toc-title-word` shoudn't be enabled for Polish U-physics, so this change doesn't have impact on recipes or style output.

**Comment by MartaSztuka** [comment]
Qa testing isn't necessary.
