### ISSUE TITLE
Fix os-number duplication in folio

### ISSUE THREAD

**Issue by tomjw64** [openstax/cnx-recipes#1375]
![folio-number](https://user-images.githubusercontent.com/1285308/64630243-4f572600-d3ba-11e9-80d4-e0648afdf3c8.png)

**Comment by tomjw64** [comment]
Verification: Folio should just have "Chapter 1" not "Chapter Chapter 1"

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b60b5410-e9c4-4c5f-bbfd-64f080bcb7c8)
