### ISSUE TITLE
Bug: Modules not loading on cnx

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#1386]
# Scenario
Some modules not loading after migrating them from content03

# Steps to Reproduce
Navigate to https://cnx.org/contents/Rko_umjB@3.2:KXdc8GaO/2-3-Arbitration 

This module, as well as various others in this collection/book, do not ever load. 

* **How many times were you able to reproduce the issue?** 
Happens every time for select modules. 

* **Images or Screenshots Included:** [ ] Yes  [ x] No  (_attach below_)

# Environment:

* **Medium**: [ ] REX [ ] PDF  [ x] cnx.org  
* **Instance**: [x ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ x] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ x] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact

* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan 

# Acceptance Criteria

**Comment by openstaxalina** [comment]
@yblock where did you get the URL that you linked to above?

I noticed that you have the collection at version 3.2 in that URL, but the Business Law collection on production doesn't have a version 3.2.  It only has up to version 2.3:

![Screen Shot 2019-09-16 at 12 53 20 PM](https://user-images.githubusercontent.com/7863733/64981100-faffea80-d880-11e9-9a45-fb48717aecea.png)


I can get section 2.3 Arbitration to load in the latest version of the collection (2.3): https://cnx.org/contents/Rko_umjB@2.3:KXdc8GaO@3/2-3-Arbitration

**Comment by yblock** [comment]
i navigated there from searching for the book in cnx, interesting.
