### ISSUE TITLE
anatomy: add Preface styling

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1392]
Preface in Anatomy should be styled with specs from carnival theme : https://github.com/openstax/cnx-recipes/issues/1073.

**Comment by brittweinstein** [comment]
@openstaxalina will investigate but it is possible we will need to wait for @lwtchu to provide input when she returns next week.

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/596c3d3f-7e81-4cdd-bfbf-04f853e32463)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d4e6c84e-2918-4818-81bf-d8a9e05ef2be)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/58ab99a6-e9e8-4d8c-bcf8-13452a732b26)
