### ISSUE TITLE
anatomy: add style for module headers

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1396]
Module headers in Anatomy should be styled with specs from https://github.com/openstax/cnx-recipes/issues/1286

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/18f0692c-35ef-4656-8222-f1ecdcdc1643)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0e760db2-929e-4ca2-8979-d76f5def8afe)
