### ISSUE TITLE
anatomy: add style to EOC sections

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1401]
Eoc sections in Anatomy should be styled with Carnival Theme specs https://github.com/openstax/cnx-recipes/issues/1085, https://github.com/openstax/cnx-recipes/issues/1074 and https://docs.google.com/spreadsheets/d/1piXDN2me_xyD2CtqODOk9irW69z4JflMwpOf0KV-Lak/edit#gid=1327731354&range=A26:B26

**Comment by MartaSztuka** [comment]
EOC styled according to instructions.
![Screenshot from 2019-10-07 16-42-40](https://user-images.githubusercontent.com/47241114/66322114-e95eaf80-e921-11e9-9178-299afe94584d.png)
![Screenshot from 2019-10-07 16-42-21](https://user-images.githubusercontent.com/47241114/66322115-e95eaf80-e921-11e9-9c51-ddb2431aef92.png)
![Screenshot from 2019-10-07 16-42-06](https://user-images.githubusercontent.com/47241114/66322116-e95eaf80-e921-11e9-828a-d2a6cadb5a06.png)
