### ISSUE TITLE
placeholder: biology unit toc

### ISSUE THREAD

**Issue by tomjw64** [openstax/cnx-recipes#1413]

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c8adf9a6-2e2d-417b-8504-2f965411a541)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/daa294b1-1c8c-47b6-8ae2-62920c0ed872)
