### ISSUE TITLE
college success: implementing chapter/splash opener doodad

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1414]
Linking #1354 
![Screen Shot 2019-09-04 at 1 23 28 PM](https://user-images.githubusercontent.com/11299125/64280673-3d3b3a80-cf17-11e9-9866-7104792f5b01.png)

New doodad for this thing for _College Success_

Replace existing doodad with the new one: https://drive.google.com/open?id=18wQDFwiYf0cYpUESmuD6xsZqorupthK9

**Comment by openstaxalina** [comment]
Issue moved to [openstax/oer.exports #3954](https://github.com/openstax/oer.exports/issues/3954) via [**ZenHub**](https://www.zenhub.com/)
