### ISSUE TITLE
Regression Test Full Chemistry PDFs

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1417]
Helene will fetch  the data from staging for Marta to test. This is raw data. using the CLI, Marta will bake, assemble and generate the PDF for testing. Helene is available for help.

**Comment by openstaxalina** [comment]
We are ready to regression test Chemistry 2e and Chemistry Atoms First 2e PDFs, with the following known issues:

**Comment by openstaxalina** [comment]
@openstaxalina to provide a list of the unique modules in Chemistry Atoms First 2e.

Every page of Chemistry 2e should be tested.

Only the unique pages/modules in Chemistry Atoms First 2e need to be tested.

**Comment by openstaxalina** [comment]
@MartaSztuka this document has a list of the 27 unique modules in Chemistry Atoms First 2e.  These modules need to be tested.  All other Chemistry Atoms First 2e modules do NOT need to be tested.

[https://app.zenhub.com/files/49744755/be10d6c6-95f8-44cc-8386-39019f53f764/download](https://app.zenhub.com/files/49744755/be10d6c6-95f8-44cc-8386-39019f53f764/download)

**Comment by helenemccarron** [comment]
Per Alina, the data is suitable on easyvm5. @MartaSztuka you can download Chemistry 2e using 
`docker-compose run --rm fetch-book chemistry`.

In order to download Chemistry 2e Atom First, you will have to switch to the following branch: 
`chem2e-data` and use 
`docker-compose run --rm fetch-book chemistry2af`

**Comment by brittweinstein** [comment]
@MartaSztuka is this complete?

**Comment by MartaSztuka** [comment]
@brittweinstein I've finished regression testing and created issues, they are in 'hidden' on Zenhub, with 'regression testing' labels.
