### ISSUE TITLE
Captions too lightly colored in Statistics

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#1422]
# What happened?
While testing Statistics I noticed the table captions are so light it's difficult to read. 

# Reproducibility Details
You can find this content on Table 1.8 -  https://content04.cnx.org/contents/8fd0axzV@4.1:km7EgaMp@2/1-2-Data-Sampling-and-Variation-in-Data-and-Sampling

# Environment:
Content04
- **Book(s)**: Stats
- **URL/Server**:  See above
- **Browser**: Chrome

# Screenshots
![2019-09-26_14-50-11.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/a0acfc13-9c32-4b8d-8020-4878ccb3bc46)

# Additional notes

**Comment by lwtchu** [comment]
Issue moved to [openstax/webview #2276](https://github.com/openstax/webview/issues/2276) via [**ZenHub**](https://www.zenhub.com/)
