### ISSUE TITLE
Biology for AP Courses: Link to Learning Re-Class

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#1425]
Spun off from https://github.com/openstax/cnx-recipes/issues/1190

Per Helene:

"Biology and AP biology both have features called “Link to learning”, but the markup is inconsistent between the two books. In biology, link to learning uses the class `.link-to-learning` while AP Biology uses the class `.interactive`. The markup (content) should be changed in AP Biology to use the class `.link-to-learning` instead of `.interactive`. The templates currently only support the class `.link-to-learning`, so the feature will not display correctly in AP biology until the markup has been changed. The current decision is to not implement support for `.interactive`"

# Example
On the left is the markup in Chemistry, and on the right the markup in AP Bio. You can see that the AP Bio markup uses `class="interactive ost-assessed-feature"`.
![image](https://user-images.githubusercontent.com/12678235/65780876-43849700-e110-11e9-9ef4-c816bd9d7b93.png)

**Comment by brittweinstein** [comment]
This will be handled in content via https://app.zenhub.com/workspaces/content-management-5c86d8c40b66e07993f45cfa/issues/openstax/content-managers/890
