### ISSUE TITLE
Clean up colors in Chemistry

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1426]
- [ ] Portrait of Chemistry - change to #1e9575
- [ ] Example - #c31427

Change blue to #00829b in:
- [ ] EOC sections 
- [ ] Learning Objectives
- [ ] `.os-text` in Appendix
- [ ] Introduction page
- [ ] TOC
- [ ] Table
- [ ] borders in EOC

**Comment by MartaSztuka** [comment]
Colours as in description.
![Screenshot from 2019-10-17 14-49-29](https://user-images.githubusercontent.com/47241114/67010138-5e35a480-f0ed-11e9-8186-8b12e1a19e2d.png)
![Screenshot from 2019-10-17 14-53-01](https://user-images.githubusercontent.com/47241114/67010407-dc924680-f0ed-11e9-82da-95d0ed3dc237.png)
![Screenshot from 2019-10-17 14-57-00](https://user-images.githubusercontent.com/47241114/67010692-6f32e580-f0ee-11e9-8532-395c0ba065b2.png)
