### ISSUE TITLE
Anatomy: remove Unit titles from book

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1427]
Unit titles which appear in the text should be removed:
![image](https://user-images.githubusercontent.com/40228854/65970362-b1112a00-e466-11e9-9cc8-2a2d0ba8ceae.png)

**Comment by MartaSztuka** [comment]
Unit title is removed from the text.
![Screenshot from 2019-10-10 13-18-20](https://user-images.githubusercontent.com/47241114/66564658-d259d080-eb60-11e9-880d-9775b9100309.png)
