### ISSUE TITLE
Anatomy: style Introduction page

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1428]
Add style to Introduction page.

In Anatomy there is no Chapter Outline.
Appears Chapter Objectives which should be styled as Learning Objectives.

![image](https://user-images.githubusercontent.com/40228854/65970802-752a9480-e467-11e9-9854-8bde39df71c2.png)

**Comment by wilkus27** [comment]
Per Larissa: title `Chapter Objectives` should be styled as h4 header

**Comment by MartaSztuka** [comment]
Looks good.
![Screenshot from 2019-10-22 11-37-47](https://user-images.githubusercontent.com/47241114/67274845-9825f280-f4c1-11e9-8390-540b2921c75f.png)
