### ISSUE TITLE
carnival theme: baked styles for web chapter outline

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1430]
<img width="643" alt="Screen Shot 2019-10-01 at 2 25 10 PM" src="https://user-images.githubusercontent.com/11299125/65993721-65a34f80-e457-11e9-8ec0-38d53066c9c0.png">

Link to document: https://drive.google.com/file/d/1SwPY7w-4332GdCECHbILgB8dMUjQE0Zo/view

This should go right under the splash image in the intro.

Design specs are from Devika if you have questions.

**Comment by paulinaszczucinska** [comment]
[https://app.zenhub.com/files/49744755/e6c5bfbc-efc4-4ae3-94cc-25610cc8d081/download](https://app.zenhub.com/files/49744755/e6c5bfbc-efc4-4ae3-94cc-25610cc8d081/download)

**Comment by paulinaszczucinska** [comment]
@lwtchu could you check if this is part of carnival100 or is this for the web?

**Comment by openstaxalina** [comment]
@paulinaszczucinska this is for the web only; I am moving this out of the current milestone.

**Comment by lwtchu** [comment]
NOT to be confused with the work done here https://github.com/openstax/cnx-recipes/issues/1635#issuecomment-584660309


This is a separate issue for ALL titles when we eventually move to the web.

**Comment by lwtchu** [comment]
closing since we're not pursuing baked styles for web any time soon. when the needs arise we can revisit as circumstances might change
