### ISSUE TITLE
Psychology 2e - RECIPE WORK: move table number to the bottom of the table

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1432]
@lwtchu commented on [Thu May 23 2019](https://github.com/openstax/oer.exports/issues/3914)

Location of testable content: https://staging.cnx.org/contents/Sr8Ev5Og@11.1:iLkaPS1F@14/1-4-Careers-in-Psychology
 
![Screen Shot 2019-05-14 at 4.33.22 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/aab6b2e4-c29b-49e5-9497-a782aa6181c9)
Looks great in webview WITH TEST CONTENT WITH TOP-TITLED MARKUP IMPLEMENTED

We're going to implement `top-titled` tables in Psychology 2e. Please move the table number to below the table and NOT surrounded by any other boxes. 

See https://github.com/openstax/content-managers/issues/829 for investigation and decisions

**Comment by brittany-johnson** [comment]
I fetched, assembled, and baked psych content from staging.cnx.org and easyvm5.cnx.org and both times the tables already are alreading displaying with the number at the bottom. 
I think work only needs to be done for this in oer. 
@Stackblocks may want to still test and confirm before closing this issue
![Screen Shot 2019-10-15 at 10 09 58 AM](https://user-images.githubusercontent.com/24909007/66844783-83cb7e00-ef34-11e9-93cd-60db2376f62a.png)
![Screen Shot 2019-10-15 at 10 09 44 AM](https://user-images.githubusercontent.com/24909007/66844784-83cb7e00-ef34-11e9-894c-c196979e9ce3.png)

**Comment by Stackblocks** [comment]
I'm getting the same results as BrittanyJ.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a0b2f0d6-0b14-4153-90c8-4330f150ef62)
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/afd3337d-56dc-405f-a9f2-2d583e10dd9a)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/49181b12-abf2-4208-90ec-1e1fa7c419c0)

**Comment by brittany-johnson** [comment]
lol jk the table title should still be on top.

**Comment by brittany-johnson** [comment]
<img width="807" alt="Screen Shot 2019-10-18 at 10 22 45 AM" src="https://user-images.githubusercontent.com/24909007/67107012-40ba1680-f191-11e9-925c-9234f0139092.png">

Okay never mind! There is no work for me to do. The tables didn't have the `top-titled` class so that is why they weren't displaying correctly. @theresamasciale added the class to `table 1.1` for test content and its displaying correctly.
