### ISSUE TITLE
Carnival Theme: Adding Color bands to EOB

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1438]
EOB section should have added Color Bands regarding the specification placed in https://github.com/openstax/cnx-recipes/issues/1074

**Comment by MartaSztuka** [comment]
Colour bands added.
![Screenshot from 2019-11-06 13-14-38](https://user-images.githubusercontent.com/47241114/68298354-6bfd9a80-0099-11ea-925a-4d4ed6905077.png)
