### ISSUE TITLE
Anatomy: Chapter title disappearance&font changes

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1445]
1. Chapter title missing in ToC
![Screenshot from 2019-10-10 13-53-28](https://user-images.githubusercontent.com/47241114/66566497-5d3cca00-eb65-11e9-9594-6ad0d5a84de0.png)

2. Font of Chapter titles has changed in text.
![Screenshot from 2019-10-10 13-52-26](https://user-images.githubusercontent.com/47241114/66566429-3b434780-eb65-11e9-9b71-4555a3e2580f.png)

**Comment by wilkus27** [comment]
@tomjw64 I think this is a regression from https://github.com/openstax/cnx-recipes/pull/1433. After removing `use-title-nodes` release flag from Anatomy everything is displaying properly:

1.
![image](https://user-images.githubusercontent.com/40228854/66574511-aba59500-eb74-11e9-9182-8cd28894511b.png)

2.
![image](https://user-images.githubusercontent.com/40228854/66574714-f9220200-eb74-11e9-9885-d2265ac9fefa.png)

**Comment by wilkus27** [comment]
Decision is to disable the release flag for now for Anatomy and Biology. Fixes will be added in the next sprint.

**Comment by MartaSztuka** [comment]
Looks good.
![Screenshot from 2019-10-11 10-10-17](https://user-images.githubusercontent.com/47241114/66635448-8f0a6b00-ec0f-11e9-993a-164b781c5f3d.png)
![Screenshot from 2019-10-11 10-10-38](https://user-images.githubusercontent.com/47241114/66635454-916cc500-ec0f-11e9-94e1-e2db4871bb3a.png)
