### ISSUE TITLE
Style Fake Titled Tables

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1447]
Style tables in Anatomy based on informations from https://github.com/openstax/cnx-recipes/issues/1080, https://github.com/openstax/cnx-recipes/issues/1241, https://github.com/openstax/cnx-recipes/issues/1174.

Edit: style Fake Titled Tables in Anatomy and Chemistry (for Chemistry some changes in recipes are needed to have a proper markup to style).

**Comment by MartaSztuka** [comment]
Fake titled tables are styled.
Anatomy:
![Screenshot from 2020-01-09 14-51-13](https://user-images.githubusercontent.com/47241114/72073820-0031eb00-32f1-11ea-9730-60d2b2165337.png)
Chemistry 2e:
![Screenshot from 2020-01-09 15-33-18](https://user-images.githubusercontent.com/47241114/72076155-6587db00-32f5-11ea-9bcb-e86eacd51536.png)
