### ISSUE TITLE
dev math 2e: support be prepared answer solutions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1453]
# What happened?

We will be adding solutions into the Be Prepared notes that occur at the beginning of most non-intro modules.  

The note is  class `be-prepared`. 

**Acceptance criteria in the comment below!**

**Comment by openstaxalina** [comment]
This will be the markup for the Be Prepared exercises:
```
<note class=”be-prepared”>
  <exercise>
    <problem>...</problem>
    <solution>...</solution>
  </exercise>
    …
</note>
```

- [ ] Solutions need to collate to the beginning of the Answer Key for each chapter:
![DevMath2eAKBePrepared.png](https://images.zenhubusercontent.com/5b57372fb01a900cfd923015/df830417-90d5-4ca0-8432-148c74c22f1e)

- [ ] Please also advise if we need to add a collation instruction in the content.

**Comment by openstaxalina** [comment]
Marc is currently editing chapters 1 & 2 on easyvm5 with the new markup.  Let him know if he needs to add collation instructions.  This will be the link to the collection (same as the link in books.txt): https://easyvm5.cnx.org/contents/yqV9q0HH@18.4:jq9gwbWo@17/1-2-Add-Whole-Numbers

**Comment by openstaxalina** [comment]
(Issue for creating test content: https://github.com/openstax/content-managers/issues/1259)

**Comment by openstaxalina** [comment]
*chapters 1 and 2* of the test content have been updated.  let the coding begin! 

https://easyvm5.cnx.org/contents/yqV9q0HH

**Comment by openstaxalina** [comment]
This is ready for work - note that I had to add a new acceptance criteria, indicated above.  So the estimate on this probably needs to be higher.  cc @brittweinstein @helenemccarron for Monday meeting (I'll be at Jury Duty).

**Comment by lwtchu** [comment]
Let's try to have these emulate the Try Its https://cnx.org/contents/yqV9q0HH@20.1:ZvQt9vai@20.1/Chapter-1

I vote to not restart numbering since it might get confusing in the answer key if it's only 1. 2. 1. 2. 1. 2.

**Comment by openstaxalina** [comment]
Link to test content chs. 1 & 2 for this recipes issue: https://easyvm5.cnx.org/contents/yqV9q0HH

(Note that we will create a separate collection with only chapters 1 & 2 for the oer.exports fix next sprint.)

**Comment by openstaxalina** [comment]
Confirmed all acceptance criteria.  Closing.  cc @helenemccarron @brittweinstein
