### ISSUE TITLE
Change border-bottom-color TopTitledTable in Chemistry

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1454]
Bottom-border-color in LastTableRow (TopTitledTable) appears as black in collection.baked.xhtml and .pdf files, needs to be changed to 
to the chemistryHeaderColor used in settings relate to #1080.
![Screenshot from 2019-10-11 17-59-21](https://user-images.githubusercontent.com/55203598/66666424-e250dd80-ec50-11e9-841d-7d6fc6dde627.png)

**Comment by brittweinstein** [comment]
@ajluk was this issue found as a result of regression testing? If so, we should not address this until the other, non-Chemistry titles have been worked on. If not, continue and I apologize!

**Comment by wilkus27** [comment]
@brittweinstein as I remember, Ania found this when she was working on cleaning up colors in Chemistry. Color of the bottom border in tables in code is set to blue (different for each book), but it's not visible in PDF. @ajluk please correct me if I'm wrong. 
But Ania found this problem at the same time when I started working on styling tables in Anatomy. And there I'm resolving this problem. PR https://github.com/openstax/cnx-recipes/pull/1463 was blocked a few times by different problems and it is still In Progress. When we merge it this issue can be also closed.

**Comment by ajluk** [comment]
Yes Natalia you're right I have found this while working on cleaning colors and it coincided with you work on tables in Anatomy.

**Comment by MartaSztuka** [comment]
Bottom border colour look's ok.
![Screenshot from 2020-01-13 11-02-13](https://user-images.githubusercontent.com/47241114/72247717-ccf3a280-35f5-11ea-943f-f69e5b9da5e4.png)
