### ISSUE TITLE
Bad XML from Neb Publication Message

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1464]
# What happened?

trying to look at the metadata, version history, or downloads for m60003 on production in legacy results in a bad-xml error, but if the xml was bad why did it save? it was apparently edited with Neb in February, but for some reason the publication message is in a table cell with a bad `<pre>` tag around it. I'm not sure what's going on, but it seems like it must be a Batch problem; how was this markup even generated? It was not fixed when I checked the module out and made changes to it (I also cannot find the bad markup in the fullsource of the module).

https://legacy.cnx.org/content/m60003/latest/content_info#cnx_history_header

# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: this module and presumably all others that were batched in february

# Environment:

- **Book(s)**: Astronomy
- **URL/Server**: https://legacy.cnx.org/content/m60003/latest/content_info#cnx_history_header
- **Location (page number, chapter/section)**: Appendix: The Brightest Twenty Stars
- **Suggested nearby searchable text**: 
- **Browser**: Firefox

# Screenshots
![Screen Shot 2019-10-16 at 5.04.23 PM.png](https://images.zenhubusercontent.com/5b572ec492e09f0d21193829/ec8f7b0a-b3fb-4651-939e-489abb7cbcf7)
# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by lwtchu** [comment]
@Bkblodget @ne-newton this is super old...and i 'm closing. if you think this should be done still we should reopen.
