### ISSUE TITLE
Carnival Theme: Embiggened Footnotes

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#1467]
# What happened?

Something has happened to the footnotes to cause them to be `font-scale(1)` (10.8pt) instead of `font-scale(0)` (9pt) or less. 

# Reproducibility Details

- Occurred in Chemistry and Microbiology on `traitorous.treacletart` across multiple bakes.

# Environment:

- **Book(s)**: Chemistry, Microbiology, probably others.
- **URL/Server**: easyvm5.cnx.org
- **Location (page number, chapter/section)**: 
    - Microbiology:  p. 114, Appendix E.
    - Chemistry:  pp. 1291-2

# Screenshots
## Microbiology
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/59d06bdb-aef2-4f4d-b3b5-ab5742a3c1a8)
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/fd095895-31ff-4016-9e99-84733093c9c4)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/069accb7-397d-41d0-998d-b20d548ab32a)
## Chemistry
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/cbfdc544-b39d-4b43-91c4-f7a5a6c38af6)
# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by helenemccarron** [comment]
Should the font-scale be -1? @lwtchu

**Comment by lwtchu** [comment]
@helenemccarron are the footnotes in the main text also -1?

**Comment by lwtchu** [comment]
@helenemccarron i misread this. yes let's do -1

**Comment by ajluk** [comment]
Changes in TDS:
in Footnotes shapes elements in below properties only the values has been changed:
**Footnotes** shape
**Container**  l.204
line-height: line-height(1), 
font-size: font-scale(-1),
**FootnoteCall** shape (this name of the shape should be added as a separate row under l.211 in the way how it was done for Footnotes shape in l.203, I guess that was missed earlier :))
**DefaultFootnoteCall** l.211
 line-height: line-height(0),
font-size: font-scale(-1),

**Comment by ajluk** [comment]
![image](https://user-images.githubusercontent.com/55203598/76217036-f4d83e80-6211-11ea-954f-43416e2aedde.png)

**Comment by MartaSztuka** [comment]
Chemistry 2e
![Screenshot from 2020-03-10 13-54-22](https://user-images.githubusercontent.com/47241114/76314229-b0fb3d00-62d6-11ea-99ec-57fafbc9915b.png)
Microbiology
![Screenshot from 2020-03-10 14-23-47](https://user-images.githubusercontent.com/47241114/76316400-d8ec9f80-62da-11ea-99c3-5bb784ec6c1d.png)
