### ISSUE TITLE
college physics: add style to Preface

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1473]
Apply style for Preface in College Physics with the same specs as in Anatomy (https://github.com/openstax/cnx-recipes/issues/1392).

Color pallete for this book: https://github.com/openstax/cnx-recipes/issues/1163

**Comment by MartaSztuka** [comment]
Styled properly.
![Screenshot from 2019-10-22 12-59-56](https://user-images.githubusercontent.com/47241114/67279884-3a4ad800-f4cc-11e9-940f-ee2c57ee593e.png)
