### ISSUE TITLE
Chapter Outline bottom is cropped.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1475]
There should be 2.7 Chemical Nomenclature and there isn't, not even on the next page.
![Screenshot from 2019-10-18 15-04-15](https://user-images.githubusercontent.com/47241114/67096948-707d1480-f1b9-11e9-8787-8c6f20ba684b.png)

**Comment by MartaSztuka** [comment]
More cropped boxes:
![Screenshot from 2019-10-21 13-20-28](https://user-images.githubusercontent.com/47241114/67201126-d958cc80-f405-11e9-8539-a80653ca5cbe.png)
![Screenshot from 2019-10-21 13-19-35](https://user-images.githubusercontent.com/47241114/67201127-d9f16300-f405-11e9-9cd0-bcd380bf9701.png)
![Screenshot from 2019-10-21 13-24-01](https://user-images.githubusercontent.com/47241114/67201211-11f8a600-f406-11e9-9ac6-69f8f6b6d70e.png)

**Comment by MartaSztuka** [comment]
Chemistry AF
![Screenshot from 2019-10-30 15-48-49](https://user-images.githubusercontent.com/47241114/67868976-048d9b00-fb2d-11e9-8e38-9dd325f4345c.png)
![Screenshot from 2019-10-30 15-51-45](https://user-images.githubusercontent.com/47241114/67869093-3acb1a80-fb2d-11e9-93ab-2242e632a96f.png)
![Screenshot from 2019-10-30 15-52-58](https://user-images.githubusercontent.com/47241114/67869179-5df5ca00-fb2d-11e9-9307-c961886666f0.png)
![Screenshot from 2019-10-30 15-53-55](https://user-images.githubusercontent.com/47241114/67869277-81b91000-fb2d-11e9-9e92-7eca86f5b4ed.png)
![Screenshot from 2019-10-30 15-54-40](https://user-images.githubusercontent.com/47241114/67869357-9ac1c100-fb2d-11e9-88a2-2f0b681268be.png)
![Screenshot from 2019-10-30 15-55-27](https://user-images.githubusercontent.com/47241114/67869436-b75df900-fb2d-11e9-949a-ca3f6397ed1b.png)

**Comment by brittweinstein** [comment]
We will adjust font to base font size and reduce chapter outline header size, also to base font size. We will also increase the whole box width to 2 inches.

**Comment by wilkus27** [comment]
Will be resolved in issue: https://github.com/openstax/cnx-recipes/issues/1625

**Comment by paulinaszczucinska** [comment]
@MartaSztuka please check if it still occurs and update the issue.

**Comment by MartaSztuka** [comment]
Chemistry 2e
![Screenshot from 2020-03-18 17-16-27](https://user-images.githubusercontent.com/47241114/76982509-4aac9500-693c-11ea-9f80-a8ba53643ca4.png)
Chemistry AF
![Screenshot from 2020-03-18 17-18-56](https://user-images.githubusercontent.com/47241114/76982759-9e1ee300-693c-11ea-93e2-83a9f8a55152.png)

**Comment by MartaSztuka** [comment]
**Chemistry 2e**
![Screenshot from 2020-03-25 14-49-50](https://user-images.githubusercontent.com/47241114/77544901-f3617400-6ea9-11ea-8a36-55eb6bb4a2e5.png)

**Comment by MartaSztuka** [comment]
Chemistry AF tested on branch `fullwidth-chapterintro-chemistryaf`
![Screenshot from 2020-03-25 15-41-12](https://user-images.githubusercontent.com/47241114/77548859-68837800-6eaf-11ea-9b70-270d374fec19.png)
