### ISSUE TITLE
Example is unstyled

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1476]
Words like `Solution`, `Check your learning` and the command should be bold according to the Theme Design Specs table.
![Screenshot from 2019-10-18 16-13-12](https://user-images.githubusercontent.com/47241114/67102048-1d0fc400-f1c3-11e9-9ffe-8c84ecef63ce.png)

**Comment by MartaSztuka** [comment]
Chemistry AF
![Screenshot from 2019-10-30 15-37-16](https://user-images.githubusercontent.com/47241114/67867765-31d94980-fb2b-11e9-86c1-8eacfa740888.png)

**Comment by brittweinstein** [comment]
@lwtchu will investigate this and provide more information. I will put this in the Icebox for now.

**Comment by lwtchu** [comment]
@MartaSztuka based on this we should update the specs
https://github.com/openstax/cnx-recipes/issues/1793

the title `Answer` should be the following: 
Style: IBM Plex Sans
Size: font-scale(1)
Weight: Bold
Uppercase: Off

**Comment by wilkus27** [comment]
Ready for testing on `carnival100` branch

**Comment by MartaSztuka** [comment]
**Chemistry 2e**
![Screenshot from 2020-03-26 13-05-27](https://user-images.githubusercontent.com/47241114/77645126-82ca5e00-6f62-11ea-957d-2233ce4c1b83.png)
**Chemistry AF**
![Screenshot from 2020-03-26 13-17-33](https://user-images.githubusercontent.com/47241114/77646100-2ff1a600-6f64-11ea-84db-4f80d3655f29.png)
