### ISSUE TITLE
Equations should have bottom margin.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1477]
Otherwise things are sticking to it.
![Screenshot from 2019-10-18 17-03-20](https://user-images.githubusercontent.com/47241114/67106321-aeceff80-f1ca-11e9-9ad0-bf3cf383d35f.png)
![Screenshot from 2019-10-18 17-12-24](https://user-images.githubusercontent.com/47241114/67106399-d7ef9000-f1ca-11e9-995e-70ac47275e6c.png)

**Comment by MartaSztuka** [comment]
Chemistry AF
![Screenshot from 2019-10-30 15-35-31](https://user-images.githubusercontent.com/47241114/67867630-fb033380-fb2a-11e9-867f-cf60c74d0025.png)

**Comment by ajluk** [comment]
I have added bottom margins to the equations within this PR: issue: https://github.com/openstax/cnx-recipes/issues/1638.

**Comment by brittweinstein** [comment]
@MartaSztuka could you please verify if this is fixed via the issue noted above?

**Comment by MartaSztuka** [comment]
Issue still occurs both in chemistry and chemistry AF.
![Screenshot from 2020-01-08 11-05-34](https://user-images.githubusercontent.com/47241114/71969417-ea47fb80-3206-11ea-881c-12d1b60a9581.png)
![Screenshot from 2020-01-08 11-08-13](https://user-images.githubusercontent.com/47241114/71969589-3e52e000-3207-11ea-8581-e7c31e49aafe.png)

**Comment by ajluk** [comment]
It is the same problem as in Biology 2e. The unnumbered equations in this books don't have class `unnumbered` added in the markup, that's why the styles for unnumbered equations aren't applied there. @lwtchu what do you think?

**Comment by lwtchu** [comment]
@ajluk are all equations in chemistry unnumbered but are missing the `unnumbered` class?

**Comment by ajluk** [comment]
@lwtchu Yes, that is the case. Previously we have one type of equations that was covering all of them, but since in Physics equations are numbered we have divided them and equations that are unnumbered need to have unnumbered class added so the styles for this type of equations can cover them.

**Comment by lwtchu** [comment]
@ajluk let me make a card on the content side ...and when we're done, we can generate a PDF to verify whether or not this is stil an issue.

**Comment by paulinaszczucinska** [comment]
@MartaSztuka please check if it still occurs and update the issue.

**Comment by MartaSztuka** [comment]
It's still an issue
![Screenshot from 2020-03-18 17-11-09](https://user-images.githubusercontent.com/47241114/76987288-3750f800-6943-11ea-9740-79d79d4f6a59.png)

**Comment by wilkus27** [comment]
After content refresh on katalyst01 fetched again. Resolved in content by added `unnumbered` class to equations.

![image](https://user-images.githubusercontent.com/40228854/77759790-9abee200-7035-11ea-906c-a9363df0ab1a.png)
