### ISSUE TITLE
100% of University Physics to the Carnival Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1479]
# Color Palette and General Notes

![f37541-78b042-c31427-00819a-b10069](https://user-images.githubusercontent.com/11299125/61414993-18cac680-a8b5-11e9-8c17-914b1ff3f62d.png)

Theme: Carnival
Chapter title, chapter number, H1, H2, H3, etc: #00819A
Splash image bar, chapter outline, box color: #00819A
Learning objectives text color: #00819A

CONTAINS UNITS

End of Chapter Sections
- Contains Glossary (`<glossary>`), Key Equations (`key-equations`), Section Summary (`key-concepts`), Conceptual Questions (`review-conceptual-questions`), Problems(`review-problems`), Additional Problems (`review-additional-problems`), Challenge Problems (`review-challenge`)

- Summary, Conceptual Questions, Problems are all separated by subsections
- Conceptual Questions, Problems, Additional Problems, Challenge Problems are in two columns

End of Book
Appendices
Answer Key
Index

**Comment by openstaxalina** [comment]
# Checklist

- [ ] book needs to be added to the template

- [ ] book-specific feature: equation call out note (cell C135 of [specs table](https://docs.google.com/spreadsheets/d/1vW0EHvn8fZgvTxZIm9xQXsqsnIDcolqwt5rWKtx4JEY/edit#gid=1663003137) )

- [ ] book-specific feature: problem solving strategy (cell TBD of [specs table](https://docs.google.com/spreadsheets/d/1vW0EHvn8fZgvTxZIm9xQXsqsnIDcolqwt5rWKtx4JEY/edit#gid=1663003137) )

- [ ] updated books.txt with template (anything else?)

- [ ] enable release flags
