### ISSUE TITLE
Placeholder: Leaky pipe - remove some blank string warnings

### ISSUE THREAD

**Issue by tomjw64** [openstax/cnx-recipes#1481]

**Comment by brittweinstein** [comment]
When baking, there shouldn't be so many warning signs related to empty strings.

**Comment by Stackblocks** [comment]
Looking good.

## Before
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1f422b00-2ec6-4658-9cbf-102cc94eb97b)

## After
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1c028aa4-e493-4d5a-b2a3-9f7b670aecee)
