### ISSUE TITLE
university physics: equation call out note

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1482]
Class: `equation-callout`
Color: #EEEAE0

Can we have the equation be in a box that spans from left to right margin? 
*Need to confirm what we are doing with equation numbers

![Screen Shot 2019-10-21 at 3 21 12 PM](https://user-images.githubusercontent.com/11299125/67240135-73287580-f416-11e9-81b6-f66da8d0eff2.png)

**Comment by openstaxalina** [comment]
closing; this has been added to the checklist in https://github.com/openstax/cnx-recipes/issues/1479
