### ISSUE TITLE
Key equations have random leading differences.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1483]
and it's not caused by equations's margine issue.
![Screenshot from 2019-10-21 13-29-45](https://user-images.githubusercontent.com/47241114/67201705-1e313300-f407-11e9-8863-aac28a6439b3.png)
![Screenshot from 2019-10-21 12-23-10](https://user-images.githubusercontent.com/47241114/67201761-44ef6980-f407-11e9-8d27-a9f3ec3644d5.png)

**Comment by brittweinstein** [comment]
We will re-test this after the katalyst01 refresh.

**Comment by brittweinstein** [comment]
Alina and Larissa will talk about if we should fix this and if so, a CM can migrate a couple of modules.  

We should not do a content refresh b/c we will lose HS Phys.

**Comment by openstaxalina** [comment]
We will migrate content for chs 1 and 3 to katalyst01 by feb 28 (in time for f.f. sprint)

**Comment by openstaxalina** [comment]
See: https://github.com/openstax/content-managers/issues/1456

**Comment by wilkus27** [comment]
I think this is the same problem as in issue: https://github.com/openstax/cnx-recipes/issues/2013.

**Comment by brittweinstein** [comment]
@MartaSztuka please verify if this is still an issue or if it was resolved by https://github.com/openstax/cnx-recipes/issues/2013

**Comment by wilkus27** [comment]
@brittweinstein This issue was just blocked by #2013 . Related PR didn't resolve this problem, it fixed only exercises. Now we need to apply solution created by @ajluk to Key Equations.

**Comment by wilkus27** [comment]
During testing please check also HS Physics. In this book there are section titles in Key Equations. I changed margins for some elements. Please verify if provided changes looks good.

**Comment by MartaSztuka** [comment]
Chemistry 2e
![Screenshot from 2020-04-23 12-40-41](https://user-images.githubusercontent.com/47241114/80090356-aa134b80-855f-11ea-963b-e8e93cda4ddd.png)
Chemistry AF @wilkus27 Key Equations have bullets sticking out, there shouldn't be any.
![Screenshot from 2020-04-23 13-24-48](https://user-images.githubusercontent.com/47241114/80094109-fbbed480-8565-11ea-92a6-1aedab00d9bc.png)
HS Physics looks ok
![Screenshot from 2020-04-23 13-31-31](https://user-images.githubusercontent.com/47241114/80094602-d4b4d280-8566-11ea-85b6-5ba6a4a505ea.png)

**Comment by MartaSztuka** [comment]
Fetched Chemistry AF bullets are gone.
![Screenshot from 2020-04-24 08-28-36](https://user-images.githubusercontent.com/47241114/80181791-cec1fe80-8605-11ea-95b8-7fc1c708fe21.png)
