### ISSUE TITLE
library wide: exercise formatting

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1486]
![image](https://user-images.githubusercontent.com/11299125/67220644-c1764e00-f3ef-11e9-8813-63815f3fc515.png)

Please have the number be with the question stem.

For example:
*21.* Write Lewis structures for ...

**Comment by oscryan** [comment]
still like this
<img width="502" alt="Screen Shot 2019-12-20 at 10 46 54 AM" src="https://user-images.githubusercontent.com/1895432/71269951-0e09d700-2316-11ea-84c2-1e1caa17f298.png">

**Comment by ajluk** [comment]
I have made those changes in University Physics within this PR:  #1739. When it will be merged these can be added to exercises in other books.

**Comment by ajluk** [comment]
These changes has been made within different PR by Helene. It is how it looks now in Biology 2e: 
![image](https://user-images.githubusercontent.com/55203598/74833132-2ba8ec00-5319-11ea-9d7c-6a33a72fa5bd.png)

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-20 17-28-59](https://user-images.githubusercontent.com/47241114/74956517-8704d800-5406-11ea-9e70-7d746dc4c8fe.png)
![Screenshot from 2020-02-20 17-28-01](https://user-images.githubusercontent.com/47241114/74956519-88360500-5406-11ea-82c2-395ae4cc15bb.png)
