### ISSUE TITLE
university physics: icon notes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1487]
See #1088 for specifications

Title: Problem Solving Strategy
Class: `problem-solving`
Color: #00819A
Icon: https://drive.google.com/open?id=1clc_5Bk4kn5qcyRqIDl6vQmFUBdXJ4WT

University Physics also has Link to Learning (`media-2` which we will change to `link-to-learning`) & Check Your Understanding (`check-understanding`) which should be the same as it is in the other carnival theme titles. 

@helenemccarron no answer needed now - but let us know when you're ready for us to cahnge the classes for the LTL and CYU notes

**Comment by openstaxalina** [comment]
Closing; this has been added to the checklist here: https://github.com/openstax/cnx-recipes/issues/1479
