### ISSUE TITLE
Generate Business Law I Essentials ePub

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1488]
Now that _Business Law I Essentials_ has been released, we need to generate an ePub for Study Edge, so they can ingest our content into an OpenStax + SE app.  Staging.cnx.org doesn't have this book, so I have requested a content refresh.

[This spreadsheet](https://docs.google.com/spreadsheets/d/14GLK8wnYo4SHTZdvFjJWYHlqdBjXCxfqZnXsjxa6emo) is where we track the titles, with their UUIDs and versions, for the ePubs we've created / need to create for Study Edge.

Here are the steps for generating an ePub:
1) SSH into the server.
2) Run a command based on the UUID provided.
3) Wait for the command to complete.
4) Download the file.
5) Delete the ePub-only content.
6) Rename the index file to `index.html`.
7) Zip the folder with the proper file name.
8) Upload to [this Google Drive folder](https://drive.google.com/drive/folders/1lw9BfhIcOG0gFdWz9ZgY3yLfXpaJ8ef0).
9) Use @cm in the #books-and-candles channel to alert content managers that an ePub is ready for QA.
10) Delete the collection that was generated in the Home folder.

# Environment:

* **Medium**: [ ] REX [ ] PDF  [x] cnx.org  
* **Instance**: [ ] production  [ ] qa  [x] staging  [ ] dev  [ ] content

# Test Plan 
- Alert @cm in the #books-and-candles channel to alert content managers that an ePub is ready for QA
- CMs will open issues in this repo for any files that do not pass testing.

# Acceptance Criteria
- All books on the spreadsheet have had ePubs uploaded to the [folder](https://drive.google.com/drive/folders/1lw9BfhIcOG0gFdWz9ZgY3yLfXpaJ8ef0).

**Comment by brittany-johnson** [comment]
Business law epub has been generated and zip is now in the google drive folder 

https://docs.google.com/spreadsheets/d/14GLK8wnYo4SHTZdvFjJWYHlqdBjXCxfqZnXsjxa6emo/edit#gid=0

**Comment by lwtchu** [comment]
Gonna close this. in CM's court ball whatever
