### ISSUE TITLE
WAIT for space saving to be completed - ToC page numbers jump to the next line

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1489]
Happens in other books too.
![Screenshot from 2019-10-22 13-19-50](https://user-images.githubusercontent.com/47241114/67280966-a75f6d00-f4ce-11e9-8c63-d739aed97ad3.png)
![Screenshot from 2019-10-22 13-19-39](https://user-images.githubusercontent.com/47241114/67280967-a75f6d00-f4ce-11e9-9efc-f5689b2ffcb2.png)

**Comment by MartaSztuka** [comment]
Chemistry AF
![Screenshot from 2019-10-30 11-15-11](https://user-images.githubusercontent.com/47241114/67849259-9504b500-fb06-11e9-8f5b-e070d7ee8e52.png)

**Comment by brittweinstein** [comment]
@lwtchu and @andymuddimer will look at the margin widths and possibly make adjustments.

**Comment by ajluk** [comment]
This issue has been resolved within the space saving PR (Chemistry 2e PDF file): 
![image](https://user-images.githubusercontent.com/55203598/78350778-09f08500-75a6-11ea-87da-652a4733afc4.png)

**Comment by MartaSztuka** [comment]
Resolved by space saving pr
![Screenshot from 2020-04-06 14-52-13](https://user-images.githubusercontent.com/47241114/78560357-4b876700-7816-11ea-928f-046f4f6ddcc4.png)
![Screenshot from 2020-04-06 14-54-19](https://user-images.githubusercontent.com/47241114/78560532-85f10400-7816-11ea-8219-2b856a74d060.png)
