### ISSUE TITLE
college physics: style chapter and module titles

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1490]
Add style to:
- [x] chapter title
- [x] module title
- [x] headers from inside of section

with specs from Carnival Theme

**Comment by MartaSztuka** [comment]
Titles and headers are styled.
![Screenshot from 2019-10-29 13-58-22](https://user-images.githubusercontent.com/47241114/67769149-37b02b80-fa54-11e9-8864-e4608705c8e0.png)
![Screenshot from 2019-10-29 13-47-15](https://user-images.githubusercontent.com/47241114/67769227-56aebd80-fa54-11e9-9680-db0ad6301652.png)
![Screenshot from 2019-10-29 14-00-20](https://user-images.githubusercontent.com/47241114/67769280-78a84000-fa54-11e9-888d-604916cd51e2.png)
