### ISSUE TITLE
Enable all flags for Microbiology

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1494]
All release flags should be enabled. Please list here which flags were enabled to they can be tested.

**Comment by brittany-johnson** [comment]
All release flags for microbio have been enabled on `t.t`. 
Please see `RELEASE_FLAGS.md` for the full list of flags

**Comment by helenemccarron** [comment]
All flags were enabled except for the `give-composites-ids` flag, which is broken.
