### ISSUE TITLE
Enable all feature flags for Anatomy

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1495]
All release flags should be enabled. Please list here which flags were enabled to they can be tested.

**Comment by helenemccarron** [comment]
All flags were enabled except for the `give-composites-ids` flag, which is broken.

**Comment by wilkus27** [comment]
And except `appendix-has-numbered-examples`. Some changes in mixin are needed to be able to enable this flag in Anatomy.
