### ISSUE TITLE
Enable all flags for AP Biology

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1496]
All release flags should be enabled. Please list here which flags were enabled and what changes are expected so they can be tested.

**Comment by ajluk** [comment]
The documentation regarding all feature flags: https://docs.google.com/document/d/1ziR2PcSvioOLAHSRNWZga3m-8DlUM_qaskIjpWtoS60/edit?pli=1#
Enabled flags:
- [ ] flag 1. **toc-labeled-pages**
- [ ] flag 14. **toc-title-word**
- [ ] flag 8. **titles-in-examples**

**Comment by ajluk** [comment]
The documentation regarding all feature flags: https://docs.google.com/document/d/1ziR2PcSvioOLAHSRNWZga3m-8DlUM_qaskIjpWtoS60/edit?pli=1#
Enabled flags:
- [ ] flag 1. **toc-labeled-pages**
- [ ] flag 14. **toc-title-word**
- [ ] flag 8. **titles-in-examples**
- [ ] flag 9. **module-titled-notes**

**Comment by MartaSztuka** [comment]
Flag 1. ok
![Screenshot from 2019-11-27 16-39-36](https://user-images.githubusercontent.com/47241114/69738769-e10f3d80-1136-11ea-82ff-0f8f8804d91d.png)
Flags 8, 9 - doesn't effect
Flag 12 ok
![Screenshot from 2019-11-27 17-09-55](https://user-images.githubusercontent.com/47241114/69739911-c76ef580-1138-11ea-9735-207694c84551.png)
Flag 13 ok
![Screenshot from 2019-11-27 16-53-08](https://user-images.githubusercontent.com/47241114/69739155-81656200-1137-11ea-910e-ebca64f13a90.png)
Flag 14 ok
![Screenshot from 2019-11-27 17-01-55](https://user-images.githubusercontent.com/47241114/69739224-a528a800-1137-11ea-98e6-510ef81881e6.png)
Flag 16 ok
![Screenshot from 2019-11-27 17-03-40](https://user-images.githubusercontent.com/47241114/69739434-03558b00-1138-11ea-9553-c633c27b5142.png)
Flag 17 it's fewer warnings
![Screenshot from 2019-11-27 17-06-52](https://user-images.githubusercontent.com/47241114/69739660-63e4c800-1138-11ea-9e50-faa995629f7c.png)
