### ISSUE TITLE
Enable all feature flags for College Physics

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1498]
All release flags should be enabled. Please list here which flags were enabled to they can be tested.

**Comment by wilkus27** [comment]
### Enable flags:

- titles-in-examples
- module-titled-notes
- use-title-nodes
- goodbye-warnings

Flags `groupChapOutlineIntroContent` and `tagSplash` are enabled in PR related with issue https://github.com/openstax/cnx-recipes/issues/1565, which will be merged in the next sprint.

Informations what affect have each flag you can find in https://docs.google.com/document/d/1ziR2PcSvioOLAHSRNWZga3m-8DlUM_qaskIjpWtoS60/edit#heading=h.hca2jjbhejsz

**Comment by MartaSztuka** [comment]
Flag 8 - no impact
Flag 9 - no impact
Flag 16 - all titles look ok
Flag 17 - noticeably fewer goodbye warnings
