### ISSUE TITLE
Book-specific design elements that (high school) Physics will need to handle in baked styles

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1505]
# Scenario

This is to facilitate a discussion next sprint about the work involved to move Physics (from TEA) into baked styles for release in March 2020.

# Link to content

https://content04.cnx.org/contents/IKZFuFtg

# Folder with screenshots of elements in current PDF (uses _University Physics_ designs)

https://drive.google.com/drive/folders/1ZfToqyardXiMLnFNNr7zTYxijSGPeqX2

# Design elements in the title

General things:
- [ ] Teacher Content/Support (these have a class (or classes) - use a display="none")
- [ ] Section Key Terms

Feature-like things:
- [ ] Grasp Check
- [ ] Snap Lab
- [ ] Worked Example
- [ ] Worked Examples (plural)
- [ ] Tips for Success
- [ ] Work in Physics
- [ ] Fun in Physics
- [ ] Boundless Physics
- [ ] Links to Physics
- [ ] Watch Physics
- [ ] Virtual Physics

In-Section Exercises
- [ ] Practice Problems

End of Section Exercises
- [ ] Check Your Understanding (use from other Carnival books?)

Collating Elements (EOC):
- [ ] Section Summaries (needs restyling; use from other Carnival books?)
- [ ] Concept Items
- [ ] Critical Thinking
- [ ] Problems
- [ ] Performance Task
- [ ] Test Prep Multiple Choice
- [ ] Test Prep Short Answer
- [ ] Test Prep Extended Response

# HS Physics Tagging Legend
https://drive.google.com/a/rice.edu/file/d/0B7KX2mPxBBE9X0dyc3RKRUlpeTg/view?usp=sharing

**Comment by openstaxalina** [comment]
Pre-work for meeting: @brittany-johnson generating a baked-styles PDF of this title.  Give all the features the same style for now.  Share PDF with Larissa to discuss at the meeting.

**Comment by brittweinstein** [comment]
Teacher support will be hidden. 

Decision making OER vs Baked
OER: remove width constraints; hide teacher support
Baked: remove constraints, link to EOC broken in any composite pages, hide teacher support, has math

**Comment by lwtchu** [comment]
Need for March if we go to baked styles
- fix broken composite pages, fixing IDs (that thing Thomas unearthed from critsit) cnx easy bake issue 97
- reliable exercises fetching - we uncovered something today that broke it

Need by July 
- pdf producer for additive manufacturing

**Comment by openstaxalina** [comment]
Here is where I understand we are:
We would need CE-Tech help to allow us to link to composite pages (https://github.com/openstax/cnx-easybake/issues/97)
And also for reliable exercise fetching
*And finally for PDF Producer, but in theory we could wait for this ’til July.*

cc @helenemccarron @brittany-johnson @Stackblocks @lwtchu @brittany-johnson 

I will talk with Bey about these things on Monday.

**Comment by openstaxalina** [comment]
The discussion happened and action items are captured above.  I will create a new card for adjustments to the recipe.  Closing this card.
