### ISSUE TITLE
Page breaks

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1506]
Exampe (Note):
![Screenshot from 2019-10-23 17-19-35](https://user-images.githubusercontent.com/47241114/67408504-65f7bc00-f5b9-11e9-88f6-3061136e290e.png)
Footnotes
![Screenshot from 2019-10-23 17-18-02](https://user-images.githubusercontent.com/47241114/67408336-1c0ed600-f5b9-11e9-8e90-e1ed94f82bba.png)
![Screenshot from 2019-10-23 17-17-51](https://user-images.githubusercontent.com/47241114/67408337-1ca76c80-f5b9-11e9-99b5-9e0fe11f5b2e.png)
![Screenshot from 2019-10-23 17-19-35](https://user-images.githubusercontent.com/47241114/67408476-51b3bf00-f5b9-11e9-9506-9ac9c4314222.png)
Tables
![Screenshot from 2019-10-23 17-16-25](https://user-images.githubusercontent.com/47241114/67408151-e10ca280-f5b8-11e9-9450-da9d2370764a.png)
Captions (Figures, tables, ect.)
![Screenshot from 2019-10-23 17-14-23](https://user-images.githubusercontent.com/47241114/67407979-9723bc80-f5b8-11e9-9891-5f7da0e87279.png)
![Screenshot from 2019-10-23 17-14-45](https://user-images.githubusercontent.com/47241114/67408016-a440ab80-f5b8-11e9-8213-f2a7fb0b4e3c.png)
By the end of this section... 
![Screenshot from 2019-10-23 17-09-43](https://user-images.githubusercontent.com/47241114/67407588-077e0e00-f5b8-11e9-97a1-fa91c529f170.png)
Exercises list
![Screenshot from 2019-10-23 17-13-28](https://user-images.githubusercontent.com/47241114/67407898-765b6700-f5b8-11e9-8b8a-e19b8ca4a9fd.png)
Table of Content 
![Screenshot from 2019-10-23 17-07-43](https://user-images.githubusercontent.com/47241114/67407430-c5ed6300-f5b7-11e9-93d4-3d9c95414852.png)
Paragraphs' last word/line
![Screenshot from 2019-10-23 17-11-52](https://user-images.githubusercontent.com/47241114/67407723-398f7000-f5b8-11e9-8730-92fbfdc99e86.png)

**Comment by paulinaszczucinska** [comment]
@MartaSztuka could you check if this problem still occurs and to update the issue?

**Comment by MartaSztuka** [comment]
Example
![Screenshot from 2020-03-18 17-49-27](https://user-images.githubusercontent.com/47241114/76985671-dfb18d00-6940-11ea-9d1a-067461106df2.png)
Footnotes
![Screenshot from 2020-03-18 17-51-55](https://user-images.githubusercontent.com/47241114/76985898-3919bc00-6941-11ea-83d7-b7b8d4619012.png)
Tables
![Screenshot from 2020-03-18 17-53-50](https://user-images.githubusercontent.com/47241114/76986066-767e4980-6941-11ea-9931-80f413c22ca3.png)
Captions (figures, tables)
![Screenshot from 2020-03-18 17-56-39](https://user-images.githubusercontent.com/47241114/76986430-eee50a80-6941-11ea-9c77-01feaed12514.png)
![Screenshot from 2020-03-18 17-56-20](https://user-images.githubusercontent.com/47241114/76986434-f0163780-6941-11ea-9c17-38127ecf4334.png)
By the end of this section...
![Screenshot from 2020-03-18 17-58-49](https://user-images.githubusercontent.com/47241114/76986639-3370a600-6942-11ea-9a33-c49b64b0adbf.png)
Exercises list
![Screenshot from 2020-03-18 17-59-49](https://user-images.githubusercontent.com/47241114/76986775-67e46200-6942-11ea-9dd4-7eebcb66d4b9.png)
Table of Content
![Screenshot from 2020-03-18 18-01-50](https://user-images.githubusercontent.com/47241114/76986891-96623d00-6942-11ea-9919-0a835e16ca2b.png)
Last word/line
![Screenshot from 2020-03-18 18-02-40](https://user-images.githubusercontent.com/47241114/76986983-b8f45600-6942-11ea-873f-794e61b843e1.png)
