### ISSUE TITLE
Double numbering

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1521]
Step 1, Step 2 etc. list has double numbering.
![Screenshot from 2019-10-25 13-26-13](https://user-images.githubusercontent.com/47241114/67568062-70d25e00-f72b-11e9-9da9-0ebf7ddfab81.png)

**Comment by MartaSztuka** [comment]
Chemistry AF
![Screenshot from 2019-10-30 11-12-29](https://user-images.githubusercontent.com/47241114/67849121-42c39400-fb06-11e9-8e61-cc78f66cdf72.png)

**Comment by brittweinstein** [comment]
@MartaSztuka can you confirm if this is still an issue.

**Comment by MartaSztuka** [comment]
@brittweinstein yes it is

**Comment by brittweinstein** [comment]
@MartaSztuka could you please provide a link to this? @lwtchu will investigate the class.

**Comment by MartaSztuka** [comment]
![Screenshot from 2020-01-08 10-20-59](https://user-images.githubusercontent.com/47241114/71965894-d8635a00-3200-11ea-8822-f1805dc8a83e.png)

**Comment by ajluk** [comment]
Changes in TDS:
@lwtchu I'm not sure where in the TDS table it should be place, but these styles are common for all books and doesn't have shapes or components. They are placed in the _common-styles.scss file. So maybe something like that can be added to the table as a name.

**Comment by lwtchu** [comment]
@ajluk if it's alright with you i won't put it in the spec doc since it's common to all books.

**Comment by MartaSztuka** [comment]
Chemistry 2e
![Screenshot from 2020-03-10 13-46-10](https://user-images.githubusercontent.com/47241114/76313722-c754c900-62d5-11ea-8584-3fbaafff3100.png)
Chemistry af
![Screenshot from 2020-03-10 13-49-37](https://user-images.githubusercontent.com/47241114/76313833-0551ed00-62d6-11ea-80f0-45447f6f69cb.png)
