### ISSUE TITLE
Allow books without appendices to use flag appendix-has-numbered-examples

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1539]
If book doesn't have appendices we are not able to enable `appendix-has-numbered-examples` release flag in it, because it causing errors.

Some changes in mixins are needed to fix that problem. 

Here is the PR with details what kind of problems appear: https://github.com/openstax/cnx-recipes/pull/1515

**Comment by wilkus27** [comment]
Ready for test. Issue was noticed in Anatomy. Because there is no Appendix in this book, any changes are unexpected. It is worth to check also book with examples in Appendix to be sure that changes from PR related with this issue don't cause any regression.

**Comment by MartaSztuka** [comment]
Anatomy (without appendix) looks good.
Chemistry (with appendix) - also.
![Screenshot from 2019-11-21 13-07-30](https://user-images.githubusercontent.com/47241114/69336957-ff20fd80-0c5f-11ea-8513-8186f6fd1af1.png)
