### ISSUE TITLE
apbiology & biology: add style to chapter title

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1546]
Chapter titles and numbers should be styled according to specs contained in : https://github.com/openstax/cnx-recipes/issues/1189 and https://github.com/openstax/cnx-recipes/issues/1072. Color palette is the same for both these books.: https://github.com/openstax/cnx-recipes/issues/1155

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image](https://user-images.githubusercontent.com/12678235/68431726-7e023a80-0178-11ea-8b71-1bbb8b4ff0b6.png)
