### ISSUE TITLE
List of tasks that Styles Devs do 

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1547]
From 10/25 staging deploy [post-mortem](https://docs.google.com/document/d/1qsOPV4U63r7rYW9cB6b_3d6WgfBFDntBBh2KzBxp2jc/edit#heading=h.qf5fnkjgv8zr) .

- [ ] CE Styles devs create a complete list of the tasks that they do, and when.  
For example, when do we run DB migrations?
- [ ] Work with CE Tech and make sure we all agree that these are the proper processes.

**Comment by openstaxalina** [comment]
@brittany-johnson started updating the CE Tech wiki with three specific things that Styles devs do.  Not an exhaustive list yet.

**Comment by brittany-johnson** [comment]
Updating documentation in this card: https://github.com/openstax/cnx-recipes/issues/2640 
closing in favor of ^
