### ISSUE TITLE
Update outdated documentation

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1548]
From 10/25 staging deploy [post-mortem](https://docs.google.com/document/d/1qsOPV4U63r7rYW9cB6b_3d6WgfBFDntBBh2KzBxp2jc/edit#heading=h.qf5fnkjgv8zr) .

- [ ] Go over https://docs.google.com/document/d/1UCO4eTtpqfAgVQq2Gwk0i5BOTWi5imZf1yWd0WFVtI0/edit# and start moving/updating information into a wiki (first step, link document in wiki)

**Comment by brittany-johnson** [comment]
https://github.com/openstax/cnx/wiki 
I've created 3 new pages in the CNX wiki. This documentation was taken from the cheatsheet
