### ISSUE TITLE
APUSH: Table caption position

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1550]
@mwest-WWprod commented on [Mon Oct 28 2019](https://github.com/openstax/tutor/issues/675)

GLOBAL
APUSH Reference View

Post-10/23 rollout, table captions now appear above table numbers, as though they are the bottommost cell in the specified table. We should emulate the positioning of figure captions if possible.

This issue has the same name but differs from earlier, closed issue #608.

Current Output
![TablePosition_2 2_APUSH](https://user-images.githubusercontent.com/19212926/67731130-8ebeed80-f9cd-11e9-927b-5dc1d0a98cbf.PNG)

---

@carlycurran commented on [Wed Oct 30 2019](https://github.com/openstax/tutor/issues/675#issuecomment-547976323)

@nathanstitt FYI, I don't think this is the case for every table, which seems odd. Can you take a look? It might be a content issue?

---

@nathanstitt commented on [Wed Oct 30 2019](https://github.com/openstax/tutor/issues/675#issuecomment-548020256)

These will have to be fixed in the content.   The  caption is in a `caption` element inside the table, but the "Table 2.1" text contained in a separate `div` element that appears after the table.  Since they're in separate containers there's no way to position the div inside the table.

To fix this the `os-caption-container` div needs to be placed inside the `caption` on the table. 

Here's the existing markup:
![image](https://user-images.githubusercontent.com/79566/67882259-f54c2480-fb0f-11e9-82dd-169da26a60da.png)

---

@carlycurran commented on [Wed Oct 30 2019](https://github.com/openstax/tutor/issues/675#issuecomment-548021638)

@openstaxalina @oscryan FYI on this table caption 

---

@openstaxalina commented on [Wed Oct 30 2019](https://github.com/openstax/tutor/issues/675#issuecomment-548027760)

Thank you for the investigation -- I think this is a change for the Styles devs.  I'll move this issue to our board.

**Comment by openstaxalina** [comment]
@helenemccarron @brittany-johnson I thought that this issue was Tutor-related, but it seems related to how we handled table titles/captions in the APUSH recipe (?).  I moved this into the current sprint in the interest of grouping APUSH issues together and possibly completing the known issues this sprint.  The priority, though is still:

# 1: #https://github.com/openstax/webview/issues/2278
# 2: https://github.com/openstax/cnx-recipes/issues/1429
# 3: this issue

**Comment by brittweinstein** [comment]
@openstaxalina will do content investigation and share link. Helene or BrittanyJ will do recipe investigation.

**Comment by openstaxalina** [comment]
screenshot of markup:
<img width="989" alt="Screen Shot 2019-11-11 at 10 16 11 AM" src="https://user-images.githubusercontent.com/7863733/68602623-50650c00-046c-11ea-996d-7c725a447283.png">

**Comment by openstaxalina** [comment]
This is the only table with a caption in the first six chapters.

**Comment by openstaxalina** [comment]
@oscryan would you be able to copy this module to easyvm5 if it is not there already?  https://content05.cnx.org/contents/CmIfJ6vh@56.1:ati9GAKm@18/2-2-%F0%9F%93%96-Chapter-2-Introductory-Essay-1607-1763

Please post the link to the content on easyvm5 once you have it.

**Comment by oscryan** [comment]
https://legacy-easyvm5.cnx.org/content/m77400/latest/?collection=col29684/latest

**Comment by oscryan** [comment]
or https://easyvm5.cnx.org/content/m77400/latest/?collection=col29684/latest

**Comment by helenemccarron** [comment]
Captions should now display within `caption-container`
![2019-11-11_11-57-01](https://user-images.githubusercontent.com/8514591/68609475-fd468580-047a-11ea-9c75-be78182741a7.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a765af83-b63f-40ae-80be-986a67dfbbf0)
