### ISSUE TITLE
biology &  apbiology: style module headers

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1555]
Module headers in Biology and AP Biology should be styled with specs from #1286

**Comment by Stackblocks** [comment]
Displaying as specified in Biology, but not AP Biology

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/10d17882-9981-4722-8a30-05cba4a6c3ee)

**Comment by helenemccarron** [comment]
![2019-11-08_10-45-57.png](https://images.zenhubusercontent.com/5b06d3244b5806bc2bd47abf/528f6783-03c2-43e4-b2c3-2216db497c3c)

Confirmed - per Larissa : `#0074BC`, knobs and dials updated. 

Note: acrobat changed the hex value slightly but the output is the same and the value in code is confirmed. 
https://github.com/openstax/cnx-recipes/pull/1554/files#diff-081e7ac017a9b29f5b2d55dc4fe05ab1R781
