### ISSUE TITLE
Biology - all issues in one.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1556]
1. Gap where screen from link should be.
![Screenshot from 2019-10-31 14-55-38](https://user-images.githubusercontent.com/47241114/67962295-3f5f0400-fbfd-11e9-8cbf-feff16b45606.png)
2. No margines for headers.
![Screenshot from 2019-10-31 14-16-24](https://user-images.githubusercontent.com/47241114/67962951-1e4ae300-fbfe-11e9-8984-db6f49fe77c7.png)
3. Figure captions aren't styled
![Screenshot from 2019-10-31 16-48-57](https://user-images.githubusercontent.com/47241114/67963137-6833c900-fbfe-11e9-89e3-f2202030f941.png)
4. Link to learning - unstyled.
![Screenshot from 2019-10-31 16-50-52](https://user-images.githubusercontent.com/47241114/67963310-a9c47400-fbfe-11e9-9b51-b62261c0ba66.png)
5. Chapter outline - unstyled.
![Screenshot from 2019-10-31 16-52-28](https://user-images.githubusercontent.com/47241114/67963449-ebedb580-fbfe-11e9-88a0-0f0e6d7d5011.png)
6. Tables - unstyled
![Screenshot from 2019-10-31 16-57-31](https://user-images.githubusercontent.com/47241114/67965284-11c88980-fc02-11e9-9642-5ef7a2fb7685.png)
![Screenshot from 2019-10-31 17-20-10](https://user-images.githubusercontent.com/47241114/67965648-bcd94300-fc02-11e9-8fe3-de1eefd2f50e.png)
7. Footnotes - unstyled, sometimes in the middle of the page.
![Screenshot from 2019-11-04 16-21-59](https://user-images.githubusercontent.com/47241114/68135001-42bafe00-ff23-11e9-8648-e70007c9e756.png)

**Comment by ajluk** [comment]
The styles to Footnotes and Link to Learning notes haven't been added within this branch: #1554

**Comment by Stackblocks** [comment]
Closing this as it is a composite of the other open cards for u.u.
