### ISSUE TITLE
Biology & AP Biology: Style ul in Preface

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1562]
Unordered lists in Preface need to have left-margin  added.

**Comment by openstaxalina** [comment]
@ajluk I moved this back to "In Progress" (FYI).

**Comment by Stackblocks** [comment]
Displaying OK in Biology, but not in AP Biology.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/07079c9a-047f-466b-916e-00c64bbfa43a)

**Comment by helenemccarron** [comment]
This will work when we enable release flags next release.

**Comment by helenemccarron** [comment]
Please regression test the biology part then send back to v.v and backlog

**Comment by MartaSztuka** [comment]
AP biology Preface styled.
![Screenshot from 2019-11-26 17-12-36](https://user-images.githubusercontent.com/47241114/69651198-0422ea00-1070-11ea-8bac-3673df82b457.png)
![Screenshot from 2019-11-26 17-12-28](https://user-images.githubusercontent.com/47241114/69651199-04bb8080-1070-11ea-9fe2-853884dd837d.png)
