### ISSUE TITLE
college physics: style Introduction page

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1565]
Add style to Introduction page in College Physics with specs from Carnival Theme.

**Comment by wilkus27** [comment]
**Theme Design Specs**

1. New shape: `Chapter Intro With Abstract`
Differences to `Chapter Intro` shape:
- new component `OutlineObjectiveLearning` in `IntroBody` with property: `margin-left: 1.5rem,`
2. Physics specific specs
- `Outline` - `background-color: B5`
- `SplashFigureBg` - `background-color: B5`
3. New color in Color Map
`physicsIntroColor: (_ref: "scheme:::B5"),`

**Comment by wilkus27** [comment]
NOTE for tester: https://github.com/openstax/cnx-recipes/pull/1587#issuecomment-556054254

**Comment by MartaSztuka** [comment]
Introduction page styled.
![Screenshot from 2019-11-22 16-36-16](https://user-images.githubusercontent.com/47241114/69439040-75982b00-0d46-11ea-9abd-65eb6d63ef2f.png)
