### ISSUE TITLE
Biology: add style to EOC sections

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1567]
Eoc sections should be styled according to specs #1085, #1074 and https://docs.google.com/spreadsheets/d/1piXDN2me_xyD2CtqODOk9irW69z4JflMwpOf0KV-Lak/edit#gid=1327731354&range=A26:B26

**Comment by MartaSztuka** [comment]
EoC styled.
![Screenshot from 2019-11-20 10-26-54](https://user-images.githubusercontent.com/47241114/69226560-a2024a80-0b80-11ea-96ee-43b2c1917018.png)
