### ISSUE TITLE
Enable goodbye-warnings flag in Biology 2e

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1571]
Related issue:  #1499
Flag 17 goodbye-warnings
Flags description is available in his document: https://docs.google.com/document/d/1ziR2PcSvioOLAHSRNWZga3m-8DlUM_qaskIjpWtoS60/edit?pli=1#heading=h.qyw3d826jh31

**Comment by Stackblocks** [comment]
Working correctly when generating on u.u.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/21d65445-ccfd-4272-8c47-e9a3c2540f90)
