### ISSUE TITLE
college physics: style notes

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1588]
All notes in College Physics should be styled with specs from Carnival Theme.

**Comment by wilkus27** [comment]
Ready for testing. Specs are added to Theme Design Specs table.

**Comment by MartaSztuka** [comment]
![Screenshot from 2020-01-13 13-25-19](https://user-images.githubusercontent.com/47241114/72256100-b440b800-3608-11ea-9367-549f54c61be0.png)
![Screenshot from 2020-01-13 13-24-24](https://user-images.githubusercontent.com/47241114/72256102-b4d94e80-3608-11ea-87d3-9ed40dc7fbb2.png)
