### ISSUE TITLE
Biology 2e: add book specific color to Learning Objective Abstract

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1589]
Learning Objective Abstract should have a book specific color specified in specs: #1155, https://docs.google.com/spreadsheets/d/1piXDN2me_xyD2CtqODOk9irW69z4JflMwpOf0KV-Lak/edit#gid=160988115, carnival theme: learning objectives: #1077.

**Comment by MartaSztuka** [comment]
Colour as specified.
![Screenshot from 2019-11-19 16-52-16](https://user-images.githubusercontent.com/47241114/69162919-a598c180-0aed-11ea-976e-a2460ba15fc9.png)
