### ISSUE TITLE
Carnival Theme superscript degree Bug

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1591]
# Scenario
College Physics with Carnival theme doesn't treat degree symbols (or mathcircles) the same as old theme MathML; it makes a superscript circle not high enough and has an underline on it.
# Steps to Reproduce

* **How many times were you able to reproduce the issue?** 

* **Images or Screenshots Included:** [x ] Yes  [ ] No  (_attach below_)
current PDF left, Carnival right
<img width="1122" alt="Screen Shot 2019-11-14 at 9 25 00 AM" src="https://user-images.githubusercontent.com/1895432/68870671-daa5ae00-06c0-11ea-9855-fb4ac6687a79.png">

# Environment:

* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org  
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact

* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan 

# Acceptance Criteria

**Comment by oscryan** [comment]
degrees are ok in Chemistry Carnival

**Comment by helenemccarron** [comment]
![2020-01-09_10-56-55.png](https://images.zenhubusercontent.com/5b06d3244b5806bc2bd47abf/3bea3148-120a-4c35-a3f9-06c17a8410d2)

**Comment by openstaxalina** [comment]
Larissa confirmed display is acceptable.

**Comment by marcjeannott** [comment]
Confirmed on College Physics staging w/ style

![2020-01-22_10-25-11.png](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/76326930-a5b6-4633-a4d8-6d21af1d2dd3)
