### ISSUE TITLE
Add style to Link to Learning in Biology 2e

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1592]
Link to Learning notes should be styled according to specs from this issue: https://github.com/openstax/cnx-recipes/issues/1082

**Comment by MartaSztuka** [comment]
styled.
![Screenshot from 2019-11-15 17-24-04](https://user-images.githubusercontent.com/47241114/68958804-1b8ae900-07cd-11ea-9d19-08344ceef062.png)
