### ISSUE TITLE
CSS is not compiling properly when running docker-compose run --rm bake-book

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#1594]
# What happened?

After making changes to the `hsphysics` recipe and running `docker-compose run --rm bake-book hsphysics`, I do not see any of my changes to the recipe reflected in `hs-physics.css`. 

If I compile the CSS manually with `$(npm bin)/node-sass ./recipes/books/hs-physics/book.scss ./recipes/output/hs-physics.css`, my changes are then reflected in `hs-physics.css`

# Reproducibility Details

- Make a change in `./recipes/books/hs-physics/_config.scss`. (ex: change the title or name of an element)
- Run `docker-compose run --rm bake-book hsphysics`
- Check `hs-physics.css` for the change
- You should see none
- Then run `$(npm bin)/node-sass ./recipes/books/hs-physics/book.scss ./recipes/output/hs-physics.css`
- Check `hs-physics.css` for the change
- You should see the change

**Comment by karenc** [comment]
`bake-book` should be compiling the recipe:

https://github.com/openstax/cnx-recipes/blob/master/script/bake-book#L58-L59

```bash
  do_progress_quiet "Compiling CSS file" \
    ./script/build-recipes "${recipe_name}"
```

We're giving the `recipe_name` to the `build-recipes` script but it looks like the script is expecting the book name:

https://github.com/openstax/cnx-recipes/blob/master/script/build-recipes#L5-L12

```bash
arg1=$1

# Pull in the BOOK_CONFIGS
source ./books.txt || exit 1

if [ ! "${arg1}" == "" ]; then
  BOOK_NAMES=("${arg1}")
fi
```

^ The first argument is expected to be a book name.

Most of the time our book names and recipe names are the same so we never even noticed this bug.  This time, the book is called `hsphysics` and the recipe is called `hs-physics` so the recipe isn't being compiled.

**Comment by lwtchu** [comment]
idk what this is for and this ? isn't happening anymore
