### ISSUE TITLE
Real Smol Mu Bug

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1596]
# Scenario
In many instances of the character μ, Carnival math in College Physics makes it extra extra tiny. Semantically appropriate, but not good formatting.
# Steps to Reproduce

* **How many times were you able to reproduce the issue?** 

* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="1118" alt="Screen Shot 2019-11-14 at 1 34 05 PM" src="https://user-images.githubusercontent.com/1895432/68890072-cf17ae80-06e3-11ea-9c04-2060e0a3150b.png">

# Environment:

* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org  
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact

* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan 

# Acceptance Criteria

**Comment by oscryan** [comment]
This also seems to happen with the ½ character sometimes:
<img width="340" alt="Screen Shot 2019-11-14 at 1 39 02 PM" src="https://user-images.githubusercontent.com/1895432/68890320-3b92ad80-06e4-11ea-8e94-89149b4847ce.png">

**Comment by oscryan** [comment]
Also sigmas
<img width="1289" alt="Screen Shot 2019-11-14 at 3 49 20 PM" src="https://user-images.githubusercontent.com/1895432/68899071-74d41900-06f6-11ea-89dd-6c51aaf97206.png">

**Comment by oscryan** [comment]
and absolute value bars
<img width="1287" alt="Screen Shot 2019-11-14 at 4 16 51 PM" src="https://user-images.githubusercontent.com/1895432/68900818-48ba9700-06fa-11ea-92eb-a01caa2742b3.png">

**Comment by helenemccarron** [comment]
This should be fixed: 
![2020-01-08_15-48-19](https://user-images.githubusercontent.com/8514591/72023271-f00a0500-3237-11ea-835c-223ecbe88ca7.png)

**Comment by openstaxalina** [comment]
Larissa confirmed display is acceptable.

**Comment by marcjeannott** [comment]
Verified using cops on staging. It's a good size.

![2020-01-22_10-20-27.png](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/a7f4899c-de56-4de8-827b-ec0b38743703)
