### ISSUE TITLE
Biology 2e: Add book specific color to Evolution Connection notes

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1599]
Evolution Connection note in Biology should have a book specific color according to : https://docs.google.com/spreadsheets/d/1vW0EHvn8fZgvTxZIm9xQXsqsnIDcolqwt5rWKtx4JEY/edit#gid=1663003137

**Comment by MartaSztuka** [comment]
book specific colour added.
![Screenshot from 2019-11-15 16-46-53](https://user-images.githubusercontent.com/47241114/68956972-69055700-07c9-11ea-823d-54f9ea1fae0a.png)
