### ISSUE TITLE
college physics: style figures

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1601]
Figures in College Physics should be styled with specs from Carnival Theme.

**Comment by MartaSztuka** [comment]
Figures styled
![Screenshot from 2019-11-22 12-12-23](https://user-images.githubusercontent.com/47241114/69421518-82eeee80-0d21-11ea-8648-11fc10c38f4c.png)

**Comment by MartaSztuka** [comment]
Figures styled.
![Screenshot from 2019-11-22 15-44-07](https://user-images.githubusercontent.com/47241114/69434999-066b0880-0d3f-11ea-9c20-2c4b0e18a021.png)
