### ISSUE TITLE
carnival theme: equations

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1605]
**Numbered and shaded**
- background color: Grey1
- number in a box .025rem stroke
- number display in the middle of equation on the right side
- padding between number and border 0.5rem
- centered

**Numbered and non-shaded**
- number in a box .025rem stroke
- number display in the middle of equation on the right side
- padding between number and border 0.5rem
- centered

**Unnumbered and non-shaded**
- centered

**Comment by wilkus27** [comment]
**Theme Design Specs**

1. New shape `EquationShape`
- Components:
`EquationContainer`

![image](https://user-images.githubusercontent.com/40228854/69428007-8c338780-0d30-11ea-82b6-b73cd518e622.png)

- Properties
`EquationContainer`:
```
display: flex,
align-items: center,
justify-content: center,
margin-bottom: 1.5rem,
```
2. New shape `NumberedEquationShape`
- Components:
```
EquationContainer
                 EquationNumber
```
![image](https://user-images.githubusercontent.com/40228854/69428421-6f4b8400-0d31-11ea-8bca-1728fa27ef8f.png)

- Properties
`EquationContainer`:
```
position: relative,
display: flex,
flex-direction: row,
align-items: center,
justify-content: center,
margin-bottom: 1.5rem,
```
`EquationNumber`
```
position: absolute;
right: 0;
top: 50%;
transform: translate(0, -50%);
border-width: 0.025rem;
border-style: solid;
line-height: normal;
padding: 0.5rem;
```

**Comment by wilkus27** [comment]
Note for tester:

in Chemistry are styled unnumbered equations
in Physics - numbered

Up to this moment there is no book with numbered and shaded equations. This kind of equation have to be styled in the future.

**Comment by MartaSztuka** [comment]
College Physics
![Screenshot from 2019-11-22 16-48-05](https://user-images.githubusercontent.com/47241114/69440333-f22c0900-0d48-11ea-93d5-53c69a9047bd.png)
Chemistry
![Screenshot from 2019-11-22 17-07-19](https://user-images.githubusercontent.com/47241114/69441230-9d898d80-0d4a-11ea-97c1-ba32b2665ed3.png)
