### ISSUE TITLE
make sure math is using STIX font

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1606]
# Scenario
It currently is not. Make sure MATH ONLY is using Stix

# Steps to Reproduce

* **How many times were you able to reproduce the issue?** 

* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)

# Environment:

* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org  
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact

* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan 

# Acceptance Criteria

**Comment by helenemccarron** [comment]
@lwtchu how can this be tested, I am not seeing what font is actually used in the output (HTML or PDF). Mathify is set to `font: 'STIXIntegralsUp',`

**Comment by lwtchu** [comment]
@helenemccarron i'm thinking it might have to be by eye. and knowing what stix font looks like.  

i think one easy way is to look for a 9 in math font. This is STIX on the left. Alegreya on the right.
![Screen Shot 2020-01-08 at 4 01 03 PM](https://user-images.githubusercontent.com/11299125/72019864-1cba1e80-3230-11ea-92ff-7901d3843ad9.png)

**Comment by helenemccarron** [comment]
Ok, I'll try to figure it out, thank you.

**Comment by lwtchu** [comment]
@helenemccarron this was in the ch 1 eoc content - i think if you search specifically for 20.9940 you'll probably find it since it's so specific.

**Comment by helenemccarron** [comment]
I am using some random test data but does this look better? @lwtchu 
![2020-01-08_16-24-55](https://user-images.githubusercontent.com/8514591/72021392-87b92480-3233-11ea-87c4-6a6a96178f24.png)
![2020-01-08_16-23-21](https://user-images.githubusercontent.com/8514591/72021406-8c7dd880-3233-11ea-84b4-edb8dbb07d96.png)

**Comment by helenemccarron** [comment]
Also, would you have a location for an integral by any chance? The value I posted above isn't support, only STIX-web and i want to make sure the integrals are displaying properly.

**Comment by lwtchu** [comment]
@helenemccarron  oh this looks like stix. :joy: maybe at some point y'all fixed it.  

whenever you're ready you can generate a pdf iwth the new stuff and i can look.

as for integrals...are we have one in university physics vol 3, 7.4 the quantum particle in a box equation 7.33

**Comment by helenemccarron** [comment]
Oh, no no, this is my test data locally, I am fixing all the things in Mathify. This will be useful for testing tough :D  I am glad to hear this looks right. Let me see if I can add that particular integral and test it, thank you!

**Comment by helenemccarron** [comment]
And the result, do those integral look ok? @lwtchu 
![2020-01-08_16-46-29](https://user-images.githubusercontent.com/8514591/72022601-7cb3c380-3236-11ea-8a95-2f8d8017f2b0.png)

**Comment by lwtchu** [comment]
yep! this looks good

**Comment by helenemccarron** [comment]
wooohooooo! Thank you!!!

**Comment by lwtchu** [comment]
<img width="215" alt="Screen Shot 2020-01-27 at 10 29 00 AM" src="https://user-images.githubusercontent.com/11299125/73193249-def23c80-40ef-11ea-936d-6734ffac5053.png">
verified
