### ISSUE TITLE
Some exercises not fetching in hsphysics

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#1607]
# What happened?
The steps that I took: 

- `docker-compose pull neb`
- `docker-compose run neb neb --version` -> `Nebuchadnezzar 9.4.0+2.g8c87ab2`
- `docker-compose build neb`

- `docker-compose run --rm fetch-book --with-resources hsphysics`
- `docker-compose run --rm assemble-book hsphysics`
- `docker-compose run --rm bake-book hsphysics`

Missing exercises is the baked content: 
![Screen Shot 2019-11-15 at 1.22.50 PM.png](https://images.zenhubusercontent.com/5b0d6efdd59b032fbd122962/83f23d93-9932-4c43-bf32-289bae1e4a0a)
![Screen Shot 2019-11-15 at 1.24.10 PM.png](https://images.zenhubusercontent.com/5b0d6efdd59b032fbd122962/cbd430d6-1f2b-4df4-a8ad-b117450c5d3d)

**Comment by Bkblodget** [comment]
content is coming from content04.cnx.org

**Comment by karenc** [comment]
I fetched the book and assembled (which fetches exercises):

```
docker-compose run --rm fetch-book hsphysics
docker-compose run --rm assemble-book hsphysics
```

I looked in `data/hsphysics/collection.assembled.xhtml` and compared it with all the exercises in `data/hsphysics/m10007/index.cnxml` and they were all there.

I think it's something that happened during baking.

**Comment by karenc** [comment]
On slack:

> BrittanyJ: Okay, I was just looking for this question:
> 
> ```
> How would the following changes affect a line that is neither horizontal nor vertical and has a positive slope?
> ```
> 
> Which is part of a `grasp check` note. I was able to find the text, it just wasn’t in the location we were expecting :facepalm: 
> I was also just counting all of the exercises and it doesn’t seem that they are missing, they are also just going in weird places. The number of exercises I counted matches the number of blank numbers in the screenshot I took in the issue :skull:
> I think its safe to say this was a false alarm??
> I’m so sorry for the confusion and wasted time!

:+1:
