### ISSUE TITLE
carnival theme: in footnotes padding-bottm need to be decreased

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1613]
Padding-bottom in Footnotes need to be decreased according to discussion with Larissa and Helene. The change is applied in cell B73 (v-grid(1) = 1,5 rem;) in Theme Design Specs (https://docs.google.com/spreadsheets/d/1vW0EHvn8fZgvTxZIm9xQXsqsnIDcolqwt5rWKtx4JEY/edit#gid=1663003137).

![image](https://user-images.githubusercontent.com/55203598/69137573-520e7f80-0abd-11ea-9673-379e96527c5c.png)

**Comment by MartaSztuka** [comment]
Tested in Chemistry
![Screenshot from 2019-11-20 14-56-43](https://user-images.githubusercontent.com/47241114/69245294-dd177480-0ba6-11ea-8a59-924574f1822c.png)

 and Biology
![Screenshot from 2019-11-20 14-40-00](https://user-images.githubusercontent.com/47241114/69245298-ddb00b00-0ba6-11ea-9f4f-30e7ba219c1e.png)
