### ISSUE TITLE
Biology 2e: Visual Connection notes are missing class 

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1615]
Some Visual Connection notes in Biology 2e are missing their specific class (`visual-connection`). This is the link to the document containing screens from baked file with all the places in the book where it occurs: https://docs.google.com/document/d/15hXsumn8P9HIHOFrH-verbY2UMRH0uNDomIk5m3uhSA/edit

**Comment by lwtchu** [comment]
We're having some issues updating the class on katalyst01 but will update you if it's done.

The issue is they're tagged as `type="visual-connection"` and should be `class="visual-connection"`

**Comment by oscryan** [comment]
replaced all type="visual-connection" with class="visual-connection"
