### ISSUE TITLE
APUSH Review and Free Response Question Numbering

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1617]
@yblock commented on [Tue Nov 19 2019](https://github.com/openstax/tutor/issues/716)

### Description 

Pattern: After AP Practice Questions occur, the numbering for questions in following modules are messed up. See the devil’s number and no numbers.

![Screen Shot 2019-11-19 at 12 57 51 PM](https://user-images.githubusercontent.com/5865292/69179600-6a889500-0ad1-11ea-9129-6be97397ea6d.png)

----------------

**Expected behavior:** 
It should reset every question type and every module.
Free response should start at 1, review questions start at 1…etc. and does the same in next module

**Steps to Reproduce the issue:** 
https://staging.cnx.org/contents/uNVgf323@7.1:tr825PwI@2/1-3-%F0%9F%94%8E-Native-People

----------------
### Acceptance Criteria
Give criteria for acceptance.

### Acceptance Tests for testrail
- **title**: 
- **categories**:

> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Tests that will be added or changed 
Written explanations of the tests that will have to be added or modified to test this bug. 

----------------

- **Product:** - 
- **User Type:** - 
- **Username:** -
- **URL:** -
- **Course number:** -
- **Course type:** -

----------------
**Environment:**

- **Instance:** -
- **OS:** -
- **Browser:** -
- **Browser Version:** -

----------------
**Images or Screenshots** (_attach below_)

---

@lwtchu commented on [Tue Nov 19 2019](https://github.com/openstax/tutor/issues/716#issuecomment-555670294)

Oops moving this to cnx-recipes

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image](https://user-images.githubusercontent.com/12678235/69438135-23d1af80-0d0a-11ea-93f1-f9a8107a025c.png)


![image](https://user-images.githubusercontent.com/12678235/69438036-04d31d80-0d0a-11ea-8b36-eb90e3c5ea84.png)
