### ISSUE TITLE
Biology for AP Courses: add styles to exercises in EoC

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1620]
The exercises in the EOC:

- [x] - Review Questions
- [x] - Critical thinking questions
- [x] - Test Prep for AP® Courses
- [x] - Science Practice Challenge Questions

 should be styled according to: https://docs.google.com/spreadsheets/d/1piXDN2me_xyD2CtqODOk9irW69z4JflMwpOf0KV-Lak/edit#gid=2076412410

Changes in Theme Design Specs:
New shapes in the **EocExerciseWithoutSubtitle** shape component:

- **Review**
- **Critical thinking**
- **TestPrep**
- **SciencePractice**

They all have have a common components and properties like so:
Container: (
            column-count: 2,
            column-gap: 2.4rem,
            column-width: auto,
        ),
EocHeader:(
            font-family: (_ref: 'typography:::sansFont'),
            font-weight: bold,
            font-size: font-scale(4), 
            line-height: line-height(4),
            text-transform: uppercase,
            column-span: all,
             // color: book specific, defined in book.scss file
        ),
ProblemNumber: (
            color: (_ref: 'colorMap:::fontBodyColor'),
            font-weight: bold,
            text-decoration: none,
        ),
ProblemDivider: (
            margin-right: h-grid(1)
        ),
    ), 

All EoC components  have a **book specific color** for APBiology set to **B7**. 

Info for the testers:

The issue regarding images form the TEST PREP FOR AP® COURSES exercices will be created and the changes will be added within another PR (#1634): 
![image](https://user-images.githubusercontent.com/55203598/69257841-01318080-0bbc-11ea-80e4-780655f3fc4c.png)

**Comment by MartaSztuka** [comment]
Space between 1, 2, 3, and abc answers is too big.
1.
![Screenshot from 2019-11-27 11-20-26](https://user-images.githubusercontent.com/47241114/69858495-6a875280-1292-11ea-948e-60ff7a7c546b.png)
2. ![Screenshot from 2019-11-27 10-50-34](https://user-images.githubusercontent.com/47241114/69858436-49befd00-1292-11ea-8154-b65688a28a7f.png)
3. ![Screenshot from 2019-11-27 11-13-14](https://user-images.githubusercontent.com/47241114/69858441-4b88c080-1292-11ea-8c0b-94faedf4a592.png)
4. ![Screenshot from 2019-11-27 11-13-26](https://user-images.githubusercontent.com/47241114/69858447-4deb1a80-1292-11ea-8d1e-3e13eb571610.png)

**Comment by ajluk** [comment]
This Issue also concerns applying margins to ordered and unordered lists in the following books:
    Anatomy,
    Chemistry,
    Biology 2e,
    Biology for AP Courses,
    College Physics,
    High School Physics,

partly includes:

    University Physics,
    Microbiology

Elements that have added list styles:

    Preface,
    Module,
    EoC (Summary, Exercises),
    Answer Key,
    Appendices

Within this PR I have also added styles to images and tables in EoC Exercises for Biology 2e, Biology for AP Courses and College Physics.

Documentation for testing purposes is available in this document: https://docs.google.com/document/d/1cry7GPpIZ00sCudMtYExkw3Y6vEH8NjfiVGUT8DgLCk/edi

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-02-07 16-02-12](https://user-images.githubusercontent.com/47241114/74040333-cd4c4700-49c3-11ea-8c4a-97721830b4f2.png)
![Screenshot from 2020-02-07 15-58-58](https://user-images.githubusercontent.com/47241114/74040335-cde4dd80-49c3-11ea-9722-6950aaf22b94.png)
![Screenshot from 2020-02-07 15-57-25](https://user-images.githubusercontent.com/47241114/74040337-cf160a80-49c3-11ea-934e-ed106f79bc08.png)
![Screenshot from 2020-02-07 15-57-12](https://user-images.githubusercontent.com/47241114/74040372-e48b3480-49c3-11ea-81c7-5dac63a21dd5.png)
