### ISSUE TITLE
"Freeze" Recipe and Create Additional Dropdown for Books Already or Soon to Be in REX

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1624]
@openstaxalina commented on [Wed Nov 20 2019](https://github.com/openstax/oer.exports/issues/3985)

# What happened?

We need to "freeze" (or pin at a version) the recipes for books that we have already QA'd in REX.  This will allow us to continue to iterate on those recipes for baked styles, while having a stable recipe version that REX can continue to use until they are ready for our new recipe.  This affects the following books, grouped below by shared recipe:

- [ ] Chemistry 2e + Chemistry: Atoms First 2e
- [ ] Anatomy & Physiology
- [ ] Biology 2e + Concepts of Biology
- [ ] AP Biology
- [ ] Microbiology
- [ ] College Physics
- [ ] AP Physics
- [ ] University Physics (Vols 1-3)
- [ ] Astronomy
- [ ] Calculus (Vols 1-3)
- [ ] Introductory Statistics + Introductory Business Statistics
- [ ] American Government 2e
- [ ] U.S. History
- [ ] Principles of Accounting (Vols 1-2)
- [ ] Economics 2e (Regular + AP - 5 titles)
- [ ] Introduction to Sociology 2e
- [ ] Introduction to Business
- [ ] Business Ethics
- [ ] Principles of Management
- [ ] Organizational Behavior
- [ ] Precalculus (includes College Algebra + Algebra & Trigonometry)

The steps to do this include:

1) for each group of books listed above, duplicate the `[book title] with recipe` entry in the dropdown.
2) retitle the new entry `[book name] REX recipe`
3) this new entry will not always get the latest recipe, the way the original entries do.  instead, this should be frozen/pinned at the recipe version as of today's date
4) add symlink for this new entry 
5) proceed through verification and deployment steps...

**Comment by lwtchu** [comment]
![Screen Shot 2019-12-19 at 12 16 32 PM](https://user-images.githubusercontent.com/11299125/71199476-a42cf700-225b-11ea-975d-6cedbe638318.png)
I'm here to reopen this card and to say Sociology 2e and University Physics are missing their locked recipes on production.

**Comment by helenemccarron** [comment]
![2020-01-10_16-20-58](https://user-images.githubusercontent.com/8514591/72190498-49ec0580-33c5-11ea-9945-b18dbf6131dd.png)
![2020-01-10_16-20-39](https://user-images.githubusercontent.com/8514591/72190503-4bb5c900-33c5-11ea-839f-0d8110dce184.png)
Confirmed to work on easyvm5
