### ISSUE TITLE
Chapter Outline Cropped - Chemistry

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1625]
All locations where Chapter Outline is cropped:
1.
![Screenshot from 2019-10-21 13-20-28](https://user-images.githubusercontent.com/47241114/67201126-d958cc80-f405-11e9-8539-a80653ca5cbe.png)
2. ![Screenshot from 2019-10-21 13-19-35](https://user-images.githubusercontent.com/47241114/67201127-d9f16300-f405-11e9-9cd0-bcd380bf9701.png)
3. ![Screenshot from 2019-10-21 13-24-01](https://user-images.githubusercontent.com/47241114/67201211-11f8a600-f406-11e9-9ac6-69f8f6b6d70e.png)
4. ![Screenshot from 2019-10-21 15-35-16](https://user-images.githubusercontent.com/47241114/67209878-6f95ee00-f418-11e9-99b7-04b8c64fa141.png)
5. ![Screenshot from 2019-10-18 15-04-15](https://user-images.githubusercontent.com/47241114/67096948-707d1480-f1b9-11e9-8787-8c6f20ba684b.png)

**Comment by lwtchu** [comment]
<img width="771" alt="Screen Shot 2019-12-19 at 10 25 51 AM" src="https://user-images.githubusercontent.com/11299125/71190404-24e2f780-224a-11ea-8c06-30c05ddea33e.png">

[chapteroutline.pdf](https://github.com/openstax/cnx-recipes/files/3984528/chapteroutline.pdf)
Can we tweak this to the following specs:

- Blue bar is 2in wide
- All font is base font-size(0) (9pt) (12px) , IBM Plex Sans

If there are a lot more 1 off issues, please let us know.

**Comment by brittweinstein** [comment]
https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/1475

**Comment by lwtchu** [comment]
<img width="771" alt="Screen Shot 2019-12-19 at 10 25 51 AM" src="https://user-images.githubusercontent.com/11299125/71190404-24e2f780-224a-11ea-8c06-30c05ddea33e.png">

[chapteroutline.pdf](https://github.com/openstax/cnx-recipes/files/3984528/chapteroutline.pdf)
Can we tweak this to the following specs:

- Blue bar is 2in wide
- All font is base font-size(0) (9pt) (12px) , IBM Plex Sans

If there are a lot more 1 off issues, please let us know.

#1628

**Comment by wilkus27** [comment]
Unfortunately, even with smaller font size and wider box some of the Chapter Outlines are too big:

![image](https://user-images.githubusercontent.com/40228854/75236142-a82a4780-57bd-11ea-84e6-cb3de0f3e6b7.png)

Decision is to apply in Chemistry `FullWidthChapterIntroShape`.

**Comment by wilkus27** [comment]
#### New specs from Larissa:
- chapter outline font size font-scale(1) 
- module link font-scale(0)
- Introduction text spanned to the right

![image](https://user-images.githubusercontent.com/40228854/75336498-8d260900-588b-11ea-97bf-4b0756714ecb.png)

**Comment by wilkus27** [comment]
Those changes cover also **College Physics**:

![image](https://user-images.githubusercontent.com/40228854/75437447-7dbfc200-5956-11ea-9502-23c76c8d6f47.png)

Additional specs for this book:

- Text in lists font size: font-scale(0)
- Bottom margin for ul list: 0.75rem

* @lwtchu you asked for the 1rem, but because we are using v-grid functions to set margins I could change it to 0.75rem.

**Comment by lwtchu** [comment]
@wilkus27 that's fine - sorry i forgot we're not using rems anymore. but the 0.75 is fine

**Comment by wilkus27** [comment]
## Changes to provide to Theme Design Specs

### Shape: `FullWidthChapterIntroShape`

_New component:_ `OutlineList`
_Properties:_
```
margin-bottom: half-v-grid(1),
```
![image](https://user-images.githubusercontent.com/40228854/75553497-c64fac00-5a38-11ea-9034-c0d6bcc246e2.png)

_Component:_ `OutlineTitleBottomBorder`
_Changed properties:_
```
width: 5.20104in;
margin-left: 10.39167rem;
```
![image](https://user-images.githubusercontent.com/40228854/75553535-dd8e9980-5a38-11ea-8381-3f6fa8436ffb.png)

_Component:_ `Outline`
_Changed properties:_
```
width: 6.5in,
font-size: font-scale(0),
line-height: line-height(0),
```
![image](https://user-images.githubusercontent.com/40228854/75553583-f8f9a480-5a38-11ea-87cd-c58b88c6c3cf.png)

_Component:_ `OutlineTitle`
_Changed properties:_
```
font-size: font-scale(1),
line-height: font-scale(1), // value has to be the same as font size
```
![image](https://user-images.githubusercontent.com/40228854/75553620-0c0c7480-5a39-11ea-80d5-958c1dd5e549.png)

_Component:_ `OutlineObjectiveLink`
_Changed properties:_
```
font-size: font-scale(0),
```
![image](https://user-images.githubusercontent.com/40228854/75553666-234b6200-5a39-11ea-8ac5-c947a6056f1e.png)


#### Book specific settings for Chemistry in this shape

_Component:_ `SplashFigureBg`
_Properties:_
```
background-color: B4
```
_Component:_ `OutlineTitle`
_Properties:_
```
color: B4
```
_Component:_ `Outline`
_Properties:_
```
border-bottom-color: B4
```
_Component:_ `OutlineTitleBottomBorder`
_Properties:_
```
border-bottom-color: B4
```

**Comment by wilkus27** [comment]
I'm not sure if there are book specific specs for pages in Theme Design Specs, so I put them here:

- if book uses `ChapterIntroShape` it also has such settings:

_Page:_ `chapter:first`
_Properties:_
```
margin-right: 2in;
```
_Page:_ `chapter:nth(2)`
_Properties:_
```
margin-right: 2in;
```
- if book use `FullWidthChapterIntroShape` those settings should be removed

**Comment by MartaSztuka** [comment]
tested
Chemistry 2e
![Screenshot from 2020-03-02 12-58-28](https://user-images.githubusercontent.com/47241114/75674662-d0b2b580-5c85-11ea-89ae-43c2a5047be4.png)
College Physics
![Screenshot from 2020-03-02 13-02-57](https://user-images.githubusercontent.com/47241114/75675473-85010b80-5c87-11ea-99e0-b806ce5a61b2.png)
