### ISSUE TITLE
Chapter Outline - Chemistry AF

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1626]
All locations where Chapter Outline is cropped:
1.
![Screenshot from 2019-10-30 15-48-49](https://user-images.githubusercontent.com/47241114/67868976-048d9b00-fb2d-11e9-8e38-9dd325f4345c.png)
2. ![Screenshot from 2019-10-30 15-51-45](https://user-images.githubusercontent.com/47241114/67869093-3acb1a80-fb2d-11e9-93ab-2242e632a96f.png)
3. ![Screenshot from 2019-10-30 15-52-58](https://user-images.githubusercontent.com/47241114/67869179-5df5ca00-fb2d-11e9-9307-c961886666f0.png)
4. ![Screenshot from 2019-10-30 15-53-55](https://user-images.githubusercontent.com/47241114/67869277-81b91000-fb2d-11e9-9e92-7eca86f5b4ed.png)
5. ![Screenshot from 2019-10-30 15-54-40](https://user-images.githubusercontent.com/47241114/67869357-9ac1c100-fb2d-11e9-88a2-2f0b681268be.png)
6. ![Screenshot from 2019-10-30 15-55-27](https://user-images.githubusercontent.com/47241114/67869436-b75df900-fb2d-11e9-949a-ca3f6397ed1b.png)

**Comment by lwtchu** [comment]
<img width="771" alt="Screen Shot 2019-12-19 at 10 25 51 AM" src="https://user-images.githubusercontent.com/11299125/71190404-24e2f780-224a-11ea-8c06-30c05ddea33e.png">

[chapteroutline.pdf](https://github.com/openstax/cnx-recipes/files/3984528/chapteroutline.pdf)
Can we tweak this to the following specs:

- Blue bar is 2in wide
- All font is base font-size(0) (9pt) (12px) , IBM Plex Sans

If there are a lot more 1 off issues, please let us know.

**Comment by lwtchu** [comment]
<img width="771" alt="Screen Shot 2019-12-19 at 10 25 51 AM" src="https://user-images.githubusercontent.com/11299125/71190404-24e2f780-224a-11ea-8c06-30c05ddea33e.png">

[chapteroutline.pdf](https://github.com/openstax/cnx-recipes/files/3984528/chapteroutline.pdf)
Can we tweak this to the following specs:

- Blue bar is 2in wide
- All font is base font-size(0) (9pt) (12px) , IBM Plex Sans

If there are a lot more 1 off issues, please let us know.

#1628

**Comment by ajluk** [comment]
This issue will be resolved within this PR: https://github.com/openstax/cnx-recipes/pull/2089

**Comment by wilkus27** [comment]
Tested within another issue: https://github.com/openstax/cnx-recipes/issues/1475#issuecomment-603879890
