### ISSUE TITLE
Chapter Outline Cropped- Biology

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1627]
All locations where Chapter Outline is cropped:
1.
![Screenshot from 2019-11-21 11-59-35](https://user-images.githubusercontent.com/47241114/69332180-6cc82c00-0c56-11ea-8c99-fb0c8eb7f279.png)
2. 
![Screenshot from 2019-11-21 12-05-23](https://user-images.githubusercontent.com/47241114/69332552-37700e00-0c57-11ea-81c7-a79148244c24.png)
3.
![Screenshot from 2019-11-21 12-08-12](https://user-images.githubusercontent.com/47241114/69332757-a188b300-0c57-11ea-8c48-2c5ece8aa22e.png)
4.
![Screenshot from 2019-11-21 12-09-52](https://user-images.githubusercontent.com/47241114/69332854-d7c63280-0c57-11ea-8638-ffd9d0920008.png)
5.
![Screenshot from 2019-11-21 12-11-51](https://user-images.githubusercontent.com/47241114/69333007-2247af00-0c58-11ea-935e-4fdce25d43a9.png)
6.
![Screenshot from 2019-11-21 12-31-23](https://user-images.githubusercontent.com/47241114/69334386-e104ce80-0c5a-11ea-8234-33ccf2cf2708.png)
7. 
![Screenshot from 2019-11-21 12-32-36](https://user-images.githubusercontent.com/47241114/69334454-05f94180-0c5b-11ea-87eb-574f66379802.png)
8.
![Screenshot from 2019-11-21 12-33-03](https://user-images.githubusercontent.com/47241114/69334478-14dff400-0c5b-11ea-8bf4-a041118fd6f0.png)
9. 
![Screenshot from 2019-11-21 12-37-40](https://user-images.githubusercontent.com/47241114/69334791-d6970480-0c5b-11ea-8f84-91617b3e11cd.png)
10. 
![Screenshot from 2019-11-21 12-38-51](https://user-images.githubusercontent.com/47241114/69334850-e878a780-0c5b-11ea-92b2-c1e1d7fa3349.png)
11. 
![Screenshot from 2019-11-21 12-39-27](https://user-images.githubusercontent.com/47241114/69334922-fcbca480-0c5b-11ea-8e79-4417ca9b59f9.png)
12. 
![Screenshot from 2019-11-21 12-44-09](https://user-images.githubusercontent.com/47241114/69335195-a9972180-0c5c-11ea-9b87-0180b95456f1.png)
13. 
![Screenshot from 2019-11-21 12-44-56](https://user-images.githubusercontent.com/47241114/69335233-c03d7880-0c5c-11ea-95c3-95e9b7ee8d1b.png)
14. 
![Screenshot from 2019-11-21 12-47-02](https://user-images.githubusercontent.com/47241114/69335357-0f83a900-0c5d-11ea-908c-f631230fbcea.png)
15.
![Screenshot from 2019-11-21 12-47-59](https://user-images.githubusercontent.com/47241114/69335397-2c1fe100-0c5d-11ea-835d-95b7c86fe447.png)
16.
![Screenshot from 2019-11-21 12-49-35](https://user-images.githubusercontent.com/47241114/69335508-65f0e780-0c5d-11ea-9fd1-f53e6bb6a5cc.png)
17.
![Screenshot from 2019-11-21 12-50-39](https://user-images.githubusercontent.com/47241114/69335562-8de04b00-0c5d-11ea-81f8-9bdca3d91039.png)
18. 
![Screenshot from 2019-11-21 12-51-03](https://user-images.githubusercontent.com/47241114/69335589-9cc6fd80-0c5d-11ea-91b0-377361af9f05.png)
19.
![Screenshot from 2019-11-21 12-51-36](https://user-images.githubusercontent.com/47241114/69335636-ac464680-0c5d-11ea-80a8-74942c140c44.png)
20. 
![Screenshot from 2019-11-21 12-51-59](https://user-images.githubusercontent.com/47241114/69335790-bec08000-0c5d-11ea-95a0-f2cbe5e62c98.png)
21.
![Screenshot from 2019-11-21 12-54-38](https://user-images.githubusercontent.com/47241114/69335989-1e1e9000-0c5e-11ea-8007-0eae2f2d5900.png)

**Comment by lwtchu** [comment]
<img width="771" alt="Screen Shot 2019-12-19 at 10 25 51 AM" src="https://user-images.githubusercontent.com/11299125/71190404-24e2f780-224a-11ea-8c06-30c05ddea33e.png">

[chapteroutline.pdf](https://github.com/openstax/cnx-recipes/files/3984528/chapteroutline.pdf)
Can we tweak this to the following specs:

- Blue bar is 2in wide
- All font is base font-size(0) (9pt) (12px) , IBM Plex Sans

If there are a lot more 1 off issues, please let us know.

**Comment by brittweinstein** [comment]
This is related to https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/1475

**Comment by lwtchu** [comment]
<img width="771" alt="Screen Shot 2019-12-19 at 10 25 51 AM" src="https://user-images.githubusercontent.com/11299125/71190404-24e2f780-224a-11ea-8c06-30c05ddea33e.png">

[chapteroutline.pdf](https://github.com/openstax/cnx-recipes/files/3984528/chapteroutline.pdf)
Can we tweak this to the following specs:

- Blue bar is 2in wide
- All font is base font-size(0) (9pt) (12px) , IBM Plex Sans

If there are a lot more 1 off issues, please let us know.

#1628

**Comment by wilkus27** [comment]
@lwtchu I investigated this problem. Chapter outlines are cropped on the right side just in the situation when they skip to the second page of the chapter. And the reason why is that we have special settings only for the first page of the chapter:

![image](https://user-images.githubusercontent.com/40228854/74545908-f3d12b80-4f49-11ea-9f41-fbcf0326b958.png)

That is, for this page right margin is set to `2in`, and Chapter Outline is placed `-2in` to the right. 
So I try to apply margin also to the second page and it works:

![image](https://user-images.githubusercontent.com/40228854/74546309-ae612e00-4f4a-11ea-9aab-422776d80a4b.png)

Chapter Outline are not cropped anymore, but this efect is applied to all second pages, and when Chapter Outline stay on the first page, second page looks odd in comparison to the third page:

![image](https://user-images.githubusercontent.com/40228854/74546598-16177900-4f4b-11ea-8f3d-3f22dca48a45.png)

What do you recommend in this situation?

**Comment by lwtchu** [comment]
@wilkus27 i'll wait for helene to advise for any technical fix. 

the screenshot following (Chapter Outline stay on the first page, second page looks odd in comparison to the third page:) it not ideal. however, i wouldn't consider it the end of the world if we have to live with it.

**Comment by wilkus27** [comment]
@lwtchu @helenemccarron about Chapter Outlines cut at the bottom, e.g: 

![image](https://user-images.githubusercontent.com/40228854/74722214-d5647c00-5238-11ea-9255-b2f548da049d.png)

problem is related with property `position: absolute` for this element. Introduction text with chapter outline jump to the second page if splash image is big or if there is a lot of text in introduction. Because Chapter Outline has property which I mention, if this element is big it doesn't jump to the second page with introduction text but it's cut.

We can remove this property but then we can't display text of the `1.1` module right after text of introduction page.

![image](https://user-images.githubusercontent.com/40228854/74722789-cf22cf80-5239-11ea-990a-c6b51a23eaf6.png)

There will be white space as huge as long is Chapter Outline. If we are ok with that solution I will align Chapter Outline to the right edge. If not I will try to reduce font size as you proposed in the previous comments.

**Comment by brittweinstein** [comment]
@wilkus27 Larissa says the horizontal spacing is fine between the outline and section title. We would like to add padding around the chapter outline box. @lwtchu will provide specs.

**Comment by lwtchu** [comment]
padding: v-grid(1)

**Comment by wilkus27** [comment]
Ok, so this is the final version:

![image](https://user-images.githubusercontent.com/40228854/74923552-4474d880-53d1-11ea-920d-f2700c83c798.png)

After discusion on the slack I also changed font size to `font-scale(0)` and increased width of Chapter Outline box to `2in`, also added left margin and increased right padding.

I apply this to all books using `ChapterIntroShape`. Because at this moment the highest priority have HS Physics and Biology (College Physics use different shape) I propose to test only those books and for other books I will create separate issue.

**Comment by lwtchu** [comment]
@wilkus27 are there any instances where it's egregiously large?

**Comment by wilkus27** [comment]
@lwtchu It's not tested yet, PR is in code review now. I checked quickly how huge chapters are in HS Physics and the biggest one has 5 modules, so in this book shouldn't be large Chapter Outlines.

**Comment by wilkus27** [comment]
## Changes to provide to Theme Design Specs

### Shape: `ChapterIntroShape`

_Component:_ `IntroBody`
_New properties:_
```
        justify-content: space-between,
        right: -2in,
        margin-left: -2in,
```
![image](https://user-images.githubusercontent.com/40228854/75252798-a96b6c80-57dd-11ea-8a9a-dd5b1b4939b4.png)

_Component:_ `Outline`
_Removed properties:_
```
        position: absolute,
        right: -2in,
```
_Changed properties:_
```
width: 2in,
font-size: font-scale(0),
line-height: line-height(0),
margin: 0 -1.2rem 0 1.5rem;
```
![image](https://user-images.githubusercontent.com/40228854/75252868-c6a03b00-57dd-11ea-9468-6021fa32c2b6.png)

_Component:_ `OutlineTitle`
_Changed properties:_
```
font-size: font-scale(0),
line-height: line-height(0),
padding: 0 2.7rem 0.5rem 0;
```
![image](https://user-images.githubusercontent.com/40228854/75252904-d586ed80-57dd-11ea-8a1e-f42fab0ad4a2.png)

_Component:_ `ChapterOutlineObjective`
_Changed properties:_
```
padding-right: 2.7rem;
```
![image](https://user-images.githubusercontent.com/40228854/75252941-e6cffa00-57dd-11ea-9df5-3f09c6d82805.png)

**Comment by MartaSztuka** [comment]
tested (every Chapter Outline in both books)
Biology 2e![Screenshot from 2020-02-27 13-54-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/98f4e93e-dcdc-4cf4-89b1-a8166b695cda)
AP Biology![Screenshot from 2020-02-27 14-05-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/96674777-8f47-482e-a4d8-031b09391468)

**Comment by MartaSztuka** [comment]
HS Physics
![Screenshot from 2020-02-27 14-36-26](https://user-images.githubusercontent.com/47241114/75450377-fb8fc780-596e-11ea-9556-7a58001a9a52.png)
