### ISSUE TITLE
Chapter Outline Cropped - Microbiology

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1628]
All locations where Chapter Outline is cropped:
1.
![Screenshot from 2019-11-21 13-22-59](https://user-images.githubusercontent.com/47241114/69337822-1b259e80-0c62-11ea-8299-5edb51d99fd7.png)
2.
![Screenshot from 2019-11-21 13-26-28](https://user-images.githubusercontent.com/47241114/69338022-8c655180-0c62-11ea-8ca1-224470b1fd8e.png)
3.
![Screenshot from 2019-11-21 13-28-19](https://user-images.githubusercontent.com/47241114/69338140-cd5d6600-0c62-11ea-9e77-131144ffd8cc.png)
4.
![Screenshot from 2019-11-21 13-29-14](https://user-images.githubusercontent.com/47241114/69338213-f54cc980-0c62-11ea-9c76-dbe2be3eaa85.png)
5.
![Screenshot from 2019-11-21 13-30-08](https://user-images.githubusercontent.com/47241114/69338265-131a2e80-0c63-11ea-9413-5e7c0a5e0944.png)
6.
![Screenshot from 2019-11-21 13-31-07](https://user-images.githubusercontent.com/47241114/69338312-32b15700-0c63-11ea-8753-447316701e30.png)
7.
![Screenshot from 2019-11-21 13-31-43](https://user-images.githubusercontent.com/47241114/69338348-46f55400-0c63-11ea-97bf-dbad71ca704b.png)
8.
![Screenshot from 2019-11-21 13-32-23](https://user-images.githubusercontent.com/47241114/69338391-62f8f580-0c63-11ea-9246-780c4e8274f1.png)
9.
![Screenshot from 2019-11-21 13-33-35](https://user-images.githubusercontent.com/47241114/69338464-8e7be000-0c63-11ea-9053-9f057a9cce96.png)
10.
![Screenshot from 2019-11-21 13-34-03](https://user-images.githubusercontent.com/47241114/69338484-9d629280-0c63-11ea-8f11-a8e2f1edd0fd.png)
11.
![Screenshot from 2019-11-21 13-34-43](https://user-images.githubusercontent.com/47241114/69338536-b53a1680-0c63-11ea-8544-6c5fed54023c.png)
12.
![Screenshot from 2019-11-21 13-35-18](https://user-images.githubusercontent.com/47241114/69338582-ca16aa00-0c63-11ea-9fc0-d80e6f187fdd.png)
13.
![Screenshot from 2019-11-21 13-37-21](https://user-images.githubusercontent.com/47241114/69338713-11049f80-0c64-11ea-98f9-8c2518f77e10.png)

**Comment by lwtchu** [comment]
[chapteroutline.pdf](https://github.com/openstax/cnx-recipes/files/3984528/chapteroutline.pdf)
Can we tweak this to the following specs:

- Blue bar is 2in wide
- All font is base font-size(0) (9pt) (12px) , IBM Plex Sans

If there are a lot more 1 off issues, please let us know.

**Comment by brittweinstein** [comment]
This is related to https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/1475

**Comment by ajluk** [comment]
Changes in TDS:
The book specific color properties need to be set for Microbiology for **FullWidthChapterIntro** shape
for components:
   **SplashFigureBg** (J126)
        background-color': B7
    **OutlineTitle** (J138)
       color': B7
    **Outline** (J137)
        border-bottom-color': B7
    **OutlineTitleBottomBorder** (J139)
   border-bottom-color': B7
And the book specific color properties set need to be removed from cells:J101, J110 in the ChapterIntro shape, which Microbiology was using previously. (I guess that cell A122 cell - Learning Objectives need to be moved under A170 as well).

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-03-25 15-02-52](https://user-images.githubusercontent.com/47241114/77544825-daf15980-6ea9-11ea-82c6-fc1fec99ab83.png)
