### ISSUE TITLE
College Success: Title is not Visible

### ISSUE THREAD

**Issue by clteam18** [openstax/cnx-recipes#1629]
- **Book(s)**: College Success
- **URL/Server**: https://content03.cnx.org/contents/X95lCXNn@3.1:8Xn0Tf1J@2/Introduction
- **Location (page number, chapter/section)**: Chapter 03/m10093
- **Suggested nearby searchable text**: Before I started college, I had heard that the

# Screenshots

![image](https://user-images.githubusercontent.com/39794953/69427024-9b2c3100-0d54-11ea-93bc-fe9f236dfc42.png)

# Additional notes

Title (Student Profile) is not visible similarly the following titles (AN A LY S I S Q U E S T I O N [https://content03.cnx.org/contents/X95lCXNn@3.1:93LeJ_RW@1/The-Benefits-of-Time-Management],  WHAT S T U D E N T S S AY [https://content03.cnx.org/contents/X95lCXNn@3.1:fXKh_AD5@3/Time-Management-in-College], AN A LY S I S Q U E S T I O N [https://content03.cnx.org/contents/X95lCXNn@3.1:rMJ-3R-k@1/Procrastination-The-Enemy-Within], AN A LY S I S Q U E S T I O N [https://content03.cnx.org/contents/X95lCXNn@3.1:V-Z8Fd77@2/How-to-Manage-Time], ACT I V I T Y [https://content03.cnx.org/contents/X95lCXNn@3.1:V-Z8Fd77@2/How-to-Manage-Time], G E T C O N N E C T E D [https://content03.cnx.org/contents/X95lCXNn@3.1:V-Z8Fd77@2/How-to-Manage-Time], ACT I V I T Y [https://content03.cnx.org/contents/X95lCXNn@3.1:N-pZKjla@1/Prioritization-Self-Management-of-What-You-Do-and-When-You-Do-It], AN A LY S I S Q U E S T I O N [https://content03.cnx.org/contents/X95lCXNn@3.1:N-pZKjla@1/Prioritization-Self-Management-of-What-You-Do-and-When-You-Do-It], A P P L I C AT I O N [https://content03.cnx.org/contents/X95lCXNn@3.1:YQWtXhgW@1/Goal-Setting-and-Motivation], AN A LY S I S Q U E S T I O N [https://content03.cnx.org/contents/X95lCXNn@3.1:RFEdN5qD@4/Enhanced-Strategies-for-Time-and-Task-Management], A P P L I C AT I O N [https://content03.cnx.org/contents/X95lCXNn@3.1:RFEdN5qD@4/Enhanced-Strategies-for-Time-and-Task-Management], AN A LY S I S Q U E S T I O N [https://content03.cnx.org/contents/X95lCXNn@3.1:RFEdN5qD@4/Enhanced-Strategies-for-Time-and-Task-Management],  ) are not visible.

**Comment by openstaxalina** [comment]
@yblock please provide markup review/screenshot.

**Comment by yblock** [comment]
The recipe was not applied. I applied and baked, titles are now appearing.

**Comment by yblock** [comment]
@clteam18 Please confirm and close the issue if resolved.
