### ISSUE TITLE
College Success: Footnote reference is not showing properly

### ISSUE THREAD

**Issue by clteam18** [openstax/cnx-recipes#1630]
- **Book(s)**: College Success
- **URL/Server**: https://content03.cnx.org/contents/X95lCXNn@3.1:93LeJ_RW@1/The-Benefits-of-Time-Management
- **Location (page number, chapter/section)**: Chapter 03/m10094
- **Suggested nearby searchable text**: the financial impact delaying graduation

# Screenshots

![image](https://user-images.githubusercontent.com/39794953/69428976-85b90600-0d58-11ea-9558-7840c40971fc.png)

# Additional notes

All the footnote reference is coming as separate line. Please check and advise.

**Comment by openstaxalina** [comment]
@yblock could you review the markup and paste a screenshot below if correct?
@lwtchu perhaps footnotes were not enabled for this title.  I do not see a reference to them in the design analysis doc.

**Comment by lwtchu** [comment]
@openstaxalina we were looking at this earlier. it looks like it's using the `<cite>` tagging as opposed to just a static reference section. we'll need to make a change to the recipe if we need to support this.

**Comment by yblock** [comment]
```<para id="fs-idm312581568">Based on independent research, a <emphasis effect="italics">Washington Post</emphasis> article details the financial impact delaying graduation by two semesters can have on a student.<cite target-id="ch03rfin-1"><note class="reference" display="inline" id="ch03rfin-1">https://www.washingtonpost.com/news/grade-point/wp/2016/06/21/spending-a-few-extra-years-in-college-may-cost-you-more-than-you-think/?noredirect=on&amp;utm_term=.f06be365e5d6</note></cite> (Spending a Few Extra Years in College May Cost You More Than You Think, Danielle Douglas-Gabriel, June 21, 2016)</para>```

**Comment by yblock** [comment]
They have used the cite tag to achieve in-line citations and linking in the PDF. This has the undesirable effect of looking wonky online. Also, the description of the citations are floating after the citation inside of the parent ```<para>``` tag.

**Comment by openstaxalina** [comment]
@yblock could you test out using the footnote tag (https://legacy.cnx.org/eip-help/footnote) and provide screenshots for this display on webview and PDF?

**Comment by yblock** [comment]
@openstaxalina this looks nice I think

![Screen Shot 2019-11-26 at 10.42.26 AM.jpg](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/9fec8e27-d98b-4f2f-993d-7a9b7c15a2b5)

**Comment by openstaxalina** [comment]
Anthony confirms manuscripts will use footnotes, not static references cc @lwtchu @yblock 

@clteam18 please use the markup above to encode this as a footnote, not a citation.   Please let us know if you have any markup questions.  If not, please close this issue.
