### ISSUE TITLE
College Success: Summary heading is not coming

### ISSUE THREAD

**Issue by clteam18** [openstax/cnx-recipes#1632]
- **Book(s)**: College Success
- **URL/Server**: https://content03.cnx.org/contents/X95lCXNn@3.1:RFEdN5qD@4/Enhanced-Strategies-for-Time-and-Task-Management
- **Location (page number, chapter/section)**: Chapter 03/m10100
- **Suggested nearby searchable text**: This chapter began by pointing out the

# Screenshots

![image](https://user-images.githubusercontent.com/39794953/69429851-818de800-0d5a-11ea-9270-5758a188bd79.png)

# Additional notes

Summary heading is not coming. Please check and advise.

**Comment by openstaxalina** [comment]
@yblock could you please review the markup?  If the markup looks correct, please paste a screenshot below to assist devs with debugging.

**Comment by openstaxalina** [comment]
I'm wondering if the class is missing -- shouldn't these be collating to EOC?

**Comment by yblock** [comment]
```<section id="fs-idm343872656" class="summary">
<para id="fs-idm320398288">This chapter began by pointing out the dangers of poor time management, both in cost and even the potential risk to graduation. After presenting why time management is important, sections of the text covered how time management for college can be different from what students may have experienced before. Following this, the chapter contained several sections on how to effectively manage time (including predicting time on task), how to use technology to your advantage, and how to prioritize tasks. Other topics included goal setting and motivation, some specific strategies for time and task management, and avoiding procrastination.</para>
</section>```

**Comment by yblock** [comment]
If this is meant to be a "Chapter Summary" then it's missing the title tag and has the wrong class applied. Tagging legend states:

```
"<section class=""section-summary"">
  <title>Chapter Summary</title>
  <para> ... </para>
</section>"
```

**Comment by openstaxalina** [comment]
@clteam18 please let us know if you have any questions about implementing this markup.  If not, please close this issue.

**Comment by clteam18** [comment]
As per your suggestion, we have used but in the Web view, heading is showing as "Section Summary" and also showing the section heading "1.7 Enhanced Strategies for Time and Task Management" as well as in PDF view, showing as "Chapter Summary". Kindly see the attachment and advise which one is correct and resolve this.
https://content03.cnx.org/contents/X95lCXNn@7.1:u3S101HY@7.1/Section-Summary

![image](https://user-images.githubusercontent.com/39794953/69814676-b8f90a80-121a-11ea-8990-7d9b749e745d.png)

**Comment by openstaxalina** [comment]
@clee1060 thank you for this feedback -- for now, please leave your markup as-is.  I believe that we will fix the webview to match the PDF titles.  cc @yblock (just FYI - no action needed right now)

**Comment by openstaxalina** [comment]
This will be handled via the issue: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/1686
