### ISSUE TITLE
Biology for AP Courses: images in TEST PREP FOR AP® COURSES are too wide 

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1633]
Images in TEST PREP FOR AP® COURSES are too wide and need to to not exceed their containers:  
![image](https://user-images.githubusercontent.com/55203598/69433707-67451180-0d3c-11ea-99f3-dff2ad976b20.png)

Changes in Theme Design Specs:
New component **ExerciseFigure** have been added to the shape **EocExerciseWithoutSubtitle** in the EoC shapes, with a property: max-width: enum('ValueSet:::OPTIONAL'). In **TestPrep** exercises which are present in Biology for AP Courses and uses **EocExerciseWithoutSubtitle** shape it is set to 100 % (max-width: 100%).

**Comment by MartaSztuka** [comment]
Images is exercises keep their size, don't overlap text anymore.
![Screenshot from 2019-12-05 15-25-55](https://user-images.githubusercontent.com/47241114/70243906-d296d680-1773-11ea-98ae-06c0030d062e.png)
