### ISSUE TITLE
Chapter Outline Cropped- Physics

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1635]
All locations where Chapter Outline is cropped:
1.
![Screenshot from 2019-11-22 17-12-15](https://user-images.githubusercontent.com/47241114/69441589-50f28200-0d4b-11ea-9810-0edb25c85dcc.png)
2.
![Screenshot from 2019-11-22 17-13-09](https://user-images.githubusercontent.com/47241114/69441652-62d42500-0d4b-11ea-8d3a-bc402469b1a3.png)
3.
![Screenshot from 2019-11-22 17-13-35](https://user-images.githubusercontent.com/47241114/69441690-71bad780-0d4b-11ea-9fec-1e446b3cdb6b.png)
4.
![Screenshot from 2019-11-22 17-13-58](https://user-images.githubusercontent.com/47241114/69441720-7f705d00-0d4b-11ea-8264-88ea64a609ae.png)
5.
![Screenshot from 2019-11-22 17-14-25](https://user-images.githubusercontent.com/47241114/69441755-8f883c80-0d4b-11ea-8ddc-99efd0e92b06.png)
6.
![Screenshot from 2019-11-22 17-14-49](https://user-images.githubusercontent.com/47241114/69441788-9d3dc200-0d4b-11ea-8379-a806f94fc3f6.png)
7.
![Screenshot from 2019-11-22 17-15-17](https://user-images.githubusercontent.com/47241114/69441826-ad55a180-0d4b-11ea-91bc-85337c4949ce.png)
8.
![Screenshot from 2019-11-22 17-16-05](https://user-images.githubusercontent.com/47241114/69441893-ce1df700-0d4b-11ea-8653-124e3b7f8c77.png)
9.
![Screenshot from 2019-11-22 17-16-36](https://user-images.githubusercontent.com/47241114/69441922-dd9d4000-0d4b-11ea-9dcc-98e4cc83dd37.png)
10.
![Screenshot from 2019-11-22 17-17-01](https://user-images.githubusercontent.com/47241114/69441940-ebeb5c00-0d4b-11ea-9e93-e97c997380e1.png)
11.
![Screenshot from 2019-11-22 17-17-30](https://user-images.githubusercontent.com/47241114/69441965-fc9bd200-0d4b-11ea-9cb2-d39fa8b32b71.png)
12.
![Screenshot from 2019-11-22 17-17-55](https://user-images.githubusercontent.com/47241114/69441996-0c1b1b00-0d4c-11ea-83a9-7c20fc6ca4e9.png)
13.
![Screenshot from 2019-11-22 17-18-42](https://user-images.githubusercontent.com/47241114/69442051-2bb24380-0d4c-11ea-9390-2f29313c6877.png)
14.
![Screenshot from 2019-11-22 17-19-14](https://user-images.githubusercontent.com/47241114/69442099-3e2c7d00-0d4c-11ea-8859-bc986d173d11.png)
15.
![Screenshot from 2019-11-22 17-19-45](https://user-images.githubusercontent.com/47241114/69442135-4d132f80-0d4c-11ea-8eb1-d10c68cb4ded.png)
16.
![Screenshot from 2019-11-22 17-20-06](https://user-images.githubusercontent.com/47241114/69442157-5ac8b500-0d4c-11ea-9ab5-61d993adee41.png)
17.
![Screenshot from 2019-11-22 17-20-36](https://user-images.githubusercontent.com/47241114/69442195-6b792b00-0d4c-11ea-924f-f1e9ae375242.png)
18.
![Screenshot from 2019-11-22 17-21-01](https://user-images.githubusercontent.com/47241114/69442226-7af87400-0d4c-11ea-8c15-be600c865b4c.png)
19.
![Screenshot from 2019-11-22 17-21-55](https://user-images.githubusercontent.com/47241114/69442296-9c596000-0d4c-11ea-8ef7-8312d2d2f011.png)
20.
![Screenshot from 2019-11-22 17-22-21](https://user-images.githubusercontent.com/47241114/69442325-abd8a900-0d4c-11ea-80c9-2a3e1cfb85cc.png)
21.
![Screenshot from 2019-11-22 17-22-46](https://user-images.githubusercontent.com/47241114/69442346-b7c46b00-0d4c-11ea-9fe7-3e560a73e57e.png)
22.
![Screenshot from 2019-11-22 17-23-07](https://user-images.githubusercontent.com/47241114/69442369-c6128700-0d4c-11ea-8339-5cd90969918d.png)
23.
![Screenshot from 2019-11-22 17-23-32](https://user-images.githubusercontent.com/47241114/69442394-d3c80c80-0d4c-11ea-9ab5-60786eab79e2.png)
24.
![Screenshot from 2019-11-22 17-23-55](https://user-images.githubusercontent.com/47241114/69442425-e17d9200-0d4c-11ea-904b-623645355834.png)
25.
![Screenshot from 2019-11-22 17-24-21](https://user-images.githubusercontent.com/47241114/69442522-05d96e80-0d4d-11ea-8be7-f9a32b08b0a4.png)
26.
![Screenshot from 2019-11-22 17-25-22](https://user-images.githubusercontent.com/47241114/69442558-14278a80-0d4d-11ea-89db-9db6c7041b33.png)
27.
![Screenshot from 2019-11-22 17-25-45](https://user-images.githubusercontent.com/47241114/69442589-230e3d00-0d4d-11ea-9aad-9bb3a16ccaa5.png)
28.
![Screenshot from 2019-11-22 17-26-08](https://user-images.githubusercontent.com/47241114/69442623-302b2c00-0d4d-11ea-8281-2b6c512cfd81.png)
29.
![Screenshot from 2019-11-22 17-26-27](https://user-images.githubusercontent.com/47241114/69442651-3faa7500-0d4d-11ea-9735-f082a912307e.png)
30.
![Screenshot from 2019-11-22 17-26-54](https://user-images.githubusercontent.com/47241114/69442687-4f29be00-0d4d-11ea-9486-17f831439aa5.png)
31.
![Screenshot from 2019-11-22 17-27-20](https://user-images.githubusercontent.com/47241114/69442729-5cdf4380-0d4d-11ea-8744-afb7b2e3decb.png)
32.
![Screenshot from 2019-11-22 17-28-01](https://user-images.githubusercontent.com/47241114/69442778-741e3100-0d4d-11ea-942c-7f0f02634b86.png)
33.
![Screenshot from 2019-11-22 17-28-26](https://user-images.githubusercontent.com/47241114/69442809-839d7a00-0d4d-11ea-8059-257dfc29cd49.png)
34.
![Screenshot from 2019-11-22 17-28-47](https://user-images.githubusercontent.com/47241114/69442843-8f893c00-0d4d-11ea-9175-a732d39f59f1.png)

**Comment by lwtchu** [comment]
<img width="771" alt="Screen Shot 2019-12-19 at 10 25 51 AM" src="https://user-images.githubusercontent.com/11299125/71190404-24e2f780-224a-11ea-8c06-30c05ddea33e.png">

[chapteroutline.pdf](https://github.com/openstax/cnx-recipes/files/3984528/chapteroutline.pdf)
Can we tweak this to the following specs:

- Blue bar is 2in wide
- All font is base font-size(0) (9pt) (12px) , IBM Plex Sans

If there are a lot more 1 off issues, please let us know.

#1628

**Comment by lwtchu** [comment]
I'm thinking we will have to do something like this for College Physics

https://github.com/openstax/cnx-recipes/issues/1430

**Comment by lwtchu** [comment]
![Screen Shot 2020-01-21 at 11 07 12 AM](https://user-images.githubusercontent.com/11299125/72826306-326f1100-3c3e-11ea-841f-c0a80c033c43.png)

Chapter outline text: Muli, Bold, font-scale(2), for college physics: B5:    #00819A
Module number: Muli, Bold, font-scale(1) - these should be links (default link color)
Line: B5:    #00819A, is it halfv-grid? whatever the weight is for icon notes border. 

Space between Chapter Outline and the line: h-grid(1) 8px

**Comment by ajluk** [comment]
New shape needs to be added to Chater Intro shapes: **FullWidthChapterIntro** under l.122
with components:

**SplashFigureWrapper**
properties:
   margin-bottom: 2rem,

**SplashFigure**
properties:
        position: relative,
        margin: 0,

**SplashFigureBg**
properties:
            content: "''",
            background-color: B2
            position: absolute,
            height: 100%,
            width: 8.5in,
            margin-left: -1in,
            z-index: -1,
            box-sizing: border-box,
            padding: inherit,
            top: 0,

**SplashImgMedia**
properties:
        line-height: 0,
        height: 100%,
        display: flex,
        width: 7.5in,
        justify-content: flex-end

**SplashImg**
properties:
     width: 8in,

**SplashCaption**
properties:
        position: relative,
        padding-top: 1rem,
        padding-bottom: 2rem,

**SplashCaptionBg**
properties:
            content: "''",
            background-color: Grey1
            position: absolute,
            height: 100%,
            width: 8.5in,
            margin-left: -1in,
            z-index: -1,
            box-sizing: border-box,
            padding: inherit,
            top: 0,

**FigureNum**
properties:
            font-family: "Muli",
            font-weight: bold,
            font-size: font-scale(1),
            color: R3

**FigureLabel**
properties:
            font-family: "Muli",
            font-weight: bold,
            font-size: font-scale(1),
            color: R3

**FigureTitle**
properties:
            font-family: "Muli",
            font-weight: bold,
            font-size: font-scale(1),

**Caption**
properties:
            font-family: ("IBM Plex Sans", sans-serif),
            font-size: font-scale(1), 

**ChapterIntroBodyWithoutProperties**
properties:
empty properties

**Outline**
properties:
        width: 6.4in,
        margin: 0 0 1.5rem 0,
        font-family: ("IBM Plex Sans", sans-serif),
        font-size: font-scale(1),
        line-height: line-height(1),
        font-weight: 500,
        **border-bottom-color: book specific (B5 for College Physics )**
        border-bottom-width: 0.2rem ,
        border-bottom-style: solid,
        box-decoration-break: slice,

**OutlineTitle**
properties:
        margin: 0 0 1.5rem 0,
        font-size: font-scale(2),
        line-height: line-height(1),
        font-weight: bold, 
        font-family: ("Muli", sans-serif),
        **color: book specific (B5 for College Physics )**
        position: relative,
        display:flex,
        flex-direction: row,

**OutlineTitleBottomBorder**:
properties:
       content: "''",
        width: 5in, 
        border-bottom-width: 0.2rem,
        **border-bottom-color: book specific (B5 for College Physics )**
        border-bottom-style: solid,
        margin-left: 11.5rem, 
        position: absolute, 
        bottom: 0,
        display: inline-block,

**ChapterOutlineObjective**
properties:
       margin-bottom: .5rem,
      
**OutlineObjectiveLink**
properties:
        display: inline-block,
        color: B8,
        font-family: ("Muli", sans-serif),
        font-weight: bold, 
        font-size: font-scale(1),
        margin-bottom: .5rem,

**ChapterOutlineObjectiveText**
   properties:
       empty properties

**OutlineObjectiveLearning**
properties:
       empty properties

**OutlineAbstract**
properties:
        margin-left: 1.5rem,
        font-family: "Alegreya",

**IntroContent**
properties:
empty properties

**IntroContentHeader**
properties:
           float: left,
           font-family: (_ref: 'typography:::Alegreya'),
            font-size: 12px,
            text-transform: uppercase,
            margin: 0 .5rem 0 0,
            font-weight: 700,

**IntroFirstPara**
properties:
            margin-top: 0,

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-12 16-48-32](https://user-images.githubusercontent.com/47241114/74351636-af158b00-4db7-11ea-8577-bb266ab021a1.png)
