### ISSUE TITLE
Biology 2e: add style to equations

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1638]
The equations in Biology need to have margin-bottom set. Here is how it looks now:
![image](https://user-images.githubusercontent.com/55203598/69537036-84b5ed80-0f7f-11ea-8a53-7bbb2d11ff03.png)

Changes in Theme Design Specs:
New shape: EquationShape
New Component: EquationContainer
        position: enum('ValueSet:::OPTIONAL'),
        display: flex,
        flex-direction: enum('ValueSet:::OPTIONAL'),
        align-items: center,
        justify-content: center,
        margin-bottom: v-grid(1),

**Comment by MartaSztuka** [comment]
Equations styled
![Screenshot from 2019-11-26 12-13-00](https://user-images.githubusercontent.com/47241114/69625614-3c620280-1047-11ea-8883-8f99e38d7d1d.png)
