### ISSUE TITLE
Biology 2e: add left margin to lists in tables

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1640]
Lists in tables in Biology need to have set additional left margin margin. Now they look like this:
![image](https://user-images.githubusercontent.com/55203598/69556430-f6546280-0fa4-11ea-9096-9900802bc304.png)

Changes in Theme Design Specs:
New component has been created and added (after TableData) to **BasicTable** shape: 

- [x] **TableDataList** with one property: **margin-left: 1.5rem**

**Comment by openstaxalina** [comment]
@ajluk I added this and tagged you in a comment to confirm I did this correctly.

**Comment by MartaSztuka** [comment]
Left margin is added.
![Screenshot from 2019-12-05 15-06-13](https://user-images.githubusercontent.com/47241114/70242331-f1e03480-1770-11ea-8d0c-248169213ad8.png)
