### ISSUE TITLE
Modify the handling of external resources for CSS

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1645]
# Scenario

This is needed in order for the Output Producer (PDF Producer) to generate a baked styles PDF on a specific branch in GitHub.  This will probably a team effort.

# Acceptance Criteria

**Comment by brittweinstein** [comment]
@openstaxalina can we close this?

**Comment by openstaxalina** [comment]
Yes - closing.

**Comment by openstaxalina** [comment]
@brittweinstein I thought so - but on second thought, this may still be needed.

As far as I know, COPS does not generate PDFs on a specific branch. It can only generate PDFs using code merged to master. (Just to check - is this functionality -- generating PDFs from a branch -- planned for CE Tech in Q2?)

I'd like to keep this in the backlog unless we decide that we do *not* want COPS to generate PDFs on a specific branch.

**Comment by lwtchu** [comment]
.________. i'm closing because i don't think this is necessary anymore?
