### ISSUE TITLE
Enable appendix-top-title-copy release flag

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1646]
The goal is to remove `appendix-top-title-copy` flag. To do that it should be enabled for all books. If any changes occur in `output.css` files those books have to be tested.

**Comment by wilkus27** [comment]
After enabling this flag 7 output files are changed:
- accounting
- ap-history
- business-ethics
- entrepreneurship
- history
- intro-business
- principle-management

Note: in accounting class `appendix` is missing in appendices. It can be tested after fix that.

**Comment by wilkus27** [comment]
After using `diff` script there are no changes in html files for:

- [ ] accounting-vol-1 (easyvm5.cnx.org)
- [ ] accounting-vol-2 (easyvm5.cnx.org)
- [ ] ap-history (content05.cnx.org)
- [ ] business-ethics (easyvm5.cnx.org)
- [ ] business-law  (cnx.org) -> is using `business-ethics` recipe
- [ ] entrepreneurship (content01.cnx.org)
- [ ] history (easyvm5.cnx.org)
- [ ] intro-business (easyvm5.cnx.org)
- [ ] principle-management (easyvm5.cnx.org)
- [ ] organizational-behavior (easyvm5.cnx.org) -> is using `principle-management` recipe

**Comment by wilkus27** [comment]
Note: no changes to styles. Step **Spec Update** can be omitted.

**Comment by Stackblocks** [comment]
The following collections have been rebaked on easyvm5.cnx.org:

- AP History: https://easyvm5.cnx.org/contents/I3AIQB35@20.1:wNGuSt-m@1/Introduction-to-This-Course
- Business Ethics: https://easyvm5.cnx.org/contents/kUrGbuHs@4.2:KCyr9xii@3/Introduction
- Entrepreneurship: https://easyvm5.cnx.org/contents/04BRDmFF@5.12:1ykNQm79@1/1-1-Introduction
- History: https://easyvm5.cnx.org/contents/zk8VYfA4@2.14:39Sgp4DO@4/Introduction
- Intro Business: https://easyvm5.cnx.org/contents/Tgl3H6iq@8.6:HFQiJQgd@7/Introduction
- Principles of Management: https://easyvm5.cnx.org/contents/w6yyq31c@10.1:Bgbu38Eg@6/Introduction
- Organizational Behavior (Using Principles of Management) - https://easyvm5.cnx.org/contents/LZQauaxb@5.7:5BErM-24@2/Introduction

Per Natalia, the Accounting collections below are still missing the Appendix class and will need that resolved before they can be rebaked

- Accounting 1: https://easyvm5.cnx.org/contents/mrS6bR5I@4.66:qv6kYQJ7@3/Why-It-Matters
- Accounting 2: https://easyvm5.cnx.org/contents/kg0cimBs@14.13:feO1bURf@4/Why-It-Matters

**Comment by openstaxalina** [comment]
@oscryan could you add the Appendix class on the two accounting titles linked above in Alan's comment?

**Comment by oscryan** [comment]
added

**Comment by openstaxalina** [comment]
Thank you, Ryan! @Stackblocks FYI - the content change was made so you should be unblocked now.

**Comment by Stackblocks** [comment]
The Accounting collections have been rebaked, now with appendix class! 🎉

**Comment by Stackblocks** [comment]
Business Law has been added and baked here: https://easyvm5.cnx.org/contents/1Civlx8s@2.1:crDpMUh6@1/Introduction

**Comment by MartaSztuka** [comment]
- AP History: no appendix

- Business Ethics: in new version is not correct ![Screenshot from 2020-01-29 09-23-59](https://user-images.githubusercontent.com/47241114/73339652-8353ba80-4279-11ea-9727-947d67921baa.png)

![Screenshot from 2020-01-29 09-24-14](https://user-images.githubusercontent.com/47241114/73339651-82bb2400-4279-11ea-99d9-46f7daa65db3.png)

- Entrepreneurship: no appendix

- U.S. History: ![Screenshot from 2020-01-29 09-30-07](https://user-images.githubusercontent.com/47241114/73339920-04ab4d00-427a-11ea-8cc2-8a2d26cd6c24.png)

- Introduction to Business:
![Screenshot from 2020-01-29 09-31-28](https://user-images.githubusercontent.com/47241114/73340035-41774400-427a-11ea-9c45-60964be235db.png)
![Screenshot from 2020-01-29 09-31-42](https://user-images.githubusercontent.com/47241114/73340039-43410780-427a-11ea-95f4-056321881dbb.png)

- Principles of Management: no appendix

- Organizational Behavior:
![Screenshot from 2020-01-29 09-36-17](https://user-images.githubusercontent.com/47241114/73340350-daa65a80-427a-11ea-8ad9-90593386df8d.png)
![Screenshot from 2020-01-29 09-36-28](https://user-images.githubusercontent.com/47241114/73340354-dc701e00-427a-11ea-9a78-2631e28dc886.png)

- Accounting 1, 2: correct in new version
![Screenshot from 2020-01-29 09-39-11](https://user-images.githubusercontent.com/47241114/73340581-4c7ea400-427b-11ea-9cd3-af39c06facee.png)
![Screenshot from 2020-01-29 09-39-32](https://user-images.githubusercontent.com/47241114/73340585-4dafd100-427b-11ea-8ccd-c9b4b257413e.png)

- Business Law: no appendix
![Screenshot from 2020-01-29 09-41-59](https://user-images.githubusercontent.com/47241114/73340866-c878ec00-427b-11ea-8b96-564cc0fb3b40.png)

**Comment by wilkus27** [comment]
There is no developer work needed. @MartaSztuka here is the description of flag from this issue: https://docs.google.com/document/d/1ziR2PcSvioOLAHSRNWZga3m-8DlUM_qaskIjpWtoS60/edit#heading=h.5jk0jrv0qm5k which should be tested. Please contact with @Stackblocks and ask about discrepancies between old and the newest version which you posted above.

**Comment by Stackblocks** [comment]
The discrepancy between the version linked above and the "New Version" accessible via the banner on that page is that the "New Version" is an incomplete bake so it doesn't have a number of styling elements including Appendix labels, header styling, and collated EoC materials. It is non-representative of completed work.

**Comment by MartaSztuka** [comment]
appendix-top-title-copy flag doesn't concern those books, I'm closing the card.
