### ISSUE TITLE
College Success: Career Connection Heading

### ISSUE THREAD

**Issue by clteam18** [openstax/cnx-recipes#1651]
- **Book(s)**: College Success
- **URL/Server**: https://content03.cnx.org/contents/X95lCXNn@7.1:fNs8whsR@7.1/Career-Connection
- **Location (page number, chapter/section)**: Chapter 03/m10100
- **Suggested nearby searchable text**: to work in radio since I was in high school and ha

# Additional notes

In this page, title displays as "Career Connection" in web view. In Pdf title displays as "Reflect and Apply". I am not sure which is correct. Please see the attachment and advice.

# Screenshots
**WEB**
https://content03.cnx.org/contents/X95lCXNn@7.1:fNs8whsR@7.1/Career-Connection

![image](https://user-images.githubusercontent.com/39794953/69815336-13df3180-121c-11ea-83c4-d319fcd11ad0.png)
 
**PDF**
![image](https://user-images.githubusercontent.com/39794953/69817510-c3b69e00-1220-11ea-9f29-ab216a65c45b.png)

**Comment by openstaxalina** [comment]
This is most likely correct in PDF and needs to be updated to match in webview - will confirm before start of sprint.

**Comment by openstaxalina** [comment]
The correct heading is "Career Connection" and this has been resolved; closing.
