### ISSUE TITLE
University Physics: add styles to ToC

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1653]
ToC in University Physics should be styled according to Theme Design Specs.
Related issue: https://github.com/openstax/cnx-recipes/issues/1070

**Comment by ajluk** [comment]
After adding the styles for Unit ToC the baked file looks like this: 
![image](https://user-images.githubusercontent.com/55203598/69866470-7419b600-12a4-11ea-940c-6b147569317f.png)

**Comment by MartaSztuka** [comment]
ToC is styled
![Screenshot from 2019-12-19 12-09-19](https://user-images.githubusercontent.com/47241114/71169463-413a6080-2259-11ea-8e39-f0c6e2815d5d.png)
