### ISSUE TITLE
Biology for Ap Courses: add max width to all images in the EoC exercises

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1655]
Too wide images are appearing not only in TestPrep exercises in Biology for AP Courses, but in all exercises in the EoC sections and need to have their width set to max 100% to fit the two column layout containers. Here is the example how it loks now:
![image](https://user-images.githubusercontent.com/55203598/69875621-e34fd400-12bd-11ea-999b-ca2d09d6b088.png)

Changes in Theme Design Specs:
The component **ExerciseFigure** with property **max-width: 100%,** has been added to the shapes in **EocExerciseWithoutSubtitle** : 
    **Review
    Critical thinking
    TestPrep
    SciencePractice**

**Comment by ajluk** [comment]
Here is how it looks now:
![image](https://user-images.githubusercontent.com/55203598/69876510-11ceae80-12c0-11ea-8254-79477121663b.png)

**Comment by openstaxalina** [comment]
Added "ExerciseFigure" component.  @ajluk I tagged you in a comment to check my work!

**Comment by MartaSztuka** [comment]
Images don't overlap text.
![Screenshot from 2019-12-05 15-43-52](https://user-images.githubusercontent.com/47241114/70245279-18549e80-1776-11ea-83b3-f84f6a919f52.png)
