### ISSUE TITLE
Biology for AP Courses: add style to Learning Objectives

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1657]
Learning Objectives in Biology for AP Courses need to by styled according to issue: #1077.

Changes in Theme Design Specs:
New shape created: **LearningObjectiveParagraphShape**
contains one new component(bolded below): 
**LearningObjectiveParagraphComponent** with properties:
color: book specific 
font-family: "IBM Plex Sans", sans-serif,
font-size: font-scale(1),
line-height: line-height(1),
font-style: italic,
margin-bottom: 0,

and previously created components:
- LearningObjectiveListComponent       
- LearningObjectiveListItemComponent,
- LearningObjectiveListDotComponent (added **color property: color:book specific** ),

The **book specific** color for Biology for AP Courses is:  #0074BC,

I also have added two properties to **Title** component (belonging to the **LearningObjectiveShape**):
font-style: italic,
font-weight: normal,

**Comment by MartaSztuka** [comment]
Learning Objectives looks ok.
![Screenshot from 2019-12-10 12-01-17](https://user-images.githubusercontent.com/47241114/70524317-312dcd00-1b45-11ea-92d2-1b7cce98b760.png)
