### ISSUE TITLE
college physics: style EOB and EOC

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1660]
Style EOC and EOB in Physics with specs from Carnival Theme.

**Comment by wilkus27** [comment]
### Changes to provide to Theme Design Specs table

1. Shape **EocSummary**, element using this shape **SectionSummary**
To do: change name of element from **SectionSummary** to **Summary**.

2. New shape: **EocSectionSummary**, new element using this shape: **SectionSummary**.
- _Component_: Container
  _Properties_: margin-bottom: v-grid(4),
- _Component_: EocHeader
  _Properties_: 
            font-family: "IBM Plex Sans", sans-serif
            font-weight: bold,
            font-size: font-scale(4),
            line-height: line-height(4),
            text-transform: uppercase,
             // color: book specific, defined in book.scss file --> for college physics: B5
            margin-bottom: v-grid(1)
- _Component_: SectionTitleLink
  _Properties_: font-family: Muli

3. New shape: **EocConceptualQuestions**, new element using this shape: **ConceptualQuestions**.
- _Component_: Container
  _Properties_: margin-bottom: v-grid(4),
- _Component_: EocHeader
  _Properties_: 
            font-family: "IBM Plex Sans", sans-serif
            font-weight: bold,
            font-size: font-scale(4),
            line-height: line-height(4),
            text-transform: uppercase,
             // color: book specific, defined in book.scss file --> for college physics: B5
            margin-bottom: v-grid(1)
- _Component_: SectionTitleLink
  _Properties_: font-family: Muli
- _Component_: ProblemContainer
  _Properties_: empty
- _Component_: ProblemNumber
  _Properties_: 
            color: black
            font-weight: bold,
            text-decoration: none,
- _Component_: ProblemDivider
  _Properties_: margin-right: h-grid(1)

4. New shape: **EocProblemsExercises**, new element using this shape: **ProblemsExercises**.
- _Component_: Container
  _Properties_: 
            margin-bottom: v-grid(4),
            column-count: 2,
            column-gap: 2.4rem,
            column-width: auto,
- _Component_: EocHeader
  _Properties_: 
            font-family: "IBM Plex Sans", sans-serif
            font-weight: bold,
            font-size: font-scale(4),
            line-height: line-height(4),
            text-transform: uppercase,
            column-span: all,
             // color: book specific, defined in book.scss file --> for college physics: B5
            margin-bottom: v-grid(1)
- _Component_: SectionTitleLink
  _Properties_: font-family: Muli
- _Component_: ProblemContainer
  _Properties_: empty
- _Component_: ProblemNumber
  _Properties_: 
            color: black
            font-weight: bold,
            text-decoration: none,
- _Component_: ProblemDivider
  _Properties_: margin-right: h-grid(1)

5. Shape: **EocKeyTerm**, element using this shape: **Key Term**, component: EocHeader, property: color  --> for college physics: B5

6. Shape: **AppendixShape**, element using this shape: **Appendix**
- _Component_: MainText
  _Properties_: color  --> for college physics: B5
- _Component_: SubTitle
  _Properties_: color  --> for college physics: B5
- _Component_: SubSubTitle
  _Properties_: color  --> for college physics: B5

**Comment by lwtchu** [comment]
@wilkus27 specs updated~

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-01-16 12-20-52](https://user-images.githubusercontent.com/47241114/72520945-cfa30180-385a-11ea-93ef-a6d653513f88.png)
![Screenshot from 2020-01-16 12-22-25](https://user-images.githubusercontent.com/47241114/72520986-dfbae100-385a-11ea-8ef0-3646176fc6f1.png)
![Screenshot from 2020-01-16 12-22-42](https://user-images.githubusercontent.com/47241114/72520999-e9dcdf80-385a-11ea-9f6f-2a05f9ddf1cb.png)
![Screenshot from 2020-01-16 12-23-08](https://user-images.githubusercontent.com/47241114/72521028-f95c2880-385a-11ea-878f-d53103b79e58.png)
![Screenshot from 2020-01-16 12-27-00](https://user-images.githubusercontent.com/47241114/72521345-88694080-385b-11ea-8e77-b66a4812791d.png)
