### ISSUE TITLE
University Physics vol1: add style to preface

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1661]
Preface in University Physics vol1 should be styled according to specs from Carnival Theme.
Related issue: https://github.com/openstax/cnx-recipes/issues/1073
There are no changes in Theme Design Specs.

**Comment by MartaSztuka** [comment]
Preface styled
![Screenshot from 2019-12-19 12-06-26](https://user-images.githubusercontent.com/47241114/71168923-0c79d980-2258-11ea-8aa8-c073c9847c94.png)
