### ISSUE TITLE
college physics: style tables

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1663]
Tables in College Physics should be styled with specs from Carnival Theme.

**Comment by wilkus27** [comment]
Note: no changes to provide to Theme Design Specs. Step `Spec Update` can be skipped.

**Comment by MartaSztuka** [comment]
Tables are styled.
![Screenshot from 2019-12-10 16-32-09](https://user-images.githubusercontent.com/47241114/70543611-f50d6300-1b6a-11ea-90fd-6b76adaaf2f4.png)
