### ISSUE TITLE
college physics: style footnotes

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1665]
Footnotes in College Physics should be styled with specs form Carnival Theme.

**Comment by wilkus27** [comment]
Note: no changes to provide to Theme Design Specs. Step `Spec Update` can be skipped.

**Comment by MartaSztuka** [comment]
Footnotes are styled.
![Screenshot from 2019-12-10 16-38-54](https://user-images.githubusercontent.com/47241114/70544005-9f858600-1b6b-11ea-8183-c71c8e179fbe.png)
