### ISSUE TITLE
AP Bio Baking Issue

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#1668]
Similar to: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/1667 

This also occurs in AP Bio per: 
https://katalysteducation.slack.com/archives/C196UGS2C/p1574182065497800?thread_ts=1574175321.471900

Here is the figure with the same error (cnxepub ERROR Bad href: #figure_19_03_04) in Biology for Ap Courses in the baked file:

**Comment by brittweinstein** [comment]
@openstaxalina assigning to you since this only occurs once. Not sure how you'd like to handle this...

**Comment by lwtchu** [comment]
i assume this is fixed. closign
