### ISSUE TITLE
University Physics vol1: add style to footnotes 

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1673]
Footnotes in University Physics vol1 should be styled according to Carnival Theme Specs.
Related issue: https://github.com/openstax/cnx-recipes/issues/437

**Comment by MartaSztuka** [comment]
Footnote is styled
![Screenshot from 2019-12-19 12-45-57](https://user-images.githubusercontent.com/47241114/71171217-8a8caf00-225d-11ea-98d5-44d6a94bbba2.png)
