### ISSUE TITLE
Biology for AP Courses: add style to tables in exercises

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1675]
Tables in exercises in Biology for AP Courses need to have set width and layout to fit the containing div in the column layout.
![image](https://user-images.githubusercontent.com/55203598/70428899-c793bd00-1a77-11ea-9089-a35b90313447.png)

**Comment by MartaSztuka** [comment]
![Screenshot from 2019-12-13 09-21-53](https://user-images.githubusercontent.com/47241114/70784687-0da79400-1d8a-11ea-9c05-80cad484f08f.png)

**Comment by MartaSztuka** [comment]
Tables look good.
![Screenshot from 2019-12-17 16-57-47](https://user-images.githubusercontent.com/47241114/71011983-a32a8700-20ee-11ea-8c81-52493fb4056f.png)
