### ISSUE TITLE
HS Physics: Collate Section Summary

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1679]
# What happened?

The section summary should collate to End of Chapter.

Content has class 'summary'.

The section summaries should collate to an end of chapter composite page called "Chapter Review" that appears after the composite page "Key Terms" (currently called "Glossary", but this will be changed).

Also, the header for the section title should appear, like they do here: https://vendor.cnx.org/contents/1Q9uMg_a@13.71:h3Rh6rqz@13.71/Summary
These headers should be **links** -- is there a release flag for that?

# Environment:

- **Book(s)**: HS Physics
- **URL/Server**: https://content04.cnx.org/contents/IKZFuFtg:ifMqCsrs (note: content will be copied to katalyst01.cnx.org)
- **Location (page number, chapter/section)**: Any non-intro section
- **Suggested nearby searchable text**: varies
- **Browser**: Chrome

# Screenshots
[Uploading... HSPhysicsSummary.png ]

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:qyS-0Xb0@4.1/Section-Summary
![Screenshot from 2020-01-13 11-45-33](https://user-images.githubusercontent.com/47241114/72249720-3e355480-35fa-11ea-8b19-f658d00bb25c.png)
