### ISSUE TITLE
HS Physics: Change "Glossary" to "Key Terms"

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1680]
@openstaxalina commented on [Mon Dec 09 2019](https://github.com/openstax/oer.exports/issues/4002)

# What happened?

# Environment:

- **Book(s)**: HS Physics
- **URL/Server**: https://content04.cnx.org/contents/IKZFuFtg:mdsCq8U- (Note: content will be moved to katalyst01.cnx.org)
- **Location (page number, chapter/section)**: any end of chapter
- **Suggested nearby searchable text**: Glossary
- **Browser**: Chrome

# Screenshots
![HSPhysicsSummary.png](https://images.zenhubusercontent.com/5b57372fb01a900cfd923015/77e2dc5a-10b7-41de-beac-c2e9b344dc62)

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:IOQZ77nL@4.1/Key-Terms
![Screenshot from 2020-01-13 11-31-28](https://user-images.githubusercontent.com/47241114/72248893-83588700-35f8-11ea-8024-41f8f1e88be4.png)
