### ISSUE TITLE
HS Physics: Collate Key Equations 

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1681]
# What happened?

Key Equations should be unnumbered, unstyled tables that collate to their own end of chapter section.  The section should have title "Key Equations", and the tables will be separated by headers for each module.  These headers should be links, if possible.

This section should fall after the Summary section.

Key Equations are in a section with class="key-equations".

# Environment:

- **Book(s)**: HS Physics
- **URL/Server**: https://content04.cnx.org/contents/IKZFuFtg:c89AcT1A (note: content is being migrated to katalyst01.cnx.org)
- **Location (page number, chapter/section)**: some non-intro sections: 1.3, 2.3, 2.4, etc.
- **Suggested nearby searchable text**: "Key Equations"
- **Browser**: Chrome

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:P2EmVF5k@4.1/Key-Equations
![Screenshot from 2020-01-13 11-47-04](https://user-images.githubusercontent.com/47241114/72249823-79378800-35fa-11ea-91fa-83d6a6686144.png)
