### ISSUE TITLE
HS Physics: Chapter Review - Concept Items

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1682]
# What happened?

Concept Items should collate to end of chapter. These should come after the Key Equations composite page.  If possible, nest Concept Items, Critical Thinking Items, Problems and Performance Task under the header "Chapter Review" (similar to how items are nested under "Chapter Review" here: https://vendor.cnx.org/contents/1Q9uMg_a:xrlIGQSi).

The section has class "concept".

Section headers should appear before the exercises from each section like they do here: https://vendor.cnx.org/contents/1Q9uMg_a@13.71:xrlIGQSi@13.71/Conceptual-Questions.
These headers should be links, if possible.

Also, Concept Items should start at "1" with each chapter:
![HSPhysicsConceptItems.png](https://images.zenhubusercontent.com/5b57372fb01a900cfd923015/d9cf7330-3a7a-494a-a273-0e08d41f03a3)

# Environment:

- **Book(s)**: HS Physics
- **URL/Server**: https://content04.cnx.org/contents/IKZFuFtg:vOVpVdiV (note: content is being migrated to katalyst01.cnx.org)
- **Location (page number, chapter/section)**: Most/all non-intro sections (2.1, 2.2, 2.3, 3.1, etc.)
- **Suggested nearby searchable text**: "Concept Items"
- **Browser**: Chrome

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:AZboNrrt@4.1/Concept-Items
![Screenshot from 2020-01-13 12-24-27](https://user-images.githubusercontent.com/47241114/72252497-a9355a00-35ff-11ea-9942-c42d072ad887.png)
