### ISSUE TITLE
HS Physics: Chapter Review - Critical Thinking Items

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1683]
# What happened?

Critical Thinking problems should collate to end of chapter. These should come after the Concept Items.  If possible, nest Concept Items, Critical Thinking Items, Problems and Performance Task under the header "Chapter Review" (similar to how items are nested under "Chapter Review" here: https://vendor.cnx.org/contents/1Q9uMg_a:xrlIGQSi).

The section has class "critical-thinking".

Section headers should appear before the exercises from each section like they do here: https://vendor.cnx.org/contents/1Q9uMg_a@13.71:xrlIGQSi@13.71/Conceptual-Questions.
These headers should be links, if possible.

Critical Thinking items should continue with the numbering from the Concept Items.  If Concept Items ends at "6", Critical Thinking starts at "7".

# Environment:

- **Book(s)**: HS Physics
- **URL/Server**: https://content04.cnx.org/contents/IKZFuFtg:vOVpVdiV (note: content is being migrated to katalyst01.cnx.org)
- **Location (page number, chapter/section)**: Most/all non-intro sections (2.1, 2.2, 2.3, 3.1, etc.)
- **Suggested nearby searchable text**: "Critical Thinking"
- **Browser**: Chrome

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:XfbtfaZw@4.1/Critical-Thinking-Items
![Screenshot from 2020-01-13 12-33-25](https://user-images.githubusercontent.com/47241114/72253040-ea7a3980-3600-11ea-9ab0-4c702dc04e6a.png)
