### ISSUE TITLE
HS Physics: Chapter Review - Problems

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1684]
@openstaxalina commented on [Mon Dec 09 2019](https://github.com/openstax/oer.exports/issues/4003)

# What happened?

Problems should collate to end of chapter. These should come after the Critical Thinking items.  If possible, nest Concept Items, Critical Thinking Items, Problems, and Performance Task under the header "Chapter Review" (similar to how items are nested under "Chapter Review" here: https://vendor.cnx.org/contents/1Q9uMg_a:xrlIGQSi).

The section has class "problem".

Section headers should appear before the exercises from each section like they do here: https://vendor.cnx.org/contents/1Q9uMg_a@13.71:xrlIGQSi@13.71/Conceptual-Questions.
These headers should be links, if possible.

Problems should continue with the numbering from the Critical Thinking items.  If Critical Thinking items end at "10", Problems start at "11".

# Environment:

- **Book(s)**: HS Physics
- **URL/Server**: https://content04.cnx.org/contents/IKZFuFtg:ENI1tClk (note: content is being migrated to katalyst01.cnx.org)
- **Location (page number, chapter/section)**: Some non-intro sections 
- **Suggested nearby searchable text**: "Problems"
- **Browser**: Chrome

**Comment by wilkus27** [comment]
Before this section will be moved to the EOC its class has to be changed. 

When new section is created in EOC it gets class `os-classFromSection-container`, so in this case the class is `os-problem-container`. But this one has already been used for another element, what causes problems in recipes.

**Comment by wilkus27** [comment]
NOTE: when this issue will be ready for testing, issue https://github.com/openstax/cnx-recipes/issues/1612 also should be tested.

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:jwVJIC81@4.1/Problems
![Screenshot from 2020-01-13 12-35-00](https://user-images.githubusercontent.com/47241114/72253144-21e8e600-3601-11ea-8447-e83f252c1928.png)
