### ISSUE TITLE
HS Physics: Chapter Review - Performance Task

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1685]
# What happened?

Performance Task should collate to end of chapter. These should come after the Problems.  If possible, nest Concept Items, Critical Thinking Items, Problems and Performance Task under the header "Chapter Review" (similar to how items are nested under "Chapter Review" here: https://vendor.cnx.org/contents/1Q9uMg_a:xrlIGQSi).

The section has class "performance".

Section header should appear before the Performance Task, like it does here: https://vendor.cnx.org/contents/1Q9uMg_a@13.71:xrlIGQSi@13.71/Conceptual-Questions.
These headers should be links, if possible.

Performance Task should continue with the numbering from the Problems. If Problems end at "28", Performance Task is "29".

# Environment:

- **Book(s)**: HS Physics
- **URL/Server**: https://content04.cnx.org/contents/IKZFuFtg:-lrSLijf (note: content is being migrated to katalyst01.cnx.org)
- **Location (page number, chapter/section)**: One non-intro section in each chapter (specific section varies by chapter)
- **Suggested nearby searchable text**: "Performance Task"
- **Browser**: Chrome

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:XQomN7TQ@4.1/Performance-Task
![Screenshot from 2020-01-13 12-25-52](https://user-images.githubusercontent.com/47241114/72252602-db46bc00-35ff-11ea-9f7d-3bda801451a1.png)
