### ISSUE TITLE
summary class needs to collate in webview

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#1686]
# Scenario
We changed to using the class 'summary' for chapter summary. Currently, this is not being collated in webview, but it should. 

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [ x] Yes  [ ] No  

![Screen Shot 2019-12-10 at 9 51 16 AM](https://user-images.githubusercontent.com/5865292/70547692-ec9b3500-1b36-11ea-8cd8-81e945962aff.png)

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [x ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ x] content03
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by openstaxalina** [comment]
Test content: 
https://easyvm5.cnx.org/contents/h2TUSN8V@3.1:Ig9JNInZ@2/Introduction
(long UUID: 8764d448-df15-4479-9df6-c93ab5c6176e on easyvm5)

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-01-23 at 2 08 28 PM](https://user-images.githubusercontent.com/24909007/73019808-f11b6480-3de9-11ea-8ea8-84e177e2ef32.png)

**Comment by openstaxalina** [comment]
@brittany-johnson is it possible to have it say "Summary" instead of "Section Summary" and to not have the section title ("1.7 blah blah"), as we did for the PDF (example here: https://github.com/openstax/oer.exports/issues/4007#issuecomment-573214659)

**Comment by brittany-johnson** [comment]
Ahhh! Yes, sorry. I thought this was just updating the class. @openstaxalina

**Comment by openstaxalina** [comment]
@brittany-johnson no it's my fault - I never added this to the card.  Should I create a new card or maybe bump the estimate up on this one?

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-01-23 at 2 39 10 PM](https://user-images.githubusercontent.com/24909007/73021958-3e013a00-3dee-11ea-85a9-32290a28f8be.png)

**Comment by brittany-johnson** [comment]
No its okay, I fixed it! @openstaxalina

**Comment by openstaxalina** [comment]
woohoo, thank you @brittany-johnson !

**Comment by omehes** [comment]
verified as discussed with Alan and BJ on master branch after injecting recipe and clearing cash, the webview did not reflect what was expected ("Summary") and Summary is now missing from cosu completely

![cosu_err111](https://user-images.githubusercontent.com/44207656/73303155-7f715b00-41db-11ea-97b0-817e30c9f657.png)

**Comment by omehes** [comment]
Reverified after latest rebake by Helen. 

![cosu_111a](https://user-images.githubusercontent.com/44207656/73399746-6802a280-42ad-11ea-9584-2ac58462cbbf.png)

**Comment by openstaxalina** [comment]
Verified on staging: https://staging.cnx.org/contents/2Uz_ZeWp@1.2:q4EcXeDe@1.2/Summary

**Comment by openstaxalina** [comment]
Verified on content03:
![Screen Shot 2020-02-12 at 4 19 34 PM](https://user-images.githubusercontent.com/7863733/74382700-7b386680-4db3-11ea-8c3d-255dbe817798.png)

**Comment by openstaxalina** [comment]
Verified on content03: ![Screen Shot 2020-02-12 at 4 20 13 PM](https://user-images.githubusercontent.com/7863733/74382745-90ad9080-4db3-11ea-9ada-38e0a15f67e8.png)
