### ISSUE TITLE
HS Physics: Test Prep - Short Answer

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1687]
@openstaxalina commented on [Tue Dec 10 2019](https://github.com/openstax/oer.exports/issues/4009)

# What happened?

Short Answer should collate to end of chapter. These should come after the  Multiple Choice.  If possible, nest Multiple Choice, Short Answer, and Extended Response under the header "Test Prep" (similar to how items are nested under "Chapter Review" here: https://vendor.cnx.org/contents/1Q9uMg_a:xrlIGQSi).

NOTE: "Test Prep" may be duplicated i.e. Test Prep --> Test Prep Short Answer.  In that case, we can change "Test Prep Short Answer" to "Short Answer" in the content.

The section has class "short-answer".

Section headers should appear before the items, like they do here: https://vendor.cnx.org/contents/1Q9uMg_a@13.71:xrlIGQSi@13.71/Conceptual-Questions.
These headers should be links, if possible.

Short Answer should be numbered, and the numbers should continue wherever Multiple Choice left off (for example, if the last Multiple Choice is number 44, Test Prep Short Answer starts with 45).

# Environment:

- **Book(s)**: HS Physics
- **URL/Server**: https://content04.cnx.org/contents/IKZFuFtg:vOVpVdiV (note: content is being migrated to katalyst01.cnx.org)
- **Location (page number, chapter/section)**: Some non-intro sections in each chapter (specific sections varies by chapter)
- **Suggested nearby searchable text**: "Short Answer"
- **Browser**: Chrome

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:x1obKz9G@4.1/Short-Answer
![Screenshot from 2020-01-13 12-28-46](https://user-images.githubusercontent.com/47241114/72252782-4db79c00-3600-11ea-8e4d-86f77c311d38.png)
