### ISSUE TITLE
HS Physics: Test Prep - Multiple Choice

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1688]
@openstaxalina commented on [Tue Dec 10 2019](https://github.com/openstax/oer.exports/issues/4008)

# What happened?

Multiple Choice should collate to end of chapter. These should come after the Performance Task.  If possible, nest Multiple Choice, Short Answer, and Extended Response under the header "Test Prep" (similar to how items are nested under "Chapter Review" here: https://vendor.cnx.org/contents/1Q9uMg_a:xrlIGQSi).

NOTE: "Test Prep" may be duplicated i.e. Test Prep --> Test Prep Multiple Choice.  In that case, we can change "Test Prep Multiple Choice" to "Multiple Choice" in the content.

The section has class "multiple-choice".

Section headers should appear before the items, like they do here: https://vendor.cnx.org/contents/1Q9uMg_a@13.71:xrlIGQSi@13.71/Conceptual-Questions.
These headers should be links, if possible.

Multiple Choice should be numbered, and the numbers should continue wherever Performance Task left off (for example, if Performance Task is number 38, Test Prep Multiple Choice starts with 39).

# Environment:

- **Book(s)**: HS Physics
- **URL/Server**: https://content04.cnx.org/contents/IKZFuFtg:vOVpVdiV (note: content is being migrated to katalyst01.cnx.org)
- **Location (page number, chapter/section)**: Some non-intro sections in each chapter (specific sections varies by chapter)
- **Suggested nearby searchable text**: "Multiple Choice"
- **Browser**: Chrome

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:NLqAP-QZ@4.1/Multiple-Choice
![Screenshot from 2020-01-13 12-31-14](https://user-images.githubusercontent.com/47241114/72252933-9bcc9f80-3600-11ea-83d1-f3e079bfdbaf.png)
