### ISSUE TITLE
HS Physics: Test Prep - Extended Response

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1689]
# What happened?

Extended Response should collate to end of chapter. These should come after the Short Answer.  If possible, nest Multiple Choice, Short Answer, and Extended Response under the header "Test Prep" (similar to how items are nested under "Chapter Review" here: https://vendor.cnx.org/contents/1Q9uMg_a:xrlIGQSi).

NOTE: "Test Prep" may be duplicated i.e. Test Prep --> Test Prep Extended Response.  In that case, we can change "Test Prep Extended Response" to "Extended Response" in the content.

The section has class "extended-response".

Section headers should appear before the items, like they do here: https://vendor.cnx.org/contents/1Q9uMg_a@13.71:xrlIGQSi@13.71/Conceptual-Questions.
These headers should be links, if possible.

Extended Response should be numbered, and the numbers should continue wherever Short Answer left off (for example, if the last Short Answer is number 49, Test Prep Extended Response starts with 50).

# Environment:

- **Book(s)**: HS Physics
- **URL/Server**: https://content04.cnx.org/contents/IKZFuFtg:RX_B1oka (note: content is being migrated to katalyst01.cnx.org)
- **Location (page number, chapter/section)**: Some non-intro sections in each chapter (specific sections varies by chapter)
- **Suggested nearby searchable text**: "Extended Response"
- **Browser**: Chrome

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:zguyEMns@4.1/Extended-Response
![Screenshot from 2020-01-13 12-36-54](https://user-images.githubusercontent.com/47241114/72253249-65dbeb00-3601-11ea-9c2d-4fb4d5d0c215.png)
