### ISSUE TITLE
Figure out how to handle extra-long links in Baked Styles

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#1694]
# Scenario
Following on from [oer.exports issue 3995](https://github.com/openstax/oer.exports/issues/3995), we need to figure out how to implement wrapping for extra-long links to prevent them from shooting off over the side of the screen.

The examples located in oer.exports were in suggested resources and footnotes (see below) but it is possible that this issue could crop up in other places as well. 

# Examples
## Suggested Resources
![image](https://user-images.githubusercontent.com/12678235/70812662-ae4b8300-1d8d-11ea-87da-4c26a40bf215.png)
Found in: [Eship Chapter 7 EoC Materials](https://easyvm5.cnx.org/contents/C2WpSVax@4.1:0z-LThbg@4.1/Suggested-Resources)

## Footnotes
![image](https://user-images.githubusercontent.com/12678235/70812684-b4416400-1d8d-11ea-909a-267ad2253991.png)
Found in: [Eship Chapter 2, Module 3](content01.cnx.org/content/col10104/1.6)

**Comment by openstaxalina** [comment]
Adding some acceptance criteria:

# Acceptance Criteria 

- [ ] long URLs break across lines without trailing into the margin
- [ ] URLs that can fit on one line do not break (this could increase page count)
- [ ] URLs that are meant to display inline (like in a paragraph) continue to do so

**Comment by brittweinstein** [comment]
@openstaxalina is this critical for DD? Can we move to FF?

**Comment by openstaxalina** [comment]
Symmetry would flag these issues if they appeared in any of the three books we're delivering to print.  So we can move this to f.f where we will likely put other Symmetry issues.

**Comment by brittweinstein** [comment]
@Stackblocks could you generate and see if this is still happening?

**Comment by Stackblocks** [comment]
@brittweinstein It is still happening with current code / data

![image](https://user-images.githubusercontent.com/12678235/101816892-38d0da80-3ae7-11eb-8aed-e435a20acf02.png)

**Comment by lwtchu** [comment]
@Stackblocks i'm going to add this to the eship epic(?) - but this will probably apply to all long text

**Comment by brittweinstein** [comment]
@lwtchu will take a cursory look first.


@Stackblocks we can timebox this to a day or two --- if this doesn't happen @lwtchu may be able to identify another alternative or a content workaround. We can't use a short link because this is a reference.

**Comment by lwtchu** [comment]
Truncated link works. GOnNAnnan ClOSe
