### ISSUE TITLE
Microbiology/College Physics/Biology 2e footnotes

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#1698]
# Scenario
Footnotes are being compiled differently and are in much different places in the chapters than in the current production PDF. 

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
every chapter

* **Images or Screenshots Included:** [x ] Yes  [ ] No  
Prod PDF on right, new on left:
![Screen Shot 2019-12-16 at 9 14 30 AM](https://user-images.githubusercontent.com/5865292/70919200-0bda0c80-1fe6-11ea-8359-c2592a3ff19f.png)

# Environment: (required)
* **Medium**: [ ] REX [ x] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [x ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [x] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by brittweinstein** [comment]
@yblock can you confirm that footnote number 4 occurs on the correct page, the page following this example? If so, this would be the desired behaviour.

**Comment by openstaxalina** [comment]
(Specifically, the desired behavior = footnote falls on the same page where the callout -- the super script -- to that footnote appears.)

**Comment by yblock** [comment]
No it does not fall on the same page as the callout. Here is a more egregious example 

![Screen Shot 2019-12-16 at 10 18 25 AM](https://user-images.githubusercontent.com/5865292/70923463-8a867800-1fed-11ea-95a4-8f0465f61bea.png)

**Comment by openstaxalina** [comment]
Got it, thanks!

Note for devs: this is how those first two footnotes look in the oer.exports PDF:
![Screen Shot 2019-12-16 at 10 32 21 AM](https://user-images.githubusercontent.com/7863733/70924636-7ba0c500-1fef-11ea-84ea-5ccbc237d9ca.png)
![Screen Shot 2019-12-16 at 10 32 38 AM](https://user-images.githubusercontent.com/7863733/70924638-7ba0c500-1fef-11ea-99b4-f0696a5d74f6.png)

**Comment by oscryan** [comment]
This is also the case for Concepts of Biology

**Comment by oscryan** [comment]
<img width="1334" alt="Screen Shot 2020-01-06 at 3 13 20 PM" src="https://user-images.githubusercontent.com/1895432/71849234-31af7a00-3097-11ea-9b19-b5967f4dde5c.png">

**Comment by brittweinstein** [comment]
@lwtchu could you please see if this occurs in Bio 2e and/or College Physics as well?

**Comment by lwtchu** [comment]
![Screen Shot 2020-02-05 at 3 41 04 PM](https://user-images.githubusercontent.com/11299125/73885747-f044f280-482d-11ea-9e82-d3d1be6a3aae.png)
![Screen Shot 2020-02-05 at 3 42 02 PM](https://user-images.githubusercontent.com/11299125/73885827-12d70b80-482e-11ea-80f6-0ce9aeb5cc67.png)

College Physics Chapter 4 - footnote is at the end of the module. Superscript is also super big


![Screen Shot 2020-02-05 at 3 46 34 PM](https://user-images.githubusercontent.com/11299125/73886196-bde7c500-482e-11ea-8a01-23d37f3549bf.png)
![Screen Shot 2020-02-05 at 3 46 18 PM](https://user-images.githubusercontent.com/11299125/73886200-bf18f200-482e-11ea-8756-c8eaeda53712.png)

Biology 2e Chapter 9 - same thing happening here. footnote pops to the end of the module and the superscript is also hella big

**Comment by lwtchu** [comment]
@brittweinstein i added the book labels for u

**Comment by MartaSztuka** [comment]
**Biology 2e**
![Screenshot from 2020-03-25 10-33-02](https://user-images.githubusercontent.com/47241114/77522144-08c3a780-6e84-11ea-8637-917dac49e7e2.png)
**College Physics**
![Screenshot from 2020-03-25 10-31-53](https://user-images.githubusercontent.com/47241114/77522041-e03bad80-6e83-11ea-89eb-320cb0afd8bb.png)

**Comment by MartaSztuka** [comment]
Hi, @brittany-johnson in those 2 books footnotes have short line, also in Microbiology line is missing in this big footnote.
**Microbiology**
![Screenshot from 2020-03-25 16-23-31](https://user-images.githubusercontent.com/47241114/77553396-0cbbed80-6eb5-11ea-8105-a79f2589c9df.png)
![Screenshot from 2020-03-25 16-23-18](https://user-images.githubusercontent.com/47241114/77553400-0ded1a80-6eb5-11ea-90bc-4276579e32a1.png)
**Concepts of Biology**
![Screenshot from 2020-03-25 16-19-49](https://user-images.githubusercontent.com/47241114/77552947-78518b00-6eb4-11ea-96d2-c596afbc6d66.png)

**Comment by brittany-johnson** [comment]
@MartaSztuka How were Concepts of Biology and Microbiology generated? I just generated Concepts of Biology and my screenshot looks very different. 
<img width="1652" alt="Screen Shot 2020-03-25 at 10 56 54 AM" src="https://user-images.githubusercontent.com/24909007/77557134-64dbfb00-6e87-11ea-8c3b-8c8b1376203d.png">

**Comment by MartaSztuka** [comment]
@brittany-johnson it was baked on `carnival100` I'll fetch it again and test, ok?

**Comment by brittany-johnson** [comment]
@MartaSztuka The code is on `gilded.gza`. 
For the other footnote issue that you tested were you given a PDF to test?

**Comment by MartaSztuka** [comment]
@brittany-johnson Yes, I've got PDFs for others, will bake microbiology and concepts of biology there, thanks!

**Comment by brittany-johnson** [comment]
@MartaSztuka I'll have to give you the PDFs, they need to be generated with code from this PR: openstax/rhaptos.cnxmlutils#169

I'll message them to you after I switch branches and regenerate

**Comment by MartaSztuka** [comment]
@brittany-johnson ok, thank you!

**Comment by MartaSztuka** [comment]
**Microbiology**
![Screenshot from 2020-03-26 08-33-17](https://user-images.githubusercontent.com/47241114/77621328-85b25800-6f3c-11ea-8d66-463cd1b438c3.png)
![Screenshot from 2020-03-26 08-33-08](https://user-images.githubusercontent.com/47241114/77621332-86e38500-6f3c-11ea-95e5-4d00cf863314.png)
**Concepts of Biology**
![Screenshot from 2020-03-26 08-35-00](https://user-images.githubusercontent.com/47241114/77621419-b85c5080-6f3c-11ea-8612-c2fab34e5c10.png)
