### ISSUE TITLE
A&P Solutions

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#1699]
# Scenario
The solutions section is missing from the new PDF

# Acceptance Criteria (required)
Solutions should be in the new PDF

# Steps to Reproduce (required)
* **Images or Screenshots Included:** [x ] Yes  [ ] No  
![Screen Shot 2019-12-16 at 11 43 42 AM](https://user-images.githubusercontent.com/5865292/70929869-9e37db80-1ff9-11ea-8860-dae2ae3b154e.jpg)

# Environment: (required)
* **Medium**: [ ] REX [ x] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [x ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by openstaxalina** [comment]
The Answer Key is suppressed by the recipe because we couldn't achieve the same set of answers in the recipe as in the oer.exports PDF.  We uploaded the Answer Key as an ancillary for this title on openstax.org.  It is okay that the baked styles PDF will not have the answer key - closing.

**Comment by openstaxalina** [comment]
(Info on which titles won't have answer key in baked styles PDF here:https://docs.google.com/spreadsheets/d/1mxjUDohm0sSHnSFi76e_8MpInUPl9r5bpVDpLxJhG1A/edit#gid=0)
