### ISSUE TITLE
Style chapters and modules in University Physics 

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1701]
The chapter and modules in University Physics should be styled according to Carnival Theme Specs Related Issues: #1479, #1072

**Comment by MartaSztuka** [comment]
Chapters and modules headers are styled.
![Screenshot from 2019-12-19 11-46-36](https://user-images.githubusercontent.com/47241114/71167882-d8051e00-2255-11ea-96b4-a9c02bac1825.png)
![Screenshot from 2019-12-19 11-46-21](https://user-images.githubusercontent.com/47241114/71167883-d89db480-2255-11ea-8a87-2b3d5b7dac24.png)
