### ISSUE TITLE
NEW HS Physics: Condensed Box Note

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1705]
![Screen Shot 2019-12-18 at 12 54 32 PM](https://user-images.githubusercontent.com/11299125/71114514-914fef00-2195-11ea-9bd2-f1a644fcb2d4.png)

Tips for Success  (`<note class="tips-for-success">`). These occur throughout the book.

Title: `TIPS FOR SUCCESS`
Font: Muli Black
Font size: 10.8pt, font-scale(1)
Background color: Grey1: `#EEEAE0`
Background: Full width (6.5 in/margin to margin)
Padding top, right, left, bottom: 1em (12px)

**Comment by wilkus27** [comment]
This is styled within PR: https://github.com/openstax/cnx-recipes/pull/1835

**Comment by wilkus27** [comment]
@lwtchu specs to provide to Theme Design Specs you can find in https://github.com/openstax/cnx-recipes/issues/1839

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-10 15-36-18](https://user-images.githubusercontent.com/47241114/74159365-f404ba80-4c1b-11ea-8201-c150fd031d18.png)
