### ISSUE TITLE
NEW HS Physics: Condensed Box Exercise

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1706]
![Screen Shot 2019-12-18 at 12 54 32 PM](https://user-images.githubusercontent.com/11299125/71114514-914fef00-2195-11ea-9bd2-f1a644fcb2d4.png)

For Grasp Check (`<exercise class="os-exercise grasp-check">`)

Title: `GRASP CHECK`
Font: Muli Black
Font size: 10.8pt, font-scale(1)
Background color: Grey1: `#EEEAE0`
Background: Full width (6.5 in/margin to margin)
Padding top, right, left, bottom: 1em (12px)

**Comment by wilkus27** [comment]
This is styled within PR: https://github.com/openstax/cnx-recipes/pull/1835.

Note: title **Grasp Check** is missing. Will be added by recipe. Here is the issue: https://github.com/openstax/cnx-recipes/issues/1853

**Comment by wilkus27** [comment]
@lwtchu specs to provide to Theme Design Specs are in https://github.com/openstax/cnx-recipes/issues/1839

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-10 14-00-12](https://user-images.githubusercontent.com/47241114/74152012-b26d1300-4c0d-11ea-8972-ab970a2ea0a9.png)
![Screenshot from 2020-02-10 13-59-58](https://user-images.githubusercontent.com/47241114/74152013-b305a980-4c0d-11ea-90fc-2f99e0b3e4a4.png)
