### ISSUE TITLE
Add style to learning objectives in University Physics vol1

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1709]
Learning Objectives should be styled according to Carnival Specs. 
Related issue: #1077.
No changes in Theme Design are needed.

**Comment by MartaSztuka** [comment]
Styled.
![Screenshot from 2020-01-09 10-05-07](https://user-images.githubusercontent.com/47241114/72054105-a3223f00-32c8-11ea-9b15-17712f52ff51.png)
