### ISSUE TITLE
Add styles to figures in University Physics vol1

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1712]
Figures should be styled according to Carnival Specs. Related issue: #1081.
No changes in Theme Design Specs are needed.

**Comment by MartaSztuka** [comment]
Styles added.
![Screenshot from 2020-01-08 17-09-40](https://user-images.githubusercontent.com/47241114/71995631-2e54f380-323b-11ea-82f5-718138a55179.png)
