### ISSUE TITLE
EOCsection-links flag doesn't work for composite chapters

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1714]
When `EOCsection-links` flag is enabled, section headers in modules from EOC should be changed to links to those sections. It doesn't work for modules inside composite chapters in EOC.

**Comment by wilkus27** [comment]
Ready for testing. No changes in style specs.

**Comment by MartaSztuka** [comment]
Tested on University Physics vol 1
![Screenshot from 2020-01-09 15-23-56](https://user-images.githubusercontent.com/47241114/72075503-2442fb80-32f4-11ea-8042-62ee64d375a4.png)
