### ISSUE TITLE
Carnival Theme: tables centering

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1716]
Tables in Carnival Theme should display at the center. Width should be set to the widest element, and number/caption of the table should display on the left side of the table.

Examples:

![image](https://user-images.githubusercontent.com/40228854/71264269-019c7300-2344-11ea-9606-9514db12fbc9.png)

![image](https://user-images.githubusercontent.com/40228854/71264239-f0ebfd00-2343-11ea-9032-747de52ac04c.png)

![image](https://user-images.githubusercontent.com/40228854/71264288-10832580-2344-11ea-8df7-36cb5ba59a1d.png)

**Comment by wilkus27** [comment]
NOTE: waiting for https://github.com/openstax/cnx-recipes/pull/1463. In this PR tables are styled in this way in Anatomy and Chemistry. After merging it, changes can be apply for other books from Carnival Theme.

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-10 10-58-26](https://user-images.githubusercontent.com/47241114/74139825-5053e400-4bf4-11ea-9ce4-d4842e075989.png)
![Screenshot from 2020-02-10 11-01-24](https://user-images.githubusercontent.com/47241114/74140078-b5a7d500-4bf4-11ea-97c5-d0d6fa45c6ed.png)
![Screenshot from 2020-02-10 11-06-17](https://user-images.githubusercontent.com/47241114/74140460-644c1580-4bf5-11ea-8268-769e94353b5a.png)
