### ISSUE TITLE
CLEAN UP: Rework tables shapes

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1717]
Most of tables have such structure:

```
div.os-table
 | div.some-class
 | table.unique-class
 | div.os-caption-container
```
Some of them has additional title and/or caption, but always there is container with class `os-table` which has child - table with its unique class.

Current problem is that all the table settings are pointing at `_selectors: (".os-table")`, so all tables shapes have impact on each other.

**Comment by wilkus27** [comment]
**Conclusion after discussion on the slack:**

per Helene

> Moving the type of table to the container rather than the table itself then changing the setting selectors makes sense. I wonder if maybe copying the table class with a different name (something like os-fakeTitle-container) so we can select the specific table container or table itself would be optimal? The settings then will need to be changed to a unique selector. If we decide not to change the recipes, an alternative would be to create new components with unique classes instead of using only shapes and use the new namespaced components for the shapes.

**Comment by MartaSztuka** [comment]
Chemistry![Screenshot from 2020-05-12 10-18-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5c5ef53b-f2c5-414e-8b80-ea5c25cb589d)
![Screenshot from 2020-05-12 10-07-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7a3d9dfb-fe8d-4d0c-8170-6372c13179b7)
HS Physics![Screenshot from 2020-05-12 10-21-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f9dea57f-ef51-4a6a-b1a8-13c955d9c7cb)![Screenshot from 2020-05-12 10-19-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9f52c551-ef74-4a80-ba38-e053e6f9faeb)
![Screenshot from 2020-05-12 10-10-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/beda6189-bef7-4152-a85f-f2c60e4c9054)![Screenshot from 2020-05-12 10-12-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cfd7d747-4d1b-472c-aec5-5c163e98d244)
AP Biology![Screenshot from 2020-05-12 10-16-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b2fefcf4-bbb1-423d-9bd7-b1254da5c137)
![Screenshot from 2020-05-12 10-14-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/aa9f34fe-7fce-4b97-b58b-0c6ac0af363e)

**Comment by MartaSztuka** [comment]
Chemistry 2e
![Screenshot from 2020-05-12 11-07-48](https://user-images.githubusercontent.com/47241114/81665401-f2c47300-9440-11ea-8635-754bbcfe65d9.png)
HS Physics
![Screenshot from 2020-05-12 11-16-59](https://user-images.githubusercontent.com/47241114/81666297-248a0980-9442-11ea-9437-75023d45f762.png)
AP Biology
![Screenshot from 2020-05-12 11-29-30](https://user-images.githubusercontent.com/47241114/81667698-e261c780-9443-11ea-8f19-adfb1d315cbd.png)
