### ISSUE TITLE
Caption text way too big in carnival

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1720]
# Scenario

Caption text way too big in carnival
# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)
<img width="536" alt="Screen Shot 2019-12-20 at 10 32 51 AM" src="https://user-images.githubusercontent.com/1895432/71269122-2842b580-2314-11ea-9a42-ef838e98fe5f.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by lwtchu** [comment]
Should be addressed with this #1786
