### ISSUE TITLE
More outrageous table padding

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1721]
# Scenario
The padding on this unnumbered unstyled table is outrageous.
https://legacy.cnx.org/content/m66427/latest/?collection=col24361/latest
# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)
<img width="551" alt="Screen Shot 2019-12-20 at 10 39 05 AM" src="https://user-images.githubusercontent.com/1895432/71269468-0eee3900-2315-11ea-9a16-77089d17aac1.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by brittweinstein** [comment]
This should be v-grid(1).

**Comment by Stackblocks** [comment]
After the work in #1797 to create table-v-grid, it looks like this:
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/20906ab6-4ce2-4401-827d-1bc7c8344e66)

 is that acceptable @oscryan ?

**Comment by oscryan** [comment]
I think @lwtchu gets to decide. That looks better, but it is still v tall to me

**Comment by lwtchu** [comment]
@Stackblocks can you send me the pdf for this so i can compare to the other pdf you gave me.

**Comment by lwtchu** [comment]
LOOK COOL BYE
