### ISSUE TITLE
All figures should be centered

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1723]
# Scenario
No figures are centered

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)
<img width="543" alt="Screen Shot 2019-12-20 at 10 43 09 AM" src="https://user-images.githubusercontent.com/1895432/71269701-9340bc00-2315-11ea-912f-079b93b8bf9e.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by lwtchu** [comment]
HELLO

if the media is in a FIGURE TAG it SHOULD BE CENTERED (WITH A CAPTION AND NUMBER)

media without a figure tag should be left aligned with no caption and no number

**Comment by ajluk** [comment]
Changes in TDS:
In Figure Shapes:
FigureContainer
added new properties:
display: flex,
justify-content: center,
align-items: center,
flex-direction: column,

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-10 14-28-58](https://user-images.githubusercontent.com/47241114/74154026-18f43000-4c12-11ea-9682-68e0ccc9fc02.png)
![Screenshot from 2020-02-10 14-47-04](https://user-images.githubusercontent.com/47241114/74155120-40e49300-4c14-11ea-9f2b-cd93f2729e7d.png)
