### ISSUE TITLE
Microbiology: List bullets outside of margin lines

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1724]
# What happened?
The bullets of the lists are outside of the margin.

# Reproducibility Details

Happens in a few places. See below.

# Environment:

- **Book(s)**: Microbiology
- **URL/Server**:  PDF
- **Location (page number, chapter/section)**: See learning objectives, section summary, main text (Chapter 2.1 "What are some things we can learn about these bacteria....", Boxed notes (See Clinical Focus Part 2 "Why is it important to identify the shape and growth...")
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots

![Screen Shot 2019-12-20 at 10 50 58 AM](https://user-images.githubusercontent.com/11299125/71270369-03037680-2317-11ea-9a54-f13862de904d.png)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by ajluk** [comment]
This issue has been resolved earlier: 
![image](https://user-images.githubusercontent.com/55203598/75762331-c8688200-5d3a-11ea-9603-dbe94e9caf29.png)

**Comment by paulinaszczucinska** [comment]
@MartaSztuka please test it, verify if it works and if it does, please close the issue.

**Comment by MartaSztuka** [comment]
It's fixed ![Screenshot from 2020-03-18 17-45-23](https://user-images.githubusercontent.com/47241114/76985292-4c785780-6940-11ea-8d53-3f94d6a269a9.png)
