### ISSUE TITLE
Link to Learning looks like it's trying to embed a video

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1725]
# Scenario
The Link to Learning features all have a vast whitespace following their link (which is unnecessarily line-returned).

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="549" alt="Screen Shot 2019-12-20 at 11 05 34 AM" src="https://user-images.githubusercontent.com/1895432/71271114-d51f3180-2318-11ea-87f7-cc5db874424d.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-03 10-34-00](https://user-images.githubusercontent.com/47241114/73641766-ca262380-4670-11ea-9b1d-af0894ae3f53.png)
