### ISSUE TITLE
University Physics vol1: Style equations and equation call out note. 

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1726]
Equations in University Physics vol1 need to be styled according to Carnival Specs. 
Related issues: https://github.com/openstax/cnx-recipes/issues/1482, https://github.com/openstax/cnx-recipes/issues/1479

Changes in Theme Design Specs:
New shape needs to be added **BoxCondensedEquationShape**
containing components:
 
- **CondensedContainer**
    background: book specific 
    padding-top: v-grid(.5),
    padding-bottom:v-grid(.5),
    margin-bottom: v-grid(1),

- **CondensedEquationContainer**
   position: relative,
   display: flex,
   flex-direction: row, 
   align-items: center,
    justify-content: center,
    margin-bottom: 0,

- **BoxedCondensedNoteEquationNumber** (I quess I must change it later to CondensedEquationNumber )
    position: absolute,
    right: 0,
    top: 50%,
    transform: translate(0, -50%),
    border-width: 0.025rem,
    border-style: solid,
    line-height: normal,
    padding: 0.5rem,
    margin-right: v-grid(.5),
This shape will be used by **EquationCallOut** note. The only book specific property need to be added is background in **CondensedContainer** for University Physics:
 background: (_ref: "scheme:::Grey1"),

**Comment by lwtchu** [comment]
Updated thank you :)

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-01-22 10-44-18](https://user-images.githubusercontent.com/47241114/72883207-32d1df80-3d04-11ea-80e0-e4f96b277b3d.png)
![Screenshot from 2020-01-22 10-47-06](https://user-images.githubusercontent.com/47241114/72883439-95c37680-3d04-11ea-816e-47cb08189478.png)

![Screenshot from 2020-01-22 10-43-47](https://user-images.githubusercontent.com/47241114/72883209-32d1df80-3d04-11ea-9f94-510788ccf365.png)
![Screenshot from 2020-01-22 10-46-03](https://user-images.githubusercontent.com/47241114/72883347-6f054000-3d04-11ea-8c1d-1e4d8f6c78f4.png)
