### ISSUE TITLE
Gigantically excessive vertical cell padding in tables

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1728]
# Scenario
too big. especially in appendices makes them 3x longer

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)
<img width="532" alt="Screen Shot 2019-12-20 at 11 15 08 AM" src="https://user-images.githubusercontent.com/1895432/71275834-267bf080-231a-11ea-98fd-8050e962b9b0.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by Stackblocks** [comment]
Resolved with https://github.com/openstax/cnx-recipes/issues/1797, same as https://github.com/openstax/cnx-recipes/issues/1721
