### ISSUE TITLE
Invisible-bullet lists showing bullets

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1729]
# Scenario
Markup: ```<list id="fs-idp137115008" list-type="bulleted" bullet-style="none">```
Showing bullets

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)
<img width="532" alt="Screen Shot 2019-12-20 at 11 15 08 AM" src="https://user-images.githubusercontent.com/1895432/71277550-de110280-231a-11ea-8800-9f7c3864b87d.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by ajluk** [comment]
Changes in TDS:
New Component needs to be added in BasicTableShape under the TableDataList (l.194):
TableDataUnstyledList
properties:
list-style-type: none,

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-12 17-03-50](https://user-images.githubusercontent.com/47241114/74353063-ae7df400-4db9-11ea-83f9-bc0578ccb29f.png)
