### ISSUE TITLE
Biology 2e, Concepts of Biology, Anatomy & Physiology baked pdfs missing answer key

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1730]
# Scenario
The current pdfs have answer keys and the baked pdfs should too.
We suppressed it for recipe work but it is time to unsuppress.
# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-13 09-53-34](https://user-images.githubusercontent.com/47241114/74417287-bf287b80-4e46-11ea-813c-7f0575ca0837.png)
![Screenshot from 2020-02-13 10-10-49](https://user-images.githubusercontent.com/47241114/74418757-2e06d400-4e49-11ea-9476-1a51ccd8de6a.png)
 In Anatomy didn't work.
![Screenshot from 2020-02-13 10-17-47](https://user-images.githubusercontent.com/47241114/74419826-c3569800-4e4a-11ea-9a43-58f1f9d8cbe8.png)

**Comment by openstaxalina** [comment]
I'm sorry, I missed this card coming through.  We purposely suppressed the Answer Keys in the recipes because we could not achieve the same set of answers in the old PDFs and the recipes.  

@ajluk could you please **undo this change** and close this card?  I apologize again for missing this.  cc @MartaSztuka

**Comment by MartaSztuka** [comment]
Answer Key is no more.
![Screenshot from 2020-02-25 11-55-22](https://user-images.githubusercontent.com/47241114/75241097-c4ca7d80-57c5-11ea-9d1f-536b40904bea.png)
![Screenshot from 2020-02-25 12-05-25](https://user-images.githubusercontent.com/47241114/75241833-27704900-57c7-11ea-8ab7-24a087b07ebd.png)
![Screenshot from 2020-02-25 12-17-36](https://user-images.githubusercontent.com/47241114/75242691-e0835300-57c8-11ea-8e79-228384fb5919.png)
