### ISSUE TITLE
University Physics vol1: Styling Problem Solving Strategy Note

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1731]
Problem Solving Strategy Note should by styled according to Carnival Theme Specs Related issues: https://github.com/openstax/cnx-recipes/issues/1479, #1487

**Comment by ajluk** [comment]
Now it looks like this (the additional title in the subtitle needs to be removed from the content as it was done in Phet note inCollege Physics -issue: https://github.com/openstax/cnx-recipes/issues/1700):
![image](https://user-images.githubusercontent.com/55203598/75242858-293b0c00-57c9-11ea-9bce-0a2c04d82f7a.png)

**Comment by MartaSztuka** [comment]
tested![Screenshot from 2020-02-27 14-18-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ab2ea4f8-ed80-4c81-9879-14f8a946d60d)
