### ISSUE TITLE
Style Link to Learning Note (Interactive) in University Physics vol1

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1733]
Link to Learning (Interactive) Note in University Physics vol1 should be styled according to Carnival Theme Specs. Related issue: #1479

**Comment by MartaSztuka** [comment]
Styled.
![Screenshot from 2020-01-09 13-43-38](https://user-images.githubusercontent.com/47241114/72068937-636a5000-32e6-11ea-8956-792215757b0b.png)
