### ISSUE TITLE
Style check your understanding note in University Physics vol1

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1735]
Check your understanding note in University Physics vol1 should be styled according to Carnival Specs. Related issues: https://github.com/openstax/cnx-recipes/issues/1479, https://github.com/openstax/cnx-recipes/issues/1083
Change in TDS:
New component added to the Icon Condensed Note Shape:
$IconCondensedNoteNumberComponent: (
  _name: "NoteNumber",
  _subselector: ' > .os-number',
  _properties: (
    margin-left: enum('ValueSet:::OPTIONAL'),
  )
);
Margin-left has been set in the u-physics.book.scss file as a University Physics book specific setting for Check Your Understanding Note:
NoteNumber:::margin-left':h-grid(3).

**Comment by MartaSztuka** [comment]
Styled
![Screenshot from 2020-01-16 10-54-34](https://user-images.githubusercontent.com/47241114/72514322-bf852500-384e-11ea-8f73-d9acc4b9514f.png)
