### ISSUE TITLE
University Physics vol1: Introduction page 

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1737]
Introduction page  in University Physics vol1 should by styled according to Carnival Specs. Related issues: #1076, #1075

**Comment by MartaSztuka** [comment]
Styled.
![Screenshot from 2020-01-09 13-37-03](https://user-images.githubusercontent.com/47241114/72068408-4719e380-32e5-11ea-84d0-8b68c581fd9b.png)
