### ISSUE TITLE
cardboard theme: table of contents styling (without units)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1740]
# SCREENSHOTS FOR ASTRONOMY
<img width="908" alt="Screen Shot 2020-01-03 at 1 11 19 PM" src="https://user-images.githubusercontent.com/11299125/71743595-8d290000-2e2a-11ea-9162-91bfcb59f02c.png">
<img width="734" alt="Screen Shot 2020-01-03 at 1 11 44 PM" src="https://user-images.githubusercontent.com/11299125/71743625-9c0fb280-2e2a-11ea-99f5-401c19468c23.png">

# SCREENSHOTS FOR OTHERS** 
![Screen Shot 2020-01-08 at 4 55 49 PM](https://user-images.githubusercontent.com/11299125/72023178-bf29d000-3237-11ea-98ab-b0995f54b498.png)
![Screen Shot 2020-01-08 at 4 56 08 PM](https://user-images.githubusercontent.com/11299125/72023192-c94bce80-3237-11ea-8d27-f56f5b1f1e15.png)

### TOC Title Word ("Table of Contents")
font-size: font-scale(2): 12.96pt, 16.8px, 1.4rem
color: book specific (P1: `#3B2746` for Astronomy, B2: `#344456` for all others)
styling: all caps
font family: book specific (Dosis for Astronomy, Roboto Condensed for all other - these are google fonts you can find on google)

TocTitle Icon: book specific (cardboard-toc1.svg for Astronomy, cardboard-toc2.svg for all others)

### ToCChapterNumber - Same for Appendix
font-family: Noto Sans,
font-weight: bold,
font-size: font-scale(0),
line-height: line-height(0),
color: book specific (P2: `#772949` for Astronomy, B4: `#24739E` for all others)

TocChapterNumberOutline (this is for the box that goes around the number
box line weight: 0.0625 rem (0.75px)
padding: 0.416 rem (5px?) 
color: book specific (Astronomy: Y1: `#E3A354`; others: B3: `#0DC0DC`)

### ToCPrefaceLink - same for Index, Answer Key, EOB material
font-family: Noto Sans,
font-weight: bold,
font-size: font-scale(1),
line-height: line-height(1),
color: book specific (P2: `#772949` for Astronomy, B4: `#24739E` for all others)

### Modules
Line next to chapter contents
width: 0.25rem (3px)
color: G2 `#F4F4F4`
padding between line and module: 0.5rem

Module title, number, Introduction, EOC, page number
font-family: noto sans
font-size: font-scale(0)
color: #000000

page numbers are the same; padding is v-grid(2) between module and page number

### Alternating background color
colors: `#FFFFFF` and Grey1: `#F9F9F9` 
padding top and bottom: v-grid(3)

**Comment by ajluk** [comment]
Hi @andymuddimer! After updating the fonts from your comment from this issue: https://github.com/openstax/cnx-recipes/issues/2684#issuecomment-700273170 The ToC styling doesn't match the screenshots provided by Larissa. This how it looks now: 
![image](https://user-images.githubusercontent.com/55203598/94572853-c5525780-0271-11eb-96f6-71e645502e63.png)
Previously I have used default links from google site and set the same default font variants: 
        titleFont: ('Roboto Condensed', sans-serif, StixGeneral),
        baseFont: ('Noto Sans', sans-serif, StixGeneral),
        mathFont: (StixGeneral),
        baseFontSize: 11px,
        baseLineHeight: 1.4rem,
So, the main ToC title used titleFont `Roboto Condensed', sans-serif` and rest of the ToC chapter and module titles used baseFont: `Noto Sans', sans-serif`. 
It looked like this then: 
![image](https://user-images.githubusercontent.com/55203598/94573581-8670d180-0272-11eb-8658-f9bb243efbc2.png)

After the update the main title is using `Roboto Condensed` (without sans-serif) and the rest of the titles use `Noto Sans` (without sans-serif as well):
        sansFont: ('Noto Sans', sans-serif, StixGeneral),
        titleFont: ('Roboto Condensed', StixGeneral),
        titleFontAstronomy: ('Dosis', StixGeneral),
        baseFont: ('Noto Sans', StixGeneral),
        eobTitleFont: ("IBM Plex Sans", sans-serif, StixGeneral),
        mathFont: (StixGeneral),
        baseFontSize: 12px,
        baseLineHeight: 1.5rem,

Do you thin I should change the `titleFont` to `'Roboto Condensed', sans-serif` and `baseFont` to `'Noto Sans', sans-serif'`
back (in the case of modules and chapter titles I can use the sansFont, which currently is set to Noto Sans, sans-serif)?

**Comment by andymuddimer** [comment]
Yes - sorry I did not know Larissa had already given you font styles. The Sans Serif version looks much better.

**Comment by ajluk** [comment]
Oh, it's ok. Thank you for looking up to it! So in that case I will change the the titleFont to sans-serif, do you think I should change the baseFont to sansSerif as well and remove the sansFont from the fonts? Or just use the sansFont in ToC and keep the baseFont without sans-serif?

**Comment by andymuddimer** [comment]
I think you can keep the fonts Larissa has in the spec above for the Table of Contents. Sorry I confused the situation.

**Comment by ajluk** [comment]
No, actually it's my fault (the confusion) because the fonts from the spec above are the fonts you have posted. :sweat_smile: I just added sans-serif by my self earlier because it was a default set in google fonts site. If that is the case should I keep the serifs in both baseFont and titleFont?

**Comment by lwtchu** [comment]
@ajluk that's okay i think we can keep what the recipe generates.

**Comment by brittweinstein** [comment]
@ajluk please see Larissa's note above.

**Comment by kswanson33** [comment]
Hey @lwtchu! For Astronomy, I want to clarify if the color of the chapter links should all be P1, like the chapter number and the appendix/preface (shown below), or if it should resemble the screenshot above, with purple chapter numbers but blue chapter title links?

![image](https://user-images.githubusercontent.com/26280712/101921066-8e19f400-3b9a-11eb-9f1c-3725f18eb509.png)

**Comment by lwtchu** [comment]
@kswanson33 oh yes - sorry i retired that blue since it was too close to the other blues but also..not close enough :joy: sorry for the confusion.
