### ISSUE TITLE
Chapter outline not formatted

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1743]
# Scenario
Concepts of Biology has a bad chapter outline format

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)
<img width="584" alt="Screen Shot 2020-01-06 at 2 41 22 PM" src="https://user-images.githubusercontent.com/1895432/71847530-b3e96f80-3092-11ea-8dc1-447b8efcb5b9.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by lwtchu** [comment]
![Screen Shot 2020-02-04 at 2 10 07 PM](https://user-images.githubusercontent.com/11299125/73782646-10a27d80-4758-11ea-9590-c4025a171d86.png)
Biology vs Concepts of Biology PDF

Concepts should function the same. They're not hard coded in the content and is automatically generated.

**Comment by wilkus27** [comment]
Checked with the newest content and newest code changes and it's working properly :thinking: 

![image](https://user-images.githubusercontent.com/40228854/75155722-e87fbc00-5710-11ea-8380-d6a283584e08.png)
