### ISSUE TITLE
University Physics: style EoC sections

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1747]
EoC sections need to be styled according to Carnival Theme Specs. Related issues: #1486, #1479.

**Comment by brittweinstein** [comment]
@ajluk I'm going to move this to the backlog since Phys isn't high prio rn

**Comment by ajluk** [comment]
Changes in TDS: 
New exercises needs to be added under the EocCompChapExercises (the all using it):

**ChallengeProblems**

          Container
          //empty properties

          CompChapPageHeader:(
             font-family: ("IBM Plex Sans", sans-serif),
             column-span: all,
             // color: book specific, defined in book.scss file
             font-weight: bold,
             font-size: font-scale(3),
             line-height: line-height(3),
             text-transform: uppercase,
            margin-bottom: v-grid(1)
        
        EocSectionTitleLink:
            font-family: Muli
            font-size: font-scale(3),

        ProblemWrapper
          display: table,
       
       ProblemContainer
           display: table-cell,

       ProblemParagraph
          margin-bottom: 0,

        ProblemNumber: 
             color: black,
            font-weight: bold,
            text-decoration: none
            display: table-cell,
        
        ProblemDivider: (
            margin-right: h-grid(1),
        
        ExerciseOrderedList: 
            margin-left: h-grid(4),
            margin-bottom: v-grid(1),
        
        ExerciseFigure: 
            max-width: 100%,
        
**ProblemsCompChapPageWithTwoColumns**

        Container:
            column-count: 2,
            column-gap: 2.4rem,
            column-width: auto,
        
        CompChapPageHeader
             font-family: ("IBM Plex Sans", sans-serif),
             column-span: all,
             // color: book specific, defined in book.scss file
             font-weight: bold,
             font-size: font-scale(3),
             line-height: line-height(3),
             text-transform: uppercase,
            margin-bottom: v-grid(1)
        
        EocSectionTitleLink:(
              font-family: Muli
            font-size: font-scale(3),

        ProblemWrapper
          display: table,

        ProblemContainer
        display: table-cell,

          ProblemParagraph
          margin-bottom: 0,

          ProblemNumber: 
              color: black,
            font-weight: bold,
            text-decoration: none
            display: table-cell,

        ProblemDivider:
            margin-right: h-grid(1)

        ExerciseOrderedList:
            margin-left: h-grid(4),
            margin-bottom: v-grid(1),

        ExerciseNestedOrderedList: 
            margin-left: h-grid(2),
            margin-bottom: v-grid(1),

        ExerciseFigure: 
            max-width: 100%,

**ConceptualQuestionsCompChapPage**

          Container:
            column-count: 2,
            column-gap: 2.4rem,
            column-width: auto,
  
        CompChapPageHeader:
            font-family: ("IBM Plex Sans", sans-serif),
            column-span: all,
             // color: book specific, defined in book.scss file

        EocSectionTitleLink:
              font-family: Muli
              font-size: font-scale(3),

        ProblemWrapper
          display: table,
         
       ProblemContainer
        display: table-cell,

        ProblemParagraph
          margin-bottom: 0,

        ProblemNumber: 
            color: black,
            font-weight: bold,
            text-decoration: none
            display: table-cell,

        ProblemDivider:
            margin-right: h-grid(1)

        ExerciseOrderedList:
            margin-left: h-grid(4),
            margin-bottom: v-grid(1),

        ExerciseNestedOrderedList: 
            margin-left: h-grid(2),
            margin-bottom: v-grid(1),

        ExerciseFigure: 
            max-width: 100%,

**AdditionalProblems**

         Container
          //empty properties

      CompChapPageHeader:
            font-family: ("IBM Plex Sans", sans-serif),
            column-span: all,
             // color: book specific, defined in book.scss file
        
        EocSectionTitleLink:
             font-family: Muli
             font-size: font-scale(3),
            
       ProblemWrapper
          display: table,

      ProblemContainer
        display: table-cell,

      ProblemParagraph
          margin-bottom: 0,

        ProblemNumber: 
             color: black,
            font-weight: bold,
            text-decoration: none
            display: table-cell,
        
        ProblemDivider: (
            margin-right: h-grid(1),
        
        ExerciseOrderedList: 
            margin-left: h-grid(4),
            margin-bottom: v-grid(1),
        
        ExerciseFigure: 
            max-width: 100%,

Book specific color for University Physics need to be added to these components in the listed shapes and exercises:
**KeyTerm**:
    CompChapPageHeader
       color': B5
**SummaryWithSectionLinks**
    CompChapPageHeader
       color': B5
**KeyEquation**:
      CompChapPageHeader
         color': B5
**ChapterReviewCompositeChapter**
     EocHeader
     color': B5
**ConceptualQuestionsCompChapPage**:
      CompChapPageHeader
      color': B5
**ProblemsCompChapPageWithTwoColumns**:(
    CompChapPageHeader
      color': B5
**AdditionalProblems**:
    'CompChapPageHeader
        color': B5
**ChallengeProblems**
   CompChapPageHeader
     color': B5

Three new components needs to be added for **SummaryWithSectionLinks** shape:
**SummarySectionUnorderedList**
        margin-left: h-grid(3),
**UnorderedNestedList**
       margin-left: h-grid(2),
**CompChapPageHeader**
        color: //book specific
        font-family: ("IBM Plex Sans", sans-serif),
        font-weight: bold,
        font-size: font-scale(3),
        line-height: line-height(3),
        text-transform: uppercase,
        column-span: enum('ValueSet:::OPTIONAL'),
        margin-bottom: v-grid(1)

**CompChapPageHeader** component with properties
        color: //book specific
        font-family: ("IBM Plex Sans", sans-serif),
        font-weight: bold,
        font-size: font-scale(3),
        line-height: line-height(3),
        text-transform: uppercase,
        column-span: enum('ValueSet:::OPTIONAL'),
        margin-bottom: v-grid(1)
 need to be added to these shapes as well:
**EocKeyTerm**
**EocKeyEqu**

**Comment by lwtchu** [comment]
@ajluk i wasn't sure where to update the following... I'm not sure if there was a shape created for those?

Three new components needs to be added for SummaryWithSectionLinks shape:
SummarySectionUnorderedList
margin-left: h-grid(3),
UnorderedNestedList
margin-left: h-grid(2),
CompChapPageHeader
color: //book specific
font-family: ("IBM Plex Sans", sans-serif),
font-weight: bold,
font-size: font-scale(3),
line-height: line-height(3),
text-transform: uppercase,
column-span: enum('ValueSet:::OPTIONAL'),
margin-bottom: v-grid(1)

CompChapPageHeader component with properties
color: //book specific
font-family: ("IBM Plex Sans", sans-serif),
font-weight: bold,
font-size: font-scale(3),
line-height: line-height(3),
text-transform: uppercase,
column-span: enum('ValueSet:::OPTIONAL'),
margin-bottom: v-grid(1)
need to be added to these shapes as well:
EocKeyTerm
EocKeyEqu

**Comment by ajluk** [comment]
@lwtchu Oh. Yes, it seems it has been missed somehow. I didn't check, because I was sure it will be there :)
So in that case the whole shape need to be added to the TDS (under l.635):
**SummaryWithSectionLinks** shape
with Components:
**Container**
            margin-bottom: v-grid(2),
**EocHeader**
            font-family: (_ref: 'typography:::sansFont'),
            font-weight: bold,
            font-size: font-scale(4),
            line-height: line-height(4),
            text-transform: uppercase,
             // color: book specific, defined in book.scss file
**CompChapPageHeader**
            font-family: (_ref: 'typography:::sansFont'),
             // color: book specific, defined in book.scss file
**EocSectionTitleLink**
           font-family: (_ref:'typography:::titleFont'),
           font-size: font-scale(3),
**SummaryUnorderedList**
           margin-left: h-grid(3),
**SummarySectionUnorderedList**
            margin-left: h-grid(3),
**SummaryNestedUnorderedList**
            margin-left: h-grid(2),

**CompChapPageHeader** component with properties need to be added to these shapes:  **KeyTerm** (under l. 588)
**KeyEqu** (l. 600)
color: //book specific
font-family: ("IBM Plex Sans", sans-serif),
font-weight: bold,
font-size: font-scale(3),
line-height: line-height(3),
text-transform: uppercase,
column-span: enum('ValueSet:::OPTIONAL'),
margin-bottom: v-grid(1)

**Comment by lwtchu** [comment]
@ajluk thanks :)

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-03-05 12-31-27](https://user-images.githubusercontent.com/47241114/75977745-5bd9b880-5edd-11ea-8c29-8da09b67cdd1.png)
![Screenshot from 2020-03-05 12-35-33](https://user-images.githubusercontent.com/47241114/75978146-300b0280-5ede-11ea-9684-5c0867e67241.png)
![Screenshot from 2020-03-05 12-37-53](https://user-images.githubusercontent.com/47241114/75978148-31d4c600-5ede-11ea-8e05-fdfa0fdd3405.png)
