### ISSUE TITLE
corn theme: splash images

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1752]
<img width="714" alt="Screen Shot 2020-04-02 at 2 12 40 PM" src="https://user-images.githubusercontent.com/11299125/78292053-0d273a80-74ec-11ea-8f3d-ee1354effc5e.png">
<img width="723" alt="Screen Shot 2020-04-02 at 2 12 24 PM" src="https://user-images.githubusercontent.com/11299125/78292056-10bac180-74ec-11ea-86e8-2461ff0be73a.png">

### Splash Figure
All splash images in this theme are 6.81in x 2.523in. The image has a 0.15in  bleed on right side of the page page. 
#### Splash image overlay
color: B1L `#093D4C`
opacity: 50%

### Top of the page bar
color: B1:   `#093D4C`
height: 0.8 in (fills in top margin) 
width: 8.5 in wide PLUS 0.125 bleeds on both sides and at the top

### Left box
color: G2:   `#C6CE33`
width: 1.814in + 0.15 bleed on the left
height: matches splash image height

### Chapter number
font-family: Roboto Slab
font-weight: bold
font-size: font-size: font-scale(3): 14.25pt, 19.01px, 1.7rem
color: white `#FFFFFF`

### White box around number
height: 2.75rem
width: 2.75 rem
color: `#FFFFFF`

### Chapter title
font-family: Roboto Slab
font-weight: bold
font style: all caps
font-size: font-scale(2): 11.88pt, 15.84px, 1.4rem
color: white `#FFFFFF`

**Comment by ajluk** [comment]
@lwtchu could you provide additional specs for:
 
- splash image opacity,
- should image caption, folio and box with a chapter number are not in one line?:  
![image](https://user-images.githubusercontent.com/55203598/82436692-85df5780-9a96-11ea-9840-45cc290baeeb.png)
And I have a question: Folio can be done on separate issue?

**Comment by lwtchu** [comment]
- we are not doing to go with the opacity or blue overlay for right now
- let's have them be in line and starting 1in from the left margin
- can the spacing in the number box be about .5 rem left/right and .25 rem top/bottom 
- Can the whole number sit 1.5 rem from the edge of the yellow box?  - or does it have to be in relation to the chapter number.

let me know if this works.

**Comment by ajluk** [comment]
@larissa I have finished working on styling Chapter Intro and been able to change the folio font color as it was on the screenshot. Let me know if it should be different color (I remember you mentioned white somewhere?): 
![image](https://user-images.githubusercontent.com/55203598/83403295-b0bb9b00-a408-11ea-91a6-d5107afeefa1.png)

**Comment by larissa** [comment]
I think you meant to tag a different Larissa there, @ajluk

**Comment by lwtchu** [comment]
@ajluk here's the card for the folio specs: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2143

i think you have the same issue that Natalia had earlier - the fonts aren't showing up on your pdf. 

sigh in order to work with the white bg images, added the overlay specs to the splash image in the original comment. it's B1 `#093D4C` at50% and should just go over the splash image. is that something we can implement?

**Comment by ajluk** [comment]
@lwtchu Thank you! I will update my PR and the fonts should work after that. Natalia has fixed it already. I will try to implement the image overlay as well. But what about the images size can it be the same size in the content? Can I leave the positioning I have made for now? I can try to set the size in the code as well and see how it cooperate with the splash bg. 

>

**Comment by lwtchu** [comment]
yes i think the positioning is fine right now - i want to double check again when the correct fonts are generated :)

**Comment by ajluk** [comment]
@lwtchu I have updated my PR. Now the fonts are generated correctly. This is how it looks in pdf file now: 
![image](https://user-images.githubusercontent.com/55203598/83547531-ac73a880-a502-11ea-850b-13951987ef2c.png)

**Comment by lwtchu** [comment]
@ajluk nice! is the tint overlay on it? i can't really tell with that picture. also the box around the number is supposed to be a square - is there a different way you are setting it ? like a border with padding?

**Comment by ajluk** [comment]
@lwtchu Thank you and for that you have noticed that the box around chapter number is tighter I have used a shorthand property and it doesn't seem to work. I have already fixed it. This is how it looks now with overlay: 
![image](https://user-images.githubusercontent.com/55203598/83641680-244add00-a5ae-11ea-99e8-8f78edc833e7.png)
I have also added some text shadow to chapter title to be more visible, but I'm not sure if this solution is consistent with the design, because we didn't use it anywhere else. Let me know what do you think about it :). It is more visible on this screenshot : 
![image](https://user-images.githubusercontent.com/55203598/83642069-a4714280-a5ae-11ea-94a2-08fa7f6ce179.png)
There is one more thing. I'm not sure about the bleeds I have set. Can I send you the pdf, so you could check it out?

**Comment by lwtchu** [comment]
@ajluk would it be better to set the bleeds in the book as a separate issue? i remember during carnival as a separate issue - or would you like to just do it with this card? 

but feel free to send me the pdf - i can take a look at all the shadow behind the text too to make sure it doesn't look too weird ins some cases

thanks!

**Comment by ajluk** [comment]
@lwtchu Thank you!  I have already set the bleeds, because they are parts of the Chapter Intro  Shape (functions uses them) I needed to set them before I have set width of the splash image and the background. I would like to sent you the pdf, because I'm not sure if I have done it correctly in the top margin bar in Chpter Intro espacially.

**Comment by lwtchu** [comment]
The top bar is missing top and sides. 
![Screen Shot 2020-06-04 at 8.46.55 AM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/6deb6f51-9be0-4f67-890f-cbef1fbb9d94)

It looks good on the yellow and splash/overlay pieces though:
![Screen Shot 2020-06-04 at 8.47.12 AM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/88b1dcc7-23c2-4043-9c68-a4dfed30f69a)

I'm not sure if you have adobe acrobat, but there's a way to check if you "edit" the pdf and select the color pieces. It should show you where the image/color block ends

**Comment by ajluk** [comment]
Thank you Larissa! I was afraid there will be a problem with the top bar what's why I asked you to check. I will try different approach there. We don't have Adobe Acrobat, only the Reader version, where the is no possibility to edit files.

**Comment by ajluk** [comment]
@lwtchu I have sent you the pdf with fixed top bar bleeds via direct message. Could you check and let know if the bleeds are there now and I can add the specs I added here?

**Comment by ajluk** [comment]
I have also added a fix to make the chapter numbers boxes more square: 
![image](https://user-images.githubusercontent.com/55203598/83898123-c4436a80-a756-11ea-8f0a-e50278b1820c.png)
Is it better this way?

**Comment by lwtchu** [comment]
the box looks good - the bleeds however still aren't showing up

**Comment by ajluk** [comment]
@lwtchu I have sent you pdf file with fix, let me know if it looks better now?

**Comment by lwtchu** [comment]
updated specs to include top bleed :grimace:

**Comment by ajluk** [comment]
Added specs:
**IntroductionContainer (IntroductionPage)**
position: relative,
top: -6rem,

**SplashImgMedia**
 line-height: 0,
 height: 100%,
display: flex,
width: 7.625in;
justify-content: flex-end;

**SplashImg**
width: 6.935in;
position: relative,

SplashMediaOverlay
content: "''",
background-color: #093D4C;
opacity: 0.5,
position: absolute,
width: 6.935in;  //same as the splash img width
height: 100%,
top: 0,
left: 6rem,
z-index: 1,
box-sizing: border-box,

**SplashFigure**
position: relative,
margin: 0,

**SplashFigureBg**
 width: 8.625in;
margin-left: -1.125in;
 content: "''",
background-color: #C6CE33;
position: absolute,
height: 100%,
width: enum('ValueSet:::REQUIRED'),
margin-left: enum('ValueSet:::REQUIRED'),
z-index: -1,
box-sizing: border-box,
padding: inherit,
top: 0,

**SplashFigureWrapper**
margin-bottom: 2rem,

**Top Bar** is styled within folio, the specs can be found there: https://github.com/openstax/cnx-recipes/issues/2143

**Comment by lwtchu** [comment]
Updating to set the splash overlay opacity to 0.3
