### ISSUE TITLE
University Physics vol 1: Examples and Deafult Notes

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1753]
Examples and Deafult Notes should be styled according to Carnival Specs. Related issue: https://github.com/openstax/cnx-recipes/issues/1079

Changes in TDS are book specific for University Physics (set in u-physics/book.scss file):

In the note DefaultNoClassNote:
    Component Container:
        group-border-color:  physicsDefaultNoteColor: (_ref: "scheme:::B5"),
    Component Title
        font-family': "Muli",
        color':  physicsDefaultNoteColor: (_ref: "scheme:::B5"),
        border-bottom-color:  physicsDefaultNoteColor: (_ref: "scheme:::B5"),

In the Example Note:
    Component Container
       border-bottom-color: exampleColor: (_ref: "scheme:::R3"),
    Component Title
       font-family': "Muli",
       color': exampleColor: (_ref: "scheme:::R3"),
       border-bottom-color: 
    Component TitleIcon
       background': url("../../styles/designs/carnival/resources/carnival-example.svg") no-repeat         top   left,
    Component ParagraphSubtitle
      font-family': ("IBM Plex Sans", sans-serif),
      font-size': font-scale(1),
      line-height': line-height(1),
      font-weight': bold,
      text-transform': uppercase,
      display': inline-block,
      padding-right': h-grid(1),
    Component FirstTitle
      font-family':("IBM Plex Sans", sans-serif),
      font-size': font-scale(1),
      line-height': line-height(1),
      font-weight': bold,
      display': block,
      margin-bottom': .2rem,
      text-transform': capitalize,

**Comment by lwtchu** [comment]
@ajluk specs updated thank you~

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-01-16 11-08-10](https://user-images.githubusercontent.com/47241114/72517101-14c33580-3853-11ea-80cf-be3a72eae952.png)
![Screenshot from 2020-01-16 11-00-02](https://user-images.githubusercontent.com/47241114/72517103-14c33580-3853-11ea-8dc8-484a29827a46.png)
