### ISSUE TITLE
University Physics vol1: style eob appendix answer key 

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1755]
Appendix and Answer key in University Physics should be styled according to Carnival Specs.

Changes in Theme Design Specs:

New component to add in the Answer Key shapes:
name: Image
properties:
display: block,
margin: v-grid(1) h-grid(1),

Book specific colors added to these components:

 in the AnswerKey shape:   
    name: Title
      color': physicsHeaderColor: (_ref: "scheme:::B5"),
    name: ExerciseTitle
      color': physicsHeaderColor: (_ref: "scheme:::B5"),

  in the Appendix shape: 
    name: SubTitle
      color':physicsHeaderColor: (_ref: "scheme:::B5"),
    SubSubTitle
      color': physicsHeaderColor: (_ref: "scheme:::B5"),

**Comment by lwtchu** [comment]
@ajluk added these

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-01-16 13-52-37](https://user-images.githubusercontent.com/47241114/72526880-b18fce00-3867-11ea-8835-b6c57282e6b5.png)
![Screenshot from 2020-01-16 13-52-21](https://user-images.githubusercontent.com/47241114/72526881-b2286480-3867-11ea-92df-3a269e1ba8a5.png)
