### ISSUE TITLE
Example title display

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1757]
Example notes titles looks like this when line is longer.
![Screenshot from 2020-01-13 15-51-56](https://user-images.githubusercontent.com/47241114/72265550-f96ee500-361c-11ea-96d2-a72cb5dbcfe4.png)
![Screenshot from 2020-01-13 15-51-48](https://user-images.githubusercontent.com/47241114/72265551-f96ee500-361c-11ea-8ec3-dd6a9608b7e4.png)
![Screenshot from 2020-01-13 15-51-34](https://user-images.githubusercontent.com/47241114/72265553-fa077b80-361c-11ea-8f18-e7f42f545602.png)

**Comment by helenemccarron** [comment]
Current mark up 
![2020-01-16_13-51-09](https://user-images.githubusercontent.com/8514591/72558795-05e77d80-3869-11ea-85b3-937e98ed8e42.png)

**Comment by lwtchu** [comment]
<img width="726" alt="Screen Shot 2020-01-17 at 11 18 16 AM" src="https://user-images.githubusercontent.com/11299125/72632153-4b648300-391b-11ea-8e0c-bb71df5ece08.png">
Is it possible to do something like this? Where we move it under the line, make it bold and match the base font?

**Comment by helenemccarron** [comment]
![2020-01-27_11-32-44](https://user-images.githubusercontent.com/8514591/73198974-a22b4300-40f9-11ea-8fae-b0e69b8c8fd3.png)
recipe change applied to an example, the example title is now below the example number and icon. Please note this applies only to physics, we need to enable it for all books that require it.

**Comment by lwtchu** [comment]
@helenemccarron this might need to be activated for college physics and AP college physics for now? they're both v closely related

**Comment by helenemccarron** [comment]
SInce those will be going through 100% regression testing soon, I enabled the flag for the following books:
    - College Physics, 
       -  AP Physics
        - Biology
       -  AP Biology

**Comment by MartaSztuka** [comment]
Still occurs![Screenshot from 2020-02-04 17-28-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1d8c92a3-704b-46f2-9265-f2ead46aed43)

**Comment by helenemccarron** [comment]
@MartaSztuka I had not merged the PR yet (was not expecting you to test today, sorry for the confusion), the code is now on dithering.dido

**Comment by helenemccarron** [comment]
@MartaSztuka also please note that is a recipe change, so you will have to bake the collection for this to work.

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-02-06 14-38-23](https://user-images.githubusercontent.com/47241114/73941923-67da5680-48ee-11ea-8405-929fe4192539.png)
