### ISSUE TITLE
hs physics: Check Your Understanding 

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1758]
Exercises in Check Your Understanding should be labeled just by the numbers

![image](https://user-images.githubusercontent.com/40228854/72268551-4d2ffd00-3622-11ea-9506-4b9a36525a3f.png)

https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:V0xq7_l-@2/1-1-Physics-Definitions-and-Applications

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/qRkBHZVu@4.2:4_xuWm-C@4/14-3-Doppler-Effect-and-Sonic-Booms
![Screenshot from 2020-01-17 17-23-49](https://user-images.githubusercontent.com/47241114/72628232-2d644600-394e-11ea-87ab-dce22f7be64e.png)
