### ISSUE TITLE
hs physics: missing solutions

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1760]
Solutions from section elements like **Worked Example** or **Check Your Understanding** are hidden. They should be visible.

PDF:
![image](https://user-images.githubusercontent.com/40228854/72340601-cda93900-36c8-11ea-9c3b-5f919d5065ef.png)

Webview:
https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:zzcryciP@3/1-3-The-Language-of-Physics-Physical-Quantities-and-Units
![image](https://user-images.githubusercontent.com/40228854/72340667-de59af00-36c8-11ea-8184-304f62c0e17b.png)

PDF:
![image](https://user-images.githubusercontent.com/40228854/72341021-8ff8e000-36c9-11ea-911b-61e3edae05bb.png)

Webview:
https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:V0xq7_l-@2/1-1-Physics-Definitions-and-Applications
![image](https://user-images.githubusercontent.com/40228854/72341039-9be4a200-36c9-11ea-83c2-597a944922e6.png)

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/qRkBHZVu@4.2:V0xq7_l-@2/1-1-Physics-Definitions-and-Applications
![Screenshot from 2020-01-16 14-20-33](https://user-images.githubusercontent.com/47241114/72528504-74c5d600-386b-11ea-88ec-39bf30cb2829.png)
![Screenshot from 2020-01-16 14-05-23](https://user-images.githubusercontent.com/47241114/72528508-755e6c80-386b-11ea-806e-8f8c199c6f5f.png)
