### ISSUE TITLE
hs physics: wrong display of numbered equations

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1762]
In HS Physics numbers of numbered equations are displayed in this way:

![image](https://user-images.githubusercontent.com/40228854/72345051-09490080-36d3-11ea-9445-c46206d680ff.png)
https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:zzcryciP@3/1-3-The-Language-of-Physics-Physical-Quantities-and-Units

They should be on the right side in border like here: https://katalyst01.cnx.org/contents/Ax2o07Ul@17.22:EC6WBNqn@13/1-2-Physical-Quantities-and-Units

![image](https://user-images.githubusercontent.com/40228854/72345141-3d242600-36d3-11ea-971a-2d0dfd14ba6e.png)

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/qRkBHZVu@4.2:zzcryciP@3/1-3-The-Language-of-Physics-Physical-Quantities-and-Units
![Screenshot from 2020-01-16 14-01-24](https://user-images.githubusercontent.com/47241114/72527311-bf921e80-3868-11ea-8e99-f75fdb963cea.png)
