### ISSUE TITLE
hs physics: bad hrefs

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1763]
In locally baking process appear errors with bad hrefs.

Screen from terminal:
![image](https://user-images.githubusercontent.com/40228854/72346285-f126b080-36d5-11ea-94d2-4a4b1afc919e.png)

Here the same hrefs to copy. It could be helpful in investigation.
```
#auto_m80211_Figure_05_01_displace
#CNX_HSPhysics_12_02_InternalEn_img
#CNX_HSPhysics_16_01_Maze
#CNX_HSPhysics_16_01_Maze
#Icon
#auto_m80267_Figure_18_01_Conservati
```

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #1376](https://github.com/openstax/content-managers/issues/1376) via [**ZenHub**](https://www.zenhub.com/)
