### ISSUE TITLE
hs physics: double titles

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1765]
Some of the elements have double titles:

https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:2-9H6qJM@2/1-2-The-Scientific-Methods
![image](https://user-images.githubusercontent.com/40228854/72353495-74e79980-36e4-11ea-935a-233ab398e887.png)

**Comment by wilkus27** [comment]
Titles marked by red are created by recipes and those pointed by arrows - by webview, but in both cases it is related with attribute `data-label`

![image](https://user-images.githubusercontent.com/40228854/72441518-24873f00-37ab-11ea-9202-9947e05648fd.png)

Here is the code from recipes responsible for one change:

![image](https://user-images.githubusercontent.com/40228854/72442046-1128a380-37ac-11ea-9e59-66025c08f1b4.png)

And here from webview:
![image](https://user-images.githubusercontent.com/40228854/72442164-48975000-37ac-11ea-9fe3-5f7ff1d0ab65.png)

In PDF there is no title `Materials`:

![image](https://user-images.githubusercontent.com/40228854/72443256-446c3200-37ae-11ea-8d44-76f63eb63ffe.png)

@openstaxalina Do we want this title? If not I think that attribut `data-label="Materials"` should be removed in the content. 

About **Grasp Check** title. How it should looks like on webview?

Here is how exercise Check Your Understanding looks like in College Physics:

![image](https://user-images.githubusercontent.com/40228854/72443990-8b0e5c00-37af-11ea-803a-798a1152ad59.png)

Do we want something similar? If yes, then maybe markup could be changed a little bit? 
This is markup of Check Your Understanding exercise from assembled.xhtml file:

![image](https://user-images.githubusercontent.com/40228854/72445754-88613600-37b2-11ea-8f04-fb15d1163f5c.png)

As you can see, title is created in content in div with `data-type="title"` attribut. And `data-label` is empty. 

@openstaxalina @helenemccarron please let me know what do you think about it? @helenemccarron do you think it's better in those cases to change content or to try fix this by webview/recipe?

**Comment by helenemccarron** [comment]
I think the data label was needed for webview and tutor, Phil made heavy use of this instead of regular titles as we do in recipes. I think we would benefit in cleaning up the markup to make it consistent with our other titles now that this book doesn't have any special needs anymore. I also think we might need at the styles in Webview to make sure we remove any extra styles we do not need anymore.

**Comment by openstaxalina** [comment]
@helenemccarron I agree on making the markup consistent with other titles.  To confirm: should we convert anything in a `label` to be in a `title` instead?

**Comment by helenemccarron** [comment]
If I understand @wilkus27 correctly, I believe that is correct?

**Comment by wilkus27** [comment]
Yes, that's right! :)

**Comment by openstaxalina** [comment]
Okay, I have created an issue for this here: https://github.com/openstax/content-managers/issues/1375

I am closing this card since there will be no coding work.  @wilkus27 @helenemccarron please reopen if I am mistaken on that.
