### ISSUE TITLE
hs physics: enable all release flags

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1770]
All release flags should be enabled for HS Physics

**Comment by wilkus27** [comment]
This is resolved within PR: https://github.com/openstax/cnx-recipes/pull/1772

**Comment by wilkus27** [comment]
Flags to test:

- [ ] toc-labeled-pages
- [ ] chapter-page-class
- [ ] toc-numbered-pages
- [ ] appendix-has-numbered-examples
- [ ] increment-section-counter-for-lo
- [ ] trash-abstract-in-preface
- [ ] EOCsection-links
- [ ] titles-in-examples
- [ ] module-titled-notes
- [ ] custom-lists
- [ ] groupChapOutlineIntroContent
- [ ] tagSplash
- [ ] toc-title-word
- [ ] use-title-nodes
- [ ] goodbye-warnings
- [ ] toc-eoc-composite-chapter
- [ ] table-move-fake-title
- [ ] several-composite-chapters

**Comment by MartaSztuka** [comment]
tested https://katalyst01.cnx.org/contents/qRkBHZVu@9.2:fvjcE4B-@4/A-Reference-Tables
