### ISSUE TITLE
hs physics: style TOC

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1776]
Table of Content in HS Physics should be styled with specs from Carnival Theme.
Current view:
![image](https://user-images.githubusercontent.com/40228854/72732773-bc639f00-3b96-11ea-93c6-470dac78e82e.png)

**Comment by wilkus27** [comment]
### Changes to Theme Design Specs

Remove all properties for `TocEocCompositeChapter` component, both in NoUnitToc and UnitToc shapes.

**Comment by lwtchu** [comment]
Didn't find TocEocCompositeChapter but i put it should be removed on the spec sheet

**Comment by MartaSztuka** [comment]
styled
![Screenshot from 2020-01-29 10-57-44](https://user-images.githubusercontent.com/47241114/73346499-417d4100-4286-11ea-86f0-89e901baa1f3.png)
