### ISSUE TITLE
hs physics: style Learning Objectives

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1780]
Learning Objectives in HS Physics should be styled with specs from Carnival Theme:
Current view:

![image](https://user-images.githubusercontent.com/40228854/72812841-8db2fa80-3c62-11ea-9f46-66a11086ac18.png)

**Comment by wilkus27** [comment]
Per Larissa, this is how title and first sentence should be styled:

![image](https://user-images.githubusercontent.com/40228854/72999038-0e0e6280-3dff-11ea-8df0-fd3119ef7eae.png)

Title has the same font style and font size as the sentence but it should be bold and not italic

**Comment by wilkus27** [comment]
### Changes for Theme Design Specs

New shape: **LearningObjectiveNoteShape**

_Component:_ **Title**
_Properties:_ 
```
    color: book specific
    font-family: IBM Plex Sans, sans-serif,
    font-size: font-scale(1),
    line-height: line-height(1),
    font-style: normal,
    font-weight: bold,
```

_Component:_ **NoteBody**
_Properties:_  empty

_Component:_ **LearningObjectiveParagraph**
_Properties:_  
```
    color: book specific
    font-family: IBM Plex Sans, sans-serif,
    font-size: font-scale(1),
    line-height: line-height(1),
    font-style: italic,
    margin-bottom: 0,
```

_Component:_ **List**
_Properties:_  
```
    margin-bottom:v-grid(2),
    margin-left: h-grid(2),
    padding-left: 0,
    font-size: font-scale(0),
    line-height: line-height(0),
    font-style: normal,
```

_Component:_ **ListItem**
_Properties:_ 
```
    color: black,
    font-family: Muli, sans-serif;
    padding: 0,
```

_Component:_ **ListDot**
_Properties:_ 
```
    color: book specific,
```


Book specific color for HS Physics is `B5`

**Comment by lwtchu** [comment]
Thanks this was super helpful @wilkus27 <3

**Comment by MartaSztuka** [comment]
![Screenshot from 2020-01-29 10-50-37](https://user-images.githubusercontent.com/47241114/73345906-37a70e00-4285-11ea-872a-bf7615c1ea52.png)
