### ISSUE TITLE
College Success -- Add Index in Webview

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1781]
@clteam18 commented on [Tue Jan 21 2020](https://github.com/openstax/oer.exports/issues/4026)

# Environment:

- **Book(s)**: College Success
- **URL/Server**: PDF 
- **Location (page number, chapter/section)**: Chapter 06/ PDF page 7
- **Suggested nearby searchable text**: one of those cherished but mysterious elements in life

# Screenshots

![image](https://user-images.githubusercontent.com/39794953/72816122-b4d2f180-3c8d-11ea-8f4d-e386e9b0aba2.png)

# Additional notes

We have used following tag(<term class='no-emphasis'>Memory</term>) for Key terms as per "tagging legend". But displaying as normal content in PDF and Web View. Please check and confirm.

---

@openstaxalina commented on [Tue Jan 21 2020](https://github.com/openstax/oer.exports/issues/4026#issuecomment-576734906)

@clteam18 thank you for flagging this.  We do **not** want the term to be bold; this is why we used the class `no-emphasis`.  However, I do not see an Index in webview -- we **do** want there to be an Index and for the term to appear there.  

Note that there is an Index in the PDF:
![Screen Shot 2020-01-21 at 9 28 46 AM](https://user-images.githubusercontent.com/7863733/72818108-81ae4500-3c30-11ea-9410-e2aa37034ec5.png)

I am going to move this issue to cnx-recipes since this likely needs to be fixed there.

**Comment by brittweinstein** [comment]
@omehes please verify this on staging when you can

**Comment by openstaxalina** [comment]
@yblock could you migrate some _College Success_ content to staging.cnx.org (it could be the same stuff on easyvm5 that has index tags), apply the College Success recipe on staging, and be sure you see the Index?

**Comment by yblock** [comment]
Confirmed Index, terms, and no-emphasis terms are all working in web and PDF!

https://staging.cnx.org/contents/2Uz_ZeWp@1.2:2vf12GJk@1.2/Index

**Comment by openstaxalina** [comment]
thank yuo @yblock !  I am closing this
