### ISSUE TITLE
Carnival theme: unit and chapter numbers in ToC

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1782]
<img width="917" alt="Screen Shot 2020-01-17 at 10 41 55 AM" src="https://user-images.githubusercontent.com/11299125/72834829-38212280-3c4f-11ea-8b3a-77efb2307494.png">

Are we able to incorporate Unit Numbers and Chapter Numbers now? I know this is a recipe change that will impact REX. So i'm not sure if we can move on? I'm opening this card for us to not to forget to address.

![Screen Shot 2020-02-26 at 11 27 51 AM](https://user-images.githubusercontent.com/11299125/75370660-11c45780-588b-11ea-9f6d-e660d7291fc4.png)
Let's also do this for Appendices

**Comment by brittweinstein** [comment]
@lwtchu could you let us know where we want to put this? We may need some TOC redesign. We will park tomorrow (2/4). We may need to state "Chapter [#]" as well as "Unit [#]"....

**Comment by lwtchu** [comment]
@brittweinstein sounds good i know there's some...issues with when we did it it added words to rex and it broke stuff but i'd like to just revisit to see if we shoudl still do this

**Comment by brittweinstein** [comment]
@lwtchu is your suggestion that we add the text mentioned in my first comment?

**Comment by brittweinstein** [comment]
@lwtchu could you please provide a link to this content so @TomWoodward can review?

**Comment by lwtchu** [comment]
Recap from Kim: This will result in changing the url slug. Rex could write something to ignore the Chapter and Unit but then CE tech might have to do something also.

SOOOOOOOO with all that being said. Need to check with Anthony and Alina if it's worth stirring pots.

**Comment by openstaxalina** [comment]
Discussed w/ Larissa: 

We locked the recipes so that we would be able to make changes in the baked styles and allow REX to choose when to get the baked styles recipe updates (and be able to get content updates in the meantime, using the locked recipes).

Therefore, I am in favor of making this change for the baked styles.

**Comment by lwtchu** [comment]
So the change would be

Add `Unit 1` and `Chapter 1` in the recipes so that they'll display in the ToC

**Comment by lwtchu** [comment]
Updated original comment to include appendix

**Comment by ajluk** [comment]
How it looks now: 
![image](https://user-images.githubusercontent.com/55203598/75471539-af567e80-5992-11ea-83ff-c04540679313.png)

**Comment by ajluk** [comment]
Info for testing purposes
It can be tested in Biology 2e (where the units have been removed from the content).

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-28 10-18-35](https://user-images.githubusercontent.com/47241114/75529854-e3be4f00-5a13-11ea-8f7a-1b72f8ff5e3a.png)
