### ISSUE TITLE
carnival theme: folio changes 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1784]
![image](https://user-images.githubusercontent.com/11299125/72836714-cc40b900-3c52-11ea-81f6-564f3c216c4a.png)

- [x] Color: Grey2: #A5A5A5
- [x] Font size: font-scale(-1)
- [x] the chapter number/section number be the only bold thing?
- [x]  increase the padding between the page number and folio contents (between 54 & 2 in the screenshot)
- [x] need specs to be added in theme doc (i can't find it on there?)

**Comment by brittweinstein** [comment]
@brittany-johnson will add the specs. @lwtchu @andymuddimer could you provide padding info?

**Comment by brittweinstein** [comment]
Refactor the folio so we don't have to do this 20398 times.

**Comment by helenemccarron** [comment]
@lwtchu to answer your question re: "the chapter number/section number be the only bold thing?" the answer is no. Markup is very limited in the folio.
Also we will have to add non-breakable spaces for the padding to be increased (again, limited options for markup = limited styling).

**Comment by helenemccarron** [comment]
@lwtchu I lied, I can use h-grid. Here's the result with h-grid(5) and lo and behold! It lines up perfectly with the content. Does this work?

![2020-02-07_13-01-52](https://user-images.githubusercontent.com/8514591/74057846-640c0a00-49aa-11ea-8334-59c148057373.png)
![2020-02-07_13-04-18](https://user-images.githubusercontent.com/8514591/74057914-82720580-49aa-11ea-80fe-78c62518f951.png)

**Comment by lwtchu** [comment]
nice! is this the space between the page number and the chapter number?

**Comment by helenemccarron** [comment]
This addresses all issues for the folio: 
TOC: no page number

Preface, left and right
![2020-02-10_12-18-51](https://user-images.githubusercontent.com/8514591/74177906-3f10d480-4c00-11ea-9e47-0dd374954664.png)
![2020-02-10_12-19-03](https://user-images.githubusercontent.com/8514591/74177912-420bc500-4c00-11ea-9c2d-f373a1fe88c8.png)

chapter intro: no page number

modules, left and right
![2020-02-10_12-19-25](https://user-images.githubusercontent.com/8514591/74178126-aaf33d00-4c00-11ea-85c3-d26cc7696db4.png)
![2020-02-10_12-19-36](https://user-images.githubusercontent.com/8514591/74178127-ab8bd380-4c00-11ea-86de-bdac919440bb.png)

EOC (with band)
![2020-02-10_12-20-30](https://user-images.githubusercontent.com/8514591/74178174-bc3c4980-4c00-11ea-86a2-54c07304fd28.png)
![2020-02-10_12-20-51](https://user-images.githubusercontent.com/8514591/74178186-c100fd80-4c00-11ea-9df6-47e963ba971d.png)
![2020-02-10_12-21-04](https://user-images.githubusercontent.com/8514591/74178193-c3fbee00-4c00-11ea-8e8b-efd921ef15c6.png)
![2020-02-10_12-21-26](https://user-images.githubusercontent.com/8514591/74178222-cd855600-4c00-11ea-905f-bdff86ddcbf8.png)

Appendices (with band), same on  both sides

![2020-02-10_12-21-39](https://user-images.githubusercontent.com/8514591/74178262-daa24500-4c00-11ea-88b9-2390a7d1c6cf.png)

Index (with band), same on both sides
![2020-02-10_12-22-01](https://user-images.githubusercontent.com/8514591/74178282-e3931680-4c00-11ea-8335-18503f3a43a5.png)

The specs were updated with the relevant information.

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-17 13-26-32](https://user-images.githubusercontent.com/47241114/74653779-2ae15000-5189-11ea-9a8f-2289aa6dea0d.png)
![Screenshot from 2020-02-17 13-25-54](https://user-images.githubusercontent.com/47241114/74653781-2b79e680-5189-11ea-94ca-9a692823a572.png)
![Screenshot from 2020-02-17 13-25-42](https://user-images.githubusercontent.com/47241114/74653782-2c127d00-5189-11ea-9aef-7e725a0f6652.png)
![Screenshot from 2020-02-17 13-25-21](https://user-images.githubusercontent.com/47241114/74653783-2c127d00-5189-11ea-8082-951f5f7145f6.png)
![Screenshot from 2020-02-17 13-24-59](https://user-images.githubusercontent.com/47241114/74653784-2d43aa00-5189-11ea-8d72-5f25da658e2f.png)
![Screenshot from 2020-02-17 13-18-29](https://user-images.githubusercontent.com/47241114/74653787-2ddc4080-5189-11ea-8570-69e5163db685.png)
