### ISSUE TITLE
carnival theme: preface headers

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1785]
![image](https://user-images.githubusercontent.com/11299125/72837808-bdf39c80-3c54-11ea-8a38-da8bb8d20559.png)

Preface

BodyH4	
“font-family: “”Muli”“,
**font-weight: 800,**
**text-transform: uppercase,**
font-size: font-scale(2),
line-height: line-height(2),
color: book specific,”

- change font-weight 800 to bold
-  remove uppercase

BodyH5
“font-family: “”Muli”“,
**font-weight: 800,**
**text-transform: uppercase,**
font-size: font-scale(1),
line-height: line-height(1),
color: book specific,”

- change font-weight 800 to bold
-  remove uppercase

**Comment by ajluk** [comment]
Already resolved: 
![image](https://user-images.githubusercontent.com/55203598/74133431-d8cc8780-4be8-11ea-82d1-a1ff97d15b05.png)
