### ISSUE TITLE
carnival theme: figure captions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1786]
![image](https://user-images.githubusercontent.com/11299125/72839089-378c8a00-3c57-11ea-8903-849a4844bf82.png)

Figure caption here should be font-scale(0) but it is not. I think it is listed as font-scale(0) in the specs doc.

`<figure>`s should be centered and `<image>` or `<media>` should be left aligned.

Screenshot is in Biology, but I think it's in all the books.

**Comment by brittweinstein** [comment]
@lwtchu could you advise on where this is? We should verify the specs at different levels.

**Comment by lwtchu** [comment]
@brittweinstein this is in the body for so far all the books we've regression tested. they're find for the splash image only

**Comment by ajluk** [comment]
Changes in TDS:
Figures
in component **FigureContainer**
change **font-size: font-scale(0)**, (was set to 1 previously)

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-10 14-15-08](https://user-images.githubusercontent.com/47241114/74152977-c74aa600-4c0f-11ea-8cc3-c7ccad47f068.png)
