### ISSUE TITLE
carnival theme: subsubtitle changes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1787]
![image](https://user-images.githubusercontent.com/11299125/72839284-9ce07b00-3c57-11ea-961a-361b429c1060.png)

SubSubtitle	
“font-family: “”Muli”“,
color: B4,
**font-weight: 800,**
**text-transform: uppercase,**
font-size: font-scale(2),
line-height: line-height(2),”

- change font weight to bold
- remove uppercase

**Comment by brittweinstein** [comment]
@lwtchu and @andymuddimer could you confirm that the value for the header is not correct?

**Comment by brittweinstein** [comment]
The change to specs for the headers level (H3?) to be font-weight bold, not the font-weight 800 and remove uppercase. 

Anywhere the font-weight 800 is found, this should be changed to bold.

**Comment by lwtchu** [comment]
@brittweinstein if it helps the label in the tech doc is `SubSubtitle` and not specified as a h3 or h4, etc ?

**Comment by helenemccarron** [comment]
The h4 (subsub titles) in modules:
![2020-02-04_16-13-17](https://user-images.githubusercontent.com/8514591/73792119-4b60e180-4769-11ea-97f8-e82ffed2c0c7.png)


I also changed the bodyh4 and BodyH5 in the preface per specs (bold, no uppercase):
![2020-02-04_16-10-49](https://user-images.githubusercontent.com/8514591/73791958-eefdc200-4768-11ea-9dae-0ec68b862b55.png)


This changes also all occurrences of font-weight: 800 to font-weight: bold
Summary section title: not sure which book.
Exercise section title: not sure which book.
In the review questions (hs physics, I think).

Please update the specs l. 471, l.515, l.523

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-10 14-52-40](https://user-images.githubusercontent.com/47241114/74155513-029ba380-4c15-11ea-9c5e-bb6a1d7562c1.png)
