### ISSUE TITLE
carnival theme: key term

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1788]
![image](https://user-images.githubusercontent.com/11299125/72839651-4889cb00-3c58-11ea-8d2c-8bdf67aad0a6.png)

Can the second line (knowledge) start at the beginning of the definition (science that seeks to …)? And have that be the functionality for definitions that go into the second line.

**Comment by lwtchu** [comment]
![image](https://user-images.githubusercontent.com/11299125/74168732-c570ea80-4bef-11ea-9b62-2bb8daec27dd.png)

Based on conversation with UX/Alina/Larissa - can we change this to a standard hanging indent? (h-grid(2))?  

*You can google image search "hanging indent" if you are not sure what it means

**Comment by ajluk** [comment]
No it looks like this: 
![image](https://user-images.githubusercontent.com/55203598/74229942-acd20480-4cc3-11ea-9438-9275129f05b7.png)

**Comment by ajluk** [comment]
Changes in TDS:
In **Key Term** shape components:
**TermDL** (l.564)
text-indent: h-grid(-2),
padding-left: h-grid(2), (margin-left should be replaced with this property)

**Term** (l.565)
padding-right: h-grid(1), (margin-left should be replaced with this property)

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-17 13-12-17](https://user-images.githubusercontent.com/47241114/74652825-30d63180-5187-11ea-833e-395ec23430b8.png)
![Screenshot from 2020-02-17 13-02-11](https://user-images.githubusercontent.com/47241114/74652748-01bfc000-5187-11ea-9ae5-6e7690dad78e.png)
