### ISSUE TITLE
carnival theme: chapter summary EocHeader

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1789]
![image](https://user-images.githubusercontent.com/11299125/72840391-b71b5880-3c59-11ea-84f7-0c14926d517b.png)

Change "1.1 The Science of Biology" font to font-scale(2).

I THINK this is the EocSectionSummary EocHeader? But I'm not sure...let me know and I can change it on the spec sheet.

**Comment by brittweinstein** [comment]
@lwtchu and @andymuddimer could you please confirm the header and fontscale do/don't match?

**Comment by lwtchu** [comment]
@brittweinstein current it is at 14pt which isn't on the font scale. so we're thinking of having it be font-scale(2) therefore resulting in 12.96pt.

**Comment by helenemccarron** [comment]
The specs need to be updated with the following:
`SectionTitleLink` and `EocSectionTitleLink` should include `font-size: font-scale(3)` after the font-family.

**Comment by helenemccarron** [comment]
Note: this is an h3, so I applied the h3  font-scale(3)
![2020-02-04_11-49-33](https://user-images.githubusercontent.com/8514591/73771691-6cfba200-4744-11ea-840c-c3279af5db5b.png) cc @lwtchu

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-11 10-57-54](https://user-images.githubusercontent.com/47241114/74226733-624d8980-4cbd-11ea-85a4-19be5ae51046.png)
