### ISSUE TITLE
carnival theme: footnotes styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1790]
![image](https://user-images.githubusercontent.com/11299125/72840497-f9449a00-3c59-11ea-9e69-7180c16f2e8d.png)

This should be font-scale(0) per the specs, but they are not. 

This is in Biology but might impact the library.

**Comment by ajluk** [comment]
This was resolved within this PR: https://github.com/openstax/cnx-recipes/pull/1856

**Comment by ajluk** [comment]
Changes in TDS are already updated but I have written it just to document.
In Footnotes components:
Container
font-size: font-scale(0),

In FootnoteCall components:
DefaultFootnoteCall
font-size: font-scale(0),

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-13 10-46-39](https://user-images.githubusercontent.com/47241114/74421978-272e9000-4e4e-11ea-8c84-59b039135272.png)
![Screenshot from 2020-02-13 11-26-15](https://user-images.githubusercontent.com/47241114/74425565-30baf680-4e54-11ea-8687-fedc0b373227.png)
