### ISSUE TITLE
carnival theme: remove line after chapter module title

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1791]
![image](https://user-images.githubusercontent.com/11299125/72840647-4e80ab80-3c5a-11ea-9fd9-a67b59bf0039.png)

Can we remove the line that  comes after the module title?

**Comment by brittweinstein** [comment]
@brittweinstein this will be a part of the header epic.

**Comment by helenemccarron** [comment]
@lwtchu does this apply to all books?

**Comment by lwtchu** [comment]
@helenemccarron i told u in person but just saw this comment - yes remove for all books. please reduce the spacing also (from 2 to 1 line height)

**Comment by helenemccarron** [comment]
![2020-02-04_14-35-59](https://user-images.githubusercontent.com/8514591/73784758-ac81b880-475b-11ea-9b71-497bab83322a.png)

The following needs to be removed from the specs, in the module title l.166:
```
        border-bottom-color: black,
        border-bottom-width: 0.05rem,
        border-bottom-style: solid,
        padding-bottom: v-grid(1),
        margin-bottom: v-grid(1),
```

**Comment by lwtchu** [comment]
@helenemccarron is it possible to remove the space to v-grid(2) after the learning objectives? the space after it looks too big now

**Comment by helenemccarron** [comment]
The update to the learning objectives requires a spec change l.223 remove 
 `margin-bottom:v-grid(2),`

![2020-02-04_16-37-14](https://user-images.githubusercontent.com/8514591/73793755-9fb99080-476c-11ea-9d2f-724c8e8deb91.png)

**Comment by MartaSztuka** [comment]
Line is still there.
![Screenshot from 2020-02-11 15-20-51](https://user-images.githubusercontent.com/47241114/74244767-385a8e00-4ce2-11ea-8588-76ba4ca42da7.png)

**Comment by helenemccarron** [comment]
@MartaSztuka what branch were you using, I tested it on earnest.einstein and I can see my changes:
![2020-02-19_13-17-38](https://user-images.githubusercontent.com/8514591/74867461-521b5700-531a-11ea-8548-e8bb266a076a.png)

**Comment by MartaSztuka** [comment]
@helenemccarron I've tested it on previous branch 9 days ago, will do again on earnest.einstein

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-20 08-42-28](https://user-images.githubusercontent.com/47241114/74911470-f6ee7080-53bc-11ea-9bdd-16a84defa4ae.png)
![Screenshot from 2020-02-20 08-41-02](https://user-images.githubusercontent.com/47241114/74911472-f950ca80-53bc-11ea-8611-c532c00d9d9f.png)
![Screenshot from 2020-02-20 08-40-51](https://user-images.githubusercontent.com/47241114/74911475-f9e96100-53bc-11ea-8aeb-a2772b72fcac.png)
