### ISSUE TITLE
carnival theme: boxed note title 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1792]
![image](https://user-images.githubusercontent.com/11299125/72841056-36f5f280-3c5b-11ea-900c-0fc0dabfaf80.png)

Title	
“color: book specifc,
font-family: book specifc,
font-weight: bold,
**font-size: font-scale(3),**
**line-height: line-height(3),**
margin-top: 0,
margin-bottom: v-grid(1),
border-bottom-style: dotted,
border-bottom-width: 0.2rem,
border-bottom-color: book specifc,
padding-bottom: half-v-grid(1)”

Change font-size to font-scale(2) and line-height to line-height(2).

**Comment by helenemccarron** [comment]
![2020-02-05_12-14-18](https://user-images.githubusercontent.com/8514591/73870094-0e502a00-4811-11ea-930f-4c2824b5d5b7.png)

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-11 15-27-45](https://user-images.githubusercontent.com/47241114/74245370-2decc400-4ce3-11ea-967c-8f4e7fbc581e.png)
![Screenshot from 2020-02-11 15-27-25](https://user-images.githubusercontent.com/47241114/74245372-2f1df100-4ce3-11ea-95f6-206882d0fc28.png)
