### ISSUE TITLE
DOCUMENTATION: carnival theme: example issue to end all example issues

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1793]
## Examples with Titles
![Screen Shot 2020-01-23 at 12 56 46 PM](https://user-images.githubusercontent.com/11299125/73014469-d93ee300-3ddf-11ea-9eaa-a218c76c3dd6.png)

### Number
Carnival specs for styles
Style: Muli Black
Weight: regular
Size: font-scale(1)
Uppercase: ON

### Title 
Carnival Specs for styles
Style: Alegreya
Size: font-scale(1)
Weight: bold
Uppercase: off

### Paragraphs with titles nested in note
Present in: College Physics, AP Physics, University Physics
Carnival Specs for styles
Style: IBM Plex Sans
Size: font-scale(1)
Weight: Bold
Uppercase: Off

### Notes with titles nested in note 
Present in: Chemistry, Chemistry AF
Carnival Specs for styles
Style: IBM Plex Sans
Size: font-scale(1)
Weight: Bold
Uppercase: Off

### Equations 
Equations will exist and should follow the normal schema as the rest of the book.

### Figures
Figures should follow existing formatting. Centered, with the same specs for the caption and numbering as the rest of the book.

#### Sample CNXML
```
<example>
    <title>Unit Conversions: A Short Drive Home</title>
    <para>...</para>
    <para>
      <title>Strategy</title>
    </para>
    <para>...</para>
    <para>
      <title>Solution for (a)</title>
    </para>
   <para>...</para>
    <para id="import-auto-id2609064">
      <title>Solution for (b)</title>
    </para>
    <equation>...</equation>
    <note>
      <title>Answer:</title>
<para>.....</para>
</note>
</example>
```

### Books with no examples
Biology 2e
Anatomy and Physiology
Microbiology
Concepts of Biology

**Comment by MartaSztuka** [comment]
**The Title Answer:**
Style: IBM Plex Sans
Size: font-scale(1)
Weight: Bold
Uppercase: Off

**Comment by brittweinstein** [comment]
@lwtchu can we close this or should we update with corn theme specs?

**Comment by lwtchu** [comment]
i'll make this relevant to carnival only and there's already #2209 #2203  for the corn theme
