### ISSUE TITLE
carnival theme: implement table v/h-grid

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1797]
For 100%

Can we implement a table v/h-grid to be half of the actual v-grid. This should help reduce the spacing and not make it wonky rectangle.

Once that's done please come back to me for more specs.

**Comment by Stackblocks** [comment]
Working to create a scale for tables that is square, using the half v-grid for h & v; that way if the half v-grid is altered then the scaling of the table will adjust to match.

**Comment by Stackblocks** [comment]
@lwtchu I have an initial change built, could you take a look and confirm that this is the kind of change you were looking for?

## examples
![2020-01-28_12-48-49.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/002e75bb-ca2d-4ba5-920f-781532822492)
---
![2020-01-28_12-54-33.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6a754c1c-e4c7-41d3-bd53-7118e61d3b5c)
---
![2020-01-28_12-58-20.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/dd4adacf-f2c1-4c0c-a6e6-7302a70094cd)
---
![2020-01-28_13-00-18.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0e7720ba-22c0-4e31-b25e-1e1d50a13386)

**Comment by lwtchu** [comment]
Looks good - will meet tomorrow to hash thru some details

**Comment by lwtchu** [comment]
@Stackblocks is there anything for the spreadsheet to update?

**Comment by MartaSztuka** [comment]
tetsed
![Screenshot from 2020-02-10 14-59-05](https://user-images.githubusercontent.com/47241114/74156079-eba98100-4c15-11ea-8e70-e9d87fd72e35.png)
