### ISSUE TITLE
change mix-ins for examples to support 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1798]
Based on this conversation: https://openstax.slack.com/archives/CBW9DFKGF/p1579204842167800

![image](https://user-images.githubusercontent.com/11299125/73003997-2e70f980-3dcc-11ea-8a1f-83db52cafa6b.png)
 
Please research to see if we can pull the random text out of the header (like in the notes) and move it into the space of the example.

**Comment by helenemccarron** [comment]
Fixing https://github.com/openstax/cnx-recipes/issues/1757

**Comment by helenemccarron** [comment]
@lwtchu this is the result without any styles changes, only recipes. Is this acceptable?
![2020-01-27_11-01-10](https://user-images.githubusercontent.com/8514591/73196030-840f1400-40f4-11ea-8c4d-feecec4d7f47.png)

**Comment by lwtchu** [comment]
@helenemccarron there's literal tears in my eyes. C'EST MAGNIFIQUE

**Comment by lwtchu** [comment]
@helenemccarron but also is it duplicating the title? it's showing up twice

**Comment by helenemccarron** [comment]
Oh, yes, it was a very long fake title with dummy content :D here's real content
![2020-01-27_11-21-56](https://user-images.githubusercontent.com/8514591/73197656-4b246e80-40f7-11ea-9d83-88ca0f3424df.png)

**Comment by lwtchu** [comment]
@helenemccarron encroyable <3 <3 <3 <3

**Comment by helenemccarron** [comment]
perfect, I'll close this issue and push against #1757 since it resolves the original issue
