### ISSUE TITLE
Figure number/caption line return in collated material

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1801]
# Scenario
In baked College Physics collated material, there are some awkward line returns on the figure number and the caption is indented

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="530" alt="Screen Shot 2020-01-23 at 12 05 15 PM" src="https://user-images.githubusercontent.com/1895432/73011024-1ce21e80-3dd9-11ea-90d1-e33705184e05.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by brittany-johnson** [comment]
Look to see if we're properly supported images and figures in the EOC

**Comment by brittweinstein** [comment]
This may be because we don't support figures in the EOC.

**Comment by Stackblocks** [comment]
This is also occurring in tables (https://github.com/openstax/cnx-recipes/issues/1695), so it is likely an issue with the captioning component which needs further investigation.

**Comment by brittany-johnson** [comment]
<img width="1652" alt="Screen Shot 2020-02-26 at 11 29 03 AM" src="https://user-images.githubusercontent.com/24909007/75370811-505a1200-588b-11ea-8f7e-108c86f5aae5.png">

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-28 11-26-43](https://user-images.githubusercontent.com/47241114/75540890-3bad8380-5a1d-11ea-8877-b263c434e2e8.png)
