### ISSUE TITLE
Embedded content should generate link text for print

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1802]
# Scenario
The Concept Trailers embedded in various chapters' intros in College Physics just say "Click to view content" with no url anywhere. The same is true of any linked content, including the Phets. That'll be awkward in print. We need a url for print so people can type it in if they want to visit from print version.

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="563" alt="Screen Shot 2020-01-23 at 12 11 11 PM" src="https://user-images.githubusercontent.com/1895432/73011485-ee187800-3dd9-11ea-8144-3087f522fa46.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by brittweinstein** [comment]
The link should display in parentheses after.

**Comment by lwtchu** [comment]
![Screen Shot 2020-02-03 at 3 53 27 PM](https://user-images.githubusercontent.com/11299125/73694577-f2784700-469d-11ea-88d4-becf4dbb58f7.png)

![Screen Shot 2020-02-03 at 3 59 52 PM](https://user-images.githubusercontent.com/11299125/73694708-3cf9c380-469e-11ea-9b2e-958aa5170079.png)

here's a screenshot from the old pdf's if it helps.

**Comment by MartaSztuka** [comment]
tetsted![Screenshot from 2020-02-20 15-48-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/802d5ce3-c216-4389-8408-245159d243fb)
