### ISSUE TITLE
footnotes from tables show up in the next module

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1803]
# Scenario
College Physics has some footnotes that are showing up in the wrong place.

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="567" alt="Screen Shot 2020-01-23 at 1 31 08 PM" src="https://user-images.githubusercontent.com/1895432/73017063-b9f68480-3de4-11ea-8dac-3d5aebe00ce0.png">

<img width="579" alt="Screen Shot 2020-01-23 at 1 31 14 PM" src="https://user-images.githubusercontent.com/1895432/73017054-afd48600-3de4-11ea-82a8-fafccfd339b9.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by oscryan** [comment]
Sometimes it's just a couple pages later in the same module
<img width="574" alt="Screen Shot 2020-01-23 at 1 52 44 PM" src="https://user-images.githubusercontent.com/1895432/73018636-a993d900-3de7-11ea-8a33-cef02e60cf43.png">
<img width="549" alt="Screen Shot 2020-01-23 at 1 52 36 PM" src="https://user-images.githubusercontent.com/1895432/73018644-ad276000-3de7-11ea-8dba-941a5af57447.png">

**Comment by oscryan** [comment]
also a problem in the appendices
<img width="584" alt="Screen Shot 2020-01-23 at 2 10 21 PM" src="https://user-images.githubusercontent.com/1895432/73019909-2627b700-3dea-11ea-8c00-644acc3338d4.png">
<img width="583" alt="Screen Shot 2020-01-23 at 2 10 11 PM" src="https://user-images.githubusercontent.com/1895432/73019910-2627b700-3dea-11ea-8071-5705eb1a61fc.png">

**Comment by brittweinstein** [comment]
@brittany-johnson will look at this with her page break work.

**Comment by MartaSztuka** [comment]
@helenemccarron @brittweinstein @lwtchu
Footnote in Appednix breaks in two
![Screenshot from 2020-03-24 16-03-50](https://user-images.githubusercontent.com/47241114/77441044-48898100-6de9-11ea-9445-e4afdcd8169d.png)

![Screenshot from 2020-03-24 16-03-57](https://user-images.githubusercontent.com/47241114/77440990-3c052880-6de9-11ea-962a-6711cf1d90a5.png)

**Comment by MartaSztuka** [comment]
**Biology 2e**
![Screenshot from 2020-03-24 17-08-12](https://user-images.githubusercontent.com/47241114/77449355-20eae680-6df2-11ea-8095-1e70c8ed2d2d.png)
![Screenshot from 2020-03-24 17-05-30](https://user-images.githubusercontent.com/47241114/77449362-221c1380-6df2-11ea-8d64-51594971aa67.png)
**HS Physics**
![Screenshot from 2020-03-24 17-24-20](https://user-images.githubusercontent.com/47241114/77451032-69a39f00-6df4-11ea-95ae-7f67308adf88.png)

**Comment by MartaSztuka** [comment]
@helenemccarron @brittweinstein @lwtchu With the latest College Physics PDF issue is fixed
![Screenshot from 2020-03-25 10-11-25](https://user-images.githubusercontent.com/47241114/77520137-0449bf80-6e81-11ea-944a-896dde8a7536.png)
![Screenshot from 2020-03-25 10-11-16](https://user-images.githubusercontent.com/47241114/77520140-057aec80-6e81-11ea-8f22-5e094798c86f.png)
