### ISSUE TITLE
collating text crash

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1804]
# Scenario
College Physics chapter 33 collated text crashes (that image is too large and that's a content issue, but why the crash)

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="597" alt="Screen Shot 2020-01-23 at 2 00 50 PM" src="https://user-images.githubusercontent.com/1895432/73019353-0c39a480-3de9-11ea-83ec-abc34d833d4e.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by oscryan** [comment]
<img width="536" alt="Screen Shot 2020-01-23 at 2 03 32 PM" src="https://user-images.githubusercontent.com/1895432/73019424-296e7300-3de9-11ea-922f-6feceb71409a.png">

**Comment by brittweinstein** [comment]
@oscryan the text is taking the same width as the image. Could you please change the image size via the export and see if that resolves this?

**Comment by brittweinstein** [comment]
Issue moved to [openstax/content-managers #1425](https://github.com/openstax/content-managers/issues/1425) via [**ZenHub**](https://www.zenhub.com/)
