### ISSUE TITLE
images escaping margins

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1806]
# Scenario
College Physics is escaping
Chapter 34.1
# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)

<img width="589" alt="Screen Shot 2020-01-23 at 2 05 53 PM" src="https://user-images.githubusercontent.com/1895432/73020022-66873500-3dea-11ea-9919-1346c7af423a.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by oscryan** [comment]
ap biology
<img width="688" alt="Screen Shot 2020-01-24 at 2 21 09 PM" src="https://user-images.githubusercontent.com/1895432/73101323-04473680-3eb5-11ea-9ace-103e4f908a51.png">

**Comment by brittweinstein** [comment]
@oscryan @lwtchu this will need to be fixed via content changes -- exporting the images at the exact size they should display.

**Comment by brittweinstein** [comment]
Issue moved to [openstax/content-managers #1424](https://github.com/openstax/content-managers/issues/1424) via [**ZenHub**](https://www.zenhub.com/)
