### ISSUE TITLE
math index terms break

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1807]
# Scenario
College Physics index term doesn't show up under symbols, but it is broken where it does show up alphabetically.

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)

<img width="1299" alt="Screen Shot 2020-01-23 at 2 13 47 PM" src="https://user-images.githubusercontent.com/1895432/73020296-f5944d00-3dea-11ea-9212-f6ed1e9295b2.png">

<img width="589" alt="Screen Shot 2020-01-23 at 2 14 28 PM" src="https://user-images.githubusercontent.com/1895432/73020603-9420ae00-3deb-11ea-8c53-4abc66be066c.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by brittweinstein** [comment]
@oscryan could you please remove the index tag from this? We will not include this term in the index as of rn.
