### ISSUE TITLE
tutor exercise table gets a number

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1811]
# Scenario
The table pulled in from a tutor exercise in AP Biology is now numbered when previously it wasn't.
https://legacy.cnx.org/content/m62717/latest/source

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="1295" alt="Screen Shot 2020-01-24 at 2 08 44 PM" src="https://user-images.githubusercontent.com/1895432/73100708-b7169500-3eb3-11ea-823e-61031dd05424.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by Stackblocks** [comment]
@brittweinstein since this pertains to AP Bio and is not part of the current print push, can it be backlogged / slid out of d.d. so we can make sure we have a clear picture of remaining table-related print work to wrap before e.e.?

**Comment by openstaxalina** [comment]
fine by me @brittweinstein - I'll move this but please let us know if we overlooked something

**Comment by Stackblocks** [comment]
The table in question doesn't have the `.unnumbered` class and as such the book generator process is treating it as a table that needs to be counted. CMs do not believe they can put a class on content in imported exercises so this may need a more complex solution.

## Table without unnumbered class
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/75e6f06f-33a5-4103-838a-cd314db965a4)

## Table with unnumbered class
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e0bf58ca-6122-4fcb-9f4b-fe2fb5681ec6)

**Comment by Stackblocks** [comment]
As a test Larissa added the class to the exercise on the exercise server and it passed through correctly. Some additional research will need to be done to make sure this isn't impacting anything else, and to see if this kind of fix needs to be applied elsewhere on the exercise server. 

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/98bd9a26-c8b3-4081-961d-0f90dd7e9a7f)

**Comment by Stackblocks** [comment]
Per Nathan, this doesn't impact anything on the Tutor side, so i'm marking this resolved by way of content adjustment.
