### ISSUE TITLE
appendices starting on immediately following pages

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1812]
# Scenario
AP Biology has appendices on facing pages, which means one of them will be on the left side in folio.

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="589" alt="Screen Shot 2020-01-24 at 3 24 05 PM" src="https://user-images.githubusercontent.com/1895432/73105122-c26ebe00-3ebd-11ea-88e3-3c0fea91391d.png">
<img width="593" alt="Screen Shot 2020-01-24 at 3 23 58 PM" src="https://user-images.githubusercontent.com/1895432/73105123-c26ebe00-3ebd-11ea-9f92-984ddcad562f.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by helenemccarron** [comment]
Addressed in https://github.com/openstax/cnx-recipes/pull/1892

**Comment by MartaSztuka** [comment]
tested. There is one blank page after appendix A.
![Screenshot from 2020-02-17 12-10-03](https://user-images.githubusercontent.com/47241114/74648695-7b06e500-517e-11ea-9a1d-04e9db66181d.png)
![Screenshot from 2020-02-17 12-06-05](https://user-images.githubusercontent.com/47241114/74648703-7e01d580-517e-11ea-8b5f-33a7fc1b6b42.png)

**Comment by brittweinstein** [comment]
@lwtchu this is the desired behaviour, right?

**Comment by openstaxalina** [comment]
I can answer this one -- yes, they should start on right-hand pages.  Should this be closed now?  cc @brittweinstein @lwtchu

**Comment by lwtchu** [comment]
Closing cause it's DESIRED
