### ISSUE TITLE
hs physics: style figures and tables

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1815]
Figures and tables in HS Physics should be styled with specs from Carnival Theme.

**Comment by wilkus27** [comment]
NOTE: there is no changes to provide in Theme Design Specs.

Ready for testing.

**Comment by wilkus27** [comment]
@MartaSztuka here are the links to the known issues: https://github.com/openstax/cnx-recipes/issues/1826 and https://github.com/openstax/cnx-recipes/issues/1827

**Comment by MartaSztuka** [comment]
styled
![Screenshot from 2020-01-29 11-05-06](https://user-images.githubusercontent.com/47241114/73347219-85247a80-4287-11ea-92b1-f62af0015dce.png)
![Screenshot from 2020-01-29 11-04-29](https://user-images.githubusercontent.com/47241114/73347220-85247a80-4287-11ea-908c-1c3e1ee00870.png)
