### ISSUE TITLE
hs physics: style equations

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1816]
Numbered and Unnumbered equations should be styled in HS Physics with specs from Carnival Theme.

**Comment by wilkus27** [comment]
NOTE: there are no changes to provide to Theme Design Specs.

It's ready for testing.

**Comment by MartaSztuka** [comment]
styled
![Screenshot from 2020-01-29 11-01-15](https://user-images.githubusercontent.com/47241114/73346879-e9930a00-4286-11ea-8605-7c7ba0a2bd1e.png)
![Screenshot from 2020-01-29 11-00-49](https://user-images.githubusercontent.com/47241114/73346880-e9930a00-4286-11ea-902c-84b57ba4ad20.png)
