### ISSUE TITLE
My how the tables have turned...or been...styled?

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#1820]
# What happened?

(_Briefly but clearly describe the issue_)

# Reproducibility Details

- **Does it also happen in an incognito window?**: 
- **Does this happen in one place, a few places, or everywhere?**:

# Environment:

- **Book(s)**:
- **URL/Server**: 
- **Location (page number, chapter/section)**:
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots

(_attach here (please clearly label what environment each screenshot came from)_)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by lwtchu** [comment]
![image.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/baf85120-eb5c-43a7-804a-55ccacf1ffd4)

**Comment by Stackblocks** [comment]
@brittweinstein Should we close epic this since all the issues are closed out?
