### ISSUE TITLE
DOCUMENTATION: library wide: note issue to end all note issues

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1824]
# Glossary
Note name: the name of the note, usually identifiable by the class (Link to Learning, Check Your Understanding, Chemistry in Everyday Life). 
Note title: often referred to as a subtitle. This will be in a `<title>` tag of some kind.

# Common structures

## Note with name and no title
Carnival theme design
![Screen Shot 2020-01-29 at 12 45 02 PM](https://user-images.githubusercontent.com/11299125/73387076-96748380-4295-11ea-9601-bdd53a535fb5.png)

## Note with name and title
Carnival theme design
![Screen Shot 2020-01-29 at 12 44 59 PM](https://user-images.githubusercontent.com/11299125/73386913-48f81680-4295-11ea-92f7-848b158c65eb.png)

Sometimes these are marked up with a `<para><title>` and not the `<note> <title>`.

## Note with only a title and no name (no class)
Carnival theme design
![Screen Shot 2020-01-29 at 12 45 08 PM](https://user-images.githubusercontent.com/11299125/73386993-6f1db680-4295-11ea-8f38-e88aa7ac7f06.png)

## Note with no name and no title
Carnival theme design 
![Screen Shot 2020-01-29 at 1 03 50 PM](https://user-images.githubusercontent.com/11299125/73388435-d2104d00-4297-11ea-92e7-3b64db3cf08b.png)

## Chapter/Learning Objectives note
Usually has a paragraph line (At the end of this chapter you should be able to...) with a list.

# Styles
## Carnival
- Boxed note
- Iconned note
- Condensed icon note
- Learning objective note (styled like a learning objective - present in HS Physics)
- Example note (styled like an example - present in HS Physics)

## Fun things inside of a note and how they should be styled
- #1706 exercises with classes on them
- #1705 note within a note (sometimes)
- paragraph titles
- equations
- figures
- images
- tables

**Comment by brittweinstein** [comment]
@lwtchu can we close this or should we update this with corn theme specs?

**Comment by lwtchu** [comment]
@brittweinstein we can close this

**Comment by lwtchu** [comment]
@brittweinstein oop also meant to say - this is good info to have for any intro people? but this mostly applies to the carnival theme
