### ISSUE TITLE
Generate Entrepreneurship, College Success, Psych 2e Zips for OpenStax + SE

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1825]
~Now that _Entrepreneurship_ has been released, we need to generate an ePub for Study Edge, so they can ingest our content into an OpenStax + SE app.  Staging.cnx.org doesn't have this book - **is it possible to use the data on cnx.org?**  If not, I will probably defer this work until we've published more of this quarter's books and I get the data on staging updated.~

We decided to use vendor.cnx.org for this - more detailed instructions are in a comment below.

[This spreadsheet](https://docs.google.com/spreadsheets/d/14GLK8wnYo4SHTZdvFjJWYHlqdBjXCxfqZnXsjxa6emo) is where we track the titles, with their UUIDs and versions, for the ePubs we've created / need to create for Study Edge.

Here are the steps for generating an ePub:
1) SSH into the server.
2) Run a command based on the UUID provided.
3) Wait for the command to complete.
4) Download the file.
5) Delete the ePub-only content.
6) Rename the index file to `index.html`.
7) Zip the folder with the proper file name.
8) Upload to [this Google Drive folder](https://drive.google.com/drive/folders/1lw9BfhIcOG0gFdWz9ZgY3yLfXpaJ8ef0).
9) Use @cm in the #books-and-candles channel to alert content managers that an ePub is ready for QA.
10) Delete the collection that was generated in the Home folder.

# Environment:

* **Medium**: [ ] REX [ ] PDF  [x] cnx.org  
* **Instance**: [ ] production  [ ] qa  [x] staging  [ ] dev  [ ] content

# Test Plan 
- Alert @cm in the #books-and-candles channel to alert content managers that an ePub is ready for QA
- CMs will open issues in this repo for any files that do not pass testing.

# Acceptance Criteria
- All books on the spreadsheet have had ePubs uploaded to the [folder](https://drive.google.com/drive/folders/1lw9BfhIcOG0gFdWz9ZgY3yLfXpaJ8ef0).

**Comment by openstaxalina** [comment]
- Make sure book is baked **vendor.cnx.org**
- Check UUID matches with spreadsheet
- ssh **vendor08.cnx.org ?????**
- /var/cnx/venvs/publishing/bin/cnx-archive-export_epub  --format baked /etc/cnx/publishing/app.ini {UUID} {bookName.epub}
    - 10-15 mins per book 
- if you ls at root, you will see everything in your home directory 
- after running you will see new file in root 
=====================
- create a folder to hold all the data to deliver 
- scp homedirs1.cnx.org:~/{bookName.epub} . 
    - run this command in the directory you created
    - 'scp' s copy 
    - '.' is the location that you're in, places the file in your current dir 
    could replace with another path 
=======
- go into finder 
- use the 'unarchiver' unarchive the folder 
- go into the new folder 
- delete unneeded files (mimetype & meta-inf)
- copy the UUID from the filename 
- go into contents folder and search for UUID 
- rename the found file to index.xhtml 
- click on file to make sure it works and is baked 
- click around to make sure the images work 
- look in resources folder to make sure the images work 
- zip the folder
- remove it from the server 
- all we are dilvering is the zip folders, rm everything else

**Comment by Stackblocks** [comment]
@openstaxalina We need to figure out who to contact about the command to generate the ePub so they can confirm that we have the right command (or that everything is set up for that command to work), as `/var/cnx/venvs/publishing/bin/cnx-archive-export_epub --format baked /etc/cnx/publishing/app.ini d380510e-6145-4625-b19a-4fa68204b6b1@10.6 entrepreneurship.epub` returns the result `-bash: /var/cnx/venvs/publishing/bin/cnx-archive-export_epub: No such file or directory`

**Comment by openstaxalina** [comment]
@philschatz could you assist with this? If not, who would be a good person to assist?

**Comment by dtwilliamson** [comment]
> * Make sure book is baked **vendor.cnx.org**
> * Check UUID matches with spreadsheet
> * ssh **vendor08.cnx.org ?????**
> * /var/cnx/venvs/publishing/bin/cnx-archive-export_epub  --format baked /etc/cnx/publishing/app.ini {UUID} {bookName.epub}
>   
>   * 10-15 mins per book
> * if you ls at root, you will see everything in your home directory
> * after running you will see new file in root
>   =====================
> * create a folder to hold all the data to deliver
> * scp homedirs1.cnx.org:~/{bookName.epub} .
>   
>   * run this command in the directory you created
>   * 'scp' s copy
>   * '.' is the location that you're in, places the file in your current dir
>     could replace with another path
>     =======
> * go into finder
> * use the 'unarchiver' unarchive the folder
> * go into the new folder
> * delete unneeded files (mimetype & meta-inf)
> * copy the UUID from the filename
> * go into contents folder and search for UUID
> * rename the found file to index.xhtml
> * click on file to make sure it works and is baked
> * click around to make sure the images work
> * look in resources folder to make sure the images work
> * zip the folder
> * remove it from the server
> * all we are dilvering is the zip folders, rm everything else

@openstaxalina There is no server vendor08.cnx.org (which I see you have questioned yourself). Do you know which server it's supposed to be? Is this to be performed on production or another environment?

**Comment by Stackblocks** [comment]
Here are some updated instructions for our records:


1. Make sure book is baked on **[vendor.cnx.org](http://vendor.cnx.org/)**
2. Check UUID matches with the tracking spreadsheet (Ask the CMs)
3. Access the Press server with `ssh Prod08.cnx.org`
4. Generate an ePub with `/var/cnx/venvs/publishing/bin/cnx-archive-export_epub --format baked /etc/cnx/publishing/app.ini {UUID} {bookName.epub}`
	- This can take 10-15 mins per book
5. If you haven't changed your location, the ePubs will be generated to your home directory.
6. Fetch the ePubs from the server using an FTP program or `scp...`
7. Go to where you downloaded the ePubs on your local machine.
8. Change the file type to .zip from .epub
9. Extract the .zip file
10. Inside the extracted .zip file, delete the mimetype and 
11. Delete unneeded files (mimetype, meta-inf, etc.)
12. Open the contents folder and find the file that matches the book's UUID
13. Rename the found file to index.xhtml
14. Open the file and click around to make sure it is working. Images should load, etc.
15. Re-zip the folder using the "Compress" option in the Mac's right click menu.
16. Upload the new zips to wherever they need to go, and delete the files you generated from Prod08.cnx.org.

**Comment by Stackblocks** [comment]
Zips generated and delivered.
