### ISSUE TITLE
Headers of columns in table are not styled correctly

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1826]
In HS Physics some of the tables have different markup. Headers of columns are putting in `tbody` tag, not `thead`.

![image](https://user-images.githubusercontent.com/40228854/73279935-19420380-41ee-11ea-9bc1-3e37e0fe52dd.png)

So tables are not styled correctly:

![image](https://user-images.githubusercontent.com/40228854/73279992-2f4fc400-41ee-11ea-90ee-8e61e156f037.png)

Here is the example of table with proper markup and styling:

![image](https://user-images.githubusercontent.com/40228854/73280107-5d350880-41ee-11ea-987e-31e1e4692d0e.png)

![image](https://user-images.githubusercontent.com/40228854/73280158-6d4ce800-41ee-11ea-9b96-b7c198d8f04d.png)

**Comment by lwtchu** [comment]
Hi. Can you find me the places where this happens so we can fix this.

**Comment by Stackblocks** [comment]
This is the first one I found, I'll keep looking to see if I turn up others.

# 1
<p id="auto_m80194_fs-id1167066029986">Some physical quantities are more fundamental than others. In physics, there are seven fundamental physical quantities that are measured in base or physical fundamental units: length, mass, time, electric current temperature, amount of substance, and luminous intensity. Units for other physical quantities (such as force, speed, and electric charge) described by mathematically combining these seven base units. In this course, we will mainly use five of these: length, mass, time, electric current and temperature. The units in which they are measured are the meter, kilogram, second, ampere, kelvin, mole, and candela (<a href="#auto_m80194_Table_01_03_SIUnits" class="autogenerated-content">[link]</a>). All other units are made by mathematically combining the fundamental units. These are called <span data-type="term">derived units</span>.</p><table id="auto_m80194_Table_01_03_SIUnits" summary="A three column, nine row table is shown. The header row contains the following column titles: blank, SI Base Unit, and blank. The first data row contains Quantity, Name, and Symbol. The second data row contains length, meter, and m. the third data row contains mass, kilogram, and kg. the fourth data row contains time, second, and s. the fifth data row contains electric current, ampere, and a. the sixth data row contains temperature, kelvin, and k. the seventh data row contains amount of substance, mole, and mol. The final data row contains luminous intensity, candela, and cd."><caption><span data-type="title">SI Base Units</span></caption><tbody>
<tr>
<td><strong>Quantity</strong></td>
<td><strong>Name</strong></td>
<td><strong>Symbol</strong></td>
</tr>
<tr>
<td>Length</td>
<td>Meter</td>
<td>m</td>

**Comment by lwtchu** [comment]
We'll just update the first table then. Alan doesn't believe we need the table to test. If you need it asap please let me know.


The others I think are okay as is.
