### ISSUE TITLE
One column tables

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1827]
One column tables are not styled correctly:

![image](https://user-images.githubusercontent.com/40228854/73280828-5e1a6a00-41ef-11ea-9223-5370400b00fe.png)

Example from HS Physics. Styled with `BasicTableShape`.

In regular tables (with several columns) there are no borders on the left and right side. We need to decide what should be done in this case.

**Comment by Stackblocks** [comment]
Resolved in PR #1921 with a temporary fix, but further work will need to be done. Created #1922 to track that work.

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-20 17-31-21](https://user-images.githubusercontent.com/47241114/74956757-e19e3400-5406-11ea-892c-2e8949ee5581.png)
