### ISSUE TITLE
carnival theme: clean up names of components

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1828]
Names of components should describe more precisely related elements. 
For example names of the components from TOC:

**TocCompositeChapter** - component related with composite chapter from End of Book (like Answer Key)

**TocEocCompositeChapter** - component related with composite chapter from End of Chapter (e.g Chapter Review)

Name of the first component doesn't show it is related with EOB.

**Comment by Stackblocks** [comment]
Handled as part of the implementation of BEM
