### ISSUE TITLE
Specs for TOC composite chapters

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1829]
## Changes to provide to Theme Design Specs

NOTE: both in the NoUnitToc and UnitToc shape

### Existing components:

_Component:_: **TocCompositeChapter**
_Properties:_: 
```
  display: block;
  margin-bottom: 3rem;
```
_Component:_: **TocCompositeChapterList**
_Properties:_: 
```
display: none
```
_Component:_: **TocCompositeChapterLink**
_Properties:_: 
```
  font-family: IBM Plex Sans, sans-serif;
  font-size: 1.2rem;
  line-height: 1.5rem;
  color: black;
  text-decoration: none;
```
_Component:_: **TocCompositeChapterLinkPage**
_Properties:_: 
```
  content: target-counter(attr(href), page);
  display: inline-block;
  margin-left: 3rem;
  font-family: IBM Plex Sans, sans-serif;
  font-size: 1.2rem;
  line-height: 1.5rem;
```
### New components:

_Component:_: **TocEocCompositeChapter**
_Properties:_: 
```
display: block,
margin-bottom: v-grid(2)
```
_Component:_: **TocEocCompositeChapterList**
_Properties:_: 
```
display: none,
```
_Component:_: **TocEocCompositeChapterLink:**
_Properties:_: 
```
font-family: "Alegreya",
font-size: font-scale(1),
line-height: line-height(1)
color: black
 text-decoration: none; 
```
_Component:_: **TocEocCompositeChapterLinkPage:**
_Properties:_: 
```
content: target-counter(attr(href), page);
display: inline-block;
margin-left: 3rem;
font-family: ("IBM Plex Sans", sans-serif),
font-size: font-scale(1),
line-height: line-height(1)
```

**Comment by lwtchu** [comment]
Updated

**Comment by MartaSztuka** [comment]
updated in Theme Design Specs
