### ISSUE TITLE
hs physics: style links, terms and footnotes

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1831]
Links, terms and footnotes should be styled with specs from Carnival Theme.

**Comment by MartaSztuka** [comment]
styled
![Screenshot from 2020-02-04 11-56-36](https://user-images.githubusercontent.com/47241114/73739747-1f346900-4747-11ea-8df5-8669c1374eb2.png)
![Screenshot from 2020-02-04 11-56-26](https://user-images.githubusercontent.com/47241114/73739749-1fccff80-4747-11ea-9a84-4acb887a8cb5.png)
![Screenshot from 2020-02-04 12-16-48](https://user-images.githubusercontent.com/47241114/73740327-4b041e80-4748-11ea-9f4c-faf51ed5c47d.png)
