### ISSUE TITLE
hs physics: style eoc and eob

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1833]
End of Chapter and End of Book should be styled with specs from Carnival Theme.

**Comment by wilkus27** [comment]
## Changes to provide to Carnival Theme

NOTE: there are created two new shapes `EocKeyEquWithSectionLink` and `EocSummaryWithSectionLink`. They are almost the same as shapes `EocKeyEqu` and `EocSummary`. The only difference is additional component `EocSectionTitleLink` with property: `font-family: Muli,`.

![image](https://user-images.githubusercontent.com/40228854/73732590-bba43e80-473a-11ea-8294-8e850bf2744d.png)

This is a temporary solution. New shapes were created to avoid changes in other books then HS Physics. During cleaning up Carnival Theme it's going to be created one shape. So my proposition is to not put those new shapes to Theme Design Specs for now and wait for future changes.

Here are the new shapes which should be put into the Theme Design Specs:

**Shape:** `EocCompositeChapter`
_Component:_ `Container`
_Properties:_
```
        margin-bottom: v-grid(4),
```

_Component:_ `EocHeader`
_Properties:_
```
        color: #00819A,
        font-weight: bold,
        font-size: font-scale(4),
        line-height: line-height(4),
        text-transform: uppercase,
        font-family: IBM Plex Sans, sans-serif;
        margin-bottom: v-grid(1)
```
**Elements using this shape**:
- `ChapterReviewCompositeChapter`
- `TestPrepCompositeChapter`

![image](https://user-images.githubusercontent.com/40228854/73733640-9ca6ac00-473c-11ea-81a6-5adffb4e80e8.png)

![image](https://user-images.githubusercontent.com/40228854/73733987-35d5c280-473d-11ea-8945-7f14889f4135.png)

**Comment by wilkus27** [comment]
**Shape:** `EocCompChapExercises`

_Component:_ `Container`
_Properties:_
```
        margin-bottom: v-grid(4),
        column-count: enum('ValueSet:::OPTIONAL'),
        column-gap: enum('ValueSet:::OPTIONAL'),
        column-width: enum('ValueSet:::OPTIONAL'),
```

![image](https://user-images.githubusercontent.com/40228854/73743691-750d0f00-474f-11ea-8326-b00f2a5d2f46.png)

_Component:_ `CompChapPageHeader`
_Properties:_
```
        color: enum('ValueSet:::REQUIRED'),
        font-family: enum('ValueSet:::REQUIRED'),
        font-weight: bold,
        font-size: font-scale(3),
        line-height: line-height(3),
        text-transform: uppercase,
        column-span: enum('ValueSet:::OPTIONAL'),
        margin-bottom: v-grid(1)
```

![image](https://user-images.githubusercontent.com/40228854/73743734-8e15c000-474f-11ea-9a77-eaefd318d5b7.png)

_Component:_ `EocSectionTitleLink`
_Properties:_
```
        font-family: enum('ValueSet:::REQUIRED'),
```

![image](https://user-images.githubusercontent.com/40228854/73743779-a4238080-474f-11ea-9322-7740d0c44efc.png)

_Component:_ `ProblemWrapper`
_Properties:_
```
        display: table,
```

![image](https://user-images.githubusercontent.com/40228854/73743914-eea4fd00-474f-11ea-96ed-7ef197d87922.png)

_Component:_ `ProblemNumber`
_Properties:_
```
        color:  enum('ValueSet:::REQUIRED'),
        font-weight:  enum('ValueSet:::REQUIRED'),
        text-decoration:  enum('ValueSet:::REQUIRED'),
        display: table-cell,
```

![image](https://user-images.githubusercontent.com/40228854/73743973-1300d980-4750-11ea-93f9-e7cbad463494.png)

_Component:_ `ProblemDivider`
_Properties:_
```
        margin-right: enum('ValueSet:::REQUIRED'),
```

![image](https://user-images.githubusercontent.com/40228854/73744001-27dd6d00-4750-11ea-9f45-d59115a56e2b.png)

_Component:_ `ProblemContainer`
_Properties:_
```
        display: table-cell,
```

![image](https://user-images.githubusercontent.com/40228854/73744042-3d529700-4750-11ea-92de-afbe76dd0877.png)


**Elements using this shape:**

- `ConceptCompChapPage`

_Component:_ `CompChapPageHeader`
_Properties:_
```
        color: #00819A;
        font-family: IBM Plex Sans, sans-serif;
```
_Component:_ `EocSectionTitleLink`
_Properties:_
```
        font-family: Muli
```
_Component:_ `ProblemNumber`
_Properties:_
```
        color:  black,
        font-weight: bold,
        text-decoration: none,
```
_Component:_ `ProblemDivider`
_Properties:_
```
        margin-right: h-grid(1),
```

The same settings for:

- `CriticalThinkingCompChapPage`
- `ProblemsCompChapPage`
- `PerformanceCompChapPage`
- `MultipleChoiceCompChapPage`
- `ShortAnswerCompChapPage`
- `ExtendedResponseCompChapPage`

**Comment by lwtchu** [comment]
This is thorough and very clear. Thank you @wilkus27

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-07 10-24-21](https://user-images.githubusercontent.com/47241114/74017483-9d397f80-4994-11ea-9549-dfe418465ff7.png)
![Screenshot from 2020-02-07 10-23-53](https://user-images.githubusercontent.com/47241114/74017486-9e6aac80-4994-11ea-8df5-2d0599e07029.png)
![Screenshot from 2020-02-07 10-23-37](https://user-images.githubusercontent.com/47241114/74017487-9e6aac80-4994-11ea-8003-cf1b9c637d2e.png)
