### ISSUE TITLE
hs physics: style notes

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1839]
### Notes to style:
 
- Grasp Check
- Snap Lab
- Worked Example
- Tips for Success
- Work in Physics
- Fun in Physics
- Boundless Physics
- Links to Physics
- Watch Physics
- Virtual Physics

More informations about styling in https://github.com/openstax/cnx-recipes/issues/1696, https://github.com/openstax/cnx-recipes/issues/1705 and https://github.com/openstax/cnx-recipes/issues/1706.

**Comment by wilkus27** [comment]
## Changes to provide to Theme Design Specs

**New shape:** `BoxCondensedNoteShape`

_Component:_ `CondensedContainer`
_Properties:_ 
```
    background: enum('ValueSet:::REQUIRED'),
    padding-top: v-grid(.5),
    padding-bottom:v-grid(.5),
    padding-right: enum('ValueSet:::OPTIONAL'),
    padding-left: enum('ValueSet:::OPTIONAL'),
    margin-bottom: enum('ValueSet:::REQUIRED'),
```
![image](https://user-images.githubusercontent.com/40228854/73931973-97cb2f00-48d9-11ea-9673-0e87174aaad3.png)

_Component:_ `Title`
_Properties:_ 
```
    font-family: enum('ValueSet:::REQUIRED'),
    font-weight: bold,
    text-transform: uppercase,
    font-size: font-scale(1),
    line-height: line-height(1),
```
![image](https://user-images.githubusercontent.com/40228854/73932011-ab769580-48d9-11ea-80ca-b5d766464e33.png)


**Changed shape:** `IconNoteShape`

_New Component:_ `DivSubtitle`
_Properties:_ 
```
    font-family: enum('ValueSet:::OPTIONAL'),
    font-size: enum('ValueSet:::OPTIONAL'),
    line-height: enum('ValueSet:::OPTIONAL'),
    font-weight: enum('ValueSet:::OPTIONAL'),
    text-transform: enum('ValueSet:::OPTIONAL'),
    display: enum('ValueSet:::OPTIONAL'),
    padding-right: enum('ValueSet:::OPTIONAL'),
```
![image](https://user-images.githubusercontent.com/40228854/73932065-c812cd80-48d9-11ea-8af8-92749c6b69ae.png)

----------------------------------------------------------------------------
### Notes:

**Note:** `VirtualPhysicsNote`
**Using shape:** `BoxedNoteShape`

_Component:_ `Container`
_Properties:_ 
```
   border-color: G7,
```
_Component:_ `Title`
_Properties:_ 
```
   font-family: Muli,
   color: G7,
   border-bottom-color: G7,
```
![image](https://user-images.githubusercontent.com/40228854/73932421-964e3680-48da-11ea-916e-a468ac0139a6.png)


**Note:** `SnapLabNote`
**Using shape:** `BoxedNoteShape`

_Component:_ `Container`
_Properties:_ 
```
   border-color: B7,
```
_Component:_ `Title`
_Properties:_ 
```
   font-family: Muli,
   color: B7,
   border-bottom-color: B7,
```

**Note:** `WatchPhysicsNote`
**Using shape:** `IconNoteShape`

_Component:_ `Container`
_Properties:_ 
```
   border-bottom-color: B7,
```
_Component:_ `Title`
_Properties:_ 
```
   font-family: Muli,
   color: B7,
   border-bottom-color: B7,
```
_Component:_ `TitleLabel`
_Properties:_ 
```
   max-width: 9rem,
```
_Component:_ `TitleIcon`
_Properties:_ 
```
   background: carnival-visualconnection.svg", no-repeat top left
```

**Note:** `LinksToPhysicsNote`
**Using shape:** `IconNoteShape`

_Component:_ `Container`
_Properties:_ 
```
   border-bottom-color: G3,
```
_Component:_ `Title`
_Properties:_ 
```
   font-family: Muli,
   color: G3,
   border-bottom-color: G3,
```
_Component:_ `TitleLabel`
_Properties:_ 
```
   max-width: 9rem,
```
_Component:_ `TitleIcon`
_Properties:_ 
```
   background: carnival-linktolearning.svg", no-repeat top left
```

**Note:** `BoundlessPhysicsNote`
**Using shape:** `IconNoteShape`

_Component:_ `Container`
_Properties:_ 
```
   border-bottom-color: G7,
```
_Component:_ `Title`
_Properties:_ 
```
   font-family: Muli,
   color: G7,
   border-bottom-color: G7,
```
_Component:_ `TitleLabel`
_Properties:_ 
```
   max-width: 9rem,
```
_Component:_ `TitleIcon`
_Properties:_ 
```
   background: carnival-boundlessphysics.svg", no-repeat top left
```

**Note:** `FunInPhysicsNote`
**Using shape:** `IconNoteShape`

_Component:_ `Container`
_Properties:_ 
```
   border-bottom-color: R4,
```
_Component:_ `Title`
_Properties:_ 
```
   font-family: Muli,
   color: R4,
   border-bottom-color: R4,
```
_Component:_ `TitleLabel`
_Properties:_ 
```
   max-width: 9rem,
```
_Component:_ `TitleIcon`
_Properties:_ 
```
   background: carnival-funphysics.svg", no-repeat top left
```

**Note:** `WorkInPhysicsNote`
**Using shape:** `IconNoteShape`

_Component:_ `Container`
_Properties:_ 
```
   border-bottom-color: BR2,
```
_Component:_ `Title`
_Properties:_ 
```
   font-family: Muli,
   color: BR2,
   border-bottom-color: BR2,
```
_Component:_ `TitleLabel`
_Properties:_ 
```
   max-width: 9rem,
```
_Component:_ `TitleIcon`
_Properties:_ 
```
   background: carnival-career.svg", no-repeat top left
```
![image](https://user-images.githubusercontent.com/40228854/73932592-f47b1980-48da-11ea-83f2-441a247ddb89.png)


**Note:** `WorkedExampleNote`
**Using shape:** `IconNoteShape`

_Component:_ `Container`
_Properties:_ 
```
   border-bottom-color: R3,
```
![image](https://user-images.githubusercontent.com/40228854/73932721-32783d80-48db-11ea-801d-c19c62b5f713.png)

_Component:_ `Title`
_Properties:_ 
```
   font-family: Muli,
   color: R3,
   border-bottom-color: R3,
```
![image](https://user-images.githubusercontent.com/40228854/73932796-5045a280-48db-11ea-993e-8fec576dd35a.png)

_Component:_ `TitleIcon`
_Properties:_ 
```
   background: carnival-example.svg", no-repeat top left
```
![image](https://user-images.githubusercontent.com/40228854/73932822-64899f80-48db-11ea-9e62-f7ec1068b32c.png)

_Component:_ `TitleText`
_Properties:_ 
```
   display: inline-block,
   word-wrap: normal,
   margin-bottom: .2rem,
   margin-left: h-grid(1),
```
![image](https://user-images.githubusercontent.com/40228854/73932845-7408e880-48db-11ea-96f8-0e5674bdea9d.png)

_Component:_ `SubTitle`
_Properties:_ 
```
   font-family: Alegreya,
   font-weight: bold,
```
![image](https://user-images.githubusercontent.com/40228854/73932873-84b95e80-48db-11ea-9fe3-7915fc56cc23.png)

_Component:_ `DivSubtitle`
_Properties:_ 
```
   font-family: IBM Plex Sans, sans-serif;
   font-size': font-scale(1),
   line-height': line-height(1),
   font-weight': bold,
```
![image](https://user-images.githubusercontent.com/40228854/73932913-969b0180-48db-11ea-95ca-f82d061b2719.png)


**Note:** `TipsForSuccessNote`
**Using shape:** `BoxCondensedNoteShape`

_Component:_ `CondensedContainer`
_Properties:_ 
```
  background': Grey1,
  padding-right': v-grid(.5),
  padding-left': v-grid(.5),
  margin-bottom': v-grid(.5),
```
_Component:_ `Title`
_Properties:_ 
```
   font-family: Muli,
```

**Note:** `GraspCheckNote`
**Using shape:** `BoxCondensedNoteShape`

_Component:_ `CondensedContainer`
_Properties:_ 
```
  background': Grey1,
  padding-right': v-grid(.5),
  padding-left': v-grid(.5),
  margin-bottom': v-grid(.5),
```
_Component:_ `Title`
_Properties:_ 
```
   font-family: Muli,
```

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-10 11-30-44](https://user-images.githubusercontent.com/47241114/74142268-d3773900-4bf8-11ea-9879-02a36db10781.png)
![Screenshot from 2020-02-10 11-31-59](https://user-images.githubusercontent.com/47241114/74142364-ff92ba00-4bf8-11ea-8edc-f27dc0e829e6.png)
![Screenshot from 2020-02-10 11-31-30](https://user-images.githubusercontent.com/47241114/74142366-002b5080-4bf9-11ea-8825-09b9c846ad36.png)
![Screenshot from 2020-02-10 11-35-16](https://user-images.githubusercontent.com/47241114/74142563-762fb780-4bf9-11ea-8a45-49e03983700a.png)
![Screenshot from 2020-02-10 11-34-25](https://user-images.githubusercontent.com/47241114/74142569-79c33e80-4bf9-11ea-92e6-603147981019.png)
![Screenshot from 2020-02-10 11-33-40](https://user-images.githubusercontent.com/47241114/74142578-80ea4c80-4bf9-11ea-959e-f8c30ac097b0.png)
![Screenshot from 2020-02-10 11-36-39](https://user-images.githubusercontent.com/47241114/74142676-a8d9b000-4bf9-11ea-9850-9f5e418ee32b.png)
![Screenshot from 2020-02-10 11-29-39](https://user-images.githubusercontent.com/47241114/74142188-a6c32180-4bf8-11ea-8d02-f4a1fd961de4.png)
