### ISSUE TITLE
carnival theme: reduce padding after boxed note style

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1840]
![image](https://user-images.githubusercontent.com/11299125/73560169-1593c400-441c-11ea-933b-4b3cef525334.png)

Reduce padding below boxed notes. I'm not sure what the grid value is now, but can we reduce it? Or can someone tell me what the value is and I can give you the new one 😬 

This content is in College Physics but I'm not sure if it impacts all of carnival theme.

**Comment by ajluk** [comment]
Change in TDS:
In **BoxedNotes** change in Container component the below property value (l.260):
**Container** 
margin-bottom: v-grid(2),

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-10 16-10-12](https://user-images.githubusercontent.com/47241114/74161813-de918f80-4c1f-11ea-9e87-0a5d3d97294e.png)
