### ISSUE TITLE
carnival theme: break missing from first two introduction paragraphs

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1841]
### College Physics
![image](https://user-images.githubusercontent.com/11299125/73562403-b1bfca00-4420-11ea-9d13-b87b6df84764.png)

### Biology
![Screen Shot 2020-01-31 at 11 56 13 AM](https://user-images.githubusercontent.com/11299125/73562428-be442280-4420-11ea-8068-605605d945eb.png)

Break is missing between ONLY the first two paragraphs in introductions. Present in Biology and College Physics so I'm assuming it's all carnival theme books.

**Comment by helenemccarron** [comment]
![2020-02-05_13-21-31](https://user-images.githubusercontent.com/8514591/73875195-76573e00-481a-11ea-9e81-90c0f160f6a6.png)

The specs need to be modified: ChapterIntroFirstPara l.108, `display: inline` should be `float: left`
The IntroFirstPara l.109 can be removed altogether

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-10 14-09-15](https://user-images.githubusercontent.com/47241114/74152613-f876a680-4c0e-11ea-86e8-82d0429f90e0.png)
![Screenshot from 2020-02-10 14-08-48](https://user-images.githubusercontent.com/47241114/74152616-f9a7d380-4c0e-11ea-9512-5cded7b28afd.png)
