### ISSUE TITLE
college physics: paragraph title styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1842]
![image](https://user-images.githubusercontent.com/11299125/73562727-59d59300-4421-11ea-94de-1b39455522a6.png) 
![image](https://user-images.githubusercontent.com/11299125/73563079-21828480-4422-11ea-8152-b7597874e9b7.png)

Is it possible to add a space between the title and the body text. These are `<title>` in `<para>` in the body.

**Comment by helenemccarron** [comment]
A new spec needs to be added:
`ParagraphTitle` with the value `margin-right: h-grid(1),` in the module section (somewhere around l. 182).
![2020-02-06_15-51-53](https://user-images.githubusercontent.com/8514591/73981793-a83ed200-48f8-11ea-9b6f-d8fdc70d2de5.png)

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-11 11-39-19](https://user-images.githubusercontent.com/47241114/74229709-333a1680-4cc3-11ea-8616-1094fbc37b78.png)
