### ISSUE TITLE
carnival theme: section folio continuing into EOC content

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1843]
![image](https://user-images.githubusercontent.com/11299125/73563138-4545ca80-4422-11ea-9607-67f9e03c7751.png)

this is in the EOC and should no longer be considered 1.4 Approximation.

Content is from College Physics but this should impact all carnival theme titles. Might be related to #1813

**Comment by brittweinstein** [comment]
We should set this as "Chapter [#] [Chapter Title]" 

There is a set standard for this somewhere that Larissa can provide if needed.

**Comment by helenemccarron** [comment]
addressed in https://github.com/openstax/cnx-recipes/pull/1892

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-17 12-56-23](https://user-images.githubusercontent.com/47241114/74651911-32065f00-5185-11ea-908c-df893d34c7e6.png)
