### ISSUE TITLE
College Success: Enable Top Titled Table Styling

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1844]
# Scenario

Top-titled tables should not have a table border around their title:

![CSTopTItleTable](https://user-images.githubusercontent.com/7863733/73563915-1a5c7600-4424-11ea-9767-fb0295f11a9f.png)
![CSTopTitleTable2](https://user-images.githubusercontent.com/7863733/73563917-1a5c7600-4424-11ea-8dbf-16b9a88ef989.png)

Test content (from the screenshots):
https://easyvm5.cnx.org/contents/h2TUSN8V@4.1:Z5FigHML@3/1-1-The-Benefits-of-Time-Management

https://easyvm5.cnx.org/contents/h2TUSN8V@4.1:G9VkA-Ru@2/1-2-Time-Management-in-College

# Acceptance Criteria (required)
![BETopTitleTable](https://user-images.githubusercontent.com/7863733/73564228-b4bcb980-4424-11ea-8e34-87fbe5612ff4.png)
(link: https://cnx.org/contents/kUrGbuHs@5.1:TVY4B3Z7@4/6-3-An-Organized-Workforce)

**Comment by helenemccarron** [comment]
All the tables listed are missing the top-titled class.

![2020-03-04_13-04-50.png](https://images.zenhubusercontent.com/5b06d3244b5806bc2bd47abf/0dbccbd9-b00d-46ae-a2c5-d083005a2ed9)

 Also,
IB: https://easyvm5.cnx.org/contents/Tgl3H6iq@9.1:DK-tGpHN@7/How-Business-and-Economics-Work
OB: https://easyvm5.cnx.org/contents/LZQauaxb@6.1:9pJHuA38@2/Barriers-to-Accurate-Social-Perception
PoM: https://easyvm5.cnx.org/contents/w6yyq31c@11.1:ti2VQkRr@6/Group-Decision-Making
aren't baked

**Comment by openstaxalina** [comment]
@yblock could you add the top-titled class to the _College Success_ content above?

@helenemccarron I _believe_ those other three aren't baked because in the past, we've been instructed to assign the CCAP template so that the recipe can be injected.  Should we go ahead and assign the recipe on the server instead?

**Comment by helenemccarron** [comment]
You may want to bake the book then revert to the  CCAP template. This will bake the book and leave it baked. Also please note that all the examples listed are missing the class, regardless of whether or not they were baked.

**Comment by yblock** [comment]
ok I added the class to those, and baked with recipe, and put CCAP back on.

**Comment by openstaxalina** [comment]
(reopening so we can get to the dev work the _College Success_ test content is ready; I am parking with Marc about the other book content tomorrow morning.

**Comment by yblock** [comment]
Oh I'm sorry, I thought this was a copy of the card!

**Comment by openstaxalina** [comment]
@helenemccarron FYI I modified this card to only include College Success for now.  We can fix the top-titled tables in the other titles sometime before REX updates its content for the fall.  I'll make a new card for that.

Please let us know if you need any other content prep for this card!

**Comment by brittweinstein** [comment]
@yblock please assign the College Success recipe and try rebaking.

**Comment by yblock** [comment]
The content is baked, just waiting for the top-titled fix.

**Comment by openstaxalina** [comment]
We confirmed that the book is baked and that the top-titled class is on the table; however, the tables appear like this: 
<img width="886" alt="Screen Shot 2020-03-09 at 10 17 07 AM" src="https://user-images.githubusercontent.com/7863733/76228758-27247480-61ef-11ea-9cce-2a9bffb732dc.png">

Therefore, we need to enable top-titled tables in this recipe.  @Stackblocks will work on this.

**Comment by omehes** [comment]
https://legacy-easyvm5.cnx.org/Members/cnxeship/col29727

table heads in webview pages look as expected (v 10.1) and in pdf too

![tableh_1](https://user-images.githubusercontent.com/44207656/76902998-1ddc7d00-686b-11ea-8c8f-f3121b424ebc.png)

![tableh_2](https://user-images.githubusercontent.com/44207656/76903015-2765e500-686b-11ea-9e1e-efaaf9988f5b.png)
