### ISSUE TITLE
library wide: attribution link on the bottom every other page

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1847]
![Screen Shot 2020-01-31 at 1 14 05 PM](https://user-images.githubusercontent.com/11299125/73567242-95755a80-442b-11ea-913e-954c1b0df087.png)

This is missing in the baked PDFs. Need to discuss with @openstaxalina to define what this needs to be.

**Comment by openstaxalina** [comment]
I'm checking this proposal with Anthony this week:

`Access for free at openstax.org.`   

This is generic for all books and is also consistent with the language REX uses (example at the bottom of this page: https://openstax.org/books/college-physics/pages/1-introduction-to-science-and-the-realm-of-physics-physical-quantities-and-units).

**Comment by openstaxalina** [comment]
Approved by Anthony - getting final approval from David/Beth/Daniel on Monday at Ops.

**Comment by brittweinstein** [comment]
@openstaxalina any update from the OPS parking lot?

**Comment by openstaxalina** [comment]
Yes, this is finalized now.

We will use the attribution:

`Access for free at openstax.org` 

...for the footer language on every other page in all books in the library.

@lwtchu this does mean that, when we release a PDF in the baked styles, we need to change the language on the copyright page to use that phrase (currently it uses a long URL that is specific to the book on openstax.org).

**Comment by ajluk** [comment]
Changes in TDS:
This property needs to be added in every other page type (page left ) in **Folio** except **Chapter Intro** (maybe addtiional row can be added - page: left to every page type).
bottom-left
font-size: font-scale(-1),
font-family: "Muli";
color: #A5A5A5;
font-weight: 700;
content: "Access for free at openstax.org.";

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-25 12-44-17](https://user-images.githubusercontent.com/47241114/75244723-9bf9b680-57cc-11ea-8f27-8ac449100800.png)
![Screenshot from 2020-02-25 12-43-44](https://user-images.githubusercontent.com/47241114/75244736-9ef4a700-57cc-11ea-8475-6e89e6d1fddd.png)
![Screenshot from 2020-02-25 12-43-07](https://user-images.githubusercontent.com/47241114/75244738-9ef4a700-57cc-11ea-918f-8c191261f2bb.png)
