### ISSUE TITLE
hs physics: style section exercises

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1848]
Text of the exercises and number should be inline:

![image](https://user-images.githubusercontent.com/40228854/73657455-9b20a980-4692-11ea-8000-a01cb2b5e837.png)

**Comment by brittweinstein** [comment]
@Stackblocks could you please review Natalia's PR here? It is related to the table work you are doing.

**Comment by wilkus27** [comment]
Some of the exercises have solutions:

![image](https://user-images.githubusercontent.com/40228854/73764773-d6df7000-4773-11ea-8a53-dc8dbba6462b.png)

Here are the specs for styling header:
```
IBM Plex Sans
Bold
font-scale(1)
Uppercase: off
```

**Comment by lwtchu** [comment]
@wilkus27 what are the specs for the solution header? 

also is it possible to have the question stem go with the number

**Comment by wilkus27** [comment]
@lwtchu sorry for the delay but I merged my PR at the end of my work so I had no time to prepare description for Theme Design Specs.

**Comment by wilkus27** [comment]
## Changes to provide to Theme Design Spec

**New shape**: `ExerciseShape`

_Component:_ `Container`
_Properties:_ `empty`

![image](https://user-images.githubusercontent.com/40228854/73922645-cd681c00-48c9-11ea-8b82-de17c0872a62.png)

_Component:_ `ProblemWrapper`
_Properties:_ 
```
        display: flex,
        flex-direction: row,
```
![image](https://user-images.githubusercontent.com/40228854/73922706-e40e7300-48c9-11ea-938e-daf73c837723.png)

_Component:_ `ProblemNumber`
_Properties:_ 
```
        font-weight: bold,
        text-decoration: none,
```
![image](https://user-images.githubusercontent.com/40228854/73922778-fdafba80-48c9-11ea-8552-642b7b7c6b51.png)

_Component:_ `ProblemDivider`
_Properties:_ 
```
        margin-right: enum('ValueSet:::REQUIRED'),
```
![image](https://user-images.githubusercontent.com/40228854/73922838-14eea800-48ca-11ea-864a-4c063b877e5c.png)

_Component:_ `ProblemContainer`
_Properties:_ `empty`

![image](https://user-images.githubusercontent.com/40228854/73922874-2932a500-48ca-11ea-96aa-5af2750818ee.png)

_Component:_ `SolutionWrapper`
_Properties:_ `empty`

![image](https://user-images.githubusercontent.com/40228854/73922908-3cde0b80-48ca-11ea-9db5-2342aee1a64c.png)

_Component:_ `SolutionTitle`
_Properties:_ 
```
        font-family: enum('ValueSet:::REQUIRED'),
        font-weight: bold,
        font-size: font-scale(1),
        line-height: line-height(1),
```
![image](https://user-images.githubusercontent.com/40228854/73922957-541cf900-48ca-11ea-81b6-6e735db71ab1.png)

**Element using this shape:** `PracticeProblemsExercises`

_Component:_ `ProblemDivider`
_Properties:_ 
```
        margin-right: h-grid(1)
```

_Component:_ `SolutionTitle`
_Properties:_ 
```
        font-family: IBM Plex Sans, sans-serif;
```

**Element using this shape:** `CheckUnderstandingExercises`

the same settings as above

**Comment by lwtchu** [comment]
beautiful thank you natalia ~

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-10 12-10-43](https://user-images.githubusercontent.com/47241114/74145145-69619280-4bfe-11ea-9f47-f4ec59d7b38b.png)
