### ISSUE TITLE
Missing title in Grasp Check

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1853]
Exercise **Grasp Check** which is styled as a note should have title: **GRASP CHECK**.

![image](https://user-images.githubusercontent.com/40228854/73736687-82230180-4741-11ea-8132-5ac8e0b72fd5.png)

**Comment by MartaSztuka** [comment]
Title is there, but it's double.
![Screenshot from 2020-02-07 11-41-21](https://user-images.githubusercontent.com/47241114/74023362-c90e3280-499f-11ea-8357-c6a2d0b19833.png)

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-07 13-28-49](https://user-images.githubusercontent.com/47241114/74029831-de8a5900-49ad-11ea-8b0a-4a81cc5e57d5.png)
