### ISSUE TITLE
hs physics: style Section Key Terms

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1854]
There should be more space between terms from Section Key Terms:

![image](https://user-images.githubusercontent.com/40228854/73737473-ff9b4180-4742-11ea-9a8a-902ccfde0fac.png)

**Comment by brittweinstein** [comment]
@Stackblocks could you please review this PR? It may be related to the tables work you're doing.

**Comment by wilkus27** [comment]
## Changes to provide to Theme Design Specs

**New shape:** `SectionKeyTermsShape`

_Component:_ `Container`
_Properties:_ `empty`

![image](https://user-images.githubusercontent.com/40228854/73925546-83ce0000-48ce-11ea-91b6-71495e932911.png)


_Component:_ `TableBody`
_Properties:_ `empty`

![image](https://user-images.githubusercontent.com/40228854/73925593-96e0d000-48ce-11ea-9ad7-7de73521dc1a.png)

_Component:_ `TableRow`
_Properties:_ `empty`

![image](https://user-images.githubusercontent.com/40228854/73925633-a5c78280-48ce-11ea-9ac7-6b03f1fc7396.png)

_Component:_ `TableData`
_Properties:_ 
```
        padding-right: h-grid(1),
        padding-top: v-grid(.5),
        padding-bottom: v-grid(.5),
```

![image](https://user-images.githubusercontent.com/40228854/73925695-b841bc00-48ce-11ea-9c4f-5f7ae8db46ca.png)

**Element using this shape:** `SectionKeyTerms`

**Comment by wilkus27** [comment]
NOTE per Alan: 

> Once #1797 has been reviewed and merged we can change the v-grids(.5) on the table spacing to table-v-grid and table-h-grid as part of a clean-up pass but since that won't be done until after we need this done they can remain v-grid(.5) for the time being.

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-10 14-55-54](https://user-images.githubusercontent.com/47241114/74155885-953c4280-4c15-11ea-8717-73ea2143bdc6.png)

**Comment by wilkus27** [comment]
@MartaSztuka I just want to make sure, are we ok with this efect? I mean, previously terms displayed right under the header Section Key Term, but after changes provided by Alan all tables are centered. Is it ok that this one also is at the center or it should be exception.

**Comment by MartaSztuka** [comment]
@wilkus27 According to specs it's correct, however we could make exception here and place it under header.

**Comment by lwtchu** [comment]
I think Marta makes a good suggestion - @wilkus27 can we target the section class to left align it?

**Comment by wilkus27** [comment]
@lwtchu Yes it is possible to done. We can try to overwrite settings from tables files in files related with section key terms or to add exception in tables settings to not apply them to tables with `section-key-terms` class .

**Comment by wilkus27** [comment]
@lwtchu That's how it looks now:

![image](https://user-images.githubusercontent.com/40228854/74945030-4ea9cd80-53f7-11ea-83e8-e568a0ccfffc.png)

I removed also margins inherited from other table shapes, because there was a huge white space underneath:

![image](https://user-images.githubusercontent.com/40228854/74945133-7ac54e80-53f7-11ea-85d6-031f3f6eb5fb.png)

**Comment by lwtchu** [comment]
looks great thank you @wilkus27

**Comment by wilkus27** [comment]
## Changes to provide to Theme Design Specs

### Shape: `SectionKeyTermsShape`

_Component:_ `Container`
_Properties:_
```
        margin-left: 0,
        margin-bottom: 0,
```
_New Component:_ `Table`
_Properties:_
```
        margin-bottom: 0,
```
_Component:_ `TableData`
_Changed Properties:_
```
        padding-top: table-v-grid(1),
        padding-bottom: table-v-grid(1),
```

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-25 12-37-28](https://user-images.githubusercontent.com/47241114/75244169-9baceb80-57cb-11ea-8f18-be060bea0cd6.png)
