### ISSUE TITLE
Add a data-uuid-key attribute to the composite chapters

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1858]
For the TOC and the system to work properly, composite chapters need a `data-uuid-key` attribute. The value can be generated from the container's title as long as containers have unique names.

**Comment by MartaSztuka** [comment]
Baking on katalyst01 is unblocked![Screenshot from 2020-02-17 13-33-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cf7fb88a-cd21-4657-9d1e-952d7f1a6217)
