### ISSUE TITLE
CLEAN UP: create one reusable component for all lists spacing

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1862]
There should be one component to unify display of all lists instead of many named components. 

This PR contains a lot of the work done on lists: https://github.com/openstax/cnx-recipes/pull/1697

**Comment by ajluk** [comment]
EOC Issues https://github.com/openstax/cnx-recipes/issues/2015

**Comment by ajluk** [comment]
Changes in TDS:
In the **AnswerKey** shape:
The **OrderedList** ,**UnorderedList** components need to be replaced with one component:
**AnswerKey__List--MarginBottomLeft**
with properties:
margin-left: h-grid(3);
margin-bottom: 0;

In the **Appendix** shape:
The **UnorderedList**, **OrderedList**, **SectionOrderedList** components need to be replaced with one component:
**List--MarginLeft**
with properties:
margin-left: h-grid(3);

**Comment by ajluk** [comment]
@MartaSztuka here is the link to the document for testing purposes, where you can spot places that need to be checked shown on screenshots for College Physics: https://docs.google.com/document/d/1cry7GPpIZ00sCudMtYExkw3Y6vEH8NjfiVGUT8DgLCk/edit#heading=h.n1yzk266rntj

**Comment by MartaSztuka** [comment]
**College Physics**
![Screenshot from 2020-03-26 11-05-48](https://user-images.githubusercontent.com/47241114/77634773-c5d00580-6f51-11ea-89ab-302e7a633bb0.png)
![Screenshot from 2020-03-26 11-12-42](https://user-images.githubusercontent.com/47241114/77635362-be5d2c00-6f52-11ea-8820-6e123a12f5a5.png)
![Screenshot from 2020-03-26 11-13-43](https://user-images.githubusercontent.com/47241114/77635447-e2207200-6f52-11ea-86e3-81f64a850c7c.png)
![Screenshot from 2020-03-26 11-14-43](https://user-images.githubusercontent.com/47241114/77635555-0d0ac600-6f53-11ea-96be-b6516015f482.png)
![Screenshot from 2020-03-26 11-16-31](https://user-images.githubusercontent.com/47241114/77635709-45120900-6f53-11ea-922d-58b333457974.png)
![Screenshot from 2020-03-26 11-17-09](https://user-images.githubusercontent.com/47241114/77635773-5e1aba00-6f53-11ea-9e84-c7cb2c110917.png)
![Screenshot from 2020-03-26 11-19-05](https://user-images.githubusercontent.com/47241114/77635968-a9cd6380-6f53-11ea-8d14-8559e288f615.png)
![Screenshot from 2020-03-26 11-21-08](https://user-images.githubusercontent.com/47241114/77636131-eac57800-6f53-11ea-900e-2e9bf1f0a7d9.png)
![Screenshot from 2020-03-26 11-22-30](https://user-images.githubusercontent.com/47241114/77636259-1ba5ad00-6f54-11ea-85f5-3ca85ce0d6bb.png)
![Screenshot from 2020-03-26 11-24-29](https://user-images.githubusercontent.com/47241114/77636428-64f5fc80-6f54-11ea-972c-89a3df5a9ee9.png)
![Screenshot from 2020-03-26 11-26-07](https://user-images.githubusercontent.com/47241114/77636592-a38bb700-6f54-11ea-8a4f-2e4d7f28dfbf.png)

**Comment by MartaSztuka** [comment]
**Biology 2e**
![Screenshot from 2020-03-26 11-30-03](https://user-images.githubusercontent.com/47241114/77636964-2d3b8480-6f55-11ea-9494-61735f6566e9.png)
![Screenshot from 2020-03-26 11-30-42](https://user-images.githubusercontent.com/47241114/77637014-40e6eb00-6f55-11ea-9c23-91b7023a20d3.png)
![Screenshot from 2020-03-26 11-31-29](https://user-images.githubusercontent.com/47241114/77637083-5c51f600-6f55-11ea-9783-717383afa78a.png)
![Screenshot from 2020-03-26 11-32-30](https://user-images.githubusercontent.com/47241114/77637145-7f7ca580-6f55-11ea-82ed-e869ab5978ef.png)
![Screenshot from 2020-03-26 11-36-16](https://user-images.githubusercontent.com/47241114/77637469-06318280-6f56-11ea-96c6-a938fe123efa.png)
![Screenshot from 2020-03-26 11-37-24](https://user-images.githubusercontent.com/47241114/77637594-32e59a00-6f56-11ea-9389-63569b4f0b4d.png)
![Screenshot from 2020-03-26 11-38-12](https://user-images.githubusercontent.com/47241114/77637671-4c86e180-6f56-11ea-994e-a8a538615d92.png)
![Screenshot from 2020-03-26 11-40-29](https://user-images.githubusercontent.com/47241114/77637874-9cfe3f00-6f56-11ea-89e2-75965c47cd0c.png)
![Screenshot from 2020-03-26 11-41-28](https://user-images.githubusercontent.com/47241114/77637966-c0c18500-6f56-11ea-9fa3-93f7eaf4696e.png)

**Comment by MartaSztuka** [comment]
**High School Physics**
![Screenshot from 2020-03-26 11-44-28](https://user-images.githubusercontent.com/47241114/77638312-404f5400-6f57-11ea-93a2-dafcc0a9dce5.png)
![Screenshot from 2020-03-26 11-48-06](https://user-images.githubusercontent.com/47241114/77638590-afc54380-6f57-11ea-8681-158a8ba92d61.png)
![Screenshot from 2020-03-26 11-50-54](https://user-images.githubusercontent.com/47241114/77638855-1b0f1580-6f58-11ea-8f42-f0fad10bf90b.png)
![Screenshot from 2020-03-26 11-58-01](https://user-images.githubusercontent.com/47241114/77639458-14cd6900-6f59-11ea-9aac-85e67fcdf9f3.png)

**Comment by MartaSztuka** [comment]
**Anatomy and Physiology**
![Screenshot from 2020-03-26 10-38-03](https://user-images.githubusercontent.com/47241114/77632198-f57d0e80-6f4d-11ea-8eaa-321083cbfdae.png)
![Screenshot from 2020-03-26 10-40-47](https://user-images.githubusercontent.com/47241114/77632428-47259900-6f4e-11ea-833d-7dd581af1d92.png)
![Screenshot from 2020-03-26 10-42-12](https://user-images.githubusercontent.com/47241114/77632580-7c31eb80-6f4e-11ea-932f-4cb9c81b83d6.png)
![Screenshot from 2020-03-26 10-43-22](https://user-images.githubusercontent.com/47241114/77632696-a84d6c80-6f4e-11ea-8b86-2948eccb3063.png)
![Screenshot from 2020-03-26 10-44-20](https://user-images.githubusercontent.com/47241114/77632783-c74bfe80-6f4e-11ea-8341-0e8d89ddd28b.png)
![Screenshot from 2020-03-26 10-45-06](https://user-images.githubusercontent.com/47241114/77632871-e21e7300-6f4e-11ea-8583-e9ff8736a82b.png)
![Screenshot from 2020-03-26 10-46-15](https://user-images.githubusercontent.com/47241114/77632972-0b3f0380-6f4f-11ea-9357-8a60aacca2cc.png)
![Screenshot from 2020-03-26 10-47-03](https://user-images.githubusercontent.com/47241114/77633041-2873d200-6f4f-11ea-89bd-6a15988cd317.png)
![Screenshot from 2020-03-26 10-48-50](https://user-images.githubusercontent.com/47241114/77633196-683ab980-6f4f-11ea-9d88-cda968a687d2.png)

**Comment by MartaSztuka** [comment]
**Chemistry 2e**
![Screenshot from 2020-03-26 12-03-31](https://user-images.githubusercontent.com/47241114/77639957-dc7a5a80-6f59-11ea-8b70-58a2e7511f41.png)
![Screenshot from 2020-03-26 12-04-35](https://user-images.githubusercontent.com/47241114/77640023-fb78ec80-6f59-11ea-9667-f405aa1d95da.png)
![Screenshot from 2020-03-26 12-05-07](https://user-images.githubusercontent.com/47241114/77640070-0f245300-6f5a-11ea-8534-11ce07453aef.png)
![Screenshot from 2020-03-26 12-05-47](https://user-images.githubusercontent.com/47241114/77640130-26634080-6f5a-11ea-8d25-6620a45f6684.png)
![Screenshot from 2020-03-26 12-07-20](https://user-images.githubusercontent.com/47241114/77640276-688c8200-6f5a-11ea-8991-d5ce37e2ba90.png)
![Screenshot from 2020-03-26 12-08-21](https://user-images.githubusercontent.com/47241114/77640355-86f27d80-6f5a-11ea-8ea7-96e02be6af4c.png)
![Screenshot from 2020-03-26 12-11-34](https://user-images.githubusercontent.com/47241114/77640592-f5cfd680-6f5a-11ea-8a7f-5f355470d0a6.png)

**Comment by MartaSztuka** [comment]
**Biology for AP Courses**
![Screenshot from 2020-03-26 12-13-59](https://user-images.githubusercontent.com/47241114/77640843-5828d700-6f5b-11ea-8888-e7bd0b3580bb.png)
![Screenshot from 2020-03-26 12-15-23](https://user-images.githubusercontent.com/47241114/77640954-81496780-6f5b-11ea-9af4-1930a58c5b05.png)
![Screenshot from 2020-03-26 12-16-30](https://user-images.githubusercontent.com/47241114/77641030-a6d67100-6f5b-11ea-8440-0a5ea2c2c5f6.png)
![Screenshot from 2020-03-26 12-17-09](https://user-images.githubusercontent.com/47241114/77641083-bd7cc800-6f5b-11ea-99bc-07f3977402a6.png)
![Screenshot from 2020-03-26 12-17-50](https://user-images.githubusercontent.com/47241114/77641135-d5544c00-6f5b-11ea-9403-7eb142a6597a.png)
![Screenshot from 2020-03-26 12-18-27](https://user-images.githubusercontent.com/47241114/77641181-eac97600-6f5b-11ea-9797-8a7934517fbe.png)
![Screenshot from 2020-03-26 12-19-24](https://user-images.githubusercontent.com/47241114/77641261-0df42580-6f5c-11ea-9574-13dec82a6770.png)
![Screenshot from 2020-03-26 12-20-55](https://user-images.githubusercontent.com/47241114/77641377-4562d200-6f5c-11ea-8293-1ad1cfc13b4b.png)
![Screenshot from 2020-03-26 12-20-47](https://user-images.githubusercontent.com/47241114/77641381-4693ff00-6f5c-11ea-89d8-817a7c6e9c3c.png)
![Screenshot from 2020-03-26 12-22-05](https://user-images.githubusercontent.com/47241114/77641490-6f1bf900-6f5c-11ea-94de-4f81e52688dc.png)
![Screenshot from 2020-03-26 12-23-00](https://user-images.githubusercontent.com/47241114/77641574-8d81f480-6f5c-11ea-8fe3-ba9a61c46e62.png)
![Screenshot from 2020-03-26 12-23-40](https://user-images.githubusercontent.com/47241114/77641643-a7233c00-6f5c-11ea-8112-9cb2bcaa83c4.png)
![Screenshot from 2020-03-26 12-24-30](https://user-images.githubusercontent.com/47241114/77641698-c3bf7400-6f5c-11ea-89ae-77b967886bc0.png)
![Screenshot from 2020-03-26 12-26-03](https://user-images.githubusercontent.com/47241114/77641829-fbc6b700-6f5c-11ea-9f7d-97e45c79e3dc.png)
![Screenshot from 2020-03-26 12-29-02](https://user-images.githubusercontent.com/47241114/77642101-68da4c80-6f5d-11ea-8437-f53a98928117.png)
![Screenshot from 2020-03-26 12-30-36](https://user-images.githubusercontent.com/47241114/77642235-9e7f3580-6f5d-11ea-8936-0f1350fc3a77.png)
