### ISSUE TITLE
CLEANUP: Expand table centering to remaining Carnival titles

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#1869]
# What happened?

Due to printing time contraints, the fixes from https://github.com/openstax/cnx-recipes/pull/1463 were only extended to Biology, HS Physics, and College Physics. They will need to be applied to the following titles as part of a cleanup sweep:

- [x] AP Biology
- [x] Microbiology
- [x] University Physics

# Screenshots

## Before
<img width="932" alt="image" src="https://user-images.githubusercontent.com/12678235/73894997-c3033f00-4843-11ea-98a2-a71c02050207.png">

## After
<img width="935" alt="image" src="https://user-images.githubusercontent.com/12678235/73894984-baab0400-4843-11ea-808c-64ab1fb382cb.png">

# Additional notes

Review the changes in https://github.com/openstax/cnx-recipes/pull/1463 and https://github.com/openstax/cnx-recipes/issues/1716 and use those as a template.

**Comment by MartaSztuka** [comment]
AP Biology![Screenshot from 2020-04-07 16-53-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3de9798c-1c5d-476a-a566-12eec072b7e6)
Microbiology![Screenshot from 2020-04-07 16-55-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8d653321-6fbb-4020-acf1-93a82475bcfd)
University Physics![Screenshot from 2020-04-07 16-57-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/561f6f08-1734-4d0f-9cb1-86fdaf849292)
