### ISSUE TITLE
CLEAN UP: create separate files for exercises from entire book

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1870]
All exercises components and shapes should be created in separate files dedicated for Exercises. 

We need to find one common solution for work from PRs: https://github.com/openstax/cnx-recipes/pull/1750/files and https://github.com/openstax/cnx-recipes/pull/1851/files

**Comment by wilkus27** [comment]
To sum up, in EOC is used `display: table` to display properly exercises if there is a math inside.

before:

![image](https://user-images.githubusercontent.com/40228854/75997536-c4d22800-5eff-11ea-9262-3db500eaa1b0.png)

after:

![image](https://user-images.githubusercontent.com/40228854/75997573-d3b8da80-5eff-11ea-92af-4e4111ced29d.png)

In Section Exercises is used `display: flex`, because when exercise starts with figure `display: table` cause such effect:

![image](https://user-images.githubusercontent.com/40228854/75997778-22667480-5f00-11ea-9bd4-2c2365fae034.png)

with `display: flex` it looks like that:

![image](https://user-images.githubusercontent.com/40228854/75997863-3f9b4300-5f00-11ea-972e-6a331d888de5.png)

**Comment by wilkus27** [comment]
@MartaSztuka This issue is in progress. Part of the work is done and could be tested, but please don't close this issue yet, because code will be reworked.

Please check problems described in comment https://github.com/openstax/cnx-recipes/issues/1870#issuecomment-595296634.  So exercises which start with paragraph contain math and which start with figure. For now we have to test it in Biology 2e, Hs Physics and College Physics. If you want to find example with math from the screenshot, it is in Chemistry 2e. Please remember that Hs Physics has also section exercises.

**Comment by MartaSztuka** [comment]
@wilkus27 I've checked in random locations i HS Physics (EoC and section exercises).
HS Physics one exercise is still not ok, or is it other reason?
![Screenshot from 2020-03-23 12-25-02](https://user-images.githubusercontent.com/47241114/77312052-8612df00-6d01-11ea-9bde-286132afc984.png)
![Screenshot from 2020-03-23 12-35-58](https://user-images.githubusercontent.com/47241114/77312768-eb1b0480-6d02-11ea-8498-b7deaea69a3d.png)
College Physics
![Screenshot from 2020-03-23 12-53-04](https://user-images.githubusercontent.com/47241114/77314082-4c43d780-6d05-11ea-8068-a2dad58db4d8.png)
![Screenshot from 2020-03-23 13-00-40](https://user-images.githubusercontent.com/47241114/77314642-5914fb00-6d06-11ea-996a-b25b5d62fbac.png)

Biology 2e, no photos in exercises, just link. I've checked all exercises - looks ok.

**Comment by wilkus27** [comment]
@MartaSztuka problem with exercise 16. from HS Physics it's a content issue.

![image](https://user-images.githubusercontent.com/40228854/77319349-fecc6800-6d0e-11ea-8bf0-104afb733e8c.png)

Text behind image is not put in any tag.

@lwtchu do you know if it is repaired on production?

**Comment by lwtchu** [comment]
<img width="647" alt="Screen Shot 2020-03-23 at 12 33 39 PM" src="https://user-images.githubusercontent.com/11299125/77345389-8b245e00-6d02-11ea-9a9a-1e2c1fbe3cb3.png">
added p tags around the exercise
