### ISSUE TITLE
INVESTIGATION: After merge to master, Microbio and UPhysics fall back to a stale recipe

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1876]
# Scenario

After we merged baked styles work to master on 1/31 (at the end of critical.cher), Ryan rebaked a representative sample of Carnival theme books on staging.cnx.org to test for regressions in a REX instance that points to latest content on staging.cnx.org. 
(Card for reference: https://github.com/openstax/content-managers/issues/1427)

While most of the books baked fine and are now being tested, Microbiology and University Physics could not be baked and "fell back" to the previous recipe:

![Screen Shot 2020-02-06 at 1 25 23 PM](https://user-images.githubusercontent.com/7863733/73971570-bd116a80-48e4-11ea-85ad-ec82efff75fb.png)

We should look into this to determine priority. 

# Acceptance Criteria (required)
- [ ] Be able to successfully bake these books on latest recipes.

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?** 2
* **Images or Screenshots Included:** [x] Yes  [ ] No  (see above)

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [x] cnx.org
* **Instance**: [ ] production  [ ] qa  [x] staging  [ ] dev  [ ] content
* **OS**: [x] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [x] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [x] unknown [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [x] High [ ] Medium  [ ] Low

# Test Plan
Should be able to successfully bake these books on latest recipes.

**Comment by brittweinstein** [comment]
At a minimum, we need an investigation in DD. It is possible that the recipe is broken. It may be a lintr issue.

**Comment by brittweinstein** [comment]
@helenemccarron  will do some analysis this week.

**Comment by paulinaszczucinska** [comment]
@wilkus27 could you: 
verify if all the feature flags are enabled, generate recipes to check if they are working and if they do, please pass the issue to QA  for Marta.

**Comment by wilkus27** [comment]
In PR https://github.com/openstax/cnx-recipes/pull/2067 all release flags was enabled for books fro Carnival Theme. This issue can be tested now. cc @MartaSztuka

**Comment by brittweinstein** [comment]
@brittweinstein follow up on this tomorrow with Katalyst.

**Comment by MartaSztuka** [comment]
@wilkus27  Tried to baked with g.g branch
![Screenshot from 2020-03-23 16-34-26](https://user-images.githubusercontent.com/47241114/77334109-aa33e780-6d24-11ea-90e2-65c9dfa9587e.png)

**Comment by MartaSztuka** [comment]
Baked on g.g branch
![Screenshot from 2020-03-26 14-03-39](https://user-images.githubusercontent.com/47241114/77649783-ae514680-6f6a-11ea-9b14-4c8fd70cbf21.png)

**Comment by wilkus27** [comment]
To be sure, tested again with different print styles:

![image](https://user-images.githubusercontent.com/40228854/77744152-7ead4780-7019-11ea-9b50-cf2c78f5ffe4.png)

First from the bottom bake with recipes from `microbiology-prod.css` file from master.
Second - with `microbiology.css` file from master.
Third - with `microbiology.css` file from gilded.gza.
