### ISSUE TITLE
Lock Eship Recipe

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1878]
# Scenario

We need to lock the recipes for the remaining titles, since these are soon to be in REX: 

- [ ] Entrepreneurship

The steps to do this include:

1. for each group of books listed above, duplicate the [book title] with recipe entry in the dropdown.
2. retitle the new entry [book name] REX recipe
3. this new entry will not always get the latest recipe, the way the original entries do. instead, this should be frozen/pinned at the recipe version as of today's date
4. add symlink for this new entry
5. proceed through verification and deployment steps...

[original card where we locked the other recipes... https://github.com/openstax/cnx-recipes/issues/1624] 

# Acceptance Criteria (required)
- [ ] "prod" (locked) version of the eship recipe appears in the Parameters dropdown
- [ ] book can be successfully baked with the locked recipe

**Comment by brittweinstein** [comment]
Decision: Alina will inform Kim that we will not lock the recipes yet for Dev Math and Psych 2e. Alina will modify this card to reflect that we will do this for E-ship.

**Comment by brittweinstein** [comment]
@omehes this should be ready to test now

**Comment by brittany-johnson** [comment]
@omehes Testing instructions: 

Collection ID : `col29104`
On the URL commands dashboard https://qualitas-server.herokuapp.com/dashboards/urlcommands
Click on `print parameters` and enter the collection ID 
Verify-in the dropdown that Entrepreneurship and Entrepreneurship (Prod) both exist. 

Thank you!

**Comment by omehes** [comment]
verified. found both eship recipes

![eship_2.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/20bc6a56-f861-450f-bcd7-c31c85bc7ecb)
