### ISSUE TITLE
EoC list overleap

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1880]
Letters and numbers overlap. Found only in those two places.
![Screenshot from 2020-02-07 10-36-19](https://user-images.githubusercontent.com/47241114/74018273-e8a05d80-4995-11ea-8b3e-a47ce926c175.png)
![Screenshot from 2020-02-07 10-34-57](https://user-images.githubusercontent.com/47241114/74018274-e938f400-4995-11ea-99b4-19741394a743.png)
![Screenshot from 2020-02-07 10-34-09](https://user-images.githubusercontent.com/47241114/74018276-e938f400-4995-11ea-9211-4d2a0ea5cc15.png)

**Comment by ajluk** [comment]
Changes in TDS:
New components need to be in EocCompChapExercises shape:
Problem_Container
        display: table-cell,
Problem_Paragraph
        margin-bottom: 0,
Exercise_Ordered_List
Exercise_Nested_Ordered_List
Exercise_Unordered_List
Exercise_Container_Ordered_List
Exercise_Figure
Exercise_Container_Unordered_List

**Comment by ajluk** [comment]
@lwtchu This issue contains specs updates for all of these issues connected to PR I have merged as well:
carnival theme: bulleted lists poppin out of EOC section margins #1907
hs physics: lists inside exercises #1906 
hs physics: extra space in exercises between question stem para and list #1909. When you update the TDS table you can assign those to @MartaSztuka as a ready for testing.

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-20 17-07-38](https://user-images.githubusercontent.com/47241114/74954522-89196780-5403-11ea-901b-de81fc5b85be.png)
