### ISSUE TITLE
HS Physics tutor exercise import regression

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1883]
# Scenario
HS Physics is not importing Tutor exercises correctly. Sometimes the LaTeX math does not render, and the multiple-choice answers are left blank.

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
For example, from https://legacy-content04.cnx.org/content/m10008/latest trying to import https://exercises.openstax.org/exercise/1789
<img width="466" alt="Screen Shot 2020-02-07 at 11 06 43 AM" src="https://user-images.githubusercontent.com/1895432/74049689-48990300-499a-11ea-9cc2-6a07baf87909.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by helenemccarron** [comment]
@oscryan  can you please take a look at the update PDF I sent you, I am not seeing the problem locally. If you find any other locations, please include them and I'll take a look.

![2020-02-12_10-22-43](https://user-images.githubusercontent.com/8514591/74354920-b02bc580-4d81-11ea-9f6b-d54d5a64132e.png)

**Comment by oscryan** [comment]
yes it's fine now

**Comment by helenemccarron** [comment]
Should we close this? cc @openstaxalina and @lwtchu

**Comment by openstaxalina** [comment]
Closing!
