### ISSUE TITLE
HS Physics glossary duplicating

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1884]
# Scenario
Terms from module https://legacy-content04.cnx.org/content/m10111/latest are duplicating in the collating key terms section of chapter 23. They are not duplicated in the markup.

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="515" alt="Screen Shot 2020-02-07 at 11 21 39 AM" src="https://user-images.githubusercontent.com/1895432/74050862-78490a80-499c-11ea-8616-3d7fd6e6fd28.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by wilkus27** [comment]
It's a content issue. There are two the same modules in chapter 23:

![image](https://user-images.githubusercontent.com/40228854/74736263-a0652300-5252-11ea-8a92-029188e2bfab.png)

So terms in the text are doubled:

![image](https://user-images.githubusercontent.com/40228854/74736341-cab6e080-5252-11ea-8e98-e1af3789abf2.png)

![image](https://user-images.githubusercontent.com/40228854/74736384-e326fb00-5252-11ea-8dc5-0d1151e6afb5.png)
