### ISSUE TITLE
WAITING TO RESOLVE ALL HIGH PRIO ISSUES: Enable All Release Flags

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1890]
# Scenario

Discussed in today's team meeting:
We will enable *all* remaining release flags (see: https://github.com/openstax/cnx-recipes/blob/master/RELEASE_FLAGS.md).

Content Managers will assist with a full-library regression test.

Alina/Larissa will review issues and prioritize any showstoppers.  (A fallback is to re-enable any flags we can't fix within the sprint.)

Other regressions will be put in future sprints.

# Acceptance Criteria (required)
- [x] all release flags have been enabled (no red "X"s at the above link)
- [x] **developers have run diffs and listed below any specific things that seem to have changed in the books**
- [x] QA has looked in these specific places
- [x] CMs have done regression testing (front/back/three chapters) and opened any issues
- [x] Alina has identified any showstopper issues
- [x] issues have been resolved or those release flags have been re-enabled and will be tracked via cards in subsequent sprints

# Test Plan

**Comment by brittany-johnson** [comment]
**Document outlining all release flags enabled:** 
https://docs.google.com/document/d/1ziR2PcSvioOLAHSRNWZga3m-8DlUM_qaskIjpWtoS60/edit?usp=sharing

**Comment by brittany-johnson** [comment]
Hello @MartaSztuka! I just updated the release flags document with the details to test the `give-composites-ids` release flag. 
Can you re-test this flag with the acceptance criteria in the document? 

Thank you! 

https://docs.google.com/document/d/1ziR2PcSvioOLAHSRNWZga3m-8DlUM_qaskIjpWtoS60/edit#heading=h.dk8rtuc6fky3

**Comment by MartaSztuka** [comment]
`give-composites-ids` flag was retested, work as expected for all books.

**Comment by brittany-johnson** [comment]
My #1 area of concern is the TOC, specifically making sure that everything is numbered and linking properly. 

Other general areas that I think are important to check are the chapter introduction, EOC, and EOB, mainly checking that things are numbering and linking correctly. 

TOC
- unit, chapter, and appendix titles
- EOC and EOB numbering and linking 

Chapter Introduction
- Splash
- Chapter Outline

EOC 
- module titles linking
