### ISSUE TITLE
Lock All Recipes Once Issues from Clean-up, Release Flags, Footnotes, Dependencies are Fixed

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1891]
# Update the Locked Version of the Following Recipes

As discussed with the team, we need to re-lock all recipes once we've tested and fixed all issues resulting from clean-up, release flags, footnotes, and dependency updates. This includes the following recipes:

- [x] Calculus Prod (with recipe) (Vols 1-3)
- [x] Precalculus Prod (with recipe)(also includes College Algebra + Algebra & Trigonometry)
- [x] Microbiology Prod (with recipe)
- [x] Anatomy & Physiology Prod (with recipe)
- [x] U.S. History Prod (with recipe)
- [x] Psychology Prod (with recipe)
- [x] Chemistry Prod (with recipe) (includes Chemistry 2e and Chemistry: Atoms First 2e)
- [x] Astronomy Prod (with recipe)
- [x] Principles of Management Prod (with recipe)(includes Organizational Behavior) (NOTE: this one is missing the word "Prod" - please add it)
- [x] Principles of Accounting Prod (with recipe) (Vols 1-2)
- [x] Business Ethics Prod (with recipe)
- [x] Introduction to Business Prod (with recipe)
- [x] AP Biology Prod (with recipe)
- [x] AP Physics Prod (with recipe)
- [x] Biology Prod (with recipe) (includes Biology 2e, Concepts of Biology)
- [x] Economics Prod (with recipe) (includes Regular + AP - 5 titles)
- [x] High School Physics Prod (with recipe)
- [x] Physics Prod (with recipe) (College Physics) **change the name to College Physics Prod** and also change the non-prod recipe to "College Physics**
*There should be no recipe called "Physics" -- they should all say either "University, AP, High School, or College" before them.*
- [x] Statistics Prod (with recipe) (includes Introductory Statistics, Introductory Business Statistics, HS Statistics)
- [x] University Physics Prod (with recipe) (Vols 1-3)
- [x] Introduction to Sociology 2e Prod (with recipe)
- [x] American Government 2e Prod (with recipe)

# Create New Locked Recipe for DevMath
The following recipes have never been locked so they need a locked version created for the first time:
- [x] Developmental Math
- [x] Entrepreneurship
- [x] College Success

The steps to do this include:

1. for each group of books listed above, duplicate the [book title] with recipe entry in the dropdown.
2. retitle the new entry [book name] REX recipe
3. this new entry will not always get the latest recipe, the way the original entries do. instead, this should be frozen/pinned at the recipe version as of today's date
4. add symlink for this new entry
5. proceed through verification and deployment steps...

[original card where we locked the other recipes... https://github.com/openstax/cnx-recipes/issues/1624] 

# Acceptance Criteria (required)
- [x] all recipes have a "prod" (locked) version available in the dropdown
- [x] books can be successfully baked with the locked recipes
- [x] There should be no recipe called "Physics" -- they should all say either "University, AP, High School, or College" before them.

**Comment by brittweinstein** [comment]
@brittweinstein put this in I.I.

**Comment by brittany-johnson** [comment]
The recipes below were not included on the list and will not have `prod` versions: 
- `ap-history ` 
  - AP History book 
- `intro-sociology `
  - not used in any book
- `pl-u-physics`
  - Polish University Physics v1-3
- `us-government `
  - not used in any book
- All TEA recipes 
  - TEA books

**Comment by openstaxalina** [comment]
@brittany-johnson thanks so much. I do not have concerns about the recipes without a locked version, for now. 

In the future, I will create a card to lock `ap-history` (once we're sure it's done). 

I think that `intro-sociology` and `us-government` could  be removed from books.txt. For the TEA books, they could be removed, but would we be able to restore them if we needed to at some point, for reference?

Finally, I will talk with Katalyst about locking `pl-u-physics` - I think this could be done when the baked styles are done for that title and/or when it's being brought into REX. There is not immediate urgency.

**Comment by brittany-johnson** [comment]
Okay, I removed the intro-sociology and us-government recipes but left the TEA books for now.
Thank you!

**Comment by brittany-johnson** [comment]
@openstaxalina Hello! Alan tested this yesterday on easyvm5, should I assign you, Larissa, or someone else to test on staging?

**Comment by openstaxalina** [comment]
I've completed this testing on CNX staging. I am closing this card and declaring this okay for a prod deploy once other tests for this release have passed. cc @brittweinstein
