### ISSUE TITLE
CLEAN UP: folios

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1893]
- [ ]  Move the band folio rules from the books to to folio.scss and remove redundancies
- [ ] Figure out a way to use book specific colors for each book (might need to convert the flat scss to shapes)
- [ ] ~~Figure out a way to support books with folio-with-band and without (EOC, Appendix, EOB)~~
- [ ] Localization: Accommodate any Poland-specific needs for _Fizyka_ (change hard coded values to read the title content instead among other things)

**Comment by brittany-johnson** [comment]
Closing in favor of https://github.com/openstax/cnx-recipes/issues/2230
