### ISSUE TITLE
Image rendering problem in HS Phys

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1896]
# Scenario
width of this image is 4.88888 inches at 150ppi. It should not be rendering so large. This is occurring all over the book.

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="600" alt="Screen Shot 2020-02-11 at 9 45 53 AM" src="https://user-images.githubusercontent.com/1895432/74253838-3a5a2800-4cb5-11ea-9bdc-36f6c9916a66.png">
# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by lwtchu** [comment]
i'M STUPid and these images are stupid we need to re-export these or point them to the other image in the same module because these are super incorrect

**Comment by lwtchu** [comment]
more context. there's two images. that look exactly the same. one is correct 150dpi/4.8inches adn the other is not correct 72dpi/10inches
