### ISSUE TITLE
Spacing after list items

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#1898]
# What happened?

The list item's content it butted up against the previous list item's content which looks a bit confusing. 

# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: 

# Environment:

- **Book(s)**: College Success
- **URL/Server**: https://content03.cnx.org/contents/Tdb74rvE@4.1:OJRni0YJ@2/1-6-Your-Safety
- **Location (page number, chapter/section)**: 1.6
- **Suggested nearby searchable text**: Be alert and stay charged.
- **Browser**: any

# Screenshots

![Screen Shot 2020-02-11 at 11.38.44 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/c48240fd-7b0d-4919-9f48-f68a3d849d91)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by brittweinstein** [comment]
REX will need to fix this as well @openstaxalina will open an issue in their repo.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/unified #896](https://github.com/openstax/unified/issues/896) via [**ZenHub**](https://www.zenhub.com/)
