### ISSUE TITLE
Update books.txt for Entrepreneurship

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1900]
# Scenario

Entrepreneurship has been released, and content01.cnx.org (where it was produced) has been wiped (cleared of data).  So we need to update books.txt to point to cnx.org, where the book now lives. 

# Acceptance Criteria (required)
Change
`entrepreneurship           entrepreneurship                   55531492-8844-471a-a980-47a5a3ee7af8   col10082   content01.cnx.org     mixins/`

to 

`entrepreneurship           entrepreneurship                   d380510e-6145-4625-b19a-4fa68204b6b1   col29104   cnx.org     mixins/` 

# Test Plan

**Comment by Stackblocks** [comment]
Waiting for content refresh to staging.

**Comment by Stackblocks** [comment]
Associated PR #1927

**Comment by Stackblocks** [comment]
Showing as correct on the e.e. branch of easyvm5.cnx.org

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/81b7dcae-da20-402a-8e55-c236e69a6980)

**Comment by omehes** [comment]
@Stackblocks I was about to ask you about testing this :) I guess, no need for it now.
