### ISSUE TITLE
hs physics: fix Introduction page

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1901]
Because of inconsistant markup Introduction page in Hs Physics wasn't styled in all chapters. After content fix some changes in recipes and styles are needed.

**Comment by MartaSztuka** [comment]
@lwtchu   In chapter 9 it's still not fixed.
![Screenshot from 2020-02-19 12-16-34](https://user-images.githubusercontent.com/47241114/74831446-8b9d9380-5315-11ea-845a-28b4cfcea67b.png)
When headers for Section Key Terms will be on katalyst01? There are some missing.
![Screenshot from 2020-02-19 12-23-24](https://user-images.githubusercontent.com/47241114/74831391-70cb1f00-5315-11ea-9f0a-10d120553f7c.png)

**Comment by lwtchu** [comment]
@MartaSztuka updated now

**Comment by MartaSztuka** [comment]
tested![Screenshot from 2020-02-20 17-33-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bd6fb14e-8dad-48ba-aa40-ad04396111ad)
