### ISSUE TITLE
carnival theme: paragraph titles in examples and notes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1904]
![image.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/58605bd1-46d1-4860-be99-cd9384cf128a)

Strategy and Solution for (a): Can we change the paragraph `<title>` in `<examples>` and `<notes>` to be font-scale(0) so it won't be the same size as the title of the note/example?

Currently it is font-scale(1). Please change to font-scale(0).

Impacts hs physics and college physics (probably) ...and other titles? but should be theme wide wherever t here's a para title in an exmaple or note

**Comment by helenemccarron** [comment]
@lwtchu which book is the screenshot taken from?

**Comment by lwtchu** [comment]
@helenemccarron HS physics

**Comment by helenemccarron** [comment]
@lwtchu in that particular example, this is not a paragraph title but a nested with headers. Because we don't support rewriting headers of notes inside of notes, they are h3, when the parent note title itself is an h4. We would need a fix to the recipes to change those to h5 to make them HTML compliant. Is that desirable?

**Comment by helenemccarron** [comment]
Also, I can change the para titles (there's a component for those, maybe we should park that tomorrow?)

**Comment by lwtchu** [comment]
@helenemccarron let's park this :parking:

**Comment by lwtchu** [comment]
This is only occuring in HS Physics. The content within the notes are very very gnarly. and disgusting. We'll have to take a look later but I will prioritize this as super super low and close the card and open something for the CM board.
