### ISSUE TITLE
carnival theme: example and worked example note icon size

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1905]
![image.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/9f36063d-e918-4ba9-8057-80ee04bba6c6)

![Screen Shot 2020-02-12 at 3.06.42 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/cdb1df11-5b67-4dc1-927e-5509462080ef)

Since the words Worked Example and Example #.# are only on one line, can we reduce the size of the icon from h-grid(3) to h-grid(2)? 

Currently impacts any books with example or worked example. Of the 3 prioritized books: hs physics and college physics are impacted

**Comment by helenemccarron** [comment]
@lwtchu Does this apply to all Icon Notes? I would recommend we do not change the specs of the note types per specific note.

**Comment by lwtchu** [comment]
@helenemccarron good point. 

@andymuddimer if you're ok with letting this one go i can close the card

**Comment by andymuddimer** [comment]
@lwtchu  I agree with @helenemccarron we do not want to introduce variations in the specs - close the card
