### ISSUE TITLE
hs physics: lists inside exercises

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1906]
This might already exist, list inside an `<exercise>` is not indented.

![image.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/ffdc9496-e187-4573-bc58-bb88826469d5) 

the a. should start where the question stem starts. screenshot is from hs physics

I think this...is only in the exercises outside of the EOC

**Comment by ajluk** [comment]
This issue will be resolved in this PR: https://github.com/openstax/cnx-recipes/pull/1919

**Comment by MartaSztuka** [comment]
tested![Screenshot from 2020-02-20 18-23-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c77f787e-1dad-43f0-b7ed-de6e9ed48bcd)
