### ISSUE TITLE
carnival theme: bulleted lists poppin out of EOC section margins

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1907]
![image.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/9cb0c240-b4f6-4fac-9a70-a83625de3260)

I feel like I have already opened a card, but i can't find it. 

Those bullets should be within the margins and start where the other lines start. ... Screenshot is from HS Physics but I feel like I've seen it in other books.

**Comment by ajluk** [comment]
This issue will be resolved in this PR: https://github.com/openstax/cnx-recipes/pull/1919

**Comment by MartaSztuka** [comment]
tetsed
![Screenshot from 2020-02-20 17-09-07](https://user-images.githubusercontent.com/47241114/74954658-bd8d2380-5403-11ea-824c-e2700f5b862a.png)
