### ISSUE TITLE
hs physics: link to learning should be a condensed icon note

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1908]
![image.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/1e538c8c-77da-4e65-a2ac-c2f1457b1c03)

This should be the same specs as a condensed icon note and it is not. It's a bit large

**Comment by wilkus27** [comment]
@lwtchu I used information from this issue: https://github.com/openstax/cnx-recipes/issues/1696

![image](https://user-images.githubusercontent.com/40228854/74447196-4858a600-4e79-11ea-83cd-331f15a83787.png)

So that's why it is icon note.

**Comment by lwtchu** [comment]
oh just kidding. @wilkus27 i'll close this :joy: clearly i'm getting everything confused.

i apologize

**Comment by wilkus27** [comment]
Oh it's ok, nothing happend :relaxed:
