### ISSUE TITLE
hs physics: extra space in exercises between question stem para and list 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1909]
![image.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/6a9fc6ab-690d-4464-878c-72dea7d37f2a)

Remove space between question stem and answer choices. 

I think I've only seen this in hs physics.

**Comment by lwtchu** [comment]
![image](https://user-images.githubusercontent.com/11299125/74384636-5514c580-4db7-11ea-9592-8ecedb9c0b19.png)

Might be related. The first one with the extra space is a regular `<exercise>` and the second one is pulled from exercises.openstax.org and thus has no extra space


```<exercise><para id="fs-id1164564984935">A pitcher throws a baseball from the pitchers mound to home plate in 0.46 s. The distance is 18.4 m. What was the average speed of the baseball?</para>
<list xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" id="fs-id1164563503955" list-type="enumerated" number-style="lower-alpha"><item>40 m/s</item>
<item>- 40 m/s</item>
<item>0.03 m/s</item>
<item>8.5 m/s</item>
</list></problem>
</exercise>

<exercise id="fs-id1167066012376">
<label/>
<problem id="fs-id1167065654893">
<para id="fs-id1167065842882">
<link class="os-embed" url="#ost/api/ex/k12phys-ch02-ex027"/>
</para>
</problem>```

**Comment by ajluk** [comment]
This issue will be resolved in this PR: https://github.com/openstax/cnx-recipes/pull/1919

**Comment by MartaSztuka** [comment]
tested![Screenshot from 2020-02-20 17-37-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/981259b4-d490-47c2-a289-eae022765e11)
