### ISSUE TITLE
hs physics: key equations left align

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1911]
![image.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/868ef12f-b04d-44d3-9cb7-5ed1a5132eca)

Can we have the key equations be left aligned so they're not floating in the middle? ONLY the key equation table.

**Comment by ajluk** [comment]
Changes in TDS: 
**TableContainer** need to be replaced in the **EocKeyEquWithSectionLink** shape to **KeyEquationsTableContainer** with following properties:
        margin-bottom: table-v-grid(2),
        margin-left: 0,
        margin-right: 0,
 **TableData** properties need to be changed to:
padding: table-v-grid(1) table-h-grid(1)
**TableHeadCell** properties need to be changed as well to:
 padding: table-v-grid(1) table-h-grid(1),
I couldn't find it in the table so it is possible the whole shape (**EocKeyEquWithSectionLink**) needs to be added there (But if it is somewhere please ignore the rest). These are it's components:
**EocHeader**
            font-family: B5
            font-weight: bold,
            font-size: font-scale(4),
            line-height: line-height(4),
            text-transform: uppercase,
          margin-bottom: v-grid(1)
**EocSectionTitleLink**
        font-family: Muli,
        font-size: font-scale(3),
**KeyEquations**
       padding: 0
**UnnumberedUnstyledTable**
        //empty properties
**TableHead**
    //empty properties
**TableRow**
    //empty properties
**TableHeadCell**
  padding: table-v-grid(1) table-h-grid(1),
**TableBody**
   //empty properties
**TableData**
  padding: table-v-grid(1) table-h-grid(1),

**Comment by MartaSztuka** [comment]
tested![Screenshot from 2020-02-27 11-49-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e43e3d63-aed7-4a2f-999c-3de78a37f4fc)
