### ISSUE TITLE
CLEAN UP: Refactor Tables

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#1922]
# What happened?

In the process of resolving #1827 it was determined that we should separate border settings from table construction to allow for finer control of borders in tables. This is too much to do as part of the "get these books published" push, but should be done as part of a clean-up cycle.

<img width="1374" alt="2020-02-14_11-42-10" src="https://user-images.githubusercontent.com/12678235/74554385-0eda7600-4f1f-11ea-9f9f-6c7978da93a2.png">

**Comment by brittweinstein** [comment]
This was resolved with a short term fix. A longer term fix needs to be put into place.

**Comment by brittany-johnson** [comment]
Closing this issue in favor of https://github.com/openstax/cnx-recipes/issues/2224
