### ISSUE TITLE
Make a 'inspection' cli step in cnx-recipes

### ISSUE THREAD

**Issue by tomjw64** [openstax/cnx-recipes#1928]
In the interest of extending our metaphor until we can't anymore: We need to be able to inspect baked goods to see if they will pass the browser's "health codes".

We will check whether our xhtml-ish content will be reordered or modified in an undesirable way due to not being parse-able as html.

### Acceptance Criteria
- Inspection can be run with `docker-compose run --rm inspect [input/file/path]`
- Inspection reports back (perhaps with a diff) when the xml/xhtml file at the given path will be reordered by the browser in an undesired way

**Comment by Bkblodget** [comment]
We decided that we will address this work of web browser jitter (aka web browser re-ordering) in the validation epic [#860](https://app.zenhub.com/workspaces/content-engineering-tech-team-5af1f4cc12da5e6d74331b60/issues/openstax/cnx/860) - therefore I am closing this issue.
