### ISSUE TITLE
Enable "Top-Titled" class tag in Biology 2e & Concepts of Biology

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#1929]
# What happened?

the Tag: `class="top-titled"` has been added to all tables in Bio2e and Concepts of Biology that have a title. The tag needs to be enabled in recipes.

# Environment:

- **Book(s)**: Biology 2e, Concepts of Biology
- **URL/Server**: Production 
Bio2e: https://legacy.cnx.org/content/col24361/latest 
Concepts of Bio: https://legacy.cnx.org/content/col11487/latest
 **Location (page number, chapter/section)**: global, throughout
- **Browser**: Chrome

# Other Notes:

I've migrated chapter 34 of Bio2e into Katalyst01: https://katalyst01.cnx.org/content/m66616/latest/
And, I've migrated chapter 18 of Concepts of Bio into Katalyst01: https://katalyst01.cnx.org/content/m45549/latest/

**Comment by ajluk** [comment]
Changes in TDS:
In **FakeTitleTable** shape these component's properties color need to be addes as book specific for Biology and AP Biology:
**TableTitle** l. 249
color': B7
 **LastTableRowData** l. 257
border-bottom-color': B7

**Comment by MartaSztuka** [comment]
Biology 2e![Screenshot from 2020-02-27 17-24-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2f3549cd-b9b3-43b0-acfb-8aca491f14dd)
Concepts of ![Screenshot from 2020-02-27 17-32-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e6b90ddd-e106-4110-9048-1f4bf3cc24b1)Biology
