### ISSUE TITLE
High school physics: some composite pages are still going to page 1 or has no page number

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1932]
# What happened?
![image](https://user-images.githubusercontent.com/11299125/74853216-3c4e6780-5303-11ea-95ac-ee4f7fba8e51.png)
As you can see here Chapter Review and Test Prep are still going to page 1 in the ToC. 

# Reproducibility Details

This is in HS Physics.

**Comment by lwtchu** [comment]
@brittweinstein i put the top three priority book labels on this first. but i tihnk it's impacting all books?

**Comment by openstaxalina** [comment]
@lwtchu @brittweinstein I think that this is isolated to high school _Physics_.  Here are screenshots of the _College Physics_ and _Biology 2e_ PDFs generated Monday.  Are you observing this in PDFs generated more recently?

_College Physics_:
<img width="853" alt="Screen Shot 2020-02-19 at 10 37 52 AM" src="https://user-images.githubusercontent.com/7863733/74853761-fe057800-5303-11ea-9a67-bc81fc54e6c0.png">

_Biology 2e_:
<img width="862" alt="Screen Shot 2020-02-19 at 10 38 02 AM" src="https://user-images.githubusercontent.com/7863733/74853789-052c8600-5304-11ea-8589-0bcc6196890d.png">

**Comment by lwtchu** [comment]
@openstaxalina bah you are correct i'm looking at old pdfs.

**Comment by openstaxalina** [comment]
@lwtchu thank you -- I am going to delete some comments above just to clean up the issue to reduce confusion.

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-25 12-33-57](https://user-images.githubusercontent.com/47241114/75243954-26411b00-57cb-11ea-9de5-412280a6ac8e.png)
