### ISSUE TITLE
HS Physics EoC sections page numbers in Contents

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1935]
Sections of EoC have page numer 1.
![Screenshot from 2020-02-20 08-31-58](https://user-images.githubusercontent.com/47241114/74910808-a4608480-53bb-11ea-995d-62a177125e88.png)

**Comment by wilkus27** [comment]
Duplicate of https://github.com/openstax/cnx-recipes/issues/1932. Can be closed.
