### ISSUE TITLE
Page break shouldn't divide Check your Understanding

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1936]
Single line of text goes on next page.
![Screenshot from 2020-02-20 08-44-55](https://user-images.githubusercontent.com/47241114/74911765-990e5880-53bd-11ea-9eb5-78369c9d936d.png)
![Screenshot from 2020-02-20 08-48-21](https://user-images.githubusercontent.com/47241114/74911832-c529d980-53bd-11ea-866a-db9f9a37d22f.png)

**Comment by ajluk** [comment]
It will be resolved within this PR: https://github.com/openstax/cnx-recipes/pull/1934. cc @helenemccarron

**Comment by MartaSztuka** [comment]
There is still single line on next page
![Screenshot from 2020-02-25 10-49-14](https://user-images.githubusercontent.com/47241114/75235462-94321600-57bc-11ea-84a1-63b5940f15dc.png)
