### ISSUE TITLE
Test Chapter Outline in all books

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1938]
Problems with Chapter Outline cut on the right side and at the bottom (like in issue https://github.com/openstax/cnx-recipes/issues/1627) appear in all books using `ChapterIntroShape`. Within issue 1627 Hs Physics and Biology 2e will be tested. After PR https://github.com/openstax/cnx-recipes/pull/1931 will be merged all other books should be verified and if in some modules Chapter Outline is still cropped design of Introduction page should be changed to this one used in College Physics (`FullWidthChapterIntroShape`).

Books using `ChapterIntroShape`:
- Ap Biology
- Chemistry
- Microbiology
- U Physics

**Comment by wilkus27** [comment]
Issue for Chemistry: https://github.com/openstax/cnx-recipes/issues/1625

**Comment by MartaSztuka** [comment]
tested in AP Biology
![Screenshot from 2020-02-27 14-05-21](https://user-images.githubusercontent.com/47241114/75449836-fe3ded00-596d-11ea-8239-c4ca7b50599b.png)

**Comment by paulinaszczucinska** [comment]
@MartaSztuka please check all the chapter outlines and leave comments here, Larissa will make the decision what to do next.

**Comment by MartaSztuka** [comment]
Chemistry 2e
![Screenshot from 2020-03-18 17-16-27](https://user-images.githubusercontent.com/47241114/76983187-47fe6f80-693d-11ea-9783-bb3d416cca52.png)
Chemistry AF
![Screenshot from 2020-03-18 17-18-56](https://user-images.githubusercontent.com/47241114/76983307-7a0fd180-693d-11ea-892d-7d42e57e56c1.png)
Microbiology
![Screenshot from 2020-03-18 17-27-06](https://user-images.githubusercontent.com/47241114/76983810-4d0fee80-693e-11ea-8e64-11c6a59a651a.png)
Biology 2e
![Screenshot from 2020-03-18 18-08-34](https://user-images.githubusercontent.com/47241114/76987488-8d25a000-6943-11ea-8434-625d51cfe29d.png)
Concepts of Biology
![Screenshot from 2020-03-18 18-09-36](https://user-images.githubusercontent.com/47241114/76987589-b9412100-6943-11ea-8279-9cc404e9017f.png)
University Physics
![Screenshot from 2020-03-18 18-11-54](https://user-images.githubusercontent.com/47241114/76987768-fdccbc80-6943-11ea-83c2-684140b50d84.png)
![Screenshot from 2020-03-18 18-12-34](https://user-images.githubusercontent.com/47241114/76987834-205ed580-6944-11ea-84fb-33f72a289a4d.png)
![Screenshot from 2020-03-18 18-12-55](https://user-images.githubusercontent.com/47241114/76987843-22289900-6944-11ea-9f95-9657e19e7557.png)

**Comment by MartaSztuka** [comment]
@lwtchu

**Comment by lwtchu** [comment]
Let's move Microbiology and University Physics into full width chapter outline... @ajluk @wilkus27  - should I open separate issues?

I was able to make some content adjustments to make biology 2e work.

**Comment by lwtchu** [comment]
Concepts of biology should remain the same - i'll make the same content changes in concepts for bio since they should be sharing the same template

chemistry AF should also share the same as chemistry.

**Comment by ajluk** [comment]
@lwtchu there is separate one for Microbiology: https://github.com/openstax/cnx-recipes/issues/1628

**Comment by wilkus27** [comment]
@MartaSztuka I believe that all needed changes are done. Can you confirm that Chapter Outline looks good now?

**Comment by MartaSztuka** [comment]
Microbiology
![Screenshot from 2020-04-06 15-53-44](https://user-images.githubusercontent.com/47241114/78565908-cfdde800-781e-11ea-8de2-f54ae2bf389c.png)
Chemistry 2e
![Screenshot from 2020-04-06 15-54-19](https://user-images.githubusercontent.com/47241114/78566001-edab4d00-781e-11ea-9849-d7dbfc7eac5b.png)
Chemistry AF
![Screenshot from 2020-04-06 16-06-22](https://user-images.githubusercontent.com/47241114/78567185-960de100-7820-11ea-982c-b470c731297c.png)
University Physics
![Screenshot from 2020-04-06 16-13-53](https://user-images.githubusercontent.com/47241114/78567916-ab373f80-7821-11ea-8199-0c55bbebf930.png)
![Screenshot from 2020-04-06 16-14-35](https://user-images.githubusercontent.com/47241114/78567953-bab68880-7821-11ea-81a2-bfcc58eea100.png)
![Screenshot from 2020-04-06 16-14-57](https://user-images.githubusercontent.com/47241114/78568000-c7d37780-7821-11ea-91d5-5ccd5f6fea19.png)

**Comment by MartaSztuka** [comment]
AP biology![Screenshot from 2020-04-07 11-45-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/71a9d2a2-da5d-46da-87ca-1e570a5c30fb)
Concepts of biology![Screenshot from 2020-04-07 12-36-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9ff90df4-4a1f-4644-8a9d-8fee264b573c)
