### ISSUE TITLE
CLEAN UP: refactor eoc components/shapes to be more reusable

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1942]
There are too many uniquely named components, could we consolidate those into fewer shapes and components.

**Comment by wilkus27** [comment]
There are four types of EOC modules:
- Key Terms
- Key Equations
- Summary
- Exercises

For each of this type we need separate shape.

There are two types of differences which appear in different books for each of these modules. 

1. Module has section links or not.
2. Module is composite page and has h2 header or module is compound composite page and has h3 header. (h2 and h3 are styled differently)

So what is the best solution in this case?

a) to have one shape, e.g for Exercises, in which components for h2, h3 and section links are added and all their properties are hard coded, even those elements don't appear in all Exercises modules?

b) to create one shape with components for h2, h3 and section links, but their properties are OPTIONAL and defined in settings.scss file if element exists?

c) to create separate shape for each case (e.g Exercises with links and h2, Exercises with links and h3, Exercises without links and with h2 etc.)?

**Comment by ajluk** [comment]
The problem with column gap getting tighter described in this issue: https://github.com/openstax/cnx-recipes/issues/1978 is related to EoC Exercise cleaning issue included here. The thing that causing the problem is display: table and display: table-caption properties set for Problem Wrapper and Problem Container. There is a separate issue related to this, created by Natalia (#1870) with proposal changes to exercises.

**Comment by helenemccarron** [comment]
A lot of the initial work was done as part of #2074. Some more clean up is necessary for all the books.

**Comment by brittweinstein** [comment]
We're keeping this in the Icebox to double-check after all shapes/components work is done that it is resolved.

**Comment by wilkus27** [comment]
Will be resolved after merge work from https://github.com/openstax/cnx-recipes/issues/2188.

**Comment by wilkus27** [comment]
Tested here https://github.com/openstax/cnx-recipes/issues/2188
