### ISSUE TITLE
Enable "Top-titled" class in AP Bio

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#1943]
# What happened?
the Tag: `class="top-titled"` has been added to all tables in AP Bio that have a title. The tag needs to be enabled in recipes.

# Environment:

- **Book(s)**: AP Biology
- **URL/Server**: Production: https://legacy.cnx.org/content/m62813/latest/
- **Browser**: Chrome

# Additional notes

I've migrated chapter 12 into Katalyst01: https://legacy-katalyst01.cnx.org/content/m62813/latest/

**Comment by MartaSztuka** [comment]
tested![Screenshot from 2020-02-27 17-08-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fea8c662-f0fe-47be-bac4-52e79ce9d70c)
