### ISSUE TITLE
biology: appendix title color

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#1944]
![image](https://user-images.githubusercontent.com/40228854/75145015-77cca580-56f8-11ea-9f2a-2e74e816d2ff.png)

Appendices titles in biology have wrong color. Now is set `#3172B6` it should be `#0074BC`.

**Comment by wilkus27** [comment]
## Changes to provide in Theme Design Specs

### Shape: `AppendixShape`

_Component:_ `MainText`
_Changed Properties:_ 
```
color: #0074BC
```
![image](https://user-images.githubusercontent.com/40228854/75251131-475d3800-57da-11ea-9dc1-9b8c42a662d6.png)

_Component:_ `SubTitle`
_Changed Properties:_ 
```
color: #0074BC
```
![image](https://user-images.githubusercontent.com/40228854/75251175-61971600-57da-11ea-91fe-6a4d44f54d26.png)

_Component:_ `SubSubTitle`
_Changed Properties:_ 
```
color: #0074BC
```
![image](https://user-images.githubusercontent.com/40228854/75251209-6fe53200-57da-11ea-840c-8152a07ea9b5.png)

**Comment by MartaSztuka** [comment]
tested
Biology2e ![Screenshot from 2020-02-27 13-22-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fad438a9-aa5f-464e-b887-f724ba0b11b0)
APBiology ![Screenshot from 2020-02-27 13-31-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3597590e-aa2a-4fa3-a012-9d87986dfc0f)
Concepts of Biology![Screenshot from 2020-02-27 13-38-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/72d13912-7f69-4642-97a7-53004fe1f511)
