### ISSUE TITLE
Symmetry Feedback: in TOC, do not allow unit number/title to break from the chapter 

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1948]
# Scenario

Chapter titles can break.

Unit titles should not be allowed to break.

Here is an instance where it breaks after the unit (note: the word "Unit" and the number will be present with latest code, so ignore that problem here):
![Screen Shot 2020-02-24 at 1 10 38 PM](https://user-images.githubusercontent.com/7863733/75182947-13651280-5707-11ea-8c2e-c5312c0d8ffa.png)

# Acceptance Criteria (required)
- [ ] chapter titles are allowed to break
- [ ] unit titles are not allowed to break

# Test Plan

**Comment by lwtchu** [comment]
The only change I would recommend here is do not orphan the UNIT TITLE ONLY. 

So no break after unit title. 
It's okay for it to break after the chapter title.

**Comment by ajluk** [comment]
This issue has been already resolved by page breaks added by BrittanyJ. Now it's not uccuring anymore: 
![image](https://user-images.githubusercontent.com/55203598/75445641-20337180-5966-11ea-80c0-523e9be2e6e1.png)

**Comment by lwtchu** [comment]
@ajluk can we make sure they're allowed to break at the chapter title level

**Comment by openstaxalina** [comment]
@brittany-johnson is making a change to allow chapter titles to break.
We still want her fix so that unit titles do not break.

**Comment by lwtchu** [comment]
We'll reference this in #861
