### ISSUE TITLE
Symmetry Feedback: Reduce Page Count: Tighter Unit and Chapter Heads Spacing?

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1949]
# Scenario

See below.  Also, could the title extend further right so as not to line-break, or will this cause problems?  (We may have to sacrifice _some_ design in order to save vertical space.)

![Screen Shot 2020-02-24 at 1 13 08 PM](https://user-images.githubusercontent.com/7863733/75183119-6b9c1480-5707-11ea-804e-51becb8b9b84.png)

![Screen Shot 2020-02-24 at 1 14 54 PM](https://user-images.githubusercontent.com/7863733/75183221-b158dd00-5707-11ea-9f1b-12d8d77a7235.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
I'm not sure this is possible with the way the font scale is set up? Can @helenemccarron confirm?

**Comment by Stackblocks** [comment]
I'll take a look at this to see how the spacing is built out. If we have any working space with the way the spacing and scales are set up i'll adjust it.

**Comment by MartaSztuka** [comment]
**Biology 2e**
![Screenshot from 2020-03-24 17-31-05](https://user-images.githubusercontent.com/47241114/77451737-5f35d500-6df5-11ea-95b3-71c5b71c0422.png)
