### ISSUE TITLE
Symmetry Feedback: Consider Key Terms Re-design

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1951]
# Scenario

![Screen Shot 2020-02-24 at 1 28 29 PM](https://user-images.githubusercontent.com/7863733/75184176-96876800-5709-11ea-893c-88b789267086.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
Let's try the two column option. 

![Screen Shot 2020-02-25 at 2.26.02 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/9207c8b5-f2b9-46f6-9eb0-99ec3385f680)

- Reduce spacing between key term and definition (I think it is currently at 5 spaces. Can we try 3? or is this a h-grid situation?)

**Comment by lwtchu** [comment]
Let's try this for all titles where there's a glossary (key term + definition)

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-03-02 at 2 34 50 PM](https://user-images.githubusercontent.com/24909007/75715432-04480c80-5c93-11ea-8a71-af74213cd945.png)

**Comment by MartaSztuka** [comment]
Tested!
![Screenshot from 2020-03-05 10-52-18](https://user-images.githubusercontent.com/47241114/75969559-6bea9b80-5ecf-11ea-93d7-7217b72296f7.png)
![Screenshot from 2020-03-05 10-56-32](https://user-images.githubusercontent.com/47241114/75971276-d56ba980-5ed1-11ea-9883-a70ac13a201b.png)

**Comment by openstaxalina** [comment]
@brittany-johnson just to confirm - was this done at the theme level or by book?

**Comment by brittany-johnson** [comment]
This was done at the theme level so it affects all carnival books 🤠
