### ISSUE TITLE
Symmetry Feedback: Chapter Outline trim 

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1952]
# Scenario

I'm collecting all this in one place.  Have asked XanEdu what their safety margin is.  **Please look at chs. 7 and 8 especially** -- there seems to be a problem when you want the Chapter Outline to go to the second page of the chapter, but the first non-intro module has already started on that page.  We may be able to fix it in code to allow it be on the first non-intro module page, but want to make sure that's what we want.

![Screen Shot 2020-02-24 at 1 31 09 PM](https://user-images.githubusercontent.com/7863733/75184408-f0882d80-5709-11ea-8266-608cb34d9005.png)

![Screen Shot 2020-02-24 at 1 30 43 PM](https://user-images.githubusercontent.com/7863733/75184348-e108e480-5709-11ea-8428-14ada4e81ef5.png)

![Screen Shot 2020-02-24 at 1 38 31 PM](https://user-images.githubusercontent.com/7863733/75185012-fdf1e780-570a-11ea-93d4-cc17e4ef13fa.png)

![Screen Shot 2020-02-24 at 1 39 05 PM](https://user-images.githubusercontent.com/7863733/75185041-0e09c700-570b-11ea-8310-eba7e0050b50.png)

![Screen Shot 2020-02-24 at 1 42 38 PM](https://user-images.githubusercontent.com/7863733/75185399-a2742980-570b-11ea-81bf-9fb2be2906b2.png)

![Screen Shot 2020-02-24 at 1 44 44 PM](https://user-images.githubusercontent.com/7863733/75185516-dc453000-570b-11ea-8146-e29cc0566525.png)

![Screen Shot 2020-02-24 at 4 12 37 PM](https://user-images.githubusercontent.com/7863733/75195908-8038d680-5720-11ea-9048-f4a180ff4216.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by wilkus27** [comment]
Problem with Chapter Outline will be resolved by https://github.com/openstax/cnx-recipes/issues/1627. PR with changes will be merged today to e.e branch. So we need an issue for thin ribbons in EOC.

**Comment by lwtchu** [comment]
Let's wait for Xanedu to get back with us with the variance. I have a feeling Symmetry is assuming this includes the bleed? Or they're super paranoid.

**Comment by lwtchu** [comment]
Confirmed with Symmetry they need 0.25in of clearance. 

I found a few instances in Biology where a word or a couple letters trickle out. It's mostly okay though! And the new design is great. 

Is there a way to make sure the words don't bleed over? 

<img width="981" alt="Screen Shot 2020-02-28 at 3 42 16 PM" src="https://user-images.githubusercontent.com/11299125/75591962-b6d75f80-5a46-11ea-9609-3adfb86b467c.png">
<img width="966" alt="Screen Shot 2020-02-28 at 3 42 25 PM" src="https://user-images.githubusercontent.com/11299125/75591977-bc34aa00-5a46-11ea-96f1-1bf89bd0adbf.png">
<img width="992" alt="Screen Shot 2020-02-28 at 3 55 09 PM" src="https://user-images.githubusercontent.com/11299125/75591985-c0f95e00-5a46-11ea-92df-26578e89a28d.png">

**Comment by wilkus27** [comment]
@lwtchu I doubled paddings in FullBleedsPaddings function, so now we should have `1.5rem + 1.2rem` visible padding and `1.2rem` padding out of the page.

This is view before changes:

![image](https://user-images.githubusercontent.com/40228854/75774864-2acc7d00-5d51-11ea-9752-05c0038697d5.png)

And after:

![image](https://user-images.githubusercontent.com/40228854/75774898-3b7cf300-5d51-11ea-8261-c21d0c3c436e.png)

**Comment by lwtchu** [comment]
@wilkus27 i can't tell if there's a 0.25 bleed - do you mind proving a screenshot with the ruler turned on in the PDF viewer?

**Comment by lwtchu** [comment]
![Screen Shot 2020-03-04 at 10 00 17 AM](https://user-images.githubusercontent.com/11299125/75897935-f911ef80-5dfe-11ea-9659-04bdbc7e9fc1.png)
Looks good thank you @wilkus27 !

**Comment by openstaxalina** [comment]
@wilkus27 I wanted to confirm that this change was made theme-wide?

If so, could @MartaSztuka verify that the issue in the below screenshot is resolved in (high school) _Physics_?

![Screen Shot 2020-03-05 at 10 37 18 AM](https://user-images.githubusercontent.com/7863733/76003281-773cc780-5ecd-11ea-9419-83f46653a3af.png)

cc @lwtchu

**Comment by wilkus27** [comment]
@openstaxalina Yes, I made a change for all books. It should be resolved by https://github.com/openstax/cnx-recipes/pull/2004.

**Comment by wilkus27** [comment]
## Changes to provide to Theme Design Specs

### Shape: `ChapterIntroShape`

_Component:_ `Outline`
_Changed properties:_
```
width: 2.15in;
```
_Component:_ `OutlineTitle`
_Changed properties:_
```
padding: 0 3.9rem 0.5rem 0;
```
_Component:_ `ChapterOutlineObjective`
_Changed properties:_
```
padding-right: 3.9rem;
```

### Page: eoc:left
_left-middle, top-left-corner, bottom-left-corner, left-bottom, left-top:_
```
padding: 2.4rem 2.4rem 2.4rem 0;
```
### Page: eoc:right
_right-middle, top-right-corner, bottom-right-corner, right-bottom, right-top:_
```
padding: 2.4rem 2.4rem 2.4rem 0;
```
### Page: appendix:left
_left-middle, top-left-corner, bottom-left-corner, left-bottom, left-top:_
```
padding: 2.4rem 2.4rem 2.4rem 0;
```
### Page: appendix:right
_right-middle, top-right-corner, bottom-right-corner, right-bottom, right-top:_
```
padding: 2.4rem 2.4rem 2.4rem 0;
```
### Page: eob:left
_left-middle, top-left-corner, bottom-left-corner, left-bottom, left-top:_
```
padding: 2.4rem 2.4rem 2.4rem 0;
```
### Page: eob:right
_right-middle, top-right-corner, bottom-right-corner, right-bottom, right-top:_
```
padding: 2.4rem 2.4rem 2.4rem 0;
```

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-03-09 11-20-29](https://user-images.githubusercontent.com/47241114/76204124-11677d00-61f8-11ea-932f-39499cffc28d.png)
![Screenshot from 2020-03-09 11-19-15](https://user-images.githubusercontent.com/47241114/76204129-12001380-61f8-11ea-99f1-a7916287ff29.png)
