### ISSUE TITLE
Symmetry Feedback: Reduce Page Count: Reduce Space before Each EOC Section

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1953]
# Scenario

I would like to make a change here to reduce page count.  Please provide specifications.
![Screen Shot 2020-02-24 at 1 32 17 PM](https://user-images.githubusercontent.com/7863733/75184573-380eb980-570a-11ea-9af7-511c30642dd9.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
can we change it from `margin-bottom: v-grid(4)` to `margin-bottom: v-grid(2)`?

**Comment by wilkus27** [comment]
@lwtchu It's already set to v-grid(2):

![image](https://user-images.githubusercontent.com/40228854/75444162-3ab81b80-5963-11ea-815c-d3fec9ff60f2.png)
