### ISSUE TITLE
Symmetry Feedback: Reduce Page Count: Reduce Space between Question Stem and Distractors

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1954]
# Scenario

I would like to make a change here to reduce page count. Please provide specifications.
![Screen Shot 2020-02-24 at 1 34 07 PM](https://user-images.githubusercontent.com/7863733/75184703-6be9df00-570a-11ea-8847-c3cba75a9a96.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
I think there was a previous issue to address this, but I can't find it. Can someone check if this is still an issue for this title?

**Comment by wilkus27** [comment]
@lwtchu It's already resolved:

![image](https://user-images.githubusercontent.com/40228854/75440019-36880000-595b-11ea-878e-1244d27d0730.png)
