### ISSUE TITLE
Symmetry Review: When Page Ends with Caption, Caption Runs into Trim?

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1957]
# Scenario

I'm not 100% positive that's the pattern, but it seems to be what happened here:
![Screen Shot 2020-02-24 at 4 10 35 PM](https://user-images.githubusercontent.com/7863733/75195810-48ca2a00-5720-11ea-9353-42a054c8c624.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by brittany-johnson** [comment]
<img width="1652" alt="Screen Shot 2020-03-06 at 10 18 06 AM" src="https://user-images.githubusercontent.com/24909007/76101312-d82ed300-5f93-11ea-8a9b-23ddbbb0bf31.png">

This should be resolved with https://github.com/openstax/cnx-recipes/pull/2010

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-03-09 11-08-53](https://user-images.githubusercontent.com/47241114/76203148-715d2400-61f6-11ea-8ed8-5223475f2362.png)
