### ISSUE TITLE
Create Style of AP Physics

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#1961]
AP Physics template should be identical to college physics (named physics in the styles directory)

During development, I had to make recipe and style changes that affect other books. 
Because the changes are all isolated to the chapter introduction section, I think we can test them now instead of putting them behind a release flag. 

For testing: 

- [x] Compare 3 chapters to the old AP Physics PDF 
- [x] Compare 3 chapters to the Physics PDF 
- [x] Check chapter intro page in **each carnival book** to make sure there are no weird page breaks 
- [x] Check chapter intro page in **ap-physics, college-physics, and ~~sociology~~** to ensure chapter outline is displaying properly 

NOTE: check sociology before re-locking recipes or when sociology is added to baked styles. @brittany-johnson will create a card for this later

**Comment by brittweinstein** [comment]
@lwtchu could you tell us what the exact difference btwn HS Phys and AP Phys is?

**Comment by lwtchu** [comment]
HS has high school content that needs to be suppressed and completely different mark up (examples are marked up like notes in HS Physics). They are in no way closely related

AP physics follows college physics almost exactly and just adds one EOC section. so same style. Different recipe to accomodate one extra EOC section.

**Comment by openstaxalina** [comment]
The extra EOC section is called "Test Prep for AP® Courses".

@brittany-johnson @Stackblocks does this answer your query from earlier today?

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-05-08 at 1 46 10 PM](https://user-images.githubusercontent.com/24909007/81438388-504f7b80-9132-11ea-85e5-51e7cf446aa3.png)

**Comment by MartaSztuka** [comment]
@brittany-johnson I've compered AP Physics to College Physics
1. Note PHET isn't styled.
![Screenshot from 2020-05-13 16-46-36](https://user-images.githubusercontent.com/47241114/81827981-96914a00-9539-11ea-86e7-609057a61da3.png)
Here is how it looks in College Physics:
![Screenshot from 2020-05-13 16-46-46](https://user-images.githubusercontent.com/47241114/81827975-95601d00-9539-11ea-8e6b-5076c8f31ddc.png)
2. Bullet points with Learning Objectives are moved 
AP Physics: 
![Screenshot from 2020-05-13 17-01-27](https://user-images.githubusercontent.com/47241114/81829669-6fd41300-953b-11ea-93d9-3685952250f4.png)
 ![Screenshot from 2020-05-13 16-50-40](https://user-images.githubusercontent.com/47241114/81828483-1d462700-953a-11ea-91eb-d9f33cc2f4a7.png)
College Physics: ![Screenshot from 2020-05-13 16-52-29](https://user-images.githubusercontent.com/47241114/81828648-4cf52f00-953a-11ea-9fc0-31c85a2fa005.png)
3. Figures are bigger.
![Screenshot from 2020-05-13 16-56-33](https://user-images.githubusercontent.com/47241114/81828991-b8d79780-953a-11ea-9cf0-69215ccbcfaf.png)
![Screenshot from 2020-05-13 16-56-48](https://user-images.githubusercontent.com/47241114/81829021-c2f99600-953a-11ea-94b7-7b9913b1790f.png)
4. Symbols![Screenshot from 2020-05-13 17-24-05](https://user-images.githubusercontent.com/47241114/81832331-a95a4d80-953e-11ea-8ea8-4e0868c2e8b1.png)
5. Answer Key is unstyled
![Screenshot from 2020-05-13 17-33-10](https://user-images.githubusercontent.com/47241114/81833337-de1ad480-953f-11ea-892a-5ab03e8dcdfc.png)
6. Footnotes shouldn't be here
![Screenshot from 2020-05-13 17-26-37](https://user-images.githubusercontent.com/47241114/81832577-fa6a4180-953e-11ea-94cf-8f339a51f6c0.png)
7. Cropped figure without caption in Preface 
![Screenshot from 2020-05-13 17-33-54](https://user-images.githubusercontent.com/47241114/81833404-f1c63b00-953f-11ea-8ec6-faee78423c66.png)

Test Prep for AP Courses looks ok.
![Screenshot from 2020-05-13 17-10-25](https://user-images.githubusercontent.com/47241114/81830753-c4c45900-953c-11ea-81fc-4c014a3b3d8c.png)

**Comment by lwtchu** [comment]
For the first one - we'll have to change the class. 
And for the images - as long as they're displaying correctly with the right PPI, we can make the changes in content.

**Comment by brittany-johnson** [comment]
Making a comment with a formatted todo list 

- [ ] Note PHET isn't styled.
- [ ] Bullet points with Learning Objectives are moved
- [ ] Figures are bigger
- [ ] Symbols
- [ ] Answer Key is unstyled
- [ ] fotnotes shouldn't be here
- [ ] Cropped figure without caption in Preface

**Comment by brittany-johnson** [comment]
@lwtchu Hello! We need the `[data-type="abstract]` added to the content for the Learning Objectives

**Comment by lwtchu** [comment]
We need to talk about this when we're back from vacations.

Notes: 
Basically College Physics and AP Physics have learning objectives marked up completely different. In my personal opinion, AP Physics is more correct as the way College Physics is marked up is extremely clunky as it lives in the metadata tags of the module and should be in its own section within the content. 

Need to discuss with BrittanyJ to figure out best next steps.

**Comment by brittweinstein** [comment]
Per Larissa, BrittanyJ will  support both until we are able to move the college physics stuff out of the abstract

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-06-09 at 1 42 21 PM](https://user-images.githubusercontent.com/24909007/84187038-13d7ae00-aa57-11ea-9ffd-306d99014a89.png)

**Comment by brittweinstein** [comment]
The CMs will handle the index spacing in Production content which should resolve the final issue. Then BrittJ will submit her PR for review!

**Comment by openstaxalina** [comment]
(CM work card: https://github.com/openstax/content-managers/issues/1742)

**Comment by brittweinstein** [comment]
@brittany-johnson will submit this PR for code review.

**Comment by brittweinstein** [comment]
@Stackblocks will generate content and share the documentation we share with vendors with @meeragovindaraju for testing.

**Comment by meeragovindaraju** [comment]
Here is a list of issues (maybe) I found while testing https://docs.google.com/document/d/1CiawcDfC7_wJ037_bPlur_OS8WNVi9ghEEiEaXWNpdY/edit

**Comment by meeragovindaraju** [comment]
Chapter outline in AP Physics
![Screen Shot 2020-07-21 at 1 21 36 PM](https://user-images.githubusercontent.com/33066187/88092848-c3279a80-cb56-11ea-9a4d-b380bc89fe26.png)

Chapter outline in College physics
![Screen Shot 2020-07-21 at 1 21 46 PM](https://user-images.githubusercontent.com/33066187/88092884-d2a6e380-cb56-11ea-992e-3f474df7f59a.png)

**Comment by brittweinstein** [comment]
@meeragovindaraju opened up issues for bugs found. This wraps up AP Physics at the 80% mark. When the bug cards are all addressed for AP Physics, we will call that title "done" for Carnival.
