### ISSUE TITLE
Enable all feature flags for University Physics

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1965]
All feature flags need to be enabled for University Physics.

**Comment by ajluk** [comment]
Enabled flags:

- chapter-page-class
- appendix-has-numbered-examples
- increment-section-counter-for-lo
- trash-abstract-in-preface
- titles-in-examples
- module-titled-notes
- use-title-nodes
- goodbye-warnings
- table-move-fake-title
- several-composite-chapters
- subtitled-examples

**Comment by MartaSztuka** [comment]
- [ ] chapter-page-class
- [ ] appendix-has-numbered-examples
- [ ] increment-section-counter-for-lo
- [ ] trash-abstract-in-preface
- [ ] titles-in-examples
- [ ] module-titled-notes
- [ ] use-title-nodes
- [ ] goodbye-warnings
- [ ] table-move-fake-title
- [ ] several-composite-chapters
- [ ] subtitled-examples

**Comment by ajluk** [comment]
Now the Example subtitle looks like this: 
![image](https://user-images.githubusercontent.com/55203598/75567989-c197f180-5a52-11ea-82f8-0a6e176d2135.png)

**Comment by MartaSztuka** [comment]
Examples subtitles looks ok.
![Screenshot from 2020-03-03 13-13-02](https://user-images.githubusercontent.com/47241114/75774741-da551f80-5d50-11ea-8038-82837912c24c.png)
