### ISSUE TITLE
CLEAN UP: rename chapter outlines shapes and components

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1973]
Rename the chapter outlines to full-width-chapter-outline and margin-chapter-outline.

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/81199656-936deb00-8f88-11ea-82ef-0c8a4f18cdab.png)

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/81210361-6412aa80-8f97-11ea-93fc-42b4eebdbf4f.png)

**Comment by Stackblocks** [comment]
@MartaSztuka Testing for this should mainly consist of making sure that the Chapter Outlines haven't had any surprise chanes.

**Comment by MartaSztuka** [comment]
@Stackblocks Chapter header has lost its style.
Chemistry 2e
![Screenshot from 2020-05-12 10-29-52](https://user-images.githubusercontent.com/47241114/81662113-64022700-943d-11ea-830d-34d6570ae988.png)

**Comment by brittany-johnson** [comment]
@MartaSztuka This issue is due to the structure of chapter titles, appendix titles, and unit titles changing in https://github.com/openstax/cnx-recipes/issues/2244

I've opened up a separate issue to handle it: https://github.com/openstax/cnx-recipes/issues/2301

**Comment by MartaSztuka** [comment]
Chemistry 2e
![Screenshot from 2020-05-13 11-57-17](https://user-images.githubusercontent.com/47241114/81799073-1bb43900-9511-11ea-88d8-60b8b1bb7a59.png)
Chemistry AF
![Screenshot from 2020-05-13 11-59-58](https://user-images.githubusercontent.com/47241114/81799211-4ef6c800-9511-11ea-81a0-32541638cdbc.png)
Anatomy
![Screenshot from 2020-05-13 12-13-34](https://user-images.githubusercontent.com/47241114/81800493-3687ad00-9513-11ea-87dc-0e20699f113f.png)
Biology 2e
![Screenshot from 2020-05-13 12-16-30](https://user-images.githubusercontent.com/47241114/81800748-9c743480-9513-11ea-9a38-b3a00c0735a3.png)
AP Biology
![Screenshot from 2020-05-13 12-41-01](https://user-images.githubusercontent.com/47241114/81802825-0e9a4880-9517-11ea-92ac-e98787614e3e.png)
Concepts of Biology
![Screenshot from 2020-05-13 12-48-22](https://user-images.githubusercontent.com/47241114/81803495-0ee71380-9518-11ea-951e-0d83b1393aae.png)
Microbiology
![Screenshot from 2020-05-13 12-50-31](https://user-images.githubusercontent.com/47241114/81803701-5cfc1700-9518-11ea-8c50-cd611b13f773.png)
HS Physics
![Screenshot from 2020-05-13 12-52-21](https://user-images.githubusercontent.com/47241114/81803924-9e8cc200-9518-11ea-9ab7-b39493b341b6.png)
College Physics
![Screenshot from 2020-05-13 12-56-26](https://user-images.githubusercontent.com/47241114/81804306-2ffc3400-9519-11ea-9fbf-5395e130d344.png)
University Physics 1
![Screenshot from 2020-05-13 12-57-30](https://user-images.githubusercontent.com/47241114/81804422-5a4df180-9519-11ea-880a-6b221b3c50a5.png)
University Physics 2
![Screenshot from 2020-05-13 13-16-14](https://user-images.githubusercontent.com/47241114/81805893-f842bb80-951b-11ea-865a-01efd679a837.png)
University Physics 3
![Screenshot from 2020-05-13 13-17-29](https://user-images.githubusercontent.com/47241114/81805996-1f998880-951c-11ea-97e4-c83c5ea09265.png)
