### ISSUE TITLE
Symmetry Feedback: Ribbon width

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1977]
# What happened?
![Screen Shot 2020-02-24 at 1 30 43 PM](https://user-images.githubusercontent.com/7863733/75184348-e108e480-5709-11ea-8428-14ada4e81ef5.png)

Symmetry marked the ribbon being potentially too thin. Can we increase it to 0.5 in?

<img width="754" alt="Screen Shot 2020-02-28 at 4 29 31 PM" src="https://user-images.githubusercontent.com/11299125/75592362-bd1a0b80-5a47-11ea-8160-d88d7525bf7f.png">

Related to #1952

**Comment by lwtchu** [comment]
Andy says: looks gud

**Comment by openstaxalina** [comment]
@brittweinstein @paulinaszczucinska this is ready for someone to work on.  Per @lwtchu , we are increasing ribbon size to 0.5 in.

**Comment by wilkus27** [comment]
### Changes to provide to Theme Design Specs

#### Page: `eoc:left`

_left-middle_, _top-left-corner_, _bottom-left-corner_, _left-bottom_, _left-top_:
```
border-left: 0.65in solid #0074BC;
```

#### Page: `eoc:right`

_right-middle_, _top-right-corner_, _bottom-right-corner_, _right-bottom_, _right-top_:
```
border-right: 0.65in solid #0074BC;
```

#### Page: `appendix:left`

_left-middle_, _top-left-corner_, _bottom-left-corner_, _left-bottom_, _left-top_:
```
border-left: 0.65in solid #0074BC;
```

#### Page: `appendix:right`

_right-middle_, _top-right-corner_, _bottom-right-corner_, _right-bottom_, _right-top_:
```
border-right: 0.65in solid #0074BC;
```

#### Page: `eob:left`

_left-middle_, _top-left-corner_, _bottom-left-corner_, _left-bottom_, _left-top_:
```
border-left: 0.65in solid #0074BC;
```

#### Page: `eob:right`

_right-middle_, _top-right-corner_, _bottom-right-corner_, _right-bottom_, _right-top_:
```
border-right: 0.65in solid #0074BC;
```

**Comment by MartaSztuka** [comment]
tested![Screenshot from 2020-03-06 10-20-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/761bdb6f-c47e-4637-95c8-fa0e8e400414)![Screenshot from 2020-03-06 10-37-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8b30a6c3-bcb3-4251-8637-c5edc32d4ab8)![Screenshot from 2020-03-06 10-47-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3fd22d59-bdb6-4df3-ad34-33ae8193eefa)
