### ISSUE TITLE
Symmetry Feedback: Blue ribbon in chapter opener should run flush with text?

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1979]
# Scenario

I'm guessing this is happening due to image size differences.  Are we leaving this as-is or fixing the images?  (I don't have a preference.)  Or is this a bug?

![Screen Shot 2020-02-28 at 5 40 17 PM](https://user-images.githubusercontent.com/7863733/75595348-94970f00-5a51-11ea-80e6-ac7debe7a2a9.png)

![Screen Shot 2020-03-02 at 3 19 03 PM](https://user-images.githubusercontent.com/7863733/75718787-2d6b9b80-5c99-11ea-8d5a-66eeaa50196f.png)

![Screen Shot 2020-03-02 at 3 25 03 PM](https://user-images.githubusercontent.com/7863733/75719249-06619980-5c9a-11ea-9fcd-7d99c15464f0.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
This isn't an issue.
