### ISSUE TITLE
Symmetry Feedback: Equation Numbers in Top Margin?

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1980]
# Scenario

I think this is fine, but wanted to verify:

![Screen Shot 2020-02-28 at 5 42 47 PM](https://user-images.githubusercontent.com/7863733/75595395-d0ca6f80-5a51-11ea-8e61-4b218dbf4210.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
This is fine.
