### ISSUE TITLE
Symmetry Feedback: Punctuation after math (?) can wrap to next line

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1981]
# Scenario

I'm guessing this is because there is math markup immediately followed by punctuation.  Can anything be done in these instances?

From 2.5:
![Screen Shot 2020-02-28 at 5 45 19 PM](https://user-images.githubusercontent.com/7863733/75595482-3d456e80-5a52-11ea-9623-a0a6abb9c878.png)

From 2.7:
![Screen Shot 2020-02-28 at 5 48 14 PM](https://user-images.githubusercontent.com/7863733/75595580-97deca80-5a52-11ea-9696-07ec4781fa84.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by Stackblocks** [comment]
# In the markup: 

## 2.5
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3da1eaf7-820c-4d8e-8c6e-63f2d8c55956)
## 2.7
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6adf21d3-0cd6-430a-aa2d-b6527b72ad86)

**Comment by brittweinstein** [comment]
@openstaxalina will investigate and track down an instance of this happening at the end of a line in the PDF.

**Comment by openstaxalina** [comment]
On today's call, we discussed how this issue had been handled in oer.exports. Perhaps we can implement a similar solution in baked PDF.  

I found an example in oer.exports of math at the end of the line, followed by punctuation, where the punctuation is **not** breaking from the math:

![oerexportsCollegePhysicsmath](https://user-images.githubusercontent.com/7863733/77443404-0a746900-6db9-11ea-8463-2fba116935c0.png)

Because of the differences in font and styles, in the baked PDF, that content does not occur at the end of a line, so it's not a perfect comparison. But I believe the screenshot above shows that there should be a way to handle inline math, followed by punctuation at the end of a line.

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-04-16 at 3 55 10 PM](https://user-images.githubusercontent.com/24909007/79505980-d9bfd200-7ffa-11ea-8c22-cd78cc6c4e8e.png)
![Screen Shot 2020-04-16 at 3 54 25 PM](https://user-images.githubusercontent.com/24909007/79505987-db899580-7ffa-11ea-9ceb-c65765309eec.png)

**Comment by brittany-johnson** [comment]
Recipe updates doc has been updated capturing the changes in this issue: https://docs.google.com/document/d/14E1Bgs-lK4kdmaPqQyEK2b82WAR9NtFwzElaJgPZhpQ/edit#

**Comment by MartaSztuka** [comment]
College Physics
![Screenshot from 2020-04-21 10-22-19](https://user-images.githubusercontent.com/47241114/79843131-1bb19500-83ba-11ea-829b-55ac3604fc90.png)
![Screenshot from 2020-04-21 10-21-49](https://user-images.githubusercontent.com/47241114/79843133-1ce2c200-83ba-11ea-9053-b8cf45c3e987.png)
Fizyka vol 1
![Screenshot from 2020-04-21 10-26-14](https://user-images.githubusercontent.com/47241114/79843447-91b5fc00-83ba-11ea-8070-e3cd64a745b9.png)
