### ISSUE TITLE
Symmetry Feedback: Discrepancy in Figure Number Styling in EOC

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1982]
# Scenario

See below:
![Screen Shot 2020-02-28 at 5 50 26 PM](https://user-images.githubusercontent.com/7863733/75595658-ef7d3600-5a52-11ea-9940-4ad2d6b5b290.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
![Screen Shot 2020-03-02 at 4.13.49 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/2ec35fc4-2585-4f1f-886a-97b2e9753e8d)

Fixed with an existing issue.
