### ISSUE TITLE
Symmetry Feedback: Text Cutoff When Figure Follows Linked Section Header

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1983]
# Scenario

Note that the bottom of the "p" in "Displacement" doesn't appear:
![Screen Shot 2020-02-28 at 5 51 55 PM](https://user-images.githubusercontent.com/7863733/75595720-23f0f200-5a53-11ea-9761-9caa5e81ab21.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
Is this tied to the no line-height issue mentioned in #1978

**Comment by ajluk** [comment]
The space under the section links will be resolved in this PR: https://github.com/openstax/cnx-recipes/pull/2014. Now it looks like this:
![image](https://user-images.githubusercontent.com/55203598/75988398-cc8ad000-5ef1-11ea-8028-9315af78b690.png)

**Comment by openstaxalina** [comment]
Here is another test case for this, from HS Physics:
![Screen Shot 2020-03-05 at 3 22 38 PM](https://user-images.githubusercontent.com/7863733/76026894-44a6c500-5ef5-11ea-95f5-7bbf3a35d806.png)

**Comment by ajluk** [comment]
I have added line-height: line-height(3) property (it gives line-height:3rem in the output) to the the section links but while it resolves this issue with images, when there are few lines in the section title links it looks poor: 
![image](https://user-images.githubusercontent.com/55203598/76073564-18914f80-5f9a-11ea-84b4-29a6eb93a845.png). The line-height before my changes for these elements was set to line-height(1) = 1.5 rem (inherited form the root). I tried to set it to line-height(2), but it gives the same output (1.5rem).

**Comment by ajluk** [comment]
I guess this case https://github.com/openstax/cnx-recipes/issues/1983#issuecomment-595454555 is connected to works on the epic issue: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2015 and especially: https://github.com/openstax/cnx-recipes/issues/1956.

**Comment by ajluk** [comment]
Now in College Physics the image under section title link looks like this: 
![image](https://user-images.githubusercontent.com/55203598/76104847-56ab6500-5fd4-11ea-9db8-d82e83b7a46f.png)

**Comment by ajluk** [comment]
Changes in TDS for this issue are already included in #1978 (they are realted).

**Comment by MartaSztuka** [comment]
College Physics - looks ok
![Screenshot from 2020-03-10 11-40-23](https://user-images.githubusercontent.com/47241114/76305477-7dfc7d80-62c5-11ea-8538-6a10ce71efa2.png)
HS Physics - still occurs.
![Screenshot from 2020-03-10 11-39-07](https://user-images.githubusercontent.com/47241114/76305512-8fde2080-62c5-11ea-9d07-82641fe12aee.png)

**Comment by ajluk** [comment]
I have mentioned here (https://github.com/openstax/cnx-recipes/issues/1983#issuecomment-595862273) what is causing the problem and this issue is a part of the epic EOC Issues #2015.

**Comment by MartaSztuka** [comment]
HS Physics
![Screenshot from 2020-03-23 13-04-48](https://user-images.githubusercontent.com/47241114/77314942-efe1b780-6d06-11ea-9b75-3b455773dc79.png)
College Physics
![Screenshot from 2020-03-23 13-14-48](https://user-images.githubusercontent.com/47241114/77315719-50252900-6d08-11ea-8a89-72c72823deaa.png)
