### ISSUE TITLE
Symmetry Feedback: Oversized Art in EOC

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1984]
# Scenario

May be fixed by https://github.com/openstax/content-managers/issues/1401; but flagging in case:
![Screen Shot 2020-02-28 at 5 54 55 PM](https://user-images.githubusercontent.com/7863733/75595837-96fa6880-5a53-11ea-9b13-4a40fd4b085f.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
Flagged here for a content fix. https://app.zenhub.com/workspaces/content-management-5c86d8c40b66e07993f45cfa/issues/openstax/content-managers/1401 Closing
