### ISSUE TITLE
Symmetry Feedback: Weird indentation in caption for some EOC art?

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1985]
# Scenario

I don't care about the lack of space between the figure number and caption, but can the caption start on the same line as the figure number rather than having the indentation on the next line?

![Screen Shot 2020-02-28 at 5 58 23 PM](https://user-images.githubusercontent.com/7863733/75595951-07a18500-5a54-11ea-9e91-24763591bc2e.png)

# Acceptance Criteria (required)
- [ ] "Figure #.# + beginning of caption" all appear on the same line
- [ ] There is some space under the figure captions (note issue here: 
![Screen Shot 2020-03-02 at 12 41 40 PM](https://user-images.githubusercontent.com/7863733/75706672-305b9180-5c83-11ea-81cf-50496222d607.png)

# Test Plan

**Comment by lwtchu** [comment]
Those are the figure captions and are fixed with an existing issue regarding figure caption and number styling in EOC. 

![Screen Shot 2020-03-02 at 4.16.43 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/6870944a-3f4a-4993-85da-0cc357873502)
