### ISSUE TITLE
Symmetry/Space Savings

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#1989]
# What happened?

(_Briefly but clearly describe the issue_)

# Reproducibility Details

- **Does it also happen in an incognito window?**: 
- **Does this happen in one place, a few places, or everywhere?**:

# Environment:

- **Book(s)**:
- **URL/Server**: 
- **Location (page number, chapter/section)**:
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots

(_attach here (please clearly label what environment each screenshot came from)_)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment]
@helenemccarron here are the page counts from oer.exports; we should try to match or be lower than these:

_College Physics_: 1424
_Biology 2e_: 1578

**Comment by helenemccarron** [comment]
Reached a stable point before release for printing. Closing. Any remaining issues will be handled separately from now on.
