### ISSUE TITLE
suppress generated CSS files in GitHub Diffs

### ISSUE THREAD

**Issue by philschatz** [openstax/cnx-recipes#199]
From https://wynnnetherland.com/journal/suppress-generated-javascript-on-github-diffs/

It seems like we just need to add a `.gitattributes` file. What do folks think? @helenemccarron @tomjw64

**Comment by tomjw64** [comment]
Does that only affect diff behavior on GitHub? Is there a nice way to handle the far more annoying CSS diffs in terminal?

**Comment by philschatz** [comment]
Yeah, it's probably just GithHub ; (

Btw, I wouldn't be opposed to `.gitignore`ing the CSS files ; )

**Comment by helenemccarron** [comment]
@Stackblocks and @kerwinso are using the css from the repo to test our changes, so those do need to be committed and up to date. 
I tend to fix the diff in the css by running `./script/build-css` after fixing any conflict in the `./scss` file, or simply ignore them until I build the final version.
