### ISSUE TITLE
library wide space savings: reduce paragraph  padding

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1991]
Reduce paragraph bottom padding to `half-v-grid`. 

Based on my calculations for Biology, it should save about 80 pages.

**Comment by MartaSztuka** [comment]
**Biology 2e**
![Screenshot from 2020-03-25 10-18-23](https://user-images.githubusercontent.com/47241114/77520779-ffd1d680-6e81-11ea-96c9-58c497f7f4a7.png)
**HS Physics**
![Screenshot from 2020-03-25 10-19-56](https://user-images.githubusercontent.com/47241114/77520938-3ad40a00-6e82-11ea-822e-a4b48e24a30c.png)
**College Physics**
![Screenshot from 2020-03-25 10-21-17](https://user-images.githubusercontent.com/47241114/77521061-635c0400-6e82-11ea-8de3-72afada6f4cd.png)
