### ISSUE TITLE
Symmetry Feedback: Equations Not Centered in Some Cases?

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1993]
# Scenario

@MartaSztuka could you please test and see if this is resolved?  Equations were not centered, at least in some instances, in _College Physics_ PDF delivered to Symmetry last week:

![Screen Shot 2020-03-02 at 12 49 57 PM](https://user-images.githubusercontent.com/7863733/75707373-65b4af00-5c84-11ea-8f83-a46f8a1b5b57.png)

Here is the old PDF where equations are properly centered:
![Screen Shot 2020-03-02 at 12 51 03 PM](https://user-images.githubusercontent.com/7863733/75707508-998fd480-5c84-11ea-9a63-a42797828893.png)

# Acceptance Criteria (required)
- [ ] equations are centered when encoded in an equation tag

cc @lwtchu 

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by MartaSztuka** [comment]
Equations are centered
![Screenshot from 2020-03-03 11-45-53](https://user-images.githubusercontent.com/47241114/75768471-b8ee3680-5d44-11ea-9be5-2cf490b9ae37.png)
![Screenshot from 2020-03-03 11-44-38](https://user-images.githubusercontent.com/47241114/75768473-ba1f6380-5d44-11ea-9979-1a8420ee2ebe.png)
