### ISSUE TITLE
Symmetry Feedback: Table Too Large

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1995]
# Scenario

![Screen Shot 2020-03-02 at 3 22 43 PM](https://user-images.githubusercontent.com/7863733/75719155-d6b29180-5c99-11ea-8e1a-a760c11728c8.png)

# Acceptance Criteria (required)
- [ ] table does not go into margin

# Test Plan

**Comment by lwtchu** [comment]
Going to try changing the header from all math in the p(10^3...) and see if it fixes it.

**Comment by lwtchu** [comment]
![Screen Shot 2020-03-04 at 9 31 51 AM](https://user-images.githubusercontent.com/11299125/75895263-00cf9500-5dfb-11ea-946b-65b02adad94b.png)
Content fix ftw
