### ISSUE TITLE
Symmetry Feedback: Folio in ch 18 is randomly for ch. 17.7

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2000]
# Scenario

I think this is happening because the chapter outline and introduction are so long.

![Screen Shot 2020-03-02 at 4 59 33 PM](https://user-images.githubusercontent.com/7863733/75726054-454a1c00-5ca7-11ea-93bd-f702b4572f82.png)

# Acceptance Criteria (required)
- [ ] folio is for 18 • Introduction or 18.0 • Introduction @lwtchu please confirm

# Test Plan

**Comment by lwtchu** [comment]
Confirmed an issue

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-03-11 15-31-31](https://user-images.githubusercontent.com/47241114/76428051-744e4500-63ad-11ea-9998-0293a8036f75.png)
