### ISSUE TITLE
Symmetry Feedback: Box within a Box (TM)

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2001]
# Scenario

I think this is fine but just in case opening for @lwtchu 's review:

oer.exports on the left; baked styles on the right
![Screen Shot 2020-03-02 at 5 05 08 PM](https://user-images.githubusercontent.com/7863733/75726477-1c765680-5ca8-11ea-831e-5288b8dbc236.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
@openstaxalina do you think it would be cool if we pulled it out in the content? in other features like for Kirchhoff's Rules, there's a box about Kirchhoff's Rules and then a separate box for Problem-Solving Strategies for Kirchhoff's Rules

**Comment by openstaxalina** [comment]
@lwtchu because this isn't a numbered element, I think that's fine.  I'll move this to the content repo!

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #1493](https://github.com/openstax/content-managers/issues/1493) via [**ZenHub**](https://www.zenhub.com/)
