### ISSUE TITLE
Style EoC in Microbiology

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2005]
EoC sections need to be styled according to Carnival Theme Specs.

**Comment by ajluk** [comment]
Changes in TDS: 
**ChapterReviewCompositeChapter**  shape need to have book specific color set for **EocHeader** to B7 for Microbiology,
Exercises using shape EocCompChapExercises need to have book specific color for Microbiology set as well: 
**CriticalThinkingCompChapPage**
          **CompChapPageHeader** color book specific B7 for Microbiology
**ShortAnswerCompChapPage**
          **CompChapPageHeader** color book specific B7 for Microbiology

New exercises in Microbiology are using the shape EocCompChapExercises and they need to be added to specs:
**MultipleChoiceCompChapPageWithTwoColumns** (I guess can be added to l.721)
**Container**component
properties:
 column-count: 2,
 column-gap: 2.4rem,
column-width: auto,
 margin-bottom: v-grid(2),
**CompChapPageHeader** component
properties:
font-family: ("IBM Plex Sans", sans-serif),
column-span: all,
color: book specific for Microbiology B7
font-weight: bold,
 font-size: font-scale(3),
 line-height: line-height(3),
text-transform: uppercase,
margin-bottom: v-grid(1)
**EocSectionTitleLink** component
properties:
font-family: "Muli",
font-size: font-scale(3),
**ProblemWrapper** component
properties:
display: table,
**ProblemNumber**
color: black,
font-weight: bold,
 text-decoration: none,
display: table-cell,
ProblemDivider
margin-right: h-grid(1),
**ProblemContainer** component
properties
display: table-cell,
**ProblemParagraph** component
properties
 margin-bottom: 0,
**ExerciseOrderedList** component
properties
margin-left:  h-grid(4),
margin-bottom: v-grid(1),
**ExerciseNestedOrderedList** component
properties
margin-left: h-grid(2),
 margin-bottom: v-grid(1),
**ExerciseFigure** component
properties
max-width: 100%,

These shapes can be added under l.730:

**FillInTheBlank**
**Container**component
properties:
 margin-bottom: v-grid(2),
**CompChapPageHeader** component
properties:
font-family: ("IBM Plex Sans", sans-serif),
column-span: all,
color: book specific for Microbiology B7
font-weight: bold,
 font-size: font-scale(3),
 line-height: line-height(3),
text-transform: uppercase,
margin-bottom: v-grid(1)
**EocSectionTitleLink** component
properties:
font-family: "Muli",
font-size: font-scale(3),
**ProblemWrapper** component
properties:
display: table,
**ProblemNumber**
color: black,
font-weight: bold,
 text-decoration: none,
display: table-cell,
ProblemDivider
margin-right: h-grid(1),
**ProblemContainer** component
properties
display: table-cell,
**ProblemParagraph** component
properties
 margin-bottom: 0,
**ExerciseOrderedList** component
properties
margin-left:  h-grid(4),
margin-bottom: v-grid(1),
**ExerciseFigure** component
properties
max-width: 100%,

**Matching**
**Container**component
properties:
 margin-bottom: v-grid(2),
**CompChapPageHeader** component
properties:
font-family: ("IBM Plex Sans", sans-serif),
column-span: all,
color: book specific for Microbiology B7
font-weight: bold,
 font-size: font-scale(3),
 line-height: line-height(3),
text-transform: uppercase,
margin-bottom: v-grid(1)
**EocSectionTitleLink** component
properties:
font-family: "Muli",
font-size: font-scale(3),
**ProblemWrapper** component
properties:
display: table,
**ProblemNumber**
color: black
font-weight: bold,
 text-decoration: none,
display: table-cell,
ProblemDivider
margin-right: h-grid(1),
**ProblemContainer** component
properties
display: table-cell,
**ProblemParagraph** component
properties
 margin-bottom: 0,

**TrueFalse**
**Container**component
properties:
 margin-bottom: v-grid(2),
**CompChapPageHeader** component
properties:
font-family: ("IBM Plex Sans", sans-serif),
column-span: all,
color: book specific for Microbiology B7
font-weight: bold,
 font-size: font-scale(3),
 line-height: line-height(3),
text-transform: uppercase,
margin-bottom: v-grid(1)
**EocSectionTitleLink** component
properties:
font-family: "Muli",
font-size: font-scale(3),
**ProblemWrapper** component
properties:
display: table,
**ProblemNumber**
color: black,
font-weight: bold,
 text-decoration: none,
display: table-cell,
ProblemDivider
margin-right: h-grid(1),
**ProblemContainer** component
properties
display: table-cell,
**ProblemParagraph** component
properties
 margin-bottom: 0,

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-03-17 16-30-45](https://user-images.githubusercontent.com/47241114/76872513-cf2fe280-686c-11ea-9fdd-2d515c04b635.png)
![Screenshot from 2020-03-17 16-30-37](https://user-images.githubusercontent.com/47241114/76872517-d0610f80-686c-11ea-8e9d-58e3473b2634.png)
