### ISSUE TITLE
Sections without section links in exercises have inherited margins

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2013]
In Microbiology there are various exercises in the EoC nested in sections without section links, which looks oddly (generate unnecessary spaces in this case). I have created a separate issue about because the removing of this margins can affect other exercises with section links in other books. Now it looks like this: 
![image](https://user-images.githubusercontent.com/55203598/75963719-4ad17d00-5ec6-11ea-941d-32d1df004684.png)

**Comment by MartaSztuka** [comment]
![Screenshot from 2020-04-14 13-44-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/16db3f3b-5e53-41fe-b977-02c6367be125)
