### ISSUE TITLE
2020 Q2 or early Q3: implement top-titled tables in remaining business series books

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2016]
# Scenario

Top-titled tables need to be implemented in _Introduction to Business_, _Organizational Behavior_, _Principles of Management_. Here is test content:

IB: https://easyvm5.cnx.org/contents/Tgl3H6iq@9.1:DK-tGpHN@7/How-Business-and-Economics-Work
OB: https://easyvm5.cnx.org/contents/LZQauaxb@6.1:9pJHuA38@2/Barriers-to-Accurate-Social-Perception
PoM: https://easyvm5.cnx.org/contents/w6yyq31c@11.1:ti2VQkRr@6/Group-Decision-Making

# Acceptance Criteria (required)
Table titles display at the top of the table, centered, with no border around them

# Test Plan

**Comment by openstaxalina** [comment]
First @marcjeannott will need to ensure the content at the links above is properly marked up as top-titled tables.  This is a Q2 problem.

**Comment by brittweinstein** [comment]
@openstaxalina what is the priority of this in relation to the Baked Styles project?

**Comment by openstaxalina** [comment]
@brittweinstein we should do this at the same time that we do the baked styles for the business series. Does this provide the information that you need?

cc @lwtchu

**Comment by brittweinstein** [comment]
@lwtchu is this reflected in the documentation cards for the cardboard theme?

**Comment by lwtchu** [comment]
@brittweinstein no the cards haven't been made for those titles yet

**Comment by lwtchu** [comment]
Going to close. They need classes added. I'll open a card for the CM board instead.
