### ISSUE TITLE
Symmetry Feedback: Inconsistent Spacing After Grasp Check Stem

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2018]
# Scenario

See two examples with different styling below:

![Screen Shot 2020-03-05 at 10 43 03 AM](https://user-images.githubusercontent.com/7863733/76003790-29748f00-5ece-11ea-873b-34ebd2bd89af.png)

![Screen Shot 2020-03-05 at 10 43 14 AM](https://user-images.githubusercontent.com/7863733/76003800-2c6f7f80-5ece-11ea-9077-648aa1ea5017.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
I generated a PDF today on COPS and problem still persist so I'm not sure if existing list fixes fixed this instance.

**Comment by ajluk** [comment]
Changes in TDS:
New component needs to be added to **BoxedCondensedNote** notes shape under l.309
**FirstParagraph**
_properties_:
margin-bottom: 0

and tthis components needs to be added to notes that are using this shape as well: **GraspCheckNote** (under l.451), **TipsForSuccessNote** (under l.448)

**Comment by MartaSztuka** [comment]
tested![Screenshot from 2020-03-11 11-09-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/da74c581-5135-41b2-9227-28c786160055)
