### ISSUE TITLE
Symmetry Feedback: Line Height too High on H2s?

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2019]
# Scenario

![Screen Shot 2020-03-05 at 10 44 39 AM](https://user-images.githubusercontent.com/7863733/76003957-65a7ef80-5ece-11ea-86e1-06b9e5492b67.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
@helenemccarron can you advise if the page saving line height reductions will impact this? i cant tell with the PDF you gave me

**Comment by brittweinstein** [comment]
Recommendation from scrum 3/9: we'll change the line-height to font scale 3

**Comment by openstaxalina** [comment]
assigned to @helenemccarron per conversation in Monday meeting

**Comment by MartaSztuka** [comment]
**HS Physics**
![Screenshot from 2020-03-24 17-29-14](https://user-images.githubusercontent.com/47241114/77451499-09612d00-6df5-11ea-8a2c-e4bfd8345bcc.png)
![Screenshot from 2020-03-24 17-28-41](https://user-images.githubusercontent.com/47241114/77451504-09f9c380-6df5-11ea-980d-7433c09ecc30.png)
