### ISSUE TITLE
Symmetry Feedback: Reduce Page Count: Section Key Terms Spacing?

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2020]
# Scenario

![Screen Shot 2020-03-05 at 10 45 59 AM](https://user-images.githubusercontent.com/7863733/76004096-97b95180-5ece-11ea-9998-8b003af4d31a.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
These are in tables generated by hand. moving to content

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1523](https://github.com/openstax/content-managers/issues/1523) via [**ZenHub**](https://www.zenhub.com/)
