### ISSUE TITLE
Symmetry Feedback: Inconsistent Styling of Table Heads

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2021]
# Scenario

I'll add more screenshots below if add'l tables showing the inconsistency are flagged.

![Screen Shot 2020-03-05 at 10 49 28 AM](https://user-images.githubusercontent.com/7863733/76004374-026a8d00-5ecf-11ea-8937-0969609e327e.png)

![Screen Shot 2020-03-05 at 10 49 18 AM](https://user-images.githubusercontent.com/7863733/76004381-05657d80-5ecf-11ea-9aa0-10a84ef5a486.png)

![Screen Shot 2020-03-05 at 11 23 50 AM](https://user-images.githubusercontent.com/7863733/76007541-d30a4f00-5ed3-11ea-8785-bd5fc04e736f.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
This is inconsistent markup. Moving to CM board

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1522](https://github.com/openstax/content-managers/issues/1522) via [**ZenHub**](https://www.zenhub.com/)
