### ISSUE TITLE
Symmetry Feedback: Key Equations Folio Persists in Other EOC Sections

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2022]
# Scenario

![Screen Shot 2020-03-05 at 11 05 28 AM](https://user-images.githubusercontent.com/7863733/76005923-54acad80-5ed1-11ea-8d73-743445ffce77.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by wilkus27** [comment]
It's already solved by https://github.com/openstax/cnx-recipes/pull/1975.

![image](https://user-images.githubusercontent.com/40228854/76196860-4d481580-61eb-11ea-9950-b6aecac0b2d7.png)

![image](https://user-images.githubusercontent.com/40228854/76196896-63ee6c80-61eb-11ea-8c8e-79db88897f67.png)

![image](https://user-images.githubusercontent.com/40228854/76196939-7668a600-61eb-11ea-82f9-2c432c2e11ae.png)
