### ISSUE TITLE
Symmetry Feedback: Equation Box Crashes with Text

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2023]
# Scenario

This may be global for equation boxes when the text above them extends nearly to the right margin:

![Screen Shot 2020-03-05 at 11 19 49 AM](https://user-images.githubusercontent.com/7863733/76007285-6bec9a80-5ed3-11ea-99b8-e16d8acd12ec.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
I think we can fix this by not having this be display math. Moving to CM board

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1521](https://github.com/openstax/content-managers/issues/1521) via [**ZenHub**](https://www.zenhub.com/)
