### ISSUE TITLE
space saving: note/example styling adjustments for space saving

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2032]
# Icon note AND example
<img width="828" alt="Screen Shot 2020-03-09 at 11 35 43 AM" src="https://user-images.githubusercontent.com/11299125/76236125-352bc280-61fa-11ea-8af5-665b67ea2765.png">

size: KEEP font-scale(1) 
line height: KEEP font-scale(0)
**make the text one line**
**icon size: try v-grid(2)?**

# Icon condensed note
<img width="373" alt="Screen Shot 2020-03-09 at 2 21 09 PM" src="https://user-images.githubusercontent.com/11299125/76249441-53e98380-6211-11ea-8f3b-94e64bd41560.png">

size: KEEP font-scale(1)
**make the text one line**
**icon size: v-grid(1)?**

# Boxed note
<img width="1032" alt="Screen Shot 2020-03-09 at 2 26 16 PM" src="https://user-images.githubusercontent.com/11299125/76249727-f6a20200-6211-11ea-9f5c-9d6a8552eba6.png">

**font-size: font-scale(1),**
**line-height: line-height(1),**

**Try removing the dotted line also**

This should impact all books in the carnival theme, but I'm putting the labels for the high prioriy books first.

**Comment by lwtchu** [comment]
Updated card to include a test to remove the dotted line in boxed notes

**Comment by MartaSztuka** [comment]
**College Physics**
![Screenshot from 2020-03-24 15-48-27](https://user-images.githubusercontent.com/47241114/77439184-04957c80-6de7-11ea-9e11-32c0fb38766c.png)
