### ISSUE TITLE
CLEAN UP  - rename the v-grid variables

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#2038]
Proposed change:
Make  `half-v-grid` the default unit
Rename:
-  `half-v-grid` to `v-spacing`
- `v-grid` to `column-v-spacing`
- `h-grid` to `h-spacing`

We would have `table-spacing` , `v-spacing`, `h-spacing` and `column-v-spacing`.

**Comment by andymuddimer** [comment]
Discussed and agreed with @helenemccarron 3/16

**Comment by helenemccarron** [comment]
addressed in addressed in https://github.com/openstax/cnx-recipes/pull/2074 - tested as part of the regression testing.
