### ISSUE TITLE
CLEAN UP - EOC: remove named table components from EOC

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#2040]
Remove the named table components and add existing table components to shapes in EOC (this includes exercises etc.)

**Comment by brittweinstein** [comment]
@helenemccarron please put points on this when you start work.

**Comment by wilkus27** [comment]
Waiting for merge changes from #2188 and #1717 .

**Comment by wilkus27** [comment]
Done within https://github.com/openstax/cnx-recipes/pull/2300
