### ISSUE TITLE
Plan for / Implement @use over @import in Sass files

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#2045]
Per the Sass docs, the maintainers of Sass are planning on [phasing out the `@import` rule. ](https://github.com/sass/sass/blob/master/accepted/module-system.md#timeline)

In their words:
> ⚠️ Heads up!
The Sass team discourages the continued use of the `@import` rule. Sass will [gradually phase it out](https://github.com/sass/sass/blob/master/accepted/module-system.md#timeline) over the next few years, and eventually remove it from the language entirely. Prefer the [`@use` rule](https://sass-lang.com/documentation/at-rules/use) instead.
>
> What’s Wrong With `@import`?
The @import rule has a number of serious issues:
>
> `@import` makes all variables, mixins, and functions globally accessible. This makes it very difficult for people (or tools) to tell where anything is defined.
>
>Because everything’s global, libraries must prefix to all their members to avoid naming collisions.
>
>[`@extend` rules are also global](https://sass-lang.com/documentation/at-rules/extend), which makes it difficult to predict which style rules will be extended.
>
>Each stylesheet is executed and its CSS emitted every time it’s `@import`ed, which increases compilation time and produces bloated output.
>
>There was no way to define private members or placeholder selectors that were inaccessible to downstream stylesheets.
>
>The new module system and the `@use` rule address all these problems.
>
>How Do I Migrate?
>We’ve written a [migration tool](https://sass-lang.com/documentation/cli/migrator) that automatically converts most `@import`-based code to `@use`-based code in a flash. Just point it at your entrypoints and let it run!

Not sure if the migration tool will work for us but since we're in a period of cleanup we should take a look at this and see what we would need to do to make this switch so we don't get stuck with EOL'd code.

**Comment by Stackblocks** [comment]
Based on my research (assuming I understand the sass docs), this is going to be a good bit more complex than just a 1:1 swap so we'll need someone with a more architectural view of the codebase to take a look at this with a mind to swap out the two.

**Comment by lwtchu** [comment]
moot point. we are leaving sass.
