### ISSUE TITLE
Adjust validation of component names to allow for BEM nomenclature

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#2046]
The current validation [throws a fit](https://openstax.slack.com/archives/CBW9DFKGF/p1583916139108500) when we try to use [BEM syntax](https://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/) and we'll need to make adjustments to make way for clearer code in the future.

This can also be used as a training exercise for the TBDs as a group.

**Comment by brittweinstein** [comment]
@Stackblocks does this need to be completed in order to call the clean up work complete?

**Comment by Stackblocks** [comment]
It looks like this was handled via https://github.com/openstax/cnx-recipes/issues/2202. Closing this one.
