### ISSUE TITLE
Bug: Figures Not Displaying in Baked PDF

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2048]
# What happened?

This was originally noted by Symmetry, but we thought it was a content issue.

In at least two instances, the figure is not displaying in the PDF even though it displays on the web:

First instance in Ch. 9 Test Prep >> [Short Answer] 
I am not sure if the problem is that there are two figures in one exercise?
(https://cnx.org/contents/zOZP3vRI@9.12:HCL6PC8c@9.12/Short-Answer)
![HSPhysicsFigureMissing](https://user-images.githubusercontent.com/7863733/76637445-c495e600-6518-11ea-989d-664f14ec9942.png)

Second instance in Ch. 20 Test Prep >> [Extended Response]
In this case there is only one figure in the exercise:
(https://cnx.org/contents/zOZP3vRI@9.12:vbO3gktF@9.12/Extended-Response)
![HSPhysicsMissingFigure2](https://user-images.githubusercontent.com/7863733/76637533-eb541c80-6518-11ea-91ae-57bc1c7f632b.png)

**Comment by openstaxalina** [comment]
@helenemccarron, she suggested investigating the content further:

Is there any different in the markup around these figures?
Are the figures different file types?

The first case is a perfect example, where one figure is showing but the other isn't - can we learn anything from that?

**Comment by oscryan** [comment]
Nope. They're exactly the same.
`Why would you expect the lever shown in the top image to have a greater efficiency than the inclined plane shown in the bottom image?
<figure id="eip-idm525299840"><media id="eip-idm192465088" alt="no alt text">
<image mime-type="image/jpeg" src="CNX_HSPhysics_09_03_levers.jpg "/>
</media>
</figure><figure id="eip-idm208041616"><media id="eip-idm217253744" alt="no alt text">
<image mime-type="image/jpeg" src="CNX_HSPhysics_09_03_wedge.jpg"/>
</media>
</figure>`

**Comment by oscryan** [comment]
WAIT

**Comment by ajluk** [comment]
In the second instance: Test Prep >> [Extended Response] it is a content issue: Test Prep >> [Extended Response] There is a module number missing in the img url: ![image.png](https://images.zenhubusercontent.com/5d808b7f46611c000130dbbd/48b9a971-8f61-4b47-a1ca-0ee5b721f7b8)

**Comment by oscryan** [comment]
Both of them had spaces in the filenames. It's fixed now.

**Comment by lwtchu** [comment]
:sob: thank god it's nothing crazy but also another case for better validation!
