### ISSUE TITLE
EoC Long equation

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2050]
When equation in two column is too long, whole paragraphs overlap second column.
![Screenshot from 2020-03-16 11-56-47](https://user-images.githubusercontent.com/47241114/76751217-6fa7d900-677f-11ea-9ecc-0fd3275e84cb.png)

**Comment by lwtchu** [comment]
<img width="399" alt="Screen Shot 2020-03-16 at 9 05 09 AM" src="https://user-images.githubusercontent.com/11299125/76765971-437f5e80-6765-11ea-97f5-9c8de24c6c72.png">
fixed in content on production
