### ISSUE TITLE
Fizyka - styles

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2051]
1. **Polish diacritics have different font**
![Screenshot from 2020-03-16 17-27-09](https://user-images.githubusercontent.com/47241114/76779440-a562b700-67ab-11ea-977e-aaa16fa3cc99.png)

**Comment by MartaSztuka** [comment]
In Example `strategia rozwiązania` and `rozwiązanie` etc. should be bolded.
![Screenshot from 2020-03-17 10-51-56](https://user-images.githubusercontent.com/47241114/76844455-988ea380-683d-11ea-9c2e-f632e2f66c0a.png)

**Comment by MartaSztuka** [comment]
Page break for Exercises numbers ![Screenshot from 2020-03-17 10-17-22](https://user-images.githubusercontent.com/47241114/76841524-30d65980-6839-11ea-8091-77f75361fef6.png)

**Comment by MartaSztuka** [comment]
Numbering in EoC should be bold and inline
![Screenshot from 2020-03-17 10-59-30](https://user-images.githubusercontent.com/47241114/76845133-a55fc700-683e-11ea-828b-e6f48b9b89b1.png)

**Comment by MartaSztuka** [comment]
One fully blank page at EoC
![Screenshot from 2020-03-17 11-16-15](https://user-images.githubusercontent.com/47241114/76846453-d0e3b100-6840-11ea-9cdb-6bbc6e1bdbc0.png)

**Comment by MartaSztuka** [comment]
Equations are missing top margine, bottom margine are are too wide (happens randomly).
![Screenshot from 2020-03-17 11-27-42](https://user-images.githubusercontent.com/47241114/76847594-9418b980-6842-11ea-9a07-db224ccae7b6.png)

**Comment by MartaSztuka** [comment]
`Interactive` header is aligned to the bottom with icon (unlike other similar notes and `link to learning`)
![Screenshot from 2020-03-17 11-35-18](https://user-images.githubusercontent.com/47241114/76848417-eb6b5980-6843-11ea-9a02-18b1ba12ef72.png)

**Comment by MartaSztuka** [comment]
Section summary header is not styled
![Screenshot from 2020-03-17 11-41-17](https://user-images.githubusercontent.com/47241114/76848599-42712e80-6844-11ea-9f52-e101ab13f2cb.png)

**Comment by MartaSztuka** [comment]
Some equations are centered some are left aligned
![Screenshot from 2020-03-17 12-17-20](https://user-images.githubusercontent.com/47241114/76851259-45225280-6849-11ea-9d7c-7035ca02abcf.png)

**Comment by MartaSztuka** [comment]
Tables are left aligned, should be centered.
![Screenshot from 2020-03-17 12-21-32](https://user-images.githubusercontent.com/47241114/76851687-f75a1a00-6849-11ea-9d91-82ca074b1719.png)

**Comment by MartaSztuka** [comment]
Dot drops to second line in random places.
![Screenshot from 2020-03-17 12-49-36](https://user-images.githubusercontent.com/47241114/76853650-ff1bbd80-684d-11ea-814b-f7fdf738dd36.png)

**Comment by MartaSztuka** [comment]
Bullet points stick out in some places.
![Screenshot from 2020-03-17 12-55-14](https://user-images.githubusercontent.com/47241114/76854080-c16b6480-684e-11ea-9751-c80c313e90ba.png)

**Comment by MartaSztuka** [comment]
Equations are styled differently (blue border appears in 10th chapter).
![Screenshot from 2020-03-17 13-15-05](https://user-images.githubusercontent.com/47241114/76855659-deedfd80-6851-11ea-8f1a-565fc2d752f0.png)
![Screenshot from 2020-03-17 13-11-24](https://user-images.githubusercontent.com/47241114/76855663-df869400-6851-11ea-8803-5b4c76ab9c16.png)

**Comment by MartaSztuka** [comment]
PhET note needs to be styled
![Screenshot from 2020-03-18 13-02-13](https://user-images.githubusercontent.com/47241114/76958914-d01e4e00-6918-11ea-87df-04c60ad4ac04.png)

**Comment by MartaSztuka** [comment]
Leading is too small (in all book in general) but with tall equations is extra hard to read.![Screenshot from 2020-03-18 13-59-13](https://user-images.githubusercontent.com/47241114/76963196-f0520b00-6920-11ea-9921-a59754267bdd.png)

**Comment by MartaSztuka** [comment]
Tables shouldn't break (if possible)
![Screenshot from 2020-03-18 15-50-26](https://user-images.githubusercontent.com/47241114/76973545-627e1c00-6930-11ea-9879-df95adb4c151.png)

**Comment by MartaSztuka** [comment]
Margines in headers should be bigger than leading.
![Screenshot from 2020-03-18 15-52-42](https://user-images.githubusercontent.com/47241114/76973801-b38e1000-6930-11ea-88cf-c6b12aee8f35.png)

**Comment by wilkus27** [comment]
### Issues which should be resolved within https://github.com/openstax/cnx-recipes/pull/2176:

- 1-6
- 8-9
- 11
- 13

**Comment by wilkus27** [comment]
### Issue 7th

Appears also in University Physics. Will be resolved in https://github.com/openstax/cnx-recipes/issues/2182.

**Comment by wilkus27** [comment]
### Content issues:

- 10
Those equations should be put in tag `data-type="equation" with class `unnumbered``
- 14
Missing class `equation-callout`
- 16
Missing class `media-2`

**Comment by wilkus27** [comment]
### Issue 12th

Global issue. Will be resolved in https://github.com/openstax/cnx-recipes/issues/1981.

**Comment by wilkus27** [comment]
### Issue 15th

Will be resolved in https://github.com/openstax/cnx-recipes/issues/2088.

**Comment by wilkus27** [comment]
### Issue 17th

Should be resolved within https://github.com/openstax/cnx-recipes/pull/2107.

**Comment by wilkus27** [comment]
### Issues 18th and 19th

- 18
We let tables to break, because then book has less pages.
- 19
Marta please verify again. If you think that some margins/paddings are still needed, please create separate issue with specs.

**Comment by MartaSztuka** [comment]
@wilkus27  Seperate issue for 19 https://github.com/openstax/cnx-recipes/issues/2184

**Comment by MartaSztuka** [comment]
Tested on 1st volume, resolved by #2176 
1. 
![Screenshot from 2020-04-10 16-08-00](https://user-images.githubusercontent.com/47241114/78996816-adf9a380-7b45-11ea-9de5-6426c55573b9.png)
2. 
![Screenshot from 2020-04-10 16-10-42](https://user-images.githubusercontent.com/47241114/78996913-df726f00-7b45-11ea-9f14-807a419b84f0.png)
3.
 ![Screenshot from 2020-04-10 16-13-32](https://user-images.githubusercontent.com/47241114/78997132-442dc980-7b46-11ea-9a2e-a637d63ac931.png)
4. 
![Screenshot from 2020-04-10 16-17-07](https://user-images.githubusercontent.com/47241114/78997381-c1f1d500-7b46-11ea-8890-6db5dc89b4e3.png)
5.
 ![Screenshot from 2020-04-10 16-19-06](https://user-images.githubusercontent.com/47241114/78997530-0aa98e00-7b47-11ea-8b9c-78ec972ca2a0.png)
6.
 ![Screenshot from 2020-04-10 16-22-08](https://user-images.githubusercontent.com/47241114/78997750-77248d00-7b47-11ea-9867-3dec9adc049e.png)
8.
 ![Screenshot from 2020-04-10 16-24-28](https://user-images.githubusercontent.com/47241114/78997910-cbc80800-7b47-11ea-93cf-3b91b2c03e6a.png)
9.
 ![Screenshot from 2020-04-10 16-25-31](https://user-images.githubusercontent.com/47241114/78997978-f7e38900-7b47-11ea-8c2d-6d4aace1da35.png)
11. 
![Screenshot from 2020-04-10 16-28-21](https://user-images.githubusercontent.com/47241114/78998183-57da2f80-7b48-11ea-887a-f621b439cade.png)
13.
 ![Screenshot from 2020-04-10 16-29-46](https://user-images.githubusercontent.com/47241114/78998255-8526dd80-7b48-11ea-86ea-8207b85a3b3c.png)
![Screenshot from 2020-04-10 16-29-30](https://user-images.githubusercontent.com/47241114/78998261-86f0a100-7b48-11ea-944e-77877b4b208b.png)
