### ISSUE TITLE
Fizyka - recipe

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2052]
1. **Preface doesn't have folio, just a dot.**
![Screenshot from 2020-03-17 08-42-52](https://user-images.githubusercontent.com/47241114/76833540-d08ceb00-682b-11ea-9917-1a6f60d94d2b.png)
2. **EoC should have eg. Chapter 1 . Key Terms folio**
![Screenshot from 2020-03-17 09-49-19](https://user-images.githubusercontent.com/47241114/76838904-e3f08400-6834-11ea-92c3-0752ef3605c8.png)

**Comment by MartaSztuka** [comment]
Page break
1. Exercises numbers ![Screenshot from 2020-03-17 10-17-22](https://user-images.githubusercontent.com/47241114/76841524-30d65980-6839-11ea-8091-77f75361fef6.png)

**Comment by MartaSztuka** [comment]
Notes, Examples, Learning objectives are not translated
![Screenshot from 2020-03-17 10-42-20](https://user-images.githubusercontent.com/47241114/76843521-33867e00-683c-11ea-8ca2-ca3857b98e60.png)
![Screenshot from 2020-03-17 10-42-05](https://user-images.githubusercontent.com/47241114/76843524-34b7ab00-683c-11ea-80fe-e03fb1d3f68f.png)
![Screenshot from 2020-03-17 10-44-05](https://user-images.githubusercontent.com/47241114/76843552-3f724000-683c-11ea-990b-cf44ba31bb6a.png)

**Comment by MartaSztuka** [comment]
abc-s should not stick out
![Screenshot from 2020-03-17 11-02-04](https://user-images.githubusercontent.com/47241114/76845316-fc659c00-683e-11ea-9667-1b6738300f8b.png)

**Comment by MartaSztuka** [comment]
Illustration source should be below not above it.
![Screenshot from 2020-03-17 12-26-12](https://user-images.githubusercontent.com/47241114/76851995-aeef2c00-684a-11ea-936b-50a5586bd497.png)

**Comment by MartaSztuka** [comment]
In Answer Key 'Check your understanding' is mixed with Chapter outline
also Chapter header is duble
![Screenshot from 2020-03-18 13-51-22](https://user-images.githubusercontent.com/47241114/76962685-f4315d80-691f-11ea-8d4f-7871ca5bf013.png)

**Comment by MartaSztuka** [comment]
Index starts with Symbols (all 3 volumes).
![Screenshot from 2020-03-18 15-37-21](https://user-images.githubusercontent.com/47241114/76972447-e46d4580-692e-11ea-89ee-783fce55480c.png)

**Comment by MartaSztuka** [comment]
**In Chapter Review list numbers overlap abc-s (one location found in vol. 3.)**
![Screenshot from 2020-03-20 12-30-58](https://user-images.githubusercontent.com/47241114/77160040-d5110800-6aa6-11ea-9ab4-5e7bbb91faa6.png)

**Comment by wilkus27** [comment]
### Issues which will be resolved within #2176:

- 2-5
- 9

**Comment by wilkus27** [comment]
### Content issues:

- 1
- 6

**Comment by wilkus27** [comment]
### Issue 7th

Will be resolved within https://github.com/openstax/cnx-recipes/pull/2107

**Comment by MartaSztuka** [comment]
Resolved by #2176 
2. ![Screenshot from 2020-04-10 15-42-33](https://user-images.githubusercontent.com/47241114/78995171-0f1f7800-7b42-11ea-92cf-6f5b9583c528.png)
3. ![Screenshot from 2020-04-10 15-46-52](https://user-images.githubusercontent.com/47241114/78995393-894ffc80-7b42-11ea-9c74-8e25710667bb.png)
4. 
![Screenshot from 2020-04-10 15-49-11](https://user-images.githubusercontent.com/47241114/78995531-dcc24a80-7b42-11ea-86cc-ffca32f16f6e.png)
![Screenshot from 2020-04-10 15-48-47](https://user-images.githubusercontent.com/47241114/78995532-ddf37780-7b42-11ea-9ed4-84b82d5afe47.png)
![Screenshot from 2020-04-10 15-48-31](https://user-images.githubusercontent.com/47241114/78995535-ddf37780-7b42-11ea-80a5-57b6f2ce1853.png)
![Screenshot from 2020-04-10 15-48-12](https://user-images.githubusercontent.com/47241114/78995536-de8c0e00-7b42-11ea-9ec1-251139978b35.png)
5. ![Screenshot from 2020-04-10 15-51-02](https://user-images.githubusercontent.com/47241114/78995642-227f1300-7b43-11ea-8cb8-6ec2ca8e842d.png)
9. Issue was found in 3th volume (1st is fine), so it's not tested yet.
