### ISSUE TITLE
Add style to Summary, Terms, Appendices in Microbiology

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2054]
Summary, Terms, Appendices in Microbiology need to be styled according to Carnival Theme Specs.

**Comment by ajluk** [comment]
Changes in TDS:
In shape **EocSummary** new component needs to added:
**EocSectionTitleLink** (under l. 608)
with properties:
font-family: (_ref:'typography:::titleFont'),
font-size: font-scale(2),
line-height: line-height(2),

**Book specific colors**  for **Microbiology** in the **Appendix** shape for components:
**MainText**
color: B7
**SubTitle**
color: B7
**SubSubTitle**
color: B7
and in the **EoCSummary** for 
**EocHeader** (cell J608)
color: B7
are already set in the table :)

I have noticed that there isn't set book specific color for **EocHeader** in **EoCSummary** shape. 
For other books using this shape theese are the colors:
Anatomy: B5 (cell G608)
Chemistry: B4 (cell E608)

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-03-24 13-13-55](https://user-images.githubusercontent.com/47241114/77424422-65b25580-6dd1-11ea-83d0-7aeb899cdbef.png)
![Screenshot from 2020-03-24 13-13-38](https://user-images.githubusercontent.com/47241114/77424427-66e38280-6dd1-11ea-8c61-7b709a874301.png)
