### ISSUE TITLE
CLEAN UP: add a component/shape for column layout in EOC

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#2057]
Some sections of the EOC can be either in a multiple columns layout or single column layout, we should support both options. 
**Note** The column layout (any multiple-column layout) should use `column-v-spacing`, otherwise use `v-spacing`

**Comment by helenemccarron** [comment]
Added some extra components while cleaning up during space saving, more work is needed to remove extra components, use new components on all books and make sure that the shapes contain all the appropriate components.

**Comment by wilkus27** [comment]
Done in https://github.com/openstax/cnx-recipes/pull/2074 and https://github.com/openstax/cnx-recipes/pull/2136
