### ISSUE TITLE
CLEAN UP: add component/shape for column layout in the EOB

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#2058]
Some sections of the EOB can be either in a multiple columns layout or single column layout, we should support both options.
Note The column layout (any multiple-column layout) should use column-v-spacing, otherwise use v-spacing

**Comment by Stackblocks** [comment]
Temp update: Waiting on this until Brittany J gets back so I can get her help getting unstuck.

**Comment by Stackblocks** [comment]
Closing this over lack of information. We will address the issue if it crops up again.
