### ISSUE TITLE
corn theme: table of contents (without units)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2060]
Spec doc link: https://docs.google.com/spreadsheets/d/1vW0EHvn8fZgvTxZIm9xQXsqsnIDcolqwt5rWKtx4JEY/edit#gid=255572881

I've added as much as I can into the spreadsheet. I will try to make it human-readable here in case what I put in the spec sheet doesnt make any sense.

### TOC Title Word ("Table of Contents")
font-size: font-scale(2): 11.88pt, 15.84px, 1.4rem
color: B1 `#093D4C`
font family: [Roboto Slab](https://fonts.google.com/specimen/Roboto+Slab)

TocTitle Icon: [corn-toc.svg](https://drive.google.com/open?id=15yxwcYiSmgK9qq_IjkjPDipq9XJXkRU_)

### ToCChapterNumber - Same for Appendix
font-family: [Noto Sans](https://fonts.google.com/specimen/Noto+Sans),
font-weight: bold,
font-size: font-scale(0): 8.25pt, 11px, 1rem
color: B2 `#1E7E91`

TocChapterNumberOutline (this is for the box that goes around the number
box line weight: 0.75px (0.682rem)
padding: 5px (0.4545 rem)
color: B2 `#1E7E91`

### ToCPrefaceLink - same for Index, Answer Key, EOB material
font-family: Noto Sans,
font-weight: bold,
font-size: font-scale(1): 9.9pt, 13.2px, 1.2rem
color:  B2 `#1E7E91`

### Modules
Line next to chapter contents
width: 0.2727rem (3px)
color: Grey1 `#F1F1F1`
padding between line and module: 0.5rem

Module title, number, Introduction, EOC, page number
font-family: noto sans
font-size: font-scale(0): 8.25pt, 11px, 1rem
color: `#000000`

page numbers are the same but with about 2 rem in between module title and page number

### Alternating background color
colors: `#FFFFFF` and Grey 2: `#F9F9F9` 

Starts with `#FFFFFF`

### Screenshot for reference
<img width="1021" alt="Screen Shot 2020-04-01 at 4 24 24 PM" src="https://user-images.githubusercontent.com/11299125/78188116-4e104800-7435-11ea-9a9f-b91640f61311.png">
** Colors might differ please consult specs above

**Comment by wilkus27** [comment]
@larissa I marked where we need information about margin/padding:

![image](https://user-images.githubusercontent.com/40228854/82032868-29e29080-969c-11ea-93b2-a47c2a983ba4.png)

**Comment by wilkus27** [comment]
I'm not sure at this moment what will be the best solution to apply styles for chapters with white background. If we decide to treat this element like those chapters with grey background, probably such paddings/margins are needed fot those parts of TOC:

![image](https://user-images.githubusercontent.com/40228854/82034617-b726e480-969e-11ea-82e7-d886b3cdc1e7.png)

**Comment by lwtchu** [comment]
ALL MARGINS in the book should be 1 inch left and right, 0.8 top and bottom - i think this should be the same as the carnival theme (with the exception of the splash openers with the chapter outlines in the margin)

Let's keep the padding between elements at 1 rem for now. Would line height play a factor in this also?

**Comment by wilkus27** [comment]
Thank you! :slightly_smiling_face: 
Yes, line height also have impact on spacing. Subtraction of line height and font size make additional space.

We need also information about paddings in container which I marked by red frame.

**Comment by lwtchu** [comment]
@wilkus27 let's do 1rem for now! if we need to make it smaller, I'll let you know.

**Comment by wilkus27** [comment]
@lwtchu This is how it looks after adding styles:

![image](https://user-images.githubusercontent.com/40228854/82814425-747fbc00-9e97-11ea-91b1-0618202ec851.png)

![image](https://user-images.githubusercontent.com/40228854/82814457-82cdd800-9e97-11ea-9eee-4576c0d984ce.png)

What do you think? Is it ok or should I modify something.
Here are the specs which I applied: 

#### Main title
```
font-size: 1.44rem;
  line-height: 1.5rem;
  color: #093D4C;
  font-family: Roboto Slab, serif;
  margin: 0;  
```

#### Main title icon
```
height: 2.8rem;
  width: 2.8rem;
  padding-right: 8px;
  bottom: -0.7rem;
```
#### Top level list
```
list-style: none;
  margin-left: 0;
```
#### Top level list item
```
padding-top: 0.7rem;
  padding-bottom: 0.7rem;
```
#### Top level link
```
font-family: Noto Sans, sans-serif;
  color: #1E7E91;
  font-size: 1.2rem;
  line-height: 1.5rem;
  font-weight: bold;
  text-decoration: none;
  padding-left: 32px;
  margin-left: 8px;
```
#### Top level link page number
```
margin-left: 8px;
```
#### Chapter and Appendix number
```
font-size: 1rem;
  line-height: 1rem;
  border-style: solid;
  border-width: 0.75px;
  border-color: #1E7E91;
  padding: 5px;
  left: 0;
```
#### Text "Chapter" and "Appendix"
```
display: none;
```
#### Middle level list (composite pages)
```
list-style: none;
  border-left-style: solid;
  border-left-width: 3px;
  border-left-color: #F1F1F1;
  margin-top: 0.7rem;
  margin-bottom: 0.7rem;
  margin-left: 32px;
  padding-left: 8px;
```
#### Middle level link
```
color: #000000;
  font-size: 1rem;
  line-height: 1.5rem;
  text-decoration: none;
```
#### Middle level link page number
```
margin-left: 8px;
```
#### Every second chapter item
```
background-color: #F9F9F9;
```
#### Composite chapter list (compound composite pages in EOC and in Answer Key)
```
display: none;
```
For paddings and margins I applied functions `v-spacing` and `h-spacing` created by Helene, that's why there is no `1rem` space anywhere as you suggested. Is it ok for you? Or do you want me to change values which I applied?

**Comment by lwtchu** [comment]
@wilkus27 the roboto slab font looks really wide 🤔 do you mind sending me the PDF if you have the chance. just that page i want to see what font is being embedded and why it's wider than what we have

**Comment by wilkus27** [comment]
@lwtchu Of course, I will send you in direct message.
Also I modify a few things:

![image](https://user-images.githubusercontent.com/40228854/83005857-9ef58480-a011-11ea-8bb3-cccc23de654a.png)

I aligned chapter number and text. Previously they didn't be at the same line. And I moved a little bit list with composite pages to start at the same line as chapter title.

Also I had to change some values from px to rem, to quite travis. 
I changed:

#### Chapter and Appendix number

font-size: 1rem;
  line-height: 1rem;
  border-style: solid;
  border-width: **0.07rem**;
  border-color: #1E7E91;
  padding: **0.5rem**;
  position: absolute;
  left: 0;

#### Middle level list (composite pages)
list-style: none;
  display: inline;
  border-left-style: solid;
  border-left-width: **0.3rem**;
  border-left-color: #F1F1F1;
  margin-top: 0.7rem;
  margin-bottom: 0.7rem;
  margin-left: **40px**;
  padding-left: 8px;

**Comment by lwtchu** [comment]
update: waiting to get PDF with correct fonts rendered

**Comment by wilkus27** [comment]
@lwtchu Here are the screenshots with fixed fonts:

![image](https://user-images.githubusercontent.com/40228854/83257005-c97f4300-a1b3-11ea-85e1-b48e20a611f0.png)

![image](https://user-images.githubusercontent.com/40228854/83257064-e1ef5d80-a1b3-11ea-9fda-de7df69cf7df.png)

**Comment by brittweinstein** [comment]
@wilkus27 please put points on this card

**Comment by lwtchu** [comment]
Awesome! Also checked the PDF I think this can be finalized.

**Comment by MartaSztuka** [comment]
@lwtchu Number boxes shape depends on numbers, do we accept it as it is, or they all should be squares?
![Screenshot from 2020-06-03 12-38-18](https://user-images.githubusercontent.com/47241114/83627396-248bae00-a597-11ea-871e-79878f41a102.png)

**Comment by lwtchu** [comment]
@MartaSztuka good catch - 

@wilkus27 is there a way to set them to equal size (preferably squares)?

**Comment by wilkus27** [comment]
@lwtchu I tried to achieve that and this is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/83767594-20868b80-a67e-11ea-80c7-13c276a19360.png)

![image](https://user-images.githubusercontent.com/40228854/83767687-3ac06980-a67e-11ea-9091-2cde4dc2284a.png)

Is it ok?

**Comment by lwtchu** [comment]
@wilkus27 this looks better thank you!
