### ISSUE TITLE
Additional chapter label in Answer Key

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2061]
In the Answer Key in University Physics additional chapter label occured. This issue regards also other books that have Answer Keys: Microbiology, Chemistry 2e.
Example form University Physics vol1 xhtml file: 
![image](https://user-images.githubusercontent.com/55203598/76976547-657b0b80-6934-11ea-873b-5ddc9a4a6e11.png)

The section headers from Check Your Understanding solutions need to be removed as well.

**Comment by yblock** [comment]
Duplicate header in table of contents as well: "UNIT 1 UNIT 1"

![Screen Shot 2020-03-18 at 10.44.02 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/cb6937c3-4c27-4a8f-a9c9-e6bd08965331)

**Comment by ajluk** [comment]
@yblock thank you! Do you know when that has happened?

**Comment by yblock** [comment]
I'll make a card for CMs to remove hard-coded unit numbers

**Comment by ajluk** [comment]
How it looks now: 
![image](https://user-images.githubusercontent.com/55203598/76982193-d3770100-693b-11ea-8fe7-fab9fcdd2fa6.png)

**Comment by MartaSztuka** [comment]
Chemistry 2e
![Screenshot from 2020-04-06 16-32-22](https://user-images.githubusercontent.com/47241114/78569649-34e80c80-7824-11ea-863c-0801af24e41f.png)
Microbiology
![Screenshot from 2020-04-06 17-23-37](https://user-images.githubusercontent.com/47241114/78575347-82b44300-782b-11ea-88f6-790d1d93bd94.png)
University Physics
![Screenshot from 2020-04-06 17-22-44](https://user-images.githubusercontent.com/47241114/78575380-91025f00-782b-11ea-894f-ce252b5b379b.png)
