### ISSUE TITLE
space saving: reduce font size for para titles in examples and check your understanding

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2063]
<img width="670" alt="Screen Shot 2020-03-18 at 1 49 55 PM" src="https://user-images.githubusercontent.com/11299125/76999303-699f2d00-6924-11ea-8f1a-3ba818f991f7.png">

These are currently at 12pt? Reduce to font-scale(0)

<img width="782" alt="Screen Shot 2020-03-18 at 2 30 35 PM" src="https://user-images.githubusercontent.com/11299125/76999694-0d88d880-6925-11ea-9def-db7956a8d17f.png">
These are at font-scale(1), reduce to font-scale(0)

**Comment by andymuddimer** [comment]
Can we remove the line space below para titles as well? Strategy, Solution and Discussion?

**Comment by MartaSztuka** [comment]
**College Physics** Header font size in exercises issue #2082
![Screenshot from 2020-03-24 11-36-05](https://user-images.githubusercontent.com/47241114/77442801-f184ab80-6dea-11ea-9ac3-0af8239947de.png)
![Screenshot from 2020-03-24 11-57-06](https://user-images.githubusercontent.com/47241114/77442478-bb472c00-6dea-11ea-85c5-201b6f01910a.png)

**Comment by MartaSztuka** [comment]
**HS Physics**
![Screenshot from 2020-03-24 16-47-00](https://user-images.githubusercontent.com/47241114/77446865-3f031780-6def-11ea-9534-e271ecbcd936.png)
