### ISSUE TITLE
answer key check your understanding issues headers

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#2064]
# What happened?

There is odd section number bolding which makes these sections look very confusing. please see screenshot

# Reproducibility Details

- **Does it also happen in an incognito window?**: 
- **Does this happen in one place, a few places, or everywhere?**: all chapter's answer key check your understanding sections

# Environment:

- **Book(s)**: University Physics
- **URL/Server**: https://ce-pdf-spike.s3.amazonaws.com/col12031-latest-production-242.pdf
- **Location (page number, chapter/section)**: Answer Key
- **Suggested nearby searchable text**: "It is probably an underestimate because the density"
- **Browser**: pdf

# Screenshots

![Screen Shot 2020-03-18 at 3.03.56 PM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/38f6fe63-5d51-4d81-a4f2-7f077deca74b)

# Additional notes

Acceptance Criteria: 
1.) font-weight (unbolded)  
2.) spacing 
3.) removal of module titles

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment]
Extra chapter header will be fixed with https://github.com/openstax/cnx-recipes/issues/2061.

I am adjusting this issue to only be about the section bolding.

**Comment by openstaxalina** [comment]
@lwtchu how would you like the section headers, such as 2.1 Scalars and Vectors, styled?

**Comment by lwtchu** [comment]
Section headers should be removed from University PHysics.

**Comment by ajluk** [comment]
This issue has been resolved by https://github.com/openstax/cnx-recipes/pull/2062.

**Comment by wilkus27** [comment]
This will be resolved by https://github.com/openstax/cnx-recipes/pull/2107

**Comment by MartaSztuka** [comment]
College physics vol 1
![Screenshot from 2020-04-16 09-55-23](https://user-images.githubusercontent.com/47241114/79429929-79b03800-7fc8-11ea-9d8b-9b81b58cb190.png)
vol 2
![Screenshot from 2020-04-16 10-06-30](https://user-images.githubusercontent.com/47241114/79430923-f7287800-7fc9-11ea-94e1-be9017e5e737.png)
vol 3
![Screenshot from 2020-04-16 10-19-44](https://user-images.githubusercontent.com/47241114/79432226-d19c6e00-7fcb-11ea-8a10-f76564ee1fd6.png)
