### ISSUE TITLE
Enable all release flags for books from Carnival Theme

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2066]
Books from Carnival Theme should have all release flags enabled.

**Comment by wilkus27** [comment]
### Enabled flags:

1. Chemistry
- `subtitled-examples`
- `several-composite-chapters`
- `toc-eoc-composite-chapter`
- `goodbye-warnings`

2. Anatomy
- `subtitled-examples`
- `several-composite-chapters`
- `toc-eoc-composite-chapter`

3. Biology
- `several-composite-chapters`
- `toc-eoc-composite-chapter`

4. AP Biology
- `several-composite-chapters`
- `table-move-fake-title`
- `toc-eoc-composite-chapter`

5. Microbiology
- `subtitled-examples`
- `several-composite-chapters`
- `table-move-fake-title`
- `goodbye-warnings`

6. College Physics
- `several-composite-chapters`
- `toc-eoc-composite-chapter`

**Comment by MartaSztuka** [comment]
Chemistry

- [ ] subtitled-examples
- [ ] several-composite-chapters
- [ ] toc-eoc-composite-chapter
- [ ] goodbye-warnings

Anatomy

- [ ] subtitled-examples
- [ ] several-composite-chapters
- [ ] toc-eoc-composite-chapter

Biology

- [ ] several-composite-chapters
- [ ] toc-eoc-composite-chapter

AP Biology

- [ ] several-composite-chapters
- [ ] table-move-fake-title
- [ ] toc-eoc-composite-chapter

Microbiology

- [ ] subtitled-examples
- [ ] several-composite-chapters
- [ ] table-move-fake-title
- [ ] goodbye-warnings

College Physics

- [ ] several-composite-chapters
- [ ] toc-eoc-composite-chapter

**Comment by MartaSztuka** [comment]
Chemistry

- [ ] subtitled-examples
- [ ] several-composite-chapters
- [ ] toc-eoc-composite-chapter
- [ ] goodbye-warnings

Anatomy

- [ ] subtitled-examples
- [ ] several-composite-chapters
- [ ] toc-eoc-composite-chapter

Biology

- [ ] several-composite-chapters
- [ ] toc-eoc-composite-chapter

AP Biology

- [ ] several-composite-chapters
- [ ] table-move-fake-title
- [ ] toc-eoc-composite-chapter

Microbiology

- [ ] subtitled-examples
- [ ] several-composite-chapters
- [ ] table-move-fake-title
- [ ] goodbye-warnings

College Physics

- [ ] several-composite-chapters
- [ ] toc-eoc-composite-chapter
