### ISSUE TITLE
answer key display

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#2068]
# What happened?

Some answer key sections such as "Conceptual Questions" have each answer in-line next to the last. This make is hard to use. In the old pdf, each answer is on a new line. 

# Reproducibility Details

- **Does it also happen in an incognito window?**: 
- **Does this happen in one place, a few places, or everywhere?**: Answer Key sections 

# Environment:

- **Book(s)**: University Physics
- **URL/Server**: https://ce-pdf-spike.s3.amazonaws.com/col12031-latest-production-242.pdf
- **Location (page number, chapter/section)**: Answer Key 
- **Suggested nearby searchable text**: "No, neither of these two theories is more"
- **Browser**: PDF

# Screenshots

![Screen Shot 2020-03-19 at 9.08.05 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/89e8bf8b-8667-4faa-bbb2-bcbbcae6dcb0)

# Additional notes

This is from a PDF generated with COPS and the u-physics style on March 18

**Comment by openstaxalina** [comment]
@lwtchu could you confirm you'd like each answer to start on a new line?  
(This is how it was in oer.exports:)
<img width="855" alt="Screen Shot 2020-03-19 at 10 03 16 AM" src="https://user-images.githubusercontent.com/7863733/77081654-f3083b00-69c8-11ea-82d0-7bdbf8c2bb00.png">

**Comment by lwtchu** [comment]
Yes they should start on a new line for easier reading

**Comment by wilkus27** [comment]
Will be resolved with https://github.com/openstax/cnx-recipes/pull/2107

**Comment by MartaSztuka** [comment]
University physics
![Screenshot from 2020-04-16 10-42-14](https://user-images.githubusercontent.com/47241114/79434677-0231d700-7fcf-11ea-8cc0-e7335d5f18b1.png)
![Screenshot from 2020-04-16 10-43-21](https://user-images.githubusercontent.com/47241114/79434752-1d044b80-7fcf-11ea-824d-7e20d1451414.png)
![Screenshot from 2020-04-16 10-43-45](https://user-images.githubusercontent.com/47241114/79434793-2b526780-7fcf-11ea-92d4-f0300e8f94a4.png)
