### ISSUE TITLE
Line breaks in TOC 

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#2069]
# What happened?

In the COPS pdf, if a TOC line is too long, it wraps to the next line; this however, looks weird and not tidy. Could cause confusion (please see example in chapter 12 where the first line looks like it doesn't have a page number). Not sure if the end of the line can be moved to the far right margin so that these breaks don't occur.

NOTE: the "Physics" style was used in COPS

# Reproducibility Details

- **Does this happen in one place, a few places, or everywhere?**: it occurs anytime a TOC entry is too long and needs to wrap to a 2nd line

# Environment:

- **Book(s)**: AP College Physics
- **URL/Server**: Production
- **Location (page number, chapter/section)**: TOC
- **Suggested nearby searchable text**: Contents

# Screenshots

![Screen Shot 2020-03-19 at 10.13.12 AM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/9c983e51-3f2f-473e-97da-fa7f30fd2aab)

**Comment by lwtchu** [comment]
should be fixed with the work helene is working on in https://github.com/openstax/cnx-recipes/issues/2072
