### ISSUE TITLE
Lack of PhET section styling

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#2070]
# What happened?

PhETs in the AP Physics COPS pdf don't seem to have any distinguishing style. It just looks like random floaty text at the end of a section. 

NOTE: the "Physics" style was used in COPs for this pdf

# Reproducibility Details

- **Does this happen in one place, a few places, or everywhere?**: Throughout textbook 

# Environment:

- **Book(s)**: AP Physics
- **URL/Server**: production
- **Location (page number, chapter/section)**: every place a PhET shows up (usually at the end of a section)
- **Suggested nearby searchable text**: "allow for progressive skill improvement"

# Screenshots

![Screen Shot 2020-03-19 at 10.28.56 AM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/54ef2b17-d309-4e73-a2fd-ae6fdcf87f6b)

**Comment by lwtchu** [comment]
I think...the class might be broken on that one. I'll move to our board for investigation

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1551](https://github.com/openstax/content-managers/issues/1551) via [**ZenHub**](https://www.zenhub.com/)
