### ISSUE TITLE
Fizyka: enable all release flags

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2071]
Enable all release flags for Fizyka dla Szkół Wyższych

**Comment by wilkus27** [comment]
- [ ]  toc-labeled-pages
- [ ]  chapter-page-class 
- [ ] toc-numbered-pages
- [ ] appendix-has-numbered-examples 
- [ ] increment-section-counter-for-lo 
- [ ] trash-abstract-in-preface 
- [ ] EOCsection-links 
- [ ] titles-in-examples 
- [ ] module-titled-notes
- [ ] custom-lists
- [ ] groupChapOutlineIntroContent
- [ ] tagSplash
- [ ] toc-title-word
- [ ] give-composites-ids
- [ ] use-title-nodes
- [ ] goodbye-warnings
- [ ] toc-eoc-composite-chapter
- [ ] table-move-fake-title
- [ ] several-composite-chapters
- [ ] subtitled-examples

**Comment by MartaSztuka** [comment]
Tested on https://katalyst01.cnx.org/contents/TqqPA4io@7.1:Y2FZThuY@3/16-1-Fale-biegn%C4%85ce
and baked PDF. Listed flags work as expected.
