### ISSUE TITLE
space saving: carnival theme: make toc full width

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2072]
# What happened?

currently the toc is margin restricted to about half a page for design purposes. we should make these full width to reduce vertical space.

(helene already did this work...didn't see a card for it)

**Comment by MartaSztuka** [comment]
**College Physics**
![Screenshot from 2020-03-24 15-33-46](https://user-images.githubusercontent.com/47241114/77437392-e62e8180-6de4-11ea-8062-4236424741d6.png)

**Comment by helenemccarron** [comment]
![2020-03-24_09-54-11](https://user-images.githubusercontent.com/8514591/77439850-92587400-6db5-11ea-93ef-263e3363e37d.png)

**Comment by helenemccarron** [comment]
@MartaSztuka This is the TOC changes (the screenshot you posted is a chapter outline)

**Comment by MartaSztuka** [comment]
@helenemccarron Yes, thank you, my mistake

**Comment by MartaSztuka** [comment]
**College Physics**
![Screenshot from 2020-03-24 16-54-01](https://user-images.githubusercontent.com/47241114/77447547-17f91580-6df0-11ea-87bb-3fbe4a773b6a.png)

**HS Physics**![Screenshot from 2020-03-24 16-52-36](https://user-images.githubusercontent.com/47241114/77447374-e4b68680-6def-11ea-8acd-f5675cf313f5.png)
**Biology 2e**
![Screenshot from 2020-03-24 16-54-47](https://user-images.githubusercontent.com/47241114/77447647-319a5d00-6df0-11ea-86fd-d3a65ca1cfcb.png)
