### ISSUE TITLE
Cut off Mathml in Appendix AP Physics

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#2075]
# What happened?

Mathml in Appendix tables is getting cut off if it's too long. 

Note: this is in AP Physics, but using the Physics style in COPs

# Reproducibility Details

- **Does this happen in one place, a few places, or everywhere?**: Appendix C

# Environment:

- **Book(s)**: AP Physics
- **URL/Server**: production
- **Location (page number, chapter/section)**: appendix c
- **Suggested nearby searchable text**: "This appendix is broken into several tables"

# Screenshots

![Screen Shot 2020-03-19 at 11.59.30 AM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/07338b50-55ff-4fdd-9ca4-aa18faf5da37)

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1553](https://github.com/openstax/content-managers/issues/1553) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lwtchu** [comment]
Content issue. We'll move this over.
