### ISSUE TITLE
Equations number boxes overlap

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2079]
@helenemccarron @brittweinstein @lwtchu  it happens in random locations, when equations are close, also in EoC Exercises (because of two columns).
1.
![Screenshot from 2020-03-24 11-25-12](https://user-images.githubusercontent.com/47241114/77415186-5ed01680-6dc2-11ea-98fd-64fc9f9e7efd.png)
2.
![Screenshot from 2020-03-24 10-23-17](https://user-images.githubusercontent.com/47241114/77413796-38a97700-6dc0-11ea-9aef-008493e2e318.png)
3.
![Screenshot from 2020-03-24 14-21-52](https://user-images.githubusercontent.com/47241114/77430231-1e30c700-6ddb-11ea-8d5f-9b357ecff502.png)

**Comment by brittweinstein** [comment]
Issue moved to [openstax/content-managers #1560](https://github.com/openstax/content-managers/issues/1560) via [**ZenHub**](https://www.zenhub.com/)
