### ISSUE TITLE
Links bottom margin

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2081]
@helenemccarron @brittweinstein @lwtchu When yt link is at the end of section distance between it and section title is too small.
![Screenshot from 2020-03-24 10-20-51](https://user-images.githubusercontent.com/47241114/77414534-7fe43780-6dc1-11ea-8d69-3a6ff3aea4d4.png)

**Comment by brittweinstein** [comment]
Moving this for the CMs to take a look at.

**Comment by brittweinstein** [comment]
Issue moved to [openstax/content-managers #1561](https://github.com/openstax/content-managers/issues/1561) via [**ZenHub**](https://www.zenhub.com/)
