### ISSUE TITLE
Example headers

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2082]
@helenemccarron @brittweinstein @lwtchu In examples headers for `Solution`, `Strategy` are not consistent.
![Screenshot from 2020-03-24 11-36-05](https://user-images.githubusercontent.com/47241114/77416033-ab682180-6dc3-11ea-9c40-f6b13efa7bb4.png)

**Comment by helenemccarron** [comment]
I'll take care of this today

**Comment by brittweinstein** [comment]
It is possible that this is from outdated content. @helenemccarron will fetch the most recent data and confirm if this is an issue or not.

**Comment by helenemccarron** [comment]
The udpated content fixed a lot of those, I fixed a bug that made them display at font-scale(1) rather than font-scale(0)
![2020-03-24_15-35-46](https://user-images.githubusercontent.com/8514591/77474504-3c9bc000-6de5-11ea-8062-2afb41ed97a3.png)

**Comment by MartaSztuka** [comment]
It's fixed in newest version.
![Screenshot from 2020-03-25 14-34-50](https://user-images.githubusercontent.com/47241114/77542050-e3e02c00-6ea5-11ea-8d08-cb56f884bbf8.png)
