### ISSUE TITLE
page break vs figure caption

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2083]
@helenemccarron @brittweinstein @lwtchu Part of figure caption jumps to next page.
![Screenshot from 2020-03-24 11-48-08](https://user-images.githubusercontent.com/47241114/77417453-ae641180-6dc5-11ea-8948-0837d5b55c90.png)

**Comment by lwtchu** [comment]
not ideal but i dont think we need to fix this cause it might cause unnecessary increase in page count
