### ISSUE TITLE
Check your understanding

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2084]
@helenemccarron @brittweinstein @lwtchu 
1.Check mark in note is noticeably smaller than in other notes.
2. Should `Solution` header be this big?
![Screenshot from 2020-03-24 11-57-06](https://user-images.githubusercontent.com/47241114/77418481-3bf43100-6dc7-11ea-80cb-5ad9ed9f6659.png)

**Comment by helenemccarron** [comment]
I'll take care of this today

**Comment by brittweinstein** [comment]
This is functioning as it should be.

**Comment by brittweinstein** [comment]
@helenemccarron is taking a look at the "Solution" size.

**Comment by brittweinstein** [comment]
Spec: font-scale 0 line height 0 font-family IBM plex

**Comment by helenemccarron** [comment]
Condensed notes are now one line tall (per #2032 ), and Link to Learning is the only condensed note so it's smaller than  icon notes (2 lines).

Fixed solutions in Link to learning
![2020-03-25_08-27-47](https://user-images.githubusercontent.com/8514591/77541327-87afe480-6e72-11ea-8475-f00aeb8d86c4.png)

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-03-25 16-41-05](https://user-images.githubusercontent.com/47241114/77555376-789f5580-6eb7-11ea-86ac-ffb5b0a2044c.png)
