### ISSUE TITLE
EoC Exercises

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2085]
@helenemccarron @brittweinstein @lwtchu Number 42 should be one line higher, could be content issue?
![Screenshot from 2020-03-24 12-05-13](https://user-images.githubusercontent.com/47241114/77419155-3d722900-6dc8-11ea-8737-17f9c2f4e3b4.png)

**Comment by helenemccarron** [comment]
@lwtchu this looks like a header within the EOC, probably is content related.

**Comment by lwtchu** [comment]
changed it on prod
