### ISSUE TITLE
Equation number box overlapping with text 

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2088]
As decided on 3/24/20, we will fix this in the PDF to get this to the printer. However, this is still a remaining issue to be fixed in Styles: 
![Screen Shot 2020-03-24 at 9.39.00 AM.png](https://images.zenhubusercontent.com/5a01faba8a75884b90866af7/68493b2f-21e0-4b46-a9e3-c0884d42471f)

**Comment by lwtchu** [comment]
Need to give new design specs. Waiting until storm is over

**Comment by lwtchu** [comment]
- Remove the box
- Muli
- font-scale(0)
- Bold
- R3:    `#C31427`

Basically should match figure numbers.

**Comment by MartaSztuka** [comment]
@wilkus27 College Physics
![Screenshot from 2020-04-15 14-13-08](https://user-images.githubusercontent.com/47241114/79336010-46679d80-7f23-11ea-8a9b-734fb8a1ac30.png)
Fizyka dla szkół wyższych tom 1 - equations number is still in frame, when equation has background.
![Screenshot from 2020-04-15 14-30-01](https://user-images.githubusercontent.com/47241114/79337376-af501500-7f25-11ea-9f9b-5185c8140f15.png)

**Comment by wilkus27** [comment]
Thank you @MartaSztuka for notice that! Let me fix it :wink:

**Comment by MartaSztuka** [comment]
Fizyka vol 1
![Screenshot from 2020-04-20 11-44-42](https://user-images.githubusercontent.com/47241114/79738399-fad73a00-82fc-11ea-93c3-5792f9d939ce.png)
University physics
![Screenshot from 2020-04-20 12-05-26](https://user-images.githubusercontent.com/47241114/79740008-4854a680-82ff-11ea-9013-444775e34f00.png)
