### ISSUE TITLE
Exercise number

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2091]
@helenemccarron @brittweinstein @lwtchu When exercise start with figure (without caption) number is bottom aligned.
![Screenshot from 2020-03-25 10-58-37](https://user-images.githubusercontent.com/47241114/77525432-50006700-6e89-11ea-8dfe-f39715b95e13.png)

**Comment by helenemccarron** [comment]
It looks like one is a figure, the other one an image, is the discrepancy desired?

**Comment by lwtchu** [comment]
@helenemccarron i'ill fix this in the content ...i think it's cause one is from exercises adn the other is in the content 🙃

**Comment by lwtchu** [comment]
adjsuted in content~!
