### ISSUE TITLE
Equation number box

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2092]
@helenemccarron @brittweinstein @lwtchu Box with number should aligned to right side.
![Screenshot from 2020-03-25 12-02-48](https://user-images.githubusercontent.com/47241114/77529995-ef752800-6e90-11ea-89a9-70f8bb4f29d0.png)

**Comment by lwtchu** [comment]
There was an empty `<label/>` tag on the equation - removed it and it fixed the probem~!![Screen Shot 2020-03-25 at 12.54.39 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/21676e66-4876-4f27-98ae-1607aa048835)
