### ISSUE TITLE
HS Physics Long equations

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2093]
@helenemccarron @brittweinstein @lwtchu It's the same as #2087 which is fixed on production and closed. It this one fixed too?
![Screenshot from 2020-03-25 12-14-40](https://user-images.githubusercontent.com/47241114/77531058-9dcd9d00-6e92-11ea-8ed6-ed7a8280f612.png)

**Comment by lwtchu** [comment]
fixed this in content ~
