### ISSUE TITLE
Tips for success

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2095]
@helenemccarron @brittweinstein @lwtchu Bullet point jumps outside the box
![Screenshot from 2020-03-25 12-57-55](https://user-images.githubusercontent.com/47241114/77534195-7da0dc80-6e98-11ea-8906-41409a12381b.png)

**Comment by helenemccarron** [comment]
I'll fix it today.

**Comment by helenemccarron** [comment]
fixed in #2090 
![2020-03-25_08-30-34](https://user-images.githubusercontent.com/8514591/77541647-effec600-6e72-11ea-8fa2-ad4ca8126463.png)

**Comment by lwtchu** [comment]
<img width="610" alt="Screen Shot 2020-03-26 at 12 05 18 PM" src="https://user-images.githubusercontent.com/11299125/77674788-164b6100-6f5a-11ea-8113-d6df866f3c9d.png">
VERIFIED
