### ISSUE TITLE
Section Key Terms

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2096]
@helenemccarron @brittweinstein @lwtchu Terms should be arranged in 5 column.
![Screenshot from 2020-03-25 13-00-50](https://user-images.githubusercontent.com/47241114/77534427-e8521800-6e98-11ea-9d85-a2057207a4ed.png)
![Screenshot from 2020-03-25 14-21-06](https://user-images.githubusercontent.com/47241114/77540828-12f59e00-6ea4-11ea-9d95-bda9909ef369.png)

**Comment by lwtchu** [comment]
these are done manually in the content - closing here
