### ISSUE TITLE
Page break vs headers

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2097]
@helenemccarron @brittweinstein @lwtchu `Problems` should be above `Performace Task` can we make it on one page?
![Screenshot from 2020-03-25 13-31-27](https://user-images.githubusercontent.com/47241114/77536778-2fdaa300-6e9d-11ea-997c-b0969df41965.png)

**Comment by lwtchu** [comment]
i think this is the empty problem section that we are removing in the content - closing ~
