### ISSUE TITLE
Section Key Terms chapter 13

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2099]
@helenemccarron @brittweinstein @lwtchu Section Key terms are centered in one chapter, also there's no space in first line.
![Screenshot from 2020-03-25 14-27-43](https://user-images.githubusercontent.com/47241114/77541528-12a9d280-6ea5-11ea-96ec-7b813895c62b.png)

**Comment by lwtchu** [comment]
there'es no class on it - i'll add it and it should fix
