### ISSUE TITLE
Add Fullwidth Chapter Intro to University Physics

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2100]
Per Larissa's coment here (https://github.com/openstax/cnx-recipes/issues/1938#issuecomment-601304990) University Physics will use Full width Chapter Intro as well.

**Comment by ajluk** [comment]
Changes in TDS:
In **FullWidthChapterIntro**  shape there is a need to set book specific color for **University Physics** in these components:
**SplashFigureBg** (cell L.126)
background-color: B5, 
**OutlineTitle** (cell L.138)
color: B5, 
**Outline** (cell L. 137)
border-bottom-color: B5, 
**OutlineTitleBottomBorder**  (cell L. 139)
border-bottom-color: B5,

In the **Chapter Intro** shape book specific color set for University Physics need to be removed from components:
**SplashFigureBg** (cell L.101)
**OutlineTitle** (cell L.111)
**Outline** (cell L. 110)

**Comment by MartaSztuka** [comment]
Tested on branch `carnival100`
1. ![Screenshot from 2020-03-31 15-07-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/824bf47f-96f0-490c-b24c-591672fa313f)
2. ![Screenshot from 2020-03-31 15-30-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0cdb184d-1e8b-40f7-b801-61e27b41f62b)
3. ![Screenshot from 2020-03-31 15-31-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a169f894-bf25-49cc-aa83-a825c5f8b5b4)
