### ISSUE TITLE
Illustration sticks out

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2101]
@helenemccarron @brittweinstein @lwtchu picture in preface is too big
![Screenshot from 2020-03-25 16-02-08](https://user-images.githubusercontent.com/47241114/77551433-9fa75880-6eb2-11ea-8254-4dfbc9a01cf4.png)

**Comment by lwtchu** [comment]
will get to this today! ~

**Comment by lwtchu** [comment]
resized these
