### ISSUE TITLE
Visual Connection Questions 

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2102]
@helenemccarron @brittweinstein @lwtchu
1. It look's like double numbering; numbers and abc-s
2. Text and numbers should be inline.
![Screenshot from 2020-03-25 16-11-41](https://user-images.githubusercontent.com/47241114/77552365-b9956b00-6eb3-11ea-82ad-e83fd25ed328.png)

**Comment by lwtchu** [comment]
this isn't ideal..but i'm not sure if there's a good way to fix it since tables have been...difficult lately. i say close this card. if we get a lot of errata or complaints, we can revisit.
