### ISSUE TITLE
Dotted Line in TOC

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#2105]
# What happened?

The dotted line following the chapter name that leads up to the page number is not part of the carnival design and should be removed. 

# Reproducibility Details

Occurs in all carnival themed books

# Environment:

- **Book(s)**:
- **URL/Server**: 
- **Location (page number, chapter/section)**:
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots

<img width="1652" alt="Screen Shot 2020-03-25 at 11 36 11 AM" src="https://user-images.githubusercontent.com/24909007/77561685-07e34380-6e8d-11ea-975a-b05c3482d05f.png">

# Additional notes

**Comment by ajluk** [comment]
Changes in TDS:
In **No unit ToC** and **Unit ToC** shapes 
In **TocChapterLinkPage** component (cells B11, B78) changes in the below properties (the rest stay the same):
 content: "target-counter(attr(href), page)",
 display: inline-block,
 margin-left: 3rem,
In **TocReferencesLinkPage** component (cell B26) changes in the below property 
 content: "target-counter(attr(href), page)",
and these two properties needs to be added to above component:
 display: inline-block,
 margin-left: 3rem,

**Comment by MartaSztuka** [comment]
College Physics
![Screenshot from 2020-04-02 14-56-30](https://user-images.githubusercontent.com/47241114/78251823-2e8b2500-74f2-11ea-9976-5a5a86abf841.png)
HS Physics
![Screenshot from 2020-04-02 15-26-53](https://user-images.githubusercontent.com/47241114/78254573-698f5780-74f6-11ea-9d28-4937d19c3bc9.png)
Biology 2e
![Screenshot from 2020-04-02 15-27-27](https://user-images.githubusercontent.com/47241114/78254619-7dd35480-74f6-11ea-9b38-0f5bf8a6ee79.png)
