### ISSUE TITLE
Table in Chapter Summary

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2109]
@helenemccarron @brittweinstein @lwtchu This table is too wide
![Screenshot from 2020-03-26 13-33-58](https://user-images.githubusercontent.com/47241114/77647891-83192800-6f67-11ea-9c34-8378f9960741.png)

**Comment by lwtchu** [comment]
Don't have to fix for this release. Maybe later, we can look into more table solutions?

**Comment by MartaSztuka** [comment]
Issue to be tested again when `continue cleanup` is merged.
![Screenshot from 2020-04-03 15-45-08](https://user-images.githubusercontent.com/47241114/78367297-1da9e480-75c2-11ea-886a-bfd05a653ada.png)

**Comment by wilkus27** [comment]
@MartaSztuka I think it's ready for testing.

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-04-20 16-09-23](https://user-images.githubusercontent.com/47241114/79761145-5c110480-8321-11ea-904f-6754f0dff790.png)
