### ISSUE TITLE
Footnote page breaks

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2110]
@helenemccarron @brittweinstein @lwtchu One Footnote breaks in two on two pages.
![Screenshot from 2020-03-26 13-45-24](https://user-images.githubusercontent.com/47241114/77648273-266a3d00-6f68-11ea-8d56-b96d6db3aa04.png)
![Screenshot from 2020-03-26 13-45-17](https://user-images.githubusercontent.com/47241114/77648275-279b6a00-6f68-11ea-9a96-fb9d6ac115ea.png)

**Comment by lwtchu** [comment]
This will have to be fixed - if we can't make it to this release, please let me know so i can make a note on our release card to manually move it

**Comment by openstaxalina** [comment]
@lwtchu just noting here that this seems to be AP Bio, not Biology 2e. Perhaps it does not need to be manually fixed in that case.

**Comment by lwtchu** [comment]
@openstaxalina i was just about to update 😂  i realized now that it's ap biology. JUST KIDDING 😬

**Comment by MartaSztuka** [comment]
@openstaxalina @lwtchu It's Biology 2e, not Ap! Lot mi fix this label right now, Sorry!

**Comment by MartaSztuka** [comment]
tested on `carnival100` branch.![Screenshot from 2020-04-03 15-48-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dc9d16f3-f040-4f42-88a3-d535bf8e0b56)
Footnote is in one piece, but isn't styled properly, another issue is opened #2152
