### ISSUE TITLE
Missing Figure

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2113]
@helenemccarron @brittweinstein @lwtchu Figure 41.15 is gone.
1. Old version PDF (baked on g.g branch)
![Screenshot from 2020-03-26 13-59-44](https://user-images.githubusercontent.com/47241114/77649452-2e2ae100-6f6a-11ea-9657-bd462ca63d56.png)
2. PDF I've got for regression testing
![Screenshot from 2020-03-26 13-59-28](https://user-images.githubusercontent.com/47241114/77649459-2f5c0e00-6f6a-11ea-8a9d-559311f9f16c.png)

**Comment by lwtchu** [comment]
fixed~ thanks for catching this
