### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2115]
@helenemccarron @brittweinstein @lwtchu What's happend to this table, is that right?
1. This is PDF for regression ![Screenshot from 2020-03-26 16-11-25](https://user-images.githubusercontent.com/47241114/77662989-d649a580-6f7c-11ea-8240-9d32e9e8cae4.png)
2. This is old Pdf ![Screenshot from 2020-03-26 16-13-49](https://user-images.githubusercontent.com/47241114/77662988-d5187880-6f7c-11ea-8ec8-e503349dc5fd.png)

**Comment by lwtchu** [comment]
This was an errata change.
