### ISSUE TITLE
Figure too big

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2116]
@helenemccarron @brittweinstein @lwtchu it's big
![Screenshot from 2020-03-26 11-34-34](https://user-images.githubusercontent.com/47241114/77668411-a9e55780-6f83-11ea-8c03-830735b73372.png)

**Comment by lwtchu** [comment]
<img width="590" alt="Screen Shot 2020-03-26 at 11 17 39 AM" src="https://user-images.githubusercontent.com/11299125/77669870-6d016c80-6f53-11ea-8f05-5c0d2b70204a.png">
fixed
