### ISSUE TITLE
Doubled Config_SetTableCaption sectting in config.scss file College Physics

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2118]
I have found that the table caption config settings for tables in College Physics config.scss file are doubled:
![image](https://user-images.githubusercontent.com/55203598/77675006-b1f5c500-6f8c-11ea-986a-d4bd82851ea1.png)

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-04-02 14-55-26](https://user-images.githubusercontent.com/47241114/78251725-0bf90c00-74f2-11ea-8c6e-7a24c96e9780.png)
