### ISSUE TITLE
Equation in new line

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2121]
@helenemccarron @brittweinstein @lwtchu In 8.1, first bullet piont, `p=mv` doesn't need to start in new line.
![Screenshot from 2020-03-27 12-12-52](https://user-images.githubusercontent.com/47241114/77750691-8d4d2c00-7024-11ea-9a48-d07ac2012d16.png)

**Comment by lwtchu** [comment]
similar to display vs inline math issue...will add to that existing issue on cm board

**Comment by lwtchu** [comment]
oops i g ot the issues mixed up..but theyre both on here: https://app.zenhub.com/workspaces/content-management-5c86d8c40b66e07993f45cfa/issues/openstax/content-managers/1564
