### ISSUE TITLE
Section Key Terms

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2122]
@helenemccarron @brittweinstein @lwtchu Space between list and Section Key Terms header could be bigger.
![Screenshot from 2020-03-27 12-27-48](https://user-images.githubusercontent.com/47241114/77751671-68f24f00-7026-11ea-98b6-3c42f52f38ca.png)

**Comment by lwtchu** [comment]
it looks about consistent with the other spacing so i'm going to close this card since a lot of work was implemented on the changes to spacing and i'm reluctant to introduce anything new
