### ISSUE TITLE
Bigger font in Chapter review

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2124]
@helenemccarron @brittweinstein @lwtchu In exercise 15 suddenly numbers are bigger.
![Screenshot from 2020-03-27 13-18-02](https://user-images.githubusercontent.com/47241114/77755512-b920df80-702d-11ea-9870-c2cdaa1208b6.png)
also here: 
![Screenshot from 2020-03-27 13-31-02](https://user-images.githubusercontent.com/47241114/77756369-529cc100-702f-11ea-89a5-6858808523ad.png)
Should I find all locations?

**Comment by lwtchu** [comment]
this is math font vs regular font. it's fine :)
