### ISSUE TITLE
Missing space

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2126]
@helenemccarron @brittweinstein @lwtchu There should be space between figure link and (a), (b).
![Screenshot from 2020-03-27 13-43-15](https://user-images.githubusercontent.com/47241114/77757218-1b2f1400-7031-11ea-8ef4-9b3cf5d20fa7.png)

**Comment by lwtchu** [comment]
this is content moving over

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1565](https://github.com/openstax/content-managers/issues/1565) via [**ZenHub**](https://www.zenhub.com/)
