### ISSUE TITLE
Missing unit

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2127]
@helenemccarron @brittweinstein @lwtchu Looks like somethig should be before `.810m/s2`, well this might be correct, not sure. Also number size, but it's another issue.
![Screenshot from 2020-03-27 13-52-47](https://user-images.githubusercontent.com/47241114/77758118-b2e13200-7032-11ea-93c8-7a2f0183195f.png)

**Comment by lwtchu** [comment]
problably display vs inline math. moving to content manager board

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1564](https://github.com/openstax/content-managers/issues/1564) via [**ZenHub**](https://www.zenhub.com/)
