### ISSUE TITLE
Practice problem with solution

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2128]
@helenemccarron @brittweinstein @lwtchu Practice problems shouldn't come with Solutions
![Screenshot from 2020-03-27 14-08-14](https://user-images.githubusercontent.com/47241114/77759531-23894e00-7035-11ea-80ed-dc219773dc25.png)

**Comment by lwtchu** [comment]
these were present when we sent the PDF to final QA. not an error.
