### ISSUE TITLE
Table has width set in the content.

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2133]
In AP Biology one of the tables in Critical Thinking Questions exercises in Chapter 12 has set width in the content to 50%: 
![image](https://user-images.githubusercontent.com/55203598/78016743-80de1180-734b-11ea-9bf8-a247f40398d4.png)
what cause that in pdf file it looks like this:
![image](https://user-images.githubusercontent.com/55203598/78016696-702d9b80-734b-11ea-9a7f-7a627584b3f8.png)
![image](https://user-images.githubusercontent.com/55203598/78017049-ff3ab380-734b-11ea-9c54-9f87c04605ce.png)
After fetching the new content from katalyst01 the problem still exists.

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1596](https://github.com/openstax/content-managers/issues/1596) via [**ZenHub**](https://www.zenhub.com/)
