### ISSUE TITLE
Fizyka ToC

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2134]
Page numbers in Table of Content should be all right aligned.

**Comment by brittweinstein** [comment]
@MartaSztuka please provide a screenshot and/or specs. Paulina may need to provide input here.

**Comment by MartaSztuka** [comment]
Something like this (example mede of hs physics)
![Screenshot from 2020-04-06 17-14-23](https://user-images.githubusercontent.com/47241114/78574664-99a66580-782a-11ea-84cd-9ff644b86863.png)

**Comment by brittweinstein** [comment]
@MartaSztuka can you provide a screenshot of the problem?

**Comment by MartaSztuka** [comment]
1.
![Screenshot from 2020-04-17 11-07-50](https://user-images.githubusercontent.com/47241114/79552786-cdd81c80-809b-11ea-9646-3d815505405a.png)
2.
![Screenshot from 2020-04-17 11-10-35](https://user-images.githubusercontent.com/47241114/79553019-27404b80-809c-11ea-9033-805a55df60ea.png)
3.
![Screenshot from 2020-04-17 11-16-30](https://user-images.githubusercontent.com/47241114/79553543-edbc1000-809c-11ea-80d6-c0f0349025ac.png)

**Comment by MartaSztuka** [comment]
![Screenshot from 2020-04-20 11-33-05](https://user-images.githubusercontent.com/47241114/79736887-ca8e9c00-82fa-11ea-8d80-70c421fe8952.png)

**Comment by MartaSztuka** [comment]
Fizyka vol 1![Screenshot from 2020-04-22 15-07-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/527ed8ec-3023-410a-ac41-c835bb3d880c)
