### ISSUE TITLE
Fizyka EoC

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2135]
In two columns exercises right one should start an the same baseline as First line not chapter header.
How it is: ![Screenshot from 2020-04-01 15-12-52](https://user-images.githubusercontent.com/47241114/78141095-48156980-742b-11ea-9189-e14c9f842a70.png)
How it should be:
![Screenshot from 2020-04-01 15-16-26](https://user-images.githubusercontent.com/47241114/78141454-cc67ec80-742b-11ea-9370-0b9336981ced.png)
(Example from HS Physics)

**Comment by brittweinstein** [comment]
assigning to @lwtchu and @andymuddimer to assess.

**Comment by MartaSztuka** [comment]
There is another approach to the issue.
Don't change where first line of right column start (there would be gaps).
Separate EoC sections with line to make it more readable.
@wilkus27  what do you think of this?
1.
![Screenshot from 2020-04-17 11-41-38](https://user-images.githubusercontent.com/47241114/79555787-6d97a980-80a0-11ea-9701-d0b494e095ea.png)
2.
![Screenshot from 2020-04-17 11-41-24](https://user-images.githubusercontent.com/47241114/79555789-6f616d00-80a0-11ea-8c85-26dedf6c503b.png)
3.
![Screenshot from 2020-04-17 11-41-13](https://user-images.githubusercontent.com/47241114/79555792-6ffa0380-80a0-11ea-8960-222b658a7c9d.png)
4.
![Screenshot from 2020-04-17 11-41-04](https://user-images.githubusercontent.com/47241114/79555793-70929a00-80a0-11ea-9f6f-06556f31f2cc.png)
5.
![Screenshot from 2020-04-17 11-44-54](https://user-images.githubusercontent.com/47241114/79556095-e434a700-80a0-11ea-8b37-39d7ffec9507.png)

**Comment by MartaSztuka** [comment]
Suggestion to use layout from Chapter outline.
![Screenshot from 2020-04-20 09-44-24](https://user-images.githubusercontent.com/47241114/79727109-256cc700-82ec-11ea-9343-b0c4dec7d662.png)

**Comment by MartaSztuka** [comment]
1.
![Screenshot from 2020-04-22 12-32-41](https://user-images.githubusercontent.com/47241114/79972051-9dc2bc00-8495-11ea-91b5-29abf6e34dbc.png)
2.
![Screenshot from 2020-04-22 12-36-14](https://user-images.githubusercontent.com/47241114/79972219-e2e6ee00-8495-11ea-907c-430598305e55.png)

**Comment by wilkus27** [comment]
#### Decision:

![image](https://user-images.githubusercontent.com/40228854/80071605-38c69f00-8545-11ea-8e62-2a0c32b0a221.png)

Line is `0.3rem` from the bottom.
Line width: 0.2rem.
Color: book specific.
Space between title and line: `h-spacing(1)` (8px)

**Comment by MartaSztuka** [comment]
Fizyka 1 ![Screenshot from 2020-04-24 13-52-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dea958bc-153e-4a9f-ae98-8f0ad5f025dc)
