### ISSUE TITLE
Clean up: apply new shapes to ap-biology and u-physics

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2137]
To do:

- fix tables in eoc exercises (impact all books with new shapes)
- apply `EOCAssesmentsShape` shape for eoc modules with exercises in AP Biology
- enable ` exercise-first-element` flag for u-physics
- add `ContentExercises` and `GenericEOC` shapes to u-physics
- apply new settings for Key Terms in u-physics
- apply new `EocSummary` and `EocKeyEquations` shapes to u-physics
- apply new `EOCDefaultCompoundComposite` shape for eoc composite chapter in u-physics
-  apply `EOCAssesmentsShape` shape for eoc modules with exercises in u-physics
- fix colors of bands, in appendix and answer key in u-physics
- fix lists in summary (impact all books with new shapes)

**Comment by MartaSztuka** [comment]
AP Biology
![Screenshot from 2020-04-07 12-29-55](https://user-images.githubusercontent.com/47241114/78659384-c3fc2f80-78cb-11ea-97a4-d6bcb6b24a09.png)
![Screenshot from 2020-04-07 13-04-28](https://user-images.githubusercontent.com/47241114/78662243-5d2d4500-78d0-11ea-8f8a-0f92751e77a7.png)
University Physics
![Screenshot from 2020-04-07 13-33-03](https://user-images.githubusercontent.com/47241114/78664469-63252500-78d4-11ea-9bd7-5975959996ba.png)
![Screenshot from 2020-04-07 13-35-01](https://user-images.githubusercontent.com/47241114/78664581-9cf62b80-78d4-11ea-98c8-9d465d497f8b.png)
![Screenshot from 2020-04-07 13-37-50](https://user-images.githubusercontent.com/47241114/78664803-0a09c100-78d5-11ea-945f-abb300dcacda.png)
![Screenshot from 2020-04-07 13-37-29](https://user-images.githubusercontent.com/47241114/78664807-0b3aee00-78d5-11ea-8fe4-ffd5fb1d2d28.png)
![Screenshot from 2020-04-07 13-37-03](https://user-images.githubusercontent.com/47241114/78664808-0bd38480-78d5-11ea-97b2-fdc4d74d30af.png)
![Screenshot from 2020-04-07 13-39-38](https://user-images.githubusercontent.com/47241114/78664908-3faeaa00-78d5-11ea-98af-3abfd497442e.png)
