### ISSUE TITLE
Clean up: apply new shapes to anatomy

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2139]
To do:
- fix title in References
- add `ContentExercises` and `GenericEOC` shapes
- apply `EOCAssesmentsShape` shape for eoc modules with exercises
- apply new `EocSummary` shape
- enable `exercise-first-element` flag

**Comment by brittany-johnson** [comment]
Hi @wilkus27 ! Looks like this issue can be moved to the ready for testing column if you're ready.

**Comment by wilkus27** [comment]
Yes :) I was waiting, because after merging my PR to carnival100 there was problem with checks, so I wanted to resolve it first.

**Comment by MartaSztuka** [comment]
Anatomy doesn't have Summary![Screenshot from 2020-04-07 14-23-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/da44cdc7-fd3e-426b-ae21-baca67470006)![Screenshot from 2020-04-07 14-28-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3e969d19-8826-439a-9454-d3e8d2393438)
