### ISSUE TITLE
Clean up: apply new shapes to microbiology

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2141]
- apply EOCAssesmentsShape shape for eoc modules with exercises in microbiology
- apply new EOCDefaultCompoundComposite shape for eoc composite chapter in microbiology
- remove unused solution title component in the eoc exercises in hsphyscis

**Comment by brittany-johnson** [comment]
Hi @ajluk ! Looks like this issue can be moved to ready for testing if you're ready.

**Comment by MartaSztuka** [comment]
Microbiology
Issue about blue ribbon has been opened; #2181
![Screenshot from 2020-04-09 09-26-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5c2c7d89-38d4-4845-85cd-87966013917b)
