### ISSUE TITLE
corn theme: folio specs

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2143]
font: roboto slab
size: font-scale(-1): 6.89pt, 9.17px, 0.8rem
color: B1:   `#093D4C`
color for intro pages: white `#FFFFFF`
format: same as carnival theme - chapter number and chapter name on one side; module number and name on other side

Footer for the "Access for free at openstax.org" link is also same formatting.

**Comment by ajluk** [comment]
@lwtchu could you provide the color specs for folio for the Introduction Page? On the screenshot you posted in the issue about Splash Image(#1752) it is slightly brighter: 
![image](https://user-images.githubusercontent.com/55203598/82435597-cccc4d80-9a94-11ea-8d61-826639a45231.png)

**Comment by lwtchu** [comment]
@ajluk it's just white `#FFFFFF`. i know it's really difficult to get the intro page folio a different color - I'm ok with it not being there or it disappearing due to the bar.

**Comment by ajluk** [comment]
@lwtchu I have set the font color for folio in Chapter Intro page to white as you suggested above and `#093D4C` for the rest of the pages. Let me know if this is how it should look like: ![image.png](https://images.zenhubusercontent.com/5d808b7f46611c000130dbbd/2be5fb53-87ff-4ff9-8e30-62f7b3d7664b)

**Comment by lwtchu** [comment]
@ajluk this looks good i'll update the top specs
