### ISSUE TITLE
corn theme: main content titles and headers

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2144]
# Main content 

## H1 (Chapter title)
See https://github.com/openstax/cnx-recipes/issues/1752 

## H2 (Module/section title)
font-size: font-scale(3): 14.25pt, 19.01px, 1.7rem
font style: roboto slab
color: B2:   `#1E7E91`

## H3
font-size: font-scale(2): 11.88pt, 15.84px, 1.4rem
font style: roboto slab
color: B2:   `#1E7E91`

## H4
font-size: font-scale(1): 9.9pt, 13.2px, 1.2rem
font style: roboto slab
color: B2:   `#1E7E91`

## H5
font size: font-scale(0): 8.25pt, 11px, 1rem
font style: roboto slab
color: B2:   `#1E7E91`

## Base font 
font size: font-scale(0): 8.25pt, 11px, 1rem
color: black `#000000`
font type: Noto Sans
link colors: B5: `#027EB5`

**Comment by ajluk** [comment]
**Chapter Intro Title** specs: 

![image](https://user-images.githubusercontent.com/55203598/84180602-13a3d680-aa88-11ea-8021-89474fef3b6b.png)
**TitleContainer**
position: relative;
top: 20rem;
z-index: 2;

![image](https://user-images.githubusercontent.com/55203598/84180723-42ba4800-aa88-11ea-937c-6171ed8a9914.png)
**TitleText**
    color: white;
    font-family: Roboto Slab, serif;
    font-size: 1.44rem;
    line-height: 1.5rem;
    font-weight: bold;
    text-transform: uppercase;
    position: relative;
    margin-left: 8rem;
    filter: drop-shadow(2px 2px 4px #000);

**TitlePartText** (hidden word Chapter)
   display: none,

![image](https://user-images.githubusercontent.com/55203598/84180833-739a7d00-aa88-11ea-8678-7789dfa8201e.png)
**TitleNumber**
font-family: Roboto Slab, serif;
font-size: 1.44rem;
line-height: 1.5rem;
color: white;
border-style: solid;
border-width: 0.07rem;
border-color: white;
font-weight: bold;
text-transform: uppercase;
padding: 0.5rem;
position: absolute;
left: 0;
top: 50%;
transform: translate(0, -50%);
width: 2.1rem;
height: 2.1rem;
display: flex;
justify-content: center;
align-items: center;

**Comment by lwtchu** [comment]
@ajluk moving this to in progress until we get headers from the content in place
