### ISSUE TITLE
Clean up: apply new shapes to chemistry

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2145]
To do:
- apply EOCAssesmentsShape shape for eoc module with exercises
- add ContentExercises and GenericEOC shapes 
- apply new settings for Key Terms
- apply new EocSummary and EocKeyEquations shapes
- add headers settings to Appendix

**Comment by MartaSztuka** [comment]
![Screenshot from 2020-04-07 13-50-01](https://user-images.githubusercontent.com/47241114/78665827-b7c99f80-78d6-11ea-8e61-566236cfac84.png)
![Screenshot from 2020-04-07 13-46-59](https://user-images.githubusercontent.com/47241114/78665855-c0ba7100-78d6-11ea-86a7-c5097025b7bd.png)
![Screenshot from 2020-04-07 13-48-19](https://user-images.githubusercontent.com/47241114/78665887-cca63300-78d6-11ea-836c-d61d4e96d547.png)
