### ISSUE TITLE
Subheaders unstyled in the Answer Key in University Physics

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2146]
Subheaders in the Answer Key became unstyled after adding new title components during the cleanup in University Physics (it is caused by missing parent selector `.os-solution-area` for H3:
![image](https://user-images.githubusercontent.com/55203598/78347657-1d4d2180-75a1-11ea-9479-eb0ac3381ee7.png)

**Comment by wilkus27** [comment]
Will be resolved in https://github.com/openstax/cnx-recipes/pull/2107

**Comment by MartaSztuka** [comment]
College physics vol 1
![Screenshot from 2020-04-16 09-49-47](https://user-images.githubusercontent.com/47241114/79429372-b62f6400-7fc7-11ea-8d64-29e874cbeeb8.png)
vol 2
![Screenshot from 2020-04-16 10-05-47](https://user-images.githubusercontent.com/47241114/79430876-e11ab780-7fc9-11ea-8e7e-42faf3b358a5.png)
vol 3
![Screenshot from 2020-04-16 10-17-46](https://user-images.githubusercontent.com/47241114/79432053-9437e080-7fcb-11ea-9bdd-765ae7616d3f.png)
