### ISSUE TITLE
Ribbon in EoB

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2150]
End of Book needs blue ribbon on margin.
![Screenshot from 2020-04-03 12-58-02](https://user-images.githubusercontent.com/47241114/78353680-c5b3b380-75aa-11ea-8dee-ce7a00b5b896.png)

**Comment by brittweinstein** [comment]
This should just require the enabling of the ribbon.

**Comment by MartaSztuka** [comment]
tested ![Screenshot from 2020-04-10 13-11-22](https://user-images.githubusercontent.com/47241114/78987088-42a3d780-7b2d-11ea-8e0e-edb2d33e8935.png)
