### ISSUE TITLE
Footnotes styling

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2152]
Footnotes needs to be styled with full width line and bigger top margine.
screen from carnival100
![Screenshot from 2020-04-03 09-52-38](https://user-images.githubusercontent.com/47241114/78361849-5abda900-75b9-11ea-8f9f-dc1afc12e8f5.png)

**Comment by lwtchu** [comment]
<img width="1159" alt="Screen Shot 2020-04-03 at 3 53 13 PM" src="https://user-images.githubusercontent.com/11299125/78404085-48e10380-75c3-11ea-8e40-acf7a9201f0d.png">
veried here
