### ISSUE TITLE
Reducing duplicate colors in carnival theme

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2154]
Colours of certain elements don't match book's specifics.
e.g. ToC chapter number should have  #0074BC
![Screenshot from 2020-04-03 15-30-45](https://user-images.githubusercontent.com/47241114/78366051-3ca77700-75c0-11ea-8372-db54b5e98a35.png)

**Comment by brittweinstein** [comment]
@lwtchu could you confirm that this is an issue?

**Comment by lwtchu** [comment]
adjusted the spec sheet. should be B5:    #00819A

**Comment by wilkus27** [comment]
I reopen the issue. I asked Marta to create issue about colors in Anatomy, because there are some elements which have different shade of blue. Probably it will be easier to find them in code. So I will list them here when start working on that.

**Comment by Stackblocks** [comment]
# The Issue
Right now there are a number of colors being used in the Carnival Theme that appear to be only very finely differentiated. Ideally we would like to reduce the number of in-play colors to avoid confusion, and also keep our code lean.

# Example Colors (sorted by name)
![2020-04-06_10-37-25](https://user-images.githubusercontent.com/12678235/79887193-f3c53000-83bf-11ea-9698-99692c5a0bf8.png)

# Example Colors (roughly sorted by hue)
![2020-04-06_10-39-41](https://user-images.githubusercontent.com/12678235/79887330-3129bd80-83c0-11ea-839f-756cdcc13d85.png)

**Comment by lwtchu** [comment]
Hope this helps... Let me know if you have any questions or are confused or if you want to double check something with me. 


![image](https://user-images.githubusercontent.com/11299125/79894975-d39b6e00-83cb-11ea-8cf9-b60094c8125c.png)

Y1: `#ECCF48` - confirm this isn't being used. Delete if it isn't being used.
Y2: `#F3BE57` -  confirm this isn't being used. Delete if it isn't being used.

O1: `#E27C4E` - confirm this isn't being used. Delete if it isn't being used.
O2: `#F37541` - KEEP!!!!

R1: `#B32B2F` - confirm this isn't being used. Delete if it isn't being used. - if being used, replace with R3
R2: `#A11F67` - confirm this isn't being used. Delete if it isn't being used. - if being used, replace with R4
R3: `#C31427` - KEEP!
R4: `#B10069` - KEEP!

BR1: `#A5633B` - confirm this isn't being used. Delete if it isn't being used. If there is one, please switch to BR2.
BR2: `#B05E36` -  KEEP!

B1: `#57BCD8` -  Delete if not in use. Replace with B6 if it is in use
B2: `#3172B6` - Replace with B7 `#0074BC`
B3: `#388097` - delete if not in use. replace with B5 if it is in use
B4:  `#00829B` - replace with B5
B5: `#00819A` - KEEP !
B6:    `#0DC0DC` - KEEP!
B7:    `#0074BC` - KEEP!
B8:    `#027EB5` - KEEP! This is the link color.

 G1:    `#99CDBF` - delete if not in use.
G2:    `#6EBB9E` - delete if not in use
G3:    `#84AE52` - Replace with G6
G4:    `#9C9D4A` - delete if not in use
G5:    `#479177` - delete if not in use  - replace with G7 if in use
G6:    `#78B042` - KEEP
G7:   `#1E9575` - KEEP

Grey1: `#EEEAE0` - KEEP
black: `#000000` - KEEP
white: `#FFFFFF` - KEEP

**Comment by Stackblocks** [comment]
Ok, i'll audit the colors and then adjust the numbers down to close any gaps left by removed items. When that's done i'll post the list here for your records.

**Comment by Stackblocks** [comment]
New color list:

O1:    `#F37541`
R1:    `#C31427`
R2:    `#B10069`
BR1:   `#B05E36`
B1:    `#0DC0DC`
B2:    `#0074BC`
B3:    `#00819A`
B4:    `#027EB5`
G1:    `#78B042`
G2:    `#1E9575`
Grey1: `#EEEAE0`
black: `#000000`
white: `#FFFFFF`

**Comment by lwtchu** [comment]
Replaced in dropdown tab and in specs tab. COOL THING: if you copy and paste the format from github over to the sheets, it'll put the color on the cell :)

**Comment by MartaSztuka** [comment]
Colours match specifications.![Screenshot from 2020-04-30 15-59-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/09033a50-ac8e-440a-82a7-03f477601524)
