### ISSUE TITLE
EoC colours

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2155]
Headers and ribbon colours are not consistent.
![Screenshot from 2020-04-03 15-52-06](https://user-images.githubusercontent.com/47241114/78368154-75951b00-75c3-11ea-9d1e-a5d189a8620b.png)

**Comment by lwtchu** [comment]
Can we make sure the EOC headers are B7:    #0074BC

**Comment by brittweinstein** [comment]
@MartaSztuka please verify the specs that Larissa noted above

**Comment by MartaSztuka** [comment]
@brittweinstein It's #00819A (baked on carnival100 branch)
![Screenshot from 2020-04-06 10-14-47](https://user-images.githubusercontent.com/47241114/78537653-18ca7800-77f0-11ea-81f2-b765ccf52cbe.png)

**Comment by MartaSztuka** [comment]
Both ribbon and header is #0074BC
![Screenshot from 2020-04-09 13-21-19](https://user-images.githubusercontent.com/47241114/78889960-05741280-7a65-11ea-96a6-2ee0c12ca456.png)
![Screenshot from 2020-04-09 13-19-11](https://user-images.githubusercontent.com/47241114/78889854-cd6ccf80-7a64-11ea-9ee5-5d4c16913518.png)
