### ISSUE TITLE
Answer Key book specific settings

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2156]
Add Book spec. settings for Answer Key (fix in code, no visible changes).
![Screenshot from 2020-04-03 16-29-13](https://user-images.githubusercontent.com/47241114/78371461-4af99100-75c8-11ea-963d-286a33b1db87.png)

**Comment by brittweinstein** [comment]
@lwtchu and @andymuddimer please provide specs.

**Comment by lwtchu** [comment]
Answers broken out by chapters (As shown in screenshot)

Each answer is on its own line. 

1. Blah blah alhb 
3. Blabh lahblahbalbhablahblahb
   (a) More blahb lahblahblahblah
5. Blabhalbhalbhalbhalbhalhb

**Comment by wilkus27** [comment]
@lwtchu Problems which you mentioned are resolved within https://github.com/openstax/cnx-recipes/issues/2068 and https://github.com/openstax/cnx-recipes/issues/1359. This issue is about book specific settings, like book specific colors.

**Comment by lwtchu** [comment]
@wilkus27 Ah sorry it wasn't clear. What specific specs do you need? The header colors for Chemistry 2e, Microbiology and University Physics?

**Comment by wilkus27** [comment]
All book specific headers colors are predefined in code, so I have all needed informations. Thank you! :relaxed:

**Comment by MartaSztuka** [comment]
University physics
![Screenshot from 2020-04-16 10-10-42](https://user-images.githubusercontent.com/47241114/79431315-8f266180-7fca-11ea-8ecb-29fcab384293.png)
![Screenshot from 2020-04-16 10-11-07](https://user-images.githubusercontent.com/47241114/79431349-9c435080-7fca-11ea-87f3-4a865d181a80.png)
![Screenshot from 2020-04-16 10-20-48](https://user-images.githubusercontent.com/47241114/79432371-fb559500-7fcb-11ea-8f72-df7b2f7cca76.png)
Chemistry
![Screenshot from 2020-04-16 10-41-15](https://user-images.githubusercontent.com/47241114/79434540-d282cf00-7fce-11ea-9f50-27e4e6a8f6bd.png)
Microbiology
![Screenshot from 2020-04-16 11-05-01](https://user-images.githubusercontent.com/47241114/79437220-3064e600-7fd2-11ea-858f-d730f9250c73.png)
