### ISSUE TITLE
Example headers

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2157]
Headers in Example are not consistent, e.g. Answer in different font.
![Screenshot from 2020-04-03 16-30-39](https://user-images.githubusercontent.com/47241114/78371780-b5aacc80-75c8-11ea-81a9-61209e680c85.png)

**Comment by brittweinstein** [comment]
@lwtchu please provide expected specs

**Comment by lwtchu** [comment]
It should match the other headers...
IBM Plex Sans
Font size(0) - 9pt
Bold

**Comment by MartaSztuka** [comment]
![Screenshot from 2020-04-14 13-22-48](https://user-images.githubusercontent.com/47241114/79219725-13ee6f80-7e53-11ea-89a9-9d6c1ea5b59d.png)
