### ISSUE TITLE
Fizyka - paragraph indentation

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2166]
In polish books paragraph indentation should be used.
Something like this
![Screenshot from 2020-04-07 16-06-53](https://user-images.githubusercontent.com/47241114/78678950-e8670480-78e9-11ea-97a4-8d2bd8e7174e.png)

**Comment by brittweinstein** [comment]
@MartaSztuka could you provide a screenshot of the problem?

**Comment by MartaSztuka** [comment]
Fizyka 1![Screenshot from 2020-04-24 12-52-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6e8adccc-a0b7-450d-9c4c-17d66aaf3f7d)
