### ISSUE TITLE
CLEAN UP: answer key

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#2167]
- [x] Remove the `exerciseComponentsDisplay` function, move it to a generic function common folder of some sort if it's still needed.
- [x]  Replace the function with a generic exercise component imported from exercises components
- [x] Remove `AnswerKeyImageComponent` and replace with generic `image` component from the figures/images components. 
- [x] Same with number, is this number necessary, can it be rolled into a generic component?
- [x] Move the shapes out of the component

**Comment by wilkus27** [comment]
@MartaSztuka during clean up I added padding to images/figures which are first elements of exercises/solutions. This padding was defined in code, but by old, not existing function. So please check those places carefully, if it doesn't break anything. This changes, as I said,  affect not only solutions in Answer Key, but also exercises (from regular modules and EOC). Please check them as well.

**Comment by MartaSztuka** [comment]
AP Biology
![Screenshot from 2020-05-26 14-58-19](https://user-images.githubusercontent.com/47241114/82903521-5bdbd880-9f61-11ea-8146-9aab9e5b46e8.png)
Chemistry 2e
![Screenshot from 2020-05-26 15-25-55](https://user-images.githubusercontent.com/47241114/82906252-3f419f80-9f65-11ea-8473-e183205dc278.png)
Chemistry AF
![Screenshot from 2020-05-26 16-31-33](https://user-images.githubusercontent.com/47241114/82913289-6bade980-9f6e-11ea-883e-ef2834954173.png)
HS Physics
![Screenshot from 2020-05-26 15-41-05](https://user-images.githubusercontent.com/47241114/82907784-5bded700-9f67-11ea-957f-25378b3165d2.png)
College Physics
![Screenshot from 2020-05-26 16-21-56](https://user-images.githubusercontent.com/47241114/82912181-0efdff00-9f6d-11ea-9bb7-2b674b748dce.png)
University Physics
![Screenshot from 2020-05-26 16-38-05](https://user-images.githubusercontent.com/47241114/82914029-51c0d680-9f6f-11ea-8476-9334e09b858d.png)
