### ISSUE TITLE
CLEAN UP: Appendix

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#2168]
- [x] Use generic H1 component instead of `appendixTitleComponent`
- [x] Move the h1 component to above the h2

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/80431800-0c4db280-88b8-11ea-8b2d-b57cf046c4e1.png)

**Comment by Stackblocks** [comment]
Testing will be confirming no substantive change between old and new (may want to generate a "before" PDF from another branch), no unexpected regressions.

**Comment by MartaSztuka** [comment]
Appendix looks as expected in all books.
![Screenshot from 2020-05-04 14-06-35](https://user-images.githubusercontent.com/47241114/80964160-ab226380-8e10-11ea-9bc9-c2615a3880af.png)
Colour in Chemistry is replaced to match other Appendices.
![Screenshot from 2020-05-04 14-08-24](https://user-images.githubusercontent.com/47241114/80964259-d3aa5d80-8e10-11ea-84b9-9b5cb40a9901.png)
