### ISSUE TITLE
CLEAN UP: Carnival title markup

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#2169]
All titles should be in titles.scss. The rule for creating titles is: 
Can I use a generic title without a million `OPTIONAL`s?
 - > If yes, use generic existing component
  - >if no, create a custom named title and use that. Add that custom title in the titles.scss along with the other similar titles (i.e `H2Title` would be followed by `H2ChapterOultine` etc.)

- [x] Remove divider in `appendixTitle` from the recipes since we are not using it. Check Appendix title markup for extra space (work may have already been completed)
- [x] Add comments to all levels to describe where to find them/what they do
- [x] Change the h3 in the h4 component in the recipes. Look for the H3s in the EOC that are being treated as H4s by the styles. Component name is `$H4--Link`
- [x] Refactor the appendTitle to be a generic `H1Number` component
- [x] Rename `MainNumber`, `MainDivider` and `MainText` to H1number, H1divider and H1text
- [x] Add h5 support to modules and wherever necessary

**Comment by wilkus27** [comment]
Other things to clean up:

- [ ] create `PageTitlesShape` for titles from `[data-type="page"]` (Preface, regular module, Appendix)
- [ ] create `ChapterTitlesShape` for chapter title
- [ ] create `EocCompositePageTitlesShape` for titles from EOC composite pages, direct children of `[data-type="chapter"]`
- [ ] create `EocCompositeChapterTitlesShape` for titles from EOC composite chapters (they contain composite pages)
- [ ] create `EocCompositeChapterTitlesWithBorderShape` for EOC titles from Polish U-physics (they are styled differently then in American books)
- [ ] create `EobTitlesShape` for titles from EOB (Index, References, Answer Key)
- [ ] remove titles components from Answer Key shapes
- [ ] remove titles components from Appendix shape
- [ ] remove `GenericEOCShape`, `EOCDefaultCompoundComposite` and `EOCCompoundCompositeWithBorder` shapes from `eoc-shapes` file (they are replaced by EOC titles shapes listed above; new shapes are created in `titles-shapes` file)
- [ ] remove titles components from Index shape
- [ ] move `$Preface__Container` component to `titles-components` file and remove `preface-components` file (NOTE: all Preface files should be removed, but there are still lists components in Preface shape, which will be moved to lists shapes in another PR)
- [ ] remove titles components from Preface shape
- [ ] remove titles components from References shape
- [ ] remove titles components from `ChapterModuleTitlesShape` (NOTE: there are two new shapes, one for chapter title and another for titles from pages; this one should be removed, but still contains lists components, which will be moved in different PR)
- [ ] remove titles components settings from all `-settings` files different then `titles-settings` file
- [ ] clean up `book.scss` files (remove includes of old shapes and settings for them; add book specific settings for components from new shapes)

**Comment by wilkus27** [comment]
@lwtchu There was a little mess with paddings/margins in Apenndix title. 

This is how it looked before clean up:

![image](https://user-images.githubusercontent.com/40228854/111175688-f668df00-85a8-11eb-8066-5d042696a460.png)

And here is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/111175878-20220600-85a9-11eb-8a23-92573ce2dede.png)

Spaces are smaller. I set v-spacing(2) (1.4rem) under blue part and v-spacing(1) (0.7rem) under and above line. I based on the specs for Answer Key title: 

![image](https://user-images.githubusercontent.com/40228854/111177139-41372680-85aa-11eb-883d-f87aafe93b03.png)

There is 1.4rem after entire title and 0.7rem above line.

Let me know if I should apply different values for Appendix title.

**Comment by lwtchu** [comment]
@wilkus27 i think sometime last year helene implemented some drastic spacing reduction to save pages - is it possible to leave it as the smaller values?

**Comment by wilkus27** [comment]
The smaller values are the new ones (I'm adding them in my PR). First screenshot shows how it looked before (with code from the e.e). So is it ok I decreased values? I should keep them, right?

**Comment by lwtchu** [comment]
@wilkus27 yes it's better to have the smaller values :) thank you natalia

**Comment by wilkus27** [comment]
### Infrormation for tester

There was a problem with selectors in components and settings for H2 from EOC overwrote settings for H2 from EOB:

![image](https://user-images.githubusercontent.com/40228854/111316387-810e1480-8663-11eb-943f-8d92833d629f.png)

It's fixed now:

![image](https://user-images.githubusercontent.com/40228854/111316517-9f741000-8663-11eb-9209-525a0e11b009.png)

**Comment by MartaSztuka** [comment]
#### PASSED
##### Microbiology![Screenshot from 2021-03-24 12-32-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/82e0789c-a650-4684-922f-bc567c236647)
##### Chemistry 2e![Screenshot from 2021-03-24 14-22-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/89f16c07-8567-483a-9fd0-a16bb7d9c8e6)
##### University Physics vol 1![Screenshot from 2021-03-24 13-02-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4b99250f-f3da-4cae-b4ae-fbc236db4cce)
