### ISSUE TITLE
corn theme - condensed icon with no title note

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2179]
These are for items like the Be Prepared, Try Its or Checkpoints.
<img width="388" alt="Screen Shot 2020-04-08 at 12 33 23 PM" src="https://user-images.githubusercontent.com/11299125/79149914-8432bd80-7d8d-11ea-9a4e-e79a9dc501dc.png">
<img width="549" alt="Screen Shot 2020-04-08 at 12 27 29 PM" src="https://user-images.githubusercontent.com/11299125/79149916-84cb5400-7d8d-11ea-9869-c7a5bdd179d9.png">

 
## Icons
Be Prepared -  https://drive.google.com/open?id=1rBbF8rHn-hObbi6e317hukZQx3shUq_1
Try It - https://drive.google.com/open?id=1d5-2oB2rBjRZGEF98_w47v6Fnh5xgC75
Width/Height: 16px - 1.45rem

## Title text (generated with the class)
Font: Noto Sans
Treatment: Bold
Color: B1:   `#093D4C`
Size: font-scale(0)

## Numbering and problem text
Font: Roboto Slab for numbering; NOto sans for Text
Color: Grey3:   `#757474` 
Size: font-scale(0)
Spacing from number: 2rem 
Note: problem text is aligned with the Try It/Be Prepared title and numbering

## Numbering and answer collation (if applicable) 
- Each class should have their own numbering scheme of Chapter#.Exercise# (Chapter 1 try its will be 1.1, 1.2, 1.3 etc. Chapter 1 Be prepared will be 1.1, 1.2, 1.3)
- Answers collate to the Answer Key with their own titled section
<img width="764" alt="Screen Shot 2020-04-08 at 4 06 09 PM" src="https://user-images.githubusercontent.com/11299125/78833679-e2892600-79b2-11ea-83e4-de94511df6d4.png">

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/83508631-7b778180-a4ca-11ea-8e1a-03d74ca55a92.png)

and here there are applied specs:

#### Note
margin-bottom: 1.4rem;

![image](https://user-images.githubusercontent.com/40228854/83509188-59caca00-a4cb-11ea-8e29-49011a047b2b.png)

#### Icon
height: 1.45rem;
  width: 1.45rem;
  padding-right: 8px;

![image](https://user-images.githubusercontent.com/40228854/83509309-867ee180-a4cb-11ea-90c0-946b1fcf3563.png)


#### Title (label and number)
margin-right: 24px;

![image](https://user-images.githubusercontent.com/40228854/83509351-9ac2de80-a4cb-11ea-8e89-0419bb5e2d56.png)


#### Title label
color: #093D4C;
  font-family: Noto Sans, sans-serif;
  font-size: 1rem;
  line-height: 1.5rem;
  font-weight: bold;
  text-transform: uppercase;
  margin-right: 16px;

![image](https://user-images.githubusercontent.com/40228854/83509407-ad3d1800-a4cb-11ea-870e-2d000049421a.png)


#### Title number
color: #757474;
  font-family: Roboto Slab, serif;
  font-size: 1rem;
  line-height: 1.5rem;

![image](https://user-images.githubusercontent.com/40228854/83509452-bf1ebb00-a4cb-11ea-831b-e6c4871f0ed1.png)


#### Note body
color: #757474;
  font-family: Roboto Slab, serif;
  font-size: 1rem;
  line-height: 1.5rem;

![image](https://user-images.githubusercontent.com/40228854/83509513-d8276c00-a4cb-11ea-9422-ce0daf88c193.png)

Is anything I should change?

**Comment by lwtchu** [comment]
@wilkus27 looks great! but the note body should be noto sans; robot slab was only for the number

**Comment by wilkus27** [comment]
@lwtchu Thank you for noticing that! :slightly_smiling_face: Here is the screenshot with proper font:

![image](https://user-images.githubusercontent.com/40228854/83613461-1aac7f80-a584-11ea-8ca8-4b03af12f457.png)

#### Note body
```
color: #757474;
  font-family: Noto Sans, sans-serif;
  font-size: 1rem;
  line-height: 1.5rem;
```

**Comment by lwtchu** [comment]
thank you ! moving back to documentation

**Comment by wilkus27** [comment]
@lwtchu I'm working on Checkpoint note from Calculus. In https://github.com/openstax/cnx-recipes/issues/2241 there is information that label "Checkpoint" should be hidden. This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/88806145-4e84d980-d1b0-11ea-9823-7cad74bed7fe.png)

Is it ok or in this case number should be style differently?

**Comment by lwtchu** [comment]
@wilkus27 this is okay!
