### ISSUE TITLE
Top margin in Equations are missing

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2182]
![Screenshot from 2020-04-09 12-59-19](https://user-images.githubusercontent.com/47241114/78888516-0e171980-7a62-11ea-972d-aa36715c5859.png)

**Comment by brittweinstein** [comment]
@lwtchu can you confirm that this is an issue? I'm thinking maybe it is intentional due to space savings.

**Comment by lwtchu** [comment]
This is intentional. The extra space below the equation are empty `<newline/>` that we will remove in the content.
