### ISSUE TITLE
WAITING FOR VERIFICATION: Fizyka - sections header

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2184]
When header breaks in two lines leading is bigger than space between header and Learning Objectives. 
How it is now: ![Screenshot from 2020-04-09 14-23-53](https://user-images.githubusercontent.com/47241114/78894808-11b09d80-7a6e-11ea-8ee9-8cc5943df8d9.png)
How it looks when space is equal:
![Screenshot from 2020-04-09 14-25-34](https://user-images.githubusercontent.com/47241114/78894843-242ad700-7a6e-11ea-83a3-1b233a848c9f.png)

**Comment by wilkus27** [comment]
Might be resolved within https://github.com/openstax/cnx-recipes/pull/2176. Please verify again, when this PR will be merged to milestone branch.

**Comment by wilkus27** [comment]
@MartaSztuka It's ready for veryfication.

**Comment by MartaSztuka** [comment]
@wilkus27  Issue is fixed, this is how two-line header looks like now:![Screenshot from 2020-04-17 11-22-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a7bfb29f-5b9c-471f-9fcc-fed40c75062d)
