### ISSUE TITLE
developmental math - chapter outline & introduction

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2189]
<img width="858" alt="Screen Shot 2020-04-09 at 3 51 30 PM" src="https://user-images.githubusercontent.com/11299125/78939635-272bc480-7a7a-11ea-8c21-6f129c9a6331.png">

### Chapter Outline text
font style: roboto slab
font size: font-scale(1): 9.9pt, 13.2px, 1.2rem
color: B2:   `#1E7E91`

### Module links/text 
font style: noto sans
font size: font-scale(0)
module title style: normal
module title color: `#000000`
number style: bold, 
number color: default link color for entire library

### Bar next to chapter module titles
Line next to chapter contents
width: 0.2727rem (3px)
color: Grey1 `#F1F1F1`
padding between line and module: 0.5rem

^ Same as TOC

### Introduction 
Icon: https://drive.google.com/open?id=1rZ-FfYEkC_YU6FsPagyUHEx3uswsHyiI
Introduction text follows the module title specs: 
font-size: font-scale(3): 14.25pt, 19.01px, 1.7rem
font style: roboto slab
color: B1:   `#093D4C`

**Comment by ajluk** [comment]
Added specs:

![image](https://user-images.githubusercontent.com/55203598/84176055-26ff7380-aa81-11ea-8954-e700324e1e2d.png)
**OutlineFullWidth**
font-family: Noto Sans, sans-serif;
font-size: 1rem;
font-weight: 500;
line-height: 1.5rem;
margin-bottom: 1.5rem;

![image](https://user-images.githubusercontent.com/55203598/84176113-3c749d80-aa81-11ea-9bc0-2a27b1e8e336.png)
**OutlineTitle**
margin: 0 0 0.5rem 0;
font-size: 1.2rem;
line-height: 1.2rem;
font-family: Roboto Slab, serif;
color: #1E7E91;

![image](https://user-images.githubusercontent.com/55203598/84176521-d0466980-aa81-11ea-85aa-e895ba25000e.png)
**OutlineObjectiveLink**
display: inline-block;
text-decoration: none;
color: #34BDD8;
font-family: Noto Sans, sans-serif;
padding-left: 0.7rem;
border-left-width: 0.2727rem;
border-left-style: solid;
border-left-color: #F1F1F1;

![image](https://user-images.githubusercontent.com/55203598/84176648-fff57180-aa81-11ea-8a2f-79f25db341a4.png)
ChapterOutlineObjectiveText
color: black;

![image](https://user-images.githubusercontent.com/55203598/84176821-4b0f8480-aa82-11ea-82c1-88c3f948a296.png)
**IntroContentHeader**
    font-size: 1.728rem;
    margin-bottom: 0.7rem;
    color: #093D4C;

![image](https://user-images.githubusercontent.com/55203598/84177231-dd178d00-aa82-11ea-844c-7fdba745f019.png)
**IntroductionTitleIcon**
background: url(toDataUri("svg+xml", "designs/corn/resources/corn-introduction.svg")) no-repeat top left;
background-size: contain;
height: 2.8rem;
width: 2.8rem;
display: inline-block;
content: '';

**Comment by lwtchu** [comment]
this looks good thank you

**Comment by MartaSztuka** [comment]
@lwtchu There's difference between colours in specs and on the screen. Now it's styled according to the screen, should it be vice versa?
![Screenshot from 2020-06-29 13-47-40](https://user-images.githubusercontent.com/47241114/86001401-1f434700-ba0f-11ea-8ee3-2003c5f35f0a.png)

**Comment by lwtchu** [comment]
@MartaSztuka sorry i had them switched on accident. thanks for catching! I've updated the specs
