### ISSUE TITLE
developmental math - learning objectives

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2190]
<img width="412" alt="Screen Shot 2020-04-09 at 4 44 02 PM" src="https://user-images.githubusercontent.com/11299125/78943858-475f8180-7a82-11ea-9581-91ce76231dcb.png">

### Learning Objectives text
font size: font-scale(1): 9.9pt, 13.2px, 1.2rem
color: B2:  ` #1E7E91`
font type: roboto slab
font style: bold

### Para & List 
bullet colors: G2:   `#C6CE33`
bullet style: https://drive.google.com/open?id=1cfuGUBck_cc-l9CQi10TDmACimFOmNS0
font style: noto sans
font size: font-scale(0)
treatment for `<para>`: bold
color: `#000000`

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/83406314-ac927c00-a40e-11ea-89ce-a46a3c65216a.png)

Should I change something?

Here are the applied specs:

#### Title
color: #1E7E91;
  font-family: Roboto Slab, serif;
  font-size: 1.2rem;
  line-height: 1.5rem;
  font-weight: bold;

#### Paragraph "By the end..."
font-weight: bold;
  margin: 0;

#### List
margin-left: 8px;
  list-style-type: none;

##### Icon
height: 0.5rem;
  width: 0.5rem;
  margin-right: 8px;
  bottom: 0.1rem;

**Comment by lwtchu** [comment]
<img width="636" alt="Screen Shot 2020-06-01 at 9 00 21 AM" src="https://user-images.githubusercontent.com/11299125/83416701-aa1c2c00-a3e6-11ea-93d3-31238047a444.png">
there's some odd spacing here and there - do you know if that's just the way the pdf is rendering or should we set kerning spacing for the font?

**Comment by wilkus27** [comment]
@lwtchu It's very odd... Even two the same words display differently: 

![image](https://user-images.githubusercontent.com/40228854/83503063-d311ef00-a4c2-11ea-83ba-2ff10a6cb897.png)

This problem occurs in entire book. I will create separate issue for that. Except that, is anything I should change in Learning Objectives?

**Comment by lwtchu** [comment]
@wilkus27 nope! other than that it looks good.
