### ISSUE TITLE
corn theme - no class boxed note

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2191]
<img width="806" alt="Screen Shot 2020-04-09 at 5 19 46 PM" src="https://user-images.githubusercontent.com/11299125/78945607-5c3e1400-7a86-11ea-804f-48dd629a579c.png">

Similar in structure to #1164 where the `<title>` of the note is moved to the top of the box. 

### Boxed note
color: G1:  `#F4F7F4`

### Title 
color: B2:   `#1E7E91`
font type: roboto slab
style: bold
font size: font-scale(0)
where to get content? in the `<title>` of the note

### Line between title and text
height: 1px (0.09rem?)
color: Grey1:   `#F1F1F1`

### Padding
top, left, bottom, right: v-grid(.5)

### Note Body
color: B1 `#093D4C`;
font-family: Noto Sans, sans-serif;
size: font-scale(0)

**Comment by wilkus27** [comment]
@lwtchu Here is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/83642641-645e8f80-a5af-11ea-8d2b-6f4cf205bff0.png)

and applied specs:

### Note
```
margin-bottom: 1.4rem;
```

### Note title
```
color: #1E7E91;
  font-family: Roboto Slab, serif;
  font-size: 1rem;
  line-height: 1.5rem;
  font-weight: bold;
  background-color: #C4CEBB;
  padding: 0.7rem;
  border-bottom-width: 0.09rem;
  border-bottom-style: solid;
  border-bottom-color: #F1F1F1;
```

### Note body 
There is no specs for this element above. This is what I applied. 
Please let me know if I should change something.
```
color: #093D4C; (B1)
  font-family: Noto Sans, sans-serif;
  font-size: 1rem;
  line-height: 1.5rem;
  background-color: #C4CEBB;
  padding: 0.7rem;
```

**Comment by lwtchu** [comment]
oh no the color is wrong - i copied the wrong hex value 😬  please change it to G1:  ` #F4F7F4` i'll update the instances where it's wrong

**Comment by lwtchu** [comment]
I also added the note body text specs up at the top

**Comment by wilkus27** [comment]
@lwtchu This is how it looks with new background color:

![image](https://user-images.githubusercontent.com/40228854/83729184-96bbcb80-a647-11ea-84ed-e2cd703525cc.png)

**Comment by lwtchu** [comment]
@wilkus27 thank you! this looks better we can consider this design final
