### ISSUE TITLE
CLEAN UP: exercises

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#2195]
- [x] Move img to figure components
  -  Is the unique even component needed?
- [x]  H-spacing .5 must be converted to whole number
   - Nice to have: change the typography functions to not accept floats
   - If unique value is required: hard code it and leave a comment as to why it's hard coded (reasons behind the "magic number"
- [x] Move `exercise_table` to tables components, 
  - assess if this component is still required, 
  - set values to OPTIONAL if necessary to combine with another existing component in the the tables components, 
   - leave comments why they are optional if needed
- [x] Move function to functions. 
   - Do we need that function: yes, it is also used in the answer key. 
  - Move the function `problemContainer` to functions.scss, 
  - make sure to implement it in exercises & answer key
  - Remove all shapes from the function. DO NOT USE SHAPES IN FUNCTIONS if they are used for components
- [x]  Move solution title to titles
- [x] Rename `Container_Specific` to `Container_withImageOnTop` or something descriptive
- [x] make a comment about the containers that can be converted to columns (this include the `Exercise__Container` and the `EOCcontainer` to remind us that we have that option, unify naming to BEM in EOC

**Comment by wilkus27** [comment]
Function from point 4 will be implemented to Answer Key within https://github.com/openstax/cnx-recipes/issues/2167

**Comment by MartaSztuka** [comment]
Chemistry 2e
![Screenshot from 2020-05-19 11-54-33](https://user-images.githubusercontent.com/47241114/82312632-9f659e00-99c7-11ea-92fa-c79b4bfd9a7a.png)
Chemistry AF
![Screenshot from 2020-05-19 12-19-26](https://user-images.githubusercontent.com/47241114/82315069-0769b380-99cb-11ea-9728-23449d97fc45.png)
College Physics
![Screenshot from 2020-05-19 12-57-58](https://user-images.githubusercontent.com/47241114/82318589-65e56080-99d0-11ea-8c1f-7550223a4510.png)
Biology 2e
![Screenshot from 2020-05-19 13-10-13](https://user-images.githubusercontent.com/47241114/82319586-1d2ea700-99d2-11ea-8dcf-570d24e63d55.png)
![Screenshot from 2020-05-19 13-09-56](https://user-images.githubusercontent.com/47241114/82319591-1e5fd400-99d2-11ea-9ed5-970732e4924d.png)
AP Biology
![Screenshot from 2020-05-19 13-28-13](https://user-images.githubusercontent.com/47241114/82321120-a050fc80-99d4-11ea-95f4-4baf3a61ad6f.png)
HS Physics
![Screenshot from 2020-05-19 15-00-27](https://user-images.githubusercontent.com/47241114/82329402-8c5fc780-99e1-11ea-88b0-9f81ccc635f7.png)
University Physics
![Screenshot from 2020-05-19 13-06-08](https://user-images.githubusercontent.com/47241114/82319271-8bbf3500-99d1-11ea-82f7-9ff25dea6621.png)
