### ISSUE TITLE
CLEAN UP: Figures and images

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#2196]
- [x] Rename components to follow our conventions
- [x] Fix the `PicCaption`,  you may be able to solve the problem using a generic function that removes the empty element that is problematic.
- [x] Rework the `figureContainer` to be "pure", 
   - a "pure component" does not define global styles for all the components nested inside, only what governs the properties of the component itself (like the ability to convert it into columns)
  - Remove and move to inner components the following:
       ```font-size: font-scale(-1),
       line-height: line-height(0),
       margin-bottom: v-spacing(1),```

**Comment by ajluk** [comment]
@MartaSztuka >>> Information for testing purposes: There should be no visible changes in Figures after the cleaning.

**Comment by MartaSztuka** [comment]
@ajluk Figures become left aligned while should be centered.
AP Biology
before:
![Screenshot from 2020-05-25 13-54-55](https://user-images.githubusercontent.com/47241114/82812384-2a94d700-9e93-11ea-9f89-b69e1623590e.png)
after:
![Screenshot from 2020-05-25 14-21-49](https://user-images.githubusercontent.com/47241114/82812391-2e285e00-9e93-11ea-9857-a98e93ee3f49.png)

**Comment by MartaSztuka** [comment]
Chemistry 2e![Screenshot from 2020-05-29 16-44-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1c017c22-bc18-4154-92ad-831b05e35866)
Chemistry AF![Screenshot from 2020-05-29 16-47-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/73ec5aca-69d9-42b2-8955-f67ec49492fd)
Anatomy![Screenshot from 2020-05-29 16-49-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6b13987c-0b1c-4eb0-b219-3c24235a8fe6)
Biology 2e![Screenshot from 2020-05-29 16-50-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bf986e06-0419-4d46-929f-ac52208a1e79)
AP Biology![Screenshot from 2020-05-29 16-51-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bb141a10-09c1-451b-8c39-30453df7403d)
Concepts of Biology![Screenshot from 2020-05-29 16-52-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/92646bf3-2291-4cc2-8c5c-f4c4f58827df)
Microbiology![Screenshot from 2020-05-29 16-53-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6a0c0d94-8c0d-4ea7-9b97-88b293e2edd0)
College Physics![Screenshot from 2020-05-29 16-54-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/603a0c63-9931-44fd-81a2-c16593544695)
HS Physics!![Screenshot from 2020-05-29 17-06-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/297e963a-236e-4f78-be9e-22a5fe2e029e)
University Physics![Screenshot from 2020-05-29 17-20-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8c206530-3a3b-4c34-808f-75e4db44b502)
