### ISSUE TITLE
CLEAN UP: modules

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#2199]
Move `ModuleParagraphTitleComponent` to the titles components

**Comment by ajluk** [comment]
@brittweinstein This issue will be resolved within this PR: #2279 I have only merged previous PR to another one to resolve clean up issues regarding modules and chapters together.

**Comment by ajluk** [comment]
Information for testing purposes about font-family in Modules and Chapters (form Larissa):

    H2-H5 titles should be all set to Muli except H1 which should be IBM plex sans

**Comment by MartaSztuka** [comment]
**HS Physics**
![Screenshot from 2020-05-14 13-55-58](https://user-images.githubusercontent.com/47241114/81934593-7e7c0200-95ef-11ea-9865-ec57dd93e098.png)
**Chemistry 2e**
![Screenshot from 2020-05-14 14-53-21](https://user-images.githubusercontent.com/47241114/81936488-b0429800-95f2-11ea-8571-f471a52cc5b6.png)
**Chemistry AF**
![Screenshot from 2020-05-14 15-03-28](https://user-images.githubusercontent.com/47241114/81937583-17ad1780-95f4-11ea-8cc2-064de2dd2ae4.png)
**Anatomy**
![Screenshot from 2020-05-14 15-17-59](https://user-images.githubusercontent.com/47241114/81939060-209ee880-95f6-11ea-9113-849db687b6af.png)
**Biology 2e**
![Screenshot from 2020-05-14 15-44-22](https://user-images.githubusercontent.com/47241114/81941971-cf90f380-95f9-11ea-996f-9c5d522f8c58.png)
**AP Biology**
![Screenshot from 2020-05-14 15-58-22](https://user-images.githubusercontent.com/47241114/81943551-d0c32000-95fb-11ea-8161-ad299139540a.png)
**Concepts of Biology**
![Screenshot from 2020-05-14 16-03-46](https://user-images.githubusercontent.com/47241114/81944103-88f0c880-95fc-11ea-866c-fde6dd5a3663.png)
**Microbiology**
![Screenshot from 2020-05-14 16-42-54](https://user-images.githubusercontent.com/47241114/81948407-fc490900-9601-11ea-89d7-95a325a9e226.png)
**College Physics**
![Screenshot from 2020-05-14 17-49-00](https://user-images.githubusercontent.com/47241114/81956151-42569a80-960b-11ea-8558-fcb51eb6325a.png)
**University Physics**
![Screenshot from 2020-05-14 17-54-43](https://user-images.githubusercontent.com/47241114/81956796-053ed800-960c-11ea-830e-7b41d592ab2e.png)
