### ISSUE TITLE
developmental math - icon boxed note

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2200]
<img width="1000" alt="Screen Shot 2020-04-10 at 2 16 24 PM" src="https://user-images.githubusercontent.com/11299125/79017041-fd37d800-7b35-11ea-974b-05b91e2e48c0.png">

### Box
color: Grey4:   `#E7EBED`

### Icon
Link: https://drive.google.com/open?id=1pLSln8K9K8So3lBH_oDntjSRCpgG_gsb

### Title for `<note class="manipulative-math">`
Title: Manipulative Mathematics
Color: B1:   `#093D4C`
Font: Noto Sans
Style: bold
Size: font-scale(0)

### Text
Color: B1:  ` #093D4C`
Font: Noto Sans
Size: font-scale(0)

### Line between title and text
height: 1px (0.09rem?)
color: `#FFFFFF`

### Padding
all around: v-grid(.5)

**Comment by wilkus27** [comment]
@lwtchu This is how it looks after styling:

![image](https://user-images.githubusercontent.com/40228854/83608340-0d3fc700-a57d-11ea-8420-d1607d3e7892.png)

And here are applied specs:

### Note
```
margin-bottom: 1.4rem
```
![image](https://user-images.githubusercontent.com/40228854/83608672-85a68800-a57d-11ea-9204-051fc86f5d3a.png)

### Title
```
color: #093D4C;
  font-family: Noto Sans, sans-serif;
  font-size: 1rem;
  line-height: 1.5rem;
  font-weight: bold;
  text-transform: uppercase;
  background-color: #E7EBED;
  padding: 0.7rem;
  margin-bottom: 0.09rem;
```
![image](https://user-images.githubusercontent.com/40228854/83609114-15e4cd00-a57e-11ea-8211-4bf0dba5ba5e.png)

### Icon
```
vertical-align: middle;
  height: 2.1rem;
  width: 2.1rem;
  margin-right: 8px;
```
![image](https://user-images.githubusercontent.com/40228854/83609206-3745b900-a57e-11ea-8f15-0dce85429c57.png)

### Note body
```
color: #093D4C;
  font-family: Noto Sans, sans-serif;
  font-size: 1rem;
  line-height: 1.5rem;
  background-color: #E7EBED;
  padding: 0.7rem;
```
![image](https://user-images.githubusercontent.com/40228854/83609272-55abb480-a57e-11ea-8e27-56f130e431ff.png)

**Comment by lwtchu** [comment]
looks good i'll move to the documentation tab

**Comment by wilkus27** [comment]
@lwtchu I'm styling now **Link to Literacy** note. In https://github.com/openstax/cnx-recipes/issues/2059 there is information that it should be styled like Icon Boxed note with title, so like note **How To** https://github.com/openstax/cnx-recipes/issues/2208. But I checked and this note don't have subtitle, so I decided to style it like **Manipulative Math** from this issue. This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/84776180-49910f80-afe0-11ea-9cc7-f0b017883556.png)

Is it ok? Should I change something?

**Comment by lwtchu** [comment]
@wilkus27 this is fine. i think that's the wrong...icon though let me remove the border i didn't realize it made its way onto the svg

**Comment by lwtchu** [comment]
@wilkus27 updated the icon here~ https://drive.google.com/open?id=1l6RLBG_UHGrCY6G5EYaFfbSQDCsd7K2V

**Comment by wilkus27** [comment]
@lwtchu That's how it looks with replaced icon:

![image](https://user-images.githubusercontent.com/40228854/84882608-cd560500-b08f-11ea-9d67-bb5661e04ee9.png)

**Comment by lwtchu** [comment]
awesome thank you !

**Comment by wilkus27** [comment]
@lwtchu Based on informations from https://github.com/openstax/cnx-recipes/issues/2267 I styled icon boxed notes from statistics:

![image](https://user-images.githubusercontent.com/40228854/89794278-1f168b00-db27-11ea-9d80-a090c64bd47d.png)

![image](https://user-images.githubusercontent.com/40228854/89794299-29388980-db27-11ea-8c80-24f8fc11fb58.png)

![image](https://user-images.githubusercontent.com/40228854/89794454-58e79180-db27-11ea-8eab-629ef3837a04.png)

Are they ok, or should I changed something? (color of the links from the last screenshot will be changed in another PR)

**Comment by lwtchu** [comment]
@wilkus27 looks good thank you :)
