### ISSUE TITLE
CLEAN UP: rename components and shapes

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#2201]
- [x] Rename all components following BEM notation.

Remove ‘Component’ and ‘Shape’ from component and shape names. Component variable name should match its ‘name’ attribute.

**Comment by Stackblocks** [comment]
QA for this is going to functionally be a regression test: generating the XHTML and PDF, then comparing them to the same things from a previous branch to check for issues. There should not be any change related to this issue as the CSS did not change.

**Comment by lwtchu** [comment]
:eyes: @Stackblocks what am i spec reviewing here

**Comment by Stackblocks** [comment]
Basically, the entirety of Column A of the spreadsheet has changed with the [attached PR](https://github.com/openstax/cnx-recipes/pull/2310/files).

**Comment by lwtchu** [comment]
Cool i'm not gonna look super in depth into this but i believe u and this is good

**Comment by MartaSztuka** [comment]
Chemistry 2e
![Screenshot from 2020-05-29 17-12-08](https://user-images.githubusercontent.com/47241114/83275538-9054cc00-a1cf-11ea-8fdb-eedfc43366ac.png)
Chemistry AF
![Screenshot from 2020-05-29 17-14-40](https://user-images.githubusercontent.com/47241114/83275770-ecb7eb80-a1cf-11ea-9dc8-500c12d28d60.png)
Anatomy
![Screenshot from 2020-05-29 17-18-45](https://user-images.githubusercontent.com/47241114/83276277-a57e2a80-a1d0-11ea-9a16-ff56b5c12bc0.png)
Biology 2e
![Screenshot from 2020-05-29 17-24-16](https://user-images.githubusercontent.com/47241114/83276680-453bb880-a1d1-11ea-8474-a4fae551c153.png)
Concepts of Biology
![Screenshot from 2020-05-29 17-26-50](https://user-images.githubusercontent.com/47241114/83276928-9d72ba80-a1d1-11ea-8931-e01354b39fb0.png)
AP Biology
![Screenshot from 2020-05-29 17-30-08](https://user-images.githubusercontent.com/47241114/83277264-13772180-a1d2-11ea-9d98-250eaa294992.png)
Microbiology
![Screenshot from 2020-05-29 17-31-27](https://user-images.githubusercontent.com/47241114/83277390-44575680-a1d2-11ea-9a88-498610593e46.png)
College Physics
![Screenshot from 2020-05-29 17-33-57](https://user-images.githubusercontent.com/47241114/83277599-9b5d2b80-a1d2-11ea-8b17-48368960e730.png)
HS Physics
![Screenshot from 2020-05-29 17-35-50](https://user-images.githubusercontent.com/47241114/83277805-e24b2100-a1d2-11ea-98d9-ce2454a61493.png)
University Physics
![Screenshot from 2020-05-29 17-42-48](https://user-images.githubusercontent.com/47241114/83278395-d6ac2a00-a1d3-11ea-9971-5b520d94ce0b.png)
