### ISSUE TITLE
corn theme - example without title

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2203]
<img width="1006" alt="Screen Shot 2020-04-10 at 3 40 47 PM" src="https://user-images.githubusercontent.com/11299125/79022800-61fa2f00-7b44-11ea-944e-fa71bcd050ef.png">

### Line top and bottom
height: 1px (0.09rem)
color: B1:   `#093D4C`
width: full content width (6.5in wide)

### Text inside feature
Should be regular base font style!

### Box with Example numbering
Font: Noto Sans
Style: Bold
Size: font-scale(0)
Color: G2:   `#C6CE33`
Format: `EXAMPLE #.#`
Padding: v-grid(.5)? 
It does not span the entirety of the page - please if it just be enough padding around the text to form the rectangle

###  Solution Title
Icon: https://drive.google.com/open?id=1EhEmFU-JD9AZmkZsGq5ugBgHdOpF9LNf
Title font size: font-scale(0)
Style: Bold
Font: Noto Sans
Color: B1:   `#093D4C`

**Comment by wilkus27** [comment]
@lwtchu Just to be sure, when you write "width: full page (6.5in wide)" above you mean it should hit the edges of the page:

![image](https://user-images.githubusercontent.com/40228854/84146177-8ba7d780-aa5b-11ea-9e04-933b195d4da3.png)

That's right?

**Comment by lwtchu** [comment]
@wilkus27 oh no i think i used the wrong words here - I've adjusted it to say full content width. so not the entire page, but the full side to side of where the content sits

**Comment by wilkus27** [comment]
Oh ok :+1: Thank you for confirmation :relaxed:

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/84640803-779c2400-aefa-11ea-81a0-413602b2652c.png)

Note: list will be styled during work on issue https://github.com/openstax/cnx-recipes/issues/2186

Here are applied specs:

#### Example container
```
border-top-width: 0.09rem;
  border-top-style: solid;
  border-top-color: #093D4C;
  border-bottom-width: 0.09rem;
  border-bottom-style: solid;
  border-bottom-color: #093D4C;
  margin-bottom: 1.4rem;
```

#### Example title
```
font-family: Noto Sans, sans-serif;
  color: #C6CE33;
  font-size: 1rem;
  line-height: 1.5rem;
  font-weight: bold;
  text-transform: uppercase;
  background-color: #093D4C;
  display: table;
  padding: 0.7rem;
  vertical-align: top;
```
#### Example body
```
padding-top: 0.7rem;
  padding-bottom: 0.7rem;
```
#### Example solution icon
```
background-size: contain;
  height: 1rem;
  width: 1rem;
  padding-right: 8px;
```

#### Example solution title
```
font-family: Noto Sans, sans-serif;
  color: #093D4C;
  font-size: 1rem;
  line-height: 1.5rem;
  font-weight: bold;
```

**Comment by lwtchu** [comment]
@wilkus27 can we tighten up the box around the example #.# text on the top and bottom? i want the distance to be equal all around and it looks like the left and right padding is smaller

**Comment by wilkus27** [comment]
@lwtchu it was caused by line height. I set it to be the same as a font size. This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/84673320-d75df380-af29-11ea-8c38-1b5fb75d044a.png)

**Comment by lwtchu** [comment]
@wilkus27 is it just the screenshot or is the line and the box a different color? might be the way it's rendered...but wanted to just make sure

the box looks great though!

**Comment by wilkus27** [comment]
@lwtchu Yes, it's just a screenshot. I asked Marta to check colors directly in PDF and they are the same for those elements.

**Comment by lwtchu** [comment]
@wilkus27 thanks! i'll move this to the documentation column and consider it done.

**Comment by ajluk** [comment]
Hi@lwtchu! Solutions in Examples in Statistics are numbered via recipes. Should I remove them (they are also numbered in webview)?: 
![image](https://user-images.githubusercontent.com/55203598/89894960-475fc180-dbdb-11ea-9a71-e02e5c0c90e5.png)
I haven't styled the numbers yet.

**Comment by lwtchu** [comment]
@ajluk please remove, it's a bit redundant.
