### ISSUE TITLE
developmental math - unnumbered unstyled table

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2205]
<img width="710" alt="Screen Shot 2020-04-10 at 4 44 11 PM" src="https://user-images.githubusercontent.com/11299125/79025243-ca4c0f00-7b4a-11ea-8b18-85036e98a70f.png">
<img width="484" alt="Screen Shot 2020-04-10 at 4 26 00 PM" src="https://user-images.githubusercontent.com/11299125/79025245-cae4a580-7b4a-11ea-9c48-e979a7431fa5.png">

**NOTE: The class for this might need to be changed but we will coordinate when we get to this**

These are targeted by the `unnumbered unsettled` class and the design is specific to the developmental math books.

### Table alignment
These tables align to the left.

### Cell borders
Cell border color: Grey1   `#F1F1F1`
Cell border width: 1px (0.09 rem)
ONLY BORDER-BOTTOM IS STYLED

### Text font
Font: Noto Sans
Size: font-scale(0)
Color: B1:   `#093D4C`
Alignment should be controlled by the content

**Comment by ajluk** [comment]
@lwtchu I have styled the unnumbered unstyled tables, but noticed something odd when I have generated the pdf file. The token symbols are not displaying in the pdf: 
![image](https://user-images.githubusercontent.com/55203598/83774724-5b8cbd00-a686-11ea-9835-21f747750c59.png)
Although they are visible in the html file: 
![image](https://user-images.githubusercontent.com/55203598/83775754-9ba06f80-a687-11ea-9ec6-94ae99081e74.png)
Is it maybe a known math/content problem?

**Comment by ajluk** [comment]
Here are the specs I added to components in this shape:

**Comment by lwtchu** [comment]
D: oh no. i don't think this is something that i have seen before re: missing tokens. could it be there needs to have more fonts embedded to the pdf? the tokens have shown up without a problem in the past. 

i would suggest looking at the fonts and seeing if there's another type needed (like a symbols package?)

**Comment by ajluk** [comment]
@lwtchu there is separate issue about the tokens: https://github.com/openstax/cnx-recipes/issues/2186. :)
