### ISSUE TITLE
corn theme - condensed icon note with title 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2206]
![Screen Shot 2020-06-16 at 9 25 49 AM](https://user-images.githubusercontent.com/11299125/84787260-65ca8780-afb3-11ea-869b-a675a39b2153.png)

 
## Icons
Media - https://drive.google.com/open?id=1ZG0D5s4PbeBt7Nor8U6gpPu7l9XyXnaY
Width/Height: 16px - 1.45rem

## Feature title text (generated with the class)
Font: Noto Sans
Treatment: Bold
Color: B1:   `#093D4C`
Size: font-scale(0)

## Title (pulled from `<title>`)
Font: Roboto Slab
Color: B1:   `#093D4C`
Size: font-scale(0)
have styling (all caps, capitalized letters, etc) set in content only

## Text
Font: NOto sans for Text
Color: Grey3:   `#757474` 
Size: font-scale(0)
Link colour: B5: `#027EB5`
Please have content align under the feature title (In the screen shot case is should align under, MEDIA)

Note: Please ignore red bullet in list.

**Comment by wilkus27** [comment]
@lwtchu At this moment entire title is created by recipe:

![image](https://user-images.githubusercontent.com/40228854/84143044-2bfafd80-aa56-11ea-8f90-0d92af5904aa.png)

This is markup after baking:

![image](https://user-images.githubusercontent.com/40228854/84143147-59e04200-aa56-11ea-864d-80177cf77abb.png)

I can split up this title. But then markup will be the same as in **How To** note: https://github.com/openstax/cnx-recipes/issues/2208#issuecomment-638243302.

What do we want to do in this case?

**Comment by lwtchu** [comment]
@wilkus27 let me change the design in another book the Media Access Additional Online Resources will be a different text

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/84657307-6233f380-af14-11ea-9d1f-740f313d3b2a.png)

Subtitle is capitalized because it is written in this way in the content.

How should I style links? I am able to style differently parts which I marked on the red.

**Comment by lwtchu** [comment]
@wilkus27 sorry! i updated the specs above. i also added the universal link color to #2144

**Comment by wilkus27** [comment]
@lwtchu Now it looks like that:

![image](https://user-images.githubusercontent.com/40228854/84769344-f6b25a80-afd5-11ea-9bd1-f136ecd7aae1.png)

I also aligned note body with title Media like it is done in the specs from above and added bottom margin to the main title. Is it ok? Should I change something?

About links, in other parts of book the entire link should be B5 that's right? I mean text and the link. That's how it is done in carnival theme:

![image](https://user-images.githubusercontent.com/40228854/84769896-e51d8280-afd6-11ea-8139-fa7e19b46c68.png)

**Comment by lwtchu** [comment]
actually - sorry i didn't realize the grey part was also rendered as a link. i updated the screenshot but can you make the whole thing just the regular B5 with the underline? i don't want to make anything special for the feature. just treat it as a regular link. and the entire link can be B5, noto sans, underlined.

**Comment by wilkus27** [comment]
@lwtchu I change the style. This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/84887146-a4387300-b095-11ea-9d33-66420de1ca67.png)

And here are applied specs:

#### Media note
```
margin-bottom: 1.4rem;
```
![image](https://user-images.githubusercontent.com/40228854/84888127-1b223b80-b097-11ea-85f0-ef8123aa5bd4.png)

#### Media title
```
margin-bottom: 0.7rem;
```
![image](https://user-images.githubusercontent.com/40228854/84888176-2ffecf00-b097-11ea-9897-fa2b81937ff0.png)

#### Media icon
```
background-size: contain;
  height: 1.45rem;
  width: 1.45rem;
  padding-right: 8px;
```
![image](https://user-images.githubusercontent.com/40228854/84888229-41e07200-b097-11ea-9e97-1393ab042525.png)

#### Media label
```
color: #093D4C;
  font-family: Noto Sans, sans-serif;
  font-size: 1rem;
  line-height: 1.5rem;
  font-weight: bold;
  text-transform: uppercase;
```
![image](https://user-images.githubusercontent.com/40228854/84888275-53c21500-b097-11ea-8d81-91a6911206cf.png)

#### Media body
```
color: #757474;
  font-family: Noto Sans, sans-serif;
  font-size: 1rem;
  line-height: 1.5rem;
  margin-left: 24px;
```
![image](https://user-images.githubusercontent.com/40228854/84888361-76542e00-b097-11ea-8b92-bdbaeec4aacf.png)

#### Media subtitle
```
color: #093D4C;
  font-family: Roboto Slab, serif;
  font-size: 1rem;
  line-height: 1.5rem;
```
![image](https://user-images.githubusercontent.com/40228854/84888396-85d37700-b097-11ea-9f1e-7ed46429be33.png)

#### Media list
```
list-style-type: none;
```
![image](https://user-images.githubusercontent.com/40228854/84888434-95eb5680-b097-11ea-8c59-5837bed1c95b.png)

#### Links
```
color: #027EB5;
```
![image](https://user-images.githubusercontent.com/40228854/84888482-a3a0dc00-b097-11ea-9f04-2474d9ba8868.png)

**Comment by lwtchu** [comment]
thank you! we can move fwd with testing for this

**Comment by wilkus27** [comment]
@lwtchu In College Algebra Coreq there is no subtitle in Media note. Only paragraph:

![image](https://user-images.githubusercontent.com/40228854/86249623-d5459700-bbaf-11ea-9dcc-237abb3a641f.png)

Is it ok how it looks now or in this case it should be style like condensed note without title (e.g Try It)?

![image](https://user-images.githubusercontent.com/40228854/86249823-12aa2480-bbb0-11ea-88a3-023641a71425.png)

So should para and links display next to Media title?

**Comment by lwtchu** [comment]
@wilkus27 i think as it is right now is fine.

**Comment by ajluk** [comment]
@lwtchu The media note styled in Calculus looks like this: 
![image](https://user-images.githubusercontent.com/55203598/89183787-0ee73480-d598-11ea-8787-58a54be9f7da.png)
There is no title, only a paragraph with link inside it.
Should there something need to be changed?

**Comment by lwtchu** [comment]
@ajluk that looks fine. thank you
