### ISSUE TITLE
developmental math: icon boxed note with title 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2208]
<img width="576" alt="Screen Shot 2020-06-03 at 1 44 53 PM" src="https://user-images.githubusercontent.com/11299125/83678024-a6350900-a5a2-11ea-8d1c-11330c4286bb.png">

### Box
color: Grey4:   `#E7EBED`

### Icon
https://drive.google.com/open?id=1V7UclR26LeMMP3CNjazmq4B4ekIxbWCp

### Title for How To
Color: B1:   `#093D4C`
Font: Noto Sans
Style: bold
Size: font-scale(0)

## Title for text from `<title>`
Color: B1:  ` #093D4C`
Font: Roboto Slab
Size: font-scale(0)

### Text
Color: B1:  ` #093D4C`
Font: Noto Sans
Size: font-scale(0)

### Line between title and text
height: 1px (0.09rem?)
color: `#FFFFFF`

### Padding
all around: v-grid(.5)

**Comment by wilkus27** [comment]
@lwtchu I'm afraid that we can't applied such design. Here is the markup:

![image](https://user-images.githubusercontent.com/40228854/83649335-590f6200-a5b7-11ea-865b-78632aac4876.png)

It is created by recipes. We move existing title to `.os-note-body` and before this tag we create new one defined by recipes. To be able to style this note like above subtitle should be sibling or child of `h3` title. I can modify mixin to achieve such markup, but this change will have an impact on webview as well.

So, my question is, do we want to change recipe or design of this note?

**Comment by lwtchu** [comment]
Let's change the design of the note - I'll provide a new screenshot after I'm done with meetings today

**Comment by lwtchu** [comment]
@wilkus27 i moved it below ...spec for the title and font and stuff should be the same but placement is just below the icon and note title we can keep the padding like the other notes at 0.7rem and line  height at 1.5rem  (like in https://github.com/openstax/cnx-recipes/issues/2200)

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/83756576-87e90f00-a66f-11ea-88b3-5eb13954a442.png)

### Note
```
margin-bottom: 1.4rem;
```
![image](https://user-images.githubusercontent.com/40228854/83756944-0d6cbf00-a670-11ea-8ee2-b60362fb0d5a.png)

### Title
```
color: #093D4C;
  font-family: Noto Sans, sans-serif;
  font-size: 1rem;
  line-height: 1.5rem;
  font-weight: bold;
  text-transform: uppercase;
  background-color: #E7EBED;
  padding: 0.7rem;
  border-bottom-width: 0.09rem;
  border-bottom-style: solid;
  border-bottom-color: #FFFFFF;
```
![image](https://user-images.githubusercontent.com/40228854/83757016-24abac80-a670-11ea-8d77-e3797205cae6.png)

### Icon
```
vertical-align: middle;
  height: 2.1rem;
  width: 2.1rem;
  margin-right: 8px;
```
![image](https://user-images.githubusercontent.com/40228854/83757069-38efa980-a670-11ea-84ec-d80c0e0c4d7b.png)

### Note body
```
color: #093D4C;
  font-family: Noto Sans, sans-serif;
  font-size: 1rem;
  line-height: 1.5rem;
  background-color: #E7EBED;
  padding: 0.7rem;
```
![image](https://user-images.githubusercontent.com/40228854/83757141-53c21e00-a670-11ea-8221-ac16d8e460b0.png)

### Subtitle
```
color: #093D4C;
  font-family: Roboto Slab, serif;
  font-weight: normal;
  font-size: 1rem;
  line-height: 1.5rem;
  margin-bottom: 0.7rem;
```
![image](https://user-images.githubusercontent.com/40228854/83757184-63d9fd80-a670-11ea-9677-fa3afadb3207.png)

**Comment by lwtchu** [comment]
@wilkus27 is there white space in the icon that is preventing it from hitting the edges of the note? if so, i can open it up again and tweak the icon settings

**Comment by wilkus27** [comment]
@lwtchu No, it looks like that because of width and height which I applied. I set the same values like in  `Manipulative Math` note (https://github.com/openstax/cnx-recipes/issues/2200). I didn't notice that icon should hit the edges. Let me fix that :slightly_smiling_face:

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now

![image](https://user-images.githubusercontent.com/40228854/84009979-4f4d7c00-a974-11ea-8fb9-893e28ed257c.png)

I streched it to the edges, but there is still space at the bottom. It is a part of icon. So the change which you mention previously is also needed here.

**Comment by wilkus27** [comment]
This is final sight after replacing image and adding changes to style.

![image](https://user-images.githubusercontent.com/40228854/84049551-dd455900-a9ac-11ea-8f02-bcfb6cd5f2af.png)

### Changed properties:

#### Title
color: #093D4C;
  font-family: Noto Sans, sans-serif;
  font-size: 1rem;
  line-height: 1.5rem;
  font-weight: bold;
  text-transform: uppercase;
  background-color: #E7EBED;
  **padding-left: 0.7rem;
  padding-right: 0.7rem;**
  border-bottom-width: 0.09rem;
  border-bottom-style: solid;
  border-bottom-color: #FFFFFF;

#### Icon
**background-size: cover;**
  display: inline-block;
  vertical-align: middle;
  **height: 4.2rem;
  width: 4.2rem;**
  content: '';
  margin-right: 8px;

**Comment by lwtchu** [comment]
@wilkus27 😬 i think the speech bubble is cut off. on the icon

**Comment by wilkus27** [comment]
Oh :thinking: Thank you for noticing that! I will try to fix this :relaxed:

**Comment by wilkus27** [comment]
@lwtchu I fix that:

![image](https://user-images.githubusercontent.com/40228854/84114458-af075e00-aa2c-11ea-8a65-29df04c782f8.png)

I hope I didn't miss anything this time :smile: 

I decreased height to **3.5rem** (v-spacing(5)). Let me know if it's ok. If icon should be bigger I can try to set height to **4.2rem** (v-spacing(6)) and width to **4.9rem** (v-spacing(7)).

**Comment by lwtchu** [comment]
@wilkus27 one tiny tiny thing - is the padding top and bottom of the text a little off? the how to doesn't look centered but i can't really tell without the PDF so i thought i would check

**Comment by lwtchu** [comment]
@wilkus27 wait is it cause of the line height? then it's fine. I'll move it to testing

**Comment by wilkus27** [comment]
@lwtchu I added some properties to make it centered. This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/84254296-53fb6700-ab11-11ea-9397-bcdbffb8a78a.png)

Is it ok? It is possible to move this title up and down. So if you want to display it for example at the same level as head of the girl from the icon I can do it :wink:

**Comment by lwtchu** [comment]
This looks good :) thanks for lettign me know the possibilities though
