### ISSUE TITLE
corn theme - example with title

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2209]
<img width="809" alt="Screen Shot 2020-04-13 at 11 42 21 AM" src="https://user-images.githubusercontent.com/11299125/79139440-ec78a380-7d7b-11ea-9b03-8602fa42e2bd.png">

### Title 
font: noto sans
treatment: bold
color: B1:   `#093D4C`
size: font-scale(0)

### Analysis (same as solution specs below) 
<img width="432" alt="Screen Shot 2020-04-13 at 12 17 54 PM" src="https://user-images.githubusercontent.com/11299125/79142256-d4efe980-7d80-11ea-979f-e569e901373c.png">
Icon: https://drive.google.com/open?id=1J4_SsdkvzMR50E7A3H2BWP_4F0BCXI2M

### Line top and bottom
height: 1px (0.09rem)
color: B1:   `#093D4C`
width: full page (6.5in wide)

### Text inside feature
Should be regular base font style!

### Box with Example numbering
Font: Noto Sans
Style: Bold
Size: font-scale(0)
Color: G2:   `#C6CE33`
Format: `EXAMPLE #.#`
Padding: v-grid(.5)? 
It does not span the entirety of the page - please if it just be enough padding around the text to form the rectangle

###  Solution Title
Icon: https://drive.google.com/open?id=1EhEmFU-JD9AZmkZsGq5ugBgHdOpF9LNf
Title font size: font-scale(0)
Style: Bold
Font: Noto Sans
Color: B1:   `#093D4C`

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/85838662-2f062580-b79a-11ea-8dee-6035ecd7f076.png)

Should I change something?

**Comment by lwtchu** [comment]
@wilkus27 i don't think so - it looks good.

**Comment by ajluk** [comment]
@lwtchu the Examples in Calculus look like so: 
![image](https://user-images.githubusercontent.com/55203598/89178187-5caa6f80-d58d-11ea-807a-70aa788c1b5f.png)
There are present ol lists without any specific class like `stepewise` or `circled`. Should I add support for these regular ol lists for excamples in this book or there will be some changes in the content?

**Comment by lwtchu** [comment]
@ajluk this is fine. thank you
