### ISSUE TITLE
corn theme - equation number

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2210]
<img width="803" alt="Screen Shot 2020-04-13 at 11 51 31 AM" src="https://user-images.githubusercontent.com/11299125/79140181-31e9a080-7d7d-11ea-812b-f7b93f88f6bd.png">

treatment: in parenthesis and bold
font: noto sans
size: font-scale(0)
color: B2:   `#1E7E91`

**Comment by ajluk** [comment]
@lwtchu I have noticed that equations in the old pdfs were unnumbered and numbering for them is suppressed in the recipe. There is hard to find a numbered equation in the book either (I have fetched College Algebra today) and have found one. So I wanted to ask you if this change is desired, just to be sure. The equation example from the screenshot you posted above also have class `unnumbered` in the content.

**Comment by lwtchu** [comment]
since there's no numbered equations in precalculus series: #2447, will reserve this for when we go to calculus

**Comment by ajluk** [comment]
@lwtchu here is how look numbered equations in Calculus after styling:

![image](https://user-images.githubusercontent.com/55203598/88791036-5e44f380-d199-11ea-9b96-cc07dde1b81f.png)
![image](https://user-images.githubusercontent.com/55203598/88791582-43bf4a00-d19a-11ea-8d53-e0639cd6230d.png)

Specs added:
**Equation** 
(same as in unnumbered equations)
display: flex;
align-items: center;
justify-content: center;
margin-bottom: 0.7rem;
(new)
position: relative;
flex-direction: row;
**EquationNumber**
position: absolute;
right: 0;
top: 50%;
transform: translate(0, -50%);
font-family: Noto Sans, sans-serif
font-size: 1rem;
line-height: 1.5rem;
font-weight: bold;
color: #1E7E91;
margin-right: 0.7rem;

**Comment by lwtchu** [comment]
@ajluk looks good thank you~
