### ISSUE TITLE
baking selected chapters

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#2211]
**Story**: As a developer, I’d like to have the ability to select a specific chapter so that I can speed up my turnover time on iterations.

# Acceptance Criteria

- dev can run a `chop 12` step in between the existing assemble and bake steps, continue running the rest of the steps and have a PDF with 1 chapter in it.
    - the contents of the chapter would be from Ch 12 while the number on the chapter would be `1`

**Comment by brittany-johnson** [comment]
Notes from initial meetings can be found in this document under the 4-13-2020 header: 
https://docs.google.com/document/d/19jSCScweg9oUdynkFwuSyi_jh9Nlq_2RMcJNURTY6Z0/edit

**Comment by brittany-johnson** [comment]
@philschatz Would the next step be a meeting to discuss implementation details? Or something else?

**Comment by Bkblodget** [comment]
@philschatz could this eventually become a feature of COPS?

**Comment by philschatz** [comment]
@Bkblodget Eventually yes, but I think this story is to provide devs with a quick way to lob off parts of a book. For example, this will allow a dev to remove all chapters except 21 so it'll look like a book with only 1 chapter in it, named "Chapter 1".

**Comment by brittweinstein** [comment]
@Bkblodget I will leave this issue in this pipeline for your prioritization!

**Comment by philschatz** [comment]
Code snippets for the different implementations we did and summary (recipe/python/javascript/xslt). A couple more code snippets need to be added that I think @brittany-johnson has on her laptop.

https://github.com/openstax/napkin-notes/blob/master/phil/chapter-chop.md

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-05-15 at 2 57 13 PM](https://user-images.githubusercontent.com/24909007/82091538-27dcf980-96bd-11ea-9a08-f75c6c7c5e01.png)
![Screen Shot 2020-05-15 at 2 49 46 PM](https://user-images.githubusercontent.com/24909007/82091541-29a6bd00-96bd-11ea-8a7c-ca3bc9245bbb.png)
