### ISSUE TITLE
Top margin equations

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2216]
![Screenshot from 2020-04-14 14-53-44](https://user-images.githubusercontent.com/47241114/79227271-ed830100-7e5f-11ea-8527-b725a6026994.png)

**Comment by brittweinstein** [comment]
@MartaSztuka just to be sure, you're referring to the top of the equations running close to the content they are underneath, correct? We should have resolved this in other Physics work.

**Comment by MartaSztuka** [comment]
@brittweinstein that's correct, issue is about space between top of the equation and bottom of text above.

**Comment by wilkus27** [comment]
This is a content issue. `newline` tags should be removed:

![image](https://user-images.githubusercontent.com/40228854/80193814-bfe54700-8619-11ea-8477-308b2eebe050.png)

It will be done with using batch tool.

**Comment by wilkus27** [comment]
#### Decision

`newline` tags will be removed using batch tool.

**Comment by MartaSztuka** [comment]
Issue moved to https://github.com/openstax-poland/content/issues/15
I'm closing.
