### ISSUE TITLE
CLEAN UP: Preface

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#2219]
[Cleanup doc](https://docs.google.com/document/d/10qrKjBt3sGoZR8KaW1xwUSApVZiRPtFxce2WkRP2LJ0/edit#heading=h.njxq5e8rshj0)
[ ] Investigate why there isn’t an H2 component in the shape

**Comment by Stackblocks** [comment]
I talked to Larissa about this and she cant remember a specific reason why the H2s wouldn't be handled, so I'm going to A/B test with the $H2config and will proceed form there.

**Comment by Stackblocks** [comment]
Followed up with Larissa and the reason that they weren't handled is that there are no H2s in the preface markup. We should still enable the H2s in the preface shape so the full suite of headers are available in the development space.
