### ISSUE TITLE
coreq math - corequisite skills section

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2222]
Content is in Chapter 1 & 2 of the [College Algebra](https://katalyst01.cnx.org/contents/9b08c294-057f-4201-9f48-5d6ad992740d) collection.

<img width="618" alt="Screen Shot 2020-04-14 at 11 12 36 AM" src="https://user-images.githubusercontent.com/11299125/79255954-d1299900-7e4c-11ea-9cd3-c469baf04cdf.png">

targeted by section class `coreq-skills`

This is a section that will contain other features. If possible, have the other features continue their original styling in regards to header sizing.

Should follow same specs as #2203 but the colors are inverted for this feature:

boxes and lines: G2: `#C6CE33`
text: B1: `#093D4C`
Title should be set at: COREQUISITE SKILLS 

## Title set from `<title>`
![image](https://user-images.githubusercontent.com/11299125/86150688-570bc680-bac3-11ea-8f0b-2f40599ca0b8.png)
Let's set this title for this section ONLY to font-scale(1) instead of the originally set font-scale(0) for this style.

**Comment by wilkus27** [comment]
@lwtchu I checked and imported sections are missing class `coreq-skills` :crying_cat_face: Can I ask you to add it?

Also I have a few questions about content of coreq sections.

### Main title

It's not just `Corequisite Skills` it has more text, different in each module:

![image](https://user-images.githubusercontent.com/40228854/85699075-81ccd800-b6db-11ea-8c83-509bcbd76f70.png)

What do you want me to do in this case?

a. Leave it as is and style it as on the screenshot which you posted?
b. Create by recipe title `Corequisite Skills` and move this one to the body as a subtitle (then in content part Corequisite Skills should be removed)?
c. Totally removed title created in the content and create it by recipe only with words `Corequisite Skills` ?

### Second Learning Objectives

Coreq section contains another Learning Objectives: 

![image](https://user-images.githubusercontent.com/40228854/85700226-74fcb400-b6dc-11ea-8cfc-4089d6da4843.png)

First one is from regular module, second - from coreq section. How it should be styled?

**Comment by lwtchu** [comment]
@wilkus27 hello! i fixed all the sections and they should have the class! 

is it possible to set the corequisite skill title to move under like we have for some example titles? we can fix the content up later to remove the redundancy 

and i meant to ping you about the LO's - when you see this message at some point can you message me. i'd like to get on the same page about best next steps

**Comment by wilkus27** [comment]
@lwtchu Sorry for the delay. I had to create separate recipe for Coreq first, to be able to start working on this. This is how it looks with styles:

![image](https://user-images.githubusercontent.com/40228854/86127282-ecb54f00-badf-11ea-88bc-49700e4a36fb.png)

Here is the end:

![image](https://user-images.githubusercontent.com/40228854/86127326-fe96f200-badf-11ea-8db6-0d4f3208d660.png)

**Comment by lwtchu** [comment]
@wilkus27 for the coreq skills section only can you bump up the fontsize of the `<title>` "Corequisite Skills: Create a study plan"  up to match the next header? What font size would it be? I can add it to the specs

**Comment by wilkus27** [comment]
@lwtchu It was set to `font-scale(0)` the same as for the main title in the box. I increased subtitle to font-scale(1):

![image](https://user-images.githubusercontent.com/40228854/86148282-b933ee00-bafa-11ea-8713-b032d55db2d6.png)

**Comment by lwtchu** [comment]
@wilkus27 i think that looks a better. i'll adjust the specs. thank you~

**Comment by wilkus27** [comment]
@lwtchu I noticed that notes How To inside coreq-skills section have class `howto`. In rest of book they have class `how-to-notitle`. Should I create style for both classes or one of them will changed?

**Comment by lwtchu** [comment]
@wilkus27 it should be changed - i thought i changed them all when i added the coreq-skills class?

**Comment by wilkus27** [comment]
@lwtchu I will try to fetch it again. In version were `coreq-skills` class are added I see notes with `howto` class. I checked also on webview and you can find it e.g. here https://katalyst01.cnx.org/contents/mwjClAV_@20.1:62_eXnY6@26/2-2-Linear-Equations-in-One-Variable

**Comment by wilkus27** [comment]
@lwtchu After our discusion about second Learning Objectives I style it like this one from regular page. This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/86363219-d42b6d00-bc76-11ea-8c3d-0436bba0f83e.png)

**Comment by lwtchu** [comment]
@wilkus27 it looks great :sob:

**Comment by wilkus27** [comment]
Here is the screenshot of exercises from coreq skills:

![image](https://user-images.githubusercontent.com/40228854/87047101-4ad9e480-c1fa-11ea-9d15-3afb64eac47f.png)

**Information for tester**:  numbering of exercises should reset within Coreq Skills section.

**Comment by wilkus27** [comment]
@lwtchu As we discussed in DM numbering of all numbered elements (Examples, Tables, Figures) should reset whithin this section. Since it is quite tricky I created separate card for this problem: https://github.com/openstax/cnx-recipes/issues/2487
