### ISSUE TITLE
Suppress coreq-skills class in the Precalculus recipe

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2223]
We'll be starting to go in to inject the `<section class="coreq-skills">` into the content. Can we please suppress this in the precalculus recipe so it will not show up? (Note: It can still be there if you inspect the HTML/content).

**Comment by lwtchu** [comment]
* Will park this with people on Thursday. Don't be alarmé

**Comment by brittany-johnson** [comment]
@lwtchu Hello! Didn't see this class in the precalculus book on katalyst01, should I look on another server?

**Comment by lwtchu** [comment]
Update: coreq-skill class is currently in chapter 1 & 2 of College Algebra on katalyst01. they will be sharing recipes

**Comment by brittany-johnson** [comment]
For testing: the class `coreq-skills` should no longer be present in the markup when inspecting the book in the browser.

**Comment by openstaxalina** [comment]
@brittany-johnson will the content itself -- the content that is inside the coreq-skills section -- be suppressed?

cc @lwtchu

**Comment by brittany-johnson** [comment]
@openstaxalina Hello! Yes, everything within the `coreq-skills` should be suppressed.

**Comment by openstaxalina** [comment]
Got it. Woohoo!

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-07-03 17-29-48](https://user-images.githubusercontent.com/47241114/86482741-d5ca6300-bd52-11ea-9711-faeea00aee87.png)
