### ISSUE TITLE
CLEANUP: Tables

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#2224]
[Cleanup doc](https://docs.google.com/document/d/10qrKjBt3sGoZR8KaW1xwUSApVZiRPtFxce2WkRP2LJ0/edit#)

- [x] Page-break in the $TableTitle component should be moved to the page break file

- [x] Review component values and update where necessary (required vs optional vs hardcoded) 

- [ ] ~~Separate out borders from tables / create a border component~~

- [ ] ~~Reorganize document to have generic table components up top, then comment-described specialty tables below~~

- [x] Captions are used in tables and figures/images. Create one general caption component to replace the current ones in the tables and figures component files

**Comment by brittany-johnson** [comment]
Related issue: https://github.com/openstax/cnx-recipes/issues/1922

**Comment by MartaSztuka** [comment]
Chemistry 2e
![Screenshot from 2020-05-11 17-16-20](https://user-images.githubusercontent.com/47241114/81578527-34a2da00-93ab-11ea-9063-88635078e005.png)
![Screenshot from 2020-05-11 17-18-04](https://user-images.githubusercontent.com/47241114/81578652-65830f00-93ab-11ea-8a15-d254a29962de.png)
HS Physics
![Screenshot from 2020-05-11 17-23-32](https://user-images.githubusercontent.com/47241114/81580124-4dac8a80-93ad-11ea-9be6-3e206756138b.png)
![Screenshot from 2020-05-11 17-34-04](https://user-images.githubusercontent.com/47241114/81580359-a11ed880-93ad-11ea-910e-dd199b689b50.png)
AP Biology
![Screenshot from 2020-05-11 17-36-52](https://user-images.githubusercontent.com/47241114/81580713-15f21280-93ae-11ea-8cb4-d37c2cccc466.png)
