### ISSUE TITLE
CLEANUP: TOC

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#2226]
[Cleanup doc](https://docs.google.com/document/d/10qrKjBt3sGoZR8KaW1xwUSApVZiRPtFxce2WkRP2LJ0/edit#)
- [x] move page break rule to page break file

- [x] Rearrange shapes so that siblings components are next to each other and not occurring after the map merge (investigate to make sure order of siblings doesn’t matter) 

- [x] Move functions to the general functions file/folder and call those functions in the shapes, assigning them to a variable

- [x] Covert components that are empty to use the no properties function 

- [x] We’re hiding  $TocCompositeChapterList with display none, investigate if this can be removed from the recipe (may not be an easy task)

- [x] Move shapes out of the components

- [x] Investigate $TocAppendixDivider, dividers are handled by the recipes so see why this was added/fix it

**Comment by ajluk** [comment]
@MartaSztuka >> Information for testing purposes: There should be no visible change in the ToC in the books.

**Comment by MartaSztuka** [comment]
Concepts of Biology
![Screenshot from 2020-05-26 15-27-33](https://user-images.githubusercontent.com/47241114/82906409-7dd75a00-9f65-11ea-853e-708ed03578b2.png)
AP Biology
![Screenshot from 2020-05-26 15-29-05](https://user-images.githubusercontent.com/47241114/82906510-a8291780-9f65-11ea-90d4-b5da83dacb3a.png)
Microbiology
![Screenshot from 2020-05-26 15-42-53](https://user-images.githubusercontent.com/47241114/82907956-95afdd80-9f67-11ea-9449-594a7b4c139d.png)
HS Physics
![Screenshot from 2020-05-26 15-43-40](https://user-images.githubusercontent.com/47241114/82908032-b11ae880-9f67-11ea-960f-6caa522f51b0.png)
College Physics
![Screenshot from 2020-05-26 15-44-51](https://user-images.githubusercontent.com/47241114/82908152-dc053c80-9f67-11ea-8a3c-572d2e5fdcf4.png)
