### ISSUE TITLE
CLEANUP: Learning Objectives

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#2227]
[Cleanup doc](https://docs.google.com/document/d/10qrKjBt3sGoZR8KaW1xwUSApVZiRPtFxce2WkRP2LJ0/edit#heading=h.3i7y3p43cq0m)

- [x] Investigate which learning objectives we have to verify which shapes we need ( see the doc for more details)

- [x] Can $LearningObjectiveTitleComponent be replaced with a component from the titles file?

- [x] Empty NoteBody can be replaced by no props function

- [x] The name of the shapes should match the component variable names (or at least be closer to the name)

- [x] Check if the lists components can be moved to _list-components.scss file

**Comment by wilkus27** [comment]
### Decision

Learnig Objectives in all books should be styled in one way, like it is done in HS Physics.
(Link to discusion: https://katalysteducation.slack.com/archives/CBW9DFKGF/p1588938854198800)

Therefore, some of the content changes are needed:

- add title "Learning Objectives" in AP Biology
- wrap text inside `[data-type="abstract"]` into `<p>` in Biology, Chemistry, Anatomy, U-Physics, Pl-U-Physics
- add `<p>` with text "By the end of this section..." in Microbiology

Those changes will be done on production. On katalyst01 it will be changed only one chapter in each book.

**Comment by wilkus27** [comment]
@MartaSztuka content is changed in Anatomy in module `Overview of Anatomy and Physiology`. There it should display properly. Everywhere else some parts of Learning Objectives could be unstyled.

Please, create content issue for polish u-physics in `openstax-poland/content` repo.

Here is the needed change.
Text from the screenshot should be wrapped into `<p>`:
![image](https://user-images.githubusercontent.com/40228854/82031471-39f97080-969a-11ea-84e2-2bf0d2431983.png)

**Comment by wilkus27** [comment]
### Recipe changes
Add title "Learning Objectives" in Biology, Anatomy and Chemistry in their `config.scss` files.

**Comment by MartaSztuka** [comment]
Anatomy
![Screenshot from 2020-05-15 16-37-48](https://user-images.githubusercontent.com/47241114/82062467-70e77a80-96ca-11ea-8f0f-769103ddc4a3.png)
Chemistry 2e
![Screenshot from 2020-05-15 15-42-51](https://user-images.githubusercontent.com/47241114/82056834-c91a7e80-96c2-11ea-899e-b420d3fcea5d.png)
Chemistry AF
![Screenshot from 2020-05-15 15-39-57](https://user-images.githubusercontent.com/47241114/82056578-6fb24f80-96c2-11ea-979b-ac64fe8a0cde.png)
Biology 2e
![Screenshot from 2020-05-15 16-07-11](https://user-images.githubusercontent.com/47241114/82059329-29f78600-96c6-11ea-8580-3f3d8f0a6f47.png)
AP Biology
![Screenshot from 2020-05-15 16-08-39](https://user-images.githubusercontent.com/47241114/82059470-5e6b4200-96c6-11ea-9ee9-4915c93cd882.png)
Concepts of Biology
![Screenshot from 2020-05-15 16-10-19](https://user-images.githubusercontent.com/47241114/82059641-996d7580-96c6-11ea-8b05-803b59f95a00.png)
Microbiology
![Screenshot from 2020-05-15 16-11-50](https://user-images.githubusercontent.com/47241114/82059799-d0dc2200-96c6-11ea-9d34-26fa49402d26.png)
HS Physics
![Screenshot from 2020-05-15 16-14-28](https://user-images.githubusercontent.com/47241114/82060116-35977c80-96c7-11ea-8cb8-7fe9f9bc9624.png)
University Physics
![Screenshot from 2020-05-15 17-19-03](https://user-images.githubusercontent.com/47241114/82066828-354faf00-96d0-11ea-90e7-851efebf6881.png)
