### ISSUE TITLE
CLEANUP: Lists

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#2228]
[Cleanup doc](https://docs.google.com/document/d/10qrKjBt3sGoZR8KaW1xwUSApVZiRPtFxce2WkRP2LJ0/edit#)

- [ ] Simplify all the lists components to two/three default generic lists components with more general selectors as it was done in the reset file

- [ ] Check the edge cases (nested lists from eoc exercises in APBiology, lists nested in sections in exercises in HS Physics)

See doc above for more details

**Comment by lwtchu** [comment]
MOOOOT
