### ISSUE TITLE
CLEANUP: Titles

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#2229]
[Cleanup doc](https://docs.google.com/document/d/10qrKjBt3sGoZR8KaW1xwUSApVZiRPtFxce2WkRP2LJ0/edit#)

- [ ] Address comment for $AppendixTitleComponent (and maybe other components with appendix specific named components), rename to be not appendix specific

- [ ] Address the comment under the $H4LinkComponent, this needs to be fixed in the recipe (H3 needs to be converted to H4)

- [ ] Make sure that file is organized with more specific components at the bottom of the file and more general at the top

- [ ] In the main number component, verify that the optionals and require are set appropriately

- [ ] Divider can maybe be removed via the recipes(???)

- [ ] Comprehensive approach to para titles (Notes- move note titles to the title components, Modules, others)

**Comment by Stackblocks** [comment]
@brittany-johnson Is this the same as/an extension of #2169 ?

**Comment by Stackblocks** [comment]
Closing alongside #2169
