### ISSUE TITLE
CLEANUP: Folio and color bands in all books

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#2230]
[Cleaup doc](https://docs.google.com/document/d/10qrKjBt3sGoZR8KaW1xwUSApVZiRPtFxce2WkRP2LJ0/edit#)

- [x] Move settings related with folio to folio.scss file

- [x] Move all mixins and settings for bands to separate file

- [x] Define at the top of the book.scss files variables for bands (color of band, selectors for first eoc and eob page)

- [x] Create `if` statement for settings for first and second page of chapter (they should be added only for books which are using ChapterIntroShape)

**Comment by wilkus27** [comment]
Those changes has impact on all books. There should be no visible changes in PDF.
During testing check bands in EOC and EOB. Also verify page margins on Introduction page.

**Comment by MartaSztuka** [comment]
Anatomy
![Screenshot from 2020-05-08 12-54-41](https://user-images.githubusercontent.com/47241114/81399323-1d55b980-912b-11ea-9ac3-e5d715e48075.png)
![Screenshot from 2020-05-08 12-52-55](https://user-images.githubusercontent.com/47241114/81399326-1e86e680-912b-11ea-8f01-ded8c79b0118.png)
![Screenshot from 2020-05-08 12-55-17](https://user-images.githubusercontent.com/47241114/81399385-3199b680-912b-11ea-9c20-9ae1198299e9.png)
Biology 2e
![Screenshot from 2020-05-08 13-20-01](https://user-images.githubusercontent.com/47241114/81401009-a7535180-912e-11ea-9afa-a9373ec4d629.png)
![Screenshot from 2020-05-08 13-19-28](https://user-images.githubusercontent.com/47241114/81401012-a8847e80-912e-11ea-98c3-58753771dfd9.png)
![Screenshot from 2020-05-08 13-24-58](https://user-images.githubusercontent.com/47241114/81401305-598b1900-912f-11ea-9473-d26426bd6b6c.png)
Chemistry
![Screenshot from 2020-05-08 14-19-44](https://user-images.githubusercontent.com/47241114/81404960-03ba6f00-9137-11ea-9756-26b1dfc6c393.png)
![Screenshot from 2020-05-08 14-32-22](https://user-images.githubusercontent.com/47241114/81405854-c35bf080-9138-11ea-8329-9197df7dcbb7.png)
![Screenshot from 2020-05-08 14-37-32](https://user-images.githubusercontent.com/47241114/81406588-2306cb80-913a-11ea-8506-e5f7dc3ffa7c.png)
HS Physics
![Screenshot from 2020-05-08 14-44-11](https://user-images.githubusercontent.com/47241114/81406712-67926700-913a-11ea-97a1-03ac8b894266.png)
![Screenshot from 2020-05-08 14-44-57](https://user-images.githubusercontent.com/47241114/81406792-85f86280-913a-11ea-8777-911a5839f9de.png)
![Screenshot from 2020-05-08 14-46-21](https://user-images.githubusercontent.com/47241114/81406917-c061ff80-913a-11ea-859a-84bfc734b664.png)
Microbiology
![Screenshot from 2020-05-08 14-51-40](https://user-images.githubusercontent.com/47241114/81407319-77f71180-913b-11ea-94fc-935ca2ee5ab8.png)
![Screenshot from 2020-05-08 14-51-11](https://user-images.githubusercontent.com/47241114/81407323-79283e80-913b-11ea-80d2-4e3dd07a54a5.png)
![Screenshot from 2020-05-08 14-52-17](https://user-images.githubusercontent.com/47241114/81407352-89d8b480-913b-11ea-971c-226326d2e36c.png)
College Physics
![Screenshot from 2020-05-08 14-55-45](https://user-images.githubusercontent.com/47241114/81407623-053a6600-913c-11ea-8371-41b4c80b5856.png)
![Screenshot from 2020-05-08 14-56-08](https://user-images.githubusercontent.com/47241114/81407710-256a2500-913c-11ea-88f3-43908fd3935a.png)
![Screenshot from 2020-05-08 14-57-28](https://user-images.githubusercontent.com/47241114/81407773-42065d00-913c-11ea-849e-70ec1e24cc47.png)
AP Biology
![Screenshot from 2020-05-08 15-02-15](https://user-images.githubusercontent.com/47241114/81408122-f43e2480-913c-11ea-943a-aa249c418c72.png)
![Screenshot from 2020-05-08 15-02-58](https://user-images.githubusercontent.com/47241114/81408164-08822180-913d-11ea-965c-1b09001ddfe7.png)
![Screenshot from 2020-05-08 15-03-52](https://user-images.githubusercontent.com/47241114/81408244-28194a00-913d-11ea-8f37-8cb79d6b9e23.png)
Chemistry AF
![Screenshot from 2020-05-08 15-11-10](https://user-images.githubusercontent.com/47241114/81408803-2f8d2300-913e-11ea-8ca8-48089b2c339d.png)
![Screenshot from 2020-05-08 15-11-45](https://user-images.githubusercontent.com/47241114/81408848-459ae380-913e-11ea-88b2-dfee57573243.png)
![Screenshot from 2020-05-08 15-32-22](https://user-images.githubusercontent.com/47241114/81410523-2baed000-9141-11ea-98e6-1e4c1faedd29.png)
University Physics
![Screenshot from 2020-05-08 15-36-18](https://user-images.githubusercontent.com/47241114/81410836-b1cb1680-9141-11ea-95be-d80c0eae3f44.png)
![Screenshot from 2020-05-08 15-36-00](https://user-images.githubusercontent.com/47241114/81410840-b2fc4380-9141-11ea-8a7d-b41a6f9165e1.png)
![Screenshot from 2020-05-08 15-35-32](https://user-images.githubusercontent.com/47241114/81410848-b42d7080-9141-11ea-805f-31ea6eeab966.png)
Concepts of Biology
![Screenshot from 2020-05-08 15-41-52](https://user-images.githubusercontent.com/47241114/81411310-7da42580-9142-11ea-8a8f-df3e1a351aac.png)
![Screenshot from 2020-05-08 15-41-13](https://user-images.githubusercontent.com/47241114/81411317-7f6de900-9142-11ea-9422-3a0df8fc0601.png)
![Screenshot from 2020-05-08 15-40-41](https://user-images.githubusercontent.com/47241114/81411320-80067f80-9142-11ea-97a2-8be6bae3e61e.png)
