### ISSUE TITLE
Fix exercises and Answer Key in Fizyka

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2235]
To display exercises from EOC and Answer Key correctly, flags `exercise-first-element` and `answer-key-h3` should be enabled. Description of those flags is on https://docs.google.com/document/d/1ziR2PcSvioOLAHSRNWZga3m-8DlUM_qaskIjpWtoS60/edit#heading=h.hca2jjbhejsz

**Comment by MartaSztuka** [comment]
Exercises first element is not a case in Fizyka. ![Screenshot from 2020-04-23 15-22-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e70bd37b-fc52-4e8f-a42a-93624880e870)
![Screenshot from 2020-04-23 15-20-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5c8bc376-efbe-44bf-81b4-c1e4b7336b02)
