### ISSUE TITLE
Make Footnotes Changes Backwards-Compatible + Merge g.g. footnote recipe & styles code

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2243]
# Scenario

Per discussion on Unified-Content sync, the latest recipes should include both the old and the new way of handling footnotes. We are doing this so that we can deploy to cnx.org, bake all the books with their latest recipes, and have the footnotes not break.

Then we'll deploy Phil's cnxmlutils transforms.

The footnote styles and recipe code that was originally merged into the `g.g` milestone was removed before we merged the milestone into master to avoid conflicts on REX. I will include that work in this PR. 
Related PRs: 
https://github.com/openstax/cnx-recipes/pull/2104
https://github.com/openstax/cnx-recipes/pull/2076
https://github.com/openstax/cnx-recipes/pull/2030

# Acceptance Criteria (required)
- [ ] latest recipes include both the old and new ways of handling footnotes
- [ ] books baked with latest recipes work well, with or without the accompanying transforms changes

# Test Plan
We need to confirm that footnotes are working in the "old" version of footnotes and the "new" version of footnotes. 

- [ ] When testing the old version of footnotes, confirm that footnotes are being numbered throughout the book. 

To test the new version of the footnotes, the PDF will have to be provided by @brittany-johnson . 
The code for this was previously tested, but was removed from the release so we need to test it again to confirm the fixes still work. These are the previous issues: 

- [ ] https://github.com/openstax/cnx-recipes/issues/1698
- [ ] https://github.com/openstax/cnx-recipes/issues/1803
- [ ] https://github.com/openstax/cnx-recipes/issues/1998

**Comment by brittany-johnson** [comment]
Updated recipes change log: https://docs.google.com/document/d/14E1Bgs-lK4kdmaPqQyEK2b82WAR9NtFwzElaJgPZhpQ/edit#

**Comment by brittany-johnson** [comment]
@MartaSztuka This issue is ready for testing. If you have any questions please let me know! 
Also, when you're ready to test the new version of the footnotes, let me know and I can send you the PDF

**Comment by MartaSztuka** [comment]
@brittany-johnson Thakns, I'm ready, you can send me PDFs I'll test it.

**Comment by MartaSztuka** [comment]
Microbiology![Screenshot from 2020-05-07 10-19-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5e5242b2-4ca0-4fbb-8192-20b9ab2f2038)![Screenshot from 2020-05-07 10-09-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f63e0be7-a0fe-4598-8c0d-218b9af3b1c1)
Biology ![Screenshot from 2020-05-07 10-22-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3a811bf6-c61d-4975-a04d-79ec157ecd0d) ![Screenshot from 2020-05-07 10-24-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/76cefe32-777d-4cd9-94d8-60515c09fb4f)
College Physics![Screenshot from 2020-05-07 10-28-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/130de294-ecb5-4c00-a7ac-486c6f582f64)![Screenshot from 2020-05-07 10-30-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9a727861-735c-4009-afd1-34fce2af0206)
HS Physics![Screenshot from 2020-05-07 10-32-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/06567004-39c0-48a4-ac4b-8e68e0d8af08)![Screenshot from 2020-05-07 10-35-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c79d3371-3ad6-452e-806b-060768c1b053)
