### ISSUE TITLE
Give the Word "Chapter" and the Chapter Number Different Indicators

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2244]
# Scenario

Per discussion in Unified-Content:

change from
<.os-number>Chapter 4</> <.os-divider>-</> Kinematics in 7 Dimensions
into the following instead?
<.os-somekindofthrowaway-namethatCEknowsabout>Chapter</> <.os-number>4</> <.os-divider>-</> Kinematics in 7 Dimensions

# Acceptance Criteria (required)
- [ ] REX is able to discard the word "chapter" in the URLs, even when books are baked with recipes that have the "Chapter" in the page title

# Test Plan

**Comment by philschatz** [comment]
Corresponding CE card so we can coordinate: https://github.com/openstax/cnx/issues/972

**Comment by brittany-johnson** [comment]
Expected markup : 

![Screen Shot 2020-05-13 at 10.03.25 AM.png](https://images.zenhubusercontent.com/5b0d6efdd59b032fbd122962/96972768-0ba4-4ae6-9a31-f9c7638b3c42)

**Comment by omehes** [comment]
Discussed with BJ and verified on Prealgebra 
![prealg2.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/2cf1c03e-56a0-4cc2-a1e9-a68a139a04f0)

and Uni Phys 1 on easyvm5
