### ISSUE TITLE
List unstyled in Preface in Fizyka dla szkół wyższych

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2253]
Some of the unordered lists in Preface in Fizyka dla szkół wyższych remain unstyled.
![image](https://user-images.githubusercontent.com/55203598/80011164-c5cd1200-84cb-11ea-9835-648626b86e95.png)

**Comment by MartaSztuka** [comment]
Fizyka 1
![Screenshot from 2020-04-24 11-18-10](https://user-images.githubusercontent.com/47241114/80196205-59622800-861d-11ea-9ab6-2314ad50f0f0.png)
