### ISSUE TITLE
corn theme - boxed note with class and title

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2256]
![Screen Shot 2020-07-30 at 11 08 33 AM](https://user-images.githubusercontent.com/11299125/88946563-07045900-d255-11ea-8807-8b8ffe3b17c4.png)

Same specs here (#2191) but the title of the note+numbering is bold and the `<title>` of the note is not bold

If the feature has numbering, numbering follows #.# schema. Resets every chapter (1.1, 1.2, 1.3, 2.1, 2.2, etc)

Used in Calculus frequently.

### Boxed note
color: G1:  `#F4F7F4`

### Theorem Title 
color: B2:   `#1E7E91`
font type: roboto slab
style: bold
font size: font-scale(0)

### Title from `<title>`
style: not bold 
color: B2:   `#1E7E91`
font type: roboto slab
font size: font-scale(0)

### Line between title and text
height: 1px (0.09rem?)
color: Grey1:   `#F1F1F1`

### Padding
top, left, bottom, right: v-grid(.5)

# Alternative color schema
See Problem Solving Strategy feature in Calculus
![Screen Shot 2020-07-30 at 11 05 29 AM](https://user-images.githubusercontent.com/11299125/88946443-e2a87c80-d254-11ea-9edc-61b4dfd7aece.png)

background is B4:   `#F7FAFB`; title color: B1:   `#093D4C`

**Comment by ajluk** [comment]
@lwtchu in this note is a similar problem with design with current subtitle markup created in recipes as it was in How To note: https://github.com/openstax/cnx-recipes/issues/2208#issuecomment-638243302. The subtitle during creation by recipes is placed in the note body container (div) and can't by styled like in the screenshot above right now without changes in recipes which can be rather complicated and can affect webview as well (it could be possible only if the subtitle is a sibling or child of the main title). Do you want me to leave it as it is without changing the recipes? Here is how it looks styled: 
![image](https://user-images.githubusercontent.com/55203598/88915812-38852080-d265-11ea-884d-f98aaf7f7b3c.png)
The subtitle is bolded in the content.

**Comment by ajluk** [comment]
@lwtchu The second note `Problem Strategy` in the content without any changes in the recipes looks like this. There is no division for main and subtitle:

![image](https://user-images.githubusercontent.com/55203598/88924746-f3b4b600-d273-11ea-97a4-91edef608e7f.png). 

In the webview it looks the same: 

![image](https://user-images.githubusercontent.com/55203598/88925068-560db680-d274-11ea-8c99-c7ea74ef0feb.png)

Should it be left this way? Then after styling they will be both bolded.

![image](https://user-images.githubusercontent.com/55203598/88925835-64100700-d275-11ea-8af7-a897297fab11.png)

Or I can split them how it was done to Media note by Natalia for this note:  But I'm not sure if it can affect webview then. And the first part of the subtitle will need to be removed from the content.:

![image](https://user-images.githubusercontent.com/55203598/88926706-a84fd700-d276-11ea-864c-30de2303c5f2.png)

After styling this note title and subtitle will look like in the Theorem then: 

![image](https://user-images.githubusercontent.com/55203598/88926779-c0bff180-d276-11ea-880d-d1b095894c1d.png)

 Let me know what do you think about it?

**Comment by ajluk** [comment]
@lwtchu  This is how the `Theorem` looks now in the pdf:
![image](https://user-images.githubusercontent.com/55203598/88949307-59fd0100-d293-11ea-80ab-0bdd3d4c58b4.png)
As we discussed on slack the subtitle is bolded in the content:

Only new specs were added to the **Subtitle**:
color: #1E7E91;
font-family: Roboto Slab, serif, StixGeneral;
font-size: 1rem;
line-height: 1.5rem;

**Comment by lwtchu** [comment]
awesome thank you - i think it looks good ~

**Comment by ajluk** [comment]
@lwtchu This is how looks the Problem-Solving Strategy note after styling:
![image](https://user-images.githubusercontent.com/55203598/89011248-52c80880-d310-11ea-9aa7-650c576fc1e6.png)
 
As we discusses on via slack the `Problem-Solving Strategy`statement will be removed from the content.
![image](https://user-images.githubusercontent.com/55203598/89011561-d7b32200-d310-11ea-9b0d-f8dce8fff6e0.png)

New specs added for **Subtitle** only:
**Subtitle**:
color:  #093D4C;
font-family: Roboto Slab, serif, StixGeneral;
font-size: 1rem;
line-height: 1.5rem;

**Comment by lwtchu** [comment]
@ajluk what's the hex value of the color you have for the background box?

**Comment by ajluk** [comment]
@lwtchu the background color I used is the one present in the alternative color schema in specs from above: B4: #D2E5E9: 
![image](https://user-images.githubusercontent.com/55203598/89156851-bac65b00-d56b-11ea-9d40-ca310e37ac36.png)

**Comment by lwtchu** [comment]
@ajluk okay i updated B4 to `#F7FAFB` on the specs.something was a little off with the settings on the file i had. this should be the only instance of that color i think

**Comment by ajluk** [comment]
@lwtchu Here is how the note looks with changed background color: 
![image](https://user-images.githubusercontent.com/55203598/89265901-7e5f3180-d635-11ea-82f0-5c65e683cdfd.png)

**Comment by lwtchu** [comment]
looks beautiful :) ! thank you for changing
