### ISSUE TITLE
WAITING until REX has updated all book versions: Remove old footnotes code from recipes

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2259]
# Scenario

In https://github.com/openstax/cnx-recipes/issues/2243 we made the footnotes changes backwards-compatible so that we could rebake the books at latest recipes without transforms changes, have REX get those versions, then deploy the transforms code.

Phil pointed out that we want to maintain our code and remove things when they are no longer being used. Therefore, we should remove the old way of handling footnotes once the process above is complete.

# Acceptance Criteria (required)
- [ ] recipes only support new footnote format
- [ ] recipes no longer support old footnote format

# Test Plan

**Comment by lwtchu** [comment]
I think cookbook resolved this.
