### ISSUE TITLE
Add lines to EOC titles

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2260]
Since each module in EOC is a separate page, text in two lolumn layout jump to the second column within this part. In PDF, modules display one by one, so sometimes it's little bit confusing, where is the next part of the sentence:

![image](https://user-images.githubusercontent.com/40228854/80187416-e605e980-860f-11ea-8cce-2a7b3c1cb7bb.png)

To make it more readable, add lines next to the titles, to separate one section from another:

![image](https://user-images.githubusercontent.com/40228854/80187641-44cb6300-8610-11ea-9c7b-ca49d2c83acb.png)

**Comment by wilkus27** [comment]
#### Decision

Since EOC has different structure in different books, it's hard to apply this feature everywhere.
Decision will be made for each book separately.

@lwtchu in this case, I move this issue to Icebox and assign it to you.

**Comment by wilkus27** [comment]
#### Informations from thread in Slack:

 In HS Physics there are regular composite pages (like Key Equations) and two composite chapters (Chapter Review, Test Prep) with compound composite pages inside. This is how it looks, when lines are added to all titles. We have two lines next to each other:

![image](https://user-images.githubusercontent.com/40228854/80944272-6cc57e00-8de9-11ea-92f4-58a59cdb9f43.png)


#### There are three types of books.

First:
- Key Terms - composite page - title H2
- Summary - composite page - title H2
- Exercises - composite page - title H2

Second:
- Key Terms - composite page - title H2
- Summary - composite page - title H2
- Chapter Review - composite chapter - title H2
  - Exercises - compound composite page - title H3

Third:
- Chapter Review - composite chapter - title H2
  - Key Terms - compound composite page - title H3
  - Summary - compound composite page - title H3
  - Exercises - compound composite page - title H3

**Comment by lwtchu** [comment]
We'll revisit this when we officially bring other titles into the carnival theme

**Comment by brittweinstein** [comment]
@lwtchu what action, if any, is needed here?

**Comment by lwtchu** [comment]
@brittweinstein this is super low priority. and i don't think this needs/should be worked on right now

**Comment by lwtchu** [comment]
closing. will open a new one if we need it
