### ISSUE TITLE
Uppercase letters in headers set in the content in Worked Examples HSPhysics

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2261]
Uppercase letters in these headers set in the content in Worked Examples HSPhysics need to  be changed to capitalized to match other headers present in this note:
![image](https://user-images.githubusercontent.com/55203598/80378875-99374280-889d-11ea-8fbf-cd8657921849.png)

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1660](https://github.com/openstax/content-managers/issues/1660) via [**ZenHub**](https://www.zenhub.com/)
