### ISSUE TITLE
Preface headers need to be styled after content changing

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2264]
![image](https://user-images.githubusercontent.com/55203598/80569236-c6e4ce80-89f8-11ea-901b-1432cb0e2615.png)
These titles in Fizyka are now placed in divs with data-type="title" and should be first replaced in the content with H3 to be styled consistently as it was done in HSPhysics:
![image](https://user-images.githubusercontent.com/55203598/80571498-03b2c480-89fd-11ea-9767-23a1cfe02c89.png)
Now they look like this: 
![image](https://user-images.githubusercontent.com/55203598/80571317-b33b6700-89fc-11ea-97a3-7acd3d5b091f.png)

**Comment by ajluk** [comment]
After changes made in the content the there is no need to style the headers in the Preface in this book. They are consistent with the other titles in others book from Carnival Theme. How the header look now: 
![image](https://user-images.githubusercontent.com/55203598/80944242-5c150800-8de9-11ea-91f8-eb05d9d04699.png)

**Comment by MartaSztuka** [comment]
Changes are accepted, headers in Preface looks great after this fix.
