### ISSUE TITLE
calculus - outlined box note

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2266]
<img width="859" alt="Screen Shot 2020-04-29 at 1 49 33 PM" src="https://user-images.githubusercontent.com/11299125/80635335-5bfbbd80-8a21-11ea-834a-6669415ba7fb.png">

Title of the feature
font type: Roboto Slab
style: Bold, all caps
size: font-scale(1)
color: B1:   `#093D4C`

Title from `<title>` in note
font type: noto sans
style: bold
size: font-scale(0)
color: B1:   `#093D4C`

Outline 
color: B1:   `#093D4C`
height: 1px (0.09rem?)

Line between feature title and title
color: B1:   `#093D4C`
height: 1px (0.09rem?)

**Comment by ajluk** [comment]
@lwtchu here is how the note looks in the pdf file: 

![image](https://user-images.githubusercontent.com/55203598/89032081-2920d880-d334-11ea-8e19-27f24dddb6bf.png)

The titles are bolded in the content as in the other notes. I have also made the main title uppercase as in the screenshot you provided, but this property wasn't in the specs. Let me know if I should change it?

**Comment by lwtchu** [comment]
@ajluk can you clarify which is the "main title" you're talking about? I want to make sure we're on the same page before saying something :joy:

**Comment by ajluk** [comment]
@lwtchu  Oh, sure! I used the name `main title` for the note/feature title on the top: 
![image](https://user-images.githubusercontent.com/55203598/89053574-b7f31c80-d357-11ea-8a6f-4d4450bd2182.png)

**Comment by lwtchu** [comment]
oh okay yes i updated the specs and these look good :) thank you!
