### ISSUE TITLE
Fix Appendix Header Font

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2276]
Headers like 'exponential arithmetics' are written in Alegreya, should be Muli.
![Screenshot from 2020-05-05 15-13-00](https://user-images.githubusercontent.com/47241114/81145741-2d2c9c80-8f77-11ea-82f3-718c9f45a119.png)

**Comment by MartaSztuka** [comment]
@Stackblocks Header font and colour is correct but Appendix B should be in one line.
![Screenshot from 2020-05-12 09-13-59](https://user-images.githubusercontent.com/47241114/81649892-4fb82d00-9431-11ea-8515-8fbc9c57b924.png)

**Comment by Stackblocks** [comment]
@MartaSztuka For this one, the attached PR only modifies the targeting of the $H2- and $H3Component, and does not make any structural changes so this regression would seem to be unrelated.

**Comment by MartaSztuka** [comment]
@Stackblocks Ok, thanks, I'm closing it.
