### ISSUE TITLE
Leading in headers

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2282]
Leading and margin is too small in certain headers.
![Screenshot from 2020-05-07 11-33-35](https://user-images.githubusercontent.com/47241114/81279046-dac2ad00-9056-11ea-903f-6e78c2342b34.png)
![Screenshot from 2020-05-07 11-45-34](https://user-images.githubusercontent.com/47241114/81280100-4e18ee80-9058-11ea-8d39-e1a3825983eb.png)

**Comment by brittweinstein** [comment]
This is reflected in #2288 so I will combine these issues.
