### ISSUE TITLE
Chapter intro order

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2283]
Elements are not in order.
![Screenshot from 2020-05-07 11-55-44](https://user-images.githubusercontent.com/47241114/81281124-b87e5e80-9059-11ea-8bdf-c333a7d34383.png)
How it should be
![Screenshot from 2020-05-07 11-56-51](https://user-images.githubusercontent.com/47241114/81281299-f24f6500-9059-11ea-85c1-09b345d6fc8c.png)

**Comment by ajluk** [comment]
It is a content issue. The `figure` tag is missing class `splash` and therefor the mixin `modify_tagSplash`is not working there: 
![image](https://user-images.githubusercontent.com/55203598/81315109-2cd0f600-908a-11ea-9fe2-e9daa738ac82.png)

**Comment by MartaSztuka** [comment]
Issue moved to https://github.com/openstax-poland/content/issues/14
I'm closing
