### ISSUE TITLE
Key Equations table styling

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2285]
Table should not be visible.
vol 2
![Screenshot from 2020-05-07 14-08-29](https://user-images.githubusercontent.com/47241114/81292698-5a0eab80-906c-11ea-91da-c9de2227a48c.png)
vol 3
![Screenshot from 2020-05-07 13-21-24](https://user-images.githubusercontent.com/47241114/81288885-bfab6980-9065-11ea-9be7-7350be731621.png)

**Comment by ajluk** [comment]
It is a content issue. The `unstyled` class is missing in the tables in Key Equations in chapter 10:
Fizyka vol 3:
![image](https://user-images.githubusercontent.com/55203598/81312883-6f450380-9087-11ea-8923-e4fb1cc85e69.png)
and in Chapter 2 in Fizyka vol 2 `unstyled` and `unnumbered` class are missing in the table: 
![image](https://user-images.githubusercontent.com/55203598/81313246-e7abc480-9087-11ea-82e5-648933e1072c.png)

**Comment by MartaSztuka** [comment]
I'm moving issue to https://github.com/openstax-poland/content/issues/13
