### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2287]
Footnotes are unstyled.
![Screenshot from 2020-05-07 13-53-22](https://user-images.githubusercontent.com/47241114/81291681-8c1f0e00-906a-11ea-966c-c1244a5fe629.png)

**Comment by brittweinstein** [comment]
@MartaSztuka can you check and see if this is still occurring?

**Comment by wilkus27** [comment]
Veryfied. Footnotes are styled now, but there is some problem with order of points:

![image](https://user-images.githubusercontent.com/40228854/92118317-9f62a000-edf6-11ea-976b-6962c3a432a1.png)

**Comment by brittweinstein** [comment]
@wilkus27 could we close this card and open a new one for the ordering above?

**Comment by wilkus27** [comment]
@brittweinstein Yes, here is the new issue for this problem https://github.com/openstax/cnx-recipes/issues/2753
