### ISSUE TITLE
Chapter headers need more space

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2288]
Refers both to ToC and Chapter header, especially when line breaks in two.
Anatomy
![Screenshot from 2020-05-07 16-14-17](https://user-images.githubusercontent.com/47241114/81304782-d2ca3380-907d-11ea-9dc0-58cc955e83f1.png)
![Screenshot from 2020-05-07 16-18-35](https://user-images.githubusercontent.com/47241114/81305291-70256780-907e-11ea-840d-05e2b4089d55.png)
AP Biology
![Screenshot from 2020-05-07 16-16-04](https://user-images.githubusercontent.com/47241114/81304993-16bd3880-907e-11ea-82a9-5e5467178415.png)
Biology 2e
![Screenshot from 2020-05-07 16-17-31](https://user-images.githubusercontent.com/47241114/81305157-49673100-907e-11ea-8aff-a24f2ca8becc.png)
Chemistry 2e
![Screenshot from 2020-05-07 16-21-20](https://user-images.githubusercontent.com/47241114/81305612-d4e0c200-907e-11ea-84a8-44b694868fa4.png)
Chemistry AF
![Screenshot from 2020-05-07 16-22-30](https://user-images.githubusercontent.com/47241114/81305786-09547e00-907f-11ea-8faa-89a44bb137bd.png)
Concepts of Biology
![Screenshot from 2020-05-07 16-23-44](https://user-images.githubusercontent.com/47241114/81305940-36089580-907f-11ea-9f0f-1781f713014f.png)
HS Physics
![Screenshot from 2020-05-07 16-25-24](https://user-images.githubusercontent.com/47241114/81306116-65b79d80-907f-11ea-9446-13b18e232798.png)
Microbiology
![Screenshot from 2020-05-07 16-26-22](https://user-images.githubusercontent.com/47241114/81306239-8849b680-907f-11ea-84cf-23be4c218827.png)
College Physics
![Screenshot from 2020-05-07 16-27-41](https://user-images.githubusercontent.com/47241114/81306391-b5966480-907f-11ea-8907-3dede857d05d.png)
University Physics
![Screenshot from 2020-05-07 16-28-38](https://user-images.githubusercontent.com/47241114/81306514-da8ad780-907f-11ea-9b4f-b4ed6d9524c1.png)

**Comment by lwtchu** [comment]
What are the specs currently? There's been a few changes since I last saw these

**Comment by brittweinstein** [comment]
@MartaSztuka are you able to provide the specs?

**Comment by MartaSztuka** [comment]
Unit links
 font-family: (_ref: 'typography:::sansFont'),
 font-size: font-scale(4),
 line-height: line-height(4),
 font-weight: bolder,
 color: #3172B6,
 border-bottom: "0.1rem solid black",
 text-transform: uppercase,
 letter-spacing: 0.1rem,
 text-decoration: none,
 padding-bottom: half-v-grid(1),
 margin-bottom: half-v-grid(1)

**Comment by lwtchu** [comment]
can we try half-v-grid(2)  - or someone ping me when you work on this so we can tweak it. i don't think i have the half-v-grid scaled documented somewhere and would be helpful to have the values for every increment

**Comment by brittweinstein** [comment]
This also occurs in Fizyka: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2282

**Comment by MartaSztuka** [comment]
@brittweinstein Problem still occurs
![Screenshot from 2020-05-27 10-20-54](https://user-images.githubusercontent.com/47241114/82995349-c6455500-a003-11ea-94a9-b0dfbcc11a71.png)

**Comment by brittweinstein** [comment]
@MartaSztuka can you confirm that this still occurs?

**Comment by MartaSztuka** [comment]
@wilkus27 There's still an issue with spacing in headers
##### Anatomy
![Screenshot from 2021-02-22 11-48-15](https://user-images.githubusercontent.com/47241114/108698174-1f470880-7504-11eb-8674-3b2c78a82b26.png)
##### AP Biology
![Screenshot from 2021-02-22 12-17-30](https://user-images.githubusercontent.com/47241114/108701235-f759a400-7507-11eb-989a-f4aa2e7800d0.png)

**Comment by wilkus27** [comment]
@lwtchu Style for chapter headers is already changed. Font is lighter then before. This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/160128074-35662576-6cb4-4a31-9c8c-ab5cb5b4ad77.png)

Do we still need more room here?

About unit titles in TOC, font size is set to `font-scale(4)` and line height to `line-height(3)`. I checked and `line-height(3)` is the same as `line-heaight(4)`. I tried next one (`line-height(5)`), but it was too big:

![image](https://user-images.githubusercontent.com/40228854/160128689-bd55c147-5e2e-4378-862f-98f792e3db0d.png)

So I decided to apply line height the same as font size (so `font-scale(4)`). This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/160128908-898518ee-ccfc-4c77-9a75-0c3eb182187d.png)

Is it ok or should I increase/decrease it?

**Comment by lwtchu** [comment]
@wilkus27 what you have looks good - does it increase the page count by a lot? :eyes:

**Comment by wilkus27** [comment]
@lwtchu I made a change only for TOC, so e.g in Anatomy it doesn't change page count.

**Comment by MartaSztuka** [comment]
#### PASSED
##### COLLEGE PHYSICS
![Screenshot from 2022-03-30 11-26-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3fa39e06-1dc5-41e2-be38-633cf10faede)
##### AP PHYSICS
![Screenshot from 2022-03-30 11-49-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/894254c3-7313-44fd-9c33-c8ac52a880cd)
##### UNIVERSITY PHYSICS 1
![Screenshot from 2022-03-30 12-37-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a983625e-b4c0-4724-81e5-8037623f9009)
![Screenshot from 2022-03-30 12-41-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d6748dd2-b7eb-4c74-bb20-d3d7c63afc33)
##### UNIVERSITY PHYSICS 2
![Screenshot from 2022-03-30 12-39-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0b14b42e-1a2d-418a-ad6c-7d20fd0b9afa)
![Screenshot from 2022-03-30 12-45-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/49b92711-ff03-4ccb-8331-2e7142750d46)
##### UNIVERSITY PHYSICS 3
![Screenshot from 2022-03-30 12-40-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7ac0c81a-fc12-4a8c-923c-1b95b7756742)
![Screenshot from 2022-03-30 12-42-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/df522b7c-baf2-45d3-938e-7c58fdff6df1)
##### BIOLOGY 2E
![Screenshot from 2022-03-30 13-19-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a7343590-d0c5-4fb1-9e51-aadcfd5573f4)![Screenshot from 2022-03-30 13-18-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6984f70c-e561-4a6d-b964-d8c559d62b1d)
##### BIOLOGY AP COURSES
![Screenshot from 2022-03-30 13-22-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/33caf587-00a5-4a6c-9e11-a958e319890d)![Screenshot from 2022-03-30 13-22-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/36d81563-2e5f-4f1f-a8e5-a5ac117ee1a5)
##### CHEMISTRY 2E
![Screenshot from 2022-03-30 13-47-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/594fadd5-043a-4a1a-b9f7-c9f6a30190bf)
##### CHEMISTRY AF
![Screenshot from 2022-03-30 13-58-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/25deb692-3126-4e98-86d6-95796462e73b)
##### ANATOMY AND PHYSIOLOGY
![Screenshot from 2022-03-30 15-13-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bfc4f709-a8c8-4dcd-abb2-8b35b0e8482a)
