### ISSUE TITLE
Colours in modules

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2290]
`By the end of this chapter` colour is #0074BC, should be #00819A
![Screenshot from 2020-05-08 12-06-56](https://user-images.githubusercontent.com/47241114/81396296-6c005500-9125-11ea-9977-f84264ab0304.png)

**Comment by wilkus27** [comment]
This will be resolved within https://github.com/openstax/cnx-recipes/pull/2293

**Comment by MartaSztuka** [comment]
![Screenshot from 2020-05-18 08-44-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cda477cd-359f-45f8-9d2d-0e247198f99a)
