### ISSUE TITLE
Figure cropped

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2294]
Right side is not complet.
![Screenshot from 2020-05-08 14-20-55](https://user-images.githubusercontent.com/47241114/81405426-e0dc8a80-9137-11ea-8517-6a587221fdfa.png)
They are all a bit out, but most cases it's easy to miss.
PDF
![Screenshot from 2020-05-08 14-37-32](https://user-images.githubusercontent.com/47241114/81406326-a5db5680-9139-11ea-9d1b-aae6774b6109.png)
.xhtml
![Screenshot from 2020-05-08 14-37-22](https://user-images.githubusercontent.com/47241114/81406333-a7a51a00-9139-11ea-943f-806f8d7633ac.png)

**Comment by ajluk** [comment]
This is happening because the image itself needs to be wider than the outer span with caption text due to the bleed requirements.

**Comment by lwtchu** [comment]
This is a content issue I"m moving this.

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1679](https://github.com/openstax/content-managers/issues/1679) via [**ZenHub**](https://www.zenhub.com/)
