### ISSUE TITLE
Numbers are unstyled

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2295]
1. They shouldn't stick out
![Screenshot from 2020-05-08 16-00-08](https://user-images.githubusercontent.com/47241114/81413236-6286e500-9145-11ea-8e29-a8d6bbb7ba17.png)
2. ABC-s could use some bold
![Screenshot from 2020-05-08 16-11-11](https://user-images.githubusercontent.com/47241114/81414143-d07fdc00-9146-11ea-8193-2c06968a7dd3.png)

**Comment by ajluk** [comment]
The second point of the issue that the lists letters should be bold will affect all Examples in all Fizyka's volumes and this is not a desired change. After discussion with Marta it will be omitted. Here is the exmaple form Fizyka vol1 where there is no bolded text in such type of lists and bolded lists letters will look odd:
![image](https://user-images.githubusercontent.com/55203598/81572138-20f37580-93a3-11ea-9033-cd8a0627d92e.png)

**Comment by MartaSztuka** [comment]
![Screenshot from 2020-05-14 11-20-13](https://user-images.githubusercontent.com/47241114/81917033-f5f06800-95d4-11ea-97c3-bf3042534ec8.png)
