### ISSUE TITLE
Update Chapter, Unit, and Appendix Title Components 

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#2301]
# Scenario
Due to the structure of the chapter, unit, and appendix titles changing in https://github.com/openstax/cnx-recipes/issues/1973 , the style components need to be updated.
Issue originally identified in https://github.com/openstax/cnx-recipes/issues/1973

# Acceptance Criteria (required)
Chapter, Unit, and Appendix titles are displaying as they were before in the TOC and throughout book

# Books: 

- [ ] chemistry-2e

![81662113-64022700-943d-11ea-830d-34d6570ae988](https://user-images.githubusercontent.com/24909007/81718451-5e0e4500-9441-11ea-8a37-6b7345106161.png)

**Comment by Stackblocks** [comment]
# Lessons Learned
## 1 - Missing Style
Issue: After breaking apart `.os-number` into two parts, the targeting needed to be updated to include the new pieces.

Solution: Make a paired component to the `.os-number` part of `$Title__Number` that covered `.os-part-text` and applied the same style.

## 2 - Line Break
Issue: The Chapter Title is breaking across two lines, where the word "chaper" is on one line, and the number is on the following.

Solution: Change the `display` from `block` to `inline block`.

## 3 - Mid-Title Gap
Issue: Now that there are two parts of the Chapter Title, the two parts either sit too flush, or there is a gap in between them in the bottom-bordered Appendix Titles.

Solution: Use a `::before` pseudo to cover the space between the two pieces.

**Comment by Stackblocks** [comment]
# Before
![image](https://user-images.githubusercontent.com/12678235/84050801-d64e2480-a973-11ea-8031-c76777f82764.png)
![2020-06-08_17-43-56](https://user-images.githubusercontent.com/12678235/84087405-aae92b00-a9af-11ea-81c2-e52b24ccdc0c.png)


# After
![2020-06-09_12-56-03](https://user-images.githubusercontent.com/12678235/84182810-a032a280-aa50-11ea-8ad1-07f03a892a74.png)
![image](https://user-images.githubusercontent.com/12678235/84427547-b2484880-abea-11ea-9eec-b71aeb07a406.png)

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-15 17-14-20](https://user-images.githubusercontent.com/47241114/84674788-b3031680-af2b-11ea-905e-2208017b9f2a.png)
![Screenshot from 2020-06-15 17-13-32](https://user-images.githubusercontent.com/47241114/84674793-b4344380-af2b-11ea-932f-829e72cbbea1.png)
