### ISSUE TITLE
APUSH - Suppress Index

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2311]
# Scenario

 It is not possible to create an Index that will meet APUSH course standards with the auto-generated functionality. Specifically, first/last name sorting is very challenging when we can only use content as it appears in the textbook itself. Please suppress the Index in the APUSH recipe. We are implementing a Glossary instead.

Test content: https://easyvm5.cnx.org/contents/I3AIQB35@22.1:VW9EWNTw@22.1/Index

# Acceptance Criteria (required)
- [ ] even with `term` tags used in the content, the Index does not display in the webview of APUSH.

# Test Plan

**Comment by openstaxalina** [comment]
Content being created as part of https://github.com/openstax/content-managers/issues/1698

**Comment by brittany-johnson** [comment]
- `term` still present in content
- Index removed

![Screen Shot 2020-06-11 at 9 54 19 AM](https://user-images.githubusercontent.com/24909007/84402021-91233000-abc9-11ea-8d8a-c56d3eebd94f.png)


![Screen Shot 2020-06-11 at 9 54 04 AM](https://user-images.githubusercontent.com/24909007/84402030-93858a00-abc9-11ea-89fb-ab415e15b8d8.png)

**Comment by brittweinstein** [comment]
@brittany-johnson and @Stackblocks will test this on easyvm5 and @openstaxalina and/or Ryan will test this on staging.

**Comment by Stackblocks** [comment]
Verified on easyvm5.cnx.org, Next step is for @openstaxalina & co. to verify on staging.

# Before 
![image](https://user-images.githubusercontent.com/12678235/84680433-55a1a200-aef8-11ea-9ffc-2f18e5c270ce.png)


# After
![image](https://user-images.githubusercontent.com/12678235/84680442-59cdbf80-aef8-11ea-828c-17bfdedb8663.png)

**Comment by brittany-johnson** [comment]
@openstaxalina Hello! Who should I assign from our side to test this issue?

**Comment by oscryan** [comment]
ok the index is gone on staging
<img width="604" alt="Screen Shot 2020-06-18 at 1 03 22 PM" src="https://user-images.githubusercontent.com/1895432/85056013-1ecfc400-b164-11ea-9704-d95e916bc4cf.png">
