### ISSUE TITLE
AP Biology missing exercises

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2313]
Problem with Assemble script.
![Screenshot from 2020-05-19 14-41-09](https://user-images.githubusercontent.com/47241114/82334477-55d97b00-99e8-11ea-838c-b2ca27ae5ddb.png)

**Comment by MartaSztuka** [comment]
@brittweinstein I fetched AP Biology again, problem still occurs.
![Screenshot from 2020-05-27 10-02-55](https://user-images.githubusercontent.com/47241114/82993704-49b17700-a001-11ea-9926-768e6c99f31d.png)

**Comment by brittweinstein** [comment]
@openstaxalina and @Bkblodget we could be seeing this for a number of reasons. We should have CE Tech take a look into Neb to see if this is simply a result of a bad fetch/content/etc.. For now, this has not been deemed a priority by either team.

**Comment by MartaSztuka** [comment]
##### FAILED
@wilkus27 Some exercises are still missing i chapters 24 to 38, sometimes all, sometimes few.
![Screenshot from 2021-02-19 17-47-33](https://user-images.githubusercontent.com/47241114/108534727-c0eb1180-72da-11eb-9d03-5e6bc81c9bb3.png)
![Screenshot from 2021-02-19 17-51-14](https://user-images.githubusercontent.com/47241114/108535247-68684400-72db-11eb-8a87-14114a20ee11.png)

**Comment by lwtchu** [comment]
the exercises need to be fetched from exercises - is there not a way for the CLI at the moment to fetch them?

**Comment by lwtchu** [comment]
:eyes: closing? it's p old. we can reopen if it's a pressing issue
