### ISSUE TITLE
corn theme: introduction page

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2314]
### Type 1: standard splash + full width chapter outline

<img width="652" alt="Screen Shot 2020-05-21 at 12 16 24 PM" src="https://user-images.githubusercontent.com/11299125/82586260-e9cc5380-9b5c-11ea-9cdf-ef5f5298526c.png">

- Title H1: https://github.com/openstax/cnx-recipes/issues/2144
- Image: https://github.com/openstax/cnx-recipes/issues/1752
- Image caption: https://github.com/openstax/cnx-recipes/issues/2185
- Chapter Outline and Introduction title: https://github.com/openstax/cnx-recipes/issues/2189

**Comment by ajluk** [comment]
Hi @lwtchu! I have added styles to Introduction Page for Calculus vol1 and there splash images in the content have different height in different chapters: 
![image](https://user-images.githubusercontent.com/55203598/88676966-02bd2c00-d0ed-11ea-9999-395bafab80e7.png)
![image](https://user-images.githubusercontent.com/55203598/88677002-1072b180-d0ed-11ea-86e4-13126f0e2043.png)
This causes the chapter title to appear in different places over the image. I can fix this in the code by setting the exact height for images in the code (3.21in) to make them look like in the other corn theme books. How it looks then: 
![image](https://user-images.githubusercontent.com/55203598/88677320-6ba4a400-d0ed-11ea-87b6-e19c652dd5b7.png)
![image](https://user-images.githubusercontent.com/55203598/88677360-7828fc80-d0ed-11ea-8256-c5660efba6a0.png)
But let me know if it will be a better solution to fix this in the content?

**Comment by lwtchu** [comment]
@ajluk we'll standardize the height of the splash image! this will be a content fix

**Comment by wilkus27** [comment]
@lwtchu Based on information from https://github.com/openstax/cnx-recipes/issues/2267 there is no Chapter Outline and Learning Objectives in Statistics. It appears Chapter Objectives. I styled it like Learning Objectives:

![image](https://user-images.githubusercontent.com/40228854/89540347-325ee900-d7fd-11ea-810b-c87690876e5b.png)

Is it ok? Or should I change something?

**Comment by lwtchu** [comment]
@wilkus27 this is great thank you!
