### ISSUE TITLE
Prealgebra: style Table of Contents

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2316]
Style TOC with specs from https://github.com/openstax/cnx-recipes/issues/2060

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-03 12-40-47](https://user-images.githubusercontent.com/47241114/83627733-b4315c80-a597-11ea-80de-182e959bcb94.png)
![Screenshot from 2020-06-03 12-40-34](https://user-images.githubusercontent.com/47241114/83627738-b4c9f300-a597-11ea-9a0d-5d9adad34cd8.png)

**Comment by lwtchu** [comment]
Reopening to retest with the square boxes https://github.com/openstax/cnx-recipes/issues/2060#issuecomment-638876187

**Comment by lwtchu** [comment]
jk..i see natalia open #2401
