### ISSUE TITLE
corn theme: appendix and preface header and titles

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2320]
# Preface/Appendix

## H1 (Title)
font-size: font-scale(4): 17.10pt, 22.81px, 2.1rem
font style: roboto slab
color: B2:   `#1E7E91`

## Appendix number/letter
<img width="394" alt="Screen Shot 2020-04-09 at 3 37 15 PM" src="https://user-images.githubusercontent.com/11299125/78938552-0b272380-7a78-11ea-8705-c679f36f28bc.png">

font-size: font-scale(4): 17.10pt, 22.81px, 2.1rem
font style: roboto slab
font color: `#000000`
box color: B2:   `#1E7E91`

## H2
font-size: font-scale(3): 14.25pt, 19.01px, 1.7rem
font style: roboto slab
color: B2:   `#1E7E91`

## H3
font-size: font-scale(2): 11.88pt, 15.84px, 1.4rem
font style: roboto slab
color: B2:   `#1E7E91`

## H4
font size: font-scale(1): 9.9pt, 13.2px, 1.2rem
font style: roboto slab
color: B2:   `#1E7E91`

## H5
font-family: Roboto Slab, serif;
color: B2:   `#1E7E91`
font size: font-scale(0): 8.25pt, 11px, 1rem

## Base font
font size: font-scale(0): 8.25pt, 11px, 1rem
color: black `#000000`
font type: Noto Sans

**Comment by wilkus27** [comment]
@lwtchu here is the issue for module titles https://github.com/openstax/cnx-recipes/issues/2144. There h2-h5 headers have different values of font-size then here. Is it intentional? Shouldn't headers in Preface be styled the same as in modules?

**Comment by lwtchu** [comment]
@wilkus27 looks like my brain short circuited and i went down one value too early - i fixed it ...it should match the other issue now. thanks for asking!

**Comment by wilkus27** [comment]
@lwtchu In this case, shouldn't h1 be bigger now? It has `font-scale(3)` as h2.

**Comment by lwtchu** [comment]
@wilkus27 i adjusted it again. when this is done can i take a look at them 🤔 h1's and h2's to people viewing the book are a little different than the way it is set up in the HTML so i want to make sure it's consistent

**Comment by wilkus27** [comment]
Yes, of course, I will add screenshots, when it will be ready. Thank you! :slightly_smiling_face:

**Comment by wilkus27** [comment]
@lwtchu I have found in Preface titles in paragraphs. They are not in any header tag (h1-h5)

![image](https://user-images.githubusercontent.com/40228854/83030561-f573ba80-a033-11ea-9ddb-2469d9b935c3.png)

How we should style them?

Also, here is the screenshot with styled Preface:

![image](https://user-images.githubusercontent.com/40228854/83030966-4f748000-a034-11ea-8059-86c5e417d31c.png)

First header marked by arrow it's `H1`, second - `H3`, third - `H4`. There is no `H2` and `H5` in Preface.

What is more, some of the headers are italic:

![image](https://user-images.githubusercontent.com/40228854/83031412-cf9ae580-a034-11ea-8a4e-e1d64b755f9b.png)

It is hard coded in the content:

![image](https://user-images.githubusercontent.com/40228854/83031541-f822df80-a034-11ea-8c52-553edb30162a.png)

Is it ok?

**Comment by lwtchu** [comment]
@wilkus27 the hardcoded italics is fine, please don't use anything to override what is hardcoded. if we need to change it we should change it in the content.

can you double check installed fonts? they're not showing up correctly in the screenshot

**Comment by wilkus27** [comment]
@larissa here is the screenshot with fixed fonts:

![image](https://user-images.githubusercontent.com/40228854/83245538-27565f80-a1a1-11ea-9d9b-d03ead394261.png)

Is it ok? Or should I change something?

Also, what is the decision about first problem which I described in my previous comment? About titles in paragraphs? Do we want to style them in some way?

Here is the screenshot from PDF (previous one was from baked html)

![image](https://user-images.githubusercontent.com/40228854/83245828-9633b880-a1a1-11ea-9948-d382ed12039f.png)

**Comment by brittweinstein** [comment]
@wilkus27 please put points on this card

**Comment by lwtchu** [comment]
Checked the updated PDF with the installed fonts - looks good thank you!

**Comment by wilkus27** [comment]
@lwtchu Thank you! :slightly_smiling_face: So as I understand, titles `How To`, `Try It` and `Media` also look good and we leave them unstyled, that's right?

**Comment by lwtchu** [comment]
@wilkus27 i changed the para titles to be section titles - do you mind checking the preface again with the specs

**Comment by wilkus27** [comment]
@lwtchu This is how it looks like:

![image](https://user-images.githubusercontent.com/40228854/83514869-b67eb280-a4d4-11ea-9e9b-a60a2ec3cf06.png)

They are now `h5` headers.

**Comment by lwtchu** [comment]
i don't have h5 headers set up at the top - is it the same as the others but at font-scale(0)?

**Comment by wilkus27** [comment]
@lwtchu Yes, here are the exact specs:

```
font-family: Roboto Slab, serif;
  color: #1E7E91;
  font-size: 1rem;
  line-height: 1.5rem;
```

**Comment by lwtchu** [comment]
thank you! moving to documentation

**Comment by lwtchu** [comment]
this looks good thanks!

**Comment by wilkus27** [comment]
@lwtchu I'm working on https://github.com/openstax/cnx-recipes/issues/2428. There is information that H1 should be font-scale(3). Previously, we decided that headers with the same level should have the same font-size in entire book. Because we have 5 levels H1-H5 we had to apply for H1 in Preface font-scale(4). Are we sure that we want to make acceptions for Appendix and Index and apply font-scale(3) for H1 in those sections? I'm afraid it might be risky. In Prealgebra there are no H2 headers in Appendix and Index, but are we sure that other books also don't have it? If H2 exists in other books, then two types of headers H1 and H2 will be font-scale(3).

**Comment by lwtchu** [comment]
@wilkus27 hmm...do you think we should just keep it at font-scale(4) across the board and have the font in the box go up with it?

**Comment by wilkus27** [comment]
Yes, I think it would be safer. @ajluk @brittany-johnson @Stackblocks what is your opinion about that?

**Comment by ajluk** [comment]
@wilkus27 Yes, it would be safer. We don't need to rework it if in the other books there will be H2 header inside these book parts. I guess the only minus is that it will look worse.

**Comment by Stackblocks** [comment]
Yeah, I think consistency of size + part will keep things from getting really messy down the line.

**Comment by ajluk** [comment]
@lwtchu I have increased the font-size for the H1 title in Appendices as Natalia and Alan suggested and this is how it looks now: 
![image](https://user-images.githubusercontent.com/55203598/85386211-970efe80-b543-11ea-8467-ec9354e4ebb7.png)
Should I change anything?

**Comment by lwtchu** [comment]
@ajluk yep i think that's fine - just want to confirm that the letter in the box isn't bold

**Comment by ajluk** [comment]
@lwtchu Sure! It isn't bolded: 
![image](https://user-images.githubusercontent.com/55203598/85413435-1cf27000-b56b-11ea-80ec-c71d30ebbab1.png)

**Comment by lwtchu** [comment]
Thanks! I updated the specs above to reflect the new font size for H1s and the letter in the box. We can move fwd with testing whenever you are ready~
