### ISSUE TITLE
corn theme: key terms

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2321]
<img width="535" alt="Screen Shot 2020-05-21 at 3 27 46 PM" src="https://user-images.githubusercontent.com/11299125/82603101-b3e89880-9b77-11ea-85dd-946065bdb70d.png">

headers should follow the standard header/titles formatting: #2144

term: bold, noto sans, font-scale(0), `#000000`
definition: noto sans, font-scale(0), `#000000` 
hanging indent: yes, spacing: v-grid(1) (?) are we still doing this

**Comment by ajluk** [comment]
How it looks now: 
![image](https://user-images.githubusercontent.com/55203598/83905691-6583ee00-a762-11ea-8a74-95ccab8b7b05.png)
@lwtchu should Key Terms be a part of composite chapter Chapter Review as in the screenshot above, because now it is a regular composite page.

**Comment by ajluk** [comment]
Specs added:
![image](https://user-images.githubusercontent.com/55203598/83907167-37ec7400-a765-11ea-9bd0-aba8de004e2b.png)

**EOC H2Title**
 color: #1E7E91,
 font-family: 'Roboto Slab', serif
 font-size: font-scale(3),
 margin-bottom: v-spacing(1),
text-transform: uppercase
**EoC container**:
margin-bottom: v-spacing(2),
**Term DT**
 font-weight: bold,
padding-right: h-spacing(1),
display: inline,
**TermDD**
display: inline,
margin-left: h-spacing(0),
**TermDL**
 text-indent: h-spacing(-2),
padding-left: h-spacing(2),

**Comment by lwtchu** [comment]
this looks good thank you

**Comment by ajluk** [comment]
@lwtchu maby you have missed it, because I have updated the comment above: https://github.com/openstax/cnx-recipes/issues/2321#issuecomment-639652547. Could you advise if we want to keep the current structure of the document or we want it to look hot it looks in the old pdf?

**Comment by lwtchu** [comment]
@ajluk oops sorry! when i opened the issue from my email it jumped to the latest comment 😓  

just to make sure - if we keep it like it is now, the words "chapter 1 review" will go away?

**Comment by ajluk** [comment]
@lwtchu yes, that's correct.

**Comment by ajluk** [comment]
And the title `Exercises` will stay there as well: 
![image](https://user-images.githubusercontent.com/55203598/84055890-bc353600-a9b5-11ea-815a-16d5d729a1c3.png)

**Comment by lwtchu** [comment]
Let's remove Exercises composite page and add Chapter Review as a composite page so it'll reflect the book.

**Comment by ajluk** [comment]
@lwtchu I'm asking just to be sure. Should all of the EoC parts (Key Terms, Key Concepts, Exercises ) sit in the Chapter Review, because in the old pdf only Key Terms sits in the Chapter Review.

**Comment by lwtchu** [comment]
@ajluk okay i double checked in the book and double checked with anthony

It should be
- Chapter Review: Key Terms, Key Concepts
- Review Exercises

chapter review and review exercises should be the same header levels

is there something i need to change on the content side? i know they're in their own little sections so I'm not sure how it will impact the way it is handled in the recipe

**Comment by lwtchu** [comment]
Chapter Review - key terms and key concepts
Review exercises
Practice Test

Only key terms and key concepts go under chapter review. Review exercises and practice test goes in their own sections on the same level as the chapter review

**Comment by wilkus27** [comment]
@lwtchu Unfortunately, we can't obtain such structure with the current recipe. Generally, we are creating EOC sections by moving existing containers to the new ones created at the end of the chapter. This step is repeated a few times. The problem is that for regular composite pages we need less steps then for composite chapters. So the effect is that composite chapters always are after regular composite pages. In this case we get:
```
Review Exercises
Practice Test
Chapter Review
   Key Terms
   Key Concepts
```
I can try to change the recipe but it might be a little bit tricky. Also it could be hard to make changes that will not have an impact on other books, so a lot of testing will be needed.

What I can easily do is to create two composite chapters, so such structure:
```
Chapter Review
   Key Terms
   Key Concepts
Exercises
   Review Exercises
   Practice Test
```

Let me know what do you think and with which direction we want to go :slightly_smiling_face:

**Comment by lwtchu** [comment]
can we go with the second option? 
```
Chapter Review
   Key Terms
   Key Concepts
Exercises
   Review Exercises
   Practice Test
```

**Comment by ajluk** [comment]
Hi @lwtchu! I have found out that in the Key Terms in Introductory Business Statistics and in High School Statistics there is wrong link attribute in the Qualitative Data and Quantitative Data which should lead to Data term above them: 
![image](https://user-images.githubusercontent.com/55203598/90007209-9ae51480-dc9a-11ea-8407-2687ddc8a7c1.png)

as it is done in the Introductory Statistics: 
![image](https://user-images.githubusercontent.com/55203598/90007510-252d7880-dc9b-11ea-95e7-61a1b0c12972.png)

Also as you can see in the screenshots the terms in Introductory Statistics (and in Business Introductory Statistics as well) are starting with capital letters. In HS Statistics they are all lowercase. I guess it is a content issue as well.

**Comment by lwtchu** [comment]
@ajluk i'll open a card on the content side
