### ISSUE TITLE
corn theme - key concepts

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2322]
<img width="552" alt="Screen Shot 2020-05-21 at 3 44 38 PM" src="https://user-images.githubusercontent.com/11299125/82604530-16db2f00-9b7a-11ea-9271-a2c42ad26efc.png">
<img width="577" alt="Screen Shot 2020-05-21 at 3 44 42 PM" src="https://user-images.githubusercontent.com/11299125/82604533-18a4f280-9b7a-11ea-882a-a063213389a0.png">

- headers will follow sizing of whatever was set for all titles/header hierarchy #2144
- sections are broken up and labeled with the section number and title
- contains lists and stepwise lists, pictures and tables - make sure these are styled like the rest of the book

**Comment by wilkus27** [comment]
@lwtchu As we discussed here https://github.com/openstax/cnx-recipes/issues/2321#issuecomment-645585196 **Chapter Review** is now composite chapter and Key Terms and Key concepts are compound composite pages. First title is H2, titles of Key Terms etc. are H3. They are styled like other headers of that level in the book. What should I do with links to the sections?

![image](https://user-images.githubusercontent.com/40228854/85281237-ebee3e80-b489-11ea-94d4-f07976506588.png)

For now, I set such specs for them
```
font-family: Roboto Slab
  font-size: 1.2rem; (font-size(1))
  line-height: 1.5rem;
  margin-bottom: 0.7rem;
```
Color is the same as for other links. Should I change something?

**Comment by wilkus27** [comment]
Generally this is how Key Concepts looks now:

![image](https://user-images.githubusercontent.com/40228854/85281639-a8480480-b48a-11ea-8a50-e4f93132e2f1.png)

Figures will be styled in another PR. Also, I have a question about Stepwise lists here: https://github.com/openstax/cnx-recipes/issues/2186#issuecomment-646664094

**Comment by lwtchu** [comment]
i think the headers look fine as is right now - are the key terms going to be styled later with #2321?

**Comment by wilkus27** [comment]
Yes, that's right :slightly_smiling_face: It's styled in another PR.
