### ISSUE TITLE
Prealgebra - style Preface

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2327]
Style Preface with specs from https://github.com/openstax/cnx-recipes/issues/2320

**Comment by wilkus27** [comment]
:exclamation:  Blocked by https://github.com/openstax/content-managers/issues/1720

**Comment by lwtchu** [comment]
@wilkus27 just published the change on katalyst01

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-09 11-33-11](https://user-images.githubusercontent.com/47241114/84131605-0dd8d180-aa45-11ea-81fa-96ecf4326462.png)
![Screenshot from 2020-06-09 11-32-29](https://user-images.githubusercontent.com/47241114/84131608-0f09fe80-aa45-11ea-9239-19be23c05476.png)
