### ISSUE TITLE
Prealgebra 2e - style module headers

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2328]
Style headers in modules with specs from https://github.com/openstax/cnx-recipes/issues/2144

**Comment by MartaSztuka** [comment]
![Screenshot from 2020-05-28 14-08-34](https://user-images.githubusercontent.com/47241114/83139620-f6b4ee00-a0ec-11ea-8b96-802124ad0679.png)
![Screenshot from 2020-05-28 14-09-37](https://user-images.githubusercontent.com/47241114/83139626-f7e61b00-a0ec-11ea-965f-d3599bd22ab1.png)
