### ISSUE TITLE
Answer Key images.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2330]
When image is first element, exercise number drops at the bottom.
chemistry 2e
![Screenshot from 2020-05-26 13-02-17](https://user-images.githubusercontent.com/47241114/82894677-3fd13a80-9f53-11ea-90ac-80394702a4eb.png)
chemistry AF
![Screenshot from 2020-05-26 13-19-35](https://user-images.githubusercontent.com/47241114/82894861-950d4c00-9f53-11ea-8bc3-08305d2aae8a.png)

**Comment by brittweinstein** [comment]
@lwtchu is this urgent? Can we fix this in the future (backlog milestone), or does this have to be resolved ASAP?

**Comment by lwtchu** [comment]
@brittweinstein this is not urgent

**Comment by wilkus27** [comment]
#### Note for the developer who will be working on that: 
changes from https://github.com/openstax/cnx-recipes/pull/2065/files should be reworked. Better solution will be to define all existing selectors for images/figures in `common-stuff.scss` file, not in each `config.scss` file. Now, release flag created in posted PR is enabled for all books, so there is no need to define "first elements" separately.

**Comment by lwtchu** [comment]
This is still an issue - so unearthing for b.b.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Chemistry 2e
![Screenshot from 2022-01-31 13-33-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6940b3dd-b36d-493f-bf7a-f265a113aac8)
##### Chemistry AF
![Screenshot from 2022-01-31 14-01-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f057c0fb-6f28-4453-9de9-20a3f6df6c20)
