### ISSUE TITLE
Confusing recipe names

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#2332]
# Scenario
The recipe for _College Physics_ is called Physics, and the recipe for _Physics_ is called High School Physics, which has led to some confusion on the content team. Could we change the titles?

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by openstaxalina** [comment]
Good suggestion, thank you!

I updated the requirements in [this card](https://github.com/openstax/cnx-recipes/issues/1891) to change "Physics" to "College Physics".

https://github.com/openstax/cnx-recipes/issues/1891

I am closing this as the work will be done as part of 1891.
