### ISSUE TITLE
Learning Objective section numbers 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#2333]
# Scenario
The Learning Objective section number are doubling for each subsequent section. For example, what 1.2.1 is showing as 1.4.1, and 1.5.1 is showing as 1.10.1, etc. 

# Acceptance Criteria (required)
Section numbers should count up by one

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?** 
     - all chapters/sections
* **Images or Screenshots Included:** [ x ] Yes  [ ] No  (_attach below_)
In this screenshot, the Learning Objective section numbers are showing 1.8.x where they should be 1.4.x, the section is being doubled
![Screen Shot 2020-05-26 at 10 23 18 AM](https://user-images.githubusercontent.com/5865292/82920408-d8a88b80-9f3c-11ea-8b32-1abf25c626b4.png)

# Environment: (required)
* **Medium**: [ x ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ x ] staging  [ ] dev  [ ] content
* **OS**: [ x ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ x ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ x ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ x ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by openstaxalina** [comment]
This is a showstopper - we cannot release without this fix.

I confirmed that this is NOT an issue in the live content: https://openstax.org/books/calculus-volume-1/pages/1-2-basic-classes-of-functions

This does seem to be introduced by recent code -- the bake before the Test Fest (march 17) did not have the issue: https://vendor.cnx.org/contents/i4nRcikn@12.6:056cQH8B@12/1-2-Basic-Classes-of-Functions

**Comment by openstaxalina** [comment]
Here's a link to some content on a CNX instance (that does not redirect to REX) that shows the issue: https://vendor-staging.cnx.org/contents/i4nRcikn@13.2:fP4FUrwS@9/1-1-Review-of-Functions

**Comment by Stackblocks** [comment]
Doubling is happening even in locally-baked content using current books.txt and looming.liberace branch

![image](https://user-images.githubusercontent.com/12678235/83284231-1528f100-a1a2-11ea-9792-be8257e48579.png)
![image](https://user-images.githubusercontent.com/12678235/83284257-18bc7800-a1a2-11ea-8bcd-6937f034c3a8.png)

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-06-03 at 9 59 05 AM](https://user-images.githubusercontent.com/24909007/83653010-e4b9cc00-a580-11ea-9a25-20d3d120f958.png)
![Screen Shot 2020-06-03 at 9 58 45 AM](https://user-images.githubusercontent.com/24909007/83653015-e5526280-a580-11ea-8b9a-8908dcb3471e.png)
![Screen Shot 2020-06-03 at 9 58 21 AM](https://user-images.githubusercontent.com/24909007/83653018-e5eaf900-a580-11ea-9129-59949ab54754.png)

**Comment by omehes** [comment]
Verified in the latest cnx/rex versions of all 3 calculus books

cal vol 1: https://rex-web.herokuapp.com/books/calculus-volume-1@latest/pages/1-introduction/?archive=https://archive-staging.cnx.org

checked randomly 1-2 sub-chapters in each chapter of all 3 calc volumes - FIXED

![lobj1.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/2c8bf97c-59ba-4ada-878c-ad8190742af3)
