### ISSUE TITLE
Space after link

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#2335]
# Scenario
Space appears after figure link in Psych 2e Chapter 3 Critical Thinking collated questions:
https://rex-web.herokuapp.com/books/psychology-2e@5.2/pages/3-critical-thinking-questions/?archive=https%3A%2F%2Farchive-staging.cnx.org

The spare does not appear on legacy or within the content CNXML.

# Acceptance Criteria (required)
no extra space

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="204" alt="Screen Shot 2020-05-26 at 11 05 05 AM" src="https://user-images.githubusercontent.com/1895432/82929716-c1bc6600-9f49-11ea-828f-ef47914d6af3.png">

# Environment: (required)
* **Medium**: [x] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [x] staging  [ ] dev  [ ] content
* **OS**: [x] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [x] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [x] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [x] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by oscryan** [comment]
It's not in the markup.

**Comment by openstaxalina** [comment]
Good catch, thanks. This also occurs on live production content: https://openstax.org/books/psychology-2e/pages/3-critical-thinking-questions

This also occurs on CNX and has occurred in all versions of the book: https://vendor.cnx.org/contents/BqulZZQy@1.1:DbSiFBlG@1.1/Critical-Thinking-Questions.

@oscryan I noticed you added other book labels -- is there a pattern? Does the extra space occur with any element linked from an EOC section?

**Comment by openstaxalina** [comment]
(I am not prioritizing this with release flags and footnotes fixes since this was not introduced by this code.)

**Comment by oscryan** [comment]
yeah i think so

**Comment by brittweinstein** [comment]
@openstaxalina is this something we can address in the NN milestone?

**Comment by openstaxalina** [comment]
@brittweinstein it is less important than the work for _College Algebra with Corequisite_. I'd prioritize it after _College Algebra with Corequisite_ is out. Is that feasible from you perspective?

cc @lwtchu

**Comment by lwtchu** [comment]
![Screen Shot 2021-02-02 at 11 12 44 AM](https://user-images.githubusercontent.com/11299125/106636483-99105580-6547-11eb-812e-0b83c78ae37c.png)
![Screen Shot 2021-02-02 at 11 13 00 AM](https://user-images.githubusercontent.com/11299125/106636530-a299bd80-6547-11eb-97ed-af5d05c02caa.png)

it's not happening in the pdf but in webview 🤔  

To whoever is working on this - are we just removing the space in the style for the PDF?

**Comment by lwtchu** [comment]
Adding to d.d.

**Comment by wilkus27** [comment]
Yes, this problem occurs only on webview. There is set margin for links in styles for rex:

![image](https://user-images.githubusercontent.com/40228854/107952223-c4f4f780-6f99-11eb-9369-47fe32ccb134.png)

@PiotrKozlowski or @jarosik10 can you take a look on this?

**Comment by PiotrKozlowski** [comment]
It looks like something which we can fix in REX. Probably @kjdav should prioritize

**Comment by lwtchu** [comment]
Moving the card over to unified so Kim can prioritize.

**Comment by lwtchu** [comment]
Issue moved to [openstax/unified #1501](https://github.com/openstax/unified/issues/1501) via [**ZenHub**](https://www.zenhub.com/)
