### ISSUE TITLE
Microbiology: Incorrect footnote link in chapter 3.3  

### ISSUE THREAD

**Issue by omehes** [openstax/cnx-recipes#2336]
Latest version of Microbiology on vendor-staging.cnx.org

![footn_33.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/f1b82a83-b5d4-4899-aead-36099eb2c6ab)

Footnote 16 goes to incorrect url:

```https://staging.cnx.org/contents/e42bd376-624b-4c0f-972f-e0c57998e765@9.2:80f2fee2-2871-5bf0-8f57-ec66e01ed7b5@9.2#fs-id1172101891959```

**Comment by brittweinstein** [comment]
@lwtchu will implement a content fix per Phil's instructions "you could change the <footnote id="fs-id1172101891959"> to be <footnote id="larissa-rocks">  or <footnote id="fs-id1172101891959-footnote">. Just anything other that what it is now should work" 

I will move this to the CM board and close here.

**Comment by brittweinstein** [comment]
Issue moved to [openstax/content-managers #1722](https://github.com/openstax/content-managers/issues/1722) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lwtchu** [comment]
@brittweinstein i still think this is worth fixing though? since it shouldn't get confused between the same ids from different element tags

**Comment by philschatz** [comment]
This seems to be a bug in baking. If 2 pages have the same `id="..."` and there is a link to it (e.g. `<a href="#...">`) the baked document points to the later element.

When the book modules are assembled into 1 large document, every

**Comment by lwtchu** [comment]
another instance where this occurs i think: https://app.zenhub.com/workspaces/content-engineering-tech-team-5af1f4cc12da5e6d74331b60/issues/openstax/cnx-recipes/2353

**Comment by omehes** [comment]
fixed

**Comment by lwtchu** [comment]
@philschatz should we repurpose this card or open a new one for the ID bug since this one is specific to microbio :joy:

**Comment by openstaxalina** [comment]
Here's the PR for the ID bug: https://github.com/openstax/cnx-epub/pull/163

I've requested that the following issues be re-tested with that PR ^
https://github.com/openstax/cnx-recipes/issues/2378
https://github.com/openstax/cnx-recipes/issues/2362
https://github.com/openstax/cnx-recipes/issues/2341

Since y'all already fixed this in content I am okay keeping it closed. We will not lose track of the epub fix and have other issues to test it against.
