### ISSUE TITLE
FIX IN REX? An additional line added before footnote

### ISSUE THREAD

**Issue by kjdav** [openstax/cnx-recipes#2337]
# What happened?

Note there is an additional line under the table, above the caption with a footnote

![image.png](https://images.zenhubusercontent.com/5b80161bfa2a9b7bdf9073e4/83530dad-02d0-4507-9a5d-d3d9dcf20113)
Prod REX on left, REX footnote PR on right

QA url: https://rex-web-issue-947-np39vpknfjij.herokuapp.com/books/us-history@latest/pages/f-united-states-population-chart/?archive=https://archive-qa.cnx.org 

# Reproducibility Details

- **Does it also happen in an incognito window?**: 
- **Does this happen in one place, a few places, or everywhere?**:

# Environment:

- **Book(s)**:
- **URL/Server**: 
- **Location (page number, chapter/section)**:
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots

(_attach here (please clearly label what environment each screenshot came from)_)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by lwtchu** [comment]
<img width="922" alt="Screen Shot 2020-05-26 at 2 55 40 PM" src="https://user-images.githubusercontent.com/11299125/82944538-056e9a00-9f61-11ea-8cc9-8a814e7e51d6.png">

Transforms adds another table line since the footnote is a part of the table now. We should probably either make it not filled or remove the border if a footnote is added to the footer of the table.

**Comment by omehes** [comment]
Another type of issue: font difference in webview of US History (in rex and previous book versionit looks good):

![usah_f](https://user-images.githubusercontent.com/44207656/82951828-86339300-9f6d-11ea-8cac-083d099caf7d.png)

**Comment by openstaxalina** [comment]
@omehes to simplify this issue, I removed the comment about the font difference. We do not need to address that since it looks fine in REX.

**Comment by openstaxalina** [comment]
@brittany-johnson when tables have a footnote, we are seeing an extra line added at the end of the table.

To remove this line, where would the change be? (cnx-recipes, REX, other?) (Note that we are **not** updating the webview repo since REX controls our webview display now.)

**Comment by brittany-johnson** [comment]
@openstaxalina It looks like a `border-top` is being added in the Rex styles. In the screenshot below, deselecting it removes it. This change will be on the unified side
![Screen Shot 2020-05-28 at 3 14 37 PM](https://user-images.githubusercontent.com/24909007/83189046-39c78f00-a0f6-11ea-91a0-698de60d95b1.png)

**Comment by openstaxalina** [comment]
Thanks to much @brittany-johnson. Moving to unified.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/unified #1111](https://github.com/openstax/unified/issues/1111) via [**ZenHub**](https://www.zenhub.com/)
