### ISSUE TITLE
Accounting recipe renders Figure links as "Exercise" anchor text in Appendices

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#2342]
# Scenario
Figure links in the Appendices for Financial Accounting say "Exercise #.#" instead of generating Figure anchor text, the way they do in the rest of the book. The markup is correct, but the recipe-generated anchor text says Exercise.
https://rex-web.herokuapp.com/books/principles-financial-accounting@6.2/pages/financial-statement-analysis?archive=https%3A%2F%2Farchive-staging.cnx.org
# Acceptance Criteria (required)
Anchor text for figure links in appendices should be Figure.

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="875" alt="Screen Shot 2020-05-27 at 11 06 19 AM" src="https://user-images.githubusercontent.com/1895432/83044916-761dc100-a00a-11ea-9845-bc563ef7e6ee.png">

# Environment: (required)
* **Medium**: [x] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [x] staging  [ ] dev  [ ] content
* **OS**: [x] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [x] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [x] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [x] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by openstaxalina** [comment]
Thanks for the catch. This is also an issue in the live book: https://openstax.org/books/principles-financial-accounting/pages/financial-statement-analysis

I am not prioritizing with release flags/footnotes fixes since this does not seem related. I am including this with a future milestone.

**Comment by openstaxalina** [comment]
Looking at this further - these figures are not numbered so there is no way for anchor text to be generated. 

This will be a **content** change to remove all three links in Appendix A of Accounting Volume 1. Change the text to "The image below".

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #1725](https://github.com/openstax/content-managers/issues/1725) via [**ZenHub**](https://www.zenhub.com/)
