### ISSUE TITLE
Entrepreneurship - footnote jumps to incorrect chapter 

### ISSUE THREAD

**Issue by omehes** [openstax/cnx-recipes#2353]
Entrepreneurship (non-rex): https://vendor-staging.cnx.org/contents/04BRDmFF@10.7:1R5dvf9p@3/1-1-Entrepreneurship-Today#fs-idm344590352

Footnote 20 in chapter 1.1 jumps to chapter 14.1

Works correctly in previous book version in webview and also correct on rex 

![chapt1.1141.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/fbea2fbd-1b6d-469d-8ba4-da5405ec9a2e)

**Comment by lwtchu** [comment]
I was able to fix this by changing the id to something else. This is due to this bug? #2336
