### ISSUE TITLE
Review exercises structure (eoc section)

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2354]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2189 

Books that this needs to be implemented for: 
- [ ] Prealgebra 2e
- [ ] Intermediate Algebra 2e
- [ ] Elementary Algebra 2e
- [ ] College Algebra CoReq
- [ ] Precalculus
- [ ] Alg & Trig

**Comment by openstaxalina** [comment]
@brittweinstein could you explain more about this issue? The link is to the chapter outline & introduction card. It's possible this card is not needed.

**Comment by brittweinstein** [comment]
Yes, I don't think this is needed. This likely was created when I was doing a card by card breakout--I will close.
