### ISSUE TITLE
Implement  Learning objectives

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2355]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2190 

Books that need this: 
- [x] Prealgebra 2e 
- [x] Intermediate Algebra 2e 
- [x] Elementary Algebra 2e 
- [x] College Algebra CoReq
- [x] Precalculus
- [x] Algebra and Trigonometry

**Comment by wilkus27** [comment]
Tested in Prealgebra, College Algebra and College Algebra Coreq. Needs tests in other books.

**Comment by MartaSztuka** [comment]
@wilkus27 `By the end...` and '`In this section...`  is not styled, should be bold.
Intermediate Algebra 2e![Screenshot from 2020-07-09 12-03-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/72658993-ee2e-4907-a654-b9cf0e0819da)
Elementary Algebra 2e![Screenshot from 2020-07-09 12-02-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/84f99b40-e09f-4d2f-8c41-5884918c0f6f)
Precalculus![Screenshot from 2020-07-09 12-04-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c8630f8a-e87a-4c6f-bfb4-5ae871aeb2c9)
Algebra and Trigonometry![Screenshot from 2020-07-09 12-05-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1d90a294-ec6e-4a54-af39-e8375ae0e17a)

**Comment by wilkus27** [comment]
@MartaSztuka This is a content issue. It will be fixed on production. More information here: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2444
