### ISSUE TITLE
Implement Chapter Outline & Introduction

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2356]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2189 

- [ ] When testing this issue, please also ensure that **figure numbering resets each section** and is numbered continuously throughout the section in **Precalculus and College Algebra with CoReq**. 

The reason why this needs to be tested in this issue is that as part of the PR for this issue, I removed the .unnumered class that was previously removing numbering from splash figures. 

Books that Need This: 
- [x] Prealgebra 2e
- [x] Intermediate Algebra 2e
- [x] Elementary Algebra 2e
- [x] College Algebra with CoReq
- [x] Precalculus
- [x] Algebra & Trigonometry

**Comment by brittany-johnson** [comment]
Coding was done in another issue: 
![Screen Shot 2020-07-01 at 10 14 49 AM](https://user-images.githubusercontent.com/24909007/86261164-d2cd4800-bb83-11ea-9be6-9dc61c0a1f38.png)

**Comment by brittany-johnson** [comment]
I removed the `.unnumbered` classes from chapter splash images in `precalculus-coreq` recipe. Splash images in this recipe should be numbered

**Comment by MartaSztuka** [comment]
Prealgebra 2e
![Screenshot from 2020-07-06 14-42-57](https://user-images.githubusercontent.com/47241114/86594269-0569ad00-bf97-11ea-8217-2eea83201681.png)

Algebra and Trigonometry
![Screenshot from 2020-07-06 14-46-05](https://user-images.githubusercontent.com/47241114/86594516-71e4ac00-bf97-11ea-8225-9f448b8a301d.png)

College Algebra
![Screenshot from 2020-07-06 15-45-17](https://user-images.githubusercontent.com/47241114/86600002-b70cdc00-bf9f-11ea-8d2e-64f2df17386e.png)

College Algebra coreq
![Screenshot from 2020-07-06 15-47-38](https://user-images.githubusercontent.com/47241114/86600229-0f43de00-bfa0-11ea-82c1-ad2fff3ecbeb.png)

Elementary Algebra
![Screenshot from 2020-07-06 14-41-46](https://user-images.githubusercontent.com/47241114/86594207-e5d28480-bf96-11ea-9791-ad34779e3cfc.png)

Intermediate Algebra![Screenshot from 2020-07-06 14-43-40](https://user-images.githubusercontent.com/47241114/86594327-1c100400-bf97-11ea-881f-3c2ea228df98.png)

Precalculus
![Screenshot from 2020-07-06 14-44-32](https://user-images.githubusercontent.com/47241114/86594405-3e098680-bf97-11ea-9961-3ac60ea8b5d1.png)
