### ISSUE TITLE
Implement Key Concepts

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2357]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2322 

Books: 
- [x] Elem Alg 2e 
- [x] Int Alg 2e 
- [x] Prealg 2e

**Comment by wilkus27** [comment]
In Prealgebra it's already tested. Only Elem and Int Alg need tests.

**Comment by MartaSztuka** [comment]
Elementary Algebra![Screenshot from 2020-07-09 11-22-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6a578f98-e714-43ab-980b-5b9a0ceca12b)
Intermediate Algebra![Screenshot from 2020-07-09 11-23-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e419e32a-0ac4-448e-916d-324afc3bc37e)
