### ISSUE TITLE
Implement Introduction Page

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2358]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2314 

Books: 
- [x] Elem Alg 2e 
- [x] Int Alg 2e 

Prealg 2e has already been done.

**Comment by wilkus27** [comment]
Done within https://github.com/openstax/cnx-recipes/pull/2471

**Comment by MartaSztuka** [comment]
Intermediate Algebra![Screenshot from 2020-07-09 11-25-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/28b0ed34-2e95-4da9-8a57-3af6898cef41)
Elementary Algebra![Screenshot from 2020-07-09 11-26-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ffed6134-18b2-4dda-86de-2b34022efd15)
