### ISSUE TITLE
Entrepreneurship: Footnotes get the wrong numbers

### ISSUE THREAD

**Issue by omehes** [openstax/cnx-recipes#2359]
~In rex: chapter 2.4, footnote 49 is unclickable.~ **See new comments below**

https://openstax.org/books/entrepreneurship/pages/2-4-frameworks-to-inform-your-entrepreneurial-path#auto_ec72e47b-f3dc-4491-bc87-4efe5cc92ed0_footnote-ref4

![footn-uncl.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/165989cb-9451-4e55-8a5f-194a1bc372e3)

**Comment by openstaxalina** [comment]
Looking at this with latest REX and content: https://rex-web.herokuapp.com/books/entrepreneurship@10.8/pages/2-4-frameworks-to-inform-your-entrepreneurial-path?archive=https%3A%2F%2Farchive-staging.cnx.org#fs-idm329206752

The footnotes have the wrong numbers in REX. For example, the footnote in the screenshot should be number 49 (see PDF screenshot), but instead it's number 4. The footnote numbers in this book restart with each chapter, not each page.

To resolve this, can REX use the footnote numbers from the recipe?

Add'l conversation here: https://openstax.slack.com/archives/CH5514N57/p1590678246237800

PDF screenshot showing correct numbering:
![FootnotesEshipPDF](https://user-images.githubusercontent.com/7863733/83188946-1270c200-a0f6-11ea-9e9d-8371bcf11400.png)

**Comment by openstaxalina** [comment]
We are changing the footnotes format and REX will make an accompanying change. @brittany-johnson providing more info.

**Comment by brittany-johnson** [comment]
More details listed in this closed issue: 
https://github.com/openstax/cnx-recipes/issues/2379

**Comment by brittany-johnson** [comment]
class `footnote-number` has been changed to data-type
![Screen Shot 2020-06-03 at 1 48 59 PM](https://user-images.githubusercontent.com/24909007/83677129-543fb380-a5a1-11ea-80ca-9e755e561742.png)

**Comment by brittany-johnson** [comment]
https://github.com/openstax/cnx-recipes/issues/2380#issuecomment-638919585
