### ISSUE TITLE
Implement Key Terms

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2360]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2321

Books: 
- [x] Prealgebra 2e
- [x] Elem Alg 2e 
- [x] Int Alg 2e

**Comment by wilkus27** [comment]
In Prealgebra is tested.
Needs tests in two other books.

**Comment by MartaSztuka** [comment]
Elem Alg 2e ![Screenshot from 2020-07-09 11-44-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/08bce73e-bb8a-4d88-99f5-96ab4c57d40f)
Int Alg 2e![Screenshot from 2020-07-09 11-45-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/03d221e9-b3c0-41a0-ad89-81a3992493f3)
