### ISSUE TITLE
Implement Key Concepts

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2361]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2322 

Books: 
- [ ] Prealgebra 2e 
- [ ] Elem Alg 2e 
- [ ] Int Alg 2e

**Comment by wilkus27** [comment]
Duplicate of https://github.com/openstax/cnx-recipes/issues/2357
