### ISSUE TITLE
RETEST WITH EPUB FIX: Entrepreneurship: footnote in incorrect chapter

### ISSUE THREAD

**Issue by omehes** [openstax/cnx-recipes#2362]
entreprship book in rex. 
chapter 3.2, footnote 30 jumps to chapter Case Questions, where the actual footnote mark is.

![footn_inc.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/eb1cb17d-f0e4-47bf-bb99-df827570b256)

This looks good in webview!

**Comment by openstaxalina** [comment]
I cannot find this content on our instance for Test Fest: https://rex-web.herokuapp.com/books/entrepreneurship@10.8/pages/3-2-corporate-social-responsibility-and-social-entrepreneurship?archive=https%3A%2F%2Farchive-staging.cnx.org

![Screen Shot 2020-05-28 at 3.44.16 PM.png](https://images.zenhubusercontent.com/5b57372fb01a900cfd923015/b4e0c554-c544-4b3e-b12e-8574af3c9a11)

**Comment by openstaxalina** [comment]
@omehes could you see if this is resolved when you test openstax/cnx-epub#163?

If this issue persists, please provide the URL where you are seeing it.

**Comment by omehes** [comment]
Verified these issues on the latest build 
https://rex-web.herokuapp.com/books/entrepreneurship@latest/pages/1-introduction/?archive=https://archive-staging.cnx.org

Looks good.
