### ISSUE TITLE
Implement main content titles and headers

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2363]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2144

Books: 
- [x] Prealgebra 2e 
- [x] Int Alg 2e 
- [x] Elem Alg 2e 
- [x] College Alg w/ CoReq
- [x] Precalculus 
- [x] Alg and Trig

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-07-08 at 3 40 29 PM](https://user-images.githubusercontent.com/24909007/86969455-71811800-c133-11ea-9cf5-329bff18fc78.png)
![Screen Shot 2020-07-08 at 3 49 59 PM](https://user-images.githubusercontent.com/24909007/86969466-7776f900-c133-11ea-9851-7ce3f4bd48e0.png)
![Screen Shot 2020-07-08 at 3 53 37 PM](https://user-images.githubusercontent.com/24909007/86969478-7f369d80-c133-11ea-8c0d-bb2869e7f970.png)

**Comment by brittweinstein** [comment]
@MartaSztuka when this passes testing and you close this, please close https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2475 as well.

**Comment by MartaSztuka** [comment]
@wilkus27 Header h4 in Example is unstyled in Elem Alg, Int Alg.
Notes has lot style in Precal and Alg&Trig.
Elem Alg ![Screenshot from 2020-07-10 13-43-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/95f79a00-650b-497c-8774-122705e2d1be)![Screenshot from 2020-07-10 13-46-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4da2b42f-a1cc-4f9f-ac90-5cb842f78517)
Prealgebra 2e![Screenshot from 2020-07-10 13-32-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e3d7d727-557d-4f5e-82a2-5ed386609463)
 Int Alg 2e![Screenshot from 2020-07-10 13-47-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/56e6dc77-69b9-43dc-a436-0932d49d4bb8) ![Screenshot from 2020-07-10 13-47-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c9e0add3-6d57-47f6-a1dc-f32284553ba4)
 College Alg w/ CoReq![Screenshot from 2020-07-10 13-50-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3f04d5c5-7257-4fe9-876f-c28a4fe959a8)![Screenshot from 2020-07-10 13-50-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/72178df7-bb66-490e-959b-1fe1b0753532)
 Precalculus![Screenshot from 2020-07-10 13-52-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5cb21726-9112-4d42-a992-7080d4a12e7a)![Screenshot from 2020-07-10 13-56-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ebea9279-2964-4941-8cc0-334e533e2ff9)
 Alg and Trig![Screenshot from 2020-07-10 14-12-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/68855cc7-bfd6-4597-8c89-6e8ae1c474fc)

**Comment by brittany-johnson** [comment]
Because College Alg w/ CoReq passed, I'm moving this to the icebox. The other books can be adjusted once coreq is out.

**Comment by wilkus27** [comment]
I think we can close this issue. All headers from screenshots are notes titles. They will be styled within work on another issues. For title in Example I created separate card: https://github.com/openstax/cnx-recipes/issues/2209
