### ISSUE TITLE
Implement Folio

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2364]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2143
Books: 
- [x] Prealgebra 2e 
- [x] Int Alg 2e 
- [x] Elem Alg 2e 
- [x] College Alg w/ CoReq
- [x] Precalculus 
- [x] Alg and Trig

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/86296284-0fb63080-bbbe-11ea-9cdc-9c33c86b2e2e.png)

![image](https://user-images.githubusercontent.com/12678235/86296260-0200ab00-bbbe-11ea-9c2a-be0bcc8b8cf0.png)

**Comment by MartaSztuka** [comment]
Prealgebra 2e![Screenshot from 2020-07-06 14-24-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f843aad8-251f-4b67-acea-f4bc9d2d7081)

Algebra and Trigonometry![Screenshot from 2020-07-06 14-26-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/671a9b6b-e6ed-4c13-ac47-7ac13f5566e2)

College Algebra![Screenshot from 2020-07-06 14-28-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d323e91d-7d42-41a1-aa9d-cb6e6afdae24)

College Algebra coreq![Screenshot from 2020-07-06 14-37-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7d5f998a-1bbf-4953-a238-475dedc66b12)

Elementary Algebra ![Screenshot from 2020-07-06 14-36-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/11ebddb1-1a18-49ab-bf1d-c634995db960)

Intermediate Algebra![Screenshot from 2020-07-06 14-32-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/25c27347-4ade-4dab-9b85-0247b245aef1)

Precalculus![Screenshot from 2020-07-06 14-34-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/665f6221-0feb-478c-b82b-d5eef0fe7882)
