### ISSUE TITLE
Implement condensed icon with no title note

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2365]
Documentation: https://github.com/openstax/cnx-recipes/issues/2179
Books: 
- [x] Prealgebra 2e 
- [x] Int Alg 2e 
- [x] Elem Alg 2e 
- [x] College Alg w/ CoReq
- [x] Precalculus 
- [x] Alg and Trig
- [x] Calculus 
- [ ] Statistics

Answer collation styling: 
- [ ] Prealgebra 2e

**Comment by brittweinstein** [comment]
We still need a PR for the Precalc, A&T, CA titles.

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-07-02 at 11 49 34 AM](https://user-images.githubusercontent.com/24909007/86388383-55c0d200-bc5a-11ea-82f7-b46e799aeed7.png)
![Screen Shot 2020-07-02 at 11 49 24 AM](https://user-images.githubusercontent.com/24909007/86388427-67a27500-bc5a-11ea-9133-97de7ed61647.png)

**Comment by wilkus27** [comment]
@MartaSztuka It can be tested now in **Precalculus**, **College Algebra** and **Algebra & Trigonometry**

**Comment by MartaSztuka** [comment]
Algebra & Trigonometry![Screenshot from 2020-07-28 12-53-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4eddda00-830a-4af9-9174-78cebc740a8b)
College Algebra![Screenshot from 2020-07-28 12-55-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c2840073-b3b0-4a4d-a492-b10cb935ed8c)
Precalculus![Screenshot from 2020-07-28 12-59-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c447c48a-1f35-4b92-9e5b-e8ede9b5f60e)

**Comment by MartaSztuka** [comment]
Not tested on Calculus and Statistics yet.

**Comment by wilkus27** [comment]
Can be tested in Calculus books. For Statistic will be created separate PR.

**Comment by MartaSztuka** [comment]
# FAILED
## Condensed icon
@wilkus27 Media note is not styled
### Calculus 1![Screenshot from 2020-08-05 09-37-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d6778c07-6462-4220-bbec-8022104dca0b)
### Calculus 2![Screenshot from 2020-08-05 09-36-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d44c81e8-fb3f-41bd-a94a-df68b11477be)
### Calculus 3![Screenshot from 2020-08-05 09-33-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a7c2efe7-c824-40f4-9950-fdc2fd7bbab8)

**Comment by wilkus27** [comment]
There is no icon condensed notes in Statistics. Issue can be closed.
