### ISSUE TITLE
Implement tokens and token lists

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2366]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2186

Books: 
- [ ] Prealgebra 2e 
- [ ] Int Alg 2e 
- [ ] Elem Alg 2e 
- [x] College Alg w CoReq
- [ ] Precalculus 
- [ ] Alg and Trig

**Comment by openstaxalina** [comment]
This was holding for the STIX font. I think this card is ready for work now.

**Comment by brittweinstein** [comment]
We can merge the PR associated with https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2455 and then start on this for the COREQ.

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-07-10 at 12 23 46 AM](https://user-images.githubusercontent.com/24909007/87119541-f9564780-c243-11ea-84be-4746c2f18ab4.png)
![Screen Shot 2020-07-10 at 12 23 40 AM](https://user-images.githubusercontent.com/24909007/87119544-fa877480-c243-11ea-8032-2eafa5c3995a.png)

**Comment by MartaSztuka** [comment]
@brittany-johnson Tested in College Algebra Coreq, in .xhtml token list looks ok, however in PDF there are question marks with style.
![Screenshot from 2020-07-15 08-55-33](https://user-images.githubusercontent.com/47241114/87513594-3faf0a80-c679-11ea-89a8-2e581971bcb3.png)
![Screenshot from 2020-07-15 08-53-14](https://user-images.githubusercontent.com/47241114/87513607-450c5500-c679-11ea-8fce-286b198bc88c.png)
