### ISSUE TITLE
Implement no class boxed note

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2367]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2191 

Books: 
- [x] Prealgebra 2e 
- [x] Int Alg 2e 
- [x] Elem Alg 2e 
- [x] College Algebra w CoReq 
- [x] Precalculus 
- [x] Alg and Int

**Comment by brittweinstein** [comment]
We need a PR for the CA, Precal, and A&T series.

**Comment by wilkus27** [comment]
@MartaSztuka It can be tested now in Precalculus, College Algebra and Algebra & Trigonometry

**Comment by MartaSztuka** [comment]
College Algebra![Screenshot from 2020-07-28 12-49-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/199364f3-1821-4853-88fe-c6058ecfaddf)
Precalculus![Screenshot from 2020-07-28 12-50-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0703e591-97a1-46d8-8224-eea6eebf04c7)
Algebra & Trigonometry![Screenshot from 2020-07-28 12-51-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c096cd52-e2c8-462a-972b-7ec0303031f2)
