### ISSUE TITLE
Implement Icon Boxed Note

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2368]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2200

Books: 
- [x] Prealg 2e 
- [x] Elem Alg 2e 
- [x] Int Alg 2e 
- [x] College Alg w CoReq 
- [x] Precalculus 
- [x] Alg and Trig 
- [x] Statistics

**Comment by brittany-johnson** [comment]
According to the documentation linked above and the [epic](https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2207), I don't believe this note is for College Alg w CoReq, Precalculus, Alg and Trig, and Statistics.

Before I remove these books from the checklist above and submit this issue for testing I want to make sure I'm correct @lwtchu cc: @brittweinstein

**Comment by lwtchu** [comment]
@brittany-johnson the `class="qa"` feature does https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2207 and it uses this icon https://drive.google.com/file/d/1siu8lGy50uNOsog48D95U9RFCH2n2U_G/view

**Comment by wilkus27** [comment]
`QA` note is styled within https://github.com/openstax/cnx-recipes/pull/2472. PR is in code review now.

**Comment by brittweinstein** [comment]
@wilkus27 does this mean we can check off the coreq book above?

**Comment by brittany-johnson** [comment]
No, not yet. Just checked and the Q&A note in coreq is currently styled like an icon condensed note. I'll update it 
![Screen Shot 2020-07-08 at 6 39 12 PM](https://user-images.githubusercontent.com/24909007/86980809-769d9180-c14a-11ea-8de3-90b4e2366fcb.png)

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-07-08 at 7 31 47 PM](https://user-images.githubusercontent.com/24909007/86983555-c7fd4f00-c151-11ea-8254-756b163e62ee.png)

**Comment by wilkus27** [comment]
@MartaSztuka It can be tested now in Precalculus, College Algebra and Algebra & Trigonometry

**Comment by MartaSztuka** [comment]
@lwtchu In Precalculus and Algebra and Algebra & Trigonometry notes should have class `how-to-notitle` and  `media-notitle` now they have `howto` and `media`. Will the class be changed in those two books?
In College Algebra both notes are styled ![Screenshot from 2020-07-28 11-36-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cb78e27e-ebf6-4ce4-8650-704435ef5607)

**Comment by lwtchu** [comment]
@MartaSztuka we will change them to be `how-to-notitle` and `media-notitle` to keep it consistent

**Comment by wilkus27** [comment]
@MartaSztuka icon boxed notes from Statistics are ready for testing:
- Calculator
- Collaborative Exercises
- Try It

**Comment by MartaSztuka** [comment]
# PASSED
## Calculator Note
### HS Statistics
![Screenshot from 2020-08-11 17-28-24](https://user-images.githubusercontent.com/47241114/89916639-26599980-dbf8-11ea-938b-8f4ae88fe305.png)
### Business Statistics
No Calculator note
### Introductory Statistics![Screenshot from 2020-08-11 17-31-06](https://user-images.githubusercontent.com/47241114/89916920-76386080-dbf8-11ea-9a43-2abe208aaea4.png)

## Collaborative Exercises
### HS Statistics
![Screenshot from 2020-08-11 17-29-11](https://user-images.githubusercontent.com/47241114/89916683-32ddf200-dbf8-11ea-8335-1efec3e678cf.png)
### Business Statistics
No Collaborative Exercises note
### Introductory Statistics
![Screenshot from 2020-08-11 17-32-01](https://user-images.githubusercontent.com/47241114/89917025-99631000-dbf8-11ea-89b7-7cbb94225c44.png)



## Try It
### HS Statistics
![Screenshot from 2020-08-11 17-29-32](https://user-images.githubusercontent.com/47241114/89916716-3ffae100-dbf8-11ea-96cd-eaf64428a2dc.png)
### Business Statistics
![Screenshot from 2020-08-11 17-33-07](https://user-images.githubusercontent.com/47241114/89917136-bdbeec80-dbf8-11ea-937d-fe85b18ff62f.png)
### Introductory Statistics
![Screenshot from 2020-08-11 17-30-33](https://user-images.githubusercontent.com/47241114/89916852-63be2700-dbf8-11ea-9d89-79febca7a499.png)
