### ISSUE TITLE
Implement example without title

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2369]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2203

Books: 
- [x] Prealg 2e 
- [x] Elem Alg 2e 
- [x] Int Alg 2e

**Comment by wilkus27** [comment]
Precalc Trio and Coreq have examples **with title**. I think we can remove those books from the list above.
Examples in prealgebra are already tested. They should be tested in Elem Alg and Int Alg.

**Comment by MartaSztuka** [comment]
@wilkus27  In Elem Alg 2e Examples has equations as figures, some of them are not styled, happens quite often in random locations ![Screenshot from 2020-07-09 11-53-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f550c6e4-33d9-4584-a0cf-86d0085758ff)
 Int Alg 2e![Screenshot from 2020-07-09 11-56-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/37634e80-803e-414a-a16e-4054c7f62d06)

**Comment by lwtchu** [comment]
The equations are in photos cause we cannot achieve the red lines or blue lines in math. I'm mostly concerned about the large image - should we open a separate issue for making sure images are the size that they are and displayed with their assigned resolution? I'm not sure if there's an issue for that yet.

**Comment by wilkus27** [comment]
@lwtchu Yes, I think we should open separate issue for images.

Also, Marta noticed here https://github.com/openstax/cnx-recipes/issues/2363#issuecomment-656644083 that in Elem Alg and Int Alg (which are using the same recipe as prealgebra) examples have titles:

![image](https://user-images.githubusercontent.com/40228854/88394741-3a139c00-cdc0-11ea-9d15-ba06bfd2f33d.png)

So I think this issue can be closed. I will create separate one for implementing examples with titles.

**Comment by lwtchu** [comment]
Sounds good thank you! We solved the image issue i think sometime..this week. I cannot recall :joy: But thank you for working on the separate issue!
