### ISSUE TITLE
Implement unnumbered unstyled table

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2370]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2205

Books: 
- [x] Prealg 2e 
- [x] Elem Alg 2e 
- [x] Int Alg 2e 
- [x] College Alg w CoReq 
- [x] Precalculus 
- [x] Alg and Trig

**Comment by wilkus27** [comment]
Related PRs:
- https://github.com/openstax/cnx-recipes/pull/2403 (Prealgebra)
- https://github.com/openstax/cnx-recipes/pull/2471 (Elem Alg, Int Alg, Precalc, Alg & Trig)
- https://github.com/openstax/cnx-recipes/pull/2443 (College Alg)
- https://github.com/openstax/cnx-recipes/pull/2454 (College Alg Coreq)

**Comment by wilkus27** [comment]
**Information:** it's not tested in Elem Alg, Int Alg, Precalc, Alg & Trig

**Comment by MartaSztuka** [comment]
Elementary Algebra![Screenshot from 2020-07-09 10-46-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/308adc2f-706c-42bd-a24d-b7fbe544ccf1)

Intermediate Algebra![Screenshot from 2020-07-09 10-49-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/263ea50e-76c4-4603-a1fc-fe0f9fd383dd)

Precalculus![Screenshot from 2020-07-09 11-12-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c4ceca94-d4dc-4f00-b8f5-109bed45af5d)

Algebra and Trigonometry![Screenshot from 2020-07-09 11-14-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5ad66d6d-5b4f-407b-b8a2-5ecfa499ccd8)
