### ISSUE TITLE
Implement condensed icon note with title

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2371]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2206

Books: 
- [x] Prealg 2e 
- [x] Elem Alg 2e 
- [x] Int Alg 2e 
- [x] College Alg w CoReq 
- [x] Precalculus 
- [x] Alg and Trig

**Comment by wilkus27** [comment]
@MartaSztuka It can be tested now in Precalculus, College Algebra and Algebra & Trigonometry

**Comment by MartaSztuka** [comment]
Precalculus![Screenshot from 2020-07-28 11-28-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9bd8fe33-0f3e-4052-bb22-2f7ca883ac03)
College Algebra![Screenshot from 2020-07-28 11-35-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/690e3f61-f6ec-421f-82a7-9f0e48e2fabe)
![Screenshot from 2020-07-28 11-30-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f5292fa5-44e6-4afd-9b0c-65789a66336a)
Algebra & Trigonometry![Screenshot from 2020-07-28 11-32-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e5beac8a-5387-46e9-b0df-a6f67a1f1cc3)
