### ISSUE TITLE
Implement icon boxed note with title 

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2372]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2208

Books: 
- [x] Prealg 2e 
- [x] Elem Alg 2e 
- [x] Int Alg 2e

**Comment by wilkus27** [comment]
Tested in Prealgebra. Needs tests in Elem and Int Alg.

**Comment by MartaSztuka** [comment]
Elem Alg 2e![Screenshot from 2020-07-09 11-49-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1ddc4f22-5076-4379-bf3c-bdc4db68d68b)
Int Alg 2e![Screenshot from 2020-07-09 11-47-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9294baa2-2841-47e4-b984-c330a75ddb75)
