### ISSUE TITLE
Implement example with title

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2373]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2209

Books: 
- [x] College Algebra w CoReq
- [x] Precalculus
- [x] Algebra and Trig

**Comment by wilkus27** [comment]
Tested in College Algebra. Needs tests in Precalc and Alg & Trig.
In College Algebra Coreq it will be testing within https://github.com/openstax/cnx-recipes/issues/2479

**Comment by MartaSztuka** [comment]
Precalc![Screenshot from 2020-07-09 12-14-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a1f607d9-41b6-4d8d-a58e-ebe030ffef86)
Alg & Trig![Screenshot from 2020-07-09 12-14-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4fd7d882-1ae6-49d3-8140-ccb2f7f48214)
