### ISSUE TITLE
Implement equation number

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2374]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2210

Books: 
- [ ] College Algebra w CoReq
- [ ] Precalculus
- [ ] Algebra and Trig

**Comment by openstaxalina** [comment]
There are no numbered equations in the Precalculus trio or the Corequisite books. We understand that the _recipe_ is suppressing all equation numbers. Therefore, we think that we can close this issue. @wilkus27 @ajluk do you have any concerns with closing this issue?

cc @brittany-johnson @brittweinstein @Stackblocks

**Comment by wilkus27** [comment]
@openstaxalina No, we don't have any concerns. We are ok with closing this :slightly_smiling_face:
