### ISSUE TITLE
Implement boxed note with class and title

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2375]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2256

Books: 
- [x] Calculus

**Comment by ajluk** [comment]
Hi @lwtchu could you confirm if the `no class` notes are the only boxed notes that are present in the Statistics books? I have checked all three of the statistics books looking for `theorem` and `problem-solving` notes, but I couldn't find them. Are there some other that should be styled within this shapes?

**Comment by lwtchu** [comment]
@ajluk i don't think there's any i'll remove it from the checklist

**Comment by ajluk** [comment]
Hi @brittweinstein! I'm closing this issue, because these notes in Calculus has been implemented and tested within these atom issues: #2561, #2559. And as @lwtchu commented above there aren't any of these types in Statistics books.
