### ISSUE TITLE
Implement outlined box note

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2376]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2266

Books: 
- [x] Calculus

**Comment by Stackblocks** [comment]
Removed stats per Larissa, this is just in Calc for now.

**Comment by Stackblocks** [comment]
Looks like this was done with https://github.com/openstax/cnx-recipes/issues/2563, marking it as complete.
