### ISSUE TITLE
Implement stats lab feature (full page section note feature

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2377]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2273

Books: 

- [x] Statistics

**Comment by ajluk** [comment]
The bleeds in the top bar and bottom line has been checked by Larissa:
![image](https://user-images.githubusercontent.com/55203598/89825696-47b57980-db55-11ea-9928-81176f364a30.png)
![image](https://user-images.githubusercontent.com/55203598/89825730-5439d200-db55-11ea-8d4d-e3da7a1f7848.png)

**Comment by MartaSztuka** [comment]
# PASSED
## Stats lab
### Intro Statistics![Screenshot from 2020-08-12 16-26-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/16f5cc7a-ba9b-4996-a3e1-932c664c0edc)

**Comment by ajluk** [comment]
I have reopened this issue, because this note is also present in HS Statistics and needs to be tested there as well.

**Comment by MartaSztuka** [comment]
# PASSED
## Stats Lab
### HS Statistics
![Screenshot from 2020-08-12 16-48-12](https://user-images.githubusercontent.com/47241114/90029864-a432a900-dcbb-11ea-9495-7873e9f00efe.png)
