### ISSUE TITLE
WAITING: RETEST WITH EPUB FIX: Cumulative issue for entrepr.ship collection - all issues here

### ISSUE THREAD

**Issue by omehes** [openstax/cnx-recipes#2378]
chapter 3 - Case Questions: footnote 30 and then 61 in the same chapter on webview:

![fitn-mism.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/653e8196-fb84-4121-b1dd-58b2888b1787)

in rex it looks like this (no footnotes at the end of the page):

![footn-rex.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/9f4e2941-8eb8-4296-b26a-a9323b00634c)

**Comment by oscryan** [comment]
Ref links in the body text of module number consecutively through chapter, but the actual footnote content at the bottom of each page restarts at 1 in each module:
For example in 15.2 the body links are numbered 4-9, but the content at the bottom it links to, on the same page,  is 1-6.
![Screen Shot 2020-05-27 at 1.41.18 PM.png](https://images.zenhubusercontent.com/5b572ec492e09f0d21193829/554de5e0-c1b9-4d8a-af41-575546f2ac6f)![Screen Shot 2020-05-27 at 1.42.06 PM.png](https://images.zenhubusercontent.com/5b572ec492e09f0d21193829/8207493d-71c9-4cd1-9523-ef0f60da871b)
![Screen Shot 2020-05-27 at 1.42.19 PM.png](https://images.zenhubusercontent.com/5b572ec492e09f0d21193829/213ebc8e-61a0-41b1-a7ed-5c1ebe623f0d)

**Comment by omehes** [comment]
More issues here:

https://app.zenhub.com/workspaces/content-engineering-tech-team-5af1f4cc12da5e6d74331b60/issues/openstax/cnx-recipes/2362

https://app.zenhub.com/workspaces/content-engineering-tech-team-5af1f4cc12da5e6d74331b60/issues/openstax/cnx-recipes/2359

**Comment by omehes** [comment]
webview: chapter 5.2, footnotes 15 and 20 jump to a different chapter (7.5)
behaves correctly in rex

**Comment by omehes** [comment]
chapter 7.1, footnote 2 - unclickable in rex
OK in webview

https://openstax.org/books/entrepreneurship/pages/7-1-clarifying-your-vision-mission-and-goals

**Comment by brittweinstein** [comment]
BrittanyJ also sees this locally.

**Comment by brittany-johnson** [comment]
*only seeing the first one where the numbering skips from 30 to 61

**Comment by openstaxalina** [comment]
Let's use this issue for the numbering skipped 31 to 60 (the first screenshot) **only**.
I _think_ this is being resolved by https://github.com/openstax/cnx-epub/pull/163?

@omehes could you let us know what issues persist when you test that PR? ^
