### ISSUE TITLE
Footnotes in the Chapter Intro are Throwing Numbering Off

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2380]
# Scenario

Entrepreneurship numbers footnotes continuously through a chapter (then resets at 1 for the next chapter). This book frequently has footnotes in the chapter intros. With the latest code, those are starting at 1 (as they should) but then the next module (ex. 3.1) is **also** restarting at 1.

![EshipFootnotesIntroModule](https://user-images.githubusercontent.com/7863733/83191138-2964e380-a0f9-11ea-8e64-13bbcd21bc28.png)

# Acceptance Criteria (required)
- [ ] footnotes number continuously through the chapter, including from intro to non-intro modules. For example, since the Intro for ch. 3 includes two footnotes, these are numbered 1 & 2. Then the first footnote in 3.1 is numbered 3.

# Test Plan

**Comment by openstaxalina** [comment]
Update: the numbering is correct in CNX instance: https://vendor-staging.cnx.org/contents/04BRDmFF@10.8:1R5dvf9p@4/1-1-Entrepreneurship-Today

We need REX to use the footnote numbers from the recipes, then this should be resolved.

So currently Styles cannot do anything to fix this issue.

![Screen Shot 2020-06-01 at 9 43 14 AM](https://user-images.githubusercontent.com/7863733/83420714-9ffd2c00-a3ec-11ea-93dc-0ba86f5e8636.png)

**Comment by brittany-johnson** [comment]
class `footnote-number` has been changed to data-type
![Screen Shot 2020-06-03 at 1 48 59 PM](https://user-images.githubusercontent.com/24909007/83677188-6cafce00-a5a1-11ea-8c0b-c2007bf2d890.png)

**Comment by MartaSztuka** [comment]
@brittany-johnson in browser footnote doesn't look as above.
![Screenshot from 2020-06-04 17-08-57](https://user-images.githubusercontent.com/47241114/83774644-3dbf5800-a686-11ea-9e0b-8d4fa87d19d2.png)

**Comment by brittany-johnson** [comment]
@MartaSztuka Ah, sorry Marta, I forgot that you don't have the latest footnote transforms available to you locally. I will leave the footnote related issues in the "Ready for testing" column and unassign you so that they can be tested on REX during our test fest. 

Thank you!
