### ISSUE TITLE
EoC Titles

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2382]
Titles `Pytania`, `Zadania` etc. are missing in EoC.
![Screenshot from 2020-05-29 12-46-59](https://user-images.githubusercontent.com/47241114/83251830-866ca200-a1aa-11ea-9bb6-8f55636e4b17.png)
![Screenshot from 2020-05-29 12-45-12](https://user-images.githubusercontent.com/47241114/83251837-87053880-a1aa-11ea-89ff-2d0971e1c24a.png)

**Comment by brittweinstein** [comment]
On the 6/2 call, we decided we could address this when there is a small break in coding in the Corn theme and that the Katalyst team will address. I will put this in the appropriate milestone.

**Comment by MartaSztuka** [comment]
# PASSED
## Titles in EoC (Kluczowe Pojęcia, Pytania, Zadania)
### Fizyka 1![Screenshot from 2020-08-13 15-59-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6a9a7840-857d-42fa-9147-e4aa9a963e78)
### Fizyka 2![Screenshot from 2020-08-13 14-53-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/053e1fc3-4f13-4516-ae10-33af5a7f9e72)![Screenshot from 2020-08-13 14-54-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a8f6709a-ca84-44ae-8eb7-64c65ebd9e4e)
### Fizyka 3![Screenshot from 2020-08-13 14-55-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8a68ae57-489d-4fa3-95bd-cfd6fa9b310c)
