### ISSUE TITLE
Prealgebra 2e - style Learning Objectives

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2383]
Style Learning Objectives with specs from https://github.com/openstax/cnx-recipes/issues/2190

**Comment by wilkus27** [comment]
:exclamation: blocked by https://github.com/openstax/content-managers/issues/1726

**Comment by lwtchu** [comment]
@wilkus27 i added the para tags on katalyst01

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-15 09-08-43](https://user-images.githubusercontent.com/47241114/84627835-e6bc4d00-aee7-11ea-893e-810c4a31ad37.png)
![Screenshot from 2020-06-15 09-04-12](https://user-images.githubusercontent.com/47241114/84627840-e7ed7a00-aee7-11ea-9cc4-62075594a5a6.png)
