### ISSUE TITLE
Prealgebra 2e - style Be Prepared note

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2386]
Style `Be Prepared` with specs from https://github.com/openstax/cnx-recipes/issues/2179

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-04 12-40-28](https://user-images.githubusercontent.com/47241114/83747245-a1cf2580-a660-11ea-9fe7-b7cb376b5560.png)
![Screenshot from 2020-06-04 12-37-31](https://user-images.githubusercontent.com/47241114/83747247-a398e900-a660-11ea-9d91-473be67ca1b8.png)
