### ISSUE TITLE
Prealgebra 2e: style Manipulative Math note

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2390]
Style Manipulative Math note in Prealgebra with specs from https://github.com/openstax/cnx-recipes/issues/2200

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-05 10-39-55](https://user-images.githubusercontent.com/47241114/83855945-1c5b7c00-a719-11ea-83c4-967300160062.png)
![Screenshot from 2020-06-05 10-39-39](https://user-images.githubusercontent.com/47241114/83855949-1cf41280-a719-11ea-9588-48db96b52503.png)
![Screenshot from 2020-06-05 10-44-03](https://user-images.githubusercontent.com/47241114/83856244-87a54e00-a719-11ea-8e15-4a461b34a182.png)
