### ISSUE TITLE
Prealgebra 2e - style no class notes

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2393]
Style notes with no class with specs from https://github.com/openstax/cnx-recipes/issues/2191

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-08 16-21-54](https://user-images.githubusercontent.com/47241114/84041524-3957af80-a9a4-11ea-833f-6a8485cbc2f7.png)
![Screenshot from 2020-06-08 16-20-09](https://user-images.githubusercontent.com/47241114/84041526-3a88dc80-a9a4-11ea-9c07-f5188dd17efe.png)
