### ISSUE TITLE
Prealgebra 2e: style How To note

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2395]
Style note How To with specs from https://github.com/openstax/cnx-recipes/issues/2208

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-16 11-06-23](https://user-images.githubusercontent.com/47241114/84755012-6ff38280-afc1-11ea-8704-99f5efbd20cc.png)
![Screenshot from 2020-06-16 11-07-55](https://user-images.githubusercontent.com/47241114/84755212-a8935c00-afc1-11ea-85ab-7ed4e43a2611.png)
