### ISSUE TITLE
Prealgebra 2e: Style Column Header Table

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2396]
Issue with specs: #2204

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-08 12-47-28](https://user-images.githubusercontent.com/47241114/84022286-4bc2f080-a986-11ea-9274-a7b21107ec4d.png)
![Screenshot from 2020-06-08 12-49-20](https://user-images.githubusercontent.com/47241114/84022436-8af14180-a986-11ea-8575-291da9a693eb.png)
