### ISSUE TITLE
Prealgebra 2e: Style Unnumbered Unstyled Tables

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2399]
Issue with specs: #2205

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-08 14-32-17](https://user-images.githubusercontent.com/47241114/84031040-47ea9a80-a995-11ea-9d13-874993f1e016.png)
![Screenshot from 2020-06-08 14-35-34](https://user-images.githubusercontent.com/47241114/84031084-5df85b00-a995-11ea-8690-ff1706384d39.png)
