### ISSUE TITLE
Different size of chapter number box in TOC

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2401]
Size of box with chapter (and appendix) number depends on number width. All boxes should be the same size and square shape.

![image](https://user-images.githubusercontent.com/40228854/83768406-06997880-a67f-11ea-8b2e-1bc44e950f21.png)

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-08 15-40-49](https://user-images.githubusercontent.com/47241114/84037157-7ae55c00-a99e-11ea-8b2b-3a0b0c47c217.png)
![Screenshot from 2020-06-08 15-40-35](https://user-images.githubusercontent.com/47241114/84037164-7c168900-a99e-11ea-8a4a-68ba72e22af5.png)
