### ISSUE TITLE
Prealgebra 2e: Style Key Terms

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2404]
Issue with specs: #2321

**Comment by brittweinstein** [comment]
@ajluk please put points on this

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-30 15-58-48](https://user-images.githubusercontent.com/47241114/86135083-a6192200-baea-11ea-916d-a9bb56b60926.png)
![Screenshot from 2020-06-30 15-56-07](https://user-images.githubusercontent.com/47241114/86135093-a7e2e580-baea-11ea-9417-4cc8c035b275.png)
