### ISSUE TITLE
Prealgebra 2e: style Try It note

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2407]
Style Try It note with specs from https://github.com/openstax/cnx-recipes/issues/2179

**Comment by wilkus27** [comment]
**Note** Lists in Try It note will be styled within work on https://github.com/openstax/cnx-recipes/issues/2186

![image](https://user-images.githubusercontent.com/40228854/84508351-6ff23a80-acc2-11ea-8469-80fbe5efc4d6.png)

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-12 16-27-42](https://user-images.githubusercontent.com/47241114/84513452-ba2aea00-acc9-11ea-979c-0c6809ad4fcd.png)
![Screenshot from 2020-06-12 16-25-46](https://user-images.githubusercontent.com/47241114/84513454-bbf4ad80-acc9-11ea-9a64-e0de3fd55bcc.png)
