### ISSUE TITLE
Prealgebra 2e: style Media note

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2410]
Style Media note with specs from https://github.com/openstax/cnx-recipes/issues/2206

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-18 12-05-20](https://user-images.githubusercontent.com/47241114/85007664-20958980-b15c-11ea-8165-43a6ced83597.png)
![Screenshot from 2020-06-18 12-00-59](https://user-images.githubusercontent.com/47241114/85007667-21c6b680-b15c-11ea-97f4-a27437772a6e.png)
