### ISSUE TITLE
Prealgebra 2e: style Example

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2411]
Style Example with specs from https://github.com/openstax/cnx-recipes/issues/2203

**Comment by MartaSztuka** [comment]
Tested 
![Screenshot from 2020-06-18 10-23-31](https://user-images.githubusercontent.com/47241114/84998324-f8079280-b14f-11ea-81ca-6a202dc64c66.png)
![Screenshot from 2020-06-18 10-20-34](https://user-images.githubusercontent.com/47241114/84998329-f9d15600-b14f-11ea-921c-483412a398e7.png)
