### ISSUE TITLE
Prealgebra 2e: Style Appendix

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2413]
Related issue with specs:  #2320

**Comment by MartaSztuka** [comment]
Prealgebra 2e
![Screenshot from 2020-06-30 15-10-30](https://user-images.githubusercontent.com/47241114/86130137-08baef80-bae4-11ea-8ab8-f475fad4b723.png)
![Screenshot from 2020-06-30 15-10-22](https://user-images.githubusercontent.com/47241114/86130142-0a84b300-bae4-11ea-88ef-2ecce71262a8.png)
![Screenshot from 2020-06-30 15-10-11](https://user-images.githubusercontent.com/47241114/86130143-0b1d4980-bae4-11ea-9392-cb757b36c5c3.png)
![Screenshot from 2020-06-30 15-09-22](https://user-images.githubusercontent.com/47241114/86130148-0b1d4980-bae4-11ea-8ce0-e207be02c4eb.png)
![Screenshot from 2020-06-30 15-09-05](https://user-images.githubusercontent.com/47241114/86130150-0bb5e000-bae4-11ea-9362-1eba9458b419.png)
![Screenshot from 2020-06-30 15-08-29](https://user-images.githubusercontent.com/47241114/86130151-0c4e7680-bae4-11ea-9006-adbd95d8c9ba.png)

There's no Appendices College Algebra.
