### ISSUE TITLE
Prealgebra 2e: Style Section Exercises

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2416]
From #2059: "There is a section at the end of each module (3.4 Exercises) that requires an icon next to the header icon - structure is similar to (#2164) class="section-exercises""
Related issue with specs:  #2164

**Comment by ajluk** [comment]
@lwtchu I have a question about the column layout in these exercises I have found place there where  some exercises are apearing in two columns. (actually found one but there can be more). Also the images there appearing differently than in the old pdf. I was trying to force three column layout behavior there, but without success. Is this look acceptable? (I'm asking here, because there is no separate issue with documentation for them).
![image](https://user-images.githubusercontent.com/55203598/84682428-e9459380-af35-11ea-88f4-eabdbc142bb3.png)
I have one more question: should these exercises start at new page?

**Comment by lwtchu** [comment]
Talked via slack: but need to investigate if exercises can be displayed in order from left to right instead of up down then left to right. (screenshot below is from existing pdf)
<img width="751" alt="Screen Shot 2020-06-15 at 11 40 27 AM" src="https://user-images.githubusercontent.com/11299125/84694960-b4264a80-af0f-11ea-9199-658769680950.png">

**Comment by ajluk** [comment]
Hi @lwtchu I have managed to style the 3 column exercises to display them fromm left to right!: 
![image](https://user-images.githubusercontent.com/55203598/84918486-f04cdd00-b0c0-11ea-9f57-34075d1451af.png)

But these exercises on the screenshot below, they were styled in 2 columns in the old pdf, so I tried to do this the same way as I did for three columns, but form some reason I can't force them to display form left to right in the pdf (just in html) also they weren't looking good in 3 columns. Is this acceptable just for these to stay this way?: 
![image](https://user-images.githubusercontent.com/55203598/84920253-34d97800-b0c3-11ea-9a15-16c7936abe59.png)

**Comment by ajluk** [comment]
Hi! @lwtchu I have finally manage to style the two column exercises with help from @brittany-johnson! Here is how it looks now: 
![image](https://user-images.githubusercontent.com/55203598/85162348-7f90f680-b261-11ea-8bfd-0223bf752c49.png)
![image](https://user-images.githubusercontent.com/55203598/85162545-d8608f00-b261-11ea-87fc-c5846da371ce.png)

**Comment by ajluk** [comment]
Specs added:

Main Title Text
display: inline-block,
margin-left: v-spacing(1),

TitleIcon
background: url(toDataUri("svg+xml", "designs/corn/resources/corn-exercises.svg")) no-repeat top left,
background-size: contain,
height: v-spacing(4),
width: v-spacing(4),
display: inline-block,
content: "''",

ThreeColumnsSectionExercises

SectionExercisesSpecific
margin-bottom: v-spacing(2),
display: table,
width: 100%,

ExerciseContainer
 margin-bottom: v-spacing(2), (1.4rem)
width: 33%,
display: inline-block,
vertical-align: top,
page-break-inside: avoid,

ExerciseContainerMaterialSet2 (displays in two columns)
margin-bottom: v-spacing(2),
width: 48%,
padding-right: v-spacing(1),
vertical-align: top,
page-break-inside: avoid,

ExercisesParagraphTitle
font-family: Noto Sans', sans-serif
font-size: font-scale(0),
line-height: line-height(0),
color: B2:    #1E7E91,
margin-top: v-spacing(1),
font-style: normal,
display: block,
clear: both,
break-after: avoid,
break-inside: avoid,

ExercisesParagraphTitleItalic
font-family: Noto Sans', sans-serif
color: B2:    #1E7E91,
 font-size: font-scale(0),
line-height: line-height(0),
font-style: italic,
column-span: all,
margin-top: v-spacing(1),
clear: both,
width: 100%,
break-after: avoid,
break-inside: avoid,

ProblemWrapper
display: table,
overflow-wrap: break-word,

ProblemSolutionNumber
 color: black,
 display: table-cell,
text-decoration: none,
 font-weight: bold,
 
ProblemSolutionParagraph
margin-bottom: v-spacing(1),
max-width: 100%,

ProblemSolutionDivider
 margin-right: h-spacing(1),
 
ExerciseTableContainer
margin-left: 0,
margin-right: 0,

Table
table-layout: fixed,
 max-width: 100%,
 
WritingExercises, EverydayExercises (Two Column Exercises)

SectionExercisesSpecific
display: table,

ExerciseContainer
width: 48%,

ExercisesParagraphTitle
font-family: Noto Sans', sans-serif
color: B2:    #1E7E91,

ExercisesParagraphTitleItalic
font-family: Noto Sans', sans-serif
color: B2:    #1E7E91,

ProblemSolutionNumber
color: black,

ExerciseTableContainer
 margin-left: 0,
margin-right: 0,


ExercisesFirstLevelOrderedListInline
display: inline,
list-style-type: none,
padding-right: .5rem


ExercisesListItem--Inline
padding-right: column-v-spacing(1),
display: inline-block,

ExercisesFirstLevelOrderedList Block
display: block,
list-style-type: none,
padding-right: 0,

ExercisesListItem--Block
padding-right: 0,
display: block,

**Comment by ajluk** [comment]
This image will be centered during styling figures: 
![image](https://user-images.githubusercontent.com/55203598/85166568-c2ee6380-b267-11ea-9a9b-4910d8abc3c6.png)

**Comment by ajluk** [comment]
Hi @lwtchu I have a question about the word `Section` in the Section Exercises title, can it be removed from recipe(as I did it in my pr)? Am asking because Natalia has a concern it can impact webview. 
![image](https://user-images.githubusercontent.com/55203598/85394679-31287400-b54f-11ea-9e67-6a9360a7bdf4.png)

**Comment by lwtchu** [comment]
we can leave the word section if that will be easier. that way webview and the pdf can match and i don't think it does anything bad to the pdf

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-25 14-14-44](https://user-images.githubusercontent.com/47241114/85717955-530c2d00-b6ee-11ea-98e1-e79e221acde6.png)
![Screenshot from 2020-06-25 14-14-30](https://user-images.githubusercontent.com/47241114/85717991-5bfcfe80-b6ee-11ea-8a82-56a38af6f6d5.png)
![Screenshot from 2020-06-25 14-20-37](https://user-images.githubusercontent.com/47241114/85718810-2573b380-b6ef-11ea-8b46-8a5fd8df03de.png)

**Comment by lwtchu** [comment]
created documentation card to correspond: https://github.com/openstax/cnx-recipes/issues/2463
