### ISSUE TITLE
Add STIX font to PrinceXML container and test w/ Bakery CLI

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#2420]
# What happened?

The STIX font is required for the corn theme, but it is not available via Google fonts URL or a similar format. 
Because of this, we need to add it to the PrinceXML Docker container and test it in the Bakery CLI. 

## Testing (Once cnx-recipes and COPS are deployed to staging)

Devs and QA will have to update their environments by running the following commands: 
```
docker-compose down
docker-compose pull neb
docker-compose pull pdf
docker-compose build neb
docker-compose build pdf
docker-compose run pdf 
docker-compose run neb neb --version
```
After running these commands, re-fetch content before baking and generating PDF. 

If you're still unable to see the tokens, you made need to restart your computer. 
If it's still not working after restarting computer, please let me know! 

- Generate one of the dev math PDFs, making sure to fetch and re-assemble the content 
- In the end of section and end of chapter exercises there should no longer be question marks but instead the symbols in the screenshot below
  -  One place to look is in prealgebra-2e on page 827 in the PDF:
![Screen Shot 2020-07-02 at 8 56 05 AM](https://user-images.githubusercontent.com/24909007/86367688-e3dc8e80-bc41-11ea-846b-4726e0130dea.png)
 - The symbols should appear when generating a PDF via COPS or locally using the docker-compose scripts

**Comment by brittany-johnson** [comment]
Tested in bakery pipeline: 
<img width="1441" alt="Screen Shot 2020-06-16 at 1 39 55 PM" src="https://user-images.githubusercontent.com/24909007/84814521-3af22a80-afd7-11ea-90bd-b4f8cf44a504.png">

**Comment by brittweinstein** [comment]
Phil and BrittJ tested this locally. When this goes to staging, Marta will generate Precalc and look for the symbol in the screenshot. @brittany-johnson will provide more info.

**Comment by brittany-johnson** [comment]
cnx-recipes and [this PR ](https://github.com/openstax/docker-princexml/pull/1)needs to be deployed to staging for this to be tested

**Comment by brittany-johnson** [comment]
Link to testing results provided by @Stackblocks https://openstax.slack.com/archives/C0LA54Q5C/p1593017950026400?thread_ts=1593009072.021100&cid=C0LA54Q5C

**Comment by brittany-johnson** [comment]
Reopening because the PDF for testing was generated on legacy staging. Legacy does NOT use the newer docker images.

**Comment by brittweinstein** [comment]
@brittany-johnson is working with CE Tech on getting this deployed. Will discuss further today.

**Comment by brittany-johnson** [comment]
COPS prod has been deployed! A dev math PDF with an example of the working STIX font can be found here on page 821. The font is very small but can be adjusted in another issue. 

![Screen Shot 2020-06-29 at 5 05 51 PM](https://user-images.githubusercontent.com/24909007/86060684-df8a5880-ba2a-11ea-9af7-de40aadd2c66.png)

**Comment by MartaSztuka** [comment]
Tested
https://user-images.githubusercontent.com/24909007/86060684-df8a5880-ba2a-11ea-9af7-de40aadd2c66.png
![Screenshot from 2020-07-02 16-10-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0846b454-67ab-4a20-8949-f7b7d78996e2)
