### ISSUE TITLE
Prealgebra 2e: style Links to Literacy note

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2421]
Style **Link to Literacy** note with specs from https://github.com/openstax/cnx-recipes/issues/2200

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-22 11-35-14](https://user-images.githubusercontent.com/47241114/85272450-7b8cf080-b47c-11ea-8f27-44d65e17b068.png)
![Screenshot from 2020-06-22 11-40-19](https://user-images.githubusercontent.com/47241114/85273004-42a14b80-b47d-11ea-8feb-8b36281fd266.png)
