### ISSUE TITLE
Prealgebra 2e: style EoC exercises

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2423]
Style **Review Exercises**, **Practise Test** with specs from https://github.com/openstax/cnx-recipes/issues/2164

**Comment by wilkus27** [comment]
@MartaSztuka Since Elem Alg and Int Alg are already added to template they can be tested as well.

**Comment by MartaSztuka** [comment]
Prealgebra 2e![Screenshot from 2020-07-09 13-04-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7d9b442e-ab47-42cd-9b84-d2b3c385c6a1)
Elem Alg![Screenshot from 2020-07-09 13-05-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/947b4eda-96bc-4f87-b8de-3dd7a00bb8cb)
Int Alg![Screenshot from 2020-07-09 13-07-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9ada41cc-e99a-4695-88eb-a995d995c3e2)
