### ISSUE TITLE
corn theme - index

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2428]
![image](https://user-images.githubusercontent.com/40228854/85022133-28acf380-b173-11ea-91d8-90b3b28308b2.png)

in the old pdf screenshot:  https://user-images.githubusercontent.com/11299125/84916433-b4475700-b083-11ea-995f-e69ee295753d.png

## H1 (Title)
font-size: font-scale(3): 14.25pt, 19.01px, 1.7rem
font style: roboto slab
color: B2:   `#1E7E91`

## Letter
font-size: font-scale(2): 11.88pt, 15.84px, 1.4rem
font style: Noto Sans
color: black: `#000000`

3 column
The links for the page numbers - can we have them be the regular link style? And not in the screenshot.

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/85022133-28acf380-b173-11ea-91d8-90b3b28308b2.png)

I applied font-scale(4) for H1. Here is my comment why: https://github.com/openstax/cnx-recipes/issues/2320#issuecomment-645962258 Let me know if I should change it to font-scale(3).

Here are all applied specs:

#### Index container
```
column-count: 3;
  column-gap: 32px;
```
#### Index title
```
color: #1E7E91;
  font-family: Roboto Slab, serif;
  font-size: 2.0736rem;
  line-height: 1.5rem;
  margin-bottom: 0.7rem;
  column-span: all;
```
![image](https://user-images.githubusercontent.com/40228854/85023145-a32a4300-b174-11ea-86a2-b053a3dd7ab7.png)

#### Index group
```
font-family: Noto Sans, sans-serif;
  margin-bottom: 1.4rem;
```
![image](https://user-images.githubusercontent.com/40228854/85023218-b9d09a00-b174-11ea-8e1c-e95d5a95b681.png)

#### Index group label
```
font-size: 1.44rem;
  line-height: 1.5rem;
  font-weight: bold;
```
![image](https://user-images.githubusercontent.com/40228854/85023307-d66cd200-b174-11ea-9bbd-e12af1034397.png)

#### Index term
```
padding-right: 8px;
```
![image](https://user-images.githubusercontent.com/40228854/85023365-ea183880-b174-11ea-8ab4-a8ce6a7e245c.png)

#### Index link
```
color: #027EB5
```
![image](https://user-images.githubusercontent.com/40228854/85023410-fb614500-b174-11ea-8f2a-4f867e876957.png)
