### ISSUE TITLE
Prealgebra 2e: style Index

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2431]
Style **Index** with specs from #2428

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-24 10-51-45](https://user-images.githubusercontent.com/47241114/85524828-ce93ae80-b608-11ea-8010-0a0696b09133.png)
![Screenshot from 2020-06-24 10-46-40](https://user-images.githubusercontent.com/47241114/85524835-d05d7200-b608-11ea-906e-a2198d20fc2a.png)
