### ISSUE TITLE
Prealgebra 2e: style Key Concepts

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2433]
Style **Key Concepts** with specs from https://github.com/openstax/cnx-recipes/issues/2322

**Comment by MartaSztuka** [comment]
Tested 
![Screenshot from 2020-06-26 14-32-50](https://user-images.githubusercontent.com/47241114/85857355-fd04bb80-b7b9-11ea-9554-63517bf99a58.png)
![Screenshot from 2020-06-26 14-32-33](https://user-images.githubusercontent.com/47241114/85857358-fd9d5200-b7b9-11ea-9691-304cc69db985.png)
