### ISSUE TITLE
College Algebra: style TOC

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2438]
Style TOC with specs from https://github.com/openstax/cnx-recipes/issues/2060

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-24 12-55-25](https://user-images.githubusercontent.com/47241114/85543075-0525f500-b61a-11ea-8baf-e64a06be4e67.png)
![Screenshot from 2020-06-24 12-53-46](https://user-images.githubusercontent.com/47241114/85543080-06572200-b61a-11ea-8127-3b26c32375ae.png)
