### ISSUE TITLE
College Algebra: style Preface

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2440]
Style Preface with specs from https://github.com/openstax/cnx-recipes/issues/2320

**Comment by MartaSztuka** [comment]
Tested 
![Screenshot from 2020-06-24 16-14-12](https://user-images.githubusercontent.com/47241114/85573046-d289f580-b635-11ea-81b7-bc173f0fec15.png)
![Screenshot from 2020-06-24 16-07-42](https://user-images.githubusercontent.com/47241114/85573325-141aa080-b636-11ea-868d-7766954cc8db.png)
