### ISSUE TITLE
corn theme: stepwise lists

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2442]
![Screen Shot 2020-06-23 at 9 30 55 AM](https://user-images.githubusercontent.com/11299125/85416599-42b05280-b534-11ea-917b-f214bb069e9a.png)

Font style: should follow base font style of whatever feature/section/book they are in
"Bullet" label: `Step #.`
Words that fall to the next line: they are aligned with the text within the list and not with the "bullet"

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/85684054-0dd80300-b6ce-11ea-82ca-997329cc1ff6.png)

Is it ok? Should I change something?

**Comment by lwtchu** [comment]
@wilkus27 perfect! thank you
