### ISSUE TITLE
corn theme: Titles shapes convention

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2445]
Styling Titles in Corn Theme needs decision what approach we should take/be the best solution.
Related document with some propositions: https://docs.google.com/document/d/1RS7ostFOCoF378p_Gi-ganVkEEKlimGW3zXFo6HEPOU/edit#heading=h.6vastgn7j4uy

**Comment by ajluk** [comment]
@MartaSztuka Information for testing purposes:
This is a clean up issue. I have cleaned the titles in the Answer Key (moved to the title shape), so this title needs to be checked in at least in one book from each dev-math, calculus,  preacalculus or precalculus-coreq and nothing should be changed there.
Screenshot for reference (Prealgebra 2e):
![image](https://user-images.githubusercontent.com/55203598/93208833-7ed30800-f75d-11ea-94cb-d3855f424a7f.png)

The paragraph titles has been also cleaned and need to be checked if there are no differences in the books from above:
Screenshot for reference (Prealgebra 2e):
![image](https://user-images.githubusercontent.com/55203598/93208958-aaee8900-f75d-11ea-9bf1-90f788dce3e6.png)

 
Within this PR I have also added page breaks to paragraph titles in the Statistics book (this is new), so they need to be tested here as well in one from the statistics books (they shouldn't be orphaned or broken inside into another page): 
Screenshots for reference:
![image](https://user-images.githubusercontent.com/55203598/93208599-18e68080-f75d-11ea-84bf-f4a5e7ae50a3.png)
![image](https://user-images.githubusercontent.com/55203598/93208408-cf963100-f75c-11ea-8d0b-bc001f86e3a9.png)
![image](https://user-images.githubusercontent.com/55203598/93208439-dae95c80-f75c-11ea-8d95-24045d0c77f8.png)

**Comment by MartaSztuka** [comment]
# PASSED
## Titles
### Precalculus
![Screenshot from 2020-09-16 13-04-41](https://user-images.githubusercontent.com/47241114/93329319-501c6680-f81d-11ea-943d-e90487cef07b.png)
![Screenshot from 2020-09-16 13-04-16](https://user-images.githubusercontent.com/47241114/93329320-514d9380-f81d-11ea-9b20-7304e301b6fa.png)
### Prealgebra
![Screenshot from 2020-09-16 13-07-44](https://user-images.githubusercontent.com/47241114/93329549-a4274b00-f81d-11ea-850a-c4a0193ca995.png)
![Screenshot from 2020-09-16 13-07-27](https://user-images.githubusercontent.com/47241114/93329551-a4bfe180-f81d-11ea-92bb-83b9bb5a3626.png)
### College Algebra coreq
![Screenshot from 2020-09-16 16-11-56](https://user-images.githubusercontent.com/47241114/93349193-7b13b400-f837-11ea-973a-043af77dd30e.png)
![Screenshot from 2020-09-16 16-10-53](https://user-images.githubusercontent.com/47241114/93349206-7ea73b00-f837-11ea-9f0d-99be93f513d7.png)
### Calculus 1
![Screenshot from 2020-09-16 16-13-46](https://user-images.githubusercontent.com/47241114/93349321-9ed6fa00-f837-11ea-828c-9d0d291c4486.png)
![Screenshot from 2020-09-16 16-14-12](https://user-images.githubusercontent.com/47241114/93349393-b57d5100-f837-11ea-9347-9ee8f5ca6a6a.png)
### HS Statistics
![Screenshot from 2020-09-16 16-20-28](https://user-images.githubusercontent.com/47241114/93350108-8f0be580-f838-11ea-95c7-66bc6610d4e5.png)
![Screenshot from 2020-09-16 16-19-27](https://user-images.githubusercontent.com/47241114/93350112-903d1280-f838-11ea-8acd-fca5fa7e45a9.png)
