### ISSUE TITLE
Prealgebra 2e: style stepwise lists

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2446]
Style stepwise lists with specs from https://github.com/openstax/cnx-recipes/issues/2442

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-06-30 09-30-37](https://user-images.githubusercontent.com/47241114/86097054-6df6ec80-bab4-11ea-914f-da09a8480ed7.png)
![Screenshot from 2020-06-30 09-29-57](https://user-images.githubusercontent.com/47241114/86097056-6f281980-bab4-11ea-8fef-91562903bf44.png)
