### ISSUE TITLE
corn theme - equations

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2447]
<img width="803" alt="Screen Shot 2020-04-13 at 11 51 31 AM" src="https://user-images.githubusercontent.com/11299125/79140181-31e9a080-7d7d-11ea-812b-f7b93f88f6bd.png">

equations in an `<equation>` tag should be centered. 
the font should be the basic math font and settings that we have installed for the corn theme

**Comment by ajluk** [comment]
How they look: 
![image](https://user-images.githubusercontent.com/55203598/85742092-41815000-b703-11ea-8f7f-1cb9e27270bc.png)

Specs added:
**Equation Container**
display: flex,
align-items: center,
justify-content: center,
 margin-bottom: v-spacing(1)

**Comment by lwtchu** [comment]
@ajluk this is good thank you!
