### ISSUE TITLE
College Algebra: style Example

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2450]
Style Example with specs from https://github.com/openstax/cnx-recipes/issues/2209

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-07-03 10-47-27](https://user-images.githubusercontent.com/47241114/86451060-a992f000-bd1a-11ea-886f-0273512c4bc4.png)
![Screenshot from 2020-07-03 10-47-03](https://user-images.githubusercontent.com/47241114/86451070-ab5cb380-bd1a-11ea-995c-84244ccb7453.png)
