### ISSUE TITLE
College Algebra: style unnumebered equations

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2451]
Related issue with specs: https://github.com/openstax/cnx-recipes/issues/2447

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-07-02 10-06-33](https://user-images.githubusercontent.com/47241114/86333465-391d9d80-bc4c-11ea-8ec3-a62380d3abec.png)
![Screenshot from 2020-07-02 09-58-30](https://user-images.githubusercontent.com/47241114/86333476-3e7ae800-bc4c-11ea-9f6e-f34b522c639d.png)
