### ISSUE TITLE
Prealgebra 2e: style Answer Key

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2455]
Related issue with specs: #2460

**Comment by ajluk** [comment]
Hi @lwtchu I have found out that images in in the Answer Key placed in the solution container has a new line element placed in paragraph before them, so they can't be styled exactly on top of the solution container as it was done in carnival theme: 
![image](https://user-images.githubusercontent.com/55203598/85869230-b3bd6780-b7cb-11ea-8a45-31f8081cc7fc.png)
In the pdf file they look like this: 
![image](https://user-images.githubusercontent.com/55203598/85869369-dd768e80-b7cb-11ea-8599-4a1ecb68e18c.png)
![image](https://user-images.githubusercontent.com/55203598/85869453-fb43f380-b7cb-11ea-8ef7-555e846b0750.png)
Is it acceptable or do you want to remove the lines from them?

**Comment by ajluk** [comment]
Specs added: 
![image](https://user-images.githubusercontent.com/55203598/85870391-3abf0f80-b7cd-11ea-8701-95b35604b90c.png)
Solution Area
display: table;
margin-bottom: 1.4rem;
width: 100%;
Solution Container
![image](https://user-images.githubusercontent.com/55203598/85870526-6b9f4480-b7cd-11ea-822c-adfbbf3c5055.png)
display: inline-table;
overflow-wrap: break-word;
margin-bottom: 1.4rem;
vertical-align: top;
width: 33%;
padding-right: 0.7rem;
![image](https://user-images.githubusercontent.com/55203598/85870673-a4d7b480-b7cd-11ea-8b49-239a9ebc0d10.png)
Solution Number
display: table-cell;
text-decoration: none;
color: #000000;
font-weight: bold;
![image](https://user-images.githubusercontent.com/55203598/85870770-ccc71800-b7cd-11ea-964b-d1a6929b03ef.png)
Solution Container
    display: table-cell;
    width: 100%;
    padding-left: 0.7rem;

**Comment by ajluk** [comment]
I've got one more question: do we want the lists with tokens also display inline if it's enough space?
![image](https://user-images.githubusercontent.com/55203598/85874777-7230ba80-b7d3-11ea-8f10-b184c1366a33.png)

**Comment by lwtchu** [comment]
@ajluk yes please. if there's enough space, we should try to have them display inline. however, do we want to wait for the #2366 to be implemented before we proceed?

**Comment by ajluk** [comment]
@lwtchu Thank you! About tokens lists I have already added basic styles for them in the section exercises just to check how the three column layout will behave and I did the same in the Answer Key, but off course it needs to be checked after Stix font implementation. What do you think if I will leave the basic styles for them here as well? Do you think that the headers look fine as they are? 
![image](https://user-images.githubusercontent.com/55203598/86095258-f4f69580-bab1-11ea-890a-f1dba8c257a9.png)

**Comment by ajluk** [comment]
@lwtchu could you open separate issue with documentation for Answer Key which I could link here and move the specs there?

**Comment by lwtchu** [comment]
@ajluk https://github.com/openstax/cnx-recipes/issues/2460

i meant to say, for the `<newline/>` issue, i need to remove them from the content, so please don't worry about those

**Comment by ajluk** [comment]
@lwtchu Ok. Thank you!

**Comment by wilkus27** [comment]
@MartaSztuka Since Elem Alg and Int Alg are already added to template they can be tested as well.

**Comment by MartaSztuka** [comment]
Prealgebra 2e![Screenshot from 2020-07-09 13-14-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f44f219b-88ca-4eda-a085-deabb2ef7067) ![Screenshot from 2020-07-09 13-12-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4820934a-6dbb-4d52-83aa-067113342968)
Elem Alg![Screenshot from 2020-07-09 13-13-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/96b410c7-a06b-4442-95bc-81a5737786c0)![Screenshot from 2020-07-09 13-12-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/04f11c0b-2461-4173-9d3d-2dc1e6cfe513)
Int Alg![Screenshot from 2020-07-09 13-10-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fa08ea00-8b3b-48ae-9a33-b4b4a63d85f6)
