### ISSUE TITLE
The text linking to unnumbered untitled tables is numbered 

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#2457]
# Scenario
https://openstax.org/books/chemistry-2e/pages/10-4-phase-diagrams#fs-idm194167232
In Chemistry 2e on REX, the linked text `Example 10.12` is linking to an unnumbered, untitled table. 
We need to confirm if the text in the PDF is appearing the same (I'm expecting it to be). 

Once that is confirmed, we must decide what the linked text should display when referring to a table that is unnumbered and untitled. Based on the decision, a recipe update is required for all books. 

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **Images or Screenshots Included:** [ x] Yes  [ ] No  (_attach below_)

![Screen Shot 2020-06-29 at 11 56 03 AM](https://user-images.githubusercontent.com/24909007/86034148-aee0f980-b9ff-11ea-8ef4-0f64041d5ec6.png)
![Screen Shot 2020-06-29 at 11 56 09 AM](https://user-images.githubusercontent.com/24909007/86034151-b0122680-b9ff-11ea-8172-b72fb7877e66.png)

# Environment: (required)
* **Medium**: [ x] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ x] production  [ ] qa  [ ] staging  [ ] dev  [ ] content

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low

# Test Plan

**Comment by openstaxalina** [comment]
The auto-generated text is designed for linking to things with numbers, since numbers might change so we don't want numbers hard-coded into a link.

When linking to things without numbers, our preference is to **require anchor text be set by the author/editor**. I am not sure the best place to enforce this (in the publishing flow, in the baking flow...?). I am putting this in the backlog for now.

**Comment by openstaxalina** [comment]
^ I created a card on the CM board to remove this specific link because we don't need a link or any text there. We'll remove the parenthetical reference entirely.

**Comment by brittany-johnson** [comment]
Awesome, thank you! 
I guess I can close this issue in cnx-recipes, correct?

**Comment by openstaxalina** [comment]
@brittany-johnson sorry, I put my feedback in two separate comments 🤦‍♀️ . Above I did have a suggestion as to how we could avoid this scenario in the future. It is low prio but I'd like to keep it open in case we find an opportunity to do this with the refactor or other work?

**Comment by brittany-johnson** [comment]
AH! I see now, sorry about that!

**Comment by lwtchu** [comment]
Refactored recipe now produces a "broken" link [link] that CMs search for prior to publishing
