### ISSUE TITLE
Coreq: create recipe and basic styles

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2458]
Create new recipe `precalculus-coreq`. At this moment only book College Algebra Coreq is added to file `books.txt`. 

Added styles:
- Toc
- Preface
- Link
- ModuleTitles
- LearningObjectives
- PageLists
- BasicTable
- ColumnHeaderTable
- UnnumberedUnstyledTable
- Index

**Comment by wilkus27** [comment]
#### Information for tester

On katalyst01 there is no separate book for College Alebra coreq for now. We are working on regular College Algebra.
To be able to test coreq, you have to use `college-algebra-coreq` in all scripts. 
If you want to bake book on the server use `precalculus-coreq` - this is name of recipe used by College Algebra Coreq.

**Comment by MartaSztuka** [comment]
Tested
![Screenshot from 2020-07-02 11-15-36](https://user-images.githubusercontent.com/47241114/86340589-6c185f00-bc55-11ea-892d-e108ed1d28fb.png)

![Screenshot from 2020-07-02 11-17-09](https://user-images.githubusercontent.com/47241114/86340702-9f5aee00-bc55-11ea-84b5-9c815fc46eae.png)

![Screenshot from 2020-07-02 11-22-55](https://user-images.githubusercontent.com/47241114/86341320-6f601a80-bc56-11ea-822d-549f4798f3a6.png)

![Screenshot from 2020-07-02 11-25-05](https://user-images.githubusercontent.com/47241114/86341641-dbdb1980-bc56-11ea-9f01-4df5deef943c.png)

![Screenshot from 2020-07-02 12-53-24](https://user-images.githubusercontent.com/47241114/86350500-12b72c80-bc63-11ea-9505-bc81068584bf.png)

![Screenshot from 2020-07-02 12-48-52](https://user-images.githubusercontent.com/47241114/86350505-164ab380-bc63-11ea-903b-f461fb252b9e.png)

![Screenshot from 2020-07-02 12-48-39](https://user-images.githubusercontent.com/47241114/86350507-16e34a00-bc63-11ea-9056-558187ecec3f.png)

![Screenshot from 2020-07-02 12-47-28](https://user-images.githubusercontent.com/47241114/86350508-177be080-bc63-11ea-8029-89c885f1c42c.png)
