### ISSUE TITLE
corn theme: answer key

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2460]
## Headers
Headers follow the schema set for the appendices and preface

## Columns
3 column layout will be utilized. The numbering should go left to right then down.

## Text
Follows base font specifications
Numbers are bold with a period.

**Comment by ajluk** [comment]
Specs Added:
Specs added: 
Answer Key CompositePage
argin-bottom: v-spacing(2),
![image](https://user-images.githubusercontent.com/55203598/85870391-3abf0f80-b7cd-11ea-8701-95b35604b90c.png)
**Solution Area**
display: table;
margin-bottom: 1.4rem;
width: 100%;
![image](https://user-images.githubusercontent.com/55203598/85872115-9b4f4c00-b7cf-11ea-9c5d-c9f937f6068f.png)
**Solution Container with Image/table on top**
display: table-cell;
vertical-align: bottom;
padding-top: 0.7rem;
width: 100%;
![image](https://user-images.githubusercontent.com/55203598/85872356-e49f9b80-b7cf-11ea-8e42-f9c6a9ad86cf.png)
![image](https://user-images.githubusercontent.com/55203598/85872404-fa14c580-b7cf-11ea-8019-d3a0c445475d.png)
**regular Solution Container**
margin-bottom: 0.7rem;
max-width: 100%;
padding-right: 0.7rem;

![image](https://user-images.githubusercontent.com/55203598/85870526-6b9f4480-b7cd-11ea-822c-adfbbf3c5055.png)
**Solution Wrapper**
display: inline-table;
overflow-wrap: break-word;
margin-bottom: 1.4rem;
vertical-align: top;
width: 33%;
padding-right: 0.7rem;
![image](https://user-images.githubusercontent.com/55203598/85870673-a4d7b480-b7cd-11ea-8b49-239a9ebc0d10.png)
**Solution Number**
display: table-cell;
text-decoration: none;
color: #000000;
font-weight: bold;
![image](https://user-images.githubusercontent.com/55203598/85870963-0ef05980-b7ce-11ea-9920-5d26f3a8825f.png)
**Solution Paragraph**
margin-bottom: 0.7rem;
max-width: 100%;
padding-right: 0.7rem;
![image](https://user-images.githubusercontent.com/55203598/85871076-3515f980-b7ce-11ea-804a-e7555353d402.png)
**AnswerKeyUnorderedListUnstyled**
list-style-type: none;
margin-left: 8px;
![image](https://user-images.githubusercontent.com/55203598/85871235-67bff200-b7ce-11ea-997f-f11a375ea79d.png)
**AnswerKeyOrderedListUnstyled**
list-style-type: none,
margin-left: h-spacing(1),
Image
max-width: 100%;
![image](https://user-images.githubusercontent.com/55203598/85871577-e3ba3a00-b7ce-11ea-9c48-7d1279567a2f.png)
**Table Container**
margin-left: 0;
margin-right: 0;
