### ISSUE TITLE
College Algebra Coreq: style notes

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2461]
Style notes in College Algebra Coreq:

- How To (https://github.com/openstax/cnx-recipes/issues/2208)
- Try It (https://github.com/openstax/cnx-recipes/issues/2179)
- Q&A (https://github.com/openstax/cnx-recipes/issues/2179)
- Media (https://github.com/openstax/cnx-recipes/issues/2206)
- No Class Note (https://github.com/openstax/cnx-recipes/issues/2191)

**Comment by wilkus27** [comment]
@MartaSztuka Can you also test `Try It` , `Be Prepared` and `Media` note in Prealgebra 2e? I had to rework styling of icon condensed notes and I just want to be sure that they display properly in both books.

**Comment by MartaSztuka** [comment]
**College Algebra Coreq**
@wilkus27 in How to note list is outside the box![Screenshot from 2020-07-09 12-18-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7b0b09f8-b48b-428f-95ca-964b79c76182)
Try it![Screenshot from 2020-07-09 12-24-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/155f49a1-e9ca-4117-b310-9d880704e2a5)
Q&A![Screenshot from 2020-07-09 12-26-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/07b01b80-9754-44e1-9456-6dd12e8e8a23)
Media![Screenshot from 2020-07-09 12-28-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ed969a37-834d-43be-86b2-c965ec9767e6)
No class note![Screenshot from 2020-07-09 12-32-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/71121ae0-2a4f-448e-8e50-5f3b602c18fa)

**Elementary Algebra**
Try it![Screenshot from 2020-07-09 12-33-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d73a36e4-51da-4c53-a66d-65133fdab66f)
Be prepared![Screenshot from 2020-07-09 12-35-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fc7f6a40-60c9-4e0c-bf42-d7fc04642bd7)
Media![Screenshot from 2020-07-09 12-38-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/11ab5e73-faf6-4b7b-921c-2ef8f0c66f3f)

**Intermediate Algebra**
Try it @wilkus27 Try it breaks in two lines![Screenshot from 2020-07-09 12-40-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/25d20ff9-94bb-435c-9125-4903a989c68d)
Be prepared![Screenshot from 2020-07-09 12-41-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8f0ec917-b4c9-40ec-81a4-16e12a15aaba)
Media![Screenshot from 2020-07-09 12-42-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/18a22f51-6a14-488b-8167-131ab61991c2)

**Prealgebra**
Try it![Screenshot from 2020-07-09 12-45-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/75002a73-dd08-4fd7-b9fc-ad0c7d0a3e3a)
Be prepared![Screenshot from 2020-07-09 12-48-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ab0daabd-0743-48c4-a3ee-d86874d03a6b)
Media![Screenshot from 2020-07-09 12-48-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f45b5a53-92b1-41b8-91a1-c6109a550d33)

**Comment by wilkus27** [comment]
List in How To will be styled within https://github.com/openstax/cnx-recipes/issues/2474

**Comment by wilkus27** [comment]
Here is the PR https://github.com/openstax/cnx-recipes/pull/2496 with fix for Try It note.

**Comment by wilkus27** [comment]
@MartaSztuka It's ready for testing :slightly_smiling_face:

**Comment by MartaSztuka** [comment]
**College Algebra Coreq**
How to
![Screenshot from 2020-07-13 12-34-45](https://user-images.githubusercontent.com/47241114/87295337-516fa100-c505-11ea-9054-05081306a44f.png)
Try it
![Screenshot from 2020-07-13 12-37-33](https://user-images.githubusercontent.com/47241114/87295549-add2c080-c505-11ea-99c9-108bc617b4b2.png)
Q&A
![Screenshot from 2020-07-13 12-38-11](https://user-images.githubusercontent.com/47241114/87295606-bf1bcd00-c505-11ea-82cc-9611effed5a9.png)
Media
![Screenshot from 2020-07-13 12-38-34](https://user-images.githubusercontent.com/47241114/87295638-ca6ef880-c505-11ea-8e73-b08e06ecfa0b.png)
No class note
![Screenshot from 2020-07-13 12-39-28](https://user-images.githubusercontent.com/47241114/87295730-eb374e00-c505-11ea-8fab-a210d355c800.png)


**Elementary Algebra**
Try it
![Screenshot from 2020-07-13 12-41-18](https://user-images.githubusercontent.com/47241114/87295880-2cc7f900-c506-11ea-8485-10f39dd68723.png)
Be prepared
![Screenshot from 2020-07-13 12-41-47](https://user-images.githubusercontent.com/47241114/87295916-3cdfd880-c506-11ea-94dd-42b0ba795805.png)
Media
![Screenshot from 2020-07-13 12-42-27](https://user-images.githubusercontent.com/47241114/87295970-55e88980-c506-11ea-8ae6-0d12e438629e.png)

**Intermediate Algebra**
Try it
![Screenshot from 2020-07-13 12-44-36](https://user-images.githubusercontent.com/47241114/87296176-a6f87d80-c506-11ea-8bf1-c0754f9e0045.png)
Be prepared
![Screenshot from 2020-07-13 12-45-59](https://user-images.githubusercontent.com/47241114/87296296-d4452b80-c506-11ea-8c53-a85e4a27fe32.png)
Media
![Screenshot from 2020-07-13 12-46-24](https://user-images.githubusercontent.com/47241114/87296351-e921bf00-c506-11ea-8edf-ad10bfa2c674.png)

**Prealgebra**
Try it
![Screenshot from 2020-07-13 12-47-59](https://user-images.githubusercontent.com/47241114/87296480-1b332100-c507-11ea-9e91-c5096e2f7fbc.png)
Be prepared
![Screenshot from 2020-07-13 12-48-24](https://user-images.githubusercontent.com/47241114/87296515-2d14c400-c507-11ea-96f6-c9200026c7e4.png)
Media
![Screenshot from 2020-07-13 12-48-49](https://user-images.githubusercontent.com/47241114/87296556-3aca4980-c507-11ea-884a-64a23a22835e.png)
