### ISSUE TITLE
College Algebra College Allgebra Coreq: style Section Exercises

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2466]
Related issue with specs: https://github.com/openstax/cnx-recipes/issues/2463

**Comment by ajluk** [comment]
There is need to `add material-set2` class to some of the exercises in College Algebra. For testing purposes these classes has been added by Larissa to 6 exercises in 2.4 Section Exercises (Algebraic): 
![image](https://user-images.githubusercontent.com/55203598/86400005-2c2e9780-bca8-11ea-8d9f-ae1cc2693939.png)

**Comment by wilkus27** [comment]
@MartaSztuka Since Precalc and Alg&Trig are already added to template they can be tested as well.

**Comment by MartaSztuka** [comment]
@wilkus27 in Precalc long equations overlap ![Screenshot from 2020-07-09 13-30-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/01086953-3b05-4d97-a97e-0777e65f8da8)
College Algebra Coreq![Screenshot from 2020-07-09 13-27-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b7f07372-6d58-4434-95cb-db4950eafab5)
College Allgebra![Screenshot from 2020-07-09 13-29-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1e4d4b0c-407c-4d9e-9c5e-5fd38f7dfdf8)

Alg&Trig![Screenshot from 2020-07-09 13-32-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a0e46a1c-6beb-4b5b-b759-c8cd0af4ef68)

**Comment by lwtchu** [comment]
@MartaSztuka these will be fixed with a content fix ([we'll add the `material-set-2` class](https://docs.google.com/spreadsheets/d/151zvgyedwSl_kgJohlSBnmMF8DNvRlXmTMYwkE52Jcw/edit#gid=0)). if that's the only thing, I'm going to close this issue. let me know if it needs to be reopen :)!
