### ISSUE TITLE
[HOLDING FOR PROD] Lock APUSH recipe

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2469]
# Scenario

Once APUSH is officially released and there are no known issues to resolve, we should lock the recipe. This will ensure we can continue with baked styles development, and Tutor can bring in updated content anytime, without the recipe changing.

NOTE that we should see if this will still be necessary with RAP. It depends on RAP functionality and when Tutor will use RAP.

# Acceptance Criteria (required)
- [x] There is a locked ("prod") version of the APUSH recipe available in the dropdown on Legacy

# Test Plan

**Comment by brittweinstein** [comment]
Styles will confirm this on the RAP call with CE Tech today. Regardless, we need to see if this is possible and get this locked.

**Comment by brittany-johnson** [comment]
Based on today's call I think we should lock the recipe. Once the approved book list is being used by everyone we won't have to lock recipes anymore, but while that process is still being worked on we can continue to lock recipes for now.

**Comment by openstaxalina** [comment]
That sounds good to me; I updated the title of the issue to reflect that we no longer need to wait on this one. Thank you @brittany-johnson 🎉

**Comment by brittany-johnson** [comment]
Verified on easyvm5
![Screen Shot 2020-08-12 at 9 30 01 AM](https://user-images.githubusercontent.com/24909007/90027709-72e7b800-dc7e-11ea-8ea7-19ff258fe6e5.png)

**Comment by meeragovindaraju** [comment]
Verified on Prod

![Screen Shot 2020-08-12 at 2 38 20 PM](https://user-images.githubusercontent.com/33066187/90059930-89573900-dca9-11ea-9a4f-6b8816200b29.png)

**Comment by brittany-johnson** [comment]
@meeragovindaraju Ah sorry, I just moved this to ready for testing a few minutes ago but didn't comment on it yet. 

This cannot be tested on prod until we deploy to prod. We have to verify for `AP U.S. History Prod`

**Comment by meeragovindaraju** [comment]
**Verified in Staging**

![Screen Shot 2020-08-17 at 10 26 07 AM](https://user-images.githubusercontent.com/33066187/90413471-19afc800-e074-11ea-923f-42abf3bff127.png)

**Comment by meeragovindaraju** [comment]
Verified in legacy production

![Screen Shot 2020-08-26 at 11 50 37 AM](https://user-images.githubusercontent.com/33066187/91332849-62f9c900-e792-11ea-9880-78e06c872eb7.png)
