### ISSUE TITLE
Remove release-flag-enabled conditionals 

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#2470]
# What happened?

We enabled all release flags in a previous release. As a final step to clean up our repo, we need to remove the `release-flag-enabled` conditionals that nest the mixins. After these are removed all recipes(non-prod) should be regenerated.
If there are any css changes, these should be noted in this issue, tested, and the [recipe updates doc](https://docs.google.com/document/d/14E1Bgs-lK4kdmaPqQyEK2b82WAR9NtFwzElaJgPZhpQ/edit) updated.

[Link to release flag descriptions doc](https://docs.google.com/document/d/1ziR2PcSvioOLAHSRNWZga3m-8DlUM_qaskIjpWtoS60/edit)

**Comment by lwtchu** [comment]
No longer pursuing now that we're doing kitchen and this is clean up for .... cnx-recipes
