### ISSUE TITLE
Implement Figures for Dev Math and CoReq 

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2473]
See documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2207 

- [x] Prealgebra 2e 
- [x] Int Alg 2e 
- [x] Elem Alg 2e 
- [x] College Alg w/ CoReq
- [ ] Precalculus 
- [ ] Alg and Trig

**Comment by wilkus27** [comment]
PR for dev-math: https://github.com/openstax/cnx-recipes/pull/2478

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-07-10 at 12 51 17 PM](https://user-images.githubusercontent.com/24909007/87183715-4241e680-c2ac-11ea-8299-b1e610cc713f.png)
![Screen Shot 2020-07-10 at 12 50 51 PM](https://user-images.githubusercontent.com/24909007/87183718-42da7d00-c2ac-11ea-8fe1-17166d3983a4.png)

**Comment by MartaSztuka** [comment]
Prealgebra 2e![Screenshot from 2020-07-13 14-19-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a1326d4d-df72-4379-ac84-c8d39e3a0407)
 Int Alg 2e![Screenshot from 2020-07-13 14-18-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/da57de6e-237c-4c01-ae4d-091c3c76bf7a)
 Elem Alg 2e![Screenshot from 2020-07-13 14-17-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/46ed1f94-467e-45ac-aba8-8d58370cc78e)
 College Alg CoReq![Screenshot from 2020-07-13 14-14-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d559f676-c3f6-406b-99b5-2e966c4f2b8c)
