### ISSUE TITLE
Implement Lists Within Notes for Dev Math and Co Req

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2474]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2207

- [x] Prealgebra 2e 
- [x] Int Alg 2e 
- [x] Elem Alg 2e 
- [x] College Alg w/ CoReq
- [x] Precalculus 
- [x] Alg and Trig

**Comment by brittany-johnson** [comment]
Link to a screenshot of where this issue occurs: https://github.com/openstax/cnx-recipes/issues/2368#issuecomment-655827026

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-07-10 at 2 55 32 PM](https://user-images.githubusercontent.com/24909007/87193048-740f7900-c2bd-11ea-8718-6947ad5db81f.png)

**Comment by MartaSztuka** [comment]
@brittany-johnson in Precalculus and  Alg and Trig all notes are unstyled
Precalculus ![Screenshot from 2020-07-13 14-09-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ea91ae3e-61b3-4f1f-9c2b-749f17903470)
Alegbra&Trigonometry![Screenshot from 2020-07-13 14-11-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ad837fb0-0d35-4792-8aae-3762b8122c69)
 Prealgebra 2e![Screenshot from 2020-07-13 14-05-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/81001015-da58-4389-ab9e-5f3997a1abb4)
 Int Alg 2e![Screenshot from 2020-07-13 14-06-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7d7f194f-1937-4ec1-8ac4-658179d658f0)
 Elem Alg 2e![Screenshot from 2020-07-13 14-07-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/25689277-1f5d-401c-b8e1-da4b593d2e5e)
 College Alg CoReq![Screenshot from 2020-07-13 14-07-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/eb180f57-7112-44a5-bf81-d5e93096dbf0)

**Comment by wilkus27** [comment]
Notes are styled within https://github.com/openstax/cnx-recipes/pull/2537. It can be retested after merge this PR.

**Comment by wilkus27** [comment]
@MartaSztuka It's ready for retesting in all 7 books. During tests please verify which problems from https://github.com/openstax/cnx-recipes/issues/2511 still exists. Some of them should be resolved within #2537

**Comment by MartaSztuka** [comment]
@wilkus27 In **Precalculus** notes are not fixed, also in `How to` not header is missing.![Screenshot from 2020-07-29 12-38-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2bd4e557-fd4d-408a-a57b-d4e0c587a65f)![Screenshot from 2020-07-29 12-37-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ec98cab5-dc6b-4182-b2d6-51ad91467801)
**Int Algebra** Steps in Examples are unstyled ![Screenshot from 2020-07-29 12-45-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0492a1af-d36b-4be8-8484-b2aaa2296a09)![Screenshot from 2020-07-29 12-42-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/632082a3-80a0-41de-9aaa-efed4fa1940f)
**Prealgebra**![Screenshot from 2020-07-29 12-33-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/39f3345d-90d2-4bc3-a57e-7e39710a6ffe)
**Elem Algebra**![Screenshot from 2020-07-29 12-49-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bde6536f-68a3-41b5-b0f5-8697d154ec99)
![Screenshot from 2020-07-29 12-49-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bae482d9-b9bb-4219-b6c5-7e10928f3aa3)
 **College Alg**![Screenshot from 2020-07-29 12-52-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/892a3d5d-ffe2-437e-a22e-096a8b5a7cac)
 **College Alg coreq**![Screenshot from 2020-07-29 12-54-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a50e6ab1-f18b-4189-b945-b08de9fd11bb)![Screenshot from 2020-07-29 12-53-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7e809919-6eea-40d0-84cd-144b7329de51)![Screenshot from 2020-07-29 12-53-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2620fc9d-85c3-40c7-850b-411b78469405)
**Alegbra&Trigonometry** 'Media' and 'How to' with stepwise list are not supported ![Screenshot from 2020-07-29 13-07-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5f8c791c-c192-40c7-96ba-51e8892aa0c3)![Screenshot from 2020-07-29 13-08-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/98462b87-9584-43fc-a98d-ca25b0bb0799)

**Comment by lwtchu** [comment]
@MartaSztuka can you give me the location of that how to note in precal that isn't working? i can change the class for you

**Comment by MartaSztuka** [comment]
@lwtchu I'm affraid there's problem with all How to and Media notes, headers and style is missing, all look like this:
**1. How to** ![Screenshot from 2020-07-29 16-56-50](https://user-images.githubusercontent.com/47241114/88816680-ef799180-d1bc-11ea-95a7-54e1cee5ebe6.png)
**2. Media**
![Screenshot from 2020-07-29 17-00-14](https://user-images.githubusercontent.com/47241114/88816926-38314a80-d1bd-11ea-82f2-01f321cb387f.png)

**Comment by lwtchu** [comment]
@MartaSztuka i edited 3.3 Power Functions and Polynomial Functions with the updated classes

**Comment by MartaSztuka** [comment]
## Passed
Classes updated in Chapter 3.3 Power Functions and Polynomial Functions.
### Precalculus
#### How to
![Screenshot from 2020-07-30 14-45-39](https://user-images.githubusercontent.com/47241114/88924548-ba7c4600-d273-11ea-9011-446afbb741d8.png)
![Screenshot from 2020-07-30 14-48-58](https://user-images.githubusercontent.com/47241114/88924629-d253ca00-d273-11ea-8374-4b0146b2f3bc.png)

#### Media
![Screenshot from 2020-07-30 14-46-30](https://user-images.githubusercontent.com/47241114/88924575-c10abd80-d273-11ea-95cf-067b18519f89.png)
![Screenshot from 2020-07-30 14-49-26](https://user-images.githubusercontent.com/47241114/88924699-e5669a00-d273-11ea-9755-4299f33225f2.png)
