### ISSUE TITLE
Implement Key Equations in EOC for Dev Math and CoReq

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2475]
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2474 

Specs: @lwtchu 

- [x] Prealgebra 2e 
- [x] Int Alg 2e 
- [x] Elem Alg 2e 
- [x] College Alg w/ CoReq
- [x] Precalculus 
- [x] Alg and Trig

**Comment by lwtchu** [comment]
@brittweinstein i'm confused as to what is needed. the link goes to lists? and do we need specs for this since it should be just another EOC section

**Comment by wilkus27** [comment]
We need an information how table should be styled:

![image.png](https://images.zenhubusercontent.com/5b2d3f82505d510c73d5ea62/7c13d3c0-3d07-45cb-9a64-95a2c59fe8b6)

This is how it looks now. Style is inherited from styles for tables. Should we change anything in Key Equations table?

**Comment by brittweinstein** [comment]
@lwtchu please weigh in on ^ when you can

**Comment by lwtchu** [comment]
@wilkus27 let's keep whatever it is that they're inheriting.  i don't think there's a new need at the moment

**Comment by brittany-johnson** [comment]
@brittany-johnson will update this card with a screenshot after the morning scrum

**Comment by wilkus27** [comment]
Since there is no need for more code changes  it can be tested now.

**Comment by MartaSztuka** [comment]
@wilkus27 In College Alg. coreq Key Equations is styled.
Coll. Alg, Precal and Alg&Trig. headers aren't styled equations in tables are.
In Prealg, Int. alg and Elem. alg Key Equations are not present.
College Algebra coreq![Screenshot from 2020-07-27 15-10-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c629020d-f09e-4574-8a64-ba2b653a88e9)
College Algebra![Screenshot from 2020-07-27 15-07-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/88ce81f0-444e-43cb-9b2b-76b8abf38436)
Precalculus![Screenshot from 2020-07-27 15-11-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e09dbe12-d6bb-4731-9996-bdd925cda7f4)
Algebra and Trigonometry![Screenshot from 2020-07-27 15-38-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a7c78408-f144-4e7e-9d2d-3f3775f8ef8d)

**Comment by wilkus27** [comment]
@MartaSztuka Some additional change in recipe is needed. Precalc should have two composite chapters in EOC part. It will be added within work on https://github.com/openstax/cnx-recipes/issues/2540. So I'm going to close this issue.
