### ISSUE TITLE
Prealgebra 2e: Style figures

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2477]
Related issue with specs: #2185

**Comment by wilkus27** [comment]
@MartaSztuka Since Elem alg and Int Alg are already added to template they can be tested as well.

**Comment by MartaSztuka** [comment]
Elem alg![Screenshot from 2020-07-09 12-56-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f3fa4f60-fb3a-47af-b911-fba28ac66ade)
Int Alg![Screenshot from 2020-07-09 12-57-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/749fd2bf-fbf0-4aa3-9f14-fc1fa8983a96)
Prealg![Screenshot from 2020-07-09 12-56-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/24f2873a-0fc7-4f0e-a123-0f1c59a7ce8a)
