### ISSUE TITLE
College Algebra Coreq: implement example

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2479]
Style Examples in Coreq College Algebra with specs from https://github.com/openstax/cnx-recipes/issues/2209

**Comment by MartaSztuka** [comment]
College Algebra Coreq![Screenshot from 2020-07-09 12-16-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/59500897-2946-4d9d-bbec-4fe835cc0e5e)
