### ISSUE TITLE
Appendix in Precalculus

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2481]
Appendix has styled headers only.
SPECS: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2207

**Comment by brittany-johnson** [comment]
Appendix titles in coreq need to be styled, here's what they look right now for reference
![Screen Shot 2020-07-08 at 7 43 27 PM](https://user-images.githubusercontent.com/24909007/86984136-57efc880-c153-11ea-99e0-12ccdb29666c.png)

**Comment by MartaSztuka** [comment]
Precalculus![Screenshot from 2020-07-28 13-36-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1349c5cf-d426-4a70-9b82-e7d5bb501eba)
