### ISSUE TITLE
Ruby Training + Kitchen Tutorials + More

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2483]
Lists of tasks to be completed: 
- [Learn Ruby (Flatiron)](https://flatironschool.com/free-courses/learn-ruby) (Slack channel #learn-ruby for help/discussion) 
- Do kitchen tutorials
- Write directions for the parts of the chemistry recipe that are written inline (+add specs)
- When find errors that are not helpful, capture it and we’ll make them more helpful
- All missing specs (https://codecov.io/gh/openstax/kitchen/tree/master/lib/kitchen)
- start with counter_spec, pantry_spec, utils_spec
- bigger task: write Chemistry recipe for whole book

Notes from initial group refactor meeting: https://docs.google.com/document/d/1JHhR3HTYBCDiPovdPwqwUsirmTvqfdgT1ib7WtFYPH0/edit

**Comment by brittany-johnson** [comment]
I've updated the card description w/ a list of additional tasks that need to be completed. The devs are able to allocate approx 20% of their time to Kitchen related work during Q3. Because of this, the card will move frequently from the backlog to in progress as we work through the checklist.

**Comment by lwtchu** [comment]
PRETTY SURE WE ARE TRAINED CAUSE WERE DOING STUFFFFF
