### ISSUE TITLE
Try it breaks in two line

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2485]
Elementart Alg ![Screenshot from 2020-07-09 11-36-30](https://user-images.githubusercontent.com/47241114/87023914-b9a64600-c1d8-11ea-824f-2a2ad6d5409b.png)
Intermediate Alg
![Screenshot from 2020-07-09 13-19-10](https://user-images.githubusercontent.com/47241114/87033635-dba6c500-c1e6-11ea-901f-1c34ae29011a.png)

**Comment by wilkus27** [comment]
@MartaSztuka This is fixed by https://github.com/openstax/cnx-recipes/issues/2496, which is connected to another issue. Please close this when you finish testing https://github.com/openstax/cnx-recipes/issues/2461.

**Comment by MartaSztuka** [comment]
Elem alg![Screenshot from 2020-07-13 12-51-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/560d49bb-dbaa-475f-a410-3938f31a01ca)
Inter alg![Screenshot from 2020-07-13 12-52-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/deec0f92-4337-43b7-970d-7b555c849ef3)
