### ISSUE TITLE
Numbered elements reset within Coreq Skills section

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2487]
All numbered elements like Examples, Tables and Figures should reset within Coreq Skills sections.

E.g. when Coreq Skills has two examples, first example beside that section should have number 1.

Look at the module `2.1 The Rectangular Coordinate Systems and Graphs` in College Algebra Coreq for the reference:

![image](https://user-images.githubusercontent.com/40228854/87046412-75776d80-c1f9-11ea-8350-777c445c1a47.png)

(On the screenshot first example out of the coreq skills with wrong number).

**Comment by MartaSztuka** [comment]
College Algebra coreq![Screenshot from 2020-07-27 15-35-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cde3abe9-e349-4fd9-8c20-ad7eab03eb64)![Screenshot from 2020-07-27 15-36-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/37b19ad2-39e1-4759-bd78-e3b04d0efc31)
