### ISSUE TITLE
Co-Req Answer Key Implementation 

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2488]
Style Answer Key in College Algebra Coreq with specs from https://github.com/openstax/cnx-recipes/issues/2460

**Comment by brittany-johnson** [comment]
@wilkus27 Hello! Since this is still in the backlog, I'm assigning Alan to work on it. The other issue he was assigned to is done in coreq.

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-07-08 at 7 43 27 PM](https://user-images.githubusercontent.com/24909007/87075719-663af480-c1e6-11ea-9509-ce9e9ef912b7.png)

**Comment by brittany-johnson** [comment]
Currently, this is what the answer key looks like
![Screen Shot 2020-07-08 at 7 43 27 PM](https://user-images.githubusercontent.com/24909007/87075755-70f58980-c1e6-11ea-88df-d8a4db95f641.png)

**Comment by brittany-johnson** [comment]
![Screen Shot 2020-07-14 at 7 41 29 AM](https://user-images.githubusercontent.com/24909007/87426876-86cbcb80-c5a5-11ea-8bec-44d2e816a2a4.png)
![Screen Shot 2020-07-14 at 7 41 23 AM](https://user-images.githubusercontent.com/24909007/87426883-87fcf880-c5a5-11ea-9bf5-edaaaed78890.png)

**Comment by MartaSztuka** [comment]
Tested![Screenshot from 2020-07-15 16-16-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dafdf3d6-e9a3-4808-b6a4-3606243e29e9)![Screenshot from 2020-07-15 16-17-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a36a4198-f1ac-4108-8bfa-48929e69056a)
