### ISSUE TITLE
EOC Styling for Co-Req Implementation

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2489]
Style EOC exercises sections with specs from https://github.com/openstax/cnx-recipes/issues/2164 and Key Terms with specs from https://github.com/openstax/cnx-recipes/issues/2321

**Comment by MartaSztuka** [comment]
![Screenshot from 2020-07-13 13-29-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f03c463c-58e3-4afb-b755-ecef5941295c)![Screenshot from 2020-07-13 13-29-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f2c8a59f-bce5-43db-ab8e-d73b3feae1da)![Screenshot from 2020-07-13 13-29-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e1900013-756b-45e4-82b2-93508b89e7f0)![Screenshot from 2020-07-13 13-30-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9fe203c4-4166-4f6c-8c60-8759f811208a)
