### ISSUE TITLE
College Algebra Coreq: implement equation styling

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2494]
Style unnumbered equations with specs from https://github.com/openstax/cnx-recipes/issues/2447

**Comment by MartaSztuka** [comment]
![Screenshot from 2020-07-13 13-34-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3c24a7f5-bee5-4e5d-ac2f-97c6677daeae)![Screenshot from 2020-07-13 13-33-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/383c0cb1-b2f6-4cee-a50a-1eefd828e2fa)
