### ISSUE TITLE
Unstyled commentary in coreq

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2501]
Commentary in Examples from College Algebra Coreq has no style:

![image](https://user-images.githubusercontent.com/40228854/87294182-a6aab300-c503-11ea-8894-d08b88866e40.png)

**Comment by MartaSztuka** [comment]
![Screenshot from 2020-07-14 12-50-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e3c3e1a5-800b-4b62-bb62-499bee052c21)
