### ISSUE TITLE
Bug: coreq math/corn theme: bullet lists are not contained in text box

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2508]
# Scenario

![Screen Shot 2020-07-20 at 3 33 01 PM](https://user-images.githubusercontent.com/11299125/87983657-5224ac00-ca9e-11ea-8f24-de802d05683a.png)

lists are not being contained in the text area

# Acceptance Criteria (required)
please bullets start where the body text starts 

# Impact
* **Severity**: [x] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [x] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/88227106-b5474780-cc32-11ea-921c-2334bab95adc.png)

**Comment by MartaSztuka** [comment]
College Algebra coreq![Screenshot from 2020-07-27 17-09-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9ce6cff8-6d83-4411-87ef-3d0f5924002c)
