### ISSUE TITLE
corn theme: stepwise lists need to be supported

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2511]
- [x] College Algebra w/ Coreq
- [x] Precalculus
- [x] Alg and Trig

![Screen Shot 2020-07-21 at 10 10 56 AM](https://user-images.githubusercontent.com/11299125/88072639-e7757e00-cb3a-11ea-949f-d1d010e7ad98.png)
Screenshot from Ch 4 Linear Functions / Sec 2 Linear Functions
These have the class `stepwise` for the list and it would be nice if they looked like the how to ones with the words "Step 1. Step 2. etc"

What it looks like now:
![Screen Shot 2020-07-21 at 10 16 35 AM](https://user-images.githubusercontent.com/11299125/88073164-800bfe00-cb3b-11ea-9e52-591edbdc4df5.png)
Screenshot from Ch 4 Linear Functions / Sec 2 Linear Functions

What it should look like:
![Screen Shot 2020-07-21 at 10 18 08 AM](https://user-images.githubusercontent.com/11299125/88073186-8601df00-cb3b-11ea-8e80-b588455a1394.png)

**Comment by MartaSztuka** [comment]
@wilkus27 in 'How to' is missing, also Step lists aren't supported.
(Example from Precalculus) ![Screenshot from 2020-07-27 15-53-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/004ccffd-cc2d-47e9-9aaa-61de9930dcda)

College Algebra coreq! Here it is ok. [Screenshot from 2020-07-27 15-45-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4d994754-1af8-4a1c-abbf-30fe6c50c446)
Algebra&Trigonometry![Screenshot from 2020-07-27 15-47-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5cdf5b44-6dd4-4f14-a03d-ffdd756e22bd)
College Algebra![Screenshot from 2020-07-27 15-49-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1bd46f7e-c633-4b65-8b90-7a833cce37db)

**Comment by MartaSztuka** [comment]
# FAILED
## Stepwise lists
### Precalculus![Screenshot from 2020-08-05 10-43-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bee1b5b4-e0fb-47c0-9c6c-22ab1aa2a598)

**Comment by wilkus27** [comment]
@lwtchu This is a content issue. Text "Step" is hard coded in content not created by recipes:

![image](https://user-images.githubusercontent.com/40228854/89407229-b42c1500-d71e-11ea-9058-9317490673ff.png)

**Comment by lwtchu** [comment]
in example 7 in the screenshot, it has the `list-type="labeled-item"` attribute on the list in CNXML. is there a way to target that and remove the bullets?

I changed a few of them to be stepwise lists for testing purposes and changed the how to classes in 6.4

**Comment by wilkus27** [comment]
@lwtchu This attribute appears also in these cases:

1) 
![image](https://user-images.githubusercontent.com/40228854/89542672-42c49300-d800-11ea-94cb-ac152bfbc531.png)

2) 
![image](https://user-images.githubusercontent.com/40228854/89542726-58d25380-d800-11ea-9f94-616b0bc0a5f4.png)

So bullets will be removed also from those lists. Is it ok?

**Comment by lwtchu** [comment]
@wilkus27 yes please - is there a way to make that a standard for all books? since the `list-type="labeled-item"` is a default for the removal of bullets in the CNXML?

**Comment by wilkus27** [comment]
@lwtchu Yes, we can do this. To make sure. Do you mean all books from corn theme or all books in general, so also from carnival theme?

**Comment by lwtchu** [comment]
@wilkus27 in general - but corn theme can be the first priority

**Comment by wilkus27** [comment]
@MartaSztuka Can you please test step lists if they are working now? For other lists about which we talked with Larissa I created separate issue https://github.com/openstax/cnx-recipes/issues/2619. As we discussed on the call other books will be tested on staging.

**Comment by MartaSztuka** [comment]
# PASSED
## Stepwise lists
### Precalculus
![Screenshot from 2020-08-14 13-08-23](https://user-images.githubusercontent.com/47241114/90243555-6787be80-de2f-11ea-9ed7-c43edc3a575e.png)
