### ISSUE TITLE
make sure drop down for precalculus-coreq recipe/style is available

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2512]
Just a friendly reminder to make sure the `precalculus-coreq` recipe and style are available on the drop down for legacy and cops.

This is blocking testing webview work.

**Comment by brittany-johnson** [comment]
Legacy dropdown has been updated: https://github.com/openstax/cnx/issues/1113
Cops dropdown not yet updated. Will edit this comment when it is

**Comment by meeragovindaraju** [comment]
The option is seen in both COPS and legacy prod.

![Screen Shot 2020-08-12 at 2 30 20 PM](https://user-images.githubusercontent.com/33066187/90059305-90317c00-dca8-11ea-9798-439665b35b95.png)

![Screen Shot 2020-08-12 at 2 29 11 PM](https://user-images.githubusercontent.com/33066187/90059355-a8a19680-dca8-11ea-8049-5213e46ca540.png)
