### ISSUE TITLE
Bug: College Physics & AP Physics : Numbered bullets are left aligned

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2514]
## Book Details

- Book Name: AP Physics
- Generation Method: docker-compose baking
- Source Collection: Col11844
- Source - PDF
- Source Server: katalyst01.cnx.org
- Branch: Nocturnal.Nico
- Page 102 & 118 & 500

## Issue Description
The numbered bullets are not in line with the text.

## Proposed Solution
Make the numbered bullets inline with the text. 

- 102
![Screen Shot 2020-07-21 at 3.12.25 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/bb042eed-73d0-4561-bb8d-d583c7b408ae)

-118
![Screen Shot 2020-07-21 at 3.13.44 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/83989a71-c3ec-4453-b257-37339b19d3ef)

- 500
![Screen Shot 2020-07-21 at 3 39 06 PM](https://user-images.githubusercontent.com/33066187/88104619-51584c80-cb68-11ea-8e68-5a4e4afefb2a.png)

**Comment by lwtchu** [comment]
Might impact rest of carnival theme??

**Comment by lwtchu** [comment]
Copied from #2528 
Appears in College Physics as well
## Book Details

- Book Name: College Physics
- Generation Method: docker-compose baking
- Source Collection: col11406
- Source: PDF
- Source Server: katalyst01.cnx.org
- Branch: Nocturnal.Nico
- Page 250

## Issue Description

The numbered bullets are left aligned

## Possible Solution

The numbered bullets are in line with the text

![Screen Shot 2020-07-22 at 1.41.11 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/6c5d0cb9-7599-40de-b424-d6e34065aa4e)

**Comment by meeragovindaraju** [comment]
- Section 25.6 
- COPS output PDFAP Physics
- the numbered bullets are still left aligned. 

![Screen Shot 2020-07-23 at 1 39 30 PM](https://user-images.githubusercontent.com/33066187/88324918-02d2bb80-ccea-11ea-9341-4d1781375db1.png)

**Comment by meeragovindaraju** [comment]
The other two sections have changed and is no longer numbered in AP Physics COPS output PDF

**Comment by meeragovindaraju** [comment]
Another example in Section 1.3

![Screen Shot 2020-07-23 at 1 52 38 PM](https://user-images.githubusercontent.com/33066187/88326556-cb650e80-cceb-11ea-98b9-205cff843b49.png)

**Comment by brittweinstein** [comment]
We will revisit this when we revise this title - maybe Q2 2021.

**Comment by MartaSztuka** [comment]
#### PASSED
##### AP College physics ![Screenshot from 2021-02-25 08-43-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/022b2e9e-541b-4e1c-96d1-d26bcba8cac8)![Screenshot from 2021-02-25 08-43-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4f4b16dd-5f79-472d-907a-c0b1d529a03b)![Screenshot from 2021-02-25 08-44-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/62d75ec6-f1b6-4de3-9dc0-d6aaf66e54bb)
##### College physics![Screenshot from 2021-02-25 08-45-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b72bae86-cbdb-414f-bc77-af9f435e8ee8)![Screenshot from 2021-02-25 08-50-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/db950273-7c4e-4958-afe7-567843634819)![Screenshot from 2021-02-25 08-49-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1b098c38-e098-4d0c-9d7d-afdc11525897)
