### ISSUE TITLE
Bug: AP Physics: Theta not italicized 

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2515]
## Book Details

- Book Name: AP Physics
- Generation Method: docker-compose baking
- Source Collection: Col11844
- Source - PDF
- Source Server: katalyst01.cnx.org
- Branch: Nocturnal.Nico
- Page 154 

## Issue Description

The theta is not italicized 

## Proposed Solution

Make the theta italicized since it is talking about the angular direction. 

![Screen Shot 2020-07-21 at 3.18.23 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/381a0f4e-9a83-4438-8c9c-afd7f10484cd)

**Comment by lwtchu** [comment]
Content issue. Closing
