### ISSUE TITLE
Bug: AP Physics: Missing Closed Bracket

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2516]
## Book Details

- Book Name: AP Physics
- Generation Method: docker-compose baking
- Source Collection: Col11844
- Source - PDF
- Source Server: katalyst01.cnx.org
- Branch: Nocturnal.Nico
- Page 164

## Issue Description
Missing Closed bracket at the end of the statement.

## Proposed Solution
Insert a closed bracket at the end of the statement. 

![Screen Shot 2020-07-21 at 3.22.13 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/bb09464d-6b62-4937-9beb-1fcd42274f8a)

**Comment by lwtchu** [comment]
Content issue. Closing.
