### ISSUE TITLE
Bug: AP Physics: Images are left justified

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2517]
## Book Details

- Book Name: AP Physics
- Generation Method: docker-compose baking
- Source Collection: Col11844
- Source - PDF
- Source Server: katalyst01.cnx.org
- Branch: Nocturnal.Nico
- Page 210 & 211

## Issue Description

Images are left-justified

## Proposed Solution

Make the images center aligned
- Page 210
![Screen Shot 2020-07-21 at 3.25.39 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/91ff5507-15ee-4ae5-80c9-4f534d27920a)

- Page 211
![Screen Shot 2020-07-21 at 3.25.58 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/6e0a0f3d-6b92-44d7-a367-fc3309ca830e)

**Comment by lwtchu** [comment]
Expected.

Figures are centered. (Figure number, caption, etc)
Images are left align. (without figure caption, number, etc)
