### ISSUE TITLE
BUG: AP Physics: There are 2 links to the video

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2518]
## Book Details

- Book Name: AP Physics
- Generation Method: docker-compose baking
- Source Collection: Col11844
- Source - PDF
- Source Server: katalyst01.cnx.org
- Branch: Nocturnal.Nico
- Page 456 & 538

## Issue Description

There are 2 links to the video

## Proposed Solution

Only allow one link
-456
![Screen Shot 2020-07-21 at 3.29.55 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/86a81e76-3012-49fa-840b-ec7a07203f5b)

-538
![Screen Shot 2020-07-21 at 3 40 17 PM](https://user-images.githubusercontent.com/33066187/88104747-7baa0a00-cb68-11ea-9f51-d56e78fe27c7.png)

**Comment by lwtchu** [comment]
The "Click to view content" is embedded features - expected.
