### ISSUE TITLE
BUG: AP Physics: Key Equations alignment 

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2519]
## Book Details

- Book Name: AP Physics
- Generation Method: docker-compose baking
- Source Collection: Col11844
- Source - PDF
- Source Server: katalyst01.cnx.org
- Branch: Nocturnal.Nico
- Page- 41, 469

## Issue Description

The placement/alignment of the test looks odd if its only a few entries

## Proposed Solution
Have the content alignment be in line to the content and not the heading.
- Page 41
![Screen Shot 2020-07-21 at 3.36.34 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/a576fe1c-10ca-485c-a243-89477c69a309) 

- Page 469
![Screen Shot 2020-07-21 at 3.35.44 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/59635950-5a9e-4dbc-a4ec-c2d031e7a254)

**Comment by lwtchu** [comment]
@meeragovindaraju would you mind generating the pdf with cops and finding all instances so we can see the scope?

**Comment by meeragovindaraju** [comment]
@lwtchu KEY EQUATIONS section is not in the COPS output PDF. Should we close this issue?
