### ISSUE TITLE
BUG: AP Physics: Should the equation number show up in the EOC content? 

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2520]
## Book Details

- Book Name: AP Physics
- Generation Method: docker-compose baking
- Source Collection: Col11844
- Source - PDF
- Source Server: katalyst01.cnx.org
- Branch: Nocturnal.Nico
- Page - 543,595, 596

## Issue Description

Should the equation numbers show up in the EOC content? 

## Possible Solution

Hide the equation numbers from the EOC content. 

- 543
![Screen Shot 2020-07-21 at 3.45.08 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/3d72647d-59f0-4428-8251-97b338e93ee5)

- 595 & 596

![Screen Shot 2020-07-21 at 3.45.38 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/c9473fab-703a-4d2e-ab6d-08ad151909d2)

**Comment by lwtchu** [comment]
This is expected. Closing~
