### ISSUE TITLE
BUG: AP Physics: Table is left justified

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2521]
## Book Details

- Book Name: AP Physics
- Generation Method: docker-compose baking
- Source Collection: Col11844
- Source - PDF
- Source Server: katalyst01.cnx.org
- Branch: Nocturnal.Nico
- Page 488 & 489

## Issue Description

This table is left justified.

## Proposed Solution

The table should be center aligned.

![Screen Shot 2020-07-21 at 3.48.15 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/165a1fc2-601b-4654-b809-65ce4a827791)

![image](https://user-images.githubusercontent.com/11299125/88316647-c600c780-ccdd-11ea-902d-44b9c5f894d7.png)

**Comment by lwtchu** [comment]
Use cops generated PDF and double check if it's still..an issue?

**Comment by meeragovindaraju** [comment]
NOT the case in COPS output PDF. Closing
