### ISSUE TITLE
BUG: AP Physics: Hyperlink in the references

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2522]
## Book Details

- Book Name: AP Physics
- Generation Method: docker-compose baking
- Source Collection: Col11844
- Source Server: katalyst01.cnx.org
- Branch: Nocturnal.Nico
- Page 429

## Issue Description
Should this be a hyper link?

## Proposed Solution
Make the URL a hyperlink

![Screen Shot 2020-07-21 at 3.51.19 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/b6fba2b3-95d5-4ce9-bf76-b25c880f61f6)

**Comment by lwtchu** [comment]
Expected.
