### ISSUE TITLE
BUG: AP Physics: Table missing the left border

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2523]
## Book Details

- Book Name: AP Physics
- Generation Method: docker-compose baking
- Source Collection: Col11844
- Source Server: katalyst01.cnx.org
- Branch: Nocturnal.Nico
- Page 783

## Issue Description

Left border of pi) is missing

## Proposed Solution

Add the left border

![Screen Shot 2020-07-21 at 3.53.34 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/5af28088-02e5-4400-8947-85f5ab67a97a)

**Comment by lwtchu** [comment]
Expected. Closing.
