### ISSUE TITLE
BUG: College Physics: Space is needed between all the chapter titles and the first Images 

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2524]
## Book Details

- Book Name: College Physics
- Generation Method: docker-compose baking
- Source Collection: col11406
- Source: PDF
- Source Server: katalyst01.cnx.org
- Branch: Nocturnal.Nico
- Page All Chapter first pages

## Issue Description

There is no space between the chapter titles and the images.

## Possible Solution

Include a gap between the chapter titles and the first images. 

![Screen Shot 2020-07-21 at 4.20.32 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/64072162-edac-4b14-9271-4e3e5efbe2ef)

**Comment by lwtchu** [comment]
![Screen Shot 2020-07-23 at 12 19 04 PM](https://user-images.githubusercontent.com/11299125/88317324-b9c93a00-ccde-11ea-8669-edd5496b62df.png)
it should work okay ??? might need to check how pdf was generated

**Comment by lwtchu** [comment]
troubleshoot pdf generation first

**Comment by brittweinstein** [comment]
@lwtchu what is the prio on this? when does this need to be addressed?

**Comment by lwtchu** [comment]
@brittweinstein there isn't an issue right now - i think there's an issue with the pdf generation

**Comment by meeragovindaraju** [comment]
The issue (needing a gap between the title and the splash image) exists even in the COPS production PDF

https://ce-pdf-spike.s3.amazonaws.com/col11406-latest-production-296.pdf


![Screen Shot 2020-07-24 at 1 38 58 PM](https://user-images.githubusercontent.com/33066187/88424658-8e644f00-cdb3-11ea-9216-f7d206e932f5.png)

**Comment by lwtchu** [comment]
@brittany-johnson do we need to add the `content` class on the `<content>` tag?

**Comment by brittweinstein** [comment]
We will revisit this when we need to revise this title, maybe in Q2 2021.

**Comment by wilkus27** [comment]
Checked with the newest changes:

**PDF generated locally**

![image](https://user-images.githubusercontent.com/40228854/108511817-b3289280-72c0-11eb-8139-d5571c1f9383.png)

**PDF generated by CORGI** 
https://openstax-cops-artifacts.s3.amazonaws.com/col11406-latest-production-235.pdf

![image](https://user-images.githubusercontent.com/40228854/108514123-c426d300-72c3-11eb-8e07-4a8b17fa2c79.png)
