### ISSUE TITLE
BUG: College Physics: Text-wrap needed

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2527]
## Book Details

- Book Name: College Physics
- Generation Method: docker-compose baking
- Source Collection: col11406
- Source: PDF
- Source Server: katalyst01.cnx.org
- Branch: Nocturnal.Nico
- Page 133 & 559 & 828

## Issue Description

Vertical motion(... line is running over the second section.

## Possible Solution
Change the font size and text-wrap

- 133
![Screen Shot 2020-07-22 at 1.14.22 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/41857aca-9f67-4525-b082-5366bbd27c36)

-559
![Screen Shot 2020-07-22 at 3 23 43 PM](https://user-images.githubusercontent.com/33066187/88225069-811e5780-cc2f-11ea-9375-0114d8792e8b.png)

- 828
![Screen Shot 2020-07-23 at 10 29 07 AM](https://user-images.githubusercontent.com/33066187/88305725-73201380-cccf-11ea-80e3-9e4d487f36ce.png)

**Comment by lwtchu** [comment]
Content issue.
