### ISSUE TITLE
BUG: College Physics: Numbered bullets are not inline with text

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2528]
## Book Details

- Book Name: College Physics
- Generation Method: docker-compose baking
- Source Collection: col11406
- Source: PDF
- Source Server: katalyst01.cnx.org
- Branch: Nocturnal.Nico
- Page 250

## Issue Description

The numbered bullets are left aligned

## Possible Solution

The numbered bullets are in line with the text

![Screen Shot 2020-07-22 at 1.41.11 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/6c5d0cb9-7599-40de-b424-d6e34065aa4e)

**Comment by lwtchu** [comment]
Same as #2514, consolidated.
