### ISSUE TITLE
BUG: College Physics: subcategories are not in bold

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2530]
## Book Details

- Book Name: College Physics
- Generation Method: docker-compose baking
- Source Collection: col11406
- Source: PDF
- Source Server: katalyst01.cnx.org
- Branch: Nocturnal.Nico
- Page 463 & 464 & 847 & 848

## Issue Description

Compared to other such tables; Blood pressures in large arteries(resting, Bladder & Digestive tract are not bold
## Possible Solution

Blood pressures in large arteries(resting, Bladder & Digestive tract need to be in bold
![Screen Shot 2020-07-22 at 2.54.08 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/229b9eca-523c-48f1-8066-af3cce4d95b0)

- Conductor, Semiconductor and Insulators

![Screen Shot 2020-07-23 at 10 32 35 AM](https://user-images.githubusercontent.com/33066187/88306115-f17cb580-cccf-11ea-859e-ab5d284f52df.png)

![Screen Shot 2020-07-23 at 10 32 26 AM](https://user-images.githubusercontent.com/33066187/88306158-00fbfe80-ccd0-11ea-8fac-2b3e10250bb7.png)

- Example

![Screen Shot 2020-07-22 at 2.58.06 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/32577cd2-039f-4b08-a728-39627f33c61b)

**Comment by lwtchu** [comment]
Content issue.
