### ISSUE TITLE
corequisite/precal - unnumbered splash images

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2533]
# What happened?
In the past, we had the splash images be unnumbered in the recipe. We weren't really sure why it was coded into the splash class and maybe decided to remove that attribute and test it with the unnumbered class since it's a little more descriptive. However...it breaks the splash. 

![Screen Shot 2020-07-23 at 10 59 26 AM](https://user-images.githubusercontent.com/11299125/88309193-9b117600-ccd3-11ea-83ce-d8590f0dc0fc.png)

SO EITHER. We need to make a special case for this book and makt the splash images in the book unnumbered (and maybe put a reason why - the intro counts with the next section therefore the numbering doesn't reset when it hits 1.1)

or we support the unnumbered class on a splash image

This should impact both the `precalculus` recipe and the `precalculus-coreq` recipe

**Comment by brittany-johnson** [comment]
Unnumbered splashes are now supported 
![Screen Shot 2020-07-27 at 12 20 57 PM](https://user-images.githubusercontent.com/24909007/88571712-acc08980-d003-11ea-882b-eaccded96deb.png)

**Comment by brittany-johnson** [comment]
For @MartaSztuka testing, I think chapter 4 is the only one with the `unnumbered splash` class? cc: @lwtchu

**Comment by lwtchu** [comment]
@MartaSztuka @brittany-johnson i also added it to chapter 5 just now so you have two instances - chapter 4 & 5 would be a good place to test.

**Comment by MartaSztuka** [comment]
# PASSED
## 1. Unnumbered splashes
In chapter 4th and 5th images have class="splash unnumbered" in PDF display properly
### College Algebra
#### Chapter 4
![Screenshot from 2020-07-30 12-08-49](https://user-images.githubusercontent.com/47241114/88911108-a594b800-d25d-11ea-8883-f6aa41cd676c.png)
![Screenshot from 2020-07-30 12-13-39](https://user-images.githubusercontent.com/47241114/88911430-205dd300-d25e-11ea-833a-cf4e2ef59c39.png)

#### Chapter 5
![Screenshot from 2020-07-30 12-11-31](https://user-images.githubusercontent.com/47241114/88911498-38355700-d25e-11ea-8f96-d05db5f48fa9.png)
![Screenshot from 2020-07-30 12-14-49](https://user-images.githubusercontent.com/47241114/88911555-4a16fa00-d25e-11ea-8c70-0fda497a9e82.png)
### College Algebra coreq
#### Chapter 4
![Screenshot from 2020-07-30 13-14-36](https://user-images.githubusercontent.com/47241114/88916638-b5fd6080-d266-11ea-8098-afff6b832849.png)
![Screenshot from 2020-07-30 13-15-50](https://user-images.githubusercontent.com/47241114/88916697-d0cfd500-d266-11ea-9313-0d6fb9d33164.png)
#### Chapter 5
![Screenshot from 2020-07-30 13-14-53](https://user-images.githubusercontent.com/47241114/88916660-c0b7f580-d266-11ea-966f-46fb997393b8.png)
![Screenshot from 2020-07-30 13-16-25](https://user-images.githubusercontent.com/47241114/88916737-e47b3b80-d266-11ea-8209-0661b9f07d7c.png)
### Precalculus
#### Chapter 4
![Screenshot from 2020-07-30 14-35-55](https://user-images.githubusercontent.com/47241114/88923482-1ba31a00-d272-11ea-9811-0d9f367947f8.png)
![Screenshot from 2020-07-30 14-37-24](https://user-images.githubusercontent.com/47241114/88923564-35dcf800-d272-11ea-9e21-ae4d94a5b0c4.png)
#### Chapter 5
![Screenshot from 2020-07-30 14-36-19](https://user-images.githubusercontent.com/47241114/88923501-2067ce00-d272-11ea-9bd2-326a4cb60f59.png)
![Screenshot from 2020-07-30 14-37-58](https://user-images.githubusercontent.com/47241114/88923619-4b522200-d272-11ea-9a98-e0bc10f801a4.png)
### Algebra&Trigonometry
#### Chapter 5
![Screenshot from 2020-07-30 15-52-23](https://user-images.githubusercontent.com/47241114/88931104-aee14d00-d27c-11ea-848d-a4ae1b2da1f0.png)

**Comment by MartaSztuka** [comment]
## Failed
### 1. Unnumbered splashes
@lwtchu In chapter 4th image doesn't have class="splash unnumbered"
#### Algebra&Trigonometry
![Screenshot from 2020-07-30 16-38-08](https://user-images.githubusercontent.com/47241114/88936413-2e721a80-d283-11ea-87e7-b3bc8f150842.png)
![Screenshot from 2020-07-30 16-08-04](https://user-images.githubusercontent.com/47241114/88932843-e3ee9f00-d27e-11ea-984b-1454cdcb4926.png)
### 2. Figure caption numer is missing for figures of unnumbered splash
#### College Algebra
##### Chapter 4
![Screenshot from 2020-07-30 16-15-58](https://user-images.githubusercontent.com/47241114/88933911-4a27f180-d280-11ea-8bd3-305a8da160a4.png)
##### Chapter 5
![Screenshot from 2020-07-30 16-19-49](https://user-images.githubusercontent.com/47241114/88934126-83f8f800-d280-11ea-8e38-57140fab8529.png)
#### College Algebra coreq
##### Chapter 4
![Screenshot from 2020-07-30 16-28-30](https://user-images.githubusercontent.com/47241114/88935140-b9521580-d281-11ea-8e79-4fd995579bb0.png)
##### Chapter 5
![Screenshot from 2020-07-30 16-27-21](https://user-images.githubusercontent.com/47241114/88935100-ac352680-d281-11ea-8e75-f0960d63e186.png)

**Comment by lwtchu** [comment]
@MartaSztuka i added the class on the image for the one that is missing

**Comment by MartaSztuka** [comment]
# FAILED
## 1. Unnumbered splashes
@lwtchu In chapter 4th image doesn't have class="splash unnumbered", it's class="os-figure"
### Algebra&Trigonometry
![Screenshot from 2020-07-31 11-13-36](https://user-images.githubusercontent.com/47241114/89020363-0f28cb00-d31f-11ea-8583-43f7091dfc20.png)
![Screenshot from 2020-07-31 11-15-43](https://user-images.githubusercontent.com/47241114/89020444-32537a80-d31f-11ea-964e-5edbcb26b9ad.png)

**Comment by lwtchu** [comment]
@MartaSztuka hm..the class is on in the CNXML. i'm republishing again to see if it'll make it through.

**Comment by brittany-johnson** [comment]
@lwtchu Should this go back to testing to verify the content fix or closed?

**Comment by MartaSztuka** [comment]
@lwtchu I've fetched the book again and baked, look's the same.
![Screenshot from 2020-08-03 17-16-15](https://user-images.githubusercontent.com/47241114/89198210-2aa90580-d5ad-11ea-9d76-059069bc57c7.png)

**Comment by lwtchu** [comment]
@brittany-johnson @MartaSztuka sigh i have no idea why the content isn't going through, but if it's working for the other chapters and you both feel comfortable, i say we can close it. i rather not spend a lot of time troubleshooting the content right now.
