### ISSUE TITLE
BUG: AP Physics: Learning objectives showing up on Chapter outline section

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2534]
Book : AP Physics
Source : COPS production latest output
View : PDF

Learning objective bullet points should not appear in the chapter outline 

- PDF
![Screen Shot 2020-07-23 at 1.46.34 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/4a9d42b8-ae3b-45d7-b680-b18355ea6020)

-Webview
![Screen Shot 2020-07-23 at 1.49.02 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/7ad7d305-d3d5-4281-99ff-9fd119c83d45)

**Comment by brittweinstein** [comment]
@lwtchu what is the prio on this?

**Comment by brittweinstein** [comment]
We will come back to this when it is time to revise this title. Possibly Q2 2021.

**Comment by wilkus27** [comment]
@lwtchu What is the final decision? Learning Objectives should be or not in Chapter Outline? This change was done within this issue https://github.com/openstax/cnx-recipes/issues/1961. Here is the PR: https://github.com/openstax/cnx-recipes/pull/2437.

Should I revert those changes?

**Comment by lwtchu** [comment]
@wilkus27 priority still isn't super high as we're not revising this, but we should revert and separate them. 

The chapter outline should be a true chapter outline 
1.1 Blah blah blah
1.2 Blah blah blah

And the Learning Objectives should be the "by the end of this section you should be able to..." stuff.

Is that possible? Or would it be difficult?

Thanks!

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

**Chapter Outline**

![image](https://user-images.githubusercontent.com/40228854/108983802-88a75280-768f-11eb-86f7-9e7aa8b82489.png)

**Learning Objectives**

![image](https://user-images.githubusercontent.com/40228854/108983870-9d83e600-768f-11eb-9a33-31f843f96e1e.png)

Is it ok?

**Comment by lwtchu** [comment]
@wilkus27 yes this looks good. thank you.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-04 12-08-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ef4a3b10-9ef9-41c8-aad7-553c54a6ed9b)![Screenshot from 2021-03-04 12-08-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/467d2f2d-3e3b-48f4-a343-e2f64874209d)
