### ISSUE TITLE
BUG: AP Physics: Images might need resizing

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2535]
- Book- AP Physics
- Source - COPS output PDF
-Section 2.5

- PDF
 ![Screen Shot 2020-07-23 at 1.54.43 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/83564786-11f0-44a4-8301-dc0abd5c0c08)

-Webview
![Screen Shot 2020-07-23 at 2.01.15 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/22402094-b9a0-4cb8-a9e3-0aaad92862a9)

- Section 2.7

-PDF
![Screen Shot 2020-07-23 at 2.02.47 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/2d85cf4c-23c2-422d-b34d-bcf2c0e3a218)

- Webview
![Screen Shot 2020-07-23 at 2.03.29 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/ee773752-45de-45b0-99b6-ec00b18a22e7)

**Comment by meeragovindaraju** [comment]
Section 7.3 on the PDF
![Screen Shot 2020-07-23 at 2 13 15 PM](https://user-images.githubusercontent.com/33066187/88328892-b8a00900-ccee-11ea-9487-bca37ccb4459.png)

**Comment by lwtchu** [comment]
Content issue - will resize images when the time comes

**Comment by meeragovindaraju** [comment]
Section 11.7
![Screen Shot 2020-07-23 at 2 23 35 PM](https://user-images.githubusercontent.com/33066187/88329822-239e0f80-ccf0-11ea-8fd2-e5af67a895eb.png)

Chapter 12 conceptual questions section
![Screen Shot 2020-07-23 at 2 28 08 PM](https://user-images.githubusercontent.com/33066187/88330274-c8205180-ccf0-11ea-9e48-fbc51c5021ff.png)
