### ISSUE TITLE
BUG: AP Physics: Link for embedded phet not generated

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2536]
- Book: AP Physics
- COPS PDF

![Screen Shot 2020-07-23 at 3 40 06 PM](https://user-images.githubusercontent.com/33066187/88338974-d6756a00-ccfe-11ea-9c87-e757b4878dda.png)

Example: Missing figures (Phet sims)
11.8
13.30
13.34
16.13
16.34
16.43
20.39
21.36
21.45
22.15
22.43
22.51
23.10
23.30
23.53
25.19
26.14
29.6
29.10
29.16
30.13
30.21
30.62
31.7
31.11
31.28
32.26

**Comment by lwtchu** [comment]
High priority if we need to reprint/release this book. Low if we don't have to.

**Comment by ajluk** [comment]
@lwtchu This is an iframe nested in a figure tag: ![image](https://user-images.githubusercontent.com/55203598/107623129-2a26b100-6c59-11eb-9e6c-7624bdcdfb0f.png)
I have found that in some books we use `$Config_Coverage_MayHaveIframes: true - a config which allows us to wrap the iframes inside a `[data-type="alternatives"]` and create links which we want to display.
But for some reasons currently in AP Physics this config is set to false. But do you remember if there was a reason to have this disabled in ap physics? I couldn't found anything about it in PR with this changes.

**Comment by lwtchu** [comment]
@ajluk i don't...remember why it was disabled. I think it'll be good to just have the link there. This can be the fix - for QA testing @MartaSztuka can just check the reported locations and make sure there's a link to the feature so the user can go to the web to look at the iframe.

**Comment by MartaSztuka** [comment]
##### PASSED
Checked in all listed locations; links work as expected.![Screenshot from 2021-02-19 10-25-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/73a4ecf0-0bf1-410b-afb7-12e975e4cca7)
