### ISSUE TITLE
Implement example with title in Dev-math

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2538]
Documentation: https://github.com/openstax/cnx-recipes/issues/2209

Titles appear only in Elementary Algebra and Intermediate Algebra.

**Comment by MartaSztuka** [comment]
# PASSED
## Example with titles looks as expected.
### Elementary Algebra
![Screenshot from 2020-07-31 10-00-54](https://user-images.githubusercontent.com/47241114/89013885-f87d7680-d314-11ea-9cd0-7bc2a49c9ac8.png)
### Intermediate Algebra![Screenshot from 2020-07-31 11-50-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0ee33f7d-54bb-461e-bdc7-0ed34dc0e2f3)
