### ISSUE TITLE
Implement missing styles to Precalculus

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2540]
Add style to

- [x] Index (https://github.com/openstax/cnx-recipes/issues/2428)
- [x] Figure (https://github.com/openstax/cnx-recipes/issues/2185)
- [x] Key Terms (https://github.com/openstax/cnx-recipes/issues/2321)
- [x] Review Exercises (https://github.com/openstax/cnx-recipes/issues/2164)
- [x] Practice Test (https://github.com/openstax/cnx-recipes/issues/2164)
- [x] Answer Key (https://github.com/openstax/cnx-recipes/issues/2460)

**Comment by MartaSztuka** [comment]
**Precalculus**![Screenshot from 2020-07-28 15-37-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c9ef7266-64ac-4bbe-8bb1-92450f24c947)![Screenshot from 2020-07-28 15-41-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2134518a-8e71-4c52-8869-cf289144d017)![Screenshot from 2020-07-28 16-11-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9804c2d9-cf6a-4e79-bf4b-532868146f12)![Screenshot from 2020-07-28 16-13-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/16a94e5b-21c6-4c96-a418-7d31ccb773cc)![Screenshot from 2020-07-28 16-17-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a7f70e19-d119-4bb9-af26-e486515519c7)![Screenshot from 2020-07-28 16-18-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f97da3d9-e308-40bc-8755-1ef5f91f8a0b)
**Algebra&Trigonometry**![Screenshot from 2020-07-28 16-20-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5e993299-819e-4aae-854d-ef12332d36c8)![Screenshot from 2020-07-28 16-22-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/38df1d48-b067-4641-b121-10eb200e53cc)![Screenshot from 2020-07-28 16-23-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6a6e7916-a27f-4c04-9742-21b80ef9bf05)![Screenshot from 2020-07-28 16-24-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/50cf41ad-f09d-4946-9aea-7da3d38d54b4)![Screenshot from 2020-07-28 16-24-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/076bf541-a8b1-45a5-ad68-270180842f13)![Screenshot from 2020-07-28 17-21-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3ed3fcdb-aac0-4fe2-b489-bb726836049a) abc lists to be styled as tokens later
**College Algebra**![Screenshot from 2020-07-28 17-05-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8a279cb0-00b6-414b-8e14-53d18d599f3d)![Screenshot from 2020-07-28 17-06-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1e17fa14-d78f-41dd-b8b9-7dc601ff98ea)![Screenshot from 2020-07-28 17-07-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ecd9b22d-4264-4ccd-8d75-223097f4f009)![Screenshot from 2020-07-28 17-07-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cb00c588-dc61-4ad5-ad4f-dbc05a5b18c9)![Screenshot from 2020-07-28 17-07-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2c0ff37f-82b0-45ee-9f70-20a930bb052f)![Screenshot from 2020-07-28 17-08-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/816694e2-6299-4858-8248-038aac01da07)
