### ISSUE TITLE
Implement TOC to Calculus

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2545]
Documentation: https://github.com/openstax/cnx-recipes/issues/2060

**Comment by MartaSztuka** [comment]
# PASSED
## Table of Content
### Calculus 1![Screenshot from 2020-07-31 13-49-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/23732fea-2588-4473-9bc7-109dc7de4902)
### Calculus 2![Screenshot from 2020-07-31 13-49-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f3834c00-7ffb-4cbf-96de-952159901318)
### Calculus 3![Screenshot from 2020-07-31 13-48-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0cf712f4-460c-4e02-9d02-bd5ab2c347dd)
