### ISSUE TITLE
Implement figures and tables in Calculus

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2549]
Documentation:
- https://github.com/openstax/cnx-recipes/issues/2204
- https://github.com/openstax/cnx-recipes/issues/2185

**Comment by MartaSztuka** [comment]
# PASSED
## Figures
### Calculus 1![Screenshot from 2020-07-31 13-52-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c556d3ce-0087-4785-90cf-c30bab171ae1)
### Calculus 2![Screenshot from 2020-07-31 13-51-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d8a918c0-4a59-4fba-9471-9cae958546b7)
### Calculus 3![Screenshot from 2020-07-31 13-53-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e1138591-6287-4fdd-8246-86023e2e422c)

**Comment by MartaSztuka** [comment]
# FAILED
## Tables
@wilkus27 Table caption should have colour #093D4C, now it's black.
### Calculus 1![Screenshot from 2020-07-31 13-57-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f1cfccdc-e191-4dce-9b59-976289976cf2)
### Calculus 2![Screenshot from 2020-07-31 13-57-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b2aa0a6d-8f7e-4fbe-9cd4-dd61592edf4e)
### Calculus 3![Screenshot from 2020-07-31 13-57-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0e3ae353-4201-480a-88ca-dc111e8ae6ac)

**Comment by wilkus27** [comment]
NOTE: In Calculus in most cases text under the table is actually a table title, not caption. That's why it will be bolded.

**Comment by MartaSztuka** [comment]
# PASSED
## Condensed icon with no title note
### Calculus 1
![Screenshot from 2020-08-04 15-13-07](https://user-images.githubusercontent.com/47241114/89298001-07da2800-d665-11ea-999c-c40720c0758b.png)
### Calculus 2
![Screenshot from 2020-08-04 15-12-32](https://user-images.githubusercontent.com/47241114/89297944-f1cc6780-d664-11ea-8177-91ec8e715a1c.png)
### Calculus 3
![Screenshot from 2020-08-04 15-11-27](https://user-images.githubusercontent.com/47241114/89297868-d9f4e380-d664-11ea-870d-7de76ef44de0.png)
