### ISSUE TITLE
Implement No Class notes to Calculus

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2551]
Documentation: https://github.com/openstax/cnx-recipes/issues/2191

**Comment by MartaSztuka** [comment]
# PASSED
## No class Notes
### Calculus 1![Screenshot from 2020-07-31 14-00-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d7a0471e-9bd5-480d-b9dc-f7eeb7937475)
### Calculus 2![Screenshot from 2020-07-31 13-59-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8eae6762-9a2f-4ae2-ba3b-7876f8978805)
### Calculus 3![Screenshot from 2020-07-31 14-01-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5d24905e-db2b-48a0-97b8-f812c13aaa74)
