### ISSUE TITLE
Calculus vol1,2,3: Style Learning Objectives and Module Titles

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2552]
Related epic issue with specs:  #2557

**Comment by ajluk** [comment]
@MartaSztuka >>> Information for testing purposes: I have also add styles for module tittles within this PR, please pay attention to them as well.

**Comment by MartaSztuka** [comment]
# PASSED
## Learning Objectives
### Calculus 1![Screenshot from 2020-07-31 13-43-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6ed1969d-3fc8-4098-bba7-09b8b14a77b6)
### Calculus 2![Screenshot from 2020-07-31 13-44-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0a45a117-9834-45b0-b592-042ef653fae2)
### Calculus 3![Screenshot from 2020-07-31 13-45-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8ef410f2-419f-47b7-92dc-3d167d0f096e)
## Module titles
### Calculus 1![Screenshot from 2020-07-31 13-46-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9f450782-6db1-4f32-b95e-dae767044ff1)
### Calculus 2![Screenshot from 2020-07-31 13-46-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7a763133-08b4-4f43-a9f9-1f998b1f1b22)
### Calculus 3![Screenshot from 2020-07-31 13-47-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6c6bb31b-aac4-4c61-b49d-3017badc11a1)
