### ISSUE TITLE
corn theme/calculus - learning objectives with numbers

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2557]
In calculus the learning objectives have numbers.

Instead of the > > > icons used as bullets in #2190 please style the numbers like so:
![Screen Shot 2020-07-29 at 9 07 45 AM](https://user-images.githubusercontent.com/11299125/88810488-039c9f00-d17b-11ea-9abf-afaef70612d6.png)

font: noto sans
weight: bold
size: font-scale(0)
color: B2:   `#1E7E91`

**Comment by ajluk** [comment]
@lwtchu How it looks in the pdf file:

![image](https://user-images.githubusercontent.com/55203598/88810945-462f9d00-d1b6-11ea-8726-203b56e612e3.png)

Specs added:

![image](https://user-images.githubusercontent.com/55203598/88811056-64959880-d1b6-11ea-95b4-88c794b3217b.png)
Number:
color: #1E7E91,
font-weight: bold,
margin-right: h-spacing(1),

![image](https://user-images.githubusercontent.com/55203598/88811632-192fba00-d1b7-11ea-9ab7-877f445b80d9.png)
H3 LearningObjectivesTitle
font-family: 'Roboto Slab', serif
color:  #1E7E91,
font-size: font-scale(1),
line-height: line-height(1),
font-weight: bold,

**Comment by lwtchu** [comment]
Looks good ~
