### ISSUE TITLE
Calculus: Style Theorem Note

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2559]
Issue with specs: #2256

**Comment by MartaSztuka** [comment]
# PASSED
## Theorem Notes
### Calculus 1![Screenshot from 2020-08-05 08-47-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4c9f0643-bfb2-49da-bb5e-e534fc7ad480)
### Calculus 2![Screenshot from 2020-08-05 08-51-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3386a470-8290-46fb-ae9c-1b1f2a4940b2)
### Calculus 3![Screenshot from 2020-08-05 08-52-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/358c1091-d3d1-4b18-bb81-d83e7aa97d59)
