### ISSUE TITLE
Calculus 1,2,3: Style Problem-Solving Strategy note

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2561]
Issue with specs:
 #2256

**Comment by MartaSztuka** [comment]
# PASSED
## Problem-Solving Strategy
### Calculus 1![Screenshot from 2020-08-07 15-55-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0a706987-e3cc-48f4-9ad0-4a9c7acdf5e9)
### Calculus 2![Screenshot from 2020-08-07 15-54-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c57a4ce9-bdd9-4156-928f-412f864367cd)
### Calculus 3![Screenshot from 2020-08-07 15-54-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2caacd95-c02d-4a29-9251-b9e07c8db4f9)
