### ISSUE TITLE
Calculus 1,2,3: Style Student Project Note

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2563]
Related issue with specs: #2266

**Comment by MartaSztuka** [comment]
# PASSED
## Student Project Note
### Calculus 1![Screenshot from 2020-08-05 09-28-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9cf3ae74-cdd2-446e-9b12-79bdd8e0be83)![Screenshot from 2020-08-05 09-28-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fe00e5e6-5162-46d9-b229-dae481036bde)
### Calculus 2![Screenshot from 2020-08-05 09-29-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d29f0c0d-2ab5-44f2-a8a1-d535707e11c8)![Screenshot from 2020-08-05 09-30-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bd9ededc-3ead-4fc5-a1c2-2f22c5f12a77)
### Calculus 3![Screenshot from 2020-08-05 09-30-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4e75ed51-4ff7-422f-a975-9a697e08e579)![Screenshot from 2020-08-05 09-31-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0c7977fd-ab54-4112-99f8-5850d6c5fdea)
