### ISSUE TITLE
Implement EOC in Calculus

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2567]
- Key Terms (https://github.com/openstax/cnx-recipes/issues/2321)
- Key Concepts (https://github.com/openstax/cnx-recipes/issues/2322)
- Key Equations (there is no separate issue for this module; it contains headers and table which should be styled like in other sections)

Note: there will be separate card for Review Exercises

**Comment by wilkus27** [comment]
@lwtchu I noticed that Key Equation in Calculus is the list:

![image](https://user-images.githubusercontent.com/40228854/89181393-e6f5d200-d593-11ea-8d81-927fcc89724f.png)

Will it be changed in the content to table or should I style it in some way?

**Comment by lwtchu** [comment]
@wilkus27 i'll open a card on the content board to move them into tables

**Comment by lwtchu** [comment]
i updated hte test content for section 1.1 for calculus vol 1. for testing

**Comment by MartaSztuka** [comment]
# PASSED
## End of Chapter
### Calculus 1

**Comment by MartaSztuka** [comment]
# PASSED
## End of Chapter
### Calculus 1
![Screenshot from 2020-08-05 15-26-26](https://user-images.githubusercontent.com/47241114/89418390-47ba1180-d730-11ea-918a-f08bd3af96b5.png)
![Screenshot from 2020-08-05 15-28-21](https://user-images.githubusercontent.com/47241114/89418415-51437980-d730-11ea-943e-92f6cb47d68b.png)
### Calculus 2
![Screenshot from 2020-08-05 15-29-52](https://user-images.githubusercontent.com/47241114/89418573-894abc80-d730-11ea-91fb-19a8c7215cb0.png)
![Screenshot from 2020-08-05 15-29-38](https://user-images.githubusercontent.com/47241114/89418576-8a7be980-d730-11ea-9ad2-fc681285d649.png)
### Calculus 3
![Screenshot from 2020-08-05 16-06-01](https://user-images.githubusercontent.com/47241114/89422406-94ecb200-d735-11ea-92bf-ae4df587f08b.png)
![Screenshot from 2020-08-05 16-06-20](https://user-images.githubusercontent.com/47241114/89422430-9fa74700-d735-11ea-91f3-634852952444.png)
