### ISSUE TITLE
Calculus vol 1,2,3: Style Examples

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2569]
Documentation issue with specs: #2203

**Comment by MartaSztuka** [comment]
# PASSED
## Examples
### Calculus 1![Screenshot from 2020-08-11 14-40-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/96323166-afe1-4983-8e35-513044046f63)
### Calculus 2![Screenshot from 2020-08-11 14-50-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e854db1a-60ec-4389-81a2-5b51613542cf)
### Calculus 3![Screenshot from 2020-08-11 15-08-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8f81e413-6026-49bc-a8b7-9a62e867b882)
