### ISSUE TITLE
Calculus vol 1, 2, 3: Style media Note

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2571]
Documentation issue with specs: #2206

**Comment by MartaSztuka** [comment]
# PASSED
## Media Note
### Calculus 1![Screenshot from 2020-08-05 16-59-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fd4adfc3-1e61-4276-afdd-6d4469452654)
### Calculus 2![Screenshot from 2020-08-05 17-05-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b9db0013-c33b-41ce-a06e-296d451d6b06)
### Calculus 3![Screenshot from 2020-08-05 17-30-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dbea5483-3514-4d2b-b1a3-fa1ddd4eb90a)
