### ISSUE TITLE
Calculus vol 1,2,3: Style Preface, Index, Appendices

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2575]
Issues with specs:
Appendix and Preface:  #2320,
Index:  #2428,

**Comment by MartaSztuka** [comment]
# PASSED
## Preface
### Calculus 1![Screenshot from 2020-08-06 11-06-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c7e1f9a9-1eff-4a23-8027-de2d3fd52de8)
### Calculus 2![Screenshot from 2020-08-06 11-09-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/da421be9-82b5-447c-981b-2d13c73154c8)
### Calculus 3![Screenshot from 2020-08-06 11-12-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/05ba37ff-8064-49eb-9137-8672e0f49038)
## Index
### Calculus 1![Screenshot from 2020-08-06 11-07-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9c45f0f9-77b4-404d-8a2c-fa1753c118c9)
### Calculus 2![Screenshot from 2020-08-06 11-10-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/86caf985-63d0-4a99-9248-80f1b9a1e65f)
### Calculus 3![Screenshot from 2020-08-06 11-12-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/72fa885e-7ede-4f04-b957-4992f82bdc92)

## Appendices
### Calculus 1![Screenshot from 2020-08-06 11-08-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a1f4fb8f-7222-4fed-8b43-cfa0ea05e01e)
### Calculus 2![Screenshot from 2020-08-06 11-10-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/64f5cfbf-cf46-4539-9ba2-c7c8938629ed)
### Calculus 3![Screenshot from 2020-08-06 11-13-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4043eb33-1333-4f4c-9a8a-a29be202df68)
