### ISSUE TITLE
Implement TOC in Statistics

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2578]
Documentation: https://github.com/openstax/cnx-recipes/issues/2060

**Comment by MartaSztuka** [comment]
# PASSED
## Table of Content
### HS Statistics![Screenshot from 2020-08-06 11-58-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/509f490b-f5e4-4b0f-a9fc-f11e652cda5f)![Screenshot from 2020-08-06 11-59-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1a22f0e1-46e0-4077-bb8b-b830bbec6962)
### Introductory Business Statistics![Screenshot from 2020-08-06 12-05-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/435d52b8-c5b3-488e-b3e9-27c0a0135028)![Screenshot from 2020-08-06 12-05-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e230e4e1-20a9-4c0a-8541-e8f0b077ea26)
### Introductory Statistics![Screenshot from 2020-08-06 12-08-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7b303134-6441-46cf-be52-cdbfefb1977c)![Screenshot from 2020-08-06 12-08-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/67d75ef4-0294-48ac-8710-2ccf433ed764)
