### ISSUE TITLE
Implement titles to Statistics

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2580]
Documentation:

- regular modules, eoc (https://github.com/openstax/cnx-recipes/issues/2144)
- Preface (https://github.com/openstax/cnx-recipes/issues/2320)
- Appendix (https://github.com/openstax/cnx-recipes/issues/2320)

**Comment by MartaSztuka** [comment]
# PASSED
## Regular Modules
### HS Statistics![Screenshot from 2020-08-10 11-25-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f4c98a34-c151-4b60-b764-bea7abea38cb)
### Business Statistics![Screenshot from 2020-08-10 11-30-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f8b9d0c9-05c3-48f3-a21c-dbb04c17d970)
### Introductory Statistics![Screenshot from 2020-08-10 11-33-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/febb2e6d-9aef-4249-9716-e87f47e96fcd)

## Preface
### HS Statistics![Screenshot from 2020-08-10 11-27-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/173e5408-71f0-4dc9-9860-954479fa7631)
### Business Statistics![Screenshot from 2020-08-10 11-28-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6b6b9e0d-c4a7-475f-b367-a66ced336cf6)
### Introductory Statistics![Screenshot from 2020-08-10 11-32-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a409749c-5324-4497-b90f-a56e5b2ab8dd)

## Appendices
### HS Statistics![Screenshot from 2020-08-10 11-27-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7d10f9cb-6718-4354-a77a-1ec276bb8c60)
### Business Statistics![Screenshot from 2020-08-10 11-31-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/41cedd2c-b9d9-4bcf-a562-7384a519fc04)

**Comment by MartaSztuka** [comment]
# FAILED
## Appendices
@wilkus27 When title break in two lines there's no leading.
### HS Statistics![Screenshot from 2020-08-10 11-38-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dcb14868-8b46-4efe-8653-1be4b792ecc1)
### Business Statistics![Screenshot from 2020-08-10 11-37-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9098a265-34ab-4c62-b450-6b205a2e7388)
### Introductory Statistics![Screenshot from 2020-08-10 11-39-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5f49bc80-b9cc-4140-9eca-a428ffb002d8)

**Comment by wilkus27** [comment]
@MartaSztuka problem with titles in Appendix is already fixed. It's ready for retesting.

**Comment by MartaSztuka** [comment]
# PASSED
## Appendices Titles
### HS Statistics![Screenshot from 2020-08-17 15-06-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9065ed01-a10c-4866-9767-233436e3940d)
### Intro Statistics![Screenshot from 2020-08-17 15-08-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/28a29a1b-35fe-4dcf-898c-059535117865)
### Business Statistics![Screenshot from 2020-08-17 15-09-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7010d221-0e74-4f75-a815-2fa68af3b944)
