### ISSUE TITLE
Add unit tests to link extras bakery step

### ISSUE THREAD

**Issue by ckline-tryptic** [openstax/cnx-recipes#2582]
## Description 

We need to add unit tests for the link_extras.py step of the bakery pipeline.

## Proposed Solution 

Break the existing `link_extras` code into functions to better facilitate testing without subprocess.

## Acceptance Criteria

- [x] Add tests to verify link replacement.
- [x] Add test to verify error handling.

**Comment by brittweinstein** [comment]
As discussed in 8/25 card review, there is no testing for Otto, so we will close. When recipes is tagged next week, this should be included.
