### ISSUE TITLE
Calculus vol1, 2, 3: Style Review Exercises

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2583]
Related documentation issue with specs: #2164

**Comment by MartaSztuka** [comment]
# PASSED
## Review Exercises
### Calculus 1![Screenshot from 2020-08-07 15-59-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b6230448-3596-4610-84eb-c17a1cafe412)
### Calculus 2![Screenshot from 2020-08-07 16-01-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/715f388e-859b-4885-97a5-0cb21769b325)
### Calculus 3![Screenshot from 2020-08-07 16-02-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cd78cf93-39fb-42fe-82a6-83469d14ca02)
