### ISSUE TITLE
Calculus vol1, 2, 3: Style Answer Key

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2585]
Related issue with specs: #2460

**Comment by MartaSztuka** [comment]
# FAILED
## Answer Key
@lwtchu Answer Key should be in three column display, but two column appears randomly. Same issue as in this one: https://github.com/openstax/cnx-recipes/issues/2486 
### Calculus 1https://github.com/openstax/cnx-recipes/issues/2486
### Calculus 2![Screenshot from 2020-08-07 15-51-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/07c6015e-fcc4-46c3-8322-ccbd3db4d14f)
### Calculus 3![Screenshot from 2020-08-07 15-30-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/76bc9059-5e5c-4323-afe3-0eae1fe73673)
cc @ajluk

**Comment by lwtchu** [comment]
@MartaSztuka i think in terms of answer key testing, we can close. and keep the spontaneous two column issue to #2486
