### ISSUE TITLE
Prealgebra 2e: Regression in Answer Key

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2587]
During working on Answer Key in Calculus I have found out that there is a regression in this part in Prealgebra 2e: 

![image](https://user-images.githubusercontent.com/55203598/89411618-03297880-d726-11ea-9bb5-34068be48a2e.png)

**Comment by ajluk** [comment]
@MartaSztuka >> information for testing purposes: The Answer Key should be tested in the Prealgebra 2e, Precalculus, College Algebra Coreq.

**Comment by MartaSztuka** [comment]
# PASSED
## Answer Key
Two columns in three column layout is known issue cc @ajluk 
### Prealgebra 2e![Screenshot from 2020-08-07 16-30-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e81110c7-3792-4939-9502-5bcc76e7b3ad)
### College Algebra Coreq
![Screenshot from 2020-08-07 16-32-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/001466a8-663c-4fb9-a8eb-0eadc8ba0269)
### Precalculus![Screenshot from 2020-08-07 17-00-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1bd8b369-e233-48c1-b476-11ece703103b)
