### ISSUE TITLE
Implement Introduction to Statistics

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2588]
Documentation: https://github.com/openstax/cnx-recipes/issues/2314

**Comment by wilkus27** [comment]
@MartaSztuka Here are more informations https://github.com/openstax/cnx-recipes/issues/2314#issuecomment-669942177

**Comment by MartaSztuka** [comment]
# PASSED
## Introductions
### HS Statistics![Screenshot from 2020-08-12 10-17-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7123927a-e7dc-46eb-b1a8-9add043800d2)
### Intro Statistics![Screenshot from 2020-08-12 10-18-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0da0fef4-8da8-4e63-a109-189bd49429b3)
### Business Statistics![Screenshot from 2020-08-12 10-20-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d16e8402-c7c1-4908-82fd-898470b935fb)
