### ISSUE TITLE
Calculus vol1, 2, 3: Style Section Exercises

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2589]
Related documentation issue with specs: #2463

**Comment by MartaSztuka** [comment]
# PASSED
## Section Exercises
### Calculus 1![Screenshot from 2020-08-07 15-23-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/598cf8c1-e72a-4a7b-b05c-cbb5ea1d628b)
### Calculus 2![Screenshot from 2020-08-07 15-24-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/657e5500-7f6f-4039-bc42-a7abe6bec96e)
### Calculus 3![Screenshot from 2020-08-07 15-24-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d9013a70-e10e-4b76-8deb-9a2e3b3d5704)
