### ISSUE TITLE
[HOLDING FOR PROD] Folio needs to be tested in all Calculus & Statistics books

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2592]
This issue can be tested when work on the Introduction page will be finished in Statistics books. 

Documentation card: https://github.com/openstax/cnx-recipes/issues/2143

**Comment by brittany-johnson** [comment]
@meeragovindaraju Hello! I see that this issue has moved into the QA Testing column. Have you already begun testing? 
If so, let's wait until the issue blocking this one has passed testing. 

Thank you!

**Comment by meeragovindaraju** [comment]
@brittany-johnson Yes I did start on the testing the Calculus Vol1. But I can put this on hold until the dependency is resolved.

**Comment by meeragovindaraju** [comment]
##Calculus vol1 looks good

![Screen Shot 2020-08-12 at 4 36 04 PM](https://user-images.githubusercontent.com/33066187/90070941-55384400-dcba-11ea-8dd3-95c6d702b943.png)

**Comment by meeragovindaraju** [comment]
**Calculus vol2 looks good**

![Screen Shot 2020-08-12 at 5 07 36 PM](https://user-images.githubusercontent.com/33066187/90073260-8286f100-dcbe-11ea-8859-a4f3f9d829c7.png)

**Comment by meeragovindaraju** [comment]
**Calculus vol3 looks good**

![Screen Shot 2020-08-13 at 10 09 13 AM](https://user-images.githubusercontent.com/33066187/90152117-14d5d600-dd4d-11ea-8a37-f7f00ac6a34b.png)

**Comment by meeragovindaraju** [comment]
**HS-Stats looks good**

![Screen Shot 2020-08-13 at 10 37 48 AM](https://user-images.githubusercontent.com/33066187/90155702-3c2ea200-dd51-11ea-9c0d-944666092e4b.png)

**Comment by meeragovindaraju** [comment]
**Business-Stats looks good**

![Screen Shot 2020-08-13 at 11 15 41 AM](https://user-images.githubusercontent.com/33066187/90159667-59b23a80-dd56-11ea-8223-4152f8fcde5f.png)

**Comment by meeragovindaraju** [comment]
**Intro to Stats looks good**

![Screen Shot 2020-08-13 at 2 29 19 PM](https://user-images.githubusercontent.com/33066187/90178349-6728ee00-dd71-11ea-93b7-971c285d7f03.png)

**Comment by meeragovindaraju** [comment]
**All looks good in Staging 🎉**
