### ISSUE TITLE
Implement No Class Note in Statistics

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2595]
Documentation: https://github.com/openstax/cnx-recipes/issues/2191

**Comment by MartaSztuka** [comment]
# PASSED
## No Class Note
### HS Statistics![Screenshot from 2020-08-10 11-52-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9af11c68-d90f-4ea7-b338-ee537e4725f5)
### Introductory Statistics![Screenshot from 2020-08-10 11-50-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/77878266-62a5-4e31-bc2f-ca234f691077)
### Business Statistics![Screenshot from 2020-08-10 11-52-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ff14f6e5-609f-4554-97e5-0273696f3def)
