### ISSUE TITLE
Statiscs: Implement Example

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2601]
Issue with documentation: #2209

**Comment by MartaSztuka** [comment]
# PASSED
## Example
### HS Statistics![Screenshot from 2020-08-12 16-51-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5a5a53dc-8b6e-408c-b45d-cac6dd8d975e)
### Intro Statistics![Screenshot from 2020-08-12 16-52-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8dda2f5e-5910-4081-aab8-31fb2291278a)
### Business Statistics![Screenshot from 2020-08-12 16-53-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/14d64922-2c7e-47b8-bf32-bdb1cb601b08)
