### ISSUE TITLE
Statistics: Implements footnotes styles

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2604]
Issue with specs:  #2465

**Comment by MartaSztuka** [comment]
# PASSED
## Footnotes
### HS Statistics![Screenshot from 2020-08-17 15-13-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1cbce33f-171f-468f-b18a-3297d7f99913)
### Intro Statistics![Screenshot from 2020-08-17 15-59-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5997d946-f011-447e-aa19-76b3140b1d95)
### Business Statistics![Screenshot from 2020-08-17 15-51-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8055a44b-b33a-41eb-b540-35909247c9d1)
