### ISSUE TITLE
Statistics: style Key Terms

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2606]
Issue with specs: #2321

**Comment by ajluk** [comment]
Link to comment about content issues in Statistics books in Key Terms: https://github.com/openstax/cnx-recipes/issues/2321#issuecomment-672804331

**Comment by MartaSztuka** [comment]
# PASSED
## Key Terms
### HS Statistics![Screenshot from 2020-08-18 13-48-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ec4db147-1832-4287-8cfe-a3611fbbf5f3)
### Intro Statistics![Screenshot from 2020-08-18 13-50-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f6b5f1a6-dedb-491b-aaaf-3f371734b245)
### Business Statistics![Screenshot from 2020-08-18 13-50-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/17129d1c-28fd-4ab3-832c-8bc0ec1b08fb)
