### ISSUE TITLE
Rework lists in notes from Corn Theme

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2608]
Lists components should be moved from notes shapes in Corn Theme. We need to create separate shape for them in `lists-shapes.scss` file. 

Link to PR with conversation about it: https://github.com/openstax/cnx-recipes/pull/2599/files#r468555490

**Comment by wilkus27** [comment]
Will be resolved within https://github.com/openstax/cnx-recipes/pull/2726

**Comment by wilkus27** [comment]
Changes for this issue were merged directly to master and there it should be tested. I think the best way to do that is to check lists in different notes in a few books from Carnival Theme.

@brittweinstein Can you recommend which books should be tested?

**Comment by lwtchu** [comment]
@wilkus27 can you give me a little more detail about the change? what is the scope? does it impact all lists in all books? and what is the expected change (or is it not visible to the human eyes :joy:?)

**Comment by lwtchu** [comment]
actually alan explained it to me (thank you @Stackblocks )

can we do concentrated testing on lists within notes for the followign titles

statistics (high school)
calculus volume 2
college algebra with coreq
interediate algebra

maybe only like...1 chapter each and only concentrating on notes.

**Comment by wilkus27** [comment]
@lwtchu Sorry, I should add more details in the description :grin:  I will put it here.

Previously if someone noticed some unstyled list in note, we styled this case only in shape of this specific note, e.g iconBoxed.
Now all of those cases are moved to the separate shape for lists in notes, which is applied to all notes except three:

- with class `media-2`
- with class `media-notitle`
- with class `chapter-objectives`

First two contain unordered lists for which we remove bullets:

![image](https://user-images.githubusercontent.com/40228854/92010642-5228f480-ed4a-11ea-92bd-3678fc72ee1b.png)

Third one is styled like Learning Objectives in Statistics:

![image](https://user-images.githubusercontent.com/40228854/92010772-7c7ab200-ed4a-11ea-9e85-edd54e97e5df.png)

(NOTE: headers of these notes are fixed in another issue).

So there might be some visible changes, because notes get additional settings for some lists.

**Comment by meeragovindaraju** [comment]
@wilkus27 I have tried to locally generate the PDFs from **master** branch but the books are unstyled. I have tried hs-stats and calculus vol2. Please advise on how to proceed.

**Comment by meeragovindaraju** [comment]
Clac-vol2 looks good

![Screen Shot 2020-09-02 at 1 50 33 PM](https://user-images.githubusercontent.com/33066187/92026077-12e8ac80-ed26-11ea-8a6c-b2c82f48d2f9.png)

**Comment by meeragovindaraju** [comment]
HS Stats looks good

![Screen Shot 2020-09-02 at 2 26 37 PM](https://user-images.githubusercontent.com/33066187/92027563-57754780-ed28-11ea-851b-c4a0615612e5.png)

**Comment by meeragovindaraju** [comment]
College Algebra with coreq looks good

![Screen Shot 2020-09-02 at 3 09 57 PM](https://user-images.githubusercontent.com/33066187/92031585-6fe86080-ed2e-11ea-84b9-577146fbd852.png)

**Comment by meeragovindaraju** [comment]
Intermediate Algebra 2e looks good!

![Screen Shot 2020-09-02 at 3 55 42 PM](https://user-images.githubusercontent.com/33066187/92035755-ca84bb00-ed34-11ea-89cd-23dc635591e9.png)
