### ISSUE TITLE
Statistics: style EoC exercises

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2611]
Related documentation issue: #2612

**Comment by ajluk** [comment]
@lwtchu I have tried carnival two column design for the Practise exercises in Statistics.
The only different thing I have noticed is there are paragraphs before the exercises in some places: 

![image](https://user-images.githubusercontent.com/55203598/90140973-c9d2b780-dd7a-11ea-8b08-bb10a3375a74.png
and images: 
![image](https://user-images.githubusercontent.com/55203598/90141339-53828500-dd7b-11ea-8199-f7ea5abb0047.png)
![image](https://user-images.githubusercontent.com/55203598/90141412-64cb9180-dd7b-11ea-8d2d-7a6e1533982c.png)

I have tried to make the span through all columns and here is how it looks then: 

![image](https://user-images.githubusercontent.com/55203598/90141644-aeb47780-dd7b-11ea-9c63-e21b3cd7b561.png)
![image](https://user-images.githubusercontent.com/55203598/90141531-875daa80-dd7b-11ea-8254-723d944cfdb3.png)
![image](https://user-images.githubusercontent.com/55203598/90141584-96dcf380-dd7b-11ea-8c01-88f1e0620971.png)

**Comment by lwtchu** [comment]
Updated specs are here:  #2612  (new documentation card)

**Comment by MartaSztuka** [comment]
# PASSED
## EoC Exercises
### HS Statistics![Screenshot from 2020-08-18 14-03-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5190ff14-9cdc-48d9-bf33-db323a7040f6)![Screenshot from 2020-08-18 14-03-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a4b5654e-d1ab-46c6-90f7-821344e715e5)
### Intro Statistics![Screenshot from 2020-08-18 14-01-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2643a293-8df8-41ed-947a-fb35dc84527c)![Screenshot from 2020-08-18 14-01-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f44efd06-aed7-4750-be35-53c03f63c7dc)
### Business Statistics![Screenshot from 2020-08-18 14-02-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e6c52090-bc85-4637-9dc4-3ccb22997251)
