### ISSUE TITLE
statistics: two column formula review

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2614]
![Screen Shot 2020-08-13 at 10 17 30 AM](https://user-images.githubusercontent.com/11299125/90153189-44391280-dd4e-11ea-8f86-386b50be7463.png)

- Headers should follow regular header schema. "Formula Review" is Roboto Slab, font-scale(3): 14.25pt, B2:  `#1E7E91`
- Sub header (10.1 Two Population...) is font-scale(1): 9.9pt
- Two column layout goes down first, then to the second column
- Base font is noto sans, font-scale(0)

**Comment by ajluk** [comment]
@lwtchu this is how the Formula Review looks now: 
![image](https://user-images.githubusercontent.com/55203598/90407892-5517ba00-e0a7-11ea-83e7-fee0c95c9a72.png)

Specs added:

![image](https://user-images.githubusercontent.com/55203598/90404269-7c1fbd00-e0a2-11ea-8306-32932d248b31.png)

H2:
column-span:all;

![image](https://user-images.githubusercontent.com/55203598/90404182-51356900-e0a2-11ea-8d36-5ccbc48ecbfd.png)

Container: 
    margin-bottom: 1.4rem;
    column-count: 2;
    column-gap: 2.4rem;
    column-width: auto;

![image](https://user-images.githubusercontent.com/55203598/90407976-78426980-e0a7-11ea-9860-da487d200fca.png)

Table Container (specs aren't changed):
margin-bottom: 1.4rem;
display: table;
margin-left: auto;
margin-right: auto;

![image](https://user-images.githubusercontent.com/55203598/90408071-a031cd00-e0a7-11ea-88f7-6e883c212616.png)

Caption Container
page-break-before: avoid 
 
Let me know if I should change something?

**Comment by lwtchu** [comment]
@ajluk the math is due to content (https://github.com/openstax/content-managers/issues/1836) 

the rest looks good though. thank you.

**Comment by ajluk** [comment]
@lwtchu Thank you for clarifying. Do you want to me to create a separate issue for testing tables? Or it will be covered on content side?

**Comment by ajluk** [comment]
@lwtchu here is how the table in the Formula Review looks now:
![image](https://user-images.githubusercontent.com/55203598/91048437-fb217200-e61b-11ea-8072-d10ebba5e462.png)
and in the content: 
![image](https://user-images.githubusercontent.com/55203598/91049219-222c7380-e61d-11ea-9172-5cd875972514.png)

I have updated the specs I added above and there are properties I have added to **Caption Container** for Tables in general (no only in Formula Review):
            display: table-caption,
            caption-side: bottom,
            prince-caption-page: all,
I have also pasted info in the Caption documentation issue about it ( #2185).

**Comment by lwtchu** [comment]
@ajluk okay looks great. thank you - does  that mean the caption would display full width of the page?

**Comment by lwtchu** [comment]
@ajluk ah okay iw asn't sure what `prince-caption-page: all,` meant just wanted to check. we can look at tables when we test for 100% on the content side. i'll make a note.

**Comment by ajluk** [comment]
@lwtchu Thank you. I have added `prince-caption-page: all` to captions in tables to make them appear on the other pages within the table if the table is splitted through pages line here:
![image](https://user-images.githubusercontent.com/55203598/91057493-8d7b4300-e627-11ea-8b65-094076228247.png)

**Comment by lwtchu** [comment]
@ajluk ah okay that makes sense thank you for clarifying
