### ISSUE TITLE
Implement Formula Review to Statistics

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2617]
Documentation: https://github.com/openstax/cnx-recipes/issues/2614

**Comment by MartaSztuka** [comment]
## PASSED
### Formula review
#### HS Statistics![Screenshot from 2020-08-28 11-17-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/389d2e7d-df0a-4f75-a7e4-e2209b4aaf5e)
#### Intro Statistics![Screenshot from 2020-08-28 11-19-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fbd3809a-8141-4bcd-813a-6f5041f394fe)
#### Business Statistics![Screenshot from 2020-08-28 11-20-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1ffb141c-b717-43a7-8f74-e669a1f7ecd0)
