### ISSUE TITLE
Implement Index to Statistics

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2618]
Documentation: https://github.com/openstax/cnx-recipes/issues/2428

**Comment by MartaSztuka** [comment]
# PASSED
## Index
### HS Statistics![Screenshot from 2020-08-18 13-56-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/98ed5e2b-9a3f-451a-bd63-34c4c156e02d)
### Intro Statistics![Screenshot from 2020-08-18 13-56-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/44c3f7dd-85f5-43cc-bd1d-bfe3043593ed)
### Business Statistics![Screenshot from 2020-08-18 13-57-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f890ce34-3348-4523-b03d-a8e5ca658eb2)
