### ISSUE TITLE
corn theme: style terms

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2621]
All term tags without class `no-emphasis` should be bolded.

![image](https://user-images.githubusercontent.com/40228854/90247452-e502fd00-de36-11ea-84a2-9017a4ee1c95.png)

**Comment by lwtchu** [comment]
@wilkus27 i think it's all term tags with class `no-emphasis` should be NOT bolded ?

**Comment by wilkus27** [comment]
@lwtchu I wrote this like that because from the coding side what we do is we are adding bold to all terms except those with class `no-emphasis`.

**Comment by lwtchu** [comment]
@wilkus27 ah okay thank you for clarifying. :)

**Comment by brittweinstein** [comment]
Marta: Calc, Precalc, Stats 

Meera: Bio, Chem, Physics

**Comment by MartaSztuka** [comment]
# PASSED
## Terms
### Calculus 1![Screenshot from 2020-08-19 11-36-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/12c36c65-baa9-48f3-8cd2-0cda09a82046)
### Precalculus![Screenshot from 2020-08-19 11-38-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7d121cb9-c577-4162-bc85-06aa3e3a1e0c)
### HS Statistics![Screenshot from 2020-08-19 11-49-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bfa60a36-b5f6-454e-bacd-d70a05b72f26)

**Comment by meeragovindaraju** [comment]
![Uploading Screen Shot 2020-08-19 at 11.30.11 AM.png…]()

**Comment by meeragovindaraju** [comment]
**I think Bio failed** :(

<img width="1621" alt="Screen Shot 2020-08-19 at 12 16 26 PM" src="https://user-images.githubusercontent.com/33066187/90668551-dd1bd200-e215-11ea-9890-f7702f0b5f79.png">

**Comment by meeragovindaraju** [comment]
Looks like Bio2e and College physics do not have the class = no.emphasis. Confirmed this with Larissa. Is there any other titles I should test? I am currently generating microbio pdf locally to test

**Comment by meeragovindaraju** [comment]
**Microbio looks good**

<img width="1619" alt="Screen Shot 2020-08-19 at 2 55 42 PM" src="https://user-images.githubusercontent.com/33066187/90683431-2545ef00-e22c-11ea-97a1-0cae978bed30.png">

**Comment by wilkus27** [comment]
Class `no-emphasis` is added in the content. No additional coding work is needed here, so I think we can close this issue. I guess we need to create new issue about missing class in `content-manager` repo. @lwtchu do you think we should test more or all books as @meeragovindaraju suggested, to check which of them don't have class `no-empasis`?

**Comment by MartaSztuka** [comment]
# EDIT
## Terms with `no-emphasis` class
There are terms with no-emphasis class in those books; are not bold.
### Precalculus
![Screenshot from 2020-08-20 10-05-26](https://user-images.githubusercontent.com/47241114/90733613-16fbdf80-e2cd-11ea-8252-251d20161aae.png)
### Calculus 1
![Screenshot from 2020-08-20 10-14-06](https://user-images.githubusercontent.com/47241114/90736051-e8323900-e2cd-11ea-8a91-eb8be6b79299.png)

## In Statistisc I did not find 'no-emphasis' class
### HS Statistics
![Screenshot from 2020-08-20 10-21-59](https://user-images.githubusercontent.com/47241114/90739677-02204b80-e2cf-11ea-9f4d-6d57970f360b.png)
