### ISSUE TITLE
Implement Solutions to Statistics

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2625]
Documentation: #2632

**Comment by MartaSztuka** [comment]
# PASSED
## Solutions
### HS Statistics![Screenshot from 2020-08-20 15-17-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/da21f61c-9c6a-48e1-88cf-6921e9446b07)
### Intro Statistics![Screenshot from 2020-08-20 15-30-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5ad7217b-274c-4cbf-be03-93ddb1a90045)
### Business Statistics![Screenshot from 2020-08-20 15-42-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b94c82f7-334d-418f-bb5b-7326b396c16c)
