### ISSUE TITLE
Add better debugging output for missing canonical case to link-extras

### ISSUE THREAD

**Issue by ckline-tryptic** [openstax/cnx-recipes#2628]
# Description
If there are missing a canonical book, we need to know the books that contain the module we are looking for.

# Acceptance Criteria
- [x] Output containing book list on missing canonical exception.

**Comment by rnathuji** [comment]
This was the output found in Concourse for `col28330 ` using tag `20200819.213932`:

```
+ exec
++ tee linked-extras/stderr
+ cp -r assembled-book/col28330 assembled-book/stderr linked-extras
+ cd linked-extras
++ cat ../book/collection_id
+ book_dir=./col28330
+ link-extras ./col28330 archive.cnx.org /code/scripts/canonical-book-list.json
Traceback (most recent call last):
  File "/usr/local/bin/link-extras", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/bakery_scripts/link_extras.py", line 115, in main
    match = match_canonical_book(canonical_ids, containing_books)
  File "/usr/local/lib/python3.7/site-packages/bakery_scripts/link_extras.py", line 72, in match_canonical_book
    match = next(uuid for uuid in canonical_ids if uuid in containing_books)
StopIteration
```

This seems the same as the [earlier pipeline](https://concourse-v6.openstax.org/teams/CE/pipelines/webhost-qa-20200811.223338/jobs/bakery/builds/47)?

**Comment by brittweinstein** [comment]
We will close this and open a new card for the extra case discussed in today's card review.
