### ISSUE TITLE
corn theme: aligning exercises with tall math in multi column layout

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2629]
![Screen Shot 2020-08-13 at 11 10 52 AM](https://user-images.githubusercontent.com/11299125/90423990-02c4a200-e083-11ea-896b-5a5250bfca73.png)

We increased the math size. Can we please have the numbers for each exercise align to the middle of the line height set by the new increase math size if there's a fraction? 

Let me know if there's any questions. This content is from College Algebra/College Algebra with Coreq. However, you can probably find instances in the dev math or precal trio.

**Comment by wilkus27** [comment]
@lwtchu I looked into it and I'm afraid it's impossible to align exercises in this way. Problem is that exercises are independent of each other, so height of the one exercise don't have an impact on height of another exercise.


@brittany-johnson @Stackblocks I have one idea how it could be resolved. Maybe we can put each three exercises in one container div or section with some class, something like that:

```
<section class="some-class">
  <div data-type="exercise"></div>
  <div data-type="exercise"></div>
  <div data-type="exercise"></div>
</section>
<section class="some-class">
  <div data-type="exercise"></div>
  <div data-type="exercise"></div>
  <div data-type="exercise"></div>
</section>
```
and then set `display: flex` or `display: table` to section , not sure what would be better. Generally it should be easier to align these three siblings in one line.

But, I see a few problems:

1. Where to create sections/divs? In the content or by recipes?
Probably it would be safer to do it by recipe in the last pass, but I'm not sure if we can do it using sass. 

2. We need such markup to style PDFs. It might have huge impact on webview, where exercises are not in columns.

3. I'm not 100% sure that putting three exercises in one parent container will help. Exercises start with paragraphs, equations, tables, figures, paragraphs with equations inside. It might be hard to fix all instances.

What do you recommend? Do you have any other ideas how we can handle this?

**Comment by lwtchu** [comment]
@wilkus27 hmm let's park this tomorrow for the call. i can join

**Comment by wilkus27** [comment]
@meeragovindaraju It should work now. Applied changes could have a huge impact on all types of exercises, that's why we decided it should be tested on feature branch `exercises-alignment`. 

Please check:
- three columns exercises
- two columns exercises
- one column exercises
- answer key
- solutions (EOC module from Statistics)

**Comment by meeragovindaraju** [comment]
- College-algebra

Three column exercise

![Screen Shot 2020-09-10 at 9 59 26 AM](https://user-images.githubusercontent.com/33066187/92750477-b4868400-f34c-11ea-9316-6933c867cbcb.png)


Mid chapter example

![Screen Shot 2020-09-10 at 10 03 44 AM](https://user-images.githubusercontent.com/33066187/92750697-f44d6b80-f34c-11ea-809d-abc4f770de83.png)

Answer Key

![Screen Shot 2020-09-10 at 10 14 32 AM](https://user-images.githubusercontent.com/33066187/92752332-75f1c900-f34e-11ea-8b0d-535b224d0fdf.png)

- PreAlgebra

![Screen Shot 2020-09-10 at 10 59 11 AM](https://user-images.githubusercontent.com/33066187/92758774-b0f6fb00-f354-11ea-9889-0cb7926553b3.png)

![Screen Shot 2020-09-10 at 11 00 32 AM](https://user-images.githubusercontent.com/33066187/92758961-ddab1280-f354-11ea-8ab1-a460bc6f684c.png)

Answer Key

![Screen Shot 2020-09-10 at 12 30 09 PM](https://user-images.githubusercontent.com/33066187/92772504-692aa080-f361-11ea-9278-38b7bf4938af.png)

**Comment by meeragovindaraju** [comment]
College Algebra with coreq Chapter 7 Exercises

![Screen Shot 2020-09-10 at 1 14 55 PM](https://user-images.githubusercontent.com/33066187/92779524-bdd11a00-f367-11ea-94b8-8bc4386c7d13.png)


Answer key

![Screen Shot 2020-09-10 at 1 19 08 PM](https://user-images.githubusercontent.com/33066187/92780090-3f28ac80-f368-11ea-88c6-164d55d0b342.png)

![Screen Shot 2020-09-10 at 1 16 59 PM](https://user-images.githubusercontent.com/33066187/92779774-f7a22080-f367-11ea-8d59-81dbd640cb21.png)

**Comment by meeragovindaraju** [comment]
Intro to stats Solutions section

![Screen Shot 2020-09-10 at 2 00 37 PM](https://user-images.githubusercontent.com/33066187/92786694-13a8c080-f36e-11ea-8dd4-60a1a8251aeb.png)

**Comment by meeragovindaraju** [comment]
@lwtchu can you take a look at the screenshots and sign off on this issue please.

**Comment by meeragovindaraju** [comment]
Numbers are not zigzag so it is good to go 👍
