### ISSUE TITLE
corn theme: introduction module page breaks

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2633]
![Screen Shot 2020-08-17 at 3 53 03 PM](https://user-images.githubusercontent.com/11299125/90443366-c05e8d80-e0a1-11ea-81bc-0c9d5ff164ef.png)
The splash image is as small as it will go - is there a way we can implement page breaks in the pdf for the introduction module?

I think it's been done before in oer.exports but I'm not sure if this is a new limitation. Happens in chapter 7 as well for College Algebra/College Algebra with Coreq

Probably impacts all books in corn theme.

**Comment by lwtchu** [comment]
talked to @brittany-johnson - this is probably library wide.

**Comment by brittany-johnson** [comment]
@lwtchu What collection is the screenshot from? I just generated from `col10002` on content01 but I didn't see an example of the weird break

**Comment by lwtchu** [comment]
going to generate a few more pdfs to verify 😬

**Comment by lwtchu** [comment]
![Screen Shot 2020-08-18 at 4 10 32 PM](https://user-images.githubusercontent.com/11299125/90566007-61fee100-e16d-11ea-84c7-084a7ba2f66d.png)
![Screen Shot 2020-08-18 at 4 11 15 PM](https://user-images.githubusercontent.com/11299125/90566054-75aa4780-e16d-11ea-928f-4436cb0368af.png)

corn (college alg with prod data) and carnival (microbio) ...looks like it's no longer an issue LOL so whatever you did??before?? was cool.
