### ISSUE TITLE
corn theme: list cell alignments should be content driven

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2637]
![Screen Shot 2020-08-18 at 8 54 49 AM](https://user-images.githubusercontent.com/11299125/90521856-a0c27600-e130-11ea-88bd-f0d11c35b570.png)
![Screen Shot 2020-08-18 at 8 54 38 AM](https://user-images.githubusercontent.com/11299125/90521860-a15b0c80-e130-11ea-94cb-93f74c230f86.png)

Text in screenshot above should not be centered. I think the default alignment for the tables are overriding the content.

[Options available in the content:](https://legacy-content01.cnx.org/eip-help/tgroup)
left - Left aligned.
right - Right aligned.
center - Center aligned.
(char and justify are also available on the list but i don't think we use them often)

this was found in college algebra with coreq however - this should be library wide.

The default can be left to center, however we need `align="left/right/center"` to be able to override.

**Comment by wilkus27** [comment]
@lwtchu I created PR for this, but as I checked on katalyst01 table from the screenshot doesn't have any attribute. Probably new content should be migrated before we start testing it. Generally after transformation from xml to xhtml name of attribute is e.g. `[data-align="left"]`.

Beside that I noticed that sometimes tables have improper attributes. For example:

**College Algebra coreq module 1.1 Example 5**
Lists should be aligned to the left.
![image](https://user-images.githubusercontent.com/40228854/90631832-b369a780-e223-11ea-90a6-fc6ca5048490.png)

**Intermediate Algebra 2e module 1.1 first table**
Numbers should be centered, not aligned to the left
![image](https://user-images.githubusercontent.com/40228854/90632072-18bd9880-e224-11ea-8cab-161ce84d8fae.png)

So I think a lots of testing and content changes will be needed. Maybe we should discuss some test plan for this problem.

**Comment by lwtchu** [comment]
i migrated chapter one - the first large table in there should have left alignment on all the cells with text.

**Comment by MartaSztuka** [comment]
# PASSED
## List Cell Alignments
### College Algebra coreq![Screenshot from 2020-08-21 10-15-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/feaebfde-114e-49ce-b350-528938d29bd5)![Screenshot from 2020-08-21 10-19-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/06636724-c6c0-4cb2-af1b-f7dbf697dfcd)![Screenshot from 2020-08-21 10-18-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2653cf16-4d02-4e97-b16e-42a1309865a0)
