### ISSUE TITLE
coreq math: nested lists not styled in EOC 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2639]
can we move the bullet points within the margins and can we also have these styled like the paragraphs (italicized, blue)

![Screen Shot 2020-08-18 at 9 07 37 AM](https://user-images.githubusercontent.com/11299125/90523330-5d690700-e132-11ea-9b73-00bb540a0159.png)

location: chapter 9

**Comment by MartaSztuka** [comment]
# PASSED
## Nested lists in EoC
### College Algebra coreq![Screenshot from 2020-08-24 10-03-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7e8a0eab-f915-43b1-bba6-5a47b5482fa5)
