### ISSUE TITLE
cardboard theme: headers (includes appendix and preface)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2644]
# Preface/Appendix

## H1 (Title)
font-size: font-scale(3): 15.55pt, 20.4px, 1.7rem
font style: Dosis for Astronomy; Roboto Condensed for everything else
color: P2: `#772949` for Astronomy; B4: `#24739E` for everything else

## Appendix number/letter
![Screen Shot 2020-08-19 at 1 43 49 PM](https://user-images.githubusercontent.com/11299125/90676738-09d5e680-e222-11ea-9594-9d2a8ead94b7.png)

![Screen Shot 2020-08-20 at 3 59 10 PM](https://user-images.githubusercontent.com/11299125/90825212-34956d00-e2fe-11ea-9687-060a4e2a7a35.png)

font-size: font-scale(3): 15.55pt, 20.4px, 1.7rem
font style: Dosis for Astronomy; Roboto Condensed for everything else
box color: Y1: `#E3A354` for Astronomy; B2: `#344456` for everything else
font color: P2: `#772949` for Astronomy; B4: `#24739E` for everything else

## H2
font-size: font-scale(2): 12.96pt, 16.8px, 1.4rem
font style: Noto Sans
font-weight: bold
color: P2: `#772949` for Astronomy; B4: `#24739E` for everything else

## H3
font size: font-scale(1): 10.8pt, 14.4px, 1.2rem
font style: Noto Sans
font-weight: bold
color: P2: `#772949` for Astronomy; B4: `#24739E` for everything else

## H4
font size: font-scale(0): 9pt, 12px, 1rem
font style: Noto Sans
font-weight: bold
color: P2: `#772949` for Astronomy; B4: `#24739E` for everything else

## H5
font style: Noto Sans
font-weight: bold
color: black `#000000`
font size: font-scale(0): 9pt, 12px, 1rem

## Base font
font size: font-scale(0): 9pt, 12px, 1rem
color: black `#000000`
font style: Noto Sans

**Comment by wilkus27** [comment]
@andymuddimer Here is how it looks with styles:

#### - Preface

![image](https://user-images.githubusercontent.com/40228854/94808573-9d89fd80-03f1-11eb-8be8-736fd2b70280.png)

#### - Appendix

![image](https://user-images.githubusercontent.com/40228854/94808637-b4c8eb00-03f1-11eb-8997-af63c53f86f0.png)

Here are also additional specs which I applied to this title:

- Text "Appendix"
```
  display: none;
```
- Text of the title
```
  padding-left: 16px;
```

- Title number
```
  border-width: 0.2rem;
  padding: 0.5rem;
  width: 2.8rem;
  height: 2.8rem;
```

Is it ok? Should I change something?

**Comment by lwtchu** [comment]
@wilkus27 for the h1 can it not be bold?

**Comment by wilkus27** [comment]
@lwtchu This is how it looks without bold:

![image](https://user-images.githubusercontent.com/40228854/95181312-6a65b680-07c3-11eb-86b1-7073a9eafc53.png)

![image](https://user-images.githubusercontent.com/40228854/95181378-7e111d00-07c3-11eb-9b37-42db787d12ec.png)

**Comment by lwtchu** [comment]
@wilkus27 looks good thanks!
