### ISSUE TITLE
Test College Algebra

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2648]
# Testing Info: 

college algebra - content01 col10002 - precal recipe

- **Book(s)**:
- **URL/Server**: 
- **Location (page number, chapter/section)**:
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots

(_attach here (please clearly label what environment each screenshot came from)_)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by meeragovindaraju** [comment]
Testing Done. Created the following issues.
COPS pdf content01 College Algebra with coreq - precalc style

https://github.com/openstax/cnx-recipes/issues/2709
https://github.com/openstax/content-managers/issues/1860
https://github.com/openstax/cnx-recipes/issues/2688
