### ISSUE TITLE
Test Calculus Volume 2 at 80% 

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2650]
# Testing Info

calculus volume 2 - production - calculus recipe

**Comment by MartaSztuka** [comment]
# Tests results
### Example Analysis is unstyled https://github.com/openstax/cnx-recipes/issues/2668
### Key Concepts lists isn't consistent https://github.com/openstax/cnx-recipes/issues/2669
### Chapter title drops down when image is shorter. https://github.com/openstax/cnx-recipes/issues/2670
### Long equations in Section Exercises (column overlap) https://github.com/openstax/cnx-recipes/issues/2671
