### ISSUE TITLE
Test High School Statistics at 80% (just spot checks)

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2652]
#Testing Instructions 

Spot checks onlyl of hs stats - production - statistics recipe

**Comment by MartaSztuka** [comment]
## Tests results
### Captions above table (table wide)  https://github.com/openstax/cnx-recipes/issues/2672
### Chapter Objective lists should be inline with line above not with bullet point. https://github.com/openstax/cnx-recipes/issues/2673
### Figure 3.9 is extending outside the page https://github.com/openstax/cnx-recipes/issues/2674
### Solution in Example is unstyled https://github.com/openstax/cnx-recipes/issues/2675
### Missing space before (Person....) https://github.com/openstax/cnx-recipes/issues/2676
### Header is unstyled https://github.com/openstax/cnx-recipes/issues/2677
### Bullet stick out https://github.com/openstax/cnx-recipes/issues/2678
### Example is too close to the header above https://github.com/openstax/cnx-recipes/issues/2679
### Key terms overlap bullet points https://github.com/openstax/cnx-recipes/issues/2680
### Images in Appendix is blurred https://github.com/openstax/cnx-recipes/issues/2681
