### ISSUE TITLE
cardboard theme: chapter outline & introduction

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2655]
![Screen Shot 2020-08-20 at 3 57 49 PM](https://user-images.githubusercontent.com/11299125/90825013-ef713b00-e2fd-11ea-9e75-ddac63bf5c02.png)
![Screen Shot 2020-08-20 at 3 57 40 PM](https://user-images.githubusercontent.com/11299125/90825017-f0a26800-e2fd-11ea-9f8f-d5d2342749e0.png)

### Chapter Outline text
font style: Dosis for Astronomy, Roboto Condensed for everything else
font size:  font-scale(3): 15.55pt, 20.4px, 1.7rem
color: P2: `#772949` for Astronomy, B2: `#344456` for everything else

### Module links/text 
font style: noto sans
font size: font-scale(0)
module title style: normal
module title color: `#000000`
number style: bold, 
number color: default link color for entire library

### Bar next to chapter module titles
Line next to chapter contents
width: 0.2727rem (3px)
color: G2: `#F2F2F2`
padding between line and module: 0.5rem

^ Same as TOC

### Introduction 
Icon: Business - https://drive.google.com/file/d/16nxeqHi64Axd8mYzt-qCpXh2J1XUkaXL/view?usp=sharing;
Astronomy - https://drive.google.com/file/d/1C4fs6R-cP0UwIMnp7WrakCwlBjsWOc4d/view?usp=sharing
font style: Dosis for Astronomy, Roboto Condensed for everything else
font-scale(3): 15.55pt, 20.4px, 1.7rem
color: P2: `#772949` for Astronomy, B2: `#344456` for everything else

The icon is the same as corn theme - do we want to try??? for the svg icon #1272

**Comment by ajluk** [comment]
@lwtchu In Introduction to Business and Principles to management there is no Chapter Outline but Learning Outcomes at the start of the Chapter. I have checked and the same content/recipes is on `katalyst01` 
![image](https://user-images.githubusercontent.com/55203598/99248597-0219e400-2809-11eb-9b75-bb4609023d84.png)
I assumed that is desirable, but asking just to be sure.

**Comment by lwtchu** [comment]
@ajluk this is intended. on the card it says it'll be learning outcomes for these titles #2982

**Comment by ajluk** [comment]
@lwtchu Could you add icon for Introduction for Astronomy?

**Comment by lwtchu** [comment]
@ajluk apologies! it's here: https://drive.google.com/file/d/1C4fs6R-cP0UwIMnp7WrakCwlBjsWOc4d/view?usp=sharing i uploaded it without adding the link 🤦‍♀️

**Comment by ajluk** [comment]
@lwtchu I have meant this icon: 
![image](https://user-images.githubusercontent.com/55203598/101956898-af153000-3c00-11eb-8248-5e9f28096a74.png) :smile:

**Comment by lwtchu** [comment]
@ajluk oops my bad! https://drive.google.com/file/d/1XxLXfokhsbYJBoun-9a7YkIe5wxkbybY/view?usp=sharing here you are~

**Comment by brittweinstein** [comment]
@ajluk  can this be closed since 3208 has been merged?
