### ISSUE TITLE
Stats - The numbers should be bold, black, no underline and the question is in line with the number 

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2656]
- The numbers should be bold, black, no underline and the question is in line with the number 
- This is seen throughout the textbook.
- COPS PDF ( Production)

**Business Stats**

![Screen Shot 2020-08-20 at 4 51 22 PM](https://user-images.githubusercontent.com/33066187/90829784-087dea00-e306-11ea-8c9b-d40646630660.png)

**Intro Stats**

![Screen Shot 2020-08-21 at 12 44 20 PM](https://user-images.githubusercontent.com/33066187/90919513-33227e00-e3ac-11ea-90e4-9fe884458548.png)

**Comment by wilkus27** [comment]
It's already styled on r.r branch:

![image](https://user-images.githubusercontent.com/40228854/91028798-42990580-e5fe-11ea-9fe3-ddc303f2c677.png)

![image](https://user-images.githubusercontent.com/40228854/91028924-6c522c80-e5fe-11ea-8af1-35e6c1c05fe5.png)
