### ISSUE TITLE
Business stats - Table and figure numbers are inconsistent 

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2658]
Business Stas - COPS - Production

![Screen Shot 2020-08-20 at 5.03.09 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/ed2709e0-507d-4f50-844a-e6fae2fccee9)

**Comment by wilkus27** [comment]
@meeragovindaraju saying that numbers are inconsistent you meant that table has number `2.10` and figure `2.4`? If yes, it's ok, tables and figures are numbered separately.

**Comment by lwtchu** [comment]
checked through a few books, table caption/number alignment is on the center of the image if there's no caption and left aligned to the table for a table. is that correct for most books @wilkus27 ?

**Comment by wilkus27** [comment]
@lwtchu Yes, that's right. In this case should I close this issue?

**Comment by lwtchu** [comment]
@wilkus27 i can close. thanks for clarifying
