### ISSUE TITLE
The total is repeated twice. It should be within the table. 

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2659]
The total is repeated twice. It should be within the table. 
Chapter 1 Practice section

**PDF**

![Screen Shot 2020-08-21 at 12.49.52 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/3d617079-4cb3-4204-8737-3fa7fc018b60)

**Webview**

![Screen Shot 2020-08-21 at 12.52.44 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/50c7fc6e-703b-4b0f-993f-71777380f1f4)

**Comment by wilkus27** [comment]
@lwtchu "Total = 273" is placed in tfoot:

![image](https://user-images.githubusercontent.com/40228854/91050837-87816400-e61f-11ea-9535-ef2953cb7bf1.png)

Should this part of table be styled differently or like tbody?

**Comment by lwtchu** [comment]
@wilkus27 i can move this one instance in the content

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1846](https://github.com/openstax/content-managers/issues/1846) via [**ZenHub**](https://www.zenhub.com/)
