### ISSUE TITLE
Solution 1 Solution 2 and Interpretation of Results are big

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2660]
Intro to stats
COPS PDF Production
Section 3.2

**PDF**

![Screen Shot 2020-08-21 at 1.17.02 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/ea4e38f3-3458-4064-979d-bc44b8a687c6)

**Webview**

![Screen Shot 2020-08-21 at 1.19.23 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/b62ccf7e-5c7c-41d5-a161-fba155bd7a50)

**Comment by wilkus27** [comment]
@lwtchu How those subtitles should be styled? Should they have any icons before like Solution and Analysis here https://github.com/openstax/cnx-recipes/issues/2209 ?

**Comment by lwtchu** [comment]
@wilkus27 yes please - use the solution and analysis icons please :)

**Comment by wilkus27** [comment]
@lwtchu In this case content change is needed. Here is proper markup from College Algebra:

![image](https://user-images.githubusercontent.com/40228854/91054112-fc569d00-e623-11ea-8ea4-f52b1fcdf0f9.png)

This is how it looks in Statistics:

![image](https://user-images.githubusercontent.com/40228854/91054997-55263580-e624-11ea-86bf-ec1759ab7fc8.png)

**Comment by lwtchu** [comment]
@wilkus27 i edited that example with the exercise, problem, solution, commentary set up on katalyst01. if things go well, i'll open a card for the content managers to make the change

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/91150789-2314e200-e6bd-11ea-8b71-8296433c9be2.png)

At this moment titles of solution and commentary are defined by recipe. So those created in the content can be removed.

1. Do you want me to add by recipe numbering to solution titles which reset within example?
I noticed that in other examples there are a lot of solutions:

![image](https://user-images.githubusercontent.com/40228854/91151457-f6ad9580-e6bd-11ea-93cc-af64e4222ab4.png)

2. Do you think it would be better to modify recipe to use commentary title created in the content? In other books commentary title was always **Analysis**. Here is **Interpretation of Results**. Is it the same for whole book or Statistics has different commentary titles?

**Comment by lwtchu** [comment]
@ajluk @wilkus27 i should've parked this today - but can we park this on thursday along with #2675....i think there's a lot of parts and i wanna make sure we're all on the same page

**Comment by wilkus27** [comment]
@lwtchu I will park this today. Also I have found that in Statistics there are other titles then "Solution" and "Interpretation of results" in Examples:

![image](https://user-images.githubusercontent.com/40228854/91855616-b6be5380-ec65-11ea-8537-e581086d8588.png)

**Comment by wilkus27** [comment]
@lwtchu Here are decisions from the call:

1. Solutions should be put into div with `[data-type="solution"]`. 
2. Title "Solution" will be created by the recipe (as it is done now) but we will also add numbering to it. If there is just one solution in the example it should have class `unnumbered` added in the content.
3. All parts which contain other subtitles should be put into `[data-type="commentary"]`. We will change recipe to use titles created in the content. (e.g "Random variable" and "Graph" from the screenshot in previous comment).

**Comment by lwtchu** [comment]
for testing:
Here aare the examples I tweaked on katalyst01 section 3.2
- 2 solution types + commentary: "In a particular college class, 60% of the students are female. Fifty percent of all students in the class have long hair."
- 2 problem + 2 solutions: "Let event G = taking a math class."
- unnumbered class on 1 solution: "Flip two fair coins. Find the probabilities of the events."

let me know if it's working as intended for you. if all is good i can open a card for the content managers to work on. it will probably take a while since there's a lot across teh 3 titles.

**Comment by wilkus27** [comment]
@lwtchu Here is how it looks now:

1. 
![image](https://user-images.githubusercontent.com/40228854/92583632-e9360500-f292-11ea-95ba-eb4c2d1d9ee4.png)

2.
![image](https://user-images.githubusercontent.com/40228854/92583738-14205900-f293-11ea-9e80-c41b52302e12.png)

3. 
![image](https://user-images.githubusercontent.com/40228854/92583792-24383880-f293-11ea-90a9-a91089f92884.png)

Is it ok?

**Comment by lwtchu** [comment]
@wilkus27 i think this is fine for now 🤔 if we need to make tweaks as we go on standardizing the content, i'll open another card but i think this will help with most of the instances

**Comment by meeragovindaraju** [comment]
Sections with multiple solutions look good now 

![Screen Shot 2020-09-11 at 11 53 35 AM](https://user-images.githubusercontent.com/33066187/92952849-46ae8b00-f426-11ea-8874-c1d9eea9c320.png)


![Screen Shot 2020-09-11 at 11 59 14 AM](https://user-images.githubusercontent.com/33066187/92952861-4b733f00-f426-11ea-8c71-a547bd8e34f7.png)

**Comment by meeragovindaraju** [comment]
Looks good here as well!

![Screen Shot 2020-09-11 at 12 19 53 PM](https://user-images.githubusercontent.com/33066187/92954562-406dde00-f429-11ea-8602-35a50e592d73.png)


![Screen Shot 2020-09-11 at 12 20 29 PM](https://user-images.githubusercontent.com/33066187/92954574-4794ec00-f429-11ea-912b-5c4befeb4ce8.png)
