### ISSUE TITLE
List needs to be in line with the rest of the text

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2662]
COPS pdf production
Chapter 9 homework section

![Screen Shot 2020-08-21 at 2.35.39 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/c82cc3b7-3460-4d37-b2fa-f531389b3160)

**Comment by wilkus27** [comment]
It's already fixed on r.r branch:

![image](https://user-images.githubusercontent.com/40228854/91022438-80ddf700-e5f5-11ea-94df-1eff94764332.png)

![image](https://user-images.githubusercontent.com/40228854/91022537-a3701000-e5f5-11ea-9081-cc586c63ef93.png)
