### ISSUE TITLE
First table needs to be centered

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2663]
COPS production PDF section 11.3

![Screen Shot 2020-08-21 at 2.45.08 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/7e10703c-7583-4766-8513-ab8bee69706e)

**Comment by ajluk** [comment]
@meeragovindaraju This issue will be resolved within this PR: #2626.

**Comment by lwtchu** [comment]
since it's a dupe and will be addressed. closing
