### ISSUE TITLE
EOB section titles overlapping

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2664]
The section title is overlapping with the text. 

COPS production pdf 

Review exercises section A & B

![Screen Shot 2020-08-21 at 3.00.54 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/050ec408-019a-4360-a8ce-b53cca5d54e8)

![Screen Shot 2020-08-21 at 2.56.59 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/da530d78-f4b8-4b59-9647-31ae5d1e95a2)

![Screen Shot 2020-08-21 at 3.02.28 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/ad1d6a93-ef86-4f65-818c-a8e79261d082)

![Screen Shot 2020-08-21 at 3.02.54 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/d1e18d3a-ca2e-4993-8e57-093882316ed5)

![Screen Shot 2020-08-21 at 3.03.32 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/11ef8029-f6ce-4f2d-96dc-6933dabb961b)

![Screen Shot 2020-08-21 at 3.03.52 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/16dd3d2c-54e3-47f2-aa40-102ecca0becf)

![Screen Shot 2020-08-21 at 3.04.27 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/530aca0c-62c1-49c3-9dd3-a4e82cdb2a12)

![Screen Shot 2020-08-21 at 3.05.02 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/da377a0d-772f-4253-a538-298bf64dabf2)

**Comment by wilkus27** [comment]
It's already fixed on r.r branch:

![image](https://user-images.githubusercontent.com/40228854/91021915-bd5d2300-e5f4-11ea-9acf-5ccfb960d417.png)

![image](https://user-images.githubusercontent.com/40228854/91021959-cd750280-e5f4-11ea-9326-d6706b1f158c.png)
