### ISSUE TITLE
Space needed between Index and Symbols

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2665]
COPS production PDF 

![Screen Shot 2020-08-21 at 3.06.22 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/59911908-1037-45f2-820f-2343737d88e2)

**Comment by wilkus27** [comment]
It's already styled on r.r branch:

![image](https://user-images.githubusercontent.com/40228854/91021582-445dcb80-e5f4-11ea-8ba5-3d2c7927acd8.png)
