### ISSUE TITLE
Calculus 2 - Example Analysis is unstyled

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2668]
## Analysis in Example is not styled in most cases (it is styled properly only in first three examples only).
![Screenshot from 2020-08-24 11-51-31](https://user-images.githubusercontent.com/47241114/91030951-2d24db00-e600-11ea-87cd-74623d263795.png)

**Comment by lwtchu** [comment]
content issue. moving

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1852](https://github.com/openstax/content-managers/issues/1852) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wilkus27** [comment]
Actually recipe change is also needed, so I reopened the issue :wink:

**Comment by MartaSztuka** [comment]
# PASSED
## Example, Analysis
![Screenshot from 2020-08-26 15-29-48](https://user-images.githubusercontent.com/47241114/91309609-140f5c00-e7b1-11ea-954c-da5c999c701c.png)
