### ISSUE TITLE
Calculus 2 - Key Concepts lists isn't consistent

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2669]
## There are three types of lists; bullets, numbers and roman numerals, is that necessary?  ![Screenshot from 2020-08-24 11-15-00](https://user-images.githubusercontent.com/47241114/91026542-2ba4e400-e5fb-11ea-939c-9df447261c88.png)
![Screenshot from 2020-08-24 11-34-48](https://user-images.githubusercontent.com/47241114/91028674-19787500-e5fe-11ea-9421-885e82e2586b.png)

**Comment by lwtchu** [comment]
can we make sure lists with nested lists are supported? be it bullet, numeral, alpha, roman numerals, etc?

**Comment by ajluk** [comment]
I have added support for nested `ol` lists in tha shape is used by Key Concepts:
![image](https://user-images.githubusercontent.com/55203598/91174688-ead2cb00-e6df-11ea-8f8d-0cfa3efdcf75.png)
![image](https://user-images.githubusercontent.com/55203598/91174695-edcdbb80-e6df-11ea-8612-3804595f632a.png)

**Comment by MartaSztuka** [comment]
## PASSED
### Key concepts lists![Screenshot from 2020-08-28 11-41-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e498c419-88b9-465c-a8be-b20dc12c7afe)![Screenshot from 2020-08-28 11-41-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c67361c5-ec8b-4404-ad2a-ad837b8182eb)
