### ISSUE TITLE
Calculus 2 - Chapter title overlap Figure caption.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2670]
## Image is too short, so the title drops down.![Screenshot from 2020-08-24 11-22-56](https://user-images.githubusercontent.com/47241114/91027628-a28eac80-e5fc-11ea-8f22-651b53ddb001.png)

**Comment by lwtchu** [comment]
content issue - will move

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1851](https://github.com/openstax/content-managers/issues/1851) via [**ZenHub**](https://www.zenhub.com/)
