### ISSUE TITLE
Calculus 2 - Long equations in EoC

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2671]
## When equation is too long columns overlap.![Screenshot from 2020-08-24 11-29-02](https://user-images.githubusercontent.com/47241114/91028042-319bc480-e5fd-11ea-8148-45c3d29e8463.png)

**Comment by lwtchu** [comment]
this is a content issue.

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1849](https://github.com/openstax/content-managers/issues/1849) via [**ZenHub**](https://www.zenhub.com/)
