### ISSUE TITLE
HS Statistics - Captions above table

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2672]
### Captions above, table-wide occurs twice in whole book and look's weird. ![Screenshot from 2020-08-24 12-55-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ac3d4e45-c0a0-4a47-93af-dc28393b3e0e)![Screenshot from 2020-08-24 12-58-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d8db914b-ee79-47ad-9ecb-b554dad831d8)

**Comment by lwtchu** [comment]
is the recipe moving the captions to the top? and is it because one of them is unnumbered?

for the first screenshot i think we should style it like the rest of the other tables. 

for the second screenshot i think we can fix in content - but i wanted to make sure if this is a caption on unnumbered table

**Comment by ajluk** [comment]
How these tables captions look now after changing the config file to support existing content captions: 
![image](https://user-images.githubusercontent.com/55203598/91153707-dcc18200-e6c0-11ea-97de-812fe87dc600.png)
![image](https://user-images.githubusercontent.com/55203598/91153784-f6fb6000-e6c0-11ea-8576-6a726c2b96e4.png)
The centering of the tables and captions will be fixed within PR (#2626).

**Comment by MartaSztuka** [comment]
## PASSED
### @lwtchu Table caption are table width, look's fine when there's one line, but sometimes it's several lines, do we like it like that?![Screenshot from 2020-08-28 10-58-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/41a2e53c-b5a2-4594-b7b4-652d723b15ab)![Screenshot from 2020-08-28 10-57-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/750cd939-91aa-463d-8b2e-c183aa4b60e9)

**Comment by brittweinstein** [comment]
@lwtchu if ^ is acceptable, we can go ahead and close this.

**Comment by lwtchu** [comment]
this is fine
