### ISSUE TITLE
HS Statistics - Chapter Objective lists

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2673]
### When lists breaks in two lines second line should start with line, not with the bullet ![Screenshot from 2020-08-24 13-03-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ddb4de7a-be2e-48f3-9847-0a6146ba2215)![Screenshot from 2020-08-24 14-20-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5bd09789-dd8b-4acf-90d1-3d704cfeb81a)

**Comment by meeragovindaraju** [comment]
Looks good!

![Screen Shot 2020-08-31 at 9 43 07 AM](https://user-images.githubusercontent.com/33066187/91732872-74661b00-eb6e-11ea-80d4-9d44a487493d.png)

![Screen Shot 2020-08-31 at 9 43 29 AM](https://user-images.githubusercontent.com/33066187/91732882-77610b80-eb6e-11ea-8145-07264f227deb.png)
