### ISSUE TITLE
HS Statistics - Figure 3.9 sticks out

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2674]
### Figure 3.9 is extending outside the page![Screenshot from 2020-08-24 13-29-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fc012af4-ecee-411a-8613-2d6984be8768)

**Comment by lwtchu** [comment]
content issue moving

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1848](https://github.com/openstax/content-managers/issues/1848) via [**ZenHub**](https://www.zenhub.com/)
