### ISSUE TITLE
HS Statistics - Bullet alignment for tables/images in lists

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2676]
### Missing space before (Person....) in the list, occurs quite often, but not everywhere. ![Screenshot from 2020-08-24 13-37-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8f112f95-309c-4705-8226-676fccf38679)

**Comment by lwtchu** [comment]
the P(person) thing is a content issue

For this card, can we focus on bullet alignment for tables/figures within lists?

**Comment by ajluk** [comment]
The work on this issue is temporarily withhold due to the other exercises alignment issue: https://github.com/openstax/cnx-recipes/issues/2629.

**Comment by MartaSztuka** [comment]
## PASSED
### HS Statistics![Screenshot from 2020-09-23 14-40-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5afc1587-98e3-45b8-bbbb-3bbca39b521d)
