### ISSUE TITLE
HS Statistics - Header unstyled

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2677]
### Header 'Random Variable Notation' has lot it's style![Screenshot from 2020-08-24 13-47-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1958cb4c-124d-47cf-8a36-7965f309af5f)

**Comment by lwtchu** [comment]
i believe this is a section within the introduction module - can we style that like the rest of the section headers?

**Comment by meeragovindaraju** [comment]
Looks good!

![Screen Shot 2020-08-31 at 9 45 24 AM](https://user-images.githubusercontent.com/33066187/91733083-ba22e380-eb6e-11ea-8977-0da331e42efa.png)

**Comment by lwtchu** [comment]
do we need to open another card for the chapter objectives header :eyes: could that be related to somethng @Stackblocks did recently?

**Comment by Stackblocks** [comment]
@lwtchu Yeah. Open a card for that and assign it to me. :+1:

**Comment by lwtchu** [comment]
@Stackblocks https://github.com/openstax/cnx-recipes/issues/2730
