### ISSUE TITLE
HS Statistics - Support lists in Key terms

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2680]
### Key terms overlap bullet points (one location)  ![Screenshot from 2020-08-24 14-32-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a37ab8da-921a-4fba-b1de-777f1c3bafe0)

**Comment by lwtchu** [comment]
can we align the bullets to be under "the method" and "applicable if"

**Comment by MartaSztuka** [comment]
## PASSED
### HS Statistics, Key Terms
![Screenshot from 2020-08-27 14-44-12](https://user-images.githubusercontent.com/47241114/91443649-e63f1b80-e873-11ea-98e6-6dc0c47269ef.png)
