### ISSUE TITLE
Move neb tests from cnx-automation to neb.

### ISSUE THREAD

**Issue by ckline-tryptic** [openstax/cnx-recipes#2685]
## Description
In the interest of consolidating tests with the code they run against, we want to move neb tests into the nebuchadnezzar repo, from the cnx-automation repo.

## Acceptance Criteria:
- [ ] tests against `neb` exist, and run successfully in the `nebuchadnezzar` repository
- [ ] tests against `neb` do not exist in `cnx-automation` repository

**Comment by brittweinstein** [comment]
Thomas will pair with Chris on this, today.
