### ISSUE TITLE
Text overflow

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2686]
Book: College Algebra with coreq
COPS pdf Content01
Section 1.4 section exercises
Texts are overflowing

![Screen Shot 2020-08-24 at 2.29.21 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/f6c00407-90e7-448d-b048-1e9287644495)

**Comment by lwtchu** [comment]
content issue. i'll go fix on production. closing
