### ISSUE TITLE
Should be a table

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2687]
Book: College Algebra with coreq
Style: precalc
Server: Content01
COPS

Section 1.5

PDF

![Screen Shot 2020-08-24 at 4.22.48 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/0de7cf28-5d49-44c2-ac0f-f4e3b6a64593)

![Screen Shot 2020-08-24 at 4 29 06 PM](https://user-images.githubusercontent.com/33066187/91098380-f910e080-e626-11ea-85d8-3d42f97d874b.png)

Webview

![Screen Shot 2020-08-24 at 4.22.57 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/5c23bcf8-825d-4fe6-8c0f-b9874e685836)

**Comment by meeragovindaraju** [comment]
Chapter 1: Key Equations

PDF

![Screen Shot 2020-08-24 at 4 31 03 PM](https://user-images.githubusercontent.com/33066187/91098564-4b520180-e627-11ea-9d4f-6fb2fd292a6b.png)

Webview:

![Screen Shot 2020-08-24 at 4 31 26 PM](https://user-images.githubusercontent.com/33066187/91098637-72a8ce80-e627-11ea-8160-39ed23608465.png)

**Comment by lwtchu** [comment]
this is a content issue - it has the unnumbered unstyled classes. i'll fix on prod

**Comment by lwtchu** [comment]
the key equations are intended
