### ISSUE TITLE
corn theme: <emphasis> produces line break in EOC para content

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2688]
Book: College Algebra with coreq
Style: precalc
Server: Content01
COPS
2.1 SECTION EXERCISES - Technology section
Periods/bullets should not be there

PDF: 

![Screen Shot 2020-08-24 at 4.34.45 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/085b0601-9824-4d88-832d-8a26b204bb76)

Webview

![Screen Shot 2020-08-24 at 4.37.34 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/df818911-1a86-4b2e-a61e-da72667e10d5)

**Comment by lwtchu** [comment]
line breaks are being injected after text with `<emphasis>` - ican we remove the line breaks - i can make these unbold temporarily before we publish the book but we should be able to support `<emphasis>` without a line break

**Comment by ajluk** [comment]
@lwtchu I have changed the selector for bolded paragrapghs in exercises, which are present in Prealgebra 2e to `[data-effect="bold"`]: 
![image](https://user-images.githubusercontent.com/55203598/91163851-822f2280-e6ce-11ea-8f55-fdd390a8cce4.png)
 to make them not cover the <strong> text in the College Algebra Coreq (which use the same shape for exercises) and now the paragraphs include it look like this: 

![image](https://user-images.githubusercontent.com/55203598/91164150-e81baa00-e6ce-11ea-867b-c0387e90c4b5.png)

PDF:

![image](https://user-images.githubusercontent.com/55203598/91164594-93c4fa00-e6cf-11ea-8a14-d5e178a38f8b.png)

![image](https://user-images.githubusercontent.com/55203598/91164399-3df05200-e6cf-11ea-90bf-26f8d5824882.png)

PDF:

![image](https://user-images.githubusercontent.com/55203598/91164285-1c8f6600-e6cf-11ea-9745-ce3b3ee6f322.png)

**Comment by lwtchu** [comment]
@ajluk content issues aside i think this is good i'll look into the content issues

**Comment by MartaSztuka** [comment]
## PASSED
### Emphasis doesn't produce line break ![Screenshot from 2020-08-28 12-27-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9a7c7b52-ac8c-4aeb-afd8-1fa537fabcaa)

**Comment by brittany-johnson** [comment]
Opening this issue so that we can confirm changes after cops deployment

**Comment by meeragovindaraju** [comment]
Passed!

![Screen Shot 2020-09-02 at 10 53 39 AM](https://user-images.githubusercontent.com/33066187/92006656-a318f880-ed0a-11ea-86b4-e3597dfca5c9.png)
