### ISSUE TITLE
Q&A section font looks too big compared to the other Q&A sections

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2689]
Book: College Algebra with coreq
Style: precalc
Server: Content01
COPS
Section 3.4 Example 5 Q&A section font looks too big compared to the other Q&A sections

![Screen Shot 2020-08-24 at 5.03.55 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/b53456d5-a4cc-42b0-8fa3-17e0bd2bdabd)

**Comment by lwtchu** [comment]
this is a content issue - will fix on production
