### ISSUE TITLE
Elementary Algebra - Everyday Math columns overlap

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2696]
### Everyday Math paragraphs need margine ![Screenshot from 2020-08-25 10-31-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cd67a901-6a39-4bb1-a58c-b43a4995ee74)

**Comment by wilkus27** [comment]
It might be related with https://github.com/openstax/cnx-recipes/issues/2761

**Comment by ajluk** [comment]
This issue has been resolved while working on #2761: 
![Uploading image.png…]()
