### ISSUE TITLE
Elementary Algebra - Images with equations

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2697]

**Comment by lwtchu** [comment]
related to #2507 and #2681? i'm a lil concerned that we'll have to go thru all the images and fix.

**Comment by ajluk** [comment]
Here is how these images look with `prince-image-resolution` set to `normal`,
![image](https://user-images.githubusercontent.com/55203598/91548508-c10ae580-e925-11ea-803f-19e63c98b2a6.png)
![image](https://user-images.githubusercontent.com/55203598/91548438-a9336180-e925-11ea-91f3-d366914a2b93.png)
But I have found examples of these oddly big other images in this case in Elementary Algebra:
![image](https://user-images.githubusercontent.com/55203598/91548716-1941e780-e926-11ea-9bb3-1a83dfe788a7.png)
![image](https://user-images.githubusercontent.com/55203598/91548661-00393680-e926-11ea-97ff-3b1b76be3fe7.png)
![image](https://user-images.githubusercontent.com/55203598/91548637-f44d7480-e925-11ea-8a9b-7c788bc84fb4.png)

And here is with the auto:

**Comment by lwtchu** [comment]
left a comment on #2681 for potentially deferring the fix/solution/investigation to after we get the cardboard theme backlog up and coreq out

**Comment by brittweinstein** [comment]
This is a duplicate of https://app.zenhub.com/workspaces/ce-styles-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2681

**Comment by brittweinstein** [comment]
@brittany-johnson HELLO HELP ME
