### ISSUE TITLE
Elementary Algebra - Unstyled paragraph

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2700]
### Paragraph is unstyled, wrong font and all  ![Screenshot from 2020-08-25 12-54-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/43b907bf-2a2c-4682-86e5-b74a384ee5f4)

**Comment by lwtchu** [comment]
this is a math table. and is intended to display this way
