### ISSUE TITLE
Elementary Algebra - unstyled word in Example

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2701]
### 'Solve' word in Step 5 is normal, should be bold![Screenshot from 2020-08-25 13-17-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6cb3043f-30ca-430c-81ac-1097d57dde82)

**Comment by lwtchu** [comment]
content issue

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1856](https://github.com/openstax/content-managers/issues/1856) via [**ZenHub**](https://www.zenhub.com/)
