### ISSUE TITLE
Elementary Algebra -  Wild dot above 'In the following exercise (...)`

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2702]
### There is singe dot above 'In the following exercise (...)` which is unnecessary ![Screenshot from 2020-08-25 13-22-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/291d1102-0c5c-4cad-9f79-df96803f81b1)

**Comment by lwtchu** [comment]
I think this is related to #2688. All of that is supposed to be on paragraph.

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/91824443-13584900-ec3b-11ea-9091-768ec39e6fc5.png)

**Comment by meeragovindaraju** [comment]
Looks good!

![Screen Shot 2020-08-31 at 9 55 10 AM](https://user-images.githubusercontent.com/33066187/91865323-e3a74200-ec36-11ea-8877-4f629c3ec788.png)

**Comment by meeragovindaraju** [comment]
Looks good!

![Screen Shot 2020-09-01 at 9 39 47 AM](https://user-images.githubusercontent.com/33066187/91865534-1bae8500-ec37-11ea-8c03-2446d63c2392.png)
