### ISSUE TITLE
Elementary Algebra - Inconsistent leading

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2703]
### Leading between 'Solve a System (...)' and  'In the following exercise (...)' is smaller than usually ![Screenshot from 2020-08-25 13-25-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/37e6bb01-e6cb-417c-8194-9458841c94b8)

**Comment by ajluk** [comment]
@lwtchu I guess it is s content issue. The titles are put in one paragraph instead in two as it is done for the rest of these exercises paragraphs titles:
![image](https://user-images.githubusercontent.com/55203598/91832089-3a1b7d00-ec45-11ea-8017-b2180c045a55.png)
![image](https://user-images.githubusercontent.com/55203598/91832048-28d27080-ec45-11ea-90f6-06b81c43e94f.png)
![image](https://user-images.githubusercontent.com/55203598/91832519-ca59c200-ec45-11ea-89d2-c8506d2dc448.png)

**Comment by lwtchu** [comment]
thanks i'll move this to the cm board
