### ISSUE TITLE
Elementary Algebra - unstyled paragraph

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2704]
### Examples of polynomials paragraph is unstyled![Screenshot from 2020-08-25 13-30-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/42dc8983-ebee-4172-95be-f0b55895640f)

**Comment by lwtchu** [comment]
this is in a mathml table so it's using the math font. i think this is expected unfortunately
