### ISSUE TITLE
Elementary Algebra - terms

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2706]
### Bold term (monomial) is not term, two others are terms, but don't have 'no-emphasis' class.   ![Screenshot from 2020-08-25 13-29-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fcfb0c5e-a37e-4bbb-885c-fe9453b6ef9e)
![Screenshot from 2020-08-25 15-27-35](https://user-images.githubusercontent.com/47241114/91180589-2ffafb00-e6e8-11ea-8853-2720e5dee1fc.png)

**Comment by lwtchu** [comment]
i'll move this to content :eyes:
