### ISSUE TITLE
Elementary Algebra - unnecessary big space

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2707]
### Space is too big  ![Screenshot from 2020-08-25 13-35-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0933c1e0-ead8-4900-89c1-ca12888a7fc2)

**Comment by lwtchu** [comment]
this is probably content

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1854](https://github.com/openstax/content-managers/issues/1854) via [**ZenHub**](https://www.zenhub.com/)
