### ISSUE TITLE
Add offending module to link-extras debug output

### ISSUE THREAD

**Issue by ckline-tryptic** [openstax/cnx-recipes#2708]
# Description
In order to determine the module that is missing from the canonical list we need to include the module in the link-extras debug output.

We had a user hit an error during link-extras when using the bakery CLI which we were unable to debug with the current output (see slack thread). Specifically, we should add output when this exception is thrown which includes the link and / or legacy ID so we can quickly identify the offending CNXML and manually perform the extras lookup.

# Acceptance Criteria
- [x] Debug output includes module that triggers the no canonical Exception.
- [ ] The output from the no containing books Exception includes information that allows users / developers to quickly debug the error / content

**Comment by omehes** [comment]
tested in PR#

Exception: No containing books.
content: ff64d142-d2a3-40d8-95dd-e827c72ec412@1
module link: /contents/m67440
failed
