### ISSUE TITLE
Table number is within the table

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#2709]
Book: College Algebra with coreq
Style: precalc
Server: Content01
COPS
Section 6.4 Example 9

![Screen Shot 2020-08-25 at 12.20.18 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/7181a38e-8ad4-4661-83db-1893423a34dd)

**Comment by lwtchu** [comment]
content issue, on an existing card to address in final qa of coreq
