### ISSUE TITLE
cardboard theme - section number treatment

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2710]
![Screen Shot 2020-08-25 at 12 25 14 PM](https://user-images.githubusercontent.com/11299125/91207227-0c2abb80-e6ce-11ea-82fb-cdf0eb23977b.png)
![Screen Shot 2020-08-25 at 12 25 40 PM](https://user-images.githubusercontent.com/11299125/91207272-1b116e00-e6ce-11ea-91fb-3df8910abceb.png)

The headers should follow the normal header sizing - #2644 

However, the numbers should have a box around it.

Font style: roboto condensed (blue), dosis (astronony/purple/yellow)
Line weight: 0.75 px (0.0625 rem)
Color: Y1: `#E3A354` for Astronomy; B3: `#0DC0DC` for the rest
Padding: 0.25 rem

**Comment by wilkus27** [comment]
@andymuddimer This is how it looks with applied specs:

![image](https://user-images.githubusercontent.com/40228854/94904981-6d4b6900-049c-11eb-841e-e6577b8c5e2d.png)

Is it ok? Border seems to be thinner than on the screenshot :thinking:

**Comment by wilkus27** [comment]
I tried to increase values. Here I applied padding `0.5rem` and border width `0.2rem`

![image](https://user-images.githubusercontent.com/40228854/94908053-670bbb80-04a1-11eb-8fa8-7ad273a06e42.png)

Please let me know what should I change :slightly_smiling_face:

**Comment by lwtchu** [comment]
@wilkus27 oops i think the font should be roboto condensed  😬  i added it to the specs

**Comment by wilkus27** [comment]
@lwtchu Here is how it looks now with increased values for border:

![image](https://user-images.githubusercontent.com/40228854/95188754-2f688080-07cd-11eb-8c3b-3f7e880cf180.png)

and with the original ones:

![image](https://user-images.githubusercontent.com/40228854/95191538-30031600-07d1-11eb-9988-ca6766574966.png)

Which should I apply?

**Comment by lwtchu** [comment]
@wilkus27 can we go with the first

**Comment by wilkus27** [comment]
@lwtchu This is how it looks in Astronomy:

![image](https://user-images.githubusercontent.com/40228854/102234932-1299a900-3ef2-11eb-9945-1a50c7c3133e.png)

Is it ok?

**Comment by lwtchu** [comment]
@wilkus27 Yes this is fine. THank you~
