### ISSUE TITLE
cardboard theme: learning objectives

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2711]
![Screen Shot 2020-09-17 at 1 39 05 PM](https://user-images.githubusercontent.com/11299125/93513232-2d588380-f8eb-11ea-96e1-3c0e3a7e43b8.png)

### business
class: `"learning-objectives"`
title: Learning Objectives 
title font: roboto condensed
text font: noto sans
title color: B2: `#344456`
size: font-scale(1): 10.8pt, 14.4px, 1.2rem
font-weight: lighter

the LO list should follow regular list specs (alpha/numeral should have letters/numbers that aren't bolded and followed by a .)

![Screen Shot 2020-10-23 at 7 00 04 PM](https://user-images.githubusercontent.com/11299125/97062770-fddc0d00-1561-11eb-8f49-4e6c0fd1675d.png)
### astronomy
class: `"learning-objectives"`
title: Learning Objectives
title font: dosis
text font: noto sans
title color: P2: `#772949`
size: font-scale(1): 10.8pt, 14.4px, 1.2rem
font-weight: bold
icon for bullet for LO: https://drive.google.com/file/d/14Nu6KIQwuDQcbA-O9RJdIWnHR6WU4Hxp/view?usp=sharing

**Comment by ajluk** [comment]
@andymuddimer This is how it looks styled with the provided specs: 
![image](https://user-images.githubusercontent.com/55203598/94696641-8edf1000-0337-11eb-9512-e7fda3fa6112.png)
The space under the title Learning Objectives will be added to the module title as a margin within another PR.
I have also tried adding `font-weight: lighter `to the title Learning Objectives and then it looks more similar to the provided screenshot and this is how it looks then:
![image](https://user-images.githubusercontent.com/55203598/94696992-f4cb9780-0337-11eb-94bd-acdf1b00ce9b.png)
Should I add this additional property to the Learning Objectives title?

**Comment by lwtchu** [comment]
@ajluk can you add font-weight lighter? i'll update the specs

**Comment by brittweinstein** [comment]
Anna has made the font change. However, when Marta tested, it still appeared bolded.

**Comment by ajluk** [comment]
The issue from comment (https://github.com/openstax/cnx-recipes/issues/2711#issuecomment-707767046) has been resolved via this issue (https://github.com/openstax/cnx-recipes/issues/2848) and related PR
