### ISSUE TITLE
cardboard theme: things we should pull from corn & carnival

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2712]
- [x] `<term>` and `<term class="no-emphasis">`
- [x] table cell alignments driven by content
- [x] folio structure (except font is Noto Sans and color is `#000000`)
- [x] standard link color and treatment
- [x] list indentations (stepwise, no label, bulleted, alpha lists)
- [x] side bar in EOC/Answer Key (change color to B4: `#24739E`; astronomy: `#772949`)

**Comment by ajluk** [comment]
@lwtchu I have a question about folio for cardboard theme. On the screenshots for Splash Images there is a difference: 
![image](https://user-images.githubusercontent.com/55203598/94417404-52b57f00-0180-11eb-81b8-6ee307bf19b9.png)
The folio is invisible in screenshot for Business books but visible in Astronomy? Should we implement it this way?

**Comment by lwtchu** [comment]
@ajluk can we do what we’ve been doing? We should just copy what we did and update the fonts to match.

**Comment by ajluk** [comment]
@lwtchu I have forgotten that you're on vacation I guess we can go back to it when you will be back. I will it as it is  for now.

**Comment by lwtchu** [comment]
@ajluk I'm back! do you have anything to add :eyes:

**Comment by ajluk** [comment]
@lwtchu I applied the same folio as in the corn theme for cardboard (except the color and font). I guess we discussed it somewhere else, that's why I haven't replied here for you comment. : slightly_smiling_face :

**Comment by lwtchu** [comment]
@ajluk ah okay. i think we covered it elsewhere too but can't remember where. i think the same folio as corn theme except color and font is good. thank you
