### ISSUE TITLE
Elementary Algebra - no margine

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2714]
### Paragraph above the note has no bottom margin ![Screenshot from 2020-08-26 11-10-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6290f56d-4efa-4461-a2ea-917f07a5c8f0)

**Comment by ajluk** [comment]
I have checked that this an unnumbered equation and added styles for them to Elementary Algebra as well (dev-math).
I have also checked Statistics if they have equations in the content and they do without class `unnumbered`. @lwtchu should they be numbered, because right now they aren't in the recipe?
![image](https://user-images.githubusercontent.com/55203598/91583172-17d9e480-e951-11ea-933d-2f8bc9dc130a.png)

**Comment by lwtchu** [comment]
@ajluk the padding looks good i can open a card for all 3 statistics books to make all the equations unnumbered -is that ok?

**Comment by ajluk** [comment]
@lwtchu is it be possible to add the class in one section for testing I can add then the styles for equations in statistics within the same PR?

**Comment by lwtchu** [comment]
@ajluk i also realized this class is for elementary algebra - ijust clarifying that we just need the classes on the statistics titles right?

i added the unnumbered class to 10.1  Two Population Means with Unknown Standard Deviations in the Introductory Statistics book (https://katalyst01.cnx.org/contents/MBiUQmmY@24.4:AeeflfGs@18/10-1-Two-Population-Means-with-Unknown-Standard-Deviations)

**Comment by ajluk** [comment]
@lwtchu Yes, that' right. Thank you!

**Comment by ajluk** [comment]
@meeragovindaraju >> Information for testing purposes:
Within this issue unnumbered equations in Elementary Algebra has been styled but also in Introductory Statistics - in this book the class `unnumbered` for equations has been added only in module 10.1 Two Population Means with Unknown Standard Deviations on katalyst01:
Screenshots for reference: 
HTML
![image](https://user-images.githubusercontent.com/55203598/91955855-166b3c00-ed04-11ea-979d-71210f0edd7d.png)
PDF
![image](https://user-images.githubusercontent.com/55203598/91955802-fdfb2180-ed03-11ea-8d25-2697689a9104.png)
Documentation with specs for unnumbered equations: 2447 (without numbers).

**Comment by lwtchu** [comment]
@ajluk do you know if the equations need a `<label/>` tag on it? or just the unnumbered class

**Comment by ajluk** [comment]
@lwtchu for the styling only the `unnumbered` class is needed.

**Comment by meeragovindaraju** [comment]
Looks good in Elementary Algebra 

![Screen Shot 2020-09-08 at 10 06 55 AM](https://user-images.githubusercontent.com/33066187/92494273-2333d800-f1bb-11ea-8b4f-3ea02c11af54.png)

Looks good in Intro to stats section 10.1

![Screen Shot 2020-09-08 at 10 20 48 AM](https://user-images.githubusercontent.com/33066187/92495967-26c85e80-f1bd-11ea-9bf6-e9fe12d1cf95.png)
