### ISSUE TITLE
Elementary Algebra - Answer Key columns

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2717]
### Answer Key, two columns in thee columns layout ![Screenshot from 2020-08-26 12-20-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/010fbc44-0877-4373-a45d-1864445db417)![Screenshot from 2020-08-26 11-40-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ea7e12f3-6b4f-4bdf-864a-3d1273804ba3)

**Comment by lwtchu** [comment]
is this related to #2486 ??

**Comment by ajluk** [comment]
@lwtchu I have checked and it is the same issue as: #2486

**Comment by lwtchu** [comment]
@ajluk @MartaSztuka i'll close this one so we can focus efforts and documentation on #2486. thank you~
