### ISSUE TITLE
college algebra/college algebra coreq - nested lists in how to not indenting properly

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2721]
![Screen Shot 2020-08-26 at 1 04 50 PM](https://user-images.githubusercontent.com/11299125/91340081-05b74500-e79d-11ea-8669-b1a16db57f3b.png)

i looked in a few places but not sure if this was addressed with any existing pr.

the a/b list is nested within the numeric list. can we make sure that nested lists get proper indentation in features?

This is in Chapter 6.4 Graphs of Logarithmic Functions; handful of other instances peppered throughout chapter 6

**Comment by lwtchu** [comment]
![Screen Shot 2020-08-26 at 1 29 26 PM](https://user-images.githubusercontent.com/11299125/91342139-38af0800-e7a0-11ea-8b1a-252488917f37.png)
another example from 8.1

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/91548374-915bdd80-e925-11ea-8a4d-78ce38e4fa81.png)

![image](https://user-images.githubusercontent.com/40228854/91548499-be0ff500-e925-11ea-89e0-1d93e3ce1d0e.png)

Is it ok?

**Comment by lwtchu** [comment]
@wilkus27 can the a start under "vertices" - the bullets start right under the text so the alpha lists should too

**Comment by wilkus27** [comment]
@lwtchu To align "a" with the text from above I had to use hard coded value `2rem` for margin:

![image](https://user-images.githubusercontent.com/40228854/91835519-cb8cee00-ec49-11ea-98cc-a29ca83c8888.png)

As @Stackblocks suggested in my PR it would be better to use created function `h-spacing`, but then "a" is moved more on the right:

![image](https://user-images.githubusercontent.com/40228854/91835694-042cc780-ec4a-11ea-89fb-a681401b42f8.png)

Are you ok with that? Or we should stay with `2rem`?

**Comment by lwtchu** [comment]
@wilkus27 can we go with the h-spacing thanks.

**Comment by brittany-johnson** [comment]
Verified on development branch:
![Screen Shot 2020-09-01 at 2 41 21 PM](https://user-images.githubusercontent.com/24909007/91898607-98565900-ec61-11ea-9653-4f8d0ab0e097.png)

**Comment by meeragovindaraju** [comment]
Looks good on the feature branch College Algebra with coreq

![Screen Shot 2020-09-01 at 2 02 33 PM](https://user-images.githubusercontent.com/33066187/91899301-8cb76200-ec62-11ea-9e7a-761d3014d787.png)


![Screen Shot 2020-09-01 at 2 02 08 PM](https://user-images.githubusercontent.com/33066187/91899312-904ae900-ec62-11ea-84d6-667855d0854d.png)
