### ISSUE TITLE
corn theme: chapter objectives erroneously styled 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2730]
![image](https://user-images.githubusercontent.com/11299125/91747655-33790100-eb84-11ea-9528-5947831ef902.png)

Please look at #2190 for specifications.

Found in HS Statistics, not sure if it impacts anything else.

**Comment by meeragovindaraju** [comment]
@Stackblocks looks good on the feature branch

![Screen Shot 2020-08-31 at 9 17 11 AM](https://user-images.githubusercontent.com/33066187/91890283-db5dff80-ec54-11ea-9951-9cbcbafae5ed.png)


![Screen Shot 2020-08-31 at 9 12 44 AM](https://user-images.githubusercontent.com/33066187/91890286-dbf69600-ec54-11ea-9c3c-cb6d3a7604d5.png)


![Screen Shot 2020-08-31 at 9 12 35 AM](https://user-images.githubusercontent.com/33066187/91890287-dc8f2c80-ec54-11ea-91e7-82e27504647b.png)

**Comment by Stackblocks** [comment]
Closed with #2756, #2733, #2722
