### ISSUE TITLE
precalculus coreq/corn theme - tokens and circled class lists aren't working in the coreq content

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2732]
![image](https://user-images.githubusercontent.com/11299125/91758331-70012880-eb95-11ea-92d8-d32ef1cedb2c.png)
This is marked up correctly but for some  reason the `circled` list feature and `tokens` aren't being styled.

This might be due to it not being styled in stand alone sections in the coreq section. (aka this isn't in a note/example/etc). 

Under Objective 2 of 5.8 Modeling Using Variation

**Comment by lwtchu** [comment]
I think this is only one instance. So I think it can slide til after the book is published. I'll modify the content slightly to make it less obvious that it's broken.

**Comment by lwtchu** [comment]
problem still persists in newly generated pdf (job 389 on cops) but this one isn't a show stopper

**Comment by meeragovindaraju** [comment]
@lwtchu I do not see that graph in section 5.8 but I found 👇  in section 5.5 College Algebra with coreq pdf from s.s branch & katalyst01

![Screen Shot 2020-09-03 at 1 59 25 PM](https://user-images.githubusercontent.com/33066187/92155930-cd8fb200-eded-11ea-8dfd-4370146c2e0b.png)

**Comment by lwtchu** [comment]
@meeragovindaraju migrated content over - let me know if there's still issues

**Comment by meeragovindaraju** [comment]
Objective 2 of 5.8 Modeling Using Variation looks good

![Screen Shot 2020-09-08 at 12 29 47 PM](https://user-images.githubusercontent.com/33066187/92509208-83347980-f1cf-11ea-9b5b-820cde93ca2b.png)
