### ISSUE TITLE
cardboard theme: boxed note

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2737]
![Screen Shot 2020-08-31 at 4 17 31 PM](https://user-images.githubusercontent.com/11299125/91769743-8e6f2000-eba5-11ea-8624-895d367a610e.png)
![Screen Shot 2020-09-15 at 4 00 54 PM](https://user-images.githubusercontent.com/11299125/93264398-ada4aa80-f76c-11ea-9796-c62d168e34ca.png)
![Screen Shot 2020-09-16 at 1 31 28 PM](https://user-images.githubusercontent.com/11299125/93377686-f9b12700-f820-11ea-8dec-64a75b99a360.png)

## Title (Link To Learning) - generated from applied class
font: Roboto Condensed for business books; Dosis for Astronomy
size: font-scale(1): 10.8pt, 14.4px, 1.2rem
treatment: all caps
color: B2: `#344456`

## Title (from `<title>` tag)
![Screen Shot 2020-09-02 at 3 45 06 PM](https://user-images.githubusercontent.com/11299125/92034788-5a296a00-ed33-11ea-9794-b18de7b93ba2.png)
font: Roboto Condensed for business books; Noto Sans for Astronomy
size: font-scale(1): 10.8pt, 14.4px, 1.2rem
color: B2: `#344456` for blue theme; P1: `#3B2746` for Astronomy

## Icon (if any)
Always sits on the right in the band.
padding right from edge: v-spacing(1)
If it is small, it sits vertically centered on the band
If it is a large scenic (like in third screenshot above) it sits on the bottom edge.

## Band at top
color: B3: `#0DC0DC`
corners: rounded

## Main text box
color: G2: `#F2F2F2`

## Main text
Should follow base font decided in #2644 

## Padding
top, left, bottom, right: v-spacing(1) 0.7rem

# Alternate Color Schemas
## Option 1 (seen abve)
![Screen Shot 2020-08-31 at 4 17 31 PM](https://user-images.githubusercontent.com/11299125/91769743-8e6f2000-eba5-11ea-8624-895d367a610e.png)

## Option 2
![Screen Shot 2020-09-02 at 3 45 06 PM](https://user-images.githubusercontent.com/11299125/92034788-5a296a00-ed33-11ea-9794-b18de7b93ba2.png)
Title: white `#FFFFFF`
Top bar: B4: `#24739E`
Bottom box: B6: `#D3E3EB`

## Option 3
![Screen Shot 2020-09-02 at 4 34 08 PM](https://user-images.githubusercontent.com/11299125/92039146-3289d000-ed3a-11ea-954d-8fb58738d0d2.png)
Title: black `#000000`
Top bar: O2: `#D34D32`
Bottom box: B5: `#D6D9DD`

## Option 4
![image](https://user-images.githubusercontent.com/11299125/93253758-ef2d5980-f75c-11ea-8525-4860179b2000.png)
Title: B2: `#344456`
Outline color: Grey3: `#EAEAEA`
Outline width: 1px (0.08 rem)
Bar up top color: O2: `#D34D32`
Bar up top width: 4px (0.33 rem)

## Option 5
![Screen Shot 2020-09-15 at 4 00 54 PM](https://user-images.githubusercontent.com/11299125/93264398-ada4aa80-f76c-11ea-9796-c62d168e34ca.png)
Title: white `#FFFFFF`
Top bar: B2: `#344456`
Bottom box: B5: `#D6D9DD`

## Option 6
![Screen Shot 2020-10-26 at 5 02 19 PM](https://user-images.githubusercontent.com/11299125/97233499-10965200-17ad-11eb-9d4d-ec3323edd5a9.png)
Title: White `#FFFFFF`
Top Bar: P2: `#772949`
Bottom box: Grey 4: `#E6EAEE`

## Option 7
![Screen Shot 2020-10-26 at 5 29 00 PM](https://user-images.githubusercontent.com/11299125/97235392-c31be400-17b0-11eb-8fbf-dbae96429a2f.png)
Title: White `#FFFFFF`
Top bar: P1: `#3B2746`
Bottom Box: P4: `#EAE8EB`

## Option 8
![Screen Shot 2020-10-26 at 5 38 27 PM](https://user-images.githubusercontent.com/11299125/97236000-235f5580-17b2-11eb-848e-4f5cc99331b7.png)

Title: `#000000`  Black
Top Bar: O2: `#D34D32`
Bottom box: Grey1: `#F9F9F9`

**Comment by wilkus27** [comment]
@andymuddimer This is how Link to Learning looks with styles:

![image](https://user-images.githubusercontent.com/40228854/94923618-70565180-04bc-11eb-8a0e-17fa418bf943.png)

I applied border-radius `0.25rem` (to make corners rounded) and set padding to `v-spacing(1)`. We don't use anymore `v-grid` function and we don't apply non integer values.

Does it look good? Should I change anything?

**Comment by wilkus27** [comment]
@andymuddimer Here is another note with subtitle and colors Option 2:

![image](https://user-images.githubusercontent.com/40228854/95057639-c1518a00-06f6-11eb-8b18-78920cf8632f.png)

Is it ok?

**Comment by wilkus27** [comment]
Here is note with Option3:

![image](https://user-images.githubusercontent.com/40228854/95065495-6bceaa80-0701-11eb-9874-5a670a998624.png)

Note: list will be styled later i separate PR.

**Comment by wilkus27** [comment]
@lwtchu `v-spacing(1) ` is `0.7rem`.

**Comment by ajluk** [comment]
@lwtchu Here is how the  Catching Entrepreneurial Spirit2 note (option 2 with icon) looks like:
![image](https://user-images.githubusercontent.com/55203598/97882934-7ee69180-1d24-11eb-91a9-381c56a4cb05.png)
Should I change something?
Specs added:
![image](https://user-images.githubusercontent.com/55203598/97883074-b0f7f380-1d24-11eb-8e5e-59b212b55272.png)
Note Title
position: relative;
padding-top: 1.4rem;
padding-bottom: 1.4rem;
Note Icon
background: url(toDataUri("svg+xml", "designs/cardboard/resources/cardboard-grouplight.svg")) no-repeat top right,
background-size: contain;
height: 5rem;
width: 11rem;
content: '';
position: absolute;
right: 0;
bottom: 0;

**Comment by lwtchu** [comment]
@ajluk beautiful~ ! i like how you have it flush with teh bottom. we've had some problems in the past :joy:

**Comment by ajluk** [comment]
@lwtchu Here is how the rest of the boxed notes with icon look like styled: 
![image](https://user-images.githubusercontent.com/55203598/98108403-2df9a900-1e9c-11eb-9308-6335b8455309.png)
![image](https://user-images.githubusercontent.com/55203598/98108487-5386b280-1e9c-11eb-883d-3a350196b8e6.png)
![image](https://user-images.githubusercontent.com/55203598/98108517-5f727480-1e9c-11eb-84f9-fbf6f21bd11d.png)
![image](https://user-images.githubusercontent.com/55203598/98108647-9fd1f280-1e9c-11eb-9f9c-222eb3b0cff9.png)

**Comment by lwtchu** [comment]
@ajluk beautiful 🤗

**Comment by ajluk** [comment]
@lwtchu This is how the Option 4 looks styled: 
![image](https://user-images.githubusercontent.com/55203598/98348811-82766300-2019-11eb-9644-3118f28f22ba.png)
Specs used:
For the **Title** 
![image](https://user-images.githubusercontent.com/55203598/98348439-0aa83880-2019-11eb-8ccd-c685c869e354.png)
color: #344456;
font-family: Roboto Condensed, StixGeneral;
font-size: 1.2rem;
line-height: 1.5rem;
text-transform: uppercase;
font-weight: normal;
background-color: #FFFFFF;
border-radius: 0.25rem 0.25rem 0rem 0rem;
padding: 0.7rem;
border-top-width: 0.33rem;
border-top-style: solid;
border-top-color: #D34D32;
border-right-width: 0.08rem;
border-right-style: solid;
border-right-color: #EAEAEA;
border-left-width: 0.08rem;
border-left-style: solid;
border-left-color: #EAEAEA;
box-decoration-break: slice;
**Note Body**
font-family: Noto Sans, StixGeneral;
font-size: 1rem;
line-height: 1.5rem;
background-color: #FFFFFF;
padding: 0.7rem;
border-width: 0.08rem;
border-style: solid;
border-color: #EAEAEA;
box-decoration-break: slice;
**Subtitle**
    color: #344456;
    font-family: Roboto Condensed, StixGeneral;
    font-size: 1.2rem;
    line-height: 1.5rem;
    font-weight: normal;
    margin-bottom: 0.7rem;

**Comment by lwtchu** [comment]
@ajluk this looks great thank you

**Comment by ajluk** [comment]
@lwtchu here is how the notes 
Sustainability and Responsible Management: 
![image](https://user-images.githubusercontent.com/55203598/99672811-3b09c100-2a74-11eb-8c22-943fbedbd317.png)
and Managerial Leadership:
![image](https://user-images.githubusercontent.com/55203598/99673038-8ae88800-2a74-11eb-90df-904c30dfdebb.png)
look like styled with icons in Principles of Management. Should I change something?

**Comment by lwtchu** [comment]
@ajluk is it possible to make the managerial leadership one bigger in the code so they're flush with the bottom and fit in the entirety of the bar? if not i can fix the svg. just let me know :)

**Comment by ajluk** [comment]
@lwtchu Yes, it will looks like this then (html) with the properties I changed pointed: 
![image](https://user-images.githubusercontent.com/55203598/99699863-c42ff080-2a92-11eb-8537-7846ae3801e7.png)

**Comment by lwtchu** [comment]
@ajluk yes perfect thank you!

**Comment by kswanson33** [comment]
@lwtchu Option 7 for Astronomy currently looks like this:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/26280712/102279729-e2ee9f00-3ef9-11eb-8a28-208363d63825.png">

Specs I added: 
- Color the subtitle the same as the header background (P1)

Do you want header/subtitle to be bold, a different color for the body text, or anything else different to match the documentation image?

**Comment by lwtchu** [comment]
@kswanson33 no as long as you have the same specs as "Title (from <title> tag)" header up there ti should be fine

**Comment by ajluk** [comment]
@lwtchu Note using specs from option 8 in Astronomy looks like this: 
![image](https://user-images.githubusercontent.com/55203598/103342970-26fdaa00-4a8b-11eb-91f4-07f5f9739199.png)
I have also added Subtitle color: P1. Let me know if it is accurate.
I have also changed these properties values for icon: 
height': 2.5rem,
bottom': v-spacing(1), (0.7rem)

**Comment by ajluk** [comment]
@lwtchu here is how looks Link to Learning note in Astronomy styled with option 6: 
![image](https://user-images.githubusercontent.com/55203598/103358017-e1ee6d80-4ab4-11eb-95eb-6bbd3b0a4e35.png)

**Comment by lwtchu** [comment]
@ajluk these look good thank you
