### ISSUE TITLE
Polish diacritics and signs in Key Terms

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2739]
#### 1. Signs

When term starts with `-` it should be sorted by first letter after this sign:

![image](https://user-images.githubusercontent.com/40228854/91961473-80d3aa80-ed0b-11ea-9022-b8a8ccc06e44.png)

#### 2. Polish diacritics

When term starts with Polish diacritics it shows up  at the beginning:

![image](https://user-images.githubusercontent.com/40228854/91961647-bf696500-ed0b-11ea-9e7c-90187e5b7048.png)

It should be sorted according to the alphabet.

**Comment by wilkus27** [comment]
#### NOTE

`świadomy sen` from the screenshot displays at the beggining because there is a blank space before `ś`, so it is treated as a symbol. It should be fixed in the content.

**Comment by wilkus27** [comment]
@MartaSztuka This should be tested after fix from the https://github.com/openstax-poland/content/issues/39 be present on katalyst01. Please contact with Patryk to make sure it is done.

**Comment by MartaSztuka** [comment]
### PASSED
![Screenshot from 2020-11-05 15-55-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/11b9cbba-8d53-48a8-8b2a-b88b95e090a7)![Screenshot from 2020-11-05 15-48-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4125386f-6d45-4031-ada3-a74e75ad7833)
