### ISSUE TITLE
cardboard theme: tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2741]
In the original issue (https://github.com/openstax/oer.exports/issues/3399) it goes in depth into how the `top-titled` class works styling. I believe most of the work is done on the recipe side (#1241) and we just need to style it (hopefully my understanding is correct!). 

There are two types: regular and `text-heavy`. Either can support the `top-titled` class where it takes the first header row and creates no borders/no boxes, centers the text and makes it bold.

# Type 1 Regular Table
![Screen Shot 2020-09-02 at 5 49 46 PM](https://user-images.githubusercontent.com/11299125/92044854-bea0f500-ed44-11ea-8e26-4640829145b0.png)
![Screen Shot 2020-09-02 at 5 49 40 PM](https://user-images.githubusercontent.com/11299125/92044856-bfd22200-ed44-11ea-84cb-52d83d03d689.png)

## First header row 
cell color: B3: `#0DC0DC`
font: noto sans, base font size
font treatment: bold
font color: B2: `#344456`
alignment: content driven

## Second header row (if present)
cell color: B4: `#24739E`
font: noto sans, base font size
font color: white `#FFFFFF`
alignment: content driven

## Non header rows
font: noto sans, base font size
font color: black `#000000`
alignment: content driven

## ALL Cell borders
Cell border color: G2: `#F2F2F2`
Cell border width: 1px 
Applies to border-left, right, top, bottom

## Cell corners
please make them all right angles contrary to what exists in the pdf

# Type 2 `text-heavy` Table
![image](https://user-images.githubusercontent.com/11299125/92045018-25bea980-ed45-11ea-9456-e5ec5dcdd968.png)

## all header rows 
cell color: G2: `#F2F2F2`
font style: noto sans
font treatment: bold
font color: B2: `#344456`
cell alignment: content driven

## Non header rows
font: noto sans, base font size
font color: black `#000000`
alignment: content driven

## Cell border
BOTTOM ONLY FOR HEADER
color: B5: `#D6D9DD`
border width: 1px

## Cell corners
please make them all right angles contrary to what exists in the pdf

# Alternate color schema for table 1 (default table)
For _Astronomy_
![Screen Shot 2020-10-26 at 12 43 18 PM](https://user-images.githubusercontent.com/11299125/97208232-e59a0700-1788-11eb-804b-0c1b2ada1ada.png)

Table body and cell borders should be the same. Only difference is the colors in the header row

## Header row
cell color: Y1: `#E3A354`
font style: noto sans
font treatment: bold
font color: P1: `#3B2746`
cell alignment: content driven
second header row color: P2: `#772949`
second header row font color: white `#FFFFFF`
Everything else should be the same

# Type 3 `unstyled` Table #3136
- Should be the same as the default table, but without the headers.
- Spans full width

**Comment by ajluk** [comment]
@lwtchu Here is how the top titled tables in Business Ethics:
![image](https://user-images.githubusercontent.com/55203598/95313639-a450be80-0890-11eb-96b8-21074753ba09.png)
Do you want me to make the top title appear on the next page if table jumps to next page?

**Comment by ajluk** [comment]
I have also added some additional spec for:
Td, Th
        padding-top: table-v-spacing(1),
        padding-bottom: table-v-spacing(1),
        padding-left: table-h-spacing(1),
        padding-right: table-h-spacing(1),
![image](https://user-images.githubusercontent.com/55203598/95315208-7f5d4b00-0892-11eb-90dc-a9cb931ab058.png)
Table (`table` tag)
    width: 100%
    border-collapse: collapse,
![image](https://user-images.githubusercontent.com/55203598/95315127-65236d00-0892-11eb-831a-3432fe478e39.png)
TableContainer (`os-top-titled-container`)
margin-bottom: table-v-spacing(2),
        display: table,
        margin-left: auto,
        margin-right: auto,

**Comment by lwtchu** [comment]
@ajluk it looks good :eyes: !

**Comment by ajluk** [comment]
Hi @lwtchu this how the tables with no specific class (have only os-table) look like in Business Law: 
![image](https://user-images.githubusercontent.com/55203598/97023048-3d502c80-1555-11eb-89d3-c93f42872ec8.png)
They have no header rows as far as I checked in Business Law. Is it expected? There is no `thead` tag:
![image](https://user-images.githubusercontent.com/55203598/97023206-77213300-1555-11eb-9b1b-1496bad65bec.png)
as there is for `top-titled tables` in the same book: 
![image](https://user-images.githubusercontent.com/55203598/97023472-d67f4300-1555-11eb-96fd-208ede7d6224.png)
Is that ok?

**Comment by lwtchu** [comment]
@ajluk these are okay. if those no thead, there's no thead. we can make a turn through the pdf again later to move content if needed. thank you for looking out~

**Comment by lwtchu** [comment]
actually i'm going to go ahead and make a content card for the theads. and we'll fix it at some point - but we shouldn't have it hinder your work!

**Comment by ajluk** [comment]
@lwtchu Thank you! That's not a problem. I just wasn't sure if I have understand the specs correctly or should I style some `trows` as well for such tables.

**Comment by ajluk** [comment]
@lwtchu Here is how the default tables with second header row looks like styled in Introduction to Business: 
![image](https://user-images.githubusercontent.com/55203598/97871782-3c698880-1d15-11eb-917e-3480dd621f39.png)
![image](https://user-images.githubusercontent.com/55203598/97872391-3d4eea00-1d16-11eb-9e1b-dbf09fe6d6e4.png)
I couldn't find top-titled tables in this book though. Is it possible that they aren't there and there will be some content changes in the future adding them? I'm asking because I have added styles for top titled tables as well in case there will be some for Introduction to Business, but let me know if should keep it just in case or remove it.

**Comment by lwtchu** [comment]
@ajluk 🤔 it looks like these should be top-titled...let me double check the content.

**Comment by lwtchu** [comment]
@ajluk actually it's okay. this looks fine - if it's too much effort to remove, it's also ok to leave it in there. i think these should have the class but 🤔 they never used it.

**Comment by ajluk** [comment]
No, it's ok. I can remove it. I'm only  not sure what do you mean by "should have the class but they never used it" :thinking:

**Comment by lwtchu** [comment]
@ajluk it looks like these should have been top-titled but it wasn't used. but it's okay - it's been printed like this and no one has said anything.

**Comment by ajluk** [comment]
Oh, I understand. Thank you! I wasn't sure if you meant used in the content.

**Comment by ajluk** [comment]
@lwtchu I have made some fixes in Default/Top Titled Table shape components, because I have noticed that there are borders missing between the th tags in some places and there is also unnecessary top border between the first tr in the table body and the thead visible only when the zoom is set to 150% for pdf file. I have found it accidentally. Here is how it looked before in Intro Business
![image](https://user-images.githubusercontent.com/55203598/100335972-e2877600-2fd5-11eb-854b-f1295a2416db.png)
Here is how it looks now: 
![image](https://user-images.githubusercontent.com/55203598/100340570-b2db6c80-2fdb-11eb-959c-f21df6e05562.png)

Here are the specs I have added:
![image](https://user-images.githubusercontent.com/55203598/100362879-458c0380-2ffc-11eb-9bd6-877cbc7f3298.png)
**FirstTableHeadCellFirstRow**
 border-left-style: none,
        border-left-color: transparent,
        border-left-width: 0rem,
        border-right-style: solid,
        border-right-color: #F2F2F2, (same as in the specs above)
        border-right-width: 0.08rem, //1px converted to rem
![image](https://user-images.githubusercontent.com/55203598/100363015-710eee00-2ffc-11eb-8139-c5f12931328b.png)
**LastTableHeadCellFirstRow**
border-left-style: none,
        border-left-color: transparent,
        border-left-width: 0rem,
        border-right-style: solid,
        border-right-color: #F2F2F2, (same as in the specs above)
        border-right-width: 0.08rem, //1px converted to rem
![image](https://user-images.githubusercontent.com/55203598/100363604-3f4a5700-2ffd-11eb-97cb-f76daacead6c.png)
 **Table Head Cell in the First Row** (not only child)
        color: #344456;
        font-family: Noto Sans, StixGeneral;
        font-weight: bold,
        font-size: font-scale(0),
        padding-top: table-v-spacing(1),
        padding-bottom: table-v-spacing(1),
        padding-right: table-h-spacing(1),
        padding-left: table-h-spacing(1),
        background-color: #0DC0DC; (same as in the specs above)
        border-left-style: solid,
        border-left-color: #F2F2F2; (same as in the specs above)
        border-left-width: 0.08rem, //1px converted to rem
        border-right-style: solid,
        border-right-color: #F2F2F2; (same as in the specs above)
        border-right-width: 0.08rem, //1px converted to rem
    )
);

![image](https://user-images.githubusercontent.com/55203598/100363323-dbc02980-2ffc-11eb-8a20-a09f2e617988.png)
**TableHeadCellFirstRowOnlyChild** (should have no borders)
color: enum('ValueSet:::REQUIRED'),
        font-family: enum('ValueSet:::REQUIRED'),
        font-weight: bold,
        font-size: font-scale(0),
        padding-top: table-v-spacing(1),
        padding-bottom: table-v-spacing(1),
        padding-right: table-h-spacing(1),
        padding-left: table-h-spacing(1),
        background-color: #0DC0DC; (same as in the specs above)

**Comment by ajluk** [comment]
@lwtchu here is how the text-heavy top titled tables looks like in Entrepreneurship: 
![image](https://user-images.githubusercontent.com/55203598/100366570-42474680-3001-11eb-9d5c-5a2e7db69636.png)

Here are the specs I have added for them:
![image](https://user-images.githubusercontent.com/55203598/100366671-673bb980-3001-11eb-85f1-b0cb6e82d9ed.png)
TableHeadCellWithBottomBorder
        color: #344456;
        font-family: Noto Sans, StixGeneral;
        font-weight: bold,
        font-size: font-scale(0),
        padding-top: table-v-spacing(1),
        padding-bottom: table-v-spacing(1),
        padding-right: table-h-spacing(1),
        padding-left: table-h-spacing(1),
        background-color: #F2F2F2;
        border-bottom-style: solid,
        border-bottom-color: #D6D9DD;
        border-bottom-width: 0.08rem, //1px converted to rem

**Comment by wilkus27** [comment]
@lwtchu In College Success there are also tables with class `unstyled`. They appear at the beginning of each section:

![image](https://user-images.githubusercontent.com/40228854/101350300-09c02c00-388f-11eb-8e94-d4ec188ddfd4.png)

How they should be styled?

**Comment by lwtchu** [comment]
@wilkus27 if we apply the regular table style - does it span the full page?
![Screen Shot 2020-12-07 at 11 22 03 AM](https://user-images.githubusercontent.com/11299125/101383196-741ca080-387e-11eb-8fbf-c21dd637ef17.png)

if not i can add a new card since this should be specific to college success

**Comment by lwtchu** [comment]
@wilkus27 actually i used my brain a bit and i don't think it will - here's the new card: #3136

**Comment by lwtchu** [comment]
@ajluk i just saw your message - thank you for finding that and making the borders clearer

**Comment by ajluk** [comment]
@lwtchu Should the tables in Astronomy all have the alternative color schema or just the default type?
What color should we use for second header rows?

**Comment by lwtchu** [comment]
@ajluk oh no i seem to have forgotten about astronomy when i madet his card

cell color: Y1: `#E3A354`
font color: P1: `#3B2746`
second header row color: `P2: #772949`

**Comment by lwtchu** [comment]
@ajluk actually it's under the "Alternate color schema for table 1 (default table)" header :joy: sorry - i added it at the end which might've been hard to find.

**Comment by ajluk** [comment]
@lwtchu Yes, I have found it, but default table is table 2 as I understood from info above and I got confused :smile: . We have created two kinds of tables for the cardboard theme (default, top-titled and text-heavy) in the code based on the classes. So in that case top-titled tables should have the regular schema and default the alternate?

**Comment by lwtchu** [comment]
@ajluk 🤔 i'm not sure i'm following. 

astronomy should have both table styles (default/top titled) with the yellow alternate color schema. i think top titled is that the first row is just blank (white bg) with the text in black, bold and centered - correct?

**Comment by ajluk** [comment]
@lwtchu Yes, you're right. They are using the same shape even in cardboard, but have different classes, that's why I was asking (default and regular tables don't have separate classes), so I guess what you have meant above is that both of the tables (default and regular) should have yellow color schema in Astronomy except text-heavy tables, right?

**Comment by lwtchu** [comment]
@ajluk yes - 

what are the different classes? i need to check cause i was pretty sure the tables in astronomy were using `top-titled` :eyes: do you have an example. 

Default and regular tables shouldn't have a class. And top-titled and text-heavy should be the other two that exist within the theme. I think top-titled is the only one used in Astronomy but please correct me if I'm wrong. :eyes:

**Comment by ajluk** [comment]
@lwtchu Yes, but beside that we have also tables without specific classes. They were called basic tables previously. And we have also tables with class `text-heavy` and unstyled (just in college success).

**Comment by lwtchu** [comment]
@ajluk okay sorry i got confused with how we're naming things :joy: the basic/default one and top titled for astronomy should match the alternate color schema ..hope that's clear D: did you have any other questions that you need clarification on?

**Comment by ajluk** [comment]
@lwtchu No problem, I got confused too. It's all clear now. Thank you! :relaxed:

**Comment by ajluk** [comment]
Screenshot for reference of the tables with alternate color schema in Astronomy: 
![image](https://user-images.githubusercontent.com/55203598/102520120-a8206e80-4093-11eb-8e2e-074aaeced120.png)

**Comment by lwtchu** [comment]
Updated to rope in unstyled table into this documentation
