### ISSUE TITLE
cardboard theme - key terms/glossaries

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2742]
![Screen Shot 2020-09-02 at 7 48 58 PM](https://user-images.githubusercontent.com/11299125/92058911-67efe700-ed55-11ea-8464-a1ae6934897e.png)

## Icon
https://drive.google.com/file/d/16DigLLGSLRxeyuhcHkbJaADdAy3PyXrh/view?usp=sharing 

## Header, text and fonts
- Please follow fonts and settings for all text here #2644 
- Please implement a hanging indent functionality 

![Screen Shot 2020-10-26 at 7 25 50 PM](https://user-images.githubusercontent.com/11299125/97242169-201f9600-17c1-11eb-9f48-cd2a9b3c12d4.png)
For Astronomy

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/95176215-d8f34600-07bc-11eb-8312-2cf9c13f8d07.png)

I changed specs for title. Based on #2644 H2 should be bold and Noto Sans, but I applied Roboto Condensed like on the screenshot which you provided at the beginning. Also I see that color is different there. Should I change it? I applied #24739E .

**Comment by wilkus27** [comment]
Oh and also for the icon I applied such specs:

```
  height: 2.1rem;
  width: 2.1rem;
  padding-right: 8px;
``` 
Is it ok?

**Comment by lwtchu** [comment]
@wilkus27 oh yes - i think that looks good. sorry i didn't realize the icon needed sizing.
