### ISSUE TITLE
Cardboard - summary

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2743]
![Screen Shot 2020-09-02 at 7 55 54 PM](https://user-images.githubusercontent.com/11299125/92059249-5c50f000-ed56-11ea-8f52-fbba4b6da715.png)

## Icon
https://drive.google.com/file/d/1U32rkP-W_UuQ0Va5PLUIhFEGkztm9CVk/view?usp=sharing

## Notes
- Broken out by section
- Since the section link is clickable - can we apply the link treatment there
- Font is the same as the base font

![Screen Shot 2020-10-26 at 7 31 10 PM](https://user-images.githubusercontent.com/11299125/97242421-d6837b00-17c1-11eb-9dfc-2cfdc38faea7.png)
For Astronomy

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/95451124-a043a000-0967-11eb-9d11-644404094027.png)

For links I applied font-size: `font-scale(1)`, font: Noto Sans Bold as like for h3 titles and color is a link color (B7: #027EB5). This is what you meant by "the link treatment"? Or should I apply title color (B4: #24739E)?

**Comment by lwtchu** [comment]
@wilkus27 yeah link treatment like the standard link blue and underline. 

i think this looks good tho.

**Comment by kswanson33** [comment]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/26280712/102274772-65736080-3ef2-11eb-88fa-93f44f8937df.png">

@lwtchu Here's how it looks with the Astronomy header and standard links. Is `B7` still a good color for the links in Astronomy, or should it be changed to something else?

**Comment by lwtchu** [comment]
@kswanson33 we'll be keeping all links across library the same :) so that color should be fine
