### ISSUE TITLE
business ethics - assessment questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2744]
![Screen Shot 2020-10-20 at 4 55 11 PM](https://user-images.githubusercontent.com/11299125/96648498-0da2e980-12f5-11eb-88af-6bc024653d00.png)

## Icon
https://drive.google.com/file/d/1-IA4Gbm1OlPC2bg8lSedIUUIrjvZdBrB/view?usp=sharing

## Notes
- Exercise number is bold
- Make sure any list that is indented is bolded (h-grid 1?) 
- Font is the same as the base font

**Comment by wilkus27** [comment]
@lwtchu based on your comment here https://github.com/openstax/cnx-recipes/issues/2748#issuecomment-707183053 should I also remove space from EOC exercises? This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/95844265-00ac5600-0d49-11eb-9b71-a5b88d02fea5.png)

**Comment by lwtchu** [comment]
@wilkus27 can we try with 0.7rem after the exercise? i want to tighten it up a bit but not too much to where it's sticking. (ideally halving the space between each exercise)

**Comment by wilkus27** [comment]
@lwtchu Here is the effect:

![image](https://user-images.githubusercontent.com/40228854/95884453-6bc35000-0d7c-11eb-9b6b-c774ad90feec.png)

**Comment by lwtchu** [comment]
@wilkus27 i just realized that the screenshot here was different and wrong. 🤦‍♀️  i updated it but sorry for the confusion and lack of attention to detail on my part here 😂

**Comment by wilkus27** [comment]
@lwtchu No problem :relaxed: Specs listed in notes were descriptive so I didn't have problems to style it :slightly_smiling_face:

**Comment by brittweinstein** [comment]
@lwtchu I'm closing this because the work for this title is done and we can use the documentation by searching the label.
