### ISSUE TITLE
business ethics - endnotes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2745]
Within Business Ethics, there are endnotes in the chapter that collate to the end of the chapter.

# Within text
![Screen Shot 2020-09-02 at 8 03 31 PM](https://user-images.githubusercontent.com/11299125/92059642-66272300-ed57-11ea-923f-b1674d062c12.png)

## Mark up
```
This is a sentence.<cite id="rf-001-a" target-id="rf-001"><note class="delete-me" display="inline"/></cite>
```

## Specs
color: standard link color
text treatment: NO UNDERLINE

# End of chapter
![Screen Shot 2020-09-02 at 8 02 52 PM](https://user-images.githubusercontent.com/11299125/92059623-58719d80-ed57-11ea-9717-b323cb65ebbd.png)

## Mark up
```
<section class="references">
  <title>Endnotes</title>
  <note id="rf-001"><link target-id="rf-001-a"><span>*</span></link><span>This is an endnote.</span></note>
</section>
```

## Icon
https://drive.google.com/file/d/1COYw-42axWZWtonKiuHNoYMjdUEviB8q/view?usp=sharing

## Specs
THIS IS THE ONLY THING THAT DEVIATES FROM THE STANDARD FONTS
- font-scale(-1): 7.5pt, 9.6px, 0.8rem
- numbering: the number is a link so it should have the blue link color and WITHOUT the underline (like the reference number above)

**Comment by wilkus27** [comment]
@lwtchu This is how it looks with styles:

![image](https://user-images.githubusercontent.com/40228854/95568664-cf6c1700-0a24-11eb-9f90-731849edd9e2.png)

Is it ok?

**Comment by lwtchu** [comment]
@wilkus27 can we make sure there's a period after the number. besides that, it looks pretty good.

**Comment by wilkus27** [comment]
@lwtchu I made fixes in recipe for title and divider. This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/95743491-24609500-0c92-11eb-859c-df54e24733eb.png)

**Comment by lwtchu** [comment]
@wilkus27 beautiful! thank you~

**Comment by brittweinstein** [comment]
@lwtchu I will close because the title that this was for is done and we can still use this as documentation by searching with the label.
