### ISSUE TITLE
cardboard theme - index

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2746]
![Screen Shot 2020-09-02 at 8 10 21 PM](https://user-images.githubusercontent.com/11299125/92060040-68d64800-ed58-11ea-94f1-e03962b54b9c.png)

## H1 (Title)
font-size: follows standard header structure set in #2644 
font style: roboto condensed
color: B4 `#24739E` for astronomy - P2: `#772949` 

## Letter (index group label)
font-size: font-scale(2): 12.96pt, 16.8px, 1.4rem
font style: Noto Sans
color: B2: #344456 for astronomy -  P1: `#3B2746`

3 column
The links for the page numbers - color is the standard link color `#027EB5`

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/95754515-73fb8c80-0ca3-11eb-8735-07ae142b6e05.png)

I think there is a mistake in the specs above for H1. B2 is #344456. I applied B4 (#24739E) as for other titles from te book. Is it ok?

**Comment by lwtchu** [comment]
@wilkus27 ah nice catch sorry about that. i updated the specs. but this looks good.

**Comment by wilkus27** [comment]
@lwtchu What is color scheme for Astronomy?

**Comment by lwtchu** [comment]
let's stick with P2: `#772949` for index and P1: `#3B2746` the letters. @wilkus27

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/102758827-9bda3100-4373-11eb-8ed8-cb0a39b87e28.png)

Note: links will be styled in another issue.

**Comment by lwtchu** [comment]
@wilkus27 looks good -thank you :)
