### ISSUE TITLE
cardboard theme - answer key

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2748]
![Screen Shot 2020-09-02 at 8 20 01 PM](https://user-images.githubusercontent.com/11299125/92060553-b99a7080-ed59-11ea-84c7-ddb58a7c053c.png)
- headers follow the regular schema
- exercises have the standard bold number.
- all one column
- separated by chapter

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/95736461-90d59700-0c86-11eb-8868-f20dc409c870.png)

Is it ok? Also I want to ask about bars. Do we want apply them also in this theme? If yes, what color we should use?

**Comment by lwtchu** [comment]
@wilkus27 can we reduce the spacing after each exercise? it should follow one after the other with no double spacing

1. ...
2. ... 
3. ...

As for the bar, let's go with B4: `#24739E`. I added it here #2748 - would you prefer it to be elsewhere?

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/95843542-1bca9600-0d48-11eb-913b-96c66122c624.png)

Is it ok?

About link, it leads to this issue. Is it intentional? :thinking:

**Comment by lwtchu** [comment]
@wilkus27 x_x no i meant to put #2712
