### ISSUE TITLE
Wrong numbering of footnotes

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2753]
There is problem with order of footnote points inside tables:

![image](https://user-images.githubusercontent.com/40228854/92118317-9f62a000-edf6-11ea-976b-6962c3a432a1.png)

_Originally posted by @wilkus27 in https://github.com/openstax/cnx-recipes/issues/2287#issuecomment-686474936_

**Comment by MartaSztuka** [comment]
## PASSED
### Footnotes numbering in Fizyka 2![Screenshot from 2020-09-23 15-07-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8d3b0868-c427-4678-b48b-57f8e07a0c67)
