### ISSUE TITLE
Bio1e - Content not collating to EOC

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#2757]
# What happened?

I Biology 1e in Rex, some content is not getting kicked to the EOC, namely Art Connections and Free Response (known as Visual Connection Questions Critical Thinking Questions in 2e respectfully) 
This may be a class issue.

# Reproducibility Details
https://rex-web.herokuapp.com/books/185cbf87-c72e-48f5-b51e-f14f21b5eabd@12.1/pages/1-1-the-science-of-biology?archive=https%3A%2F%2Farchive-staging.cnx.org#fig-ch01_01_05

- **Does this happen in one place, a few places, or everywhere?**:
Throughout

# Environment:
Rex on Staging
- **Book(s)**: Biology
- **URL/Server**: https://rex-web.herokuapp.com/books/185cbf87-c72e-48f5-b51e-f14f21b5eabd@12.1/pages/1-1-the-science-of-biology?archive=https%3A%2F%2Farchive-staging.cnx.org#fig-ch01_01_05
- **Location (page number, chapter/section)**: 1.1
- **Browser**: Chrome

# Screenshots

![2020-09-09_12-08-49.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/bbc9e703-5445-4e31-a069-bb7b5b24bfe2)

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #1887](https://github.com/openstax/content-managers/issues/1887) via [**ZenHub**](https://www.zenhub.com/)
