### ISSUE TITLE
corn - precal/precalcoreq style - try it's not contained in margins

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2758]
![Screen Shot 2020-09-09 at 5 40 37 PM](https://user-images.githubusercontent.com/11299125/92662054-a2143800-f2c3-11ea-9630-92ae8489c574.png)

I believe when a Try It is nested too far down (maybe 3 levels in?) it no longer obeys the rules of margins.

This is in College Algebra 8.3 or Precalculus. Module - The Parabola 

Or it could be a list is nested in it? I'm not sure. This happens about twice in the book and I can't seem to pinpoint why.

**Comment by wilkus27** [comment]
@lwtchu I fetched the newest version of coreq algebra and baked it on t.t. This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/93337713-ccb54200-f829-11ea-8bac-bae02aa83cb9.png)

I checked and list from the screen is `ul` with `[data-labeled-item="true"]` , so when I merge PR https://github.com/openstax/cnx-recipes/pull/2769 it will look like that:

![image](https://user-images.githubusercontent.com/40228854/93341721-bcec2c80-f82e-11ea-9abe-1b9ec3a8cd34.png)

Is it ok?

**Comment by lwtchu** [comment]
@wilkus27 yes! thank you. i think before it just...kept running off the page and i wasn't sure why. but if it's fixed that's good.

**Comment by MartaSztuka** [comment]
### PASSED
#### College Algebra![Screenshot from 2020-09-22 18-06-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/60b037a6-495a-4863-87f5-ee809ad1e6cd)
#### College Algebra coreq![Screenshot from 2020-09-22 18-07-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8716cadc-df99-4893-b8e4-aa4091f7f53e)
#### Precalculus![Screenshot from 2020-09-22 18-09-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bb11ea38-a81f-4de6-a2f5-653d2dd1ffa1)
