### ISSUE TITLE
corn - precalculus/precalculus-coreq - Lists in EOC paras need proper indentation

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2759]
![Screen Shot 2020-09-09 at 4 38 12 PM](https://user-images.githubusercontent.com/11299125/92662252-0fc06400-f2c4-11ea-81c4-39fd7767fc5e.png)

9.3 Geometric Squares - College Algebra or College Algebra with Corequisite

Happens only once so it's liveable in its current state right now.

Can we please have the proper indentation for lists here also?

**Comment by ajluk** [comment]
How ti looks now:
![image](https://user-images.githubusercontent.com/55203598/93448129-8b796c80-f8d3-11ea-8c89-c8039ef766f1.png)

**Comment by MartaSztuka** [comment]
## PASSED
### College Algebra
![Screenshot from 2020-09-18 15-10-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c6f91c72-50b7-4705-9326-6e47646a67ae)
### College Algebra coreq![Screenshot from 2020-09-18 15-12-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d51fcb3c-3613-408b-bb52-b89b265c4d37)
