### ISSUE TITLE
corn - precalculus/precalculus-coreq - tokens need to be supported in labeled lists also

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2760]
![Screen Shot 2020-09-09 at 4 10 03 PM](https://user-images.githubusercontent.com/11299125/92662392-5910b380-f2c4-11ea-971b-4944fb336a0b.png)
![Screen Shot 2020-09-09 at 2 38 38 PM](https://user-images.githubusercontent.com/11299125/92662394-5ada7700-f2c4-11ea-9703-7522b3d40905.png)

This happens a few times in college algebra.
6.3 College Algebra/College Algebra with Coreq for the screenshot that says "Converting from Logarithmic Form to Exponential Form"

**Comment by wilkus27** [comment]
@lwtchu Those lists should have class `circled`. We are using attribute `list-type="labeled-item"` to remove bullets from the lists.

**Comment by lwtchu** [comment]
@wilkus27 i thought the `circled` class moved things around if they fit. in these instances i don't want the content to move, i just need them to appear one after th eother. is it possible to have just the `<span class="token">` work in a `labeled-item` list?

**Comment by wilkus27** [comment]
@lwtchu Yes, I was able to apply that. This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/93302364-23a32300-f7fa-11ea-9375-55a37e5ba8f8.png)

**Comment by lwtchu** [comment]
@wilkus27 thanks! this looks great <3

**Comment by MartaSztuka** [comment]
@lwtchu  Do we want to add circled lists in other Examples with abc lists?
### College Algebra
#### Fixed example
![Screenshot from 2020-09-18 17-05-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/237073f0-ad7a-43bb-b6a1-397a10e73acd)
#### List without circle list ![Screenshot from 2020-09-18 17-09-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/baa7a354-8652-4062-b354-2769bfd76be0)
### College Algebra coreq![Screenshot from 2020-09-18 18-07-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a4cd28c2-a773-4892-9a2e-a8da99307cdd)

**Comment by lwtchu** [comment]
@MartaSztuka yes - can you ignore those for now? there were just a few that were missed. but we've been trying to convert as many of them as we  could during productin of the book.

**Comment by brittweinstein** [comment]
@lwtchu based on your comment above, would you call this card done?

**Comment by lwtchu** [comment]
@brittweinstein oh right. i'm always scared to close cards :joy: but i can close it. :eyes:
