### ISSUE TITLE
corn - precalculus recipe - suppressed coreq content numbering impacting book

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2762]
![Screen Shot 2020-09-10 at 9 23 23 AM](https://user-images.githubusercontent.com/11299125/92744706-530fe680-f347-11ea-890d-bdb5cf25ec6b.png)

Hello! There's a slight deviation in this recipe compared to the `precalculus-coreq` recipe.

The precalculus-coreq recipe restarts numbering for things outside of the `coreq-skills` class. I need the same functionality in the regular `precalculus` recipe.

Thanks! This is pretty urgent. Will discuss priority with y'all when calls are done? Idk

I migrated Fresh Fresh content to Katalyst01. The entire College Algebra book SHOULD have the coreq-content on it.

**Comment by brittany-johnson** [comment]
Numbering should now be correct in precalc recipe:
<img width="954" alt="Screen Shot 2020-09-10 at 11 20 42 PM" src="https://user-images.githubusercontent.com/24909007/92858940-48436900-f3bc-11ea-85c8-c09d6eec16ff.png">

**Comment by meeragovindaraju** [comment]
Looks good in Algebra & Trig

![Screen Shot 2020-09-11 at 1 44 14 PM](https://user-images.githubusercontent.com/33066187/92961513-f854b880-f434-11ea-8d80-98353d76431e.png)

**Comment by meeragovindaraju** [comment]
Looks good in the College Algebra

![Screen Shot 2020-09-11 at 2 40 40 PM](https://user-images.githubusercontent.com/33066187/92966309-ed9e2180-f43c-11ea-9920-219893600a64.png)

**Comment by meeragovindaraju** [comment]
Looks good in precalc

![Screen Shot 2020-09-11 at 3 33 53 PM](https://user-images.githubusercontent.com/33066187/92970407-3efddf00-f444-11ea-83ed-582bfa1d7ace.png)
