### ISSUE TITLE
Images on top in solutions in the EoC

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2766]
In HS Statistics there are images placed on top of the solution containers but mixin for such containers doesn't cover them (they are present in the EoC sections not EoB of the book): 
![image](https://user-images.githubusercontent.com/55203598/93096966-4b34a700-f6a5-11ea-8502-fb72070d26b6.png)

**Comment by MartaSztuka** [comment]
## PASSED
### HS Statistics![Screenshot from 2020-09-23 16-23-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d5388a60-d083-48e3-8a05-2bd7d3db35fe)
