### ISSUE TITLE
college success - end of chapter content

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2774]
![Screen Shot 2020-09-16 at 2 08 20 PM](https://user-images.githubusercontent.com/11299125/93381343-23208180-f826-11ea-819d-32f8af0caba3.png)

College Success is unique in that it is comprised of the following EOC sections, but they are short and do not need to be separated out by module.

Font should follow the schema set by #2644 

Icons and classes/structure are as follows:

- Summary `class="summary"` icon: https://drive.google.com/file/d/1U32rkP-W_UuQ0Va5PLUIhFEGkztm9CVk/view?usp=sharing
- Career Connection `class="career-connection"` icon: https://drive.google.com/file/d/1tZDE2I5JPF6Ggo676xs79VSs4izviUKQ/view?usp=sharing
- Rethinking `class="rethinking"` icon: https://drive.google.com/file/d/1lVezUadPa780bzW-XuOYTP_kbmi0_UmO/view?usp=sharing
- Where to go from here? `class="where-go"` icon: https://drive.google.com/file/d/15IaTMSNVux44rZrFxSyE_ZlYFoXiK0xZ/view?usp=sharing

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-10 10-15-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1b11cb15-e1c5-40a9-9d2e-5fa60cd8d29a)
