### ISSUE TITLE
cardboard theme - supporting colwidth/datawidth attribute

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2776]
![Screen Shot 2020-09-16 at 3 39 31 PM](https://user-images.githubusercontent.com/11299125/93390131-d55e4600-f832-11ea-9339-832b9346c000.png)

# in the cnxml
![Screen Shot 2020-09-16 at 3 35 27 PM](https://user-images.githubusercontent.com/11299125/93389941-89ab9c80-f832-11ea-8bc5-c8de168db661.png)

# in the html
![Screen Shot 2020-09-16 at 3 37 12 PM](https://user-images.githubusercontent.com/11299125/93389956-8e705080-f832-11ea-8a7f-24f73643c8ab.png)

location in college success: 8.3 Communication and Technology 

In the content, there is a way for a specific width to be set so that the boxes are equal in size or if we need a table to display a certain way outside of the default setting.

We need to make sure that this happens within the PDF as well. In this case, due to limitations in oer.exports, we had to set it at 2.5rem in order for the PDF to render a specific way. Let me know if this can be supported or if there's any attributes we can fix for the new pipeline.

I also need to find if this affects any book in the library, as it is an available attribute in the CNXML. However, I do know College Success specifically uses this.

This also used to be a shot in the dark to figure out what oer.exports could do. Could we develop some set standard for the CMs to use that will generate something? (Ping me when you get to this card :D)

**Comment by wilkus27** [comment]
@lwtchu I was trying to style it. It's very hard to find the proper value for rem. It depends on a basic font size set for the root. In this theme it's `12px`.

For example, here is an effect for `12.5rem`:

![image](https://user-images.githubusercontent.com/40228854/101618797-bd9df480-3a12-11eb-84e2-c61219b63b41.png)

And here for `12rem`:

![image](https://user-images.githubusercontent.com/40228854/101619740-f8545c80-3a13-11eb-8dda-063ba4fde543.png)

I was also trying to use percentages (25% for each column):

![image](https://user-images.githubusercontent.com/40228854/101623486-ce516900-3a18-11eb-8b4b-5123202ff9f3.png)

I think the best way for this kind of issues is to specify what effect is required. For example, that table should be stretched to full width of container/page and all columns should have the same width. If table should have different size (then full width) we need a value in inches or px to be able to find a proper value in rem. 

If we are ok with using percentages, we need an information about ratio. For example, table width is 3/4 width of the container and each column should be 1/4 of table width.

Let me know what do you prefer, rems or %.

Also we need to think what information should be put in the `col` attribute to be more descriptive.

**Comment by lwtchu** [comment]
@wilkus27 we initially did em since it was the only thing that worked on the old pipeline.

would it be better if we changed it to percentages? so for that example above, it should be 25% for each column so that they'll be equal in width. i can test with a few examples in college success if that sounds good to you.

**Comment by Stackblocks** [comment]
@wilkus27 It seems like you did a pretty thorough investigation into this and if you didn't see anything that was uniquely limiting about using percentages (issues with odd numbers of columns, large numbers of columns, the pipeline not working with percentages consistently etc.) then it's worth a shot at the very least. If necessary, we can change it later but I don't believe it will be.

**Comment by lwtchu** [comment]
Link to thread https://openstax.slack.com/archives/CBW9DFKGF/p1607957021085000

We will use the proportion value for colwidth (`1*`). Second best case would be percentages, but we should stick to the proportions.
