### ISSUE TITLE
library wide - pdf bookmarks

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2778]
# Issue
![image](https://user-images.githubusercontent.com/11299125/93482749-a93fd500-f8c5-11ea-9937-fe911b616c77.png)
![image](https://user-images.githubusercontent.com/11299125/93482765-acd35c00-f8c5-11ea-8f38-1f00ab3a6722.png)

# Acceptance Criteria
According to this https://www.princexml.com/doc/11/pdf-bookmarks/ we can target headers? If so can we go down to H2 (module title, ex 1.1 Real Numbers) like in the old pipeline
https://files.slack.com/files-pri/T1FDQ2DJS-F01AW8K612P/image.png

**Comment by MartaSztuka** [comment]
## PASSED
### HS Statistics
![Screenshot from 2020-09-25 17-21-54](https://user-images.githubusercontent.com/47241114/94285157-a1ca9c80-ff53-11ea-95c4-fc4e7924b8d6.png)
### College Algebra coreq
![Screenshot from 2020-09-25 17-21-19](https://user-images.githubusercontent.com/47241114/94285094-8f506300-ff53-11ea-81d6-f818e8e8fb6e.png)
### Precalculus
![Screenshot from 2020-09-25 17-36-53](https://user-images.githubusercontent.com/47241114/94286777-bdcf3d80-ff55-11ea-85b9-b9c073480678.png)
