### ISSUE TITLE
introduction to business - summary of learning outcomes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2782]
![Screen Shot 2020-09-21 at 3 59 36 PM](https://user-images.githubusercontent.com/11299125/93820963-86922100-fc23-11ea-9b60-fd9a7c95694c.png)

## Icon
https://drive.google.com/file/d/1U32rkP-W_UuQ0Va5PLUIhFEGkztm9CVk/view?usp=sharing

## Notes
- Broken out by section
- Since the section link is clickable - can we apply the link treatment there
- Font is the same as the base font 
- I believe the "1. How do business and not for profit ..." text should be in the content already

**Comment by ajluk** [comment]
@lwtchu Here is how Summary looks after styling: 
![image](https://user-images.githubusercontent.com/55203598/98229652-75df0580-1f5a-11eb-83ac-e04fbdc01aba.png)

**Comment by lwtchu** [comment]
@ajluk beautiful ~!

**Comment by brittweinstein** [comment]
@lwtchu I'm closing this because the work for this title is done and we can use the documentation by searching the label.
