### ISSUE TITLE
introduction to business - preparing for tomorrow's workplace skills

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2783]
![Screen Shot 2020-09-21 at 4 21 41 PM](https://user-images.githubusercontent.com/11299125/93822968-a2e38d00-fc26-11ea-87d9-df5f53549e23.png)

### Icon
https://drive.google.com/file/d/1-IA4Gbm1OlPC2bg8lSedIUUIrjvZdBrB/view?usp=sharing

### Notes
- follows regular schema for text and header
- DOES NOT break up by module like other EOC 
- should just be a list of 1, 2, 3, 4 5...etc content.

**Comment by ajluk** [comment]
@lwtchu This how this section looks styled: 
![image](https://user-images.githubusercontent.com/55203598/98370184-72bb4680-203a-11eb-9a8b-80bddf57f1cf.png)
Could you explain what do you mean by "does not break up"? It shouldn't break to next page like on the screenshot below:
![image](https://user-images.githubusercontent.com/55203598/98370362-c037b380-203a-11eb-90b2-747fdfcb8ede.png)

**Comment by lwtchu** [comment]
@ajluk sorry! it doesn't break up in that it's not separated by module like some other sections that are eoc. i'll clarify my statement. thank you though this looks good as is

**Comment by brittweinstein** [comment]
@lwtchu I'm closing this because the work for this title is done and we can use the documentation by searching the label.
