### ISSUE TITLE
Mixins modify_addFirstElementClass() and modify_tagExerciseWithFirstElementClass() have some code repetitions

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2784]
During working on issue  #2766 a problem with code refactoring has occurred. The goal we wanted to achieve was to make less code duplicates in the mixins(`modify_addFirstElementClass()`, `modify_tagExerciseWithFirstElementClass()`)It was described by Natalia in this comment:
https://github.com/openstax/cnx-recipes/pull/2767#discussion_r489411557
The main obstacles in doing this were the nested maps: `$Config_BookCompositePages`, `$Config_ChapterCompositePages` when we would like to add some conditionals and variables based on internal the map key `type`.

**Comment by brittweinstein** [comment]
@brittany-johnson will review (15-30 min) this to assess when this may need to get done.

**Comment by brittany-johnson** [comment]
@ajluk Hello! From a quick review, of the issue, I don't think that the time or effort needed for this issue is worth the payoff since we are prioritizing the recipe rewrite this upcoming quarter. 
BUT this is just my opinion. @ajluk If you feel differently please let me know!

**Comment by ajluk** [comment]
@brittany-johnson I have missed your comment somehow in the inbox. I'm sorry for the late response. Yes, you're right. In the case of prioritizing the recipe rewriting I think it's not worth the effort.
