### ISSUE TITLE
introduction to business - ethics activity

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2785]
![Screen Shot 2020-09-22 at 9 48 29 AM](https://user-images.githubusercontent.com/11299125/93898433-d242da00-fcb8-11ea-8908-162a5cbdeaff.png)

### Icon
https://drive.google.com/file/d/1tZDE2I5JPF6Ggo676xs79VSs4izviUKQ/view?usp=sharing

### Notes
- should follow regular schema
- regular text flow (mostly just paragraphs)

**Comment by ajluk** [comment]
@lwtchu This how the section looks styled: 
![image](https://user-images.githubusercontent.com/55203598/98370464-e3626300-203a-11eb-858e-35c66045b353.png)
It also has the second title in `h4` tag as Critical Thinking Case (I asked about this title here), that's the reason it is blue.

**Comment by lwtchu** [comment]
@ajluk okay thanks - is the header in the summary a H3 for the module titile? it looks a bit bigger there 🤔

**Comment by ajluk** [comment]
@lwtchu If you're asking about Ethics Activity, it's h4, but it is actually not a module title: 
![image](https://user-images.githubusercontent.com/55203598/98515846-0162da00-226c-11eb-8151-e09e6436f1d1.png)
 But if there are any titles in the EOC sections that aren't modules like in the Summary they are H4. In the Summary they are H3: 
![image](https://user-images.githubusercontent.com/55203598/98515793-e1cbb180-226b-11eb-8000-ba5038ecd973.png)

**Comment by lwtchu** [comment]
@ajluk ah okay. i suspected it as such but wasn't sure. this looks good. thank you.

**Comment by brittweinstein** [comment]
@ajluk I'm moving this into testing for @MartaSztuka since @lwtchu has approved the screenshot here.

**Comment by MartaSztuka** [comment]
### PASSED
![Screenshot from 2020-11-16 16-15-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/687109e1-43f5-4c31-9a14-8df4344c4ab3)
