### ISSUE TITLE
introduction to business - working the net

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2786]
![Screen Shot 2020-09-22 at 9 55 28 AM](https://user-images.githubusercontent.com/11299125/93899297-ca376a00-fcb9-11ea-9e5f-fe2b25982bf6.png)

### Icon
https://drive.google.com/file/d/16q5cnsweMPzvGmSabpQNXtfofsC9etvA/view?usp=sharing

### Notes
- should be just lists. headers and fonts remain the same

**Comment by ajluk** [comment]
@lwtchu How it looks: 
![image](https://user-images.githubusercontent.com/55203598/98370907-9cc13880-203b-11eb-81e3-e2ed69870d55.png)

**Comment by lwtchu** [comment]
@ajluk looks good :)

**Comment by brittweinstein** [comment]
@lwtchu I'm closing this because the work for this title is done and we can use the documentation by searching the label.
