### ISSUE TITLE
introduction to business - critical thinking case

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2789]
![Screen Shot 2020-09-22 at 10 44 20 AM](https://user-images.githubusercontent.com/11299125/93905467-9d3a8580-fcc0-11ea-8547-f2cf34820eb6.png)
![Screen Shot 2020-09-22 at 10 44 29 AM](https://user-images.githubusercontent.com/11299125/93905476-9f9cdf80-fcc0-11ea-9070-4ef81d2c8598.png)

### Icon
https://drive.google.com/file/d/1lVezUadPa780bzW-XuOYTP_kbmi0_UmO/view?usp=sharing

### Notes
- just text follows same schema as regular headers

**Comment by ajluk** [comment]
@lwtchu I have a question about Critical Thinking Questions: Should I style the title to be bold as on the screenshot above? It has no `h` tag, it's just a div with [data-type="title"] attribute as you can see on the screenshot below: 
![image](https://user-images.githubusercontent.com/55203598/98368027-ebb89f00-2036-11eb-8f76-177c6e3db4f5.png)
Or is it some content issue?

**Comment by lwtchu** [comment]
@ajluk hm should i make a separate documentation card for OL titles? i can do that... and provide specs. i think it should be fine if it's just bold though

**Comment by ajluk** [comment]
@lwtchu Please do make the separate documentation. It will be easier to test it, because this titles can be found in many places in the book, not only in the EoC Critical Thinking Case. I will style them within another PR then. Thank you!

**Comment by lwtchu** [comment]
@ajluk here's the list title card: #3039

**Comment by brittweinstein** [comment]
@ajluk I will go ahead and close this card since the Intro Business PR has been merged and @lwtchu has created a new card for the next title. Please let me know if this is not the case!

**Comment by ajluk** [comment]
@brittweinstein I have checked that this feature has been tested within testing this big issue: https://github.com/openstax/cnx-recipes/issues/2931 but if you prefer to test the small ones separately please let me know.

**Comment by MartaSztuka** [comment]
### PASSED
![Screenshot from 2020-11-16 16-22-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/debfddb1-a19d-41e4-8303-cd71a3f76bc9)
