### ISSUE TITLE
introduction to business - hot links address book

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2791]
![Screen Shot 2020-09-22 at 10 48 23 AM](https://user-images.githubusercontent.com/11299125/93906784-3ae28480-fcc2-11ea-8efc-b464a608aa80.png)

### icon
https://drive.google.com/file/d/1QmnvWNNCnGPV6-YRiyS9xEu5-ryK340R/view?usp=sharing

### notes
- should be a list
- headers/fonts the same

**Comment by ajluk** [comment]
@lwtchu Here is how this section looks styled: 
![image](https://user-images.githubusercontent.com/55203598/98371132-f6c1fe00-203b-11eb-839b-f3096b3d81d6.png)

**Comment by lwtchu** [comment]
@ajluk it looks good thank you!

**Comment by brittweinstein** [comment]
@ajluk has this been merged for intro business already? if so, let's go ahead and close this.

**Comment by ajluk** [comment]
@brittweinstein Sorry for the delay. I've missed you message somehow. Yes it has been styled within this PR: #2932. I'm closing this issue.
