### ISSUE TITLE
Add Additive Manufacturing (80%) to the corn theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2799]
# Content
- The content is currently on content03. Please check with the content team to get content migrated

# Recipe and Design

- We will be reusing the `statistics` recipe! With a few minor changes. Hopefully, it will be clear below.
- Please name the new recipe/style `additive-manufacturing`.
- Most of the changes are done in the EOC collating sections.

There will be 3 sections with exercises. They should follow the same format as the existing Practice and Homework styles/structure (one column, broken out by section, exercises are styled with a bolded exercise number and problem stem follows the number, answers should collate to the Answer section)
<img width="359" alt="Screen Shot 2020-09-25 at 12 41 11 PM" src="https://user-images.githubusercontent.com/11299125/94298854-6bc5f200-ff2c-11ea-8032-cc011c5defce.png">

- [x] Review Questions (`class="review-questions"`)
- [x] Case Questions (`class="case-questions"`)
- [x] Discussion Questions (`class="free-response"` - this class exists, we can reuse!)

- [ ] Add recipe/style drop down in cops.
- [ ] Add recipe drop down on legacy.

Everything else should function the same as the `statistics` recipe.

**Comment by lwtchu** [comment]
@Stackblocks ryan and i reviewed the pdf and have the follwing comments

"yes. smashing" - ryan
"everything looks like it's there" - larissa

**Comment by Stackblocks** [comment]
The rough test plan for this is going to be: 
- Use the new Bakery CLI to fetch the test data from content03
- Run that data through the bake process to produce an output. 
- Focus on assessing the overarching look of the book, and the specifics of the new exercise types while being aware that it is built on limited content so in places where something like a splash image is missing there will be visual issues that are not related to the styling code. (At least not yet, lol)

**Comment by meeragovindaraju** [comment]
EOC looks good. 
[collection.pdf](https://github.com/openstax/cnx-recipes/files/5467422/collection.pdf)


![Screen Shot 2020-10-30 at 3 06 33 PM](https://user-images.githubusercontent.com/33066187/97752181-86f2c700-1ac1-11eb-8091-c67d0996f30c.png)
