### ISSUE TITLE
introduction to business - references

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2800]
Within Introduction to Business, there are references in the chapter that collate to the end of the book. Standard structure should be set up already by the recipe.

# Within text
![Screen Shot 2020-09-25 at 2 44 24 PM](https://user-images.githubusercontent.com/11299125/94309386-9f5d4800-ff3d-11ea-97bf-5ee1c3df2c56.png)

## Mark up
```
<cite target-id=“rf-1234”>
       <note class=“reference” display=“inline” id=“rf-1234">
         Reference data here.
      </note>
</cite>
```

## Specs
color: standard link color
text treatment: NO UNDERLINE

# End of book
![Screen Shot 2020-09-25 at 2 41 05 PM](https://user-images.githubusercontent.com/11299125/94309212-54433500-ff3d-11ea-80e0-3ea03503f60a.png)

## Mark up
```
<section class="references">
  <title>References</title>
  <note id="rf-001">This is reference.</note>
</section>
```
## Specs
-standard appendicies and base text font and sizes
- numbers: bold, not links

**Comment by ajluk** [comment]
@lwtchu here is how the References look like styled with provided specs: 
![image](https://user-images.githubusercontent.com/55203598/98009069-7316d000-1df5-11eb-9bdf-3e80042d8ba1.png)
Should I change something?
Do we need more f.ex: bigger margin between each chapter references: 
![image](https://user-images.githubusercontent.com/55203598/98009553-f59f8f80-1df5-11eb-96aa-e57889a83ab7.png)
Now it is `v-spacing(1) =  0.7rem`
The headers are using the specs from header schema.

**Comment by lwtchu** [comment]
@ajluk what are the specs for the title "Reference" and the module title? they look like the same size 🤔  are they the same header level

**Comment by ajluk** [comment]
@lwtchu They are H1 and H2 and use the specs from the schema: 
![image](https://user-images.githubusercontent.com/55203598/98216950-10831880-1f4a-11eb-94c6-85ff39f556b2.png)
![image](https://user-images.githubusercontent.com/55203598/98217066-3c060300-1f4a-11eb-928a-b0e802711d54.png)

**Comment by lwtchu** [comment]
@ajluk yep that's fine i just wanted to double check - this should be fine :) thank you

**Comment by ajluk** [comment]
@No problem. It looked odd for me too at first time I saw it and I also checked the fonts just to be sure if the tags are using correct ones. :smile:

**Comment by brittweinstein** [comment]
@lwtchu I'm closing this because the work for this title is done and we can use the documentation by searching the label.
