### ISSUE TITLE
ElemAlg2e Cops PDF has more spacing after tokens 

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#2804]
# What happened?
Cops PDF has more spacing in tokens throughout the book. Possibly not an issue, but worried about crashing. 

- **Does this happen in one place, a few places, or everywhere?**: throughout

# Environment:

- **Book(s)**: Elementary Algebra 2e
- **URL/Server**: prod
- **Location (page number, chapter/section)**: throughout

# Screenshots

![2020-09-28_08-39-53.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/28f5d46d-7ac8-4509-8643-3230d72a82cc)

**Comment by lwtchu** [comment]
@marcjeannott was there anything crashing? if there was, i'd say to open a card on the content-manager board to do a content work around.

**Comment by openstaxalina** [comment]
Could not find any crashing content -- did not open a card for cm board.
