### ISSUE TITLE
ElemAlg2e Left Aligned Art 

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#2805]
# What happened?
I noticed that sometimes art is left aligned. This does not affect all art but does effect some. I've captured two examples here One image right about Example 4.1, and another in a note below Try It 4.2 

# Environment: Prod?

- **Book(s)**: Elementary Algebra 2e

# Screenshots
![2020-09-28_09-12-56.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/8e4734b5-369d-4337-94ba-43cf93c96863)

![2020-09-28_09-19-38.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/aae4ebc4-3c6f-4583-991d-70af145e3195)

# Additional notes

**Comment by lwtchu** [comment]
this is intentional. images not in `<figure>` are now left aligned.
