### ISSUE TITLE
Splash image issues 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#2806]
# Scenario
The splash image seems to have a pretty heavy filter on it that drastically changes its appearance. 
Note: I am resizing the splash image in the screenshot to fix this title placement issue, this card is just for the filter. 

# Acceptance Criteria (required)
Splash image should not have a filter (to my knowledge) 

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [ x] Yes  [ ] No  (_attach below_)
![Screen Shot 2020-09-28 at 10.19.38 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/d3d522f7-64c5-4fe7-b35b-84e2a3d5d114)

# Environment: (required)
* **Medium**: [ ] REX [x ] PDF  [ ] cnx.org
* **Instance**: [x ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [x ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [x ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by marcjeannott** [comment]
**All titles** have this blue filter over their splash images.

**Comment by openstaxalina** [comment]
May tone down the blue tint -- but will need to source some new splash images.

**Comment by openstaxalina** [comment]
Related work: https://github.com/openstax/content-managers/issues/1851

**Comment by ajluk** [comment]
@lwtchu do we need to make the overlay(filter) brighter? Or there is just work on the content side to be done.

**Comment by lwtchu** [comment]
@ajluk can you show me what it would look like at 30%?

**Comment by ajluk** [comment]
@lwtchu I think you meant the opacity/transparency - it is not set in the percentages but in values from 0 to 1, when I have set it to 0.3 this how the image looks like in html: 
![image](https://user-images.githubusercontent.com/55203598/102382440-c1a9b380-3fca-11eb-9b80-bbd29fa5db9f.png)
It was previously set to 0.5.

**Comment by lwtchu** [comment]
@ajluk i think it'll look better for every thing if we set it to 30% - i'll adjust the documentation on #1752  


thank you

**Comment by ajluk** [comment]
@lwtchu Here is how the image looks in PDF file: 
![image](https://user-images.githubusercontent.com/55203598/103291641-85278000-49ec-11eb-9688-62afbd727ec2.png)

**Comment by lwtchu** [comment]
@ajluk looks good thank you

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-07 17-14-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5472732b-3a78-46f6-abe3-1ff67eb7dcdd)
