### ISSUE TITLE
ElemAlg2e - EOC missing chapter number

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#2807]
# What happened?
EOC is missing the chapter number in the Chapter Review section this may or may not be intentional. 

# Environment:

- **Book(s)**: Elementary Algebra 2e 
- **URL/Server**: Prod? 
- **Location (page number, chapter/section)**: Throughout EOC

# Screenshots

![2020-09-28_10-30-12.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/502e8c73-125f-45d1-a4ff-976d966b8057)

**Comment by lwtchu** [comment]
intentional closing~
