### ISSUE TITLE
Business Ethics: style figures

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2809]
Documentation: https://github.com/openstax/cnx-recipes/issues/2643

**Comment by MartaSztuka** [comment]
## PASSED
### Business Ethics figures
![Screenshot from 2020-10-01 16-10-24](https://user-images.githubusercontent.com/47241114/94820335-a2a27900-0400-11eb-8455-6a4a0c55aed6.png)
![Screenshot from 2020-10-01 15-58-12](https://user-images.githubusercontent.com/47241114/94820442-c1087480-0400-11eb-969b-e29224321a37.png)
