### ISSUE TITLE
Corn PDF Table of Contents just says Contents

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#2812]
# What happened?
Corn theme makes the TOC say just Contents, this is probably intentional, but worth noting anyway. 
# Screenshots

![2020-09-29_09-08-46.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/30a74d3f-9161-4013-87ee-5b7e558e4145)

**Comment by lwtchu** [comment]
😬  i don't think this is intentional...but it also will match everything else 🤔  so we'll leave as is for now.
