### ISSUE TITLE
Corn PDF has added word "Section" to EOS Exercises

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#2814]
# What happened?
Noticed that Production just has a the section number, corn has the word section. This is likely intentional, but opening a card just in case. 

# Screenshots

![2020-09-29_10-32-23.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/04ddead1-c212-44bc-8029-017fceb8ee04)

**Comment by lwtchu** [comment]
Intentional. Closing.
