### ISSUE TITLE
Business Ethics: style headers

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2816]
Documentation: https://github.com/openstax/cnx-recipes/issues/2644

**Comment by MartaSztuka** [comment]
### PASSED
#### Preface![Screenshot from 2020-10-08 11-25-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a2b3ffbf-6b5a-4249-8e9c-3e26831bb538)
#### Module![Screenshot from 2020-10-08 11-27-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b3781f7b-8f2a-4a16-809f-747318f51b7e)
#### Appendix![Screenshot from 2020-10-08 11-27-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/af9d418b-23b5-45ca-b10d-f42afc844be2)
