### ISSUE TITLE
Business Ethics: style Learning Objectives

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2817]
Documentation issue: #2711

**Comment by MartaSztuka** [comment]
## PASSED
![Screenshot from 2020-10-05 13-04-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8ecce0dc-d0e0-4b7b-9557-fffb3473c679)

**Comment by lwtchu** [comment]
@MartaSztuka can you see if the "learning objectives" is bolded? or is that how the font renders?

**Comment by MartaSztuka** [comment]
@lwtchu Yes, it is bolded.
![Screenshot from 2020-10-05 16-01-05](https://user-images.githubusercontent.com/47241114/95089165-19eb4c00-0724-11eb-875b-0de9199281ed.png)

**Comment by lwtchu** [comment]
There's some recent chatter on #2711 to add a font-weight: lighter on the text so it doesn't render bolded in the pdf. I'm going to reopen to make sure that gets captured.

**Comment by brittweinstein** [comment]
@ajluk please see Larissa's note above.

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-10-21 17-37-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6f598c4c-40c1-40ee-93c8-f9cc0820dc9f)
