### ISSUE TITLE
Business Ethics: style footnotes

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2824]
Issue with documentation: #2747

**Comment by ajluk** [comment]
@MartaSztuka >> Information for testing purposes: The footnotes can be easily found in Appendices.

**Comment by MartaSztuka** [comment]
### PASSED
![Screenshot from 2020-10-12 13-55-34](https://user-images.githubusercontent.com/47241114/95743855-b2d51680-0c92-11eb-9773-ffcef96f1764.png)
