### ISSUE TITLE
Solution Numbers not Displaying Business Stats Corn

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#2825]
# What happened?
Solution numbers just have the number 1 (this is across all chapters) 

- **Book(s)**: Introductory Business Statistics
- **URL/Server**: Prod
- **Location (page number, chapter/section)**: Throughout
- **Suggested nearby searchable text**: Solution

# Screenshots
![2020-10-01_12-43-40.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/9ed8ec4e-92ee-462b-a4d7-0bfba88daa4b)

**Comment by theresamasciale** [comment]
Also an issue in Statistics

![Screen Shot 2020-10-05 at 9.01.17 AM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/29eb53a7-c119-442f-880b-d9665d560fb6)

**Comment by lwtchu** [comment]
This will be fixed with https://github.com/openstax/content-managers/issues/1876
