### ISSUE TITLE
Business Ethics: style Link to Learning note

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2828]
Documentation: https://github.com/openstax/cnx-recipes/issues/2737

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2020-10-07 12-57-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/66e9cd21-48e3-40ad-a3a1-85ca6b0425a9)
