### ISSUE TITLE
Odd Styling of Example Solution (one off - might be content related?)

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#2831]
# What happened?
I noticed some odd styling with a specific example solutions because it only happens once that I've seen i'm led to believe it is a content fix. 

# Reproducibility Details

- **Does it also happen in an incognito window?**: N/A
- **Does this happen in one place, a few places, or everywhere?**: One place I think

# Environment:

- **Book(s)**: Bus Stats
- **URL/Server**: Corn PDF
- **Location (page number, chapter/section)**: Chapter 3 Section 2
- **Suggested nearby searchable text**: "events of being female and having long hair"

# Screenshots

![2020-10-02_09-43-35.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/6f5b35dd-7c4c-496d-b182-9ebbb8e8a701)

**Comment by lwtchu** [comment]
Known issue to be fixed with https://github.com/openstax/content-managers/issues/1876
