### ISSUE TITLE
Business Ethics: style Real World note

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2832]
Documentation: https://github.com/openstax/cnx-recipes/issues/2737 - Option 2

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2020-10-07 14-28-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c9a5fad4-ba5b-41e5-8683-510d5701b7a7)
