### ISSUE TITLE
Business Ethics: style What Would note

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2834]
Documentation: https://github.com/openstax/cnx-recipes/issues/2737 Option 3

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2020-10-07 14-50-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5365bade-af87-4004-8169-735fada8f1e7)
