### ISSUE TITLE
Business Ethics: style Ethics Across note

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2836]
Documentation: https://github.com/openstax/cnx-recipes/issues/2737 Option 3

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-10-07 15-59-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0a8e07fb-e314-440e-be07-77ce5073744b)
