### ISSUE TITLE
Business Ethics: style Key Terms

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2838]
Documentation: https://github.com/openstax/cnx-recipes/issues/2742

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2020-10-08 13-34-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/38741fd5-5ae3-47de-9d87-44a7be6f6648)
