### ISSUE TITLE
Statistics/Corn theme: Bulleted list isn't indented Corn theme Introductory Stats (need to do before spanish recipe)

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#2839]
# What happened?

While testing corn theme I noticed that a bulleted list isn't indented as I would expect, and how they currently are on the old PDFs.
From what I can tell this is not throughout the book, but a single bulleted list behaving strangely which makes me think it's a content issue.  

# Reproducibility Details

- **Does this happen in one place, a few places, or everywhere?**: I've only seen this one so far 

# Environment:

- **Book(s)**: Introductory Statistics 
- **URL/Server**: Prod
- **Location (page number, chapter/section)**: Chapter 5 Introduction
- **Suggested nearby searchable text**: The outcomes are measured, not counted.
- **Browser**:

# Screenshots

![2020-10-05_08-18-30.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/9e13a2f3-680a-451b-a914-bd4ba6b8bf7e)

# Additional notes
Please move to whichever board you would like.

**Comment by lwtchu** [comment]
This might've been missed in the grand sweep of list fixes - this was probably missed in the introduction module. We should probably do this before we implement the spanish recipe/style.

**Comment by ajluk** [comment]
@lwtchu I have checked this part in content generated on cops today and the problem seems resolved: 
![image](https://user-images.githubusercontent.com/55203598/99965093-a4e7da80-2d94-11eb-97d8-dfcdfebf492b.png)

**Comment by lwtchu** [comment]
@ajluk thank you for checking i'll close this.
