### ISSUE TITLE
Top Table Titles not Styled in Statistics (corn theme)

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#2842]
# Scenario
Testing Corn theme, found that top table titles don't appear to be styled in _Statistics_. See screenshot, this table appears within the lab experiments

# Acceptance Criteria (required)
Style top table titles

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)

![Screen Shot 2020-10-05 at 10.24.32 AM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/44ca5d46-dc30-4cfa-8e8b-9a3bdece87e1)

# Environment: (required)
* **Medium**: [ ] REX [x] PDF  [ ] cnx.org
* **Instance**: [x] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [x] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [x] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1953](https://github.com/openstax/content-managers/issues/1953) via [**ZenHub**](https://www.zenhub.com/)
