### ISSUE TITLE
Statistics Lab subheaders not styled (corn theme)

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#2843]
# Scenario
Testing corn theme in _Statistics_ and saw that subheaders used as steps in the labs are not styled (see screenshot)

# Acceptance Criteria (required)
style subheaders/steps in labs

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)

![Screen Shot 2020-10-05 at 11.30.20 AM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/97a1e483-8518-4b17-aba1-63606aa70b04)

# Environment: (required)
* **Medium**: [ ] REX [x] PDF  [ ] cnx.org
* **Instance**: [x] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [x] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [x] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by lwtchu** [comment]
This should be fixed with https://github.com/openstax/content-managers/issues/1876
