### ISSUE TITLE
Appendix links to the previous appendix last table Intro Stats

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#2844]
# What happened?

In corn theme link text that should say "Appendix E" will instead say "Table C26". It'll still take users to Appendix E when clicked, but the text is always referring to the previous appendix section's last table (or targetable thing?) 

# Reproducibility Details

- **Does this happen in one place, a few places, or everywhere?**:  Every time there's a link to a Appendix I think

# Environment:

- **Book(s)**: Introductory Statistics
- **URL/Server**: Prod

- **Suggested nearby searchable text**:  Using the data from Lap 1 only,

# Screenshots

![2020-10-05_13-32-34.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/21bfb68f-733f-43df-a711-e87b8e9ec3a3)

# Additional notes

May also be in other books. I'll update labels accordingly

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1952](https://github.com/openstax/content-managers/issues/1952) via [**ZenHub**](https://www.zenhub.com/)
