### ISSUE TITLE
Business Ethics: style Summary

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2846]
Documentation: https://github.com/openstax/cnx-recipes/issues/2743

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2020-10-14 15-05-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/879e0db8-2d6b-4b19-a1ff-5c4258cfa25c)
