### ISSUE TITLE
Calculus Volumes Preface - Bulleted Lists displaying bullets in Corn

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#2847]
# What happened?
On the live PDFs the coverage and scope section does not have visible bullets, but it does in the corn theme. 

# Reproducibility Details
- **Does this happen in one place, a few places, or everywhere?**: Across the three volumes of Calculus

# Environment: 

- **Book(s)**: Calculus Vol 1, 2 ,3 
- **URL/Server**: Prod
- **Location (page number, chapter/section)**: Preface Coverage and Scope

# Screenshots

![2020-10-06_08-30-44.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/a79ea156-96dc-4170-b36d-55449821405e)

# Additional notes

May not be a big enough issue. Just pointing it out.

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #1954](https://github.com/openstax/content-managers/issues/1954) via [**ZenHub**](https://www.zenhub.com/)
