### ISSUE TITLE
Business Ethics: Learning Objective spec update

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2848]
Link to comment in the documentation issue:https://github.com/openstax/cnx-recipes/issues/2711#issuecomment-704268532

**Comment by MartaSztuka** [comment]
### FAILED
#### Header is stil bold![Screenshot from 2020-10-12 17-36-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2686b623-e174-4c01-8eec-4f414fcabc1a)
![Screenshot from 2020-10-12 17-46-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/172c6644-7757-4774-adc3-76dd22f31faf)

**Comment by MartaSztuka** [comment]
### PASSED
![Screenshot from 2020-10-21 15-20-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/754ef19f-f05f-4284-bec4-4fac23e378cf)
