### ISSUE TITLE
Business Ethics: Style Introduction Page

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2851]
Issues with documentation: #2642, #2655

**Comment by lwtchu** [comment]
### BLEEDS PASSED
![Screen Shot 2020-10-16 at 12 31 07 PM](https://user-images.githubusercontent.com/11299125/96289966-7dd70580-0fab-11eb-936f-aff34ee638cd.png)

**Comment by MartaSztuka** [comment]
## PASSED
![Screenshot from 2020-10-27 14-32-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9af17983-a3ab-47fb-aaa6-565947ddb6f6)
