### ISSUE TITLE
Business Ethics: style Endnotes

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2855]
Documentation: https://github.com/openstax/cnx-recipes/issues/2745

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2020-10-15 13-47-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7939e373-0c12-4fe2-a6e8-b19629d63a5e)
