### ISSUE TITLE
Business Ethics: style Answer Key

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2857]
Documentation: https://github.com/openstax/cnx-recipes/issues/2748

**Comment by MartaSztuka** [comment]
### PASSED
![Screenshot from 2020-10-15 13-21-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/76d8aab5-6fae-449e-93cc-fcb2dbfc88dd)
