### ISSUE TITLE
Test New Interactive Types for Blowout

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2864]
@openstaxalina commented on [Mon Oct 12 2020](https://github.com/openstax/content-managers/issues/1963)

##  Description

SRM provided the below three samples of different types of interactive elements that we may use in the Blowout titles.

Please test embedding each one in a module (can all be the same module) and seeing how this comes through in REX. Please also test the PDF and make note of anything that would need to change there to "support" these (i.e. link to them, not display them in the PDF). Finally, with any interactive types that we think we might use, we should also test them in Tutor (Theresa may be able to do this).

Drag and Drop Interactive
Link: http://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/template_drag_and_drop_categorizing/
Source file: http://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/template_drag_and_drop_categorizing.zip
 
Case Study Scenario with Questions
Link: http://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/case_study_with_questions_template/
Source file: http://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/case_study_with_questions_template.zip
 
Timeline interactive
Link: http://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/stepped_graphic_timeline_template/
Source: http://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/stepped_graphic_timeline_template.zip
 
## Why do you need us to do it? Who is this for? 
This is so we can start developing specs for interactive elements we will support in the Blowout titles.

### Acceptance Criteria/what change should users see
*Move card to Review/QA if this has something in it*
- [ ] review at 10/19 content strategy meeting; decide next steps

## When do you need us to do this by? 
**please note if this is urgent
Possible to test and provide feedback for 10/19 content strategy meeting?

**Comment by meeragovindaraju** [comment]
- Unable to view the media in REX. There is a blank block instead of the media.
- There is a link present above the block that takes me to the URL "Click to view content"
- Link to the REX view https://rex-web.herokuapp.com/books/031da8d3-b525-429c-80cf-6c8ed997733a@23.6/pages/39256206-03b0-4396-abb6-75e6ee5e3c7b?archive=https://archive-staging.cnx.org
- This is after baking has successfully completed as per GOB.
- Moving the issue to backlog. I Waiting on creds to log into COPS

REX view

![Screen Shot 2020-10-13 at 11 08 08 AM](https://user-images.githubusercontent.com/33066187/95886938-d6589980-0d44-11eb-8953-a67cedd621e1.png)

Legacy View

![Screen Shot 2020-10-13 at 11 12 07 AM](https://user-images.githubusercontent.com/33066187/95887012-f4be9500-0d44-11eb-986d-3d4f18a69271.png)

**Comment by lwtchu** [comment]
@brittany-johnson i'm thinking these won't display because there's no html file i can directly point to with the link provided. there is an HTML file that is in the zip. can you think of a way for us to temporarily host this so we can test the embed?

**Comment by meeragovindaraju** [comment]
PDF view:
![Screen Shot 2020-10-13 at 4 37 47 PM](https://user-images.githubusercontent.com/33066187/95919026-7842ab00-0d72-11eb-959c-4b83b7df4639.png)

**Comment by brittany-johnson** [comment]
@lwtchu After inspecting the iframe it seems that it's not displaying because it's hosted on an unsecured site, using HTTP instead of HTTPS. 
The first thing that comes to mind is to use [Github pages](https://pages.github.com/) to securely serve the content to the iframe. This would be free but we would have to create a throwaway GitHub repository to store the HTML in. 

If this doesn't sound good I can think of another way?

**Comment by brittany-johnson** [comment]
Also long term, if we'll be using the SRM embeddables they'll probably have to fix this

**Comment by lwtchu** [comment]
@meeragovindaraju 

They fixed the https issue... can you replace with the following links and wait for it to bake on staging and see if it'll display in REX with the heroku link? Thanks!

Drag and Drop Interactive
Link:https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/template_drag_and_drop_categorizing/
Source file: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/template_drag_and_drop_categorizing.zip
 
Case Study Scenario with Questions
Link:https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/case_study_with_questions_template/
Source file: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/case_study_with_questions_template.zip
 
Timeline interactive
Link:https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/stepped_graphic_timeline_template/
Source: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/stepped_graphic_timeline_template.zip

**Comment by lwtchu** [comment]
@openstaxalina it works! if you want to review https://rex-web.herokuapp.com/books/031da8d3-b525-429c-80cf-6c8ed997733a@23.7/pages/39256206-03b0-4396-abb6-75e6ee5e3c7b?archive=https://archive-staging.cnx.org

**Comment by meeragovindaraju** [comment]
Looks good in Legacy view:

![Screen Shot 2020-10-20 at 11 15 52 AM](https://user-images.githubusercontent.com/33066187/96614430-bb969f80-12c5-11eb-9a32-6e5ac13f06ce.png)

Looks good in REX view:

![Screen Shot 2020-10-20 at 11 16 22 AM](https://user-images.githubusercontent.com/33066187/96614482-cbae7f00-12c5-11eb-816a-77a83c66b7c1.png)

**Comment by meeragovindaraju** [comment]
PDF View:

![image](https://user-images.githubusercontent.com/33066187/96635456-7bddb100-12e1-11eb-93d0-727e43e2b03d.png)

**Comment by brittweinstein** [comment]
@meeragovindaraju @brittany-johnson please put points on this when you can!

**Comment by lwtchu** [comment]
Further discussion here: https://docs.google.com/document/d/1fgx3zfprxDi-yg372KqMQQ8QGZhGbVQpl4JfDGqRuTE/edit

and here https://openstax.slack.com/archives/CH5514N57/p1603387770166400

Will draft questions in a bit. Just gathering notes

**Comment by lwtchu** [comment]
@meeragovindaraju when you get back, do you mind putting these in also - same as before. just copy in the link to the iframe. 

I did test removing the width and height, but if you add those back in, that'd be okay too.

Drag and Drop Interactive
1.
Link: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/template_drag_and_drop_categorizing/
Source file: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/template_drag_and_drop_categorizing.zip
 
2.
Link: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/drag_and_drop_labeling_template_horizontal/
Source file: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/drag_and_drop_labeling_template_horizontal.zip
 
3.
Link: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/drag_and_drop_labeling_template_portrait/
Source file: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/drag_and_drop_labeling_template_portrait.zip
 
4.
Link: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/drag_and_drop_matching_template/
Source file: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/drag_and_drop_matching_template.zip
 
5.
Link: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/drag_and_drop_sequencing_template/
Source file: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/drag_and_drop_sequencing_template.zip
 
 
Card Interactive
1.
Link: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/card_flip_flash_cards_template/
Source file: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/card_flip_flash_cards_template.zip
 
2.
Link: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/card_flip_memory_game_template/
Source file: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/card_flip_memory_game_template.zip
 
 
Case Study Scenario with Questions
1.
Link: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/case_study_with_questions_template/
Source file: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/case_study_with_questions_template.zip
 
2.
Link: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/case_study_content_only_(click_through)_template/
Source file: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/case_study_content_only_(click_through)_template.zip
 
 
Stepped Graphic interactive
1.
Link: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/stepped_graphic_timeline_template/
Source: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/stepped_graphic_timeline_template.zip
 
2.
Link: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/stepped_graphic_slider_template/
Source: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/stepped_graphic_slider_template.zip
 
 
Tabbed interactive
1.
Link: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/tabbed_interaction_notebook_template/
Source: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/tabbed_interaction_notebook_template.zip
 
2.
Link: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/template_tabbed_interaction_buttons/
Source: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/template_tabbed_interaction_buttons.zip
 
3.
Link: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/template_variant_tabbed_interaction_buttons/
Source: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/template_variant_tabbed_interaction_buttons.zip
 
 
Graphic Map with Zoom interactive
1.
Link: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/graphic_map_with_zoom_and_callouts_template/
Source: https://webshares.sixredmarbles.com/samples/phase%202_chrome_updated_template/samples/graphic_map_with_zoom_and_callouts_template.zip

**Comment by meeragovindaraju** [comment]
REX view: https://rex-web.herokuapp.com/books/031da8d3-b525-429c-80cf-6c8ed997733a@23.9/pages/39256206-03b0-4396-abb6-75e6ee5e3c7b?archive=https://archive-staging.cnx.org

Drag and drop:

![Screen Shot 2020-10-26 at 11 03 39 AM](https://user-images.githubusercontent.com/33066187/97196908-00fe1580-177b-11eb-89a9-1f1aaf41d6c4.png)

Card Interactive: 

![Screen Shot 2020-10-26 at 11 04 51 AM](https://user-images.githubusercontent.com/33066187/97196994-1d9a4d80-177b-11eb-9d20-d2c1b666846c.png)

Case Study Scenario with Questions:

![Screen Shot 2020-10-26 at 11 05 43 AM](https://user-images.githubusercontent.com/33066187/97197074-360a6800-177b-11eb-9618-f045e88fffa4.png)

Stepped Graphic interactive:

![Screen Shot 2020-10-26 at 11 06 29 AM](https://user-images.githubusercontent.com/33066187/97197172-520e0980-177b-11eb-9774-ae432af826e2.png)


Tabbed Interactive:

![Screen Shot 2020-10-26 at 11 07 13 AM](https://user-images.githubusercontent.com/33066187/97197250-6b16ba80-177b-11eb-9fe4-d1db751844cc.png)

Graphic Map with Zoom interactive:

![Screen Shot 2020-10-26 at 11 07 37 AM](https://user-images.githubusercontent.com/33066187/97197312-7f5ab780-177b-11eb-89bd-1987f759511d.png)

**Comment by meeragovindaraju** [comment]
PDF View:

![Screen Shot 2020-10-26 at 11 41 11 AM](https://user-images.githubusercontent.com/33066187/97201211-30fbe780-1780-11eb-9cef-0adec2ba1f99.png)

**Comment by brittweinstein** [comment]
@lwtchu what do you think of the latest ^ ? What else may be needed?

**Comment by lwtchu** [comment]
oh this should be good - i'll go ahead and close the card 🤔  i'll reopen if there's more. 

thanks!

**Comment by openstaxalina** [comment]
@philschatz I know you had asked about the source files for interactives (so we can figure out how to host them ourselves) - do the links in these comments answer your question?

https://github.com/openstax/cnx-recipes/issues/2864#issuecomment-712936442

https://github.com/openstax/cnx-recipes/issues/2864#issuecomment-715534678

cc @Bkblodget @lwtchu
