### ISSUE TITLE
Business Ethics: style lists

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2865]
Documentation: https://github.com/openstax/cnx-recipes/issues/2712

All lists should have proper indentations.

**Comment by MartaSztuka** [comment]
### PASSED
![Screenshot from 2020-10-16 15-18-11](https://user-images.githubusercontent.com/47241114/96263087-e41b5280-0fc2-11eb-96ab-ef25ceefa074.png)
![Screenshot from 2020-10-16 15-19-14](https://user-images.githubusercontent.com/47241114/96263185-0319e480-0fc3-11eb-9d4e-59934fcf6587.png)
![Screenshot from 2020-10-16 15-20-14](https://user-images.githubusercontent.com/47241114/96263486-5a1fb980-0fc3-11eb-9aec-c31216c69f97.png)
![Screenshot from 2020-10-16 15-24-11](https://user-images.githubusercontent.com/47241114/96263767-acf97100-0fc3-11eb-9cfe-4f94821ce16a.png)
