### ISSUE TITLE
Custom footnotes in Precalculus

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2867]
Preface should have a footnote that is in roman numerals.
In other modules footnotes are in arabic numerals, continuous throughout the book.

**Comment by wilkus27** [comment]
@MartaSztuka  I added also Business Ethics label, because my changes has impact also on this book. Please check if I didn't break anything there :grin:

**Comment by MartaSztuka** [comment]
## PASSED - roman numerals in Preface, arabic numerals in chapters
### Algebra & Trigonometry
#### Preface ![Screenshot from 2020-10-22 12-51-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d18a2fa2-9ddb-48b8-aa35-81f9f15614a3)
#### Chapters ![Screenshot from 2020-10-22 12-56-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2c9df269-0641-43e9-adf9-17f27b9a763f)
### Precalculus
#### Chapters ![Screenshot from 2020-10-22 12-18-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/02e2ccef-a09f-4c16-b79c-c3321c3d12e3)
#### Preface ![Screenshot from 2020-10-22 12-20-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b155e5cd-e953-4cab-85df-606f83eff40f)

## FAILED
### Business Ethics - arabic numerals in chapters
#### no footnotes in Preface
#### Chapters ![Screenshot from 2020-10-22 12-26-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e81cb524-be7d-4abb-ad76-a7b02c81e679)
### Algebra & Trigonometry - arabic numerals in both
#### Preface![Screenshot from 2020-10-22 13-06-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6335cddc-7458-4e31-a02f-87bbf96be82f)
#### Chapters![Screenshot from 2020-10-22 13-05-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/08463e61-eb66-47fd-9de3-2e58e0237775)
### College Algebra! - arabic numerals in both
#### Preface ![Screenshot from 2020-10-22 12-33-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/45583e2b-c4c3-453b-8d83-fc877ba754ad)
#### Chapters ![Screenshot from 2020-10-22 12-41-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/67749911-90f9-4c6f-ab29-081c2a35478c)
### College Algebra coreq - arabic numerals in both
#### Preface![Screenshot from 2020-10-22 12-46-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/39a7d666-60a9-4317-9d48-909d617b1e2f)
#### Chapters![Screenshot from 2020-10-22 12-47-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/48e787cc-4b01-4245-9093-894cd353b4bf)

**Comment by MartaSztuka** [comment]
## FAILED
### Business Ethics - arabic numerals in chapters
#### no footnotes in Preface
#### Chapters ![Screenshot from 2020-10-22 12-26-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e81cb524-be7d-4abb-ad76-a7b02c81e679)
### Algebra & Trigonometry - arabic numerals in both
#### Preface![Screenshot from 2020-10-22 13-06-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6335cddc-7458-4e31-a02f-87bbf96be82f)
#### Chapters![Screenshot from 2020-10-22 13-05-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/08463e61-eb66-47fd-9de3-2e58e0237775)
### College Algebra! - arabic numerals in both
#### Preface ![Screenshot from 2020-10-22 12-33-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/45583e2b-c4c3-453b-8d83-fc877ba754ad)
#### Chapters ![Screenshot from 2020-10-22 12-41-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/67749911-90f9-4c6f-ab29-081c2a35478c)
### College Algebra coreq - arabic numerals in both
#### Preface![Screenshot from 2020-10-22 12-46-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/39a7d666-60a9-4317-9d48-909d617b1e2f)
#### Chapters![Screenshot from 2020-10-22 12-47-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/48e787cc-4b01-4245-9093-894cd353b4bf)

**Comment by MartaSztuka** [comment]
## PASSED
Fatched new content, footnotes look ok now.
### College Algebra
#### Preface
![Screenshot from 2020-10-23 14-32-16](https://user-images.githubusercontent.com/47241114/97003965-95c70000-153c-11eb-955d-51d0a88ce79f.png)
#### Chapters
![Screenshot from 2020-10-23 14-33-58](https://user-images.githubusercontent.com/47241114/97004150-e5a5c700-153c-11eb-9c5d-ec3bec8c81dc.png)
### College Algebra coreq
#### Preface
![Screenshot from 2020-10-23 14-31-53](https://user-images.githubusercontent.com/47241114/97003928-85af2080-153c-11eb-958e-4a853cbd598a.png)
#### Chapters
![Screenshot from 2020-10-23 14-31-27](https://user-images.githubusercontent.com/47241114/97003886-78923180-153c-11eb-9605-c49bc9569780.png)

### Business Ethics
#### Preface —
#### Chapters
![Screenshot from 2020-10-23 14-36-47](https://user-images.githubusercontent.com/47241114/97004326-33baca80-153d-11eb-8092-d9eaab7a30df.png)
