### ISSUE TITLE
corn theme, statistics recipe: removing solution numbering

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2868]
# What happened?
After long debate and analysis (https://github.com/openstax/content-managers/issues/1876), I think it'll be best to fix these one off issues and such with moving the content to a more standardized state (which is one solution per example). 

With that being said, please remove the numbering for solutions within examples. It currently says `Solution 1` `Solution 2` etc

# Environment:

- **Book(s)**: Statistics (High School), Business Statistics, Introductory Statistics
- **Location (page number, chapter/section)**: Look for any and all examples. 

Easy way to test is that the words "Solution 1" are no longer present.

**Comment by lwtchu** [comment]
# Acceptance Criteria 
This should be a go - please targed unnumbered classes in the solutions. The numbering should only appear if there's more than 1 solution.

**Comment by lwtchu** [comment]
Adding deadline firm as we are about to do production on 2es

**Comment by wilkus27** [comment]
@lwtchu I want to make sure. Do we want numbering in this situation?

![image](https://user-images.githubusercontent.com/40228854/214305700-36260f95-65d4-47ae-82c7-551adb643608.png)

Here we have a few exercises, each of them has problem and solution.

Or numbering should be added only when one exercise has more then one solution?

So it would be:

```
Problem
  some text
Solution 1
  some text
Solution 2
  some text
```

**Comment by lwtchu** [comment]
@wilkus27 x_x that was supposed to be fixed. where's the location for that?

**Comment by lwtchu** [comment]
@wilkus27 do you know which book this is from? i need to look into this

**Comment by wilkus27** [comment]
@lwtchu It's from `Introductory Statistics`, Example 1.13.

So there will be only one problem and one solution in examples, that's right?
If yes, should I remove totally functionality for adding numbers to title `Solution`? For now it's added only to Statistics. Do we want to keep code just in case, even if there gonna be no case where we need numbering?

**Comment by lwtchu** [comment]
@wilkus27 I think it would be worth removing the  numbering anyway since they're broken up and separated by letters. We can comment out the code though just in case something changes in a later edition.
