### ISSUE TITLE
corn theme, statistics style/recipe: adding a "Problem" label to problems in examples

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2871]
![image](https://user-images.githubusercontent.com/11299125/96292961-9ea15a00-0faf-11eb-8c65-f82788a9af88.png)

This is for statistics ONLY. 

Is it possible to add a `Problem` title (like `Solution` (without the number)).

Same specs but with a different icon: https://drive.google.com/file/d/1zl8ULuh8EZb9t3AV75Yzwh8Takb6U8xl/view?usp=sharing

**Comment by ajluk** [comment]
@lwtchu Should the solution be reusable for other books recipes in the future as an option after all examples markup will be standardized or it will be used only in statistics?

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/170087168-0bd28bbd-8912-45d4-9229-d785b581795d.png)

**Comment by lwtchu** [comment]
@ajluk what would it take to make it usable for all books? will we need to add a class on the examples?

**Comment by ajluk** [comment]
@lwtchu Oh, no. I just meant that I can make this change in the statistic recipe file directly or make a new/adjust the example direction in cookbook, so other books can use it later on :slightly_smiling_face: I chose the second option in my connected PR, but let me know if this not something you had in mind.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-06-02 at 22.20.19.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f4a2e6f7-68d0-4571-80f5-d30182f37153)
