### ISSUE TITLE
Possible bug: Recipe injects book UUID on intermodular links

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2876]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [x] recipe [ ] styles [ ] both [x] i don't know

Is the recipe injecting the book's UUID at the beginning of intermodular links, and if so, is this intended?

Starting from the beginning...

Screenshot showing we encoded only the module UUID for this intermodular link ([link to page in Legacy](https://legacy.cnx.org/content/m63594/1.16/?collection=col12190/1.13&legacy=true)):
![Screen Shot 2020-10-16 at 3 33 37 PM](https://user-images.githubusercontent.com/7863733/96306295-07470180-0fc5-11eb-8f78-d94bdb4b8468.png)

Screenshot showing the recipe (?) added the book UUID to this intermodular link: ([link to page at vendor.cnx.org](https://vendor.cnx.org/contents/J_WQZJkO@13.1:t8ejHQax@16/2-1-How-Individuals-Make-Choices-Based-on-Their-Budget-Constraint)):
![Screen Shot 2020-10-16 at 3 37 02 PM](https://user-images.githubusercontent.com/7863733/96306578-8b998480-0fc5-11eb-8926-83a648735602.png)

Actual behavior [in REX](https://github.com/openstax/cnx-recipes/issues/new?assignees=&template=BUG_TEMPLATE.md&title=) is to go to the page in an entirely different book (that it's also in) -- I am talking with Kim about this:
![Screen Shot 2020-10-16 at 3 38 30 PM](https://user-images.githubusercontent.com/7863733/96306655-b683d880-0fc5-11eb-9bfb-df74fb61c7c7.png)

# Acceptance Criteria
Will depend on decisions above

# Bug Location(s)
collection ID:
server:
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
I don't think this is an issue anymore? Also I think we talked about this in another context. Farewell forgotten card.
