### ISSUE TITLE
Clean up: Refactor lists shapes in corn theme

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2878]
Based on Natalia's suggestions from this comment (https://github.com/openstax/cnx-recipes/pull/2798#pullrequestreview-509162030): 
- create two shapes: for lists in exercises from one column sections and from multi column sections
- separate components for lists from one column layout and multicolumn layout
- define settings in book.scss file not in lists-settings.scss if needed

**Comment by brittweinstein** [comment]
@ajluk is this for corn or carboard theme?

**Comment by ajluk** [comment]
@lwtchu could you advise how many books (and maybe which of them) Marta should test within this issue? These changes affects all of the books from corn theme. I think Collega Algebra Coreq should be checked because there are exercises in coreq sections present and maybe Marta could pick one from dev-math and calculus books? What do you think?

@MartaSztuka During testing this issue circled lists with tokens needs to be checked if they still look ok (it's a clean up issue) in section `coreq` in College Algebra Coreq, section Exercises, EoC exercises, EoB Answer Key, Try It notes, Examples in the books from corn theme.

**Comment by lwtchu** [comment]
@ajluk yeah that sounds good. college algebra coreq, elementary algebra and then calculus vol 2?

**Comment by ajluk** [comment]
@lwtchu Thank you! Yes I thin it should be ok.

**Comment by MartaSztuka** [comment]
#### PASSED
##### College Algebra Coreq![Screenshot from 2021-03-16 14-39-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/916c3fd2-3776-4d8e-a4f5-7a19fae6d72e)![Screenshot from 2021-03-16 14-41-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bf1f3301-3dc9-4367-9417-17c02f1728ce)![Screenshot from 2021-03-16 14-40-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a5be49ac-f904-441a-86d3-b88c464970c1)![Screenshot from 2021-03-16 14-42-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/88ce1653-d3b1-49b5-a369-a55c07144fed)![Screenshot from 2021-03-17 09-50-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/355e1b23-18c2-438e-86ce-a014765c5d02)
##### Elementary Algebra![Screenshot from 2021-03-17 09-41-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0e26400a-afdf-433c-9e5d-c59adf5c242e)![Screenshot from 2021-03-17 09-42-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7c22f975-1e9c-4027-8287-61d873189f2f)![Screenshot from 2021-03-17 09-48-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/68f5a2af-c173-4a4f-8600-3aff26a922e9)
##### Calculus vol 2![Screenshot from 2021-03-17 11-18-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b4fbe54c-c40e-4bb6-a071-207964b44579)![Screenshot from 2021-03-17 11-19-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a8d0d08c-be59-46f1-becd-60af4d4b20b8)![Screenshot from 2021-03-17 11-20-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/149a318b-e696-40b4-9b1b-70421d158d0e)
