### ISSUE TITLE
Add Business Law to template3

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2879]
Business Law use the same recipe (and styles) what Business Ethics. 
Here is the documentation with list of all elements which should be checked during tests: https://github.com/openstax/cnx-recipes/issues/2684

**Comment by wilkus27** [comment]
@MartaSztuka I'm moving this issue to Ready for Testing, but I think we should wait until Anna will merge her PR (https://github.com/openstax/cnx-recipes/pull/2859) with styles for Chapter Intro and folio.

**Comment by MartaSztuka** [comment]
## PASSED
### General Things:
#### Table of Contents![Screenshot from 2020-10-22 14-03-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7887911e-13d0-4a04-be9c-319c513b48cf)
#### Figure caption/title/number styling![Screenshot from 2020-10-22 14-05-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/688f6785-2f60-4edb-9591-adb585a0fcc2)
#### Headers![Screenshot from 2020-10-22 14-08-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6f62c996-2d1f-46d2-b675-c41c7c396107)
#### Section number treatment![Screenshot from 2020-10-22 14-11-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cd80f282-b846-45be-b285-92cb1144bc6f)
#### Endnotes![Screenshot from 2020-10-22 14-16-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0fd8de1c-b23e-4a58-9837-aab203bcfed3)
#### Footnotes - there are no footnotes (?)
#### Blockquotes - there are none
#### Lists![Screenshot from 2020-10-22 14-24-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/214b5ba6-6b07-4889-b9ca-21f6deff3b9d)

### Feature-like things:
#### Link to Learning —
#### Cases from the Real World —
#### What Would You Do? —
#### Ethics Across Time and Cultures  - there are none of those in Business Law

### End of Chapter Content:
#### Key Terms - there are none
#### Summary![Screenshot from 2020-10-22 14-30-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6af41e1c-2cd6-4e60-b355-42d898c766ff)
#### Assessment Questions![Screenshot from 2020-10-22 14-30-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/74c7af31-fa60-4773-bd07-38c92a521add)
#### Endnotes![Screenshot from 2020-10-22 14-30-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9a350938-8f7a-424c-96da-aa2250c65a05)

### End of Book Content:
#### Appendices - there are none
#### Answer Key![Screenshot from 2020-10-22 14-31-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c6e86b48-11c0-4e08-9b22-4830fee1e9a3)

## FAILED
#### Splash image are missing right margin![Screenshot from 2020-10-22 14-03-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f1b54eda-7638-469b-ab92-7b54b182da5a)
#### Chapter Outline / Introduction is unstyled![Screenshot from 2020-10-22 14-09-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/92c33eb2-f3f6-4325-9a23-e3b8c89e8717)
#### Learning Objectives - there's Learning Outcome and it's unstyled![Screenshot from 2020-10-22 14-13-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5a90a972-bd24-4f0c-8798-a01d60323b12)
#### Tables are unstyled ![Screenshot from 2020-10-22 14-15-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cf252958-88c0-42a0-9ecb-dc5dfc27cd4d)

**Comment by MartaSztuka** [comment]
## FAILED
#### Splash image are missing right margin![Screenshot from 2020-10-22 14-03-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f1b54eda-7638-469b-ab92-7b54b182da5a)
#### Chapter Outline / Introduction is unstyled![Screenshot from 2020-10-22 14-09-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/92c33eb2-f3f6-4325-9a23-e3b8c89e8717)
#### Learning Objectives - there's Learning Outcome and it's unstyled![Screenshot from 2020-10-22 14-13-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5a90a972-bd24-4f0c-8798-a01d60323b12)
#### Tables are unstyled ![Screenshot from 2020-10-22 14-15-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cf252958-88c0-42a0-9ecb-dc5dfc27cd4d)

**Comment by wilkus27** [comment]
@MartaSztuka I added comment at the beginning that we should wait with testing because changes for Chapter Intro are not merged yet.

About problem with tables, I will create separate issue for that. 

Also I noticed on your screens that Endnotes are not styled correctly. Here is how they should look:

![image](https://user-images.githubusercontent.com/40228854/96974210-3277a680-1519-11eb-8d86-213ab6ffc5e5.png)


@lwtchu This is a content issue. Here is the proper markup from Business Ethics:

![image](https://user-images.githubusercontent.com/40228854/96974699-e24d1400-1519-11eb-902e-a6faa675b2d5.png)

That's how it looks in Business Law:

![image](https://user-images.githubusercontent.com/40228854/96974775-fa249800-1519-11eb-9668-882235ebb155.png)

**Comment by wilkus27** [comment]
Here is issue for tabels: https://github.com/openstax/cnx-recipes/issues/2890.

@MartaSztuka I'm moving this issue back to the Ready to Testing column. Please, test it when #2859 be also ready for testing.

**Comment by lwtchu** [comment]
@wilkus27 Apologies, I should've been a little more clear about the Endnotes - it is only using the functionality to put those references to the end. I do not think there is a corresponding reference number within the text. In that case, I would pass what Marta posted for the Endnotes there.

**Comment by wilkus27** [comment]
@lwtchu Business Ethics contains corresponding numbers:

![image](https://user-images.githubusercontent.com/40228854/97145598-bf636f80-1766-11eb-8d75-2b98ab341498.png)

**Comment by lwtchu** [comment]
🤔 hmm okay. do you know if i can get the PDF off cops yet? this might be a p big content change

**Comment by MartaSztuka** [comment]
## PASSED
#### Splash image![Screenshot from 2020-10-27 14-39-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/853a7108-f8df-436f-abb4-8c54b972b2a1)
#### Chapter Outline / Introduction![Screenshot from 2020-10-27 14-39-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e654688d-9a35-488b-a573-986ada6c7730)
#### Learning Objectives![Screenshot from 2020-10-27 14-40-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/05d86c0e-3353-4263-99ab-6cf993585d4e)

**Comment by lwtchu** [comment]
update: business law WIL NOT have the reference number in the text. it is using ONLY the endnote section so it'll collate to the EOC.

**Comment by MartaSztuka** [comment]
## PASSED
#### Splash image ![Screenshot from 2020-10-27 16-40-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/06ee4728-3576-4e4e-ab0d-120ec85e971f)
#### Chapter Outline / Introduction![Screenshot from 2020-10-27 16-40-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9faf4cb6-2d9c-4865-998b-9e9a9734e11c)

**Comment by MartaSztuka** [comment]
## FAILED
#### Learning Objectives - there's Learning Outcome and it's unstyled![Screenshot from 2020-10-27 16-41-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0e3cc483-fc0b-4874-91f7-4d7a1505ec80)

**Comment by wilkus27** [comment]
@MartaSztuka Learning Outcome should be styled now. It's ready for testing.

**Comment by MartaSztuka** [comment]
### PASSED
#### Learning Outcome![Screenshot from 2020-11-02 09-41-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8920f27b-a761-48b7-a2ec-03978136d957)
