### ISSUE TITLE
statistics recipe/style: top title table enabled

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2882]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [x] both [ ] i don't know

![image](https://user-images.githubusercontent.com/11299125/96299804-37d56e00-0fba-11eb-8d55-08905dc6f072.png)
This will be a recipe & style change? I'm not sure if it's already in recipes but never activated?? Idk.

# Acceptance Criteria
The top titled table is activated and the top row is transformed into a "title"

## Specs for title
font: noto sans
color: B1:   `#093D4C`
treatment: bold, 700
cell color: none 
cell border: none
text alignment: center

Rest of the table should look the same.

# Bug Location(s)
collection ID: https://katalyst01.cnx.org/contents/MBiUQmmY@24.7:i_O99VEg@5/1-6-Sampling-Experiment
server: katalyst01/production
chapter/section: 1.6
surrounding text: Restaurants Stratified by City and Entree Cost

https://github.com/openstax/content-managers/issues/1953#issuecomment-708523424

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by wilkus27** [comment]
@lwtchu I enabled recipe settings for top titled tables. They have proper markup now. This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/107641283-b940c280-6c73-11eb-8897-10e5d579d749.png)

![image](https://user-images.githubusercontent.com/40228854/107641405-e0978f80-6c73-11eb-8487-853064d8ebc9.png)

How it should be styled? We didn't style top titled tables in Corn Theme (https://github.com/openstax/cnx-recipes/issues/2204). We have only three shapes: for basic, column header and unnumbered unstyled tables.

**Comment by lwtchu** [comment]
@wilkus27 for the top-titled table in corn theme i updated the original issue to call out the "Specs for title" the rest of the table should look the same

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/107777943-c3ca8d00-6d43-11eb-86fe-7d55bcb9dd70.png)

I tried also to add space between title and table (v-spacing(1)):

![image](https://user-images.githubusercontent.com/40228854/107778093-e9f02d00-6d43-11eb-9ca3-cb356f6c6d1d.png)

Let me know which version do you prefer :wink:

**Comment by lwtchu** [comment]
@wilkus27 how much spacing is used in the cardboard theme?

**Comment by wilkus27** [comment]
In px? `v-spacing(1)` is always `0.7rem`. In Cardboard base font size is 12px, so `0.7rem = 8.4px`.

**Comment by lwtchu** [comment]
@wilkus27 okay let's stick with 0.7rem v-space(1) :) thank you

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-24 11-23-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7fcae1aa-fbdb-4d13-b962-aea8c544acaa)
