### ISSUE TITLE
principles of management - chapter review questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2884]
![Screen Shot 2020-10-20 at 12 11 39 PM](https://user-images.githubusercontent.com/11299125/96620717-6f4f5d80-12cd-11eb-8339-a563b74cef98.png)

- Icon: https://drive.google.com/file/d/1-IA4Gbm1OlPC2bg8lSedIUUIrjvZdBrB/view?usp=sharing
- header schema follows the other EOC header schemas
- base text is the noto sans 9 pt font. make sure there's no space between the questions and they go one after the other in the list.

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-02 13-10-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/44f85fec-64f2-47ca-b9fd-de7c6c5e9ae9)
