### ISSUE TITLE
accounting - chapter outline & introduction

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2888]
![Screen Shot 2020-10-21 at 3 46 20 PM](https://user-images.githubusercontent.com/11299125/96785607-a8aec880-13b4-11eb-9909-5aa40422e24e.png)

This is mostly the same as #2655 but notable difference is the absence of the grey bar and the new LO bullets.

### Chapter Outline text
font style: Roboto Condensed 
font size:  font-scale(3): 15.55pt, 20.4px, 1.7rem
color:  B2: `#344456` 

### LO number and bullet treatment
link color: standard link color
treatment: bold
font size: font-scale(0)
font style: noto sans
icon: https://drive.google.com/file/d/14Nu6KIQwuDQcbA-O9RJdIWnHR6WU4Hxp/view?usp=sharing

### Module links/text 
font style: noto sans
font size: font-scale(0)
module title style: normal
module title color: `#000000`

### Why It Matters
Icon: https://drive.google.com/file/d/16nxeqHi64Axd8mYzt-qCpXh2J1XUkaXL/view?usp=sharing
font style: Roboto Condensed 
font-scale(3): 15.55pt, 20.4px, 1.7rem
color:  B2: `#344456`

**Comment by LostMojo** [comment]
Hey, @lwtchu , I just want to double check that the size of the LO buttons match what you picture (They say they're the same height as the text, but appear a little larger)

(This is from the pdf)
![Screen Shot 2020-12-08 at 2.10.39 PM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/75d05ed9-2b7d-411d-be2d-5b5dfad89790)

**Comment by lwtchu** [comment]
@LostMojo hmmmm can you explain the margin thing 😬  like within what margins (page? the list?) i just wanna be on the same page 😅

**Comment by MartaSztuka** [comment]
Hi! @LostMojo Lo numbers colour is light blue, if this is ok, I'll close.![Screenshot from 2020-12-17 13-37-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c3158eaa-31ef-4153-8b2d-f187c9f53139)
##### PDF![Screenshot from 2020-12-17 13-41-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f7289213-f96e-4221-be93-05fb78aed3b4)

**Comment by LostMojo** [comment]
That must have happened during the restructuring! The chapter intro has already been merged in, but I'll see if I can make a little hotfix for it

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2020-12-21 13-59-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/06e9bd95-882c-47f8-878a-72033355f873)
