### ISSUE TITLE
accounting - LO links

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2889]
![Screen Shot 2020-10-22 at 9 37 04 AM](https://user-images.githubusercontent.com/11299125/96887432-32f53c00-144a-11eb-97e8-c3b8f59b4bd4.png)

- targeted by a class:  `<link class="lo-reference" document="m#####"/>`
- use this icon https://drive.google.com/file/d/12qOsipeGDvc4PVkpJ-0oFPFnJ050TaOt/view?usp=sharing
- a module link with no anchor text typically returns the words `Section #.#`, this should remove the word Section and replace with the LO svg
- have the blue link be the default link color but WITHOUT the underline
- font and size matches the base text font/size

**Comment by kswanson33** [comment]
The specified selector, `class="lo-reference"`, is not present in accounting

**Comment by lwtchu** [comment]
@kswanson33 😬 I'm starting to have a deep dark fear that whenever it gets transformed from CNXML to HTML, it gets wiped out. we might require the forces of BrittanyJ or ...maybe even Phil. I'll wait to see if BrittanyJ has any insights though. I can at least confirm it's on the CNXML on katalyst01 and production.

**Comment by kswanson33** [comment]
@lwtchu Could always just be a me-problem 🌱 (although I did re-run all my scripts, and still no luck.) I'll wait till after the break on this one!

**Comment by lwtchu** [comment]
@kswanson33 oh no i'm looking at the content on CNX when it's baked...and i don't see the class :joy: so i have a strong scary feeling that some work might need to be done. but also I will pocket the fear for after thanksgiving since we need to be positive for the pie.

**Comment by kswanson33** [comment]
🥧🥧🥧

**Comment by kswanson33** [comment]
Status: Styling for LO links is implemented. Changes to recipe are required to remove the "LO" text before the section number. Currently the accounting recipe adds `LO #.#` to the content in plain text. 

@wilkus27 has [suggested](https://github.com/openstax/cnx-recipes/pull/3222#discussion_r547364147) that "LO" be wrapped in a span element that can be targeted and hidden with `display:none`. I think this is the best way too.

After recipe updates, the HTML should look something like this:

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/3f4e4470-d539-4e01-8d80-7dc1a5ace100)

The recipe work will likely be done after the break.

**Comment by lwtchu** [comment]
@kswanson33 following up on this - did you need anything :eyes:

**Comment by brittany-johnson** [comment]
I just merged the needed recipes change into a.a. This change separates the `LO` text and the module number into different spans. The LO text can now be selected and hidden in a separate PR @kswanson33 
![Screen Shot 2021-01-13 at 10 48 56 AM](https://user-images.githubusercontent.com/24909007/104483188-7533a280-558d-11eb-89dc-f942959b1201.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-15 13-45-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0463383d-aea6-47e8-a2f0-95767b14a6fa)
