### ISSUE TITLE
Business Law: style no class tables

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2890]
Documentation: https://github.com/openstax/cnx-recipes/issues/2741

**Comment by MartaSztuka** [comment]
### PASSED
![Screenshot from 2020-11-02 09-38-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c7f4056f-f48c-40a1-8e0c-b9b68371aeb9)
