### ISSUE TITLE
accounting - red text

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2892]
![Screen Shot 2020-10-23 at 11 20 55 AM](https://user-images.githubusercontent.com/11299125/97028498-d6fde680-1521-11eb-8631-155af6aa54eb.png)

- targeted by `<emphasis class="colored-text">`
- apply the color: R1: `#CC0000`
- remove the bold that is default to `<emphasis>`

**Comment by kswanson33** [comment]
PR: https://github.com/openstax/cnx-recipes/pull/3072

Affects accounting; found on katalyst01 with col25448.

All text targeted by `.colored-text` should be colored with `#CC0000`, and have `font-weight: normal`.

Example of applied changes:
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/ea2766dd-c5e7-48a8-91fe-9cfaa9005522)

**Comment by meeragovindaraju** [comment]
**Test Passed**

<img width="821" alt="Screen Shot 2020-12-02 at 8 51 06 AM" src="https://user-images.githubusercontent.com/33066187/100888439-bd827f80-347b-11eb-94a3-43fca2b9b61b.png">


<img width="776" alt="Screen Shot 2020-12-02 at 8 52 09 AM" src="https://user-images.githubusercontent.com/33066187/100888459-c2473380-347b-11eb-97a7-9b2eab9167ce.png">
