### ISSUE TITLE
accounting - eoc problem sets

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2893]
Accounting has 7 question sections in the EOC.  Not every chapter will have all of them.

### Multiple Choice `<section class="multiple-choice">`
![Screen Shot 2020-10-23 at 5 12 33 PM](https://user-images.githubusercontent.com/11299125/97058301-05e08080-1553-11eb-93be-9dfd6f8222f2.png)

- standard multiple choice exercise 
- exercise number is bolded with period
- the LO number and icon should come from #2889 
- spacing between each exercise is the same as business ethics: 0.7rem
- numbering is 1, 2, 3, etc and continuous for the chapter
- icon: https://drive.google.com/file/d/1Oz3Ej81o-JVLC75amloQ3m-YPDH-hoCN/view?usp=sharing

### Questions `<section class="questions">`
![Screen Shot 2020-10-23 at 5 21 08 PM](https://user-images.githubusercontent.com/11299125/97058735-3e348e80-1554-11eb-8817-d10ba7210218.png)
- icon: https://drive.google.com/file/d/1-IA4Gbm1OlPC2bg8lSedIUUIrjvZdBrB/view?usp=sharing
- exercise number is bolded with period
- LO icon ssame as bove
- spacing between each exercise is 0.7rem
- number is 1, 2, 3, etc and continuous for the chapter

### Exercise Set A / Exercise Set B `<section class="exercise-set-a">` `<section class="exercise-set-b">`
![Screen Shot 2020-10-23 at 5 36 41 PM](https://user-images.githubusercontent.com/11299125/97059553-560d1200-1556-11eb-9635-7c8a9d90f930.png)
- IMPORTANT: i think this is done in the recipe already but the numbering differs in that it starts with EA or EB. EA1, EA2, EA3... and EB1, EB2, etc 
- icon for set A https://drive.google.com/file/d/1LxWsRljZtkKxBDxQQOgFbrvtDRevOc2D/view?usp=sharing
- icon for set B https://drive.google.com/file/d/1-pbKFNu3ZWzyDYsEjfX0gMnUb_MeYWhh/view?usp=sharing
- exercise number is bolded with period
- LO icon ssame as bove
- spacing between each exercise is 0.7rem

### Problem Set A / Problem Set B `<section class="problem-set-a">` `<section class="problem-set-b">`
![Screen Shot 2020-10-23 at 5 49 17 PM](https://user-images.githubusercontent.com/11299125/97060148-19421a80-1558-11eb-80e5-f7dbcc6c6079.png)
-specs are same as the exercise set above as are icons, however numbering is PA1, PB1 respectively

### Thought Provokers `<section class="thought-provokers">`
![Screen Shot 2020-10-23 at 5 49 50 PM](https://user-images.githubusercontent.com/11299125/97060188-2fe87180-1558-11eb-9d43-784b9e379a9e.png)
- specs are the same as all above except numbering is TP1,...
- icon: https://drive.google.com/file/d/1lVezUadPa780bzW-XuOYTP_kbmi0_UmO/view?usp=sharing

**Comment by kswanson33** [comment]
This can be tested, but the LO links won't be styled until that PR is merged. The exercises should look like this:

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/42717f50-8d78-43e8-bae0-d568907be9b6)

Changes affect the EOC exercises on accounting (katalyst01, col25448).

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-18 09-31-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2d463a39-089c-492c-b5dc-00f3d15a9d60)![Screenshot from 2020-12-18 09-32-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2d9df535-243d-4f1d-9fe9-d9088c426a1e)![Screenshot from 2020-12-18 09-32-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d4795874-cc4d-4d99-9cee-2d7a16b05b4e)
