### ISSUE TITLE
accounting - answer key

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2895]
![Screen Shot 2020-10-23 at 6 16 52 PM](https://user-images.githubusercontent.com/11299125/97061286-fade1e00-155b-11eb-814b-6b89794895de.png)
- header schema follows #2644 
- broken up by chapter and by the question types (#2893) 
- numbers for exercises are bold and followed by a period - since they link back i think they should be blue?
- no need for spacing between exercises
- one column

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/095f04a5-1399-4dbb-9cc9-38bf8234981b)

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/dbb4a150-edd0-473f-9f17-6990226c7564)

- Added v-spacing(1) = 1.4rem spacing beneath each set of solutions
- The default H3 title includes margin-bottom=0.7rem -- how do you feel about this? (Spacing below "Multiple Choice" and "Questions" or no spacing?)

**Comment by lwtchu** [comment]
@kswanson33 :eyes: looks good can we have the exercise number counters be black though. i know it'll override the link color

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/13d3afc9-39b7-4b41-a5a2-a761876ad019)
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/ca2917a4-5b8a-483d-aac0-8393908906f2)

**Comment by lwtchu** [comment]
@kswanson33 beautimous. thank you ~

**Comment by kswanson33** [comment]
PR: https://github.com/openstax/cnx-recipes/pull/3092

Affects the answer key section (at end of book) for accounting.

Find accounting on katalyst01.cnx.org with col25448.

Headers should use the standard cardboard header scheme, via #2644. See above for screenshots and specs discussion!

**Comment by meeragovindaraju** [comment]
**Test Passed**

<img width="865" alt="Screen Shot 2020-12-02 at 8 46 52 AM" src="https://user-images.githubusercontent.com/33066187/100887883-17cf1080-347b-11eb-82d1-3e3a04fc1abb.png">

<img width="852" alt="Screen Shot 2020-12-02 at 8 47 09 AM" src="https://user-images.githubusercontent.com/33066187/100887904-1c93c480-347b-11eb-96f3-24e6ba949a0f.png">
