### ISSUE TITLE
Introduction to Business: style Table of Contents

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2897]
Documentation: https://github.com/openstax/cnx-recipes/issues/1740 - version blue

**Comment by MartaSztuka** [comment]
### PASSED
![Screenshot from 2020-10-30 11-45-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/98fd140f-f04c-4309-9657-6940c2e5bd2b)

**Comment by brittany-johnson** [comment]
The final design is missing some specs - the grey background color should be on odd number chapters, not even and the module numbers should be bolded. Reopening

**Comment by kswanson33** [comment]
[Link to PR](https://github.com/openstax/cnx-recipes/pull/3075)

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/ad628869-28d1-43a8-a925-7d096c4c151b)

**Comment by kswanson33** [comment]
[Pull request](https://app.zenhub.com/workspaces/ce-styles-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/3075)

intro-business is on katalyst01 with col25734.

Applied changes affect only the table of contents:

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/924dc3ef-1fb4-460a-b9f6-342075dd5314)

**Comment by meeragovindaraju** [comment]
**Test Passed**

![Screen Shot 2020-12-07 at 6 41 28 PM](https://user-images.githubusercontent.com/33066187/101422283-e95a9680-38bb-11eb-86c1-edfd7c148c4b.png)
