### ISSUE TITLE
Introduction to Business: style figures

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2901]
Documentation: https://github.com/openstax/cnx-recipes/issues/2643

**Comment by MartaSztuka** [comment]
### PASSED
![Screenshot from 2020-10-30 13-13-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ac8e9ff6-f6df-44da-b1d7-0b9f5c618a64)
