### ISSUE TITLE
Introduction to Business: Implement Headers

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2903]
Issue with documentation:  Titles: #2644,  Section number treatment #2710
@MartaSztuka Information for testing purposes >>> Within this issue also Key Terms should be tested, because the have been added within the same PR (Issue with specs:  #2742).

**Comment by MartaSztuka** [comment]
### PASSED
#### Headers![Screenshot from 2020-11-02 10-15-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1e5060a7-22b1-4263-9e73-4b6752c6aab9)![Screenshot from 2020-11-02 10-16-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b2a30b22-1999-4135-8df4-27d60f8d4160)
#### Key Terms![Screenshot from 2020-11-02 10-13-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5fb1261d-3638-4fd8-9789-aafc1783e494)
