### ISSUE TITLE
astronomy - for further exploration

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2906]
![Screen Shot 2020-10-27 at 9 06 38 AM](https://user-images.githubusercontent.com/11299125/97313427-97424200-1834-11eb-90dc-4db4110c9a99.png)

- icon: https://drive.google.com/file/d/1DDH6nL3XsxwNwzK60TuC72p4-Eh5HkmF/view?usp=sharing
- headers should follow #2644 
- there are subsections in this 
- can we have the same treatment as #2745 where the second and third lined sentences are indented?

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/102789019-cd6af080-43a3-11eb-9296-b9c74a940a81.png)

Is it ok? Links will be styled in another PR.

**Comment by lwtchu** [comment]
@wilkus27 this looks good thank you
