### ISSUE TITLE
astronomy - collaborative group activities

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2907]
![Screen Shot 2020-10-27 at 9 20 41 AM](https://user-images.githubusercontent.com/11299125/97314506-ca390580-1835-11eb-8609-fe9e99e98ec1.png)
- icon: https://drive.google.com/file/d/1o9MNsxYFFmRcyK48N4lyOgZLCelZanHG/view?usp=sharing
- headers should follow #2644 
- these are upper alpha lists. can we have them operate the same as the exercises in the EOC? where the counter is bold with a period. and there's space (0.7rem) between each list item?

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/102897376-2ef49300-4468-11eb-8c41-aba0f32b7df4.png)

Is it ok?

**Comment by lwtchu** [comment]
@wilkus27 yes thank you~
