### ISSUE TITLE
astronomy - exercises

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2909]
![Screen Shot 2020-10-27 at 9 24 48 AM](https://user-images.githubusercontent.com/11299125/97315054-4cc1c500-1836-11eb-95df-122576955486.png)

- headers should follow #2644 
- there are sub sections in this that break out the different types of questions
- exercises should be the same as the other books in the theme (number is bold, with period, 0.7 rem between exercises)
- icon https://drive.google.com/file/d/1gawt9Vc5hkhYoac3qAYTlcPE7tzfqBmR/view?usp=sharing

**Comment by ajluk** [comment]
@lwtchu Here is how the Exercises look styled: 
![image](https://user-images.githubusercontent.com/55203598/103552195-cf58a780-4eab-11eb-9b1b-58617ce26a46.png)
I have used P1 color ( #3B2746) for H2 titile, I assumend it is the correct one. Is that ok?

**Comment by lwtchu** [comment]
@ajluk yes thank you

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-08 10-16-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2d76404a-82c0-4db6-a67f-30cff64bdaca)
