### ISSUE TITLE
Introduction to Business: implement Splash image, Chapter Outline, Introduction

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2910]
Issues with documentation: https://github.com/openstax/cnx-recipes/issues/2655 , https://github.com/openstax/cnx-recipes/issues/2642

**Comment by ajluk** [comment]
Screenshot for refenrence: 
![image](https://user-images.githubusercontent.com/55203598/97451210-d0151080-1933-11eb-93c1-d0adef404b5e.png)
Learning outcomes will be styled within another PR.

**Comment by MartaSztuka** [comment]
### PASSES![Screenshot from 2020-11-02 11-23-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6feb4234-3832-4dda-9283-520659947ca2)
