### ISSUE TITLE
Change folio footer/ preface header text in Fizyka and Psychologia to Polish analogue text

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2913]
Currently all books have set footer and preface header folio text in English: 
![image](https://user-images.githubusercontent.com/55203598/97435721-1e6ce400-1921-11eb-94d2-471e81a443f5.png)
We would like to change "Access for free at openstax.org" text to "Podręcznik dostępny na openstax.org” in the footer and "Preface" text to "Przedmowa" in the Preface header .

**Comment by MartaSztuka** [comment]
### PASSED
#### Fizyka 1![Screenshot from 2020-11-13 10-14-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dcd0322d-9865-464e-ada9-09cdb552da1d)
#### Fizyka 2![Screenshot from 2020-11-13 10-16-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/88ebe188-dd6f-4dfd-bcfe-67a0d2eafa37)
#### Fizyka 3![Screenshot from 2020-11-13 10-17-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dd49214c-d6a4-42c8-af9a-a21552e1e159)
