### ISSUE TITLE
Introduction to Business: Implement tables

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2916]
Issue: #2741

**Comment by MartaSztuka** [comment]
### PASSED![Screenshot from 2020-11-13 12-59-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4bb0fe14-d786-4c75-973a-d8f60298be41)![Screenshot from 2020-11-13 12-59-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bc45b015-3fb9-428d-b606-1c96f943c1cd)![Screenshot from 2020-11-13 12-58-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fc4c9dbe-e928-46fd-bbe4-63e55241b522)
