### ISSUE TITLE
Introduction to Business: Implement footnotes, blockquotes, links

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2917]
Documentation issues:  
Footnotes #2773
Blockquotes #2749

**Comment by MartaSztuka** [comment]
### PASSED
#### Footnotes![Screenshot from 2020-11-02 13-49-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f09c7fdd-2d7d-425e-8614-6050469688c2)
#### Links![Screenshot from 2020-11-02 13-50-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ae2bb4f0-8017-4da9-abe5-ea55222fb934)
#### Blackquotes![Screenshot from 2020-11-02 14-08-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b603b9f8-8c40-47ef-a5a5-bad915f87f0c)

**Comment by MartaSztuka** [comment]
### FAILED
#### Blockquotes
@lwtchu Those are seperated blockquotes, and there's page break here, is this how blockquotes should look?
![Screenshot from 2020-11-02 14-08-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b603b9f8-8c40-47ef-a5a5-bad915f87f0c)![Screenshot from 2020-11-02 14-20-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/33e9a4df-6a13-4bdc-87f0-628cec72d05f)

**Comment by lwtchu** [comment]
@MartaSztuka #2749  -- here's the documentation card for blockquotes

**Comment by ajluk** [comment]
@lwtchu Did you mean that the styling is fine here and shouldn't  change anything?

**Comment by lwtchu** [comment]
@ajluk oh sorry i didn't understand the question completely - i think it's okay to me. the page break isn't ideal, but i think it's fine.
