### ISSUE TITLE
Introduction to Business: style Catching the Entrepreneurial Spirit note

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2924]
Issue with documentation: https://github.com/openstax/cnx-recipes/issues/2737

**Comment by MartaSztuka** [comment]
### PASSED![Screenshot from 2020-11-13 12-57-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d886b86d-6f9e-4de8-9907-e80615a28b86)
