### ISSUE TITLE
Business Intro: style all of the rest Icon Boxed notes

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2928]
Documentation issue: #2737 
Notes styled within this issue and connected PR:
![image](https://user-images.githubusercontent.com/55203598/98108109-c5aac780-1e9b-11eb-823e-9d444962d00e.png)

**Comment by MartaSztuka** [comment]
### PASSED
#### MANAGING CHANGE![Screenshot from 2020-11-13 11-58-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c18e23a8-5008-4ccf-a55e-f8d3171f4dfd)
#### CONCEPT CHECK![Screenshot from 2020-11-13 11-59-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5b448195-9006-436e-9ea2-ff089000a953)
#### CUSTOMER SATISFACTION AND QUALITY![Screenshot from 2020-11-13 12-00-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7ac0d47e-9cb7-462d-a593-fd9ba9e62d95)
#### EXPANDING AROUND THE GLOBE![Screenshot from 2020-11-13 11-57-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c8d34c78-4c21-437e-9ef6-083cb056715e)
#### ETHICS IN PRACTICE![Screenshot from 2020-11-13 12-01-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/87853a06-a368-4ae1-8178-997b53d03028)
