### ISSUE TITLE
Introduction to Business: style EoC Sections

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2931]
Within this issue all of the EOC sections in Introduction to Business will be styled.
Issues with documentation: 
Summary #2782,
Preparing for tomorrow's workplace skills #2783
Ethics activity #2785
Working the net #2786
Critical thinking case #2789
List Title: #3039

**Comment by MartaSztuka** [comment]
### PASSED
#### Summary![Screenshot from 2020-11-13 13-01-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f20bcccf-dea7-427e-a80a-052fd5f8c829)
#### Preparing for tomorrow's workplace skills![Screenshot from 2020-11-13 13-03-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/963983e4-f36e-4a30-95a2-21b6511c9b1b)
#### Ethics activity![Screenshot from 2020-11-13 13-04-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d44612a4-1d27-41f5-90c3-0cbce68394e1)
#### Working the net![Screenshot from 2020-11-13 13-04-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9d48f514-5775-497c-8184-3f58a28c5518)
#### Critical thinking case![Screenshot from 2020-11-13 13-05-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/675901fe-a037-491e-923f-c6d861f3e6ad)
#### List Title![Screenshot from 2020-11-13 13-05-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/77dc5ade-a6cf-47a6-a7a4-8d737f953317)
