### ISSUE TITLE
Tables Aren’t Styled in Solutions of Examples

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#2933]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know

![2020-11-05_11-19-48.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/3531adb8-fe66-46fa-836d-6a8d22b16102)

Table looks like it has the unstyled class but it doesn't have any class. 
`<table id="Table_01_01_12" summary="Two rows and six columns. The first row is labeled, “n” and the second row is labeled, “g(n)”. Reading the columns as ordered pairs, we have: (1, 8), (2, 6), (3, 7), (4, 6) , and (5, 8)." class="unnumbered"><label/>`

# Acceptance Criteria
Tables in solutions are styled correctly. 

# Bug Location(s)
collection ID: col11667
server: Prod
chapter/section: Chapter 1 Section 1
surrounding text: When we input 2 into the function our output is 6.

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by brittweinstein** [comment]
@lwtchu please put prio on this

**Comment by brittweinstein** [comment]
This is a table nested in a list within a solution -- @lwtchu does not think it is styled if it is within a list.

**Comment by ajluk** [comment]
@lwtchu This is a content issue. I checked in the content on `katalyst01` and the `unstyled` class hasn't been removed from the table. I guess the same problem isin the content in production: 
![image](https://user-images.githubusercontent.com/55203598/107622355-04e57300-6c58-11eb-9cce-8dbe15b24f38.png)

**Comment by marcjeannott** [comment]
Just realized the code I posted was the problem's and not the solution's shown in the screenshot, though neither have the unstyled class applied, I've updated my original post with the markup of the solution's table.

**Comment by lwtchu** [comment]
@marcjeannott can you either migrate this module to katalyst01 or make the change eon katalyst01 so anna can fix? thanks

**Comment by marcjeannott** [comment]
@lwtchu done - https://legacy-katalyst01.cnx.org/content/m49301/latest/

**Comment by ajluk** [comment]
@lwtchu Sorry for the delay, but I have missed the notification somehow. I have fetched the the updated content and the tables looks good: 
![image](https://user-images.githubusercontent.com/55203598/108995928-0d00d200-769e-11eb-99ac-53238d2dafb6.png)

**Comment by lwtchu** [comment]
@marcjeannott do you know when the original screenshot pdf you have was generated?

**Comment by marcjeannott** [comment]
@lwtchu I thought you generated and marked up the original PDF, so I'm not sure.

**Comment by lwtchu** [comment]
Closing card. It's fixed
