### ISSUE TITLE
Accounting: Table of Contents

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2934]
Should be in line with: https://github.com/openstax/cnx-recipes/issues/1740

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/59f4c5f5-4454-4c68-8ba1-59325a2c5e8a)

After applying all styles, the TOC looks like this. I have checked intro-business, which has a TOC that's been approved, and determined that intro-business is inheriting some styles from the root which are essential to making the TOC look appropriately styled. 

@lwtchu What styles should be applied at the root of accounting? Is there a card for this?

**Comment by lwtchu** [comment]
@brittany-johnson can you advise on the root thing? i'm not sure how the other titles are being styled :eyes:

**Comment by kswanson33** [comment]
@lwtchu @brittany-johnson I have now determined that a one-line addition of an import from common fixes this issue. It does also add additional styles throughout the book. I think this is probably what we want, but it seems to be outside the scope of this card! Thoughts?

**Comment by lwtchu** [comment]
@kswanson33 i think it's up to you ... i don't have strong feelings about it but it might be helpful for new folks?? is this something that needs to happen for every new book..like there's theme level styles to import?

**Comment by kswanson33** [comment]
@lwtchu I'll follow up with my team about this!

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/9d660f14-4077-4ec9-b1a1-5c2379910065)

@lwtchu Progress so far^ 

The only thing that doesn't match the specs at this point is that the chapter numbers (1.1, 2.3, etc) aren't bold (they are bold in the specs). I've looked into it, and previously approved ToCs ([intro-business](https://github.com/openstax/cnx-recipes/issues/2897) and [business-ethics](https://github.com/openstax/cnx-recipes/issues/2803)) are also missing that style. 

Option 1: I could match these books by skipping the bold
Option 2: I could add the bold styling to just the accounting book
Option 3: I could add the bold styling to the cardboard theme, which would affect all books.

What do you think is best?

**Comment by brittany-johnson** [comment]
Hello! @kswanson33 I just re-opened and assigned you to https://github.com/openstax/cnx-recipes/issues/2897
While you're implementing the design for Accounting, can you make changes to the TOC components and shapes so that the comment I left in #2897 is addressed in both books? 

Thank you for pointing out the missing bold text!

**Comment by kswanson33** [comment]
@brittany-johnson Will do!

**Comment by kswanson33** [comment]
Changes applied to accounting:

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/025167b7-7a97-4e55-8861-a0e8bbf72338)


Accounting is on katalyst01 with col25448.

Discussion of specs is above, and on [the PR](https://app.zenhub.com/workspace/o/openstax/cnx-recipes/issues/3075).

**Comment by meeragovindaraju** [comment]
**Test Passed**

![Screen Shot 2020-12-07 at 4 41 40 PM](https://user-images.githubusercontent.com/33066187/101414201-469a1c00-38ab-11eb-9657-79d2d7e78055.png)

![Screen Shot 2020-12-07 at 4 42 36 PM](https://user-images.githubusercontent.com/33066187/101414207-4ac63980-38ab-11eb-9145-af204f2f4f68.png)
