### ISSUE TITLE
Accounting: Splash image

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2935]
Should be in line with https://github.com/openstax/cnx-recipes/issues/2642

**Comment by kswanson33** [comment]
Will be resolved with #2888.

**Comment by meeragovindaraju** [comment]
I have tried to fetch and pull twice but I don't see the intended changes to the splash image

![Screen Shot 2020-12-08 at 5 23 08 PM](https://user-images.githubusercontent.com/33066187/101553382-24bb9a80-397a-11eb-963b-ac6bf2d742c9.png)

**Comment by kswanson33** [comment]
The recipe isn't working for the intro section right now on the bakery CLI. In order to see changes applied, use docker-compose to fetch/assemble/bake. :(

**Comment by meeragovindaraju** [comment]
**Test Passed**

![Screen Shot 2020-12-09 at 5 36 41 PM](https://user-images.githubusercontent.com/33066187/101701817-50f01d80-3a45-11eb-8aaa-62b13322da02.png)
