### ISSUE TITLE
Accounting: figure/table number and caption styling

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2936]
Should be in line with https://github.com/openstax/cnx-recipes/issues/2643

**Comment by kswanson33** [comment]
- Affects the figure numbers and captions on images and tables in accounting.
- [Link to branch](https://github.com/openstax/cnx-recipes/pull/3114)
- Applied changes:

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/2e1621b0-f9b9-4bd7-aeed-eeb9e62c0689)

**Comment by kswanson33** [comment]
- Selector: `.os-caption-container`
- Doesn't affect the captions on splash images

**Comment by meeragovindaraju** [comment]
**Test Passed**

![Screen Shot 2020-12-03 at 2 00 15 PM](https://user-images.githubusercontent.com/33066187/101094714-703d0580-3582-11eb-9b04-3aa701945c19.png)


![Screen Shot 2020-12-03 at 4 12 35 PM](https://user-images.githubusercontent.com/33066187/101094727-74692300-3582-11eb-8b4c-e0592be30353.png)
