### ISSUE TITLE
Accounting: Headers

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2937]
Should be in line with https://github.com/openstax/cnx-recipes/issues/2644

**Comment by MartaSztuka** [comment]
Hi, @LostMojo ! Headers look ok, but there's Preface class missing. Here's the issue about it: https://github.com/openstax/cnx-recipes/issues/3115 so I'm closing this one.![Screenshot from 2020-12-03 13-35-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/86c69b79-91ad-4621-90d5-92ac9aa55593)
