### ISSUE TITLE
Accounting: Footnotes

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2940]
Should follow https://github.com/openstax/cnx-recipes/issues/2773

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/485e545d-ea94-4202-90b1-4448a1709ea8)

**Comment by kswanson33** [comment]
Specs #2773

Changes applied to footnotes in accounting
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/1d45e3a0-cbb0-4a72-b0a6-46a1e495aae3)

[Link to PR](https://github.com/openstax/cnx-recipes/pull/3117)

accounting is on katalyst01 with col25448

**Comment by meeragovindaraju** [comment]
**Test Passed**

![Screen Shot 2020-12-08 at 11 44 51 AM](https://user-images.githubusercontent.com/33066187/101521085-f2df0f80-394a-11eb-816a-2f6d5e908d73.png)

![Screen Shot 2020-12-08 at 11 45 05 AM](https://user-images.githubusercontent.com/33066187/101521089-f377a600-394a-11eb-9de2-b54babfe3c29.png)

![Screen Shot 2020-12-08 at 11 45 40 AM](https://user-images.githubusercontent.com/33066187/101521090-f377a600-394a-11eb-9c24-fc0d56176d0a.png)
