### ISSUE TITLE
Accounting: Think It Through

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2942]
`<note class="think-through">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with color option 2

**Comment by LostMojo** [comment]
40 Test Content Locations
collection ID: col25448
server: katalyst01.cnx.org
chapter/section: Sprinkled throughout

![Screen Shot 2020-12-01 at 11.42.08 AM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/9013a79c-7985-419d-bd5b-3d0f035196c8)

**Comment by meeragovindaraju** [comment]
**Test Passed** But the PDF had only 4 'Think it through' sections. The PDF did not have all the content. 

![Screen Shot 2020-12-03 at 4 53 25 PM](https://user-images.githubusercontent.com/33066187/101098363-6ae2b980-3588-11eb-8c67-336a7b5f3330.png)

[collection.pdf](https://github.com/openstax/cnx-recipes/files/5639461/collection.pdf)
