### ISSUE TITLE
Accounting: Concepts In Practice

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2943]
`<note class="concepts-practice">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with color option 2

**Comment by kswanson33** [comment]
https://github.com/openstax/cnx-recipes/pull/3060

**Comment by kswanson33** [comment]
This content can be fetched from katalyst01.cnx.org, with col25448. Specs: [Color option 2](https://github.com/openstax/cnx-recipes/issues/2737). 

Screenshot of applied changes:
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/01ff75ad-6604-4669-a4b6-bf2f114093fb)

**Comment by meeragovindaraju** [comment]
Concepts in Practice looks good 

![Screen Shot 2020-11-18 at 12 15 23 PM](https://user-images.githubusercontent.com/33066187/99573511-cfecbb80-299b-11eb-8f53-cccdb6a6fbf8.png)

**Comment by kswanson33** [comment]
https://github.com/openstax/cnx-recipes/issues/2944 Thread where we discuss the letter spacing issue in the title
