### ISSUE TITLE
Accounting: Your Turn

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2944]
`<note class="your-turn">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with color option 3

**Comment by LostMojo** [comment]
@lwtchu 

Two Things:
- What letter spacing in the title should be used?
- The padding around the title seems greater in the example

![Screen Shot 2020-11-16 at 3.09.48 PM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/a4eb49b6-21fc-4fc6-961f-d2123096d72c)

**Comment by kswanson33** [comment]
Same questions apply to #2943!

**Comment by lwtchu** [comment]
@LostMojo 😬  can you check the letter spacing that natalia or anna used for the stuff in business ethics since i just approved those. 

the example is following old grid scale values - i think whatever we do now should be consistent with the stuff implemented in business ethics? 😬  if that's okay. if not, let me know and we can park/discuss/hop on a call/whatever you need

**Comment by brittany-johnson** [comment]
@LostMojo @kswanson33 After pulling the latest on the milestone branch, try fetching and generating the business-ethics book and taking a look at the `RealWorld` note, looks like it also uses option 2. For option 3, try looking at `WhatWould` 

You can also look at one of the recently closed business-ethics cards

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/ff63324c-6e5c-44c9-a620-eca42a1c6855)

Here's a `What Would` note from a closed card in business-ethics. To me, the letter spacing and the padding looks the same.

**Comment by lwtchu** [comment]
@kswanson33 looks great thank you - i assume lists will be covered by a separate list issue?

**Comment by kswanson33** [comment]
@lwtchu Presumably? If you're looking at the bullet points being off to the left on the image above, that image was from a closed business-ethics card, which I linked.

**Comment by lwtchu** [comment]
@kswanson33 OH LOL my reading comprehension was not good. um. yeah i think what you had is fine 😬

**Comment by meeragovindaraju** [comment]
Your Turn looks good

![Screen Shot 2020-11-19 at 4 57 58 PM](https://user-images.githubusercontent.com/33066187/99734426-65fe1000-2a88-11eb-90a0-5c429b38c537.png)
