### ISSUE TITLE
Accounting: IFRS Connection

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2945]
`<note class="ifrs-connection">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with color option 2

**Comment by kswanson33** [comment]
Specs #2737

Changes applied to IFRS Connection note

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/d2a6a62e-2834-4b17-9e6d-0476f0aeef9e)

[Link to PR](https://github.com/openstax/cnx-recipes/pull/3119)

accounting is on katalyst01 with col25448

**Comment by meeragovindaraju** [comment]
**Test passed**

![Screen Shot 2020-12-09 at 5 44 41 PM](https://user-images.githubusercontent.com/33066187/101702332-42eecc80-3a46-11eb-8f66-e153759ef263.png)
