### ISSUE TITLE
Accounting: Ethical Considerations

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2946]
`<note class="ethical-considerations"> `- uses #2737 with color option 2

**Comment by kswanson33** [comment]
Specs #2737

Changes applied to Ethical Considerations note in accounting

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/8f3d1460-385f-4408-af06-1e700f9340f1)

[Link to PR](https://github.com/openstax/cnx-recipes/pull/3119)

accounting is on katalyst01 with col25448

**Comment by meeragovindaraju** [comment]
**Test Passed**

![Screen Shot 2020-12-09 at 5 41 36 PM](https://user-images.githubusercontent.com/33066187/101702098-d4aa0a00-3a45-11eb-9d9e-c3d6eb69821b.png)
