### ISSUE TITLE
Accounting: Link to Learning

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2947]
`<note class="link-to-learning"> `- uses #2737 with color option 1

**Comment by kswanson33** [comment]
Specs #2737

Changes applied to Link to Learning note in accounting

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/8da09257-0b2b-41c4-a16a-7ea86a94c17e)

[Link to PR](https://github.com/openstax/cnx-recipes/pull/3119)

accounting is on katalyst01 with col25448

**Comment by meeragovindaraju** [comment]
**Test Passed**

![Screen Shot 2020-12-09 at 5 40 30 PM](https://user-images.githubusercontent.com/33066187/101702026-af1d0080-3a45-11eb-8830-09731a9e09fd.png)
