### ISSUE TITLE
Accounting: Continuing Application at Work

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2948]
` <note class="continuing-application">`- uses https://github.com/openstax/cnx-recipes/issues/2737 with color option 2

**Comment by kswanson33** [comment]
Specs #2737

Changes applied to Continuing Application at Work note in accounting

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/81fd7a25-47f6-4385-9e10-e5fcb520749f)

[Link to PR](https://github.com/openstax/cnx-recipes/pull/3119)

accounting is on katalyst01 with col25448

**Comment by meeragovindaraju** [comment]
**Test Passed**

![Screen Shot 2020-12-09 at 5 39 18 PM](https://user-images.githubusercontent.com/33066187/101701946-85fc7000-3a45-11eb-911d-74d457554932.png)
