### ISSUE TITLE
Accounting: Key Terms

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2949]
Should follow: https://github.com/openstax/cnx-recipes/issues/2742

**Comment by kswanson33** [comment]
Changes applied to the Key Terms section in accounting following 


[Link to PR](https://github.com/openstax/cnx-recipes/pull/3124)

**Comment by meeragovindaraju** [comment]
**Test Passed**

![Screen Shot 2020-12-07 at 4 57 19 PM](https://user-images.githubusercontent.com/33066187/101415344-56b2fb00-38ad-11eb-9286-02cb2decd25d.png)
