### ISSUE TITLE
Accounting: Summary

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2950]
should be the same as https://github.com/openstax/cnx-recipes/issues/2743 but it has a bulleted list and the list follows standard list indentation

**Comment by kswanson33** [comment]
Specs #2743

Changes applied to the summary section of accounting
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/0b6abd26-3268-4085-9d09-0749f633b4ca)

[Link to PR](https://github.com/openstax/cnx-recipes/pull/3125)

Accounting is on katalyst01 with col25448

**Comment by meeragovindaraju** [comment]
**Test Passed**

![Screen Shot 2020-12-07 at 6 07 17 PM](https://user-images.githubusercontent.com/33066187/101420408-af879100-38b7-11eb-9d37-ea0c837852d8.png)
