### ISSUE TITLE
Accounting: Index

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2952]
Should follow https://github.com/openstax/cnx-recipes/issues/2746

**Comment by kswanson33** [comment]
Changes applied to the accounting index from specs in #2746
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/4f44cec1-3179-4d8c-b279-58433662dc97)

[Pull request](https://github.com/openstax/cnx-recipes/pull/3127)

Accounting is on katalyst01 with col25448

**Comment by meeragovindaraju** [comment]
**Test passed**

![Screen Shot 2020-12-07 at 4 47 09 PM](https://user-images.githubusercontent.com/33066187/101415030-d1c7e180-38ac-11eb-9c2e-fa3049e7a0b2.png)
