### ISSUE TITLE
Entrepreneurship: Table of Contents

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2953]
Should follow https://github.com/openstax/cnx-recipes/issues/1740

**Comment by MartaSztuka** [comment]
#### PASSED ![Screenshot from 2020-12-01 14-35-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/022720af-deb7-4e0b-9226-ad8e33db286f)
