### ISSUE TITLE
Entrepreneurship: Splash Images

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2954]
Should follow https://github.com/openstax/cnx-recipes/issues/2642

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/100116809-79d4b800-2e74-11eb-9d1b-9c7436c533af.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-03 09-53-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e02e6fad-d2b7-4de8-9eef-69c58ce2fbba)
