### ISSUE TITLE
Entrepreneurship: figure/table number and caption styling

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2955]
Should follow https://github.com/openstax/cnx-recipes/issues/2643

**Comment by MartaSztuka** [comment]
#### PASSED ![Screenshot from 2020-12-01 14-26-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0c51291b-b71f-45ea-ba33-e6b14f8848d8)
