### ISSUE TITLE
Entrepreneurship: Headers

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2956]
should follow https://github.com/openstax/cnx-recipes/issues/2644

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-01 14-58-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bf9248f1-7a46-4d56-b6cd-69e808af48e7)
