### ISSUE TITLE
Entrepreneurship: chapter outline & introduction

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2957]
Should follow https://github.com/openstax/cnx-recipes/issues/2655

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/100116771-6de8f600-2e74-11eb-8299-9e716abe31b4.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-03 09-46-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9f105a0c-7700-4ff4-b924-0ce5fb02e3ff)
