### ISSUE TITLE
Entrepreneurship: section number treatment

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2958]
Should follow https://github.com/openstax/cnx-recipes/issues/2710

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2020-12-01 14-56-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e369ec85-5910-424b-83fc-c935a5e2fe58)
