### ISSUE TITLE
Entrepreneurship: Learning Objectives

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2959]
Should follow https://github.com/openstax/cnx-recipes/issues/2711

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/100230071-806f3800-2f25-11eb-98be-a9c23d6692e1.png)
The space under the module title will be added within PR styling headers.

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-03 09-45-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a8437ef6-f0d4-4359-9cdf-ab8c5f7a3bd0)
