### ISSUE TITLE
Entrepreneurship: Tables

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2960]
Should follow https://github.com/openstax/cnx-recipes/issues/2741 (mostly default style and some text-heavy, top-titled)

**Comment by ajluk** [comment]
Screeenshot for reference of top-titled text-havy tables in Entrepreneurship (they can be found in the html file by `os-text-heavy-top-titled-container` class): 
![image](https://user-images.githubusercontent.com/55203598/100341638-1fa33680-2fdd-11eb-8a49-2ae23b76f27a.png)
Within this issue also top titled tables need to be tested in Entrepreneurship and  default tables for example in Introduction to Business (I haven't found default tables without specific class in Entrepreneurship).
How they should look (Intro Business): 
![image](https://user-images.githubusercontent.com/55203598/100341978-9b9d7e80-2fdd-11eb-8fdc-20f4dd001466.png)
![image](https://user-images.githubusercontent.com/55203598/100342060-b3750280-2fdd-11eb-8c71-557d1ae1fdd2.png)
![image](https://user-images.githubusercontent.com/55203598/100341931-89234500-2fdd-11eb-939f-8ba3bfb92d44.png)
Entrepreneurship:
![image](https://user-images.githubusercontent.com/55203598/100342363-2c745a00-2fde-11eb-8fea-63133f83b8c7.png)
![image](https://user-images.githubusercontent.com/55203598/100342484-5594ea80-2fde-11eb-801b-d8d49cf38379.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-03 10-16-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5fc7773c-e25e-4664-9698-47a674e438a7)![Screenshot from 2020-12-03 10-15-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fa721a31-d6b3-4f46-b4a6-1b5ba5bd12d8)
