### ISSUE TITLE
Entrepreneurship: Footnotes

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2961]
Should follow https://github.com/openstax/cnx-recipes/issues/2773

**Comment by MartaSztuka** [comment]
#### PASSED ![Screenshot from 2020-12-01 14-25-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/66d39568-ea8b-44b3-a34c-1bb758a90a38)
