### ISSUE TITLE
Entrepreneurship: Are You Ready?

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2962]
`<note class="are-you-ready">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with color option 3

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-01 15-11-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e83dab5a-da9c-4944-b1d4-fe552a530b42)
