### ISSUE TITLE
Entrepreneurship: What Can You Do?

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2963]
`<note class="what-can-do">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with color option 3

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-02 11-13-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/658a282d-80ac-4bb2-aba8-9f089290a69c)
