### ISSUE TITLE
Entrepreneurship: Link to Learning

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2964]
`<note class="link-to-learning">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with color option 1

**Comment by MartaSztuka** [comment]
#### PASSED
Link's font and colour to be styled later.
![Screenshot from 2020-12-02 11-00-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/449f967c-b50c-48e8-9ae1-ab0f7b1cbf52)
