### ISSUE TITLE
Entrepreneurship: Entrepreneur in Action

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2965]
`<note class="entrepreneur-in-action">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with color option 2

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-02 10-57-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f7ae1439-4793-4263-8149-c53a61e2a265)
