### ISSUE TITLE
Entrepreneurship: Work It Out

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2966]
`<note class="work-it-out"> `- uses https://github.com/openstax/cnx-recipes/issues/2737 with color option 2

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-02 10-56-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7e519aca-93c7-4d3e-933b-c9d29840017d)
