### ISSUE TITLE
Entrepreneurship: Key Terms

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2967]
Should follow https://github.com/openstax/cnx-recipes/issues/2742
`class="key-terms"`

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-02 11-33-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/54fa07f1-d3d3-4aa9-a178-128affaec1ba)
