### ISSUE TITLE
Entrepreneurship: Summary

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2968]
Should follow https://github.com/openstax/cnx-recipes/issues/2743 

`class="section-summary"`

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-02 13-28-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ffbfa54d-9b1e-4dea-941e-0ddcf0365417)
