### ISSUE TITLE
Entrepreneurship: Discussion Questions

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2970]
`class="discussion-questions" `

https://github.com/openstax/cnx-recipes/issues/2700 (same specs, different title. this doesn't have the multiple choice list as well but spacing should be the same between the exercises. icon: https://drive.google.com/file/d/1lb8jseP8ES7W7wqmr4uH2gb2UNnCFJ-Z/view?usp=sharing)

**Comment by ajluk** [comment]
@brittweinstein the documentation link from above is by mistake pointing to some closed issue, but it should be rather #2744 (the same as for Review Questions). I was asking Larissa for confirmation in this comment:  https://github.com/openstax/cnx-recipes/issues/2885#issuecomment-734878977

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/100471597-e05b0f80-30da-11eb-954c-ac94fb410af2.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-03 11-06-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b810d433-36c1-422e-9c71-f51a1a8f8343)
