### ISSUE TITLE
Entrepreneurship: Case Questions

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2971]
Case Questions `class="case-questions"` - same as discussion questions but with this icon: https://drive.google.com/file/d/1tZDE2I5JPF6Ggo676xs79VSs4izviUKQ/view?usp=sharing

**Comment by ajluk** [comment]
@brittweinstein Here is the same situation as with Discussion Question, the correct link to documentation issue should be rather #2744.

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/100471720-27e19b80-30db-11eb-965a-50c8d2e0726a.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-03 12-40-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d2c11f7f-83eb-4178-84af-b0a4e763655f)
