### ISSUE TITLE
Entrepreneurship: Appendices

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2972]
Should follow schema in https://github.com/openstax/cnx-recipes/issues/2644

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2020-12-01 14-36-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ebb708b6-9192-4dd8-b528-70890208dbb9)

**Comment by MartaSztuka** [comment]
### EDIT: Links are not active, the are just paragraphs.
#### PASSED
![Screenshot from 2020-12-01 14-39-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/98eb0d0f-d320-4813-9cc9-57eaf89a549e)

**Comment by brittweinstein** [comment]
@brittany-johnson will confirm that this is an issue on production before passing it along to the Content Managers.

**Comment by lwtchu** [comment]
@MartaSztuka @brittweinstein this is expected behavior. i will close this. if there's another issue, feel free to open again.
