### ISSUE TITLE
Entrepreneurship: Index

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2973]
should follow https://github.com/openstax/cnx-recipes/issues/2746

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-03 13-32-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/477a2d39-4b0d-4a1d-bf5c-3f1e0741c0a3)
