### ISSUE TITLE
Intro Business: Appendices

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2975]
Should follow header schema in https://github.com/openstax/cnx-recipes/issues/2644

**Comment by ajluk** [comment]
@brittweinstein I have worked on this issue together with other EoB section within this issue: #3040.

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-11-20 12-07-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a42fb4c7-cd42-4a20-823b-5d29a7b6bfb4)
