### ISSUE TITLE
Principles of Management: Table of Contents

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2976]
Should follow https://github.com/openstax/cnx-recipes/issues/1740

uses the blue version

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2020-11-23 10-43-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c085eb85-2078-450a-87a1-f9a14abb81e2)
