### ISSUE TITLE
Principles of Management: Splash Images

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2977]
https://github.com/openstax/cnx-recipes/issues/2642 

uses blue version; city scape icon

**Comment by MartaSztuka** [comment]
#### PASSED ![Screenshot from 2020-11-20 17-17-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/486e5283-7226-44ce-86b2-985dfd3550be)
