### ISSUE TITLE
Principles of Management: figure/table number and caption styling

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2978]
Should follow https://github.com/openstax/cnx-recipes/issues/2643

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-11-20 17-00-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7cb5425f-52fd-49ec-8466-48cd2d48126f)![Screenshot from 2020-11-20 17-01-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/66100864-3809-4c1a-bd53-15e2be45321b)
