### ISSUE TITLE
Principles of Management: chapter outline & introduction

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2980]
Should follow https://github.com/openstax/cnx-recipes/issues/2655

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-11-20 17-19-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4a9b3890-fd15-434e-941c-6d1d18f7fc4e)
