### ISSUE TITLE
Principles of Management: Section Numbers

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2981]
should follow https://github.com/openstax/cnx-recipes/issues/2710

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2020-11-23 10-41-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c25c0d65-c4ba-4f88-bee6-2bd93bb3a452)
