### ISSUE TITLE
Principles of Management: Learning Outcomes

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2982]
Should follow https://github.com/openstax/cnx-recipes/issues/2711 

They are called "Learning Outcomes"

**Comment by MartaSztuka** [comment]
#### FAILED
@ajluk I think `After reading this chapter...` should not be bold, since `By the end of this chapter...` isn't in other books. Is that correct? ![Screenshot from 2020-11-20 17-22-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/18e1019f-29b5-4476-89ce-f15baa0af3fa)

**Comment by ajluk** [comment]
@MartaSztuka the paragraph is bolded in the content in this book: 
![image](https://user-images.githubusercontent.com/55203598/99826513-bfce0b00-2b58-11eb-8d76-760c2f5ecf7c.png)
@lwtchu Could you advice if it should stay this way?

**Comment by lwtchu** [comment]
yes. if it's in the content, let's leave it for now. @MartaSztuka if everything else looks ok, feel free to pass and close

**Comment by brittweinstein** [comment]
@ajluk please put points on this when you can.
