### ISSUE TITLE
Principles of Management: Tables

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2983]
Should follow https://github.com/openstax/cnx-recipes/issues/2741

(mostly default style,` top-titled`) ** utilizes a lot of content driven alignment for text

**Comment by ajluk** [comment]
@lwtchu I couldn't find any top-ttiled tables in Priniciples of Management book, so I guess it is the same content issue as it was with Introduction to Business. I have only styled default basic tables. Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/99512733-189b7900-298a-11eb-9862-e7455d383bed.png)

**Comment by lwtchu** [comment]
@ajluk thank you anna. it looks good.

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-11-20 16-55-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/28251807-0887-424c-b1b1-23beece0c4b7)
