### ISSUE TITLE
Principles of Management: Footnotes

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2984]
Should follow https://github.com/openstax/cnx-recipes/issues/2773 

(there are two in chapter 14.3 Process Theories...)

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/99531029-6c19c100-29a2-11eb-8678-947e7f46ab79.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2020-11-23 11-04-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e6d7e0f6-847b-464a-8eae-bd8b87a2452c)
