### ISSUE TITLE
Principles of Management:  Exploring Managerial Careers 

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2986]
`<note class="exploring-manager-careers">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with option 4 - exact same as "Exploring Business Careers" but this is titled "Exploring Managerial Careers" be sure to test with <title> in the note

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-11-23 13-56-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/96688e5d-6389-4992-8491-0193228171ff)
