### ISSUE TITLE
Principles of Management: Concept Check

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2987]
`<note class="concept-check">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with option 5 icon https://drive.google.com/file/d/1QkZHu0sGGcZWc5FY6cfmPa-b79X0e2Mz/view?usp=sharing be sure to test with <title> in the not

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-11-23 12-39-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ab23351f-f836-44a8-ba55-d9b53d7d52de)
