### ISSUE TITLE
Principles of Management:  Sustainability and Responsible Management

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2988]
`<note class="sustainability-responsible">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with option 2 icon https://drive.google.com/file/d/1-p4uIGpJCz3-DmEiBKU5ukAheA48Owk_/view?usp=sharing be sure to test with <title> in the note

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-11-23 13-16-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3ac1bd55-c6be-4127-b090-c770b56a8bb1)
![Screenshot from 2020-11-23 13-18-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fe5bd9f2-e17a-413b-a163-c27ca08f9d6a)
