### ISSUE TITLE
Principles of Management: Managerial Leadership

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2989]
`<note class="managerial-leadership">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with option 2 icon https://drive.google.com/file/d/1WZm0hAvgzLkuqNjOqDYEQkIlgNDd8HtK/view?usp=sharing be sure to test with <title> in the note

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2020-11-23 13-19-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a824e060-1a8c-4135-8d00-45395f13ce54)
