### ISSUE TITLE
Principles of Management: Ethics in Practice

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2990]
`<note class="ethics-in-practice">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with option 2 icon https://drive.google.com/file/d/1znnLBlJViwAmAMNM1D8rGynnTSsZnu5K/view?usp=sharing be sure to test with <title> in the note

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-11-23 13-51-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/88163eed-d74e-48f6-ae1a-4d2636ff7af4)
