### ISSUE TITLE
Principles of Management: Managing Change

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2991]
`<note class="managing-change"> `- uses https://github.com/openstax/cnx-recipes/issues/2737 with option 2 icon https://drive.google.com/file/d/1a0vuzLNzFziOquwJM6qoUJMlWxfSXgsL/view?usp=sharing be sure to test with <title> in the note

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-11-23 13-47-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d32bb1fe-5824-419a-8c84-f76d09e3de8b)
