### ISSUE TITLE
Principles of Management: Catching the Entrepreneurial Spirit

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2992]
`<note class="catching-spirit">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with option 2 icon https://drive.google.com/file/d/1JELPOVCO7AimoAHHh8JES333XVY9eO3I/view?usp=sharing be sure to test with <title> in the note

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-11-23 13-42-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8332388c-2e55-433d-9905-9c6f704b6842)
