### ISSUE TITLE
Principles of Management: Key Terms

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2993]
Should follow https://github.com/openstax/cnx-recipes/issues/2742

`<section class="key-terms">`

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-02 11-34-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/924b6538-d35d-4aea-9f9c-2a7411374964)
