### ISSUE TITLE
Principles of Management: Summary of Learning Outcomes 

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2994]
Should follow https://github.com/openstax/cnx-recipes/issues/2782 

`<section class="section-summary">`

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-02 15-51-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/70a784fa-0378-4eda-bb2b-2da4d6be9d4c)
