### ISSUE TITLE
Principles of Management: Management Skills Application Exercises

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2995]
Should follow https://github.com/openstax/cnx-recipes/issues/2884 but with this icon https://drive.google.com/file/d/169_IQ6DAi8qsAGZv152QHVtSerJIp1z_/view?usp=sharing

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/100097683-2e62df80-2e5d-11eb-9fd0-87f5d7bcfb49.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-02 16-11-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/442f5b86-d4e1-46a0-8268-923e778f408d)
