### ISSUE TITLE
Principles of Management: Managerial Decision Exercises

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2996]
`<section class="manage-exercises">` - same as https://github.com/openstax/cnx-recipes/issues/2884 but with this icon https://drive.google.com/file/d/1HmkBOwnzFJX3dktyuzvCNYRSoVo8KSsY/view?usp=sharing

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/100097782-52bebc00-2e5d-11eb-8ec2-ea0e550ee234.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-02 16-14-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9e39fb52-4e43-455c-babd-8c23fc1efe10)
