### ISSUE TITLE
Principles of Management: Critical Thinking Case

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2997]
`<section class="critical-thinking">` - same as https://github.com/openstax/cnx-recipes/issues/2789 from Intro to Business

**Comment by MartaSztuka** [comment]
Hi! @brittany-johnson There are links that doesn't work as well. This will be fixed in content, should I close the issue then? ![Screenshot from 2020-12-02 15-27-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8c9ebf05-0ec4-4dd3-903c-d7c28b3a6b90)

**Comment by lwtchu** [comment]
@MartaSztuka this is expected - this link isn't encoded as a link. feel free to close if the feature looks good to you
