### ISSUE TITLE
Principles of Management:  References

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2998]
Should follow: #2800

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/99530553-c1a19e00-29a1-11eb-9219-746c55ad39d8.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-11-23 14-04-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0d7d3b0b-1df8-4d95-b92f-fbf2eefe0fbd)
