### ISSUE TITLE
Principles of Management: Index

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2999]
Should follow https://github.com/openstax/cnx-recipes/issues/2746

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/99530493-a767c000-29a1-11eb-8e73-626a4a8a6a39.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-11-23 13-57-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c408b356-194e-4f46-b5a3-cbe2bfd0ed9a)
