### ISSUE TITLE
College Success: Table of Contents

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3000]
Should follow https://github.com/openstax/cnx-recipes/issues/1740 

uses the blue version

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-09 16-23-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/585a4466-f17c-460c-b770-068566c325fe)
