### ISSUE TITLE
College Success: Figure caption/title/number styling 

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3002]
Should follow https://github.com/openstax/cnx-recipes/issues/2643

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-08 15-10-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/87f3a566-e9e0-4a48-ba62-133fef3d7f78)
