### ISSUE TITLE
College Success: Headers

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3003]
Should follow: https://github.com/openstax/cnx-recipes/issues/2644

**Comment by MartaSztuka** [comment]
#### PASSED
##### Preface![Screenshot from 2020-12-08 15-13-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/53f8ecb1-b34b-47ba-b3de-fac374a0f12d)
##### Appendix![Screenshot from 2020-12-08 15-14-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c8a33a32-7124-4a92-b81f-6561a17d5c96)
