### ISSUE TITLE
College Success: Appendices

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3004]
Should follow header schema in https://github.com/openstax/cnx-recipes/issues/2644

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-08 15-12-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b50bd80d-aae2-4244-86d6-2df1b9e5abc2)
