### ISSUE TITLE
College Success:  Introduction

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3005]
Should follow https://github.com/openstax/cnx-recipes/issues/2655 

exception NO CHAPTER OUTLINE

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-09 15-25-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3a714e38-e0c4-4a08-a52a-85af0d3070ac)
