### ISSUE TITLE
College Success: Section Numbers

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3006]
should follow https://github.com/openstax/cnx-recipes/issues/2710

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-08 15-11-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a7d7f9d2-e524-4faf-b7c8-59d91abd0d48)
