### ISSUE TITLE
College Success: Learning Outcomes

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3007]
should follow https://github.com/openstax/cnx-recipes/issues/2711 Called "Learning Outcomes"

**Comment by wilkus27** [comment]
@brittweinstein There is no Learning Outcomes in College Success.

There is only **Questions to consider** at the beggining of each section but it doesn't have any class.

![image](https://user-images.githubusercontent.com/40228854/101167143-c325c400-3639-11eb-95de-a1d279119c05.png)

Here is exact markup:

![image](https://user-images.githubusercontent.com/40228854/101167286-f8321680-3639-11eb-9528-d6b062ee7df1.png)

**Comment by lwtchu** [comment]
@wilkus27 my mistake i don't think there's LOs in this book. let me close this out and remove it from the epic list
