### ISSUE TITLE
College Success: Tables

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3008]
Should follow https://github.com/openstax/cnx-recipes/issues/2741 

(mostly default style, `top-titled`) ** utilizes a lot of content driven alignment for text

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-18 10-52-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f96f6dc1-135f-4bb5-9da3-55562a04d6ca)
