### ISSUE TITLE
College Success: Blockquotes

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3010]
Should follow https://github.com/openstax/cnx-recipes/issues/2749

**Comment by ajluk** [comment]
@lwtchu In College Success all the blockquotes are bolded in the content: 
![image](https://user-images.githubusercontent.com/55203598/101355521-f5802d00-3896-11eb-888c-7c4cdcfe9f81.png)
Is it intentional or rather a content issue?

**Comment by lwtchu** [comment]
@ajluk that is in the content and intended. i'm noticing the quotes aren't doubled..so i can make a card for the content fix for #3044

**Comment by ajluk** [comment]
@lwtchu I have seen your message on #3044 (https://github.com/openstax/cnx-recipes/issues/2741#issuecomment-740063701). If there will be some additional changes needed after content fix for Business Ethics blockquotes, please let me know.

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-08 14-53-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/91ba2c5d-def6-4585-bc90-63b5edc1a345)
