### ISSUE TITLE
College Success: Student Profile

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3011]
`<note class="student-profile">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with option 4

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/101360089-78a48180-389d-11eb-869c-d58bf32bf92f.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2020-12-09 13-18-05](https://user-images.githubusercontent.com/47241114/101629050-08266d80-3a21-11eb-9193-273c284721d7.png)
