### ISSUE TITLE
College Success: Application

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3012]
`<note class="application"> `- uses https://github.com/openstax/cnx-recipes/issues/2737 with option 5 icon https://drive.google.com/file/d/1QkZHu0sGGcZWc5FY6cfmPa-b79X0e2Mz/view?usp=sharing

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/101363806-1ac66880-38a2-11eb-86de-2b38e89a068b.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-08 14-58-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bf9e6653-4b3b-47f0-ac6c-6b43874bb404)
