### ISSUE TITLE
College Success: Activity

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3013]
`<note class="activity">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with option 3 icon https://drive.google.com/file/d/1rqjZpGr5BPLtvWpBKaufULvzmXl7vEpa/view?usp=sharing

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-08 14-50-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/babc8faa-e7ad-43ac-a910-db1e9316e9a6)
