### ISSUE TITLE
College Success: Analysis

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3014]
`<note class="analysis-question">` - uses https://github.com/openstax/cnx-recipes/issues/2737 with option 2 icon https://drive.google.com/file/d/1znnLBlJViwAmAMNM1D8rGynnTSsZnu5K/view?usp=sharing

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/101477565-aea23e00-394f-11eb-8cf0-d07cf7db8e24.png)

**Comment by MartaSztuka** [comment]
##### Title is unstyled, should be thin and navy blue. ![Screenshot from 2020-12-09 15-18-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/41ae5e1b-5352-48d3-a420-3bc6e648d785)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-11 15-24-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2c1bdfda-67de-439d-b74f-2fa34fb148c1)
