### ISSUE TITLE
College Success: What Students Say

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3015]
`<note class="what-students-say">` - uses https://github.com/openstax/cnx-recipes/issues/2737 option 3 icon https://drive.google.com/file/d/1g-BiNNtEMH6UKgetLBy7FrCKVLa8zBu5/view?usp=sharing

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/101487525-a0a7e980-395e-11eb-9ef8-932a31834696.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-10 10-11-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2a9c685a-1d92-4daf-a8d3-01940328e275)
