### ISSUE TITLE
College Success: Get Connected

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3016]
`<note class="get-connected"> `- uses https://github.com/openstax/cnx-recipes/issues/2737 option 2 icon https://drive.google.com/file/d/16SoDMSGKfmCz4aed86kgMF3v4dtWkTq6/view?usp=sharing

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-10 10-13-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/144639e2-d848-4b4d-81cc-583785eea608)
