### ISSUE TITLE
Astronomy: Table of Contents

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3018]
Should follow https://github.com/openstax/cnx-recipes/issues/1740

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-16 17-37-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0e32beae-e301-44d5-ae1c-b6c6902a7c23)![Screenshot from 2020-12-16 17-38-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8d6e8709-8e15-4e91-bc0e-43643cc7a033)
