### ISSUE TITLE
Astronomy: Splash Images

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3019]
should follow https://github.com/openstax/cnx-recipes/issues/2642

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-04 11-08-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1c662ae7-be4d-44ff-a5bb-7e9331a740fb)
