### ISSUE TITLE
Astronomy: Figure caption/title/number styling

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3020]
should follow https://github.com/openstax/cnx-recipes/issues/2643

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-18 15-36-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3cd75d89-545a-4c77-b0f1-42219e12c092)
