### ISSUE TITLE
Astronomy: Headers

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3021]
Should follow https://github.com/openstax/cnx-recipes/issues/2644

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-18 15-28-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5c64c753-fc3b-404c-bfd0-7dbeeea2b61e)![Screenshot from 2020-12-18 15-27-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/97bc5411-3d04-4a53-ab05-fd1550eea1d0)
