### ISSUE TITLE
Astronomy: Appendices

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3022]
Should follow schema in https://github.com/openstax/cnx-recipes/issues/2644

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-18 15-34-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1ab94a02-18ef-48a3-ad28-5041ad9d5482)
