### ISSUE TITLE
Astronomy: Section Numbers

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3023]
Should follow https://github.com/openstax/cnx-recipes/issues/2710

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-18 15-31-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ae288411-8e86-4628-83bf-4a0cb4122c25)
