### ISSUE TITLE
Astronomy: Chapter Outline/ Introduction

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3024]
Should follow https://github.com/openstax/cnx-recipes/issues/2655

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-04 11-07-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2a15d074-2e3f-4534-99ce-3cd37512af6d)
