### ISSUE TITLE
Astronomy: Learning Objectives

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3025]
Should follow https://github.com/openstax/cnx-recipes/issues/2711

**Comment by kswanson33** [comment]
specs: #2711
changes applied to: learning objectives in astronomy
PR: #3179
astronomy is on katalyst01 with col11992

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-22 10-19-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e9c1ee79-0f7f-456a-a7c7-9e6c7b96a825)
