### ISSUE TITLE
Astronomy: Tables

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3026]
Should follow https://github.com/openstax/cnx-recipes/issues/2741 (scroll to Alternate color schema for table 1 (default table))
Edit: both default and regularr tables should have the alternate color schema. Based on Larissa's comment here: https://github.com/openstax/cnx-recipes/issues/2741#issuecomment-746848895

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/102520241-c5553d00-4093-11eb-8ac6-19b0d667fa49.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-04 11-05-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1c0cbabe-d60f-4f17-8995-f9e05de391ab)
