### ISSUE TITLE
Astronomy: Footnotes

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3027]
Should follow https://github.com/openstax/cnx-recipes/issues/2773

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-18 15-32-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1d136d96-8668-4111-aa94-d98bfd2ddecd)
