### ISSUE TITLE
Astronomy: Voyagers in Astronomy 

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3029]
`class="voygers-in-astronomy" `

https://github.com/openstax/cnx-recipes/issues/2737 (remember instead of Roboto Condensed, use Dosis and for the <title> it is Noto Sans) option 7 icon: https://drive.google.com/file/d/1ENO95sIXKiQxCJOrcQ7qVkB6GM4uxjVK/view?usp=sharing

**Comment by kswanson33** [comment]
Question on #2737

**Comment by kswanson33** [comment]
specs: #2737
changes applied to: astronomy voyagers note
PR: #3203
astronomy is on katalyst01 with col11992

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-22 10-17-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bfd19442-4458-4030-891e-1737394a4e56)
