### ISSUE TITLE
Astronomy: Seeing for Yourself 

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3030]
`class="seeing-for-yourself"` https://github.com/openstax/cnx-recipes/issues/2737 option 8 - icon: https://drive.google.com/file/d/1g1Gs6OQc5jENBQ27vjVT4ypYZ58pAgga/view?usp=sharing

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-07 11-09-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7392b360-0949-4247-b293-5d1bdfb3751e)
