### ISSUE TITLE
Astronomy: Link to Learning

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3031]
`class="link-to-learning"` https://github.com/openstax/cnx-recipes/issues/2737 option 6 - icon: https://drive.google.com/file/d/1rXFrx3lvj7N7KKVws33Zfxb1Px6VnG7c/view?usp=sharing

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/103358060-03e7f000-4ab5-11eb-98d7-c4c9fb99a24b.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-08 10-14-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7dbe48b7-56f8-4a01-bf51-e62b3712a41d)
