### ISSUE TITLE
Astronomy: Making Connections

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3032]
` class="making-connections" ` https://github.com/openstax/cnx-recipes/issues/2737 option 8 - icon: https://drive.google.com/file/d/1ChVwfGfKpC1Ss3XBlHhZnmVTnn9YGvJO/view?usp=sharing

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/103413397-a36eb680-4b79-11eb-8b40-1ce8f2eb9edf.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-08 10-12-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/948efbd5-0aac-491b-9a54-c7cab785e5a2)
