### ISSUE TITLE
Astronomy: Astronomy Basics

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3033]
`class="astronomy-basics` https://github.com/openstax/cnx-recipes/issues/2737 option 7 icon: https://drive.google.com/file/d/1bsxA2pLP1wC0HiO5Q1KCOv_NLO3ShSOA/view?usp=sharing

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/103416826-93aa9e80-4b88-11eb-94eb-c00ec80f0c55.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-08 10-00-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f6623db2-27dc-459c-80ff-0163770dd294)
