### ISSUE TITLE
Astronomy: Key Terms

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3034]
(uses `<glossary>`) - https://github.com/openstax/cnx-recipes/issues/2742 please use the same specs here but use Dosis header - P1: #3B2746 with this icon: https://drive.google.com/file/d/1hG9R4OQZFAU2QPyWY3zY1bcDMx7JO2AH/view?usp=sharing - screenshot is in the issue for reference

**Comment by kswanson33** [comment]
specs: #2742 & this card
changes applied to: astronomy EOC key terms
PR: #3205
astronomy is on katalyst01 with col11992

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2020-12-22 17-44-28](https://user-images.githubusercontent.com/47241114/102912209-691c5f80-447d-11eb-9052-4675b64fa0e0.png)
