### ISSUE TITLE
Astronomy: Summary

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3035]
`class="summary"` - https://github.com/openstax/cnx-recipes/issues/2743 please use the same specs here but use Dosis header P1: #3B2746 with this icon: https://drive.google.com/file/d/1JhzN_Zb3BhK1mqHb1NVeh4aiOkm5yyfz/view?usp=sharing

**Comment by kswanson33** [comment]
Question on #2743

**Comment by kswanson33** [comment]
specs: #2743 & this card
changes applied to: astronomy EOC summary
PR: #3204
astronomy is on katalyst01 with col11992

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-22 10-20-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ece2442c-cf0d-4e7b-ac27-4cb321cd4ceb)
