### ISSUE TITLE
intro to business - list titles

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3039]
![Screen Shot 2020-11-09 at 6 23 47 PM](https://user-images.githubusercontent.com/11299125/98611983-c33fd780-22b8-11eb-83e6-809266b3f15c.png)

"Critical Thinking Case" here is a `<title>` within a `<list>`

- keep the font the same as the base font (color, style, size)
- treatment: bold

**Comment by ajluk** [comment]
This issue will be also addressed within this PR: https://github.com/openstax/cnx-recipes/pull/2932

**Comment by ajluk** [comment]
@MartaSztuka Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/98696573-41ad7f80-2374-11eb-8add-a4104017a55f.png) This list can be also found in other parts of the book (not only EOC).

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-11-23 14-16-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/42a86d27-3843-4fc5-83e7-ce8a6b4ec2be)![Screenshot from 2020-11-23 14-14-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a15ada35-bba7-4d1d-9690-0440ae233319)
