### ISSUE TITLE
Introduction to Business: Style Index Appendices

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3040]
Issue with documentation: #2746

**Comment by MartaSztuka** [comment]
Hi, @lwtchu are we sure about Symbols at the top of Index? 
![Screenshot from 2020-11-13 15-54-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6e446140-68e7-4bca-a19a-4d11cfda4a03)

**Comment by lwtchu** [comment]
@MartaSztuka the symbols at the top is fien and is standard. i think the Act is just confusing since it's supposed to go with the text above it... hmmmm 

@ajluk how difficult would it be to make a small indention for the second line of each term?

**Comment by ajluk** [comment]
@lwtchu It shouldn't be difficult if you mean something like this (it's html file so the links are whole here): 
![image](https://user-images.githubusercontent.com/55203598/99103464-e384d480-25df-11eb-82d6-42809058970d.png)
but what I'm afraid here is that it will affect items with a lot of page number links, so they will be indented as well then in such places:
![image](https://user-images.githubusercontent.com/55203598/99103586-1b8c1780-25e0-11eb-9d09-48b4a65c637b.png)

**Comment by lwtchu** [comment]
@ajluk hmm let's leave as is for now. if we have a lot of issues from people, we can reevaluate.
