### ISSUE TITLE
Business Ethics : Large page break

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#3042]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know

![Screen Shot 2020-11-11 at 12.31.25 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/2ec13fbb-db1a-4e28-9707-dd5421cfeb93)

# Acceptance Criteria

# Bug Location(s)
collection ID: col25722
server: COPS production
chapter/section: 1.3
surrounding text: 1.3 Multiple versus Single Ethical Standards
PDF link: https://openstax-cops-artifacts.s3.amazonaws.com/col25722-latest-production-519.pdf

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
... a bunch of content is missing on production one second.

**Comment by lwtchu** [comment]
just kidding, the entire section was placed in an all encompassing LO section... the content fix i made should fix this. will regenerate on cops to verify.

**Comment by lwtchu** [comment]
![Screen Shot 2020-11-16 at 10 59 02 AM](https://user-images.githubusercontent.com/11299125/99283534-c1b36980-27fa-11eb-92d9-c5b927e0517e.png)
