### ISSUE TITLE
Business Ethics - Summary and key terms are switched in order

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#3043]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know

![Screen Shot 2020-11-11 at 12.47.28 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/9061ff7a-24f5-499d-9541-78ad8cdc85e2)

# Acceptance Criteria

# Bug Location(s)
collection ID: col25722
server: COPS production
chapter/section: 1 EOC
surrounding text: 1.Summary
PDF link: https://openstax-cops-artifacts.s3.amazonaws.com/col25722-latest-production-519.pdf 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by meeragovindaraju** [comment]
@lwtchu This is the case for all the chapters.

**Comment by lwtchu** [comment]
@brittany-johnson i can't remember if this was due to a limitation to oer.exports or recipe...would you happen to know if the order is vital for recipes

**Comment by brittweinstein** [comment]
@Stackblocks would you be able to look into this one?

**Comment by Stackblocks** [comment]
I'll take a look to see if this is something that I know how to tackle 👍

**Comment by lwtchu** [comment]
@Stackblocks i think this is already happening in the recipe so it's not...a huge deal but it doesn't match the PDF 😬  i vaguely recall it being a recipe or a oer.export limitation but i cannot remember which one.

**Comment by Stackblocks** [comment]
We resolved the oer.export limitation but did not create an equivalent for cnx-recipes iirc.

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/102233547-055ec900-3eb6-11eb-9b50-95c56e7f53da.png)

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-01-12 10-24-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cfa1091a-5402-4bc3-967d-b5c30706336e)
