### ISSUE TITLE
Business Ethics extra set of quotes and look different than in the old PDF

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#3044]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know

COPS PDF

![Screen Shot 2020-11-11 at 1.28.35 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/406f3f55-a2f4-4adf-a4e8-c0ac599c910e)

Old PDF on Openstax.org

![Screen Shot 2020-11-11 at 1.34.11 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/d773b23f-596b-4a25-b6d9-5ea0244e6525)
# Acceptance Criteria

# Bug Location(s)
collection ID: col25722
server: COPS production
chapter/section: 4.2
surrounding text: Environmental Justice section and just before LINK TO LEARNING
PDF link: https://openstax-cops-artifacts.s3.amazonaws.com/col25722-latest-production-519.pdf

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by meeragovindaraju** [comment]
Section 5.4

COPS PDF

![Screen Shot 2020-11-11 at 1 55 26 PM](https://user-images.githubusercontent.com/33066187/98858114-b4c2fe80-2425-11eb-8416-16c960c1d11d.png)


PDF from openstax.org

![Screen Shot 2020-11-11 at 1 55 38 PM](https://user-images.githubusercontent.com/33066187/98858143-be4c6680-2425-11eb-9bc8-5b3409953522.png)

**Comment by meeragovindaraju** [comment]
Section 7.5

COPS pdf

![Screen Shot 2020-11-11 at 2 07 01 PM](https://user-images.githubusercontent.com/33066187/98859078-3cf5d380-2427-11eb-8324-c021803ae0b4.png)


PDf from openstax.org

![Screen Shot 2020-11-11 at 2 07 48 PM](https://user-images.githubusercontent.com/33066187/98859129-4d0db300-2427-11eb-9013-017be1c0d6ff.png)

**Comment by meeragovindaraju** [comment]
Section 11.1

COPS PDF

![Screen Shot 2020-11-11 at 2 19 50 PM](https://user-images.githubusercontent.com/33066187/98860277-05882680-2429-11eb-8ff5-f69213057265.png)


PDF from openstax.org

![Screen Shot 2020-11-11 at 2 20 42 PM](https://user-images.githubusercontent.com/33066187/98860324-19cc2380-2429-11eb-86e2-3ee59cc0bfa6.png)

**Comment by meeragovindaraju** [comment]
Section 11.1

COPS PDF

![Screen Shot 2020-11-11 at 2 21 29 PM](https://user-images.githubusercontent.com/33066187/98860517-6d3e7180-2429-11eb-87a7-20b9728e5771.png)


PDF from openstax.org

![Screen Shot 2020-11-11 at 2 21 45 PM](https://user-images.githubusercontent.com/33066187/98860548-7a5b6080-2429-11eb-81e1-d73a080154c0.png)

**Comment by meeragovindaraju** [comment]
Section 11.3

COPS PDF

![Screen Shot 2020-11-11 at 2 25 01 PM](https://user-images.githubusercontent.com/33066187/98860738-bdb5cf00-2429-11eb-875a-a4e2274e4ab9.png)


PDF from openstax.org

![Screen Shot 2020-11-11 at 2 25 09 PM](https://user-images.githubusercontent.com/33066187/98860771-c6a6a080-2429-11eb-960a-192619d65a18.png)

**Comment by lwtchu** [comment]
1. can we remove the extra quotes surrounding the blockquote? the quotes should come from the content

2. can we also insert line breaks between the `<para>` within the blockquote tags?

**Comment by ajluk** [comment]
@lwtchu These additional quotes are added by the browser and maybe in prince in the pdf (I couldn't find it in the documentation): 
![image](https://user-images.githubusercontent.com/55203598/99972492-dcf41b00-2d9e-11eb-9915-b9b4deb48326.png)
This problem also take place on webview: 
![image](https://user-images.githubusercontent.com/55203598/99974158-d797d000-2da0-11eb-80ea-b6fbf20f8652.png)
In this case there two options:

**Comment by brittweinstein** [comment]
@ajluk please put points on this when you can

**Comment by lwtchu** [comment]
@ajluk interesting! thank you for the thorough investigation. I'll move this to the next milestone so I can take a look at the content when I'm back from vacation.

**Comment by lwtchu** [comment]
@ajluk i think the quotes are marked up correctly in _College Succes_. When this feature gets implemented in _College Success_ do you mind pinging me? If I can verify that it works in _College Success_ with no issue I can open a card for content changes.

**Comment by lwtchu** [comment]
Going to move this over to the content team for the content fix.
