### ISSUE TITLE
Business Ethics - EOC Endnotes numbered list not inline as it is in the old PDF

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#3045]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know

COPS PDF

![Screen Shot 2020-11-11 at 1.44.23 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/32ed493a-9cbd-4bf5-8588-273c1cb6822a)

PDF on openstax.org

![Screen Shot 2020-11-11 at 1.49.42 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/8f94dceb-f725-4b0f-843e-da5d1fc9750b)

# Acceptance Criteria

# Bug Location(s)
collection ID: col25722
server: COPS production
chapter/section: EOC all chapters
surrounding text: EOC Endnotes
PDF link: https://openstax-cops-artifacts.s3.amazonaws.com/col25722-latest-production-519.pdf

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
lowish prio, but can we have the second line line up with the start of the first line

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/101772126-3ec8ba80-3aeb-11eb-8c44-16f09996cee1.png)

**Comment by lwtchu** [comment]
@ajluk looks good thank you

**Comment by ajluk** [comment]
@lwtchu I have added some specs while styling it: 
**EndnoteNoteSection** (whole section with class .references)
 margin: 0,
**EndnoteNote** ([data-type="note"])
padding: '0 0 0 2.2rem',
**EndnoteLink** (a)
        position: relative,
        left: -0.8rem,
        width: 0,
        display: inline-block,
       property removed in this component: margin-right: h-spacing(1),

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-15 13-49-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b3ca0984-9eca-401d-adf5-90e568d71d79)
