### ISSUE TITLE
Business Ethics - Chapter 11 listed EOB Answer key

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#3046]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know

Chapter 11 listed in the answer key although no EOC questions present.

![Screen Shot 2020-11-11 at 2.29.05 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/b44969ed-a021-4f1f-b388-f4cba7127bf8)

# Acceptance Criteria

# Bug Location(s)
collection ID: col25722
server: COPS production
chapter/section: Answer key
surrounding text: Answer key
PDF link: https://openstax-cops-artifacts.s3.amazonaws.com/col25722-latest-production-519.pdf

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
there are no answers in chapter 11 but is is possible to suppress something if there's nothing in it?

**Comment by ajluk** [comment]
After a discussion there was a decision that we will be working on this issue in KITCHEN.

**Comment by wilkus27** [comment]
Checked with the current version of content and kitchen. Problem still appears:

![image](https://user-images.githubusercontent.com/40228854/150560751-7873c72a-3a14-4498-ac31-3682ee00d9f9.png)

**Comment by wilkus27** [comment]
### Information for tester

Changes are merged to main, not released yet.
