### ISSUE TITLE
Business Ethics - Some more space needed between Chapter outline and the first numbered bullet

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#3047]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know

![Screen Shot 2020-11-11 at 4.12.32 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/e9283934-7c9b-4381-aa1a-b27c05e5e506)

# Acceptance Criteria

# Bug Location(s)
collection ID: col25722
server: COPS production
chapter/section: Chapter outline
surrounding text: Chapter outline
PDF link: https://openstax-cops-artifacts.s3.amazonaws.com/col25722-latest-production-519.pdf

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
can we add a 1 vgrid padding to this? putting it in this sprint because it might impact more chapter outlines in the theme

**Comment by ajluk** [comment]
@lwtchu I have fixed the margin shorthand property which is currently set to `margin: 0 0 0.5 0 `remfor Chapter Outline title property and now it looks like this: 
![image](https://user-images.githubusercontent.com/55203598/99818640-c22b6780-2b4e-11eb-8dbc-9e726a7d325c.png)
Is that space amount enough under the title now?

**Comment by lwtchu** [comment]
@ajluk thank you anna this looks good.

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-02 17-00-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/498bf8a4-a84c-4cce-89e8-37b66ebc89c0)
