### ISSUE TITLE
HS Statistics, Appendix D - Confirm Display Issues Do Not Occur with Baked Styles

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#3054]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know [x] oer.exports only (I hope)

We received two errata reports (12770 and 12766) letting us know there are some display issues in appendix D for HS Statistics. The character Â is being added in random places. This is **not** occurring on the [web version](https://openstax.org/books/introductory-statistics/pages/d-group-and-partner-projects). This PDF was generated in oer.exports so I hope the issue is limited to oer.exports.

@meeragovindaraju, would you be able to generate a new HS Stats PDF on COPS and compare Appendix D with the [web version](https://openstax.org/books/introductory-statistics/pages/d-group-and-partner-projects)? Please note any differences/possible bugs.

# Acceptance Criteria
- [ ] new HS Stats PDG, generated on COPS, has been compared to [web version](https://openstax.org/books/introductory-statistics/pages/d-group-and-partner-projects) of the book
- [ ] any display differences are noted with screenshots/explanation below

# Bug Location(s)
PDF hosted on openstax.org
chapter/section: Appendix D
surrounding text: see screenshot; multiple locations throughout module and possibly others

# Test Content Location(s)
(leave blank if the same as above)
collection ID: HS Stats collection on cnx.org - can get version from Approved Books List 
chapter/section: Appendix D
surrounding text: see screenshot; multiple locations throughout module and possibly others

**Comment by openstaxalina** [comment]
![StatsAppendixIssue](https://user-images.githubusercontent.com/7863733/98969664-b13a8080-24d4-11eb-8bd1-cbb11f8aefab.png)

**Comment by meeragovindaraju** [comment]
The character Â is seen in Appendix D. I do **not** see this anywhere else in the book.  

![Screen Shot 2020-11-13 at 10 00 34 AM](https://user-images.githubusercontent.com/33066187/99092729-23739980-2597-11eb-9728-7a5c822602a0.png)

**Comment by openstaxalina** [comment]
Thank you @meeragovindaraju! It looks like this is a **content** issue. Marc is fixing this as part of https://github.com/openstax/content-managers/issues/2000. 

I will close this card. Thank you very much for the investigation!
