### ISSUE TITLE
due 1/19: computer science - testing color math and `<code>`

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3055]
Test content: https://legacy-content04.cnx.org/content/m10015/latest/?collection=col10004/latest

Can we test the following:

- [x] can we style `<code>` with a different monotype font? 
- [x] can we style the math with a monotype font? - what is available on our current math pipeline and I can pick one.
- [x] i added a `class` on the inline `<code>` to test colors. please use whatever color you choose for now. is it possible to target code with a class to change color?
- [x] does `<m:mathstyle color="_____">` work? 
- [x] is there a way to implement standard code formatting?? if things are in `<code>` - this is a far fetched thing but just asking
~- [ ] can we page break across math?~

Anyway - I'd like to check back sometime next week to see progress. I'd like to have answers for these questions by 11/24 at the latest. Ping me if you have questions.

I just want to know if these things are possible. I do not need this to go to production or anything else.

**Comment by brittany-johnson** [comment]
- By default, the `code` tag's font family is `monospace` - we can change it to any monotype font (or any font). The tag is not processed during mathifying so we can use any font that we would use to style other text with CSS 
![Screen Shot 2020-11-18 at 11 21 28 PM](https://user-images.githubusercontent.com/24909007/99625038-f12dc600-29f4-11eb-8ad1-290f57ec5503.png)

- We’re currently using mathjax version2.7.8 . [This is a list of all of the fonts available to us.](https://docs.mathjax.org/en/v2.7-latest/font-support.html) From this list, only these fonts have a mono type: 
  - STIX General
  - Latin Mordern 

- We can change the colors of inline code by targeting the selector *insert rainbow* 
![Screen Shot 2020-11-18 at 11 38 24 PM](https://user-images.githubusercontent.com/24909007/99626225-5c789780-29f7-11eb-90cf-817280f16f07.png)

**Comment by lwtchu** [comment]
@brittany-johnson do you mind sending me a pdf of this i can't believe it

**Comment by lwtchu** [comment]
<img width="887" alt="Screen Shot 2020-11-19 at 11 10 59 PM" src="https://user-images.githubusercontent.com/11299125/99815237-a785ce00-2b0f-11eb-88e2-aef3397b928f.png">
[collection.with-math (2).pdf](https://github.com/openstax/cnx-recipes/files/5574313/collection.with-math.2.pdf)

**Comment by brittany-johnson** [comment]
Final update before holidays: 

I believe we should be able to use [highlight.js](https://highlightjs.org/) to standardize code snippets in the book during PDF generation. I ran into some issues that I need more time to resolve. 

- [PrinceXML does not currently support ES6](https://www.princexml.com/doc/javascript/#javascript-in-prince) BUT it is on their [roadmap which was updated November 2020](https://www.princexml.com/roadmap/)
- highlight JS is written w/ a lot of es6 features and syntax. During my testing I was able to use Babel to convert most of it to es5 but there are still a lot things Prince is complaining about during generation. I was able to resolve a lot of these using polyfills, but only got about 1/3 of the way through the 4K line JS file
- When I get back from vacation I'm going to schedule a meeting with Phil to get his advice before I spend more time working through these errors. I don't want to go to far if this package won't work well with the rest of the pipeline for example.

**Comment by brittweinstein** [comment]
@brittany-johnson please put points on this

**Comment by lwtchu** [comment]
![Screen Shot 2020-11-23 at 12 20 05 PM](https://user-images.githubusercontent.com/11299125/99999756-3e5bc000-2d86-11eb-93ac-b9c9e70ef5bb.png)
ignore the highlight. but this part i didn't put any spacing and it's just... the code tag. i'm wondering if you had anything to do with the way it formatted @brittany-johnson?

**Comment by lwtchu** [comment]
notes from meeting with @philschatz : 
do code formatting earlier in the process - right after baking or right before. 
phil says it's possible to do code formatting. 
exploration can be done quicker with CE tech folks. - this could be a good way to get kendra and mary jo in more experience. 

cc @LostMojo @kswanson33 i'll discuss this with yall in a bit

**Comment by brittany-johnson** [comment]
Update + decisions: 

- We're using `highlight.js` to parse `pre` tag elements in content during the mathify step 
  - [CNXML `code` tags are converted to `pre` tags ](https://legacy.cnx.org/eip-help/code)
- Content nested in a `pre` element with the `lang` class is parsed and classes are added by `highlight.js` depending on the` lang` class on the element
  - This means that it is a content requirement that all `code`/`pre` elements have a valid `lang` class attribute
  - [A list of valid classes to be used can be found here under the `Classes` column](https://github.com/highlightjs/highlight.js/blob/master/SUPPORTED_LANGUAGES.md)
  
Here is an example of the markup before and after highlight.js is ran: 

Before (baked)
```
<pre lang="python" id="auto_050e28d3-5319-4e8f-a6b8-169865b2ba26_eip-971" data-display="block">
  my_integer = 5
  my_floating_point = 26.2
  my_Boolean = True
  my_string = 'characters'
</pre>
```

After (highlight)
```
<pre lang="python" id="auto_050e28d3-5319-4e8f-a6b8-169865b2ba26_eip-971" data-display="block">
my_integer = <span class="hljs-number">5</span>
my_floating_point = <span class="hljs-number">26.2</span>
my_Boolean = <span class="hljs-literal">True</span>
my_string = <span class="hljs-string">'characters'</span>
</pre>
```

- The actual styling of the code snippets (ie. color, font size, font family) will be added via the stylesheet with the rest of the PDF styles.
  - [highlight.js has a collection of themes that we can borrow from](https://highlightjs.org/static/demo/) The final style should be decided and implemented in a separate issue
  
As I'm writing this comment, I have one more test to write so that the process fails if a valid `lang` class was not added to a `pre`/`code` element. And then it will be done! https://github.com/openstax/mathify/pull/69

If you have any questions before the W.W meeting please let me know! @lwtchu

**Comment by brittany-johnson** [comment]
Also spent over a week on this so I increased the points lol

**Comment by brittany-johnson** [comment]
@lwtchu I think ideally we would want to test this on Corgi but we can't confirm the classes on the PDF, and we're not applying any styling to the code blocks yet via baked styles. So I think we can test this more later once we have test content and styles applied. What do you think?

**Comment by lwtchu** [comment]
@brittany-johnson yes - once we get the test content i think we can test it then? is everything technically implemented? and the html output has the classes on it?
