### ISSUE TITLE
Implement Introduction Page in Principles of Management

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3058]
This issue covers all introduction page issues + learning outcomes:  #2977, #2978, #2980, #2982
Issues with documentation:
Splash image #2642 - uses blue version; city scape icon
Figure caption/title/number styling #2643
Chapter Outline / Introduction #2655
Learning Objectives #2711 - titled "Learning Outcomes"

**Comment by MartaSztuka** [comment]
### PASSED
![Screenshot from 2020-11-23 14-10-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/faf03a16-5b55-4813-a66c-36274511901e)
