### ISSUE TITLE
Excessive disk usage by docker

### ISSUE THREAD

**Issue by aiwenar** [openstax/cnx-recipes#3061]
Reported to me by @MartaSztuka 

Scripts using docker (in Marta's case this appeared to be specifically scripts/fetch-book) leave stale containers. In Marta's case there were maybe 20 or 30 instances of `/bin/bash -c "neb get ...`, which together with their images were taking 15 GB of disk space.

Additionally, when fetching books, they are first downloaded to a docker volume and then copied to destination directory, but are never removed from the volume. In Marta's case that volume was taking another 5 GB of disk space.

I'm not sure whether the first is still an issue as I see that docker-compose is being invoked with `--rm`, but Marta had stale containers from 7 months to a few weeks old and I couldn't find any issue or PR which appeared relevant, so I assume it sill is. I also never used docker-compose so I don't know whether `--rm` is sufficient.

**Comment by brittweinstein** [comment]
Marta is using the prune command to get by in the meantime.

**Comment by m1yag1** [comment]
The prune command was what I was going to suggest to help with this. Is there anything the styles devs are doing specifically?

**Comment by tomjw64** [comment]
A slack thread we had talking about ways to clear out space taken up by docker: https://openstax.slack.com/archives/C0LA54Q5C/p1595433679006500

**Comment by m1yag1** [comment]
`docker system prune -a` seems to also get a lot of mileage.

**Comment by lwtchu** [comment]
closing this since it's a few months old :eyes: reopen if you need it o pen again.
