### ISSUE TITLE
Principles of Management: Blockquotes

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3066]
Should follow: https://github.com/openstax/cnx-recipes/issues/2749

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/99531139-94a1bb00-29a2-11eb-81ce-80e9f418678b.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-11-23 11-49-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c10d3dd5-3927-4f22-bc12-796d158609b6)
