### ISSUE TITLE
Migrate from Travis to Github Actions 

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#3069]
travis-ci.org is closing at the end of December and all repos must transfer over to travis-ci.com which will limit requests made unless on a specific paid plan

We use travis-ci to run tests on all submitted PRs in cnx-recipes, oer.exports, webview, and kitchen. 

This issue will focus on switching only cnx-recipes and oer.exports to Github Actions

**Comment by lwtchu** [comment]
Closing :shrug:
