### ISSUE TITLE
cardboard: list titles

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3080]
Based on: #3039
![Screen Shot 2020-11-09 at 6 23 47 PM](https://user-images.githubusercontent.com/11299125/98611983-c33fd780-22b8-11eb-83e6-809266b3f15c.png)

"Critical Thinking Case" here is a `<title>` within a `<list>`

- keep the font the same as the base font (color, style, size)
- treatment: bold

**Comment by ajluk** [comment]
@lwtchu I have created this documentation card, because I have noticed that in Principles of Management there is also this type of lists present. So I made it theme wide.

**Comment by lwtchu** [comment]
@ajluk ooh okay thank you anna. i think this is a good idea.

**Comment by lwtchu** [comment]
idk why this is open. closign
