### ISSUE TITLE
college physics: toc unstyled

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3082]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [x] i don't know

![Screen Shot 2020-11-23 at 6 42 45 PM](https://user-images.githubusercontent.com/11299125/100031857-47678400-2dbc-11eb-913a-b58af5948029.png)
It's been broken for a while now I checked a PDF on cops from October 14 
Maybe some release made it disappear? We'll probably need to fix this before titles in the carnival theme go to print.

# Acceptance Criteria
Old specs if you need: https://github.com/openstax/cnx-recipes/issues/1070

# Bug Location(s)
collection ID: screenshot is from College Physics col11406; any or all books in carnival theme can be used to test
cops job:532
server: production/cops
chapter/section: TOC
surrounding text: idk it's like right there

# Test Content Location(s)
(leave blank if the same as above)
collection ID: col11406
server:  prod

**Comment by lwtchu** [comment]
We should probably fix this before CMs QA the PDFs for print revisions.

**Comment by ajluk** [comment]
@lwtchu I have investigated the issue and it appeared that only College Physics can have this bug, because the reason ToC isn't styled is that the release flags has been disabled for this book. I couldn't find issue pointing to that change. The only change I have found was in  v1.56.0. I guess it could have been done after the name of the recipe was changed from `physics` to `college physics`. Should I enable back all the flags for College Physics?

**Comment by lwtchu** [comment]
@ajluk i think that should be okay - we should probably regenerate and skim thru the pdf just to make sure nothing else has exploded

**Comment by ajluk** [comment]
@lwtchu Thank you! I will enable the flags back. Should I do it now or in the next milestone (a.a)?

**Comment by lwtchu** [comment]
@ajluk if you have time now, i can't see why it needs to wait. we can move it to this milestone.

**Comment by ajluk** [comment]
@lwtchu Do you want Marta to test all feature flags regarding College Physics within this issue or just the ToC?

**Comment by lwtchu** [comment]
@ajluk @MartaSztuka can you test the TOC and then spot check a few spots (i.e. skimming preface, 1 chapter and EOC) just to make sure everything looks like they are there and nothing looks too terrible

**Comment by ajluk** [comment]
@MartaSztuka I have also enabled one new flag for College Phycis `move-footnotes`. Here is the file with flags descriptions: https://docs.google.com/document/d/1ziR2PcSvioOLAHSRNWZga3m-8DlUM_qaskIjpWtoS60/edit. In case of College Phycisc there is only a need to check if the footnotes are on the corresponding site of the book as footnotes links.

**Comment by MartaSztuka** [comment]
### PASSED
#### Footnotes![Screenshot from 2020-12-17 10-01-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3e4fbec6-ad72-4adc-b76f-6150e75b0a34)

**Comment by MartaSztuka** [comment]
#### PASSED
##### ToC![Screenshot from 2020-12-17 11-39-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9352ff5a-fc1c-44b7-876b-70ca47a267b9)
##### Preface![Screenshot from 2020-12-17 11-40-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6f7cc914-6f94-4367-97a9-cc58fe75599a)
##### Chapter 1![Screenshot from 2020-12-17 11-41-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a8c7a986-1133-44d4-80bd-bfae47694a2d)
##### EoC![Screenshot from 2020-12-17 11-42-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/54afbfc2-bda4-4c7b-a26d-277f06c554af)
