### ISSUE TITLE
entrepreneurship - suggested resources

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3109]
Implement: https://github.com/openstax/cnx-recipes/issues/2886

**Comment by MartaSztuka** [comment]
@brittany-johnson there are missing links (same problem as in #2972).![Screenshot from 2020-12-02 13-23-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ab22a71e-41f5-4ec1-a4f9-20c0da7e4458)

**Comment by lwtchu** [comment]
@MartaSztuka this is expected - if everything else looks good please close the issue
