### ISSUE TITLE
Entrepreneurship Preface

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#3115]
Preface doesn't show in Menu and the header is unstyled.
@brittany-johnson it looks like preface class is missing.
#### html
![Screenshot from 2020-12-03 09-59-14](https://user-images.githubusercontent.com/47241114/100987591-022b1b00-354f-11eb-87b4-d5e0fdfc38d3.png)
#### PDF
![Screenshot from 2020-12-03 10-06-56](https://user-images.githubusercontent.com/47241114/100987959-71a10a80-354f-11eb-8b1a-0a3e79c0c112.png)

**Comment by MartaSztuka** [comment]
Same with Accounting
![Screenshot from 2020-12-03 13-35-31](https://user-images.githubusercontent.com/47241114/101019003-99eb3200-356c-11eb-8842-43d4a7f2571f.png)

**Comment by lwtchu** [comment]
fixed content on katalyst01 and production
