### ISSUE TITLE
College Success: style tables with colwidth/datawidth attribute

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3123]
Implement: https://github.com/openstax/cnx-recipes/issues/2776

**Comment by wilkus27** [comment]
@MartaSztuka before testing this, please fetch new content. There were changes for `col` attributes.

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-18 10-39-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5494067d-f1b6-4e86-a971-5176d76987f9)
