### ISSUE TITLE
Accounting Appendices

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#3128]
It looks like the appendix class is missing in accounting.

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/f243f022-2a2e-470f-8987-ee103b550d7f)

(Should have `class="appendix"` on the selected div.)

According to #3115, the preface is also missing.

**Comment by lwtchu** [comment]
Fixed on katalyst01 and production
