### ISSUE TITLE
Missing LO links in accounting

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#3129]
The class `lo-reference` is not present in accounting. #2889

**Comment by lwtchu** [comment]
Did some investigation. 

Can confirm that it exists in the CNXML. 
<img width="967" alt="Screen Shot 2020-12-09 at 12 28 23 PM" src="https://user-images.githubusercontent.com/11299125/101672738-dbbc2280-3a1b-11eb-8339-da7439785368.png">

But by the time it gets to webview (baked), the class is gone. The link text is changed though -  but I assume that is a recipe thing and is separate from this.
![Screen Shot 2020-12-09 at 12 22 03 PM](https://user-images.githubusercontent.com/11299125/101672775-e971a800-3a1b-11eb-9ce9-9fcb55601a57.png)
https://vendor.cnx.org/contents/mrS6bR5I@7.6:8B4i7sLU@8/1-2-Identify-Users-of-Accounting-Information-and-How-They-Apply-Information
https://archive.cnx.org/contents/9ab4ba6d-1e48-486d-a2de-38ae1617ca84@7.6:921e5ae1-464e-5449-b263-06d2f13fd250@7.6.html

Checking unbaked HTML - and the class is missing. I am starting to Suspect transform nonsense??
![Screen Shot 2020-12-09 at 12 42 45 PM](https://user-images.githubusercontent.com/11299125/101673017-36ee1500-3a1c-11eb-87ad-ce5f34727fcb.png)
https://legacy.cnx.org/content/m67833/1.8/?collection=col25448/1.7&legacy=true

@philschatz do you mind taking a look 👀
