### ISSUE TITLE
astronomy - bring in items from carnival theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3158]
Documentation: #2712

**Comment by MartaSztuka** [comment]
#### PASSED
##### 1. term class="no-emphasis"![Screenshot from 2021-01-08 10-23-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/122f4300-51c2-43dc-9448-32ca27b1b90b)
##### 2. table![Screenshot from 2021-01-08 10-30-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f950823d-45d1-4262-9cd7-b9e28dac2f73)
##### 3. folio![Screenshot from 2021-01-08 10-31-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/edd44830-fc08-4b0a-9b16-bf9e4d3115b8)
##### 4. links![Screenshot from 2021-01-08 10-31-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/efd56dc7-43cd-4a41-9314-8ca6c77e97cf)
##### 5. list ![Screenshot from 2021-01-08 10-35-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f5d59ce5-db70-41e2-9ec1-c1bc3a41ff85)![Screenshot from 2021-01-08 10-33-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/901f200f-5990-4a75-bf64-be5c519c7f48)
##### 6. side bar![Screenshot from 2021-01-08 10-36-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/82f66756-cac9-49fd-825a-abcf83c44029)![Screenshot from 2021-01-08 10-36-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cdd63fc7-1d31-4043-9fb7-c2b04a12adf4)
