### ISSUE TITLE
distribution preview flipping splash image/outline

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#3163]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know
(if this is the wrong repo please forward or let me know)

We located 2 titles in our testing that have the splash images and "Chapter Outline" flipped in Introduction modules when compared to production view:

![Screen Shot 2020-12-11 at 10.16.20 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/059f4556-38d2-40c6-b8c0-861de52cd105)

# Acceptance Criteria

# Bug Location(s)
https://rex-web.herokuapp.com/books/calculus-volume-1@20.2/pages/1-introduction?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20201202.200738

https://rex-web.herokuapp.com/books/031da8d3-b525-429c-80cf-6c8ed997733a@23.12/pages/preface?archive=https://openstax.org/apps/archive-preview/20201202.200738

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by brittweinstein** [comment]
@lwtchu please put a prio on this when you can - we may want to discuss at the next REX meeting.

**Comment by lwtchu** [comment]
@kjdav i don't think this is a big deal - but i can't remember if this is something rex needs to do...or the recipe. i don't think it matters either way but just checking with you (this is the distribution preview)

**Comment by kjdav** [comment]
hm... I wouldn't expect rex to be in charge of remembering what order to show these, is there a reason we would want that?

**Comment by lwtchu** [comment]
@kjdav i think it's just personal preference. some people feel strongly about it. but if you don't feel strongly about it, i can prioritize the fix for a later date

**Comment by wilkus27** [comment]
@lwtchu This change is needed for Baked Styles. In PDFs Chapter Outline has to be under the Splash Image. To achieve this we made some changes in recipes to rearrange elements from Introduction page. That's why it has an impact also on webview.

**Comment by lwtchu** [comment]
Since we need the fix and...there isn't a huge preference. 😬  I'm going to close this. And if anyone has a problem with me closing it, just reopen and let me know :joy:
