### ISSUE TITLE
sociology 2e - add header styles

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3165]
Documentation: #3164

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2021-01-12 17-20-18](https://user-images.githubusercontent.com/47241114/104342429-1cb3c500-54fb-11eb-8896-00ee7802fb4b.png)
![Screenshot from 2021-01-12 17-25-11](https://user-images.githubusercontent.com/47241114/104342456-250c0000-54fb-11eb-8e36-d338c4cd293b.png)
