### ISSUE TITLE
Images not displaying on Rex Preview 

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#3166]
# Brief Description of Scenario and Screenshots
Images aren't appearing in Principles of Management - either the entire field is empty (see below) or it displays a broken image icon. 

What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know

![2020-12-11_14-19-24.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/5e598d95-7c98-40bc-a69d-35cc6a8e55a7)

# Acceptance Criteria
Images display correctly

# Bug Location(s)
collection ID: col28330
server: Rex-web-production
chapter/section: Throughout
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by brittweinstein** [comment]
@lwtchu I'll make a note of bringing this to the REX meeting on Thursday.

**Comment by lwtchu** [comment]
@marcjeannott which link did you click on? View - Rex Web is the link with images. please check with the origianl card to see where you're supposed to test

**Comment by marcjeannott** [comment]
@lwtchu this was suppose to be closed sorry Theresa and I already figured out I had clicked on the wrong link by mistake. False Alarm!
