### ISSUE TITLE
example titles styles changed 

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#3167]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know
example titles styles changed between the rex qa and production. Production has camelcase example titles, rex test has all caps.
![Screen Shot 2020-12-11 at 2.02.34 PM.png](https://images.zenhubusercontent.com/5b572ec492e09f0d21193829/ba570f61-23a9-44d4-abac-f02360dcf432)

# Acceptance Criteria

# Bug Location(s)
collection ID: College Physics
server: https://rex-web.herokuapp.com/books/college-physics@23.12/pages/11-3-pressure?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20201202.200738
chapter/section: everywhere
surrounding text: example

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by brittweinstein** [comment]
@lwtchu would this be a recipes issue or a REX issue?

**Comment by lwtchu** [comment]
@brittweinstein there's an issue #3082 where the release flags weren't enabled due to the recipe name change. i want to wait for that to go out to eliminate that as a possibility before we look into this

**Comment by lwtchu** [comment]
this is intended with the new design.
