### ISSUE TITLE
principles of management: nested alpha and numeric lists fall out of content margins

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3169]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know

![Screen Shot 2020-12-11 at 3 16 29 PM](https://user-images.githubusercontent.com/11299125/101955680-e0bbd600-3bc3-11eb-9d19-1bc09deb745e.png)

I think these are specific to certain areas. Please see below for locations.

# Acceptance Criteria
The list is within the 6.5 in wide content space.

# Bug Location(s)
collection ID: col28330
server: any
chapter/section: 2.1 Overview of Managerial Decision-Making has both
surrounding text: 
- for bulleted list: reduced productivity if there are too few workers or insufficient supplies
- for number list: check the first list after each module title

**Comment by ajluk** [comment]
@lwtchu here is how it looks with standard list margin added: 
![image](https://user-images.githubusercontent.com/55203598/102087913-7a7cc080-3e1a-11eb-8803-a1b656296a43.png)
Is it acceptable due to standardization or should I make the first ol list less indent?

**Comment by lwtchu** [comment]
@ajluk this is acceptable. thank you!

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-17 12-28-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5ac12108-47ab-4c6e-b482-eb6b27c49355)
