### ISSUE TITLE
principles of management - alphabetize key terms

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3170]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [x] recipe [ ] styles [ ] both [ ] i don't know

![Screen Shot 2020-12-11 at 3 33 34 PM](https://user-images.githubusercontent.com/11299125/101957070-59239680-3bc6-11eb-8d8d-8fc2dfb53cf5.png)

# Acceptance Criteria
Can we alphabetize these? If so, in the screenshot above it would look like this:
![Screen Shot 2020-12-11 at 3 35 01 PM](https://user-images.githubusercontent.com/11299125/101957129-75bfce80-3bc6-11eb-94f5-e20510cf3145.png)

# Bug Location(s)
collection ID: col28330
server: any all
chapter/section: key terms section
surrounding text: look for "key terms"

* Can we see if this can be applied to all Key Terms that share this same format? Or is that too difficult? Let me know :)

**Comment by MartaSztuka** [comment]
#### PASSED
Checked in all Key Terms![Screenshot from 2021-01-08 13-04-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/211bc67b-0e3a-4b7d-87a5-df37e9c7f0d1)
