### ISSUE TITLE
sociology 2e - add generic items from other themes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3174]
Documentation #3173

**Comment by MartaSztuka** [comment]
#### PASSED
##### Term![Screenshot from 2021-01-22 10-08-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/da5e8b04-df07-4735-b27f-ae97ba66bc0b)
##### Table![Screenshot from 2021-01-22 10-09-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4d2782d7-7d22-434e-a59c-cb6a305e9488)
##### Folio![Screenshot from 2021-01-22 10-10-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7420ae2d-fc09-48c1-9ba9-211d38782a5b)![Screenshot from 2021-01-22 10-10-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3e71155e-6efa-47f0-a4be-0869af7678a2)
##### Link colour![Screenshot from 2021-01-22 10-28-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8bddc068-f617-4c01-950f-c7eebe0e4c61)
##### Lists![Screenshot from 2021-01-22 10-26-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0164bf71-8b8b-440a-9d26-8c6858157ae0)![Screenshot from 2021-01-22 10-26-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4c8e07f9-5024-45f2-80d0-3f8f3823f80f)![Screenshot from 2021-01-22 10-26-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4a75610f-dcc2-40a5-bda9-79ca4ae837e5)
##### Side bar![Screenshot from 2021-01-22 10-29-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3ff7dcc7-fcdb-4099-b360-3823641d2acc)
##### Footer text![Screenshot from 2021-01-22 10-29-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ca553150-a6e5-45ec-aa3e-2a3bac1d9e92)
##### Images![Screenshot from 2021-01-22 10-32-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7ae34480-e014-4e7a-855a-06ac97867596)
