### ISSUE TITLE
sociology 2e - implement figure styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3184]
Documentation: #3183 

I do not think Sociology 2e has figure titles

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-12 17-19-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0c15d859-0601-4872-ac60-5efb49aa8dfd)
