### ISSUE TITLE
sociology - table style

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3186]
#3185 

I think only Table style 1 exists. Tables should have standard `<caption>` and  `<title>`

**Comment by LostMojo** [comment]
12 Test Content Location(s)
collection ID: col11762
server: katalyst
chapter/section: assorted chapters
surrounding text: TABLE X.X

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-21 16-35-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2b1cd750-0c2c-4ef1-ba4e-1cb4d2e6f20c)
