### ISSUE TITLE
accounting - pull in other items from existing themes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3188]
#2712 - documentation

Hello!  I am not sure if these were implemented yet - would you mind going through to check? Thanks!

**Comment by kswanson33** [comment]
- [x] `<term>` and `<term class="no-emphasis">`
Elements with data-type="term" link to index. Elements with class="no-emphasis" are not bold, while the others are bold.

- [x] table cell alignments driven by content
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/372f849c-1e3c-45a8-b9b8-f58d38639ca0)

- [ ] folio structure (except font is Noto Sans and color is #000000)
Preface: 
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/145440d1-045f-4a96-a6f7-528c81e4e1bf)
Chapter header:
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/b43a26c1-1bd4-4350-97ee-35f13007144b)
Odd page #
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/1a5033b0-f6b1-4f42-b505-7ba18835ddf0)
Even page #
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/ce1c07b9-541a-42d6-85a8-056dcd30495e)
**BUG
Key terms, Summary, Questions, Multiple Choice, Exercise Sets & Problem Sets, Appendices, Answer Key, Index: page number is doubled**
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/b4ab5dd4-cee1-416f-be4c-a8f66a3c3242)
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/84490368-3001-40b7-a5e6-2886872c032a)
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/e77d18c4-5c49-4ec1-a32e-357f05038f19)

- [x] standard link color and treatment
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/d5632e2a-21b1-47ff-9647-0f2ee82de0e3)

- [x] list indentations (stepwise, no label, bulleted, alpha lists)
I scanned through, looks good.
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/1ae9492e-ab9e-44eb-a2ad-05f5e23c4128)

- [ ] side bar in EOC/Answer Key (change color to B4: #24739E; astronomy: #772949)

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/e686da30-7a53-4a43-98d8-8e52a3d903c1)
Adding bands removes the doubled page numbers from the folio.

**Comment by kswanson33** [comment]
The only thing that I saw needed changing was to add the page bands to accounting, but the other items should be double-checked as well.

PR: #3195
accounting is on katalyst01 with col25448

**Comment by MartaSztuka** [comment]
#### PASSED
##### 1. Terms![Screenshot from 2020-12-22 14-07-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/25e533e7-4f8b-41e0-a86c-b5b3fc4422b1)
##### 2. Folio![Screenshot from 2020-12-22 14-09-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a7e408fa-d92e-4cd4-957f-fe0c1cab06b7)
##### 3. Table![Screenshot from 2020-12-22 14-10-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3ddafb56-e8da-4bfe-ba64-f4a8c7f69012)![Screenshot from 2020-12-22 14-10-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/009119f9-2043-4f8a-bea0-4a6208025c1b)
##### 4. Preface![Screenshot from 2020-12-22 14-11-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c12c3cf1-b055-42be-89d5-e1919f860dfa)
##### 5. Chapters![Screenshot from 2020-12-22 14-13-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4d4b6808-6a61-4158-9b53-810bf7e29910)
##### 6. EoC![Screenshot from 2020-12-22 14-15-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fea0b127-99ee-4640-8167-8484ac322da0)![Screenshot from 2020-12-22 14-15-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fa14d728-0e1c-401e-9b69-2648f75cceda)
##### 7. Footnotes![Screenshot from 2020-12-22 14-22-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fafb6cca-fcd9-4b0f-809e-e932b73b8652)
##### 8. Lists indentations![Screenshot from 2020-12-22 14-29-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3ed0fcaf-b73d-4b76-8103-28c903e21578)
