### ISSUE TITLE
cosmos theme - iconned note

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3193]
![Screen Shot 2020-12-15 at 1 38 54 PM](https://user-images.githubusercontent.com/11299125/102264199-eaeb1680-3eda-11eb-86ff-db663ce2eacc.png)

Very similar to the carnival theme iconned notes with some slight font changes. Please keep padding same as carnival theme unless you feel like we can clean it up a bit. 

# [Theme assets folder](https://drive.google.com/drive/u/0/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2)
## Stroke
weight: 1.5pt
color: dependent on feature (this one is B2: `#0074BC`) 

## Icon size
placement: Bottom of icon sits 3px below the bottom stroke
size: 16.5 px (please confirm if this is correct)

## Feature name title
font: [archivo black](https://fonts.google.com/specimen/Archivo+Black?query=archivo+black)
weight: regular, 400
color: black `#000000`
treatment: all caps
font-size: font-scale(1): 10.8pt, 14.4px, 1.2rem

## Feature title from `<title>`
font: archivo
weight: medium, 500
color: black `#000000`
font-size: font-scale(1): 10.8pt, 14.4px, 1.2rem

## Base text
font: ibm plex sans
weight: regular, 400
color: black `#000000`
font-size: font-scale(0): 9pt, 12px, 1rem

**Comment by kswanson33** [comment]
![image](https://user-images.githubusercontent.com/26280712/104215640-0e847c80-5407-11eb-9835-26ef06481aed.png)

Specs added:
- border weight is `0.2rem`
- horizontal spacing between icon and title text is `0.5rem`
- vertical padding between title and first border is `v-spacing(0)`
- vertical padding between note body and second border is `v-spacing(0)`
- icon size is `v-spacing(4)`
- vertical position of icon is `-0.3rem`
- margin below subtitle is `v-spacing(0)`

**Comment by lwtchu** [comment]
documentation closing
