### ISSUE TITLE
sociology - sociology in the real world feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3197]
- class: `sociology-real-world`
- uses #3193 
- title: Sociology in the Real World
- has `<title>`
- icon: [cosmos-world.svg](https://drive.google.com/file/d/1QfMTz9Wq_Iv3H1JL0jxJgXe_bgla9Hk4/view?usp=sharing)
- color: B2: `#0074BC`
- should contain mostly paragraphs

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-15 14-36-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8d2f80a8-e24f-4e71-bbe8-f61d4becf912)
