### ISSUE TITLE
sociology - social policy and debate

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3199]
- class: `sociology-policy-debate`
- uses #3193 
- title: Social Policy & Debate
- has `<title>`
- icon: [cosmos-debate.svg](https://drive.google.com/file/d/1gf0keZTY1ePMqbT7jB_OM53lYIHLrJfg/view?usp=sharing)
- color: G1: `#1E9575`
- should contain mostly paragraphs

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-15 14-36-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/52f5e370-cd5e-4f92-bffe-36fa915ebfb3)
