### ISSUE TITLE
sociology 2e - sociological research

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3200]
- class: `sociological-research`
- uses #3194
- title: Sociological Research
- has `<title>`
- top bar color: B1: `#38568A`
- bottom box color: B4: `#EFF3FA`
- should contain mostly paragraphs, sometimes figures

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-15 14-34-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/851f9d79-1c75-40d0-95fd-5af4ccd18e67)
