### ISSUE TITLE
sociology - big picture feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3201]
- class: `sociology-big-picture`
- uses #3194
- title: Big Picture
- has `<title>`
- uses alternate color schema 2 (red)
- should contain mostly paragraphs, sometimes figures

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-15 16-43-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/54137374-58da-40e8-bbfd-39808b9f1134)
