### ISSUE TITLE
<thead> styling has changed unexpectedly 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#3202]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know

![Screen Shot 2020-12-16 at 11.42.52 AM.jpg](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/378ad27b-3cbc-4624-8f9a-656b1500f43f)
(screenshot above from Business Ethics)

![image.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/3e509265-588d-4ab5-8485-852d527093e5)

# Acceptance Criteria
tables should be styled as detailed [in this issue](https://github.com/openstax/oer.exports/issues/3399)

# Bug Location(s)
collection ID: col30149
server: prod (COPS PDF)
chapter/section: 4.1
surrounding text: " Regulation of the instrumentalities of interstate commerce "

Content: https://katalyst01.cnx.org/contents/Rko_umjB:YJH9XmRf/4-1-Commerce-Clause

It looks like theads are not being styled properly on default tables in Business Law - which is using the Business Ethics recipe.

I only added the thead to chapter 4.1

**Comment by lwtchu** [comment]
Can we make sure default tables follow #2741 for default tables. Mainly the left header cell is the same as the others.

**Comment by yblock** [comment]
It looks like the top-titled class styling isn't rendering the same as it was before COPS in general. The screenshot below is from Business Ethics with business-ethics recipe. Current production PDF we have posted on left, current COPS output on right:
![Screen Shot 2020-12-16 at 11.42.52 AM.jpg](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/424099c1-fb5d-410f-bc9e-988604c5e704)

**Comment by lwtchu** [comment]
@yblock thank you for checking!

**Comment by ajluk** [comment]
@lwtchu I have checked PDF generated locally for Business Ethics and I guess the problem has been already resolved by my previous changes for the tables (I have noticed some regression and fixed it in the meantime):
![image](https://user-images.githubusercontent.com/55203598/103527698-08305680-4e83-11eb-9243-a941afefc83e.png)

**Comment by lwtchu** [comment]
@brittweinstein gonna keep this one here until we have the next corgi deploy :eyes: if that's ok

**Comment by ajluk** [comment]
@lwtchu Branch with changes fixing it was merged to `y.y`.

**Comment by lwtchu** [comment]
![Screen Shot 2021-01-13 at 12 24 08 PM](https://user-images.githubusercontent.com/11299125/104493146-43750880-559a-11eb-896e-f0c3e2a5a219.png)
confirmed fix

@yblock please reopen if..it happens again.
