### ISSUE TITLE
sociology 2e - key terms

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3207]
Documentation #3206

Marked up with `<glossary>`
Title: Key Terms

**Comment by brittany-johnson** [comment]
Unassigning myself since I'm still working on https://github.com/openstax/cnx-recipes/issues/3055
I'll pick this back up once I'm done if it's still available

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-20 09-21-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/38b4ae36-20b8-4739-95c6-647968097549)
