### ISSUE TITLE
sociology - section summary

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3210]
Documentation ##3209 
Class: `class="section-summary"`
broken up by module sections
title: Section Summary

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-14 14-14-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d4eef0fd-2dd9-4aaf-bcca-2935e8bf7251)
