### ISSUE TITLE
sociology - section quiz

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3212]
Documentation #3211 

Class: `class="section-quiz"`
broken up by module sections
title: Section Quiz

**Comment by MartaSztuka** [comment]
@ajluk Headers are unstyled![Screenshot from 2021-01-14 16-50-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4d754154-3ab5-4bd8-84b0-0b1d521e6ac3)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-15 08-59-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2ac6bc9a-ca0f-4910-aaa1-12da2a34b831)
