### ISSUE TITLE
sociology - short answer

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3213]
Documentation #3211 - without the embedded lists

class: `class="short-answer"`
title: Short Answer

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-14 16-57-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ba9dec74-69fd-450e-9af1-872cedaccb08)
