### ISSUE TITLE
sociology - further research

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3215]
Documentation: #3214
Class: `class="further-research"`
title: Further Research
broken up by module sections

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-21 10-11-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/710a7496-c290-4e0b-9004-824bc3dc1589)
