### ISSUE TITLE
sociology - references

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3216]
Documentation: #3214
Class: `class="references"`
title: References
broken up by module sections

**Comment by kswanson33** [comment]
![Screen Shot 2021-01-15 at 2.23.43 PM.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/141177b7-64d2-4879-9f1c-84b5d2d82acb)

@lwtchu @brittany-johnson I'm seeing some weird stuff re: links in References. Most of the URLs in References are plaintext, not wrapped in an `<a>` element (eg. green arrow). However, some of them are links, and whenever that happens, code from `_common-settings.scss` adds an `::after` tag to the element containing the URL. In this case, the content of the link already is the URL. This causes the link text to be repeated twice (eg. red arrow).

Is this a content problem? A styles/recipes problem? And what ultimately should the specs for these URLs be (clickable or static, styled with link styling or black text & no underline)?

**Comment by lwtchu** [comment]
@kswanson33 this is a content problem. can you just leave it as is for now and i'll open a bug on the CM side once the book is done?

**Comment by kswanson33** [comment]
@lwtchu Sounds good, thanks!

**Comment by lwtchu** [comment]
Linking CM card here: https://github.com/openstax/content-managers/issues/2083

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-21 10-14-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3b531afd-3938-4a12-bc0b-0e887fd724dd)
