### ISSUE TITLE
american government - table of contents

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3223]
Documentation: #3154

Has units.

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-19 12-10-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ea3a5c16-25d8-4ced-8685-d40ec35afee0)

**Comment by wilkus27** [comment]
Reopen to fix Unit styling. Here are the specs: https://github.com/openstax/cnx-recipes/issues/3154#issuecomment-762965934

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-22 15-51-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fed8f1be-1f0b-4bec-b0e9-5280d9af590d)
