### ISSUE TITLE
american government - generic library wide check

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3224]
Documentation: #3173

**Comment by MartaSztuka** [comment]
#### PASSED
##### 1. Table![Screenshot from 2021-02-01 16-14-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6c7b311d-24c4-44a6-9881-c2db46fdebdf)
##### 2. Folio![Screenshot from 2021-02-01 16-14-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ad763fd3-c9e5-4d47-8e66-efcacd447042)
##### 3. Link colour![Screenshot from 2021-02-01 16-16-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a33c76f6-633d-4ec6-8c94-6871bbee9f65)
##### 4. Lists indentations![Screenshot from 2021-02-01 15-06-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/249ed15d-fe66-4445-ada4-13dd44674ce6)![Screenshot from 2021-02-01 16-15-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8216891c-927e-4339-8eef-7dc868a9f4a4)
##### 5. Side bar![Screenshot from 2021-02-01 16-16-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3d16592d-3fa0-477b-ac25-ba858b0d4f13)
##### 6. Footer![Screenshot from 2021-02-01 16-16-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0227a05f-def7-46bd-b30c-756bd0a79890)
##### 7. Image settings![Screenshot from 2021-02-01 16-18-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/af68456b-7820-42b8-a0f2-9464172bf0ee)
