### ISSUE TITLE
american government - splash

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3228]
Documentation #3171

I am aware the splashes have a border and a drop shadow. There is a card to fix it on the content side, but we don't have to wait for the fix to go through to make sure it works.

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-21 11-16-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5b5d2a33-a2f3-4acf-af4d-ea68cce80fa9)
