### ISSUE TITLE
american government - learning objectives

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3231]
Documentation #3175
Version 3

**Comment by ajluk** [comment]
Screenshot for reference:
![image](https://user-images.githubusercontent.com/55203598/104924774-33946480-599e-11eb-846d-65fedb169e44.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-21 11-01-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ca80bf6b-6bb3-4fce-9813-d468b86919ee)
