### ISSUE TITLE
american government - link to learning

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3236]
- class: `link-to-learning`
- uses #3235
- title: Link to Learning
- icon: [carnival-linktolearning.svg](https://drive.google.com/file/d/1jm3US-spU6F3BwURhHDY5Emxpe5vmyOr/view?usp=sharing)
- color: G3: `#78B042`

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-20 17-55-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/99243d0d-7d32-46d1-83b7-941c44cf4629)
