### ISSUE TITLE
Astronomy: implement For Further Exploration

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3239]
Documentation: https://github.com/openstax/cnx-recipes/issues/2906

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-08 09-59-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5ea03d72-cb8a-4430-8707-75e99178d3e9)
