### ISSUE TITLE
Astronomy: implement Collaborative Group Activities

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3240]
Documentation: https://github.com/openstax/cnx-recipes/issues/2907

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-08 11-31-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d121943e-5572-4f4a-9642-ba4d772dee3d)
