### ISSUE TITLE
Generate Elementary Algebra 2e, Intermediate Algebra 2e, and Prealgebra 2e ePubs 

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#3242]
We need to generate ePub zips for our ecosystem partners of the dev math trio (2nd editions), so they can ingest our content. This should be tested on staging.cnx.org as it is Mary Jo and Kendra's first time creating these. But, the final zip should be created from Prod, once Alan gets back to supervise.

[This spreadsheet](https://docs.google.com/spreadsheets/d/14GLK8wnYo4SHTZdvFjJWYHlqdBjXCxfqZnXsjxa6emo) is where we track the titles, with their UUIDs and versions, for the ePubs we need to create for our partner.

Here are the steps for generating an ePub (first test on staging):
1) SSH into the server.
2) Run a command based on the UUID provided. (Could possibly vary depending on server)
`/var/cnx/venvs/publishing/bin/cnx-archive-export_epub  --format baked /etc/cnx/publishing/app.ini {UUID} {bookName.epub}`
3) Wait for the command to complete.
4) Download the file.
5) Delete the ePub-only content.
6) Rename the index file to `index.html`.
7) Zip the folder with the proper file name.
8) Upload to [this Google Drive folder](https://drive.google.com/drive/folders/1lw9BfhIcOG0gFdWz9ZgY3yLfXpaJ8ef0).
9) Use @cm in the #books-and-candles channel to alert content managers that an ePub is ready for QA.
10) Delete the collection that was generated in the Home folder.

# Environment:

* **Medium**: [ ] REX [ ] PDF  [x] cnx.org  
* **Instance**: [x] production  [ ] qa  [ ] staging  [ ] dev  [ ] content

# Test Plan 
- Test on staging first. If all looks good, then create the final zip from production when Alan gets back so he can make sure nothing explodes on accident. 
- Alert @cm in the #books-and-candles channel to alert content managers that an ePub is ready for QA
- CMs will open issues in this repo for any files that do not pass testing.

# Acceptance Criteria
- The Dev Math 2e books on the spreadsheet have had ePubs uploaded to the [folder](https://drive.google.com/drive/folders/1lw9BfhIcOG0gFdWz9ZgY3yLfXpaJ8ef0).

# Deadline
- End of January, if possible.

**Comment by lwtchu** [comment]
Note: @LostMojo @kswanson33 can try this when we get back, if they run into problems, we can wait for @Stackblocks

**Comment by LostMojo** [comment]
Complete!

Documentation on creating ePubs can be found on Confluence [here](https://openstax.atlassian.net/wiki/spaces/~631807039/pages/1173979137/Generating+ePubs).
