### ISSUE TITLE
american government - table styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3243]
Documentation #3185 

Uses type 2 - top-titled

I added the top-titled class to the tables on katalyst01

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-26 15-23-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5c2cb6d5-3235-4e53-93b0-19b739130540)
