### ISSUE TITLE
american government - review questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3247]
title: Review Questions
documentation: #3211 - has multiple choice
class: `review-questions`
note: the pdf currently has these in two columns, can we keep it to 1 right now.

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-20 11-57-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a7edd16d-7b20-48bd-bfa9-12026ab81ab2)
