### ISSUE TITLE
american government - critical thinking questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3248]
title: Critical Thinking Questions
documentation: #3211 - does not have multiple choice
class: `critical-thinking`

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-20 13-22-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/49822d56-fc80-4aac-9056-009a9fce6fa7)
