### ISSUE TITLE
american government - suggestions for further study

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3250]
![Screen Shot 2020-12-21 at 12 35 16 PM](https://user-images.githubusercontent.com/11299125/102810277-09448c80-4389-11eb-9761-3964af6648bb.png)

- follows regular header schema #3164 
- `class="suggested-reading"`
- title: Suggestions for Further Study
- should just be separate paragraphs of text 
- can the second/third/etc. line of each paragraph indent (hanging indent)?

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-20 14-31-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e2f84abb-57d8-4b9b-93ae-7d23a70b8702)
