### ISSUE TITLE
american government - appendices

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3251]
- follows #3164 for headers
- some have figures - make sure styling is captured

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-22 15-26-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/04bb3259-4a9f-460d-9ac7-42aed4db626b)![Screenshot from 2021-01-22 15-26-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/053020a0-4ae8-4590-8170-b5a6b863030c)
