### ISSUE TITLE
american government - milestone

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3255]
- class: `milestone`
- uses #3194
- title: Milestone
- has `<title>`
- uses alternate color schema 3 (green)
- should contain mostly paragraphs

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/105011667-807b4800-5a3d-11eb-82cb-d22267b56c66.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-21 11-38-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a529938b-1fd2-419c-81b7-68125d53dbfe)
