### ISSUE TITLE
american government - get connected!

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3256]
- class: `get-connected`
- uses #3193 
- title: Get Connected!
- has `<title>`
- icon: [cosmos-connected.svg](https://drive.google.com/file/d/1F3PAuu9LMu-uiamqy_t-qODiVgNniFNL/view?usp=sharing)
- color: B2: `#0074BC`
- contains paragraphs, figures, lists, tables, etc - please check to make sure styling of all elements trickle down to the note

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/105029782-153c7080-5a53-11eb-8f90-ccab759ee8c3.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-22 10-56-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cc56a7ff-1d7a-49d4-8060-74685334ff6f)
