### ISSUE TITLE
american government - finding a middle ground

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3257]
- class: `class="middle-ground"`
- uses #3194
- title: Finding a Middle Ground
- has `<title>`
- uses color schema 1 (the blue one)
- should contain mostly paragraphs, sometimes figures

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/105013323-6cd0e100-5a3f-11eb-8907-7a78d963e779.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-21 11-36-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6532c8b2-d4b2-4810-a8dd-2d3c7deea4bc)
