### ISSUE TITLE
american government - insider perspective

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3258]
- class: `class="insider-perspective"`
- uses #3194
- title: Insider Perspective
- has `<title>`
- uses color schema 2 (red)
- should contain mostly paragraphs, sometimes figures

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/105018298-11a1ed00-5a45-11eb-9799-d5454378489f.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-21 11-38-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c191d6c8-3e3b-4bd7-be01-7b695f0689b8)
