### ISSUE TITLE
psychology - generic library wide check

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3261]
Documentation: #3173

**Comment by MartaSztuka** [comment]
#### PASSED
##### 1. Table![Screenshot from 2021-02-01 14-44-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/21dff3b7-e278-4c24-b8c8-18e714cf68c1)
##### 2. Folio![Screenshot from 2021-02-01 14-45-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9f1ff256-a92e-4413-9b67-e8350bd52561)
##### 3. Link colour![Screenshot from 2021-02-01 14-46-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/80ef30e7-709e-4011-9c6b-2815f04100c2)
##### 4. Lists indentations![Screenshot from 2021-02-01 14-46-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4337559e-28ee-4145-b6f6-c6fe1c7d4b5f)![Screenshot from 2021-02-01 14-46-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/efb39146-4aa3-48dd-ad94-fada6bf946af)
##### 5. Side bar![Screenshot from 2021-02-01 14-47-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8b8bda6b-b02e-44b6-8701-ced379c4bd82)
##### 6. Footer![Screenshot from 2021-02-01 14-47-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d507ba40-bc07-4450-8d28-7c3ad82d3918)
##### 7. Image settings![Screenshot from 2021-02-01 14-51-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f662ba10-8c06-4380-9fd7-0d5d3ce4c6a9)![Screenshot from 2021-02-01 14-52-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/17efe004-dfb8-41aa-a952-3a39b408e8ec)
