### ISSUE TITLE
psychology - table of contents

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3262]
Documentation #3154
No units

**Comment by ajluk** [comment]
Screenshot for reference:
![image](https://user-images.githubusercontent.com/55203598/105165959-44b4b100-5b17-11eb-89bf-8b0afe7c3dfc.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-21 14-44-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fe977672-129d-4b36-9f91-5e6415d2781e)
