### ISSUE TITLE
psychology - headers

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3263]
Documentation #3164

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/105166465-c3a9e980-5b17-11eb-997e-dca12cc1e7bd.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-21 14-42-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7bff81af-e3c8-41cd-b313-4d5a2cda3b23)
