### ISSUE TITLE
psychology - splash 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3267]
Documentation #3171

I am aware the splashes have a border and a drop shadow. There is a card to fix it on the content side, but we don't have to wait for the fix to go through to make sure it works.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-26 13-27-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/57444685-e3e0-470d-a984-3d4e0cb961ca)
