### ISSUE TITLE
psychology - figure & figure captions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3271]
Documentation #3183

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/105174981-9f540a00-5b23-11eb-938d-01df448ef1a1.png)

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-21 16-44-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bf28cdd2-dd02-45f9-a6ee-2abf2e2e3551)
