### ISSUE TITLE
psychology - table styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3272]
Documentation #3185 

I believe Psychology uses top-titled for everything 🤔

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/106022158-d6975d80-60c5-11eb-97f0-b4a585c40b58.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-28 14-58-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7602d03d-38e8-42bd-882b-231e4806866e)
