### ISSUE TITLE
psychology - link to learning

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3273]
- class: `link-to-learning`
- uses #3235
- title: Link to Learning
- icon: [carnival-linktolearning.svg](https://drive.google.com/file/d/1jm3US-spU6F3BwURhHDY5Emxpe5vmyOr/view?usp=sharing)
- color: G3: `#78B042`

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/105829025-20981a80-5fc4-11eb-8ebb-c6043f9b7956.png)

**Comment by lwtchu** [comment]
@ajluk can we make the text in the feature  ibm plex sans? thanks :)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-27 14-48-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/352160e2-8fb2-409a-b984-80bc3aae785d)
