### ISSUE TITLE
psychology - everyday connection

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3274]
- class: `everyday-connection`
- uses #3194
- title: Everyday Connection
- has `<title>`
- uses color schema 4 (yellow)
- contains paragraphs, figures, lists, tables, etc - please check to make sure styling of all elements trickle down to the note

**Comment by ajluk** [comment]
![image](https://user-images.githubusercontent.com/55203598/105864098-dfb6fa80-5ff1-11eb-885f-de9507f8ddcf.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-27 16-08-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5e639755-5fea-4ea0-9b90-bdb0a99112c3)
