### ISSUE TITLE
psychology - what do you think?

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3275]
- class: `class="what-do-you-think"`
- uses #3194
- title: What Do You Think?
- has `<title>`
- uses color schema 1 (blue)
- should contain mostly paragraphs, sometimes figures, sometimes quotes

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/105963847-c6f62580-6081-11eb-847b-8d16f3911035.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-28 14-31-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/86fd0773-deb3-47b8-af6d-7f574f253ed0)
