### ISSUE TITLE
psychology - blockquotes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3277]
Documentation #3276

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-27 09-37-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0cc94c6d-9394-4416-bada-78d59e70f44a)![Screenshot from 2021-01-27 09-37-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7284af49-0f18-460b-8828-9767a81b32b0)
