### ISSUE TITLE
psychology - dig deeper

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3278]
- class: `class="dig-deeper"`
- uses #3194
- title: Dig Deeper
- has `<title>`
- uses color schema 3 (green)
- should contain mostly paragraphs, sometimes figures, sometimes quotes

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/105965381-a16a1b80-6083-11eb-92f7-5d3a7e6e4a70.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-28 14-30-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/323339ee-c178-4504-b728-5d90982bc127)
