### ISSUE TITLE
psychology - connect the concepts

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3279]
- class: `class="connect-the-concepts"`
- uses #3193 
- title: Connect the Concepts
- has `<title>`
- icon: [cosmos-connected.svg](https://drive.google.com/file/d/1F3PAuu9LMu-uiamqy_t-qODiVgNniFNL/view?usp=sharing)
- color: B2: `#0074BC`
- contains paragraphs, figures, lists, etc - please check to make sure styling of all elements trickle down to the note

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-27 11-24-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/32ec406e-9fbe-4daf-8451-e4f3617fb045)
