### ISSUE TITLE
psychology  - review questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3283]
title: Review Questions
documentation: #3211 - has multiple choice
class: `review-questions`
note: the pdf currently has these in two columns, can we keep it to 1 right now.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-27 13-27-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/68102fc3-4e23-44ee-a092-cfb6ab514034)
