### ISSUE TITLE
psychology - critical thinking questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3284]
title: Critical Thinking Questions
documentation: #3211 - does not have multiple choice
class: `critical-thinking`

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-28 13-35-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d04cb6c8-8d20-4240-b93f-aea2442ce93e)
