### ISSUE TITLE
psychology - personal application questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3285]
title: Personal Application Questions
documentation: #3211 - does not have multiple choice
class: `"personal-application"`

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-28 13-32-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a76e13d2-545b-4511-a56f-70cf6808d648)
