### ISSUE TITLE
accounting - unstyled tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3290]
It has come to my attention that accounting has unstyled tables. Please utilize the same style in College Success...I'll update the table documentation in a bit. #3136

**Comment by kswanson33** [comment]
Status: should just need review and merge!

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-01-06 17-21-17](https://user-images.githubusercontent.com/47241114/103792230-ac60fb80-5043-11eb-9a97-0c8dfe99bea4.png)
![Screenshot from 2021-01-06 17-20-46](https://user-images.githubusercontent.com/47241114/103792243-b125af80-5043-11eb-9c83-b7a79a0fbbb3.png)
![Screenshot from 2021-01-06 17-20-10](https://user-images.githubusercontent.com/47241114/103792290-c0a4f880-5043-11eb-8875-ae683e64c7b6.png)
