### ISSUE TITLE
Regression in Unstyled Tables in College Success

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3294]
I have found out there has been regression in unstyled tables in College Succes caused by overwriting the styles for this tables by default tables: 
![image](https://user-images.githubusercontent.com/55203598/103345983-1fda9a00-4a93-11eb-91cc-d3a4f01da5d7.png)

**Comment by lwtchu** [comment]
@kswanson33 is this related to the work you were doing with the unstyled tables in accounting?

**Comment by lwtchu** [comment]
Original specs/documentation here: #3136

**Comment by ajluk** [comment]
@lwtchu @kswanson33 I have checked that my changes won't affect the unstyled tables in Accounting that the they will look different (I was doing review for Kendra's PR and try my changes on her branch). There the regression wasn't visible because Accounting doesn't have default tables (only top titled). But if you would like to double check, please do.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-08 14-00-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8b240470-362a-40e9-9e38-f87997308def)
