### ISSUE TITLE
Change page size to A4 for Polish University Physics

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3297]
Current page size in generated PDF file is letter (8,5 in ✕ 11 in) which is default for Prince. We would like to change the page size to A4(8,27 in ✕ 11,69 in) for Polish University Physics.

**Comment by ajluk** [comment]
Screenshot for reference (the desire size should be A4(8,27 in ✕ 11,69 in)): 
![image](https://user-images.githubusercontent.com/55203598/103409082-68fb1e80-4b65-11eb-98e9-34be7f1ab0d1.png)

**Comment by ajluk** [comment]
@MartaSztuka to test this issue you need to create PDF file for this book, open it with Adobe Acrobat f.ex. and check in the File/Properties if the correct print size is set in inches (8,27 in ✕ 11,69 in).

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-07 18-20-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/332995de-16be-4aae-8ae0-60043a4823cb)
