### ISSUE TITLE
Fizyka: add dot to part and chapter titles

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3301]
In part and chapter titles there should be dot after number:

![image](https://user-images.githubusercontent.com/40228854/103529507-16cc3d00-4e86-11eb-801d-8d0e9150a8be.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-08 12-35-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4c110ab3-1f49-4f8d-93cb-a09f87a5d50b)
