### ISSUE TITLE
us history - library wide elements check

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3309]
Documentation: #3173

**Comment by MartaSztuka** [comment]
#### PASSED
##### Table cells
#####
#####
#####
#####
#####

**Comment by MartaSztuka** [comment]
#### PASSED
##### Table cells![Screenshot from 2021-02-11 14-15-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8b56d51a-aa0e-403f-ac22-ad39e2c0a8c3)
##### Folio structure![Screenshot from 2021-02-11 14-15-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8742b67f-6c73-464a-bde7-8a23ff5eab75)
##### Link colour![Screenshot from 2021-02-11 14-36-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7fa273e3-1d91-40b6-ac11-9d26f5e114fd)
##### List indentations![Screenshot from 2021-02-11 14-54-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/438cb5b9-5359-4948-a0cb-477b72cb7fa7)![Screenshot from 2021-02-11 14-54-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/663e84e6-a9fd-43b0-8272-f5ddda725ab5)
##### Side bar![Screenshot from 2021-02-11 14-54-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/28ec97f9-bb87-4f9f-bdcd-092af0c91623)
##### Footer text![Screenshot from 2021-02-11 14-55-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/aaed0211-ed16-4a0f-9104-ebb44d45daba)
##### Images settings![Screenshot from 2021-02-11 14-55-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ba2f53b4-7f28-4828-93b0-096bc1c8990f)
