### ISSUE TITLE
us history - table of contents

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3310]
Documentation: #3154

Does not have units

**Comment by ajluk** [comment]
![image](https://user-images.githubusercontent.com/55203598/106127403-d39c7b80-615e-11eb-9673-62197c9a3f18.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-01 14-07-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e6e9afac-118b-4691-9610-dc9596d2094e)
