### ISSUE TITLE
us history - headers

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3311]
Documentation #3164

**Comment by ajluk** [comment]
![image](https://user-images.githubusercontent.com/55203598/106135632-7c9ba400-6168-11eb-8e44-aeae3b875dc6.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-01 14-08-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/290555dd-522f-4be2-8f7c-17d7912c52de)
