### ISSUE TITLE
us history - splash images

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3312]
Documentation #3171

I am aware the splashes are super small and have a shadow. There is a card to fix it on the content side, but we don't have to wait for the fix to go through to make sure it works.

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/106311332-44c65680-6265-11eb-93a4-b51d7d016b10.png)
Within PR covering this issue the splash image will be restyled such the images will be centered and have their own sizes. The discussion with Larissa about this change can be found in the documentation issue (starting from this comment: https://github.com/openstax/cnx-recipes/issues/3171#issuecomment-769780738).

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-05 14-37-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dee8e9a3-6003-4532-83f7-51d09e8d31f9)

**Comment by MartaSztuka** [comment]
##### Sociology![Screenshot from 2021-02-05 15-12-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d86ea046-1d82-4c59-ab35-c892e0399443)
##### Psychology![Screenshot from 2021-02-05 15-14-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c3b6d124-f9f4-4512-b463-818861930294)
