### ISSUE TITLE
us history - implement footnotes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3319]
Documentation #3181 

look for text: Herbert Hoover, address delivered in Denver,

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-02 12-59-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c6aeddf5-e8e3-4d09-a0a9-4fb87292d6aa)
