### ISSUE TITLE
us history - figures

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3322]
Documentation #3184

**Comment by ajluk** [comment]
Screenshot for reference:
![image](https://user-images.githubusercontent.com/55203598/106276966-a15f4c80-6238-11eb-9da8-76ffb7adeacb.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-03 10-59-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0b377547-633a-46c4-8524-5d302d25e96c)
