### ISSUE TITLE
us history - click and explore

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3324]
- class: `history click-and-explore`
- uses #3235
- title: Click and Explore
- icon: [carnival-linktolearning.svg](https://drive.google.com/file/d/1jm3US-spU6F3BwURhHDY5Emxpe5vmyOr/view?usp=sharing)
- color: G3: `#78B042`

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/106729874-42218380-660e-11eb-9ae6-a2f6326ec954.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-05 14-34-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4b5a9e46-2e6c-4977-93c1-76554a9cfbec)
