### ISSUE TITLE
us history - defining american

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3325]
- class: `class="history defining-american"`
- uses #3194
- title: Defining American
- has `<title>`
- uses color schema 4 (the yellow one)
- should contain mostly paragraphs, sometimes figures, quotes

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/106736876-4ce01680-6616-11eb-9407-943ba5a02cd4.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-09 16-12-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3cf12edb-3c88-4911-8a94-1a038a7f85ab)
