### ISSUE TITLE
us history - americana

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3326]
- class: `class="history americana"`
- uses #3194
- title: Americana
- has `<title>`
- uses color schema 1 (the blue one)
- should contain mostly paragraphs, sometimes figures, quotes

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/106739486-7f3f4300-6619-11eb-8821-44997f612c98.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-09 16-11-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3d0fcdc5-b714-4d29-8e4e-c6dde7e66e4e)
