### ISSUE TITLE
us history - my story

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3327]
- class: `class="history my-story"`
- uses #3194
- title: My Story
- has `<title>`
- uses color schema 2 (the red one)
- should contain mostly paragraphs, sometimes figures, quotes

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/106739682-b31a6880-6619-11eb-9b74-8fc8ff4f9965.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-09 16-13-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0b50ae44-3088-4ff4-a231-9942a860a0c6)
