### ISSUE TITLE
Polish books: separate label text and label counter in target labels

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3335]
Markup of links to elements from the book (such as Figures, Tables, Exercises etc.) should be changed to this form:

![image](https://user-images.githubusercontent.com/40228854/104343203-f17da580-54fb-11eb-9ef9-c323d12cee7f.png)

**Comment by wilkus27** [comment]
Initial work for American books is done here: https://github.com/openstax/cnx-recipes/pull/3317 .

**Comment by wilkus27** [comment]
**Decision:** it will be resolved in new pipeline (Kitchen).

**Comment by lwtchu** [comment]
@wilkus27 i moved this into b.b. since these are all refactored now if you want to do :)
