### ISSUE TITLE
us history - key terms

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3340]
Documentation #3206 
Title: Key Terms
Targeted by `<glossary>`

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-03 14-17-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b3f1c6e4-20da-4174-89a0-ef5b0de3fdc2)
