### ISSUE TITLE
us history - review questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3342]
title: Review Questions
documentation: #3211 - has multiple choice
class: `review-questions`
note: the pdf currently has these in two columns, can we keep it to 1 right now.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-04 13-23-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a0b81a98-8a0d-4bd9-a64b-dd5a3966fbce)
