### ISSUE TITLE
us history - critical thinking questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3343]
title: Critical Thinking Questions
documentation: #3211 - does not have multiple choice
class: `critical-thinking`

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-04 14-13-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/293d071c-7d58-49b6-8f37-954e5331e71f)
