### ISSUE TITLE
us history - appendices

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3348]
- follows #3164 for headers
- some have figures and tables - make sure styling is captured

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-03 13-13-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1f7c9781-b8c9-42e9-bb68-584a7eca7742)![Screenshot from 2021-02-03 13-12-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/268cfcbd-a710-4d1a-84a6-5af162fa3114)
