### ISSUE TITLE
us history - answer key

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3350]
Documentation #3252

**Comment by MartaSztuka** [comment]
@wilkus27 @lwtchu There is space missing before following answer, it happens in random locations, usually but not only when answer is one letter.![Screenshot from 2021-02-04 16-37-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8db7337b-dcf5-47eb-a969-b215c9514876)![Screenshot from 2021-02-04 16-46-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/800f48cb-d40a-4b2a-8df6-ef44327de4b2)

**Comment by lwtchu** [comment]
@wilkus27 is it possible to add a little padding or space? i rather there be a tiny bit too much than none.

**Comment by wilkus27** [comment]
@lwtchu I checked and I think spaces are added in the content. It's strange, but in a Chrome browser there is no information about that. I can see it only in Firefox :thinking: 

![image](https://user-images.githubusercontent.com/40228854/107010002-14674680-6796-11eb-8749-b3b6adaf1a2c.png)

I will try to set margin in styles, but probably spaces will be inconsistent. Let me try.

**Comment by wilkus27** [comment]
Yes, spaces are different. I set margin right to `h-spacing(1)` (8px).

![image](https://user-images.githubusercontent.com/40228854/107015014-9fe3d600-679c-11eb-9a92-8c1cfd064cd7.png)

**Comment by lwtchu** [comment]
@wilkus27 awesome thank you i think this is good.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-09 15-22-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bdd0ff5a-f7a3-4122-865b-8ea001669a9b)
