### ISSUE TITLE
economics - pull other library wide things into book

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3354]
Documentation/checklist #3173

**Comment by MartaSztuka** [comment]
#### PASSED
##### term![Screenshot from 2021-03-11 14-24-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/230cbd2b-5b29-47b1-a40f-4d40bfe12ead)
##### table![Screenshot from 2021-03-11 14-24-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/96cb2c32-4fae-4da1-9e28-e9940b07cde3)
##### folio structure![Screenshot from 2021-03-11 14-24-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f004dd24-7663-4b62-a554-c63296390a90)
##### standard link color![Screenshot from 2021-03-11 14-25-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1baca3e1-50e3-4a90-8441-e3b1e59e44a0)![Screenshot from 2021-03-11 14-25-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a163a912-4034-459b-9547-cfc7c899e9bf)
##### list indentations![Screenshot from 2021-03-11 14-26-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/32458c4e-c08d-4d92-b13a-5c902f060c0f)![Screenshot from 2021-03-11 14-26-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6dfa880d-2d7e-4ef0-8de2-07d5da309462)
##### side bar in EOC![Screenshot from 2021-03-11 14-27-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fef3bf68-caf7-40bd-989e-c3b6eeb0fe7a)
##### footer text![Screenshot from 2021-03-11 14-35-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fd2603b7-17d2-438b-955b-3abf31272cb6)
##### images settings![Screenshot from 2021-03-11 14-37-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9b4d4057-80cb-4372-bf9c-10a49dcd08b6)
