### ISSUE TITLE
economics - table of contents

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3355]
Documentation: #3154
no units

**Comment by ajluk** [comment]
![image](https://user-images.githubusercontent.com/55203598/106882482-18845d00-66df-11eb-8a51-b0f6e7c87c62.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-08 13-20-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/db7238fa-d02f-469e-830d-4200aec2ff83)
