### ISSUE TITLE
economics - headers

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3356]
Documentation #3164

**Comment by ajluk** [comment]
![image](https://user-images.githubusercontent.com/55203598/106888146-710b2880-66e6-11eb-888e-0b89b5bd4865.png)
![image](https://user-images.githubusercontent.com/55203598/106888178-7d8f8100-66e6-11eb-9b86-a6e5e83c51fe.png)
![image](https://user-images.githubusercontent.com/55203598/106888204-87b17f80-66e6-11eb-91f4-aa2065316bad.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-08 13-21-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c86afbcd-8ad2-46bc-a7ee-d762821bb0b7)
