### ISSUE TITLE
economics - learning objectives

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3358]
Documentation #3175
Version 3

**Comment by ajluk** [comment]
![image](https://user-images.githubusercontent.com/55203598/106908071-3a8dd780-66ff-11eb-9de0-e428b9babc45.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-08 13-19-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/02b8d214-f343-404a-8e3c-e3493488da45)
