### ISSUE TITLE
economics - bring it home

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3359]
- class: `class="economics bringhome"`
- uses #3193 
- title: Bring It Home
- has `<title>`
- icon: [cosmos-home.svg](https://drive.google.com/file/d/1I3pXCnF8dFKFtW1Nlfr5Bqi18Xy-GcEj/view?usp=sharing)
- color: BR1: `#8B693A`
- contains mostly paragraphs, figure, lists

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-24 10-36-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7a2da8c4-baf4-458c-b720-c2e78b02f033)
