### ISSUE TITLE
economics - chapter objectives

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3361]
![Screen Shot 2021-01-13 at 4 21 02 PM](https://user-images.githubusercontent.com/11299125/104517325-69f76b80-55bb-11eb-9342-f95d251577c2.png)

- `class="economics chapter-objectives"`
- same treatment as the version 3 for learning objectives but doesn't have a title #3175 
- font style: IBM Plex Sans
- size: font-scale(0): 9pt, 12px, 1rem
- color: black `#000000`

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-24 10-35-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c4238bd3-dbac-4e06-97d6-8dd426a62d7a)
