### ISSUE TITLE
economics - blockquotes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3364]
Documentation #3276

**Comment by ajluk** [comment]
@lwtchu There are no blockquotes in cuurent content of Principles of Economics. Should this issue will be closed or should I keep the styles for blockquotes for the other economics books which can use the same styles just in case?

**Comment by lwtchu** [comment]
@ajluk hmm i found one...do you mind looking for this text `<quote id="fs-idp57104384">The time at our disposal is limited. There are only twenty-four hours in the day. We have to choose between the different uses to which they may be put. ... Everywhere we turn, if we choose one thing we must relinquish others which, in different circumstances, we would wish not to have relinquished. Scarcity of means to satisfy given ends is an almost ubiquitous condition of human nature.</quote>`

**Comment by ajluk** [comment]
@lwtchu Sorry for the late response, but I have also found it during the work on the Introduction for Economics :sweat_smile:. But thank you!

**Comment by lwtchu** [comment]
@ajluk i just realized..that the quote is different cause it's not marked up consistently 🤦  give me a second - i'll have to open a card for the content fix.

**Comment by lwtchu** [comment]
@ajluk i hcanged it for that instance on katalyst01. let me know if there's another instance you need me to change.

corresponding cm issue for reference: https://github.com/openstax/content-managers/issues/2012

**Comment by ajluk** [comment]
@lwtchu Thank you! There is another instance in Introduction in Chapter 33, so it will be easier during the testing for Marta but I can ask her during the testing the Introduction to just look into this one you have already changed.

**Comment by ajluk** [comment]
@lwtchu I have fetched new content form katalyst01 and something went wrong  - there is para inside q tag :disappointed:  : 
![image](https://user-images.githubusercontent.com/55203598/107751978-62dc8e00-6d1e-11eb-9735-f39a3e5c7aed.png)
The `q` should be changed for `blockquote` tag.

**Comment by lwtchu** [comment]
@ajluk 🤔 i wonder if it's because it's in ...the introduction module??? i'm really confused. let me take a look at the quote in ch 33 also

**Comment by lwtchu** [comment]
@ajluk okay i figured it out it was nested in another paragraph. ...try now?

**Comment by ajluk** [comment]
@lwtchu Now the correct tag has been added, but for some reason the quotes are missing: 
![image](https://user-images.githubusercontent.com/55203598/107923117-53a14e80-6f71-11eb-8a47-6f44e903caf2.png)
I suspect the culprit here could be the `para` which has been left inside the `blockquote` tag. Previously as you can seen in the screenshot above there was para outside the `blockquote` tag:
![image](https://user-images.githubusercontent.com/55203598/107923851-5a7c9100-6f72-11eb-87c5-dd91401fc28b.png)
and there has been some places in the books where there was such markup, but not vice versa. Could the `para` from inside the `blockquote` tag be removed?
Or could you switch the `blockquote` to `para` and add `para` inside around the left the text?

**Comment by ajluk** [comment]
@MartaSztuka Blockquotes with content changes made by Larissa can be found in sections 2.1 and 2.3. There will be no quotation marks around them for now. They will be added in the content but until then  you need to check only the margins. Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/108882290-85b35000-7604-11eb-83ad-e56b712b045d.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-24 11-11-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2ba26db9-b25d-4a49-83a8-2ce1212fc97d)
