### ISSUE TITLE
us history - blockquotes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3365]
Documentation #3276

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/106483880-4daa6880-64af-11eb-8855-523eec28e6e5.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-03 09-45-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/39cabe83-1a36-4ef7-a2fe-3220413cc27a)
