### ISSUE TITLE
economics - link it up

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3366]
- class: `class="economics linkup"`
- uses #3235
- title: Link It Up
- icon: [carnival-linktolearning.svg](https://drive.google.com/file/d/1jm3US-spU6F3BwURhHDY5Emxpe5vmyOr/view?usp=sharing)
- color: G3: `#78B042`

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-24 10-39-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c0926aa6-2074-45be-82d1-80f188fb040c)
