### ISSUE TITLE
economics - clear it up 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3372]
- class: `class="economics clearup"`
- uses #3193 
- title: Clear It Up
- has `<title>`
- icon: [cosmos-coin.svg](https://drive.google.com/file/d/1tXtR8ybFHSN9QNhwYf8-9Hlgr2l_K3sv/view?usp=sharing)
- color: B3: `#00819A`
- contains mostly paragraphs, figure, lists

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/107495344-427ec900-6b90-11eb-8f26-af962e3e2a79.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-11 15-07-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e4a4f9c6-8d4d-414d-a355-ab7874f1b68e)
