### ISSUE TITLE
Add University Physics kitchen recipe to CORGI

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3375]
Acceptance criteria
- [ ] Old recipe isn't available/referenced/existent? in CORGI 
- [ ] New kitchen recipe is used in CORGI
- [ ] PDF generates with no major issues
- [ ] Web view generates with no major issues
- [ ] Ping Larissa if you need someone to test

**Comment by lwtchu** [comment]
for testing corgi: check your understanding should be not thrown away - you'll see it twice in a feature.

**Comment by lwtchu** [comment]
hold off til june 17th

**Comment by Stackblocks** [comment]
@lwtchu Is this considered done at this point, since we are using CORGI to generate UPHYS?

**Comment by lwtchu** [comment]
@Stackblocks i t hink this is done I'll close
