### ISSUE TITLE
Unit titles in American Government should be hidded

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3382]
There are unit titles present in American Government which should be hidden via the styles:
![image](https://user-images.githubusercontent.com/55203598/104756851-9a2a4000-575c-11eb-8ace-d1c4f5da721b.png)

**Comment by ajluk** [comment]
@MartaSztuka The the acceptance criterium is that unit titles shouldn't be visible.

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2021-01-21 10-58-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/40438d29-6f03-4aee-9302-2cdc29cd3816)
##### ToC![Screenshot from 2021-01-21 10-53-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ce03aa45-bb1f-4683-86c0-0c7f7a13d121)
