### ISSUE TITLE
Precal - Bold & Italic variable in para causing line breaks

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#3394]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know

![Screen Shot 2021-01-19 at 12.48.26 PM.png](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/ce09645f-2503-408f-9249-ba308222880e)

The different variables seem to be making new lines. This may be because each has two emphasis tags (a bold and an italic) however this same thing is used in the exercises without breaking into new lines. 

# Acceptance Criteria
The variables aren't causing line breaks. 
# Bug Location(s)
Precalculus PDF - 8.8 Exercises Folio 908
collection ID: col11667
server: Prod
chapter/section:  8.8
surrounding text: For the following exercises, use the vectors

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
I think we had something similar when equations were introduced. Can we make sure the emphasis tags still work but remove the line breaks?

Thanks

**Comment by lwtchu** [comment]
@wilkus27 @ajluk can y'all take a look at this one - it should be p simple. if it's not, please let me know.

**Comment by ajluk** [comment]
@lwtchu I have baked Precalculus on the current `c.c` branch and the variables doesn't cause the line break anymore (I think this issue has been already fixed, by this PR: https://github.com/openstax/cnx-recipes/pull/2692/commits/91345794ab2edd00f74ac5ea88fa308b0f887b56).
![image](https://user-images.githubusercontent.com/55203598/106578389-be996100-653f-11eb-838f-9330e4e2e42c.png)

**Comment by lwtchu** [comment]
Oh nice. Closing :joy:
