### ISSUE TITLE
economics - work it out

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3401]
- class: `class="economics workout"`
- uses #3194
- title: Work It Out
- has `<title>`
- uses color schema 1 (the blue one)
- should contain mostly paragraphs, sometimes figures, sometimes tables

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/107495278-2aa74500-6b90-11eb-8013-db2fd5dee86f.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-11 15-09-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ed8556ba-f80c-4820-b9f1-ddce560ea90d)
