### ISSUE TITLE
american government - blockquotes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3405]
Documentation #3276

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-01-27 10-40-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0ea0c01e-82f6-4189-b9f6-52f0504070c3)![Screenshot from 2021-01-27 10-39-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0dfe0b31-e77c-4320-a6aa-f3ed5d37da63)
