### ISSUE TITLE
Q1: Test how required context shows up in REX, PDF when question pulled in from Exercises

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#3408]
@openstaxalina commented on [Mon Dec 21 2020](https://github.com/openstax/content-managers/issues/2034)

##  Description

1. Select a book to test with, and copy a couple modules of content from that book into CNX under your personal username (not an OpenStax username). (Note: I put the BCA Release on this, just because we are testing this as part of the Blowout. You don't need to use BCA content, and we don't have any yet anyway.)
2. In Exercises, encode some questions with required context. Select a variety of types of context: a feature box, a figure, etc. The required content must occur in the modules you copied from Step 1. Test the 4 question types: single- and multi-part, multiple choice and open ended.
3. Using the nickname, place these into your module of test content on the CNX instance.
4. Assign the book (w/ recipe) and publish.
5. In CORGI, generate & review the PDF & REXview and see if the required context shows up. Please include screenshots below and any notes about the display.
 
## Why do you need us to do it? Who is this for? 
In Exercises, we can set "required context", such as a figure, feature box, etc. for a question. This context will display with the question in Tutor. (We use this when the student must have access to that content to answer the question.) We need to check if/how this appears in the REX and PDF versions of the book.

Starting with the Blowout titles, we will encode all/nearly all book questions in Exercises so books are Tutor-ready. REX will also use these questions for a Practice Widget (launching with HS Physics in January). We need to make sure the requires context functionality is supported not only in Tutor but also REX and PDF formats.

## When do you need us to do this by? 
**please note if this is urgent
Must be done within Q1 so devs can resolve any issues before Blowout titles go into production

---

@theresamasciale commented on [Fri Jan 22 2021](https://github.com/openstax/content-managers/issues/2034#issuecomment-765448828)

Exercises created (all have required context with features found within the same module the exercises are being placed into):
25084
25085
25086

module: m89835
collection: col32641

Link to PDF: https://openstax-cops-artifacts.s3.amazonaws.com/col32641-latest-production-105.pdf
Link to rex web preview: https://rex-web.herokuapp.com/books/7de3b673-0d9f-42da-9431-a401ea698895@2.1/pages/acceleration?archive=https://openstax.org/apps/archive-preview/20210111.201713

PDF and Web Preview results: exercises show up in both pdf and web, but the required context features do not. screenshot of PDF:

![Screen Shot 2021-01-21 at 11.54.28 AM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/a14b4bc5-df2f-4093-b78c-362ec29a0c08)

**Comment by openstaxalina** [comment]
@lwtchu for the Blowout titles, all the assessments will be coded into Exercises and some may "require context", such as a feature, figure, etc. In these cases, the required context should either display right above the question OR there could be a link back to it wherever it appears in the book. 

Would you be able to ask CE Styles how this could be accomplished? I am not sure if we'd need CE Tech's help, as well. I am leaning toward the linking if that could be accomplished. Theresa put in test material above.

(Also noting to park on Monday @ Content Strategy meeting)

**Comment by openstaxalina** [comment]
...continuing to think -- if we go the linking method, we could have a generic anchor text phrase such as "Refer to this material to answer the question below". We wouldn't necessarily have to generate the exact Figure #, etc.

**Comment by lwtchu** [comment]
Note: Collection for Theresa's test content is on Production

**Comment by lwtchu** [comment]
AP Biology has exercises pulled in from exercises.openstax.org if you want to see how it works.

**Comment by lwtchu** [comment]
I have better, real-er content here:
![Screen Shot 2021-03-23 at 11 01 54 AM](https://user-images.githubusercontent.com/11299125/112177807-3f332000-8bc7-11eb-9d40-0702f7c37115.png)

col10004
World History
content03
on exercise: WH-Ch01-Mod01-RQ01
25350@3
Should pull in this image: https://content03.cnx.org/resources/34847c0baf29a9f2bfe802602f89bdf29c1433ca/Figure01_01_Iroquois.png

**Comment by lwtchu** [comment]
There's also a bunch in the visual connection section.

**Comment by kswanson33** [comment]
Linking to the required context is preferred

**Comment by lwtchu** [comment]
Okay can i have it inject this before the question stem but after the questiono number? 

`<span class="req-context">Refer to <link target-id="context-cnxfeatureid-goes-here"/></span>`

Result would be something like this where the Figure 2.1 is generated from that link there ^ : 

1. Refer to Figure 2.1. What is the answer to life, the universe, and everything?

**Comment by lwtchu** [comment]
needs phil's review but was busyyyyy - will reping sometime this week

**Comment by Stackblocks** [comment]
Link is present in the exercise, and correctly links to the specified test image. If additional styling / treatments need to be done we can set up a new issue.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/bea39dec-509e-42f4-a88c-2ef0754cfa09)
