### ISSUE TITLE
Fix blockquotes in cardboard theme

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3409]
During the investigation about blockquotes it occurs that Prince uses the default properties values for `blockquote` html tag. If we would like to make Prince use the precise values we add we need to reset the default values first. 
![image](https://user-images.githubusercontent.com/55203598/105525981-1a631f00-5ce2-11eb-85c9-4590b1194457.png)

**Comment by ajluk** [comment]
@MartaSztuka Testing this issue require check in one of the cardboard books which have blockquotes if they have proper margins set (margin-left/right: 0.25in).

**Comment by MartaSztuka** [comment]
#### PASSED
##### Business Ethics![Screenshot from 2021-01-27 10-43-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/009ce92a-cd6c-446d-8bcd-4a10c0fb1b48)![Screenshot from 2021-01-27 10-42-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/de247538-e71f-4979-9310-3281617cae8b)
