### ISSUE TITLE
economics - equations

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3413]
Documentation #3412

I believe these are all supposed to be unnumbered. But I do not see the class in the content. Is the recipe suppressing equation numbering automatically? IF it is, we might need to not do that and use the class.

**Comment by wilkus27** [comment]
@lwtchu By default none of the equation has number. If we want to have numbered equations than we have to add special config to file related with some book, and then all equations without class "unnumbered" will be numbered.

Do we want to have numbered equations in Economics? Or in any other book from cosmos theme? I can check if they have this config.

**Comment by wilkus27** [comment]
Ok, I checked and none of the cosmos books has this config, so now even if some equations don't have class `unnumbered` they don't have numbers. How we can find which books should have numbered equations? Should we compare them with old PDFs from eor.export?

**Comment by lwtchu** [comment]
@wilkus27 interesting - in your professional opinion, do you think we should add the config file and utilize the class? or just leave it as is?

**Comment by wilkus27** [comment]
Generally, if we are sure that book doesn't have numbered equations we don't specify config. It's empty by default. We should create numbers only in these books which should have them.

About class, all unnumbered equations should have it.

In Economics equations don't have class `unnumbered`. What is the desired effect? If they should be numbered, then I have to make a change in the recipe, and specify config, which creates numbering. Otherwise, we should make a change in the content and add class `unnumbered`.

**Comment by lwtchu** [comment]
@wilkus27 the desired effect is no numbering for all of it. We can keep it empty if it's empty by default. I'll store that in my mind :joy:

**Comment by wilkus27** [comment]
Ok :slightly_smiling_face: :+1: In this case, can I ask you @lwtchu to add class `unnumbered` to one instance of equation in the book on katalyst01, so we can test the styles? Also, do you want me to create a card on content-managers repo about adding class to all equations in Economics?

**Comment by lwtchu** [comment]
@wilkus27 i just added teh class to katalyst01 i'll make a card for the CM board. thank you

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-11 11-39-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1c9a2f03-4de1-4673-9ab5-f62dfcf498b9)![Screenshot from 2021-02-11 11-38-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0350a8e9-c000-4612-a3c6-8a6d8f480a65)
