### ISSUE TITLE
economics - key concepts and summary

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3414]
Documentation: #3209
Title: Key Concepts and Summary
class: `class="summary"`

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-09 10-55-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cefa0226-391c-473e-83a9-625fb30c170f)
