### ISSUE TITLE
economics - self check questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3415]
title: Self-Check Questions
documentation: #3211 - has multiple choice, some short answer
class: `class="self-check-questions"`

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-09 12-11-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f4a07839-f843-476e-90b7-f3866afa7583)
