### ISSUE TITLE
economics - review questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3416]
title: Review Questions
documentation: #3211 - i don't think there's MC
class: `review-questions`
note: the pdf currently has these in two columns, can we keep it to 1 right now.

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-02-09 13-04-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fe437203-dd7b-4d49-b65a-72fecfc2bb95)
