### ISSUE TITLE
economics - critical thinking questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3417]
title: Critical Thinking Questions
documentation: #3211 - does not have multiple choice
class: `critical-thinking`
note: these are also two column in the book but let's keep it as 1

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-09 13-55-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/44470b49-d0ae-4e71-81f5-2c152ae7c7d0)
