### ISSUE TITLE
economics - problems

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3418]
title: Problems
documentation: #3211 - does not have multiple choice
class: `class="problems"`
note: these are also two column in the book but let's keep it as 1

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-10 09-49-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/07095884-22cd-49d7-89e9-27f132f83903)
