### ISSUE TITLE
economics - appendix

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3419]
- follows #3164 for headers
- some have figures/tables - make sure styling is captured

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-10 13-23-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/99e06ed5-f389-4088-aa2e-0dac89432586)![Screenshot from 2021-02-10 13-22-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b6990d62-842e-4cc1-a496-cda56348e122)
