### ISSUE TITLE
economics - answer key

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3420]
~Documentation #3252~

DO NOT USE THE DOCUMENTATION.
![Screen Shot 2021-02-11 at 11 35 03 AM](https://user-images.githubusercontent.com/11299125/107674987-33b21800-6c5d-11eb-981e-16ada0eefece.png)

- headers follow #3164
- number for question is bold
- exercises display one after the other
- same spacing as the EOC questions (.7rem after each exercise)

**Comment by lwtchu** [comment]
@wilkus27 here's the updated specs for the econ answer key. this should ONLY be for economics

**Comment by MartaSztuka** [comment]
@wilkus27 there's no first line indentation ![Screenshot from 2021-02-19 09-06-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f2170d95-b8cc-4a71-a57c-1380b656cb93)

**Comment by lwtchu** [comment]
@MartaSztuka yes sorry - the original screenshot isn't very good 😓  i apologize. your's looks good. thank you for asking.
