### ISSUE TITLE
economics - references

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3422]
Documentation #3244
JUST the end of book portion. And each para should have a hanging indent for the second line.

Let me know if you'd prefer a separate documentation card...but I figured it was close enough 😬

**Comment by MartaSztuka** [comment]
@wilkus27 References looks good, but indentations are missing![Screenshot from 2021-02-18 16-01-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1347deac-3f0d-4574-806f-c8efcf187471)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-19 09-03-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/048b4444-4e83-48ea-83b9-a7f0a0d14fd6)
