### ISSUE TITLE
DO NOT FIX - revisit during revision Try It numbering repeats in Introductory Business Statistics

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#3436]
# Brief Description of Scenario and Screenshots
Try it numbering is repeated when two try-its appear one after the other in Introductory Business Statistics. Spoke to Larissa and because Try-Its mirror Example numbering, a try-it following another try-it could freak it out because it doesn't have an Example number to mirror, so it repeats. See screenshot.

Note: this was noted in [errata report 8808](https://openstax.org/django-admin/errata/errata/8808).

What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know

![Screen Shot 2021-01-27 at 12.08.30 PM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/b63ca890-77a1-4055-9ced-3227f8246cfa)

# Acceptance Criteria
numbering doesn't repeat--though this could mess with numbering overall so this card may have to wait. 

# Bug Location(s)
collection ID: col11776
server: prod
chapter/section: appears in multiple places:
1. Chapter 11.5 - there are two try-it 11.11
   - https://cnx.org/contents/tWu56V64@35.6:JnIRZCIv@13/11-5-Test-for-Homogeneity

2. Chapter 5.1 & 5.2 - try-it 5.1 numbering appears in both sections
   - https://cnx.org/contents/tWu56V64@35.6:pZOyE0wI@16/5-1-Properties-of-Continuous-Probability-Density-Functions

3. Chapter 4.2; there are two try-it 4.4
   - https://cnx.org/contents/tWu56V64@35.6:Yy_iE2FM@15/4-2-Binomial-Distribution

4. Chapter 3.5; there are two try-it 3.30
   - https://cnx.org/contents/tWu56V64@35.6:fCadB1zn@14/3-5-Venn-Diagrams

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
Need to talk to alina about this.

**Comment by openstaxalina** [comment]
(content fix could be putting both exercises in the same <note> and numbering them)

**Comment by lwtchu** [comment]
I believe...this is in the RFQ for 2e. So closing. Ladies please yell at me if I'm incorrect.
