### ISSUE TITLE
bug: additive manufacturing - splash image broken

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3449]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know

![Screen Shot 2021-01-29 at 3 11 02 PM](https://user-images.githubusercontent.com/11299125/106330627-2ce0d980-6249-11eb-83f3-e14e5b8eae04.png)

Same style with Intro to Statistics content
![Screen Shot 2021-01-29 at 3 59 38 PM](https://user-images.githubusercontent.com/11299125/106331726-0a4fc000-624b-11eb-9975-1bf5e31dbc2b.png)

# Acceptance Criteria
![Screen Shot 2021-01-29 at 3 43 17 PM](https://user-images.githubusercontent.com/11299125/106330637-2f433380-6249-11eb-9c28-0aa8f0430d8d.png)
It should look like it does in rest of the theme.

# Bug Location(s)
collection ID: https://legacy-content03.cnx.org/content/col10000/latest/
server: content03
chapter/section: chapter 1
surrounding text: 

# Test Content Location(s) 
(leave blank if the same as above)
collection ID: test with statistics collection (col11562) on katalyst01  (should be really similar in content)
server: 
chapter/section:
surrounding text:

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-02 17-05-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c216727b-c9da-49e9-8325-8e18f441360c)
