### ISSUE TITLE
Math on top of text

### ISSUE THREAD

**Issue by Jacqueline-Yarbrough** [openstax/cnx-recipes#3463]
## Acceptance Criteria
Can we change the Key Equations EOC section in University Physics to one column?

## Original Bug Report

A math equation is bleeding onto text in another column. I don't know what kind of issue this is.

![image.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/6e1c152b-667f-4faf-a56c-aab0670c4dc4)

# Bug Location(s)
collection ID: col12031
server: prod
chapter/section: **Chapter 4: Motion in Three Dimensions**; "Chapter Review"; "Key Equations"
surrounding text: "Key Terms" before; "Summary" after

A math equation is bleeding onto text in another column, as well as onto the border. I don't know what kind of issue this is.

![Screen Shot 2021-02-04 at 4.08.19 PM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/21dede1a-6859-4541-9398-91cd69bc4165)

![Screen Shot 2021-02-04 at 4.10.04 PM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/7664f9e3-fae5-4797-99ad-fea375e35b04)

# Bug Location(s)
collection ID: col12031
server: prod
chapter/section: **Chapter 15: Oscillations**; "Chapter Review"; "Key Equations"
surrounding text: "Key Terms" before; "Summary" after

A math equation is bleeding onto the page's border. I don't know what kind of issue this is.

![Screen Shot 2021-02-05 at 1.56.16 PM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/66e7e69c-42f5-4b77-a406-aaa91267981b)

# Bug Location(s)
collection ID: col12031
server: prod
chapter/section: **Chapter 16: Waves**; "Chapter Review"; "Key Equations"
surrounding text: "Key Terms" before; "Summary" after

A math equation is bleeding onto text in another column. I don't know what kind of issue this is.

![Screen Shot 2021-02-05 at 2.13.21 PM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/fc35b107-1ac4-4c01-91a8-e30a75154198)

# Bug Location(s)
collection ID: col12031
server: prod
chapter/section: **Chapter 17: Sound**; "Chapter Review"; "Problems"
surrounding text: "Conceptual Questions" before; "Additional Problems" after

A math equation is bleeding onto text in another column. I don't know what kind of issue this is.

![Screen Shot 2021-02-08 at 2.12.15 PM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/2064412f-902b-4da7-bb8e-db0bec597ec6)

# Bug Location(s)
collection ID: col12067
server: prod
chapter/section: **Chapter 1: The Nature of Light**; "Chapter Review"; "Key Equations"
surrounding text: "Key Terms" before; "Summary" after

A math equation is bleeding onto the page border. I don't know what kind of issue this is.

![Screen Shot 2021-02-08 at 2.24.51 PM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/576b7bc6-08d0-42a8-8ee2-e4986b502a32)

# Bug Location(s)
collection ID: col12067
server: prod
chapter/section: **Chapter 3: Interference**; "Chapter Review"; "Key Equations"
surrounding text: "Key Terms" before; "Summary" after

**Comment by Jacqueline-Yarbrough** [comment]
Please feel free to send any comments or criticisms about how I created this card; this is the first one I've made.

**Comment by lwtchu** [comment]
@Jacqueline-Yarbrough no criticism. we might need to do a content fix. do you mind checking to see if it happens in more places? and put them in this card

**Comment by Jacqueline-Yarbrough** [comment]
Will do!

**Comment by oscryan** [comment]
Ooh yeah this is a two-column problem hm. I don't like breaking the really short equations with only one equal sign but. egh

**Comment by lwtchu** [comment]
yeah i wanana see scope. if it's really bad we can un two column it

**Comment by marcjeannott** [comment]
This is also a column issue it's wonky but not too prevalent ![Screen Shot 2021-02-05 at 1.26.14 PM.png](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/7cd8e0ba-0442-4679-8b4e-3e7ac26facb7)

**Comment by lwtchu** [comment]
@marcjeannott what's wrong with the screenshot you posted?

**Comment by marcjeannott** [comment]
@lwtchu oops sorry, should have been more clear - just the one or two word per line because of the columns.  Just wonky nothing broken.

**Comment by lwtchu** [comment]
@Jacqueline-Yarbrough in the chapter review problems can you make the math break after teh equal sign. i'll change this card to changing the key equations to one column

**Comment by MartaSztuka** [comment]
#### PASSED
##### University Physics vol 1![Screenshot from 2021-02-19 13-43-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/860cfe92-0257-49f3-9474-6f13e78acc6c)
##### University Physics vol 2![Screenshot from 2021-02-19 14-36-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e87f0e08-41f6-439f-93c5-c8640503d529)
##### University Physics vol 3![Screenshot from 2021-02-19 15-09-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/60d0bc84-290c-4bd1-8467-381666aac4bb)
