### ISSUE TITLE
Missing figure

### ISSUE THREAD

**Issue by Jacqueline-Yarbrough** [openstax/cnx-recipes#3468]
Figure 14.26 is missing from the Corgi-generated pdf. I don't know what kind of issue this is.

![Screen Shot 2021-02-04 at 3.54.07 PM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/01112cad-b11b-4d47-91c9-012361845d13)

# Acceptance Criteria

# Bug Location(s)
collection ID: col12031
server: prod
chapter/section: 14 Fluid Mechanics; Flow Rate and its Relation to Velocity
surrounding text: Figures 14.25 and 14.27 are there.

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section: 
surrounding text:

**Comment by lwtchu** [comment]
@Jacqueline-Yarbrough messaged u on slack but crossposting here for the future. can you double check the content to make sure the figure is actually there. it might've gottten misplaced in the content since the old pdf was generated

**Comment by Jacqueline-Yarbrough** [comment]
![Screen Shot 2021-02-05 at 12.28.08 PM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/b505cc1c-f430-4645-b4cd-ac491027fbff)

Figure title was wrong in the code; it's fixed now.
