### ISSUE TITLE
Key Equations

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#3471]
In EoC Key Equations table lines shouldn't be visible, class `unnumbered-unstyled` is missing. Occurs in: 

- Fizyka vol 1 Chapter 10
- Fizyka vol 2 Chapter 2, 12, 13
- Fizyka vol 3 Chapter 10, 

e.g. Fizyka vol 2
![Screenshot from 2021-02-05 13-19-20](https://user-images.githubusercontent.com/47241114/107033030-fceb8600-67b4-11eb-8e0a-378859f19a94.png)

![Screenshot from 2021-02-05 13-02-27](https://user-images.githubusercontent.com/47241114/107031403-6b7b1480-67b2-11eb-919a-419fc3a20f8a.png)

**Comment by ajluk** [comment]
@MartaSztuka as we discussed and you have posted in some tables in Key Equations the classes `unnumbered unstyled` are missing in the contetnt, so I'm assigning @PatBoj to this issue.

**Comment by ajluk** [comment]
This issue will be fixed on the content side in polish repo, so I;m closing this one.
