### ISSUE TITLE
Final endnote in module not linking back

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#3473]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [x] recipe [ ] styles [ ] both [ ] i don't know

CE opened up a [card](https://github.com/openstax/content-managers/issues/2097) noting a couple link validation errors found in Business Ethics. Three endnotes in chapter 8 are not linking back to the proper text. All three endnotes appear at the end of their respective modules and are marked up correctly; however, once collated, these three final endnotes do not link back.

Note: they do link properly in legacy, but not in cnx (when it's collated). Here is example markup:

Citation in text: `<cite id="rf-006-a" target-id="rf-006"><note class="delete-me" display="inline"/></cite>`

Endnote:
`<note id="rf-006"><link target-id="rf-006-a"><span>6</span></link><span>Gretel Kauffman, "Record Number of Corporations Earn Perfect Score for LGBTQ-Friendly Policies," <emphasis effect="italics">Christian Science Monitor</emphasis>, December 6, 2016. https://www.csmonitor.com/Business/2016/1206/Record-number-of-corporations-earn-perfect-score-for-LGBT-friendly-policies.</span></note>`

Here are the three instances Bey noted in her original card:

|Module|Broken Content|CNX Link|
|--------- |-------------|----------|
|m66977|`<note id="rf-010"><link target-id="rf-010-a"><span>10</span></link><span>Jenna Goudreau, “The Pet Culture,” <emphasis effect="italics">Forbes</emphasis>, October 15, 2009. https://www.forbes.com/2009/10/15/pets-dogs-cats-forbes-woman-time-children.</span></note>`|[Chapter 8 End Notes](https://vendor.cnx.org/contents/kUrGbuHs@5.12:HowMxrVb@5.12/End-Notes)|
|m66973|`<note id="rf-006"><link target-id="rf-006-a"><span>6</span></link><span>Gretel Kauffman, “Record Number of Corporations Earn Perfect Score for LGBTQ-Friendly Policies,” <emphasis effect="italics">Christian Science Monitor</emphasis>, December 6, 2016. https://www.csmonitor.com/Business/2016/1206/Record-number-of-corporations-earn-perfect-score-for-LGBT-friendly-policies.</span></note>`|[Chapter 8 End Notes](https://vendor.cnx.org/contents/kUrGbuHs@5.12:HowMxrVb@5.12/End-Notes)|
|m66974|`<note id="rf-014"><link target-id="rf-014-a"><span>14</span></link><span>Bryce Covert, “New Jersey’s Equal Pay Law Is the New Gold Standard,” <emphasis effect="italics">Huffington Post</emphasis>, April 4, 2018. https://www.huffingtonpost.com/entry/opinion-covert-equal-pay-day-new-jersey_us_5acbc59be4b0337ad1ead22d.</span></note>`|[Chapter 8 End Notes](https://vendor.cnx.org/contents/kUrGbuHs@5.12:HowMxrVb@5.12/End-Notes)|

# Acceptance Criteria
Endnotes that appear at the end of a module collate properly so that they are able to link back to the correct section page. 

# Bug Location(s)
collection ID: col25722
server: production
chapter/section: Chapter 8: sections 8.3, 8.4, 8.5
surrounding text: see above table for note text

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
@theresamasciale how urgent is this

**Comment by lwtchu** [comment]
Anyway - I think once it's collated, the collated link doesn't know where to go since it's no longer on the same page. Recipe will probably have to inject a link

**Comment by theresamasciale** [comment]
I would say fairly urgent. Bey's note was:

> REX is still able to pull this content right now, but within weeks they will fully onboard to RAP (testing begins next week) in which case they would not be able to retrieve this content until it is fixed.

So before REX is onboarded to RAP.

**Comment by lwtchu** [comment]
jesus christ. i'll see if i can squeeze this in.

**Comment by lwtchu** [comment]
@theresamasciale checked one of the modules - i think it's misnumbered cause there's no 002 reference in the main text in m66973... and i think everything is one off so it doesn't know where to go 🙃  might need to renumber?

**Comment by theresamasciale** [comment]
Looks like an endnote reference got removed in the last errata changes, but the endnote itself at the end of the module wasn't removed, causing the misnumbering issue and the DEVASTATION. anyway, i fixed it. closing! thank you larissa!!!!!!!!!
