### ISSUE TITLE
english composition - chapter outline

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3484]
Documentation: #3175 
Version 2

Placement of this should be after the splash image.

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-03-03 at 10 32 32 AM](https://user-images.githubusercontent.com/24909007/109838450-cb2adb00-7c0b-11eb-957e-2a5b8f6dc8c0.png)

**Comment by lwtchu** [comment]
@brittany-johnson sorry to be nitpicky but if it goes to a second line, can it start where the words start and not all the way to the left?

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-03-03 at 11 44 55 AM](https://user-images.githubusercontent.com/24909007/109848447-e6024d00-7c15-11eb-860d-07e39926c2b1.png)

**Comment by lwtchu** [comment]
beautiful !~
