### ISSUE TITLE
english composition - splash image

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3488]
Documentation #3171

**Comment by brittany-johnson** [comment]
![Uploading Screen Shot 2021-03-02 at 3.30.53 PM.png…]()

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-03-02 at 3 30 53 PM](https://user-images.githubusercontent.com/24909007/109717960-56ed2a80-7b6c-11eb-8dba-a0901c8661f6.png)
