### ISSUE TITLE
english composition - learning outcomes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3489]
This should be at the start of every module.

Documentation #3175 
Version 3
Uses `<section class="learning-objectives">` and standard markup

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-03-03 at 12 02 43 PM](https://user-images.githubusercontent.com/24909007/109850692-65911b80-7c18-11eb-9aee-a52833708259.png)
