### ISSUE TITLE
english composition - paragraph icon annotations

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3490]
Note from vendor: 
Linguistics--maybe a set of letters
Culture--maybe a flag
Visual--maybe an eye
Speech--maybe a mouth
Auditory--maybe an ear
Kinesthetic--maybe a human form in motion
Dreaming--maybe a cloud

Need to test with the two following first.
## Functionality
![Screen Shot 2021-02-08 at 4 47 09 PM](https://user-images.githubusercontent.com/11299125/107291180-5fe75200-6a2d-11eb-8928-11bd59895e8e.png)

If the para has one, two or three (no more) then the classes, is it possible to move the text to the side and place them one after the other? 
- icon height & width - v-spacing(2) 
- padding between icon and text - v-spacing(0) 
- padding between icons - v-spacing(0)
- para should also have `annotation` class on it in addition to icons

## Icons
- Linguistics - [icon](https://drive.google.com/file/d/1iqiO6BjqcXDXWrHDmMog__J3NPsVrhpV/view?usp=sharing) - `class="linguistic-icon"`
- Culture - [icon](https://drive.google.com/file/d/1dwyVQHI7ChjKKSAjPDx6U4ZERE8dQMyr/view?usp=sharing) - `class="culture-icon"`
- Dreaming [icon](https://drive.google.com/file/d/1JYbvV2CCWjEqasBdJ-3EHB2--EK-7EcG/view?usp=sharing) - `class="dreaming-icon"`

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-03-04 at 3 52 37 PM](https://user-images.githubusercontent.com/24909007/110036138-27702680-7d02-11eb-8d81-5882bffd33a4.png)
![Screen Shot 2021-03-04 at 3 52 12 PM](https://user-images.githubusercontent.com/24909007/110036146-2939ea00-7d02-11eb-9e4e-a7f55a945ff1.png)

**Comment by lwtchu** [comment]
@brittany-johnson WOWOWOWOW CU T E A F

**Comment by lwtchu** [comment]
closing. opening new one for change requests and final icons
