### ISSUE TITLE
english composition - tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3509]
Documentation #3185

type 1 - use type 1

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-03-02 at 3 39 39 PM](https://user-images.githubusercontent.com/24909007/109718926-8a7c8480-7b6d-11eb-9bb9-2aa63248c654.png)
![Screen Shot 2021-03-02 at 3 39 30 PM](https://user-images.githubusercontent.com/24909007/109718930-8badb180-7b6d-11eb-8ed8-db49a3f99f20.png)
