### ISSUE TITLE
english composition - blockquotes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3510]
Documentation #3276

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-03-02 at 3 41 25 PM](https://user-images.githubusercontent.com/24909007/109719096-c57eb800-7b6d-11eb-853d-7b7808895b58.png)

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-03-02 at 3 41 48 PM](https://user-images.githubusercontent.com/24909007/109719130-d0d1e380-7b6d-11eb-80cf-f046cd47383c.png)
