### ISSUE TITLE
Clean up Learning Objectives code after content update

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3511]
In History and Psychology 2e there were text nodes in the Learning Objectives instead of paragraph: 
![image](https://user-images.githubusercontent.com/55203598/107746941-f1e5a800-6d16-11eb-8747-e6201a74d554.png)
I have added a temporary fix (added styles to the container to cover the para as well). Now the paragraphs has been added in the content. I have cleaned the code and during testing this issue Learning Objectives in History and Psychology need to be tested.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Psychology 2e![Screenshot from 2021-02-25 15-56-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b279df04-ffd8-46e4-85ab-06b9cb90c6cf)![Screenshot from 2021-02-25 15-57-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/99a9ef2c-432f-4364-a335-1b5832223cf9)
##### US History![Screenshot from 2021-02-25 15-59-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0ab390c6-717d-4f46-9a6a-1bf35c197f59)![Screenshot from 2021-02-25 15-59-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fcd6779a-32da-4671-ac2b-2365187f0340)
