### ISSUE TITLE
english composition - literacy narrative trailblazer module section

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3513]
<img width="889" alt="Screen Shot 2021-02-15 at 9 11 56 AM" src="https://user-images.githubusercontent.com/11299125/107963496-dfb17700-6f6d-11eb-9c4d-627f3b261ed3.png">

## Content
It has these tags: 
`<document class="narrative-trailblazer">
<content class="narrative-trailblazer">`

## Specs
This will be very similar to the Stats Lab feature #2273 

### Bar
height: 3 rem
color: Y1: `#DCB83D`
spans edge to edge - please include 0.125in bleed

### Module number
font: archivo
weight: regular, 400
size: font-scale(2): 12.96pt, 16.8px, 1.4rem
color: black `#000000`

### Module Title
font: archivo
weight: bold, 700
size: font-scale(2): 12.96pt, 16.8px, 1.4rem
color: black `#000000`
text: Literacy Narrative Trailblazer (is there a way to set this in the content)

### Author name
font: archivo
weight: regular, 400
size: font-scale(2): 12.96pt, 16.8px, 1.4rem
color: black `#000000`

### Icon 
file: [cosmos-pencil.svg](https://drive.google.com/file/d/11X0zrUXYaAyEvF8jhC-VDuy1TBHqCWT6/view?usp=sharing)
placement: it needs to be flush with the bottom of the bar
sizing..i'm not sure yet.

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-03-02 at 1 04 21 PM](https://user-images.githubusercontent.com/24909007/109700778-d8868d80-7b57-11eb-9004-ba22b1d27be4.png)
