### ISSUE TITLE
pdf bookmarks anchor too low

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#3514]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ x] styles [ ] both [ ] i don't know

The generated pdf anchors for the navigation pane link too low on the page on Chapter links (kind of shows a tiny bit of the bottom of the splash image, just looks off.)

# Acceptance Criteria

# Bug Location(s)
collection ID: any 
server: production 
chapter/section: any 
surrounding text: any 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
Low ish priority since I'm not sure if there's something we can do in Prince (I checked and it doesn't seem to specify specifics). 

Is the target just the header and they put the header at the bottom of the view screen?

**Comment by ajluk** [comment]
@yblock, @lwtchu I'm not sure if I understood the description of the issue correctly. Is the main problem regards the Introduction Page displaying to high and  some part of it is invisible (top margin) when the user clicks the bookmark targetting chapter title? 
![image](https://user-images.githubusercontent.com/55203598/108699887-2111cb80-7506-11eb-892d-45d777a68c2a.png)

**Comment by yblock** [comment]
This is what it looks like in Intellectual Property when I click the chapter 1 link:

![Screen Shot 2021-02-22 at 9 41 58 AM](https://user-images.githubusercontent.com/5865292/108731585-4f85ab80-74f2-11eb-862d-416fd4e2d5fb.png)

**Comment by lwtchu** [comment]
@ajluk in PDFs, you can set the link to pull up either at the top, middle or bottom position of the screen you're viewing. in adobe i think you can even set the zoom. if there's nothing in prince to help set that, we might have to close this card.

**Comment by ajluk** [comment]
@lwtchu @yblock Thank you, so I haven't understood you correctly. In Prince there is one property that supports toolbar actions for Acrobat: `prince-pdf-open-action` (https://www.princexml.com/doc/12/doc-refs/#prop-prince-pdf-open-action), but I couldn't found the correct value for positioning the page when click on link it in the Prince documentation. I only found that you can set the zoom  by `zoom( fit-page | fit-width | fit-height | percent )` when the document is opening. I have also found a named actions list for Acrobat but I couldn't found the properties which set positioning of the displaying page, when someone click on a link here as well. @lwtchu could you paste the path/name of the toolbar menu property which you are using to to "set the link to pull up either at the top, middle or bottom position of the screen" in Acrobat. I can try to use it as a value for the property I have posted above.
But I have noticed that when I'm opening random book and click on the chapter title link it looks like this in Acrobat on Ubuntu: 
![image](https://user-images.githubusercontent.com/55203598/108836769-88e11880-75d1-11eb-9735-18839ddebada.png)

**Comment by lwtchu** [comment]
@ajluk you can scroll and ... right click on the bookmark to set a specific spot. i'm not sure where i can actually write and define it specifically in a field. for the cardboard theme is it low because the title text is in the middle of the page?

**Comment by ajluk** [comment]
@lwtchu In my version of Acrobat there is no such option, when I right click on a bookmark to position the page, but yes you're right the bookmarks are targeting the titles, so if the tile is lower, the page after clicking on the title bookmark will be visible from the title to the bottom. I have checked in Precalculus to confirm this behavior: 
![image](https://user-images.githubusercontent.com/55203598/108997188-97960100-769f-11eb-87a4-dec351c53a37.png) In this case there is no option we can use from Prince properties to change that, because these property which I have written above (prince-pdf-open-action) is only working when someone is opening the document.

**Comment by lwtchu** [comment]
Sounds good - due to limitations of Prince at the moment we will close this. If there are developments in the future, we can reopen.
