### ISSUE TITLE
microbiology / university physics - change alegreya font

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3516]
Hi! We got a report that the Alegreya font is difficult to read. I think we should change it to IBM Plex Serif to keep things simple.

# Acceptance Criteria
Change all instances of Alegreya to *IBM Plex Serif*
Note: This is the same font being used in the cosmos theme.

Please apply this to Microbiology and University Physics. (Will this hit the other carnival theme books? If so, that is okay too but these books are the priority).

**Comment by MartaSztuka** [comment]
#### PASSED
##### Microbiology![Screenshot from 2021-02-19 12-12-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7e82c671-1417-4094-839e-4fa8abb386df)
##### University Physics vol 1![Screenshot from 2021-02-19 13-30-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/81f192fd-17d4-48a2-8a26-d0a6b3d5c5d4)
##### University Physics vol 2![Screenshot from 2021-02-19 14-40-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3a70f5e9-d936-4bfd-a6e1-f64cae308491)
##### University Physics vol 3![Screenshot from 2021-02-19 15-11-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1353bdd5-f6e8-4078-ad8a-eb64acceb6c1)
