### ISSUE TITLE
microbiology - answer key change to inline paragraph

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3517]
![Screen Shot 2021-02-14 at 3 18 02 PM](https://user-images.githubusercontent.com/11299125/107889399-edb4b880-6ed7-11eb-8001-17bfb2902a9b.png)

## Issue
The answers for microbiology are all text or really short - is it possible to save some room by making them all flow one after the other instead of line breaking between each answer?

## Acceptance criteria
Should be like the cosmos theme but headers follow carnival theme rules #3252

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/108185174-4ff5ff00-710c-11eb-9b57-f0f2e2db7306.png)

Should I change anything?

**Comment by lwtchu** [comment]
@wilkus27 this looks good thank you

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-19 12-13-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1e78eba4-0147-4f70-ab9d-576e0f1d4ce3)
