### ISSUE TITLE
microbiology - preface header colors inconsistent 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3518]
![Screen Shot 2021-02-14 at 3 24 39 PM](https://user-images.githubusercontent.com/11299125/107889524-cdd1c480-6ed8-11eb-8f59-0d622ae05c21.png)

The header colors in the preface do not match the rest of the book. Please change to B2: `#0074BC`

**Comment by MartaSztuka** [comment]
##### PASSED
Header colour is #0074BC, as in whole book.
