### ISSUE TITLE
microbiology - micro connections feature change to iconned note

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3519]
![Screen Shot 2021-02-14 at 3 27 46 PM](https://user-images.githubusercontent.com/11299125/107889575-3de04a80-6ed9-11eb-88b6-d84dbef1bbcd.png)

Can we change this to the regular iconned note specs? And NOT the condensed icon?

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/108077219-9267ff00-706c-11eb-97a8-80a75f414d58.png)

Is it ok?

**Comment by lwtchu** [comment]
@wilkus27 beuatiful! thank you

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-24 13-01-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/be3b03a4-7678-4455-ab8d-c368ca3b7316)
