### ISSUE TITLE
microbiology - numbered list not contained in margins

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3520]
![Screen Shot 2021-02-14 at 3 30 04 PM](https://user-images.githubusercontent.com/11299125/107889624-96174c80-6ed9-11eb-8b98-5b042c75789b.png)
In 2.4 Staining MIciroscopic Specimens (and other places)

Can we make sure the lists are contained within the margins? I think we've done similar fixes in other titles.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-19 11-48-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d3107833-fac6-4ffd-af26-5b0fbb4af86f)
