### ISSUE TITLE
carnival - wrong header color in appendix

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3521]
![Screen Shot 2021-02-14 at 3 41 21 PM](https://user-images.githubusercontent.com/11299125/107889889-2b671080-6edb-11eb-90e7-69711a2ece08.png)

The appendix titles should be B3: `#00819A` (it should match the rest of the book headers and the ribbon color)

**Comment by wilkus27** [comment]
After investigation I found out that this problem appears in every book from Carnival Theme. 

#### Information for tester
anatomy - #00819A
biology - #0074BC
chemistry - #00819A
microbiology - #0074BC
physics - #00819A  (college-physics, hs-physics, u-physics, pl-u-physics)

**Comment by lwtchu** [comment]
@wilkus27 thank you for checking! if you don't have time to test everything, i'd prioritize microbiology and university physics.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Anatomy
There's no Appendices, but all headers are #00819A
##### Biology 2e![Screenshot from 2021-02-22 13-19-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/44f224b3-4320-477f-9902-f34346a842b6)
##### Chemistry 2e![Screenshot from 2021-02-22 15-31-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/00f5929a-3d44-4c5c-b545-2837e5152df1)
##### Microbiology![Screenshot from 2021-02-22 15-40-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/76323d0d-ae2c-4480-b543-9856fb0f3526)
##### College Physics![Screenshot from 2021-02-22 16-57-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2d6932d1-209f-4d69-a626-92a89ca65c55)
##### University Physics 1![Screenshot from 2021-02-23 10-42-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9d4908f3-aa00-4108-a513-fd83045665f5)
##### University Physics 2![Screenshot from 2021-02-23 12-11-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3df8296f-f274-4d01-87ed-6df4c98435db)
##### University Physics 3![Screenshot from 2021-02-23 12-13-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e50489cb-305e-4019-92e0-1ecb663133f4)
##### Fizyka 1![Screenshot from 2021-02-23 14-58-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c7efa92b-8250-4a14-bc69-cb97b18a634f)
##### Fizyka 2![Screenshot from 2021-02-23 17-19-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/108e9c16-6c8f-4227-ab47-207a1072a03e)
##### Fizyka 3![Screenshot from 2021-02-23 17-26-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4f468bac-d53b-4ff1-beb2-95888f3aaa08)
