### ISSUE TITLE
english composition - tutor exercises enabled

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3523]
Books moving forward will be using tutor exercises for assessments. This will be using the nickname functionality (used in APUSH/LLPH)

range of exercises is 25087-25092 (numbers in case we need to look it up)

They are on production so make sure you're pointing to exercises.openstax.org

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-03-03 at 4 10 23 PM](https://user-images.githubusercontent.com/24909007/109879296-0690ce00-7c3b-11eb-8ffa-bac1f9480cd1.png)
