### ISSUE TITLE
english composition - different text treatments annotation and public domain text

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3525]
# Annotation text
class: `<para class="annotation-text">`
font: IBM Plex Sans
treatment: italics
size: font-scale(0) - 9pt
color: B2: `#0074BC`

# Public domain text
class: `<para class="public-domain">`
font: [Courier Prime](https://fonts.google.com/specimen/Courier+Prime?preview.text_type=custom)
size: font-scale(0) - 9pt
treatment: nothing special
color: black `#000000`

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-03-03 at 1 01 56 PM](https://user-images.githubusercontent.com/24909007/109857772-a725c480-7c20-11eb-915a-09eb9f5449bd.png)
![Screen Shot 2021-03-03 at 2 22 27 PM](https://user-images.githubusercontent.com/24909007/109867260-e6a5de00-7c2b-11eb-80fa-e107f56a717d.png)

**Comment by lwtchu** [comment]
closing this to make a new one for changes
