### ISSUE TITLE
english composition - further reading

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3541]
Documentation: #3214
NO separate module headers

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-03-02 at 3 46 01 PM](https://user-images.githubusercontent.com/24909007/109719533-69686380-7b6e-11eb-9523-bbb0f9fe2bb7.png)

**Comment by lwtchu** [comment]
@brittany-johnson can we apply the hanging indents for lines after the first  to these?
