### ISSUE TITLE
anthropology - generic items for cosmos theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3550]
Documentation/checklist #3173

**Comment by MartaSztuka** [comment]
#### PASSED
##### term
![Screenshot from 2021-03-10 15-34-57](https://user-images.githubusercontent.com/47241114/110645364-30f00780-81b6-11eb-9695-98186245bd23.png)

##### table
![Screenshot from 2021-03-10 15-37-07](https://user-images.githubusercontent.com/47241114/110645698-7f050b00-81b6-11eb-85d3-f7a6051083e3.png)

##### folio
![Screenshot from 2021-03-10 15-37-51](https://user-images.githubusercontent.com/47241114/110645815-980dbc00-81b6-11eb-9b53-2a1f51f0f27e.png)

##### link color
![Screenshot from 2021-03-10 15-37-31](https://user-images.githubusercontent.com/47241114/110645764-8c21fa00-81b6-11eb-8917-5132b1ef087d.png)

##### list indentations
![Screenshot from 2021-03-10 15-35-42](https://user-images.githubusercontent.com/47241114/110645529-567d1100-81b6-11eb-952a-d58075e56d89.png)
![Screenshot from 2021-03-10 15-36-18](https://user-images.githubusercontent.com/47241114/110645593-6694f080-81b6-11eb-8a28-1d8deb852000.png)
![Screenshot from 2021-03-10 15-36-45](https://user-images.githubusercontent.com/47241114/110645634-701e5880-81b6-11eb-819c-2c204c0f38b4.png)
##### side bar in EOC
![Screenshot from 2021-03-10 15-38-22](https://user-images.githubusercontent.com/47241114/110645890-ab208c00-81b6-11eb-9c47-67f727fe4612.png)
##### footer text
![Screenshot from 2021-03-10 15-38-37](https://user-images.githubusercontent.com/47241114/110645935-b673b780-81b6-11eb-930a-7c595ec44176.png)
##### images settings
![Screenshot from 2021-03-10 15-39-57](https://user-images.githubusercontent.com/47241114/110646146-e622bf80-81b6-11eb-8c4f-ea08447f50cc.png)
