### ISSUE TITLE
anthropology - table of contents

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3551]
Documentation #3154
No units

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/109790046-3e831b80-7c11-11eb-8414-d1a676c8db82.png)

**Comment by ajluk** [comment]
This issue will be coverd within anthropology recipe PR (https://github.com/openstax/cnx-recipes/pull/3606) where I have copy/paste styles form Psychology and no other changes are needed there. When it will be merged I will move it to ready for testing column.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-04 14-33-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/692f71a2-42f5-4ae9-8fc9-e9404aaf1a76)
