### ISSUE TITLE
anthropology - headers

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3552]
Documentation #3164

**Comment by ajluk** [comment]
@lwtchu There is no Preface in Anthropology yet, that is intentional I suppose, but I'm asking just to be sure if I should wait with this issue for some content update?

**Comment by ajluk** [comment]
@lwtchu I have one more question. This how look the nested list present in section 1.3: 
![image](https://user-images.githubusercontent.com/55203598/109797465-d08f2200-7c19-11eb-9a7d-0deee7d725c3.png)
This is because the `li` element only contains the marker, but no content: 
![image](https://user-images.githubusercontent.com/55203598/109797649-03d1b100-7c1a-11eb-8d5a-0e58f0576342.png)
Do you want to fix this somehow?
Same case further: 
![image](https://user-images.githubusercontent.com/55203598/109797815-3d0a2100-7c1a-11eb-8920-71c0069b47e5.png)

**Comment by lwtchu** [comment]
@ajluk i added a fake preface to the content

**Comment by ajluk** [comment]
@lwtchu I have fetched the updated content form the same server and something weird happened to the splash image :fearful: :
![image](https://user-images.githubusercontent.com/55203598/109841325-347d0f00-7c49-11eb-9636-9fc66fd99153.png)
and the rest of the images (just the alt text is displaying): 
![image](https://user-images.githubusercontent.com/55203598/109841375-45c61b80-7c49-11eb-8cf0-2b0ae15dd947.png)

**Comment by ajluk** [comment]
The Preface is there though: 
![image](https://user-images.githubusercontent.com/55203598/109841760-a8b7b280-7c49-11eb-9d14-af6abd37230d.png)

**Comment by lwtchu** [comment]
@ajluk headers look good. i'll ping you about the image

**Comment by ajluk** [comment]
@lwtchu About the nested lists(comment from above: https://github.com/openstax/cnx-recipes/issues/3552#issuecomment-789641200), are the stayed as they are?

**Comment by lwtchu** [comment]
@ajluk it was marked up poorly. i fixed it.

**Comment by ajluk** [comment]
@lwtchu Thank you! Here is how it looks now:
![image](https://user-images.githubusercontent.com/55203598/109960274-e3bcf300-7ce8-11eb-8cc2-5f581bfab244.png)

**Comment by ajluk** [comment]
@MartaSztuka within this issue please also check the nested lists from above (they are present in section 1.3 Reckoning Kinship across Cultures)

**Comment by MartaSztuka** [comment]
#### PASSED
##### Headers![Screenshot from 2021-03-09 13-56-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/59b929b0-4179-4fca-90b2-af20e8bb8fdf)
##### Nested lists![Screenshot from 2021-03-09 13-58-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3a51d081-1f8e-4a03-a66a-19e8d961aa1e)![Screenshot from 2021-03-09 13-57-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b60e019c-5f10-44f0-81c6-2aeea8cccf8d)
