### ISSUE TITLE
anthropology - splash images

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3553]
Documentation #3171

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/109805089-4ea3f680-7c23-11eb-91e9-1e6769de36bf.png)
This issue will be coverd within anthropology recipe PR (https://github.com/openstax/cnx-recipes/pull/3606) where I have copy/paste styles form Sociology and regarding this feature no other changes are needed. When it will be merged I will move it to ready for testing column.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-09 13-53-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6d392a1c-0454-4aee-b952-d53be6ff7f19)
