### ISSUE TITLE
anthropology - chapter outline

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3554]
Documentation: #3175
Version 2

Placement of this should be after the splash image.

**Comment by ajluk** [comment]
![image](https://user-images.githubusercontent.com/55203598/109809306-721d7000-7c28-11eb-9efe-a1a77eeb23c7.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-09 13-58-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7c8fa74f-8c39-4558-8272-145e5e5f9f63)
