### ISSUE TITLE
polish u-pysics: regression testing

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3555]
Solution for additional space after paragraphs which contain footnotes references (https://github.com/openstax/cnx-recipes/issues/3315) might cause some regression. So pl-u-physics should be tested page by page.

Link to PR: https://github.com/openstax/cnx-recipes/pull/3540

**Comment by MartaSztuka** [comment]
#### Fizyka vol 2
##### @wilkus27 there's double space in EoC chapter 1, after question 67.![Screenshot from 2021-03-23 16-19-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4c36fab5-54c2-49d0-aa98-477ffc5568a7)
##### Answer Key chapter 7 ![Screenshot from 2021-03-24 17-31-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/de93d89f-1937-4ae0-a5f6-009ca342db0f)

**Comment by wilkus27** [comment]
It happens because settings for paragraphs from problems and solutions overwrites settings for `p.has-noteref`:

![image](https://user-images.githubusercontent.com/40228854/112614292-6127df00-8e21-11eb-9c96-ce12b4ed6760.png)

**Comment by lwtchu** [comment]
@wilkus27 can this be closed or should i put it in the backlog?

**Comment by wilkus27** [comment]
@lwtchu we can put this to the backlog. Fixing selectors doesn't help, problem still occurs. We need to spent more time on this to figure out why it doesn't work. We discussed with team that it's not urgent, so we come back to this later.

**Comment by lwtchu** [comment]
@wilkus27 thanks !

**Comment by wilkus27** [comment]
After updating to Prince 14, there is no more problem with empty space after exercise:

![image](https://user-images.githubusercontent.com/40228854/151555807-67b05c3f-9dd9-4571-a8d2-4d7d94d81695.png)

But footnote is in the column not at the end of the page.

In Answer Key it looks good:

![image](https://user-images.githubusercontent.com/40228854/151556031-ea80f142-465a-4e6e-8dbc-aec25aeee4ce.png)

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/151586682-9ae251ba-7e87-4673-a757-f6fbc18457e5.png)

**Comment by ajluk** [comment]
@MartaSztuka While testing this issue it will be good to check also American University Physics vol 2 especially the place from this screenshot (https://github.com/openstax/cnx-recipes/issues/3555#issuecomment-806606502) and also pay attention to how the other footnotes look like in the whole book.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Fizyka tom 2
![Screenshot from 2022-02-01 14-16-41](https://user-images.githubusercontent.com/47241114/151975775-3ce5b3af-ad2f-40ca-81eb-de526ba82c5f.png)
##### Physics vol 2
![Screenshot from 2022-02-01 14-23-22](https://user-images.githubusercontent.com/47241114/151976325-b920fc23-06b4-42ad-8a99-c999ba9770b3.png)
