### ISSUE TITLE
Psychologia - Splash Image/Intro

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#3558]
![Screenshot from 2021-02-25 12-49-06](https://user-images.githubusercontent.com/47241114/109149693-35ed9980-7768-11eb-8e81-d6e096bac49e.png)

### Splash image
position: centered on the page
margin: 0.7in from top

### Background color
encompasses space behind image (maybe splash can sit on top for the box), the top margin area and behind the splash figure caption
background: `#969696`
width: 8.5in, full width + bleeds (0.125in (1/8in))
### Figure caption and number
This is specific to the splash.
padding above and below: 1.5rem (what's the closest hgrid?)

### Figure number
font: Archivo
weight: bold, 700
color: yellow `#FFCC00`
treatment: all caps
font size: font-scale(0): 9pt, 12px, 1rem

### Figure title
font: Archivo
weight: bold, 700
color: yellow `#FFCC00`
font size: font-scale(0): 9pt, 12px, 1rem

### Figure caption
font: IBM Plex Sans
weight: regular, 400
color: white` #FFFFFF`
font size: font-scale(0): 9pt, 12px, 1rem

### Chapter Title
font: Archivo
weight: regular, 400
color: white `#ffffff`
font-scale(5): 22.39pt, 30px, 2.5rem
width: 5.5 in
padding under title: 2rem

### Chapter Number
font: Archivo
weight: bold, 700
color: yellow `#FFCC00`
font-scale(8): 38.7pt, 51.6px;, 4.29982rem
width: 1in
alignment: sits right justified on the margin

### Bleeds
image: keep image centered - if image is supposed to have bleed, it will be exported out with that size
size: 0.125in (1/8in)
![Screenshot from 2021-02-25 13-08-59](https://user-images.githubusercontent.com/47241114/109151592-a8f80f80-776a-11eb-9657-bbc57e0d4191.png)

## INTRODUCTION
Introduction module title
font: Archivo
weight: bold, 700
treatment: all caps
font size: font-scale(0): 9pt, 12px, 1rem
color: `#00627b`
placement: place inline with the first paragraph - similar to carnival theme

Text
Same as base font

Notes
In the past we've had a problem witht he page break in the introduction where the paragraph would spill into the margins if it goes to a second page. Can we make sure there's proper margins when there's a page break

**Comment by ajluk** [comment]
Screenshot for reference:
![image](https://user-images.githubusercontent.com/55203598/109315899-54789100-784b-11eb-8262-5abed1c9957d.png)
