### ISSUE TITLE
Psychologia - Sięgnij po więcej note

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#3562]
![Screenshot from 2021-02-25 14-11-34](https://user-images.githubusercontent.com/47241114/109158568-d301ff80-7773-11eb-860e-e5bb4af7fad6.png)

## Stroke
weight: 1.5pt
color: `#79b142`

## Icon size
placement: Bottom of icon sits 3px below the bottom stroke
size: 16.5 px (please confirm if this is correct)

## Feature name title
font: archivo black
weight: regular, 400
color: black #000000
treatment: all caps
font-size: font-scale(1): 10.8pt, 14.4px, 1.2rem

## Feature title from <title>
font: archivo
weight: medium, 500
color: black #000000
font-size: font-scale(1): 10.8pt, 14.4px, 1.2rem

## Base text
font: ibm plex sans
weight: regular, 400
color: black #000000
font-size: font-scale(0): 9pt, 12px, 1rem

**Comment by ajluk** [comment]
Screenshot for reference:
![image](https://user-images.githubusercontent.com/55203598/109503562-bb3fb980-7a9a-11eb-9bb2-919f3360a241.png)
