### ISSUE TITLE
Psychologia: implement styles for Introduction page

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3566]
Documentation:
- Splash Image:  https://github.com/openstax/cnx-recipes/issues/3558
- Chapter Outline: https://github.com/openstax/cnx-recipes/issues/3564

**Comment by ajluk** [comment]
Screenshot for reference:
![image](https://user-images.githubusercontent.com/55203598/109315899-54789100-784b-11eb-8262-5abed1c9957d.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-08 10-26-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/95a2c1cd-58d9-40f4-9cbe-30e77585404a)
