### ISSUE TITLE
Psychologia: implement headers

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3567]
Documentation: https://github.com/openstax/cnx-recipes/issues/3559

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-03-10 11-21-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/49a0774b-f8d0-457a-a395-c635fe39e95d)![Screenshot from 2021-03-10 11-21-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b70e340d-6baf-46d2-943b-2251ac66c97e)
