### ISSUE TITLE
Psychologia: implement TOC

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3568]
Documentation: https://github.com/openstax/cnx-recipes/issues/3560

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-04 13-42-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/23ad0303-5088-48b8-b0e6-bbd05f40fba0)![Screenshot from 2021-03-04 13-43-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/76e9fdb8-eda8-4a81-915c-bbba5bdad759)
