### ISSUE TITLE
Psychologia: implement figures

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3569]
Documentation: https://github.com/openstax/cnx-recipes/issues/3561

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-04 13-41-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/614c8807-5669-4893-bd12-9a41939c850e)![Screenshot from 2021-03-04 13-42-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/84bc7d00-696b-4c40-8f29-2f2d8eaa20f6)
