### ISSUE TITLE
Psychologia: implement Sięgnij po więcej note

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3570]
Documentation: https://github.com/openstax/cnx-recipes/issues/3562

**Comment by ajluk** [comment]
Screenshot for reference:
![image](https://user-images.githubusercontent.com/55203598/109503562-bb3fb980-7a9a-11eb-9bb2-919f3360a241.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-04 13-38-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8d235aba-7b02-45a2-9ca4-ffda4203b805)
