### ISSUE TITLE
Psychologia: implement tables

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3571]
Documentation: https://github.com/openstax/cnx-recipes/issues/3563

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-05 11-46-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f61082c1-dfd6-4b80-a45e-352ea1df62eb)
