### ISSUE TITLE
Psychologia: implement EOC

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3572]
Documentation: https://github.com/openstax/cnx-recipes/issues/3565

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-10 11-44-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fb41b98a-cc73-4b7f-864b-93cf9ce47386)![Screenshot from 2021-03-10 11-44-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7ebb324e-b0ff-4c86-ae43-39919b811a27)
