### ISSUE TITLE
anthropology - learning outcomes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3578]
This should be at the start of every module.

Documentation #3175 
Version 3
Uses `<section class="learning-objectives">` and standard markup

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-09 14-12-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/86b0b325-1871-4482-823d-7a33cad9ef66)
