### ISSUE TITLE
anthropology - introduction

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3579]
documentation #3191

**Comment by ajluk** [comment]
![image](https://user-images.githubusercontent.com/55203598/109809410-8d887b00-7c28-11eb-9490-28e1b1917dd7.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-09 13-54-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a5104cd4-c0dc-43e1-b05f-3635c7449ba9)
