### ISSUE TITLE
anthropology - figures

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3580]
Documentation #3183

**Comment by ajluk** [comment]
Figures will be tested after merging recipe PR: #3606, where I have copy/paste sociology styles, where was no change needed there:
![image](https://user-images.githubusercontent.com/55203598/109821387-37bacf80-7c36-11eb-9f8e-be52a753b632.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-04 14-33-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/43cbce4a-fce5-4570-9687-b569a851ac40)
