### ISSUE TITLE
anthropology - tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3581]
Documentation #3185

type 1 - use type 1

**Comment by ajluk** [comment]
This issue will be resolved within anthropology recipe PR(#3606). After copy/paste styles form Sociology no additional changes were needed there:
![image](https://user-images.githubusercontent.com/55203598/109822003-d7785d80-7c36-11eb-885e-9f9c137f17c9.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-04 14-32-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/92ce0842-6606-47a2-a53d-ef2d2cd47bc2)
