### ISSUE TITLE
anthropology - ethnographic sketches

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3582]
- class: `ethnographic-sketches`
- uses #3194
- title: Ethnographic Sketches
- has `<title>`
- uses alternate color schema 3 (green)
- should contain mostly paragraphs, sometimes figures

**Comment by wilkus27** [comment]
This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/109815961-7f3e5d00-7c30-11eb-8866-3dff13aecb35.png)

@lwtchu Is it ok?

**Comment by lwtchu** [comment]
@wilkus27 yes! looks great thank you

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-04 14-31-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2320f8f9-6481-4599-bd16-e070094b3a27)
