### ISSUE TITLE
anthropology - mini-fieldwork activity

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3583]
- class: `fieldwork-activity`
- uses #3194
- title: Mini-Fieldwork Activity
- has `<title>`
- uses alternate color schema 1 (blue)
- should contain mostly paragraphs, sometimes figures

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/109825180-d98feb80-7c39-11eb-8b0d-1227205ab142.png)

**Comment by lwtchu** [comment]
@wilkus27 i think that looks fine. thank you

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-04 14-30-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/64303423-fd0b-495b-b3db-97cff0751381)
