### ISSUE TITLE
anthropology - profiles in anthropology

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3584]
- class: `profiles-anthropology`
- uses #3194
- title: Profiles in Anthropology
- has `<title>`
- uses alternate color schema 2 (red)
- should contain mostly paragraphs, sometimes figures

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/109835221-507db200-7c43-11eb-88e2-13fc1124a467.png)

**Comment by lwtchu** [comment]
@wilkus27 looks good. thank you!

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-10 13-05-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1477d4af-9800-46e3-beb0-114ec3ad64b0)
