### ISSUE TITLE
anthropology - video

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3585]
- class: `media-video`
- uses #3235
- title: Video
- icon: [carnival-media.svg](https://drive.google.com/file/d/1ysubfctsaUx_oPahgDg0Fi9OyqtccdNJ/view?usp=sharing)
- color: G1: `#1E9575`

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/109853068-c7bc4180-7c55-11eb-8a91-35a7cb702ad5.png)

**Comment by lwtchu** [comment]
cute! thank you :)

**Comment by lwtchu** [comment]
@wilkus27 nice! looks good

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-10 14-06-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bb04063e-1a06-48d7-b565-3cf91a1d320b)
