### ISSUE TITLE
anthropology - key terms

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3587]
Documentation #3206 
Title: Key Terms
Targeted by `<glossary>`

**Comment by ajluk** [comment]
Key Terms will be tested after merging recipe PR: #3606, where I have copy/paste sociology styles, where was no change needed there:
![image](https://user-images.githubusercontent.com/55203598/109827073-b82fff00-7c3b-11eb-96d3-47f21122829b.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-04 14-35-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c8092eb0-a4f3-4583-a43d-61d4ac4b87e4)
