### ISSUE TITLE
anthropology - section summary

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3589]
Documentation #3209
title: Summary
`class="section-summary"`
not broken up by chapter

**Comment by ajluk** [comment]
I have confirmed with Larissa that Summary in Anthropology shouldn't have sections titles/numbers.
This is how it looks: 
![image](https://user-images.githubusercontent.com/55203598/109827808-5a4fe700-7c3c-11eb-97fe-e97501fa8f84.png)
Summary will be tested after merging recipe PR: #3606, where I have copy/paste sociology styles, where was no change needed there.

**Comment by ajluk** [comment]
@lwtchu just to confirm, title for this section should be `Section Summary` as on the screenshot above?

**Comment by lwtchu** [comment]
@ajluk it should be just `Summary`

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-10 09-53-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/46cc30ea-531b-4c7b-b650-fddfad7eab1b)
