### ISSUE TITLE
anthropology - critical thinking questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3590]
title: Critical Thinking Questions
documentation: #3211 - does not have multiple choice
class: `critical-thinking`
note: these are being pulled in from exercises.openstax.org

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/109833178-55416680-7c41-11eb-9ff1-d283ab87fc5f.png)

**Comment by lwtchu** [comment]
@ajluk 🤔 it looks like it's already fetching the tutor exercises :joy: but this looks good

**Comment by ajluk** [comment]
@lwtchu I have used the old pipeline because the content is on different server and Marta couldn't fetch form this server within the new pipeline, I guess it needs to be checked when the content will be moved to katalyst as well.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-09 14-58-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8a499b24-b03b-41c0-b0fe-80cc5482c4db)
