### ISSUE TITLE
anthropology - bibliography

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3591]
Documentation: #3214
NO separate module headers
`class="references"`

**Comment by ajluk** [comment]
@lwtchu Should the title be changed to Bibliography? Now it is references: 
![image](https://user-images.githubusercontent.com/55203598/109834081-1b249480-7c42-11eb-8d26-192a51926ca9.png)

**Comment by lwtchu** [comment]
@ajluk yes please - please change the text to say Bibliography

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/109839698-aa807680-7c47-11eb-9cc6-5a8d2d7ac65e.png)

**Comment by lwtchu** [comment]
@ajluk nice thank you!

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-09 13-52-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/37e8cc2c-d8fb-48ec-9419-1a61534b6fea)
