### ISSUE TITLE
anthropology - index

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3592]
documentation: #3217

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/109838271-4c06c880-7c46-11eb-92e4-eb24470cfce0.png)

**Comment by ajluk** [comment]
Index will be tested after merging recipe PR: #3606, where I have copy/paste sociology styles, where was no change needed there.

**Comment by MartaSztuka** [comment]
@ajluk index doesn't look as in reference ![Screenshot from 2021-03-04 14-07-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/baf8a1c2-1a5a-455b-9d04-9d7520669d03)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-04 14-29-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9eee7888-df24-49d8-98a0-7065a537f605)
