### ISSUE TITLE
carnival theme - muli to mulish

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3596]
Google has removed the Muli font. We should use [Mulish](https://fonts.google.com/specimen/Mulish?preview.text_type=custom) instead since it's close.

**Comment by lwtchu** [comment]
@wilkus27 i changed teh title to say only caranival theme (?) i don't think it impacts..another theme.

**Comment by wilkus27** [comment]
@lwtchu Yes, Muli was used only in Carnival.

**Comment by wilkus27** [comment]
### Affected elements:
(Information for tester)

- folio
- TOC chapter and appendix number
- chapter title ("Chapter" + number)
- headers H2-H5 (Preface, regular module, EOC, EOB)
- index group label (letters A, B etc.)
- appendix title -> only text, not number
- equation number
- figures caption title (not caption text), splash image too
- chapter outline: title + links (or chapter objectives)
- notes title (all types - boxed, icon, etc.)
- example title
- list in abstract or learning objectives
- table header

@lwtchu @MartaSztuka  Let me know if something is unclear. I can add screenshots of all or some of these elements for better understanding.

**Comment by lwtchu** [comment]
@wilkus27 i think the list is fine. @MartaSztuka do you mind just spot checking in university physics (pick one volume) and microbio?

**Comment by MartaSztuka** [comment]
#### PASSED
##### Microbiology
###### folio![Screenshot from 2021-03-05 09-36-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b0e7c239-0720-4a41-b9b1-1b7f5270c539)
###### TOC chapter and appendix number![Screenshot from 2021-03-05 09-41-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/afd16d01-a0d1-438a-8a26-494c0ec49da2)
###### chapter title ("Chapter" + number)![Screenshot from 2021-03-05 09-42-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f52f1314-7ad0-4cb4-a087-bf9a64a119f8)
###### headers H2-H5 (Preface, regular module, EOC, EOB)![Screenshot from 2021-03-05 09-44-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/139a6342-0a73-460c-9eb2-ff6d377d40e5)![Screenshot from 2021-03-05 09-43-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/32b74ac2-ab4e-4e1f-815c-fdd2b17988a9)
###### index group label (letters A, B etc.)![Screenshot from 2021-03-05 09-45-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b49d50e3-0907-49e8-b687-b5c63734fcb2)
###### appendix title -> only text, not number![Screenshot from 2021-03-05 09-46-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4a7599b4-4c39-4245-857e-085b33313bb6)
###### figures caption title (not caption text), splash image too![Screenshot from 2021-03-05 09-47-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d3ea8e0d-0fcd-4312-ac09-e8fd33e3733a)![Screenshot from 2021-03-05 09-46-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bb5de50a-e271-4bdf-938e-4cfde9ce531b)
###### chapter outline: title + links (or chapter objectives)![Screenshot from 2021-03-05 09-50-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b4ccd532-7f1a-444f-9a8f-446ace985db8)
###### notes title (all types - boxed, icon, etc.)![Screenshot from 2021-03-05 09-52-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/191deec7-06f0-4cb7-bfdb-95d67c556d40)
###### list in abstract or learning objectives![Screenshot from 2021-03-05 09-51-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/80c7fd42-eba4-404c-9076-18f31e3fe207)
###### table header![Screenshot from 2021-03-05 09-53-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fba359b0-f66b-4704-b479-15d01d8dfd36)

##### University physics vol 1
###### folio
###### TOC chapter and appendix number![Screenshot from 2021-03-05 11-01-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/66381883-4be5-4147-921e-9ab811a5a202)
###### chapter title ("Chapter" + number)![Screenshot from 2021-03-05 11-02-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2cbac1ad-4ab1-4f5c-8ff8-68a2b3e03bf7)
###### headers H2-H5 (Preface, regular module, EOC, EOB)![Screenshot from 2021-03-05 11-04-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/24cd532d-886a-4bee-a765-eae3a583d66e)
###### index group label (letters A, B etc.)![Screenshot from 2021-03-05 11-05-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9d281af5-b9c3-485c-a18b-cb2ee48076b6)
###### appendix title -> only text, not number![Screenshot from 2021-03-05 11-06-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1be71e62-a7c5-4785-8a27-f6b1619c39db)
###### equation number![Screenshot from 2021-03-05 11-07-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8e2b7110-44b3-433c-becc-dc252cbb1687)
###### figures caption title (not caption text), splash image too![Screenshot from 2021-03-05 11-06-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/889e0c49-14f8-44c2-b19e-fcad600ea5e5)
###### chapter outline: title + links (or chapter objectives)![Screenshot from 2021-03-05 11-07-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a344a067-f5b4-4da2-91d8-e63809acb328)
###### notes title (all types - boxed, icon, etc.)![Screenshot from 2021-03-05 11-08-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f3334885-4100-4dff-8be6-b4faa15fd261)
###### example title![Screenshot from 2021-03-05 11-08-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/71c1dc3f-e6da-4ae5-b371-115586b3d07e)
###### list in abstract or learning objectives![Screenshot from 2021-03-05 11-09-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8e469bd0-02ed-48ea-98cd-d33bc030d808)
###### table header![Screenshot from 2021-03-05 11-10-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/866d62bd-c147-428d-a5e4-78bf880c134f)
