### ISSUE TITLE
microbiology - styling table captions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3597]
![image](https://user-images.githubusercontent.com/11299125/109517836-4dca6380-7a6f-11eb-92bb-aca596927b8b.png)

the table captions for microbiology have been unstyled due to the removal of the muli font. i suspect this will probably impact university physics also??

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/110112175-aec8a300-7db1-11eb-8805-5e93560166fa.png)

I applied Mulish font to table label and number. It has impact on all books from Carnival Theme.

**Comment by lwtchu** [comment]
@wilkus27 thank you - it looks good!

**Comment by MartaSztuka** [comment]
#### PASSED
##### Microbiology![Screenshot from 2021-03-11 13-20-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f4e6c29d-2b90-499e-b0ae-6bd1bdb2fd0a)
##### University Physics![Screenshot from 2021-03-11 13-38-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/14ca0a92-65c1-4eaa-892a-961a23802692)![Screenshot from 2021-03-11 13-38-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d19775fb-d6d0-4671-ad21-b5c1e8807714)
