### ISSUE TITLE
english composition - writing process sections

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3599]
<img width="831" alt="Screen Shot 2021-03-01 at 12 15 32 PM" src="https://user-images.githubusercontent.com/11299125/109540284-dce37580-7a87-11eb-8577-970ee040390a.png">

There are 4 recurring sections in the Writing Process sections. We'd like to call these out to the student.

These should be all H2's and the icon can sit next to the text? Like 1 v-grid. They should be contained within the margins of the text.

### Quick Launch
class: `quick-launch`
icon: [cosmos-launch.svg](https://drive.google.com/file/d/1gy7ydGlYDqfjZnDOkE4FuVgfXEXlFV4m/view?usp=sharing)
titletext generated from class: `Quick Launch:`

### Drafting
TBD

###Peer Review
TBD

###Revising
TBD

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-03-03 at 4 41 33 PM](https://user-images.githubusercontent.com/24909007/109882344-55d8fd80-7c3f-11eb-989b-7dfc9d291346.png)

**Comment by lwtchu** [comment]
new icons and such in another issue
