### ISSUE TITLE
carnival theme - index base font size change

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3605]
![Screen Shot 2021-03-02 at 9 45 58 AM](https://user-images.githubusercontent.com/11299125/109674025-31e0c380-7b3c-11eb-9a64-09c053958d9d.png)

Currently it's at font-scale(1). Can we bump the base text to font-scale(0).9pt? 

Let's do Microbiology & University Physics first.

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/110235507-a77bd380-7f30-11eb-9c32-d00630b10c92.png)

I also reduced space between group of terms. It was `v-spacing(3)`, I set it to `v-spacing(1)`. What do you think?

**Comment by lwtchu** [comment]
@wilkus27 this looks good thank you !

**Comment by MartaSztuka** [comment]
#### PASSED
##### Microbiology![Screenshot from 2021-03-11 13-16-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/52ebd5da-213b-458a-ba78-081c8b01346d)
##### University Physics![Screenshot from 2021-03-11 13-40-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0e6b4d9f-9e3e-4878-a93f-a7b4b7ccec4a)
