### ISSUE TITLE
Anthropology: recipe

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3607]
The PR linked to this issue contains changes made to adjust the recipe created by Phil for Anthropology based on Sociology recipe. Within it I have additionally copied styles from Sociology book.scss file to anthropology book.scss. There were styles from book from other theme, but it will be reworked during working on Anthropology epic.

**Comment by ajluk** [comment]
@lwtchu I moved this card to your column and assigned you, because the work on Anthropology has been done and there was no additional changes to the recipe, so you could close it if you think it's time.

**Comment by lwtchu** [comment]
@ajluk sounds good thank you again :)
