### ISSUE TITLE
world history - learning objectives

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3611]
<img width="649" alt="Screen Shot 2021-03-02 at 1 01 38 PM" src="https://user-images.githubusercontent.com/11299125/109700812-e1775f00-7b57-11eb-967d-ce066beb7f14.png">

This should be at the start of every module.

Documentation #3175 
Version 4
Uses `<section class="learning-objectives">` and standard markup

Note: The numbering here used is very similar to Calculus. 
Chapter#.Module#.Seq# - where the first number is the chapter, second is the module/section it is in and the third is the regular sequential number

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-23 10-04-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7f891004-9d7d-404b-a823-5bc99d288248)
