### ISSUE TITLE
world history - generic items for cosmos theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3613]
Documentation/checklist #3173

**Comment by MartaSztuka** [comment]
#### PASSED
##### term![Screenshot from 2021-03-23 11-26-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/18a9404b-6a87-43a5-8389-96aacf878b9b)![Screenshot from 2021-03-23 11-26-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c14a4c17-80f7-4280-8290-c2c82368bd16)
##### table![Screenshot from 2021-03-23 11-28-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6ef44d66-9b59-47c5-a9b6-9b24a473723f)
##### folio![Screenshot from 2021-03-23 11-28-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/14cfdd82-1d88-4f23-b606-096360b74a1a)
##### link colour![Screenshot from 2021-03-23 11-29-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6b3a65ca-2ed5-44c0-a6b1-f28d018df9df)
##### list indentations![Screenshot from 2021-03-23 11-31-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e19f5634-576b-488a-985e-be9487dff0fb)![Screenshot from 2021-03-23 11-32-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/afe62459-e87b-42fd-9aa8-a6c1cb5b893b)
##### side bar in EOC![Screenshot from 2021-03-23 11-30-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/62ec5c30-839b-401d-b766-51932fa43c8e)
##### footer text![Screenshot from 2021-03-23 11-27-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/42682b87-503e-46cf-9a36-1d13e80da435)
##### images settings![Screenshot from 2021-03-23 11-30-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/78c63fc2-b91d-4aab-91ec-5c6ece08f328)
