### ISSUE TITLE
Bottom Left Corner of Splash Images

### ISSUE THREAD

**Issue by Jacqueline-Yarbrough** [openstax/cnx-recipes#3624]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [X] i don't know

![Screen Shot 2021-03-03 at 9.09.34 AM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/3d9ca7c6-5aa7-4787-8a48-335ab0e6d0de)

# Acceptance Criteria

# Bug Location(s)
collection ID: col12031, col12074, col12067
server: prod
chapter/section: splash images
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by ajluk** [comment]
@lwtchu This issue is really odd, because in the Document Viewer we use on Linux it is not visible: 
![image](https://user-images.githubusercontent.com/55203598/109991590-bbde8700-7d0a-11eb-8055-0f61e494164b.png)
But in the Acrobat Reader and Master PDF it is present:
![image](https://user-images.githubusercontent.com/55203598/109991557-b3864c00-7d0a-11eb-9687-7caa0969a995.png)
![image](https://user-images.githubusercontent.com/55203598/109991690-d44ea180-7d0a-11eb-93ab-9ab4afd7f8d8.png)
In this case do you think we should still try to fix this ?

**Comment by lwtchu** [comment]
@ajluk is the blue bar and image the same size in the css specs? if that is the case it might just be an adobe issue and we can close it.

**Comment by ajluk** [comment]
@lwtchu Yes they are, their width is hardcoded and the height is set to 100% of the container so they are basically the same size, but for some reason they look differently on Adobe and Master PDF viewers. But I have good news, I was able figure out a workaround solution to this issue. I have set different values to `z-index` property for the splash bg(-3), span containing image(-2) and the caption bg,(-1) what makes the caption bg cover this small visual difference between splash image and it's background - it's on the top of them. I haven't changed their sizes. Here how it looks: 
![image](https://user-images.githubusercontent.com/55203598/110122733-47661f80-7dc0-11eb-8f3b-c536d2d9cfb4.png)

**Comment by ajluk** [comment]
I have also set a clean up issue as a blocker to this one, because there is a clean up needed during changing the z-index values in nested components which need to be cleaned, so it will be good to merge the cleanup PR for this part before these changes are applied.

**Comment by lwtchu** [comment]
@ajluk oh how interesting! do you know how much work (approx) would be needed fo rthe clean up issue? i don't think we can implement by friday - but since this is low priority we can get to this in the coming weeks? how does that sound?

**Comment by ajluk** [comment]
@lwtchu Sorry for the delay. I have already merged both PR's (one related with issue and the other clean up one). Both of them only need to be tested. :slightly_smiling_face:

**Comment by MartaSztuka** [comment]
#### PASSED
##### Master PDF editor![Screenshot from 2021-03-17 15-12-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e3268b3b-6073-47d5-a951-f89807eb9225)
##### Document Viewer![Screenshot from 2021-03-17 15-10-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a97463fc-3401-4d14-9663-8d9caf154892)
