### ISSUE TITLE
world history - headers

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3630]
Documentation #3164

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-16 10-00-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/629408ba-ad0d-4511-a0b6-c3f6bbe2132a)![Screenshot from 2021-03-16 10-00-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6736c418-eb19-4d21-977b-174f4ced6fb1)
