### ISSUE TITLE
world history - splash image

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3631]
Documentation #3171

I think the provided source image goes edge to edge? Need to check later.

**Comment by MartaSztuka** [comment]
@kswanson33 There are 2 types of splash images, first one is correct, but the second looks good to. Which one we take?
###### 1![Screenshot from 2021-03-16 09-53-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b60d31c6-bcc1-475b-9033-dbc68eff0909)
###### 2![Screenshot from 2021-03-16 09-54-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/946a6e6a-a458-4bb1-a4a4-01408ead34a0)

**Comment by lwtchu** [comment]
@MartaSztuka both is fine for the prototype i think the vendor wanted to try out the two options.
