### ISSUE TITLE
world history - in their own words

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3633]
- class: `own-words`
- uses #3194
- title: Profiles in Anthropology
- has `<title>`
- uses alternate color schema 1 (blue)
- should contain mostly paragraphs, blockquotes
- **NEW** `list class="critical-thinking"` - added new "Question section" specs on documentation card. Should be a line above the list and bold text for everything under the line.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-18 11-34-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/628ea2f6-69e8-4794-a16a-cd6655771668)
