### ISSUE TITLE
world history - link to learning

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3634]
- class: `link-to-learning`
- uses #3235
- title: Link to Learning
- icon: [carnival-linktolearning.svg](https://drive.google.com/file/d/1jm3US-spU6F3BwURhHDY5Emxpe5vmyOr/view?usp=sharing)
- color: G3: `#78B042`

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-03-18 11-41-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ab5a45fa-8ab9-42ac-845a-c7c4393a30a7)
