### ISSUE TITLE
world history - dueling voices

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3635]
- class: `dueling-voices`
- uses #3194
- title: Dueling Voices
- has `<title>`
- uses alternate color schema 2 (red)
- should contain mostly paragraphs, images
- **NEW** `list class="critical-thinking"` - added new "Question section" specs on documentation card. Should be a line above the list and bold text for everything under the line.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-18 11-29-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e3641836-f755-493c-8aec-0604ce0d83e1)
