### ISSUE TITLE
world history - beyond the book

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3636]
- class: `beyond-book`
- uses #3194
- title: Beyond the Book
- has `<title>`
- uses alternate color schema 3 (green)
- should contain mostly paragraphs, images
- **NEW** `list class="critical-thinking"` - added new "Question section" specs on documentation card. Should be a line above the list and bold text for everything under the line.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-18 10-39-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/672c3a25-3fe3-44b1-a1d4-149fe473cb48)
