### ISSUE TITLE
world history - the past meets the present

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3637]
- class: `past-present`
- uses #3194
- title: The Past Meets the Present
- has `<title>`
- uses alternate color schema 4 (yellow)
- should contain mostly paragraphs, images
- **NEW** `list class="critical-thinking"` - added new "Question section" specs on documentation card. Should be a line above the list and bold text for everything under the line.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-18 11-33-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fbbc1839-9e38-4fb3-98de-f8449106d5b3)
