### ISSUE TITLE
world history - key terms

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3639]
Documentation #3206 
Title: Key Terms
Targeted by `<glossary>`

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-18 10-30-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c4b5fd34-e1a0-4f0f-8159-e868bf9a3561)
