### ISSUE TITLE
world history - section summary

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3640]
Documentation: #3209
Title: Section Summary
class: `class="section-summary"`
Broken up by section

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-18 11-39-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/60f9d54f-6178-42e8-ae8b-dc10f597379b)
