### ISSUE TITLE
world history - review questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3641]
title: Review Questions
documentation: #3211
class: `review-questions`
note: these are being pulled in from exercises.openstax.org

Broken up by section

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-18 10-31-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/59535325-beb0-414d-a494-f821b39b508d)
