### ISSUE TITLE
world history - check your understanding

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3642]
title: Check Your Understanding
documentation: #3211
class: `check-understanding`
note: these are being pulled in from exercises.openstax.org

Separated by section

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-03-18 11-39-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7487ff06-e0e9-4f4f-8500-ab5b7adaafe9)
