### ISSUE TITLE
world history - reflection questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3643]
title: Reflection Questions
documentation: #3211
class: `reflection-questions`
note: these are being pulled in from exercises.openstax.org

Separated by section

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-18 11-38-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1b4d3cd3-a6cd-4434-b44b-08a5127c004d)
