### ISSUE TITLE
world history - visual based questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3644]
title: Visual-Based Questions
documentation: #3211
class: `visual-questions`
note: these are being pulled in from exercises.openstax.org

Separated by section

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-18 11-35-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2ce4ef4e-aa98-43d2-9ba6-b51e9003e8a5)

**Comment by lwtchu** [comment]
@kswanson33  i just noticed the table in exercise 30 isn't styled - is there a way to apply that table stying to exercises?
