### ISSUE TITLE
world history - making connections

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3645]
title: Making Connections
documentation: #3211
class: `making-connections`
note: these are being pulled in from exercises.openstax.org

Separated by section

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-18 11-36-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/99af3da5-3871-4856-83e9-0d727fb33969)
