### ISSUE TITLE
world history - thought provokers

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3646]
title: Thought Provokers
documentation: #3211
class: `thought-provokers`
note: these are being pulled in from exercises.openstax.org

Separated by section

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-18 11-37-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0db19d33-b4fe-4813-be9b-5f5852e9605d)
