### ISSUE TITLE
Implement New Footnotes Style in Polish Recipes

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#3647]
@kjdav and @paulinaszczucinska to determine whether this is a showstopper for releasing Polish books in REX -- that will determine priority for this.

# Brief Description of Scenario and Screenshots
What kind of issue is this? [x] recipe [ ] styles [ ] both [ ] i don't know

The word "Footnote" (or Footnotes) appears in English in the Polish-language books. 

[This did not used to happen.](https://cnx.org/contents/FqtblkWY@2.2:znMPeDv5@2/2-1-Model-cz%C4%85steczkowy-gazu-doskona%C5%82ego)

[But it happens now on CNX](https://cnx.org/contents/FqtblkWY@6.1:znMPeDv5@5/2-1-Model-cz%C4%85steczkowy-gazu-doskona%C5%82ego)...

...[and in REX, even when using the new RAP pipeline](https://rex-web.herokuapp.com/books/16ab5b96-4598-45f9-993c-b8d78d82b0c6@5.1/pages/1-5-przemiany-fazowe?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive%2F20210224.204120).

@philschatz says this is likely because the Polish recipes are using the old footnotes style. **However, below, Natalia and Piotr indicated this may be a simpler matter of needing to input the Polish word for "Footnote" in REX's translation file.** 

We may need to implement the new style of footnotes in the Polish books, either doing this ourselves or helping Katalyst developers with this. Here are the related issues I found (may not be comprehensive 😬 ): 
https://github.com/openstax/cnx-recipes/issues/2243
https://github.com/openstax/cnx-recipes/issues/2379

# Acceptance Criteria
- [ ] "Footnotes" appears in Polish in both _Fizyka_ and _Psychologia_ (if there are footnotes), in the REX view

**Comment by wilkus27** [comment]
We are using new footnotes tags in polish books.
(collection.assembled.xhtml)

![image](https://user-images.githubusercontent.com/40228854/110238224-b66a8200-7f40-11eb-997b-6bc905993ec0.png)


For cnx.org @PiotrKozlowski has already done needed changes in webview repo: https://github.com/openstax/webview/pull/2302/files

![image](https://user-images.githubusercontent.com/40228854/110237873-b1a4ce80-7f3e-11eb-9807-416d3ebe9dbb.png)

And it's working https://cnx.org/contents/TqqPA4io@4.16:Zx_pvyiS@6/1-1-Zakres-stosowalno%C5%9Bci-praw-fizyki 

![image](https://user-images.githubusercontent.com/40228854/110237891-cd0fd980-7f3e-11eb-96f9-0905df30450e.png)

As I understand, similar change should be done for REX but internationalization work didn't start yet, so there is no place to put translation of some strings. @PiotrKozlowski Let me know if I'm wrong.

**Comment by PiotrKozlowski** [comment]
@wilkus27 you're right. The "Footnotes" text comes from our internationalization file which is not translated yet

**Comment by lwtchu** [comment]
@Bkblodget - just checking, but is there a chance there's a translation file for the polish books on rex for the word "footnote" to appear in polish? 

if so, we can close this card I think. :eyes:

**Comment by Bkblodget** [comment]
@lwtchu I think row 6 in this [spreadsheet](https://docs.google.com/spreadsheets/d/1-oBwejkXX-p7Or4ogUuAzfXLXT5RYcHJZA3Rg2yBDac/edit#gid=247436993) may be what you are looking for?

**Comment by PiotrKozlowski** [comment]
I can confirm that `i18n:content:footnotes:title` from the [spreadsheet](https://docs.google.com/spreadsheets/d/1-oBwejkXX-p7Or4ogUuAzfXLXT5RYcHJZA3Rg2yBDac/edit#gid=247436993) is responsible for displaying the title from the screenshot.

**Comment by Bkblodget** [comment]
This will be addressed on the REX end - card [here](https://app.zenhub.com/workspaces/openstax-unified-5b71aabe3815ff014b102258/issues/openstax/unified/1552).

**Comment by lwtchu** [comment]
thank you @Bkblodget <3 i'll close this card
