### ISSUE TITLE
world history - source questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3648]
title: Source Questions
documentation: #3211
class: `source-questions`
note: these are being pulled in from exercises.openstax.org

Separated by section

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-03-18 11-36-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c5292b5d-7509-4f06-b256-8086c7c74de3)
