### ISSUE TITLE
world history - appendix

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3650]
- follows #3164 for headers
- some have figures/tables - make sure styling is captured

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-19 12-11-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bbffbbad-9465-4d93-9ad6-d4df56315cbe)![Screenshot from 2021-03-19 12-12-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/40979775-2502-45b0-aa3a-e1caa0cd0d85)
