### ISSUE TITLE
world history - glossary in appendix

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3651]
Similar to #1339

These are lists within a section that has the class `column-container`. 

- The lists SHOULD NOT have bullets or anything. 
- The base font should be smaller: font-scale(-1) 
- The text should be in 3 columns! And text should go from top to bottom, then left to right.
- The section titles should function as intended within the scale/header documentation.

**Comment by kswanson33** [comment]
![image](https://user-images.githubusercontent.com/26280712/111217744-e69acc00-85a3-11eb-8432-ce6d9b8e3f5b.png)

Added settings:
- column spacing follows Index

@lwtchu deliver unto me your judgment

**Comment by lwtchu** [comment]
https://github.com/openstax/cnx-recipes/issues/3651
HERE IS YOUR JUDGEMENT

**Comment by MartaSztuka** [comment]
@kswanson33 there's still problem with style (letters, bullets, one column) ![Screenshot from 2021-03-19 11-44-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/351bc534-0e04-4861-8c8f-d96ddd5ceb32)![Screenshot from 2021-03-19 11-48-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/225e792c-94d9-44c4-b95d-9fe1ce72e2e6)

**Comment by kswanson33** [comment]
Thanks Marta! I fixed the selector; that should work now.

**Comment by MartaSztuka** [comment]
@kswanson33 it is fixed, except for letters colour ![Screenshot from 2021-03-23 09-44-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1fee1229-111e-4bcd-84ff-1b478bcea1ad)![Screenshot from 2021-03-23 10-02-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dbd6cb16-6e32-48c2-a008-06dcc87e9830)

**Comment by lwtchu** [comment]
going to close this and assume it's been done
