### ISSUE TITLE
world history - centered text

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3655]
Documentation #3654

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-23 11-05-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/81b4fb81-0faa-4f6e-ac7c-21ef9dfd6f67)![Screenshot from 2021-03-23 11-06-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/88bf9ddb-35df-4da4-9b8c-55d54eacc3c8)
