### ISSUE TITLE
Table bottom line

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#3656]
Bottom line isn't table wide in one table.
![Screenshot from 2021-03-05 11-52-31](https://user-images.githubusercontent.com/47241114/110106604-2e527400-7daa-11eb-820a-d9765202e359.png)

**Comment by wilkus27** [comment]
It's because cells in one before last row are merged:

![image](https://user-images.githubusercontent.com/40228854/110238759-aacc8a80-7f43-11eb-9b3d-d554c7c67dae.png)

I'm afraid we are not able to choose these `td`s by css to apply bottom border for them. I think this was the reason why we removed table borders in Carnival theme. 

@ajluk @brittany-johnson @Stackblocks am I remember correctly?

@lwtchu If we want to keep this border I think we can do this only by adding special class in content for such cells.

**Comment by wilkus27** [comment]
Hmm :thinking: I checked and in American Psychology there is no problem in this table:

![image](https://user-images.githubusercontent.com/40228854/110239064-54f8e200-7f45-11eb-808d-1770ae1e746d.png)

So actually we can do content fix for this particular table and apply similar markup as in Psychology 2e. But there is a chance that problem from the issue appears somewhere else in any book from Cosmos theme.

Let me know what we should do in this case.

**Comment by ajluk** [comment]
@wilkus27 Yes it was similar problem in tables from carnival theme and as I remember it was the reason why we gave up the colored bottom borders in them.

**Comment by wilkus27** [comment]
Actually I have found a solution. I created empty component with bottom border in caption and moved it up to stick to the table. This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/112142636-229ee400-8bd7-11eb-978a-590287d57ac5.png)

It affects all books from Cosmos Theme, so probably a few books should be tested.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Psychologia pl![Screenshot from 2021-03-25 10-58-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/386f4f04-3add-4fd5-82e0-c57bf726e640)
##### Psychology![Screenshot from 2021-03-25 11-15-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/abdb7a79-6aa1-434e-9e6a-96c4f61cd2cc)
##### Word History![Screenshot from 2021-03-25 11-52-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1743c04f-a53a-4dfd-9d4f-7abaf3ddef5d)
##### Antropology ![Screenshot from 2021-03-25 12-54-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ac2463eb-6bb7-4012-a0a3-ebb30f24e9fb)
