### ISSUE TITLE
sociology 3e - reenable answer key

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3663]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [x] recipe [x] styles [x] both [ ] i don't know

The answer key was suppressed in the recipe due to us being unable to match the output of the oer.exports PDF. Since we are doing a 3e, we should enable this again.

# Content
You can use the existing Sociology 2e content.

# Acceptance Criteria
- [ ] Style documentation - https://github.com/openstax/cnx-recipes/issues/3252
- [ ] Enable only HALF (every other answer)

**Comment by wilkus27** [comment]
@lwtchu There is an additional title **Answers**:

![image](https://user-images.githubusercontent.com/40228854/111447877-254c9580-870e-11eb-9d0b-77aaba8de16f.png)

Should I remove it by recipes or it will be done in the content? Or do you want me to style it in some way?

**Comment by lwtchu** [comment]
@wilkus27 OH GOD lol let me try to remove it. one second

**Comment by lwtchu** [comment]
@wilkus27 i just removed all the titles - let me know if this is ok

**Comment by wilkus27** [comment]
It looks good now. Thank you!

![image](https://user-images.githubusercontent.com/40228854/111490738-8fc7fa80-873b-11eb-9ee2-81286dc8ebbb.png)

**Comment by lwtchu** [comment]
@wilkus27 beautiful :) !

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-03-18 16-12-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ef329e72-d50f-45a4-b9e1-5ac938feb92d)
