### ISSUE TITLE
world history - header row in middle of table

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3665]
Targeted by `class="header-row"`

Same style as #3185 header row - no side borders, just a band in the middle and bold the text.

There's one in Death from the Steppe: Genghis Khan and the Mongols

**Comment by MartaSztuka** [comment]
@kswanson33 Table look's fine, but shouldn't the headers in middle row be  centered, as in the top row?
![Screenshot from 2021-03-19 12-00-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e1d7712b-7c66-4285-8bdf-64c2382db0c1)![Screenshot from 2021-03-19 12-03-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c489fae0-acf5-40db-a2d1-c6605cffeff2)

**Comment by kswanson33** [comment]
@MartaSztuka I believe that the header row will still follow whatever alignment is set with `data-align`. Since that attribute isn't set here, it defaults to left. Thoughts @lwtchu ?

**Comment by lwtchu** [comment]
@kswanson33 that's fine. if they want it to be centered we can add a data-align attribute

**Comment by MartaSztuka** [comment]
@kswanson33 @lwtchu if it's fine I'm closing the issue
