### ISSUE TITLE
sociology 3e - learning objectives change request

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3667]
# Brief Description of Change and Screenshots
What kind of change is this? [x] recipe [x] styles [ ] i don't know

Documentation: #3175

Currently these are combined in version 1. We need to separate it out and have the Chapter Outline and Learning Objectives to be like versions 2 & 3. 

# Acceptance Criteria
- [x] In the intro, it should automatically generate the chapter outline 
- [x] At the start of each section, there should be a "Learning Objectives" title and the list under it.        
       
# Content Location(s)
Use the existing Sociology 2e katalyst01 collection

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/111336454-8d02d200-8675-11eb-9887-da7c7cc51d34.png)

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-03-19 09-02-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d7c2df55-5585-45a6-a4b2-f6b5ebe90442)
