### ISSUE TITLE
finance - table caption label numbering styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3678]
![Screen Shot 2021-03-11 at 1 00 05 PM](https://user-images.githubusercontent.com/11299125/110839914-baacdd00-8269-11eb-8d0f-d18f95bbeb8d.png)

# THE NEW PART ~
Can we see if we can pull the figure number and title to the top and leave the caption at the bottom? Previously not possible. We could also add a class to this it's possible so we do not confuse it with the default table. But first, let's determine if we can do it :) !!!

# Figure number 
font-style: noto sans
font-size: font-scale(0): 9pt, 12px, 1rem
treatment: bold
color: black `#000000`

# Figure title
font-style: noto sans
font-size: font-scale(0): 9pt, 12px, 1rem
treatment: bold
color: black `#000000`

# Figure caption
font-style: noto sans
font-size: font-scale(-1): 7.5pt, 9.6px, 0.8rem
treatment: regular/none
color: Grey2: `#757474`

**Comment by LostMojo** [comment]
I don't believe there's a way to separate the Table title & Number away from the actual caption, as they're all inside the os-caption-container together (which is a sibling to the table). I think we'd need to make a change to the recipe to do this.

**Comment by lwtchu** [comment]
@LostMojo 🤔  how much work do you estimate this will take we can also park this tomorrow

**Comment by LostMojo** [comment]
hm, well, add a separate table baking procedure to kitchen? Maybe a few hours?

**Comment by lwtchu** [comment]
@LostMojo hmmm okay how much work would it take to just take the whole thing (figure number, caption, title) and move to the top - is that faster. we could do that.
