### ISSUE TITLE
finance - calculator buttons/functions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3684]
# Primary
`span class="primary-function"`
font: courier prime
weight: regular, 400
size: font-scale(0): 9pt, 12px, 1r em
font color: B5: `#D6D9DD`
text background color: B2: `#344456`

# Secondary
`span class="secondary-function"`
font: courier prime
weight: regular, 400
size: font-scale(0): 9pt, 12px, 1rem
text color: B2: `#344456`

**Comment by LostMojo** [comment]
Where is the calculator used? Is it a table (as suggested in the finance epic?)?

**Comment by lwtchu** [comment]
@LostMojo  there's tables but these are `<span>` tags. there should be some in Net Present Value (NPV) Calculation

**Comment by LostMojo** [comment]
Added in #3814
