### ISSUE TITLE
sociology 3e - lists booping outside of margins

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3688]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know

![Screen Shot 2021-03-12 at 9 11 34 AM](https://user-images.githubusercontent.com/11299125/110959181-0f586280-8313-11eb-8951-d9aad43166d2.png)

# Acceptance Criteria
The dots are move in. I think it's the same padding issues as before, it's just not caught in tables for Sociology.

# Bug Location(s)
collection ID: col11762
server: production or katalyst01
chapter/section:  chapater 2. look for table 2.2
surrounding text:

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-18 16-11-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/743e3326-b497-4d46-b035-a47a8aad834b)
