### ISSUE TITLE
psychologia: link out of the note 

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3694]
When link is very long it goes out of the note:

**Psychologia, module 12.5**
![image](https://user-images.githubusercontent.com/40228854/111178856-d4249080-85ab-11eb-850f-3eec1b0648b2.png)

**Comment by wilkus27** [comment]
### Information for tester

Fix for that affect all books from all thems. Please test one or two more books to check if everything is ok.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-18 15-01-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fed2b5a2-cb96-4df5-86b2-911b8c3747d5)

**Comment by MartaSztuka** [comment]
###### World History![Screenshot from 2021-03-19 12-17-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d3a52527-05d3-4afb-8592-0bfa8a0fb5e8)
###### Introduction to Sociology![Screenshot from 2021-03-19 12-18-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/610384a8-1d97-439a-8174-d7fa4e9ff0df)
