### ISSUE TITLE
Psychologia: page break after table title

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3695]
The markup for tables with titles in polish Psychology is different than for top titled tables in American books. There is a page break rule needed to be added for the table title:   
![image](https://user-images.githubusercontent.com/55203598/111180868-b6f0c180-85ad-11eb-9f89-d5f948f9d8de.png)
![image](https://user-images.githubusercontent.com/55203598/111181234-0d5e0000-85ae-11eb-879c-b13dbb87bce0.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-18 15-04-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c7d958bf-4f03-48e8-b471-98694030b2cf)
