### ISSUE TITLE
finance - stepwise lists

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3701]
<img width="739" alt="Screen Shot 2021-03-15 at 2 00 45 PM" src="https://user-images.githubusercontent.com/11299125/111206808-dd573280-8596-11eb-9ce6-666cefdde9d6.png">

```
<list list-type="enumerated" number-style="arabic" class="stepwise">
     <item>Lorem ipsum<item>
     <item>Lorem ipsum</item>
     <item>Lorem ipsum</item>
</list>
```

- Might have multiple paras or math under each `<item>`
- The "Bullets" are the words "Step 1." - I assume you just add the word "Step" into a numerated list.
- "Number" is bold
- Font for entire thing is the same as base font (noto sans, font-scale(0), black `#000000`)
- Make sure paragraphs start where the text starts and not where the bullet starts

**Comment by LostMojo** [comment]
Added in #3814
