### ISSUE TITLE
psychologia: align lists in tables

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3707]
Lists in tables need margin:

![image](https://user-images.githubusercontent.com/40228854/111278689-201e1680-863a-11eb-8c18-eefe21ec8d61.png)

**Comment by lwtchu** [comment]
similar issue for sociology here #3688

**Comment by wilkus27** [comment]
It should be fixed by https://github.com/openstax/cnx-recipes/pull/3708. I will move it to tests.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-03-18 15-07-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/69fcdedc-4609-4565-ae07-b428af9d9123)
