### ISSUE TITLE
psychologia: style lists in EOC

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3709]
Lists from EOC sections should be aligned to the right.

![image](https://user-images.githubusercontent.com/40228854/111288333-5bbdde00-8644-11eb-91d8-d00a43005aa1.png)

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-03-18 13-04-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7d932dd1-7477-4b98-b12a-4fd0b78218d6)
