### ISSUE TITLE
Answer Key falls on even page

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#3719]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ x] styles [ ] both [ ] i don't know

# Acceptance Criteria
I believe it should fall on an odd page as other chapters/appendices do 
# Bug Location(s)
collection ID: col12087
server: prod
chapter/section:  Answer Key
surrounding text: Answer Key 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by ajluk** [comment]
@lwtchu I've fixed this issue, but this is library wide, could you advise which books should be tested within this issue? 
In carnival theme Answer Key have such books: Chemistry, University Physics, Fizyka, Microbiology. 
In corn: Camculus, Prealgebra, Algebra Trigonometry, Precalculus, College Algebra, CA Coreq
In cardboard: Business Ethics, Business Law, Accounting
In cosmos: Sociology, American Government, Economy, History.
I have also found out that this problem also appeared for Bibliography/References - should they also appeared on the right page?

**Comment by lwtchu** [comment]
@ajluk yes re: the bibliography/references

the high prio books at the moment are: CA coreq, sociology, and history  - would y'all be interested in testing fizyka?

**Comment by ajluk** [comment]
@lwtchu Thank you! I will create separate issue/pr for Bibliography/References in this case. Regarding testing Fizyka I thin yes.

**Comment by ajluk** [comment]
@MartaSztuka Within testing this issue please check the books from Larissa's comment above ^^ (College Algebra Coreq, Sociology, History, Fizyka).  :relaxed:

**Comment by MartaSztuka** [comment]
#### PASSED
##### Microbiology ![Screenshot from 2021-03-29 15-06-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6928c92f-5db9-4c42-9620-49bd1f36e420)
##### College Algebra Coreq ![Screenshot from 2021-03-29 15-39-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/03ac004b-19fe-4f6b-9d5d-66276f023f8f)
##### Sociology ![Screenshot from 2021-03-29 16-09-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b770d570-54eb-40fa-920c-b96648361967)
##### History ![Screenshot from 2021-03-29 16-42-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b3c9030b-5eaf-46fb-8411-09ef86b0b2d8)

**Comment by MartaSztuka** [comment]
##### @ajluk fizyka still has Answer Key on even page
##### Fizyka vol 1 ![Screenshot from 2021-03-29 17-40-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e2003a79-c56a-4051-ac8e-987e77b23870)

**Comment by MartaSztuka** [comment]
#### PASSED
##### Fizyka 1
![Screenshot from 2021-04-09 11-46-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3fc89fb3-74cd-48cc-97a1-285b69f93271)
##### Fizyka 2
![Screenshot from 2021-04-09 12-05-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ea9cbd57-d73b-47df-92ea-938b809f4f82)
##### Fizyka 3
![Screenshot from 2021-04-09 12-34-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/df20a926-0125-4521-9b9e-cfc061d16711)
##### Microbiology
![Screenshot from 2021-04-09 11-44-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e60a90c7-8e48-4ba5-8428-14b1985bbbd2)
##### College Algebra Coreq
![Screenshot from 2021-04-09 11-45-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/93a2492b-a865-421c-b992-80918f3b4263)
##### Sociology
![Screenshot from 2021-04-09 12-02-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/36e57b55-cc20-4614-8058-83cab5913a87)
##### History
![Screenshot from 2021-04-09 12-35-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/847f26c8-410a-4970-8279-45ab6527621a)
