### ISSUE TITLE
Contents page number wrapping to new line with long chapter title

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#3720]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know

![Screen Shot 2021-03-18 at 3.28.12 PM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/aa51f5e5-73df-41bb-8ca4-782a88e6b158)

# Acceptance Criteria
Maybe the body text should be 9 like it is everywhere else which would allow enough room for this to not happen 

# Bug Location(s)
collection ID: col12087
server: Prod
chapter/section:  Contents
surrounding text: 12.3 Whole Genome

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by ajluk** [comment]
@lwtchu I have tried few solutions which comes to my mind here:
1. Decrease the section links and page numbers `font-size` and `line-height` property values from font-scale(1), line-height(1) to 0 as it was suggested in the issue description. Here is the sample:
![image](https://user-images.githubusercontent.com/55203598/112146589-0e111a80-8bdc-11eb-9862-904cca0a4f9c.png)
2.Decrease the Toc page `margin-right` property value from in to 0.75in (this was the widest possible value for the page number to fit in the line). Here is how it looks then: 
![image](https://user-images.githubusercontent.com/55203598/112146197-9511c300-8bdb-11eb-9a18-4962d5b27ead.png)
3.Decrease the page number `margin-left` property value from 3rem to 1rem. Here how the toc looks then: 
![image](https://user-images.githubusercontent.com/55203598/112146336-bf638080-8bdb-11eb-8e20-4874df73d31c.png)

Let me know which option is the most accurate in your opinion. :slightly_smiling_face:  Also these changes are theme wide (they can be applied also to one book if it is necessary).

**Comment by lwtchu** [comment]
@ajluk i THINK they are supposed to be font-size(0) 🤔 and at some point it changed.

can we do option 1 for right now?

**Comment by ajluk** [comment]
@lwtchu Hmm, that's interesting :thinking: I will implement option 1 (I have also checked other solutions because the font-size(0) seemed small for me :smile:

**Comment by lwtchu** [comment]
@ajluk thank you :joy: i have on a list soemwhere to build out documentation cards for the carnival theme

**Comment by ajluk** [comment]
@lwtchu should Marta test more books from carnival theme within this issue than just Microbilogy?

**Comment by lwtchu** [comment]
@ajluk we can test just microbio

**Comment by MartaSztuka** [comment]
#### PASSED
##### Microbiology![Screenshot from 2021-04-08 14-52-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7fa59026-0912-4e30-a816-5f7c44607264)
