### ISSUE TITLE
tiny charts and maps

### ISSUE THREAD

**Issue by Jacqueline-Yarbrough** [openstax/cnx-recipes#3722]
# Figures of charts and/or graphs are much smaller than ideal; several maps are illegible. Figures of photos are sized normally. 
These figures look fine online, but are too small for print. I generated a pdf of this book in CORGI at 11:27am for reference.

What kind of issue is this? [ ] recipe [ ] styles [ ] both [X] i don't know

![Screen Shot 2021-03-19 at 12.03.21 PM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/6c921480-81c5-4432-89b0-5e8013f0a2df)

![Screen Shot 2021-03-19 at 12.02.45 PM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/b0e8bd9f-efad-4578-b835-cb7e6c0de421)

# Bug Location(s)
collection ID: col11740
server: production
chapter/section: throughout text
surrounding text:

**Comment by Jacqueline-Yarbrough** [comment]
@lwtchu there aren't any size restrictions on these figures in the content

**Comment by lwtchu** [comment]
@Jacqueline-Yarbrough for these two can you download the originals and open them in photoshop and inspect the size pls :)

**Comment by lwtchu** [comment]
Determined from other titles that it's an old image export issue. We've been contracting vendor to reexport.
