### ISSUE TITLE
finance - R code snippet

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3725]
This uses the class `r`? Let me know if we should change it.

Can you tell me the list of classes that highlight.js puts on the text so I can assign color? 

Thanks!

**Comment by LostMojo** [comment]
I'm not seeing any classes besides `class="r"`, the code blocks appear as <pre></pre> with a couple of spans acting as newlines thrown in between bits of code.

Also I'm guessing that these shouldn't end with a `<div class="not-converted-yet">`?

![Screen Shot 2021-03-22 at 5 03 50 PM](https://user-images.githubusercontent.com/5740972/112064283-b8cbff00-8b30-11eb-8714-1a810a9f57ba.png)

Is this a known bug?

**Comment by lwtchu** [comment]
Putting notes here:

Changed teh content to have class="language-r" or lang="r"?  NOt sure which one will work.

**Comment by lwtchu** [comment]
- hljs-comment - R1: `#CC0000`
- hljs-built_in - Grey 5: `#5C5C5C` 
- hljs-number -  G2 `#18775D`
- hljs-literal -  B7: `#2E3092`

font for everything: courier prime
color for regular text: black `#000000`
snippet background: white `#ffffff`
