### ISSUE TITLE
CLEAN UP: refactor appendix in Carnival Theme

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3735]
- [x] In Carnival Theme appears Glossary Appendix. There should be created components and shape for it, similar to these from Cosmos theme: https://github.com/openstax/cnx-recipes/pull/3704/commits/a0bb30c9159d5ccf027befaa726c936e8ecaf5da.
- [x] Shape should be applied only to books where Glossary Appendix exists.
- [x] All old Appendix components should be removed.

**Comment by ajluk** [comment]
@MartaSztuka within this issue one book from carnival theme with "regular" Appendix need to be tested (f.ex University Physics could be the best pick, because it was in revision) and the one with Appendix Glossary (Microbiology) + you can check one of our Fizyka.

**Comment by MartaSztuka** [comment]
#### PASSED
##### University Physics 1![Screenshot from 2021-04-02 14-46-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f6b04e54-2e3c-4f83-a738-d7e2c9ba7789)
##### Microbiology
![Screenshot from 2021-04-02 14-47-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ac464049-b681-47f2-a354-5f1b9640b102)
##### Fizyka vol 1![Screenshot from 2021-04-02 15-15-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/86a3219a-2a33-4814-b3f5-2781320bf78a)
