### ISSUE TITLE
Fizyka - regression testing

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#3736]
##### 1. Equations, top margine is missing, vol 1
![Screenshot from 2021-03-24 14-25-51](https://user-images.githubusercontent.com/47241114/112318000-e0e06d00-8cac-11eb-8d9d-f79b3b171709.png)
##### 2. Column overlap side bar (long equation) vol 1
![Screenshot from 2021-03-24 14-27-17](https://user-images.githubusercontent.com/47241114/112318190-0f5e4800-8cad-11eb-892f-43085ef3fbeb.png)
##### 3. List stick out vol 1
![Screenshot from 2021-03-24 14-29-57](https://user-images.githubusercontent.com/47241114/112318578-78de5680-8cad-11eb-9e9e-29e0cb0162fc.png)
##### 4. Long equation in EoB vol 1
![Screenshot from 2021-03-24 14-35-26](https://user-images.githubusercontent.com/47241114/112319315-3b2dfd80-8cae-11eb-80f8-18475e450c88.png)

**Comment by ajluk** [comment]
@MartaSztuka the first issue I guess is a content one, but I'm not sure: 
![image](https://user-images.githubusercontent.com/55203598/112328429-9c59cf00-8cb6-11eb-8bfd-6791fd0064d1.png)
There is only a text node which doesn't have a margin. Maybe these text should be changed to paragraph
Number 3 and 4 both concern long equations, which I guess van be break in the content as well. 
I have also opened a working card for number 3: #3737

**Comment by wilkus27** [comment]
@MartaSztuka Can you check during testing https://github.com/openstax/recipes/issues/179 if these problems still occur?

**Comment by MartaSztuka** [comment]
#### PASSED
###### 1
![Screenshot from 2021-12-16 14-00-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5e870c11-54c5-48d4-bdff-24a234d7a208)
###### 2
![Screenshot from 2021-12-16 14-05-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/35b1b3e3-e8dd-4a17-bac6-cc9a7d2396f5)
###### 3
![Screenshot from 2021-12-16 14-06-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d1b2bba4-9e1e-449e-b72e-b872ddc780f4)
###### 4
![Screenshot from 2021-12-16 14-08-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bb9467b6-b395-4669-87d0-5d393d0b10fb)
###### 5
![Screenshot from 2021-12-16 14-11-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c5a85e50-86bf-4698-bf66-430642e83f4e)
