### ISSUE TITLE
microbiology: style equations

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3741]
All equations with `data-type="equation"` should be centered. They are aligned to the left now:

![image](https://user-images.githubusercontent.com/40228854/112341278-90bfd580-8cc1-11eb-9661-5778dfb17dc8.png)

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-03-30 10-05-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a5307075-2f3e-4d31-a24e-629f0e768bb6)
