### ISSUE TITLE
computer science - splash image

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3743]
Documentation: #2642
Blue version

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-04-12 at 9 23 00 AM](https://user-images.githubusercontent.com/24909007/114410121-b7f71d80-9b70-11eb-8533-59a52a352b9c.png)
![Screen Shot 2021-04-12 at 9 23 08 AM](https://user-images.githubusercontent.com/24909007/114410141-bc233b00-9b70-11eb-9a56-77ac3853f929.png)
