### ISSUE TITLE
computer science - learning objectives

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3748]
![Screen Shot 2021-03-24 at 1 01 21 PM](https://user-images.githubusercontent.com/11299125/112361115-0cf5f100-8ca1-11eb-883e-85df957685b2.png)
Documentation #2711
Blue version - numbering is slightly different. See World History or Calculus for numbering.

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-04-12 at 4 42 29 PM](https://user-images.githubusercontent.com/24909007/114466419-168ebc80-9bae-11eb-87d7-3a899d598de0.png)

**Comment by MartaSztuka** [comment]
#### PASSED
##### BCA
![Screenshot from 2021-05-07 11-57-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f485e729-4fc4-41c4-830b-67f96137f1f8)
##### Computer Science
![Screenshot from 2021-05-07 12-36-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/db49d7df-2cdc-4be1-a1cb-80df0aad8e4c)
