### ISSUE TITLE
computer science - tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3749]
Documentation #2741

Can we make sure the default, top-titled and text-heavy tables are enabled

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-04-08 at 11 53 09 AM](https://user-images.githubusercontent.com/24909007/114066148-02228b00-9861-11eb-8687-2aec4835f792.png)
![Screen Shot 2021-04-08 at 11 52 42 AM](https://user-images.githubusercontent.com/24909007/114066150-02bb2180-9861-11eb-9f68-ec59e2c05678.png)
![Screen Shot 2021-04-08 at 11 54 32 AM](https://user-images.githubusercontent.com/24909007/114066560-7826f200-9861-11eb-9a07-5904b7b8b7a9.png)

**Comment by brittany-johnson** [comment]
I didn't see the `top-titled` class in the content
