### ISSUE TITLE
computer science - python code snippets

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3750]
So there will be two approaches to this:

# Inline code call out
???? threw it in both a code and a note tag just to test. i think it'll work.

# Code tag, no class - keeps spacing, can put colors wherever you want
This will use the note tag with the `class="code"` 

# Background color
Grey1: `#F9F9F9`

## Font specs
font style: courier prime
font size: scale(0) 9pt

## Colors
`<span class="green-code">` = G2 `#18775D`
`<span class="purple-code">` = P3: `#9028A3` 
`<span class="gray-code">` = Grey 5: `#5C5C5C`
`<span class="red-code">` = R1: `#CC0000`
`<span class="blue-code">` = B7: `#2e3092`
`<span class="brown-code">` =  BR1: `#A35200`

# Code tag with python class - spacing and auto colors

## Font specs
font style: courier prime
font size: scale(0) 9pt

## Colors
Colors: https://highlightjs.readthedocs.io/en/latest/css-classes-reference.html 
`hljs-comment` = G2 `#18775D`
`hljs-keyword` = P3: `#9028A3` 
`hljs-function` = black `#000000`
`hljs-title` = Grey 5: `#5C5C5C`
`hljs-params` = black `#000000`
`hljs-string` = R1: `#CC0000`
`hljs-built_in` = B7: `#2e3092`
`hljs-number` =  BR1: `#A35200`

From Grace: Color the code:
Comments: green
Commands: purple
Strings: red
Variables: blue
Numbers: Brown

This uses the class `python` or `lang="python"` with the `display="block"` attribute to have it space out correctly.

**Comment by brittany-johnson** [comment]
`data-lang="python"` is working - but the snippet has to also be wrapped in the `pre` tag. For example: 

<code class="python" data-lang="python">
  <pre>
      blah blah blah 
  </pre>
</code>

Without it, it looks like this: 
![Screen Shot 2021-04-13 at 12 27 03 PM](https://user-images.githubusercontent.com/24909007/114595094-9fabff00-9c53-11eb-9480-f15fc3c37df4.png)

Instead of this: 

![Screen Shot 2021-04-13 at 12 28 01 PM](https://user-images.githubusercontent.com/24909007/114595183-b4889280-9c53-11eb-9578-55b4438c5576.png)

**Comment by lwtchu** [comment]
MAKING GLOBAL NOTE REMINDER for anyone whwo is looking: code snippets wont work if theyre nested in a para well they would but look like that ^^ 

if you want it to display like a block, un nest and add a display=block attribute on the boi

**Comment by brittany-johnson** [comment]
**List of highlight classes:** 
`hljs-comment`
`hljs-keyword`
`hljs-function`
`hljs-title` 
`hljs-params`
`hljs-string`
`hljs-built_in`
`hljs-number`

**Comment by lwtchu** [comment]
`hljs-comment` = P3: `#9028A3`
`hljs-keyword` = G2 `#18775D`
`hljs-function` = black `#000000`
`hljs-title` 
`hljs-params`
`hljs-string` = B7: `#2e3092`
`hljs-built_in`
`hljs-number`

**Comment by brittany-johnson** [comment]
<img width="525" alt="Screen Shot 2021-04-14 at 5 54 17 PM" src="https://user-images.githubusercontent.com/24909007/114795652-b1290000-9d54-11eb-9d4d-91f33a7f2b71.png">
<img width="541" alt="Screen Shot 2021-04-14 at 5 54 10 PM" src="https://user-images.githubusercontent.com/24909007/114795655-b25a2d00-9d54-11eb-9463-1f3753410987.png">
<img width="573" alt="Screen Shot 2021-04-14 at 5 54 05 PM" src="https://user-images.githubusercontent.com/24909007/114795656-b38b5a00-9d54-11eb-81c6-101645486db5.png">

**Comment by brittany-johnson** [comment]
Screenshots for `Code tag, no class - keeps spacing, can put colors wherever you want` :

![Screen Shot 2021-04-19 at 10 09 25 AM](https://user-images.githubusercontent.com/24909007/115259367-6feb7400-a0f7-11eb-8a0d-e19889b68010.png)
![Screen Shot 2021-04-19 at 10 09 52 AM](https://user-images.githubusercontent.com/24909007/115259373-71b53780-a0f7-11eb-85d1-3cf9bd44063c.png)
