### ISSUE TITLE
computer science - math type font and styles

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3752]
There is some color math in this book, it should be set in the content. So if you see it, do not be alarmed.

Question - is there an existing monotype space font and what would it take to change only this book's math type to that font.

**Comment by brittany-johnson** [comment]
<img width="525" alt="Screen Shot 2021-04-14 at 5 54 17 PM" src="https://user-images.githubusercontent.com/24909007/114790484-74580b80-9d4a-11eb-8ad2-f5d1adb6ba9f.png">
<img width="541" alt="Screen Shot 2021-04-14 at 5 54 10 PM" src="https://user-images.githubusercontent.com/24909007/114790488-7621cf00-9d4a-11eb-9e61-39df2a131fc5.png">
<img width="573" alt="Screen Shot 2021-04-14 at 5 54 05 PM" src="https://user-images.githubusercontent.com/24909007/114790491-76ba6580-9d4a-11eb-95ec-0493a42ee6d4.png">

**Comment by brittany-johnson** [comment]
The font size is very small but confirmed that the color and font family are coming through 
<img width="486" alt="Screen Shot 2021-04-14 at 7 08 29 PM" src="https://user-images.githubusercontent.com/24909007/114795708-dc135400-9d54-11eb-85be-3b999260dca6.png">
