### ISSUE TITLE
computer science - middle header row

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3753]
Similar functionality to #3665
The row has a class on it `<row class="header-row">`

Uses #2741 specs for Second Header row (if present)

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-04-12 at 3 23 02 PM](https://user-images.githubusercontent.com/24909007/114456971-1c32d500-9ba3-11eb-86b1-68e4f5fe882d.png)
![Screen Shot 2021-04-12 at 3 23 31 PM](https://user-images.githubusercontent.com/24909007/114456972-1dfc9880-9ba3-11eb-8346-f517fc786083.png)
