### ISSUE TITLE
computer science - concepts in practice

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3755]
- Documentation #2737
- color option 2
- Class: `<note class="concepts-practice">`
- title: Concepts in Practice

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-04-06 at 3 02 30 PM](https://user-images.githubusercontent.com/24909007/113771579-29eee300-96e9-11eb-9ec7-2dd35ad4da90.png)
