### ISSUE TITLE
computer science - link to learning

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3756]
- Documentation #2737
- color option 1
- Class: `<note class="link-to-learning">`
- title: Link to Learning

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-04-06 at 3 17 15 PM](https://user-images.githubusercontent.com/24909007/113773122-3116f080-96eb-11eb-837a-3a0e7b5d86a8.png)
