### ISSUE TITLE
computer science - global issues in technology

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3757]
- Documentation #2737
- color option 3
- Class: `<note class="global-tech">`
- title: Global Issues in Technology

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-04-06 at 3 49 23 PM](https://user-images.githubusercontent.com/24909007/113776658-c0be9e00-96ef-11eb-88f2-58a70ff806df.png)
