### ISSUE TITLE
computer science - industry spotlight

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3759]
- Documentation #2737
- color option 5
- Class: `<note class="industry-spotlight">`
- title: Industry Spotlight
- Contains an exercise called Your Turn
- has a class `your-turn` 
- title "Your Turn" and "Solution" title should be just base font, but bold.
<img width="671" alt="Screen Shot 2021-03-24 at 4 02 52 PM" src="https://user-images.githubusercontent.com/11299125/112382902-6dddf300-8cba-11eb-896f-f60fa978f26a.png">

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-04-07 at 2 19 34 PM](https://user-images.githubusercontent.com/24909007/113921946-4c960000-97ac-11eb-8852-3160fd65d5f9.png)
