### ISSUE TITLE
computer science - technology in everyday life

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3760]
- Documentation #2737
- color option 3
- Class: `<note class="tech-everyday">`
- title: Technology in Everyday Life
- Like #3757 - contains an exercise called Your Turn
- has a class `your-turn` 
- title "Your Turn" and "Solution" title should be just base font, but bold.
<img width="671" alt="Screen Shot 2021-03-24 at 4 02 52 PM" src="https://user-images.githubusercontent.com/11299125/112382902-6dddf300-8cba-11eb-896f-f60fa978f26a.png">

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-04-07 at 2 26 41 PM](https://user-images.githubusercontent.com/24909007/113922746-4a807100-97ad-11eb-9ed0-794120a4291a.png)

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-04-07 at 2 31 31 PM](https://user-images.githubusercontent.com/24909007/113923376-178aad00-97ae-11eb-8fa9-91257c62975e.png)
