### ISSUE TITLE
References/Bibliography falls on even page

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3764]
References/Bibliography placed in the EoB part should also appear on the right page. 
How it looks now in Psychology 2e: 
![image](https://user-images.githubusercontent.com/55203598/112508812-2d50a900-8d90-11eb-94f0-4a695c7b62a3.png)
In Psychologia:
![image](https://user-images.githubusercontent.com/55203598/112508919-49544a80-8d90-11eb-925f-c423e5181db2.png)
Economy2e (here the page side is correct, but when the changes made for the Answer Key from this PR( #3733) will be merged it will display on the left side):
![image](https://user-images.githubusercontent.com/55203598/112509985-4ad24280-8d91-11eb-930c-82ffc0fde363.png)
This problem also occurs in books from carnival theme: Anatomy:
![image](https://user-images.githubusercontent.com/55203598/112510112-6b9a9800-8d91-11eb-9f8f-029089a6b8c9.png)

**Comment by MartaSztuka** [comment]
#### PASSED
##### Anatomy ![Screenshot from 2021-03-30 12-11-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/41905b1f-1339-4397-9e43-842664c68114)
##### Economics 2e![Screenshot from 2021-03-30 11-46-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3cf47196-7332-4131-9509-abef312315d1)
##### Psychologia ![Screenshot from 2021-03-30 13-37-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4bca009b-f42c-4632-9093-9d4600542c0b)
##### Psychology 2e ![Screenshot from 2021-03-30 13-53-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ca7538f1-57a6-4ea3-98b2-65b31608ec12)
