### ISSUE TITLE
computer science - eoc assessment questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3766]
There are 7 sections that all basically look the same.
![image](https://user-images.githubusercontent.com/11299125/112520529-83f6bc80-8d69-11eb-9b23-4cc3cbbed802.png)

- standard multiple choice exercise and will be pulled from exercises.tutor.org
- exercise number is bolded with period
- spacing between each exercise is the same as business ethics: 0.7rem
- numbering is 1, 2, 3, etc and continuous for the chapter

# Review Questions `review-questions`
icon: https://drive.google.com/file/d/1Ltc0whfkE49KScYfgJ_72T7f99_T7Brk/view?usp=sharing
title: Review Questions

# Conceptual Questions `conceptual-questions`
icon: https://drive.google.com/file/d/1-IA4Gbm1OlPC2bg8lSedIUUIrjvZdBrB/view?usp=sharing
title: Conceptual Questions

# Practice Exercises `practice-exercises`
icon: https://drive.google.com/file/d/1U32rkP-W_UuQ0Va5PLUIhFEGkztm9CVk/view?usp=sharing
title: Review Questions

# Problem Set A `problem-set-a`
icon: https://drive.google.com/file/d/1LxWsRljZtkKxBDxQQOgFbrvtDRevOc2D/view?usp=sharing
title: Problem Set A

# Problem Set B `problem-set-b`
icon: https://drive.google.com/file/d/1-pbKFNu3ZWzyDYsEjfX0gMnUb_MeYWhh/view?usp=sharing
title: Problem Set B

# Thought Provokers `thought-provokers`
icon: https://drive.google.com/file/d/1lVezUadPa780bzW-XuOYTP_kbmi0_UmO/view?usp=sharing
title: Thought Provokers

# Labs `labs-assessments`
icon: https://drive.google.com/file/d/14brT2QhTuydTya8rrokTE6dYFu5kcsZS/view?usp=sharing
title: Labs

**Comment by brittany-johnson** [comment]
<img width="802" alt="Screen Shot 2021-04-14 at 5 19 30 PM" src="https://user-images.githubusercontent.com/24909007/114787715-d82c0580-9d45-11eb-8919-722fef541b55.png">
<img width="814" alt="Screen Shot 2021-04-14 at 5 19 36 PM" src="https://user-images.githubusercontent.com/24909007/114787736-de21e680-9d45-11eb-9492-4772e8e49e50.png">
<img width="796" alt="Screen Shot 2021-04-14 at 5 19 43 PM" src="https://user-images.githubusercontent.com/24909007/114787755-e5e18b00-9d45-11eb-9d18-f903e9888640.png">
<img width="745" alt="Screen Shot 2021-04-14 at 5 19 48 PM" src="https://user-images.githubusercontent.com/24909007/114787767-eb3ed580-9d45-11eb-94f0-a3fa5e095db9.png">
<img width="784" alt="Screen Shot 2021-04-14 at 5 19 53 PM" src="https://user-images.githubusercontent.com/24909007/114787789-f42fa700-9d45-11eb-8c83-6747c4ea1ebf.png">
