### ISSUE TITLE
Add PL Psychology to Kitchen

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3767]

**Comment by wilkus27** [comment]
### Intentionally differences between old and new recipe

1. Remove dots from chapter numbers
2. Remove paragraphs from lists items
3. Remove id from `os-caption` in figures
4. Different ids for terms (in old recipe terms were counted first, then baked; in new recipe they are counted after baking, also terms from composite pages are counted separately)

**Comment by lwtchu** [comment]
@wilkus27 i know marta is out - but is this ready to close or should i move to a later milestone since she might be still testing?

**Comment by wilkus27** [comment]
@lwtchu Can we move this to the next milestone? As we know Marta tested it briefly before she went on vacations, but probably she will do more in-depth tests when she's back.

**Comment by lwtchu** [comment]
I moved it :) Thanks for the update.
