### ISSUE TITLE
BCA - link to learning

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3773]
- Documentation #2737
- color option 1
- Class: `<note class="link-to-learning">`
- title: Link to Learning

**Comment by ajluk** [comment]
@lwtchu In one of the link to learning notes in section 1.2 there are figures present but no link, would you like to fix this in content?: 
![image](https://user-images.githubusercontent.com/55203598/114056319-d53a9c00-9891-11eb-8043-c8f087e9b232.png)

**Comment by lwtchu** [comment]
@ajluk oh thank you! no it's okay - just fyi this module is where the vendor is testing images on backgrounds so link to learning had the light grey background

**Comment by ajluk** [comment]
Oh, thank you for the information, that's interesting!

**Comment by lwtchu** [comment]
big card was closed out, closing these little ones too
