### ISSUE TITLE
BCA - checkpoint

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3774]
- Documentation #2737
- color option 5
- Class: `<note class="check-point">`
- title: Checkpoint
- Includes an exercise

**Comment by ajluk** [comment]
@lwtchu The checkpoint note was numbered in Calculus, should it be also numbered in this book? Should the exercises and solutions in this note be also numbered as it was done in calculus and moved to the Answer Key. With default note config settings added there they look line this: 
![image](https://user-images.githubusercontent.com/55203598/113909611-27b78200-97d8-11eb-8865-078b2918ba70.png)

**Comment by lwtchu** [comment]
@ajluk the splash classes should be added and i'll edit the main card to say there is no answer key

**Comment by lwtchu** [comment]
<img width="784" alt="Screen Shot 2021-04-07 at 2 29 36 PM" src="https://user-images.githubusercontent.com/11299125/113923052-b4007f80-97ad-11eb-8aad-658203b01a2e.png">
Can we have it be unnumbered and look something like this?

**Comment by ajluk** [comment]
@lwtchu Ok! Could there be added unnumbered class in to content to `[data-type="exercise"]` element?: 
![image](https://user-images.githubusercontent.com/55203598/113986273-5c195580-984d-11eb-8052-1d897d31947f.png)

**Comment by lwtchu** [comment]
@ajluk sure thing ! just added it.

**Comment by ajluk** [comment]
How it looks: 
![image](https://user-images.githubusercontent.com/55203598/114069698-91e72a00-989f-11eb-84a8-49b1916e16be.png)

**Comment by lwtchu** [comment]
this looks good thank you :eyes:
