### ISSUE TITLE
BCA - learning objectives

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3789]
![Screen Shot 2021-03-24 at 1 01 21 PM](https://user-images.githubusercontent.com/11299125/112361115-0cf5f100-8ca1-11eb-883e-85df957685b2.png)
Documentation #2711
Blue version - numbering is slightly different. See World History or Calculus for numbering.

**Comment by ajluk** [comment]
@lwtchu Here is how it looks:
![image](https://user-images.githubusercontent.com/55203598/114061884-31ec8580-9897-11eb-952b-e124afa48e42.png)
**Specs added**:
![image](https://user-images.githubusercontent.com/55203598/114062065-6102f700-9897-11eb-9959-07c20ff95327.png)
**Numbered Token**
font-weight: bold,
margin-right: h-spacing(1) - 8px
Should I change something?

**Comment by ajluk** [comment]
I have also removed bottom margin, which was inherited form other H3 title, is it look better or should the margin be there?: 
![image](https://user-images.githubusercontent.com/55203598/114062691-1635af00-9898-11eb-9a70-2a8606f0eca6.png)

**Comment by lwtchu** [comment]
@ajluk i think removed looks better :eyes:

**Comment by lwtchu** [comment]
big card was closed out, closing these little ones too
