### ISSUE TITLE
BCA - tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3790]
Documentation #2741

Can we make sure the default, top-titled and text-heavy tables are enabled

**Comment by ajluk** [comment]
@lwtchu I have a question about this table: 
![image](https://user-images.githubusercontent.com/55203598/114206287-79d4e080-995b-11eb-89e4-f6beeb8cab5e.png)
It is a defult table without any specific class. As you can see on the screenshpt from above It doesn't have the top border, the reason for that is that there is not `thead` there, only `tbody`: 
![image](https://user-images.githubusercontent.com/55203598/114206667-dc2de100-995b-11eb-9c47-771f31a81ad7.png)
Will there be such tables and this need a fix? Or this is a content issue/test issue?

**Comment by lwtchu** [comment]
@yblock can you put theads on the headers of the tables? and in table 1.7 the "Frequency of reports" should be the middle header row.

**Comment by yblock** [comment]
Changes have been made

**Comment by lwtchu** [comment]
big card was closed out, closing these little ones too
