### ISSUE TITLE
cardboard: Top Titled and Default Tables without `thead` are missing top border 

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3816]
The first header row td is missing top border, when `top-titled` and `default` tables don't have `thead`: see https://github.com/openstax/cnx-recipes/issues/3790#issuecomment-816777531
Example from BCA before content update: 
![image](https://user-images.githubusercontent.com/55203598/114742494-17f5eb80-9d4c-11eb-9710-da07f6ce28c4.png)

**Comment by ajluk** [comment]
@lwtchu I have added the top borders back to first row cells in the table body, but as you can see on the screenshpt below in the first table it causes a small space between the background colored thead and the and the body row cell:
![image](https://user-images.githubusercontent.com/55203598/148096312-bdce8545-9674-4a9e-990b-690ea0834904.png)
I remember I have removed the border previously within this [PR](https://github.com/openstax/cnx-recipes/pull/3097), but I didn't predict it can have such impact. Can this be accepted?

**Comment by lwtchu** [comment]
@ajluk yes i think it's ok

**Comment by MartaSztuka** [comment]
#### PASSED
##### BCA
![Screenshot from 2022-01-05 12-33-22](https://user-images.githubusercontent.com/47241114/148214997-0c1ed8e4-1836-4416-8f5a-4236db7733b8.png)
![Screenshot from 2022-01-05 13-05-02](https://user-images.githubusercontent.com/47241114/148215004-f59c3cc5-0c4b-428a-aade-c98112952ca0.png)
![Screenshot from 2022-01-05 13-07-16](https://user-images.githubusercontent.com/47241114/148215182-d23d4255-8b65-4181-a2dc-a84f50b45c87.png)
##### Intro Business
![Screenshot from 2022-01-05 13-17-28](https://user-images.githubusercontent.com/47241114/148216474-51c92c2c-b0f0-4b4c-afd4-28aadda9b5d3.png)
![Screenshot from 2022-01-05 13-16-52](https://user-images.githubusercontent.com/47241114/148216481-f89b378b-8ac7-45ff-9298-07ac6bfe6924.png)
![Screenshot from 2022-01-05 13-19-12](https://user-images.githubusercontent.com/47241114/148216634-582482b7-baa3-42d3-b544-ea5ef489cb6d.png)
##### Astronomy
![Screenshot from 2022-01-05 13-26-53](https://user-images.githubusercontent.com/47241114/148217753-c8a502a0-b250-420b-95c8-e3a2cb2e36f7.png)
![Screenshot from 2022-01-05 13-23-02](https://user-images.githubusercontent.com/47241114/148217774-94e74fe7-c384-468e-88a5-16bc172c4083.png)
![Screenshot from 2022-01-05 13-25-15](https://user-images.githubusercontent.com/47241114/148217787-2de1995a-eaf1-4671-89c3-f9ae44ed2964.png)
