### ISSUE TITLE
contemporary math - learning objectives

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3818]
Documentation: #2190

**Comment by lwtchu** [comment]
![Screen Shot 2021-11-03 at 12 01 57 PM](https://user-images.githubusercontent.com/11299125/140121818-4815dc9f-6220-4eb5-8fce-5fc87b15e05f.png)


This isn't displaying as it should be in the recently generated PDF on CORGI 
Job: 2082

**Comment by kswanson33** [comment]
![image](https://user-images.githubusercontent.com/26280712/142071453-8b25e367-604d-4232-ae8a-d6d5625e2a79.png)
html structure of the learning objectives seems to be a bit funky. Styles expects:
1. learning objectives to be wrapped in an `<abstract>`
2. the nested list to be `ul`, not `ol`

Should this be a content fix, or should I code a workaround?

**Comment by lwtchu** [comment]
Update - request to add style functionality for the section with a class. Content also updated to have no enumerated list in tagging

**Comment by MartaSztuka** [comment]
@lwtchu there's still a problem with learning objective
##### baked locally on w.w.
![Screenshot from 2021-11-18 12-42-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/219d94d3-c032-4d5b-a879-551184ad9ee4)
![Screenshot from 2021-11-18 12-45-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f9814434-8af2-4d0d-83b4-b5cd8593d237)
##### CORGI (job 2366) 
![Screenshot from 2021-11-18 12-48-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f07fa690-6244-4e83-903a-4ed82de7c7a9)
##### CORGI (job 2371) - I've repeat job 2082 from issue description, there are errors.
![Screenshot from 2021-11-18 12-55-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c9d32303-c29c-46e5-b2a3-f105e7a11b5e)

**Comment by kswanson33** [comment]
This looks like a content issue: I can tell because the LO list is numbered in the screenshots. For my development purposes, I had Larissa change the LO list to an unnumbered list, so that styles can work.

But, the change was made on the `playground` collection, not `contemporary-math`. I haven't been able to build `contemporary-math` for a while since it breaks in the `assemble` step. Not sure how to direct you to get updated content ... :grimacing:

**Comment by lwtchu** [comment]
![Screen Shot 2021-11-19 at 10 25 32 AM](https://user-images.githubusercontent.com/11299125/142657196-f87e7073-011b-4f5e-84b2-ab19bb7c502e.png)
Verified

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5d48e64d-b25d-481c-8f1f-500653421ff2)

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5d48e64d-b25d-481c-8f1f-500653421ff2)
