### ISSUE TITLE
sociology recipe - answer key display

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3822]
# Brief Description of Change and Screenshots
What kind of change is this? [x] recipe [ ] styles [ ] i don't know

if i do not have anything in the answer key, could there be an option to have it not display a header for that chapter see here for example, this is not ideal (go to answer key): https://rex-web.herokuapp.com/books/introduction-sociology-2e@15.8/pages/chapter-11?arc[…]%2Fopenstax.org%2Fapps%2Farchive-preview%2F20210412.215425

we are trying to balance the 3e and 2e changes for sociology (we re-enabled the answer key for sociology 3e #3663) and still utilize one recipe.

based on this thread: https://openstax.slack.com/archives/CH5514N57/p1618512976008200 

# Acceptance Criteria

# Content Location(s)
collection ID: col11762
server: production
chapter/section:  answer key
surrounding text:  answer key

**Comment by lwtchu** [comment]
phil says it shsould be possible so that's..one good news.

**Comment by brittany-johnson** [comment]
Answer key should not be present in soc 2e but present in 3e. 3e content can be found on `content02 col10084 `for testing

![Screen Shot 2021-04-20 at 1 53 56 PM](https://user-images.githubusercontent.com/24909007/115449040-f8ddda80-a1df-11eb-8bf6-a36d9111e43f.png)
![Screen Shot 2021-04-20 at 1 54 09 PM](https://user-images.githubusercontent.com/24909007/115449056-fbd8cb00-a1df-11eb-8159-d939b7b203ca.png)

**Comment by lwtchu** [comment]
Need to test 1 2 3e when it goes to corgi
