### ISSUE TITLE
Sociology - Answer Key and Index in Sans Serif Font Instead of Serif

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#3841]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know

![2021-04-28_11-57-54](https://user-images.githubusercontent.com/12678235/116470269-cd3e9e00-a838-11eb-86cd-672c19becfcb.png)

# Sample mark up if applicable

# Acceptance Criteria
Font is consistent across the entire ToC

# Bug Location(s)
collection ID: col10018
server: content02
chapter/section: ToC
surrounding text: N/A

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
😬  this is intentional.
