### ISSUE TITLE
iframe embeds leave large gap in business-ethics style

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#3843]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know

![Screen Shot 2021-04-29 at 12.31.31 PM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/6019a2bd-ab1a-497c-844b-991aafa2951a)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
This happens both inside and outside of a figure.

# Sample mark up if applicable
<media id="youtube-PSFE" alt="YouTube Video: A Patent System for Everyone">
    <iframe width="660" height="371.4" src="https://openstax.org/l/PatentSystemForEveryone"/>
</media>

# Acceptance Criteria
PDF should not have large white space where the iframe would load in web 

# Bug Location(s)
collection ID: col32642
server: prod
chapter/section: 1.2 
surrounding text: face of the earth

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
I think MaryJo recently fixed this for Finance. 🤔  So might need to apply the same thing in the PDF for this style

**Comment by lwtchu** [comment]
`@include use('IFrame', 'common:::Hidden');`

**Comment by KarinaMendez2** [comment]
fixed :)
![image.png](https://images.zenhubusercontent.com/5c54789f0a972e6fd1ece1a0/739731d3-0487-4cfa-8c79-ea03ea83331e)

**Comment by Stackblocks** [comment]
Displays OK with current code and content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ff941c62-6803-42a1-91e5-f381216ed062)
