### ISSUE TITLE
Change anything targeting md:title to title

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3846]
# Brief Description of Change and Screenshots
What kind of change is this? [x] recipe [ ] styles [ ] i don't know

# Acceptance Criteria
Goal is that the md:title tag will be stripped when we move content to GitHub. We'll need to make sure anything selecting md:title just points to the title for the modules. We'll need to do this by June.

# Content Location(s)
collection ID:
server:
chapter/section: 
surrounding text: 

CM's can probably help with testing - just generate the book and make sure nothing wrong with titles.

**Comment by lwtchu** [comment]
Corresponding ce card: https://github.com/openstax/cnx/issues/1515

**Comment by brittany-johnson** [comment]
Sooo false alarm lol! This change won't create a diff in the assembled content so we don't have to update anything on our end @lwtchu. Closing since no work has to be don.
Details: https://openstax.slack.com/archives/C0LA54Q5C/p1621278066030700

**Comment by lwtchu** [comment]
cc @ne-newton turns out we don't need to do anything on our end so y'all are clear to do whatever y'all need to do for CE 8)
