### ISSUE TITLE
Fizyka: unstyled lists

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3847]
Fizyka contains lists with markup:

![image](https://user-images.githubusercontent.com/40228854/116984038-15dbd880-accb-11eb-82a6-2b6a1cdd5e55.png)

![image](https://user-images.githubusercontent.com/40228854/116984107-2db35c80-accb-11eb-8204-045b581ddf4e.png)

Title should be bold and bullets from lists should be removed.

Screenshot for reference:

![image](https://user-images.githubusercontent.com/40228854/116984391-7bc86000-accb-11eb-9c88-50e2faedf49d.png)

(All screenshots came from `pl-u-physics-vol2`)

**Comment by MartaSztuka** [comment]
#### PASSED
Content problem is described here: https://app.zenhub.com/workspaces/content-60365eeceaa1f0000e9828e8/issues/openstax-poland/content/110
##### Fizyka 1
![Screenshot from 2021-05-07 13-50-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b7a4e5b7-7024-4011-a1b8-7a8439dc6a4e)
##### Fizyka 2
![Screenshot from 2021-05-07 14-43-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/22517367-be7d-4145-97ca-334e1471fb9a)
##### Fizyka 3
![Screenshot from 2021-05-07 15-08-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2400e097-6413-4e12-a23a-7c6dbc3d23a9)
