### ISSUE TITLE
Sociology, English Comp - Splash images displaying correctly in PDF, incorrectly in XHTML

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#3849]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ x ] i don't know

![2021-05-04_10-16-29](https://user-images.githubusercontent.com/12678235/117031463-39e8eb00-acc6-11eb-98c7-812d3bd366c9.png)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?

Occurs consistently throughout

# Sample mark up if applicable
<div class="os-figure has-splash">

# Acceptance Criteria
Image sizing may be a separate issue, so for now the acceptance criteria is that the background for the image should span the full width of the page

# Bug Location(s)
collection ID: col10018
server: content02
chapter/section: 1
surrounding text: `Every day 7.5 million people use the railways`

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by Stackblocks** [comment]
This is _probably_ because the directions for handling the splash are prince-based, but I wonder if there is a way to make it work for the base content as well

**Comment by lwtchu** [comment]
Next steps: get more info about how content is ingested in other places... figure out painless way to convert non-72ppi images for screen friendly.

**Comment by lwtchu** [comment]
Not an issue. Or at least one we want to fix.
