### ISSUE TITLE
table breaking in US Population Chart appendix

### ISSUE THREAD

**Issue by Jacqueline-Yarbrough** [openstax/cnx-recipes#3852]
Appendix F: United States Population Chart is only one table, but it starts on the page after the title page, so it's just kind of goofy looking. 
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know

![Screen Shot 2021-05-06 at 4.17.45 PM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/eb9bfa15-65e1-4a79-be28-f9d6101fe554)

![Screen Shot 2021-05-06 at 4.17.55 PM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/778945d4-1d43-4868-b852-aeb00b88296b)

This is a one-off

# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID: col11740
server: production
chapter/section: Appendix F
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
@ajluk the work got merged for this right? do you think we can close

**Comment by ajluk** [comment]
Yes, that's right. I'm closing it based on your comment from above (https://github.com/openstax/cnx-recipes/issues/3852#issuecomment-949719027).
