### ISSUE TITLE
Algebra & Trig - Bold and Italic variable causing line break 

### ISSUE THREAD

**Issue by marcjeannott** [openstax/cnx-recipes#3855]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know

![Screen Shot 2021-05-07 at 9.03.17 AM.png](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/9b0ace52-585c-4067-8f07-5a5e82c53138)

This is from Corgi PDF I generated on May 6th. I believe this issue is similar to [Issue 3394](https://github.com/openstax/cnx-recipes/issues/3394)

The different variables seem to be making new lines. This may be because each has two emphasis tags (a bold and an italic) however this same thing is used in the exercises without breaking into new lines. 

# Acceptance Criteria
The variables aren't causing line breaks. 
# Bug Location(s)
Algebra and Trig PDF - 10.8 Section Exercises Folio 1013
collection ID: col11758
server: Prod
chapter/section:  10.8
surrounding text: For the following exercises, use the given vectors to compute

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
This should've been fixed with https://github.com/openstax/cnx-recipes/commit/91345794ab2edd00f74ac5ea88fa308b0f887b56  -- can we make sure it's fixed in the precal styles file also?

**Comment by lwtchu** [comment]
removing the effect="bold" will also fix it but karina and anna (karinanna :joy:) have also done the fix. need to talk to a PHILosopher of content to either validate the content better or transform it or...something else

**Comment by lwtchu** [comment]
I think this got merged - you can test when it goes to staging on corgi maybe :eyes:

**Comment by Stackblocks** [comment]
Displaying OK in updated CORGI output

![image](https://user-images.githubusercontent.com/12678235/119554367-31824e00-bd62-11eb-9b98-3ce310315447.png)
