### ISSUE TITLE
English Comp - Table Number Font

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#3861]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ x ] styles [ ] both [ ] i don't know

Table numbers in English Comp are in IBM Plex Sans [instead of Archivo](https://github.com/openstax/cnx-recipes/issues/3185)

![2021-05-14_11-31-43](https://user-images.githubusercontent.com/12678235/118305065-1afc0d00-b4ad-11eb-90bf-f555b5b3094d.png)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?

Consistent Occurrence

# Sample mark up if applicable

```
<div class="os-caption-container"><span class="os-title-label">Figure </span><span class="os-number">1.1</span><span class="os-divider"> </span><span data-type="title" id="auto_f4d4370c-dc05-4cb0-8dd1-be7b77359505_1" class="os-title"><!-- no-selfclose --></span><span class="os-divider"> </span><span class="os-caption">Long before...(Credit: N. Giovannucci).</span></div></div>

```

# Acceptance Criteria

# Bug Location(s)
collection ID: col10001
server: content06
chapter/section: 1.4
surrounding text: `A rhetorical situation occurs every time anyone communicates with anyone else.`

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-06-23 at 10 54 08 AM](https://user-images.githubusercontent.com/24909007/123129178-5d502c80-d411-11eb-8401-f3ecd4e58fa6.png)

**Comment by Stackblocks** [comment]
Table number text now in Archivo, which is good, but the space between the word "Table" and the Number is in Minion Pro. I'll bring this up in group chat and either kick it back or mark it as a non-issue / separate issue, depending.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b236d466-74da-4b0d-9ade-a1445dc6dab7)

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d6ce1848-8776-4dfc-b4a1-c97cabc8817d)

**Comment by lwtchu** [comment]
@Stackblocks found this old card https://github.com/openstax/oer.exports/issues/3311 - we can't seem to get all of them so I would say not open another card
