### ISSUE TITLE
(WEB STYLING) English Comp - Literary Narrative Trailblazer banner doesn't span the full page width in HTML view

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#3864]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ x ] styles [ ] both [ ] i don't know

![2021-05-17_15-07-39.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4a414f09-bed0-4cea-b1fb-87147e3fb0e3)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
It happens in the sole instance in the test content

# Sample mark up if applicable

# Acceptance Criteria
Banner displays properly in all versions of content

# Bug Location(s)
collection ID: col10001
server: Content06
chapter/section: All
surrounding text: Start of section

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
This  will break the PDF if we fix. Saving for web if we end up  doing it

**Comment by KarinaMendez2** [comment]
Modifying the styles for web will affect pdf

**Comment by ajluk** [comment]
@lwtchu I guess I have found a solution that could work for both pdf and webview. Here is how it looks now in pdf: 
![image](https://user-images.githubusercontent.com/55203598/135897574-a7ff2c6e-c9c7-49ca-b9f1-d26fce810bcc.png)
And here is baked.xhtml file: 
![image](https://user-images.githubusercontent.com/55203598/135897747-ddb37485-a26e-4169-8538-ac1d38ba4578.png)
I fixed it by removing the width of the title with colored bar and add minus right margin to stretch the bar but left the content in place. I have used the exact solution as I did in my old PR for Stats Lab note https://github.com/openstax/cnx-recipes/pull/2599/files (Statistics.) Let me know if this is the desired result :slightly_smiling_face:

**Comment by lwtchu** [comment]
oh nice ! what a fancy fix ~ it looks good. I'll throw it in this milestone

**Comment by MartaSztuka** [comment]
#### PASSED
tested on old content
![Screenshot from 2021-10-06 12-14-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d8473079-0efa-4e3e-b362-4bac848d98b6)![Screenshot from 2021-10-06 12-14-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cc29bdf3-5ffe-44ae-87ed-a0c1f36e8447)
