### ISSUE TITLE
English Comp - Footnote getting placed at end of call line in HTML

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#3865]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ x ] recipe [ ] styles [ ] both [ ] i don't know

![2021-05-17_10-59-28](https://user-images.githubusercontent.com/12678235/118551862-cd3d0a00-b723-11eb-8c3c-4f61dc85a22d.png)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
Consistently throughout the sample content
# Sample mark up if applicable

# Acceptance Criteria
Footnotes behave consistently between HTML and PDF

# Bug Location(s)
collection ID: Col10001
server: Content06
chapter/section: 1.2, 1.3
surrounding text: family home have had little formal education / 
authors provide specific details of the scenes and action

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/421de742-c428-4f2e-89bf-7d8f12f48200)

@Stackblocks in the PDF, the footnote is correctly positioned at the end of whichever page it falls on. Since the HTML doesn't have page breaks (and therefore no "end of page" aside from the end of the document), it isn't possible to replicate this behavior. Do you have an alternative in mind?

**Comment by Stackblocks** [comment]
That makes sense. As an alternative is there any way to treat it that will cause it to not look like it's accidentally phased between two para blocks? That may not be possible since as you said it's behavior is designed to work with concepts that simply aren't present in the webview.

As with the right boundary spillover issue, this is pretty low prio since it doesn't impact the currently visible webview or the PDF output, but is something to consider as we move forward with total content display.

**Comment by kswanson33** [comment]
It might be good to have a UI person's input on this. I assume the web view will break up the document somehow, i.e. by chapter or section? Footnotes could go at the bottom of those areas once that's set up. But that's just a suggestion.

**Comment by lwtchu** [comment]
@kswanson33 is this in the HTML view? i think REX/Tutor has something on their end to move them to the  bottom of the page
