### ISSUE TITLE
English Comp - ToC display varies between HTML and PDF

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#3866]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ x ] recipe [ ] styles [ ] both [ ] i don't know

![2021-05-17_15-09-26](https://user-images.githubusercontent.com/12678235/118552234-450b3480-b724-11eb-8520-d9832fceda5f.png)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
There is only one ToC in the book, so legally it happens 100% of the time ¯\_(ツ)_/¯

# Sample mark up if applicable

# Acceptance Criteria
ToC displays consistently between HTML and PDF

# Bug Location(s)
collection ID: Col10001
server: Content06
chapter/section: ToC
surrounding text: N/A

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by kswanson33** [comment]
This should affect all cosmos books with unit TOCs.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6fad6adc-43dc-464c-ad63-fc344990b514)
