### ISSUE TITLE
icebox bc everyone hates it. bug - <emphasis effect="bold"> should not add a data-effect="bold" attribute to the <strong> tag

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3870]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know [x] neither

#3855  brought this on - title describes what is happening.

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
Yes

# Sample mark up if applicable

# Acceptance Criteria
`<emphasis effect="bold">` should not add a `data-effect="bold"` attribute to the `<strong>` tag when it is transformed from CNXML to HTML

# Bug Location(s)
collection ID: col11758 - algebra and trigonometry is probably the easiest place to find
server: Prod
chapter/section: 10.8
surrounding text: For the following exercises, use the given vectors

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by LostMojo** [comment]
Fixed in [this PR](https://github.com/openstax/rhaptos.cnxmlutils/pull/208)

**Comment by LostMojo** [comment]
Basically, there shouldn't be a data-effect="bold" atttribute attatched to any strong tag.

Like here's the changes that happened on the tests:

![Screen Shot 2022-06-14 at 9 33 52 AM](https://user-images.githubusercontent.com/5740972/173603992-9ca50e4e-56c1-47d0-941f-6a4b36b37458.png)

Strong is still there, data-effect attribute removed.
