### ISSUE TITLE
Support embedded Iframes in Econ books (and across library)

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#3874]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [x] both [ ] i don't know

We are going to embed some interactive iframe graphs into the economics books. Here's an example: https://fred.stlouisfed.org/series/UNRATE

This is the example markup used to place the graph into the content: `<media id="123" alt="unemployment graph"> <Iframe height="475" width="670" "https://fred.stlouisfed.org/graph/graph-landing.php?g=DKwU"/></media>`

And it came out like this:

![Screen Shot 2021-05-21 at 2.53.04 PM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/25a5190c-c89a-4c91-906b-8f5d627395c9)

Please fix economics style so that it may accommodate iframes making the graph viewable in webview but a clean url in pdf.

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
yeah

# Sample mark up if applicable
`<media id="123" alt="unemployment graph"> <Iframe height="475" width="670" "https://fred.stlouisfed.org/graph/graph-landing.php?g=DKwU"/></media>`

# Acceptance Criteria

# Bug Location(s)
collection ID: col12122
server: staging (from example but will also need this done in production)
chapter/section: 20.3 (from example, but these will be embedded in almost every chapter)
surrounding text: "Rising Wage and Low Unemployment: Where Is the Unemployment in Supply and Demand?"

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
i think this is the same-ish issue as #3843

**Comment by lwtchu** [comment]
side notes - we're starting to embed more - is there a way to make sure this fix can hit all the books library wide or is that not possible :eyes:

**Comment by lwtchu** [comment]
I think the thing got merged so i'm gonna close this :eyes:

**Comment by Stackblocks** [comment]
Showing OK on staging. 

![image](https://user-images.githubusercontent.com/12678235/128407431-0246d6f3-ae25-4eae-801b-2934d85f8ce9.png)
