### ISSUE TITLE
philosophy - learning objectives

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3880]
This should be at the start of every module.

Documentation #3175 
Version 3
Uses `<section class="learning-objectives">` and standard markup
Title: Learning Objectives

**Comment by brittany-johnson** [comment]
<img width="548" alt="Screen Shot 2021-06-16 at 10 44 22 AM" src="https://user-images.githubusercontent.com/24909007/122279482-b23df100-cead-11eb-9b2a-6fe804dd0702.png">
