### ISSUE TITLE
philosophy - read like a philosopher

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3884]
- class: `read-philosopher`
- uses #3194
- title: Read Like a Philosopher
- has `<title>`
- uses alternate color schema 1 (blue)
- should contain mostly paragraphs, sometimes figures

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-06-15 at 4 15 58 PM](https://user-images.githubusercontent.com/24909007/122124510-fde09400-cdf4-11eb-93d9-9838b50b436f.png)
