### ISSUE TITLE
philosophy - think like a philosopher

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3885]
- class: `think-philosopher`
- uses #3194
- title: Think Like a Philosopher
- has `<title>`
- uses alternate color schema 2 (red)
- should contain mostly paragraphs, sometimes figures

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-06-15 at 4 17 29 PM](https://user-images.githubusercontent.com/24909007/122124648-32ece680-cdf5-11eb-9383-babf8be5a20d.png)
