### ISSUE TITLE
philosophy - write like a philosopher

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3886]
- class: `write-philosopher`
- uses #3194
- title: Write Like a Philosopher
- has `<title>`
- uses alternate color schema 3 (green)
- should contain mostly paragraphs, sometimes figures

**Comment by brittany-johnson** [comment]
<img width="511" alt="Screen Shot 2021-06-16 at 10 04 59 AM" src="https://user-images.githubusercontent.com/24909007/122244270-5e6de080-ce8a-11eb-89e4-f6ecc876d4ce.png">
