### ISSUE TITLE
philosophy - connections

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3887]
- class: `philo-connections`
- uses #3235
- title: Connections
- icon: [carnival-linktolearning.svg](https://drive.google.com/file/d/1jm3US-spU6F3BwURhHDY5Emxpe5vmyOr/view?usp=sharing)
- color: G3: `#78B042`

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-06-15 at 4 20 23 PM](https://user-images.githubusercontent.com/24909007/122124963-9aa33180-cdf5-11eb-948d-c9ff3a589f42.png)
