### ISSUE TITLE
philosophy - timeline

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3888]
- class: `class="time-line"`
- uses #3193 
- title: Timeline
- has `<title>`
- icon: [cosmos-timeline.svg](https://drive.google.com/file/d/19PDQXCF7vdaXmiiGnzLjvHM3EJj_is3R/view?usp=sharing)
- color: P1: `#9028A3`
- will contain an iframe - please make sure it doesn't add the extra space or do weird things - it should just be the link

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-06-15 at 4 42 18 PM](https://user-images.githubusercontent.com/24909007/122127376-af34f900-cdf8-11eb-8af3-2ebb6fdcb790.png)
