### ISSUE TITLE
philosophy - key terms

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3889]
Documentation #3206 
Title: Key Terms
Targeted by `<glossary>`
Replace the red with B2: `#0074BC`

**Comment by brittany-johnson** [comment]
![Screen Shot 2021-06-15 at 4 04 38 PM](https://user-images.githubusercontent.com/24909007/122123266-675fa300-cdf3-11eb-96d7-5119c234b39a.png)
