### ISSUE TITLE
philosophy - summary

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3890]
Documentation #3209
title: Summary
`class="summary"`
broken up by chapter
replace red with B2: `#0074BC`

**Comment by brittany-johnson** [comment]
<img width="527" alt="Screen Shot 2021-06-16 at 11 46 56 AM" src="https://user-images.githubusercontent.com/24909007/122260187-967c2000-ce98-11eb-9a25-2fd48e636eb8.png">
