### ISSUE TITLE
philosophy - review questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3891]
title: Review Questions
documentation: #3211 - does not have multiple choice
class: `review-questions`
note: these are being pulled in from exercises.openstax.org
replace red with B2: `#0074BC`
number them consecutively, broken up by section

**Comment by brittany-johnson** [comment]
<img width="753" alt="Screen Shot 2021-06-16 at 4 02 22 PM" src="https://user-images.githubusercontent.com/24909007/122293279-778f8500-cebc-11eb-9d5b-41f31500cb1d.png">
