### ISSUE TITLE
political science - table of contents (TOC)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3897]
Documentation #3154
Has Units
Replace the red with B2: `#0074BC`

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/71d2495e-7945-4d01-9ac8-6c19bdeed43e)

**Comment by kswanson33** [comment]
style merged, but not testable until [recipe](https://github.com/openstax/recipes/pull/46) is merged

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ead6c009-b4d8-4d52-9e15-0111db299f49)
