### ISSUE TITLE
political science - headers

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3898]
Documentation #3164
Replace red with B2: `#0074BC`

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/155b223f-6509-4705-b6d9-dd6715a8e158)

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/eda654f4-3879-4029-b937-0b45024c0ade)

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/8021349f-33c5-4a7d-809d-cccede42d04e)

**Comment by kswanson33** [comment]
style merged, but not testable until [recipe](https://github.com/openstax/recipes/pull/46) is merged

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![2021-07-15_17-08-02.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a11f096c-1d81-4532-bf28-6e1091a2eaf9)

![2021-07-15_17-08-13.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/85a6c1cb-dadc-4443-bc85-10c61c5a7c96)
