### ISSUE TITLE
political science - splash image

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3899]
Documentation #3171
Replace red number with  B2: `#0074BC`

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/ef539293-fd52-45c3-a6f6-0512add2a96d)

**Comment by kswanson33** [comment]
style merged, but not testable until [recipe](https://github.com/openstax/recipes/pull/46) is merged

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3547486e-bbe3-4cd0-9259-6f0039df2bb6)
