### ISSUE TITLE
political science - chapter outline

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3900]
Documentation: #3175
Version 2

Placement of this should be after the splash image.

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/db6527e8-d5f3-4b3c-a922-f5cb64b59a47)

**Comment by kswanson33** [comment]
style merged, but not testable until [recipe](https://github.com/openstax/recipes/pull/46) is merged

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5b7cc61b-08e7-464b-9bc2-1bc6c011b40d)
