### ISSUE TITLE
political science - section learning outcomes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3901]
This should be at the start of every module.

Documentation #3175 
Version 3
Uses `<section class="learning-objectives">` and standard markup
Title: Learning Outcomes

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/3d5397d7-47f2-4d48-833d-ad3776e0055e)

**Comment by kswanson33** [comment]
style merged, but not testable until [recipe](https://github.com/openstax/recipes/pull/46) is merged

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/cbc62700-6e49-48de-af21-5aa0d5842eac)
