### ISSUE TITLE
political science - introduction

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3902]
documentation #3191

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/a5d26b65-f195-41e8-9375-a876ad29b54d)

**Comment by kswanson33** [comment]
style merged, but not testable until [recipe](https://github.com/openstax/recipes/pull/46) is merged

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/55940a10-d56f-46c8-90fe-51b2dca05c9e)

**Comment by lwtchu** [comment]
is it too late  👀  the INTRODUCTION text should be black in IBM  plex sans

**Comment by lwtchu** [comment]
WAITW RONG BOOK BYE CLOSING AGIN
