### ISSUE TITLE
political science - figure/table captions and numbering

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3903]
Documentation #3183 
Replace the red with B1: `#38568A`

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/208c363d-d686-4a6e-b28a-52fdaef81104)

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/8d67fd7f-f919-48e4-b061-db6fca8ce0fb)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/42547e9d-ea34-4752-92ec-581c0e29ad2d)
