### ISSUE TITLE
political science - table design

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3904]
Documentation #3185

type 1 - use type 1

replace red with B1: `#38568A`

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/070f9fb1-a27b-4c49-a0d2-cea0ec035eff)

**Comment by kswanson33** [comment]
style merged, but not testable until [recipe](https://github.com/openstax/recipes/pull/46) is merged

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![2021-07-15_16-56-21.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/9e0fef31-b333-4550-953a-926fe3486b45)
