### ISSUE TITLE
political science - end of book references

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3905]
Documentation: #3244
Goes to the end of the book
Numbered like in American Government
Replace red with B2: `#0074BC`

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/0906a4a7-a200-4268-9f2b-e273f91e8ae0)

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/8a3a0b85-4ae8-4a4a-89c8-5db4c17ffb3a)

**Comment by kswanson33** [comment]
style merged, but not testable until [recipe](https://github.com/openstax/recipes/pull/46) is merged

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/65f41d12-abee-4e3b-80d6-fef5c2aca0dc)
