### ISSUE TITLE
political science - show me the data

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3907]
- class: `class="show-data"`
- uses #3193 
- title: Show Me the Data
- has `<title>`
- icon: [cosmos-data.svg](https://drive.google.com/file/d/1wuOBZTVgcBQNsos3nO07I8ZeLby0ect5/view?usp=sharing)
- color: R1: `#C31427`
- might contain an iframe - please make sure it doesn't add the extra space or do weird things - it should just be the link and might also contain links, figures, etc

**Comment by kswanson33** [comment]
style merged, but not testable until [recipe](https://github.com/openstax/recipes/pull/46) is merged

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![2021-07-15_16-12-23.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/25fd763a-63ec-40a5-bf4d-a48a16d8a1f8)
