### ISSUE TITLE
political science - connecting courses

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3908]
- class: `class="connecting-courses"`
- uses #3194
- title: Connecting Courses
- has `<title>`
- uses alternate color schema 1 (blue)
- should contain mostly paragraphs, sometimes figures

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/558637cc-d80e-4385-b104-78ccfb695fc8)

**Comment by kswanson33** [comment]
style merged, but not testable until [recipe](https://github.com/openstax/recipes/pull/46) is merged

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f115a623-b6d8-4a70-ac74-2f6647fb4145)
