### ISSUE TITLE
political science - meet a professional

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3909]
- class: `class="meet-professional"`
- uses #3193 
- title: Meet a Professional
- has `<title>`
- icon: [cosmos-career.svg](https://drive.google.com/file/d/16YzCGkD73wGUQuQCFRS1e-ZUkJ0Wek0O/view?usp=sharing)
- color: BR1: `#8B693A`
- might contain video, definitely will contain a list so make sure it doesn't boop out

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/52aa96b6-8b56-4aa3-8e1a-bcb70873548f)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/34449bb0-e6fc-4576-b48a-b0668c1480b9)
