### ISSUE TITLE
political science - 50/50 in 2020

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3910]
- class: `class="fifty-fifty"`
- uses #3194
- title: 50/50 in 2020
- has `<title>`
- uses alternate color schema 3 (green)
- might contain image, mostly text

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/3e29d496-3b78-4066-9a9c-c04213c2a924)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7bab2634-756d-433f-bc59-2117f8b25484)
