### ISSUE TITLE
political science - what can i do?

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3911]
- class: `class="what-do"`
- uses #3194
- title: What Can I Do?
- has `<title>`
- uses alternate color schema 4 (yellow)
- might contain image, mostly text

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/d15f6a91-8f90-41dc-9202-686e5fecd1f5)

**Comment by kswanson33** [comment]
style merged, but not testable until [recipe](https://github.com/openstax/recipes/pull/46) is merged

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3e6b8a54-387a-4f70-8b0a-ca8263c19256)
