### ISSUE TITLE
political science - where can i engage?

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3912]
- class: `class="where-engage"`
- uses #3194
- title: Where Can I Engage?
- has `<title>`
- uses alternate color schema 2 (red)
- might contain image, mostly text

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/d07b1243-5965-40fb-82d5-c0cac47951fc)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/846ccc35-22f5-4b54-8072-8ab4ebe2185c)
