### ISSUE TITLE
political science - video

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3913]
this is the EXACT same as anthropology feature

- class: `media-video`
- uses #3235
- title: Video
- icon: [carnival-media.svg](https://drive.google.com/file/d/1ysubfctsaUx_oPahgDg0Fi9OyqtccdNJ/view?usp=sharing)
- color: G1: `#1E9575`

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/d2be6505-8393-42be-8378-55ef7bbfef1b)

@lwtchu the "Video" title is autogenerated in Kitchen, so I think it can be removed from the content!
