### ISSUE TITLE
political science - key terms

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3914]
Documentation #3206 
Title: Key Terms
Targeted by `<glossary>`
Replace the red with B2: `#0074BC`

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/b2865a61-1bdb-4fd9-a709-542090a7ed8d)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0bd88bf9-4caa-403f-9d74-3ca8dc5c8556)
