### ISSUE TITLE
political science - summary

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3915]
Documentation #3209
title: Summary
`class="summary"`
broken up by chapter
replace red with B2: `#0074BC`

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/8ee801bc-bd13-49a6-9fed-3cb437bf084f)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8eacdaad-b4e2-45c3-a7a1-a5209e621d98)
