### ISSUE TITLE
political science - review questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3916]
title: Review Questions
documentation: #3211 - does not have multiple choice
class: `review-questions`
note: these are being pulled in from exercises.openstax.org
replace red with B2: `#0074BC`
number them consecutively, broken up by section

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/5445498c-c54f-4a60-96f7-783deab7c6aa)

**Comment by kswanson33** [comment]
style merged, but not testable until [recipe](https://github.com/openstax/recipes/pull/46) is merged

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/9c748db8-35b9-4022-b5e1-bd1f832545a7)
