### ISSUE TITLE
political science - suggested readings

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3917]
Documentation: #3214
NO separate module headers
`class="suggested-reading"`
replace red with B2: `#0074BC`

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/f98f5124-c214-4eca-933e-aa605b92f6b8)

**Comment by kswanson33** [comment]
not testable until [recipe](https://github.com/openstax/recipes/pull/46) is merged

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/30bdb74b-fc8b-4ea7-8152-ecb50dbe6536)
