### ISSUE TITLE
english composition - paragraph icon update

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3923]
Work mostly done here #3490. We just need to update the icons and add new ones.

## this is done
- Linguistics - [icon](https://drive.google.com/file/d/1iqiO6BjqcXDXWrHDmMog__J3NPsVrhpV/view?usp=sharing) - `class="linguistic-icon"`

## replace
- Culture - [icon](https://drive.google.com/file/d/1dwyVQHI7ChjKKSAjPDx6U4ZERE8dQMyr/view?usp=sharing) - `class="culture-icon"`
- Dreaming [icon](https://drive.google.com/file/d/1JYbvV2CCWjEqasBdJ-3EHB2--EK-7EcG/view?usp=sharing) - `class="dreaming-icon"`

## new
- Visual - [icon](https://drive.google.com/file/d/180VwqYVVw6hOUi8geP9-SYs-XJtoa8IR/view?usp=sharing) - `class="visual-icon"`
- Speech - [icon](https://drive.google.com/file/d/1O0Baigp_-ViR-09NkmoZXhyI8-yVTQPY/view?usp=sharing) - `class="speech-icon"`
- Auditory - [icon](https://drive.google.com/file/d/1kTWSEkx_Jen7xHXb7sFurn2-RQYGXnUi/view?usp=sharing) - `class="auditory-icon"`
- Kinesthetic - [icon](https://drive.google.com/file/d/18cMX3HQzgIgbHRDYq4ukbi-9uJ3vMzel/view?usp=sharing) - `class="kinesthetic-icon"`

**Comment by brittany-johnson** [comment]
Dreaming
![Screen Shot 2021-06-23 at 11 14 37 AM](https://user-images.githubusercontent.com/24909007/123132305-3810ed80-d414-11eb-9fd1-72e393bb4e06.png)

**Comment by brittany-johnson** [comment]
<img width="594" alt="Screen Shot 2021-06-23 at 4 07 24 PM" src="https://user-images.githubusercontent.com/24909007/123168142-2f80dd00-d43d-11eb-90f9-c5aaf4605f6e.png">
<img width="645" alt="Screen Shot 2021-06-23 at 4 07 29 PM" src="https://user-images.githubusercontent.com/24909007/123168144-30197380-d43d-11eb-8fa2-7259779a71f0.png">

**Comment by Stackblocks** [comment]
- [ ] Displays OK with current code & content
![2021-06-30_10-00-41.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6b8170a3-e141-489c-9e7a-95351dffd1be)
