### ISSUE TITLE
english composition - annotation text treatment

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3924]
![Screen Shot 2021-06-16 at 1 39 05 PM](https://user-images.githubusercontent.com/11299125/122274571-4ad17280-cea8-11eb-9536-1ec47e41f1c7.png)

# Public domain text
class: `<para class="public-domain">`
**CHANGE** font: from Courier Prime TO **IBM Plex Sans**
**NEW** indent on left and right, kind of like the quote treatment
Add a line to the side on the left
weight: 1px
color: G1: `#1E9575`

# Student sample text
class: `<para class="student-sample">`
Same as above but with B2: `#0074BC`

**Comment by Stackblocks** [comment]
- [ ] Displays OK with current code & content
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/23866da2-c5a3-4b6e-bac6-cbf1290e34af)
