### ISSUE TITLE
english composition - replace literacy narrative trailblazer icon

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3925]
<img width="546" alt="Screen Shot 2021-06-09 at 4 36 12 PM" src="https://user-images.githubusercontent.com/11299125/121432864-d2ffc700-c940-11eb-834e-6ff649620cee.png">

New icon here: https://drive.google.com/file/d/1jnU-XolCGcrDwKdb08hv0CdBOKdIurpP/view?usp=sharing

Make sure it's still flush with the line and mountain peaks a little over the line

**Comment by brittany-johnson** [comment]
<img width="704" alt="Screen Shot 2021-06-24 at 2 23 59 PM" src="https://user-images.githubusercontent.com/24909007/123320803-dc1f9500-d4f7-11eb-9818-3a37ffd42190.png">

**Comment by Stackblocks** [comment]
- [ ] Displays OK with current code & content
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/dc9e9db0-2356-4208-834a-d88cce3e2f91)
