### ISSUE TITLE
english composition - new literacy narrative trailblazer photo quote treatment

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3926]
Note class `author-quote`.
Will ALWAYS contain a photo and a blockquote.
Documentation #3931

**Comment by Stackblocks** [comment]
Blockquote falls off of the right side of the page instead of wrapping, test content generated 2021-06-29 with current magnetic.moscow.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1e795e75-a155-47c8-8cf4-868ac7d3c398)

**Comment by Stackblocks** [comment]
- [ ] Displays OK with current code & content
![image](https://user-images.githubusercontent.com/12678235/124022936-12a35700-d9b3-11eb-9069-80ed4c970997.png)
