### ISSUE TITLE
english composition - writing process sections icons

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3928]
Functionality achieved in #3599

Icons need to be updated for each class:

### Quick Launch
*This is technically already done but they didn't like the icon, so just update the icon.
class: `quick-launch`
icon: [cosmos-launch.svg](https://drive.google.com/file/d/1gy7ydGlYDqfjZnDOkE4FuVgfXEXlFV4m/view?usp=sharing)
titletext generated from class: `Quick Launch:`

### Drafting
class: `drafting`
icon: [cosmos-pencil.svg](https://drive.google.com/file/d/11X0zrUXYaAyEvF8jhC-VDuy1TBHqCWT6/view?usp=sharing)
titletext generated from class: `Drafting:`

### Peer Review
class: `peer-review`
icon: [cosmos-peerreview.svg](https://drive.google.com/file/d/1DS1zGlEXHQUyshT9xFSE94ZwND9lBctg/view?usp=sharing)
titletext generated from class: `Peer Review:`

### Revising
class: `revising`
icon: [cosmos-revision.svg](https://drive.google.com/file/d/12ZIBw7AE9yw1hL2N35tPDETdZ0I1MosD/view?usp=sharing)
titletext generated from class: `Revising:`

**Comment by brittany-johnson** [comment]
<img width="463" alt="Screen Shot 2021-06-25 at 11 56 05 AM" src="https://user-images.githubusercontent.com/24909007/123459774-590c4680-d5ac-11eb-8537-8384fbdc4a25.png">
<img width="649" alt="Screen Shot 2021-06-25 at 11 55 26 AM" src="https://user-images.githubusercontent.com/24909007/123459777-59a4dd00-d5ac-11eb-906f-1dd309cf20f4.png">
<img width="492" alt="Screen Shot 2021-06-25 at 11 55 40 AM" src="https://user-images.githubusercontent.com/24909007/123459778-5a3d7380-d5ac-11eb-93a0-e3a1b0f4ad56.png">
<img width="433" alt="Screen Shot 2021-06-25 at 11 55 54 AM" src="https://user-images.githubusercontent.com/24909007/123459781-5a3d7380-d5ac-11eb-913b-ce9ab8d7144b.png">

**Comment by Stackblocks** [comment]
- [ ] Displays OK with current code & content
![2021-06-30_10-04-19.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1a37dbe6-f197-4f48-9fa3-abbd0210d7bb)![2021-06-30_10-02-28.png]
(https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/9d6f423d-3122-43ad-8e08-f529f4abe227)![2021-06-30_10-02-00.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e3f8ffc4-3b3d-4796-8797-cfff4fc55812)![2021-06-30_10-02-09.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a5467574-3b1d-4f0c-992a-0a7a4e6b541f)
