### ISSUE TITLE
english composition - bugs with living in their own words feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3929]
Original #3524 Documentation card #3193

<img width="1135" alt="Screen Shot 2021-06-10 at 1 52 56 PM" src="https://user-images.githubusercontent.com/11299125/121581227-39ddb880-c9f3-11eb-90c4-9d44012b5223.png">

- [x] font treatment for "Living By Their Own Words" title should be archivo bold and black and all caps; specific specs are on 3193
- [x] title "Literacy from Unexpected Sources" should be archivo medium, black 
- [x] green end line for end of section is missing
- [x] Idk ...if there should be another documentation card since this is a section and note a note 😬

**Comment by wilkus27** [comment]
@lwtchu Specs for title were set properly, but they are overwritten by specs for general H3:

![image](https://user-images.githubusercontent.com/40228854/123259278-97462f00-d4f4-11eb-809f-7c53531b970e.png)

I need to set more specific selector. But I have a question. What color should be title of this section? When I fix selector it will be green as border. Is it ok? Or it should be black, like in card 3193, or maybe red like it is now?

**Comment by wilkus27** [comment]
This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/123285465-5b6b9380-d50d-11eb-81ed-f07ea8c67ef3.png)

End of the section:

![image](https://user-images.githubusercontent.com/40228854/123285585-763e0800-d50d-11eb-901b-6dbd4d34ed29.png)

About question from the last point of the issue, I think it's ok to use documentation card created for the note. We are using components from the iconned note in the shape for section and keep everything in notes directory. So it's even more helpful to have one card ;)

**Comment by lwtchu** [comment]
@wilkus27 looks great  thank you :)

**Comment by Stackblocks** [comment]
- [ ] Displays OK with current code & content

![2021-06-30_11-03-30.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4c841d40-2f0b-498e-9b99-0cdad99d435b)![2021-06-30_11-03-50.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/385ecb27-46f6-42e0-b60d-177d14ce72ef)![2021-06-30_11-04-11.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b0f3e51e-0104-41ab-837e-a343c0648fa8)
