### ISSUE TITLE
Support headers in intro modules

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#3930]
# Brief Description of Change and Screenshots
What kind of change is this? [ ] recipe [x] styles [ ] i don't know

HOWDY, there are headers in the intro module of chapter 18, Sociology 3e. This is not typical so when generating the pdf, they were not styled and went unnoticed. See screenshot below. 

![Screen Shot 2021-06-07 at 4.42.00 PM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/be297a05-fb71-4d8e-a3dc-7934b7727b78)

# Acceptance Criteria
We'd like the headers in intro modules to be supported and match other headers in normal modules.

# Content Location(s)
collection ID: col32649
server: prod
chapter/section: Chapter 18, introduction
surrounding text: `The wage gap in the United States`

**Comment by ajluk** [comment]
@lwtchu These are h3's. should the be styled as regular h3 in the schema?: 
![image](https://user-images.githubusercontent.com/55203598/123297763-29abfa00-d518-11eb-99d0-77ed8bc3765a.png)

**Comment by lwtchu** [comment]
@ajluk ah yes - styled like regular h3's we can do this later though I'll schedule it in for the o.o  release

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/142020456-5b56cba1-24dd-46e5-84af-18ecd9a2d254.png)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/54084d7c-fe96-4db4-a60b-67156ea7a12a)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2021-11-17 10-30-59](https://user-images.githubusercontent.com/47241114/142174597-b8eec65d-176e-465a-a9f2-63a1560872aa.png)
![Screenshot from 2021-11-17 10-32-16](https://user-images.githubusercontent.com/47241114/142174652-70caa6e5-ca81-4020-9686-954137b87846.png)
