### ISSUE TITLE
cosmos theme - photo and quotation note

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3931]
![Screen Shot 2021-06-11 at 1 13 25 PM](https://user-images.githubusercontent.com/11299125/121731862-15e3ab00-cab7-11eb-8463-caf1d5ea42d9.png)

# Figure 
- vertically centered to the box
- horizontally centered on the left side of the box (could it be like almost like two cells next to each other on the page)
- image  caption and figure numbering style should be supported

# Box treatment
- padding should match that of the other features which is I think v-grid(1)?
- color: Y2: `#FFF7E5`

# Quote treatment
## first para (quote)
- font family: archivo
- weight: regular, 400
- treatment: italic
- size: font-scale(4): 18.66pt, 25.2px, 2.1rem
- alignment: centered to the right side of the box

## second para (attribution -- Educated: A Memoir)
- should match figure caption
- font family: ibm plex sans
- weight: regular, 400
- size: font-scale(0): 9pt, 12px, 1rem
- alignment: centered to the right side of the box (goes with the text above)

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/69327b98-aedd-4fbc-9c2d-920564477217)

Specs added: 
- `line-height` on large quote: `v-spacing(4)`
- padding around feature: `v-spacing(2)`

**Comment by lwtchu** [comment]
Closing cause this is mergy merged and there's a separate card
