### ISSUE TITLE
english composition - handbook numbering

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3932]
![Screen Shot 2021-06-15 at 2 29 32 PM](https://user-images.githubusercontent.com/11299125/122112167-2614c680-cde6-11eb-9a73-5367806da91b.png)

class: `<document class="handbook">` and `<content class="handbook">`

follows same design for headers in #3164 for appendix/any  end of book content

can we add numbering to the h1's?

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-21 09-13-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2826df84-b7a0-4497-b2cf-272501bcfa6c)
