### ISSUE TITLE
english composition - underline text  styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3933]
![Screen Shot 2021-06-14 at 1 56 55 PM](https://user-images.githubusercontent.com/11299125/121944575-6ad22c00-cd18-11eb-832d-4b0bb36c469c.png)

If possible, can we have the underline be the standard bottom border, but to not be confused with links to make it colored and with highlight?

line color: Y1: `#DCB83D`
highlight color: Y2 `#FFF7E5`

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/71c0a0d8-6e13-4104-b935-d2b62f0f2966)
