### ISSUE TITLE
english composition - punctuation emphasis

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3934]
![Screen Shot 2021-06-14 at 1 59 59 PM](https://user-images.githubusercontent.com/11299125/121944921-d3b9a400-cd18-11eb-9a9b-459b8e0f252e.png)

targeted by `<span class="emphasis-punctuation">` 
font size: font-scale(1): 10.8pt, 14.4px, 1.2rem
treatment: bold, 700
background highlight color: Y2: `#FFF7E5`

**Comment by Stackblocks** [comment]
- [ ] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/243edc26-c0e3-4154-9856-f09366b055e0)
