### ISSUE TITLE
english composition - handbook outline

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3935]
![Screen Shot 2021-06-15 at 2 29 32 PM](https://user-images.githubusercontent.com/11299125/122112167-2614c680-cde6-11eb-9a73-5367806da91b.png)

Documentation #3175 
Version 2 (Chapter Outline)
Title: Outline
Numbering for list: H.# (H.1, H.2, etc) 
Linking will be done in content.

**Comment by wilkus27** [comment]
@lwtchu Do you plan to add some other text to Outline list or there will be always just titles of the sections from Handbook page? If just titles, I think we can create Outline totally by recipe, not in the content, like we do for Chapter Outlines.

**Comment by lwtchu** [comment]
@wilkus27 interesting...can we do it with the h1's?

**Comment by wilkus27** [comment]
Yes, first I have to add numbering to section titles, but then I can copy entire title and use it in Outline.

**Comment by lwtchu** [comment]
@wilkus27 🤩  awesome i'll update the tagging legend

**Comment by wilkus27** [comment]
@lwtchu This is how it looks (without styles for now). I created `div` with `os-handbook-outline` class: 

![image](https://user-images.githubusercontent.com/40228854/123651866-1e184600-d82c-11eb-9559-592449b8b203.png)

Can I ask you for a few content changes? :slightly_smiling_face: 

1. Remove section with `handbook-outline` class.
2. Add ids to section titles that should be numbered.
3. Create some other section after "Paragraphs and Transitions" so we can test if numbering is working good.

**Comment by lwtchu** [comment]
@wilkus27 done 8) sorry it took so long i missed the comment :grimace:

**Comment by wilkus27** [comment]
@lwtchu No problem :wink: I just finished adding styles for it. And this is how it looks:

![image](https://user-images.githubusercontent.com/40228854/123831326-80447a00-d904-11eb-84b4-81ced348491f.png)

I'm moving card to code review :slightly_smiling_face:

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-01 14-27-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/70be3ecc-32d5-4cac-b878-e6b202c5b91b)
