### ISSUE TITLE
Anthropology - Final Prototype

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3938]
The authors did not like this design so we'll have to move this to the Carnival theme. I'll do my best to make the cards super clear.

https://legacy-content06.cnx.org/content/col10005/latest/

**Comment by ajluk** [comment]
@lwtchu Currently there are no footnotes present in the content, so we didn't add the styling for them, but will the footnotes be added later and we should add the styling in advance for them?

**Comment by lwtchu** [comment]
@ajluk here's the new footnote issue https://github.com/openstax/cnx-recipes/issues/4003

**Comment by lwtchu** [comment]
? Closing :eyes:
