### ISSUE TITLE
anthropology - update toc to carnival theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3946]
Documentation #1070 - there might be some slight font/size changes. i want to match it closer to what we have for cosmos theme
Please use B2: `#0074BC` for the accent colors

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2021-07-20 14-31-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a6623af1-0c18-4c4a-94e1-55099e322e9b)![Screenshot from 2021-07-20 14-33-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3d901854-50b8-4dc0-9cb6-4094dbd9154f)
