### ISSUE TITLE
Contemporary Math - Tables in solutions crowding text

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#3952]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ x ] i don't know

![2021-06-22_11-59-54.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5507b3e5-746c-4d23-91ae-0f760119989e)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
Happens consistently

# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
(leave blank if the same as above)
collection ID: col10008
server: content04
chapter/section: 1.1
surrounding text: Notice that the last bin doesn’t follow

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server:
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
I think these are tables specifically in LISTS. Maybe we can add a lil more padding

**Comment by lwtchu** [comment]
Broken content can't work on this yet

**Comment by LostMojo** [comment]
Caused by the table being a sibling to the raw li text

**Comment by MartaSztuka** [comment]
@LostMojo spacing between tables and paragraphs is still too small.
![Screenshot from 2022-01-12 15-04-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ea67d914-06b3-4a84-a68e-be6276e4a211)![Screenshot from 2022-01-12 15-04-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a552ddc6-d1fd-4b2d-9866-b525eba02f85)

**Comment by lwtchu** [comment]
@LostMojo what spacing is this at now :eyes:
