### ISSUE TITLE
Contemporary Math - Your Turn headers getting orphaned on page break

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#3953]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [x]  recipe [ ] styles [ ] both [ ] i don't know

![2021-06-22_11-58-15.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/47579d91-ec4f-4ce3-99f4-935f5592e62b)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences? 
Happens several times with Your Turn notes, may also happen in other notes.

# Sample mark up if applicable

# Acceptance Criteria
Headers do not get orphaned at page break

# Bug Location(s)
collection ID: col10008
server: Content04
chapter/section: 1.2 - Visualizing Data
surrounding text: shows the region of every institution of higher learning

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by kswanson33** [comment]
@Stackblocks I wasn't able to find an instance of this happening ... I did confirm that Your Turn headers have the `break-after: avoid` styling (see below):

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/307b71f8-e541-48c1-9997-0fc5d55888e3)

I think this is a pretty old issue ... I wonder if it was only happening in an earlier version of the content? If you think it's okay, I think we can close

**Comment by Stackblocks** [comment]
Yeah, considering how much work was done in the last 7mo. I think it's safe to close this out. If it reappears we can open a new issue.
