### ISSUE TITLE
Placement of Chapter Outline "Line" is Awkward with Spanish Translation

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#3957]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know

![Screen Shot 2021-06-28 at 9 40 35 AM](https://user-images.githubusercontent.com/7863733/123655846-fe196000-d7f4-11eb-8754-9488040e78f3.png)

This looks fine in the English version (below), but perhaps because of the extra characters of the Spanish translation, it looks like a mistake there.

![Screen Shot 2021-06-28 at 9 42 26 AM](https://user-images.githubusercontent.com/7863733/123655980-1d17f200-d7f5-11eb-8434-66c5651cb711.png)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
Yes - every chapter opener

# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID:
server:
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
Updated documentation to tighten up the design #1076 - might be able to get this update when we implement for anthro

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/93edced9-a867-4d8e-bb35-e82e619363c4)
