### ISSUE TITLE
Problemas De Desafío Header Breaks from Problems 

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#3958]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know

Not positive we can/should change this, but it did not happen in the English version - wanted to check:

![Screen Shot 2021-06-28 at 9 46 13 AM](https://user-images.githubusercontent.com/7863733/123656705-c65ee800-d7f5-11eb-8f9e-7ca714db8dbc.png)

vs:

![Screen Shot 2021-06-28 at 9 47 36 AM](https://user-images.githubusercontent.com/7863733/123656778-d7a7f480-d7f5-11eb-8fb4-988c901314eb.png)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
Not every instance; I believe we have rules in place that are determining the pattern of occurrences.

# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID:
server:
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
if this is merged i can close? idk.

**Comment by Stackblocks** [comment]
Working fine on Staging Deploy

![image](https://user-images.githubusercontent.com/12678235/128403997-52c95c04-6beb-4333-8ea6-b67a5b4954a7.png)
