### ISSUE TITLE
anthropology - update headers to carnival theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3960]
documentation #1072 
there might be some slight font/size changes. i want to match it closer to what we have for cosmos theme
Please use B2: `#0074BC` for the accent colors

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-15 17-04-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/60ee483d-fded-4d8b-a8e2-18c81c3102a5)![Screenshot from 2021-07-15 17-04-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bb898ea9-4702-4ba8-9aaa-84b0e15dbe59)
