### ISSUE TITLE
anthropology - add carnival theme splash treatment

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3961]
Documentation #1075; specs have been updated to match current formatting. might have some slight adjustments to text font/size

accent color B2: `#0074BC`

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-21 09-10-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ce853ac6-8fe1-4190-ab7f-64b2f3755298)
