### ISSUE TITLE
anthropology - update figure captions to carnival theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3962]
documentation #1081 - also made some clean up to the documentation so it's clearer. make sure it matches

**Comment by kswanson33** [comment]
This will also impact figures across carnival

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-20 14-39-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8665bc3f-1b2e-4afa-9fa3-8c2876eb7e90)![Screenshot from 2021-07-20 14-39-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3416c05e-7cab-44ff-8e56-9b96b02bee17)
