### ISSUE TITLE
anthropology - table design to carnival t heme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3963]
documentation #1080
should be really close to cosmos current design - only changes are probably some font and color tweaks
accent color should be B2: `#0074BC`

**Comment by kswanson33** [comment]
as per slack discussion with @lwtchu, using the same accent color for tables as for figures (`#C31427`)

**Comment by kswanson33** [comment]
This will impact BasicTables across carnival

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-20 14-35-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8c7ab40e-7c5c-4cde-ad6d-0c65e8065493)![Screenshot from 2021-07-20 14-35-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/57bbcbf6-4b45-44ae-b68c-b3d22fabdd6d)
