### ISSUE TITLE
anthropology - update learning objectives to carnival theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3964]
Documentation #1077 
Accent color: B2: `#0074BC`
Some slight tweaks to the font sizes/etc to better match the cosmos theme

**Comment by LostMojo** [comment]
@lwtchu Is this just for anthropology, or should it be applied to all learning objectives in Cosmos?

**Comment by lwtchu** [comment]
@LostMojo (replying here for documentation) - we  should move anthropology to the carnival theme and apply any changes to all of carnival (carnival theme has some inconsistencies since it was the first theme that we did)

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-20 14-29-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/80e0a9a4-0781-4735-b211-37997fe8a127)
