### ISSUE TITLE
anthropology - update chapter outline to carnival theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3965]
Documentation #1076

Version 2 without the list for LO. 

Accent color B2: `#0074BC`

**Comment by kswanson33** [comment]
This will also impact any carnival book that used the old version of the Version 2 outline

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-21 09-05-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3a4201d3-003b-4ceb-8930-acc9a9d17fda)
