### ISSUE TITLE
anthropology - update feature boxes to carnival theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3967]
# Ethnographic Sketches
change from boxed note to icon note #3966
icon: [carnival-sketch](https://drive.google.com/file/d/1lRZPIFSYt4zpqKkFE2q_fN85unGHllw2/view?usp=sharing)
color: O1: `#F37541`
class: `ethnographic-sketches`

# Mini-Fieldwork Activity
change from boxed note to icon note #3966
icon: [carnival-pithhelmet](https://drive.google.com/file/d/15oElk9MyUotUkchT9DAP5F-hzacWp3Ro/view?usp=sharing)
color: B3: `#00819A`
class: `fieldwork-activity`

# Profiles in Anthropology
change from boxed note to icon note #3966 
icon: [carnival-profile](https://drive.google.com/file/d/1JoxTOazjhIp5z7Yw43KpoWU8roLmsnEA/view?usp=sharing)
color: R1: `#C31427`
class: `profiles-anthropology`

# Video
update fonts to match #3968
color: G2: `#1E9575` (the same but in carnival, this is listed as G2 instead of G1)

# Podcast
update fonts to match #3968
color stays the same just adding here for reference - B2: `#0074BC`

**Comment by LostMojo** [comment]
Does the video and podcast notes have their own special icon as well?

**Comment by lwtchu** [comment]
@LostMojo yea but i think it was done already - I think you can copy over the icon file :eyes: or is that not how it works

**Comment by MartaSztuka** [comment]
#### PASSED
###### ETHNOGRAPHIC SKETCHES
![Screenshot from 2021-07-21 09-17-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/77e6c932-23c9-4d16-894a-a5b48584a639)
###### MINI-FIELDWORK ACTIVITY
![Screenshot from 2021-07-21 09-17-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d7946179-96a5-4bb4-aade-64ed1625fba8)
###### PROFILES IN ANTHROPOLOGY
![Screenshot from 2021-07-21 09-18-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/693127c0-fc14-457c-965f-ca33c6e37e8c)
###### PODCAST
![Screenshot from 2021-07-21 09-19-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/941ae5e6-7757-4e3c-82fd-15721edfd06a)
###### VIDEO
![Screenshot from 2021-07-21 09-19-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/db22a616-c295-451f-8b2f-89910601ea50)
