### ISSUE TITLE
anthropology - update eoc/eob to carnival theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3969]
can we make sure the fonts match #1072 

B2: `#0074BC` - accent color for headers and ribbon

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-15 17-10-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/399d19d5-dfed-4103-8705-26c1f4fa438d)![Screenshot from 2021-07-15 17-10-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9e06e117-e729-4ea8-9ae0-ce04cd0c814d)
