### ISSUE TITLE
english composition: rework unit opener

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3972]
More information here: https://github.com/openstax/cnx-recipes/pull/3955#pullrequestreview-696166969.

This changes shouldn't have an impact on PDF. Visually it should look the same.
Here are specs: https://github.com/openstax/cnx-recipes/issues/3936

**Comment by lwtchu** [comment]
We can wait to test REX preview if you want before you get started. The release should go out sometime tomorrow and we'll be able to test and see if this is still impacting the TOC

**Comment by MartaSztuka** [comment]
@wilkus27 Bleeds shows for light pink box bot not for red one
![Screenshot from 2021-07-15 09-34-12](https://user-images.githubusercontent.com/47241114/125751445-53354afb-4bbb-4eb4-8a22-d9fbee883607.png)

**Comment by wilkus27** [comment]
@lwtchu I found a solution to problem that Marta mention here: https://github.com/openstax/cnx-recipes/issues/3972#issuecomment-880482968. But it's not perfect :disappointed: It works only when unit content fits to the one page. It can't jump to another one. Otherwise design will be broken. Are we ok with that?

My previous solution (done in n.n milestone) covered this problem. Here https://github.com/openstax/cnx-recipes/issues/3936#issuecomment-877152001 I added screenshots how it would look when text jump to another page. 

So my question is, what is more important here? To have bleeds or to have design that looks ok when it displays on two pages?
Because it's very hard to find solution that covers both issues. Let me know what do you think.

**Comment by lwtchu** [comment]
@wilkus27 i'm trying to make sure it fits into one page - I think it should be okay 🤔 . i think it's more important to have bleeds.

**Comment by wilkus27** [comment]
Ok, thank you! So I'm moving my PR to code review.

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-27 11-09-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0d358ed5-c284-4d35-a904-3c624d4f8c4c)
