### ISSUE TITLE
American Government 3e footnote superscript comma

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#3986]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know
<img width="634" alt="Screen Shot 2021-07-12 at 4 33 43 PM" src="https://user-images.githubusercontent.com/1895432/125359141-7cb2e900-e32f-11eb-8428-9bdc0e671968.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
yes

# Sample mark up if applicable
`<para> ...<footnote>...</footnote><footnote>...</footnote></para>`
# Acceptance Criteria

# Bug Location(s)
collection ID: col33102
server: production
chapter/section: 2.3
surrounding text: regular voters grew as levels of income and education increased.

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
Can we m ake sure there's a comma between the two footnote references (40,41)

**Comment by MartaSztuka** [comment]
@lwtchu Coma between footnotes look's like this, is that ok, or we want it blue and in index?
![Screenshot from 2021-11-22 11-27-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6c5315a2-a94f-47fd-b7da-25ccb3b0ed75)

**Comment by ajluk** [comment]
@lwtchu I have an additional question to Marta's comment. If the the comma should be in superscript (if it should off course), it should be black right? We need to add a special class to the `sup` tag in Kitchen, let me know if you have any preferences about the class name :slightly_smiling_face: For the `span` tag I have used here the class was `os-reference-link-separator` but here we need another one to prevent it overwrites other element with the same class (there is one index), maybe `os-superscirpt-link-separator` would be suitable? Let me know what are your thoughts?

**Comment by lwtchu** [comment]
@ajluk sorry for the delay - i'm going to move this to the next sprint.

i think os-footnote-link-separator might be better? since the other one is specific to referencess

**Comment by ajluk** [comment]
@lwtchu Thank you! But should the comma be in superscript and black?

**Comment by lwtchu** [comment]
@ajluk oops sorry i missed this :| yes that would be great

**Comment by lwtchu** [comment]
@ajluk i can't tell - did this already go out a while back :joy:

**Comment by ajluk** [comment]
@lwtchu No, I was going to remind myself and you about it :sweat_smile:

**Comment by ajluk** [comment]
Screenshot for reference:
![image](https://user-images.githubusercontent.com/55203598/150580569-ae73f449-ddda-45cb-9596-9f65df1c8d6c.png)

**Comment by lwtchu** [comment]
eee it looks great

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2022-01-24 12-45-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fc36aa15-fb06-489f-864f-ea41cd99e195)
