### ISSUE TITLE
AmGov 3e space after all external links is underlined

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#3987]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know
<img width="474" alt="Screen Shot 2021-07-13 at 2 33 08 PM" src="https://user-images.githubusercontent.com/1895432/125522915-51029e1b-eb20-4f9e-875d-b1b0cddc3e5e.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
yes
# Sample mark up if applicable
`<link url="https://openstax.org">`
# Acceptance Criteria

# Bug Location(s)
collection ID: col33102
server: production
chapter/section: all
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by ajluk** [comment]
@lwtchu This issue has been already fixed by Natalia within this PR: https://github.com/openstax/cnx-recipes/pull/4083: 
![image](https://user-images.githubusercontent.com/55203598/142026552-a067e4d1-873a-4e9c-9593-1e7a6187bbd3.png)

**Comment by lwtchu** [comment]
![Screen Shot 2021-11-17 at 3 44 37 PM](https://user-images.githubusercontent.com/11299125/142287323-8f1f489c-02e4-4758-81af-6e82c073378f.png)
Verified fixed on CORGI job 2355
