### ISSUE TITLE
English Composition: Handbook toc link page class 

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3990]
Link to Handbook page doesn't have any specific class in toc:
![image](https://user-images.githubusercontent.com/55203598/125808865-ee7b826e-42d2-41b1-b759-af39d228c124.png)

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/125812825-e1fbab37-15b6-486f-b60b-648d24ba1169.png)

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-20 13-40-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7a335be2-82e6-4f7b-af9a-6399d0999409)
