### ISSUE TITLE
Anthropology: update key terms to carnival theme

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3992]

**Comment by ajluk** [comment]
@lwtchu Here is how the Key Terms look styled: 
![image](https://user-images.githubusercontent.com/55203598/125929793-3be23bad-a689-406e-bb1c-7f4e1a815d24.png)
But I have one question if they should stay in two columns like they are in the rest of the carnival books?

**Comment by lwtchu** [comment]
@ajluk good point ...let's keep it like this for now t hank you I completely forgot about the two column business

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-20 14-06-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2add98f5-8718-4468-86e7-03e5c23559f0)
