### ISSUE TITLE
Anthropology: Update Lists, Links to carnival theme

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3993]

**Comment by ajluk** [comment]
Screenshot for reference:
![image](https://user-images.githubusercontent.com/55203598/125929632-c9f8d84d-1bc3-41e9-a6df-1f22c5ba2535.png)

**Comment by lwtchu** [comment]
@ajluk what's different abouot this link treatment? vs the other themes

**Comment by ajluk** [comment]
@lwtchu There was any treatment before because they are provided via each theme and when we changed the theme to carnival we couldn't use cosmos I guess. So I just added the link treatment for carnival here.

**Comment by lwtchu** [comment]
ahh okay thank you for explaining
