### ISSUE TITLE
Anthropology: update Summary to carnival theme

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3994]
Summary updated to carnival theme looks like so: 
![image](https://user-images.githubusercontent.com/55203598/125933629-6376ea49-c60e-449f-aa30-42f5568033c7.png)
Here is how it looks before: 
![image](https://user-images.githubusercontent.com/55203598/125933563-534f327a-ec0f-4afd-9855-f3362d5b5e4d.png)
@lwtchu should I keep the two column layout or rather we should leave one column?

Also I have one more question if we should keep the band color, which now is set to `#00819A` or rather change it to accent color for anthropology: `#0074BC` (will match the headers)?: 
![image](https://user-images.githubusercontent.com/55203598/125934506-e9811442-7983-4361-831d-d599955fe759.png)

**Comment by lwtchu** [comment]
@ajluk i think we should match t he headers should tighten up the amount of colors

**Comment by MartaSztuka** [comment]
##### PASSED
Ribbon and headers are the same colour: #0074BC
![Screenshot from 2021-07-20 13-57-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c0898b22-67bc-49b0-8601-d5f5555d0cf3)
