### ISSUE TITLE
Anthropology: update Critical Thinking to Carnival

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3995]
Here is how EOC exercises looks in Carnival:

![image](https://user-images.githubusercontent.com/40228854/125937526-36c32641-ae15-41f4-b953-8146d36d39e1.png)

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-20 13-52-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/97fd827c-715e-4aa5-a43d-8d6f4f497b9f)
