### ISSUE TITLE
Anthropology: update Index to Carnival

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3998]
This is how Index looks in Carnival Theme:

![image](https://user-images.githubusercontent.com/40228854/125942261-26095efd-ad23-4dd2-8400-0780356f2de7.png)

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-20 15-57-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b11ca857-fa25-4c33-9258-cbaf045c7a75)
