### ISSUE TITLE
Anthropology: update References to Carnival

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4000]
There are no EOC References in previous Carnival books, so I just added indentations like in oter themes:

![image](https://user-images.githubusercontent.com/40228854/125949428-c717c77f-59fd-4564-822a-dfde887aafc9.png)

@lwtchu let me know if I should make any changes.

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-20 14-06-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5ee28ebe-f28a-4e75-8144-54826f972e62)
