### ISSUE TITLE
bca - put composite EOC in a header called "chapter review"

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4010]
![Screen Shot 2021-07-28 at 12 15 59 PM](https://user-images.githubusercontent.com/11299125/127367137-b5f465da-4908-4fd1-84ef-7a0d9f0ef30f.png)
See how  `Chapter Review` is holding all the EOC stuff. Can we implement this in BCA?

**Comment by brittany-johnson** [comment]
<img width="577" alt="Screen Shot 2021-08-04 at 12 43 01 PM" src="https://user-images.githubusercontent.com/24909007/129392541-fc4d6c5e-8f35-43a1-99ea-db379f0baeb7.png">

**Comment by Stackblocks** [comment]
Showing as expected with current code / content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/91e7b03f-ac5e-4a12-a2b5-8722f8616fd8)
