### ISSUE TITLE
computer science - put composite page in EOC under "chapter review" 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4011]
Same as #4010 
![Screen Shot 2021-07-28 at 12 15 59 PM](https://user-images.githubusercontent.com/11299125/127367137-b5f465da-4908-4fd1-84ef-7a0d9f0ef30f.png)
See how  `Chapter Review` is holding all the EOC stuff. Can we implement this in Computer Science?

**Comment by lwtchu** [comment]
idk why this is c losed. i don't think we ever did this??

**Comment by lwtchu** [comment]
Should look like this: https://github.com/openstax/cnx-recipes/issues/4280#issuecomment-998189261

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content, per the above comment.
![image](https://user-images.githubusercontent.com/12678235/149212683-c1d2a603-9a11-4734-8d3b-baf9b95aeeb0.png)
