### ISSUE TITLE
bca - learning objectives style change

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4012]
change to match updated specs here #2711 for numbered LO

basically they want it to match computer science 

we will need to update the rest of the cardboard theme but we should hit bca for now.

**Comment by Stackblocks** [comment]
Displaying as expected with current content / code

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c5ed837c-9137-40e5-be1d-7447eede8f72)
