### ISSUE TITLE
OPS-0012 Composition - paragraph icons not showing in web view

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4014]
Icons  are only visible in PDF view, not in web view. Kindly check and advise.

Web View:
![image](https://user-images.githubusercontent.com/86622862/127527869-ec07e549-a6e9-46ec-9fb5-05005a189c75.png)

PDF View:
![image](https://user-images.githubusercontent.com/86622862/127527889-d488b4de-1c42-41c3-9968-962cbf5e9f2e.png)

# Bug Location(s)
collection ID: col00001
server: https://copper-anteater-egyq5vxq.ws-us11.gitpod.io/
chapter/section: Chapter 18, Section 18.3
surrounding text: Within a medium—for example, a video—you might include images, audio, and text.

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by openstaxalina** [comment]
will discuss on tomorrow's call - how critical is it to have the icons designated visually in web view?

**Comment by openstaxalina** [comment]
Matt will discuss with Shelley to establish a ranking of which elements are most important pedagogically to carry over to the web view. Icons are on that list but unsure where it will rank.

**Comment by srm-openstax** [comment]
From Shelley: This is of moderate priority. Icons direct instructors and students to text that highlights varying learning styles and issues.

**Comment by lwtchu** [comment]
This is merged and on production.
