### ISSUE TITLE
OPS-0012 Composition - paragraph icons doubling

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4015]
In  the input file we have marked "[insert linguistics> and <dreaming> icons]" as in the tagging legend as <para class = "annotation linguistic-icon dreaming-icon">. But the PDF view shows the same icon twice.

PDF view:
![image](https://user-images.githubusercontent.com/86622862/127528382-345f92b7-ffcd-476d-85ea-b3e6a3edf7d9.png)

# Bug Location(s)
collection ID: col00001
server: https://github.com/openstax/osbooks-writing-guide
chapter/section: Chapter 18, Section 18.5, m00006
surrounding text: Now you will experiment with using multiple modes to create an advocacy project.

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
For dev: I think this is because we haven't tested with 1 or two instances and it's trying to auto-fill for 3? Let me know-- i can also get some test content

**Comment by ajluk** [comment]
I have checked that this issue will be resolved in Kitchen. It needs to be tested after English Composition Kitchen release.

**Comment by ajluk** [comment]
@lwtchu I'm no sure. I guess it can be done after Eng Com recipe release  in Kitchen.

**Comment by wilkus27** [comment]
English Composition is now merged and put into tag `v1.5.0`, so I'm moving this issue to Ready for testing column.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/697976b2-f23f-4d98-a1cd-c41d55c31359)
