### ISSUE TITLE
OPS-0012 Composition - locally hosted interactive is not displaying correctly on webview and PDF

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4016]
We  have coded the interactive file in <iframe>. But does not seem interactive in PDF and web view. Kindly check and advise.

# Bug Location(s)
collection ID: col00001
server: https://copper-anteater-egyq5vxq.ws-us11.gitpod.io/
chapter/section: Chapter 18, Section 18.5
surrounding text: As preparation for writing, consider different types of media, and match them to their appropriate purposes in this interactive.

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
![Screen Shot 2021-07-30 at 2 48 42 PM](https://user-images.githubusercontent.com/11299125/127704822-92bc5c93-57e4-4552-92b5-48f0b5316567.png)
![Screen Shot 2021-07-30 at 2 50 44 PM](https://user-images.githubusercontent.com/11299125/127704825-e3bbe70e-9bf0-40cd-94dc-162f810067b1.png)
![Screen Shot 2021-07-30 at 2 50 52 PM](https://user-images.githubusercontent.com/11299125/127704826-a28c070d-52d9-4df6-9bd0-f880b9d4062f.png)


Some more screenshots. Need to troubleshoot how to properly link interactives in content and generate the correct link.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/cnx #1644](https://github.com/openstax/cnx/issues/1644) via [**ZenHub**](https://www.zenhub.com/)
