### ISSUE TITLE
OPS-0012 Composition

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4018]
In  all the heading, text colors are appeared in PDF view. But not in Web View. Kindly check and advise.

Web view:
![image](https://user-images.githubusercontent.com/86622862/127530731-410e5298-d5b3-4d58-8e2d-3007279e2c59.png)

PDF view:
![image](https://user-images.githubusercontent.com/86622862/127530807-c26524e7-be99-456f-ba49-f3c62fb98a75.png)

# Bug Location(s)
collection ID: col00001
server: https://copper-anteater-egyq5vxq.ws-us11.gitpod.io/
chapter/section: Chapter 18, Section 18.2
surrounding text: Digital Representations of Embodiment and Cultural Identity

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
This is expected.
