### ISSUE TITLE
OPS-0012 Composition - exercises are not aligned  to question number in webview

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4019]
In  Discussion Question section, numbers with content alignment is incorrect in web view only. Kindly check and advise.

Web view:
![image](https://user-images.githubusercontent.com/86622862/127531285-f7525a97-9bad-44c3-a319-65a600bd2d61.png)

# Bug Location(s)
collection ID: col00001
server: https://copper-anteater-egyq5vxq.ws-us11.gitpod.io/
chapter/section: Chapter 18, Section 18.2
surrounding text: 1. How does using a multimodal approach allow Bolatagici to communicate her lived experience?

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by openstaxalina** [comment]
@lwtchu investigating why the text is blue

**Comment by lwtchu** [comment]
Text is blue due to the linking of the exercise. We've included feedback in our XML review. I believe once the mark up is fixed, this should be resolved. 

Once the content is updated, kindly regenerate and see if the issue has been resolved.

**Comment by lwtchu** [comment]
Still an issue - prioritize lower against the other webview things

**Comment by lwtchu** [comment]
@openstaxalina oh yes i opened the card here - https://github.com/openstax/unified/issues/1726

**Comment by lwtchu** [comment]
No longer an issue
![Screen Shot 2023-01-23 at 1 15 13 PM](https://user-images.githubusercontent.com/11299125/214129184-19dbe58c-d58a-4874-b295-c50619a6ad39.png)
