### ISSUE TITLE
OPS-0012 Composition - support caption in unnumbered images

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4020]
Image  caption is appeared in top of the image in web view (Section 18.4). Kindly check and advise. (This occurrence only)

PDF view:
![image](https://user-images.githubusercontent.com/86622862/127531506-9daf438c-a3ed-4ed3-b786-39edd462c0b1.png)

# Bug Location(s)
collection ID: col00001
server: https://github.com/openstax/osbooks-writing-guide
chapter/section: Chapter 18, Section 18.4, m00005
surrounding text: Alexandra Dapolito Dunn (Credit: Eric Vance/Wikimedia Commons, PD US EPA)

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
Question for devs: can this be updated in kitchen/styles to impact all books?

**Comment by srm-openstax** [comment]
Kindly check and resolve this issue.

**Comment by lwtchu** [comment]
@srm-openstax this issue has been scheduled into a milestone for a code fix. please let us know if the fix needs to be expedited.

**Comment by Stackblocks** [comment]
The caption is now appearing in the appropriate place beneath the image, but it's has a number which I believe is an issue in this case. @lwtchu can you weigh in?

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/05575276-2bb9-4c54-8195-22f288ace935)

**Comment by lwtchu** [comment]
@Stackblocks @wilkus27 oh yeah. We just  need the image right aligned still, but with the caption under the image.

**Comment by wilkus27** [comment]
@lwtchu I just fetched the newest content. There is no more `unnumbered` class for this figure.

![image](https://user-images.githubusercontent.com/40228854/134696986-fb361f54-d4d3-44fb-9f69-3eef12f21fb1.png)

**Comment by lwtchu** [comment]
@wilkus27 🙃  let me see contact them

**Comment by Stackblocks** [comment]
@wilkus27 Thanks for looking into it and clearing up the confusion about the numbering! Larissa found another instance of an unnumbered image and it is still showing the caption above the image.


![image](https://user-images.githubusercontent.com/12678235/134700061-0c3e91a3-0a7e-4c27-bca9-e120e8fee739.png)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/498548b6-99ca-42fa-b35d-1291561a2669)
