### ISSUE TITLE
OPS-0012 Composition - annotated text design not on  webview

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4021]
In  begin student section, left side border appeared in PDF view, but not in web view. Kindly check and advise.

Web view:
![image](https://user-images.githubusercontent.com/86622862/127532184-e5800109-16a1-4837-9e7e-f429d935d30e.png)

PDF view:
![image](https://user-images.githubusercontent.com/86622862/127532002-7ab323c3-cebd-4699-a459-2948972bd827.png)

# Bug Location(s)
collection ID: col00001
server: https://copper-anteater-egyq5vxq.ws-us11.gitpod.io/
chapter/section: Chapter 18, Section 18.5
surrounding text: I chose the photo essay genre to show the effects of war

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by openstaxalina** [comment]
will discuss on tomorrow's call - how critical is it to have annotated text designated visually in web view?

**Comment by openstaxalina** [comment]
It is a pedagogical requirement that annotated text - and student passage text - have some sort of visual indicator/differentiation on the web. cc @lwtchu

**Comment by openstaxalina** [comment]
This could be a different color "screen" or box behind student passages, etc.

**Comment by openstaxalina** [comment]
This also came up in @anthonypalmiotto's review of the chapter -- the presentation is not clear on the web, so we do need to do something to denote that this is annotated.

See the "I revised..." "I changed..." statements at the end of this page: https://rex-web.herokuapp.com/books/ee7ce46b-0972-4b2c-bc6e-8998c785cd57@a2e8f73/pages/18-5-writing-process-create-a-multimodal-advocacy-project?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20210804.143519

Versus the much clearer presentation in PDF:
https://openstax-cops-artifacts.s3.amazonaws.com/writing-guide-latest-git-1276.pdf

**Comment by lwtchu** [comment]
Merged and on production
