### ISSUE TITLE
OPS-0012 Composition - public-domain text does not have border on webview

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4022]
In  "living by their own words" section, left side border appeared in PDF view, but not in web view. Kindly check and advise.

Web view:
![image](https://user-images.githubusercontent.com/86622862/127532393-0ae847b2-a201-4cdd-b866-5af1e727a41c.png)

PDF view:
![image](https://user-images.githubusercontent.com/86622862/127532415-d46640c6-3fb6-4dbd-98cc-38095fdfbcfa.png)

# Bug Location(s)
collection ID: col00001
server: https://copper-anteater-egyq5vxq.ws-us11.gitpod.io/
chapter/section: Chapter 18, Section 18.4
surrounding text: On this day in 1990, a new era was ushered in for

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
@srm-openstax the border on the left is for the texts tagged with `public-domain` and not a part of the living by their own words feature.  please confirm if this paragraph intends to have the `public-domain` class

**Comment by openstaxalina** [comment]
will discuss on tomorrow's call - how critical is it to have public domain text designated visually in web view?

**Comment by openstaxalina** [comment]
It is a pedagogical requirement that public domain text have some sort of visual indicator/differentiation on the web. cc @lwtchu

**Comment by openstaxalina** [comment]
The Living By Their Own Words features **will** include public domain and annotated text - these types of text will also occur elsewhere.

**Comment by lwtchu** [comment]
Merged and on production
