### ISSUE TITLE
OPS-0012 Composition - extra space injected after linked text

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4023]
It appears that in the PDF view the styling is adding a space after a link. The CNXML doesn’t have a space but there is one in the PDF that is part of the linked text.

PDF view:
![image](https://user-images.githubusercontent.com/86622862/127532865-d2c344b3-f718-4fce-aa14-886de6621e49.png)

CNXML view:
`including <link url="http://www.bolatagici.com/tadrua">photography</link>, video, fine art, and <link url="https://diasporadic679.wordpress.com/torika-bolatagici/">mixed media</link>.`

# Bug Location(s)
collection ID: col00001
server: https://github.com/openstax/osbooks-writing-guide
chapter/section: Chapter 18, Section 18.2 - m10003
surrounding text: is a creator, educator, and art historian who works with various modalities, including photography, video, fine art, and mixed media. 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by wilkus27** [comment]
@lwtchu I checked and space is added in styles. It looks bad when there are punctuation marks after links, but when there are words space is needed:

![image (1)](https://user-images.githubusercontent.com/40228854/131688129-f171afc4-5da2-4b1b-8aef-121f2d779f07.png)

The only solution will be to add some class to links that have punctuation marks after, then we can remove additional space just from them.

**Comment by lwtchu** [comment]
@wilkus27 how is it injected in the recipe? is it possible to add the space after the `</link>` closing tag?

**Comment by wilkus27** [comment]
@lwtchu This is done in styles for PDFs. We are creating `after` element inside links with content of the link adress (it's needed for printed versions):

![image (2)](https://user-images.githubusercontent.com/40228854/131897403-4b59efaf-96c8-4aa9-86a1-9f88079e92c9.png)

What I can do is to modify it from:
`content: " (" attr(href) ") ";`
to
`content: " (" attr(href) ")";`
so there will be no space after `)`. But as I said in my previous comment when there is a word after link it will stick to the parentheses.

**Comment by wilkus27** [comment]
Actually I just noticed that there is a space in the content before words :thinking: 

![image (3)](https://user-images.githubusercontent.com/40228854/131898892-00391f4e-7a0a-46b8-b7dc-25d8ebfff4ce.png)

Let me try to remove space after `)` from styles and we will see how does it look in PDF. Maybe there won't be problem :crossed_fingers:

**Comment by lwtchu** [comment]
@wilkus27 okay! if not we might need to do some digging around and see if it might be a cnxml to  HTML issue. keep me posted!

**Comment by wilkus27** [comment]
@lwtchu It looks good :tada: 

![image (4)](https://user-images.githubusercontent.com/40228854/131980592-ccaa02a1-a78f-4b88-bf27-3cfb65043af8.png)

Sorry for the confusion :grin: 

I made this change library wide, is that ok? Or should I fix this only for English Composition for now?

**Comment by lwtchu** [comment]
@wilkus27 library wide is okay 

@Stackblocks can we spot check a few links in the books that are in production with this one when it goes to staging?

**Comment by Stackblocks** [comment]
- [X] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7b9ef252-4181-47ab-bd25-c56b69ec62eb)
