### ISSUE TITLE
OPS-0012 Composition - Figure labels

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4027]
# Brief Description of Change and Screenshots
What kind of change is this? [ ] recipe [ ] styles [ ] i don't know

![Screen Shot 2021-08-03 at 10 50 30 AM](https://user-images.githubusercontent.com/86622862/128047939-70dccfb5-44b5-463f-a7cf-d82ac2091a10.png)

From  Shelley: Are we able to label all images as Figures? We do not need Table labels in this book.

# Acceptance Criteria

# Content Location(s)
collection ID:
server:
chapter/section: 18.5, pp. 22 & 23
surrounding text:

**Comment by lwtchu** [comment]
@srm-openstax if this is marked up as a table, it will be a table. this is standard across the openstax library. I'm proposing no change.
