### ISSUE TITLE
OPS-0012 Composition - Table Boundaries

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4028]
# Brief Description of Change and Screenshots
What kind of change is this? [ ] recipe [ ] styles [ ] i don't know

![Screen Shot 2021-08-03 at 10 50 30 AM](https://user-images.githubusercontent.com/86622862/128048539-fd570284-81db-49a5-a579-1f3ca01969b3.png)

From Shelley: Are we able to have both the top and bottom line of the table in color/maroon?

# Acceptance Criteria

# Content Location(s)
collection ID:
server:
chapter/section: 18.5, pp 22 & 23
surrounding text:

**Comment by lwtchu** [comment]
This is the standard design for the theme. Proposing no change.
