### ISSUE TITLE
OPS-0012 Composition - Figure Captions

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4029]
# Brief Description of Change and Screenshots
What kind of change is this? [ ] recipe [ ] styles [ ] i don't know

![Screen Shot 2021-08-03 at 11 06 57 AM](https://user-images.githubusercontent.com/86622862/128049029-c3edaef6-8767-4aa2-9e5d-6bdff2078030.png)
![Screen Shot 2021-08-03 at 11 07 09 AM](https://user-images.githubusercontent.com/86622862/128049041-b2c42431-b107-4daa-b68d-e2b700dbdd7b.png)

From Shelley: Are we able to have all Figure captions consistently centered or left margin flush?

# Acceptance Criteria

# Content Location(s)
collection ID:
server:
chapter/section: 18.3, p. 12 & 18.3, p. 14
surrounding text:

**Comment by lwtchu** [comment]
If it is multi lined (long caption), it wil be left aligned. If it is short, like the second one, it will center with the image in case the image is also narrow so that it won't be placed too far away from the image. 

Proposing no change.
