### ISSUE TITLE
OPS-0012 Composition - Trailblazer Header Title Change

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4030]
# Brief Description of Change and Screenshots
What kind of change is this? [ ] recipe [ ] styles [ ] i don't know

![Screen Shot 2021-08-03 at 11 21 01 AM](https://user-images.githubusercontent.com/86622862/128051228-be78061b-c63f-445b-aa83-f63eba925d12.png)

From Shelley: The header will NOT always include Literacy Narrative--that part of head will change with each chapter. Also, the name and birthdate of the Trailblazer will change in each chapter.

# Acceptance Criteria

# Content Location(s)
collection ID:
server:
chapter/section: Design Proto
surrounding text:

**Comment by openstaxalina** [comment]
SRM is requesting variable text before and after the word "Trailblazer". For example Literacy Narrative Trailblazer: Tara Westover; Multimodal Trailblazer: [name].

Expressed that it may not be possible to have variable text both before and after the word "Trailblazer" and have it all set in the title.

**Per Anthony, better design might be "Trailblazer" as the only design treatment, then the module title is "[type]: [author name] [dates]"**
Example:

1.2 Trailblazer
Literacy Narrative: Tara Westover (b. 1986)

Let's discuss at our meeting later @lwtchu

**Comment by lwtchu** [comment]
Can we change this title to just `Trailblazer`?

**Comment by srm-openstax** [comment]
For clarification, the request was only for the variable text **before** "Trailblazer." The "Tara Westover" part is in the title of the section and that is okay and how it was expected. But as I understand we're moving forward with only having the header show Trailblazer and we'll put (e.g.) Literacy Narrative Trailblazer: Tara Westover (b.1986) in the <title>.

**Comment by srm-openstax** [comment]
We have deleted "Literacy Narrative" from the XML file based on the correction received. However, "Literacy Narrative" is not deleted in the PDF output. Please find the below screenshots. Kindly check and resolve this issue.

![trailblazer](https://user-images.githubusercontent.com/86622862/131733682-ad311e5e-43ca-4c09-a0b0-5a76401af6c9.png)
![Trailblazer1](https://user-images.githubusercontent.com/86622862/131733702-a01a41e1-1130-48f7-b950-d8f247f0cf33.png)
![trailblazer2](https://user-images.githubusercontent.com/86622862/131733705-4bdeca07-96bc-47f2-8f02-662f4a1eb49f.png)

**Comment by lwtchu** [comment]
@srm-openstax this will have to be a style/template code fix. we are currently working on it and will let you know when the code is released via email

**Comment by wilkus27** [comment]
@lwtchu fixed in the kitchen https://github.com/openstax/recipes/pull/87. Let me know if I should make a change also in old recipe.

**Comment by lwtchu** [comment]
@wilkus27 no we dont need to make the change in the old recipe  - thank you!

**Comment by Stackblocks** [comment]
Headers are now simply showing up as "Trailblazer" so this may need some additional adjustment on one side or another. 

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/aa2836cb-1559-42f4-9fbe-b52609f0581b)

**Comment by wilkus27** [comment]
This is a content issue. Here is a screen from assembled file:

![image (8)](https://user-images.githubusercontent.com/40228854/133081081-72cc64f2-4567-4701-9cde-df9bf5f610d9.png)

In the title there should be put text that is going to be subtitle after baking.
So in the baked file here is a title created by recipe:

![image (9)](https://user-images.githubusercontent.com/40228854/133081617-510d73d3-141f-4671-b0e5-1036bd3d770f.png)

and here is one from the content:

![image (10)](https://user-images.githubusercontent.com/40228854/133081713-49d00c7b-10b9-41df-a2fa-eb08a57f3cec.png)

**Comment by lwtchu** [comment]
@wilkus27 once this goes to production, i'll alert the XML production team to make the proper adjustments

**Comment by srm-openstax** [comment]
@lwtchu - it seems production can already begin to put the entire new title into the <title> tag, and then it will be right when the code is fixed?  Currently, they're putting the correct title into the metadata title but not in the <title> itself.  I was about to connect with them about doing that but I wanted to check with you to confirm it does also need to go into the <title>. (This is Margie.) 
![image](https://user-images.githubusercontent.com/86622862/133275788-324bd9fe-24e1-4d6a-ac72-d531abf8868f.png)

**Comment by Stackblocks** [comment]
Code work complete, now waiting for the content fix to be implemented before the issue can be fully closed out.

**Comment by openstaxalina** [comment]
@srm-openstax after speaking with Larissa, yes - the production team should set `[genre] Trailblazer: [name]` in the `<title>` tag for this chapter and all others moving forward.

Please keep in mind, until Larissa notifies you of the code release (scheduled for ~9/22), the display will continue to be incorrect in that "Literacy Narrative Trailblazer" will show in the yellow ribbon. After the code release, only "Trailblazer" will show in the yellow ribbon with **[genre] Trailblazer: [name]** in black text below.

**Comment by lwtchu** [comment]
Sent release notes. Closing issue.
