### ISSUE TITLE
OPS-0012 Composition - Indentation

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4031]
# Brief Description of Change and Screenshots
What kind of change is this? [ ] recipe [ ] styles [ ] i don't know

![Screen Shot 2021-08-03 at 11 13 24 AM](https://user-images.githubusercontent.com/86622862/128049943-748ff0ea-6a2d-4f6c-b3a1-16e349e91531.png)

From Shelley: Is there a way to add the icon without creating the extra indentation? It's odd that the two paragraphs don't align.

# Acceptance Criteria

# Content Location(s)
collection ID:
server:
chapter/section: 18.1, p. 5
surrounding text:

**Comment by lwtchu** [comment]
We'll need to test and check with print specs in case this goes into the gutter of the spine. I don't anticipate this blocking any work, so we will take some time to explore options.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/40f66ce8-c601-4033-b436-4f34d9fb49a1)
