### ISSUE TITLE
OPS-0012 Composition - Restart Numbering of Discussion Questions For Each Section

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4032]
# Brief Description of Change and Screenshots
What kind of change is this? [ ] recipe [ ] styles [ ] i don't know

![Screen Shot 2021-08-03 at 11 15 38 AM](https://user-images.githubusercontent.com/86622862/128050353-c73fc23e-6fd4-4ae9-a953-e37578625fe9.png)

![Screen Shot 2021-08-03 at 11 16 01 AM](https://user-images.githubusercontent.com/86622862/128050376-428a8f24-d71d-4ee2-b125-0054d1b645ea.png)

From Shelley: Numbering of Discussion questions should restart in each section. They should NOT be sequential within the chapter.

# Acceptance Criteria

# Content Location(s)
collection ID:
server:
chapter/section: 18.2, p. 9 & 18.4, pp. 18-19
surrounding text:

**Comment by srm-openstax** [comment]
We have coded separately in POET. But automatically takes over the PDF view continuously. Kindly check and resolve this issue.

![DQ_Issue](https://user-images.githubusercontent.com/86622862/130228471-425e88e8-025c-4753-8305-bf60d09e73fa.png)

**Comment by lwtchu** [comment]
@srm-openstax the numbering is not controlled via POET. it will be fixed when the code gets updated for the template on CORGI. hope this helps.

**Comment by openstaxalina** [comment]
@srm-openstax once you submit an issue, please do not continue to modify/troubleshoot in the content, as this makes bug fixing very challenging. **We will always provide specific instructions to you if there is a content fix for the issue.** In this case, a code change is required, which we are working on.

**Comment by lwtchu** [comment]
@wilkus27 in kitchen is good - thank you

**Comment by Stackblocks** [comment]
Discussion Questions currently showing as un-numbered. Not sure if this is a result of the fix in Kitchen or the adjustments made to the content, so this will need to be re-investigated 

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f15aa742-acca-41bb-98c3-ac260498d8d0)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![2021-09-10_13-42-38.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c1c88388-8d2c-459a-9eab-780a697c79db)
