### ISSUE TITLE
OPS-0012 Composition - Further Reading

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4034]
# Is it possible to code for both paragraph format and citation format in this section? These titles ... The following is an example ... s/b paragraph format.

What kind of change is this? [ ] recipe [ ] styles [ ] i don't know

![Screen Shot 2021-08-04 at 10 54 45 AM](https://user-images.githubusercontent.com/86622862/128213531-68e7bf66-9245-45fa-8310-eb4cad6cd533.png)

# Acceptance Criteria

# Content Location(s)
collection ID:
server:
chapter/section: Ch 18, Further Reading, p. 432
surrounding text:

**Comment by lwtchu** [comment]
@srm-openstax I think it will have to be either or - do you have a preference?

**Comment by srm-openstax** [comment]
If it's either/or, then leave as is. Thanks!

**Comment by lwtchu** [comment]
Since we are leaving as is - we will close this.
