### ISSUE TITLE
OPS-00012 | Composition _ Web view issue OpenStax portal

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4037]
The process of web view conversion in CORGI has changed exactly. However, the book did not open in the web view. Kindly check this issue and provide the solution. I have attached the screenshot for your reference.

Note: Other books in CORGI open correctly.

![webview1](https://user-images.githubusercontent.com/86622862/128494030-11c400ea-c7d3-4a1b-83a3-f546c13e2264.png)
![webview2](https://user-images.githubusercontent.com/86622862/128494057-a0fbca8b-459c-4c7e-bb20-1a3cf78c5d12.png)

# Bug Location(s)
collection ID: osbooks-writing-guide/writing-guide
Job id: 1267
server: https://corgi.openstax.org/
chapter/section: Chapter 18
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
Hello! Found the problem. Ch 13 and Ch14 have the same title "Research Process: Accessing and Recording Information"! Renaming the chapter fixes the problem. Please do so and let us know when you are  done  and we can regenerate and  continue our XML review.

**Comment by lwtchu** [comment]
Rex view was  generated with CORGI job 1275

**Comment by srm-openstax** [comment]
Working fine. Acknowledged. Thanks for your support.
