### ISSUE TITLE
contemporary math - make chapter title and number larger

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4039]
Documentation https://github.com/openstax/cnx-recipes/issues/1752

Please change chapter title and chapter number from font-scale(2) to ***font-scale(4): 17.10pt, 22.81px, 2.1rem***

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/129785205-5a5a9cba-da3f-40a1-8152-2b349a4f0f6b.png)

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-08-19 10-23-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/66f3a602-e533-4ad8-af03-3fb30be77f28)![Screenshot from 2021-08-19 10-27-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ee3811c5-df18-4d4a-a648-b10ff07e8586)
