### ISSUE TITLE
contemporary math - new color schema for table for warmer tone

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4042]
Documentation https://github.com/openstax/cnx-recipes/issues/2204 
Change B1: `#093D4C` to R3: `#80004C` for the header row only

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-08-31 12-08-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c797c180-3aa4-4a6c-9458-96133c35aeb4)
![Screenshot from 2021-08-31 12-09-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8d819935-ae42-4511-bdac-b1ff6ded04cb)
