### ISSUE TITLE
finance - code snippets

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4044]
can we implement the same things here https://github.com/openstax/cnx-recipes/issues/3750 but for this book 

if you need content - please ask a CM to look for the code snippets in computer science and copy and paste into the finance test content

**Comment by LostMojo** [comment]
@lwtchu (for when you get back) I'd like to go over how this differs from the current implementation of Rcode!

**Comment by lwtchu** [comment]
I think this is done? Closing. LMK if it should be reopened
