### ISSUE TITLE
finance - video activity

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4045]
![Screen Shot 2021-08-06 at 4 30 08 PM](https://user-images.githubusercontent.com/11299125/128573003-8efbf4fc-6085-40e1-8b17-b20528321945.png)

Goes in the EOC - last.

Similar to #2785

Icon: https://drive.google.com/file/d/1MqJSaztF5LZ41-6LZvKhV8OXQC2asCPy/view?usp=sharing
Title: Video Activity
class: `video-activity`
Has embedded video and exercises. Please number each item and then reset.

**Comment by ajluk** [comment]
@lwtchu is there somewhere a content available with more than one `video-activity` section? Right now on  `content06.cnx.org` in `col10007` there is only one present, so there is no possibility to check the numbering: 
![image](https://user-images.githubusercontent.com/55203598/130627152-b4c392e9-38a3-4187-b6f5-d2df8e33092a.png)
If no could you add another section to the content? Thank you!

**Comment by ajluk** [comment]
@lwtchu Here is how the Video Activity looks styled: 
![image](https://user-images.githubusercontent.com/55203598/131504000-d6273420-f8f6-4ce8-9016-b11188eefc0d.png)
The numbering is not working properly now, I can make changes to the recipe, but it could be tricky. I guess it will be easier to fix it in Kitchen. Let me know if we need such changes in the old repo for Finance.

**Comment by ajluk** [comment]
Within my PR I have also styled Source and Notes, but I'm not sure if I picked the correct icon here (https://drive.google.com/file/d/1COYw-42axWZWtonKiuHNoYMjdUEviB8q/view?usp=sharing ). Here is how it looks: 
![image](https://user-images.githubusercontent.com/55203598/131504488-e7555885-edbd-4c64-802e-3bca4ef1e95d.png)
Let me know if anything should be changed here as well. :slightly_smiling_face:

**Comment by lwtchu** [comment]
@ajluk i think this is fine :eyes:

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![2021-08-31_11-09-39](https://user-images.githubusercontent.com/12678235/131538157-5bc165d2-59fb-4257-8e1b-d1db49866c49.png)

**Comment by lwtchu** [comment]
@Stackblocks fyi the numbering for exercises will come with the refactored recipe that karina did and will go out with r.r
