### ISSUE TITLE
finance - EOC collation

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4046]
Please make sure EOC goes as follows: 

- Summary `section-summary`
- Key Terms (if possible) - see if we can move Key Terms after Summary? If not do not pursue. `<glossary>`
- CFA Institute `cfa-institute`
- Sources and Notes `sources-notes`
- Multiple Choice `multiple-choice`
- Review Questions `review-questions`
- Problems `problem-set`
- Video Activity #4045 **NEW**  `video-activity`

Sources and Notes, MC, Review Questions and Problems are all currently still chilling in their sections.

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/129938277-a299e1e6-bb50-4470-b7e0-adc78de99a72.png)

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-08-20 13-36-56](https://user-images.githubusercontent.com/47241114/130227581-26b4cc0a-677e-4cfd-b3f3-a791b2f87993.png)
