### ISSUE TITLE
finance - link to learning subtitle needs to be styled

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4047]
![Screen Shot 2021-08-06 at 4 38 42 PM](https://user-images.githubusercontent.com/11299125/128573646-689ea6bb-ab17-45c6-8274-f9473a9c3ce9.png)

subtitle needs to be styled like all the other feature subtitles

**Comment by brittany-johnson** [comment]
<img width="675" alt="Screen Shot 2021-08-12 at 2 21 26 PM" src="https://user-images.githubusercontent.com/24909007/129271717-91fa4134-64a7-4182-99b3-40511b5a026d.png">

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7f3f3a03-cdfa-4ced-8d01-b4ad77cc4db4)
