### ISSUE TITLE
finance - think it through

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4048]
update to color schema 3  
class: `think-through`
Documentation: #2737

**Comment by brittany-johnson** [comment]
<img width="711" alt="Screen Shot 2021-08-12 at 2 05 24 PM" src="https://user-images.githubusercontent.com/24909007/129269761-3cfb1138-cd30-4077-b46c-c47fa05ca6a0.png">

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/491484bc-acaa-4d84-89fe-ccb54afde481)
