### ISSUE TITLE
finance - figure and table labels

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4049]
can we investigate if we can move figure numbers and titles/table numbers and titles to above the image/table? 

and leave the caption below.

padding, specs, and placement should be the same :eyes:  

IF SO please do so. this is lower prio tho

**Comment by LostMojo** [comment]
In kitchen, it shouldn't be too hard to grab the title and table number and in front of the table but within the .os-table div wrapper. But what do you mean by specs should be the same?

**Comment by lwtchu** [comment]
@LostMojo oh the styling should just stay the same for the font/color/etc

**Comment by lwtchu** [comment]
move to kitchen. make another card related to this switch these books to have the table numbers first in recipes repo

**Comment by lwtchu** [comment]
Issue moved to [openstax/kitchen #363](https://github.com/openstax/kitchen/issues/363) via [**ZenHub**](https://www.zenhub.com/)
