### ISSUE TITLE
finance - tighten spacing for tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4052]
so for the default tables, what's the smallest we can go? same question as #4050 - how small can we go? can we match it to the timeline table? around 2px all around?

trying to achieve this look
![Screen Shot 2021-08-04 at 3 19 03 PM](https://user-images.githubusercontent.com/11299125/128575026-945b458d-f2a7-4e88-b6d0-559b07e535e8.png)

***IF YOU NEED A CLASS*** i can suggest `condensed-table` and you can ask a CM to add it to all the tables

**Comment by LostMojo** [comment]
@lwtchu Should this affect all cardboard tables or just the ones in finance?

**Comment by lwtchu** [comment]
in book..scss for finance, when it goes `@include use('DefaultTable', 'cardboard:::TableWithBordersShape');`  just change 'DefaultTable' to 'CondensedDefaultTable'

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image](https://user-images.githubusercontent.com/12678235/134697715-e41ef4c5-50a0-4771-945b-62c784df9be5.png)
