### ISSUE TITLE
finance - calculator button updates

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4053]
# Primary
`span class="primary-function"`
- [x] REMOVE background color
- [x] change font-weight: bold, 700
- [x] change text color to B2: `#344456`

# Secondary
`span class="secondary-function"`
LEAVE AS IS (should be same as above but regular, 400 weight font)

**Comment by brittany-johnson** [comment]
<img width="773" alt="Screen Shot 2021-08-11 at 3 21 28 PM" src="https://user-images.githubusercontent.com/24909007/129111549-e3f07d6e-5078-4570-81eb-af5210b92a5c.png">

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1b315b46-4da9-4688-a654-59bd87a9e76d)
