### ISSUE TITLE
Change "Respuestas Clave" to "Clave de Respuestas"

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#4061]
# Brief Description of Change and Screenshots
What kind of change is this? [x] recipe [ ] styles [ ] i don't know

In the Spanish recipes, it should be "Clave de Respuestas" not "Respuestas Clave". Discussed [here](https://openstax.slack.com/archives/C022NETP39N/p1622729062373100?thread_ts=1621961709.213500&cid=C022NETP39N). The other change got made, but not this one.

# Acceptance Criteria
"Respuestas Clave" should NOT appear. Instead the title of the Answer Key -- in both the Table of Contents and back of book -- should be "Clave de Respuestas".

# Content Location(s)
collection ID: col10280
server: content01
chapter/section: Table of Contents, End of Book
surrounding text: "Respuestas Clave" should NOT appear. Instead the title of the Answer Key -- in both the Table of Contents and back of book -- should be "Clave de Respuestas".

**Comment by Stackblocks** [comment]
This was fixed for [Kitchen version 8.0.0](https://github.com/openstax/kitchen/blob/HEAD/CHANGELOG.md#800---2021-06-29), but the recipe for University Physics is still [using 6.1.0](https://github.com/openstax/recipes/blob/main/books/u-physics/bake). We need to update the version of kitchen being used, which may entail some additional work on the University Physics recipe. 

There is also the band-aid option of fixing this on the recipe localization side, but that is less than ideal and we would like to avoid it if possible.

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/130103773-5c33a4d8-e50a-4ff7-9181-0b34c6cc17f7.png)

Looking good in local testing, next need to test it in the CORGI pipeline.

**Comment by Stackblocks** [comment]
![2021-08-25_09-37-38](https://user-images.githubusercontent.com/12678235/130810986-548d3c00-6d33-46dc-90c8-4df1931b4e3a.png)
