### ISSUE TITLE
Bullets and icons overlapping issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4069]
As per guidance we have changed the icons in the "list item" to "paragraph" coding as like below, Now the icons are rendering in pdf but it's overlapping with bullets in list. Please check and advise.

<item class="annotation linguistic-icon"><term…
to
<item><para class="annotation linguistic-icon"><term…

Coding:
![Coding](https://user-images.githubusercontent.com/86622862/130608371-436ad57a-cf16-4704-ba4e-537900484536.png)

PDF:
![PDF](https://user-images.githubusercontent.com/86622862/130608231-9975d7ef-163e-4aba-9126-4f08af5abd81.png)

# Bug Location(s)
collection ID: col00001
server: https://github.com/openstax/osbooks-writing-guide
chapter/section: Chapter 18, Section 18.1, m00002
surrounding text: Multimodal genres are uniquely positioned to address audiences through

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by kswanson33** [comment]
![image](https://user-images.githubusercontent.com/26280712/132716697-40b15387-35ed-4626-bfea-ebc25f810f5c.png)

Removing bullets, as this element has `data-bullet-style="none"`.

**Comment by lwtchu** [comment]
![Screen Shot 2021-09-15 at 5 11 45 PM](https://user-images.githubusercontent.com/11299125/133516717-8c7c97fb-23d1-4cf4-9529-00496f63a7c8.png)
Verified on prod.
