### ISSUE TITLE
OPS-Composition_PDF Generate Issue in CORGI

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4084]
We trying to generate PDF in CORGI for the "osbooks-writing-guide/writing-guide" book.  But it's not generate PDF throws some error. Kindly check & reslove it.
![Corgi_issue](https://user-images.githubusercontent.com/86622862/132231499-526db006-c368-4418-b52d-0ba67126ab3d.png)

# Bug Location(s)
collection ID: col00001
server: https://github.com/openstax/osbooks-writing-guide
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by ne-newton** [comment]
Every `<section>` requires a `<title>`
In `m00014` there was a section without a title.
I added the [line](https://github.com/openstax/osbooks-writing-guide/blob/378055833a6d554b65a90affd36db580d6fb4ed0/modules/m00014/index.cnxml#L27) `<title>To test</title>` and the book built successfully in CORGI as job 1411

**Comment by srm-openstax** [comment]
Query resolved. Thanks for your support.
