### ISSUE TITLE
update styling for english composition to support exercise pipeline update

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4088]
Documentation for structure and new way exercises are being pulled in and supported: https://github.com/openstax/cnx-recipes/issues/4087 

Styling documentation: #3211 (old english comp card: https://github.com/openstax/cnx-recipes/issues/3653)

**Comment by Stackblocks** [comment]
Questions imported in the new style match the questions from the old English Comp Question Styling issue

![image](https://user-images.githubusercontent.com/12678235/133099262-69ab3fed-ced8-4d0f-9a30-ca4b35f89a2c.png)
