### ISSUE TITLE
OPS-Composition Exercise linking issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4092]
When we are clicking on the exercise links in the web version they are not going to any question on the server. It just says Loading. Please check and resolve this issue.

We have coded it as below.

<exercise id="exer-00001">
  <problem id="prob-00001">
  <para id="para-00013"><link class="os-embed" url="https://exercises.openstax.org/exercise/EC_Ch18-Sec2_DQ1"/></para>
  </problem>
  </exercise>

![Excercise](https://user-images.githubusercontent.com/86622862/132667226-0444bdd2-8dc4-4ef9-8acd-b96801d58f53.png)
![Excercise_loding_issue](https://user-images.githubusercontent.com/86622862/132667238-247e3f3d-7ecd-4b90-87c3-52f84b322d94.png)

# Bug Location(s)
collection ID: col0001
server: https://copper-anteater-egyq5vxq.ws-us16.gitpod.io/
chapter/section: 18.2
surrounding text: during her residency in Barbados

**Comment by lwtchu** [comment]
I edited the mark up in the repository. The link shouldn't point the user to exercises.openstax.org. It's a functionality to pull in the data from exercises.openstax.org and into the content. I removed the `https://exercises.openstax.org/` and replaced it with the `#` as noted in the tagging legend.

You can see the exercise content being pulled in here. You will see there's no numbering and that fix will go out with https://github.com/openstax/cnx-recipes/issues/4088 - which will be released sometime next week.

![Screen Shot 2021-09-09 at 11 08 04 AM](https://user-images.githubusercontent.com/11299125/132722264-95206ba8-ba5e-4d5d-954e-2d61de92f778.png)
![Screen Shot 2021-09-09 at 11 08 20 AM](https://user-images.githubusercontent.com/11299125/132722270-01a062d3-3de3-4818-8b30-6041595f56cb.png)

**Comment by openstaxalina** [comment]
From @srm-openstax 

Please find below updated links after resolution of ticket #4092 (Appearance of exercise editor questions in PDF file & Web View)
 
Repository link:
https://github.com/openstax/osbooks-writing-guide
 
Gitpod link:
https://copper-anteater-egyq5vxq.ws-us16.gitpod.io/
 
PDF view:
https://openstax-cops-artifacts.s3.amazonaws.com/writing-guide-latest-git-1513.pdf
 
Web view:
https://rex-web-production.herokuapp.com/books/ee7ce46b-0972-4b2c-bc6e-8998c785cd57@1389587/pages/2-works-cited?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20210831.185645
 
@lwtchu please close this ticket if all looks good to you. thank you!
