### ISSUE TITLE
OPS-0012 Further reading section placement issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4099]
We have received the correction for should placed the "Evaluation" section is to be placed after the "Further Reading" section. We have coded accordingly in the XML file in POET. But the Further Reading section in the output file automatically comes to an end of the chapter. Please check and resolve this issue.

![further_reading1](https://user-images.githubusercontent.com/86622862/132980066-7cc18f68-d40e-4b0c-abc1-121ffcaed1ac.png)
![Further_Reading](https://user-images.githubusercontent.com/86622862/132980067-dded50f9-905a-48cb-8e95-32532a955c0d.png)

collection ID: col00001
server: https://copper-anteater-egyq5vxq.ws-us15.gitpod.io/
chapter/section: Chapter 1/ Section 1.8
surrounding text: It’s a good idea to familiarize yourself with texts of evaluation and analysis

**Comment by lwtchu** [comment]
We initially identified three sections that would be move to the End of Chapter:
Further Reading
Works Cited
Works Consulted

Are we adding Evaluation and Analysis to that list (it will appear in the TOC). Or removing Further Reading?

**Comment by srm-openstax** [comment]
In the manuscript the **Evaluation** and **Analysis** were intended to be subtitles within the **Further Reading** section although they were styled as if they were meant to be at the same level.  There is a lead in sentence referring to them, as topics that would be addressed _within_ the Further Reading. 

But per Shelley when asked about how to handle this, "OK, let’s delete “Evaluation” and “Analysis” and alphabetize as a single list under Further Reading." 

So, no action from OpenStax is required. Production will need to make that change to the content.

**Comment by lwtchu** [comment]
@srm-openstax okay -  feel free to test and close out the card if it works out! if not, let us know and i can try to help come up with other content markup solutions

**Comment by srm-openstax** [comment]
Thanks for your support, the content is revised and hence this style is not required.
