### ISSUE TITLE
philosophy/political science - increase spacing between sections

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4101]
![Screen Shot 2021-09-13 at 1 37 07 PM](https://user-images.githubusercontent.com/11299125/133138504-ad5d4462-13c9-41bd-b040-013ad0394d7b.png)

Is this currently set to v-space(1)? Can we increase it to 2?

**Comment by wilkus27** [comment]
@lwtchu I want to make sure where we need these spaces.
If we have such tree:

```
-page.preface
-chapter
  - page.introduction
  - page (regular)
  - page (regular)
  - composite-page (eoc)
  - composite-page (eoc)
-page.appendix (eob)
-composite-page.index (eob)
```
I should increase spaces after:
a) regular pages or 
b) regular pages and introduction page or 
c) all pages (also preface and appendix) or
d) everywhere (after all pages and composite pages)? :smile:

**Comment by lwtchu** [comment]
let's go with option `b) regular pages and introduction page`

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/dc1c9e08-93e1-41b9-bcf7-12ebdfbb7021)
