### ISSUE TITLE
cosmos theme/political science/philosophy: reduce spacing between term and definition in 'key term' section

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4102]
![Screen Shot 2021-09-13 at 1 55 28 PM](https://user-images.githubusercontent.com/11299125/133140782-8a2001c7-b6c5-4d17-aa42-d9fdcb84daeb.png)

is there a way to reduce the padding between the term and definition? maybe to 1-3px depending on what our options are

feedback from authors and vendors was that it made the page seem too busy and confusing 

how much work would it be for it to hit across the entire theme?

priorities: this will probably i mpact philosophy and political science

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ff146ff6-31a7-4aa7-b792-fbf516987125)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![image](https://user-images.githubusercontent.com/12678235/140136746-16313a5c-3d2a-4953-92c1-231e422e701a.png)
