### ISSUE TITLE
philosophy/political science - indent second/third/etc line in index

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4104]
![Screen Shot 2021-09-14 at 12 20 00 PM](https://user-images.githubusercontent.com/11299125/133305681-509224e7-51ac-437f-89f3-a839d74f9c3a.png)

updated specs here to account for indention #3217

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image (19)](https://user-images.githubusercontent.com/40228854/134175455-f842ec24-be33-40eb-a2fc-f28ee4a263b6.png)

Is it ok, or indentation should be bigger?

**Comment by lwtchu** [comment]
@wilkus27 looks great! will this tricke thru the theme? or we'll have to go book by book?

**Comment by wilkus27** [comment]
@lwtchu I made a change that impact only poli sci and philo, but I can easily modify this to apply indentation to entire cosmos theme. Do you want me to do this?

**Comment by lwtchu** [comment]
We can do this for PoliSci/Philo for now and hit the theme later.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0a65ee8d-6503-49c5-99be-676f3a3535a8)
