### ISSUE TITLE
Move styles from Rex

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4105]
Create basic files and directories for styles from Rex in `cnx-recipes` repo.

### Testing
The output css files are in [repo](https://github.com/jarosik10/rex-test-styles). It uses gh-pages to make the css file accessible:
https://jarosik10.github.io/rex-test-styles/main/webview-generic.css.

To test the styles in REX, you have to visit the page with `content-style` param set to the link of css file.

Example:
https://openstax.org/books/american-government-2e/pages/1-1-what-is-government?content-style=https://jarosik10.github.io/rex-test-styles/main/webview-generic.css

The current version of styles are inside `main` directory: `rex-test-styles/main/webview-generic.css`.
Every PR with a new set of styles will have a separate `webview-generic.css` file. 
Like: `/rex-test-styles/<pr_name>/webview-generic.css`.

**Comment by lwtchu** [comment]
closing since it looks like everything is done. let me know if should be open again
