### ISSUE TITLE
philosophy/political science - update selectors for exercises styles

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4109]
in order for the exercises to be styled correctly, please update 

tied to https://github.com/openstax/recipes/issues/92

**Comment by wilkus27** [comment]
I checked and Kendra's changes from this PR: https://github.com/openstax/cnx-recipes/pull/4080 are covering Philosophy. This is how it looks with updated version of recipe:

![image (18)](https://user-images.githubusercontent.com/40228854/133645796-1af9ab0f-a2ae-4803-9cad-7f836f7f3e38.png)

I'm leaving this issue opened for testing of Political Science.

**Comment by KarinaMendez2** [comment]
Already done for all books in cosmos theme by @kswanson33
