### ISSUE TITLE
OPS-0012 English Composition table empty column width issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4111]
The width of the blank column in the table cannot be expanded by the colwidth value. Kindly check and advise.
![colwidth1](https://user-images.githubusercontent.com/86622862/133565236-f90f9262-769d-48ab-b256-6603a4ac9dab.png)
![colwidth2](https://user-images.githubusercontent.com/86622862/133565261-1000fc38-cfd7-49eb-b3c1-d468d41db800.png)

# Bug Location(s)
collection ID: col00001
server: https://copper-anteater-egyq5vxq.ws-us15.gitpod.io/
chapter/section: 4.5
surrounding text: To help you organize you work, complete a graphic organizer like

**Comment by lwtchu** [comment]
@srm-openstax can you try it with proportions? example to follow: 

```
<colspec colnum="1" colname="c1" colwidth="1*"/>
<colspec colnum="2" colname="c2" colwidth="3*"/>
```

(3* here means 3x the proportion - that column will be 3x the width of the other columns)

**Comment by lwtchu** [comment]
For future reference, related issue for another book here https://github.com/openstax/cnx-recipes/issues/2776 

Might need to double-check that it's enabled in this style also.

**Comment by srm-openstax** [comment]
It's working fine. Thanks for your support.
