### ISSUE TITLE
OPS-0012 English Composition center align issue in Heading levels

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4112]
We have received the correction correction from customer to place title in center align. But, center value is not supported in the heading level. Kindly check and advise.
![heading_center_align1](https://user-images.githubusercontent.com/86622862/133568772-12055146-4196-49c2-bf8d-2257b42f53af.png)
![heading_center_align2](https://user-images.githubusercontent.com/86622862/133568789-a0eb3cee-22a5-40a3-a4e3-14fcb3ec7e63.png)

# Bug Location(s)
collection ID: col00001
server: https://copper-anteater-egyq5vxq.ws-us15.gitpod.io/
chapter/section: 6.4
surrounding text: Biello, D. (2007, May 25). Combatting climate change: Farming out

**Comment by lwtchu** [comment]
We do not support centering `<section>` titles throughout the library to ensure consistency. We will not be pursuing this change.
