### ISSUE TITLE
political science - feature updates

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4116]
# change to icon note #3193 

## 50/50 in 2020
- change class to `changing-political`
- change title to `THE CHANGING POLITICAL LANDSCAPE`
- color B2: `#0074BC`
- icon [cosmos-group.svg](https://drive.google.com/file/d/1FpP7B3T_RpgtH5T0tMgfWTwKKdQwSuk-/view?usp=sharing)

## Where Can I Engage?
- color P1: `#9028A3`
- icon: [cosmos-ballot.svg](https://drive.google.com/file/d/1F7EPm8sD3JYNB-Q02gktL2szbuA099sh/view?usp=sharing)

## What Can I Do? 
- color G4: `#0F4839`
- icon: [cosmos-skill.svg](https://drive.google.com/file/d/1KN_m-ik89Tw7rObrmCSD5LeK_dZ-U04c/view?usp=sharing)

# The following are condensed icon notes #3235 

## Podcast
exact same as https://github.com/openstax/cnx-recipes/issues/3586 - can we move that in here?

**Comment by Stackblocks** [comment]
- [X] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d44a4d8b-382a-4906-96ed-a4480e1cb844)
