### ISSUE TITLE
WAITING for devs to be ready to also change the class on their side: Baked styles content fixes: Change link to learning classes for Biology 2e/Concepts of Biology/AP Biology

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#4122]
@lwtchu commented on [Thu Jun 20 2019](https://github.com/openstax/content-managers/issues/890)

Currently the tag in Biology 2e for link to learning features say `interactive interactive-long`

We are looking to change it simply to `link-to-learning`.

1. First test in one module and import into Tutor to see what happens. (Try on tutor-content)
2. According to Nathan, it shouldn't change anything.
3. If it doesn't change anything, proceed with batching the change.
4. If it does do something, please open a tutor card and then proceed with batching the change.

NOTE: In AP Biology it uses the class `interactive`. There are also other LO tags. Please ignore those. I don't think they mean anything, but I rather not delete them.

---

@openstaxalina commented on [Mon Jul 08 2019](https://github.com/openstax/content-managers/issues/890#issuecomment-509290711)

@lwtchu FYI I moved this into Q3 and listed it under baked styles support: https://docs.google.com/document/d/1dhtBNlgDGml9v7bRGgfDkEQ_2rYnVpg-wHXsEMMFogI/edit#heading=h.nez9e0y34pjw

<blockquote><img src="https://lh6.googleusercontent.com/jJ1cSBo5X4_wmQ1BfyQTJN92YzgKnAy_dNkOBhcMPMXrNlQFNbYMdE4kX7G_ff3Kkck3Aw=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://docs.google.com/document/d/1dhtBNlgDGml9v7bRGgfDkEQ_2rYnVpg-wHXsEMMFogI/edit?usp=embed_facebook">2019-Q3: Quarterly KDs</a></strong></div><div>2019-Q3: Quarterly KDs Q3 Dates: July 1, 2019 - Friday, September 30, 2019  Notes on 2019-Q3 Updated Product Management Process Added Icons to Indicate Commitment or Stretch KDs Length of Quarter Major Key Deliverables (MKDs) for 2019 Key Deliverable (KD) Check-In Information Icons Statuses BIT ...</div></blockquote>

---

@lwtchu commented on [Thu Oct 03 2019](https://github.com/openstax/content-managers/issues/890#issuecomment-538124057)

I thinkw e can do this now because REX is on top of the book

---

@openstaxalina commented on [Tue Oct 08 2019](https://github.com/openstax/content-managers/issues/890#issuecomment-539536082)

Can you please add to the testing to test the before/after appearance in webview (make sure it has rebaked...you may need to do this on some server that doesn't redirect to REX) and also the PDF?  In case we need to regenerate the oer.exports PDF in March.

---

@openstaxalina commented on [Tue Oct 08 2019](https://github.com/openstax/content-managers/issues/890#issuecomment-539541031)

Update: this **will** break the oer.exports PDF.  We are going to wait to make this change until we are more certain about the timeline for baked PDF.

**Comment by lwtchu** [comment]
Closing - super old. If still needed please open a new card.
