### ISSUE TITLE
blank page with page number after chapters in spanish u-physics

### ISSUE THREAD

**Issue by Jacqueline-Yarbrough** [openstax/cnx-recipes#4124]
# blank page with page number after chapters (including preface) in spanish u-physics

What kind of issue is this? [ ] recipe [ ] styles [ ] both [X] i don't know

![Screen Shot 2021-09-22 at 11.56.18 AM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/805f692d-8ffe-4b55-9f83-bcc133e60a19)

# Does this happen for every instance? 
if the chapter ends on an odd page, the following page is always blank with a page number

# Bug Location(s)
collection ID: col33393
server: production
chapter/section: preface; chapters 1, 2, 4 – 7, 9, 14, – 17; appendices A, E – G; answer key; and index
surrounding text:

**Comment by lwtchu** [comment]
@Jacqueline-Yarbrough i think this is so that the chapters can start on the right side (odd page) of the printed book :eyes: sorry i thought you meant a separately numbered page before the TOC ...gonna close :eyes:
