### ISSUE TITLE
Add World History recipe to Kitchen

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4125]

**Comment by lwtchu** [comment]
I think this is done? Closing

**Comment by lwtchu** [comment]
Wait no jk it just didn't get moved

**Comment by ajluk** [comment]
@lwtchu The last related issue to World History was closed: https://github.com/openstax/cnx-recipes/issues/4177. Is there a need to test the entire book after it? If yes I will assign Marta to it :slightly_smiling_face:

**Comment by lwtchu** [comment]
@ajluk yes please :)

**Comment by MartaSztuka** [comment]
#### PASSED
###### Contents 
###### Preface
###### Chapter outline
###### 
###### 
###### 
###### 
###### 
######

**Comment by MartaSztuka** [comment]
#### PASSED
##### 
##### 
##### 
##### 
##### 
#####

**Comment by MartaSztuka** [comment]
@ajluk In Glossary letters are unstyled
###### Appendix A, Glossary
![Screenshot from 2021-11-19 17-16-48](https://user-images.githubusercontent.com/47241114/142656038-ac30c2a3-0763-49ee-b736-02fd8121050a.png)

#### PASSED
###### Contents
![Screenshot from 2021-11-19 17-01-08](https://user-images.githubusercontent.com/47241114/142653323-fb9074a7-1851-4a9f-86bd-4ec521120611.png)
###### Preface
![Screenshot from 2021-11-19 17-01-30](https://user-images.githubusercontent.com/47241114/142653374-6cbaeb2f-75d2-4d4c-a3ff-a4a62b90e676.png)
###### Chapter outline
![Screenshot from 2021-11-19 17-02-14](https://user-images.githubusercontent.com/47241114/142653484-aac04b51-0d69-40a6-8eef-4715845fdfa6.png)
###### Figure
![Screenshot from 2021-11-19 17-03-08](https://user-images.githubusercontent.com/47241114/142653601-62e36544-9312-438f-9b24-7e880247042f.png)
###### Table
![Screenshot from 2021-11-19 17-05-40](https://user-images.githubusercontent.com/47241114/142653963-d5afb0de-fcd1-410b-9e5e-aec3bb66075e.png)
###### Notes
![Screenshot from 2021-11-19 17-06-06](https://user-images.githubusercontent.com/47241114/142654040-d070bd2d-5c6b-4415-a169-a8eaa230cdd8.png)
![Screenshot from 2021-11-19 17-06-22](https://user-images.githubusercontent.com/47241114/142654083-c68178df-523a-4ce7-a1fd-3ac3c7d70a9d.png)
![Screenshot from 2021-11-19 17-06-41](https://user-images.githubusercontent.com/47241114/142654136-3427c1d7-da90-49d0-b382-fecf5543d519.png)
![Screenshot from 2021-11-19 17-07-02](https://user-images.githubusercontent.com/47241114/142654187-fc60b46e-65c8-4c84-9a2b-1a7fffcb45a9.png)
###### Footnote
![Screenshot from 2021-11-19 17-07-14](https://user-images.githubusercontent.com/47241114/142654251-e0061f3d-1ba6-44f3-8441-adee21cf2635.png)
###### Key terms
![Screenshot from 2021-11-19 17-08-11](https://user-images.githubusercontent.com/47241114/142654390-94ee31ac-66ab-4125-adf9-269e251c1253.png)
###### Section summary & Review questions
![Screenshot from 2021-11-19 17-08-34](https://user-images.githubusercontent.com/47241114/142654494-6d447ab5-7e86-4580-bd15-77533564b9c8.png)
###### Reflection Questions & Making Connections
![Screenshot from 2021-11-19 17-09-28](https://user-images.githubusercontent.com/47241114/142654626-fd834b04-ff46-4408-a7bf-d1a6b8bc896c.png)
###### Thought Provokers & Source Questions
![Screenshot from 2021-11-19 17-10-08](https://user-images.githubusercontent.com/47241114/142654722-780d266f-99d4-4179-a6d3-563c210d497b.png)
###### Appendix
![Screenshot from 2021-11-19 17-15-27](https://user-images.githubusercontent.com/47241114/142655531-78102ba0-33c2-43b7-8150-dfe6e3d05e12.png)
###### Index
![Screenshot from 2021-11-19 17-16-02](https://user-images.githubusercontent.com/47241114/142655653-c7e40b11-f52e-4732-9ec0-af22ff7018c0.png)

**Comment by ajluk** [comment]
I have checked and found out that the styles for h3 were missing for Appendix Glossary in cosmos shape for this part. I created a PR fixing it. Here is how it looks styled. There are also the specs visible on the screenshot: 
![image](https://user-images.githubusercontent.com/55203598/142661838-50317588-963b-4f63-adb5-e5383a29577c.png)

**Comment by MartaSztuka** [comment]
Since Glossary issue is fixed I'm closing this one.
