### ISSUE TITLE
BCA: wrong target labels

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4126]
Some of the target labels are linked to the wrong elements:

1. `<a class="autogenerated-content" href="#auto_abdf9b63-540d-4bb0-8b73-dd2be052d616_figure_01_01_Theory">` should be linked to figure `auto_abdf9b63-540d-4bb0-8b73-dd2be052d616_figure_BCA_01_01_Theory`

It's linked now to media inside figure:

![image (21)](https://user-images.githubusercontent.com/40228854/134480270-74e8fbb4-aba2-4ba6-b2e2-49849f9ddc3b.png)

2. `<a xmlns="http://www.w3.org/1999/xhtml" class="autogenerated-content" href="#auto_abdf9b63-540d-4bb0-8b73-dd2be052d616_figure_01_01_FemSupport">[link]</a>` should be linked to figure: `id="auto_abdf9b63-540d-4bb0-8b73-dd2be052d616_figure_BCA_01_01_FemSupport"`.

It's linked now to media inside figure:

![image (22)](https://user-images.githubusercontent.com/40228854/134480907-05f268ed-dda5-4f23-8351-7206561fe52e.png)

3. `<a xmlns="http://www.w3.org/1999/xhtml" class="autogenerated-content" href="#auto_abdf9b63-540d-4bb0-8b73-dd2be052d616_figure_01_01_LaborForce">[link]</a>` should be linked to figure: `id="auto_abdf9b63-540d-4bb0-8b73-dd2be052d616_figure_BCA_01_01_LaborForce"`

It's linked now to media inside figure:

![image](https://user-images.githubusercontent.com/40228854/134483201-290ccb84-8d50-405e-bb2a-0ffd0b974170.png)

4. `<a xmlns="http://www.w3.org/1999/xhtml" class="autogenerated-content" href="#auto_abdf9b63-540d-4bb0-8b73-dd2be052d616_figure_01_01_Telework">[link]</a>` should be linked to figure: `id="auto_abdf9b63-540d-4bb0-8b73-dd2be052d616_figure_BCA_01_01_Telework"`.

It's linked now to media inside figure:

![image (1)](https://user-images.githubusercontent.com/40228854/134483691-ebdb8239-af06-4ce0-bede-51914209793b.png)

5. `<a xmlns="http://www.w3.org/1999/xhtml" class="autogenerated-content" href="#figure-01-02-TCommBen">[link]</a>`. I'm not sure what is the proper id of the figure. In old recipe this link is empty.

6.  `<a xmlns="http://www.w3.org/1999/xhtml" class="autogenerated-content" href="#auto_d2af13aa-9999-4900-aca8-329915dd4d45_figure-01-03-Elmina">[link]</a>` should be linked to figure: `auto_d2af13aa-9999-4900-aca8-329915dd4d45_eip-figure-01-03-Elmina`.

It's linked now to media inside figure:

![image (2)](https://user-images.githubusercontent.com/40228854/134505235-0f54cc7d-c9cc-4253-81bf-a12b068f15f2.png)

**Comment by lwtchu** [comment]
changes pushed 8)
