### ISSUE TITLE
OPS-0012 Composition - PDF converting issue in CORGI [URGENT]

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4127]
We encountered the following issues when converting to PDF in CORGI, and the PDF was not converted. Please investigate and remedy this problem.

![Corgi](https://user-images.githubusercontent.com/86622862/134505753-0789843d-ac1d-44df-9535-76b81e463091.png)

# Bug Location(s)
collection ID: col00001
server: Gitpod: https://copper-anteater-egyq5vxq.ws-us17.gitpod.io/
           CORGI: https://corgi.openstax.org/
Job ID: 1672 
Collection id: osbooks-writing-guide/writing-guide

**Comment by lwtchu** [comment]
Can't replicate the error for job 1672 and the new generation succeeds. If there's a spot in the content that isn't rendering properly or there's other errors, please point them to us.
