### ISSUE TITLE
BCA: wrong markup of top-titled table

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4128]
Here is the top-titled table from BCA:
(`id="auto_8624d898-718e-4a61-a5c8-e57cf2745c0c_fs-idm391428576"`)

![image (3)](https://user-images.githubusercontent.com/40228854/134506913-04119c54-f632-4b74-bbb0-2766bdefef15.png)

Title that goes above the table after baking should be put into the `<thead>`. 
Here is the example of proper markup:

![image (4)](https://user-images.githubusercontent.com/40228854/134507442-b5915730-ac26-4973-ba66-2cddaee4b823.png)

**Comment by lwtchu** [comment]
just finished thissss once #4126 goes this will be pushed
