### ISSUE TITLE
World History: Broken links

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4134]
There are 5 places where the broken links can be found (they all appear in Visual Based Questions and href='#exercise/WH-Ch01-Mod01-VBQ01'):
**Chapter 1**
1.
![image](https://user-images.githubusercontent.com/55203598/134668851-199053de-ad4f-4212-acab-e318c9bae511.png)
2.
![image](https://user-images.githubusercontent.com/55203598/134669233-53b65264-2f73-40fa-8edd-c296e3d8d497.png)
3.
![image](https://user-images.githubusercontent.com/55203598/134669360-81b15271-0254-42b7-8a34-a800b71e7e1b.png)

**Chapter 2**
4.
![image](https://user-images.githubusercontent.com/55203598/134669441-529bb1a0-97f8-4a47-9cd1-8bd930392fbc.png)
5.
![image](https://user-images.githubusercontent.com/55203598/134669570-375b7c22-b707-459d-802d-f3686d2c3a6d.png)

During assembling and validating such errors are present: 
![image](https://user-images.githubusercontent.com/55203598/134670005-ab6c0ab3-fbe4-4182-a0f5-0e9289903efe.png)
![image](https://user-images.githubusercontent.com/55203598/134670671-76bb0f30-2886-4d2c-a734-091215e19ffd.png)

**Comment by lwtchu** [comment]
🤔  @ajluk  hm... i tried to redo the nickname ..let me know if there's anything else ???

**Comment by lwtchu** [comment]
Found out requires context ID doesn't exist. Fixed that and it worked!
