### ISSUE TITLE
OPS-0012 Composition - Table, Further reading and Works Cited section styles alignment issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4138]
The elements of the tables, further reading & works cited sections are not supported in the Handbook chapter. Kindly check and resolve this issue.

![H1](https://user-images.githubusercontent.com/86622862/135281889-416eb0ac-063e-4ac2-b82b-ac022d14a894.png)
![H2](https://user-images.githubusercontent.com/86622862/135282045-4dcbcf94-601b-43fe-bb64-36cffe37531d.png)
![H3](https://user-images.githubusercontent.com/86622862/135282096-f2cd3689-17b0-4c71-a08b-dab23fe757e4.png)
![H4](https://user-images.githubusercontent.com/86622862/135282124-77bdf11c-49f6-47de-b723-fbd005c8647e.png)

# Test Content Location(s)
collection ID: col00001
server: https://copper-anteater-egyq5vxq.ws-us18.gitpod.io/
chapter/section: Handbook
surrounding text: Global

**Comment by ajluk** [comment]
Per @lwtchu the table numbering in `handbook` page should be similar to the one we us in the Appendices with letter `H` in place of appendix letter. Example from World History table numbering in appendices: 
![image](https://user-images.githubusercontent.com/55203598/136619463-1a7a7953-a56f-4372-8fa1-df85e42d0b03.png)

**Comment by ajluk** [comment]
Screenshots for reference for tables in Handbook page: 
![image](https://user-images.githubusercontent.com/55203598/136625766-161ecbe0-cdbb-4585-b9cc-64772d0d8703.png)
![image](https://user-images.githubusercontent.com/55203598/136625794-73e33ec0-fd1b-4df1-8c78-d67f57449fb5.png)

**Comment by ajluk** [comment]
@MartaSztuka Resolving this issue required changes in Kitchen recipe for English Composition, so tests need to be performed on current updated `main` recipes branch in book-pipeline. To do this you need first run script `./install-submodules.sh --update` in book-pieline and then go into `recipes` catalog (`cd recipes/`): 
![image](https://user-images.githubusercontent.com/55203598/136817669-2e3456cf-733c-4fd0-9fbb-f4eddc6f63be.png)
then pull the latest changes there (by using `git pull`).

**Comment by MartaSztuka** [comment]
#### PASSED
##### Tables![Screenshot from 2021-10-18 10-42-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/19582609-93a7-4921-9d34-2fc97b859b05)![Screenshot from 2021-10-18 10-43-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b4cf1e55-f050-4ea1-9f1b-5b999d3d2425)
##### Works Cites![Screenshot from 2021-10-18 10-44-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5be18dbb-ecae-4e27-9f4a-4d10dca3f312)
