### ISSUE TITLE
Clean up cosmos theme: Check if shapes used for indentation styling can to be refactored in common one.

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4155]
Currently there are two shapes used for styling sections with indentation in cosmos theme(`ModuleWithIndentationShape`, `SectionWorksCitedShape`). Within working on #4138 another one  has been created to avoid sectors overwriting and need to add more special classes: `HandbookModuleWithIndentationShape`. It needs to be checked during the clean up if these shapes can refactored and combined as one.

**Comment by lwtchu** [comment]
@ajluk since this is merged shoudl we close it

**Comment by ajluk** [comment]
@lwtchu The PR referenced under this issue is only related one, so the issue should remain open until someone will look into the shapes mentioned in the descriptions and and refactor them if it is possible.

**Comment by lwtchu** [comment]
@ajluk just doing some clean up - i think we missed this 🤔 do you remember what this card was for

**Comment by lwtchu** [comment]
@ajluk okay i'll move this to a later sprint

**Comment by ajluk** [comment]
During working on #4289 a part of the clean up `ModuleWithIndentaion` shapes has been done. The HanbookModuleWithIndentaion shape has been removed and the EoC `ModuleWithIndentaionShape` has been moved out from eoc files to module files to clarify  it can be also used by sections other than EoC (f.ex. Hanbook sections in English Composition ). Two shapes using indentation remained untouched because they contain inner elements like titles (SectionWorksCitedShape): 
![image](https://user-images.githubusercontent.com/55203598/145192151-390cc652-01e2-4087-991e-aea7ecd22e5f.png)
 and chapter area(EobReferencesWithoutNumberingShape) :
![image](https://user-images.githubusercontent.com/55203598/145192237-8604748e-6988-4e87-a51b-dd9ff4ba2c81.png)
 During working on this issue it will be needed to analyze if we can create one generic shape for EoB and EoC modules with indentation or it will be better to keep the remaining 3 shapes as they are.

**Comment by LostMojo** [comment]
`HandbookModuleWithIndentationShape` no longer exists, and it looks like the common components in the other two styles will be handled by the big refactor!
