### ISSUE TITLE
Table with orphaned header in English Composition 

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4163]
During testing English Composition for #3852 Marta has found a table with orphaned header: 
![image](https://user-images.githubusercontent.com/55203598/138481179-d9acd654-3a02-45e9-b7d4-2dc623a54aae.png)
The issue needs to checked if it can be fixed library-wide.

**Comment by ajluk** [comment]
@lwtchu I checked that the rule for non braking pages after table headers has been already added in the code by BrritanyJ a while ago: 
![image](https://user-images.githubusercontent.com/55203598/148050811-baade94c-c263-43d5-bb76-9430b199edbc.png)
The reason this table is breaking after the "header" is that it is not a actually a header but a regular `tr` with `td`s but the text in the cells has been put in `strong` tags so visually it looks like a header. It is rather a content issue I guess: 
![image](https://user-images.githubusercontent.com/55203598/148051091-5d9f2749-cc08-43d1-809e-737eb3e3664e.png)

**Comment by lwtchu** [comment]
@ajluk OH i should've checked. Thank you for letting me know

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #2489](https://github.com/openstax/content-managers/issues/2489) via [**ZenHub**](https://www.zenhub.com/)
