### ISSUE TITLE
Add Accounting vol1,2 to Kitchen

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4165]

**Comment by ajluk** [comment]
@MartaSztuka I have already found out that the headers need a fix in Appendices, but if there is anything else please let me know :slightly_smiling_face: 
![image](https://user-images.githubusercontent.com/55203598/144271597-6d8757a8-63d7-4494-9e81-83e514fe0a88.png)

**Comment by ajluk** [comment]
@MartaSztuka Testing will be postponed until content for vol1 will be ready.

**Comment by ajluk** [comment]
@MartaSztuka The content is ready and available on github: https://github.com/openstax/osbooks-principles-accounting-bundle
There are two collections under this adress to test.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Principles of Accounting 1 - Financial Accounting
###### Contents
![Screenshot from 2022-01-12 12-45-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2eb22651-65fd-497e-ab94-80d846732301)![Screenshot from 2022-01-12 12-45-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9509be0f-3513-42a5-8ac7-e5c520c7807b)
###### Preface
![Screenshot from 2022-01-12 12-45-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9a19baf7-9ae3-4a8d-86e8-7c65ec670ddb)
###### Chapter outline
![Screenshot from 2022-01-12 12-46-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8a27f51c-f016-4a38-b4cf-8cfd7a241554)
###### Figure
![Screenshot from 2022-01-12 12-46-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4c92cc84-c118-46e0-98a6-e2dbe479c14e)
###### Table
![Screenshot from 2022-01-12 12-47-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dcfad0e2-aff3-4414-a3ba-93ec24b236fd)
###### Notes
![Screenshot from 2022-01-12 12-47-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/99cce4f4-ce18-4970-bd2c-a08572710afd)![Screenshot from 2022-01-12 12-48-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/352da20f-2182-4904-afc6-44f16cf3de8d)
###### Footnote
![Screenshot from 2022-01-12 12-49-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/86d101d8-7ed5-4381-9691-da40080400f2)
###### Link to Learning
![Screenshot from 2022-01-12 12-51-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6151f34b-1c4c-483f-b22e-d1059686f501)
###### Key terms
![Screenshot from 2022-01-12 12-49-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4fbd1a5f-ce46-4174-9e60-dbe22aba658c)
###### Summary
![Screenshot from 2022-01-12 12-50-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/25040c86-c043-438a-8a9b-b52bb9765d54)
###### Multiple Choice
![Screenshot from 2022-01-12 12-50-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3aac7627-a947-43be-b79b-66723eac572f)
###### Exercise Sets
![Screenshot from 2022-01-12 12-52-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d75003c9-8860-4efb-a2f3-ca642f422b60)
###### Thought Provokers
![Screenshot from 2022-01-12 12-53-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/60a8421b-da17-424e-9365-feaf9a4aebaa)
###### Appendix
![Screenshot from 2022-01-12 12-54-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/06e1aa93-97d9-42a9-855e-85f7510eddfd)
###### Answer Key
![Screenshot from 2022-01-12 12-55-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/13dd2202-6c42-433d-bc8a-3228ba553ca9)
###### Index
![Screenshot from 2022-01-12 12-55-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3cd7054d-2ef6-4618-ab02-7ab22fb9d748)

**Comment by MartaSztuka** [comment]
#### PASSED
##### Principles of Accounting 2 - Managerial Accounting
###### Contents
![Screenshot from 2022-01-12 13-01-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9c3724d8-9632-4611-9f5f-94376eddac49)![Screenshot from 2022-01-12 13-00-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cf9e65bf-4d99-4568-abdd-4a70ef1d2e35)
###### Preface
![Screenshot from 2022-01-12 13-01-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9d79338c-66b4-4ac0-9bd5-6b1e651b2dc3)
###### Chapter outline
![Screenshot from 2022-01-12 13-04-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/605cbd01-1f9e-4883-b6cd-af71023da23e)
###### Figure
![Screenshot from 2022-01-12 13-06-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7552869b-5097-4614-aa72-d4618a834b46)
###### Table
![Screenshot from 2022-01-12 13-07-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/22a87b61-2c4e-4d4c-95cd-bdcf3637ede2)
###### Notes
![Screenshot from 2022-01-12 13-08-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/84531f92-0e34-414f-971a-3bccb591e308)![Screenshot from 2022-01-12 13-08-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/57989673-9c67-43c1-b07e-537e1dbed93f)![Screenshot from 2022-01-12 13-07-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5a5e3fa6-c40d-4643-9477-fdfa90e3d732)
###### Footnote
![Screenshot from 2022-01-12 13-05-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/de1e6333-69c9-49a8-962d-b6a093108248)
###### Link to Learning
![Screenshot from 2022-01-12 13-12-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4a282f76-1b4b-4494-8014-9fcf0fb46558)
###### Key terms
![Screenshot from 2022-01-12 13-13-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/98e202af-07dd-4e2b-bb14-2f30df9dd65b)
###### Summary
![Screenshot from 2022-01-12 13-15-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f41a93b6-6576-46de-8df4-ea11b6b26c23)
###### Multiple Choice
![Screenshot from 2022-01-12 13-16-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/44b0d32e-323d-4bb8-bfb8-8d0fac3ff700)
###### Exercise/Problem Sets
![Screenshot from 2022-01-12 13-17-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b69103e9-dee6-469d-97e7-2e13028d4b58)![Screenshot from 2022-01-12 13-17-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/31747f3a-bf52-4726-b62b-25473a56fdc0)
###### Thought Provokers
![Screenshot from 2022-01-12 13-19-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/215f6890-4916-443e-807d-8205a9e062ae)
###### Appendix
![Screenshot from 2022-01-12 13-19-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4299220e-3060-4bfa-b126-339e9fcb0abb)
###### Answer Key
![Screenshot from 2022-01-12 13-20-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bb0369b3-9107-45fd-bc81-7cc03dc9cd89)
###### Index
![Screenshot from 2022-01-12 13-21-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5aed9277-a62a-4a0e-9ead-319ad55110df)
