### ISSUE TITLE
After common instruction questions are need to be indented

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4170]
@mps-openstax commented on [Mon Oct 25 2021](https://github.com/openstax/osbooks-contemporary-math/issues/4)

After common instruction questions are need to be indented. Please below snaps for reference and suggest. These are linked from exercises.

**Input file:**
<img width="530" alt="input3" src="https://user-images.githubusercontent.com/88098452/138703973-35010c23-0c08-45b3-9c76-be3499986fc3.PNG">
:
**Output required:**
<img width="576" alt="output3" src="https://user-images.githubusercontent.com/88098452/138704184-95b874f8-6ccf-4000-9ffb-7f2c7fea8cad.PNG">

**Comment by lwtchu** [comment]
# Acceptance Criteria

Can we indent sub questions within a MPQ? Same indention width as a list.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ce5709eb-5f7b-4924-a75a-857e4d1f4f14)

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/df6cc165-cbd9-4e51-a392-9529a5b55a7e)
