### ISSUE TITLE
Check Your Understandings are not rendering properly as required.

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4171]
@mps-openstax commented on [Mon Oct 25 2021](https://github.com/openstax/osbooks-contemporary-math/issues/3)

Question numbers are not appearing. Please see the details below for reference.

**Input file:**
<img width="522" alt="input2" src="https://user-images.githubusercontent.com/88098452/138701331-e6ea862a-2b5a-4890-ac35-ece3c8b44e56.PNG">
:
**Output file:**
<img width="573" alt="output2" src="https://user-images.githubusercontent.com/88098452/138701437-838bc511-d284-4ac4-ba09-447e3d372b85.PNG">

**Comment by kswanson33** [comment]
One thing that would really help is if these sections were given a class or something that I could target with a selector. Could this be done in the content? cc @lwtchu

**Comment by lwtchu** [comment]
@kswanson33 i can do it in the test content - if successful i'll update the tagging legend and let them know

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2021-11-15 11-38-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2953b568-4866-4efb-aab3-5aac8e3437bb)
