### ISSUE TITLE
world history - replace header color

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4173]
Documentation #3164
Replace red with B2: `#0074BC`

same with what we did in philo and poli sci :( no one seems to like the red 

please get the table/figure numbers also 
Replace the red with B1: `#38568A` (#3903)

**Comment by MartaSztuka** [comment]
@lwtchu Headers have right colour (#0074BC) but Figures and Tables captions are in different blue (#38568A) is that ok?
##### table and figure
![Screenshot from 2021-11-02 11-52-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7c79b830-1fa0-46bc-ac73-fe631117dd0d)![Screenshot from 2021-11-02 11-52-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bde1af58-eee7-4e3b-830a-715eca5bc3f6)
##### headers and numbers
![Screenshot from 2021-11-02 11-46-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6b2cdb03-9784-4dba-af2f-dbce9b2d0de9)![Screenshot from 2021-11-02 11-46-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fc717483-2fb4-4f84-971e-3057e2ee64a6)![Screenshot from 2021-11-02 11-47-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/17045b0d-4048-401d-926c-1f91ff2c839c)

**Comment by Stackblocks** [comment]
Table and Figure header are still showing as off-color.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/160acb06-8b19-4c58-816f-464764388daf)

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/11e6143c-dc79-4c4e-93c3-5e98ee943133)

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5b1ef152-a15f-47fc-b344-5c5697683187)

**Comment by Stackblocks** [comment]
@LostMojo When you get a moment can you link the associated PR to this issue so we can have the record of them being connected?

**Comment by LostMojo** [comment]
#4191 has associated work

**Comment by kswanson33** [comment]
@lwtchu I think this is what was asked for but can you confirm :eyes:

**Comment by Stackblocks** [comment]
Based on that new info this looks good 😂

Moving on to Regression Testing
