### ISSUE TITLE
world history - italics in chapter titles

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4174]
![Screen Shot 2021-10-25 at 12 42 52 PM](https://user-images.githubusercontent.com/11299125/138744176-f1486ff7-c69a-4957-9766-7ddf57c335cc.png)
![Screen Shot 2021-10-25 at 12 44 11 PM](https://user-images.githubusercontent.com/11299125/138744334-3a6d9247-1685-435e-9aa8-9c983ac7c9a8.png)

Pax Mongolia should be italicised. I wonder if this would be better in POET? Is there something we need to fix on the recipe side?

**Comment by lwtchu** [comment]
Targeting Jan 2022 to give CE tech some space to complete other things.

**Comment by LostMojo** [comment]
So, the text inside the <emphasis></emphasis> tags has to be enabled by something in the pipelines, which is why we aren't seeing the text in italics. It's with CE right now.

**Comment by openstaxalina** [comment]
Confirmed with WW, Anthony, Kelsey that we can avoid italics in chapter titles in World History. _Pax Mongolica_ was the only instance. However, italics will be much more frequent in section/module titles. I will check w/ Neil/Larissa that this is still permitted in the new editor.

Closing this issue.
