### ISSUE TITLE
world history - update dueling voices feature colors

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4175]
Original issue: https://github.com/openstax/cnx-recipes/issues/3635
- class: `dueling-voices`

update colors to: Alternate color schema 5 (purple) from https://github.com/openstax/cnx-recipes/issues/3194
top bar: P2: `#651C72`
bottom box: P3: `#F2E8F4`

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/6ecd4b60-0868-4408-87ee-d5dd4e3c778c)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2021-11-02 11-42-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c1d48886-9c78-44ad-9e19-99a70505885a)
