### ISSUE TITLE
world history - adjust key term spacing

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4176]
we did this work for political science/philosophy here https://github.com/openstax/cnx-recipes/issues/4102

can we have this be applicable across theme?

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/67f96d20-3c39-4e8a-b105-255a21355cd8)
