### ISSUE TITLE
english composition/writing guide - orphaned comma in index

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4180]
![image.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/1da47efc-2726-48ba-aff7-99c9ffab7756)

i  think we've encountered this before (but i can't find a ...card), is this fixable? if not, it's not a super high priority.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/94c43c49-75a1-4758-9c1a-4ee8b56dc53b)
