### ISSUE TITLE
OPS-0012 Finance - Excel code center alignment

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4183]
Some of the excel codes appeared in center alignment in the provided MS file. So, we have treated as "equation" element, output is generated as per the input MS.

But, the below mentioned occurrence is appeared italic formatting in the excel code, emphasis elements didn't support under the "equation" element. So, we have treated as 'code display="block"' element. There is no specific style in the tagging legend for center align. How to align the excel codes such that they are in the center of the page. Kindly check and advise.

![Excel_Code_Input](https://user-images.githubusercontent.com/86622862/139032931-6131e552-22f1-49dd-b93c-fd63bd89bdc3.png)
![Excel_Code_XML](https://user-images.githubusercontent.com/86622862/139032968-67bdcd6d-abe1-449f-a1a1-6b0c050687e7.png)
![Excel_Code](https://user-images.githubusercontent.com/86622862/139033007-8e2fa255-4b72-4e89-819a-ae24dbca48c7.png)

# Bug Location(s)
collection ID: col00006
server: https://yellow-falcon-nrfjf7qa.ws-us18.gitpod.io/
chapter/section: Chapter 14/Section 3
surrounding text: To calculate the slope of the regression model, use the Excel command

**Comment by lwtchu** [comment]
@srm-openstax I have updated the tagging legend and added row 54 for the mark up. You will need to add this class to any code snippet that you would like centered. `<code class="centered-code">`

Please remove the items in the `<equation>` tag

**Comment by lwtchu** [comment]
@Stackblocks this requires content changes - we COULD test locally - but we can also wait for the changes SRM will do

**Comment by srm-openstax** [comment]
@lwtchu We have updated the center code elements for excel commands on GitPod, based on the instruction.

      <code class="centered-code">=CORREL(C3:C14,B3:B14):   0.947</code>
      <code class="centered-code">=SLOPE(C3:C14,B3:B14):    0.113</code>
      <code class="centered-code">=INTERCEPT(C3:C14,B3:B14): 	-1,496.340</code>

**Comment by lwtchu** [comment]
@srm-openstax thank you :)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/410fbb6e-eb41-4119-94d3-9a7216c1bfb5)

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/2ed34237-6eb1-4a9b-af8f-bef895c5b424)
