### ISSUE TITLE
OPS-0012 Finance - Span styles are didn't support the Web view

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4185]
Some of the span styles aren't support in the Web view. So, I have attached the screenshot for your reference. Kindly check and resolve this issue.

<span class="red-code">
<span class="blue-code">
<span class="primary-function">CF</span>
<span class="secondary-function">CF</span>

![Primary-function_Input](https://user-images.githubusercontent.com/86622862/139043023-f280a4c4-3456-49d2-bbc4-2177e70803b8.png)
![primary-function](https://user-images.githubusercontent.com/86622862/139043045-91c363db-bcf9-4aaa-88a1-047f026e8deb.png)
![Software-code_Input](https://user-images.githubusercontent.com/86622862/139043093-111fb99b-1aed-4132-865e-233bebb5ef8e.png)
![Software-code](https://user-images.githubusercontent.com/86622862/139043107-9b1ec3c2-15bc-44ee-8629-735d6bd9b0ec.png)

# Bug Location(s)
collection ID: col00006
server: https://yellow-falcon-nrfjf7qa.ws-us18.gitpod.io/
chapter/section: Chapter 14/Section 1
surrounding text: Calculator Steps for Finding the Relationship between Nike Stock Price and Value of

# Bug Location(s)
collection ID: col00006
server: https://yellow-falcon-nrfjf7qa.ws-us18.gitpod.io/
chapter/section: Chapter 14/Section 6
surrounding text: The results can also be saved as a formula and called “model” using the following R command.

**Comment by openstaxalina** [comment]
This is being handled with these two cards:

https://github.com/openstax/unified/issues/1802
https://github.com/openstax/unified/issues/1801
