### ISSUE TITLE
corn theme - table of contents toc missing design

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4186]
![Screen Shot 2021-10-28 at 8 40 52 AM](https://user-images.githubusercontent.com/11299125/139267740-50bb326f-77b7-4e0c-8431-e9a9e288d558.png)

The lil grey bar next to the modules is missing.... 
Documentation - should look like this #2060 

content in screenshot: osbooks-introduccion-estadistica-bundle/introducción-estadística 
should test with books in corn theme just to make sure: precal, prealgebra, statistics, contemporary math

priorities for testing: contemporary math, precal

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/88f38e06-748f-45d0-af62-0596783e3bd9)
