### ISSUE TITLE
OPS-0012 Philosophy - Quote style didn't support in Output

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4188]
We have treated the quote paragraph as per the tagging legend <quote><para></para></quote>. But, view doesn't appear in the output PDF. Kindly check and resolve this issue.

![blockquote_tagging_legend](https://user-images.githubusercontent.com/86622862/139671855-ade75588-8a5c-4eb5-ab2c-fe2fa081ee9c.png)
![blockquote_XML](https://user-images.githubusercontent.com/86622862/139671867-22e53de2-2427-4c41-8a75-e5b3a526f706.png)
![blockquote_output](https://user-images.githubusercontent.com/86622862/139671880-c3de796e-4fa2-41dd-9101-aa86242ba864.png)

# Bug Location(s)
collection ID: col00005
server: https://coffee-grouse-ulafn81g.ws-us18.gitpod.io/
chapter/section: Chapter 1/Section 3
surrounding text: Someone will say: “Yes, Socrates, but cannot you hold your tongue,

**Comment by lwtchu** [comment]
@srm-openstax do you know if this will be needed in any other book?

**Comment by lwtchu** [comment]
# Acceptance Criteria
Documentation: #2749 (from cardboard theme but we can apply spacing/functionality to this)

**Comment by srm-openstax** [comment]
> @srm-openstax do you know if this will be needed in any other book?

Yes. This style applied in English composition. Also the alignment was correctly in the output file.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a2c6c5f0-0ebd-460a-b8cf-a15ba1cc5a79)
