### ISSUE TITLE
0012-Philosophy Summary section heading style issue in output

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4189]
We have received the below correction from customer. We have treated the summary section as per the tagging legend. But, view doesn't appear in the output PDF. Kindly check and resolve this issue.

**Summary headers should match the header font styles used in other EOC sections.**

![Summary_Tagging_Legend](https://user-images.githubusercontent.com/86622862/139673474-99b51271-57a5-4065-b6dc-a9231d4733a7.png)
![Summary_XML](https://user-images.githubusercontent.com/86622862/139673494-07786bb5-1ae1-4893-a739-4c64f40e3b86.png)
![Webview](https://user-images.githubusercontent.com/86622862/139673513-2fc58ab8-dd26-4727-a290-9976f2d32f35.png)

# Bug Location(s)
collection ID: col00005
server: https://coffee-grouse-ulafn81g.ws-us18.gitpod.io/
chapter/section: Chapter 1/Section 4
surrounding text: of who you are and what your place is in the world.

**Comment by lwtchu** [comment]
@srm-openstax I've updated the note in the tagging legend with "These should be placed in the respective section's module and they will be move by the code to the end." 

Could you try that please?

**Comment by srm-openstax** [comment]
@lwtchu We have tried as per the tagging legend. We think the output is correctly now. Please see the below screenshot. Kindly check and advise.

![Summary_output_updated](https://user-images.githubusercontent.com/86622862/140020982-a2129cc4-3c2e-45d4-814c-a9960714b296.png)

**Comment by lwtchu** [comment]
@srm-openstax What is the issue you are trying to solve? The screenshot looks right to me.

**Comment by srm-openstax** [comment]
We have moved the summary contents to respective section according to the tagging legend. But we have received the below correction from the customer. Kindly check and resolve.

![summary_correction](https://user-images.githubusercontent.com/86622862/141063790-bcc98057-2c02-4705-ab8c-2653b8609685.png)

**Comment by lwtchu** [comment]
![Screen Shot 2021-11-12 at 1 33 00 PM](https://user-images.githubusercontent.com/11299125/141524448-b8428d2c-beb0-4645-9c73-3be4d5a77e04.png)

@srm-openstax the screenshot attached is a recent PDF generated 3 days ago, job 2246. Could you check there and see if it's resolved? I can't replicate this issue.

**Comment by srm-openstax** [comment]
@lwtchu Yes. The issue has been resolved. Thanks for your support.
