### ISSUE TITLE
0012-Philosophy end of chapter content order didn't support in output

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4190]
We have received the following corrections from the customer. We have followed the below order in the CNXML file. But, the output file does not come in this order.

**End of chapter content should appear in the following order:
Summary
Key Terms
Review Questions
Further Reading
References

Please fix so that Review Questions and Further Reading are above References.**

# Bug Location(s)
collection ID: col00005
server: https://coffee-grouse-ulafn81g.ws-us18.gitpod.io/
chapter/section: Chapter 1/Section 6
surrounding text: who you are and what your place is in the world.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/85bc4951-aa1e-4467-b0ec-cafbea54fa80)

**Comment by srm-openstax** [comment]
@Stackblocks EOC order it is still not coming as expected in the PDF file. Kindly see the below screenshot.

![Philosophy_EOC](https://user-images.githubusercontent.com/86622862/143867745-624a764d-b037-4cdd-9f74-ccb9eebf9dbe.png)

**Comment by lwtchu** [comment]
@srm-openstax We will notify you when it is actually out on CORGI production via email.

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/50a6bc3b-d87f-4b02-855c-2f44148245e9)
