### ISSUE TITLE
OPS_0012-Political Science styles didn't support in output (Introduction image, Footnotes & Summary heading)

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4194]
We have faced the below style issues in output. Kindly check and resolve.

We have coded the introduction page image [figure class="splash"] according to the tagging legend. But, output didn't convert properly.
![Introduction_XML](https://user-images.githubusercontent.com/86622862/139801196-77f4fafd-85a6-48c4-8ccb-9c6bc0b1b5d5.png)
![Introduction_Output](https://user-images.githubusercontent.com/86622862/139801221-12224e3d-dccc-4beb-8393-8cf2eb2f2c60.png)

We have coded the footnotes [footnote] according to the tagging legend. But, output didn't convert properly.
![footnote_input](https://user-images.githubusercontent.com/86622862/139801134-9944ff3d-0179-4884-a708-0e91824025a8.png)
![footnote_output](https://user-images.githubusercontent.com/86622862/139801143-4ed82901-c7bc-49d9-bcdd-123238d3474a.png)

We have coded the summary headings according to the tagging legend. However, an unnecessary section title is created in the output PDF.
![summary_input](https://user-images.githubusercontent.com/86622862/139801263-4306fbbd-7cd5-4835-9ee5-06f998f46c37.png)
![summary_output](https://user-images.githubusercontent.com/86622862/139801305-6e983a9c-2cd5-4978-ad73-efdfdf7cf7ac.png)

# Bug Location(s)
collection ID: col00000
server: https://plum-narwhal-acs1o54u.ws-us17.gitpod.io/
chapter/section: Chapter 1/Introduction
surrounding text: Barbara Mikulski (credit: “Goddard Congressional Visit”

collection ID: col00000
server: https://plum-narwhal-acs1o54u.ws-us17.gitpod.io/
chapter/section: Chapter 1/Section 1
surrounding text: “Social Impact,” About AARP, AARP, accessed March 1,

collection ID: col00000
server: https://plum-narwhal-acs1o54u.ws-us17.gitpod.io/
chapter/section: Chapter 1/Section 6
surrounding text: 8.1 An interest group is an organized collection of individuals

**Comment by lwtchu** [comment]
@srm-openstax For the splash/footnote it might be related because footnotes isn’t supported for this template. We’ll have to enable it.
For the Summary - These should be placed in the respective section’s module and they will be move by the code to the end. - The tagging legend has been updated.


I also separated out the footnote issue and will reserve this for the Summary Issue

#4196

**Comment by srm-openstax** [comment]
@lwtchu : We have coded summary section as per the updated tagging legend. So, please ignore the summary section issue.
And also, we have updated the introduction page issue in our end. Now, this issue has been resolved. So, we have closed this ticket. Thanks for your support.
