### ISSUE TITLE
political science - supporting footnotes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4196]
from #4194

We have coded the introduction page image [figure class="splash"] according to the tagging legend. But, output didn't convert properly.
![Introduction_XML](https://user-images.githubusercontent.com/86622862/139801196-77f4fafd-85a6-48c4-8ccb-9c6bc0b1b5d5.png)
![Introduction_Output](https://user-images.githubusercontent.com/86622862/139801221-12224e3d-dccc-4beb-8393-8cf2eb2f2c60.png)

We have coded the footnotes [footnote] according to the tagging legend. But, output didn't convert properly.
![footnote_input](https://user-images.githubusercontent.com/86622862/139801134-9944ff3d-0179-4884-a708-0e91824025a8.png)
![footnote_output](https://user-images.githubusercontent.com/86622862/139801143-4ed82901-c7bc-49d9-bcdd-123238d3474a.png)

# Acceptance Criteria

I think the splash issue has something to do with the footnote - the other splashes in the book works.

**Comment by Stackblocks** [comment]
Footnotes are present, but are being displayed inline.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/979ecb55-1ba1-4f79-bbf9-d75962ac7930)

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/2ed34237-6eb1-4a9b-af8f-bef895c5b424)
