### ISSUE TITLE
Additive Manufacturing - style Chapter Outline

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4198]
Add styles for Chapter Outline:

![image](https://user-images.githubusercontent.com/40228854/140324145-5e397bc6-48db-4b18-9f25-89ab2a1ddbec.png)

It was hard coded before. It's added in new kitchen recipe.

Specs for Chapter Outline: https://github.com/openstax/cnx-recipes/issues/2189

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2021-11-05 11-39-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0c369ad9-97c2-49d8-9258-1f42b5f1ab71)
