### ISSUE TITLE
Additive Manufacturing - style injected solutions

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4201]
Specs: https://github.com/openstax/cnx-recipes/issues/2632

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2021-11-15 10-40-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3fc51bb6-6a66-4a59-9295-52cbeab6c2ef)
