### ISSUE TITLE
OPS-0012 Anthropology horizontal figures alignment issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4212]
Two images are in the input file within an image number. We have coded it as mentioned in the CNXML manual file. However the alignment did not come up properly in the output file. Kindly check and resolve this issue.

**Sample coding in CNXML guide:**
![Subfigure_Example](https://user-images.githubusercontent.com/86622862/141451676-6de9cd8a-5255-4794-8291-e1b261c7e78e.png)

**Sample Output:**
![Subfigure_Example_Output](https://user-images.githubusercontent.com/86622862/141451734-5b00f59a-97f9-46be-8afa-e55a7c729154.png)

**Input MS:**
![Subfigure_input](https://user-images.githubusercontent.com/86622862/141451615-59d8e81a-9679-4e2e-8146-f74ede6b49cd.png)

**CNXML coding in POET:**
![Subfigure_coding](https://user-images.githubusercontent.com/86622862/141451861-01531e34-0185-43e5-b6e6-2d63095294ca.png)

**Output PDF:**
![Subfigure_output](https://user-images.githubusercontent.com/86622862/141452062-53f4629c-d935-4f2e-b7a2-eb26e3de8db9.png)

# Bug Location(s)
collection ID: col00002
server: https://teal-flea-z00dgejm.ws-us18.gitpod.io/
chapter/section: Chapter 10/Section 4
surrounding text: the U.S.-Mexico border wall at Nogales, Arizona, in February

**Comment by lwtchu** [comment]
@srm-openstax We do not support horizontal or subfigure mark up. Please create it as one piece of art and label it on the art piece. 

Example, Figure 1.7 in our American Government 3e title: https://openstax.org/books/american-government-3e/pages/1-2-who-governs-elitism-pluralism-and-tradeoffs

**Comment by srm-openstax** [comment]
@lwtchu Thanks a lot for your suggestion.
