### ISSUE TITLE
OPS-0012 Anthropology interactive file hidden issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4213]
We have inserted the interactive file according to the instruction manual. But, it is not shown in the output PDF. Kindly check and resolve this issue.

**CNXML Coding:**
      <media alt="atoms_isotopes">
      <iframe width="660" height="371.4" src="../../media/Interactive/anthropology_chapter02_case_study_content_only/index.html"/>
      </media>

# Bug Location(s)
collection ID: col00002
server: https://teal-flea-z00dgejm.ws-us18.gitpod.io/
chapter/section: Chapter 2/Section 1
surrounding text: decay known; exchange with atmosphere and productions rates constant

**Comment by lwtchu** [comment]
Tied to #4016 #4072. This will not be available until we release the functionality to support interactives. It should be coming within the next week or so.

**Comment by lwtchu** [comment]
Cleaning cards. Other teams are building the functionality. Closing this card as it's been published without the interactives already.
