### ISSUE TITLE
OPS-0012 Finance - Multiple Choice questions alignment issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4215]
We have received the below alignment issues for Question section from customer. Kindly check and resolve this issue.

**Global - in online/HTML version, in all Multiple Choice  there's an extra space between the number and the period

In the PDF "Multiple Choice" section, there are two horizontal alignment issues [in all 11 problems]
a) the alphabetic answer choices should not be further flush left than the problem numbers;
b) within the answer choices, they should be equally horizontally aligned (currently the third choice, i.e. letter c) doesn't align with a, b, and d choices** 

![received_corrections](https://user-images.githubusercontent.com/86622862/141776343-09d46e32-e017-45ea-ac34-8eec0cc55ee0.png)

# Bug Location(s)
collection ID: col00006
server: https://yellow-falcon-nrfjf7qa.ws-us18.gitpod.io/
chapter/section: Chapter 14/Section 6
surrounding text: and values of the dependent variable plotted on the

**Comment by lwtchu** [comment]
# Acceptance Criteria 
Related work found here #4090 - please make sure lists in injected exercises follow the same padding as the other titles.

**Comment by wilkus27** [comment]
### Information for tester

Changes from PR affect lists from injected exercises in all books from Cardboard theme.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f0e6b0bf-0834-4fca-88fb-323f5ca2de44)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f872670f-c5c2-414a-9f05-090aa0a2c629)

**Comment by MartaSztuka** [comment]
#### PASSED
##### Finance
![Screenshot from 2021-11-16 16-37-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/97955533-0be5-487e-bcc4-684bbbaed9c2)
##### BCA
![Screenshot from 2021-11-16 17-04-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e6cc5c82-7bcb-4d49-bda0-c874ba320d04)
