### ISSUE TITLE
OPS-0012 Finance - Video activity questions space issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4216]
We have received the below corrections from customer. Kindly check and resolve this issue.

**In HTML version, delete extra space between "1" and period**

![Video_activity](https://user-images.githubusercontent.com/86622862/141777451-a766e811-9abb-426d-b201-d2b789294c24.png)

# Bug Location(s)
collection ID: col00006
server: https://yellow-falcon-nrfjf7qa.ws-us18.gitpod.io/
chapter/section: Chapter14/Section 6
surrounding text: Simple Linear Regression

**Comment by ajluk** [comment]
@lwtchu I have checked and there is no additional space visible between the number and the dot in the current content in locally generated html and pdf  files: 
![image](https://user-images.githubusercontent.com/55203598/148245267-dc943343-f18b-40a0-8339-477353c5cfd2.png)
![image](https://user-images.githubusercontent.com/55203598/148245431-2d6a75b0-abb9-4b71-8390-3656b82fb61e.png)

**Comment by lwtchu** [comment]
@ajluk sorry it was only on the label - but it's a webview issue

**Comment by lwtchu** [comment]
![Screen Shot 2023-01-23 at 1 22 25 PM](https://user-images.githubusercontent.com/11299125/214130609-b485ff27-a494-4d03-956c-3514e1a7b8a9.png)
verified fixed on webview
