### ISSUE TITLE
OPS-0012 Finance - Video activity questions number reordering issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4217]
We have received the below question number reordering issue from customer. Kindly check and resolve this issue.

**1.    (Make this correction also in HTML and ensure no extra space between number and period.)**

![video_activity1](https://user-images.githubusercontent.com/86622862/141778183-6280cc30-6f15-475c-9043-8af0e1d513c6.png)

# Bug Location(s)
collection ID: col00006
server: https://yellow-falcon-nrfjf7qa.ws-us18.gitpod.io/
chapter/section: Chapter 14/Section 6
surrounding text: How to Calculate Correlation for Stocks, Bonds, and Funds

**Comment by lwtchu** [comment]
@srm-openstax the numbers are auto injected and there is no space between the number and period - could they point out where they are seeing this?

**Comment by lwtchu** [comment]
@srm-openstax Since this is regarding the webview and not the PDF, I will be closing this and directing my team to #4216
