### ISSUE TITLE
cardboard theme - table of contents TOC broken 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4218]
![Screen Shot 2021-11-15 at 9 59 45 AM](https://user-images.githubusercontent.com/11299125/141816473-23e91fde-cdf7-41ce-8256-654a9d2e752f.png)
Similar issue to #4186. The styling is missing the little bar in the modules and such.
Documentation #1740 

This content is from Finance https://github.com/openstax/osbooks-intro-finance/

**Comment by MartaSztuka** [comment]
#### PASSED
###### Astronomy
![Screenshot from 2021-12-01 15-06-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d6fb0d45-aa34-44ea-88a3-e3ce8968b891)![Screenshot from 2021-12-01 15-06-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fc464441-68dd-4326-ac7d-19503c22e5b5)
###### BCA
![Screenshot from 2021-12-01 15-08-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ddb0217f-a88c-42cc-adb4-33fb3db38522)
###### Finance
![Screenshot from 2021-12-01 15-10-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cac1e89a-c9a8-45f6-b12b-d01e33ff8787)
