### ISSUE TITLE
Computer Science - Review Questions

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#4229]
Answer lists stick out i Review Questions
![Screenshot from 2021-11-17 11-45-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2c952553-967f-4b1c-9425-ec022afb4043)

**Comment by wilkus27** [comment]
This problem appears in PDF baked with old recipe. There are some problems with validation when baking in book pipeline with new recipe. When that be fixed, check whether problem with Review Questions still exists.

**Comment by lwtchu** [comment]
@wilkus27 i'll take a look next week 🤔  and try to generate on corgi and fix errors

**Comment by ajluk** [comment]
The problem still persist after generating pdf in book-pipeline: 
![image](https://user-images.githubusercontent.com/55203598/149153392-c10bf9d0-cdc9-48b7-a981-76e1048916df.png)

**Comment by ajluk** [comment]
@lwtchu I noticed that the exercises are also unnumbered, I will add numbering while working on this issue.

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/149187339-7ef8f911-88af-4e0e-a40a-4159e09f2885.png)

**Comment by ajluk** [comment]
@lwtchu I have noticed that there is an empty page after Chapter Review title, but it was happening before my changes within this PR. 
![image](https://user-images.githubusercontent.com/55203598/149190366-d8113ecd-67c0-48c1-b127-a5e30c8cdff5.png)
I asked Mary Jo because she worked on the wrapper and there will be opened a separate card for it.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![2022-01-12_14-21-27.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d182e7a5-7f0c-4950-ab8c-1925773e87e3)

The issue with the empty page will be addressed in a separate card (https://github.com/openstax/cnx-recipes/issues/4359)

**Comment by ajluk** [comment]
@MartaSztuka Could you check if the numbering of the exercises has been also fixed within my PR? The issue demanded changes in the recipe so test need to be performed on recipes `main` branch with current changes.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-01-13 10-12-16](https://user-images.githubusercontent.com/47241114/149300648-0710c639-bafa-4c8e-a59d-91057892cb39.png)

**Comment by lwtchu** [comment]
Should we close this?

**Comment by Stackblocks** [comment]
I'll double check it on CORGI and then close it out.
