### ISSUE TITLE
Contemporary Math Exercises Concern

### ISSUE THREAD

**Issue by mps-openstax** [openstax/cnx-recipes#4231]
As discussed in the weekly meeting we are supposed to create multipart questions for the exercises those have sub-items. If we are move forward with that could you please let us know/suggest how to handle below cases. Snapshot with other details given below for reference.

Chapter – 11
Module – 05
 
![image](https://user-images.githubusercontent.com/88098452/142362622-85d0f33c-1316-4dfd-ab17-d1ecffde164f.png)
                                                                      
Chapter -  02
 Chapter Review

![image](https://user-images.githubusercontent.com/88098452/142362689-210cda8d-eaf1-4fdf-871c-cd5fc35c5f06.png)

# Content Location(s)
collection ID: osbooks-contemporary-math/contemporary-math

**Comment by mps-openstax** [comment]
For the first one could you please let us know where we capture the text "In the following questions, use the Hamilton method of apportionment to answer the questions." Below is snapshot for reference. Please suggest further.

![image](https://user-images.githubusercontent.com/88098452/151946379-b1e8913a-0331-498a-b9be-ac7c6af6b9f4.png)

**Comment by openstaxalina** [comment]
@mps-openstax please encode that text in the "Intro" tab in the Exercises editor.

**Comment by lwtchu** [comment]
#4427  #4434 #4442  should capture all other new issues. closing.
