### ISSUE TITLE
0012-Political Science end of chapter content order didn't support in output

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4232]
We have received the below correction from customer. Kindly check and resolve this issue.

**Unless this is a standard way that OpenStax orders end-of-chapter features, the Summary should come before Key Terms. The correct order for these end-of-chapter features is:
Summary
Key Terms
Review Questions
Suggested Readings**

![Political_Science_EOC_Section_Order](https://user-images.githubusercontent.com/86622862/142385391-a5dca774-0b02-43fc-be3d-86e636e7c203.png)

# Bug Location(s)
collection ID: col00000
server: https://plum-narwhal-acs1o54u.ws-us18.gitpod.io/
chapter/section: Chapter 8/Section 1-6
surrounding text: An interest group is an organized collection of individuals

**Comment by lwtchu** [comment]
# Acceptance Criteria
Can we edit the recipe to have the EOC go 
Summary
Key Terms
Review Questions
Suggested Readings

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-12-01 15-56-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/53c7917d-f596-4465-bf4b-7cc50d6815a3)
