### ISSUE TITLE
standardizing iframe link behavior in PDF

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4233]
# Acceptance Criteria
1. all iframes in pdf should have their links (whether resource link or regular old link) reconstructed to point to either the rex feature (preferred) or the rex page (acceptable)
2. the work to suppress this "Click to view content (https://etc)" link will be done in another card #4352

### OLD CONTEXT AS TO WHY WE ARE DOING THIS IN THER FIRST PLACE

![image](https://user-images.githubusercontent.com/11299125/142466874-bfdd47a1-b01a-4166-a968-57cc388df152.png)

Now that CE has enabled this, the iframe link isn't enabled in the PDF.  (It should  have the  `Click to view content (link)` text appear right before the "Critical REsponse: An Annotated Model" header)

Content:

```  
<media alt="atoms_isotopes">
  <iframe width="660" height="371.4" src="../../media/Interactive/Comp_Figure 18_18.5_020/index.html"/>
  </media>
```

Ideally should go to the iframe in the content (maybe to the media ID) with the 

#4009 - PR
Content should say `Click to view content (https://_____)` << maybe it doesn't know how to populate the link here 🤔

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/4527e315-e044-431c-a60e-c8dd0ffc2c13)

**Comment by MartaSztuka** [comment]
@kswanson33 There is link, but I've got 'No such file' error.
![Screenshot from 2021-11-23 16-38-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/de30d028-2393-4ad3-ae60-df586868c690)
![Screenshot from 2021-11-23 16-34-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/14d6ccd4-a85c-42d3-89e0-6f5e068bdc45)
![Screenshot from 2021-11-23 16-34-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1168a18e-b1d0-4f17-87d2-432da92410d6)![Screenshot from 2021-11-23 16-34-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/51493017-528a-492e-bb5f-d21cd3d75fed)

**Comment by kswanson33** [comment]
Need to display the URL text as well as fix the file error

**Comment by lwtchu** [comment]
this is deprioritized until we can figure out how to generate the link and we are not enabling them for the launch anyway 

context: https://openstax.slack.com/archives/C022NETP39N/p1637672326025200

**Comment by lwtchu** [comment]
These are commented out - but I think we can make a separate branch for y'all to test with. 

First need to work with CE to figure out how to get the link

**Comment by philschatz** [comment]
Just a brain dump:

- Right now the URL for the interactives are in `<iframe src="...">` elements
- Ideally the link will point to REX
    - example: https://staging.openstax.org/books/writing-guide/pages/1-5-writing-process-thinking-critically-about-a-text#para-00032
    - the URL target (after the `#`) should point to the nearest ancestor of the iframe (or the iframe itself if it has an `<iframe id="..."`
- a linkify-rex step already converts some links to REX URLs. The links need to have additional attributes on them so the step can create a rex-link

Also,

**Comment by kswanson33** [comment]
iirc, the issue is that we have:

input:
`<iframe src="some-link">`

baking:
hides iframe, adds
`<a href="some-link">Click to view content (some-link)</a>`

linkify-rex:
updates link address, we end up with
`<a href="some-link-rexified">Click to view content (some-link)</a>`

but what we want is:
`<a href="some-link-rexified">Click to view content (some-link-rexified)</a>`

@philschatz would it be possible to update the linkify-rex step to target the text as well? for example, if we did this in baking: `<a href="some-link">Click to view content (<span data-linkify-rex="true">some-link</span>)</a>` then linkify-rex could target `data-linkify-rex` elements and correct both the link targeting and link content.

**Comment by lwtchu** [comment]
Some issues:
If the link that is generated goes to the rex page - 
- Link will be redundant on web. How will we hide?
- Currently the other "Click to view content" links are less redundant since the SIM goes full page as it is embeddable content.
- This is slightly different behavior in that we are trying to open it in web. vs opening something that is already hosted 
- Need to iron out actual behavior for this once we make some decisions about how to treat these sims

**Comment by Stackblocks** [comment]
Tested with the [`lchu-testing-iframes`](https://github.com/openstax/osbooks-writing-guide/tree/lchu-testing-iframe/collections) branch of Writing Guide, and links now route to the module's page in REX.

![image](https://user-images.githubusercontent.com/12678235/163840131-252c0012-398d-4a41-9a31-9b4e7fa6fc3b.png)

![image](https://user-images.githubusercontent.com/12678235/163840448-78d7adc6-3a67-45cc-a495-2bfdbc1b6399.png)
