### ISSUE TITLE
0013-Political Science file opening issue in Web view (Chapter 8)

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4234]
We have faced the output file opening issue in Web view. The Web view has been successfully converted in CORGI. CORGI didn't show any error messages. Kindly check and resolve this issue.

![Webview_Political_Science](https://user-images.githubusercontent.com/86622862/142596855-a6e34fad-5bbc-4b4b-8a40-34021d15c524.png)

# Bug Location(s)
CORGI Job id: 2370 
Web view: https://rex-web-production.herokuapp.com/books/89060098-2918-4037-8ebe-d90622d7a6bf@fa6e6ca/pages/1-introduction-to-politics-and-political-science?archive=https://openstax.org/apps/archive-preview/20211111.153520 
chapter: 8

**Comment by lwtchu** [comment]
Can't find anything obvious in the content at the moment - we think it might be the footnotes issue. A fix should go out sometime next week

**Comment by openstaxalina** [comment]
The web view is opening here: https://rex-web.herokuapp.com/books/89060098-2918-4037-8ebe-d90622d7a6bf@8388f3d/pages/8-introduction?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20211206.184556#foot-00001

I am going to close this.
