### ISSUE TITLE
Appendix Glossary headers in World History are missing styles

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4237]
During testing World History kitchen epic issue Marta has found out that the headers in Appendix Glossary are unstyled: https://github.com/openstax/cnx-recipes/issues/4125#issuecomment-974212132. As I have checked the shape for Appendix Glossary is missing the headers styling in cosmos theme.

**Comment by ajluk** [comment]
@lwtchu Here is how it looks now: 
![image](https://user-images.githubusercontent.com/55203598/142663979-fbe9d95c-15b1-4942-a745-66fca74c6157.png)
There are also the specs visible on the screenshot: 
![image](https://user-images.githubusercontent.com/55203598/142661838-50317588-963b-4f63-adb5-e5383a29577c.png)
Should I change something?

**Comment by lwtchu** [comment]
@ajluk oh nice thank you <3 this looks good

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-11-23 11-17-49](https://user-images.githubusercontent.com/47241114/143006890-3d53576c-a590-4fd0-b440-8373c185de8c.png)
