### ISSUE TITLE
writing guide - change request annotated text

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4240]
class: `<para class="annotation-text">`
color: change from B2: #0074BC

TO 

G6: `#156851`

Thread here: https://openstax.slack.com/archives/C8V1XET1R/p1637352365321000

TL;DR the blue font gets confusing on REX due to the underline and it looking like a link. Victoria suggested to change it to green. 

corresponding rex card https://app.zenhub.com/workspaces/openstax-unified-5b71aabe3815ff014b102258/issues/openstax/unified/1723

book is in github - osxbooks-writing-guide

**Comment by ajluk** [comment]
How it looks in xhtml file: 
![image](https://user-images.githubusercontent.com/55203598/143009885-2ca19c8d-3fb6-4b3c-813a-3861e90d79ac.png)

**Comment by MartaSztuka** [comment]
#### @lwtchu There are red headers within the note, is that expected? If so I'll close the issue.
![Screenshot from 2021-11-23 14-16-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7764dcfe-1d73-432f-a51e-d1eb5f86d079)

**Comment by ajluk** [comment]
@lwtchu The reason for the border/icon problem is that the border is added to the whole paragraph, but the icon is a child lement of the paragraph so the border will display outside the icon: 
![image](https://user-images.githubusercontent.com/55203598/143038197-5364000c-5c72-43a9-891a-a3ce723d265f.png)
I'm not sure how it can be fixed :thinking: I can try add the before element instead of a border and let you know about the results.

**Comment by lwtchu** [comment]
@ajluk @MartaSztuka  

okay might be a separate issue for both - the red header is..not ideal but let's leave for now 😫   it's a very very small fix. do you mind opening a separate card and assigning me so i can prioritize?

and can we leave the icons as is for right now also? there's a separate card for the icons for rex and i don't want to mess with it right now.

**Comment by MartaSztuka** [comment]
@ajluk @lwtchu here's the issue:
https://app.zenhub.com/workspaces/ce-styles-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/4257

**Comment by ajluk** [comment]
@lwtchu should we close this issue or do prefer to keep it open?

**Comment by lwtchu** [comment]
I think it has passed right ? We can close since we captured the other issues elsewhere
