### ISSUE TITLE
writing guide - bug - center class=“section-workscited” when nested in "living by their own words"

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4242]
Where the work was done: https://github.com/openstax/cnx-recipes/issues/4118

There's about five of these where the section using the `"section-workscited"` class aren't centering. PRobably cause we added the style on the h2 or h3 and not the h4? something like that?
![Screen Shot 2021-11-22 at 12 19 06 PM](https://user-images.githubusercontent.com/11299125/142914448-57be684c-aa84-4464-97d9-d9036d22cc31.png)

Five locations search for the following text:
1. Biello, D. (2007, May 25). Combatting climate change: Farming
2. Ballhaus, R., & Armour, S. (2020, April 22). Health chief’s early missteps
3. Barnard, Neal. “How Eating More Plants Can Save Lives and the Planet.”
4. Domanski, C. W. (2013). Mysterious
5. Ali, Lorraine. “‘Such a Nasty Woman’: Trump’s

book is in github - osxbooks-writing-guide

**Comment by wilkus27** [comment]
Issue is ready for testing.

@lwtchu when I was working on that I noticed that some of the sections with this class have empty headers. Here is one example:

![image](https://user-images.githubusercontent.com/40228854/143026973-64675865-5349-4742-aece-3d04f3a34ef2.png)

**Comment by MartaSztuka** [comment]
##### PASSED
##### 1. ![Screenshot from 2021-11-23 15-31-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b62ebcf3-7f85-4e3d-9455-cdcbcddbd752)
##### 2. ![Screenshot from 2021-11-23 15-32-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9f15116d-fac3-4595-a232-4ad5d0cc8cbb)
##### 3. ![Screenshot from 2021-11-23 15-33-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/870103dc-a29f-4724-a3e7-c4f8c24f90e7)
##### 4. ![Screenshot from 2021-11-23 15-33-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/36e9a2eb-fb20-4cf1-8c6a-7e8eac720966)
##### 5. ![Screenshot from 2021-11-23 15-34-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5ab3254c-cd74-426e-b7bb-781aa799a89d)

**Comment by lwtchu** [comment]
The other content issue is an issue that  I will open a separate card for :joy:

**Comment by openstaxalina** [comment]
documenting for future -- Works Cited and References are centered whenever they appear in the main book content. when they appear EOC, they are left-aligned. SRM previously confirmed this was acceptable.
