### ISSUE TITLE
writing guide - change request - increase px between double underline

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4243]
![Screen Shot 2021-11-22 at 4 54 59 PM](https://user-images.githubusercontent.com/11299125/142947190-1c1ae68e-fd6c-49d2-9ec0-10e4363b0f4f.png)
![Screen Shot 2021-11-22 at 4 55 04 PM](https://user-images.githubusercontent.com/11299125/142947194-76cd0d7d-fbf5-46fd-879a-cc113fc44400.png)

Depending on the PDF reader or browser or how you are looking at it, the lines sometimes appear thick or inconsistent. 

What is the weight of the line? (I'm not sure what thin translates to...) 

If it's about 0.5px wide for the underline - can we try 2px in between the two lines?

**Comment by ajluk** [comment]
@lwtchu the weight value of the border line wasn't set in the properties, so by default it was set to medium. I have increased it to thick, which I as I have checked is around .45rem, but it was also a little to thin and in some places the lines were falling into one , so I increased it to 0.5rem and here is how it looks then: 
![image](https://user-images.githubusercontent.com/55203598/143056949-d1807605-7df0-4d25-a95d-0a948f4f279a.png)
Is it ok to keep?

**Comment by lwtchu** [comment]
@ajluk is there a way to keep the 0.45 rem but increase the space in between the two double lines???? or is that not controllable

**Comment by ajluk** [comment]
@lwtchu It is not controllable I'm afraid. We can only increase the width property value here and it controls both space and thickness. There is another property which can be used in such cases (text-decoration/underline) additionally to border-bottom and it can look as the second border, but here the offset (the space between the text and the underline) can't be controlled because Prince doesn't support the text-decorarion-offset property and it looks like this then: 
![image](https://user-images.githubusercontent.com/55203598/143241444-9a80375f-322d-487f-b742-e0560c604850.png)

**Comment by lwtchu** [comment]
Ah okay - is 0.5 the best option? You can send me the PDF of .45 and .5 and I can try printing it and viewing it on a few monitors to see 

Thank you also for explaining

**Comment by lwtchu** [comment]
we have tested .45, .3, .5, .35, .2, .25 rem. there's no good solution as i think it is dependent on the resolution and type of screen you have. we will stick with the default medium line thickness which is about .2rem 

solution: just zoom in :(

**Comment by ajluk** [comment]
Screenshots for reference: 
100% zoom:
![image](https://user-images.githubusercontent.com/55203598/144224559-2b8ce019-6317-4a4b-b371-4d3799ee053a.png)
200% zoom:
![image](https://user-images.githubusercontent.com/55203598/144224680-1413bdd8-b45a-450f-9385-7ad4b8c2564b.png)

**Comment by MartaSztuka** [comment]
##### PASSED
###### 100%
![Screenshot from 2021-12-01 12-39-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dfc928a5-ef40-42a5-bfe0-c9ec86f8916b)
###### 200%
![Screenshot from 2021-12-01 12-38-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3eeeee6e-1e78-4616-bcd6-cf25d21a49dd)
###### xhtml
![Screenshot from 2021-12-01 12-51-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cee00f5d-ee33-495c-b9dc-800720e55897)
