### ISSUE TITLE
OPS-0012 Anthropology - Quote style didn't support in Output

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4245]
We have treated the quote paragraph as per the tagging legend. But, view doesn't appear in the output PDF. Kindly check and resolve this issue.

**CNXML Code:**
[quote id="quote-00001"]
      [para id="para-00020"]Text[/para]
[/quote]

# Bug Location(s)
collection ID: col00002
server: https://github.com/openstax/osbooks-introduction-anthropology
chapter/section: Chapter 1/ Section 1
surrounding text: When they divided the Purusa, into how many parts

**Comment by lwtchu** [comment]
Should be similar to #4188

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/144848182-857a386c-c5b7-4b67-a32a-7952c056ba0a.png)

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-12-07 10-36-29](https://user-images.githubusercontent.com/47241114/145004360-7f20a6d7-94e6-42e8-948f-477c58e1c5e6.png)

**Comment by srm-openstax** [comment]
@MartaSztuka, @ajluk  - Please confirm if the issue is resolved or merged  with #4287 and still under resolution.

**Comment by lwtchu** [comment]
@srm-openstax This is not released yet. Again, we will contact you when it is resolved and released for production via the release notes that I send in the email.
