### ISSUE TITLE
writing guide - enable h5/h6 in the handbook

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4249]
![Screen Shot 2021-11-23 at 9 29 53 AM](https://user-images.githubusercontent.com/11299125/143062656-29b412a5-08d1-4f79-a3d9-773382799b27.png)
![Screen Shot 2021-11-23 at 10 19 52 AM](https://user-images.githubusercontent.com/11299125/143062663-18d63a3e-005a-45ad-94e7-5085233c59d0.png)

Pulled from #3164 - basically JUST FOR THE HANDBOOK - can we bump up the header sizes? by one?

# Book Content
## H1 (Title) -  unless it's the splash image
font style: Archivo
weight: semi-bold, 600
font-size: font-scale(4): 18.66pt, 25.2px, 2.1rem
color: R1: `#C31427`

## H2
font-size: font-scale(3): 15.55pt, 20.4px, 1.7rem
font style: Archivo
weight: semi-bold, 600
color: R1: `#C31427`

## H3
font size: font-scale(2): 12.96pt, 16.8px, 1.4rem
font style: Archivo
weight: semi-bold, 600
color: R1: `#C31427`

## H4 
font size: font-scale(1): 10.8pt, 14.4px, 1.2rem
font style: Archivo
weight: semi-bold, 600
color: R1: `#C31427`

## H5
font size: font-scale(0): 9pt, 12px, 1rem
font style: Archivo
weight: semi-bold, 600
color: R1: `#C31427`

## H6
font style: IBM Plex Sans
font-weight: bold, 700
color: black `#000000`
font size: font-scale(0): 9pt, 12px, 1rem

## Base font
font size: font-scale(0): 9pt, 12px, 1rem
color: black `#000000`
font style: [IBM Plex Serif](https://fonts.google.com/specimen/IBM+Plex+Serif?query=ibm+plex+seri#standard-styles)
weight: regular, 400

**Comment by wilkus27** [comment]
@lwtchu I didn't change anything for H1, because it's styled like Appendix header, so it has font size 6:

![image](https://user-images.githubusercontent.com/40228854/143461049-16f996f6-dd63-4bb5-b418-a50a2153f4e6.png)

**Comment by MartaSztuka** [comment]
#### PASSED
##### H1
![Screenshot from 2021-11-25 17-32-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3f9548c8-8106-49cf-8707-561f2a5171e9)
![Screenshot from 2021-11-25 17-34-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/07ac9a9f-99c4-4daa-8c9e-e3c44df58bf9)
##### H2
![Screenshot from 2021-11-25 17-09-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/95ca2062-e3e9-47fb-8e79-85a598e78aae)
![Screenshot from 2021-11-25 17-08-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/18f5b1b5-cf03-476b-9672-dd3940066a12)
##### H3
![Screenshot from 2021-11-25 17-23-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2f6c6c05-8306-4fba-9a79-3e787b1dbad7)
![Screenshot from 2021-11-25 17-23-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2cc93b27-1c78-4619-a037-1588c1560644)
##### H4
![Screenshot from 2021-11-25 17-15-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/de978eea-31ba-4c59-91fb-53523d73796c)![Screenshot from 2021-11-25 17-15-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9dcafe57-4852-4c14-8358-38d5070a67e9)
##### H5
![Screenshot from 2021-11-25 17-21-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c75b168d-b3f9-4d80-9c22-ffa33516f7ea)![Screenshot from 2021-11-25 17-20-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5af80719-e269-40dd-b05b-bd120251af32)
##### Base font
![Screenshot from 2021-11-25 17-36-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/30f04027-7708-4289-9344-ec65f4a531b4)![Screenshot from 2021-11-25 17-35-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4686ab5d-4de9-475b-91cc-1fceca5431b6)

**Comment by lwtchu** [comment]
@MartaSztuka do you mind looking for the content in the original screenshot? I'd like to see how it looks - thanks ! 

And I want to make sure it's only isolated in the Handbook since the  H5 header is only in there I think

**Comment by MartaSztuka** [comment]
@lwtchu Changes are only in Handbook. Screenshots for Headers in Handbook are above, Headers in the rest of the book are here:
###### H2
![Screenshot from 2021-11-26 10-04-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/53a469bb-e517-4002-88cf-fc5ebe885f5c)
###### H3
![Screenshot from 2021-11-26 10-05-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f87d9198-389d-4edb-b756-e3ccdfbffe90)
###### H4
![Screenshot from 2021-11-26 10-05-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0a4370fd-d6ac-4263-b93e-3f618289898e)
###### H5
![Screenshot from 2021-11-26 10-06-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8ebaf995-b937-476f-bcc4-2fa7845426fe)
