### ISSUE TITLE
writing guide - nested list in h5 boopin out of handbook margins

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4250]
![Screen Shot 2021-11-23 at 9 29 53 AM](https://user-images.githubusercontent.com/11299125/143067340-ef6bcdc5-352b-46db-8980-f8f8a49f327b.png)

one day i will know peace where my cat isn't actively trying to climb onto my face. but today is not that day.

can we maybe boop these lists back in? thank you <3

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-11-26 16-48-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c461495d-a0cd-4220-9ed6-b5aed694df12)
