### ISSUE TITLE
writing guide - update mark up issue for icons and add alt text

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4252]
Currently this is the output for the icon mark up. There is a request from the REX team to 
```
<p class="annotation culture-icon visual-icon auditory-icon" id="para-00003"/>
<div class="os-icons">
  <span class="culture-icon"/>
  <span class="visual-icon"/>
  <span class="auditory-icon"/>
</div>
<span class="os-text">Write a review of a specific film, book, TV series, podcast, play, or video game that you think contributes something significant to the genre and to the culture at large. Show how the subject—the primary source—of your review illustrates something compelling or exceptional about a particular idea or theme common to the genre. For example, the CW series <span data-type="term" class="no-emphasis" id="term492" group-by="C"><em data-effect="italics">Crazy Ex-Girlfriend</em></span> (2015–2019) is a romantic comedy that eschews and even satirizes traditional romantic comedy tropes such as the "grand gesture," doing something out of love for someone. Use specific evidence from your primary source to support a central idea, or thesis. In an essay of about 1,200 to 1,500 words, provide an overall judgment about your subject and support it with evidence from the primary source and from secondary sources if applicable. In addition, explore how your specific source has contributed something significant to its genre. In other words, <em data-effect="italics">why is this subject interesting, different, or worthy of analysis?</em> Be sure to demonstrate awareness of your source's cultural and historical context as well. For example, if your review is about a romantic comedy, provide relevant information about the history, conventions, or expectations of that genre. Think about and explain the ways your topic adheres to or breaks from audience expectations.</span>
```

There is a strange self enclosing `<p/>` tag and the icon container should probably be a span and the text should be a para. 

Very long thread here: https://openstax.slack.com/archives/CH5514N57/p1637617759061600

- [ ] We'll need to adjust this in recipes
- [ ] Update styles selectors 
- [ ] Add role AND aria label AND title attributes to the span tags for the icons [(approved alt text with classes and images)](https://docs.google.com/document/d/167-lSFr2xVFxBkBYfH79SPI9Y9JcsbiNSIOS8NMrq0Y/edit?usp=sharing)

Example: 
`<span class="culture-icon" role="img" title="culture lens icon" aria-label="culture lens icon">`

Note: DECIDED to not include alt text in the SVG content because things won't display as a tool tip or be picked up by a reader.

For testing: It should look the same in the PDF as it was before. And can we just test the aria-label thing in JAWS?

**Comment by TomWoodward** [comment]
i think probably what was intended, and would be fine for rex, would be if the paragraph wrapped everything and the div was a span. paragraphs automatically end if they run into a block element so that seems like the issue here

**Comment by Stackblocks** [comment]
- [ ] Showing up well in the markup
- [ ] Reads properly in JAWS (testing in progress)

**Comment by openstaxalina** [comment]
Per Larissa, easiest way to test is to hover over the icon and ensure alt text displays. [Confirmed](https://rex-web.herokuapp.com/books/ee7ce46b-0972-4b2c-bc6e-8998c785cd57@835f2e7/pages/1-1-reading-to-understand-and-respond?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20211206.184556):
![Screen Shot 2021-12-07 at 12 40 22 PM](https://user-images.githubusercontent.com/7863733/145087343-f8aa9bb5-2bf6-474f-9626-9ea66e52691e.png)
