### ISSUE TITLE
writing guide - single para citation

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4253]
![Screen Shot 2021-11-23 at 4 29 03 PM](https://user-images.githubusercontent.com/11299125/143139262-d238ffa0-7e6b-4762-8cb4-1cea5081978f.png)

There's a new request for single para hanging indents for when they go longer than one line. 

It is a `<p class="citation">`. 

Some sample locations and searchable text:
![Screen Shot 2021-11-23 at 4 24 27 PM](https://user-images.githubusercontent.com/11299125/143139348-90ab3258-e561-437c-8c4a-db1fc0487cec.png)
- Glance at Form: Citation Style, Purpose, and Formatting (“Food Preparation Workers.”) (Authority: This web page is produced by the Bureau of Labor Statisti)
- Annotated Student Sample: “Healthy Diets from Sustainable Sources Can Save the Earth” by Lily Tran (Chai, Bingli Clark, et al.)
- Writing Process: Informing and Analyzing (Buiten, Miriam C. “Towards Intelligent Regulation of A)
- Handbook (United States Department of Veterans Affairs)

**Make sure it works in handbook, nested and with the student-sample citation.** 

It should look like this within the text.
![Screen Shot 2021-11-23 at 4 31 17 PM](https://user-images.githubusercontent.com/11299125/143139460-b1480a8c-be2b-4f83-a074-85daf933f142.png)

**Comment by wilkus27** [comment]
@lwtchu I found citations also in public domain paragraphs, so I added support for them as well.

**Comment by MartaSztuka** [comment]
##### PASSED
###### 1.
![Screenshot from 2021-11-29 15-39-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8c5b225c-a708-4f3a-beb4-8c5d1967e307)
###### 2.
![Screenshot from 2021-11-29 15-42-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4948e270-1461-40be-893f-a842707ba8a8)
###### 3.
![Screenshot from 2021-11-29 15-45-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/55298e17-36d2-4f9c-a2b4-319cb0fa2c40)
###### 4.
![Screenshot from 2021-11-29 15-47-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c72231f4-d66c-48c7-a335-063e25e632ef)
