### ISSUE TITLE
OPS-0012 Finance - Question spacing issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4256]
We have received the below correction from the customer. Kindly check and resolve this issue.

**(In web/HTML view only) insert vertical space between Problems 3 and 4**

![problems_question_space](https://user-images.githubusercontent.com/86622862/143188218-afafa35d-295f-4495-845d-784c5a4adc04.png)

# Bug Location(s)
collection ID: col00006
server: https://yellow-falcon-nrfjf7qa.ws-us17.gitpod.io/
chapter/section: Chapter 14/Section 6
line number: 208

**Comment by lwtchu** [comment]
@srm-openstax 
![Screenshot 2021-12-03 145123](https://user-images.githubusercontent.com/11299125/144671207-a87f64a5-42b3-495a-8623-2f7469f053eb.png)

webview  view - will open card when we are done with writing guide

**Comment by lwtchu** [comment]
Cleaning cards. Won't fix for web at the moment.
