### ISSUE TITLE
Writing guide - red header inside a note

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#4257]
Red header occurs inside green notes 'Livin by their own words'.
![Screenshot from 2021-11-24 10-25-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8695aeba-41a7-426a-a3ee-34ce1d276cba)

**Comment by lwtchu** [comment]
Change this to black to match the other internal  title.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4c234cfa-c4a5-49bd-8573-1623d3981f2f)

**Comment by lwtchu** [comment]
![Screenshot 2022-01-06 102645](https://user-images.githubusercontent.com/11299125/148415739-5cb4f327-704b-4c2d-8c9e-a95beb0bd6fb.png)
verified on staging
