### ISSUE TITLE
Writing Guide handbook folio still displays chapter 20

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4273]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know

<img width="620" alt="Screen Shot 2021-12-01 at 11 43 00 AM" src="https://user-images.githubusercontent.com/1895432/144290642-4cc37fa7-7e79-445c-9fdd-6fa90354e6ea.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
yes, for the whole handbook section
# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: 
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link:  https://github.com/openstax/osbooks-writing-guide
chapter/section: after ch 20
surrounding text: "This handbook is a brief yet comprehensive"

**Comment by lwtchu** [comment]
Similar functionality to Appendix folio - Can we just have it say  `Handbook` ??

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a2eac624-539a-47b6-a09a-a9e5153b2bc6)

**Comment by lwtchu** [comment]
![Screenshot 2022-01-06 102611](https://user-images.githubusercontent.com/11299125/148415667-77876830-237c-43ba-b709-3e499f744bc6.png)
verified on staging
