### ISSUE TITLE
Colons in Writing Guide section headers

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4274]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know
We don't want automatic colons after "Peer Review" and "Revising" in sections with `class="peer-review"` and `class="revising"`

<img width="752" alt="Screen Shot 2021-12-01 at 11 02 49 AM" src="https://user-images.githubusercontent.com/1895432/144290943-69fdd220-df38-4abb-8298-81e481479cbc.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
it doesn't seem to happen in places where there is a title specified in the tag instead of an empty singleton `<title/>`
# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: 
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
Mightttt be content cause this expects a title with that section  🤔

**Comment by oscryan** [comment]
there are two places where it doesn't have one, tho, so either i need somebody to give me some titles or it gotta Not Expect That

**Comment by lwtchu** [comment]
FROM THEE ANTHONY: Re the nondestinational colons — they  can remain as is in my opinion  I mean the heading is before something…so the colon is referring to what is after it, and there’s a paragraph there so we’re gold ponyboy.  I COULD probably come up with an ending phrase for each of those headers if that would be better.  At this point I think that it’s probably more work than needed (for all’v’us).  No one will be confused or concerned about them I think.
