### ISSUE TITLE
US History - table in Appendix

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#4275]
In Appendix C table doesn't break, there's an empty page.
![Screenshot from 2021-12-02 16-38-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/860999f8-ff46-4a56-89bc-6fd2131b127a)

**Comment by lwtchu** [comment]
Similar to this: https://github.com/openstax/cnx-recipes/issues/3852 ??? Maybe?

**Comment by wilkus27** [comment]
Checked with the newest content and styles. It's already fixed:

![image](https://user-images.githubusercontent.com/40228854/151983064-9463fc03-eeea-46f5-a58a-ea699bc0dabf.png)
