### ISSUE TITLE
US History - quote

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#4276]
In note one quote isn't styled properly.
![Screenshot from 2021-12-02 16-40-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/467db88e-4468-41e7-a43b-6dc7c8417d9f)

**Comment by lwtchu** [comment]
Apply same style functionality from  https://github.com/openstax/cnx-recipes/issues/2749 

we might need to make some content changes for the quotations

**Comment by wilkus27** [comment]
@lwtchu I checked, and this is a content issue. Text should be put into `<blockquote>` tag not `<q>`:

![image](https://user-images.githubusercontent.com/40228854/146212087-f9c3cb8a-f1d2-4759-98cd-1888e5fa4f69.png)

Example of proper element:

![image](https://user-images.githubusercontent.com/40228854/146212272-2eaa44a4-f9ce-4d20-ad71-fe63f1beaede.png)

**Comment by lwtchu** [comment]
@wilkus27 thank you :) i'll move this card

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #2487](https://github.com/openstax/content-managers/issues/2487) via [**ZenHub**](https://www.zenhub.com/)
