### ISSUE TITLE
Create BakedPDF Documentation

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#428]
## User Story
- As a user, I want to have documentation on BakedPDF so that I can understand how it works.

## Acceptance Criteria
- When I read the BakedPDF documentation, I expect to be able to understand roughly how it works.

## Definition of Ready
- [ ] Documentation has been created
- [ ] Documentation has been peer-reviewed
- [ ] Documentation is made available

**Comment by brittweinstein** [comment]
@brittany-johnson is this complete?

**Comment by brittweinstein** [comment]
@brittany-johnson can we close this?
