### ISSUE TITLE
world history - put composite assessment pages in EOC under "Assessments"

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4280]
![Screenshot 2021-12-03 115304](https://user-images.githubusercontent.com/11299125/144649729-3fa30712-fdff-49a9-ac46-84f9b90615ba.png)
Can we put the assessment type EOC under `Assessments`

Check Your Understanding
Reflection Questions
Visual-Based Questions
Making Connections
Thought Provokers
Source Questions

Kind of like this #https://github.com/openstax/cnx-recipes/issues/4011

**Comment by LostMojo** [comment]
So this is a change that'll need to be made in kitchen to wrap the composite chapter list items in an 'assessments' subcategory.

**Comment by LostMojo** [comment]
To do this with existing Kitchen, we'll have to put the composite chapters in the EOC into a section called "Assessments"-- Would this be ok?

**Comment by LostMojo** [comment]
[Recipe part of this](https://github.com/openstax/recipes/pull/175)

**Comment by Stackblocks** [comment]
@lwtchu The indentation feels big, can I get a judgement call on that to try and head off a possible future request? 
That being said, any appearance tweaks can be handled in a separate issue because the core functionality works as requested in this one. :+1:

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b2ecdf52-e36f-4b93-a222-824970604b06)

**Comment by lwtchu** [comment]
@LostMojo @Stackblocks Sorry it wasn't clear - but in the other titles they're suppressed in the TOC and ONLY  assessments shows up but in REX they're able to make that drop down. This is how it was implemented in BCA
![Capture1](https://user-images.githubusercontent.com/11299125/146818723-d2dd7a3e-fdb2-4a7b-bad7-52471c19a562.PNG)

**Comment by lwtchu** [comment]
@LostMojo i moved this to abundant.allspice - do y ou think you have time this week or next to do the change? it's similar functionality to the comp sci/bca books. the screenshot of webview probably didn't help

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-01-13 10-32-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0fc0fe4d-5411-4afc-b392-b3b87d20d1bc)
