### ISSUE TITLE
precal quad - Try It figure links break

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4283]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know
Markup is correct but link does not autogenerate anchor text in this Try It
<img width="621" alt="Screen Shot 2021-12-03 at 2 25 13 PM" src="https://user-images.githubusercontent.com/1895432/144668994-c896d384-71ad-4cbd-8756-63c48cb36d5a.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
just one instance
# Sample mark up if applicable
`<link target-id="Figure_01_01_007"/>`
# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: https://github.com/openstax/osbooks-college-algebra-bundle
chapter/section: 3.1 Functions and Function Notation, try it 7
surrounding text: Using

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
we can just test with any of the books in the repo since it's the same content

just want to make sure both recipes work though (precalculus and precaluclus-coreq)

**Comment by lwtchu** [comment]
@openstaxalina @theresamasciale this isn't a big ish deal since it's only in one spot(?) but i figured we should  get it done in time for Print and the next contnet update.

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/ddce6ae2-8740-47f2-bc6e-cff458c7e876)

I can't reproduce this issue ... when I run richb-press, I get the above.

**Comment by oscryan** [comment]
I changed the content. It is now an unlinked bolded example name

**Comment by kswanson33** [comment]
can this issue be closed then? @oscryan

**Comment by oscryan** [comment]
i'd like to put it back someday maybe. but for now i guess
