### ISSUE TITLE
world history - italicized term is not italicized in index

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4284]
![Screenshot 2021-12-03 143239](https://user-images.githubusercontent.com/11299125/144671345-4b33d59b-fe7b-49ca-b6f4-1f0373b6a13f.png)
![Screenshot 2021-12-03 143301](https://user-images.githubusercontent.com/11299125/144671348-ed5828e5-68b7-4dc5-8d89-9da82789012b.png)

Is it possible to have the term also be italicized if it's italicized in the text?

Mark up: ` (<term class="no-emphasis"><emphasis effect="italics">Homo sapiens sapiens</emphasis></term>`

**Comment by ajluk** [comment]
Information for testing purposes. This issue demanded changes in Kitchen and recipe update and because of this it needs to be tested on current `main` branch in the `recipes` repo.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image](https://user-images.githubusercontent.com/12678235/146565435-690fd7dc-9b1f-46f1-809f-3c4bd137a386.png)

**Comment by lwtchu** [comment]
![Screenshot 2022-01-06 094850](https://user-images.githubusercontent.com/11299125/148410169-4a32505c-0a78-4358-9b91-1d515cf1697b.png)
verified on staging
