### ISSUE TITLE
OPS-0012 Anthropology - Bullet list alignment issue in introduction page

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4285]
We have followed as per the tagging legend. But, We have received the below correction from the customer. Kindly check and resolve this issue.

**Moving these bullet points is fine.**

![bullet_list_input](https://user-images.githubusercontent.com/86622862/144834648-9c75937a-9f51-446d-9e2c-e9e3ef5fa25e.png)
![bullet_list](https://user-images.githubusercontent.com/86622862/144834669-d3a570ee-7718-486a-be93-bdf36356114e.png)

# Bug Location(s)
collection ID: col00002
github openstax/osbooks- link: https://teal-flea-z00dgejm.ws-us21.gitpod.io/
chapter/section: Chapter 17/Introdcution
surrounding text: How do you define health?

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![image](https://user-images.githubusercontent.com/12678235/146586743-b0f01854-6773-4c01-b578-00c30ffa40bc.png)

**Comment by lwtchu** [comment]
![Screenshot 2022-01-06 102530](https://user-images.githubusercontent.com/11299125/148415570-6e09d40a-55ae-4dce-904f-8e5a0def9799.png)
verified on staging

**Comment by lwtchu** [comment]
Verified on production
