### ISSUE TITLE
References need restyling after Kitchen changes made to alphabetize them

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4289]
The section tags around references paragraphs has been removed in Kitchen during sorting references alphabetically:
![image](https://user-images.githubusercontent.com/55203598/144890635-dbd59fd1-acfc-48f6-90e7-cc406ce52886.png)
The shape used to create indention in cosmos theme used section wrappers so the styles need to be changed for References in Philosophy.

**Comment by ajluk** [comment]
@MartaSztuka during working on this issue a part of the clean up in modules with indentation shapes has been done. For testing purposes it will be safer to test more that one book from cosmos theme. The good choice could be English Composition, where sections Works Cited, Further Reading and Works Consulted from EoC need to be checked and also sections Works Cited and Further Reading in Handbook pages need to be tested. The third book could be Political Science because it is one of the new books (section Suggested Reading in the EoC needs checking).

**Comment by MartaSztuka** [comment]
#### PASSED
##### Philosophy
![Screenshot from 2021-12-08 13-04-39](https://user-images.githubusercontent.com/47241114/145205596-ecc184d5-6be8-48e8-8cbd-1b27377357d9.png)

##### Political science
![Screenshot from 2021-12-08 13-02-52](https://user-images.githubusercontent.com/47241114/145205416-38fc1244-7175-470b-83d0-5b2e77c4c0f8.png)
![Screenshot from 2021-12-08 13-03-01](https://user-images.githubusercontent.com/47241114/145205454-f8785035-09da-46d7-8cbf-6cc1ccb0c2c4.png)

##### Writing guide
![Screenshot from 2021-12-08 13-07-03](https://user-images.githubusercontent.com/47241114/145205846-7d75021c-0d23-4329-99d0-98eac4ad238c.png)
![Screenshot from 2021-12-08 13-06-27](https://user-images.githubusercontent.com/47241114/145205852-b2caa98c-baf9-4bb7-bd82-91589fb24891.png)
![Screenshot from 2021-12-08 13-08-23](https://user-images.githubusercontent.com/47241114/145205975-d87b4f03-b2a5-4b10-8561-11a00d137b80.png)
