### ISSUE TITLE
Create BakedPDF Training Resources

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#429]
## User Story
- As a user I want training resources so that I can learn how to use BakedPDF

## Acceptance Criteria
- When I use the training materials, I expect to learn how to use BakedPDF on my own.

## Definition of Ready
- [ ] Training materials have been created
- [ ] Training materials have been peer-reviewed
- [ ] Training materials have been made available to the user

**Comment by brittweinstein** [comment]
@brittany-johnson is this complete?

**Comment by openstaxalina** [comment]
Yes.
