### ISSUE TITLE
OPS-0012 Anthropology - Chinese characters view issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4292]
The received input MS file Chinese language content appeared in input MS. We have coded as per the input. But output shows in question mark that content. Kindly check and resolve this issue.

![Chinese_language](https://user-images.githubusercontent.com/86622862/144964077-12c92aab-2ad5-4909-850e-67d473f7c969.png)

# Bug Location(s)
collection ID: col00002
github openstax/osbooks- link: https://teal-flea-z00dgejm.ws-us21.gitpod.io/
chapter/section: Chapter14/Section 3 & Chapter 17/Section 2
surrounding text: a sticky rice dumpling, wrapped in bamboo leaves, prepared for the Dragon Boat Festival

**Comment by lwtchu** [comment]
@srm-openstax We do not support Chinese characters in the platform. I discussed with Anthony and can you translate the title  and adjust the credit to:

credit: modification of "Dragon Boat Festival Zongzi" by Evan Wood/flickr, CC BY 2.0

**Comment by srm-openstax** [comment]
We have updated. Thanks for your suggestion.
