### ISSUE TITLE
Finance - Tighten padding in tables

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#4294]
# Brief Description of Change and Screenshots
What kind of change is this? [ ] recipe [x] styles [ ] i don't know

@lwtchu suggested to change the padding from 4-5px to 2px - she noted that she thought this was in this PR: https://github.com/openstax/cnx-recipes/pull/4077/files
but since that PR has been merged and this PDF was generated today, I think a change is still needed.

![Screen Shot 2021-12-07 at 4 31 53 PM](https://user-images.githubusercontent.com/7863733/146039153-cbda3d93-a00a-4375-9419-fb76a64c9772.png)

# Acceptance Criteria
Larissa to discuss w/ team when back

# Content Location(s)
collection ID:
github openstax/osbooks- link: github.com/openstax/intro-finance
chapter/section: 14
surrounding text: table 14.3 right after text "500 shown previously"

**Comment by lwtchu** [comment]
@openstaxalina :eyes: i don't think that's the screenshot you wanted to put

**Comment by openstaxalina** [comment]
@lwtchu thanks - good catch! I updated above

**Comment by ajluk** [comment]
Hi @lwtchu! Here is how the table looks in PDF at 100% zoom: 
![image](https://user-images.githubusercontent.com/55203598/147957593-ea565045-1d80-4482-b367-aa5588c07339.png)
and here it is at 150%: 
![image](https://user-images.githubusercontent.com/55203598/147957673-998b5a02-da88-433e-8978-a3936dec4241.png)
The cell with word Step looks like the right padding has been removed but it is only a false impression, let me know if it is accepted (in my current pr all of the paddings are set to 0.16rem which is equivalent to 2px for default tables in finance).

**Comment by lwtchu** [comment]
@ajluk for the spacing we might need to teach them to do `newline/`

what does "has been removed but it is only a false impression" mean?

**Comment by ajluk** [comment]
@lwtchu By "has been removed but it is only a false impression" I meant the padding looks like there is almost none (to small) on the right side of some `thead` cells f.ex. cell with the word Step (in table 14.5)  is it acceptable and I can implement it or would you like the right and left paddings be increased a little? And can I also ask what you mean by "for the spacing we might need to teach them to do newline/"? :smile:

**Comment by lwtchu** [comment]
@ajluk OHHHH okay :joy: uhhh need to teach the teams to not put separate paragraphs for single lines when they can just add a line break

**Comment by ajluk** [comment]
Oh, ok, thank you for clarifying! :smile_cat: But are the paddings acceptable or should I change something?

**Comment by lwtchu** [comment]
@ajluk yes it's good :) thanks

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-01-11 11-11-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/08597936-bdd3-4927-b1e9-6e3424885896)![Screenshot from 2022-01-11 11-16-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c0f786e8-028d-4f12-914f-2da0ff26a788)![Screenshot from 2022-01-11 11-18-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d7de358b-1544-4c47-83ab-c80c4a6da887)
