### ISSUE TITLE
change request - writing guide - handbook to start on odd page

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4305]
# Brief Description of Change and Screenshots
What kind of change is this? [ ] recipe [x] styles [ ] i don't know
![Screenshot 2021-12-14 111856](https://user-images.githubusercontent.com/11299125/146047724-e56938a7-3690-45d1-b1e7-c5e98d1c101f.png)

Can we have the Handbook get the rule to start on a Odd page (add a blank page ONLY if it's on an even page).

# Acceptance Criteria
Handbook starts on  ODD page so it can start on the right hand side of the book when printed.

# Content Location(s)
collection ID:
github openstax/osbooks- link: https://github.com/openstax/osbooks-writing-guide
chapter/section: handbook
surrounding text:

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/846316d9-aff6-4b92-85c4-e2e1c0cef49c)
