### ISSUE TITLE
OPS-0013 Philosophy - Centered text alignment issue in Output

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4306]
We have followed as per the tagging legend. But, didn't convert the center alignment in output. Kindly check and resolve this issue.

**Tagging Legend:**
![philosophy_centered_text_TL](https://user-images.githubusercontent.com/86622862/146142496-7a1e84a3-ca0e-45c4-a23a-07cdf270469e.png)

**CNXML:**
![philosophy_centered_text_CNXML](https://user-images.githubusercontent.com/86622862/146142523-fe0055a0-fbfc-485d-92da-5f91e454a2b7.png)

**Output:**
![philosophy_centered_text_output](https://user-images.githubusercontent.com/86622862/146142539-bcaa2b9d-6cdb-44a9-a2e9-bff584ecf194.png)

# Bug Location(s)
collection ID: col00005
github openstax/osbooks- link: https://coffee-grouse-ulafn81g.ws-us23.gitpod.io/
chapter/section: Chapter 2/Section 2
surrounding text: Do you know the answer? For most people, multiplying two-digit

**Comment by lwtchu** [comment]
# Acceptance Criteria

Can we enable this in the Philosophy book? And make it library wide maybe? Thanks!

**Comment by ajluk** [comment]
@lwtchu I have looked through the `cnx-recipes` repo and found out that there was already a shape created for styling centered text in the common shapes but it was just used in World History. I have added it in philosophy `book.scss` file and this how it looks: 
![image](https://user-images.githubusercontent.com/55203598/146545858-7263938b-36b7-4af8-b0ee-5cb39e902b67.png)
In this shape the centered text is also unbolded, is this something we would like to have in philosophy as well? And also by library wide you meant that it should be also added in other books in all themes or just create a shape we can use in the future (which has been already done by :slightly_smiling_face:)?

**Comment by lwtchu** [comment]
@ajluk this is fine - can we also add it in other books in all the themes? is that too much? or we should continue enabling the shape?

**Comment by ajluk** [comment]
@lwtchu It depends if class `centered-text` has been already added to the content in other books so it can be tested or if you would like to add this functionality  in advance without testing these books without the class in the content? Centered text has been applied in code only for Computer Science, World History and Finance so far.  It is a simple functionality I guess and we don't use this class for anything else as I have checked :thinking: let me know what are your thoughts :slightly_smiling_face:

**Comment by lwtchu** [comment]
@ajluk hmmmm okay i'll just  have to remember to add it to the new books - we can just add in philosophy for now.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-01-04 12-18-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c6f128f4-7f82-444d-aadf-c10f066292e8)

**Comment by srm-openstax** [comment]
Yet to resolve this issue. Still now, we have faced the center align issue in output. Kindly check and resolve.

**PDF view (Page 42):**
https://openstax-cops-artifacts.s3.amazonaws.com/introduction-philosophy-latest-git-3104.pdf
