### ISSUE TITLE
College Algebra footnote squishes padding too far

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4307]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know
<img width="584" alt="Screen Shot 2021-12-15 at 9 00 56 AM" src="https://user-images.githubusercontent.com/1895432/146211435-452271d9-c06a-4981-853b-32262d552312.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
there's only one
# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: college-algebra-bundle/college-algebra-2e
chapter/section: 9.7 Probability
surrounding text: "Use this data for the exercises that follow"

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
We think it might be the footnote?

**Comment by KarinaMendez2** [comment]
it's no longer overlapping 

![image.png](https://images.zenhubusercontent.com/5c54789f0a972e6fd1ece1a0/13d7e098-88c1-41df-a14e-d349b7da0689)
