### ISSUE TITLE
Fix Handbook Links in Writing Guide

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#4314]
@openstaxalina commented on [Fri Dec 17 2021](https://github.com/openstax/content-managers/issues/2466)

##  Description

Ania (REX QA) caught that the links in the Outline at the top of the Handbook are not working at all in the web (Ryan notes that in the PDF, they go to the top of the ToC). Per Ryan's investigation, the outline is collated by the recipe so this is a recipe fix.
 
## Why do you need us to do it? Who is this for? 
So that folks trying to use the Handbook can effectively navigate to different sections of it.

### Acceptance Criteria/what change should users see
- [ ] links in the Handbook work on the web preview and the PDF 
- [ ] Ryan has updated ABL with minimum code version that has the fix

Content location: https://github.com/openstax/osbooks-writing-guide

**Comment by MartaSztuka** [comment]
#### PASSED
Links in Handbook outline works properly
Footage below:
https://watch.screencastify.com/v/lsJ652p59wL0ONmKniRE
