### ISSUE TITLE
REX Content Parsing - addScopeToTables - adding scope="col" to table headers for screen readers

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4315]
# Purpose
adds `scope="col"` to each table heading (th scope attribute specifies for screenreaders whether a heading applies to a row or column) - this is beneficial for screen readers

![Capture](https://user-images.githubusercontent.com/11299125/146799174-db2e7cd0-00dc-48be-85ef-767f993b672f.PNG)

# Acceptance Criteria
-  `scope="col"` is now added via the recipes for each book 
- I do not think this will impact the PDF - please confirm if I'm right or wrong :joy: 

I think we should also do a mini test fest? For this?

**Comment by kswanson33** [comment]
Kitchen update has been made; still needs a recipes update. Pausing on that until we restructure recipes to all depend on the same kitchen version.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![2022-01-13_16-43-08.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/bb5fec2f-f2c8-4157-8d31-bb9f68d7964c)
