### ISSUE TITLE
writing guide - add unit numbering to unit introduction page 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4316]
![Screenshot 2021-12-20 132050](https://user-images.githubusercontent.com/11299125/146821113-1c863cf6-57f9-404b-bb09-5825e03382bd.png)

location: https://github.com/openstax/osbooks-writing-guide
class: `class="unit-opener"`

Can we add `Unit #` as auto injected text? 

Why? When it is unnumbered, it breaks highlighting on REX and we want it to be auto injected because it is numbering. This rule should be applied to all unit-opener classed modules.

**Comment by ajluk** [comment]
Hi @lwtchu! Here is how it looks in the toc: 
![image](https://user-images.githubusercontent.com/55203598/146944875-5596ddaa-127e-46aa-9d5e-94e00912aa17.png)
in the toc links to pages like are created form actual titles, so it needed a change in the unit page title itself:
![image](https://user-images.githubusercontent.com/55203598/146944951-803f27a5-7529-48c9-997b-e7d2a3bca6f0.png)
Is that ok if the part of the title selected on the screenshot (Unit 1) will be hidden in pdf?

**Comment by lwtchu** [comment]
@ajluk ooh yeah i think it'll be ok to hide it in the PDF - i forgot there's a UNIT 1 label up top.

**Comment by ajluk** [comment]
Screenshots for reference: 
![image](https://user-images.githubusercontent.com/55203598/147114472-31f2fa01-5e95-4c5a-8d92-ad21a4708e3a.png)
![image](https://user-images.githubusercontent.com/55203598/147114528-13b85c19-163c-4c05-a4c9-17d0c0c582a0.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-01-03 12-22-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/67607e17-0b86-4ef8-8308-91eed19b134c)![Screenshot from 2022-01-03 12-22-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3de29ee5-6398-4922-bff2-63200e7fd7bf)
