### ISSUE TITLE
finance (and other books with footnotes) - update old footnote to new tagging structure

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4317]
![Screenshot 2021-12-20 142153](https://user-images.githubusercontent.com/11299125/146827942-33a82c71-114f-45ae-b787-1e12814359e1.png)  

It's labeled as Footnotes (old) and I think there's a numbering issue. Can someone check the Finance recipe to make sure it matches 

Phil thinks it was fixed here: https://github.com/openstax/cnx-recipes/issues/2359 
Something about collated sections footnotes get numbered first before they move the content. The CNX-Recipes change might not have been  made to kitchen.

So far other books impacted:
Entrepreneurship
Algebra and Trig

**Comment by philschatz** [comment]
This might be related: There was a change in cnx-recipes that maybe didn't make into kitchen? #2397

Also, the `Footnotes (old)` in red is from the spymode browser extension so it is not in the content

**Comment by KarinaMendez2** [comment]
The fix exists in kitchen - all good

**Comment by lwtchu** [comment]
@KarinaMendez2 is there a reason why the finance book is still using the old one?
