### ISSUE TITLE
political science - support video titles  in video feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4318]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know
![Screenshot 2021-12-20 164937](https://user-images.githubusercontent.com/11299125/146844304-98c14fa0-8071-4a89-b27b-3bf1b46d9e1f.png)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
Yes

# Sample mark up if applicable
```
 <note class="media-video" id="note-00001">
      <title>What Is An Interest Group?</title>
      <media alt="atoms_isotopes">
      <iframe width="660" height="371.4" src="https://openstax.org/r/virginiapublic"/>
      </media>
      </note>
```

# Acceptance Criteria
Please style the title like the other titled notes

font: archivo
weight: medium, 500
color: black #000000
font-size: font-scale(1): 10.8pt, 14.4px, 1.2rem

# Bug Location(s)
collection ID: col00000
github openstax/osbooks- link: https://github.com/openstax/osbooks-introduction-political-science
chapter/section: there's two - one in What Are the Pros and Cons of Interest Groups? and t he other in Political Parties
surrounding text:

**Comment by wilkus27** [comment]
@lwtchu repo with content doesn't exist anymore :eyes: Is there a new one? I can't find any repo with `political` in the name.

**Comment by Stackblocks** [comment]
Displays according to the specs in the test data.

![2022-01-11_12-00-29.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/71a81b8b-daf6-451d-b827-886730fa9ba3)
