### ISSUE TITLE
Content Parsing - setLinksAttributes - set target to blank and add rel to links 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4319]
# Purpose
set target to blank and add `rel` to links that begin with http:// or https:// or // and set target blank and allow indexing links to other books for links that begin with ../ 
![Screenshot 2021-12-21 100427](https://user-images.githubusercontent.com/11299125/146961277-8213736a-31cd-469c-93b7-0c5c633f01b4.png)

# Acceptance Criteria
-  all links have target set to blank `target="_blank"` and `rel="noopener nofollow"` 
- I do not think this will impact the PDF - please confirm if I'm right or wrong :joy:

**Comment by kswanson33** [comment]
> and allow indexing links to other books for links that begin with ../

What's the AC for this? Should `../` links also get the attributes?

This seems like it might be connected to [linking iframes to rex](https://github.com/openstax/cnx-recipes/issues/4233), since that also works with `../` links.

**Comment by lwtchu** [comment]
from beth ::
```
for each link that has an href
   if the href starts with 'https://' or 'http://' or '//'
      add target='_blank' and rel='noopener nofollow'
   else if the href starts with '../'
      add target='_blank' and remove the rel attribute
```

**Comment by lwtchu** [comment]
Still blocked by ideal behaior for internally hosted resources. See epic for more information

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ea421801-d3d7-4fb5-b245-22c0ba024295)
