### ISSUE TITLE
Astronomy TOC appendices v far apart

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4320]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know

old on the left, new git pdf on the right
<img width="1610" alt="Screen Shot 2021-12-20 at 9 12 14 AM" src="https://user-images.githubusercontent.com/1895432/147001162-c356fb44-5caf-402b-9ae0-b97d2b8f7e28.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
there's only one toc
# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: https://github.com/openstax/osbooks-astronomy
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
I think this hits all cardboard theme. Is the spacing due to the general padding we've set for the chapters?

**Comment by ajluk** [comment]
@lwtchu Yes, the spacing is due to the general padding we've set for `li` items (chapters, appendices, etc.) in the toc: 
![image](https://user-images.githubusercontent.com/55203598/148210138-51b0e692-c0b4-431f-b9a8-5966a6a3686a.png)

**Comment by lwtchu** [comment]
@ajluk i th ink the padding is good - can we make a separate issue for the page break issue?

**Comment by ajluk** [comment]
@lwtchu Thank you! Here is the separate issue I opened for page rule: https://github.com/openstax/cnx-recipes/issues/4350

**Comment by ajluk** [comment]
@MartaSztuka while testing these issue please check also Computer Science, because of units and icon presence in the ToC and some other random book from cardboard theme.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Astronomy
![Screenshot from 2022-01-11 11-42-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2c285913-05f7-426b-b84b-ce6994f8069b)![Screenshot from 2022-01-11 11-42-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/764601e3-a229-47b6-9653-4e96c1d0393d)
##### Finance
![Screenshot from 2022-01-11 12-02-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/70e8f677-9985-4405-a44b-1d15d40e6cda)
##### Intro business
![Screenshot from 2022-01-11 12-12-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8ba0db6d-8971-4e8c-a300-ef76bc323d48)![Screenshot from 2022-01-11 12-12-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/47a0b693-2256-4356-99b2-aae8cef7846b)
##### Computer Science
![Screenshot from 2022-01-11 13-00-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3eea7045-ce27-449d-b8be-0a9e45945753)
