### ISSUE TITLE
[do not start - needs Larissa's review] evaluate behavior of footnotes in PoliSci

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#4321]
# Brief Description of Change and Screenshots
What kind of change is this? [ ] recipe [ ] styles [x] i don't know

Anthony flagged, on FOLIO pages 40-41 of this PDF, that several footnote references occur in the paragraph on FOLIO pg. 40 but the footnote does not start until FOLIO pg. 41. Are footnotes working as intended?

![Screen Shot 2021-12-21 at 6 11 19 PM](https://user-images.githubusercontent.com/7863733/147013541-9707571e-6c2f-49fd-9e2b-79d4b5e6a2ea.png)

# Acceptance Criteria
TBD/Larissa

# Content Location(s)
collection ID:
github openstax/osbooks- link:
chapter/section: 
surrounding text:

**Comment by lwtchu** [comment]
@openstaxalina this might be the ongoing footnote mystery of when it decides to go to the next page and when it decides to not. it is most likely going to the next page due to the amount of footnotes. I'm wondering if it'll get better if we upgrade to the new prince?

**Comment by openstaxalina** [comment]
@lwtchu sounds good; if there's no identifiable bug to fix now, you could close this issue or track it with "things to investigate post-Prince upgrade". the main thing is that the footnotes are showing!

**Comment by lwtchu** [comment]
@openstaxalina there is no improvement to prince 14 other than it telling us that it won't fit in the errors when we generate locally :sob: so I'm closing for now.
