### ISSUE TITLE
OPS-0013 Finance - Table alignment issue in Preface section

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4323]
Table elements are didn't support in the preface section. Kindly find the below screenshot and resolved this issue.

![Preface_Table](https://user-images.githubusercontent.com/86622862/147338379-3c18a283-b356-44b6-9648-a5deb4bf3072.png)

# Bug Location(s)
collection ID: col00006
github openstax/osbooks- link: https://black-spoonbill-qjwe2jp5.ws-us25.gitpod.io/
chapter/section: Preface
surrounding text: chapters, as indicated in the following table of contents:

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-01-04 12-21-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3008009f-c6ea-495d-95aa-37429e630089)
