### ISSUE TITLE
OPS-0013 Finance - 2nd level bullet list alignment issue in Preface section

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4324]
Second level bullet list alignments are didn't support in the preface section. Kindly find the below screenshot and resolved this issue.

![Preface_bullet](https://user-images.githubusercontent.com/86622862/147338630-63537843-7a3a-4279-b956-644ca2ce45e1.png)

# Bug Location(s)
collection ID: col00006
github openstax/osbooks- link: https://black-spoonbill-qjwe2jp5.ws-us25.gitpod.io/
chapter/section: Preface
surrounding text: examine the concepts learned in each chapter.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-01-04 12-21-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b009e67f-7418-4833-8523-e40df33930be)
