### ISSUE TITLE
OPS-0013 Finance - bullet list alignment issue in Think it Through section

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4327]
Bullet list alignments are incorrect in Think it Through section. Kindly check and resolve this issue.

![Think it through_bullet](https://user-images.githubusercontent.com/86622862/148008821-183e86b3-4982-448b-91f8-699ea8e279f9.png)
![Think it through_cnxml](https://user-images.githubusercontent.com/86622862/148008824-8c63d139-3264-44ee-aa46-4c322cbc4dfb.png)

# Bug Location(s)
collection ID: col00006
github openstax/osbooks- link: https://black-spoonbill-qjwe2jp5.ws-us25.gitpod.io/
chapter/section: Chapter 4/Section 4
surrounding text: Normal repair and maintenance on the manufacturing facility

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-01-05 13-42-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e2638c5a-9dc5-4188-a8b8-9b43b6a6e963)

**Comment by srm-openstax** [comment]
@MartaSztuka , @lwtchu - Please suggest the solution as it says this is passed but we are still getting bullets outside the box in PDF version for Chapter 4

**Comment by wilkus27** [comment]
@srm-openstax These changes are not released yet. To be able to see them you should generate PDF on current milestone branch https://github.com/openstax/cnx-recipes/pull/4313.

**Comment by lwtchu** [comment]
@srm-openstax  Again, as a reminder, I will email you when the changes are out.
