### ISSUE TITLE
Spanish Stats Bundle EOC Title Capitalization/Changes

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4328]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know

From final QA review from vendor, these are the EOC titles that need capitalization modified/text edited:

Tarea -> Tarea para la casa
Revisión del Capítulo -> Repaso del capítulo
Revisión de Fórmulas -> Repaso de fórmulas
Uniéndolo todo: Tarea -> Resúmalo todo: tarea para la casa
Uniéndolo todo: Práctica -> Uniéndolo todo: Práctica

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?

# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID: col10060/col10046
github openstax/osbooks- link: https://github.com/openstax/osbooks-introduccion-estadistica-bundle
chapter/section: ToC
surrounding text: Contenido

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
This should be in the es file in Kitchen or recipes (?)

**Comment by lwtchu** [comment]
@KarinaMendez2 checking with you re: grammar in Spanish about capitalization...I'll message you

**Comment by lwtchu** [comment]
Confirmed grammatically that only the first letter should be capitalized. 

We can change the es files for the 6 spanish books.

**Comment by yblock** [comment]
my attempt at these changes, github wont let me PR

`es:
  eoc_free_response: 'Tarea para la casa'
  eoc:
    summary: 'Repaso del capítulo'
    formula-review: 'Repaso de fórmulas'
    practice: 'Práctica'
    bring-together-homework: 'Resúmalo todo: tarea para la casa'
    bring-together-exercises: 'Uniéndolo todo: Práctica'
    free-response: 'Tarea para la casa'
    solutions: 'Soluciones'
  notes:
    try: 'Inténtelo '
    lab: 'Laboratorio de estadísticas '
    collab: 'Ejercicio Colaborativo'
    calculator: 'Uso de la calculadora TI-83, 83+, 84, 84+'
    chapter-objectives: 'Objetivos del Capítulo'
`

**Comment by KarinaMendez2** [comment]
oop, I'm actually assigned to it lol I'll make a PR for it tomorrow :)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![2022-01-12_09-47-21.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ba37f9ef-cc9f-41ee-baef-d5933f06b533)
