### ISSUE TITLE
Spanish Stats bundle missing "Introduction" translation 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4329]
Spanish Stats bundle missing "Introduction" translation at top of page near page number:

![Screen Shot 2022-01-04 at 9.22.29 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/822dfc27-d29f-4b75-b69c-aa2014a65d18)

**Comment by lwtchu** [comment]
It's translated everywhere else - where does the folio translation come from? It should be `Introducción`

Please make sure the English book isn't impacted

**Comment by kswanson33** [comment]
I fixed this across all themes; English books should still say "Introduction" in the top corner, while Spanish books should be translated.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e25655c1-8cb4-4eab-b8ac-24782006f528)
