### ISSUE TITLE
Spanish Stats bundle missing decimal number for example solutions

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4330]
Example 1.1 should have solution 1.1, not just 1:

![Screen Shot 2022-01-04 at 9.25.09 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/453b9541-5a99-42d5-be8d-5055052f27a0)

**Comment by lwtchu** [comment]
@yblock i think that's  supposed to be numbered for things that have two solutions. can you put an  unnumbered class on that solution?

**Comment by yblock** [comment]
I'm just comparing with the English PDF to find discrepancies. This is book-wide, and has the decimals in English versions.

**Comment by lwtchu** [comment]
@yblock 🤔 which is the english version that you're using? like latest generated from corgi or on prod?

**Comment by lwtchu** [comment]
will not fix. ideally there should be an unnumbered class on the exercise with one solution
