### ISSUE TITLE
Spanish Stats - support para and list titles

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4332]
Title within a section are not bold:

Spanish:
![Screen Shot 2022-01-04 at 10.29.20 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/1bed1d13-bb87-42f4-b16d-14a57c9c647f)

English:
![Screen Shot 2022-01-04 at 10.29.15 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/990405cc-352e-4eb9-9fd6-490cdabbf7a5)

**Comment by lwtchu** [comment]
No change for this one

**Comment by yblock** [comment]
@lwtchu Further down the PDF they also not that titled things in this form don't seem to be treated as title at all, no bold and no new-line. Example screenshot has a title highlighted for example:

![Screen Shot 2022-01-04 at 10.41.38 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/29f58e69-b6f0-42b8-b527-5de7d25ea8f7)

**Comment by lwtchu** [comment]
@yblock do you have the mark up or location

**Comment by yblock** [comment]
@lwtchu here is one example of this, there are many as you could imagine since titles are all over the place. 

https://github.com/openstax/osbooks-introduccion-estadistica-bundle/blob/46889eb2580ea604dcdede0c5183fecd981ccfb3/modules/m50257/index.cnxml#L21

**Comment by lwtchu** [comment]
i see -_- it's nested paragraph title in a list. which..we don't typically support

**Comment by lwtchu** [comment]
# Acceptance Criteria

I think it is time to support List and  Para titles. 

Is there a way to target them so it's just Bolded base font and there's a line break?

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/aa5daafb-f8ee-4bde-8ad9-ad51fe6c9c05)
