### ISSUE TITLE
Spanish Stats bundle equations are not centered and have extra text added 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4333]
In the two math equations below for example, the phrase "Los términos" is being added before the equation which is not present in the English versions. I also noticed that when the equation has no space between the para tag and the equation tag it does center it, but I will be fixing the missing space which means equations aren't centering properly. 

![Screen Shot 2022-01-04 at 10.38.07 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/1da30d70-075c-477a-aca1-a699f3d47605)

**Comment by yblock** [comment]
note to self: table summaries need to be translated

**Comment by lwtchu** [comment]
`La siguiente fórmula proporciona esta información:</para><equation id="eip-249"><m:math><m:msup><m:mrow><m:mo>(</m:mo><m:mfrac><m:mrow><m:msub><m:mi>a</m:mi><m:mi>n</m:mi></m:msub></m:mrow><m:mrow><m:msub><m:mi>a</m:mi><m:mn>0</m:mn></m:msub></m:mrow></m:mfrac><m:mo>)</m:mo></m:mrow><m:mrow><m:mfrac><m:mn>1</m:mn><m:mi>n</m:mi></m:mfrac></m:mrow></m:msup><m:mo>=</m:mo><m:mover><m:mi>x</m:mi><m:mo>~</m:mo></m:mover></m:math></equation><para id="eip-931">Por último, observamos que la fórm`

Module: m62299
Repo: https://github.com/openstax/osbooks-introduccion-estadistica-bundle

Is the Los terminos auto injected? And if so, can we remove?

**Comment by KarinaMendez2** [comment]
I was unable to replicate the extra text `Los términos`. @lwtchu added the classname `unnumbered` and that fixed the `centering` part.

**Comment by lwtchu** [comment]
@Stackblocks this is in regression testing to see if we can see it happening on corgi again. I'm hoping the release will...reset everything and make it go away

**Comment by openstaxalina** [comment]
In the CORGI jobs from 4 days ago, we don't see Los términos:

https://openstax-cops-artifacts.s3.amazonaws.com/introducci%C3%B3n-estad%C3%ADstica-empresarial-latest-git-3085.pdf
<img width="653" alt="Screen Shot 2022-01-11 at 3 15 25 PM" src="https://user-images.githubusercontent.com/7863733/149022560-c4b856ba-b2e6-40ee-91a8-ea30a6512de5.png">

https://rex-web.herokuapp.com/books/f346fe75-ae39-4d11-ad32-d80c03df58cb@7b61baa/pages/2-5-media-geometrica?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20220105.181309
<img width="839" alt="Screen Shot 2022-01-11 at 3 14 18 PM" src="https://user-images.githubusercontent.com/7863733/149022557-afe7827a-190c-4d61-af49-d92a72ddb359.png">

With Larissa's permission, I am closing this issue.
