### ISSUE TITLE
Spanish stats - supporting lists in key terms (glossary)

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4338]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know

![Screen Shot 2022-01-05 at 1.07.51 PM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/ace8b866-d35a-4710-acf0-8ebc1ba4b854)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
first time i've seen it, not sure the cause

# Sample mark up if applicable

`<section id="fs-idm59813888" class="summary"><title>Repaso del capítulo</title><para id="fs-idp48275616">Un experimento estadístico se puede clasificar como experimento binomial si se cumplen las siguientes condiciones:</para>
<list id="fs-idm159853952" list-type="enumerated"><item>Hay un número fijo de ensayos, <emphasis effect="italics">n</emphasis>.</item>
<item>Solo hay dos resultados posibles, denominados “acierto ” y “fallo” para cada ensayo. La letra <emphasis effect="italics">p</emphasis> indica la probabilidad de acierto en un ensayo y la <emphasis effect="italics">q</emphasis> la probabilidad de fallo en un ensayo.</item>  
<item>Los <emphasis effect="italics">n</emphasis> ensayos son independientes y se repiten utilizando condiciones idénticas.</item>
</list><para id="fs-idp5771264">Los resultados de un experimento binomial se ajustan a una distribución de probabilidad binomial. La variable aleatoria <emphasis effect="italics">X</emphasis> = el número de aciertos obtenidos en los <emphasis effect="italics">n</emphasis> ensayos independientes. La media de <emphasis effect="italics">X</emphasis> se puede calcular mediante la fórmula <emphasis effect="italics">μ</emphasis> = <emphasis effect="italics">np</emphasis`

# Acceptance Criteria

# Bug Location(s)
collection ID: 
github openstax/osbooks- link: https://github.com/openstax/osbooks-introduccion-estadistica-bundle
chapter/section: 4.4 Términos Clave
surrounding text: Un experimento estadístico se puede clasificar como experimento

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
![Screenshot 2022-01-06 105012](https://user-images.githubusercontent.com/11299125/148419463-2eafdfcb-ab91-4ce1-baff-6f8554522520.png)
CONFIRM it happens in the English as well

**Comment by kswanson33** [comment]
styling for ordered lists is now implemented across corn

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5f91feda-7e58-4aa2-b54f-578a9ac2c337)
