### ISSUE TITLE
Spanish Stats missing section number in Practice 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4339]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know

Missing x.0 section numbering when there is an entry for an Introduction module. Review questions, Practice, etc.

![Screen Shot 2022-01-05 at 1.17.16 PM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/02c7a4bd-4410-4827-ab72-b878f0a2e1b6)

# Does this happen for every instance? If no, is there a discernible pattern of occurrences?
Where there is a practice for an Introduction module this seems to happen. The regular module numbers are displayed for subsequent practices, just the x.0 ones missing. 

# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: https://github.com/openstax/osbooks-introduccion-estadistica-bundle
chapter/section: Chapter 4 Practice, section 4.0 (Introduction) 
surrounding text: Las características de una distribución de probabilidad o función de densidad (pdf) son las siguientes:

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
Introductions aren't numbered. Sorry
