### ISSUE TITLE
Spanish Statistics: Feature title change 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4342]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know

Reviewer says it should be: "USO DE LAS CALCULADORAS TI-83, 83+, 84 Y 84+"

![Screen Shot 2022-01-06 at 8.28.14 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/ac6c2498-0d32-4f1e-90c2-39c3918e7e84)

Reviewer says is should be: "Laboratorio de estadística"
![Screen Shot 2022-01-06 at 8.40.59 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/7a371cd8-8acb-4438-915e-606cb648ad0b)

# Does this happen for every instance? If no, is there a discernible pattern of occurrences?
All instances of feature title. 

# Sample mark up if applicable
class="statistics calculator"

class="statistics lab"

# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: https://github.com/openstax/osbooks-introduccion-estadistica-bundle
chapter/section: various
surrounding text: class="statistics calculator" / class="statistics lab"

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by KarinaMendez2** [comment]
this issue will be included in [this PR](https://github.com/openstax/recipes/pull/197) for [this card](https://app.zenhub.com/workspaces/ce-styles-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/4328)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![2022-01-11_17-03-08](https://user-images.githubusercontent.com/12678235/149035350-da097b11-cba9-45d3-862a-66e39430a0d2.png)
