### ISSUE TITLE
note class="finger" is not styled 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4343]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know

![Screen Shot 2022-01-06 at 12.02.28 PM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/27fa3bed-44dc-44e6-8e71-3b869e8c985b)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
All note with only the finger class look like this.

# Sample mark up if applicable
`note id="id7166567" class="finger"><label/><title>NOTA</title>`

# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: https://github.com/openstax/osbooks-introduccion-estadistica-bundle/blob/9cad8991645687d7ad9fb9e165c0cfe23616dd4a/modules/m46922/index.cnxml#L217
chapter/section: 2.7
surrounding text: Nos centraremos en la utilización e interpretación de la

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: https://github.com/openstax/osbooks-introduccion-estadistica-bundle
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
#4097 already have a card :rip:
