### ISSUE TITLE
Spanish Stats Calculator feature title change

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4346]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know

<note id="fs-idm25803056" class="statistics calculator">

![Screen Shot 2022-01-07 at 3.27.57 PM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/c784923b-7825-4dc5-b09b-125f65140823)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
every note with class="statistics calculator"

# Sample mark up if applicable
<note id="fs-idm25803056" class="statistics calculator">

# Acceptance Criteria
Title for this feature should be changed to "USO DE LAS CALCULADORAS TI-83, 83+, 84 Y 84+"
# Bug Location(s)
collection ID:
github openstax/osbooks- link: https://github.com/openstax/osbooks-calculus-bundle
chapter/section: various
surrounding text: USO DE LA CALCULADORA TI-83, 83+, 84, 84+

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link:  
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
colbito this is already opened https://github.com/openstax/cnx-recipes/issues/4342
