### ISSUE TITLE
Page break rule for top level li for chapters in ToC

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4350]
A page break rule needs to be added to top level `li` for chapters to prevent page break after these titles in the ToC (Example is from Astronomy): 
![image](https://user-images.githubusercontent.com/55203598/148734909-1050b37c-68e8-4286-9bad-bdea7bbd3c98.png)

**Comment by lwtchu** [comment]
# Acceptance Criteria

Let's just have only 1 other line go with it or 2. Not the whole thing. If it's the whole think I think it'll result  in big big gaps

**Comment by ajluk** [comment]
@lwtchu I have added `page-break-before: avoid` rule to the `ol.os-chapter`container for the li chapter pages: 
![image](https://user-images.githubusercontent.com/55203598/149163049-166110dc-b7f2-402b-bc04-9107d36674f5.png)
Now the page is breaking only after each chapter pages depends on the amount of left space (not before them all after chapter title): 
![image](https://user-images.githubusercontent.com/55203598/149162576-c4b18ea8-06da-433f-ad08-e1a33a9fa802.png)
![image](https://user-images.githubusercontent.com/55203598/149162611-f6a95e54-34e4-452a-888c-da5f83ec531f.png)
![image](https://user-images.githubusercontent.com/55203598/149162633-b27b9dc1-b819-4c9c-982d-2d52b396a8d6.png)

**Comment by lwtchu** [comment]
@ajluk this is good i'll move this to the next sprint though

**Comment by lwtchu** [comment]
@ajluk jk it's already in the next sprint

**Comment by ajluk** [comment]
@lwtchu Could you also advice which books should be tested within this issue? The changes affects all of them.

**Comment by lwtchu** [comment]
New books publishing soon:
- anthropology
- spanish statistics

The CMs should be able to test the revision books

**Comment by MartaSztuka** [comment]
#### PASSED
##### Astronomy
![Screenshot from 2022-01-19 10-37-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7d69a1d6-6792-424e-a66a-df9844c343d2)
##### Psychologia
![Screenshot from 2022-01-19 13-03-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/54791150-7db4-48e3-9656-1612f88dbf57)
##### Fizyka
![Screenshot from 2022-01-19 13-05-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8865496c-abf4-4778-9f02-f26d25086fde)
