### ISSUE TITLE
[probably when we do Baked Styles for Web] Do Not Display "Click to view content" on the Web View when iframe is present

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#4352]
# Brief Description of Change and Screenshots
What kind of change is this? [ ] recipe [ ] styles [x] i don't know

The "Click the view content" message is redundant in this context:

<img width="1317" alt="Screen Shot 2022-01-10 at 11 39 17 AM" src="https://user-images.githubusercontent.com/7863733/148812462-4b849425-a166-4460-9732-a1e47e632911.png">
https://rex-web-production.herokuapp.com/books/052b8372-0c5e-4ff6-8fd3-326377e9e91f@324e2b3/pages/14-video-activity?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20211111.153520

While we want that message on the PDF to give people something to click (I think), it is redundant and confusing on the web because the same content is displaying in the iframe just below. Also, students can click within the video itself to open the content on its own tab in YouTube. 

Since this necessitates different behaviors on web and PDF, I think it makes most sense to do this when we have the baked styles **for web** infrastructure in place. 

# Acceptance Criteria
- [ ] In REX, "Click to view content" no longer displays above iframes, in any book with such content

# Content Location(s)
collection ID:
github openstax/osbooks- link:
chapter/section: 14 (or most/any chapters) - "Video Activity" composite page
surrounding text: "Based on the scatter plot shown,"

**Comment by lwtchu** [comment]
We solved this with #4765
