### ISSUE TITLE
investigation: test prince 13 and 14 on existing titles 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4353]
It is time to upgrade Prince XML. 

1. Please download and install 13 and 14 from https://www.princexml.com/
2. Make a PDF of College Physics, College Algebra and Writing Guide from both versions.
3. Send to Larissa 

If there's anything that breaks or doesn't work, please also let Larissa know. And if you have any opinions about what will need to be changed, what is good/bad about each, feel free to share

**Comment by lwtchu** [comment]
Currently no major issues besides
- tokens in College Algebra needs a font installed
- https://github.com/openstax/cnx-recipes/issues/4376
- and ...I think that's it

**Comment by ajluk** [comment]
-  warning about `@top-middle` page region property will be no longer supported: 
![image](https://user-images.githubusercontent.com/55203598/150185408-32c97e9a-3318-4786-992a-062876d3c2bc.png)
we use it in folio file for introduction pages: 
![image](https://user-images.githubusercontent.com/55203598/150185501-11f4f1e1-db03-4c38-b585-afbee2a9b542.png)
It can be replaced though by `@top-center` (from Prince documentation): 
![image](https://user-images.githubusercontent.com/55203598/150185662-0f85e527-e49b-43bb-a1bc-f64f565890da.png)
This warning appeared when testing Finance and Contemporary Math. It is currently used in corn and cardboard theme folio files.

**Comment by lwtchu** [comment]
Closing since we already upgraded
