### ISSUE TITLE
Extra page space after Composite Chapter Wrapper

### ISSUE THREAD

**Issue by LostMojo** [openstax/cnx-recipes#4359]
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ x ] i don't know

There's an extra page of blank space after the wrappers for composite chapters (i.e. "Assignments" or "Chapter Review"

Occurs in: 
World History

![Screen Shot 2022-01-12 at 11.29.56 AM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/1c86f85c-225e-46e9-986e-5f1807d3d153)

Computer Science:

![Screen Shot 2022-01-12 at 11.31.32 AM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/c5f17bbf-6174-4990-9731-12bd6bcf599a)

**Comment by lwtchu** [comment]
@LostMojo i put this in B.B - there is a place for page break rules  -that might be where it's getting the rule?

**Comment by wilkus27** [comment]
@LostMojo I think that changing `firstSelector` here https://github.com/openstax/cnx-recipes/blob/cb28438a4d0f370da2045c22d4d230221fe0734b/styles/books/world-history/book.scss#L2 to class for composite chapter would help :thinking:
