### ISSUE TITLE
[DART-SASS] update styles/build/build.js

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4363]
`styles/build/build.js` **

Kendra thinks we can skip this and other recipe-related things because recipes are now in Kitchen. Please confirm first. We shouldn't remove until we are completely off Legacy though. SO DO NOT REMOVE and we can keep this card to deprecate when legacy is finally gone.

**Comment by Stackblocks** [comment]
Is there a local testing step needed for this? If so, can you provide details on what constitutes the acceptance criteria for this card? Thanks!

**Comment by lwtchu** [comment]
I think this was already refactored and we're already using it x_x Going to close :joy:
