### ISSUE TITLE
carnival theme: footnotes

### ISSUE THREAD

**Issue by damondemar** [openstax/cnx-recipes#437]
![Screen Shot 2019-08-06 at 4 58 46 PM](https://user-images.githubusercontent.com/11299125/62580297-7c6c6200-b86b-11e9-84a9-a1fc40ac86e5.png)

Should be Alegreya Regular 1.2rem (9pt)
Width of line: 110 px (11rem)
Line stroke weight: 0.5pt 
Line is 1 line height above the text

** All footnotes across all titles so be NO SMALLER than 1.2rem (9pt)
Footnotes are generally a superscript number BUT should be able to support symbols as well

**Comment by lwtchu** [comment]
@wilkus27 i added more specs. let me know if you need any clarification!

**Comment by wilkus27** [comment]
Thank you! :smiley:

**Comment by Stackblocks** [comment]
Please take a look at the footnotes, they're interacting weirdly with their neighbors. 

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ea821edd-05f4-4d3a-baea-6e77fa516a3c)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/2316ca9d-534d-4cd3-80b1-e4fcd5bbd155)

**Comment by wilkus27** [comment]
About first screenshot, this is the part of content, regular list, not footnote.

About second one, generally footnotes should display at the bottom of the page with last paragraph of module which contains footnote call. After discussion with Helene: the future goal will be to prevent the titles and learning objectives to be breaking apart.

**Comment by Stackblocks** [comment]
Following review by Helene and Natalia, marking as closed. We will handle the content breaking issue in a separate tracker.
