### ISSUE TITLE
[DART-SASS] project wrap up and completion

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4370]
Once all styles can be built with `styles/build/build.dart`:
- [ ] update script/build-styles to call `styles/build/build.dart`
- [ ] update documentation

**Comment by kswanson33** [comment]
- [ ] switch `./script/build-styles` to calling `dart` instead of `node`
- [ ] switch `./script/build-impacted-styles` to calling `dart` instead of `node`
- [ ] recompile styles with dart to get rid of unimportant diffs

**Comment by LostMojo** [comment]
Complete in #[4601](https://github.com/openstax/cnx-recipes/pull/4601) , but it seems like a card wasn't created for me to link to

**Comment by LostMojo** [comment]
To test:
- Do build-styles and build-impacted-styles run build.dart?
- Does any given book style take under 30s to build?
- Are the chapters' first pages still styled correctly? (If there's a problem or a difference with the aesthetic changes to the CSS, they'd show up here)

**Comment by kswanson33** [comment]
`build-styles` and `build-impacted-styles` run `build.dart` & the performance is improved as expected 👍
