### ISSUE TITLE
updates to code and pre html outputs for rex use

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4372]
There are long threads and documents about this issue, but the way code transforms into HTML has caused some inconsistencies for REX

https://openstax.slack.com/archives/CH5514N57/p1642092367021600
https://docs.google.com/document/d/1tU7V0J0BS7YCo3r2rkK4zWhm1SqCSLwwHDglAlCJcik/edit#heading=h.4d2qa3i46m2d

First is to add data-type="code" to the output. data-lang should be already set by the CNXML content.\

Adding finance and comp sci label since these snippets are prevalent in these books and have special  pedagogical functionality

**Comment by lwtchu** [comment]
(Phil's PR is attached - it's a draft rn)

**Comment by philschatz** [comment]
The PR was merged, a [new one](https://github.com/openstax/nebuchadnezzar/pull/212) was created and is now waiting on review and should be in enki soon after (just one more PR after that :sweat_smile: ).

**Comment by lwtchu** [comment]
:eyes: both got merged so i['ll close this
