### ISSUE TITLE
Organize References by Chapter Title in Psychology, Am Gov and Poli Sci + other books (webview)

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#4374]
# Brief Description of Change and Screenshots
What kind of change is this? [x] recipe [ ] styles [ ] i don't know

Right now, a bunch of our books in the library have reference sections in which they do NOT have chapter subtitles so the page is just a giant list of references that start over alphabetically per chapter. For users, it would be better if this list had chapter subtitles to indicate when the list ended for one chapter and began for the next. Anthony has specifically requested this change be made in Psychology as it's being revised this March.

Note that the PDF is already like this; the issue only occurs in webview. Here are links to the webview and pdf for you to PERUSE:

[PDF](https://openstax-cops-artifacts.s3.amazonaws.com/col31502-latest-production-3039.pdf)
[Web Preview](https://rex-web.herokuapp.com/books/06aba565-9432-40f6-97ee-b8a361f118a8@6.15/pages/preface?archive=https://openstax.org/apps/archive-preview/20211213.222327)

Screenshot of Psychology 2e:

![Screen Shot 2022-01-14 at 9.40.34 AM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/8c7f19f3-150f-4bda-944a-d6ff2480bd6d)

# Context
Because of this card https://app.zenhub.com/workspaces/openstax-unified-5b71aabe3815ff014b102258/issues/openstax/unified/1690, any `h2[data-type="document-title"]` gets removed. Is it possible to add `data-rex-keep=true` somewhere on the headers ONLY in the reference titles.

# Acceptance Criteria
- Webview resembles the pdf in that the reference section is organized by chapter titles. 
- PDF Styling does not change
- only change is `h2[data-type="document-title"]`

# Content Location(s)
collection ID: col31502
github openstax/osbooks- link: not totally migrated to poet yet.
chapter/section: references
surrounding text: references

**Comment by lwtchu** [comment]
It this our thing? Where the titles are injected by the PDF pipeline? vs Recipes? Can we have it be injected by recipes instead so it'll carry over to REX? 

If I'm wrong please let me know

**Comment by wilkus27** [comment]
@lwtchu It's a REX thing. I talked about it with Bartek when he was working here. As I remember in REX they are removing H2 titles (or H3 :thinking: ) because there were redundant:

![image](https://user-images.githubusercontent.com/40228854/150349622-3ccec069-0d01-4036-9997-6872b996ec89.png)

But they didn't specify it should be just first title not all from the page. I think it was fixed for EOC sections, but probably they should open a card for EOB References too.

**Comment by lwtchu** [comment]
oooooh interesting - i wonder if this is something we can fix with baked styles later. 🤔 i'll move it to the backlog for now. thank you for the context

**Comment by openstaxalina** [comment]
CE Styles is adding an attribute which @bethshook knows about -- so REX knows not to remove these titles.

**Comment by openstaxalina** [comment]
I see the chapter titles in the [REX Prod preview](https://rex-web-production.herokuapp.com/books/89060098-2918-4037-8ebe-d90622d7a6bf@577c8a3/pages/references?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20220411.192702), after their release today which included [this card](https://github.com/openstax/unified/issues/1870).

@lwtchu please review and confirm this can be closed when you get the chance.

**Comment by Stackblocks** [comment]
Both halves of this appear to be in place now.

![2022-04-22_14-13-11.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/368b821a-06d6-4021-a4f2-87a98180e86d)
