### ISSUE TITLE
0013-Philosophy - Figure and Table link issues in Webview

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4382]
We have received the below correction from customer, and we coded as per the tagging legend. We faced this issue with all the figures and table links in WebView. Kindly check and resolve this issue.

**When I click the Table 5.1 in both hyperlinks in this paragraph, it only works the first time.**

Bug Location(s)
collection ID: col00005
github openstax/osbooks- link: https://coffee-grouse-ulafn81g.ws-us25.gitpod.io/
chapter/section: Chapter 5/Section 3
surrounding text: use words that indicate a conclusion—for example, “therefore” or “hence”

**Comment by lwtchu** [comment]
Known global issue for webview - will not be fixed before publication.

**Comment by lwtchu** [comment]
This is how links within a page work if pointed to a specific ID.
