### ISSUE TITLE
contemporary math - list out of margins in examples

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4383]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know

![image](https://user-images.githubusercontent.com/11299125/150175059-483a3ec7-2941-4cab-a3a6-e30132a511e5.png)
![image](https://user-images.githubusercontent.com/11299125/150175168-ae891c39-08ff-4506-9cfa-d19094c32f76.png)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
yes

# Sample mark up if applicable
```
  <title>Expressing the Relationship between Sets Symbolically</title>
    <exercise id="exer-00005">
    <problem id="prob-00005">
    <para id="para-00023">Consider the subsets of a standard deck of cards:
    <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>S</mi><mo>=</mo><mo>{</mo><mi mathvariant="normal">spades, hearts, diamonds, clubs</mi><mo>}</mo></mrow></math>; <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>R</mi><mo>=</mo><mo>{</mo><mi mathvariant="normal">hearts, diamonds</mi><mo>}</mo></mrow></math>; <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>B</mi><mo>=</mo><mo>{</mo><mi mathvariant="normal">spades, clubs</mi><mo>}</mo></mrow></math>; and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mi>C</mi><mo>=</mo><mo>{</mo><mi mathvariant="normal">clubs</mi><mo>}</mo></mrow></math></para>
    <para id="para-00024" xmlns="http://cnx.rice.edu/cnxml">Express the relationship between the following sets symbolically.</para>
    <list list-type="enumerated" number-style="lower-alpha" id="list-00007">
    <item>Set S and set B.</item>
    <item>Set C and set B.</item>
    <item>Set R and R.</item>
    </list>
    </problem>
```

# Acceptance Criteria
Please boop them back into the margins

# Bug Location(s)
collection ID: osbooks-contemporary-math/contemporary-math
github openstax/osbooks- link: https://github.com/openstax/osbooks-contemporary-math
chapter/section: chapter 1
surrounding text: Expressing the Relationship

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![2022-01-25_14-53-18.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8938127f-9cae-476a-ba02-374ed5a11664)
