### ISSUE TITLE
Unset font family for H4 link titles in cardboard theme

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4384]
During testing Prince 14 on Finance a font family error occurred:
![image](https://user-images.githubusercontent.com/55203598/150183834-7c563dc5-5d6f-4921-8b6e-3dd22255c181.png)
After checking it appeared that font-family in for h4 link headers was set in the `_titles-components.scss` file instead of the `titles settings files`: 
![image](https://user-images.githubusercontent.com/55203598/150184197-c8490695-0676-4416-b5a4-67f0311d14ed.png)
![image](https://user-images.githubusercontent.com/55203598/150184281-94e65ae7-89ef-49ae-a2bf-6be8d6bc413a.png)

**Comment by ajluk** [comment]
@MartaSztuka This issue can be tested on bca book in the EoC secions chcking if the H4 link titles has correct font-family set: 
![image](https://user-images.githubusercontent.com/55203598/151171837-79446535-f11e-4146-962b-71e4d325222e.png)

**Comment by MartaSztuka** [comment]
#### PASSED
##### BCA
![Screenshot from 2022-01-26 15-34-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bde0e764-4750-40b0-b36b-38af60de24d7)
##### Finance
![Screenshot from 2022-01-26 15-41-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1472e059-a211-4209-abd4-022057bfa73d)
