### ISSUE TITLE
Unstyled nested ul list in Anthropology

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4387]
Nested `ul` list appears unstyled in Chapter 20.3 in Anthropology:
![image](https://user-images.githubusercontent.com/55203598/150309557-13bb89f8-2142-490d-b562-df0f5a5ea8d4.png)
![image](https://user-images.githubusercontent.com/55203598/150309418-583a6719-af72-4c1c-b2a5-c8768135c1f6.png)
Surrounding text: The American Anthropological Association (AAA) (https://openstax.org/r/ParticipateAndAdvocate) has
identified five public policy areas

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5c62de3d-155c-4e5a-83dd-d08fef3395c7)
