### ISSUE TITLE
EOC titles links without underline

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4388]
Links to modules in EOC sections don't have underline:

Polish U-Physics:

![image](https://user-images.githubusercontent.com/40228854/150342972-d31b889a-342b-4014-ba26-6d17352e53b2.png)

Business Ethics:

![image](https://user-images.githubusercontent.com/40228854/150343060-747b44a5-fb8f-41b1-be9d-8f95c109e748.png)

**Comment by wilkus27** [comment]
There are no changes in styles that remove it. Also it's working properly in `baked.xhtml` file.

![image](https://user-images.githubusercontent.com/40228854/150343319-4f6e37e4-bf03-49cf-b135-74b14d922121.png)

![image](https://user-images.githubusercontent.com/40228854/150343414-3cf96bfe-a783-4777-b4c7-54bf9232c998.png)

Side note: it was working in PDF on 12/6 https://github.com/openstax/cnx-recipes/issues/4266#issuecomment-986663154.

**Comment by wilkus27** [comment]
**UPDATE:** probably will be fixed after updating Prince to version 14.

**Comment by ajluk** [comment]
In the content generated within `enki` after Prince uodate to 14th version the EoC section links underlines are back there :tada: : 
![image](https://user-images.githubusercontent.com/55203598/153030080-8bc59fe7-c289-4c3b-b3d0-c80d4d334045.png)
