### ISSUE TITLE
pl-u-physics: align images from Answer Key

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4389]
Some of the images from Answer Key are not aligned properly with solution number or list item in it:

(Fizyka vol1, Answer Key chapter 3)
![image](https://user-images.githubusercontent.com/40228854/150344304-35d5dd90-a447-4355-bf0a-e93fbeaa666d.png)

They should display at the same level as solution number.

**Comment by MartaSztuka** [comment]
@wilkus27 Most of cases when answer starts with image are fixed, but I've found couple of issues in all 3 books.
##### Fizyka 1
###### Chapter 3
This one is fine
![Screenshot from 2022-01-27 16-20-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e384dc01-e0bb-4672-b6a4-1df86767ba82)
###### Chapter 5
Is this semicolon intentionally here?
![Screenshot from 2022-01-27 16-34-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8c85d26b-c850-4af4-a00e-5c42436465db)
###### Chapter 16
Page break between number/letter and picture.
![Screenshot from 2022-01-27 16-36-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e85f24ca-4d1c-4fb1-b8fa-9f0da76a40cc)

##### Fizyka 2
###### Chapter 3
Image in new line
![Screenshot from 2022-01-27 16-27-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0aa82ffa-d058-452b-994a-0c4820aa915a)
###### Chapter 5
![Screenshot from 2022-01-27 16-29-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8e417221-7d17-4519-b54c-707a91a3f4dc)
###### Chapter 10
![Screenshot from 2022-01-27 16-30-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6508f3ed-32b7-416b-b11d-13456bc1b624)![Screenshot from 2022-01-27 16-30-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a74b0a19-8f3e-4d6e-92dc-cba015fd1501)
###### Chapter 13
![Screenshot from 2022-01-27 16-31-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f2a314f3-35b8-4aef-b44e-dabc10d44ba1)

##### Fizyka 3
###### Chapter 2
![Screenshot from 2022-01-27 16-42-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9e0170d0-101e-402f-a45f-aff076a321a0)
###### Chapter 8
![Screenshot from 2022-01-27 16-43-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dfcff6ed-40fa-420e-8e69-1ffa1d4e1786)

**Comment by wilkus27** [comment]
After discussion with team, we decided that we will not fix problems with lists in paragraphs and newlines. Changing that might cause problem with empty spaces, and make book bigger. Only problem that we want to fix is the first one. Here is an issue for that in the content repo: https://github.com/openstax-poland/content/issues/143.

I'm closing this issue.
