### ISSUE TITLE
library wide: folio and pages 

### ISSUE THREAD

**Issue by damondemar** [openstax/cnx-recipes#439]
<img width="1090" alt="Screen Shot 2019-05-20 at 6 45 22 PM" src="https://user-images.githubusercontent.com/11299125/58058685-73eb7180-7b2f-11e9-86e5-5f1dddad2a97.png">

ON THE LEFT PAGE (all even numbered pages): `CHAPTER # • Chapter title`
ON THE RIGHT PAGE (all odd numbered pages): `#.# Module title`

Font: style matches H1, H2, H3 fonts for book example: in carnival theme it's Muli Bold
Font size: 1.2rem (9pt)
Page number: 1.2rem (9pt)

**Comment by openstaxalina** [comment]
@tomjw64 I'm not sure if this is the right time to ask this, but we are considering implementing a folio with the following specifications:

**If the title has units**
- List unit number, chapter number, and chapter title on even pages:
![Screen Shot 2019-03-19 at 11 33 06 AM](https://user-images.githubusercontent.com/7863733/54624153-d2667780-4a3a-11e9-967a-a44a64e54d70.png)
-List Section number and section title on odd pages:
![Screen Shot 2019-03-19 at 11 33 50 AM](https://user-images.githubusercontent.com/7863733/54624183-e27e5700-4a3a-11e9-92bb-b7984022204f.png)


**If the title does not have units**
Same as above except no unit number, and the chapter number will be styled with color/bolding instead.

Is it within scope right now to investigate this?

cc @helenemccarron @lwtchu

**Comment by helenemccarron** [comment]
This will require to create settings for pages see https://github.com/openstax/oer.exports/blob/master/css/refactor/page-slots.less and https://github.com/openstax/oer.exports/blob/master/css/refactor/page-skeleton.less

**Comment by brittany-johnson** [comment]
<img width="693" alt="Screen Shot 2019-08-14 at 3 56 43 PM" src="https://user-images.githubusercontent.com/24909007/63055751-3ab36b00-beac-11e9-9124-2c0701b1e25e.png">
<img width="577" alt="Screen Shot 2019-08-14 at 3 57 01 PM" src="https://user-images.githubusercontent.com/24909007/63055753-3ab36b00-beac-11e9-935d-cfaf7acdd086.png">
<img width="648" alt="Screen Shot 2019-08-14 at 3 57 07 PM" src="https://user-images.githubusercontent.com/24909007/63055754-3ab36b00-beac-11e9-9914-4ae65fb0a54d.png">

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![2019-08-15_11-44-59.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b37ab76d-2cb4-4e35-b69d-aea8183bf64a)
---
![2019-08-15_11-45-06.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8ca942d2-e72d-41ed-ab3d-31649dac4746)
