### ISSUE TITLE
Astronomy top-titled tables not top titling

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4395]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know
first page of a long table has the title at the top (new github pdf on the left)
<img width="1614" alt="Screen Shot 2022-01-24 at 7 35 32 AM" src="https://user-images.githubusercontent.com/1895432/150830604-09ba86d6-e8da-43fe-a5f9-620f54f4f6ac.png">
but the second page does not
<img width="1578" alt="Screen Shot 2022-01-24 at 7 35 40 AM" src="https://user-images.githubusercontent.com/1895432/150830776-923f3772-2d36-4bde-9fed-5d3a46eb721b.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?

# Sample mark up if applicable
`class="top-titled">`
`<tgroup cols="4">`
`<colspec colnum="1" colname="c1"/>`
`<colspec colnum="2" colname="c2"/>`
`<colspec colnum="3" colname="c3"/>`
`<colspec colnum="4" colname="c4"/>`
`<thead>`
`<row>`
`<entry namest="c1" nameend="c4" align="center">Major Radio Observatories of the World</entry>`
`</row>`
`<row valign="top">`
`<entry valign="top" align="center">Observatory</entry>`
`<entry valign="top" align="center">Location</entry>`
`<entry valign="top" align="center">Description</entry>`
`<entry valign="top" align="center">Website</entry>`
`</row>`
`</thead>`
`<tbody>`
# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: 
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
Got confused about this - i think it looks fine in the pdf sorry
