### ISSUE TITLE
Astronomy figure captions now double spaced

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4397]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know
new on the left

<img width="1576" alt="Screen Shot 2022-01-24 at 11 21 52 AM" src="https://user-images.githubusercontent.com/1895432/150832787-4d03466c-50a2-4050-b364-a6fac1edae6e.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
yes
# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: 
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
# Acceptance Criteria
Documentation here: #2643

I think this is related to #4399; similarly, can we reduce the line height or ??? idk what is causing this

**Comment by wilkus27** [comment]
@lwtchu for line heights we are using special functions that were created by Helene a few years ago. As I remember she created them for some printing purposes and to keep spacing consistent. They take only a few values and are connected to font size. The base (smallest) value is `1.5rem` and this is what is used now in figure caption. 

I tried to hard coded a specific value, not use a function. This is how it looks with `1rem` line height:

![image](https://user-images.githubusercontent.com/40228854/151964491-9e3a65ad-45f8-4c4b-bd71-97d680cd2731.png)

Do you want me to use this hard coded value, or we should stay with `line-height(1)`?

**Comment by lwtchu** [comment]
@wilkus27 yeah i think that will be good - it just looks a little odd with the wide spacing for the small fonts

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-02-02 10-23-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/815a57c6-8530-4487-88e7-de4978a4d258)
