### ISSUE TITLE
Astronomy math aligned left instead of center

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4398]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know
new on the left
<img width="1658" alt="Screen Shot 2022-01-24 at 9 00 22 AM" src="https://user-images.githubusercontent.com/1895432/150833388-8988f368-7668-4b43-ab05-faf78b69190b.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
seems to be everywhere, including inside features

# Sample mark up if applicable
<equation id="fs-id1164754917641" class="unnumbered"><label/><m:math><m:mrow><m:msup><m:mi>D</m:mi><m:mn>3</m:mn></m:msup><m:mo>=</m:mo><m:mo stretchy="false">(</m:mo><m:msub><m:mi>M</m:mi><m:mn>1</m:mn></m:msub><m:mo>+</m:mo><m:msub><m:mi>M</m:mi><m:mn>2</m:mn></m:msub><m:mo stretchy="false">)</m:mo><m:msup><m:mi>P</m:mi><m:mn>2</m:mn></m:msup></m:mrow></m:math></equation>
# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: https://github.com/openstax/osbooks-astronomy
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-01-31 14-35-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8d4331e3-aef0-4de4-bb9c-6527d6b5a950)
