### ISSUE TITLE
Astronomy footnotes now double spacing

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4399]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know
new github pdf on the left
<img width="1567" alt="Screen Shot 2022-01-24 at 11 49 13 AM" src="https://user-images.githubusercontent.com/1895432/150838496-8f087ff3-c519-4569-9bb1-4500dcb7f136.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
yep, everywhere
# Sample mark up if applicable
regular `<footnote>` tags
# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: 
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
# Acceptance Criteria
Documentation here: #2773

What is the line height? And should we reduce it?

**Comment by wilkus27** [comment]
@lwtchu Please read my comment from https://github.com/openstax/cnx-recipes/issues/4397#issuecomment-1026766951. I did the same for footnotes (hard coded value `1rem`). This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/151974857-1aeed9df-6203-4acd-bf2c-497d722197e4.png)

Please, let me know if we should apply it :wink:

**Comment by lwtchu** [comment]
@wilkus27 commented on the other issue but go ahead with the change please

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-02-02 10-45-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/06e68e23-74b9-4ef3-bf84-ecc8bc4b20d2)![Screenshot from 2022-02-02 10-45-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5682cc67-5df9-4597-8d74-393ba90bc1bd)![Screenshot from 2022-02-02 10-55-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bffa014a-c147-4bac-bd64-20a2f23455e0)
