### ISSUE TITLE
Astronomy Appendix header bumps full-page table off page

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4400]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know
<img width="762" alt="Screen Shot 2022-01-24 at 12 48 00 PM" src="https://user-images.githubusercontent.com/1895432/150845169-3c8da2f7-11a7-481e-835b-43869015fff0.png">
<img width="750" alt="Screen Shot 2022-01-24 at 12 48 07 PM" src="https://user-images.githubusercontent.com/1895432/150845179-d767a13c-d88c-4e48-bcc3-32c53b21af36.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
this seems to be the only one
# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: 
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by wilkus27** [comment]
Checked with the newest content and styles. It's already fixed:

![image](https://user-images.githubusercontent.com/40228854/151978131-091a8306-4dec-4b60-b3dc-18810044cf20.png)
