### ISSUE TITLE
marketing - splash image

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4406]
Documentation: #2642
Blue version

**Comment by wilkus27** [comment]
This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/153443149-f1f646d9-8769-4929-a533-358f08ff00f3.png)

**Comment by Stackblocks** [comment]
![2022-02-24_16-22-49.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/da4e70db-cc10-4435-9117-681714c4ccf4)
