### ISSUE TITLE
marketing - section number treatment

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4411]
Documentation #2710 (blue version)

**Comment by wilkus27** [comment]
This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/153483732-631b45e6-d1f3-4e3b-a3f9-6c5d7518b20d.png)

**Comment by Stackblocks** [comment]
![2022-02-24_16-25-33.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/52c668db-7853-4566-9eea-2a369181aa56)
