### ISSUE TITLE
Spanish Introductory Statisctics: Styled list overlaps Solution title in Example 2.32

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4414]
![image](https://user-images.githubusercontent.com/55203598/151379172-5de55710-c012-4fee-86dd-4770e5f6c7cd.png)
![image](https://user-images.githubusercontent.com/55203598/151379246-1d266790-4e2c-45a9-868b-c666e8354d61.png)

**Comment by ajluk** [comment]
@lwtchu I opened this issue based on the things I have found during running Prince tests. I checked the styles and couldn't found a reason why the list looks like this. It is styled (have the left margin set to 27px). I also checked how it looked under Prince 12 and nothing has changed. I don't have an idea how can it be fixed. Can it stay this way?

**Comment by lwtchu** [comment]
hm i think so it's just not ideal. i don't think a feature is meant to be nested into a list...i'll close though
