### ISSUE TITLE
OPS-0013 Political Science Bullet List Not Supported in Web Preview - Preface Section

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4415]
Bullet list not supported at preface section in Web Preview, but it's supported in PDF view. Please check & resolve.

![PC_Preface](https://user-images.githubusercontent.com/86622862/151558339-b9c34344-33d5-48a8-bbdc-cb9f919aa693.png)

# Bug Location(s)
collection ID: col00000
github openstax/osbooks- link: https://plum-narwhal-acs1o54u.ws-us29.gitpod.io/
chapter/section: Preface
surrounding text: The Changing Political Landscape highlights and illustrates how

**Comment by lwtchu** [comment]
Related to https://github.com/openstax/cnx-recipes/issues/4202

**Comment by lwtchu** [comment]
there was a fix that went out a while back and it hits all prefaces. closing. will need to wait for these titles to adopt baked styles for web
