### ISSUE TITLE
marketing - tables 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4418]
There will be two types 

- "Text Tables" - which are the default
- Data Tables - are more condensed like the Finance ones

Documentation: #2741 
Text tables (no class) - type 1
Data tables (`class="data-table"`) - type 4

**Comment by wilkus27** [comment]
This is how it looks:

**No class table**

![image](https://user-images.githubusercontent.com/40228854/153574646-adc31c26-d6c6-4f1a-80c6-db3b66b74fb0.png)

**Data table**

![image](https://user-images.githubusercontent.com/40228854/153574724-13116ab9-7567-44c0-800e-c5dfb1de7a9a.png)
