### ISSUE TITLE
marketing - footnotes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4420]
Subsequently, due to the Endnotes, the footnotes need to have roman numeral numbering.

Like #2747

**Comment by wilkus27** [comment]
This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/154026970-2ca04cda-2a0f-4765-86e5-bb3ed8411de9.png)

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6c62da0c-6425-4674-95b2-095cb1fe6e37)
