### ISSUE TITLE
marketing - knowledge check

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4421]
`class="knowledge-check"`
- Section at the end of the module
- Same styling as a normal section; and exercises
- Has embedded exercises
- Answers to go the Answer Key (make sure this is labeled in the answer key)

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/153600170-c7121bf7-edfc-4751-8fae-eaa9c0c88e8a.png)

Is it ok? Should I add a title for this section before exercises, like **Knowledge Check** or something like that?

**Comment by wilkus27** [comment]
And here is Answer Key:

![image](https://user-images.githubusercontent.com/40228854/154059402-a815cae7-b0b2-4f4d-b935-3974a4a99f6c.png)

**Comment by lwtchu** [comment]
@wilkus27 i think this looks good for now - if they don't like it, we can adjust in the second round.

**Comment by Stackblocks** [comment]
@wilkus27 Looks good style-wise but are all of the necessary answers appearing in the answer key? It looks like there are four questions in the `knowledge-check` in the section, but two answers in the key.

![2022-02-23_16-12-39.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/182e9ef9-de47-44d3-ad1f-0a1ce9d6679e)![2022-02-23_16-08-59.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8adac393-3b77-4069-96b0-72b406aa88eb)

**Comment by wilkus27** [comment]
@Stackblocks @lwtchu I checked and it's a content problem. The data correctness is not defined in these solutions:

![image](https://user-images.githubusercontent.com/40228854/155500125-82216759-4b35-42a9-b9ba-04e586352d5e.png)
