### ISSUE TITLE
Contemporary Math: Your Turn, Exercises, Chapter Review and Chapter Test solutions are not populated in Answer Key

### ISSUE THREAD

**Issue by mps-openstax** [openstax/cnx-recipes#4427]
# Brief Description of Change and Screenshots

In Chapter 2: Statistics, Your Turns, Exercises, Chapter Reviews and Chapter Tests solutions are not populated in PDFs.

# Acceptance Criteria

# Content Location(s)
collection ID: osbooks-contemporary-math/contemporary-math
github openstax/osbooks-link: https://openstax-osbookscontempo-4csu9rejapa.ws-us29.gitpod.io/
chapter/section: Statistics/All modules
surrounding text: 
**Your Turn from Input**
![image](https://user-images.githubusercontent.com/88098452/151927183-c7280540-e266-414f-a844-84c53107bc98.png)

**Shapshot from PDF(GitPod)**
![image](https://user-images.githubusercontent.com/88098452/151927379-a74dad74-088a-4eb9-9b06-a921f68db98b.png)

**XML Markup**
 ![image](https://user-images.githubusercontent.com/88098452/152014914-f6a4df5b-e78c-4fe5-8c35-56f80820fc3c.png)

**Exercises from Input**
![image](https://user-images.githubusercontent.com/88098452/151927978-6a7794ef-2ac5-405a-a592-3fc8eeae1a70.png)

**Snapshot from PDF(GitPod)**
![image](https://user-images.githubusercontent.com/88098452/151927911-3bb26b00-ee0d-47eb-964c-5e2775e453bf.png)

**XML Markup**
![image](https://user-images.githubusercontent.com/88098452/152015076-216d9979-a7e8-437e-a44c-8a42d10ef8f8.png)

**Chapter Review from Input**
![image](https://user-images.githubusercontent.com/88098452/151928198-62238479-e28d-47d1-b97e-e0a477ba4513.png)

**Snapshot from PDF(GitPod)**
![image](https://user-images.githubusercontent.com/88098452/151928384-c3713bca-5684-426a-9837-26704f7640cd.png)

**XML Markup**
![image](https://user-images.githubusercontent.com/88098452/152015252-812aa345-86d5-40f4-bda8-db599d1cc393.png)

**Chapter Test from Input**
![image](https://user-images.githubusercontent.com/88098452/151928528-c9c64fdc-4170-4f30-aa6e-5953ac52d1f3.png)

**Snapshot from PDF(GitPod)**
![image](https://user-images.githubusercontent.com/88098452/151928622-ed25d5bd-7e21-43b4-b7b6-de42ebceb3e8.png)

**XML Markup**
![image](https://user-images.githubusercontent.com/88098452/152015594-679e2936-2973-48c0-b34a-e491ac3146a8.png)

**Comment by openstaxalina** [comment]
Umesh notes that the solutions to Check Your Understanding *are* showing.

**Comment by lwtchu** [comment]
Might be related to #4434 #4442

**Comment by lwtchu** [comment]
@Stackblocks with k's changes on the other issues - can you see if you can spot these also

**Comment by KarinaMendez2** [comment]
In the pdf, this `chapter-test` section has no title and bad numbering: 
![image](https://user-images.githubusercontent.com/25258810/154522835-2c490a9c-eeaf-4df7-87e3-9d380cf51288.png)

![image](https://user-images.githubusercontent.com/25258810/154523058-db2c163e-246b-4b9e-bf5b-920376376d22.png)

the reason might be bad nesting in content (`chapter-test` inside `chapter-review`)
![image](https://user-images.githubusercontent.com/25258810/154522964-e3cd1022-76bf-43d0-afdd-d05653411308.png)

**Comment by Stackblocks** [comment]
@lwtchu I'm seeing the same thing as Karina, and like she says the Chapter 2 `chapter-test` is built differently than the (working) chapter 1 & 8 `chapter-test`s, so it looks like a content issue.

**Ch.2 (Broken)**
![2022-02-17_14-48-56](https://user-images.githubusercontent.com/12678235/154568868-aa30f49d-9dbc-4b08-bc5b-e79d63c1567f.png)

**Ch.1 (Working)**
![2022-02-17_14-50-08](https://user-images.githubusercontent.com/12678235/154568939-54ab9368-a274-4741-a05d-81a8469c188e.png)

**Ch.8 (Working)**
![2022-02-17_14-50-55](https://user-images.githubusercontent.com/12678235/154569019-8211e8e8-7f2d-41b5-a6be-e057fd8c9bcc.png)

**Comment by lwtchu** [comment]
Note: We shoudl still release outside of this content issue. I"ll tell the team when we're done with ch 8 review

**Comment by openstaxalina** [comment]
@lwtchu is this still waiting to be released?

**Comment by lwtchu** [comment]
Content looks fixed 
![Screen Shot 2022-10-11 at 2 48 46 PM](https://user-images.githubusercontent.com/11299125/195185108-84a872c3-d3c6-4e4c-9172-44dc651e02a8.png)
