### ISSUE TITLE
economics - numbered figure link isn't populating

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4430]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [x] recipe [ ] styles [ ] both [ ] i don't know

![Screen Shot 2022-02-01 at 10 33 59 AM](https://user-images.githubusercontent.com/11299125/152010003-93618bbf-c4bc-4518-8bae-e10bbc20d4a3.png)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
No - this link won't pull in the figure number. Is it needing something else?

# Sample mark up if applicable

# Acceptance Criteria
Not sure why the number isn't being pulled ?  Ideally it should say Figure 1.2 since it links to that image above it - it's only happening in Economics - any idea why?

# Bug Location(s)
collection ID: principles-economics-2e
github openstax/osbooks- link: https://github.com/openstax/osbooks-principles-economics-bundle
chapter/section: 1.1 
surrounding text: world, there are people who are hungry, homeless (for example, those who call park benches their beds, as [link]

**Comment by Malar-Natarajan** [comment]
These 1es have this [link] issue in specific pages (probably where content was updated). But the same location in 2es did not have any issue
https://staging.openstax.org/books/college-algebra/pages/7-7-solving-systems-with-inverses#Equation_09_07_01
https://staging.openstax.org/books/college-algebra/pages/3-1-functions-and-function-notation#Table_01_01_12
https://staging.openstax.org/books/algebra-and-trigonometry/pages/11-7-solving-systems-with-inverses#Equation_09_07_01

**Comment by Malar-Natarajan** [comment]
@lwtchu Filip (Katalyst QA) found few more books with this issue. I am adding those here:

https://staging.openstax.org/books/elementary-algebra-2e/pages/10-3-solve-quadratic-equations-using-the-quadratic-formula
https://staging.openstax.org/books/elementary-algebra-2e/pages/1-2-use-the-language-of-algebra
https://staging.openstax.org/books/introductory-statistics/pages/8-2-a-single-population-mean-using-the-student-t-distribution
https://staging.openstax.org/books/algebra-and-trigonometry/pages/11-7-solving-systems-with-inverses#Equation_09_07_01
https://staging.openstax.org/books/college-algebra/pages/7-7-solving-systems-with-inverses#Equation_09_07_01
https://staging.openstax.org/books/college-algebra/pages/3-1-functions-and-function-notation#Table_01_01_12
https://staging.openstax.org/books/college-algebra/pages/6-key-concepts
https://staging.openstax.org/books/anatomy-and-physiology/pages/2-1-elements-and-atoms-the-building-blocks-of-matter#fig-ch02_01_01
https://staging.openstax.org/books/anatomy-and-physiology/pages/preface MOST OF LINKS

**Comment by lwtchu** [comment]
Let's ignore the cases where it links to an unnumbered item and fix this case in Econ/Antomy.

**Comment by ajluk** [comment]
@lwtchu There is one more separate case in Introductory Statistics (Sorry I have missed it earlier and just checked), where the link is pointing to Appendix H Tables page id: 
![image](https://user-images.githubusercontent.com/55203598/153455778-8111a315-2d93-4eae-8afb-26986188cdf9.png)
There are few such cases in the book regarding the same appendix page/id.
![image](https://user-images.githubusercontent.com/55203598/153456282-1feb5b86-dd3a-4cb8-bae8-a4e3cb32865e.png)
Should it be fixed in recipes or it is also content issue?

**Comment by lwtchu** [comment]
@ajluk do you remember if in oer.exports there was a case where the link would generate anchor text for appendix pages

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

## Econ
![2022-02-15_14-52-16.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/58962627-faeb-4b49-bd60-56ce13ec7939)

![2022-02-15_14-53-29.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/48bb7762-ed46-49cb-96b3-42f1bddba1e8)

## Anatomy
![2022-02-15_15-33-13.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/13d6d4cb-28f4-4aaf-b7d5-dc83b8935743)

![2022-02-15_15-33-49.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/aba914dd-584c-4517-99fb-5609810ebe0a)

**Comment by MartaSztuka** [comment]
#### PASSED
##### Principle of Economics
![Screenshot from 2022-02-16 09-53-44](https://user-images.githubusercontent.com/47241114/154229500-2579708d-4441-4f51-acc7-7dbd252ba21d.png)
##### Anatomy
![Screenshot from 2022-02-16 10-29-51](https://user-images.githubusercontent.com/47241114/154235500-4a78ad99-7ea8-4efc-986f-bcbac24a9729.png)
