### ISSUE TITLE
marketing - word document icon feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4431]
- Documentation #3680
- Icon: https://drive.google.com/file/d/1MbcXgUKhuIG4uZc7wESlyI9ObnFUhflr/view?usp=sharing
- Class: `<note class="word-document">`

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/153891008-64884aed-154d-414f-a913-f1aa1454a495.png)

Is it ok? It looks quite big in comparison to EOC sections icons :eyes:

**Comment by lwtchu** [comment]
@wilkus27 hm it's exported to be the same size as the finance excel spreadsheet #3681 icon 🤔  Is it because the first example is only one line?

**Comment by wilkus27** [comment]
@lwtchu Icon is the same size everywhere. We just using smaller icons for EOC section title. That's why it looks weird in this particular place. My only concern was, is it intentional that this note is in EOC section? Usually they contain just paragraphs or exercises.

**Comment by lwtchu** [comment]
@wilkus27 this isn't a note in the EOC section - it's just a static little side bar for finance and marketing. you'll see in the finance content it's everywhere and that is on purpose.

**Comment by Stackblocks** [comment]
Seeing the same thing as Natalia, so as long as the icon's size is what it is supposed to be it's good to go. (It can also be adjusted later since the element is built out)

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/df27c785-4e6b-4355-b53b-c11165ce7661)

**Comment by lwtchu** [comment]
i think this is fine since it's in line with finance 🤔
