### ISSUE TITLE
A tiny dash follows footnote links in some book pages

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/cnx-recipes#4432]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know

<img width="1484" alt="Screen Shot 2022-02-01 at 2 04 34 PM" src="https://user-images.githubusercontent.com/40276461/152044228-010ecb32-8dcc-40b0-b523-9fcbf0d89416.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
Happens in all footnote links of some books like Org behavior, principles-management

# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: https://rex-web.herokuapp.com/books/organizational-behavior/pages/1-2-the-changing-workplace
chapter/section: 1.2
surrounding text: entrepreneurship—those strengths are increasingly threatened by weaknesses in areas such as the tax code, basic education, macroeconomic policies, and regulation.”3 Companies face a variety of changes and challenges

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by ajluk** [comment]
@lwtchu I looked into this issue, because it seems familiar I have fixed this problem already within working on the link separator [issue](https://github.com/openstax/cnx-recipes/issues/3986): 
![image](https://user-images.githubusercontent.com/55203598/153156293-ec869fd4-1214-4a1e-af9e-e456ebd471ce.png)

**Comment by LostMojo** [comment]
This looks like a problem with the rex content-- it looks like there's whitespace between the citation number and the end of the underlined link. 

![Screen Shot 2022-03-02 at 4.49.55 PM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/0896cb79-fb42-4500-95a9-373b862512ed)

This whitespace doesn't appear in the most recent enki builds though.

![Screen Shot 2022-03-02 at 4.54.12 PM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/5612b444-866e-4585-a9d6-d1c8793d4c74)

So... problem solved, I guess?
