### ISSUE TITLE
marketing - marketing dashboard

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4433]
![Screen Shot 2022-02-02 at 5 31 32 PM](https://user-images.githubusercontent.com/11299125/152255292-a0f3d582-26a0-4fe5-bd86-1a0a0c10ec71.png)

- Documentation #2737
- color option 1
- Class: `<note class="marketing-dashboard">`
- icon: [cardboard-marketingdashboard.svg](https://drive.google.com/file/d/1oAoHVtFaL0V2lhVNdFRYJ4rQ5k9FoiAd/view?usp=sharing)
- title: Marketing Dashboard

**Comment by wilkus27** [comment]
@lwtchu About exercises within this note (https://github.com/openstax/cnx-recipes/issues/4401#issuecomment-1029232005) this is how it looks. In recipes I'm adding labels **Exercise #number** for problem and **Solution** for solution. In styles I'm just adding bold. Is it ok? Should I change anything in recipe/style?

![image](https://user-images.githubusercontent.com/40228854/153845655-166a3e4b-93bf-43c5-b5ae-251072c67362.png)

**Comment by wilkus27** [comment]
This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/154480003-5a36c0f7-850d-4a09-85e3-cea5ead72ba8.png)

**Comment by Stackblocks** [comment]
![2022-02-23_16-16-53.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/9111e544-865d-421b-adde-57fa5049b1ff)
