### ISSUE TITLE
Contemporary Math: Check Your Understanding - supporting embedded exercises and multipart questions

### ISSUE THREAD

**Issue by mps-openstax** [openstax/cnx-recipes#4434]
# Brief Description of Change and Screenshots
In Check Your Understanding section Question numbers are not populated and answers are not populated at the end of the book in the "Answer Key" section where all other answers are appearing.

# Acceptance Criteria

# Content Location(s)
collection ID: osbooks-contemporary-math/contemporary-math
github openstax/osbooks- link: https://openstax-osbookscontempo-bh0adrdlh5a.ws-us30.gitpod.io/
chapter/section: Statistics/Check Your Understanding
surrounding text: 
**Snapshot from Manuscript**
![image](https://user-images.githubusercontent.com/88098452/152129434-5e70404d-592b-4e0b-b9c6-4ea12b6d1dca.png)

**Snapshot from PDF**
![image](https://user-images.githubusercontent.com/88098452/152130093-c5052fef-90f2-41da-9fab-a456f376ddd1.png)

**Snapshot from XML Mark-ups**
![image](https://user-images.githubusercontent.com/88098452/152130540-a3ee2458-a733-4445-aca4-c06ef82a2551.png)

**Comment by lwtchu** [comment]
# Acceptance Criteria 
Can we make sure the assessments that get pulled in get the correct numbering schema and the answer goes to the answer key?

**Comment by KarinaMendez2** [comment]
section was missing the class name 

> check-understanding

**Comment by lwtchu** [comment]
Added class name to the tagging legend
