### ISSUE TITLE
OPS - Philosophy Upper-alpha list indent issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4435]
We have coded as per the OPS guidelines. But we have received the below correction from customer. Kindly check and resolve this issue.

**Received corrections:** Production - indent A and B

**CNXML**:
 <list list-type="enumerated" id="list-00002">
      <item>Things that lack knowledge tend to act toward an end/goal.</item>
      <item>These things act toward an end either by chance or by design.
      <list list-type="enumerated" number-style="upper-alpha" id="list-00003">
      <item>It is obvious that it is not by chance.</item>
      <item>Things that lack knowledge act toward an end by design.</item>
      </list></item> 

**Output PDF:**
![Ch6](https://user-images.githubusercontent.com/86622862/152138374-414856a3-8f86-47f3-ab37-5479619f805a.png)

# Bug Location(s)
collection ID: col00005
github openstax/osbooks- link: https://coffee-grouse-ulafn81g.ws-us30.gitpod.io/
chapter/section: Chapter 6/Section 3
surrounding text: It is obvious that it is not by chance.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-02-17 10-58-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2c9a3e45-7f87-44e8-a008-15bf2e7c98ea)
