### ISSUE TITLE
marketing - marketing in practice

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4436]
- Documentation #2737
- color option 2
- Class: `<note class="marketing-practice">`
- title: Marketing in Practice
- icon - [cardboard-leadership.svg](https://drive.google.com/file/d/1WZm0hAvgzLkuqNjOqDYEQkIlgNDd8HtK/view?usp=sharing)

**Comment by wilkus27** [comment]
This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/153850528-8d7e7f94-97fe-4ea7-9dfb-cdfcdb81090f.png)

**Comment by lwtchu** [comment]
@wilkus27 sorry i thought i added this but can you include the icon for this feature. it's https://drive.google.com/file/d/1WZm0hAvgzLkuqNjOqDYEQkIlgNDd8HtK/view?usp=sharing

**Comment by wilkus27** [comment]
Here is note with icon:

![image](https://user-images.githubusercontent.com/40228854/154054309-2598b5dc-4cd2-440a-8a81-5f6116093c1b.png)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![2022-02-24_15-52-22.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d4666182-26cf-4b78-9c8a-f275612f4d6b)
