### ISSUE TITLE
marketing - companies with a conscience

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4437]
- Documentation #2737
- color option 2 
- icon [cardboard-road.svg](https://drive.google.com/file/d/1znnLBlJViwAmAMNM1D8rGynnTSsZnu5K/view?usp=sharing)
- Class: `<note class="companies-conscience"">`
- title: Companies with a Conscience

**Comment by wilkus27** [comment]
This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/153865150-2520acf9-693d-46cd-af46-27b4c355ce8e.png)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![2022-02-24_15-50-47.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d51d381f-1ff6-4ebd-8a72-e918b33a6364)
