### ISSUE TITLE
marketing - eoc sections and assessment 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4440]
![image](https://user-images.githubusercontent.com/11299125/111837252-9e421d80-88c5-11eb-97bd-a3fa07aa6a34.png)

- exercise number is bolded with period
- numbering RESETS after each section

IF there are no assessments, it should be a regular section with paragraphs and images.

### Applied Marketing Knowledge: Discussion Questions
- Title: Applied Marketing Knowledge: Discussion Questions
- `<section class="marketing-discussion">`
- icon: [cardboard-discussion.svg](https://drive.google.com/file/d/1lb8jseP8ES7W7wqmr4uH2gb2UNnCFJ-Z/view?usp=sharing)

### Critical Thinking Exercises
- Title: Critical Thinking Exercises
- `<section class="critical-thinking">`
- icon: [cardboard-assessments.svg](https://drive.google.com/file/d/1-IA4Gbm1OlPC2bg8lSedIUUIrjvZdBrB/view?usp=sharing)

### Building Your Personal Brand
- Title: Building Your Personal Brand
- `<section class="building-brand">`
- icon: [cardboard-brand.svg](https://drive.google.com/file/d/1Lr_ln4NfhkYran4_JNxrzDEWTYyz2rmY/view?usp=sharing)

### What Do Marketers Do?
- Title: What Do Marketers Do?
- `<section class="marketers-do">`
- icon: [cardboard-managegroup.svg](https://drive.google.com/file/d/169_IQ6DAi8qsAGZv152QHVtSerJIp1z_/view?usp=sharing)

### Marketing Plan Exercise
- Title: Marketing Plan Exercise
- `<section class="marketing-plan">`
- icon: [cardboard-net.svg](https://drive.google.com/file/d/16q5cnsweMPzvGmSabpQNXtfofsC9etvA/view?usp=sharing)

### Closing Company Case
- Title: Closing Company Case
- `<section class="company-case">`
- icon: [cardboard-casestudy.svg](https://drive.google.com/file/d/1tZDE2I5JPF6Ggo676xs79VSs4izviUKQ/view?usp=sharing)

**Comment by wilkus27** [comment]
This is how it looks:

**Marketing Discussion**

![image](https://user-images.githubusercontent.com/40228854/153600608-c6b519cd-31f2-46e8-826c-7f78787b9031.png)

**Critical Thinking**

![image](https://user-images.githubusercontent.com/40228854/153600722-663d2280-c7a4-42dc-b87d-caf37c3ef208.png)

**Building Brand**

![image](https://user-images.githubusercontent.com/40228854/153600827-b64570c1-e33f-4245-9102-b93018bd9e29.png)

**Marketers Do**

![image](https://user-images.githubusercontent.com/40228854/153600944-45ca250e-d165-4be4-99bc-8fbc27f1a282.png)

**Marketing Plan**

![image](https://user-images.githubusercontent.com/40228854/153601035-5fefe6fa-e4d0-4e1e-9d9b-dded64ad1005.png)

**Company Case**

![image](https://user-images.githubusercontent.com/40228854/153601152-a845f2e1-f739-404d-a1a4-a6ea5763be73.png)

![image](https://user-images.githubusercontent.com/40228854/153601325-aa147c34-96c4-4691-ba5d-b935a0c3ed25.png)

Arrows point to solutions. @lwtchu as you mentioned here https://github.com/openstax/cnx-recipes/issues/4401#issuecomment-1029232005 they should be removed from the content, that's right?

**Comment by lwtchu** [comment]
@wilkus27 turns out these are just hard coded into the content - I put two linked embedded assessments at the end of the section for testing

**Comment by wilkus27** [comment]
This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/154480178-87a10c79-2bfd-4c23-86ba-c2e565552f48.png)
