### ISSUE TITLE
Contemporary Math: Your Turn question numbers are not appearing - support multipart questions in Your Turn

### ISSUE THREAD

**Issue by mps-openstax** [openstax/cnx-recipes#4442]
# Brief Description of Scenario and Screenshots
In [Your Turn]s, question numbers are not populated neither in PDF nor in Web view.

collection ID: osbooks-contemporary-math/contemporary-math
github openstax/osbooks- link: https://openstax-osbookscontempo-6vbyzvu7392.ws-us30.gitpod.io/
chapter/section: Statistics/Your Turn

**Snapshot from Input**
![image](https://user-images.githubusercontent.com/88098452/152298966-1982e15b-30f4-4c6b-b621-3a59b7d90b03.png)

**Snapshot from Web View**
![image](https://user-images.githubusercontent.com/88098452/152299163-c4f8558e-96fe-4b12-ab83-21b2e01d91c2.png)

**Snapshot from XML mark-up**
![image](https://user-images.githubusercontent.com/88098452/152299515-44f70559-9c5b-4a75-8ae3-2c2579855a76.png)

**Comment by lwtchu** [comment]
# Acceptance Criteria
We need to support MPQs in the Your Turn feature - if you are working on this card, please come talk to me so we can discuss how to move the code parts from the exercise and place and number in the feature box

**Comment by lwtchu** [comment]
![image](https://user-images.githubusercontent.com/11299125/154351505-8a94d4c3-86c5-412a-b166-822eb408cc4d.png)

New acceptance criteria: please remove the your turn numbering since it'll be redundant with the MPQ and questions pulled in. And set to the specs here: https://github.com/openstax/cnx-recipes/issues/2200

**Comment by Stackblocks** [comment]
@KarinaMendez2 Some`Your Turn` problems are missing the gap between the title and body boxes. Is this a markup difference in the content or maybe a targeting issue, do you think? 

All (or most) of the `Your Turn`s in 8.1 are missing the gap, and in 8.2 and 8.3 there are a mixture.

**Gapless**
![2022-02-17_13-48-13](https://user-images.githubusercontent.com/12678235/154559461-eae48f6f-e5d0-4bb5-999d-372efaaefcd3.png)

**With Gap**
![2022-02-17_13-18-46](https://user-images.githubusercontent.com/12678235/154559984-83e167e8-1554-4abe-9916-811c46d76fec.png)

**Comment by KarinaMendez2** [comment]
🤔 I will look into it 🧐

**Comment by Stackblocks** [comment]
Karina looked into it and couldn't replicate it, so when I double checked my stuff I found out it was an Adobe Acrobat rendering issue where at certain zoom levels and on certain places on the page it just decided not to show the space. Moving this over to CORGI testing and if it keeps coming up somehow we can look into it again.

![2022-02-17_15-24-15](https://user-images.githubusercontent.com/12678235/154573729-0a55ec3a-1d67-4a32-b37d-0e0630552d84.png)
