### ISSUE TITLE
OPS-0013 Political Science: Chapter titles missing in Reference section in Web Preview

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4443]
Hi Team,
Chapter titles missing in "References" section in Web Preview. But the titles are visible in PDF view. Please see the attached screenshots for your reference.

![Chapter8_Web Preview](https://user-images.githubusercontent.com/86622862/152302286-eb108cae-6414-416f-bfaa-c8cf10e1f52d.png)
![Chapter8_PDF_View](https://user-images.githubusercontent.com/86622862/152302291-ec15166f-593b-4fc3-a09b-1cda329e9636.png)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?

# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID: col00000
github openstax/osbooks- link: https://plum-narwhal-acs1o54u.ws-us30.gitpod.io/
chapter/section: References
surrounding text: How COVID-19 Has Changed Public Policy

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
Already has an existing issue: https://github.com/openstax/cnx-recipes/issues/4374 

Closing this one as a duplicate.
