### ISSUE TITLE
statistics - display="inline" not currently supported

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4444]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know

The attribute `display="inline"` does not seem to have the desired effect of placing images inline with the surrounding text, resulting in a new line for each image. 

<img width="1038" alt="Screen Shot 2022-02-03 at 9 48 30 AM" src="https://user-images.githubusercontent.com/5865292/152377422-a106c6a2-49df-40e3-9996-b045b9cddcb0.png">

# Does this happen for every instance? If no, is there a discernible pattern of occurrences?
All instances

# Sample mark up if applicable

```<media id="fs-id14772600" display="inline" alt="2.ª tecla">
    <image mime-type="image/png" src="../../media/ti83-2nd.png"/>
```

# Acceptance Criteria
images are able to be tagged with inline and place inline with the surrounding text.

# Bug Location(s)
A great example of this is Appendix G in Introductory Statistics

https://openstax.org/books/introductory-statistics/pages/g-notes-for-the-ti-83-83-84-84-calculators

collection ID: col11562
github openstax/osbooks- link: https://github.com/openstax/osbooks-introductory-statistics-bundle
chapter/section: Appendix G
surrounding text: `represents yellow command or green letter behind a key`

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
@yblock can you do me a favor and see if it works in the pdf also

**Comment by jbwilson8** [comment]
@lwtchu there is a problem with enki. It's failing on on a missing resource: 
../resources/f34c312dd426439d447cee336510e1834cd27f46

It's failing for MaryJo as well.

**Comment by lwtchu** [comment]
@jbwilson8 please use `larissa-test` branch for now. I'll look into the content issue tomorrow.

**Comment by wilkus27** [comment]
It's already fixed:

**Styles from REX**

![image](https://user-images.githubusercontent.com/40228854/222070307-eef21e9e-7f34-4d5c-9207-4326cbdc2e19.png)

**Styles from ce-styles**

![image](https://user-images.githubusercontent.com/40228854/222070427-8d46d865-72b7-46ff-a226-eea2b348c33b.png)

**Comment by lwtchu** [comment]
@yblock sorry for being super late w this but once we move to baked styles for web, it'll be fixed :eyes:
