### ISSUE TITLE
OPS-0012 Finance - Paragraphs overlapping issue[Urgent]

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4447]
We have received the below global issue in most of Finance chapters in PDF version. The lines in some of the paragraphs are overlapping. This is happening in paragraphs with footnote tags. Kindly check and resolve this issue.

![1](https://user-images.githubusercontent.com/86622862/152479009-d53d0471-0876-4776-bfc5-0f147bb8400f.jpg)
![2](https://user-images.githubusercontent.com/86622862/152479024-d1df3026-3b02-40b9-9a11-6a654e57263d.jpg)
![3](https://user-images.githubusercontent.com/86622862/152479062-3cf0f582-24b7-4e65-8aba-783716326355.jpg)

# Bug Location(s)
collection ID: col00006
github openstax/osbooks- link: https://black-spoonbill-qjwe2jp5.ws-us30.gitpod.io/
chapter/section: All chapters (Global issue)
surrounding text: However, by November 28, 2001, credit rating agencies had reduced Enron’s bond

**Comment by lwtchu** [comment]
This is possibly related to #4396. Important to fix this book first.
