### ISSUE TITLE
Add styles for pl-economics

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4448]

**Comment by MartaSztuka** [comment]
@ajluk There are two issues here; 
1. In Key terms list indentation
2. Index is missing content for names and foreign
###### Contents
![Screenshot from 2022-02-07 12-05-24](https://user-images.githubusercontent.com/47241114/152776872-75b6f073-e4fb-4317-a9f7-84b3a254d731.png)
###### Preface
![Screenshot from 2022-02-07 12-07-52](https://user-images.githubusercontent.com/47241114/152777043-3005e49b-5e6c-46fb-809e-f7189f26791d.png)
###### Chapter outline
![Screenshot from 2022-02-07 12-08-46](https://user-images.githubusercontent.com/47241114/152777146-d8bc39b3-9145-4e71-9fac-a90de41c337f.png)
###### Figure
![Screenshot from 2022-02-07 12-10-10](https://user-images.githubusercontent.com/47241114/152777338-8b6fda6a-f367-41a4-822f-f36b4268ce20.png)
###### Table
![Screenshot from 2022-02-07 12-09-36](https://user-images.githubusercontent.com/47241114/152777256-2c648e7b-0ef6-49fc-854a-f30279f2db0b.png)
###### Krok po kroku
![Screenshot from 2022-02-07 12-11-21](https://user-images.githubusercontent.com/47241114/152777492-d75bab6d-868a-4473-ae5d-cccc3bc5a962.png)
###### Poznaj szczegóły
![Screenshot from 2022-02-07 12-11-53](https://user-images.githubusercontent.com/47241114/152777578-f0ab659b-8d5c-421d-b562-86db789c4c53.png)
###### Do przemyślenia
![Screenshot from 2022-02-07 12-12-50](https://user-images.githubusercontent.com/47241114/152777675-997bd9b7-919d-4b4c-b5ee-bf7a52e6889e.png)
###### Sięgnij po więcej
![Screenshot from 2022-02-07 12-14-02](https://user-images.githubusercontent.com/47241114/152777836-a51d1486-6a43-43c0-afaf-2843fc4c5a39.png)
###### Footnote
![Screenshot from 2022-02-07 12-26-21](https://user-images.githubusercontent.com/47241114/152779649-752a3db6-6d45-4b73-ae29-5067b22c937c.png)
###### Key terms - there's unwanted indentation
![Screenshot from 2022-02-07 12-18-32](https://user-images.githubusercontent.com/47241114/152778451-9339202c-dd8d-431b-a2e1-648577a3b723.png)
###### Summary
![Screenshot from 2022-02-07 12-18-57](https://user-images.githubusercontent.com/47241114/152778560-1b412792-406c-44b9-891f-7aa9970cc2da.png)
###### Exercises
![Screenshot from 2022-02-07 12-19-33](https://user-images.githubusercontent.com/47241114/152778632-2f9b761d-3888-4f82-a2f3-b529aba11231.png)
![Screenshot from 2022-02-07 12-20-03](https://user-images.githubusercontent.com/47241114/152778697-04260da7-0b77-485b-9f8d-0548387a858e.png)
###### Answer Key
![Screenshot from 2022-02-07 12-21-48](https://user-images.githubusercontent.com/47241114/152778989-841df33b-b8fb-4e89-a67d-639ac3eea16c.png)
###### Bibliography
![Screenshot from 2022-02-07 12-22-55](https://user-images.githubusercontent.com/47241114/152779235-b215b0e0-d5fa-4663-a5b4-dc8815a1207d.png)
###### Index
![Screenshot from 2022-02-07 12-25-44](https://user-images.githubusercontent.com/47241114/152779524-8c849b2f-19ac-4bf1-ad23-c58ba23e17f7.png)
![Screenshot from 2022-02-07 12-25-32](https://user-images.githubusercontent.com/47241114/152779516-dcfbe7a1-a810-403a-8fec-49d8080686b1.png)

**Comment by ajluk** [comment]
@MartaSztuka The Key Terms issue will be fixed in cookbook. As we discussed via slack the Indexes need a content fix in terms.

**Comment by MartaSztuka** [comment]
We have decided to leave it opened for further style changes.

**Comment by ajluk** [comment]
Closing since [epic card ](https://github.com/openstax/cnx-recipes/issues/4550)has been created for styles changes for pl-economics.
