### ISSUE TITLE
Remove two-column preface of Chemistry

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4449]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know
Art too wide for two-column (if we ensmallen, it will be illegible)
<img width="1614" alt="two column preface makes art crash" src="https://user-images.githubusercontent.com/1895432/152625391-33bc8f09-9469-451e-b7a9-39ab278fb211.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?

# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: 
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: https://github.com/openstax/osbooks-chemistry-bundle/chemistry-2e
chapter/section: preface
surrounding text:

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/154059305-03e4ce62-57ea-418c-954c-e0184682a981.png)

**Comment by MartaSztuka** [comment]
#### PASSED
###### Chemistry 2e
![Screenshot from 2022-02-17 10-37-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3280a549-280e-4652-b4bd-31a8843eb35e)
###### Chemistry AF
![Screenshot from 2022-02-17 10-39-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6a13c854-ed7a-4e8f-b67d-a5e678e97957)
