### ISSUE TITLE
Chemistry figure crashes with body text

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4450]
# Brief Description of Scenario and Screenshots
<img width="1583" alt="crashing figure" src="https://user-images.githubusercontent.com/1895432/152625761-f5f26e6e-f374-4a38-b220-7b3c2e3fc3d0.png">

What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
Definitely not every time, but the pattern is not discernible to me from the markup
# Sample mark up if applicable
standard figure tag
# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: 
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link:  https://github.com/openstax/osbooks-chemistry-bundle
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
Footnote issue captured here: #4396
