### ISSUE TITLE
Chemistry figures ensmallened too far

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4451]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know
<img width="1588" alt="images ensmallened" src="https://user-images.githubusercontent.com/1895432/152626250-bd7b2866-4bfa-4834-8056-7dcaabb2bf3e.png">
<img width="1588" alt="image ensmallened in example" src="https://user-images.githubusercontent.com/1895432/152626316-f3229e7f-5d19-4358-8cf5-0eae5d973ab1.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
Not every time. Some images that ensmallen have the scaled-down class, some do not. Some are in body text, some are in features.

# Sample mark up if applicable
```
<media id="fs-idp29412624" class="scaled-down" alt="This figure uses the example of 1300 grams. The one and the 3 are significant figures as they are clearly the result of measurement. The 2 zeros could be significant if they were measured or they could be placeholders.">
<image mime-type="image/jpeg" src="../../media/CNX_Chem_01_05_SigDigits3_img.jpg"/>
</media>
```
```
<media id="fs-idm34238496" alt="A table is shown that is made up of six columns and five rows. The header row reads: “Element,” “Quantity,” a blank space, “Average atomic mass (a m u),” a blank space, and “Subtotal (a m u).” The first column contains the symbols “A l,” “S,” “O,” and a merged cell. The merged cell runs the length of the first five columns. The second column contains the numbers “2,” “3,” and “12” as well as the merged cell. The third column contains the multiplication symbol in each cell except for the last, merged cell. The fourth column contains the numbers “26.98,” “32.06,” and “16.00” as well as the merged cell. The fifth column contains the symbol “=” in each cell except for the last, merged cell. The sixth column contains the values “53.96,” “96.18,” “192.00,” and “342.14.” There is a thick black line under the number 192.00. The merged cell under the first five columns reads “Molecular mass.” To the right of this table is a ball-and-stick structure. It shows yellow and grey sphere connected to red spheres in a complex pattern. The yellow and grey spheres are similar in size, but the red spheres appear to be smaller by comparison.">
<image mime-type="image/jpeg" src="../../media/CNX_Chem_03_01_alsulfatemass_img-019d.jpg"/>
</media>
```
# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: 
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: https://github.com/openstax/osbooks-chemistry-bundle
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
I think this might be related to a very old PPI issue as seen in Am Gov #3989 and some other books. I still can't figure out if it's a figure related issue or not but can someone check the PPI settings on the book?

**Comment by ajluk** [comment]
@lwtchu The image resolution for this book (as for the others in carnival theme) is set by `prince-image-resolution: auto, 200dpi;` which means that Prince uses the resolution which is given by the image itself and if there is none given it falls to 200dpi. I remember we had some problem with images in Fizyka while ago where there was resolution also in metadata created by different graphic tools that were used on the images.

**Comment by lwtchu** [comment]
@ajluk was the solution for fizyka images to export again with specific resolution? something weird might be embedded in these older images

**Comment by lwtchu** [comment]
FIXED IN CONTENT. we should no longer have pictures for ants

**Comment by ajluk** [comment]
@lwtchu I'm sorry, but I have missed your previous comment :disappointed: . But I'm happy it has been solved. And yes some of our images needed to have changed the default resolution and other needed to metadata have been cleaned.

**Comment by lwtchu** [comment]
@ajluk yes for these instances, it appeared that they were actually resized to be half their height, so we were able to retrieve the old files.
