### ISSUE TITLE
Chemistry 2e figure captions added line spacing

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4453]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know
<img width="1507" alt="double spaced figure caption" src="https://user-images.githubusercontent.com/1895432/152625637-94f6d508-04e3-49bc-8b4f-b7daccc6de4e.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
yes, every time
# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: 
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: https://github.com/openstax/osbooks-chemistry-bundle
chapter/section: all
surrounding text:

**Comment by lwtchu** [comment]
similar issue to https://github.com/openstax/cnx-recipes/issues/4397 - let's make this change since there shouldn't be a larger emphasis on captions/footnotes

**Comment by ajluk** [comment]
lwtchu I tried decrease the line-height from 1.5rem to 1rem in caption and here is how it looks:
![image](https://user-images.githubusercontent.com/55203598/153898777-bb55df28-f2e6-4251-b664-d29fc1a51731.png
![image](https://user-images.githubusercontent.com/55203598/153899803-7392c42b-b1ea-4b9f-be2c-52b0981e1812.png)

I guess the font-size also need to be decreased a little but let me know. :slightly_smiling_face: (Not it is equal to 1rem-12px)

**Comment by lwtchu** [comment]
@ajluk i think this looks good thank u~

**Comment by ajluk** [comment]
@lwtchu Ok, but which option? 1 or 1.4rem? :slightly_smiling_face:

**Comment by lwtchu** [comment]
@ajluk sorry let's do 1.4. less crowded but not as aggressively large

**Comment by MartaSztuka** [comment]
#### PASSED
###### Chemistry 2e
![Screenshot from 2022-02-17 10-35-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1baa6743-cf87-453b-9b7b-11e90d4ea5d0)![Screenshot from 2022-02-17 10-34-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/85463b2d-5ca9-400d-ae2f-b35061b112a0)
