### ISSUE TITLE
Chemistry footnote line spacing increased

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4454]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know
<img width="1609" alt="footnote doublespacing" src="https://user-images.githubusercontent.com/1895432/152626617-a2a0f31d-36d9-4619-acab-d39401c70ca5.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
yes, every instance
# Sample mark up if applicable
regular footnote tag
# Acceptance Criteria

# Bug Location(s)
collection ID:
github openstax/osbooks- link: 
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: https://github.com/openstax/osbooks-chemistry-bundle
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
can we make a change similar to https://github.com/openstax/cnx-recipes/issues/4399

**Comment by ajluk** [comment]
@lwtchu Here is how the footnote text look like with line-height decreased from 1.5rem to 1 rem: 
![image](https://user-images.githubusercontent.com/55203598/154057743-b9b8e258-8ab7-4772-ab41-62d0df914177.png)

**Comment by lwtchu** [comment]
@ajluk this is fine

**Comment by MartaSztuka** [comment]
#### PASSED
###### Chemistry 2e
![Screenshot from 2022-02-17 10-41-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1a3d127e-330e-48c1-8212-428138ee3a27)
