### ISSUE TITLE
Revert to one column collation for EOC sections (Exercises and Key Equations in Chemistry

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4461]
# Brief Description of Change and Screenshots
What kind of change is this? [ ] recipe [ ] styles [x] i don't know
Please there is too much crashing math and images and tables. Also some images get ensmallened too hard to be legible

# Acceptance Criteria
Exercises and Key Equations sections are now 1 column instead of 2. 

# Content Location(s)
collection ID:
github openstax/osbooks- link: https://github.com/openstax/osbooks-chemistry-bundle
chapter/section: 
surrounding text:

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/154080770-2dfd851a-027d-4616-8687-fd31abb75245.png)
![image](https://user-images.githubusercontent.com/55203598/154080813-f5dfd1dd-052f-4a85-a508-39d49f0d6bb3.png)

**Comment by MartaSztuka** [comment]
#### PASSED
##### Chemistry 2e
![Screenshot from 2022-02-17 10-23-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/013263c3-6c7a-4326-ac5b-323b2fa97657)![Screenshot from 2022-02-17 10-23-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/74d74809-4bb1-4eda-96d4-1c5d2aca75cb)
##### Chemistry AF
![Screenshot from 2022-02-17 10-26-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0fe5b197-047d-4fee-b694-9a6414c41172)![Screenshot from 2022-02-17 10-25-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4a214aa2-41a7-449b-b5b8-665d5e508bd1)
