### ISSUE TITLE
statistics - missing translation

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4465]
![Screen Shot 2021-10-08 at 3 50 39 PM](https://user-images.githubusercontent.com/11299125/136623600-8e5df5c7-e54c-48fa-a256-6fc89a9b14fb.png)

i think this is in university physics so you can copy it over >>

**Comment by wilkus27** [comment]
Checked with the current code. It's already fixed:

![image](https://user-images.githubusercontent.com/40228854/164187011-cabdab4c-8f05-4486-b9dc-a27ce0499fc7.png)
