### ISSUE TITLE
Update folio strings

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4467]
Folio strings for Preface and the bottom text "Access for free at openstax.org" has support in Kitchen. This issue was created for testing purposes since I have updated the strings to be supported in Kitchen for all style themes. @MartaSztuka please test one book from each theme (cosmos, cardboard, corn, carnival). Please also check Psychologia instead of Mikroekonomia, because both of the books are using cosmos theme. Also Fizyka (one from the 3 volumes) should be checked.

**Comment by ajluk** [comment]
This issue also demands changes from Kitchen (for polish book). It will be tested after `cookbook` will be conntected with `enki` pipeline.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Psychologia
![Screenshot from 2022-02-16 11-49-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/554e28c4-dcf1-4f8e-9d49-9b0821ed6c9a)
##### Astronomy
![Screenshot from 2022-02-16 11-49-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3b5f6c66-6155-4b87-a9d8-80c977a29f85)
##### Fizyka 1
![Screenshot from 2022-02-16 11-50-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f5c7002c-8ab7-498e-a62a-728344b4a736)
##### Contemporary math
![Screenshot from 2022-02-16 11-51-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b42982cd-70d7-478d-8d1d-e02f62eca90b)
