### ISSUE TITLE
OPS-0012 Finance - Table border issue in morerows element

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4470]
We have received the below correction from customer. Kindly check and resolve this issue.

**In this chapter, there are still rules missing in Table 15.4.  We requested this be fixed at first pages and it still isn't showing in final pages. Do you know what the problem might be here?**

**CNXML Coding:**
![Table15 4_CNXML](https://user-images.githubusercontent.com/86622862/153127847-7a46d3d7-9786-4592-bd4f-dfc3fe9f77a5.png)

**Output PDF:**
![Table15 4](https://user-images.githubusercontent.com/86622862/153127485-9459050a-397b-4f25-8be0-46c9c991a93d.png)

# Bug Location(s)
collection ID: col00006
github openstax/osbooks- link: https://openstax-osbooksintroduc-6ykvohvt662.ws-us30.gitpod.io/
chapter/section: Chapter15/Section4
surrounding text: The arithmetic average return for CVS was 11.11%, and the geometric average return was 9.29%.

**Comment by oscryan** [comment]
Tried to force cell borders with colsep, didn't wor
<img width="1070" alt="Screen Shot 2022-02-09 at 12 46 44 PM" src="https://user-images.githubusercontent.com/1895432/153269025-ad3fe772-bcd4-4145-914a-b57a0b675c10.png">
k

**Comment by openstaxalina** [comment]
@srm-openstax we (OpenStax) will fix and confirm this during the final publication steps. Please proceed with your QA without this fix.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![2022-02-18_11-11-00.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/562dadf2-d7ee-494f-936e-d428d9d2ec61)
