### ISSUE TITLE
marketing - red text

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4471]
- targeted by `<emphasis class="colored-text">`
- apply the color: R1: `#CC0000`
- remove the bold that is default to `<emphasis>`

same functionality as: https://github.com/openstax/cnx-recipes/issues/2892

**Comment by wilkus27** [comment]
This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/153898740-369f13ff-90e9-4789-8c24-ef78d6b8b2ef.png)

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f94bcbc4-734f-433e-8d0a-f14f03648ca3)
