### ISSUE TITLE
marketing - equations

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4477]
- centered
- standard stix font
- SHOULD have unnumbered class on them so they are unnumbered

**Comment by wilkus27** [comment]
This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/154031756-aeb1f5b2-7a83-446f-a43d-caeac5825192.png)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/55d9d2d9-525f-45b0-80c3-5ea29b919607)
