### ISSUE TITLE
finance - fix excel spreadsheet note

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4480]
Currently Excel Spreadsheet note isn't baked properly. It doesn't have `os-note-body` part:

![image](https://user-images.githubusercontent.com/40228854/154078566-0363c080-6ebe-4575-8836-10e4f9c11a50.png)

**Comment by Stackblocks** [comment]
- [x] `os-note-body` now appearing with current code & content

![2022-02-18_13-12-14.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e0a2cd3b-51c4-4a25-bb65-374cb957a0be)
