### ISSUE TITLE
college physics - updates to learning objectives

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4485]
we will pull them out of the chapter outline and place them into the section where they belong

- content change will need to happen to put them into the `<section class="learning-objectives">` format

we will need to pull the style from AP Physics and put in the college physics

**Comment by Stackblocks** [comment]
Seems to be getting sorted / displaying correctly :+1:

![2022-03-09_16-39-41.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a2c1fc75-c99d-4639-873a-d4c67047c0f0)
