### ISSUE TITLE
college physics - authentic assessment

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4487]
- tagging will be `<section class="authentic-assessment">`
- exercises will exist - answers WILL NOT go to the answer key the embedded assessments will not have public answers

Need to get test content pls hold

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content


![2022-03-10_15-34-18.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/aeaf7faf-556c-4739-b8b7-6bf420f4147f)
