### ISSUE TITLE
cardboard - fix learnig objectives

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4488]
Fix Learning Objectives style to match specs from https://github.com/openstax/cnx-recipes/issues/2711.

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

- unnumbered LO

![image](https://user-images.githubusercontent.com/40228854/154285242-517821bd-0f88-4a85-91ba-5eb56ff3f577.png)

- numbered LO

![image](https://user-images.githubusercontent.com/40228854/154285445-47f3bb8d-4d9d-4bdf-82eb-4d37398c263c.png)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![2022-02-22_16-56-49.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0a3212e3-82d6-4cef-bc5b-037fd748ee9d)
