### ISSUE TITLE
college physics recipe - suppress AP Physics specific test prep for ap courses

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4496]
suppress the following part
- test prep for ap courses - `class="ap-test-prep"`

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![2022-03-09_16-56-25.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d263f6d7-f952-45a7-8611-03df02d29a85)
