### ISSUE TITLE
AP Physics - styles - two column test prep section

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4497]
please set the - test prep for ap courses - `class="ap-test-prep"`- into two columns

**Comment by MartaSztuka** [comment]
@KarinaMendez2 Test Prep is still in one column
![Screenshot from 2022-03-07 11-14-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fd83f888-61ff-4d3a-8ad7-14998a259bad)
![Screenshot from 2022-03-07 11-09-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/573da0a0-0f91-4247-aa26-161a92089662)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-03-07 14-47-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5842a5d7-468f-4628-b94b-f07bbcfb42c6)
