### ISSUE TITLE
Create part labels for figures within boxes instead of individual numbered figures

### ISSUE THREAD

**Issue by skiselica** [openstax/cnx-recipes#4498]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know

How do we create one numbered figure with parts within a boxed feature.

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?

# Sample mark up if applicable

# Acceptance Criteria
<img width="529" alt="Screen Shot 2022-02-17 at 4 06 07 PM" src="https://user-images.githubusercontent.com/99816778/154571140-9ff70ae9-24f6-4334-8aa9-1dd62e15dc9c.png">

# Bug Location(s)
collection ID:
github openstax/osbooks- link: 
chapter/section: 
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
Could you please merge them into one image with text labels (font and image specs should be the same as the other art). 

It can be done like this image:
![image](https://user-images.githubusercontent.com/11299125/155004774-322d2b44-1cfa-4215-a45a-0e0735f2dde4.png)
[Figure 1.4 in Sociology 3e](https://openstax.org/books/introduction-sociology-3e/pages/1-2-the-history-of-sociology )

Or like this: 

![Figure_01_02_17abcd](https://user-images.githubusercontent.com/11299125/155004373-3b91edde-aed9-42b2-9468-ef00387b4db0.png)
[Figure 1.18 in Biology 2e](https://openstax.org/books/biology-2e/pages/1-2-themes-and-concepts-of-biology)

Sample caption is available in the links above.
