### ISSUE TITLE
Add support for class="data-table"

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4501]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know

There are some wide tables in calculo that I have added class="data-table" to to make them fit in the PDF. Like we did for the Spanish Stats bundle, please add this class to be supported for the calculo bundle. 

Here is an example of a really long one that I'm hoping this class will fix. Searchable text to find the table in content `http://www.census.gov/prod/2013pubs/p60-245.pdf` 

<img width="394" alt="Screen Shot 2022-02-21 at 10 03 18 AM" src="https://user-images.githubusercontent.com/5865292/154991090-c4128b3e-c69c-4e66-b52b-5277966f1987.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?

# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
collection ID: m53481
github openstax/osbooks- link: [calculo github](https://github.com/openstax/osbooks-calculo-bundle)
chapter/section: 1.5
surrounding text:  Esta tabla tiene 3 filas y 10 columnas. La primera fila está marcada

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by kswanson33** [comment]
A little confused about a few things: 
- The surrounding text isn't coming up when I search in either of 3 volumes
- There is currently only 1 example of a table where the `data-table` class has been added, and it isn't the one in the screenshot
  - The table, Tabla 1.10, is already a `column-table`, and we currently don't allow a table to be 2 kinds of table at once. Do you want me to look into seeing if I can change that?
- I tried adding the class `data-table` to the table in the screenshot & adding the styles, but it didn't seem to do much :/ 
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/9da78f43-eeeb-457f-ad7d-efab17de407c)


To demonstrate that styles have been added to tabla 5.8:
![Screen Shot 2022-02-23 at 4.50.09 PM.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/e34e47b4-938a-425c-b579-a57943d1561f)

**Comment by lwtchu** [comment]
Added the class to that table and talked to Kendra. The table padding should be .16rem as opposed to 1. Which...doesn't look like it was applied here.

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/394840df-90c1-4a15-94b8-8d312803f772)

To Alan or Marta: This issue required a refactor of EOC tables across the corn theme, since there were some redundant styles that were overriding the DataTable styles in priority. Do you mind taking a quick look to make sure me removing those styles didn't cause problems?

**Comment by Stackblocks** [comment]
I'll review EOC tables across the corn theme at the start of next sprint :+1:

As for this table, i'm seeing the same thing as your screenshot above so I'm going to go ahead and move this card along.

![2022-03-10_17-24-44.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b1078624-972d-4db5-9872-6ab2ba41acb9)
