### ISSUE TITLE
list numbers crashing with text - support lists in glossary

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4503]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know

List numbers are crashing with text in Revisión Del Capítulo - Términos Clave section. 

<img width="562" alt="Screen Shot 2022-02-18 at 10 50 13 AM" src="https://user-images.githubusercontent.com/5865292/154726577-f498558d-9dc5-4139-9479-f6746307c12b.png">

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?

# Sample mark up if applicable
```
<glossary>
<definition id="fs-id1167793449052">
<term>punto crítico de una función de dos variables</term>
<meaning id="fs-id1167793449058">el punto <m:math><m:mrow><m:mrow><m:mo>(</m:mo><m:mrow><m:msub><m:mi>x</m:mi><m:mn>0</m:mn></m:msub><m:mo>,</m:mo><m:msub><m:mi>y</m:mi><m:mn>0</m:mn></m:msub></m:mrow><m:mo>).</m:mo></m:mrow></m:mrow></m:math> se llama punto crítico de <m:math><m:mrow><m:mi>f</m:mi><m:mrow><m:mo>(</m:mo><m:mrow><m:mi>x</m:mi><m:mo>,</m:mo><m:mi>y</m:mi></m:mrow><m:mo>).</m:mo></m:mrow></m:mrow></m:math> si se cumple una de las dos condiciones siguientes<newline/> <list id="fs-id1167793401290" list-type="enumerated" number-style="arabic">
<item><m:math><m:mrow><m:msub><m:mi>f</m:mi><m:mi>x</m:mi></m:msub><m:mrow><m:mo>(</m:mo><m:mrow><m:msub><m:mi>x</m:mi><m:mn>0</m:mn></m:msub><m:mo>,</m:mo><m:msub><m:mi>y</m:mi><m:mn>0</m:mn></m:msub></m:mrow><m:mo>).</m:mo></m:mrow><m:mo>=</m:mo><m:msub><m:mi>f</m:mi><m:mi>y</m:mi></m:msub><m:mrow><m:mo>(</m:mo><m:mrow><m:msub><m:mi>x</m:mi><m:mn>0</m:mn></m:msub><m:mo>,</m:mo><m:msub><m:mi>y</m:mi><m:mn>0</m:mn></m:msub></m:mrow><m:mo>).</m:mo></m:mrow><m:mo>=</m:mo><m:mn>0</m:mn></m:mrow></m:math></item>
<item>Al menos uno de <m:math><m:mrow><m:msub><m:mi>f</m:mi><m:mi>x</m:mi></m:msub><m:mrow><m:mo>(</m:mo><m:mrow><m:msub><m:mi>x</m:mi><m:mn>0</m:mn></m:msub><m:mo>,</m:mo><m:msub><m:mi>y</m:mi><m:mn>0</m:mn></m:msub></m:mrow><m:mo>).</m:mo></m:mrow></m:mrow></m:math> y <m:math><m:mrow><m:msub><m:mi>f</m:mi><m:mi>y</m:mi></m:msub><m:mrow><m:mo>(</m:mo><m:mrow><m:msub><m:mi>x</m:mi><m:mn>0</m:mn></m:msub><m:mo>,</m:mo><m:msub><m:mi>y</m:mi><m:mn>0</m:mn></m:msub></m:mrow><m:mo>).</m:mo></m:mrow></m:mrow></m:math> no existe</item>
```
# Acceptance Criteria

# Bug Location(s)
collection ID: col10030
github openstax/osbooks- link: [calculo github](https://github.com/openstax/osbooks-calculo-bundle)
chapter/section: terms
surrounding text: si se cumple una de las dos condiciones siguientes

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
Need to enable list styling inside of a Glossary - can we hit the rest of the books in the theme with this change?

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/e7870d8d-86c4-46dc-bec1-74db982f8a40)

unable to reproduce in enki ... was this already fixed?

**Comment by yblock** [comment]
hmm yes it does appear to be fixed in the most recently generated content. Cool!
