### ISSUE TITLE
marketing - link to learning

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4504]
- Documentation #2737
- color option 1
- Class: `<note class="link-to-learning">`
- title: Link to Learning
- SUPPORT subtitles https://github.com/openstax/cnx-recipes/issues/4095

**Comment by wilkus27** [comment]
This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/155096042-8ce909c1-308d-4d70-8d42-36f9888f5ac5.png)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3e7ab921-e7be-4248-baf3-bf6418b69a4d)
