### ISSUE TITLE
contemporary math - exercise alignment

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4505]
![Screen Shot 2022-02-21 at 5 00 07 PM](https://user-images.githubusercontent.com/11299125/155035929-66924a32-871e-43bf-ad7c-f4919628defd.png)

https://github.com/openstax/osbooks-contemporary-math 

I believe this is an injected exercise. Is there a way to align the text for exercises even if the numbers are double digit? We can also talk options and talk if this impacts more books.

**Comment by ajluk** [comment]
@lwtchu Here is how the change in the exercise numbers styling looks like in pdf in contemporary math:

1. When `.os-number` (the link with exercise number) has width set to **2%**:

![image](https://user-images.githubusercontent.com/55203598/156202367-abc6d443-f529-4861-8cdc-edfb7778c724.png)

   - within 3 digits number case (it looks worse there-see first number):
   
![image](https://user-images.githubusercontent.com/55203598/156202521-9a13250c-7c93-45e6-aefd-6732111a4457.png)

2. When the width is set to **3%**:
![image](https://user-images.githubusercontent.com/55203598/156202846-18f923fa-ce82-42c5-b2d2-8413160114e6.png)

  - it looks good also for 3 digits, but off course the number takes more place 
![image](https://user-images.githubusercontent.com/55203598/156203106-43285831-7f1e-40b5-a45d-cdf56feb4693.png)

**Comment by ajluk** [comment]
The decision was to fix the styling only for one column exercises and answer key, because the fix is not working in 2/3 column exercises/answer key.

**Comment by ajluk** [comment]
@MartaSztuka please test exercises and answer key in Contemporary Math (also content/section exercises at the end of the modules) Chemistry, Statistics, Accounting (one of the volumes). @lwtchu should we test more books? I didn't mention other math books because there the exercises are in 3 columns, simmilar situation is in physics (2 columns).

**Comment by ajluk** [comment]
@MartaSztuka the solution which worked for 3 digit numbers didn't properly with a large amount of math and tables in Chemistry, so there was a decision to apply the solution which works only for 2 digits.

**Comment by ajluk** [comment]
@lwtchu Could you take a look and advice if we need to do more tests or test more books? :slightly_smiling_face:

**Comment by lwtchu** [comment]
@ajluk i think this is good and very thorough :)
