### ISSUE TITLE
statistics - linking to exercises issues

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4507]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know

![Screen Shot 2022-02-22 at 10 23 15 AM](https://user-images.githubusercontent.com/11299125/155177098-684792dd-2e69-4664-893b-1e018869a679.png)
![image](https://user-images.githubusercontent.com/11299125/155231204-04f1f74a-b2c9-4840-81dc-3d089c5a6f79.png)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
no? I'm very confused. I think it might be due to it not being linked to an id that starts with "eip-". And is it broken because it has the word "exercise" in the ID? The ones that work link to an id that starts with "eip-" but wondering if the recipe is being strict or something else.

# Sample mark up if applicable

# Acceptance Criteria

# Bug Location(s)
https://github.com/openstax/osbooks-introductory-statistics-bundle

**Comment by lwtchu** [comment]
https://github.com/openstax/cnx-recipes/issues/4508#issuecomment-1048064114 

Might be related to this issue detailed in this comment ^^

**Comment by lwtchu** [comment]
Side note - is there a way to figure out which books this might impact?

**Comment by openstaxalina** [comment]
a few more instances for testing purposes:

[**_Introductory Statistics_ chapter 7**](https://openstax.org/books/introductory-statistics/pages/7-practice)
![Screen Shot 2022-02-22 at 4 32 44 PM](https://user-images.githubusercontent.com/7863733/155232505-6c2ba993-878c-4c3b-b9d4-37c11602f084.png)

[**_Introductory Statistics_ chapter 8**](https://openstax.org/books/introductory-statistics/pages/8-homework)
![Screen Shot 2022-02-22 at 4 31 00 PM](https://user-images.githubusercontent.com/7863733/155232597-3930f86b-07d6-43fc-bcbb-c3327d249b1a.png)

[**_Introductory Business Statistics_ chapter 2**](https://openstax.org/books/introductory-business-statistics/pages/2-practice)
![Screen Shot 2022-02-22 at 4 49 47 PM](https://user-images.githubusercontent.com/7863733/155232653-6674f02c-dddd-4f70-ad9e-ccfdecf46003.png)

**Comment by ajluk** [comment]
@lwtchu I think it is a content issue. In the assembled file there are links under the exercises which has the same id as the exercises. So kitchen is only adding an exercise label to the link as it should replacing [link] with exercise label and numbering. I guess there links should be just removed from the content, but if I'm missing something here let me know :slightly_smiling_face: : 
![image](https://user-images.githubusercontent.com/55203598/155323374-9178fcfe-2689-4175-976e-de8bb9e8572d.png)

**Comment by lwtchu** [comment]
Notes: Probably due to line 1116 here: https://github.com/openstax/rhaptos.cnxmlutils/blob/master/rhaptos/cnxmlutils/xsl/cnxml-to-html5.xsl#L1097

Need to talk to Phil!!

**Comment by lwtchu** [comment]
![image](https://user-images.githubusercontent.com/11299125/155364045-f7f0940b-9b98-44f2-bc2d-64131da0ef76.png)
![image](https://user-images.githubusercontent.com/11299125/155364064-daa51eea-6812-41a7-a6f5-084464149552.png)

Second screenshot might be causing issue in #4508

**Comment by philschatz** [comment]
[The changes](https://github.com/openstax/rhaptos.cnxmlutils/pull/206) are now [in enki](https://github.com/openstax/enki/pull/86)

**Comment by lwtchu** [comment]
@philschatz nice thank you !!

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/156051794-2632c4cf-c01e-4d36-827b-8aea81c9c1cd.png)
