### ISSUE TITLE
linking to two exercises in an exercise

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4508]
In CORGI we get this error if we introduce two `<link target-id="exercise11"/>`  in an exercise.
![Screen Shot 2022-02-22 at 10 54 15 AM](https://user-images.githubusercontent.com/11299125/155180546-54e5ada6-ab3e-4c9c-b3fe-97fe570050cc.png)

Is this our error? Or someone else's? It happened in stats but we reverted the change.

Test content: https://github.com/openstax/osbooks-ce-styles-test/testing-anchor

**Comment by lwtchu** [comment]
I FIGURED SOMETHING OUT

I think any `<link>` tag with any link or url or id to something called exercise - there’s a rule somewhere to treat all of those as embedded exercises and because statistics has some exercises with the id that contains the word “exercise” the recipe thinks “oh this is embedded, try to embed something”

which is why we get the weird links in #4507 and the error here

**is there a way to prompt embedded exercises without searching for the exercise word in <link> but to be prompted when it has the class=“os-embed”**

**Comment by philschatz** [comment]
[The changes](https://github.com/openstax/rhaptos.cnxmlutils/pull/206) are now [in enki](https://github.com/openstax/enki/pull/86)
