### ISSUE TITLE
finance - double URLs for embedded content in pdf

### ISSUE THREAD

**Issue by Jacqueline-Yarbrough** [openstax/cnx-recipes#4509]
The URLs in the Finance pdf appear twice, like this: "Click here for content. (https://openstax.org/) (https://openstax.org/)

This does not appear to be a content issue; link is only in the content once.

![Screen Shot 2022-02-23 at 10.59.19 AM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/9e511eb1-fe9f-465d-9585-45bd3de7f0af)

```
<section class="video-activity" id="sect-00012">
<title/>
<section id="sect-00013">
<title>Why Climate Change Means New Risk for US Financial Markets</title>
<media alt="climate-change">
<iframe width="660" height="371.4" src="https://openstax.org/r/player-pbs"/></media>
<exercise id="exer-00006">
<problem id="prob-00006">
<para id="para-00037"><link class="os-embed" url="#exercise/FI_Ch1_Sec1_VA2Q3"/></para>
</problem>
</exercise>
<exercise id="exer-00007">
<problem id="prob-00007">
<para id="para-00038"><link class="os-embed" url="#exercise/FI_Ch1_Sec1_VA2Q4"/></para>
</problem>
</exercise>
</section>
``` 

https://github.com/openstax/osbooks-intro-finance/

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image](https://user-images.githubusercontent.com/12678235/155613430-0850a93e-756a-4b66-aaa4-e2973605cc6f.png)
