### ISSUE TITLE
finance - remove subheading in CFA Institute 

### ISSUE THREAD

**Issue by Jacqueline-Yarbrough** [openstax/cnx-recipes#4510]
# What happened?

In the end-of-chapter section called "CFA Institute," the subheading for the last module in the chapter is at the top of this section. While the code is within the last module, it applies to the chapter as a whole, so the subheading is inaccurate and should be removed.

# Environment:

- **Introduction to Finance**
- **End-of-chapter section, "CFA Institute" (in every chapter)**

# Screenshots

![Screen Shot 2022-02-23 at 11.28.55 AM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/a61b59b9-de51-420f-b8de-f132deeb7250)

![Screen Shot 2022-02-23 at 11.29.48 AM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/af5ab6db-0240-4638-bdda-4a00852650f2)

# Markup

```
<section class="cfa-institute" id="sect-00006">
  <title>CFA Institute</title>
  <para id="para-00014">This chapter supports some of the Learning Outcome Statements (LOS) in this <link url="https://openstax.org/r/cfa-institute-org">CFA® Level I Study Session</link>. Reference with permission of CFA Institute.</para>
  </section>
</content>
```

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/957a7ce6-32db-4389-812b-a42ffacdf0b3)
