### ISSUE TITLE
[unfixable. waiting for prince xml to fix] footnotes are printed on the page following the referenced text

### ISSUE THREAD

**Issue by Jacqueline-Yarbrough** [openstax/cnx-recipes#4512]
# What happened?

Several footnotes are printed on the page following the referenced text. 

# Environment:

- **Introduction to Finance**
- **Sections 3.2, 3.4, 3.6, 4.4, 4.5, 12.1, 20.3**

# Screenshots
_The first screenshot is on page 78, second screenshot is on page 79._

![Screen Shot 2022-02-23 at 1.36.41 PM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/28b723fa-4c0c-44a9-bbca-aad5bac3e97e)

![Screen Shot 2022-02-23 at 1.37.29 PM.png](https://images.zenhubusercontent.com/5fcf9f93f5c7da63cf5e6dd8/9d680805-bf1b-44d7-bd99-7d202983f6c1)

# Markup

```
<figure id="fig-00001">
<title>Rate of Inflation Measured by the Consumer Price Index, 1947–2020<footnote id="foot-00001">Data from US Bureau of Labor Statistics. “Consumer Price Index for All Urban Consumers: All Items in US City Average (CPIAUCSL).” FRED. Federal Reserve Bank of St. Louis, accessed July 7, 2021. https://fred.stlouisfed.org/series/CPIAUCSL</footnote></title>
<media alt="Rate of inflation measured by the Consumer Price Index for All Urban Consumers between 1950-2020. It shows that the percentage change in the consumer price index was the highest in 1980, while it has remained between -2.5% to 7.5% since then."><image mime-type="image/png" src="../../media/FINAN_Figure_03_02_010.png"/></media>
</figure>

```

**Comment by lwtchu** [comment]
Related to #3548 ; currently no good technical fix

**Comment by lwtchu** [comment]
unfixable - prince hasn't had an update
