### ISSUE TITLE
OPS_Political Science_double URLs for embedded content in pdf

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4513]
The URLs in the Political Science pdf appear twice, like this: "Click here for content. (https://openstax.org/) (https://openstax.org/)

This does not appear to be a content issue; link is only in the content once. Kindly check and resolve this issue.

**Input:**
![url-input](https://user-images.githubusercontent.com/86622862/155516370-c70758c4-fd84-47f1-8b38-e729554b5a9c.png)

**Output:**
![url-output](https://user-images.githubusercontent.com/86622862/155516393-265f97b9-a34d-44bd-88c3-184f08e9f301.png)

# Bug Location(s)
collection ID: col00000
github openstax/osbooks- link: https://plum-narwhal-acs1o54u.ws-us33.gitpod.io/
chapter/section: Global
surrounding text: Erdogan Moves to Consolidate Power After Failed Military Coup

**Comment by lwtchu** [comment]
Similar issue to #https://github.com/openstax/cnx-recipes/issues/4509

**Comment by lwtchu** [comment]
The change in #4509 hits several books - so it will prob fix this one also

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/156051967-d03dba41-6c57-4234-a522-6fd291b45a0d.png)
