### ISSUE TITLE
contemporary math - nested list in note escaping margins

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4518]
# Brief Description of Scenario and Screenshots
![Screen Shot 2022-03-01 at 10 35 38 AM](https://user-images.githubusercontent.com/11299125/156209847-4d93b1e9-fb41-4bd4-a52c-4d975b06d1d1.png)

# Acceptance Criteria
The lists are within and margins and second nested list is indented from the first (a b c is indented under 1)

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-contemporary-math
collection slug (if applicable):
chapter/section: 1.4 - work it out feature titled: Covid-19 Hospitalization Data based on Vaccination Status
surrounding text: Draw a two-circle Venn diagram that represents the data in the table.

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/157006200-9814c467-3469-41a1-8f3f-325818732b00.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-03-07 14-20-27](https://user-images.githubusercontent.com/47241114/157042655-5aa7d5be-f3b7-4139-9922-d9ec66e08507.png)
