### ISSUE TITLE
contemporary math - small style change for subtitle in work it out

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4519]
![Screen Shot 2022-03-01 at 10 35 34 AM](https://user-images.githubusercontent.com/11299125/156210244-71f8245e-1f7f-4672-acb2-1dc8114d2e22.png)

# Acceptance Criteria
I believe the font and size is correct, but can we have the title match that pink color? thanks!

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-contemporary-math
collection slug (if applicable):
chapter/section: 1.4 - work it out feature titled: Covid-19 Hospitalization Data based on Vaccination Status
surrounding text: ^

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/972ff1cf-7f7d-49ca-b9db-5904332b4db9)
