### ISSUE TITLE
Contemporary Math: Sequence numbers for "Your Turns" are not populating now

### ISSUE THREAD

**Issue by mps-openstax** [openstax/cnx-recipes#4524]
After the update, "Your Turn" numbers are not populating in the PDF. Please see the snapshots from Previous PDF (Git) and revised PDF (Git) for your reference.

**Snapshot from Previous PDF**
![image](https://user-images.githubusercontent.com/88098452/156777111-b78e329a-5368-411b-b4b6-4b4eaab2a4d2.png)

**Snapshot from Revised PDF**
![image](https://user-images.githubusercontent.com/88098452/156777315-d1ecb6d7-6717-4e51-b4be-b44421204235.png)

**Comment by lwtchu** [comment]
Talked to MPS

Ideally we have the Your Turn numbered and then the numbers reset within the Your Turn. 

11.1
1.
2.

11.2
1.
2.

**Comment by MartaSztuka** [comment]
@lwtchu "Your Turns" looks as expected, but empty headers occurs.
![Screenshot from 2022-03-22 11-19-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/40d6198b-bc7b-49cc-9379-65f5da51971c)![Screenshot from 2022-03-22 11-20-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bb0d3aef-2834-482d-ad20-ca8f548b22ac)

**Comment by KarinaMendez2** [comment]
@lwtchu @MartaSztuka i'm working on a quick fix, just for good practice.

**Comment by lwtchu** [comment]
@KarinaMendez2 oh okay :joy: thank you <3

**Comment by Stackblocks** [comment]
Empty headers have been cleared out :+1: ![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d164e0f4-dc5d-45a7-86c6-0ad45af28037)
