### ISSUE TITLE
OPS-0013 Political Science YouTube link issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4527]
We’ve created the short link but it’s not working in the following embedded link ‘https://www.youtube.com/embed/KSxkjY_E53U' (refer below screenshot_Video unavailable).

![youtube1](https://user-images.githubusercontent.com/86622862/157228221-994d32d0-daae-4d57-bd77-e065cf501fd3.png)

This video short link did not working from PDF file, but working from online version. Kindly check and resolve this issue.

![youtube2](https://user-images.githubusercontent.com/86622862/157228252-628ddc46-baf7-4f26-a45f-d907d7b04752.png)

# Location(s)
github openstax/osbooks- link: https://plum-narwhal-acs1o54u.ws-us34.gitpod.io/
chapter/section: Chapter 10/Section 1
surrounding text: In this video, heads of state--including a führer, kings, a queen, a duke, an emperor

**Comment by lwtchu** [comment]
@srm-openstax I think this is a YouTube-specific error. When I copy and paste in the link to my browser, it gives me the same error. I suspect they are trying to send people to the website. We'll explore other options to try to make this experience better for PDF users, but let's leave this as is if it works in the webview.
