### ISSUE TITLE
exercises / assessment formatting update

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4530]
@lwtchu commented on [Fri Oct 08 2021](https://github.com/openstax/unified/issues/1726)

# Description
Remove the extra space between number and period and move the text inline with the number. Example:

1. Question question question?
2. Ah yes question question question?

Discussion questions (usually found under trailblazer sections)
chapter/section: Chapter 18, Section 18.2
surrounding text: 1. How does using a multimodal approach allow Bolatagici to communicate her lived experience?

![image](https://user-images.githubusercontent.com/11299125/136584020-e04d99c2-350c-46ed-ae82-36d0195bb750.png)

LOW PRIO - but just thought I'd open here. 
corresponding issue: https://github.com/openstax/cnx-recipes/issues/4019

# Acceptance Criteria
Give criteria for acceptance.

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Epic Doc
URL

# Pipeline
1A-PRE DESIGN
- [ ] PDM approves UX LoFi Design

1C-DESIGN
  - [ ] PDM approves UX HiFi Design

2B-REVIEW
  - [ ] UX approves change
  - [ ] QA approves change
  - [ ] PDM approves change
  
3A-PEND RELEASE
  - [ ] QA verifies that the acceptance tests are imported into TestRail

# Process 
[Work Management for Unified](https://github.com/openstax/unified/blob/master/CONTRIBUTING.md)

---

@lwtchu commented on [Wed Jan 12 2022](https://github.com/openstax/unified/issues/1726#issuecomment-1011405675)

Not sure if related - there's also an extra space between the number and period.
![image](https://user-images.githubusercontent.com/11299125/149213180-01a94646-d818-426b-a795-f23574d17eeb.png)
(Finance Chapter 14)

Corresponding Finance issues that are the same https://github.com/openstax/cnx-recipes/issues/4216  https://github.com/openstax/cnx-recipes/issues/4256

---

@lwtchu commented on [Thu Feb 03 2022](https://github.com/openstax/unified/issues/1726#issuecomment-1029216863)

https://github.com/openstax/cookbook/blob/main/spec/kitchen_spec/directions/bake_injected_exercise/bake_injected_exercise_question_spec.rb#L126 

^ Will this help?

---

@Malar-Natarajan commented on [Fri Feb 18 2022](https://github.com/openstax/unified/issues/1726#issuecomment-1044685667)

With 1799 Rex release, the following books also have this issue:
Prealgebra 2e
Elementary Algebra
Calculus Volume 2
Algebra and Trig 1e
College Algebra 1e
Precalculus 1e
College algebra with coreq 1e
Statistics [high school]
Financial Accounting
Managerial Accounting
Introductory Statistics
Introductory Business Statistics

https://openstax.slack.com/archives/CH5514N57/p1643843164879309

---

@Dantemss commented on [Tue Mar 08 2022](https://github.com/openstax/unified/issues/1726#issuecomment-1061869910)

For the space between the number and the dot: The problem here is in the content, there's a newline in the html between the number and the dot \<span\>. There's a hack we can do in CSS where we set the parent element to have a font-size of 0 and set the original font-size on the children so the space won't render, but it may be safer to fix the content instead if possible.

The other issue is simpler, it's just the line break from the question content \<div\> so we can either make it inline or inline-block or change it to a \<span\>.

**Comment by lwtchu** [comment]
https://app.zenhub.com/workspace/o/openstax/cookbook/issues/29

**Comment by MartaSztuka** [comment]
There are problems with exercises in following books:
##### Elementary Algebra
All lists stick out, certain elements are unstyled.
![Screenshot from 2022-03-10 16-24-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c5791e72-f771-4e61-9f88-270bea1f9302)
##### Calculus 2
Isn't space between those too big?
![Screenshot from 2022-03-10 16-33-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4c87c99c-5966-4497-804b-50d6fd9dcbd8)
#### PASSED
##### Prealgebra
![Screenshot from 2022-03-10 16-27-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/69387bea-3950-4d84-af47-8d0a91609f86)
![Screenshot from 2022-03-10 16-30-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7f24effb-e5a4-4996-8626-6bd85190d66b)

**Comment by lwtchu** [comment]
@MartaSztuka it looks like elementary algebra isn't generated with the right recipe? it should be with prealgebra.

**Comment by Stackblocks** [comment]
Elementary Algebra looks good

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0a09b88a-cab7-44d9-b78c-b45dfe2d6f61)

>

**Comment by MartaSztuka** [comment]
#### PASSED
##### College Algebra Coreq
![Screenshot from 2022-03-11 11-13-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/43da0b22-3bb3-46ea-9647-c55b1f40f8fd)
##### Algebra & Trigonometry
![Screenshot from 2022-03-11 11-16-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4643b0ef-8bb0-4c45-a7f1-531edec7e653)
##### Precalculus
![Screenshot from 2022-03-11 11-18-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f6d4cae2-395d-4765-b64c-642b4283b05e)
##### HS Statistics
![Screenshot from 2022-03-11 11-21-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/554851a6-f2eb-49f7-8281-1dd32b7b32b7)
##### Intro Statistics
![Screenshot from 2022-03-11 11-23-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7a2153ae-b1d1-4d70-9f55-9ed1ac1c5dc3)
##### Intro Finance
![Screenshot from 2022-03-11 11-25-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ee874a00-de7d-4b96-ae5f-805e54f49254)
##### Financial Accounting
![Screenshot from 2022-03-11 11-30-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fb3ff8fd-8930-4da2-bfef-f7d0d51f4174)
##### Marginal Account
![Screenshot from 2022-03-11 11-31-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/61ee9a69-9340-42df-ab5d-400d9abe8a06)

**Comment by Dantemss** [comment]
For the newline issue:

The style to make those divs inline already exists, but it requires the exercises to be wrapped in a section or div with one of a few classes, namely `os-eob`, `os-eoc` or `section-exercises`.

So either the affected books need to be updated to add one of those or we need to change the styles to add more classes... or make inline exercises the default and regression test everything.

**Comment by lwtchu** [comment]
@Dantemss that makes sense 🤔  we might need to make separate cards for those instances x_x
