### ISSUE TITLE
Writing Guide: Screen reader markup introduced stray marks on the PDF

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#4531]
# Brief Description of Scenario and Screenshots
Example 1 (folio 18)
![Screen Shot 2022-03-08 at 5 03 05 PM](https://user-images.githubusercontent.com/7863733/157340514-5156e2b7-0e6d-4f7a-bff1-49739b22315d.png)
Example 2 (folio 19)
![Screen Shot 2022-03-08 at 5 03 35 PM](https://user-images.githubusercontent.com/7863733/157340517-eab64d12-b36b-4fea-8e3d-51a06ec49eb3.png)

Additional examples found on folio pages 20, 25, 27-28, 46-49, 73. List is not exhaustive.

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
Unsure, but appears fairly frequent (11 out of the first 73 pages).

# Acceptance Criteria
- [ ] stray marks no longer appear on the PDF

# Sample mark up if applicable
```
<!-- Please paste here. -->
```

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-writing-guide
collection slug (if applicable): writing-guide
chapter/section: 1.4
surrounding text: "legal voter Larry Harmon"; "an inaccurate summary of the original post"

**Comment by lwtchu** [comment]
I think this is the screen reader text that is being poorly hidden.

**Comment by kswanson33** [comment]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/26280712/157486026-02f39152-0c7b-4091-a597-f436f31a7c09.png">

Settings:
- `opacity: 0`

@Stackblocks is it worth checking the screenreader still reads the text, or are we pretty confident this won't mess it up?

**Comment by Stackblocks** [comment]
@lwtchu If the only thing that changed was a display then there shouldn't be a problem. 

I'll add it to my list to double-check for the next accessibility review session but for the time being we should be OK to get this out the door for the publishers.

**Comment by lwtchu** [comment]
![Screen Shot 2022-03-09 at 10 54 53 AM](https://user-images.githubusercontent.com/11299125/157491025-bd7485da-a16b-44ae-b698-08a49ee456ce.png)
Tested locally - can confirm text is still there. jUst InViSiBle like they should be !!

**Comment by MartaSztuka** [comment]
#### PASSED
Text is invisible
![Screenshot from 2022-03-10 14-55-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bb161cf2-f892-45bc-bed0-293fb48a35b3)![Screenshot from 2022-03-10 14-57-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7824d6e6-e5ca-4cd4-b95d-da91d7dec70a)![Screenshot from 2022-03-10 14-57-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/983dcff9-31ae-4d25-a938-a8d42d5f5231)![Screenshot from 2022-03-10 14-58-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/db2f1016-1ced-4b5d-a9fe-67c5209c7f0c)
