### ISSUE TITLE
Mikroekonomia - bring it home note

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#4542]
![Screenshot from 2022-03-16 13-02-01](https://user-images.githubusercontent.com/47241114/158585664-1e660034-fd53-4058-8974-edb2d744915c.png)

- class: `class="economics bringhome"`
- uses #3193 
- title: Bring It Home
- has `<title>`
- icon: [cosmos-home.svg](https://drive.google.com/drive/u/0/folders/1bNHn_NpzAxHXLqVgdgZQc29ZptPTdkq0)
- color: `#ff6600`
- contains mostly paragraphs, figure, lists

**Comment by ajluk** [comment]
Screenshot for reference:![image](https://user-images.githubusercontent.com/55203598/158857560-1bd332b7-28e3-4fd7-b0a2-34c0df88201a.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-03-18 10-00-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8ccb6d5a-29a1-4975-81bf-4a69c77a0610)
