### ISSUE TITLE
Lists paragraphs pl-economics

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4551]
The paragraphs in lists added by Adaptarr need to be removed in pl-economics recipe:
![image](https://user-images.githubusercontent.com/55203598/158635683-c165a021-c9e0-4ef8-b300-aa0878bb150c.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-03-17 11-30-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/17531887-3c44-4c18-8b6c-52e54c4ccb9b)
