### ISSUE TITLE
OPS-0013 Political Science -- Chapter endnote text hidden issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4559]
We encountered the problem of text disappearing in the reference section throughout the book. Kindly check and resolve this issue.

![reference](https://user-images.githubusercontent.com/86622862/158807884-7648642c-1c7f-4141-8e65-ea864d591bcb.png)

# Location(s)
github openstax/osbooks- link: https://plum-narwhal-acs1o54u.ws-us38.gitpod.io/
chapter/section: Throughout the book
surrounding text: “Women Who Shaped the Universal Declaration,” United Nations, accessed January 25, 2022

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-03-24 12-58-25](https://user-images.githubusercontent.com/47241114/159911753-e567d175-35de-4fad-b29c-e9291d05242f.png)
