### ISSUE TITLE
Mikroekonomia - learning objectives

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#4566]
![Screenshot from 2022-03-18 14-47-14](https://user-images.githubusercontent.com/47241114/159014604-0a271431-fb44-4f43-9408-f525ae6a9265.png)

## Title
font: Archivo
weight: bold, 700
treatment: all caps
font size: font-scale(0): 9pt, 12px, 1rem
color: `#ff6600`

## Text 
font: IBM Plex Sans
font size: font-scale(0): 9pt, 12px, 1rem
color: black `#000000`

## List
should follow basic nested list specs
font: IBM Plex Sans
font size: font-scale(0): 9pt, 12px, 1rem
color: black `#000000`

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/159021333-ecef1ecd-ddec-4e60-aacc-08c34870a860.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-03-18 15-52-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6341fde7-f78f-45e0-ad05-9cdf4efd4c3d)
