### ISSUE TITLE
college physics 2e - answer key points to wrong page on TOC

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4567]
# Brief Description of Scenario and Screenshots
<img width="671" alt="Screen Shot 2022-03-18 at 9 26 13 AM" src="https://user-images.githubusercontent.com/1895432/159021429-fbaa917c-aece-4533-87ea-772dd43e8b4a.png">

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.

# Acceptance Criteria

# Sample mark up if applicable
```
<!-- Please paste here. -->
```

# Location(s)
github openstax/osbooks- link: [https://github.com/openstax/osbooks-college-physics-bundle](https://github.com/openstax/osbooks-college-physics-bundle)
collection slug (if applicable):
chapter/section: 
surrounding text:

**Comment by lwtchu** [comment]
The page number should be 
![image](https://user-images.githubusercontent.com/11299125/159042263-4283d772-7bbb-45e4-8845-36d58c692064.png)

**Comment by MartaSztuka** [comment]
#### PASSED
link works properly
![Screenshot from 2022-03-25 10-42-48](https://user-images.githubusercontent.com/47241114/160096244-a22d4486-47e0-404c-b007-ba5b13ba78f4.png)
![Screenshot from 2022-03-25 10-42-33](https://user-images.githubusercontent.com/47241114/160096258-d34de3a6-aa02-4845-8d54-ec36a32ba39d.png)
