### ISSUE TITLE
Caption font size larger in new college physics pdf

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4569]
<img width="1478" alt="Screen Shot 2022-03-18 at 1 20 09 PM" src="https://user-images.githubusercontent.com/1895432/159061489-1b9ffe8a-a475-407b-8846-fd0aa29996ef.png">
New on the left, old on the right

# Brief Description of Scenario and Screenshots

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
every instance
# Acceptance Criteria

# Sample mark up if applicable
```
<!-- Please paste here. -->
```

# Location(s)
github openstax/osbooks- link: 
collection slug (if applicable):
chapter/section: 
surrounding text:

**Comment by lwtchu** [comment]
Need to tweak some font specs since we made some big changes since this book was published. Please meet with me if you pick up this card

**Comment by ajluk** [comment]
@lwtchu Here are the specs for whole figure caption: 
![image](https://user-images.githubusercontent.com/55203598/159887825-5ac559f6-4936-4e29-aca5-a5bf8fbc5c55.png)
The font size is equal to 12px (1rem) which is base font size actually.
Here are the specs used only for title label and number: 
![image](https://user-images.githubusercontent.com/55203598/159889560-8fa05756-699a-40a2-b9b5-73a704662e01.png)
For the caption text the font differs:
![image](https://user-images.githubusercontent.com/55203598/159889814-bf3608ac-aa5c-4ad9-a8e2-d1ef3fa6307d.png)
The specs for Intro splash figures caption elements are exactly the same except `text-transform: uppercase` property added for title label: 
![image](https://user-images.githubusercontent.com/55203598/159890562-5104f5c9-7a7c-4486-8df2-d082395fb31d.png)
I have uppercased the splash figure title for comparison: 
![image](https://user-images.githubusercontent.com/55203598/159892284-afe7e24e-8e9e-400a-b141-30814ff4e153.png)
How would you like to change the specs?

**Comment by ajluk** [comment]
@lwtchu font-size was already set font-scale(0) for figures and wasn't set at all for splash figures (it was base font size inherited from typography.scss file: 
![image](https://user-images.githubusercontent.com/55203598/160624389-d57ee406-575c-47ce-8c8e-b9f2154df71a.png)
 ), so if I change it to 1 it will be even bigger: 
![image](https://user-images.githubusercontent.com/55203598/160648256-d0ff73e2-719f-49df-a1eb-6605d697c829.png)
![image](https://user-images.githubusercontent.com/55203598/160648310-2c7b6cc7-22e1-4033-838c-b6c15643a3db.png)
On the above screenshot it can be seen how `font-size=font-scale(1)` will look on in chapter intro and regular figures. Let me know this is a desired change.

**Comment by lwtchu** [comment]
@ajluk oh i meant font-scale(-1)?

**Comment by ajluk** [comment]
Ok, sorry for the misundertanding, here is how the caption looks line within the `font-scale(-1)` for regular figures: 
![image](https://user-images.githubusercontent.com/55203598/160875020-f9053acb-0829-4a29-b63c-6d1da21a716d.png)
![image](https://user-images.githubusercontent.com/55203598/160875182-0387cf5f-4fb6-4580-b18e-e8b01e438ff4.png)
and splash ones: 
![image](https://user-images.githubusercontent.com/55203598/160875115-af7fbee6-4f10-42e4-aac6-8bfae9e413d1.png)
Is there anything else what should be changed?

**Comment by ajluk** [comment]
Screenshot for reference when testing cookbook change: 
![image](https://user-images.githubusercontent.com/55203598/161271395-b6b76fe6-33cf-4504-873a-5913b6fc78de.png)

**Comment by ajluk** [comment]
Update: `line-height` should be also reduced to `1rem` for figure captions (both regular and splash)
