### ISSUE TITLE
OPS-0013 Political Science -- Unnumbered figure not aligned center

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4570]
We have received the below correction from customer. Kindly check and resolve this issue.

**Please make sure the box is centered.**

We have coded as per the tagging legend. But in the output PDF the image is aligned on the left side not centered.
**Tagging legend:**
![unnumbered](https://user-images.githubusercontent.com/86622862/159209059-039e5d20-6e73-4378-b8f0-c62f58747f31.png)

**CNXML file:**
![unnumbered_CNXML](https://user-images.githubusercontent.com/86622862/159209071-ab81fb08-e3f1-454a-9280-3a3e238f1b59.png)

# Location(s)
github openstax/osbooks- link: https://plum-narwhal-acs1o54u.ws-us38.gitpod.io/
chapter/section: Chapter 14/Section 5
surrounding text: Neorealism at a Glance

**Comment by lwtchu** [comment]
![Screen Shot 2022-03-21 at 10 39 58 AM](https://user-images.githubusercontent.com/11299125/159296944-2e0e73e8-4e09-4230-908e-a12b5a4b4128.png)
Can we make sure things marked up as `<figure>` stay centered. `<media>` items with no figure tag should be left aligned.

**Comment by lwtchu** [comment]
Note: The `<para>` with the bold "Box 14.1" numbering will be removed.

**Comment by ajluk** [comment]
@lwtchu I have fixed baking unnumbered figures for this book, but the unnumbered figures only get the `os-figure` wrapper which centers them when they have titles or captions. Should we change it and bake all unnumbered figures? If no the `para` containing figure caption text should be transformed to figure `figcaption` or div[data-type="title"]` in content.

**Comment by lwtchu** [comment]
@ajluk they'll remove that para! so we don't have to worry about it.

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/159894653-aa091a7e-60f9-42cb-8309-8dc3e923d54c.png)
(The figure caption is just a para so it won't be centered, it will be deleted/transformed to caption in the content).

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-03-24 13-02-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a0012af0-29d8-4117-a435-57578c139ea9)
