### ISSUE TITLE
OPS-0013 Political Science - 2nd level bullet list alignment issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4571]
We have received the below correction from customer. Kindly check and resolve this issue.

**These three points are subtopics under the first bullet point, so they should be indented more.**

**CNXML:**
![2nd-level-bullet-CNXML](https://user-images.githubusercontent.com/86622862/159213055-d6e723b3-1e1e-49d2-8635-ad18333db71b.png)

**PDF:**
![2nd-level-bullet-pdf](https://user-images.githubusercontent.com/86622862/159213066-13ec96d8-3d3f-4b58-9e8a-9ade1d379fbd.png)

# Location(s)
github openstax/osbooks- link: https://plum-narwhal-acs1o54u.ws-us38.gitpod.io/
chapter/section: Chapter 13/Section 1 
surrounding text: rational reflection, the people come to believe one of the following statements

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/159726602-c5317e08-8bc2-4558-83cb-4c2b2fa1fb62.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-03-23 16-47-07](https://user-images.githubusercontent.com/47241114/159740751-fa1be02a-9bca-465e-9b93-778f5629cea7.png)

**Comment by srm-openstax** [comment]
This problem has yet to be resolved. Please see the screenshot below. Kindly check and update this.

![2nd_level_bullet_alignment](https://user-images.githubusercontent.com/86622862/159845441-cf667d5f-a393-4253-8e48-132b222abada.png)

**Link for Output PDF in CORGI:** https://openstax-cops-artifacts.s3.amazonaws.com/introduction-political-science-latest-git-4758.pdf

**Comment by MartaSztuka** [comment]
This one also look's good, are there any other instances to check?
![Screenshot from 2022-03-24 11-42-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/76c702f1-3031-4745-9c23-3967abac5c00)
