### ISSUE TITLE
Contemporary Math: hyperlinks to the Figure/Table credits are appearing by default even if we are intentionally removing these.

### ISSUE THREAD

**Issue by mps-openstax** [openstax/cnx-recipes#4573]
Hyperlinks the Figure/Table are appearing by default even if we are not adding <a href=""> tag to them. Is there a way to do so. Please see the snapshots below for your reference.

**Output Snapshot from PDF**
![image](https://user-images.githubusercontent.com/88098452/159297323-f9c2d95a-1133-4fac-a633-233d0fe5ba52.png)

**Snapshot from Exercise Platform before Saving the exercise**
![image](https://user-images.githubusercontent.com/88098452/159298471-8bc01ea7-45ec-4811-82aa-446b0f0dfba2.png)

**Snapshot after saving the Question**
![image](https://user-images.githubusercontent.com/88098452/159298926-bb0c691a-3c72-43bd-a073-e2718a29ea4b.png)

**Question Details**
ID: 29013@14
Nickname: CM-C08-M1-Q008

**Comment by openstaxalina** [comment]
@lwtchu do we need coordination with REX or any other teams on this one?

**Comment by lwtchu** [comment]
@openstaxalina we were waiting for the content switch thing - i think we'll schedule it for the next sprint or so depending on priorities.

**Comment by wilkus27** [comment]
@lwtchu I see this issue is moved from Icebox to Backlog? It's ready to work on, isn't it? I fetched the newest content, but none of the exercises work:

![image](https://user-images.githubusercontent.com/40228854/196938396-64485dae-d079-4c4f-8aeb-55d8849a5473.png)

**Comment by lwtchu** [comment]
@wilkus27 i'm unable to replicate this :eyes: the exercises all seem to be there when it's generated. i wonder if something is missing in the files you pulled?  you could  try  clearing it out and trying again

**Comment by wilkus27** [comment]
@lwtchu I tried to fetch new content on Friday and today, but still exercises don't work :thinking: 
I mean in 8th chapter, where problem from the issue appears. In first chapter for example exercises are generationg properly.

**Comment by lwtchu** [comment]
I see some existing content fixes for this in Contemporary Math where they put "Source" as the anchor text. I'll propose that they do that.
