### ISSUE TITLE
College Physics 2e table separated from its title

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4575]
# Brief Description of Scenario and Screenshots
<img width="733" alt="Screen Shot 2022-03-22 at 9 20 56 AM" src="https://user-images.githubusercontent.com/1895432/159503918-4c913b89-ebb7-452b-8654-7d5bb3b60c8e.png">
<img width="731" alt="Screen Shot 2022-03-22 at 9 20 50 AM" src="https://user-images.githubusercontent.com/1895432/159503924-8994f2cd-aabe-4b44-968a-ed012b59b8b2.png">

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
Only found one so far
# Acceptance Criteria

# Sample mark up if applicable
```
<!-- Please paste here. -->
```

# Location(s)
github openstax/osbooks- link: 
collection slug (if applicable):
chapter/section: 
surrounding text:

**Comment by oscryan** [comment]
Also, very big table avoids breaking even when this makes the previous page very empty
<img width="732" alt="Screen Shot 2022-03-22 at 8 47 55 AM" src="https://user-images.githubusercontent.com/1895432/159521700-d6744012-b443-4b62-8cb9-bf934cffd561.png">
<img width="733" alt="Screen Shot 2022-03-22 at 8 48 03 AM" src="https://user-images.githubusercontent.com/1895432/159521710-296a43c4-9fc7-4127-99c4-b57af4d2cf70.png">

**Comment by lwtchu** [comment]
To whomever working on this card: can you tell me what the rules are for the page breaks for tables? Ideally it should be able to break within the `<tbody>` and NOT `<thead>` and the number/caption is not orphaned

**Comment by ajluk** [comment]
@lwtchu Here are the page breaks rules for all tables:

**Comment by lwtchu** [comment]
@wilkus27 is there a way to write something where if it's not the first or last row, the table can break?

**Comment by ajluk** [comment]
@lwtchu I guess you accidentally tagged Natalia, but I will check it out. :smile:

**Comment by lwtchu** [comment]
@ajluk :joy: i'm so sorry i was messaging her in the other two cards I was on and just typed it out of habit bahhh I'm sorry

**Comment by ajluk** [comment]
@lwtchu I have added page break rules to first and last tr like so:
![image](https://user-images.githubusercontent.com/55203598/160176448-a756c666-9719-4cce-a17d-8f461b5f0d07.png)
I couldn't use widows or orphans because they are designed for text lines in paragraphs.
Here is how the tables look like now :slightly_smiling_face: : 
![image](https://user-images.githubusercontent.com/55203598/160176699-40c24713-c52e-42db-a14d-6fb7fd35d0ca.png)
![Uploading image.png…]()

**Comment by MartaSztuka** [comment]
#### PASSED
##### College Physics 2e
![Screenshot from 2022-03-29 15-19-50](https://user-images.githubusercontent.com/47241114/160620827-13d58361-1fab-451b-a8f2-08c877787b1f.png)
![Screenshot from 2022-03-29 15-19-18](https://user-images.githubusercontent.com/47241114/160621645-952d43da-19db-4cee-910d-754a94e2dc14.png)
##### College Physics AP
![Screenshot from 2022-03-29 15-38-46](https://user-images.githubusercontent.com/47241114/160624504-3cac051e-8fee-434b-b3ba-5ceb588002a1.png)
![Screenshot from 2022-03-29 15-38-28](https://user-images.githubusercontent.com/47241114/160624517-b649998a-d6fb-4896-85e6-bfcca700d7cb.png)
