### ISSUE TITLE
carnival theme (A&P) - reducing spacing 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4590]
Please reduce padding in the following places

# learning objectives
![image](https://user-images.githubusercontent.com/11299125/160880030-7b0139c1-335b-4023-b687-1d7e5ace6212.png)

# figure captions
![image](https://user-images.githubusercontent.com/11299125/160880157-c9d240e8-9233-4b36-92cb-4431b99d153a.png)

# eoc sections
![image](https://user-images.githubusercontent.com/11299125/160880221-a61fd2d5-b470-44ce-b40a-80d718f70a2f.png)

A&P is called out for testing purposes, but this should impact all the books in the theme.

**Comment by ajluk** [comment]
@lwtchu I have reduced bottom-margins/paddings to` 0.7 rem` in the following places:

1. under the splash figure caption container
![image](https://user-images.githubusercontent.com/55203598/161062005-53e6c3ff-43d6-42da-b60a-e161e27ae126.png)

2. under the regular figures and tables
![image](https://user-images.githubusercontent.com/55203598/161062158-e2d3becc-5984-40e5-b790-3b1427d7e942.png)
![image](https://user-images.githubusercontent.com/55203598/161062985-c400036e-f1a8-427c-8de8-7ea1d8df1027.png)

3. Under the notes: 
![image](https://user-images.githubusercontent.com/55203598/161062458-46aa4667-1518-4536-b08d-91fce88f2b0d.png)

4. Under the EoC sections: 
![image](https://user-images.githubusercontent.com/55203598/161062784-8b062446-96a8-4d5a-a9e2-8f0d6e719e42.png)

5. Under the Index letters groups: 
![image](https://user-images.githubusercontent.com/55203598/161063158-c50d5bbb-7c34-45b0-b6e5-27b48aa85931.png)

 

Learning Objectives in Anatomy already had decreased bottom margin: 
![image](https://user-images.githubusercontent.com/55203598/161062333-66971483-e3fc-49e5-9b1c-79f80e205a1b.png)

**Comment by MartaSztuka** [comment]
Fizyka will be tested later. Closing the issue
