### ISSUE TITLE
Contemporay Math: Chapter 8, Image/Art numbering issues

### ISSUE THREAD

**Issue by mps-openstax** [openstax/cnx-recipes#4592]
The numbering of figures that appear in the Answer section is throwing off the figure numbering. (It jumps from Figure 8.25 (page **187**) to 8.32 (page **191**) here, for example.)

PDF is available at https://openstax-cops-artifacts.s3.amazonaws.com/contemporary-math-latest-git-4939.pdf

**Comment by lwtchu** [comment]
More robust card here: https://github.com/openstax/cnx-recipes/issues/4613
