### ISSUE TITLE
carnival theme - change base font from ibm plex serif to sans

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4599]
In the interest of saving space, please change from IBM plex serif to sans

Books to focus on are A&P and college physics

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/161295308-1b2b41f4-68a0-44c4-bf55-4b86a7a58f57.png)

**Comment by MartaSztuka** [comment]
Polish Physics will be tested later. Closing the issue
