### ISSUE TITLE
refactor kitchen unit tests to use snapshots

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4602]
^ whatever teh title says - someone can add more details in here

**Comment by kswanson33** [comment]
Switching from using inline HTML snippets to using [rspec-snapshot](https://github.com/levinmr/rspec-snapshot). This will keep all expected output HTML for kitchen tests in a `__snapshots__` directory. Input HTML snippets will remain inline. Expected output can be changed by using the `UPDATE_SNAPSHOTS=1` env variable when we make a change that creates a desired diff in the expected output.

**Comment by kswanson33** [comment]
closing cause this is dev side only
