### ISSUE TITLE
Precálculo 2e: need new class for "Preguntas y Respuestas" label 

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#4603]
# Brief Description of Scenario and Screenshots
Precalculo 2e needs a new class for the note labeled "Preguntas y respuestas". Currently, the class "precalculus qa" is used for this note and renders a "Q&A." The new class should render "PREGUNTAS Y RESPUESTAS"

Please set as "Preguntas y respuestas" in the es file and set text to uppercase in the feature styles.

![Screen Shot 2022-04-07 at 3 36 19 PM](https://user-images.githubusercontent.com/99201272/162291619-39335f56-b604-4cb7-afe9-0fe3e9c3bff4.png)

This problem occurs throughout the book.

# Acceptance Criteria

# Sample mark up if applicable
```
<note id="fs-id1165137740780" class="precalculus qa">
<label>PREGUNTAS Y RESPUESTAS</label>
```

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-precalculo
collection slug (if applicable): precálculo
chapter/section: Throughout book
surrounding text: N/A

**Comment by lwtchu** [comment]
in order to fit PREGUNTAS Y RESPUESTAS into that spot, could we break it up somehow like

PREGUNTAS
Y RESPUESTAS

**Comment by ajluk** [comment]
To achieve the tile label wrapping effect I have used such properties: 
![image](https://user-images.githubusercontent.com/55203598/163587290-42a858f0-041c-47f3-81d7-612743aac6c7.png)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![2022-04-18_16-05-48.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a121ad42-755b-46d2-9e77-c1a19628fb77)
