### ISSUE TITLE
Precálculo 2e: need new or revised class for "Ejercicio" label

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#4604]
# Brief Description of Scenario and Screenshots
Precalculo 2e needs a new or revised class for the note labeled "Ejercicio." Currently, the class "precalculus try" is used for this note and renders as "INTÉNTELO." It should render as "Ejercicio."

![Screen Shot 2022-04-07 at 4 37 49 PM](https://user-images.githubusercontent.com/99201272/162324633-e6d3b883-3cb8-48cc-ade9-1e9bbc26558e.png)

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
This problem occurs throughout the book.

# Acceptance Criteria

# Sample mark up if applicable
```
<note id="fs-id1165137588587" class="precalculus try">
<label>Ejercicio</label>
```

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-precalculo
collection slug (if applicable): precálculo
chapter/section: Throughout book
surrounding text: N/A

**Comment by lwtchu** [comment]
Consulted with Beth and Lina and they both say Inténtelo makes more sense for "Try It"
