### ISSUE TITLE
Precálculo 2e: Fix text overlapping margin

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#4609]
# Brief Description of Scenario and Screenshots
An equation is overlapping and disappearing into the page margin. The bottom half of the equation is completely lost.

![Screen Shot 2022-04-08 at 3 56 12 PM](https://user-images.githubusercontent.com/99201272/162530263-feb38d33-0a26-4520-83e5-841c77a54ffd.png)

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
Only occurrence in the first 750 pages.

# Acceptance Criteria

# Sample mark up if applicable
```
<!-- Please paste here. -->
```

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-precalculo
collection slug (if applicable): precálculo
chapter/section: 7.2, Ejemplo 6, under Figura 5
surrounding text: "El siguiente paso es hallar el coseno de y el seno de El coseno de es el lado adyacente sobre la hipotenusa. Podemos hallarlo a partir del triángulo en la Figura 5: También podemos hallar el seno de del triángulo
en la Figura 5, como el lado opuesto sobre la hipotenusa: Ahora estamos listos para evaluar"

**Comment by lwtchu** [comment]
I'm not sure how to fix this, but is there a way to detect math within these spaces?

**Comment by ajluk** [comment]
@lwtchu As I checked we have a page break rule (`page-break-inside: avoid`) added to `data-type="equation"` elements.

**Comment by lwtchu** [comment]
@ajluk not sure - but could it be because it's in an example?

**Comment by ajluk** [comment]
@lwtchu Sorry for bothering you within the content changes, I checked locally and it didn't help much. :disappointed: I checked the exmples styling as you suggested, but disabling the `display: block` property they use to style the whole container didn't changed anything, so next I have tried disable circled list styling and it is probably the reason why the equation is floating to page margin. I will try to fix it.

**Comment by lwtchu** [comment]
@ajluk oooh maybe we should remove from the list?

**Comment by ajluk** [comment]
@lwtchu Yes, that could fix the issue. I was thinking about something else, when we will see more places like this, we could add a specific class to such circled lists (e.g. `circled-block`) and use different styling for them (as block level list).

**Comment by lwtchu** [comment]
![image.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/f6588839-17b4-4b70-b7da-56a198aca883)

YAY removing from list worked
