### ISSUE TITLE
Precálculo 2e: Overlapping text running into next column

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#4611]
# Brief Description of Scenario and Screenshots
In some of the exercise sections, the text from one column is running into the next column. See screenshots below.

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
This happens in a few instances in chapters 6 and 8.

**Section 6.2 Exercises, Aplicaciones en el mundo real**
![6 2 Aplicaciones en el mundo real](https://user-images.githubusercontent.com/99201272/162774665-a3b14092-1be5-45a5-bfed-84d373eb1989.png)

**Section 8.1 Exercises, Gráficos**
(surrounding text: En los siguientes ejercicios, calcule la medida del ángulo si es posible. Redondee a la décima más cercana)
![8 1 Ejercicios, Graficos](https://user-images.githubusercontent.com/99201272/162777330-449e1ab0-a30a-4951-8a26-0c8eafd579c5.png)

**Section 8.1 Exercises, Extensiones (2 instances)**
![8 1 Ejercicios, Extensiones](https://user-images.githubusercontent.com/99201272/162776974-d322e56f-f939-4cc2-bb87-253a4e25332b.png)

**Section 8.2 Exercises, Aplicaciones en el mundo real**
![8 2 Aplicaciones en el mundo real, p864](https://user-images.githubusercontent.com/99201272/162778339-49d92395-8150-4c0c-97f5-c80ccbd015d6.png)

**Chapter 8, End-of-chapter Exercises, Vectores**
(surrounding text: En los siguientes ejercicios, calcule la magnitud y la dirección del vector)
![Chp8 Ejercicios, p971](https://user-images.githubusercontent.com/99201272/162779138-4f7457b3-f708-425b-83cc-eb60cf68a848.png)

# Acceptance Criteria

# Sample mark up if applicable
```
<!-- Please paste here. -->
```

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-precalculo
collection slug (if applicable): precálculo
chapter/section: See instances above.
surrounding text: See instances above.

**Comment by lwtchu** [comment]
@caylaeagon 99% chance there's white space in those pieces of art. if you don't have time to change them, see if you can put the `class="material-set-2"` on the exercise and it'll force the exercise to 2 columns
