### ISSUE TITLE
Contemporary Math - Bug: numbered figures in Answer Key content (all collated content?) are counted/numbered pre-collation

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#4613]
# Brief Description of Scenario and Screenshots
@mps-openstax noted that the figure numbering is off because numbered images in the Answer Key (collated element) are numbered based on their original location in the content.

The effect is that someone reading the book sees the figure numbers skip, like from Figure 1.4 to Figure 1.6, because "Figure 1.5" was moved to the answer key.

@mps-openstax could you please put in an example or two in comments below?

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
I believe this happens in every instance with numbered figures in the answer key. 

# Acceptance Criteria

# Sample mark up if applicable
```
<!-- Please paste here. -->
```

# Location(s)
github openstax/osbooks- link: 
collection slug (if applicable):
chapter/section: 
surrounding text:

**Comment by lwtchu** [comment]
> The numbering of figures that appear in the Answer section is throwing off the figure numbering. (It jumps from Figure 8.25 (page **187**) to 8.32 (page **191**) here, for example.)
> 
> PDF is available at https://openstax-cops-artifacts.s3.amazonaws.com/contemporary-math-latest-git-4939.pdf

Comments from #4592

**Comment by lwtchu** [comment]
@mps-openstax could you please remove the `<figure>` tags around the `<img>` in the answers? thank you
