### ISSUE TITLE
Contemporary Math: how to capture inline image/graphics in XML

### ISSUE THREAD

**Issue by mps-openstax** [openstax/cnx-recipes#4614]
Is there a different way to capture inline images/graphics/symbols? If we are using <media alt="Insert Alt Text"><image mime-type="image/jpg" src="../../media/CS_symbol_04_B00.jpg"/></media> then it breaks the flow of the text.

Please see the snapshots below and suggest.

**Snapshot of the Input file**
![image](https://user-images.githubusercontent.com/88098452/163173750-6fd727ae-5436-465f-89aa-f7e753600e14.png)

**Snapshot of the Output file**
![image](https://user-images.githubusercontent.com/88098452/163173879-926a604c-cf37-4c9a-9640-6bca64752c98.png)

**Comment by lwtchu** [comment]
Please add `display="inline"` to the media tag. I have also updated the tagging legent with the instructions on line 28.

**Comment by openstaxalina** [comment]
@mps-openstax this is a markup change, detailed by Larissa above. Please reopen this issue if the new markup does not satisfy display requirements.
