### ISSUE TITLE
Precálculo: "ejercicios de sección" heading in the end-of-book answer key needs to be in sentence case

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#4617]
# Brief Description of Scenario and Screenshots
The "ejercicios de sección" heading in the end-of-book answer key begins with a lowercase letter instead of in sentence case. 

![Screen Shot 2022-04-15 at 4 50 58 PM](https://user-images.githubusercontent.com/99201272/163839241-587c5706-9107-41a6-92f5-c89506d60849.png)

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
Yes.

# Acceptance Criteria
`ejercicios de sección` should be `Ejercicios de sección`

# Sample mark up if applicable
```
<!-- Please paste here. -->
```

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-precalculo
collection slug (if applicable): precálculo
chapter/section: End-of-book Answer Key
surrounding text: n/a

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-04-19 14-57-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0498b158-a529-47b3-950f-703e3c44ad74)
