### ISSUE TITLE
Caption - split general container component

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4620]
General Container component mostly contains OPTIONAL properties. It would be better to split this component into containers of a few types.

**Comment by wilkus27** [comment]
@lwtchu I have a few questions about styles.

**1. Line height in Cardboard**

For Figures it is set to `1rem`. Should I apply this for Chapter Intro Figure and Tables for consistency? Here is an example for tables:

current style
![image](https://user-images.githubusercontent.com/40228854/164458805-9b94f819-b835-4159-badc-1e18e139e667.png)

with decreased line height
![image](https://user-images.githubusercontent.com/40228854/164458929-f6d7cda3-79c5-41f3-9d8c-6881d70d9500.png)

**2. Margin bottom**

Should I add margin bottom for caption everywhere for consistency? In some themes it's added for each type of caption container (figure, chapter intro, table), in others just for one type.

**Comment by lwtchu** [comment]
1. let's apply for consistency - the 1rem line height
2. has it historically had a margin bottom? this will help with the padding right? - maybe we can add a small amount.

**Comment by wilkus27** [comment]
@lwtchu Ok :+1: I will set 1rem line height. About bottom margin, I analized it more carefully and after that I think it would be better to leave this as is. Differences come from different way of styling. Sometimes margin was added to entire figure, table and sometimes just to the caption, but the visual effect is the same.

**Comment by Stackblocks** [comment]
Captions showing with 1rem line height, no unexpected changes noted.

![2022-05-02_15-18-36.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e922c4f1-28b4-435d-880e-99da6f1cbba9)

**Comment by lwtchu** [comment]
![Screen Shot 2022-05-09 at 3.18.34 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/ff68c4ac-f2af-43c7-9e79-e21feb10c4bc)

![Screen Shot 2022-05-09 at 3.18.50 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/b170f66d-e4c8-4a4b-8907-220474189a66)

screenshots from astronomy and business law. passed
