### ISSUE TITLE
Refactor `./script/run` for cnx-recipes devs

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#4621]
[this script](https://github.com/openstax/cnx-recipes/blob/main/script/run) remains useful to dev workflows, but many dependencies in the repo have changed since it was last updated, and we have found ways that it is ... inefficient

Acceptance Criteria:
- [x] `./script/run` allows for portable lightweight development & can containerize `./script/build-styles` and `./script/build-impacted-styles` and any single `dart ./script/build/build.dart <in> <out>` script. (do we use more scripts than that these days??)
- [x] `./script/run` uses Dockerfile in cnx-recipes
- [x] file changes from running various build scripts persist outside the container & after the container has been stopped
- [x] run script has been simplified; no longer uses docker-compose
- [x] run script doesn't leave containers running or create extra images (check that it can be run many times without creating a new image each time)
- [x] files created by the container have [permissions](https://gist.github.com/philschatz/b2d0f8957c98d3e69ba825722929b652#volume-permissions) f[ixed](https://github.com/openstax/enki/blob/main/dockerfiles/10-fix-perms.sh)

**Comment by lwtchu** [comment]
Humanreadable Goal: create lightweight container-ized version ; but too many skeletons. need to deskeletonize script

**Comment by lwtchu** [comment]
MJ learning bash for this. so this is why it's in icebox

**Comment by lwtchu** [comment]
Update: Weird docker issues blocking
