### ISSUE TITLE
AP Physics math does not render in 2 collated sections

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4622]
Math works fine in collated sections Glossary, Section Summary, Conceptual Questions and Test Prep for AP Courses. The one section collating in AP Physics that negates the rendering of the math is Problems & Exercises.
<img width="1636" alt="Screen Shot 2022-04-21 at 2 11 09 PM" src="https://user-images.githubusercontent.com/1895432/164536373-72c802d0-bad8-40f7-9a3d-2088b755dd59.png">

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
Yes, every chapter.

# Acceptance Criteria

# Sample mark up if applicable
```
<!-- Please paste here. -->
```

# Location(s)
github openstax/osbooks- link: 
collection slug (if applicable):
chapter/section: 
surrounding text:

**Comment by lwtchu** [comment]
Use osbooks-college-physics-bundle and slug: college-physics-ap-courses-2e with the ap-physics-2e recipe

**Comment by kswanson33** [comment]
It should now generate math correctly (Problems & Exercises section math has the `m:` prefix on math tags & the rendering looks good)

**Comment by MartaSztuka** [comment]
#### PASSED
There is `m:` prefix in Exercises section.
![Screenshot from 2022-05-24 12-53-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0f643f38-36ff-47b6-a426-be050992bda8)![Screenshot from 2022-05-24 12-52-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/80c77f1b-8236-47e6-b463-c7342f9477aa)
