### ISSUE TITLE
Add Bake Appendix pl-economics

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4632]
Baking Appendices needs to be added to pl-economics recipe after content changes.
- change needed in styles -  add color bands to appendix pages
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/166663605-e79f6442-b92a-4332-85b2-aac7f998bf13.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-05-04 14-41-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/048a3f1d-7779-4be4-be46-5066e1c95b62)![Screenshot from 2022-05-04 14-41-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3c95951d-ed99-42c8-bcc3-1ca65d9c97d4)![Screenshot from 2022-05-04 14-41-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b031dd09-cc0c-4ebd-909b-3f8530a184d7)
