### ISSUE TITLE
OPS-0013 Political Science Japanese characters not Supported in output (PDF & Web-view)

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4633]
We have updated this caption according to the comments. However, the output was not properly converted to Japanese characters in PDF. Kindly check and resolve this issue.

**Comments PDF:**
![Comments_PDF](https://user-images.githubusercontent.com/86622862/165750518-824bcd32-d787-4751-b5dd-705246bfe61a.png)

**Output PDF:**
![Output_PDF](https://user-images.githubusercontent.com/86622862/165750595-19171870-2cd8-4037-9daf-13b8aed18b93.png)

# Location(s)
github openstax/osbooks- link: https://plum-narwhal-acs1o54u.ws-us43.gitpod.io/
chapter/section: Chapter 10/Section 6
surrounding text: In Japan’s parliamentary system, the prime minister is the head of the Cabinet

**Comment by lwtchu** [comment]
@srm-openstax Would you be open to putting the translation? "Commemorative Photo 2"

**Comment by lwtchu** [comment]
Sent to @yblock to add in content for Final QA

**Comment by yblock** [comment]
I replaced with the translation
