### ISSUE TITLE
college physics broken rex link

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#4634]
context: https://openstax.slack.com/archives/CH5514N57/p1651158426684589

Broken sample content:

```
<div data-type="media" id="auto_02f52a02-2484-4ccb-bbd4-3c94edaa8e09_concept-trailer-newtons-laws" data-alt="OpenStax Concept Trailer for Newton's Laws">
 
<div class="os-has-iframe os-has-link" data-type="alternatives"><a class="os-is-link" href="https://openstax.org/books/college-physics/pages/4-introduction" to="" newton="" laws="" of="" motion="" target="_blank" rel="noopener nofollow" dynamics:="">Click to view content</a>
```

AC: The spare attributes should be part of the link target & create a well formed rex link that works

**Comment by lwtchu** [comment]
context: https://openstax.slack.com/archives/CH5514N57/p1651158426684589

**Comment by kswanson33** [comment]
For QA: 
- book should build instead of breaking at the `git-bake-meta` step
-  The link near search text "Most of the scientific theories that are described in this book descended from the work of these scientists." should be ... normal, and have a url that looks like `https://openstax.org/books/<book>/pages/<number>-<some-kind-of-title>`

**Comment by Stackblocks** [comment]
College Physics bake ran from start to finish without needing additonal nudges and the link URL matches the structure described.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/2dd84dc9-d799-4d70-97aa-4958e8f6e748)

**Comment by lwtchu** [comment]
![Screen Shot 2022-05-09 at 3.08.20 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/8c9126ba-3f09-4d41-8cde-7d94b2ce2bf0)

Staging 

The link 404s tho? ...should we open another card
