### ISSUE TITLE
marketing - unit opener

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4647]
![Screen Shot 2022-05-02 at 2 30 58 PM](https://user-images.githubusercontent.com/11299125/166312899-e8493786-860d-4d05-91c3-81871ebe2a50.png)

Similar to https://github.com/openstax/cnx-recipes/issues/3936

Change the Archivo title fonts to Roboto Condensed
Base font to Noto Sans
Red to: B2: `#344456`
Faint red to: Grey1: `#F9F9F9`

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![2022-05-24_15-22-04.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f0227263-31c8-4704-9099-c9e21ca65b76)

![2022-05-24_15-20-47.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3c3283b2-7c4f-4ec8-bee7-9de7fead9e10)
