### ISSUE TITLE
marketing - feature updates

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4648]
![Screen Shot 2022-05-19 at 9.10.31 AM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/a9b8f7ab-dccd-457a-9d68-7bcc3b8243f2)

# Link to Learning
top bar: O3: `#F37541`
top title text color: black `#000000`
bottom box: Y2: `#fcf6ee`
icon: [cardboard-globe.svg](https://drive.google.com/file/d/16SoDMSGKfmCz4aed86kgMF3v4dtWkTq6/view?usp=sharing)

# Marketing Dashboard
top bar: R2: `#B10069`
top title text color: white `#FFFFFF`
bottom box: R3: `#F7E6F0`
icon: [cardboard-marketingdashboard.svg](https://drive.google.com/file/d/1oAoHVtFaL0V2lhVNdFRYJ4rQ5k9FoiAd/view?usp=sharing) - SLIGHTLY NEW DESIGN PLEASE REUPLOAD

# Marketing in Practice
top bar: P3:`#9028A3`
top title text color: white `#FFFFFF`
bottom box: Grey1: `#F9F9F9`
icon: same as before [cardboard-leadership.svg](https://drive.google.com/file/d/1WZm0hAvgzLkuqNjOqDYEQkIlgNDd8HtK/view?usp=sharing)

# Companies with a Conscience
top bar: G1: `#1E9575`
top title text color: black `#000000`
bottom box: G2: `#F2F2F2`
icon: same as before [cardboard-conscience.svg](https://drive.google.com/file/d/1NmorXaY1W9xCetBI4OdapG5G4FlLFfCP/view?usp=sharing)

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/169264083-ccfd58c6-2660-4dce-ab0a-93cfe04a3f4d.png)

![image](https://user-images.githubusercontent.com/40228854/169264142-74f2a727-3993-4c47-b0c8-6a0d01d022b3.png)

![image](https://user-images.githubusercontent.com/40228854/169264258-62358347-578f-45f7-9a6b-e192d006c82f.png)

![image](https://user-images.githubusercontent.com/40228854/169264383-dec9a75e-839b-4d5b-9d06-401982928205.png)

At the screenshot above body font color in Marketing in Practice seems to be grey. Now it's black. Should I change it?

**Comment by wilkus27** [comment]
@lwtchu Ok, thank you! :relaxed: Here is dashboard note with new icon:

![image](https://user-images.githubusercontent.com/40228854/169322358-f553905e-43ab-4804-8263-625c7419680f.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-05-20 16-53-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/18ae813a-2902-46c9-8508-121e7a74fa66)![Screenshot from 2022-05-20 16-53-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/41635366-9511-48d8-aba6-c0e085b27805)![Screenshot from 2022-05-20 16-53-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/120134bd-d3ae-4221-bfbf-5bb968543421)![Screenshot from 2022-05-20 16-53-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/88a4d43e-2040-43df-8b97-9ec95d9462e1)
