### ISSUE TITLE
marketing - rename endnotes to references

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4649]
![Screen Shot 2022-05-03 at 11 35 10 AM](https://user-images.githubusercontent.com/11299125/166498750-64f54fc1-c892-439f-929d-8fad4bc0103c.png)

Can we rename the endnotes to references?

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-05-18 16-47-35](https://user-images.githubusercontent.com/47241114/169070507-9507100c-8a80-4563-aead-4935c136ce78.png)
