### ISSUE TITLE
marketing - learning outcomes design change

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4650]
![Screen Shot 2022-05-03 at 11 40 05 AM](https://user-images.githubusercontent.com/11299125/166499679-712ed592-d606-4bc9-abb3-a6f1242fd896.png)

Change numbering to LO 1, LO 2, --- could we potentially make this a numbered list with the LO svg from accounting? Let me know please

**Comment by lwtchu** [comment]
@ajluk yes they want to change the LOs to 1 2 3 🤔  is that an issue

**Comment by ajluk** [comment]
Screenshot for reference (confirmed by Larissa via slack :slightly_smiling_face: ): 
![image](https://user-images.githubusercontent.com/55203598/169356256-b2f1976d-d963-44b5-b1fe-b2a8cf44b1b7.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-05-25 12-06-38](https://user-images.githubusercontent.com/47241114/170237885-9affa492-0b55-4b39-8407-fe518ed3d607.png)
