### ISSUE TITLE
Style chapter intro figure titles

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4656]
![Screen Shot 2022-05-09 at 2.14.55 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/c5e1593a-42fb-4596-98c8-e90cb67bd4ac)
![Screen Shot 2022-05-09 at 2.11.15 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/1b8db326-f736-42fc-917a-9f6e6aa9ea19)

Figure title in introduction unstyled in Astronomy and Business Law (cardboard theme)

@wilkus27 should I open a separate card for the bugs

_Originally posted by @lwtchu in https://github.com/openstax/cnx-recipes/issues/4642#issuecomment-1121476962_

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/169083304-bbc6b672-670e-44cf-9fa1-6454966a01d5.png)

**Comment by MartaSztuka** [comment]
#### PASSED
###### Astronomy
![Screenshot from 2022-05-19 13-36-00](https://user-images.githubusercontent.com/47241114/169284561-a7a95e9e-4400-4d95-aaca-a3c32768c545.png)
