### ISSUE TITLE
[blocked] update nokogiri to 1.13+

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#4657]
Will fix issues like #4622 going forward (handles character encoding in document fragments)

**Comment by kswanson33** [comment]
phil says we may be able to achieve the same result by upgrading nokogiri

**Comment by kswanson33** [comment]
from phil via slack:

Using byebug, [this line](https://github.com/openstax/cookbook/blob/main/lib/kitchen/element_base.rb#L554) internally creates a DocumentFragment when assigning node.children (see [1](https://github.com/sparklemotion/nokogiri/blob/ca877887551ef19d8ec51fc4dfb503097bf8da45/lib/nokogiri/xml/node.rb#L257-L263), [2](https://github.com/sparklemotion/nokogiri/blob/ca877887551ef19d8ec51fc4dfb503097bf8da45/lib/nokogiri/xml/node.rb#L1317-L1324), [3](https://github.com/sparklemotion/nokogiri/blob/ca877887551ef19d8ec51fc4dfb503097bf8da45/lib/nokogiri/xml/node.rb#L929), ) .

The DocumentFragment is constructed using default options instead of inheriting the STRICT flag from the document (see [2](https://github.com/sparklemotion/nokogiri/blob/ca877887551ef19d8ec51fc4dfb503097bf8da45/lib/nokogiri/xml/node.rb#L930), [3](https://github.com/sparklemotion/nokogiri/blob/5fcea4236242af3d508587a85f70a244f9c7f80f/lib/nokogiri/xml/document_fragment.rb#L21), )

Our version of the code has this [ctx.parse(tags)](https://github.com/sparklemotion/nokogiri/blob/5fcea4236242af3d508587a85f70a244f9c7f80f/lib/nokogiri/xml/document_fragment.rb#L21) while the latest version of nokogiri has [ctx.parse(tags, options)](https://github.com/sparklemotion/nokogiri/blame/ca877887551ef19d8ec51fc4dfb503097bf8da45/lib/nokogiri/xml/document_fragment.rb#L30) . The [commit](https://github.com/sparklemotion/nokogiri/commit/ad1658391ced72b02065bc67cf256c585286cd3a) that changes that line links to bugs that match what we've observed: Setting Strict does not apply to fragments that are added to the document

**Comment by kswanson33** [comment]
Tried to upgrade, but 1.13, while fixing the weird namespace thing, introduces other problems. These problems are introduced in the upgrade from 1.12 to 1.13. They include:

- two kitchen directions with badly formatted HTML (this is now being handled differently by nokogiri, and is easily fixed)
- a mysterious problem where terms with _well_-formatted ampersands have their ampersands (and surrounding letters) deleted when the term is added to the index

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/877cd491-99f1-4c85-ad9f-1cfb2e7b269a)

This makes me concerned about what other changes 1.13 might introduce that aren't being caught by our tests. Because this calls for more testing, we're going to hold off on this for now.

**Comment by lwtchu** [comment]
Waiting for BAP :boom:

**Comment by lwtchu** [comment]
Closing card because we are a ways away from making this happen (?) or making it easily happen. We can close and reopen when the time is right. Or reopen this.
