### ISSUE TITLE
First elements in exercises, answer key need support in College Physics 2e recipe

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4659]
Regarding point 1 from: https://github.com/openstax/cnx-recipes/issues/4630#issuecomment-1125287281
![image](https://user-images.githubusercontent.com/55203598/168296456-af216e49-f6c3-4e0c-bfe2-5429deb94aff.png)

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/168306590-6c56a915-8373-4f7e-b69a-64d8025c848e.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-05-17 14-17-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fa3c1aa7-765d-473e-8263-6f4a0cf0aa70)
