### ISSUE TITLE
Add space between images and paragraphs in exercises

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4660]
Regarding point 2 from: https://github.com/openstax/cnx-recipes/issues/4630#issuecomment-1125287281
Bottom margins has been removed (set to `0`) from paragraph in exercises in almost all themes (except corn), but when the next sibling is an image more space is needed. 
![image](https://user-images.githubusercontent.com/55203598/168307694-0b505989-f75f-4f46-a25d-f6030be7ad7f.png)
In corn the paragraph bottom margin can be also removed, but here we need to add a top margin to circled lists if they are the next sibling.

**Comment by wilkus27** [comment]
### Information for tester

During figures refactoring I missed this book, so I added now all needed changes. Beside problem from the card, would you mind test also things from this Epic https://github.com/openstax/cnx-recipes/issues/4630 for Accounting? :relaxed:
