### ISSUE TITLE
Contemporary Math: Numbered tables appearing in Answer/Solution of exercises are not populating Table Numbers

### ISSUE THREAD

**Issue by mps-openstax** [openstax/cnx-recipes#4668]
Numbered tables appearing in the answer/solution to the exercises are not populating Table numbers. Please see the coding from the exercise platform and the PDF created from CORGI for your reference below. Please suggest.

**Snapshot from Exercise Platform**
![image](https://user-images.githubusercontent.com/88098452/169308020-ac7ec4a1-aca1-4be5-a6d9-a5a5a09040f0.png)

**Snapshot from PDF**
![image](https://user-images.githubusercontent.com/88098452/169309082-5eae8c71-9dac-42c8-bcec-db2bdacaccb6.png)

**Comment by lwtchu** [comment]
@mps-openstax Could you try changing the copy to say something along the lines of "the table in the solution for (link to exercise)"

**Comment by openstaxalina** [comment]
MPS is no longer flagging this as an open issue and I understand this has been resolved in content. Closing
