### ISSUE TITLE
accounting - chapter outline icons fall out of margin

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4669]
![image](https://user-images.githubusercontent.com/11299125/169352454-1f9f570b-2cc3-4e3b-acb9-08e8b297b369.png)

Can we have these fall back within the content space :joy:

**Comment by ajluk** [comment]
@lwtchu I have checked how it looks on the latest content and code and it seems the issue has been resolved: 
![image](https://user-images.githubusercontent.com/55203598/169794558-a978dc1b-1af7-4785-b227-ccfab985b9c3.png
I have checked both two volumes from: https://github.com/openstax/osbooks-principles-accounting-bundle

**Comment by lwtchu** [comment]
@ajluk oh nice. i'm gonna close :joy:
