### ISSUE TITLE
Contemporary Math: Provide Guidance on Markup for "Research It" ONE-TIME Header

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#4699]
# Brief Description of Scenario and Screenshots

@lwtchu there is a one-off header in CMath as shown below. Note: this is not a planned or requested feature. Is this OK to leave displaying as-is or is there better markup you suggest?

(I thought maybe "Research It: History of Zero" to save some space.)

![Screen Shot 2022-05-31 at 3 07 53 PM](https://user-images.githubusercontent.com/7863733/171266751-fa6ac89c-5589-4fba-87f1-eda086e293f9.png)

If you need the exact location in the book please tag MPS.

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
N/A - only one instance

# Acceptance Criteria
- [ ] Larissa to approve markup as-is or provide new markup on this card
- [ ] Larissa to alert Umesh & Sam re: decision via email 

# Location(s)
github openstax/osbooks- link: github.com/openstax/osbooks-contemporary-math
collection slug (if applicable): contemporary-math
chapter/section: unknown
surrounding text: "The history of the number 0 was not inherently natural."

**Comment by lwtchu** [comment]
@mps-openstax First, the Projects section is missing the `class="projects"` class.  I would suggest moving the `RESEARCH IT!` under the Projects section as another project and changing the title to `History of Zero`. The other Projects in this section has some sort of research/Googling element and I think it can go together.

**Comment by openstaxalina** [comment]
per MPS I am closing this
