### ISSUE TITLE
baked styles refactor: splash figures

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4703]
- [x] standardize splash figures wrapper (`div.os-figure.has-splash`) bottom margin to 0.7rem 
Across the themes bottom margin value set for splash figures wrapper differentiate: 
- CARNIVAL: `0.7rem (margin-bottom: v-spacing(1),)`
- CARDBOARD:` 2rem` (here it will need to be checked if reducing won't be to low and won't break the intro design)
- CORN:  `2rem`
- COSMOS: `3.5rem (v-spacing(5))`
Example from statistics: 
![image](https://user-images.githubusercontent.com/55203598/171879333-986032ed-5fe2-4065-b534-3319f10936b1.png)

- [x] standardize splash figure caption top and bottom paddings to `0.7rem` (?) after confirmation from Larissa 

- CARNIVAL
        `padding-top: v-spacing(1),
        padding-bottom: v-spacing(1),`

- CARDBOARD (there was no top padding, just margin bottom)
        `margin-bottom: v-spacing(1),`

- CORN
        `padding-top: 1rem,
        padding-bottom: 2rem,`

- COSMOS (there was no top padding, just margin bottom)
      ` margin-bottom: v-spacing(1),`

- excluding splash figures from chapter intro shapes will be done within a separate issue

**Comment by ajluk** [comment]
@lwtchu Here is how the intro looks before and after decreasing the splash figure wrapper bottom margin to 0.7rem in:
1. cosmos 
![image](https://user-images.githubusercontent.com/55203598/179570025-1c867fec-bae4-4174-84bd-6f1f934cac70.png)
![image](https://user-images.githubusercontent.com/55203598/179570129-2404be4e-98d6-4b47-a3b8-fc08f79b1bb7.png)
2.cardboard
![image](https://user-images.githubusercontent.com/55203598/179570320-41f4afb2-3d54-4767-a6aa-f1f73e98d074.png)
![image](https://user-images.githubusercontent.com/55203598/179570345-9743c7df-63f4-4821-bd49-befec82f376d.png)
3. carnival (here it was already done)
![image](https://user-images.githubusercontent.com/55203598/179570241-286a6ab9-c051-4b2e-9c2c-66ea77d78ca5.png)
4.corn (here the left space is set by the padding bottom (`2rem`) for captions in splash figures, can we standardize it to `0.7rem` as in the other themes?)
![image](https://user-images.githubusercontent.com/55203598/179570469-2e2982aa-0eb5-415b-a3a0-d2913b529055.png)
![image](https://user-images.githubusercontent.com/55203598/179570518-8f084e9e-ff38-4c0d-8e05-592afd02ffed.png)
Can we keep it for all themes or is the margin bottom value to low?

**Comment by lwtchu** [comment]
@ajluk i think the v-space(2) looks nicer for the figure bottom. maybe set everything  around to 0.7em and then the bottom is 1.4?

**Comment by MartaSztuka** [comment]
#### PASSED
###### corn STATISTICS
![Screenshot from 2022-07-25 10-10-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f2983200-ad55-4748-a822-816764c52018)
###### carnival ANTROPOLOGY
![Screenshot from 2022-07-25 10-13-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5418098f-02e2-45e1-8b49-6ed46273bd32)
###### cardboard FINANCIAL ACCOUNTING
![Screenshot from 2022-07-25 11-05-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e31948d2-8ec4-4a74-81b5-01b21095ce2c)
###### cosmos PHILOSOPHY
![Screenshot from 2022-07-25 10-34-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/66a2d769-97a9-4fc5-82c1-11689581d77a)
