### ISSUE TITLE
Index name term reference

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4704]
There was a change made in Adaptarr for terms containing names to have term reference value set in `cxlxt:name` attribute instead of `'cmlnle:reference'. It needs to be supported in cookbook if possible for polish books which will utilize it in content:
![image](https://user-images.githubusercontent.com/55203598/171880716-54a3c38f-1d35-43c7-9db1-91ce298f086f.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-06-08 17-22-22](https://user-images.githubusercontent.com/47241114/172655079-dd2d8603-7f6c-4045-aef8-cab64264443e.png)
