### ISSUE TITLE
 Italicize all foreign elements in all books

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4721]
All `[data-type="foreign"]` spans need to be italicized, in Polish books additionally such elements are the wrappers for terms and these should be also italicized and unbolded: 
![image](https://user-images.githubusercontent.com/55203598/175040617-1df13e96-9d1f-4313-bb07-6b78e58b5502.png)

**Comment by ajluk** [comment]
Information for testing purposes. Screenshot for reference come from Mikroekonomia, but such markup can be also found in pl-psychology, pl-u-physics: 
![image](https://user-images.githubusercontent.com/55203598/175041771-115ea371-2ef2-4091-aedf-479c635c6d34.png)

**Comment by ajluk** [comment]
@Stackblocks I have assigned you to this issue because Marta is still unavailable, but it is not urgent so it can wait till the end of the sprint until she will be back, so she can then check Mikroekonomia as well. :relaxed:

**Comment by MartaSztuka** [comment]
#### PASSED
###### Mikroekonomia
![Screenshot from 2022-06-29 11-02-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/18bf997b-22ce-4625-a412-a46b2102dd97)
###### Psychologia
![Screenshot from 2022-06-28 16-08-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6606cbbe-4025-4521-adc2-f5a3df7acf02)
###### Fizyka 1
![Screenshot from 2022-06-29 10-41-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6620d173-562d-4417-9366-ce31fa501f24)
###### College physics
![Screenshot from 2022-06-28 17-30-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2f088cfc-ffd0-4640-956f-a6d8f40980ea)
###### Algebra and Trigonometry
![Screenshot from 2022-06-29 08-40-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4f7b1e32-fa4a-4007-a7e6-fde1a7155cf0)
