### ISSUE TITLE
AP Physics 2e: Test Prep for AP Courses Weird Page Breaks

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#4723]
# Brief Description of Scenario and Screenshots

During production for AP Physics 2e (due out 7/13) Wisewire flagged weird page breaks. They are all in the Test Prep for AP Courses sections. On the [PDF here](https://openstax-cops-artifacts.s3.amazonaws.com/college-physics-ap-courses-2e-latest-git-6232.pdf), they occur on PDF pages (NOT folio pages!) 214, 215, 632, 1045, 1046, 1048. Two screenshots attached.

![Screen Shot 2022-06-22 at 3 48 41 PM](https://user-images.githubusercontent.com/7863733/175133857-0db87230-27d2-4496-bd42-17323cb4e197.png)
![Screen Shot 2022-06-22 at 3 48 49 PM](https://user-images.githubusercontent.com/7863733/175133859-efc6c490-4cfa-47e0-a2af-798b29b3c7ea.png)

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.

# Acceptance Criteria

# Sample mark up if applicable
```
<!-- Please paste here. -->
```

# Location(s)
github openstax/osbooks- link: 
collection slug (if applicable):
chapter/section: 
surrounding text:

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-06-27 at 11.41.25.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3a0b363d-6ae3-4ce9-b0c9-be6b8c790547)

---
![CleanShot 2022-06-27 at 11.38.24.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/49d6277e-8736-4964-9d2d-c086aaa240f4)
