### ISSUE TITLE
marketing - new careers in marketing feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4724]
![Screen Shot 2022-06-22 at 4 25 04 PM](https://user-images.githubusercontent.com/11299125/175141274-c6f1bf2e-9848-4bb8-8f70-c7c31b70c551.png)

- Documentation #2737
- color option 1
- Class: `<note class="careers-marketing">`
- title: Careers in Marketing
- icon: [cardboard-outlook.svg](https://drive.google.com/file/d/1iNsVTe6ilyz8D36AJvIZ7gTzs8R94RwT/view?usp=sharing)
- test content: https://github.com/openstax/osbooks-ce-styles-test

**Comment by lwtchu** [comment]
Per the closed issue above, I think there's test content in the actual book now: https://github.com/openstax/osbooks-principles-marketing

**Comment by lwtchu** [comment]
@Stackblocks when you testy test can you show me the icon pls

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-07-04 15-38-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ed7065fe-8b87-4004-86e2-98bb614d835c)
