### ISSUE TITLE
exercise refactoring - modules without title links need bottom margin removal

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4725]
This issue will cover point 2 from https://github.com/openstax/cnx-recipes/issues/4720 to narrow the amount research and changes:

2. Modules with exercises without title links - we want exercises to stuck to each other
![image](https://user-images.githubusercontent.com/55203598/175248370-1a226143-abbe-4057-9a7d-624b5df7cfd0.png)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-07-06 at 13.31.33.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/61efae5c-454a-4108-9b48-0db3e4caa836)
