### ISSUE TITLE
organic chemistry - TOC table of contents

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4731]
Documentation: #4730 
Does not contain units

Please set base font to IBM Plex Serif. This is a new TOC documentation for carnival theme since we never had a card to document. I've updated some of the specs to reflect the cosmos theme sizing so that they'll match more.

**Comment by wilkus27** [comment]
@lwtchu To make sure, everything what has IBM Plex Sans in TOC documentation should be changed to IBM Plex Serif just in Organic Chemistry?

**Comment by lwtchu** [comment]
@wilkus27 
- 🤔 i think we can leave it as is. we can keep the base text as ibm plex serif (paragraphs and exercises)
- I think we can change it to all caps - I'll update the screenshot with what you have to bring it closer to the Cosmos theme if that's ok? Just to eliminate any inconsistencies since the two themes should be roughly the same

**Comment by wilkus27** [comment]
@lwtchu Ok, thank you :relaxed:

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-07-08 13-13-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/53eac177-3b76-4d40-828e-de2790ee43d1)
![Screenshot from 2022-07-08 13-15-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/de868075-414e-4929-b579-74df92d86259)
