### ISSUE TITLE
organic chemistry - headers

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4733]
Documentation #4732

Can we set the base font to IBM Plex Serif just for this title? Features, captions can still remain IBM Plex Sans and the headers can retain their style. Just the basal/base font to IBM Plex Serif

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/177554887-07c898c9-4872-45f0-9967-c5395854d0b7.png)

![image](https://user-images.githubusercontent.com/40228854/177554988-72ec9461-47d7-406c-b107-53fc16e7199f.png)

![image](https://user-images.githubusercontent.com/40228854/177555187-106df3f7-f7f6-4eef-8e05-879b4e61f3d8.png)

![image](https://user-images.githubusercontent.com/40228854/177555290-f786028b-2b5f-4f62-a3ce-7df7288c7b6a.png)

Is it ok? Also, styles were different then in documentation (font sizes and spacing), so my changes affects all books from Carnival. Are we ok with that?

**Comment by wilkus27** [comment]
@lwtchu Ok, thank you! :relaxed: 

About Index, yes it will be styled in another PR. Here I added styles only to the main title "Index".

**Comment by lwtchu** [comment]
Please test: Ochem, ap physics 2e and one other one you have strong feelings for

**Comment by MartaSztuka** [comment]
#### PASSED
###### ORGANIC CHEMISTRY
![Screenshot from 2022-07-08 13-17-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ba1eb07d-91e6-421f-b12e-e814c0f3ced5)

![Screenshot from 2022-07-08 13-17-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/594531ed-690f-4472-b962-f35ea3f12bf1)

![Screenshot from 2022-07-08 13-17-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/06108275-a816-4732-8ad2-4e65f502fc7a)

![Screenshot from 2022-07-08 13-17-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2eafd248-f3d8-4f6f-a33a-246806baf909)

![Screenshot from 2022-07-08 13-59-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9bd9f56f-7040-49af-ab47-49b41d33f538)


###### AP PHYSICS
![Screenshot from 2022-07-08 13-51-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b3f29ee3-d58b-4540-9a22-4dd1500a32e0)

![Screenshot from 2022-07-08 13-51-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c482d142-c337-4563-9078-3e5ab1bc2620)
![Screenshot from 2022-07-08 13-57-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1770cec2-8dbf-48d6-8c0e-42b1e7d694d2)


![Screenshot from 2022-07-08 13-52-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/10b04421-b623-4170-be2d-7ce3f8479810)

###### ANATOMY AND PHYSIOLOGY 
![Screenshot from 2022-07-08 13-54-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c48f8d1c-5512-4f72-84a6-3a794151cb59)
![Screenshot from 2022-07-08 13-57-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2a377842-4fb7-4881-95b1-117cca4ff47c)


![Screenshot from 2022-07-08 13-54-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/017aab05-e29e-4975-9dea-c3bf9e2ec711)

![Screenshot from 2022-07-08 13-54-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8165aa3c-9a30-4a2d-b04d-c37de4c7ef7d)
