### ISSUE TITLE
organic chemistry - splash image

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4734]
documentation: #1075

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-07-08 13-13-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/240cd2e3-7071-4c3e-b917-60038f40008c)

**Comment by Stackblocks** [comment]
![CleanShot 2022-07-18 at 17.24.45.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/cc91859f-7b19-4fcb-b6e9-bb493837dfac)
