### ISSUE TITLE
organic chemistry - learning objectives

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4740]
documentation #1077
use the bulleted list

there is only one example right now. we are still trying to confirm the existence of LOs but since they're standard, we should apply to the theme

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-07-08 13-03-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f5d6db47-ced6-4f33-946e-a5691f4c876c)
