### ISSUE TITLE
testing to validate access for mwoline

### ISSUE THREAD

**Issue by mwolinewisewire** [openstax/cnx-recipes#4744]
# Brief Description of Scenario and Screenshots

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.

# Acceptance Criteria

# Sample mark up if applicable
```
<!-- Please paste here. -->
```

# Location(s)
github openstax/osbooks- link: 
collection slug (if applicable):
chapter/section: 
surrounding text:

**Comment by openstaxalina** [comment]
closing -- test complete :-)
