### ISSUE TITLE
organic chemistry - worked examples

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4745]
Documentation: #1793

Title: Worked Example
Numbering: Yes
Subtitle in example: Yes
Paragraphs with titles for Strategy and Solution: Yes

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-07-08 16-46-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c9aebe1c-d375-4cd1-8be3-9b1dcf5674a6)
