### ISSUE TITLE
organic chemistry - why this chapter? feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4748]
Documentation #4746
(Since creation, I made some minor tweaks to the specs - all caps title and reducing the subtitle size.)

Title: Why This Chapter?
Subtitle: None
Color: G2:`#1E9575`

**Comment by wilkus27** [comment]
@lwtchu This note is first element after Introduction title. In current styles this title is displayed in line with introduction content, so this is how it looks:

![image](https://user-images.githubusercontent.com/40228854/177776193-eedbbf4d-25a4-4a5a-a2b3-ce6049418957.png)

Does it gonna be changed in content? Or is it a final version and I should change styles (display **Introduction** above the note)?

**Comment by lwtchu** [comment]
@wilkus27 we might have to move the introduction - is that possible or do we need to treat it like a regular header?

**Comment by wilkus27** [comment]
@lwtchu I moved Introduction title up and this is how it looks:

![image](https://user-images.githubusercontent.com/40228854/177985266-0f3ccf5d-9edf-465b-948c-deff67f94b5b.png)

**Comment by lwtchu** [comment]
@wilkus27 could we have it match the module title design?  like the h1 in here #4732

**Comment by wilkus27** [comment]
@lwtchu Title "Introduction" is a H2 header. This is how it looks with regular H2 styles:

![image](https://user-images.githubusercontent.com/40228854/178251501-8ce2bdc1-3975-47e0-8e30-bf512eb9f36f.png)

Should I apply H1 specs anyway?

**Comment by wilkus27** [comment]
### Information for tester

New specs from documentation are applied to all books from Carnival.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-07-12 16-19-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dedeb517-0834-4541-a467-0e257972f1a1)
