### ISSUE TITLE
organic chemistry - something extra feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4750]
Documentation #3966

Title: Something Extra
Subtitle: Yes in `<title>`
Class: `class="something-extra"`
Color: B1: `#0DC0DC`
Icon: [carnival-microconnections.svg](https://drive.google.com/file/d/1z3nm9jswlV-pNb5v7UOlFwXZIAY1SKbZ/view?usp=sharing)

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/177956542-149a2abe-b813-471d-9b2a-10a23ec6b5fa.png)

In subtitle some of the words are bold, because they are terms. Is it intentional?

![image](https://user-images.githubusercontent.com/40228854/177956800-a24eca4a-a617-4a72-b078-dda6e2b7f247.png)

**Comment by wilkus27** [comment]
@lwtchu It looks good now :relaxed: Thank you!

**Comment by wilkus27** [comment]
### Information for tester

New specs from documentation are applied to all books from Carnival.

**Comment by MartaSztuka** [comment]
@wilkus27 in Biology there is still bold title in note 
![Screenshot from 2022-07-12 17-09-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2a230977-2b3c-4789-9b23-ece7fefb8d5c)

#### PASSED
##### ORGANIC CHEMISTRY
![Screenshot from 2022-07-12 17-07-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fdb94c47-5de2-47a8-b3ef-9b28f369b5f2)

##### ANATOMY

![Screenshot from 2022-07-12 17-15-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5f42efc0-b62e-4a69-80b3-6ea893fd5900)

**Comment by wilkus27** [comment]
I tried to check Biology, but I'm getting error:

![image](https://user-images.githubusercontent.com/40228854/178979961-f087ea42-83c6-4bb8-964e-9894b644b2fb.png)

It's on the `git-validate-xhtml-mathified` step, so I can't generate PDF, but I checked baked html and note looks good there:

![image](https://user-images.githubusercontent.com/40228854/178980200-483fde76-ddc1-4793-97bb-cf49be72ca97.png)

**Comment by lwtchu** [comment]
@wilkus27 ill check on the exercises. we might need to create a separate card for the biology one - but we can also test on corgi once it goes out 🤔
