### ISSUE TITLE
organic chemistry - working problems

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4751]
Documentation #4746

Title: Working Problems
Subtitle: None
Color: R2: `#B10069`

**Comment by wilkus27** [comment]
### Information for tester

New specs from documentation are applied to all books from Carnival.

**Comment by MartaSztuka** [comment]
#### PASSED
##### ORGANIC CHEMISTRY
![Screenshot from 2022-07-12 17-17-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e4f3334d-851f-4c5a-9f3c-3d3c296b041d)
##### ANATOMY
![Screenshot from 2022-07-12 17-19-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8aa4e388-e445-477a-ad0a-2a74a4824b92)
##### BIOLOGY
![Screenshot from 2022-07-12 17-20-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e7049276-8e9e-4fa6-88b9-457c25fa6514)
