### ISSUE TITLE
organic chemistry - end of chapter

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4754]
# Key Terms
- uses `<glossary>`
- documentation #4752
- set to two column

# Summary
- `class="summary"`
- documentation #4753
- divided by sections/module? NO
- set to two column
- test content contains a feature box

# Summary of Reactions
- `class="summary-reactions"`
- should be a regular section with a list
- divided by sections/module? NO
- set to 1 column 
- not present in every section

# Exercises
- Covered here #4749 

# Practice Your Scientific Analysis and Reasoning
- `class="practice-scientific"`
- should be a regular section with another nested section
- divided by sections/module? NO
- set to 1 column
- not present in every section

**Comment by MartaSztuka** [comment]
#### PASSED
###### Key Terms
![Screenshot from 2022-07-27 17-29-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d38dce98-93ed-4e8b-a11a-4e5cab6edcf9)
###### Summary
![Screenshot from 2022-07-27 17-29-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6aeda6ff-1eda-4e5e-873e-a6ea72713c36)
###### Summary Reactions
![Screenshot from 2022-07-27 17-33-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/17327d3f-c008-4913-a253-75f8d0e08bfd)
###### Problems
![Screenshot from 2022-07-27 17-29-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fcf9192c-138e-4a7b-a7fa-126903cb31c6)
###### Visualizing Chemistry
![Screenshot from 2022-07-27 17-34-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/10679990-cc7c-4518-9158-31462802f464)
###### Additional Problems
![Screenshot from 2022-07-27 17-35-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fb3d2e40-468e-4b09-9e82-da237328db0c)
###### Practice Your Scientific Analysis and Reasoning
![Screenshot from 2022-07-27 17-36-54.png]

**Comment by lwtchu** [comment]
@Stackblocks i added this to p.p since the change got merged late? we can test when it gets to corgi
