### ISSUE TITLE
organic chemistry - index styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4756]
#4755 - please add indentation for 2+ line (hanging indent)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-07-08 at 13.33.48.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/fafd58e5-e6e6-4592-8916-1dce8a34b6a6)

![CleanShot 2022-07-08 at 13.50.48.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7df4bf7b-7127-482f-9f02-9db0893fd606)
