### ISSUE TITLE
organic chemistry - answer key

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4758]
documentation #4757

**Comment by Stackblocks** [comment]
Answer needs to be inline with question number. Currently it has  each item on a new line, i.e.
```
Question Number
Subquestion
Answer
```

![CleanShot 2022-07-26 at 15.19.13.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/54b69ad9-8b7f-4ae6-a572-a767df1388d6)

**Comment by wilkus27** [comment]
### Information for tester

Solutions from injected exercises were not styled in Carnival up to this moment. Not sure if it's because they're not exist in other books or it was missed. Changes have an impact on `ap-physics-2e`, `chemistry`, `college-physics-2e`, `pl-u-physics`, `u-physics`.

**Comment by MartaSztuka** [comment]
#### PASSED
###### ORGANIC CHEMISTRY
![Screenshot from 2022-07-29 14-05-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5ffd43e1-ab16-4715-825f-438e2dee4f91)
###### AP PHYSICS
![Screenshot from 2022-07-29 14-34-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/be147100-605f-4515-bda7-df87aaf7ca40)
###### COLLEGE PHYSICS
![Screenshot from 2022-07-29 14-59-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/eb0a437d-dbb4-457a-81d2-a714f04db83b)
###### FIZYKA 1
![Screenshot from 2022-07-29 15-37-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/52068bfc-5973-4d5b-875e-2c31afa4e14d)
