### ISSUE TITLE
Marketing Theme - Request for answers formatting in Answer key section

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4759]
We have received the below feedback from customer. Kindly check and update the below one.

**The answer key contents should read like “1. c. Complex buying ….” Similarly “2. b. Marketing stimuli …” etc.**

**What is appearing:**
![thumbnail_image006](https://user-images.githubusercontent.com/86622862/176592088-522c0620-d3c7-4e52-9be5-718261e41623.png)

**The Expectation:**
![thumbnail_image007](https://user-images.githubusercontent.com/86622862/176592112-915fd4a7-9c33-410a-9614-be2179a3c4b8.png)

Sample output link. [https://openstax.org/books/introductory-business-statistics/pages/13-solutions]

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-principles-marketing
chapter/section: Chapter 3/Section 1
surrounding text: It’s time to check your knowledge on the concepts presented in this section.

**Comment by lwtchu** [comment]
# Acceptance Criteria

Can we keep the period? I'm not sure if we're tossing it out in the PDF... and it goes through to web?

**Comment by srm-openstax** [comment]
We don't put period in CNXML file. So didn't show the period in both output (PDF and Webview). Answer key section was generated automatically, based on the knowledge check section. Please find the below PDF view & Webview links.

**PDF view:** https://openstax-cops-artifacts.s3.amazonaws.com/principles-marketing-latest-git-6269.pdf
**Web view:** https://rex-web.herokuapp.com/books/2731eee8-0eb1-4d80-ae83-01b4af642ff6@26d5641/pages/chapter-3?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20220622.165524

**Comment by lwtchu** [comment]
@srm-openstax the acceptance criteria was for the developers, this will have to be a code fix

**Comment by srm-openstax** [comment]
@lwtchu In the Web View, there is another punctuation issue that must be fixed.  There is an extra space between every question number and first period that must be deleted.

![thumbnail_image](https://user-images.githubusercontent.com/86622862/179896914-9d7a1820-4280-4d71-b2bb-7874b2c6d30a.png)

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now in PDF

![image](https://user-images.githubusercontent.com/40228854/179980754-3c049c7f-d234-4c57-b925-ffe54cf6f652.png)

About problem from above (space between number and dot), there should be created separate card for REX team.

**Comment by lwtchu** [comment]
@wilkus27 i deleted my old comment cause I got confused. I'll make a separate card for the spacebut that in the pdf looks good

**Comment by lwtchu** [comment]
@wilkus27 i'll add this to the other card I just created so we can discuss there thank you :)

**Comment by Stackblocks** [comment]
- [x] Punctuation is showing OK both after the number and after the answer letter.

![CleanShot 2022-07-21 at 13.57.32.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3bef72f0-4b32-4cc4-bb93-caa36b4ac843)
