### ISSUE TITLE
marketing - careers in marketing icon update

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4760]
I removed the weird white bar on the binoculars in the original icon. Something in the SVG didn't render properly as it made its way to the PDF. Please reupload a new icon

https://drive.google.com/file/d/1iNsVTe6ilyz8D36AJvIZ7gTzs8R94RwT/view?usp=sharing

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/179207677-a32694ed-f8dd-4124-a94c-bfbd9059b482.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-07-18 10-53-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9ff08c09-b93b-42a8-b652-ea920ac1389c)
