### ISSUE TITLE
College Physics exercise link anchor text failing

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4761]
<img width="361" alt="Screen Shot 2022-07-05 at 11 13 58 AM" src="https://user-images.githubusercontent.com/1895432/177373234-e7fa0f6f-670e-47c5-8687-0061cda821b0.png">

# Brief Description of Scenario and Screenshots
These exercise links should both have autogenerated anchor text for exercise 16 in this section.

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
it's all exercise links. BUT NOT IN AP PHYSICS RECIPE. THEY'RE FINE THERE
# Acceptance Criteria

# Sample mark up if applicable
```
<!-- Please paste here. -->
```

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-college-physics-bundle
collection slug (if applicable): college-physics-2e
chapter/section: 3.3, 3.5, a bunch more
surrounding text: Solve the following problem using analytical techniques: Suppose you walk 18.0 m straight west and then 25.0 m straight north.

**Comment by lwtchu** [comment]
Checked with Ryan. We should be pulling an older commit. Here is the one from the day before the content hack https://github.com/openstax/osbooks-college-physics-bundle/tree/cbbaf2ba21e3dd8afb90abbf35ce6e0e4100d0dd we will revert the content back once we have fixed things

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-07-11 at 16.27.02.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/08beaca0-25a4-4a13-8a72-9fc284318cb5)
