### ISSUE TITLE
college physics / ap physics 2e - bold para titles in exercises

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4763]
# Brief Description of Scenario and Screenshots

![image](https://user-images.githubusercontent.com/11299125/177612825-721079d3-1ae3-41b2-ac1a-46f18951b158.png)

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
Yes

# Acceptance Criteria
The para title ("Unreasonable Results" in the screenshot) is bolded. 

# Sample mark up if applicable
```
<exercise id="fs-id3091745" type="problems-exercises">
<problem id="fs-id1446513">
<para id="fs-id2446920"><title>Unreasonable Results</title></para>
<para id="fs-id986894">The relatively scarce naturally occurring calcium isotope <m:math><m:mrow>
<m:msup><m:mrow/><m:mn>48</m:mn></m:msup>
<m:mtext>Ca</m:mtext>
</m:mrow>
</m:math> has a half-life of about <m:math><m:mrow><m:mn>2</m:mn><m:mo>×</m:mo><m:msup><m:mn>10</m:mn><m:mn>16</m:mn></m:msup><m:mspace width="0.25em"/><m:mtext>y</m:mtext></m:mrow></m:math>. (a) A small sample of this isotope is labeled as having an activity of 1.0 Ci. What is the mass of the <m:math><m:mrow>
<m:msup><m:mrow/><m:mn>48</m:mn></m:msup>
<m:mtext>Ca</m:mtext>
</m:mrow>
</m:math> in the sample? (b) What is unreasonable about this result? (c) What assumption is responsible?</para></problem>
</exercise>
```

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-college-physics-bundle
collection slug (if applicable): college-physics-2e ; ap-physics-2e
chapter/section: multiple
surrounding text:

**Comment by wilkus27** [comment]
@lwtchu This is what it looks now:

![image](https://user-images.githubusercontent.com/40228854/180177703-2b7c9c5c-632f-45c3-9edb-48023a6449b6.png)

I applied bold to problem title in all Carnival books. Is that ok? Or it's better to apply this only to physics?

**Comment by lwtchu** [comment]
@wilkus27 beautiful :hearts:

**Comment by wilkus27** [comment]
### Information for tester

This change is applied to all books from Carnival (but I'm not sure if such titles appear anywhere else :thinking: )

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-07-21 at 15.25.30.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5c695724-2b6f-4d2d-81f3-19b9c1f963ab)
---
![CleanShot 2022-07-21 at 15.25.53.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/dd049199-c08a-4334-b8e3-dddc6e67a9f1)
---
![CleanShot 2022-07-21 at 16.32.35.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/69219853-9a8d-4520-8f85-90ea59a50f73)
