### ISSUE TITLE
content switch iframe link pdf vs rex format issue

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4765]
![Screen Shot 2022-07-11 at 4 05 15 PM](https://user-images.githubusercontent.com/11299125/178358357-af8de8eb-3a91-49e0-a000-0bb844ff6157.png)

Keep screenreader stuff separate - focus on iframe content behavior. 

# Location(s)
https://github.com/openstax/osbooks-writing-guide/tree/enabled-sims
https://github.com/openstax/osbooks-college-physics-bundle - important to do for college physics before fall

**Comment by lwtchu** [comment]
Phil's notes below

# Decision

This tries to align to terms in [CSS Media Query](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries)

We'll switch based on the media. Options include:

- `screen`
- `print`
- `screenreader`

Example XHTML markup:

```xml
<div data-type="media-options">
    <p      data-media="print screenreader">This interactive does the following things....</p>
    <iframe data-media="screen" src="https://PHET"/>
    <p      data-media="print"><a href="REX...">I am a link</a></p>
</div>

<!-- The double-underline -->
<u data-type="emphasis" data-effect="double-underline">
  <span data-media="screenreader">double underline</span>
  leave
  <span data-media="screenreader">end double underline</span>
</u>
```

And corresponding CSS in REX and the PDF:

```css
/* REX web */
@media screen {
  [data-media~=screenreader] { /* move offscreen */ }
  [data-media]:not([data-media~=screen],[data-media~=screenreader]) { display: none }
}

/* REX PDF */
@media print {
  [data-media]:not([data-media~=print]) { display: none }
}

/* PDF */
[data-media]:not([data-media~=print]) { display: none }
```

**Note:** The only change to the double-underline is replacing the attribute `data-screenreader-only="true"` with `data-media="screenreader"` 

---
---
---
---
---
---
---
---
---
---


# Background

We have a few places where we want the content to have multiple formats and, depending on how the content is being rendered, want to choose which format to show or whether to hide a format.

Here are a few ways we render our content:

1. REX Web
1. REX Ctrl+P PDF
1. REX Screenreader ("sr-only")
1. Downloaded PDF
1. Printed PDF (future?)
1. ePub3 (future?)
1. ePub2 (future?)


Here are alternative formats we may choose to render:

1. Interactives:
    1. `<iframe>` (for REX Web)
    1. link to REX (for Downloaded PDF)
    1. QR code (for Printed PDF)
    1. screenshot image (for REX Ctrl+P PDF)
1. Math:
    1. MathML markup (for ePub3)
    1. Math SVG images (for PDF and ePub3 fallback)
    1. Math PNG images (for ePub2)
1. Move but don't remove:
    1. Shift screenreader-only text off the visible part of the page (REX Web, Downloaded PDF)
1. Remove in some renderers:
    1. Hide chapter outlines (REX Web, REX Ctrl+P PDF)

**Note:** some of these formats like QR code & Math SVG/PNG images could be done after the common-format content has been created. They were added in here to help fill-in options but might just cause **over-designing** a solution.


# Prior Art (ePub3)

Here's how the [ePUB spec supports alternate formats](https://idpf.org/epub/30/spec/epub30-contentdocs.html#sec-xhtml-content-switch). It only allows readers to choose based on this `required-namespace` attribute.

```xml
<epub:switch id="cmlSwitch">
   
   <epub:case required-namespace="http://www.xml-cml.org/schema">
      <cml xmlns="http://www.xml-cml.org/schema">
         <molecule id="sulfuric-acid">
            <formula id="f1" concise="H 2 S 1 O 4"/>
         </molecule>
      </cml>
   </epub:case>
   
   <epub:default>
      <p>H<sub>2</sub>SO<sub>4</sub></p>
   </epub:default>
   
</epub:switch>
```


# Option: Two Options

For the immediate issue we could just have 2 for the renderer to choose from: "static" or "dynamic". It could look like this:

```xml
<!-- static/dynamic only has 2 options -->
<div data-type="if-else(?)">
    <p      data-case="static"  ><a href="REX...">I am a link</a></p>
    <iframe data-case="dynamic" src="https://PHET"/>
</div>
```

**sr-only:** This doesn't seem to address the screenreader-only problem

**Chapter Outline**: Chapter Outlines could be shoehorned by being in the `data-case="static"` section but then would unexpectedly reappear in the REX Ctrl+P PDF rendering


# Option: Switch element

We could wrap the options in a switch.

The names could be switch/case or alternatives/option, or ???.

```xml
<div data-type="switch">
    <p      data-case="link"   ><a href="REX...">I am a link</a></p>
    <iframe data-case="iframe" src="https://PHET"/>
    <!-- The following are maybes: -->
    <p      data-case="qr"     ><img src="qr.png"/></p>
    <audio  data-case="audio"  src="./reaction.mp3"/>
    <video  data-case="video"  src="./reaction.avi"/>
</div>
```

Adding a class on the parent element allows renderers to choose using CSS:

```xml
<div data-type="switch" class="has-link has-iframe has-qr">
    <p      data-case="link"   ><a href="REX...">I am a link</a></p>
    <iframe data-case="iframe" src="https://PHET"/>
    ...
</div>
```

```css
/* Now, CSS is able to show/hide whichever element they want */
.has-iframe :not([data-case='iframe']) { display: none; } /* REX-web */
.has-qr     :not([data-case='qr'])     { display: none; } /* REX-PDF */
```

**sr-only:** Not sure how this would be marked up yet

**Chapter Outline:** Chapter Outlines could use this method but it is unclear what the `data-case="???"` would be



# Option: Media element

Instead of inventing a new "switch" element we could just use the existing CNXML `<media>` element (see [Docs](https://legacy.cnx.org/eip-help/media)).

The `<media>` element allows children inside it and already sort of acts like alternatives that a renderer chooses from.

With this option, any enki step that adds an option (like cookbook does when it encounters an iframe and adds a link to REX) would update the class attribute on the media element and add the option as a child element. The markup ends up looking just like the "switch" option above and can use CSS to style.

```xml
<div data-type="media" class="has-link has-iframe has-qr">
    <p      data-case="link"   ><a href="REX...">I am a link</a></p>
    <iframe data-case="iframe" src="https://PHET"/>
    <!-- The following are maybes: -->
    <p      data-case="qr"     ><img src="qr.png"/></p>
    <audio  data-case="audio"  src="./reaction.mp3"/>
    <video  data-case="video"  src="./reaction.avi"/>
</div>
```

**sr-only:** Not sure how this would be marked up yet

**Note:** Chapter Outlines would need to be solved in a different way


# Option: media/switch Hybrid

Since the definition of `<media>` and `<switch>` is the same we could use `<media>` most of the time and `<switch>` for elements like the Chapter Outline that are not a "type of media" per se.

**Comment by lwtchu** [comment]
@kswanson33 i think that's it for now - do we want to do screen readers separate or together?

**Comment by Stackblocks** [comment]
@kswanson33 Can you provide some additional detail on what i'm looking for when testing this? I've generated English Comp using the branch content and i'm getting the same thing in the PDF and the rex-linked output and i'm not sure if that's working as expected or if I should be seeing a difference there.

![CleanShot 2022-07-25 at 14.57.23.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3d3f17bb-93bb-4469-b620-b8175d738f12)

---

![CleanShot 2022-07-25 at 14.56.43.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/2b5f34d4-14a4-4050-91ce-4b6a381a9431)

**Comment by kswanson33** [comment]
Changes are less visual for this: 

- Iframes & links should have an HTML markup change. Iframes should no longer be hidden by an `iframe { display: none; }` style but instead a `[data-type="switch"] > :not(data-media~=print) { display: none; }` selector. Behavior for iframe should be identical to how it was before.
- Screenreader spans should be styled by a `data-media~=screenreader` selector instead of a `data-screenreader-only=True` selector. Behavior for screenreader spans should be identical to how they were before.
- Rex view has not yet implemented styles changes, I believe. Both the iframe and the link will be visible on the web view. Ultimately the link will be hidden and the iframe will be shown.

A good example of content to test on would be writing guide, since it has both iframes and screenreaders. There's a branch where the iframes aren't commented out, I think.

**Comment by Stackblocks** [comment]
All of the component parts are present and looking good! Thanks for the clarification. Moving this over to CORGI testing.

![CleanShot 2022-07-27 at 16 38 35](https://user-images.githubusercontent.com/12678235/181377420-96e20502-098c-4c98-ae7c-6c40f79cc667.png)
![CleanShot 2022-07-27 at 16 38 20](https://user-images.githubusercontent.com/12678235/181377431-b2089c6e-417b-4227-b119-a0ca7ded166f.png)
![CleanShot 2022-07-27 at 16 39 21](https://user-images.githubusercontent.com/12678235/181377448-7bc72281-56d8-4de2-beeb-062a253f6255.png)
![CleanShot 2022-07-27 at 16 39 46](https://user-images.githubusercontent.com/12678235/181377457-20239640-032e-454e-b38c-b84b1c214a07.png)
