### ISSUE TITLE
rex bug - unit pages need "unit" title in page title so remove redundancy in cookbook

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4770]
# Brief Description of Scenario and Screenshots
We did some of this here https://github.com/openstax/cnx-recipes/issues/4316 but the lack of "Unit" in the actual page title is breaking Rex since the slug is the exact same as the chapter 1 introduction. ([slack thread](https://openstax.slack.com/archives/CH5514N57/p1657730318270319))

Since we cannot inject or modify  page titles with ease for module/page titles, we need to just set by hand and remove redundancies. 

What breaks REX:
![Screen Shot 2022-07-13 at 12 39 20 PM](https://user-images.githubusercontent.com/11299125/178796433-dcda6caf-f6e2-496c-a438-a6fe5b4026ff.png)

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
Yes

# Acceptance Criteria
![Screen Shot 2022-07-13 at 4 44 20 PM](https://user-images.githubusercontent.com/11299125/178842173-7bdadac9-5237-4a13-9285-e498f70bc6e4.png)
![Screen Shot 2022-07-13 at 4 45 34 PM](https://user-images.githubusercontent.com/11299125/178842216-ccafb233-df14-42c8-96fb-ffeca77c0268.png)
^ This intro page is fine; if we can remove it that's a nice to have. But we JUST need to remove the redundant Unit 1 in the TOC

The behavior is as desired in the webview
![Screen Shot 2022-07-13 at 4 44 30 PM](https://user-images.githubusercontent.com/11299125/178842374-d0338c74-ee74-4189-88da-60ba2afe99c7.png)

# Location(s)
github openstax/osbooks- link:  https://github.com/openstax/osbooks-writing-guide
collection slug (if applicable): writing-guide

also impacts Marketing https://github.com/openstax/osbooks-principles-marketing 
^^ waiting for content change for marketing

**Comment by ajluk** [comment]
@lwtchu This hit it look looks after hiding (adding `display: none`property) unit page link number `os-part-text` in styles in ToC: 
Writing Guide
![image](https://user-images.githubusercontent.com/55203598/180194469-d9f8c494-6b79-4ad9-85e8-5756df9cfafd.png)
Marketing
![image](https://user-images.githubusercontent.com/55203598/180194652-3868d85a-9d20-4771-97e2-7cee9228fb17.png)
Is it the desired look or should I changed something?

**Comment by lwtchu** [comment]
@ajluk :eyes: is it also possible to remove the 1

**Comment by ajluk** [comment]
@ Do you mean also just hide it in the pdf styles? If yes, yes it is possible :+1:

**Comment by ajluk** [comment]
@lwtchu Here is how it looks when the whole number is hidden: 
![image](https://user-images.githubusercontent.com/55203598/180396661-de418fc3-dc1a-430c-8eff-52b9d34568d4.png)
![image](https://user-images.githubusercontent.com/55203598/180396744-59337a6a-3da9-4b68-8083-04c78a44b1cd.png)

**Comment by lwtchu** [comment]
@ajluk yes just the pdf styles ⭐ amazing. beautiful

**Comment by MartaSztuka** [comment]
#### PASSED
##### Writing guide
![Screenshot from 2022-07-26 10-02-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/57bbdec2-5108-4618-9df7-4cadf31416c6)
##### Marketing
![Screenshot from 2022-07-26 10-04-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8c47d929-f5a2-41aa-849b-0e9cece36173)
