### ISSUE TITLE
Marketing Theme - Unit Opener Page Styling Change Request

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4771]
Copying in Comments from below

# Request 
In the PDF and Web views, request the words "Unit Introduction" be bolded and in the same font color (blue/grey) as the words "Unit 2" in the header above.  (Please apply this design request to all three unit openers, if possible.) Thank you.

Also please insert extra space/line between "Unit Introduction" and paragraph (starting with "Welcome to").

![thumbnail_image004](https://user-images.githubusercontent.com/86622862/179911989-80570f68-9534-418d-908e-9b919d17982e.png)

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-principles-marketing
chapter/section: Unit 2
surrounding text: Welcome to Unit 2 of Principles of Marketing.

# Acceptance Criteria
- [ ] add padding between unit introduction and the paragraph - can we check what the padding is in Writing Guide?
- [ ] Bold the Module Title (Unit Introduction), set to Roboto Condensed and set to B2: `#344456`

**Comment by srm-openstax** [comment]
@lwtchu We have received the below correction from customer. Kindly check and do the needful.

**This should be in bold and the same color font as Unit 2 and background dark blue/gray color..  If necessary, please raise ticket.  [See Writiing Guide with Handbook as an example.]**

![Unit_Opener_output](https://user-images.githubusercontent.com/86622862/179664258-e14b8576-e5bd-490e-9b64-1a2de2e0b56d.png)

**Comment by ireinbergs** [comment]
SRM Editorial clarification: (Disregard the unclear Writing Guide reference.) In the PDF and Web views, request the words "Unit Introduction" be bolded and in the same font color (blue/grey) as the words "Unit 2" in the header above.  (Please apply this design request to all three unit openers, if possible.) Thank you.

**Comment by ireinbergs** [comment]
Also please insert extra space/line between "Unit Introduction" and paragraph (starting with "Welcome to").

**Comment by wilkus27** [comment]
@lwtchu This is what it looks now

![image](https://user-images.githubusercontent.com/40228854/180735386-7be59866-d3e4-4ff2-93f7-468877625fcf.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-07-25 11-18-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e2304bc2-d989-4125-b4dd-830df757f9e6)
