### ISSUE TITLE
Marketing Theme - Embedded video links in PDF view

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4772]
We have coded embedded video links are as per the tagging legend. But, incorrect links are generated in output PDF. We faced this issue in throughout file. Kindly check and resolve this issue.

**Tagging Legend:**
![iframe-tagging-legend](https://user-images.githubusercontent.com/86622862/178906276-1beaabe8-f803-4499-bd50-f30fc1a968a1.png)

**CNXML:**
![iframe-cnxml](https://user-images.githubusercontent.com/86622862/178906807-13696110-2825-4590-b8d2-add21f5ba959.png)

**Short Link:**
![iframe-short-link](https://user-images.githubusercontent.com/86622862/178906364-3e7b4cd5-bd08-4cbb-8d6c-a0c848b8125c.png)

**PDF View:**
![Iframe-pdf](https://user-images.githubusercontent.com/86622862/178907260-bc3d902d-1716-435a-a6a4-f19832b8470f.png)

**Web View:**
![iframe-web-view](https://user-images.githubusercontent.com/86622862/178906399-3ca4fcd6-1b1c-4e03-80f4-da3bcecc8ce9.png)

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-principles-marketing
chapter/section: Chapter 3/Section 2
surrounding text: This humorous video from

**Comment by lwtchu** [comment]
@srm-openstax This is by design so users in the PDF can go to webview to view the embedded content.

**Comment by srm-openstax** [comment]
@lwtchu We have received the below feedback from customer.

**it seems like the "Click to view content" links are not working in the web view either.** 

![image](https://user-images.githubusercontent.com/86622862/179339334-c7e80be1-5964-439b-810c-93de48aad83f.png)

Kindly check and advise.

**Comment by lwtchu** [comment]
https://www.opengui.de/known-book-production-issues - I've added the issue here with the future behavior of the iframes. Let me know if you have any questions.

**Comment by srm-openstax** [comment]
We have received the below feedback from editorial team. Kindly check and resolve this issue.

**The links in the PDF don’t go to the Web view.
In the most recent Ch. 19 (former Appendix) PDF, there are only two videos – one link goes to a CNN news website with a video, and the other goes here:**

![thumbnail_image](https://user-images.githubusercontent.com/86622862/189805246-5af67d91-1367-4da5-8c72-87c94e795491.png)

**I also clicked through about 5 videos in the latest version of Ch. 4 PDF (currently with production) and same error issue.**

**Comment by srm-openstax** [comment]
Sorry for the inconvenience. Just now, we have received the below information from customer. So, we have closed this ticket. Thanks for your support.

**Please close this ticket as we received information from customer technical team that these links will work once full book is published online.**
