### ISSUE TITLE
Polish books - figure title

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4774]
Change figure title `Rysunek` to `Ilustracja` in all Polish books:

![image](https://user-images.githubusercontent.com/40228854/179535660-a51c4115-cfd8-409a-a082-2d62c8e0438b.png)

It should be changed also for all links to figures:

![image](https://user-images.githubusercontent.com/40228854/179536072-21a6d530-1536-4295-8789-136e4ab8a2c2.png)

**Comment by MartaSztuka** [comment]
#### PASSED
##### FIZYKA 1
![Screenshot from 2022-07-21 10-44-48](https://user-images.githubusercontent.com/47241114/180171425-3fbd65d3-6859-4dfe-b8db-8c6d6661344b.png)
##### FIZYKA 2
![Screenshot from 2022-07-21 11-29-03](https://user-images.githubusercontent.com/47241114/180180620-843d0016-df9e-430d-ae30-008eb4a0d3e3.png)
##### FIZYKA 3
![Screenshot from 2022-07-21 11-28-13](https://user-images.githubusercontent.com/47241114/180180387-7d7da90b-fec3-4ad9-9178-cb7be9f85be2.png)
##### PSYCHOLOGIA
![Screenshot from 2022-07-21 10-48-17](https://user-images.githubusercontent.com/47241114/180172263-6e623d02-43eb-4ec6-b971-f115da874580.png)
![Screenshot from 2022-07-21 10-47-36](https://user-images.githubusercontent.com/47241114/180172283-27d333f4-53b0-44b2-92eb-da4996ab4c4c.png)
##### MIKROEKONOMIA
![Screenshot from 2022-07-21 12-06-24](https://user-images.githubusercontent.com/47241114/180188765-b4a45a61-a496-4223-81c0-a1a68d4ef016.png)
