### ISSUE TITLE
Organic Chemistry - Table Caption

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#4776]
# Brief Description of Scenario and Screenshots
(Follow-up from https://github.com/openstax/cnx-recipes/issues/4741)

`Table Caption` should be in IBM Plex Sans per [the specs](https://github.com/openstax/cnx-recipes/issues/1080), is currently in IBM Plex Serif.

![CleanShot 2022-07-18 at 11.14.33.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/38ff8b1e-ce13-4d45-9590-29d87e6f0a06)
# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
Happens consistently throughout the book
# Acceptance Criteria
Table Caption text font is IBM Plex Serif
# Sample mark up if applicable
```
<span xmlns="http://www.w3.org/1999/xhtml" class="os-title" data-type="title">Ground-State Electron Configurations of Some Elements</span>
```

# Location(s)
- **github openstax/osbooks- link**: https://github.com/openstax/osbooks-organic-chemistry
- **collection slug**: organic-chemistry
- **branch**: design-chapter
- **chapter/section**: 1.1
- **surrounding text**: represent the number of electrons in a particular orbital.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-07-20 10-40-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1a77a564-5368-446f-ab1e-13e4db680f68)
