### ISSUE TITLE
create changelog.md for ce-styles repo

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4777]
# Brief Description of Scenario
please create a changelog doc for the ce-styles repo like the one in the cookbook repo. we'll start with this approach for the P.P sprint

**Comment by kswanson33** [comment]
+ update the ce-styles release docs to include a step for updating the changelog headers before merging the milestone branch

**Comment by lwtchu** [comment]
Whenever we do code freeze, make a new blank changelog.md - or sometime before we do code freeze.
