### ISSUE TITLE
Line return at every number in AP College Physics 2e answer key

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4778]
<img width="270" alt="Screen Shot 2022-07-19 at 2 33 01 PM" src="https://user-images.githubusercontent.com/1895432/179834942-5374b163-e2bb-453a-b750-34b22944c4a2.png">

# Brief Description of Scenario

Entire answer key has line return after every problem number.

# Acceptance Criteria

# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-college-physics-bundle
- **collection slug:** college-physics-ap-courses-2e
- **ref/branch:**
- **chapter/section:** answer key
- **surrounding text:** answer key

**Comment by lwtchu** [comment]
# acceptance criteria
the answer key should have the number be black and bold with the first line of the answer inline with the number

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![CleanShot 2022-07-25 at 16 21 20](https://user-images.githubusercontent.com/12678235/180877770-f02977bc-7f8d-45cc-8a2c-e32e7194c2ea.png)
