### ISSUE TITLE
iframe content link doesn't acknowledge registered trademark symbol or dash

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4779]
![image](https://user-images.githubusercontent.com/11299125/180012442-413f8a0f-7a23-474f-9d2f-4bee6273d957.png)

# Brief Description of Scenario
The link goes to https://openstax.org/books/college-physics-ap-courses-2e/pages/2-connection-for-ap-courses 

but it SHOULD go to 

https://openstax.org/books/college-physics-ap-courses-2e/pages/2-connection-for-ap-r-courses

There is an extra -r- in the link for the registered trademark logo ® since the title is `Connection for AP® Courses`

Similar issue here (scroll down)
https://openstax.org/books/college-physics-2e/pages/9-4-applications-of-statics-including-problem-solving-strategies 

link points to https://openstax.org/books/college-physics-2e/pages/9-4-applications-of-statics-including-problemsolving-strategies

but should have a dash between problem and solving

# Pattern of Occurrence 
every time

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-college-physics-bundle
- **collection slug:** college-physics-ap-courses-2e
- **ref/branch:** n/a
- **chapter/section:** 2.0 for the screenshot
- **surrounding text:**  Essential Knowledge 3.A.1

**Comment by lwtchu** [comment]
Maybe ask REX how they generate their URL/slugs?

**Comment by lwtchu** [comment]
sidelined for other big priorities (ochem)

**Comment by wilkus27** [comment]
@lwtchu Do you know if this is the only one case when we want to support special character? I made a fix just for this particular one, but I'm wondering if I should create some more general functionality?

**Comment by wilkus27** [comment]
@lwtchu Ok :+1: So I will leave my fix as is for now, and if we encounter problems with other symbols I will create more general solution.

**Comment by MartaSztuka** [comment]
#### PASSED
link points to:
https://openstax.org/books/college-physics-ap-courses-2e/pages/2-connection-for-ap-r-courses
![Screenshot from 2022-09-05 16-02-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9f080788-b3cf-4433-9e2a-f18b78f11380)

**Comment by lwtchu** [comment]
@MartaSztuka do you still have the pdf to test the https://openstax.org/books/college-physics-2e/pages/9-4-applications-of-statics-including-problem-solving-strategies link? just look for `including-problem` and see if there's a dash between problem and solving

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-09-15 13-27-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e825a947-1a17-4878-876d-9c18acfdfc0c)
