### ISSUE TITLE
organic chemistry - add red text to list of color text spans

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4783]
Similar to #4742 but please set text with this class `<span class="red-text">` to R1: `#C31427` 

https://github.com/openstax/osbooks-organic-chemistry/tree/Design-Chapter

Content: Figure 1.6 Shapes of the 2p

**Comment by wilkus27** [comment]
### Information for tester

`red-text` class appears in Figure 1.4, not Figure 1.6.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-07-22 at 11.56.49.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/053f417d-9d01-4bf0-9010-6da419a020db)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-07-25 09-26-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/99025fc5-c4e0-480a-8c92-228c7a316524)

![Screenshot from 2022-07-25 09-26-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c22457bc-9fd3-4bc1-a371-716ec1b1b378)
