### ISSUE TITLE
organic chemistry - change example title

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4784]
![Screen Shot 2022-07-21 at 9 39 48 AM](https://user-images.githubusercontent.com/11299125/180241766-9f5b5b83-c364-41b4-8552-b2b572e83db4.png)
Can we change "EXAMPLE" to "WORKED EXAMPLE"

Content: https://github.com/openstax/osbooks-organic-chemistry/tree/Design-Chapter

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/180406556-da1682ca-2825-4d38-98ea-da759a810da0.png)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-07-22 at 11.55.17.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4ddaa745-6947-4053-b1d9-c43e475567e5)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-07-25 09-28-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a7ea1d2a-7453-4292-9429-5aab59ef68dd)
