### ISSUE TITLE
organic chemistry - figure caption and title padding inconsistent

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4785]
![Screen Shot 2022-07-21 at 9 48 57 AM](https://user-images.githubusercontent.com/11299125/180244223-8c14d322-bf4e-40af-b2d1-0fde6479dba3.png)

Top image is the Introduction figure and the second is in a module.
Is there a way to make them consistent? Vendor's preference is the one in the Introduction module.

Content: https://github.com/openstax/osbooks-organic-chemistry/tree/Design-Chapter

**Comment by wilkus27** [comment]
@lwtchu additional space in a second figure is added by this component:

![image](https://user-images.githubusercontent.com/40228854/180447837-b27e6e5d-73e7-42e6-ac3a-e6130af97fbd.png)

It's not defined properly. Based on the name, it should affect only titles from paragraphs. I can't find any case to check why exactly we needed additional margin for such titles. Do you think we can remove this component totally? Or it's better to leave it just in case and fix its selector?

**Comment by lwtchu** [comment]
@wilkus27 #4763 < would it be because of theses para titles?

**Comment by wilkus27** [comment]
@lwtchu No, these para titles were styled just in exercises. This component is for para titles in regular pages. I'm wondering if it's a leftover. It's a very old component. I can't find first PR that adds it, but component name was changed two years ago in some cleaning up issue, so it was created even earlier.

**Comment by lwtchu** [comment]
@wilkus27 i think it's safe to remove then

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-07-27 17-27-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8e39eca3-e02e-46fa-b786-d44e0acb1fc5)
