### ISSUE TITLE
organic chemistry - spacing around span color text

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4786]
![Screen Shot 2022-07-21 at 9 56 32 AM](https://user-images.githubusercontent.com/11299125/180245880-33b73094-e677-4751-b02d-ed10f260ae25.png)

There's a tiny bit of padding around the color text - is it possible to  remove it so the comma and parenthesis flow like normal text if it were uncolored?

Content: https://github.com/openstax/osbooks-organic-chemistry/tree/Design-Chapter

**Comment by wilkus27** [comment]
I think it's the same problem as in https://github.com/openstax/cnx-recipes/issues/4780. Something is wrong with spans.
Another discussion that might be related: https://katalysteducation.slack.com/archives/C022NETP39N/p1658414894839379

**Comment by kswanson33** [comment]
https://openstax.slack.com/archives/C022NETP39N/p1658414894839379 OS link to discussion

**Comment by lwtchu** [comment]
locally upgrade nokogiri to 1.13 and see if it solves this issue

**Comment by ajluk** [comment]
This issue is caused by creating additional white spaces (new lines) between `os-caption` children during the figure caption baking: 
![image](https://user-images.githubusercontent.com/55203598/183452352-7150f4c7-2c1c-44f8-9d03-cbc9f07f6801.png)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![CleanShot 2022-08-19 at 16.27.11.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3d6c6f36-c88b-456e-9f5a-35c22a493c10)
