### ISSUE TITLE
Enable target labels in Mikroekonomia

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4787]
Enable auto creating target labels for introduction, non-intro modules and appendices for Mikroekonomia (pl-economics ) in cookbook.

**Comment by ajluk** [comment]
Screenshots for reference: 
The links can be found in Chapter 2 from section 2.1.
![image](https://user-images.githubusercontent.com/55203598/181227664-eff5a956-d1b2-41cf-870b-4f5f38a51fb1.png)
![image](https://user-images.githubusercontent.com/55203598/181227897-d5356bfa-d154-4738-914b-7ce65ca856ed.png)
![image](https://user-images.githubusercontent.com/55203598/181227994-c081974d-6b08-402a-834e-7f5755669482.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-08-08 13-08-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6dbc563e-90f3-4f04-b88b-f5012ae13f70)

![Screenshot from 2022-08-08 13-08-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d798f33a-b661-4c69-8d52-f5393240d179)
