### ISSUE TITLE
Organic Chemistry Alphabetical Multipart Questions

### ISSUE THREAD

**Issue by LostMojo** [openstax/cnx-recipes#4788]
Takes the original injected exercises in Organic Chemistry:

![Screen Shot 2022-07-25 at 2.12.32 PM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/4b71c69c-cdba-48a1-8894-a65d683a57fa)

and formats them in a way so that the overarching question has a number, and each subquestion has a letter.

Like so:

![Screen Shot 2022-07-25 at 2.17.00 PM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/734e6e75-ed9b-45f2-9637-e1791174760e)

![Screen Shot 2022-07-25 at 2.17.33 PM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/a71758dd-0f46-4b1e-b79d-71c08e2fa8fd)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-07-26 10-00-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7cde479f-5d79-409a-b69e-547021c3519d)
