### ISSUE TITLE
organic chemistry - enable emphasis effects on color text

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4789]
# Brief Description of Scenario
![Screen Shot 2022-07-27 at 2 36 17 PM](https://user-images.githubusercontent.com/11299125/181365036-4d2b50cb-7592-4276-b363-16fa77e67bb5.png)
Different lobes above have the span but also have `emphasis` on it. 

# Acceptance Criteria
"Different lobes" above should be bold in addition to having color text.

# Sample Mark-Up
```
<emphasis effect="bold"><span class="cyan-text">Different</span></emphasis> <emphasis effect="bold"><span class="red-text">lobes</span></emphasis> of <emphasis effect="italics">p</emphasis> and <emphasis effect="italics">d</emphasis> orbitals are often drawn for convenience as teardrops, but their actual shape is more like that of a doorknob, as indicated.
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-organic-chemistry/tree/Design-Chapter
- **collection slug:** organic-chemistry
- **ref/branch:** Design-Chapter
- **chapter/section:** 1.2
- **surrounding text:** different lobes (Figure 1.4)

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/182119571-134f86a3-823d-42d9-9959-40d37f90c84e.png)

It wasn't bold because in styles `font weight` was set to `normal`. I'm guessing that in a first book, for which colored text was created, we didn't want a bold. Is it ok, that I revert this property? Or are there books where it should stay `normal`?

My change affects `accounting`, `computer-science`, `finance`, `marketing` and `organic-chemistry`.

**Comment by lwtchu** [comment]
@wilkus27 ah i see - yeah it set it to bold  even without an emphasis tag. is there a way to make sure it's not bold if it doesn't have the emphasis tag

**Comment by wilkus27** [comment]
@lwtchu Do you have an example where it's not in emphasis tag? In all cases that I found in these books colored text is in `<strong>`

![image](https://user-images.githubusercontent.com/40228854/182532347-4371903a-03c1-4159-971b-852d2beb375a.png)

**Comment by lwtchu** [comment]
@wilkus27 ahhh - do you think we'll need to adjust the way it's done in accounting to make it say `<span class="red-text">` instead of `<emphasis class="colored-text">`?

**Comment by wilkus27** [comment]
@lwtchu Yes, I think it would be the best :+1:

**Comment by lwtchu** [comment]
@wilkus27 i'll move out a few sprint...need to figure out how to coordinate with content/rex/pdf 🤔

**Comment by lwtchu** [comment]
@wilkus27 let's make this change in the q.q. sprint - to remove the bold  suppressing. I'll open cards later to make it work for marketing/accounting

**Comment by lwtchu** [comment]
@Stackblocks this will affect accounting/marketing in that it'll make their red text bold. we will fix the tagging for those after this goes out to to prod

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-08-15 at 17.18.51.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/fe35015c-6573-430b-879a-bd86921d09ae)
