### ISSUE TITLE
organic chemistry - space savings in eoc problems (inline multipart questions)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4790]
![Screen Shot 2022-08-02 at 9 47 54 AM](https://user-images.githubusercontent.com/11299125/182403872-d2c3f344-717d-4317-9097-43c4e14e0329.png)
Similar behavior to this https://github.com/openstax/cnx-recipes/issues/2186, though not exactly the same.

Is there some way we can target the individual questions (`data-type="alphabetical-question-multipart"`) and move them inline? Or we can add a class to these?

Whoever is working on this -- we can talk it out and fiddle with the content.

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/182802797-06a05f35-a3af-4ec6-a6ac-59fd6296ea02.png)

Other example:

![image](https://user-images.githubusercontent.com/40228854/182802913-b7a85ac1-8a3d-477f-b05d-84a5e1baeb72.png)

Is it ok? Should I change something?

**Comment by lwtchu** [comment]
@wilkus27 is there a way to add a class on the items that we don't want to be in-line? just in case something doesn't flow right

**Comment by wilkus27** [comment]
@lwtchu If these cases are random, like there is not any specific rule for that (e.g exercises with images), then the best solution will be to put class on entire injected exercise:

![image](https://user-images.githubusercontent.com/40228854/182877723-1674c6f6-0c1b-45f2-a137-101bbaf3ed9c.png)

After that I can specify in styles to display in-line only MPQ from injected exercise that doesn't have class `not-inline` or something like that.

**Comment by lwtchu** [comment]
@wilkus27 testing `class="exercise-block"` on these two exercises OrgChem_C01_Q006 and OrgChem_C01_Q014

**Comment by lwtchu** [comment]
BLOCKED - class gets removed; need to talk to @philschatz and @kswanson33 on  Thursday about this 🤔

**Comment by philschatz** [comment]
To move the class attribute from the `<a href="#/ost/...">` element onto the exercise a change will need to be made to the template that injects the exercise [here](https://github.com/openstax/cnx-epub/blob/83fa4a1706d74d72ee2e48460e57c318a5210231/cnxepub/templates/exercise_template.py#L3-L5).

**Comment by wilkus27** [comment]
### Information for tester

Test the same way as here: https://github.com/openstax/cnx-recipes/issues/4819#issuecomment-1234349376

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-09-05 10-56-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3a368587-b690-4a4a-831c-cf684ab02e10)

![Screenshot from 2022-09-05 10-57-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/91095357-8843-45c1-87c8-598697af58e8)
