### ISSUE TITLE
organic chemistry - image placement for images within embedded exercises

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4791]
![image](https://user-images.githubusercontent.com/11299125/181365582-cce851a9-5de3-4a84-b8c7-465d1d2bc250.png)

related slack thread: https://openstax.slack.com/archives/C022NETP39N/p1658931884879559

Can we have the TOP of images aligned to the paragraph?

**Comment by lwtchu** [comment]
Put text in paragraph should make this easier.

**Comment by lwtchu** [comment]
Content should be done 🤔  we can work on this now

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now in content:

![image](https://user-images.githubusercontent.com/40228854/182644592-f4642f4e-4dea-4785-bdd9-cfe98f08eefc.png)

Image should be next to the para. Para should contain only text. Something like that:

![image](https://user-images.githubusercontent.com/40228854/182644799-c014a9f0-7b81-4eae-9f57-89de31a7ae98.png)

With that markup and changes from this issue https://github.com/openstax/cnx-recipes/issues/4790 that is how it'll look (more less; this is html, in PDF it might look a little bit different):

![image](https://user-images.githubusercontent.com/40228854/182645386-2880264b-1bdd-4095-8764-2e0448433aba.png)

Do we still want to have images aligned to the top of the paragraph or it can stay that way (under the paragraph)?

**Comment by lwtchu** [comment]
@wilkus27 i think we can wait until #4790 is done so i can see what might be helpful... 🤔 need to think about book wide design implications

**Comment by wilkus27** [comment]
@lwtchu Ok :+1: Actually inline exercises are ready. This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/182806349-20fe3054-1a3f-4252-a189-ea3576f3a36a.png)

If we want to operate with image alignment, content should be changed as I described above (image should be next to the para, not inside). I changed that locally in assembled file to see what it's gonna look like. This is the effect:

![image](https://user-images.githubusercontent.com/40228854/182806839-6e31f107-001c-4570-84a2-76654a42e050.png)

**Comment by wilkus27** [comment]
Test the same way as here: https://github.com/openstax/cnx-recipes/issues/4819#issuecomment-1234349376

**Comment by wilkus27** [comment]
### Update

This exercise has now `exercise-block` class, so it shouldn't be displayed in line.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-09-02 16-34-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3cc75fd3-b024-40fc-a930-1d60e15616a2)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-09-05 10-53-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c92ba0a3-1da7-483d-aa6b-0dec99a99c1e)
