### ISSUE TITLE
Mikroekonomia - Learning objectives

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#4793]
CEL DYDAKTYCZNY is missing in every module
![Screenshot from 2022-07-28 10-01-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6d463361-faa1-440e-81e7-545ab6d4c9ea)
As described here:
https://app.zenhub.com/workspaces/ce-styles-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/4566

**Comment by wilkus27** [comment]
Learning Objectives have different markup in books. In Legacy it used to be created in metadata within `<abstract>` tag which was generated to `div` with `data-type="abstract"` in xhtml. Some books contain just section with class `learning-objectives`:

```
<section class="learning-objectives" id="sect-00001">
      <title>Learning Objectives</title>
      <para id="para-00005">By the end of this section you should be able to</para>
        <list id="list-00001">
          <item>Lorem ipsum dolor sit amet.</item>
          <item>Consectetur adipiscing elit.</item>
          <item>This is to test learning objective feature if we add it.</item>
        </list>
    </section>
```
We need to make sure which markup is the best. Are we trying to standardize Learnig Objectives? If yes, in which way?

**Comment by wilkus27** [comment]
**Update**: we can't add section to Adaptarr and then keep other elements out of section, as it is done in american books:

![image](https://user-images.githubusercontent.com/40228854/182121065-2994035d-a571-4c01-9d02-226ffa28ad26.png)

To discuss: is it ok to add another way of creating Learning Objectives and treat it as a note in Polish books?

**Comment by wilkus27** [comment]
**Decision:** it should be done as a note.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-08-04 12-54-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5e7c20d7-e0ea-4244-9b05-976f9e6a64b1)

![Screenshot from 2022-08-04 12-56-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9656358d-12c0-4d34-90bd-f0b819e92deb)
