### ISSUE TITLE
by end of quarter? Add page type attribute to TOC elements

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#4795]
# Brief Description of Scenario
When the TOC goes to Rex, it gets disassembled into JSON. Certain attributes, including `class`, are lost. Rex wants better classification of page types on the TOC so that they don't have to infer it from the structure of JSON object. 

Add a page type attribute (TBD) to all TOC pages.

In conjunction with openstax/ce#1944

# Acceptance Criteria

TOC `<li>`s that correspond to page elements are classified by page type under the attribute `data-toc-target-page-type`.

# Location(s)
Content change to all books. Will not affect PDF appearance or styling.

**Comment by lwtchu** [comment]
pure cookbook issue - no styles. just adding page-type attribution in addition to the classes

**Comment by kswanson33** [comment]
possible attribute names:

- `data-page-type` (con: the elements being marked aren't the page elements, but the ToC links to the page elements)
- `data-toc-page-type`
- `data-link-to-type`
- something else?

**Comment by kswanson33** [comment]
`data-toc-target-page-type` wins 🎉

**Comment by lwtchu** [comment]
@kswanson33 do you want me to move this to the next sprint

**Comment by MartaSztuka** [comment]
@LostMojo What exactly should be tested here and in which books?

**Comment by LostMojo** [comment]
What should be tested: That the list items in the Table of Contents have an attribute called `data-toc-target-page-type` and that it is set to what page type it's pointing to. (Because classes don't make it onto webview, this is another way of passing along that data) (Example: `data-toc-target-page-type="os-toc-preface"`)

Books this should appear in: Every book with a toc

**Comment by MartaSztuka** [comment]
So far I've checked in Political Science and toc doesn't have attribute `data-toc-target-page-type`.
Book is in rex web preview.
Is there some other places I should look for it?
![Screenshot from 2022-09-08 16-42-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e1fe097b-bc6a-4678-95d3-bc2bc6ac1c58)

**Comment by LostMojo** [comment]
Hm. That's not good, that's where it is on the xhtml files-- @lwtchu it looks like webview might be getting rid of the other attributes?

**Comment by lwtchu** [comment]
@LostMojo @MartaSztuka oh i think there's another layer to go through - is there a way to check the baked HTML? before you generate webview or pdf preview?

**Comment by MartaSztuka** [comment]
@lwtchu There is `data-toc-target-page-type="os-toc-chapter-page"` in baked XHTML attribute. I'll test it there.
![Screenshot from 2022-09-09 10-26-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cbc85967-a373-46e2-8ceb-42374af61078)

**Comment by MartaSztuka** [comment]
##### precálculo
![Screenshot from 2022-09-09 11-14-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/56e51427-d799-42f2-a440-a3c57f286c78)

##### organic chemistry
![Screenshot from 2022-09-09 11-19-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/24071e99-c35d-4832-972c-6e13fe1c783e)

##### sociology
![Screenshot from 2022-09-09 11-24-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c082039f-23de-4c54-b7d0-24fef2917eb6)

##### contemporary math
![Screenshot from 2022-09-09 11-39-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e8951cbb-548e-475d-9832-e14a046a5e6c)

**Comment by lwtchu** [comment]
@MartaSztuka awesome - i'll go ahead and close. kendra already alerted CE tech so they can make the appropriate changes to the pipeline to rex
