### ISSUE TITLE
Mikroekonomia: Terms with invalid index attributes

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4796]
Terms with invalid index attributes should not break the baking process. They need to got to the default index type and be logged in the console so they can be easily spotted and fixed.
How the error output looked before: 
![image](https://user-images.githubusercontent.com/55203598/181766295-23488069-d636-4944-b965-58ebd46a971a.png)
In cookbook we currently support only two `index` attributes values: `name` and `foreign`. In Adaptarr there is a feature when the user can pick an index type in which the term should appear as default and then the index attribute value is set to `default`, such terms and also the ones with invalid index value (e.g. by a typo) should be accepted and logged with a warning without break the baking process.

**Comment by ajluk** [comment]
Screenshot for reference (terms with invalid indexes are put to default index - index rzeczowy and three indexes are created without break the baking process): 
![image](https://user-images.githubusercontent.com/55203598/182107710-4dc406db-99a1-451e-9e40-f3559cbabc03.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-08-01 12-58-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4ea4bc00-6211-4da1-88a2-508015899ecc)
![Screenshot from 2022-08-01 12-59-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/199d7377-c181-4998-a28d-97f829d3ebc4)
