### ISSUE TITLE
Polish books - change text in folio

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4797]
Text in folio should be `Podręcznik dostępny za darmo na openstax.org`

![image](https://user-images.githubusercontent.com/40228854/182145790-3e852379-2e16-4b74-b3b5-a9d36dd7f3f5.png)

**Comment by MartaSztuka** [comment]
#### PASSED
###### Mikroekonomia
![Screenshot from 2022-08-02 12-11-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/580f92d7-3095-47c9-813d-54eda38babed)

###### Psychologia
![Screenshot from 2022-08-02 11-49-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7acf58f3-431e-44a5-bef0-de1d5ca3778e)

###### Fizyka
![Screenshot from 2022-08-02 11-48-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/56ff639b-01ca-439b-8b9c-f814b756e8f5)
