### ISSUE TITLE
testing nokogiri upgrade locally

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4798]
# Brief Description of Scenario
See if upgrading to nokogiri 1.13 will solve the issues listed in #4786 and #4780. If it does, regroup to see what testing and upgrade strategy to pursue to complete #4657 (blocked due to a lot of unknowns and testing burden)

**Comment by ajluk** [comment]
Updating `nokogiri` to `1.13.8` locally in cookbook and `enki` pipeline didn't solved adding unwanted white spaces (they were new lines in both cases) from issues listed in https://github.com/openstax/cnx-recipes/issues/4786 and https://github.com/openstax/cnx-recipes/issues/4780.

**Comment by lwtchu** [comment]
closing this - there's no good solution here. will check with Phil again to see why we need to do #4657
