### ISSUE TITLE
Organic Chemistry - Figure Caption Too Small

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#4800]
# Brief Description of Scenario

Figure Numbers, Titles, and Captions are 7.5pt, when they should be 9pt per https://github.com/openstax/cnx-recipes/issues/1081.

### Examples
![CleanShot 2022-08-01 at 14.47.50.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a0de6ccb-2ded-4b14-af8e-e3116195bdbc)
![CleanShot 2022-08-01 at 14.54.12.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/46f2c53b-c45d-4007-8b6d-44ba8289315e)

# Pattern of Occurrence 

Consistent throughout book
# Acceptance Criteria
Figure caption text sizes line up with the spec.

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:** Design-Chapter
- **chapter/section:** all
- **surrounding text:** The additive combination is lower in energy

**Comment by lwtchu** [comment]
updating specs to match this
