### ISSUE TITLE
FIZYKA - regression testing

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#4801]
#### 1. In lists some numbers are written in regular font, some are in math - should be consistent.
![Screenshot from 2022-08-03 12-45-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fea645d4-f914-400e-8acb-ea4465a31ebf)
#### 2. Long equation
![Screenshot from 2022-08-03 12-50-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3d395951-f864-4e85-960f-b66866b85016)
###### 3.2
![Screenshot from 2022-08-03 15-06-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dc4b32d2-8417-4d71-bac1-9694a0f96551)
###### 3.3
![Screenshot from 2022-08-03 16-11-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/26ab14b2-e27a-48f6-a093-9e82a9d87348)
#### 4. Headers "Klocek 1" should be styled
![Screenshot from 2022-08-03 13-51-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c9cfaa90-a7a6-451c-9668-9ba358c87610)
#### 5. maby we should get rid of bold in foreign terms (just italic)
![Screenshot from 2022-08-03 15-47-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e6c470bf-1ac0-4aed-b061-4d26073d5d70)
#### 6.  we don't need bullet points when there's abc
![Screenshot from 2022-08-03 16-19-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c768e1b0-5e53-47e5-8b53-07eb7dbc0c51)
#### 7. numbers and equations should be inline
![Screenshot from 2022-08-03 16-22-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/533b2800-83f6-49db-a222-baa88b156fbc)
![Screenshot from 2022-08-03 16-24-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/230e0622-9f93-4aa9-9ec7-63a7f40f83f4)
![Screenshot from 2022-08-03 16-27-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a68f1779-3854-4bde-a0ea-11b66f339232)![Screenshot from 2022-08-03 16-28-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/148f68e7-b8e2-44e9-b899-4ed239f88b31)

**Comment by MartaSztuka** [comment]
#### FIZYKA 2
#### 1. In lists some numbers are written in regular font, some are in math - should be consistent.
![Screenshot from 2022-08-03 17-42-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/662fb455-c070-49b0-a56b-a9696b75013f)

**Comment by wilkus27** [comment]
### CARDS FOR CONTENT ISSUES:
1. https://github.com/openstax-poland/content/issues/284

**Comment by wilkus27** [comment]
### Problems that we are not going to resolve

4. **Klocek 1** is part of math, we can't style it:

![image](https://user-images.githubusercontent.com/40228854/183629697-f7ae9baa-4d4f-4009-a7c5-5c23b21668b7.png)
