### ISSUE TITLE
Fizyka - unstyled lists in Examples

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4803]
Add indentation to lists from Examples:

Fizyka vol1, Przykład 9.12
![image](https://user-images.githubusercontent.com/40228854/183599474-f06a5cc7-521c-4cfa-83af-2f37ff563876.png)

Fizyka vol1, Przykład 17.8

![image](https://user-images.githubusercontent.com/40228854/183599616-bbb97903-3daa-4aab-9078-f1c1a675e107.png)

**Comment by wilkus27** [comment]
### Information for tester

These changes has an impact also on `ap-physics-2e`, `chemistry`, `college-physics-2e`, `organic-chemistry` and `u-physics`.

**Comment by MartaSztuka** [comment]
#### PASSED
###### FIZYKA 1
![Screenshot from 2022-08-09 15-17-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e9489cd8-2e4f-4ef3-8cdd-96bc534e6a10)
![Screenshot from 2022-08-09 15-21-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/41ef9f99-5d75-49f9-a1bc-569fa2336050)
###### CHEMISTRY 2E
![Screenshot from 2022-08-09 15-25-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2184acad-60e0-48b4-b0df-d639836853e2)
###### COLLEGE PHYSICS
![Screenshot from 2022-08-09 16-01-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/81283ab1-97ec-4678-bfaf-d96ab73b6cff)
###### ORGANIC CHEMISTRY (no lists in examples)
![Screenshot from 2022-08-09 16-00-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ce7413dd-bb1b-49d5-ac6a-673929ec2053)
###### UNIVERSITY PHYSICS 1
![Screenshot from 2022-08-09 16-21-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1c89f562-233c-41ab-9e4a-13ddbf4165a4)
