### ISSUE TITLE
organic chemistry - put original design for chapter opener

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4807]
![Screen Shot 2022-08-09 at 12 15 47 PM](https://user-images.githubusercontent.com/11299125/183715375-65a28ba6-c033-41c9-940b-d8ae013ae260.png)

Remove the feature/design for #4748 
Reset as normal chapter opener #4806

**Comment by wilkus27** [comment]
This is what it looks like now:

![image](https://user-images.githubusercontent.com/40228854/184158407-b63d771d-1370-491e-8b42-b95df9dc31ed.png)

**Comment by lwtchu** [comment]
@wilkus27 thank you <3

**Comment by Stackblocks** [comment]
My local output matches what Natalia presented.

![CleanShot 2022-08-15 at 17.13.58.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f0db7441-b6c5-4480-9812-8a61c42e183b)
