### ISSUE TITLE
organic chemistry - chapter outline update

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4808]
![Screen Shot 2022-08-10 at 9 30 57 AM](https://user-images.githubusercontent.com/11299125/183927904-acdc41db-65b0-456b-8b2f-f353d09cbd93.png)

**JUST** for Organic Chemistry

Title: Change `Chapter Outline` to `Chapter Contents`
Font for modules: Unbold, set size to font-scale(-1): 7.5pt, 9.6px, 0.8rem

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-08-15 at 17.12.45.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/09068ec8-058b-48ab-92f8-310908d4072c)
