### ISSUE TITLE
organic chemistry - table caption and accent color

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4809]
![Screen Shot 2022-08-10 at 11 28 56 AM](https://user-images.githubusercontent.com/11299125/183963606-5832da3f-8900-4611-8a80-638822c7cfad.png)

Change table label and accent color from red to B5: `#0078a3`

**Comment by Stackblocks** [comment]
Table title and accent are now set to B5, the listed color in Adobe Acrobat is slightly off due to known app-side issues rather than something on our end.

![CleanShot 2022-08-15 at 17.11.38.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1d9a7832-5382-4711-8991-c655abc5441b)

**Comment by lwtchu** [comment]
@Stackblocks ah  yeah adobe acrobat has a different color profile. as long as it's almost the same 🥲
