### ISSUE TITLE
organic chemistry - different colors for module headers and EOC

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4811]
## Module headers

![Screen Shot 2022-08-10 at 12 46 24 PM](https://user-images.githubusercontent.com/11299125/183981112-1d20c811-d2bf-439d-bd29-b1a3726d51c0.png)
JUST the module header, can we set it to R1: `#C31427`

## EOC
![Screen Shot 2022-08-10 at 12 47 33 PM](https://user-images.githubusercontent.com/11299125/183981444-d528e7b3-8deb-4c7b-8a1d-2291e5e60b77.png)
![Screen Shot 2022-08-10 at 12 47 48 PM](https://user-images.githubusercontent.com/11299125/183981446-4f76607d-643b-47ab-a85b-800035d7b742.png)

set the headers to black `#000000` for key terms, summary, summary of reactions, visualizing chemistry, additional problems, practice your scientific analysis and reasoning

**Comment by wilkus27** [comment]
@lwtchu We are using one shape to style titles from all `[data-type="page"]`s, so beside modules there are also Appendix and Preface:

![image](https://user-images.githubusercontent.com/40228854/184134658-b9f1785a-e1b0-4d16-8be5-0206e8880b69.png)

![image](https://user-images.githubusercontent.com/40228854/184134722-74315d06-266d-4f4b-8e82-506a91cfe7b5.png)

Is that ok? Or do you want me to create separate shape for pages not from the chapter and leave there blue color?

**Comment by wilkus27** [comment]
And what about Introduction title? It should be blue or red?

![image](https://user-images.githubusercontent.com/40228854/184135895-b52be130-325b-46db-b714-8762ea9adba0.png)

**Comment by lwtchu** [comment]
@wilkus27 we just want JUST the h1 to  be red - is that possible, or does it have to be all of them?

**Comment by wilkus27** [comment]
@lwtchu Module headers are `H2`, so with current code `H2`s from Preface and Appendix will also be red. But I can modify shape or split it in two (not sure yet what would be better) if we want to have red only for first module header.

**Comment by lwtchu** [comment]
@wilkus27 i think that's ok 🤔 let's set h2's to red - author wants to break up the blue a bit

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-08-15 at 17.15.28.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e9e0a322-b630-4692-a7df-2c76ba8949e0)
![CleanShot 2022-08-15 at 17.15.49.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0a8a3674-a97d-4664-b9be-fba2fe19e99b)
