### ISSUE TITLE
organic chemistry - remove section label for end of module problems

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4812]
![Screen Shot 2022-08-10 at 12 49 41 PM](https://user-images.githubusercontent.com/11299125/183981693-324987d3-fc22-4429-a8dd-1730dd777957.png)

delete the #.# problems and delete in the answer key as well

**Comment by wilkus27** [comment]
@lwtchu This is what it looks like

#### EOS
![image](https://user-images.githubusercontent.com/40228854/184892938-62dc34ac-5348-4f29-92ea-aef2371bdad7.png)

#### Answer Key
![image](https://user-images.githubusercontent.com/40228854/184893169-4e3c1bca-51a0-42b6-8c27-13d7d4d6066a.png)

Is it ok?

**Comment by lwtchu** [comment]
@wilkus27 yes thank you - what the author wanted !

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-08-16 at 17.31.17.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6f2feee8-710f-47e9-ad0d-286c1cfff46d)
