### ISSUE TITLE
organic chemistry - rename Something Extra feature to Chemistry Matters

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4813]
new class: `chemistry-matters`
new title: Chemistry Matters
same design as #4750 but title change

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![CleanShot 2022-08-23 at 16.11.07.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/43eda5ea-ac6c-4a25-8083-67cd68c6f13e)
