### ISSUE TITLE
organic chemistry - key terms

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4815]
key terms are now in a section with a list with the class `"key-terms"`

section: `"key-terms"`
title: Key Terms
placement: before summary

For testing:
This commit has the content that isn't commented out https://github.com/openstax/osbooks-organic-chemistry/commit/ef1b70826091673e3554c8b6368de66c4339c4de

**Comment by lwtchu** [comment]
moving to backlog - [organic chemistry - links to key terms baking bug](https://github.com/openstax/cnx-recipes/issues/4818) is merged but not thru QA but should be ok

**Comment by wilkus27** [comment]
@lwtchu This is what it looks now:

![image](https://user-images.githubusercontent.com/40228854/187232154-d254ae98-6b66-4058-b670-4e8fe37ddf70.png)

Should I style links somehow or is it ok?

**Comment by lwtchu** [comment]
@wilkus27 is it possible to do two column for these now that it's just the words?

**Comment by wilkus27** [comment]
@lwtchu Yes :relaxed: Here's the change.

![image](https://user-images.githubusercontent.com/40228854/187393299-ade9340f-d254-41f8-ab64-352a6981cab6.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-08-30 14-25-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/133c7350-ab46-4945-bf7c-e8b61c1b73b9)
