### ISSUE TITLE
organic chemistry - summary of reactions title 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4816]
![Screen Shot 2022-07-27 at 11.24.57 AM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/b70a5d2c-9ba5-4dc4-94a2-1f309e6443da)
this is missing the OF in `Summary of Reactions`

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content, color changed as part of https://github.com/openstax/cnx-recipes/issues/4811
![CleanShot 2022-08-15 at 17.15.55.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/532e8665-6021-45cc-b3ea-546c1b1f1bae)
