### ISSUE TITLE
mikroekonomia - disappearing figures

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4817]
There are some figures that are added in Adaptarr but they're missing in PDF:

![image](https://user-images.githubusercontent.com/40228854/184103557-07a41bca-5935-4c5e-b984-568ba7894302.png)

Answer Key, Rozdział 9:

![image](https://user-images.githubusercontent.com/40228854/184103731-6160b3db-c639-4c0f-bdc0-d1c5035a4d7e.png)

**Comment by Stackblocks** [comment]
Images are appearing in the baked book, second image rolls over to new page but doesn't appear to have an irregular break.

![CleanShot 2022-08-11 at 10.01.36.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a7f9022b-62da-4299-9899-65a93755dd71)

![CleanShot 2022-08-11 at 10.01.21.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ee7e9875-34b7-40d0-81b8-f8d26cd9be39)
