### ISSUE TITLE
organic chemistry - links to key terms baking bug

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4818]
## Scenario
We are trying to link to key terms within the content as a new-ish feature since POET adds id's to terms now.

However, the ID links show up as broken
![Screen Shot 2022-08-15 at 9.48.27 AM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/de52826f-889f-4e81-bedb-0ab9730c5584)

Cookbook is OVERRIDING all the term IDs within the content so once the content is baked, the links are considered broken. (See below for assembled vs baked files)

Assembled:
`Even simpler than condensed structures are <span data-type="term" id="auto_e8416a43-c719-4db7-a87a-1ee7ec8bb673_term-00003">skeletal structures</span> such as those shown in ...`

Baked has the wonky term113 at the end of the ID:
`Even simpler than condensed structures are <span data-type="term" id="auto_page_e8416a43-c719-4db7-a87a-1ee7ec8bb673_term113" group-by="s">skeletal structures</span> such as those shown in ...`

## Acceptance Criteria

- Remove the overriding term IDs OR do a conditional thing where if it sees IDs, it doesn't override.
- `Link points to nowhere` warning message is not logged re: terms when generating ochem (from the `git-validate-xml-mathified` step)
- links to terms in ochem work

For testing: 
This commit has the content that isn't commented out https://github.com/openstax/osbooks-organic-chemistry/commit/ef1b70826091673e3554c8b6368de66c4339c4de

**Comment by lwtchu** [comment]
Not sure why Kitchen adds own IDs, initial work here is to figure out why?

**Comment by kswanson33** [comment]
not sure why but this is [where](https://github.com/openstax/cookbook/blob/main/lib/kitchen/directions/bake_index/v1.rb#L127)

**Comment by lwtchu** [comment]
leftover from easybake - didn't add this until POET added ID's 

can do something li ke don't override if there are term IDs

**Comment by lwtchu** [comment]
need to check katalyst books

**Comment by lwtchu** [comment]
Checked with Theresa - all of our books should have generated term IDs since errata has gone through all the books

**Comment by wilkus27** [comment]
@lwtchu In Adaptarr yes, terms have autogenerated IDs, so Psychologia and Mikroekonomia have them. But Fizyka was not created in Adaptarr and terms in this book (books - all 3 volumes) don't have IDs. They're added by recipe.

**Comment by lwtchu** [comment]
FINAL DECISION: Add an option to cookbook to add IDs if there are  none, but keep the ID's on terms if the IDs exist

**Comment by kswanson33** [comment]
For QA: I tested on ochem, but not Fizyka. Would appreciate verification that the links work & also that no regressions have been introduced around terms & the index

**Comment by Stackblocks** [comment]
- Ochem looks good, Fyzika still needs to be checked out.

**Assembled**
![CleanShot 2022-08-24 at 11.01.25.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e86cb7a0-a7fb-448b-a1c8-1dd2d208a426)

**Baked**
![CleanShot 2022-08-24 at 11.02.28.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/027f5b4f-b683-40a7-b2fc-5d2c1c4d05f6)

**Build Process**
https://images.zenhubusercontent.com/49744755/bf78cc44-1f05-4c90-905f-1b944ac8d289/cleanshot_2022_08_24_at_10_56_28.mp4

**Comment by MartaSztuka** [comment]
###### Fizyka 1
###### Assembled
![Screenshot from 2022-08-25 11-31-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7f8c7a0a-2da8-4317-843b-6f08b94c7841)
###### Baked
![Screenshot from 2022-08-25 11-41-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cdc46e3b-edef-463e-b9e9-82b303354faa)

**Comment by lwtchu** [comment]
baking successful
