### ISSUE TITLE
organic chemistry (impact all books) - do not override classes for injected exercises

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4819]
## Scenario
In order to turn off display:inline for the exercises, we have to enable display:block for the exercises with the class `class="exercise-block"`. However, the injected exercises completely overrides the class/exercise tagging.

[Test content](https://github.com/openstax/osbooks-organic-chemistry/tree/Design-Chapter): on these two exercises OrgChem_C01_Q006 and OrgChem_C01_Q014
![Screen Shot 2022-08-04 at 10 26 55 AM](https://user-images.githubusercontent.com/11299125/182886022-3d51cc53-8be2-4833-9b81-ff59e29839eb.png)

To move the class attribute from the `<a href="#/ost/...">` element onto the exercise a change will need to be made to the template that injects the exercise [here](https://github.com/openstax/cnx-epub/blob/83fa4a1706d74d72ee2e48460e57c318a5210231/cnxepub/templates/exercise_template.py#L3-L5).

_Originally posted by @philschatz in https://github.com/openstax/cnx-recipes/issues/4790#issuecomment-1212362609_

**Comment by lwtchu** [comment]
add pair programming label to this

**Comment by kswanson33** [comment]
see (new!) [documentation](https://openstax.atlassian.net/wiki/spaces/CE/pages/2099413010/Contributing+to+injected+exercises+on+cnx-epub) on contributing to injected exercises on cnx-epub

**Comment by kswanson33** [comment]
For testing: This was a cnx-epub change; notes about testing these are [here](https://openstax.atlassian.net/wiki/spaces/CE/pages/2099413010/Contributing+to+injected+exercises+on+cnx-epub#QA-Testing). This change has not yet been released on neb, and so can only be tested with option 2. If there are questions about this process, feel free to ping me :)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-09-05 10-55-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/38e551ac-ce90-4cb4-b904-6b11370bdf05)

![Screenshot from 2022-09-05 10-53-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3e3f12c0-fa15-4032-9a61-09f4fca4306e)
