### ISSUE TITLE
Business Ethics - Chapter Title in Webview

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#482]
@mwest-WWprod commented on [Thu Jul 19 2018](https://github.com/Connexions/oer.exports/issues/3709)

content01
GLOBAL - Webview

Chapter title does not appear on opener page (only appears in TOC listing). Chapter title should appear if possible.

![chaptertitle webview](https://user-images.githubusercontent.com/19212926/42968647-e5e7f97e-8b71-11e8-8c60-83c09a905b8d.png)

---

@openstaxalina commented on [Thu Jul 19 2018](https://github.com/Connexions/oer.exports/issues/3709#issuecomment-406413810)

@Stackblocks could you please move this to cnx-recipes?

**Comment by openstaxalina** [comment]
This is out of scope for the business titles.  Consider for a future improvement.
