### ISSUE TITLE
mikroekonomia - unstyled header in Introduction

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4820]
On Introduction page there is an unstyled H3 title:

Chapter 6
![image](https://user-images.githubusercontent.com/40228854/184340630-0f09ccc3-ddf6-48f2-814c-1466ae4d2020.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-08-17 11-31-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6a38799b-112c-4c29-9a5e-dcc4e9596bee)
