### ISSUE TITLE
Organic Chemistry - remove working problems feature and set as no class note

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4821]
![Screen Shot 2022-08-15 at 10.27.16 AM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/b52d1ebe-8395-40ab-b964-55018bad3fe5)

Remove  `class="working-problems"`

Use the same style non-icon boxed note but have the title of the feature driven by the content `<title>`

Same concept as https://github.com/openstax/cnx-recipes/issues/2191

**Comment by lwtchu** [comment]
@kswanson33 @LostMojo @Stackblocks i forgot too open this card but it's something we've done before so i set it as a 2 :eyes: not an issue for ants, but still doable.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![CleanShot 2022-08-23 at 15.00.21.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4b02358a-f3aa-44f0-961c-7153a7087481)
![CleanShot 2022-08-23 at 14.58.43.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ac8bf81b-4457-4e41-9343-815ea7d8e011)
