### ISSUE TITLE
writing guide - MLA format for citations

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4822]
@lwtchu commented on [Wed Jan 12 2022](https://github.com/openstax/unified/issues/1798)

# Description
There's 3 locations where the citation format needs to happen: centered title and each citation/entry needs a hanging indent if it is 2 or more lines long). 

## EOC for Works Cited and Further Reading
![Screenshot 2022-01-12 134146](https://user-images.githubusercontent.com/11299125/149210306-50d1a956-bc28-4b85-9150-f3c9ee7bf319.png)
This is collated to the end of the chapter and only needs a hanging indent for each entry. Title can remain as is in the title bar.
AND for Further Reading `class="further-reading"`

## In section
![Screenshot 2022-01-12 134452](https://user-images.githubusercontent.com/11299125/149210697-edb7b89d-6337-4d7e-bff7-2ca264dcb6d7.png)
This is in section. The title "Works Cited" should be centered and the entries need to have the hanging indent. 
Location: 5.5
Class: `class="section-workscited"`

## In line citations
![Screenshot 2022-01-12 134704](https://user-images.githubusercontent.com/11299125/149211008-68951a03-589c-434e-b364-335c4e1de35d.png)
These are single-paragraph entries that need a hanging indent. They are mostly found in the Handbook section and a few live...in other sections. I can find it if needed. 
Class: `class="citation"`

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

# Acceptance Tests
Additional acceptance tests that are required by this bug fix.

1. Check below a/c in polish/spanish books if applicable
2.
3. 

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Pipeline
1A-PRE DESIGN
- [ ] PDM approves UX LoFi Design

1C-DESIGN
  - [ ] PDM approves UX HiFi Design

2B-REVIEW
  - [ ] UX approves change
  - [ ] QA approves change
  - [ ] PDM approves change
  
3A-PEND RELEASE
  - [ ] QA verifies that the acceptance tests are imported into TestRail

# Process 
[Work Management for Unified](https://github.com/openstax/unified/blob/master/CONTRIBUTING.md)

**Comment by jbwilson8** [comment]
@lwtchu The current version doesn't seem to have a works cited title at the top. Does one need to be added and centered or is that intentional?
![Screen Shot 2023-01-26 at 10 16 09 AM](https://user-images.githubusercontent.com/26155528/214889450-b78296f9-f5d3-4469-a896-be1b6916d7be.png)
![Screen Shot 2023-01-26 at 10 15 49 AM](https://user-images.githubusercontent.com/26155528/214889459-1e7e169b-8c5f-4487-830d-f3a113d379bc.png)

**Comment by lwtchu** [comment]
@jbwilson8 this is intentional because it's the name of the module and we can't change that. - the other headers will need to be centered.

**Comment by jbwilson8** [comment]
@lwtchu In further reading there is a line that is not a citation, but in the xhtml its just a p element and is indistinguishable from the other elements that are citations. Should we add a citations class to the citations or a class onto the instruction line that I'm assuming shouldn't be indented?
![Screen Shot 2023-01-26 at 10 16 09 AM](https://user-images.githubusercontent.com/26155528/214906818-87af7429-634a-4cc0-9a1d-5d42732c127f.png)
![Screen Shot 2023-01-26 at 10 15 49 AM](https://user-images.githubusercontent.com/26155528/214906827-3dbec2b2-96fd-4107-9834-c3344a52cd25.png)

**Comment by lwtchu** [comment]
@jbwilson8 i think it's okay to apply it to that one line - it was approved like that by the authors.

**Comment by Stackblocks** [comment]
Displays OK with current code & content.

![CleanShot 2023-02-03 at 16.25.39.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7feac4a8-d017-41e1-8dc1-e604b3ae6d59)
---
![CleanShot 2023-02-03 at 16.26.30.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/9c5b6793-71bc-4c46-a766-9d0b3df1029d)
---
![CleanShot 2023-02-03 at 16.25.04.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8bf4deb9-6a6b-4165-b1dd-a5ed7200b0bd)
