### ISSUE TITLE
webview - consistent header styling (make sure smaller (h5) headers aren't larger than larger headers (h4))

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4823]
@Malar-Natarajan commented on [Tue Aug 13 2019](https://github.com/openstax/unified/issues/433)

# Description
Few headings in preface page of A&P look smaller than cnx. See screenshot highlighted in red

https://drive.google.com/file/d/155go_I0ftEZzBAW1KYHbki6Fvd7gdkQg/view?usp=sharing

# Acceptance Criteria
All the headings in preface page of A&P look similar to cnx in size

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Epic Doc
URL

# Checklist for Done
1A-PRE DESIGN
- [ ] Description is complete
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
  - [ ] The work is broken into reasonable and consistent work items.
  - [ ] For large issues, story issues are created for the work items, with Description, Acceptance, and an Estimate.  They are moved into 1B-DECOMP DONE.
  - [ ] If child stories are created, the original issue is changed to an epic with label `Epic`.  The child story issues are linked to it. It is moved below DECOMPED BELOW in 1B-DECOMP.
  - [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] A behavior doc is published.
  - [ ] A kickoff call has been held.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2A-CODE
  - [ ] A pull request is opened.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

2B-REVIEW
  - [ ] Visual Design approval
  - [ ] QA approval
  - [ ] PDM approval
  - [ ] Developer approval
  - [ ] The pull request is merged into master, and the change branch is deleted.

3A-PEND RELEASE
  - [ ] All the changes in the release are deployed to the Release Candidate environment.
  - [ ] The release is declared frozen by the Product Manager.

3B-RELEASE REVIEW
  - [ ] Acceptance tests pass for all issues in the release
  - [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by lwtchu** [comment]
@lwtchu use sifter to find h5's

**Comment by lwtchu** [comment]
Books with H5s
https://openstax.github.io/sifter/#v=1&q=h5&sourceFormat=xhtml
Writing Guide
Principles of  Marketing
Principles of Management
Financial Accounting
Finance
Precalculus
Prealgebra
Physics (HS)
Microbio
Sociology 3e
Fizyka
College Success
College Physics
Biology
A&P 

I did not include other books within bundles.

**Comment by Stackblocks** [comment]
h5s are no longer larger than h4s in initial testing; checking out additional books and testing a h6.

![CleanShot 2023-02-22 at 10.14.07.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/db56e3d4-87c6-45fc-b80d-3086eb8ee4a0)
---
![CleanShot 2023-02-22 at 10.14.34.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d5af9fac-dfac-4219-8ffb-8e35e79d586b)
