### ISSUE TITLE
Psychology 2e - Space after link in webview

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4824]
@lwtchu commented on [Wed Feb 17 2021](https://github.com/openstax/unified/issues/1501)

@oscryan commented on [Tue May 26 2020](https://github.com/openstax/cnx-recipes/issues/2335)

# Scenario
Space appears after figure link in Psych 2e Chapter 3 Critical Thinking collated questions:
https://rex-web.herokuapp.com/books/psychology-2e@5.2/pages/3-critical-thinking-questions/?archive=https%3A%2F%2Farchive-staging.cnx.org

The spare does not appear on legacy or within the content CNXML.

# Acceptance Criteria (required)
no extra space

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="204" alt="Screen Shot 2020-05-26 at 11 05 05 AM" src="https://user-images.githubusercontent.com/1895432/82929716-c1bc6600-9f49-11ea-828f-ef47914d6af3.png">

# Environment: (required)
* **Medium**: [x] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [x] staging  [ ] dev  [ ] content
* **OS**: [x] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [x] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [x] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [x] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

---

@oscryan commented on [Tue May 26 2020](https://github.com/openstax/cnx-recipes/issues/2335#issuecomment-634214625)

It's not in the markup.

---

@openstaxalina commented on [Thu May 28 2020](https://github.com/openstax/cnx-recipes/issues/2335#issuecomment-635558574)

Good catch, thanks. This also occurs on live production content: https://openstax.org/books/psychology-2e/pages/3-critical-thinking-questions

This also occurs on CNX and has occurred in all versions of the book: https://vendor.cnx.org/contents/BqulZZQy@1.1:DbSiFBlG@1.1/Critical-Thinking-Questions.

@oscryan I noticed you added other book labels -- is there a pattern? Does the extra space occur with any element linked from an EOC section?

---

@openstaxalina commented on [Thu May 28 2020](https://github.com/openstax/cnx-recipes/issues/2335#issuecomment-635558841)

(I am not prioritizing this with release flags and footnotes fixes since this was not introduced by this code.)

---

@oscryan commented on [Thu May 28 2020](https://github.com/openstax/cnx-recipes/issues/2335#issuecomment-635559002)

yeah i think so

---

@brittweinstein commented on [Fri May 29 2020](https://github.com/openstax/cnx-recipes/issues/2335#issuecomment-635978855)

@openstaxalina is this something we can address in the NN milestone?

---

@openstaxalina commented on [Fri May 29 2020](https://github.com/openstax/cnx-recipes/issues/2335#issuecomment-635997805)

@brittweinstein it is less important than the work for _College Algebra with Corequisite_. I'd prioritize it after _College Algebra with Corequisite_ is out. Is that feasible from you perspective?

cc @lwtchu 

---

@yblock commented on [Wed Jun 10 2020](https://github.com/openstax/cnx-recipes/issues/2335#issuecomment-642039080)

I also noticed an extra space issue in the index sections. It looks like there is an extra space being added between links and a comma separating multiple section links: 
<img width="499" alt="Screen Shot 2020-06-10 at 9 14 08 AM" src="https://user-images.githubusercontent.com/5865292/84278882-e93f3100-aafa-11ea-92f5-d8e708a4a58f.png">

In this example, there is an extra space between the word "Derivative" and the comma.

---

@lwtchu commented on [Tue Feb 02 2021](https://github.com/openstax/cnx-recipes/issues/2335#issuecomment-771807871)

![Screen Shot 2021-02-02 at 11 12 44 AM](https://user-images.githubusercontent.com/11299125/106636483-99105580-6547-11eb-812e-0b83c78ae37c.png)
![Screen Shot 2021-02-02 at 11 13 00 AM](https://user-images.githubusercontent.com/11299125/106636530-a299bd80-6547-11eb-97ed-af5d05c02caa.png)

it's not happening in the pdf but in webview 🤔  

To whoever is working on this - are we just removing the space in the style for the PDF? 

---

@lwtchu commented on [Tue Feb 02 2021](https://github.com/openstax/cnx-recipes/issues/2335#issuecomment-771808241)

Adding to d.d. for microbiology fix

---

@wilkus27 commented on [Mon Feb 15 2021](https://github.com/openstax/cnx-recipes/issues/2335#issuecomment-779223619)

Yes, this problem occurs only on webview. There is set margin for links in styles for rex:

![image](https://user-images.githubusercontent.com/40228854/107952223-c4f4f780-6f99-11eb-9369-47fe32ccb134.png)

@PiotrKozlowski or @jarosik10 can you take a look on this?

---

@PiotrKozlowski commented on [Mon Feb 15 2021](https://github.com/openstax/cnx-recipes/issues/2335#issuecomment-779251047)

It looks like something which we can fix in REX. Probably @kjdav should prioritize

---

@lwtchu commented on [Wed Feb 17 2021](https://github.com/openstax/cnx-recipes/issues/2335#issuecomment-780860863)

Moving the card over to unified so Kim can prioritize.

**Comment by lwtchu** [comment]
same space issues as #4786 ?? maybe. do after we adopt baked styles for web for entire library

**Comment by ajluk** [comment]
@lwtchu Based on Natalias comment from above this issue is caused by styles added in rex, not baking (#4786 is caused by baking).

**Comment by wilkus27** [comment]
@lwtchu Problem doesn't appear with styles from `ce-styles` repo

![image](https://user-images.githubusercontent.com/40228854/217256023-9000d3d1-00b2-41a0-9575-2806db0bb932.png)

**Comment by lwtchu** [comment]
@wilkus27 thank you im going to close 🤔
