### ISSUE TITLE
World History Ch 10 -- TOC styling incorrect -- Item List Numbers, Missing Page Numbers

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4826]
![image](https://user-images.githubusercontent.com/89537088/184724119-9e519133-b080-446d-8dd8-ea2926161a68.png)
# Brief Description of Scenario
1. TOC should not contain item list numbers. Please delete item list numbers from TOC
2. TOC is missing page numbers

# Pattern of Occurrence 
This is the test chapter so this is the first occurrence.

# Acceptance Criteria
TOC will NOT have item list numbers
TOC will have page numbers

# Location(s)
- **osbooks repo:**  osbooks-world-history
- **collection slug:** world-history
- **ref/branch:**
- **chapter/section:** Ch 10 / TOC
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax As mentioned in #4827, this template was created with Units in mind. To add a unit, you need to create another subcollection in the TOC editor in POET and place the chapters within it. If this book will no longer require units, please let us know and we will make the design change.
