### ISSUE TITLE
organic chemistry - set base text to justified

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4830]
We did this locally - but please change root to have text-align: justified. can this ONLY be applied to Organic Chemistry?

**Comment by Stackblocks** [comment]
The grim deed is done 😔
![CleanShot 2022-08-24 at 13.20.47.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1daa0a3f-db6c-41fa-9eb0-80ad6dde7bc8)
