### ISSUE TITLE
organic chemistry - remove subheader in summary and summary of reactions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4831]
![Screen Shot 2022-08-17 at 10 03 46 AM](https://user-images.githubusercontent.com/11299125/185174441-866e3a77-a212-46dc-937d-21ebc1c0e8d5.png)
![Screen Shot 2022-08-17 at 10 03 48 AM](https://user-images.githubusercontent.com/11299125/185174448-9d4fedb0-b393-4200-bdae-8d53d331b4e1.png)

Please remove the module headings (1.12 Drawing Chemical Structures) Each chapter will just have 1 summary and 1 summary of reactions

**Comment by Stackblocks** [comment]
Summary subtitle is removed, but the Summary of Reactions subtitle is still present when generated with current code.
![CleanShot 2022-08-24 at 13.23.37.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/705ff46c-4fc4-4c25-b7ba-65451c72d7ad)

**Comment by wilkus27** [comment]
Oh I missed that :eyes: Thank you for noticing! Fix is ready :wink:

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-08-25 12-22-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3f0ca759-535a-4fb9-8f1e-fae8f0539ca8)
