### ISSUE TITLE
Contemporary Math: Stem-and-Leaf tables captured in Exercised are not left aligned in PDF view as expected

### ISSUE THREAD

**Issue by mps-openstax** [openstax/cnx-recipes#4832]
## Summary 
Stem-and Leaf tables captured in exercises are not appearing left aligned in PDF as expected though these are appearing correctly in WebView as expected. Please see the snapshots below from PDF view and their respective coding from Exercise.

**PDF View**
![185041103-605c2c62-ad62-408c-92f8-02c1dbc3ddb4](https://user-images.githubusercontent.com/88098452/185955854-5e3c3bc2-f98a-46b4-99f1-2fe06e997dbf.png)

**Coding from Exercise**

![185041460-72d4f81a-aa4b-48da-b569-4ef3f1b53096](https://user-images.githubusercontent.com/88098452/185956148-17d7fbbf-c71b-4afa-b922-52c890ef2227.png)

## Acceptance Criteria
- [ ] HTML attributes within a table in an injected exercise carries through and can affect content placement

## Content Location
Your Turn 8.15 chapter 8.3 Mean, Median and Mode
https://github.com/openstax/osbooks-contemporary-math

**Comment by wilkus27** [comment]
@lwtchu Attribute should be named `data-align`:

![image](https://user-images.githubusercontent.com/40228854/187172762-52c3e58a-214c-4308-b4cf-c97fefb77590.png)

not `align`:

![image](https://user-images.githubusercontent.com/40228854/187172891-23fb6467-d540-4a60-82bf-67b0e83c3e40.png)

**Comment by lwtchu** [comment]
@wilkus27 i added the attribute  - but i think it's still centering on the  PDF?

**Comment by lwtchu** [comment]
@wilkus27 it looks like it took a while for the content to update through 🤔 but looks fine on CORGI as well. I'll alert the vendor when the release goes out.

**Comment by lwtchu** [comment]
@wilkus27 the data-align attribute goes away when i save in exercises and only the align attribute is able to stay. could you show me what the HTML looks like when it's assembled?

**Comment by wilkus27** [comment]
@lwtchu I checked and in injected exercise is still `align`

![image](https://user-images.githubusercontent.com/40228854/189648868-9d56c26a-b47f-48a5-9d19-694ddd9763da.png)

In regular exercise it's `data-align`:

![image](https://user-images.githubusercontent.com/40228854/189649160-4856335b-eea6-4b38-b0ab-26d06083c0f1.png)

**Comment by lwtchu** [comment]
@wilkus27 where are these samples from? like assemble? or  baked? I'm trying to figure out where the fix needs to happen since we can't fix the content :(

**Comment by wilkus27** [comment]
@lwtchu These screenshots are from assembled file.

**Comment by lwtchu** [comment]
@wilkus27 thanks! i'll...ask around to see how we can enable it for exercises

**Comment by openstaxalina** [comment]
Bug card opened here: https://github.com/openstax/tutor/issues/1829

ETA to be provided.

**Comment by openstaxalina** [comment]
@lwtchu FYI I removed `status:content.issue` label since this will be an exercises fix (card linked above and I am checking with Erika about it later today).

**Comment by lwtchu** [comment]
![Screen Shot 2022-10-19 at 3 04 38 PM](https://user-images.githubusercontent.com/11299125/196792761-be13b10c-6471-451f-bcda-279c05bedd69.png)
![Screen Shot 2022-10-19 at 3 04 51 PM](https://user-images.githubusercontent.com/11299125/196792809-50a93810-09b4-4b10-b96c-08dd1a7987df.png)
can confirm adding `data-align` attribute sticks and carries thru to PDF
