### ISSUE TITLE
Contemporary Math: Chapter number and Titles are not rendering properly

### ISSUE THREAD

**Issue by mps-openstax** [openstax/cnx-recipes#4833]
## Summary 

Chapter number and Title are classing in PDF. Please see the PDF view for your reference below and do the needful as quick as possible.

**PDF View**
![183935996-20895c06-95b7-402c-a9a5-a742115bcecb](https://user-images.githubusercontent.com/88098452/185956760-c56f15a2-5e0b-444e-843c-e699c866c07f.png)

**Coding**
![183938568-4a3cea99-d4b5-4c4d-ae04-fa8b974e4547](https://user-images.githubusercontent.com/88098452/185956838-ed4d7fe1-377f-403b-8aeb-ec0a06ee69d8.png)

## Acceptance Criteria
- [ ] second line of the title starts under the first line and there is line height added to the specs 
- [ ] CONTENT ONLY - splash image needs to have a minimum height of 2.5 in

## Location
https://github.com/openstax/osbooks-contemporary-math
Chapter 3

**Comment by lwtchu** [comment]
@mps-openstax we can adjust the title, however all splash images in this theme need to have the set dimensions of 7 x 2.5in as stated on https://www.opengui.de/contemporary-math

**Comment by ajluk** [comment]
@lwtchu Here is the best result I could achieve today: 
![image](https://user-images.githubusercontent.com/55203598/186202020-3c9ac24c-9313-4269-9ebf-60f6b022d36f.png)
![image](https://user-images.githubusercontent.com/55203598/186201934-6af788d6-381c-4ae6-b452-701d73edb62d.png)
![image](https://user-images.githubusercontent.com/55203598/186200641-86e89bbe-6385-43ae-9ede-7400bd68f53a.png)
The number in the square isn't centered completely as you see probably (it has a little more space on the top):
![image](https://user-images.githubusercontent.com/55203598/186202281-08c0af73-5362-404a-a921-6723bc13f79a.png)
Is that acceptable? I'm sking since in this case when we positioning the whole title, the number and text it is really hard to get the ideal effect.

**Comment by lwtchu** [comment]
@ajluk would it be easier if we removed the square? it's not really necessary and i would prefer the two line titles vs having a square for the number

**Comment by ajluk** [comment]
@lwtchu I have check it more carefully and found out that the issue with styling it is in the line-height I needed to increase to 2.0736rem for all of the h1 to make bigger gap between the two lines of the title text. So I tried to also increase the width,height of the number from 2.1 to 2.8rem (for increase the square center the number). It looks like this then: 
![image](https://user-images.githubusercontent.com/55203598/186923607-c7abbaca-dbf3-4398-88d8-907860cd54d0.png)
In the second example I have left the width/heigh of the numbers untouched, but decreased the font of the number to 1.2rem to center it within smaller square: 
![image](https://user-images.githubusercontent.com/55203598/186951168-3358470b-9ee2-45c5-9162-302d1da5a9aa.png)
![image](https://user-images.githubusercontent.com/55203598/186951094-ac1a804e-101f-44de-8959-a41d1f11380b.png)

**Comment by lwtchu** [comment]
@ajluk let's not decrease the font - let's increase the width and height and number. i fear if it's too small, it'll get lost in the intro. (go with option 1)

**Comment by lwtchu** [comment]
@ajluk looks good :) i'll alert them of the splash image being too small when the fix goes out

**Comment by MartaSztuka** [comment]
@ajluk gap between this lime and blue boxes is too big and bottom margine, but it's conten, beside that it's ok
![Screenshot from 2022-08-31 18-03-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1fec0e05-5db3-4c3a-996e-64297aa46f49)
![Screenshot from 2022-08-31 17-59-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fd671b09-53f1-41d6-9bce-a33c3a11fd62)
![Screenshot from 2022-08-31 17-59-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d7a40968-06d4-417d-b1d5-e44357f8a262)
