### ISSUE TITLE
Contemporary Math: Chapter 5 - Lists inside exercises are not indented properly

### ISSUE THREAD

**Issue by mps-openstax** [openstax/cnx-recipes#4834]
## Summary 
Lists inside exercises are not appearing with proper indentation: Please see the PDF output below for your reference.

![183069929-02d8b997-81fb-4131-8304-1d42d5409816](https://user-images.githubusercontent.com/88098452/185957618-888ba4fd-042b-4de1-bb70-421f260a9412.png)

In preview these are appearing correctly. Please see the snapshot of both coding and the preview below for your reference.

![183070504-fc20463e-4209-4855-a1af-4302d915a237](https://user-images.githubusercontent.com/88098452/185957651-16956a5c-bcb3-45e6-be9d-c0de8c76a7d3.png)

Please do the needful so that these will appear correctly in the PDF otherwise kindly suggest how to proceed.

Thank You!

## Acceptance Criteria
- [ ] lists pulled in from exercises tool gets indented styling 

## Location
https://github.com/openstax/osbooks-contemporary-math 
Section 2.5 Exercises 
Surrounding text: Write the conditional statement

**Comment by Stackblocks** [comment]
- [x] List has been fixed to not be outdented.

![CleanShot 2022-08-24 at 15.17.56.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/753499fb-ba3c-4c2b-8455-c65db8f6af13)
