### ISSUE TITLE
(webview) organic chemistry - mechanism art styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4836]
## Summary  
@lwtchu Sorry, yes it is possible. I should have generated it for you before asking. :sweat_smile:  Here is how the caption looks for such figures in rex preview (quite good actually :slightly_smiling_face: ): 
![image](https://user-images.githubusercontent.com/55203598/185607905-4c41b68f-8447-4a68-8e92-91c908c05231.png)
Are there needed some changes  there too or not at this moment?

_Originally posted by @ajluk in https://github.com/openstax/cnx-recipes/issues/4814#issuecomment-1220558242_

Figure number styling and title and caption are lost once they are moved above the image.

## Acceptance Criteria
The figure caption is smaller than the base text and the figure number is bolded (example below)
![Screen Shot 2022-08-23 at 9 17 42 AM](https://user-images.githubusercontent.com/11299125/186182121-8f78804f-a774-4a89-b740-dc47b0d3a823.png)

## Content
https://github.com/openstax/osbooks-organic-chemistry/tree/Design-Chapter
content pieces labeled: `class="mechanism-figure" `

**Comment by lwtchu** [comment]
@ajluk @wilkus27 to pair with  kendra or mary jo to get onboarded to webview styling - not super high prio. can do before december

**Comment by ajluk** [comment]
@lwtchu Here is how it looks (change font, bolded title label + number, added padding bottom 1rem to caption text, the rest is identia as in the rest of the webview figures styling): 
![image](https://user-images.githubusercontent.com/55203598/187711716-b5576e6a-7fc6-48c6-9da8-5ad2006380bb.png)
Is it what you have in mind?

**Comment by lwtchu** [comment]
@ajluk it can be in a separate line. we can make improvements and iterations once baked styles for web is adopted

**Comment by ajluk** [comment]
@MartaSztuka Testing this issue demands generating rex-preview for organic-chemistry. It can be done by checkout on branch `rex-preview` on enki and then using the `all-git-web` command, e.x. `./enki --data-dir ./data/organic-chemistry --command all-git-web --repo osbooks-organic-chemistry   --book-slug organic-chemistry  --style organic-chemistry  --ref main` and then use `rex-preview` command e.g. `./enki --command rex-preview --data-dir ./data/organic-chemistry`. There will be links available in the console.Please open one in the browser. If the styles changes for mechanism figures can't be seen yet (I'm not sure here) please add at the end of the generated lins `&content-style=https://raw.githubusercontent.com/openstax/ce-styles/7787b77814d8921abacb71125d811b3f52abf6e5/styles/output/webview-generic.css`.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-09-02 13-03-28](https://user-images.githubusercontent.com/47241114/188126273-fb46fc84-a216-43fd-9192-ba49d4c3603f.png)

![Screenshot from 2022-09-02 13-03-41](https://user-images.githubusercontent.com/47241114/188126316-814624b3-30d7-40e9-b2c2-f5ab818ef740.png)

![Screenshot from 2022-09-02 13-03-47](https://user-images.githubusercontent.com/47241114/188126336-5e6b855d-4274-45eb-b52c-00a90417558a.png)
