### ISSUE TITLE
Marketing Theme - PDF converting issue in CORGI (EOC Section Endnote callout)

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4838]
In the manuscript, the last 5 endnote callouts (28 to 32) are appearing in the EOC section. Also, the CORGI doesn’t support these endnote callouts in EOC section, as a result, the PDF also not converted in CORGI, refer the below screenshots. Kindly check and resolve this issue.

**Input MS:**
![CC_Input](https://user-images.githubusercontent.com/86622862/186800382-b2f6769a-6ae1-41c5-95bc-50d9d9ee6ecf.png)

**CNXML:**
![CC_CNXML](https://user-images.githubusercontent.com/86622862/186800663-3698c306-a8cd-46f1-ac4e-8633aadc8fae.png)

**CORGI:**
![CC_CORGI_Error](https://user-images.githubusercontent.com/86622862/186800678-2f7623cf-c633-4b15-b7a8-9e17da1ada31.png)

# Acceptance Criteria 
The links are being changed once the EOC section moves and they are no longer referencing themselves and causes a broken link. Not sure if there is a way for moved items to get the page id attached to links for the references?

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-marketing
- **collection slug:** principles-marketing
- **ref/branch:**  https://github.com/openstax/osbooks-principles-marketing/tree/testing-gh-4838
- **chapter/section:** Chapter 4/Section 5
- **surrounding text:** 1995, with one person, one computer, and one client

**Comment by lwtchu** [comment]
Investigate the fix first. If it's a bit complicated, we can explore maybe a content fix

**Comment by wilkus27** [comment]
@lwtchu I looked into it and this is how it works now:

In assembled file we have such elements:
```
page(id=some1)
  cite(id=foo1, href=bla1)
  section_to_eoc
    cite(id=foo2, href=bla2)
  section.references
    note(id=bla1, href=foo1)
    note(id=bla2, href=foo2)
page(id=some2)
  cite(id=foo3, href=bla3)
  section_to_eoc
    cite(id=foo4, href=bla4)
  section.references
    note(id=bla3, href=foo3)
    note(id=bla4, href=foo4)
```
During baking we change id of cite elements and href of note element. Cite id is created by `#{page.id}-endNote#{cite.count_in(:chapter)}` and note href by `#{page.id}-endNote#{note.count_in(:chapter)}`. So this step should be done before sections are moved to eoc (to be able to get page id), but then we will have such situation:

```
page(id=some1)
  cite(id=some1-endNote-1, href=bla1)
page(id=some2)
  cite(id=some2-endNote-3, href=bla3)
composite-page
    cite(id=some1-endNote-2, href=bla2)
    cite(id=some2-endNote-4, href=bla4)
composite-page.references
    note(id=bla1, href=some1-endNote-1)
    note(id=bla2, href=some1-endNote-2)
    note(id=bla3, href=some2-endNote-3)
    note(id=bla4, href=some2-endNote-4)
```
So links gonna be working properly, but cite numbering will be messy. In content we will see cites in such order: 1, 3, 2, 4. 
Is it ok or do we want to make a content fix (remove cites from eoc sections) in that case?

**Comment by wilkus27** [comment]
### Update

We are going to use existing ids (created in the content) not create them by recipy.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-09-19 at 16.02.02.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7da59406-0e3d-4aa0-ad10-1652fde9faa7)
