### ISSUE TITLE
Marketing Theme - Figure label punctuation missing issue in Appendix

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4841]
We have coded figure captions are as per the tagging legend. But punctuation missing in output (PDF & Webview). Please see the below screenshots. Kindly check and resolve this issue.

**Input:**
![App_Fig_Caption_Input](https://user-images.githubusercontent.com/86622862/186828200-330c0a28-7668-4bb0-b47a-07f01029dd0d.png)

**Output:**
![App_Fig_Caption_Output](https://user-images.githubusercontent.com/86622862/186828214-2243b84b-14b0-4c14-b356-6a5084e6a8df.png)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-marketing
- **collection slug:** principles-marketing
- **ref/branch:** main [https://openstax-osbooksprincip-ifukm04n2xb.ws-us63.gitpod.io/]
- **chapter/section:** Appendix/Section A1
- **surrounding text:** disclosures to share the impact of ESG efforts

**Comment by lwtchu** [comment]
@srm-openstax We don't typically do punctuation on the Appendix figures and would require a library-wide change. Suggestion to leave as is for now and closing the card. Please reopen if you feel this is extremely high priority.
