### ISSUE TITLE
Organic Chemistry - Table caption

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#4844]
#### Table caption font and top margin are too big.
![Screenshot from 2022-08-29 13-46-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/679e16fb-bb06-4480-952f-db0365040b92)
![Screenshot from 2022-08-29 13-46-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/146a2a79-6a5a-4cbb-a0f0-08e0bde5b9b5)
#### caption for Figure:
![Screenshot from 2022-08-29 15-48-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5e95750d-78f3-401c-8476-19b76a9eb81c)
![Screenshot from 2022-08-29 15-48-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e618eed6-1365-40d5-995a-fd9620894114)

**Comment by lwtchu** [comment]
@LostMojo can we have them match the figure caption?

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-09-07 11-02-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2d841a24-b12e-40d6-be1b-c1569fe274f8)

![Screenshot from 2022-09-07 11-04-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0604b98d-3bc1-4406-ae3e-942c901009eb)
