### ISSUE TITLE
Marketing and Accounting - Index page colored text style update

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4845]
We have received the below feedback from customer. Kindly check and update this issue.

**If a company name (such as “Chevy” in the “C” section below) is tagged for both red font treatment and indexing,
Can you please suggest whether it’s possible to have the red font for companies appear just in the chapter, but not in the index?
In other words, I would like to have the index terms all appear just in regular, black font.**

![thumbnail_image001](https://user-images.githubusercontent.com/86622862/187918884-9016101c-2135-4c31-8f74-beb726833be9.png)

# Acceptance Criteria
- [ ] Red text is now targeted by `<span class="red-text">` - please update the CSS as it is no longer using `<emphasis class="colored-text">`
- [ ] Please remove <span> styling in the Index
- [ ] This will also impact Accounting - I am updating content now. 

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-marketing
- **collection slug:** principles-marketing
- **ref/branch:** https://openstax-osbooksprincip-6m1z7lkqavu.ws-us63.gitpod.io/
- **chapter/section:** Chapter 4/Section 1(Global)
- **surrounding text:** B2B and B2C components. For example, consider 

Content for Accounting: https://github.com/openstax/osbooks-principles-accounting-bundle (principles-financial-accounting and principles-managerial-accounting) can check for brands like Tesla, Apple, Disney, etc

**Comment by lwtchu** [comment]
Working with SRM to see when it is a good time to switch the tagging to `<span class="red-text">` ; will update card once content is ready

**Comment by lwtchu** [comment]
CONTEXT FOR DEV: Change was introduced due to this card: https://github.com/openstax/cnx-recipes/issues/4789 ; if you are working on this card and need more context please contact me or @wilkus27

**Comment by MartaSztuka** [comment]
#### PASSED
##### MARKETING
![Screenshot from 2022-09-13 16-44-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9fccb403-0618-43a7-81b2-0af7be31bda8)

![Screenshot from 2022-09-13 16-44-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/51980957-f067-4cd5-abae-7673099a502e)

![Screenshot from 2022-09-13 17-08-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/09cebe11-2dda-4282-b180-07b73f8cf718)

##### FINANCIAL ACCOUNTING
![Screenshot from 2022-09-13 17-06-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2a71b102-2b3c-4e97-a688-8fd62fc5fbb8)

![Screenshot from 2022-09-13 17-08-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/764530c8-ac2c-4c07-aa9e-94429a785489)


##### MANAGERIAL ACCOUNTING
![Screenshot from 2022-09-13 17-09-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/918208c3-5a5f-4003-8565-3de3bcd764f6)

![Screenshot from 2022-09-13 17-10-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f13c2299-b7ed-4ee9-be04-1d7156e1829e)

**Comment by srm-openstax** [comment]
We have received the below feedback from customer. Kindly check and resolve this issue. Please find the example screenshots below.

**“The red font not appearing in the web view (okay in PDF).”**

![redfont](https://user-images.githubusercontent.com/86622862/194220011-2773125f-a244-481d-acee-2b30f56405b8.png)
![redfont1](https://user-images.githubusercontent.com/86622862/194220022-74530e65-7f43-4bd5-bb87-a5d034d47fdd.png)

**Comment by lwtchu** [comment]
@wilkus27 it should be the same on webview. we developed the few in text colors with the rex team a while back to make sure this will work for accessibility with the highlighting - it's this one right R1: `#CC0000`

**Comment by MartaSztuka** [comment]
#### PASSED
##### MARKETING
![Screenshot from 2022-10-20 12-00-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4e92fe5d-2a48-4966-b464-d9041671b80c)![Screenshot from 2022-10-20 12-10-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b7f226ae-a9dd-491c-9983-348c5e469211)

##### MANAGERIAL ACCOUNTING
![Screenshot from 2022-10-20 12-42-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2c770abf-b798-4dbe-9acf-234a4bcd0f14)

##### FINANCIAL ACCOUNTING
![Screenshot from 2022-10-20 13-09-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5d517e6e-960a-45e0-909a-4e2b2295e796)

**Comment by lwtchu** [comment]
Fix isn't on CORGI or REX yet - need to coordinate this code version with CE and REX team
