### ISSUE TITLE
baked styles refactor - lists in corn

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4846]
Part of https://github.com/openstax/cnx-recipes/issues/4694

- [x]  Corn - Stepwise lists - create separate shape for them like in Cardboard.
- [x]  Corn - create separate shape for EOS lists.
- [x]  Corn - create separate shape for circled lists. Make sure to style tokens from paragraphs and from labeled lists.
- [x]  Corn - move tables components to tables shapes.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Statistics
![Screenshot from 2022-11-29 10-37-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8d630f5a-90e4-461d-8c4f-275a896e1e01)

![Screenshot from 2022-11-29 10-38-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/13812f04-ba49-4582-9762-e04032b93cdf)

![Screenshot from 2022-11-29 10-38-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ab9d08ed-e255-4573-85e6-40a2d9c86bd1)

![Screenshot from 2022-11-29 10-39-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1cfbab4f-2915-48eb-b4aa-218adceb3ae2)

##### Contemporary math
![Screenshot from 2022-11-29 11-00-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f46239bf-3eb3-42d7-83e3-65109d540763)

![Screenshot from 2022-11-29 11-06-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/94f24a81-61be-427f-bb74-352d9d7dda7d)

##### Calculus 1
![Screenshot from 2022-11-29 11-38-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/42839055-5464-4736-8173-b370759cb5fe)

![Screenshot from 2022-11-29 11-38-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/34b3da64-1187-4982-8dac-0636c6c3cdf5)

![Screenshot from 2022-11-29 11-39-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1c061696-571e-4b1d-b5ad-9c3bd63c7cf6)

##### College Algebra coreq
![Screenshot from 2022-11-29 12-41-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ead16fcb-0209-4be3-9d1e-1d0bc177ba58)

![Screenshot from 2022-11-29 12-42-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f8df245a-7bd5-42a3-913d-d0de1b9fdeea)

![Screenshot from 2022-11-29 12-43-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c47f3cd1-6af9-4de3-bdac-1986dbd65295)

![Screenshot from 2022-11-29 12-45-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b0d3a95c-4fda-47ed-9b51-48a364dc00ac)
