### ISSUE TITLE
World History - Change Learning Objectives from Numbered List to Bulleted List

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4848]
# Brief Description of Scenario
Please change Learning Objectives from Numbered List to Bulleted List
Learned Objectives should appear as Bulleted List like this example from Chemistry:
![image](https://user-images.githubusercontent.com/89537088/187997378-4da99cc3-69aa-462c-8383-5286a3afa7e3.png)

QUESTION: How are bulleted learning objectives indicated in metadata? How can assessment questions be tagged to point to individual LO?

# Pattern of Occurrence 
Every Instance of LO

# Acceptance Criteria
- Learning Objectives will be a Bulleted List
- Please have bullets match the header color BR1: `#8B693A`
  
# Sample Mark-Up
```
<section class="learning-objectives" id="sect-00001">
    <title>Learning Objectives</title>
    <para id="para-00001">By the end of this section, you will be able to:</para>
    <list id="list-00001">
    <item>Describe the effects on everyday life of the major innovations of the late nineteenth and early twentieth centuries</item>
    <item>Analyze the ways in which <term class="no-emphasis" id="term-00001">technology</term> and <term class="no-emphasis" id="term-00002">mechanization</term> affected the industrial work experience</item>
    <item>Explain how the <term class="no-emphasis" id="term-00003">working-class family</term> changed because of <term class="no-emphasis" id="term-00004">industrialization</term></item>
    </list>
    </section>
```

# Location(s)
- **osbooks repo:** osbooks-world-history
- **collection slug:** world-history
- **ref/branch:**
- **chapter/section:** all chapters / section class="learning-objectives"
- **surrounding text:**

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-09-16 at 15.04.22.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b0b65604-fb3b-45fe-9f6d-4a96cd7be314)
