### ISSUE TITLE
Cookbook - remove or stabilize IDs generated at bake time

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4850]
# Brief Description of Scenario

As we know, IDs must be unique to an HTML document for that document to be valid. An additional requirement for IDs comes from Rex's highlighting feature: since highlights are anchored by ID to the content, if an ID changes (for example, in subsequent iterations of the book generation pipeline) the user's highlight will break. Therefore, IDs created by cookbook need to be as stable as possible, and should be avoided in favor of IDs that originate in the cnxml.

Documentation for new ID behavior & list of current cookbook ID transformations: https://openstax.atlassian.net/wiki/spaces/~899755122/pages/2115436545/Adds+IDs+to+elements 

Thread for context: https://openstax.slack.com/archives/CH5514N57/p1662050910202659

# Acceptance Criteria
- All IDs that can be are removed from cookbook & replaced with IDs created by POET
- Unstable IDs are stabilized (or have `nonstatic_` prepended to the ID)
  
# Location(s)
- **osbooks repo:** 
- **collection slug:**
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:**

**Comment by philschatz** [comment]
Can Katalyst add the `id="..."` attribute to `<term>` elements?

The value of the attribute does not matter as long as it is unique. For example, POET auto-injects `id="term-000001"` but the value could be anything. Here is an [example diff](https://github.com/openstax/osbooks-fizyka-bundle/compare/add-id-to-term) that changes all the attributes in the fizyka repo

**Comment by lwtchu** [comment]
Closing until this becomes a larger issue later.
