### ISSUE TITLE
Marketing Book Theme - Center alignment issue in PDF output

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4851]
We have coded as per the tagging legend. But, center alignment element didn't support in PDF output. This element is working fine in web-view. Please find the below screenshots. Kindly resolve this issue.

**Tagging Legend:**
![equation-tagginglegend](https://user-images.githubusercontent.com/86622862/189579834-9f3f5172-7971-4d7d-91b9-cd0df070595c.png)

**PDF View:**
![equation-pdfoutput](https://user-images.githubusercontent.com/86622862/189579847-e2ddf311-d789-46e2-844d-a1ea6c5910b1.png)

**Web View:**
![equation-webviewoutput](https://user-images.githubusercontent.com/86622862/189579856-69fb2d6f-b3a4-4d6b-9907-648fee7150e6.png)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-marketing
- **collection slug:** principles-marketing
- **ref/branch:** https://openstax-osbooksprincip-4kwuicssrly.ws-us64.gitpod.io/
- **chapter/section:** Chapter 10/Section 3
- **surrounding text:** the marketing campaign was $20,000, the ROI would be:

**Comment by srm-openstax** [comment]
This problem has now been fixed in the output PDF. So we are closing this ticket.

**Comment by srm-openstax** [comment]
We have coded [equation class="unnumbered] as per the above solution. But, still now we faced the alignment issue in PDF version. Please find the screenshots. Kindly check and resolve this issue.

![image](https://user-images.githubusercontent.com/86622862/194468989-4dbedc17-8246-419b-8e88-b6bca754f4fc.png)

![image](https://user-images.githubusercontent.com/86622862/194469217-6698137b-2c90-485e-bf9b-fe68b3476565.png)

**Note:** Actually, this alignment is converted correctly in previous version. Please find below previous and current version links:
Previous version link: [https://openstax-cops-artifacts.s3.amazonaws.com/principles-marketing-latest-git-7682.pdf]
Current version link: [https://openstax-cops-artifacts.s3.amazonaws.com/principles-marketing-latest-git-7825.pdf]

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
---
![CleanShot 2022-10-14 at 10.05.44.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c521e526-a9f0-4145-a456-857fb1219c54)

---

![CleanShot 2022-10-14 at 10.04.41.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b37275ac-5a83-4517-bdbc-fb7072f796a9)

**Comment by srm-openstax** [comment]
We have received from customer, the below additional correction for equation. So, kindly include the below point and update the style.

**Could Production add a comment that, in the PDF output, some vertical spacing (white space / blank row or line) should also be added above and below the formulas, so that they resemble the HTML view, which is acceptable.**

**Comment by lwtchu** [comment]
@srm-openstax the spacing in the PDF is standard to keep the page count down. if there is a high priority need to increase spacing, we will explore but at this time i would prefer to keep it as is

**Comment by lwtchu** [comment]
@srm-openstax  please add an `unnumbered` class on the equation

**Comment by srm-openstax** [comment]
Resolved this issue. Thanks for your support.
