### ISSUE TITLE
webview styles - index missing styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4853]
# Brief Description of Scenario
Disco released baked styles for web for [_Organizational Behavior_ ](https://rex-web-organizational--ufhnxb.herokuapp.com/books/organizational-behavior/pages/index)

Styling still exists on Disco, so we should double check to see what the original specs were. Please ask someone on the team if needed.

## What it looks like now
![Screen Shot 2022-09-12 at 12 20 45 PM](https://user-images.githubusercontent.com/11299125/189716922-ea49407b-0808-4c20-a524-91c0f767eafd.png)
https://rex-web-organizational--ufhnxb.herokuapp.com/books/organizational-behavior/pages/index

## What it should look like
![Screen Shot 2022-09-12 at 12 21 18 PM](https://user-images.githubusercontent.com/11299125/189717010-7e2ab446-b91c-44d1-8ac7-84f1724ee5d9.png)
https://openstax.org/books/organizational-behavior/pages/index

# Pattern of Occurrence 
Just the index

# Acceptance Criteria
- [ ] titles for each section (Symbols, A, B, C, etc) have header styling
- [ ] terms are bolded
  

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-of-management-bundle
- **collection slug:** organizational-behavior
- **ref/branch:** N/A
- **chapter/section:** index
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-09-28 10-03-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9c55a352-09e5-4bf2-81ab-14b5c7893f13)
