### ISSUE TITLE
webview styles - scaled-down and scaled-down-60 not working

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4854]
# Brief Description of Scenario
Disco released baked styles for web for [_Organizational Behavior_ ](https://rex-web-organizational--ufhnxb.herokuapp.com/books/organizational-behavior/pages/index)

Styling still exists on Disco, so we should double check to see what the original specs were. Please ask someone on the team if needed.

## What it looks like now
![Screen Shot 2022-09-12 at 12 46 38 PM](https://user-images.githubusercontent.com/11299125/189721859-2f6d3627-98c4-440a-b504-7d6c8d98a244.png)
![Screen Shot 2022-09-12 at 12 46 44 PM](https://user-images.githubusercontent.com/11299125/189721872-f1735ede-d7fa-40bd-bb9c-3d2f46ba3844.png)
https://rex-web-organizational--ufhnxb.herokuapp.com/books/organizational-behavior/pages/1-2-the-changing-workplace

## What it should look like
![Screen Shot 2022-09-12 at 12 46 57 PM](https://user-images.githubusercontent.com/11299125/189721996-dcf90947-cb34-4bac-8d4b-63283d9aa16a.png)

https://openstax.org/books/organizational-behavior/pages/1-2-the-changing-workplace

# Acceptance Criteria
- `scaled-down` class should scale art down xx%
- `scaled-down-60` class should scale art down xx% - i assume 60% but need to check with Disco
  

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-of-management-bundle
- **collection slug:** organizational-behavior
- **ref/branch:** N/A
- **chapter/section:** index
- **surrounding text:**

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/bd7f471a-00a9-4fa5-a9e5-f723cde3f364)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-09-27 12-44-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fe623cbb-4074-48e6-be10-4ae27a5d613b)
