### ISSUE TITLE
investigate id in BakeChapterReferences.v2

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#4856]
[ID added in direction](https://github.com/openstax/cookbook/blob/main/lib/kitchen/directions/bake_chapter_references/v2.rb#L26)

IDs are added in CNXML & overwritten by this line. Investigate whether the transformed ID can be removed without impacting performance.

(may help solve #4838)

### Acceptance Criteria

- If the ID can be removed, ID is removed
- If the ID cannot be removed, comment on issue with reason

**Comment by wilkus27** [comment]
Tested within https://github.com/openstax/cnx-recipes/issues/4838. Closing the issue.
