### ISSUE TITLE
Change Table styling in Features in Introductory Statistics and Introductory Business Statistics

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#4857]
# Brief Description of Scenario
In preparation for the 2nd edition of Intro Stats and Biz Stats, Colby reviewed the PDFs for both titles and noticed tables within features may be difficult to read with the grey background. See his note below with a screenshot:

Table styling in features could be improved from readability. The light grey background in features makes it hard to see the light grey cell padding. I'd recommend modifying the cell padding color to have more contrast with the background.

![Screen Shot 2022-09-15 at 3.02.48 PM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/5796b5db-5694-49b5-b997-f70a54d1e10e)

# Pattern of Occurrence 
This happens every time a table is nested within a feature with a grey background, such as Try Its.

# Acceptance Criteria
Tables in features no longer have a grey background. Perhaps a white background to provide contrast and help readability.

Change Grey1: `#F9F9F9` to Grey2: `#757474` for cell borders. Can be done across theme?
  

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introductory-statistics-bundle
- **collection slug:** introductory-business-statistics ; introductory-statistics
- **ref/branch:** main
- **chapter/section:** throughout

**Comment by wilkus27** [comment]
I want to make sure in which direction we want to go :relaxed: 

- Here is what it looks just with darker border:

In note
![image](https://user-images.githubusercontent.com/40228854/194295710-55a0578c-5a51-448a-8fb8-0153997f56af.png)

On page
![image](https://user-images.githubusercontent.com/40228854/194295815-d690003b-7e76-4429-9e19-a4badb8294f5.png)

- Here also with white background:

![image](https://user-images.githubusercontent.com/40228854/194296038-8b4118f8-6fb6-4a4c-9b4c-38f7e4e05261.png)

- If we want to change border color just in tables from notes with colored background, it will be more complicated. Each book has different features (with different classes), so it's hard to set a selector for styles. We should probably add one additional common attribute (it may be class) either to notes with colored background or directly to tables.

**Comment by lwtchu** [comment]
@wilkus27 can we go with a non-white/transparent background for now? i think the text works on the bg, it was only the lines that were hard to see

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![CleanShot 2022-10-12 at 17.15.17.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/36fc8010-85cb-42bd-9f6c-b1d12907f061)![CleanShot 2022-10-12 at 17.14.37.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e679ef13-ea74-440d-b1f8-ea3bcdba875e)
