### ISSUE TITLE
Add icon styling to NOTE and REMINDER features in Introductory Statistics and Business Statistics 

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#4858]
# Brief Description of Scenario
During Colby's review of Intro Stats and Business Stats, he noted it might be nice to have some special styling for features titled "Note" and "Reminder" to better suit other features within the book (see examples below). 

![Screen Shot 2022-09-15 at 3.03.33 PM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/f22b92cb-9479-460a-a45f-6b83dcdee67e)
![Screen Shot 2022-09-15 at 3.05.42 PM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/5d862430-b5b7-43d9-882b-03868fcc578e)

# Pattern of Occurrence 
All "Note" and "Reminder" features

# Acceptance Criteria
If styles can add an icon or something to the features. 
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introductory-statistics-bundle
- **collection slug:** introductory-business-statistics ; introductory-statistics
- **ref/branch:** main
- **chapter/section:** throughout

**Comment by lwtchu** [comment]
:( there's no classes on these notes, so i can't target them to add an icon. but i did change all the titles to CAPS so it'll stand out more and be in line with the other stuff.
