### ISSUE TITLE
Support H4 titles within sections in Introductory Stats and Business Stats

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#4859]
# Brief Description of Scenario
H4 titles within sections are currently not supported, and they are unstyled in the PDFs. We need this fixed in preparation for 2e production beginning early next year.

Example: Introduction to chapter 4 in Business Statistics:

![Screen Shot 2022-09-15 at 3.21.48 PM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/d48804b4-0b36-445f-8413-cebc8fa5738a)

# Pattern of Occurrence 
Rare. this might be the only occurrence, at least in Biz Stats.

# Acceptance Criteria
H4 titles in a section are styled; specs found here: https://github.com/openstax/cnx-recipes/issues/2144 
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introductory-statistics-bundle
- **collection slug:** introductory-business-statistics ; introductory-statistics
- **ref/branch:** main
- **chapter/section:** chapter 4 intro
- **surrounding text:** Combinational Formula

**Comment by lwtchu** [comment]
This might be because it's in the Intro module

**Comment by wilkus27** [comment]
@lwtchu I noticed that equation under this title is not styled, so I made a fix for that as well:

![image](https://user-images.githubusercontent.com/40228854/191918058-7a69ada6-f34f-4a8c-b459-d837c69358c0.png)

**Comment by lwtchu** [comment]
@wilkus27 oh awesome - do you know if they're styled across the book? if not i can make a separate card

**Comment by wilkus27** [comment]
@lwtchu They're styled in a whole book now :wink:

**Comment by MartaSztuka** [comment]
#### PASSED
###### BUSINESS STATISTICS
![Screenshot from 2022-09-26 13-11-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2fd44b34-b6ae-4920-bd12-cdfb8bfa193a)

###### STATISTICS
![Screenshot from 2022-09-26 13-17-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f41e8a13-6640-4d73-8b6a-04ca6ee8ea16)
