### ISSUE TITLE
World History -- Chinese Characters Not Displaying in PDF

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4860]
# Context
Chinese Characters display in Web View but do NOT display in PDF
Web View  
![image](https://user-images.githubusercontent.com/89537088/190504588-d32338c3-d2c9-49fb-bb7a-14f6f65bbc2e.png)

PDF
![image](https://user-images.githubusercontent.com/89537088/190505335-62c89ff3-1ec3-46e4-98d7-ed5a4b9c8a89.png)

# Acceptance Criteria
Chinese characters display in PDF

# Content
## Sample Mark-Up
```
<caption>Mao Zedong. This 1967 artist&#8217;s rendering of Mao Zedong greeting a cheering Chinese public during the Cultural Revolution shows loyal party members following him and holding the Little Red Book that contained his most popular sayings. (credit: modification of work &#8220;1967-11 1967年 毛泽东接见红卫兵油画&#8221; by《人民畫報》1967年/Wikimedia Commons, Public Domain)</caption>

```

## Location(s)
- **osbooks repo:** osbooks-world-history
- **collection slug:** world-history
- **ref/branch:**
- **chapter/section:** Module m00033; Chapter 9 (currently) "Cold War Conflicts"; Introduction
- **surrounding text:** Caption of Figure 9.1 of Introduction

**Comment by lwtchu** [comment]
@ww-openstax We don't support Chinese characters. Can you please add a translation (below) of the credit? 

`modification of work "1967-11 1967 Oil Painting of Mao Zedong meeting the Red Guards" by China Pictorial 1967/Wikimedia Commons, Public Domain`

Thank you!

**Comment by ww-openstax** [comment]
Thanks!
