### ISSUE TITLE
World History -- Change Assessment Heading Output

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4861]
# Context
Please change text output of End of Chapter Assessment Headings as indicated below:
"Check Your Understanding" please change to "Check Your Understanding Questions"
"Reflection Questions" please change to "Application and Reflection Questions"

What is the the function of the "section/title" tag in the EOC sections? The headings appear to be generated by the "section" tag. Changing the text of the "section/title" tag or even deleting the "section/title" tag from all modules within a chapter has no effect on the output or validation.

Thanks!

# New specifications or link to documentation cards
![image](https://user-images.githubusercontent.com/89537088/191544308-acee44fd-a1a2-4efd-8296-1a367a75a08c.png)

## Impact 
All chapters in book World History 

# Acceptance Criteria
section class="check-understanding" will output heading "Check Your Understanding Questions"
section class="reflection-questions" will output heading "Application and Reflection Questions"
# Content
## Sample Mark-Up
Desired change:
```
<section class="check-understanding">
  <title>Check Your Understanding Questions</title>
</section>
<section class="reflection-questions">
  <title>Application and Reflection Questions</title>
</section>
```

## Location(s)
- **osbooks repo:** osbooks-world-history
- **collection slug:** world-history
- **ref/branch:**
- **chapter/section:** all chapters / section class="check-understanding" and section class="reflection-questions"
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax It's mostly so people editing the content can see what section it is - we auto inject the title with the code so it can keep the styling and spelling consistent across all the chapters. we can make the change in the code for you and it'll impact the entire book

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-09-28 10-05-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5f8a3ab6-5b3f-4cc2-91e8-5e75f63e138a)
