### ISSUE TITLE
Change behavior of `ElementBase#copy` to ignore IDs

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#4866]
# Context
Part of push to remove IDs from cookbook.

`ElementBase#copy` handles copying an element. Currently, it handles copying an element ID by appending `_copy_#` to the ID & tracking the number of copies. 

However, 1) there don't seem to be instances of copied elements with IDs in the library anymore, and 2) in the case that there may be copied elements with IDs in the future, it's unlikely that there will be a utility for the copied element's ID. 

# New specifications or link to documentation cards

Change this functionality to not put an ID attribute onto a copied element, even when the original has an ID. All copy number tracking can also be removed/deprecated.

See first item in [the table](https://openstax.atlassian.net/wiki/spaces/~899755122/pages/2115436545/Adds+IDs+to+elements) for more

## Impact 
All books, HTML only, not visible in content

# Acceptance Criteria

- [ ] No IDs ending in `_copy_#` present in content

(This will be hard to test because I don't believe that (outside of our tests) there's an element in the library that this functionality applies to anyway. This may be an implementation-only change.)

**Comment by Stackblocks** [comment]
As stated earlier, without a visual output testing is a bit different from usual but if it's passing the spec tests and i'm not seeing anything wildly out of place on a cursory glance across the library i'd say we're good to go.

Didn't spot any deformations in Anthropology, Astronomy, Calculus, or Economics.

--- 
_(Grepping for the string, just in case)_

**Control Search**
![CleanShot 2022-11-11 at 12.27.35.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6891db51-dec1-45b9-9f55-27dde3c8ba96) (it goes on)

**Test Search**
![CleanShot 2022-11-11 at 12.32.08.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8fd9bb84-b654-4c0e-a6bb-b5224d3d6df2)
