### ISSUE TITLE
computer programming python - splash image

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4867]
Documentation: https://github.com/openstax/cnx-recipes/issues/2642
Blue version

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-10-12 at 13.10.00.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/165c7c2f-80b7-4acc-a87f-905f07c0bb69)
