### ISSUE TITLE
[webview] fix long equations

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4868]
Part job was done within https://github.com/openstax/cnx-recipes/issues/4686. 

There was a problem with webview styles being overide by basic styles (https://github.com/openstax/cnx-recipes/issues/4686#issuecomment-1240366392). 

## Acceptance Criteria
The math container scrolls horizontally when overflow occurs and does not overflow the parent container.

## Example of wrong behaviour
https://openstax.org/books/chemistry-2e/pages/1-6-mathematical-treatment-of-measurement-results
![image](https://user-images.githubusercontent.com/40228854/192277781-2d8ceb6c-6be7-4a64-9c6f-a7affe7249e7.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-09-27 11-28-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/87d1ccfb-8f7a-4112-bc91-fb7b266542e7)

![Screenshot from 2022-09-27 11-28-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/32f43e79-3180-42a3-a418-960d7b4802d8)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-09-27 12-12-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9ef1c234-e096-4144-b736-aa64108dadc3)

![Screenshot from 2022-09-27 12-12-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bd3aaa8c-efc3-4cad-9a9a-6853b914d9cb)
