### ISSUE TITLE
computer programming python - section number treatment

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4873]
Documentation https://github.com/openstax/cnx-recipes/issues/2710 (blue version)

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-10-12 at 13.07.39.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d14769d7-8474-4938-ae23-44cbf7d64a9c)
