### ISSUE TITLE
computer programming python - learning objectives

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4874]
![Screen Shot 2022-09-27 at 3 56 14 PM](https://user-images.githubusercontent.com/11299125/192633740-d43a660e-aa6b-47ce-aead-558d9a046679.png)

Documentation https://github.com/openstax/cnx-recipes/issues/2711
Blue version - please use bulleted list

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-10-13 at 14.09.44.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ff0938bd-cc49-42e4-952b-2db8fe117e0d)
