### ISSUE TITLE
computer programming python - code snippet and code styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4877]
Documentation/work done with highlight.js #3750 - please make sure this is enabled and ready to go

## Font specs
font style: courier prime
font size: scale(0) 9pt

## Colors to match zyBooks output
Based on [CSS stylesheet that zyBooks is using](https://drive.google.com/file/d/1-fOUTuvfyk9m-CvFTTluVgbZkc4r3UzG/view?usp=sharing)

`hljs-comment` = `#5c5c5c`
`hljs-keyword` = `#0000aa` 
`hljs-function` = `#006900`
`hljs-title` = Grey 5: `#5C5C5C`
`hljs-params` = black `#000000`
`hljs-string` =  `#914700`
`hljs-built_in` = `#006464`
`hljs-number` =  `#006767`

The blocks should be using the class python or lang="python" with the display="block" attribute to have it space out correctly.

## Acceptance criteria

- [ ] code snippets are styled with a monotype font 
- [ ] highlight.js is auto adding classes to python components
- [ ] the colors from the classes match the list above

**Comment by wilkus27** [comment]
@lwtchu highlight.js probably should be enabled in some of the step of generating book. In `finance` all needed classes are already visible in assembled file. I can't check `computer-science` because there is some content problem.

This file should be named `introduction-computer-science.collection.xml`
![image](https://user-images.githubusercontent.com/40228854/195059457-1a0d14c7-cffe-4e0b-99b4-c4d77b6d4830.png)


Here, in `python` book, there are no hilight classes for now. I'm not sure which team we should contact with :thinking:

**Comment by lwtchu** [comment]
@wilkus27 so the way it was set up was that the `code class="python"` in the CNXML and it should trigger the highlight.js to add the class? In the process? can you tell from the old PRs how it gets activated? if not i can try to ask phil but he's on vacation

**Comment by wilkus27** [comment]
@lwtchu As I checked, in old PRs there are only regular changes for styles. There is no code for adding classes. In finance book classes exists in assembled file, so it wasn't changed in cookbook or styles. Unfortunatelly there is no PR linked to issue for computer-science :crying_cat_face: Maybe the change was done in another repo :thinking:

**Comment by lwtchu** [comment]
@wilkus27 x_x ok i will ask around

**Comment by wilkus27** [comment]
### Update

Styles change is merged. Waiting for changes in function for highlights (https://katalysteducation.slack.com/archives/C022NETP39N/p1665734026939539)

**Comment by lwtchu** [comment]
@wilkus27 I made a new card for the inline snippets - can this card be just for testing the code blocks?

**Comment by wilkus27** [comment]
@lwtchu Sounds good to me :+1: I will move it to **Ready for testing** column.

**Comment by MartaSztuka** [comment]
@lwtchu Those classes are missing in the content (we might want to add them for testing purpose)
###### hljs-keyword

###### hljs-function

###### hljs-title

###### hljs-params

###### hljs-number

#### PASSED
###### hljs-comment
![Screenshot from 2022-10-20 11-24-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cdbce761-a760-4423-a8b2-55412bc4145f)

###### hljs-string
![Screenshot from 2022-10-20 11-14-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/71a35b2d-62b1-445d-8002-9dcb37ddc2aa)

###### hljs-built_in
![Screenshot from 2022-10-20 11-16-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/48f0b69e-f1be-40e9-846b-069990dec849)
