### ISSUE TITLE
computer programming python - checkpoint feature 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4879]
Documentation https://github.com/openstax/cnx-recipes/issues/2737
color option 5
Title: white `#FFFFFF`
Top bar: B2: `#344456`
Bottom box: B5: `#D6D9DD`

Class: `<note class="guided-slides">`
title: Checkpoint
NO SUBTITLE
NO ICON
Always contains an iframe

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-10-13 at 11.23.46.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/48d7c09d-699f-45fa-aabe-eabfdfef10b2)
