### ISSUE TITLE
computer programming python - concepts in practice

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4880]
Documentation https://github.com/openstax/cnx-recipes/issues/2737
color option 2
Title: white `#FFFFFF`
Top bar: B4: `#24739E`
Bottom box: B6: `#D3E3EB`

Class: `<note class="learning-questions">`
title:  Concepts in Practice
Contains INJECTED EXERCISES. Please reset numbering per section. If there are answers, please put in answer key #4878 and have section headers 
Also contains a Subtitle

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content, resets properly at each new section. 

![CleanShot 2022-10-13 at 11.22.52.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ae5857ff-1f90-4f56-be70-b8e183f8c747)
