### ISSUE TITLE
computer programming python - try it

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4881]
Documentation https://github.com/openstax/cnx-recipes/issues/2737
color option 4
Title: B2: `#344456`
Outline color: Grey3: `#EAEAEA`
Outline width: 1px (0.08 rem)
Bar up top color: O2: `#D34D32`
Bar up top width: 4px (0.33 rem)

Class: `<note class="practice-program">`
title:  Try It
Containes iframe, text, and subtitle

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-10-13 at 11.24.50.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/87082a2d-bf8b-4765-8b74-3aa5790b3a3b)
