### ISSUE TITLE
computer programming python - index

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4882]
Documentation https://github.com/openstax/cnx-recipes/issues/2746

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-10-13 at 14.57.34.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5e255034-c759-4b24-b7b8-b75026d54f88)
