### ISSUE TITLE
World History - Change Introduction heading style to be parallel in design to Module heading

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4883]
# Context
Introduction is parallel to Modules in product structure and TOC, so should Introduction header be parallel in design?

![image](https://user-images.githubusercontent.com/89537088/193636358-8b29809c-154e-473e-aae5-7b8b3bd62e61.png)

# New specifications or link to documentation cards
Match styling of Introduction headings to styling of Module headings

## Impact 
Every chapter Introduction throughout book.

# Acceptance Criteria
styling of Introduction heading matches styling of Module headings

## Location(s)
- **osbooks repo:** osbooks-world-history
- **collection slug:** world-history
- **ref/branch:**
- **chapter/section:** all chapters / Introduction
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax this is the standard styling for introduction modules across this theme. proposing no change at this time
