### ISSUE TITLE
semi-broken links in Fizyka dla szkół wyższych Toms 1 & 2 

### ISSUE THREAD

**Issue by Jacqueline-Yarbrough** [openstax/cnx-recipes#4885]
# Brief Description of Scenario
There are 7 semi-broken links in Tom 1, and 3 semi-broken links in Tom 2. The links appear to be broken (they just look like [link]) but they still link to the correct place. Below is an example in Tom 1:

<img width="752" alt="Screen Shot 2022-10-04 at 3 07 57 PM" src="https://user-images.githubusercontent.com/75643768/193915878-98d5751c-1071-4ddb-9fe4-ba47eb9b04e9.png">

# Acceptance Criteria
The links should display the name of the destination instead of "[link]."
  
# Sample Mark-Up
```
– patrz <link target-id="CNX_UPhysics_03_03_SubTrain" cmlnle:case="nominative "/>. Rozumiemy je jednak jako przyspieszenie o zwrocie przeciwnym do kierunku ruchu, albo także jako ujemne przyspieszenie (piszemy jego wartość ze znakiem minus).</para>
```

# Location(s)
- **osbooks repo:** [osbooks-fizyka-bundle](https://github.com/openstax/osbooks-fizyka-bundle)
- **collection slug:** fizyka-dla-szkół-wyższych-tom-1 and fizyka-dla-szkół-wyższych-tom-2
- **chapter/section for Tom 1:** 3.3, 3.4, 3.4, 3.5, 3.5, 4.3, 7.1
- **chapter/section for Tom 2:** 2.3, 7.3, 6 answer key 
- **surrounding text:** search "[link]"

**Comment by lwtchu** [comment]
Maybe similar to the #4876

**Comment by wilkus27** [comment]
#### Volume I
All instances are content issues:

1. `#auto_827a747c-d0b2-40b7-94e6-9f658d35d894_CNX_UPhysics_03_03_SubTrain` - remove space after `nominative `
2. `#auto_3bf05d74-2357-47c9-9fe0-ad814f700488_fs-id1168326850769` - remove space after `locative ` 2x
3. `#auto_23d1adc0-5cd7-4746-b08b-44bba6b950d4_fs-id1168328328571` - remove space after `dative `
4. `#auto_23d1adc0-5cd7-4746-b08b-44bba6b950d4_fs-id1168328282779` - remove space after `dative `
5. `#auto_4d85eb93-c2f7-4c58-b336-485d1ec1f012_fs-id1165167586654` - is linking to unnumbered equation
6. `#auto_e2be6e76-4467-4cdb-8ab2-b4068c3c2ee5_CNX_UPhysics_07_01_Sum-Area`  - remove space after `locative `

**Comment by wilkus27** [comment]
#### Volume II

Content issues:

1. `#auto_1408f347-6447-4c50-b038-b13348ca21a1_imp-idm371591728` - is linking to unnumbered equation
2. `#auto_f2e8d5d1-4d5f-4a3d-8be9-775722b7e1e4_CNX_UPhysics_24_03_LineChg` - wrong name of case (denominator)

Recipe problems (to discuss with team):

1. `#page_0eeac5b5-aa82-43b8-914b-b49e968aa7d8` - target labels for pages are blocked in recipe

**Comment by wilkus27** [comment]
### Update

Page labels will be unblocked in recipe.

Here is an issue for all content problems: https://github.com/openstax-poland/content/issues/336

**Comment by MartaSztuka** [comment]
#### PASSED
##### Fizyka 1
###### 1.
![Screenshot from 2022-10-19 16-36-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fbca72b3-8f69-450c-9b70-d89adff9c98d)

###### 2.
![Screenshot from 2022-10-19 16-40-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/372bd320-f0cc-48b3-89b3-2d37100c666c)

###### 3.
![Screenshot from 2022-10-19 16-41-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a5f5efa4-d716-4ff6-8ef9-727b921ad313)

###### 4.
![Screenshot from 2022-10-19 16-41-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/65c7ede3-00f0-40ed-86d1-8ff560e18836)

###### 5.
![Screenshot from 2022-10-19 16-52-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6bea25c8-616e-4e98-b2d8-6dce2d4af75a)

###### 6.
![Screenshot from 2022-10-19 16-43-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ef12f031-41cb-40b9-a104-8e94d0c02f40)

###### 7.
![Screenshot from 2022-10-19 16-44-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9713f204-8fe0-42f8-a5c4-786c66f9c808)

##### Fizyka 2
###### 1.
![Screenshot from 2022-10-19 16-57-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/23c88321-6343-4282-acf3-dd570d775b81)

###### 2.
![Screenshot from 2022-10-19 16-58-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bcc66f6e-5517-4f45-8bc6-838547d51679)
