### ISSUE TITLE
Marketing Book Theme - Unnecessary hyperlinked underline under the hyperlinked superscript number

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4886]
We have received the below feedback from customer. Please find the below screenshots. Kindly check and resolve this issue.

**There’s an extra/unnecessary hyperlinked underline under the hyperlinked superscript number.**

**Web View:**
![endnote1](https://user-images.githubusercontent.com/86622862/194222082-ea4f6974-bf8e-494d-973c-2e0cfc171dd7.png)

**PDF View:**
![endnote2](https://user-images.githubusercontent.com/86622862/194222114-3c6ebec7-5e73-4ca0-a35c-2a5c3ea52697.png)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-marketing
- **collection slug:** principles-marketing
- **ref/branch:** https://openstax-osbooksprincip-g5aw5gsup1z.ws-us70.gitpod.io/
- **chapter/section:** Chapter6/Section3 (Global correction)
- **surrounding text:** Median is a common statistic when identifying the income level of a specific geographic region.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-10-18 10-15-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bac2a1c4-cd54-4e72-b717-0787c3da86a4)

**Comment by lwtchu** [comment]
Issues aren't on CORGI or REX yet - need to coordinate this code version with CE and REX team
