### ISSUE TITLE
Marketing Book Theme - Reference Section unwanted underline issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4887]
We have received the below feedback from customer. Please find the below screenshots. Kindly check and resolve these issues.

**It appears that, in the Web view References section, an extra white space also appears between the number and the period, in some of the citations, along with the undesirable underlining**

**PDF View:**
![reference1](https://user-images.githubusercontent.com/86622862/194227413-2adb8e23-4d45-45ba-bed1-9d2032cd4e13.png)

**Web View:**
![reference2](https://user-images.githubusercontent.com/86622862/194227432-8532a983-9515-4ec4-974f-4fd8d72fd1d6.png)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-marketing
- **collection slug:** principles-marketing
- **ref/branch:** https://openstax-osbooksprincip-g5aw5gsup1z.ws-us70.gitpod.io/
- **chapter/section:** Chapter 11/Section 1
- **surrounding text:** and see how the selected frames look on your face before you purchase.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-10-19 13-15-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d4131b76-d0ad-42c1-b171-b7b602018987)

**Comment by lwtchu** [comment]
Issues aren't on CORGI or REX yet - need to coordinate this code version with CE and REX team
