### ISSUE TITLE
Phet simulation text translation for Física universitaria

### ISSUE THREAD

**Issue by Jacqueline-Yarbrough** [openstax/cnx-recipes#4888]
# Context
In the pdf version of the University Physics books, text that says "Click to view content" appears before the link to a phet simulation. This text needs to be translated in the Spanish University Physics books. 
English: Click to view content.
Español: Haga clic para ver el contenido.

![Screen Shot 2022-10-12 at 3 27 59 PM](https://user-images.githubusercontent.com/75643768/195441944-fc198e4f-364a-4621-8448-4bd6afda6654.png)

## Impact 
This affects Física universitaria volumens 1–3. 

# Acceptance Criteria
All Phet simulations in Física universitaria volumens 1–3 have the text "Click to view content" replaced with the Spanish translation.

## Location(s)
- **osbooks repo: osbooks-fisica-universitaria-bundle** 
- **collection slug: física-universitaria-volumen-1, física-universitaria-volumen-2, and física-universitaria-volumen-3**

**Comment by wilkus27** [comment]
Text "Click to view content" is added only to iframe elements:

assembled file:
![image](https://user-images.githubusercontent.com/40228854/196126429-bb992485-9b9c-4045-aed4-6e6af5f9b4bc.png)

baked file:
![image](https://user-images.githubusercontent.com/40228854/196126812-b1867b2b-fca6-454c-a5b4-0f7c5aa1db4b.png)


There are no iframes in any of Fisica volumes.

**Comment by lwtchu** [comment]
Checked with Jacqueline. Moved to next sprint, content will be added this week.

**Comment by lwtchu** [comment]
Content should be available now. This is scheduled for next  sprint

**Comment by wilkus27** [comment]
After content fix it's working as intended:

![image](https://user-images.githubusercontent.com/40228854/203735990-1cdbbf41-00ee-4910-97ed-1da870db09b1.png)

No code changes are needed.

**Comment by lwtchu** [comment]
Oh nice - should've checked :C thank you @wilkus27
