### ISSUE TITLE
Contemporary Math: In Projects which are appreaing in every chapter, lists are not appearing with proper indent

### ISSUE THREAD

**Issue by mps-openstax** [openstax/cnx-recipes#4889]
In **Projects** which are appreaing in every chapter, lists are not appearing with proper indent. Please see the snapshot below for your reference. This is from the **Chapter 13**.

![image](https://user-images.githubusercontent.com/88098452/195507918-5ffa1b16-9aaf-490c-8b6b-5ce9ce72c3a7.png)

The corresponding XML for these are as given below for reference.

![image](https://user-images.githubusercontent.com/88098452/195517092-21471a0b-402a-4ff4-80e1-fd4fd183ee49.png)

Kindly, please check and do the needful.

**Comment by wilkus27** [comment]
I noticed that also headers are not styled:

![image](https://user-images.githubusercontent.com/40228854/196113473-c49c13c9-071e-42dc-9e40-6d3839172a7e.png)

I made a fix for that in the same PR.

**Comment by MartaSztuka** [comment]
#### PASSED


![Screenshot from 2022-10-18 10-20-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2d3a7ddf-d16f-43d3-ab5f-52d3fbf7c89f)
![Screenshot from 2022-10-18 10-19-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1b81b7c4-9471-444b-bfc2-dc8659325c0e)
