### ISSUE TITLE
Python - Monospaced text not wrapping properly, breaking cells

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#4890]
# Brief Description of Scenario

In places where monospaced text runs into an edge, it continues on rather than wrap to stay in bounds.

![CleanShot 2022-10-13 at 14.56.50.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1b8f59b4-05fa-4c51-b9ac-d5fabc33006a)

![CleanShot 2022-10-13 at 11.24.12.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ba4c3a7b-7abb-4c26-80b8-9fbd7008b883)

![CleanShot 2022-10-13 at 14.55.59.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/218adb30-56ce-41c6-b80f-ec0aa8709c4b)

![CleanShot 2022-10-13 at 14.47.17.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f3f1c43d-5a57-4630-bf6d-2505e89e5fdd)

# Pattern of Occurrence 

Happens in Table 1.2, Table 1.3, Table 1.4 and in `Try It: Five Quotes`

# Acceptance Criteria

  Monospace text should remain within bounds.

# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-computer-programming-python
- **collection slug:** computer-programming-python
- **ref/branch:** main
- **chapter/section:** 1
- **surrounding text:** 
  - An escape sequence is two characters
  - mistakes that anyone could make when programming
  - several guidelines from PEP 8
  - Write a program that prints the following five quotes

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-10-19 17-28-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/076c75e5-9e28-4d42-b2df-0da35368a84d)

![Screenshot from 2022-10-19 17-28-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/530efda3-bbbf-406d-9c10-b77a5e517388)

![Screenshot from 2022-10-19 17-29-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/284f3e36-1fb0-43d2-8ad1-b0b4d7ffed0a)
