### ISSUE TITLE
World History - Duplicate Chapter Titles Across Units Not Allowed?

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4893]
# Context
Duplicate chapter titles across **Units** throws validation error. 

![DuplicateChTitle](https://user-images.githubusercontent.com/89537088/196578869-21021e25-efaf-4609-b324-ac08fd8103d0.JPG)

**Is this expected or is this a bug?**

# Content
## Sample Mark-Up
```
  <col:content>
    <col:subcollection>
      <md:title>Unit A</md:title>
      <col:content>
        <col:subcollection>
          <md:title>Understanding the Past - Unit A</md:title>
          <col:content>
            <col:module document="m00053"/>
            <col:module document="m00054"/>
            <col:module document="m00055"/>
            <col:module document="m00056"/>
          </col:content>
        </col:subcollection>
      </col:content>
    </col:subcollection>
    <col:subcollection>
      <md:title>Unit B</md:title>
      <col:content>
        <col:subcollection>
          <md:title>Understanding the Past - Unit B</md:title>
          <col:content>
            <col:module document="m00049"/>
            <col:module document="m00050"/>
            <col:module document="m00051"/>
            <col:module document="m00052"/>
          </col:content>
        </col:subcollection>
      ...
     </col:content>
    </col:subcollection>
  </col:content>
```

## Location(s)
- **osbooks repo:** osbooks-world-history
- **collection slug:** world-history
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax We do not allow for the same chapter title in the same volume. The two chapters look roughly like the same content - is this intentional?

**Comment by ww-openstax** [comment]
Submitted in error. The duplicate chapter titles are NOT present across Units. The duplicate chapter titles appear in separate volumes/collections. 
Closing.
