### ISSUE TITLE
computer programming python - inline code snippet styling with highlight.js

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4894]
# Brief Description of Scenario
Waiting for changes in function for highlights (https://katalysteducation.slack.com/archives/C022NETP39N/p1665734026939539) 
_Originally posted by @wilkus27 in https://github.com/openstax/cnx-recipes/issues/4877#issuecomment-1283672195_

There are inline code snippets that render with `<code>` tags and don't have `<pre>` tags on them for highlight.js to start applying styling. 

# Pattern of Occurrence 
any and all inline code (code that is nested in a para or list)

# Acceptance Criteria
Need to determine the following

- [ ] how does the original zyBooks book style these? are they all in pre snippets?
- [ ] do we add functionality to highlight.js to apply to code snippets or style it manually?
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-computer-programming-python
- **collection slug:**
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:**

**Comment by LostMojo** [comment]
@lwtchu Does zyBooks style with pre-snippets? Do we want to add something to cookbook to add those tags?

Computer Science still has a content problem, so I can't check the finished xhtml to compare, but there's no cookbook-side baking going on to add or do anything to the computer science code snippets

**Comment by lwtchu** [comment]
forgot to mention - content is here https://github.com/openstax/osbooks-computer-programming-python/tree/pre-tag-testing

**Comment by lwtchu** [comment]
forgot to mention - content is here https://github.com/openstax/osbooks-computer-programming-python/tree/pre-tag-testing

**Comment by lwtchu** [comment]
for larissa - add inline-code tag for things that you want to appear inline on pre 

check pre tagging and classes

**Comment by lwtchu** [comment]
Updated content with `class="python inline-code"` on https://github.com/openstax/osbooks-computer-programming-python/tree/pre-tag-testing

PLEASE ONLY look at section 1.1 Output and Input - Preformat test with a nested list & Preformat test with para  & the first two exercises in concepts in practice

**Comment by lwtchu** [comment]
Please remember that this issue is two fold. 1. in the modules/book with CNXML content and 2. in the exercises / HTML content. highlight.js requirements are to add styling to code within pre tags i think.

## within the book
`<preformat>` and `<code>` tags as their limitations on attributes and what they will transform into. If `<code>` is nested, the pre tag won't show up. But if it isn't nested, it will. Please look at the module 1.1 Output and Input first two sections nested for the test content  and modify that. So far the content we are testing with is just `<preformat>` by itself with the class since that will create the closest to what highlight.js needs.

## assessments
One major hurdle here was `data-lang` gets stripped out of the attributes upon publishing the assessments. When testing the content here, please be cognizant of what remains after publishing. the first two exercises in concepts in practice are the two we should mess with to contain the testing 

## Requirements
- It should be fairly consistent with what we are doing to make the NON inline code match which is 
`<code class="python" lang="python" display="block"></code>`
- make sense for both assessment and content in book
- not too hacky sacky so we can have XML teams execute this (clear instructions can be written for specific types of content that is identifiable)
