### ISSUE TITLE
Marketing Book Theme - Unwanted line break appeared in the inline equation

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4895]
We have received the below correction from customer. We have coded as per the tagging legend. Kindly check and resolve this issue.

**Correction:**
![chapter12-footnote](https://user-images.githubusercontent.com/86622862/197184631-0c49d124-f5c8-4f5a-a1c1-2da21dd34a51.png)

**CNXML:**
![chapter12-footnote1](https://user-images.githubusercontent.com/86622862/197184670-edf9ec4e-6c8c-4fd9-b038-94fafae0aa0e.png)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-marketing
- **collection slug:** principles-marketing
- **ref/branch:** https://openstax-osbooksprincip-mchkf3ekpfb.ws-us72.gitpod.io/
- **chapter/section:** Chapter 12/Section 3
- **surrounding text:** this smartphone to include these costs plus a profit of 10 percent,

**Comment by lwtchu** [comment]
@srm-openstax An equation tag makes sets the math in display block format. If you want the math to be inline with the text, please remove the equation tag and set it as regular math.

**Comment by srm-openstax** [comment]
This issue has been resolved. Thanks for your guidance. Please find the below screenshot.

![image](https://user-images.githubusercontent.com/86622862/197998573-ddac6c2c-ab52-4394-a348-954a5b69faa5.png)
