### ISSUE TITLE
World History - Styling for feature box discussion questions

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4897]
# Context
Styling of figure box discussion questions between PDF View and Webview should be consistent. We prefer a horizonatal line separator with unbolded text in discussion questions.  
**PDF View**
![image](https://user-images.githubusercontent.com/89537088/197555146-7e819a24-6b6f-42a3-b73d-cac395811ef2.png)

**Webview**
![image](https://user-images.githubusercontent.com/89537088/197555903-5d196d61-539d-4c45-ad24-a959cd8eb3dc.png)

## Impact 
This book

## Location(s)
- **osbooks repo:** osbooks-world-history
- **collection slug:** world-history
- **ref/branch:**
- **chapter/section:**  Feature Box Discussion Questions
- **surrounding text:**

**Comment by lwtchu** [comment]
# Acceptance Criteria

PDF
Can we unbold the text

Web
Can we add a line similar to the one below the title  (In their own words)?

**Comment by ww-openstax** [comment]
@lwtchu I'm not sure if your comment was a question for Wisewire or another team but our response is:
yes
**Acceptance Criteria**
PDF
Unbold the text

Web
Add a line similar to the one below the title

Thanks!

**Comment by lwtchu** [comment]
@ww-openstax the acceptance criteria is for my team! you can ignore them. I’ll generally try my best to tag you for any specific questions or comments

**Comment by MartaSztuka** [comment]
#### PASSED
##### PDF
![Screenshot from 2022-11-17 11-11-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1a3a4fbb-bb35-4b06-be22-26c784e2059e)

##### webview
![Screenshot from 2022-11-17 11-17-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/215ecb14-7071-4496-8fb5-71d5ffb02c07)
