### ISSUE TITLE
contemporary math - data-align left enable in answer key

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4901]
# Brief Description of Scenario
data-align = "left" isn't registering in the answer key. All of these numbers should be left aligned 

![Screen Shot 2022-10-25 at 9 56 39 AM](https://user-images.githubusercontent.com/11299125/197808569-9e9b3910-b119-4b19-9360-9cfe14254836.png)

![image](https://user-images.githubusercontent.com/11299125/197817880-66b865ef-c71b-4448-b082-1ff74fab3cb7.png)

![image](https://user-images.githubusercontent.com/11299125/197817902-c565611a-a0a7-48e3-b6a0-7c7256698251.png)

# Pattern of Occurrence 
Answers to the following
- Your Turn 8.10
- Section 8.2 Question 9, 11, 20, 21
- Section 8.2 Check Your Understanding 9

# Acceptance Criteria
The numbers should be left aligned in the right column of the table
  
# Sample Mark-Up
```
&nbsp;<table class="unnumbered">
<tbody>
<tr><td data-align="left">4</td>
<td data-align="left">7</td>
</tr>
<tr><td data-align="left">5</td>
<td data-align="left">9 7 4</td>
</tr>
<tr><td data-align="left">6</td>
<td data-align="left">9 8 7</td>
</tr>
<tr><td data-align="left">7</td>
<td data-align="left">8 7 5 2 2 1 0</td></tr>
<tr><td data-align="left">8</td>
<td data-align="left">9 6 5 4 4 1</td>
</tr>
<tr><td data-align="left">9</td>
<td data-align="left">7 7 6 3 3 1</td>
</tr>
<tr><td data-align="left">10</td>
<td data-align="left">7 6 3 1</td>
</tr></tbody>
</table>
```

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-contemporary-math
- **collection slug:** contemporary-math
- **ref/branch:** main
- **chapter/section:** ch 8  
- **surrounding text:**

**Comment by wilkus27** [comment]
@lwtchu There is the same problem with content as in previous card. Exercises don't work in Chapter 8.

**Comment by lwtchu** [comment]
@wilkus27 could you see if someone can replicate the issue locally? They’re appearing on CORGI

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-10-31 at 12.15.00.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a872c408-1695-4cc3-b44d-3071ca618e98)
