### ISSUE TITLE
organic chemistry - update chemistry matters feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4902]
# Brief Description of Scenario
![Screen Shot 2022-10-25 at 3 29 03 PM](https://user-images.githubusercontent.com/11299125/197875404-281347bc-ed76-430a-ba20-1769741e5621.png)

# Pattern of Occurrence 
Please target chemistry matters feature that was created here #4750 

# Acceptance Criteria
- increase `Chemistry Matters` text to font-scale(5): 22.39pt, 30px, 2.5rem
- change horizontal line colors to R3: `#E00087`
- change icon to [carnival-microconnections2.svg](https://drive.google.com/file/d/191v4zIC4dsqXeu3MOGouXioTqcrCqh7o/view?usp=sharing)
  

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-organic-chemistry/tree/Design-Chapter
- **collection slug:** organic-chemistry
- **ref/branch:** Design-Chapter
- **chapter/section:**  end of last section before EOC
- **surrounding text:** Chemistry Matters

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-10-27 17-25-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0cb0c65e-f993-4ed6-804f-939ab0c8cb18)
