### ISSUE TITLE
answer key refactoring - tables

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4904]
Corn - Remove tables components from `AnswerKey` shape and create new shape `TableFromAnswerKey` in `table-shapes.scss` file.

**Comment by wilkus27** [comment]
### Information for tester

It affects `Calculus`, `Contemporary Math`, `Dev-Math`, `Precalculus` and `Precalculus-Coreq`

**Comment by Stackblocks** [comment]
- [ ] Displays OK with current code & content

**Calculus**
![CleanShot 2022-10-27 at 15.28.34.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/80d8ea6d-50ea-43c6-b5c2-6faf290a8b2a)

**Contemporary Math**
![CleanShot 2022-10-27 at 15.29.56.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f13fd5fb-f608-4dce-8467-854350854be3)
