### ISSUE TITLE
Marketing Theme - Bullets list not supported in WebView - Preface section

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4905]
Bullet list not supported at preface section in Web Preview, but it's supported in PDF view. Kindly check and resolve this issue.

**PDF output:**
![image](https://user-images.githubusercontent.com/86622862/199012287-2e29c79c-9873-4bf2-b54d-3a5e7a060310.png)

**Web View:**
![image](https://user-images.githubusercontent.com/86622862/199012398-ac6ebf6e-4ab5-4899-a75b-49a8655dbda0.png)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-marketing
- **collection slug:** principles-marketing
- **ref/branch:** https://gitpod.io/start/#openstax-osbooksprincip-mrjct9wzpll
- **chapter/section:** Preface
- **surrounding text:** This feature box presents examples of challenges, managerial decisions, and the

**Comment by wilkus27** [comment]
@lwtchu Just for the information, bullets were removed on purpose previously. I added them back. It has an impact on all books.

**Comment by lwtchu** [comment]
@wilkus27 ah okay. i think if they want to remove it they'll have to add it in the content to apply the no bullet style. I'll keep that in mind thank you for the context

**Comment by Stackblocks** [comment]
-[x] Displays OK with current code & content

![CleanShot 2022-11-10 at 16.50.34.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e689d7be-05f6-46af-8c39-249469aa6bbb)
