### ISSUE TITLE
Marketing Theme - Figure caption placement incorrectly in PDF view - Preface Section

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4906]
We have coded as per the tagging legend. But figure captions placement incorrectly in PDF view. Webview is fine. Kindly check and resolve this issue. 

**Web View:**
![image](https://user-images.githubusercontent.com/86622862/199170695-81019238-6b28-415e-9c1c-e0d56b709d98.png)

**PDF View:**
![image](https://user-images.githubusercontent.com/86622862/199170575-06714bb7-d60b-4cbd-b1e0-ae94a604e88b.png)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-marketing
- **collection slug:** principles-marketing
- **ref/branch:** https://gitpod.io/start/#openstax-osbooksprincip-mrjct9wzpll
- **chapter/section:** Preface
- **surrounding text:** Senior contributing authors: Maria Gomez Albrecht (left), Mark Green (center), Linda Hoffman (right).

**Comment by wilkus27** [comment]
@lwtchu Figures were not baked in the Preface. After change they're numbered now:

webview
![image](https://user-images.githubusercontent.com/40228854/201088523-36944917-658b-4189-9c88-da6c3d7e8c5b.png)

PDF
![image](https://user-images.githubusercontent.com/40228854/201088589-a0d17ef5-0517-42ac-a3cb-5b013a4adced.png)

**Comment by lwtchu** [comment]
@wilkus27 that's fine - thank you!

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-11-10 at 11.25.34.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3db08da9-aad8-411f-a581-a580ffe3a6e0)
