### ISSUE TITLE
answer key refactoring - standardize shapes

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4907]
- Create `AnswerKeyShape` in all themes to style module
- Create `AnswerKeyWithNestedSolutionAreasShape` in Corn - used in Precalculus
- Create `AnswerKeySolutionShape` in all themes to style just solutions (regular `[data-type=solution]` and injected `[data-type="question-solution"]`) - in Corn it's used to style three types of solutions
  - three columns (calculus, dev-math, precalculus, precalculus-coreq)
  - one column from EOC (statistics)
  - one column from EOB (contemporary-math)
- Create `AnswerKeySolutionInlineShape` in Carnival and Cosmos to display solutions in line (american-government, sociology, history, microbiology)
- Create `AnswerKeySolutionMultipartShape` in Carnival - used in Organic Chemistry

**Comment by Stackblocks** [comment]
✅ No irregularities spotted in books tested, new features like nested answers still functioned properly.
