### ISSUE TITLE
chapter intro refactoring - titles

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4908]
- Create separate shape for titles from Chapter Intro
- Add headers up to H5

**Comment by MartaSztuka** [comment]
#### PASSED
##### philosophy
![Screenshot from 2022-11-16 16-23-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/68484cd8-a756-4d8e-818b-4a9554a49e3f)

##### contemporary math
![Screenshot from 2022-11-16 16-30-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8aa81931-dd1d-4fdc-8cfa-9af851ebf3a6)

##### political science
![Screenshot from 2022-11-16 16-46-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9c4c9be4-4356-464d-90c1-b7cacdc79a1d)

##### precálculo
![Screenshot from 2022-11-16 17-03-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cdecd802-8d71-4374-a939-ef81b86de506)

##### sociology
![Screenshot from 2022-11-16 17-06-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2b9b4260-dabd-4aaf-babd-68b4b886909c)

##### astronomy
![Screenshot from 2022-11-16 17-11-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2cbbc841-f18f-478f-a87d-cfa69d535c02)
