### ISSUE TITLE
World History - Images Out of Layout in Appendix

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4909]
# Context
In Appendix C, the images are out of layout in PDF View. In WebView the same images look good.

# New specifications or link to documentation cards
PDF View
![PDF_Output](https://user-images.githubusercontent.com/89537088/201413697-7009da7b-e099-4c30-8d84-7c2c32e1ac27.JPG)

Web View
![WebPreview](https://user-images.githubusercontent.com/89537088/201413729-2bfb5447-14bc-4a3e-9784-019ba72e08ee.JPG)

## Impact 
All images in Appendix C

# Acceptance Criteria
Images in Appendix C PDF View are in Layout

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-world-history
- **collection slug:** world-history-volume-2
- **ref/branch:** module m00074
- **chapter/section:** Appendix C
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax Art must be created with the maximum width/height specifications listed on https://www.opengui.de/art-photo-guidelines#max_art. Please re-export the map to the right size
