### ISSUE TITLE
World History - TOC Unit Numbering; Change to Roman Numeral

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4910]
# Context
In TOC Unit Titles, change generated text from "Unit 1" to "Unit I:" etc.
Or supress generated text in Unit Titles and we can add desired text to <md:title>

# New specifications or link to documentation cards
![image](https://user-images.githubusercontent.com/89537088/201932172-35b1f6f2-fb35-41b9-b8e6-d7183dafd6a4.png)

## Impact 
Just this book

# Acceptance Criteria
Unit I: Connections Across Continents, ...
Unit II: An Age of Revolution, ...
Unit III: The Modern World, ...

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-world-history
- **collection slug:** world-history-volume-2
- **ref/branch:**
- **chapter/section:** TOC
- **surrounding text:**

**Comment by openstaxalina** [comment]
additional context from Wisewire -- this is suggested to avoid confusion between Volume numbering and Unit numbering. E.G. to avoid the issue of "Volume 1", "Volume 2" + "Unit 1, "Unit 2", etc.

@lwtchu please make the decision on this...do we have other multi-volume books with units, and has this been an issue? is this a rigid industry standard? David or Anthony may also have feedback.

**Comment by lwtchu** [comment]
If we do this, we'll end up having two separate recipes/styles. Other books with separate volumes don't have units, but we also do not have a separate numbering schema for the chapters and there hasn't been any reported confusion. Closing issue as we aren't going to pursue separate numbering schema
