### ISSUE TITLE
chapter intro refactoring - Chapter Outline

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4911]
- Move `ChapterOutlineShape` to `learning` files. 
- Rename these files to `objectiveoutline-components` etc.
- Chapter Outlines components will be renamed within Learning Objectives refactoring.

**Comment by MartaSztuka** [comment]
#### PASSED
##### philosophy
![Screenshot from 2022-11-16 17-16-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/58fbd16c-56db-4ba7-b4c4-593f4df928da)

##### contemporary math
![Screenshot from 2022-11-16 17-18-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5f9fd6cd-5e9f-4ca9-b162-4d69907b1b62)

##### political science
![Screenshot from 2022-11-16 17-21-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f649cbe3-67c6-4f50-b727-3526b8f738e9)

##### sociology
![Screenshot from 2022-11-16 17-23-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e76db715-3149-4aa3-b69b-459e28a32f04)

##### astronomy
![Screenshot from 2022-11-16 17-26-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5c704ed4-90de-4109-8fe6-871a0653bf10)

##### precálculo
![Screenshot from 2022-11-16 17-30-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3b3a733e-4eef-4573-8133-d9a523b15162)
