### ISSUE TITLE
chapter intro refactoring - Splash Figure

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4912]
- Move `SplashFigureShape` to `figureimage` files.
- Delete `chapterintro` files totally.

**Comment by MartaSztuka** [comment]
#### PASSED
##### introduction political
![Screenshot from 2022-11-21 10-45-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/edded216-d1a8-47d7-b85f-c732aea3078c)

##### calculus 1
![Screenshot from 2022-11-21 12-29-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6a2387eb-ef73-48f1-97ce-30b7086c5463)

##### sociology
![Screenshot from 2022-11-21 12-56-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dbce5a86-111f-45ab-9fed-84af2478ed2d)

##### astronomy
![Screenshot from 2022-11-21 13-04-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0751dc83-1d78-449c-8232-1ee1797ab445)
