### ISSUE TITLE
World History - URLs to Embedded Video Not Generating Properly in PDF View

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4913]
# Context
For content that is tagged for embedded video with media/iframe, system-generated url is not correct in PDF view.

Webview displays correctly

# New specifications or link to documentation cards
PDF View
![image](https://user-images.githubusercontent.com/89537088/202252226-3b4a520a-b983-4148-924c-ed7639d10629.png)

WebView
![image](https://user-images.githubusercontent.com/89537088/202249798-788c91f5-82ac-4bf6-9d8d-a34a501440f4.png)

# Content
## Sample Mark-Up
```
<para id="para-00030">Following are two propaganda cartoons. The first is an <link url="https://openstax.org/l/77MakeMineFree">American video called <emphasis effect="italics">Make Mine Freedom</emphasis></link> that was made in 1948.</para>
    <media alt="make_mine_free">
      <iframe width="660" height="371.4" src="https://openstax.org/l/77MakeMineFree"/>
      </media>
    <para id="para-00031">In it, viewers are warned about the dangers of &#8220;ism,&#8221; which listeners in the United States would understand to mean &#8220;communism.&#8221; Please note that the video contains racist imagery, as did many American cartoons from this time period. The salesman peddling &#8220;communism&#8221; to gullible Americans is wearing a zoot suit, a style of dress associated with men of color.</para>
    <para id="para-00032">The second video is a <link url="https://openstax.org/l/77Millionaire">Soviet cartoon called <emphasis effect="italics">The Millionaire</emphasis></link> that portrays the behavior of the wealthy in the United States.</para>
    <media alt="millionaire">
      <iframe width="660" height="371.4" src="https://openstax.org/l/77Millionaire"/>
      </media>
```

## Location(s)
- **osbooks repo:** osbooks-world-history
- **collection slug:** world-history-volume-2
- **ref/branch:** module m00034
- **chapter/section:** 14.1
- **surrounding text:** Beyond the Book. Cold War Propaganda

**Comment by lwtchu** [comment]
@ww-openstax Once the book is live, the link will point to the section of the online section that the video lives in. If the video shows up on the web preview, it will go to the right place.
