### ISSUE TITLE
unit opener refactoring - titles

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4914]
- Create separate shape for titles from Unit Opener in `titles` files.

**Comment by MartaSztuka** [comment]
#### PASSED
##### writing guide
![Screenshot from 2022-11-21 14-44-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/61558f57-314d-4a02-9c31-b6602ee8bb22)

##### marketing
![Screenshot from 2022-11-21 14-45-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/654c04a6-34ba-47c4-bed6-b29420959ac2)
