### ISSUE TITLE
unit opener refactoring - move to Common

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4915]
- Move `UnitOpener` components and shape to `common` files
- Standardize components names

**Comment by MartaSztuka** [comment]
#### PASSED
##### writing guide
![Screenshot from 2022-11-21 15-01-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ec8b404a-1f0a-4df9-a314-1543f5797de0)

##### marketing
![Screenshot from 2022-11-21 14-58-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/20b2ecc9-dcb8-4efa-a9f8-44fdf6913572)
