### ISSUE TITLE
Implement single underline screen reader text

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4916]
# Brief Description of Scenario
Original issue: https://github.com/openstax/ce-styles/issues/127 

https://github.com/openstax/cnx-recipes/issues/4103 - We added this in Writing Guide [Section 6-6](https://rex-web.herokuapp.com/books/ee7ce46b-0972-4b2c-bc6e-8998c785cd57@833cc3c/pages/008e5069-1d14-4234-8a94-151a5b776f6a?archive=https://openstax.org/apps/archive/20220815.182343#para-00014)

Need to make sure that all single-underlines in our books have the same screenreader-only elements inside the <u> tag that say "underline" and "end underline"

# Pattern of Occurrence 
See below for all books with underline - might be worth investigating implementing globally.

# Acceptance Criteria
all single-underlines in our books have the same screenreader-only elements inside the <u> tag that say "underline" and "end underline"
  

# Location(s)
**Single Underline locations:**
Biology(493/493. Found 12)
- [m44405](https://legacy.cnx.org/content/m44405/latest/#fs-id2029814) Studying Cells 
- [m44431](https://legacy.cnx.org/content/m44431/latest/#fs-id1595819) Energy in Living Systems 
- [m44431](https://legacy.cnx.org/content/m44431/latest/#fs-id1595819) Energy in Living Systems 
- [m44432](https://legacy.cnx.org/content/m44432/latest/#fs-id2316327) Glycolysis 
- [m87357](https://legacy.cnx.org/content/m87357/latest/#fs-id1671263) Key Terms 

Astronomy(200/404. Found 7)
- [m59792](https://legacy.cnx.org/content/m59792/latest/#fs-id1163975674170) The Behavior of Light 

American Government 2e(204/204. Found 1)
- [m72423](https://legacy.cnx.org/content/m72423/latest/#fs-id1163758400666) Intergovernmental Relationships 

American Government(204/204. Found 1)
- [m58969](https://legacy.cnx.org/content/m58969/latest/#fs-id1163758400666) Intergovernmental Relationships 

Algebra and Trigonometry(172/172. Found 15)
- [m51261](https://legacy.cnx.org/content/m51261/latest/#fs-id1165137844421) Functions and Function Notation 
- [m51284](https://legacy.cnx.org/content/m51284/latest/#fs-id1526800) Right Triangle Trigonometry 
- [m51284](https://legacy.cnx.org/content/m51284/latest/#fs-id1526800) Right Triangle Trigonometry 
- [m51284](https://legacy.cnx.org/content/m51284/latest/#fs-id1526800) Right Triangle Trigonometry 
- [m51286](https://legacy.cnx.org/content/m51286/latest/#fs-id931590) The Other Trigonometric Functions 
- [m49448](https://legacy.cnx.org/content/m49448/latest/#fs-id1165137443996) Counting Principles

**Comment by Stackblocks** [comment]
@wilkus27 It looks like something is off with this. Something may be mis-targeted, and the text for underline / end underline needs to be hidden.

![CleanShot 2023-02-07 at 15.23.06.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b45d99a3-2139-4fd3-94da-91678d1b5d9f)
---
![CleanShot 2023-02-07 at 15.25.19.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/200902cf-e791-4729-af17-7441ae31ab90)

**Comment by wilkus27** [comment]
@Stackblocks Thank you for noticing that! :relaxed: I made change for recipe and forgot to check styles :woman_facepalming: 

@lwtchu I hid unwanted text, do we want to style underlines in some way? In English Composition they are yellow. Do we want to add any color for them in books from this card?

This is what it looks now:

#### Astronomy
![image](https://user-images.githubusercontent.com/40228854/217530191-484bf64e-321f-470c-bbf5-13a280ecbc1e.png)

#### Biology
![image](https://user-images.githubusercontent.com/40228854/217530307-1f2c0ddd-e31a-4770-a37a-1822322840f2.png)

**Comment by lwtchu** [comment]
@wilkus27 we do not have to style it for now since it's not as important in these titles.

**Comment by Stackblocks** [comment]
The errant text is now properly hidden. 🎉

![CleanShot 2023-02-08 at 14.47.21.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1674e1dc-c89b-4531-99b5-6716371780ff)
---
![CleanShot 2023-02-08 at 14.46.59.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b2deb19e-07ff-4362-b10f-7e4c589f9b82)


@lwtchu We may want to consider running these by some users who are used to screenreader based reading for some UX checks because in cases like Biology where partial words are underlined for emphasis cramming in "underline | end underline" really does a number on intelligibility to me, but i'm not super fluent in it.

https://images.zenhubusercontent.com/49744755/1595b9da-46a6-4553-949e-d2054e821826/cleanshot_2023_02_08_at_18_08_40.mp4

**Comment by lwtchu** [comment]
@Stackblocks good point - for this case we might went to change up the way it's marked up. I'll open an errata in a bit

**Comment by lwtchu** [comment]
@openstaxalina to catalog this issue for potential vendors to answer :eyes:
