### ISSUE TITLE
add image dimensions to <img>s

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#4917]
# Context

Rex needs image dimensions data so that they can unbouncify their page loading (SEO). Currently, rex has to send a request during rendering in order to get this data. If that data was instead available on the html, it would be easier for everyone.

# New specifications or link to documentation cards

- For every `<img>` tag, add attributes listing their heights & widths. 
- If an existing attribute is used (either `height` or `width`) that differs from the image pixel count, keep it, and to add the second dimension, scale it appropriately. 
- Log a warning if the attributes can't be found. 

Implementation sketch:
- read height and width from JSON in IO_RESOURCES
- attribute names are `height` and `width`

## Impact 

All books -- html only

# Acceptance Criteria

- [ ] `<img>` elements across books have attributes listing heights & widths of image
- [ ] heights & widths are accurate to image pixel dimensions or scaled
- [ ] styling not impacted

**Comment by kswanson33** [comment]
note that this causes a dependency between image metadata files & cookbook, which didn't previously exist. for maintainability going forward, cookbook should send some error or warning that will alert us of any problems that may be caused if the image metadata files ever change/move.

**Comment by Stackblocks** [comment]
Tested books in each theme: 
- + no instances of `resource not found`
- + `"width"` and `"height"` showing up consistently in IO_RESOURCES JSON files.
- - Images have exploded in size, it looks like there is some kind of targeting mismatch with whatever compresses the images to the right size.
- - Expansion not consistent across all images, unclear if there is some kind of commonality between the ones that are blowing up.

![CleanShot 2023-06-13 at 16.27.47.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b0f2ce95-748d-465b-b277-5ddaef40f799)

### Ochem
![CleanShot 2023-06-13 at 16.32.39.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/669fb885-bb09-4b13-bd6b-97ea5d550377) (**Before** page count is 997)
![CleanShot 2023-06-13 at 16.31.46.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/9d7e36a3-d54f-46df-9636-d9a9f9e4bc16)
![CleanShot 2023-06-13 at 16.32.01.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d82fe1cd-98e2-4a3e-b76a-e510f0bcf426)
![CleanShot 2023-06-13 at 16.41.30.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5ed45112-b765-4be8-a638-2e34e8f2a686)

### US History
![CleanShot 2023-06-13 at 16.34.36.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d603811c-f687-4385-b594-31e523b819ff)
![CleanShot 2023-06-13 at 16.35.01.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/86b03dad-520e-4c0a-9af2-a5845d346295)
![CleanShot 2023-06-13 at 16.35.40.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0651fb0a-a15d-4a9b-8f81-86e5a6e20016)

### College Success
![CleanShot 2023-06-13 at 16.42.53.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5101c059-5958-49d8-8e65-8985b5fb82e6)
![CleanShot 2023-06-13 at 16.43.16.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b77297af-09bc-453c-bc9c-b7b990a80999)

**Comment by Stackblocks** [comment]
Image sizing issue has been fixed. New PDFs looking good.
![CleanShot 2023-06-14 at 16 03 11](https://github.com/openstax/cnx-recipes/assets/12678235/93795e3d-c871-4827-a5ec-367210a6acf9)
---
![CleanShot 2023-06-14 at 16 03 43](https://github.com/openstax/cnx-recipes/assets/12678235/de2fee19-2914-4428-8506-c529ac725b24)
