### ISSUE TITLE
toc target labeling

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#4918]
# Context

This work replaces/revises the work done in #4795. It's in conjunction with https://github.com/openstax/ce/issues/1944

Rex wants to support their ToC functionality (shown below) with better data typing. 

<img width="428" alt="image" src="https://user-images.githubusercontent.com/26280712/202766727-74fd0ebf-762e-4f91-b358-58cb8a8cccf1.png">

- The HTML is the original source of information for the Rex ToC
- After baking, relevant information from the HTML ToC is processed into JSON. Rex receives this JSON and generates its ToC from there.

The markup on this image shows a draft idea of what the JSON might ultimately look like:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/26280712/202765061-d26af3f5-06e0-4e1b-bedd-33e53db1dbc4.png">

- To lay the groundwork for this markup, all `<li>`s in the HTML ToC need to provide data in the form of attributes (which will ultimately be grabbed by the JSON).

# New specifications or link to documentation cards

Each `<li>` in the ToC needs 1-2 attributes added. Attributes are `data-toc-type` and `data-toc-target-type`.

Since this work revises/replaces the work done in #4795, the `data-toc-target-page-type` attribute should be removed too.

types of target content to differentiate:

- [x] unit: `data-toc-type="unit"` (no `data-toc-target-type`)
- [x] unit intro (page): `data-toc-type="link"` & `data-toc-target-type="unit-intro"`
- [x] preface (page) `data-toc-type="link"` & `data-toc-target-type="preface"`
- [x] appendix (page) `data-toc-type="link"` & `data-toc-target-type="appendix"`
- [x] chapter `data-toc-type="chapter"`
- [x] chapter intro (page) `data-toc-type="link"` & `data-toc-target-type="chapter-intro"`
- [x] section/core content/non introduction page (page) `data-toc-type="link"` & `data-toc-target-type="numbered-section-page"`
- [x] index (composite page) `data-toc-type="link"` & `data-toc-target-type="index"`
- [x] answer key (composite chapter) `data-toc-type="answer-key"`
- [x] answer key chapter (composite page) `data-toc-type="link"` & `data-toc-target-type="answer-key-chapter"`
- [x] eoc composite chapter (composite chapter) `data-toc-type="eoc-chapter"`
- [x] eoc composite page (composite page) `data-toc-type="link"` & `data-toc-target-type="eoc-page"`

## Impact 
All books. No visible change in PDF.

# Acceptance Criteria

- [x] above attributes have been added to TOC `<li>`s
- [x] removed `data-toc-target-page-type`
- [ ] no visible change in PDF

**Comment by openstaxalina** [comment]
Discussed with @TomWoodward and @erikayvonne -- this is needed in February so Assignable can filter the TOC for beta users ideally in March.

**Comment by kswanson33** [comment]
also added:
- `data-toc-type='eob-chapter'` to non-answer key composite chapters in eob
- `data-toc-target-type='references'` to both citation & section reference pages
- `data-toc-target-type='handbook'` to handbook pages

**Comment by TomWoodward** [comment]
@kswanson33 can we sync on this stuff? Most of it looks fine to me but some is unfamiliar. What is a handbook? Are we abusing the word "chapter"? Is it important to distinguish between unit-intro and chapter-intro?

I'm not sure if this is still super relevant, but we had talked about adding things to the book tree that reference things outside the book, to differentiate from that, should we make these toc-type="content-link" instead of just "link" ?

I realize that I've missed a bunch of internal conversations y'all have had about this, sorry if I'm re-hashing, I'm just trying to wrap my head around it

**Comment by lwtchu** [comment]
@TomWoodward heyo! kendra is out sick - but i can answer a few things. the handbook is only within _writing guide with handbook_ (it's a module set differently than an appendix at the end of the book) 

we're trying to be as specific as possible since different intros have different functionality pedagogically on the off chance that we might need to differentiate later. however i can add this to our meeting tomorrow and hash it out.

**Comment by TomWoodward** [comment]
yea lets talk about it tomorrow, too much specificity brings us back to where we started of not knowing what anything is because everything is different

**Comment by lwtchu** [comment]
Decision and timeline:
- merge this PR for code freeze tomorrow
- disco to offer suggestions for generalization
- make separate cards once the generalization-ification is decided 
- off cycle cookbook release on feb 15 for final changes 
- request new web hosting pipeline from ce feb 16/17 
- disco to adopt new web hosting pipeline week of feb 20

**Comment by kswanson33** [comment]
The changes:

- `unit-intro`, `chapter-intro` -> `intro`
- `numbered-section-page` -> something shorter
   - `section-page`
   - `numbered-section`
- `answer-key`, `eoc-chapter`, `eob-chapter` -> all composite chapters = the same thing)
   - `sub-book-tree`
   - `composite-subbook`
- `answer-key-chapter` -> `answer-key`
- `eoc-page`, `references`, `handbook` -> `composite-page`
- `data-toc-type="link"` -> `data-toc-type=<something more specific>`
   - `"content"` ✔️ 
   - `"page"` → ❌ confusing with `data-type="page"`
   - `"content-link"`

Checkmark ✔️  represents my vote. No strong preferences. If nobody cares very much, I can make an executive decision.

___

References and handbook have something specific going on with the toc styling, but are otherwise like other `composite-page`s. I think we can label those as regular `composite-page`s. Then, the only specifically typed composite pages would be `index` and `answer-key`. Does that sound good?

> this defines preface, intro, section-page as the types of authored pages, there is no generic type for them.

^did you want a generic type for these? They're all `data-type="page"` elements. (& a note: `appendix` belongs in this category too)

@TomWoodward

**Comment by TomWoodward** [comment]
of the ones you didn't vote on, i prefer `numbered-section` to `section-page`, and `sub-book-tree` to `composite-subbook` (mostly because `sub-book-tree` could apply to things that aren't composite)

your vote for `content` is fine with me. if we're hemming and hawing maybe `book-content` (i'm imagining a world where this "toc" references things that are outside the book)

**Comment by kswanson33** [comment]
For QA, updated specs (combining this card & #5016):

- unit: `data-toc-type="unit"` (no data-toc-target-type)
- unit intro (page): `data-toc-type="book-content"` & `data-toc-target-type="intro"`
- preface (page) `data-toc-type="book-content"` & `data-toc-target-type="preface"`
- appendix (page) `data-toc-type="book-content"` & `data-toc-target-type="appendix"`
- chapter `data-toc-type="chapter"`
- chapter intro (page) `data-toc-type="book-content"` & `data-toc-target-type="intro"`
- section/core content/non introduction page (page) `data-toc-type="book-content"` & `data-toc-target-type="numbered-section"`
- index (composite page) `data-toc-type="book-content"` & `data-toc-target-type="index"`
- answer key subsection aka all answers from chapter (composite page) `data-toc-type="book-content"` & `data-toc-target-type="answer-key"`
- all composite chapters: `data-toc-type="sub-book-tree"`
- composite pages (not answer key subsections or indices): `data-toc-type="book-content"` & `data-toc-target-type="composite-page"`
