### ISSUE TITLE
baked styles refactor - examples (second) 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4919]
1. Create separate shape for lists from examples.
It should cover both lists levels in all themes.
2. Subtitles - examples have different markup within different themes.
I would leave current components as they are, even though shapes are not consistent.
3. Media from para - there is only one case in Organic Chemistry, but book is still in progress.
There might be a chance that such element will appear in other places, e.g exercises. Then it would be better to create separate shape for medias from para or move this component to existing shape in figureimage-shapes file if it's possible.

**Comment by openstaxalina** [comment]
this is covered by https://github.com/orgs/openstax/projects/40/views/6?pane=issue&itemId=36563075 and doesn't need its own epic. closing.
