### ISSUE TITLE
baked styles refactor - exercises (second)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4920]
1.	Problem Wrapper and Solution Wrapper - remove word "Wrapper" from names
2.	Cosmos - create common components for problems and solutions number, divider and paragraph
	like it is done in other themes
3.	Problem Container with Image/Table on top - apply Problem Container with First Element instead
	like it is done in Carnival. Remove exerciseChildContainer function totally.
4.	Problem Container with Inline List on top - create component without using exerciseChildContainer function
5.	Corn - remove lists components from Exercise Module shape. Add them to lists-shapes file.
6.	Injected Exercise Context and Divider - should we style them in all themes? They're added only to Cosmos.
7.	Exercises Multipart Question shape- should we add it to all themes?
8.	Corn - Injected Exercise Multipart Question Indent - if we decide to add shape from previous point, move this 
	component to there.
9.	Remove redundancy using one of the method from How to avoid using one component a few times in one shape?
	(If anybody come up with better solution feel free to apply it)

**Comment by openstaxalina** [comment]
this is covered by https://github.com/orgs/openstax/projects/40/views/6?pane=issue&itemId=36563075 and doesn't need its own epic. closing.
