### ISSUE TITLE
World History - Eliminate bad breaks in Glossary Appendix

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4921]
# Context
In the glossary appendix, is there a way via tagging or styling change to eliminate widows and orphans?
# New specifications or link to documentation cards
![image](https://user-images.githubusercontent.com/89537088/203396500-5b1015bd-a2ce-4625-b6c1-a321fc12b016.png)

# Content
## Sample Mark-Up
```
<content class="appendix">
    <section class="column-container" id="sect-00024">
      <section id="sect-00001">
      <title>A</title>
      <list id="list-00001">
```

## Location(s)
- **osbooks repo:** osbooks-world-history
- **collection slug:** world-history-volume-2
- **ref/branch:** module m00072
- **chapter/section:** Appendix A
- **surrounding text:**

**Comment by lwtchu** [comment]
Message for devs: i'm not sure if we can completely eliminate orphans, but can we see how bad the breaks get if we don't allow for breaking across columns for the definition?

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-11-28 16-51-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1a96adfe-c754-40a7-940a-ee0743c3cdc8)

**Comment by ww-openstax** [comment]
Final Pages delivered to OSX 12/1
