### ISSUE TITLE
Economics 3e -- [link] in PDF -- platform unable to autofill anchor text

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4923]
# Brief Description of Scenario
In Economics 3e, we have encountered one instance of [link] where platform is unable to autofill anchor text. Logging as directed by PDF-Web-QA instructions on opengui.de

![image](https://user-images.githubusercontent.com/89537088/203599039-2b058c3e-06c5-4bdd-856a-6e628b98e364.png)

# Pattern of Occurrence 
one instance

# Acceptance Criteria

  
# Sample Mark-Up
```
Create a table, patterned after <link target-id="ch14mod02_tab06"/>. The first column should show



<table id="ch14mod02_tab06" summary="The table shows J
```

# Location(s)
- **osbooks repo:** osbooks-principles-economics-bundle
- **collection slug:** principles-economics-3e
- **ref/branch:** module m63909
- **chapter/section:** section id="ch14mod02_prob" class="problems"
- **surrounding text:**

**Comment by lwtchu** [comment]
# Acceptance Criteria
Make sure moved collated sections can point back to the document that it came from

**Comment by LostMojo** [comment]
Link leads to a table without any text, we might need to add some text content-side so the link will have something to grab on to.

![Screen Shot 2022-11-29 at 3.30.00 PM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/a5221d80-e5ca-4c0e-ab1e-1fb4de92fb83)

**Comment by lwtchu** [comment]
@ww-openstax would it be alright if i removed the `unnumbered` class?

**Comment by ww-openstax** [comment]
@lwtchu I'm not sure. I will investigate.     --Mike Bujewski

**Comment by ww-openstax** [comment]
Final Pages delivered to OSX 11/30

**Comment by lwtchu** [comment]
Removed the class and pushed content changes.
