### ISSUE TITLE
lists refactoring - add missing components to shapes

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4927]
Complete lists shapes with missing components. For example, if in section wrapper there is styled only ordered list, add also unordered one etc.

- [x] `PageListsShape` (Preface, regular module, Appendix)
- [x] `CompositePageListsShape` (EOC, Answer Key, References)
- [x] `ExercisesListsShape`
- [x] `NotesListsShape`

**Comment by MartaSztuka** [comment]
#### PASSED
##### philosophy
![Screenshot from 2022-12-06 12-37-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e4f92c0d-1596-4c1f-bcd6-7316e04d1c39)

![Screenshot from 2022-12-06 12-37-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/301b13e5-26c0-48fc-838c-e517bacb98de)

![Screenshot from 2022-12-06 12-38-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/456dce57-7690-47d5-b411-4a227cf07b7e)

![Screenshot from 2022-12-06 12-39-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1be18e1a-3d68-4979-b7de-558eaeb8e69c)

##### political-science
![Screenshot from 2022-12-06 12-44-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/805f9a18-d6e8-40ae-996b-674103236dfb)

![Screenshot from 2022-12-06 12-49-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6e7360f7-63f6-4ce6-8b79-6c48780c65c2)

![Screenshot from 2022-12-06 12-51-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9ee9935c-0eca-4a02-a764-63d56203c74a)

![Screenshot from 2022-12-06 12-51-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/08c3937f-a7a7-472a-a413-ab92aca1a718)

![Screenshot from 2022-12-06 12-52-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6066cc2b-7888-4746-813e-cb19cacaebdf)

##### contemporary-math
![Screenshot from 2022-12-06 12-55-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0abb082a-d0d1-4166-b278-a14fc5efb9e3)

![Screenshot from 2022-12-06 12-56-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e18e3028-f5cc-44b3-a626-cf63911579b8)

![Screenshot from 2022-12-06 12-56-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f86c608b-48d5-43f8-a961-9ea200aaab85)

![Screenshot from 2022-12-06 12-57-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bd94ade6-d156-4b58-9c97-98fd14e82555)

###### sociology
![Screenshot from 2022-12-06 13-09-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/63a9f2a3-8c3f-41e3-b30c-bc1e63991db4)

![Screenshot from 2022-12-06 13-10-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/abd17050-3759-40c5-9d46-a399587587ad)

![Screenshot from 2022-12-06 13-10-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9317183f-be3b-44bf-80de-de089b8b008d)

![Screenshot from 2022-12-06 13-11-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bb33f1d5-9c81-43a7-9036-15f715dba2da)

![Screenshot from 2022-12-06 13-12-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9a5afd4b-321c-4737-a0a4-a628d0e3d5b9)

##### astronomy
![Screenshot from 2022-12-06 13-18-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c8161db7-2291-4141-880b-4b3b26d36810)

![Screenshot from 2022-12-06 13-17-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/65930a47-1387-4e1a-93b4-62bac16c51fd)

![Screenshot from 2022-12-06 13-17-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3eace3ef-a4e6-4b04-8a3f-ff548a73ca2d)

![Screenshot from 2022-12-06 13-16-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5a45ea7b-8ecc-4226-9471-1f6d4a3a94c1)

![Screenshot from 2022-12-06 13-15-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/63b04d8e-1eaa-442f-9bea-588b69c3518c)

**Comment by lwtchu** [comment]
looked at principles of marketing, ochem, world history vol 2, computter programming w python, economics 3e, and contemporary math
