### ISSUE TITLE
lists refactoring - standardize lists with special attributes

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4928]
- [x] Stepwise Lists - standardize components names within themes (`corn`, `cardboard - finance`)
- [x] Stepwise Lists - style unnumbered list (`cardboard - finance`)
- [x] Stepwise Lists - remove styles from `common-styles` file and move them to `StepwiseListsShape`
- [x] Unstyled Lists - remove component from `carnival:::TableListShape`. It's coved in `common-styles` file
- [x] Unstyled Lists - change component name for unstyled list from note (`corn`) to avoid confusion. It's not list with `[data-bullet-style='none']` attribute.
- [x] Titled Lists - move shape to titles files (`carnival - pl-u-physics`)

**Comment by MartaSztuka** [comment]
#### PASSED
##### finance
![Screenshot from 2022-12-14 10-11-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3d30dd03-2832-4e4d-aca5-e5448495b8ae)

![Screenshot from 2022-12-14 10-12-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0f396935-742e-4069-ae6c-ef74b64a44f9)

![Screenshot from 2022-12-14 10-13-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/30a43c08-5b54-4000-89a6-5d376e7b09d6)

##### fizyka 1
![Screenshot from 2022-12-14 10-37-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/213d0376-20bb-4f05-a6ff-e2a96ae86d54)

![Screenshot from 2022-12-14 10-38-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bb0bbe40-c356-4ec7-aa5f-8e2ac219129f)

![Screenshot from 2022-12-14 10-38-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/85f2291e-8428-4fad-9959-ad3307410696)

![Screenshot from 2022-12-14 10-39-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0b1a4d41-b2fb-4d34-9384-ace3f4051ace)

##### philosophy
![Screenshot from 2022-12-14 10-44-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fef1736f-009b-4444-96dc-3ac095fb845b)

![Screenshot from 2022-12-14 10-44-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/651a0a35-4ff0-4a61-8f81-211262d52f8b)

##### financial accounting
![Screenshot from 2022-12-14 11-26-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/42e54a06-d7cf-4b5b-b531-5976c9374f3b)

![Screenshot from 2022-12-14 11-25-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ebd46a13-9fa2-4d88-8d68-310247ae66ff)

![Screenshot from 2022-12-14 11-24-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/41099def-3be4-459e-a0d3-7f42c632293c)

![Screenshot from 2022-12-14 11-25-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/55e3e0f0-e9fd-4af4-83e6-b60e6123bca9)
