### ISSUE TITLE
Calculus - Key Equation Styling Changed

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#4929]
# Brief Description of Scenario
At some point the lines dividing the equations in the "Key Equations" section of the EOC have lost their styling, reverting to a broken wide-stroke line. 

The title for each equation also appears to have changed style. 

# Pattern of Occurrence 

Consistent Occurrance

# Acceptance Criteria

A) Styling of Calculus Key Equations is returned
B) The new style is judged to be adequate
  
# Screenshots
## Before
![CleanShot 2022-12-08 at 08.41.05.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/769880f9-3369-4bfd-89e8-a11765af034e)

## After
![CleanShot 2022-12-07 at 16.57.38.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0295cd1a-ed3d-4762-b084-394bdd0606e8)

# Location(s)
- **osbooks repo:** osbooks-calculus-bundle
- **collection slug:** calculus-volume-1
- **ref/branch:** main
- **chapter/section:** EoC
- **surrounding text:** N/A

**Comment by wilkus27** [comment]
@lwtchu It was changed within this issue: https://github.com/openstax/cnx-recipes/issues/4857. Should I revert that change?

**Comment by lwtchu** [comment]
@wilkus27 oh right. let me...think. maybe we need to set a different class on these. I'll take a look at the content today to see how big the content change scope will be

**Comment by lwtchu** [comment]
@wilkus27 these have the `unnumbered unstyled` class on them - could we just revert the change for the ones tagged with `unstyled`? the other regular tables can have the darker line

**Comment by wilkus27** [comment]
@lwtchu My only concern is that `unnumbered unstyled` table might appear also within features with colored background. I think better solution will be to create separate settings for tables from Key Equations, but I'm not sure if such selector be strong enough. If not, then we have to add additional class. For now we can try with `.os-key-equations-container  .os-table.os-unstyled-container`.

**Comment by lwtchu** [comment]
@wilkus27 sounds good i'll make the class and update the issue once everything is updated

**Comment by lwtchu** [comment]
Strategy for this card
1. See if we can isolate the style for `unnumbered unstyled` tables within Key Equations
2. If not, please @ me and I can make the content change to add a new class and then you can make a small change in cookbook and styles

**Comment by jbwilson8** [comment]
@lwtchu In the original styling there is a break in the line because it is a table. Is this still acceptable?
![Screen Shot 2023-01-23 at 1 25 51 PM](https://user-images.githubusercontent.com/26155528/214131303-adf3d58d-755a-4900-acee-8b8dcb5778d8.png)

**Comment by lwtchu** [comment]
@jbwilson8 this is acceptable and expected

**Comment by MartaSztuka** [comment]
#### PASSED
###### Calculus 1
![Screenshot from 2023-01-24 14-33-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/134f3a1c-1402-461d-ac6a-178016e96c62)

###### Calculus 2
![Screenshot from 2023-01-24 15-10-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/510cb47c-d72b-454e-bbf0-215a372f9a59)
###### Calculus 3
![Screenshot from 2023-01-24 15-12-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4f3ade7a-8126-44e8-ab30-834469a1c582)
