### ISSUE TITLE
Add dedication note styling to Organic Chemistry

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#4931]
# Brief Description of Scenario
Author and editorial want to add a dedication page to Organic Chemistry and have it included in REX. A workaround discussed with Larissa is creating a "Dedication and Preface" module for Organic Chemistry. This module would begin with a note with class `dedication-page` and include an unnumbered figure plus some text.

I've added test code to a branch in the organic chemistry repo here: https://github.com/openstax/osbooks-organic-chemistry/tree/dedication-test

# Pattern of Occurrence 
This will only appear in the preface of Organic Chemistry

# Acceptance Criteria
**NOTE FROM LARISSA: PLEASE SEE BELOW FOR SPECS** 
Dedication note class is styled and doesn't explode rex. Here is the mockup Micah styled for the print version (that may not be used if this preface version works out): [https://app.zenhub.com/files/49744755/fec9412e-412e-4a21-99e8-7f28211e7eb8/download](https://app.zenhub.com/files/49744755/fec9412e-412e-4a21-99e8-7f28211e7eb8/download)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:** https://github.com/openstax/osbooks-organic-chemistry/tree/dedication-test
- **chapter/section:** preface
- **surrounding text:** Peter McMurry

**Comment by lwtchu** [comment]
![Screen Shot 2022-12-16 at 1 44 08 PM](https://user-images.githubusercontent.com/11299125/208177027-45460320-2eea-4f7d-a9f6-fb42c420ba56.png)

## Stroke
weight: 1.5pt
color: B2: `#0074BC`

## Body text
same as preface text

## caption under image
font size: font-scale(2): 12.96pt, 16.8px, 1.4rem
color: B2: `#0074BC`

**Comment by wilkus27** [comment]
@lwtchu This is what it looks now.

Is it possible to remove title "Dedication" from the content? If not, I will try to do this by recipe.

Also I added bold to figure caption to match picture from above. Is it ok, or should I remove it?

![image](https://user-images.githubusercontent.com/40228854/210244152-52db6354-7755-4758-907b-f870e8b25568.png)

**Comment by lwtchu** [comment]
@wilkus27 removed!

**Comment by MartaSztuka** [comment]
@wilkus27 There is an extra line
![Screenshot from 2023-01-09 15-52-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/73d082b6-785d-4af4-840c-6d05f3fe52ac)

**Comment by lwtchu** [comment]
@MartaSztuka 🤔 let's leave as is for now. i suspect we'll have to remove it but i want to make sure this is okay for the author before we do more work

**Comment by wilkus27** [comment]
@MartaSztuka This is an underline for Preface title.

**Comment by Stackblocks** [comment]
![CleanShot 2023-01-17 at 12 04 41](https://user-images.githubusercontent.com/12678235/212977185-bf8c5477-e163-456b-b995-f68766cb9894.png)

A couple of things are off when generated on CORGI, but there may be a number of reasons why. Marking this in the issue for the time being, but since the other elements of the release have gone out OK i'll re-close this for the time being and we can open a new card for continuing work.

**Comment by lwtchu** [comment]
Hmm It's not showing up still. I'm going to convert your comment into an issue for the next sprint
