### ISSUE TITLE
computer programming with python - add new elaboration feature 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4932]
# Design Summary
Documentation #2737
color option 3
title driven by content in `<title>`
Title: black `#000000`
Top bar: O2: `#D34D32`
Bottom box: B5: `#D6D9DD`
contains mostly text
no class
  
# Sample Mark-Up
```
     <note id="note-00001">
        <title>Python style guide</title>
        <para id="para-00005"><link url="https://peps.python.org/pep-0008/">PEP 8</link> is the official style guide for Python. <term id="term-00001">PEP</term> stands for Python Enhancement Proposal. Members of the Python community write PEPs to document best practices and propose new features. The table below is based on several guidelines from PEP 8.</para>
      </note>
```

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-computer-programming-python/
- **collection slug:** computer-programming-python
- **ref/branch:**
- **chapter/section:**  Formatting code
- **surrounding text:** Python style guide

**Comment by wilkus27** [comment]
@lwtchu This is what it looks like:

![image](https://user-images.githubusercontent.com/40228854/210330219-373962d0-ffaa-4785-af3c-b767fdd29a3c.png)

**Comment by lwtchu** [comment]
@wilkus27 looks great !

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-01-09 10-58-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8a581068-db10-467a-a3f6-94f56b1a4f3f)
