### ISSUE TITLE
computer programming with python - add example feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4933]
# Design Summary
Documentation #2899 (but please use the fonts for the business series, use roboto condensed and not dosis)

![Screen Shot 2022-12-21 at 9 38 56 AM](https://user-images.githubusercontent.com/11299125/208943895-a7e79e80-2aee-411f-bf60-92c5f916e83f.png)

New color scheme
Top bar: G1: `#1E9575`
Bottom box: G2: `#F2F2F2`
Text: Black `#000000`

Numbering: #.#
Subtitle from `<title>`
  
# Sample Mark-Up
```
      <example id="exam-00001">
        <title>Fun with print()</title>
        <para id="para-00014">Ex. "The weather for today is sunny!" is printed to the screen on a single line by the following:</para>
        <code class="python" lang="python">print("The weather for today is", end=" ")</code> 
        <code class="python" lang="python">print("sunny!")</code>
      </example>
```

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-computer-programming-python/
- **collection slug:** computer-programming-python
- **ref/branch:**
- **chapter/section:**  Formatting code
- **surrounding text:** Python style guide

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-01-09 11-00-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c8725ac9-d5fe-444e-881f-946355935769)
