### ISSUE TITLE
Organic Chemistry - embedded exercises - enabling `exercise-block` in EOC sections

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4936]
# Context
Is there a way to turn off the inline display of the (a) (b) (c) in multipart questions?
The OSX email "Organic Chemistry Round 2 Prototype" from 9/14 (see screenshot below) seems to indicate that there is. 

# New specifications or link to documentation cards
![image](https://user-images.githubusercontent.com/89537088/210655584-4c25284d-02a1-4f37-9d15-c5271c39e633.png)

**### Screenshot from 9/14 email**
![image](https://user-images.githubusercontent.com/89537088/210653636-8a1c0dc5-39bb-4982-98a6-d56062db2786.png)

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<exercise id="exer-00002">
  <problem id="prob-00002">
    <para id="para-00015"><link class="os-embed" url="#exercise/02-06-OC-P10"/></para>
  </problem>
</exercise>
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** chapter 02 / Section 2.6 / Module m00023 /Assessment Nickname:02-06-OC-P10  ID:36122@3
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax The tagging is on row 52. Please add the class `exercise-block` to the link.

```
<exercise>
<problem>
<para><link class="os-embed exercise-block" url="#exercise/Nickname"/></para>
</problem>
</exercise>
```

**Comment by ww-openstax** [comment]
added exercise-block to class attribute but it did not work

module m00023 line 93
`<exercise id="exer-00002">
  <problem id="prob-00002">
    <para id="para-00015"><link class="os-embed exercise-block" url="#exercise/02-06-OC-P10"/></para>
  </problem>
</exercise>`

Section 2.6 exercise 10
https://openstax-cops-artifacts.s3.amazonaws.com/organic-chemistry-latest-git-8710.pdf

**Comment by lwtchu** [comment]
# Acceptance Criteria
We enabled this class in the EOC, but please enable it in the `section-exercise`

**Comment by LostMojo** [comment]
Hey @jbwilson8 I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/ce-styles-5cdc84baee941c07853fbbf2/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by jbwilson8** [comment]
@lwtchu the exercise block class isn't present in the EOC? Do you want someone with coobook knowledge to add them in or do we want to make all of the exercises block instead of inline?

**Comment by lwtchu** [comment]
@jbwilson8 we should add this class functionality in for the EOC - we don't want all of the exercises to be block. :eyes: i can remove the label on this if we're not ready to onboard onto cookbook yet

**Comment by lwtchu** [comment]
New temporary content to get around the enki error until broken links are resolved within content: https://github.com/openstax/osbooks-organic-chemistry/tree/larissa-test

**Comment by Stackblocks** [comment]
The distractors are now showing up as more styled, but a/b & c/d are still inline with one another. 

@jbwilson8 Looks like it may need some additional tweaks, but that can roll forward to next sprint per @lwtchu 

![CleanShot 2023-02-09 at 15 12 59](https://user-images.githubusercontent.com/12678235/217940966-ddff60cf-8075-4b65-81b1-d99fea09ea1f.png)

**Comment by Stackblocks** [comment]
- Displays OK with updated code & content from distinguished.dragonology.

![CleanShot 2023-02-20 at 11.23.13.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c184df3c-070d-4e30-a5f6-9fdd6f4df44d)
