### ISSUE TITLE
Organic Chemistry - need span class="yellow-text" and "purple-text"

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4937]
# Context
Content includes text with yellow color and tagging is needed similar to other span classes in tagging legend row 49

![image](https://user-images.githubusercontent.com/89537088/211233059-aa562fe0-72fb-4c95-af5c-b88493e72249.png)

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<figure id="fig-00002">
       <title>Electronegativity values and trends.</title>
    <media alt="Electronegativity values and trends.">
              <image mime-type="image/jpeg" src="../../media/OChem_02_01_002.jpg"/>
            </media>
    <caption>Electronegativity generally increases from left to right across the periodic table and decreases from top to bottom. The values are on an arbitrary scale, with F = 4.0 and Cs = 0.7. Elements in <emphasis effect="bold"><span class="red-text">red</span></emphasis> are the most electronegative, those in <emphasis effect="bold">yellow</emphasis> are medium, and those in <emphasis effect="bold"><span class="green-text">green</span></emphasis> are the least electronegative.</caption>
    </figure>
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** chapter 02 / Section 2.1 / Module m00018  fig-00002
- **surrounding text:**

**Comment by lwtchu** [comment]
## Acceptance Criteria

New `<span class="yellow-text">` has been added to the content and tagging legend.

Please use the same functionality as the other color text and use the Y1: `#8F7200` color (this is new, please add to the theme list of colors)

**Comment by ww-openstax** [comment]
@lwtchu 
In addition to yellow text we also need purple text. Thanks.
![image](https://user-images.githubusercontent.com/89537088/213951074-d45d3a33-ee9f-4912-b502-0ccc8847e8ec.png)

**Comment by LostMojo** [comment]
@lwtchu do you have a hex color for the purple text we want here?

**Comment by lwtchu** [comment]
please use class `purple-text` and use P1: `#8d4c83`

**Comment by LostMojo** [comment]
@lwtchu On the main git branch of organic chemistry, it looks like the caption portion used as an example hasn't been given the class "yellow-text", also, is there a good testing location for "purple-text?"

**Comment by lwtchu** [comment]
Test content on `larissa-test` branch in  m00018 surrounding text: electronegativity generally increases from left to right

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-01-25 10-21-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0cc4205d-0df9-486e-b426-eb2a077daa58)

![Screenshot from 2023-01-25 10-22-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/428187b8-0633-40bb-bcd4-22660ba5be8e)
