### ISSUE TITLE
Organic Chemistry - MathML Equations Should Be Centered

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4938]
# Context
Tagging legend does not contain equation container tag. Tagging legend does not contain method for centering equations. 
Equations need to be centered.

We tried using equation tagging present in Chemistry 2e but this does not center equations in Organic Chemistry.

![image](https://user-images.githubusercontent.com/89537088/211243943-c5b7a141-bca7-4479-9e46-38c2b7bc4762.png)

# New specifications or link to documentation cards
This screenshot is from Chemistry 2e. The equations in Organic Chemistry should be centered like this:
![image](https://user-images.githubusercontent.com/89537088/211245777-a795fefb-16db-4d9c-a6a0-609e14dff17f.png)

# Acceptance Criteria

# Content
## Sample Mark-Up
This is tagging from Organic Chemistry
```
<para id="para-00001">Acids differ in their ability to donate H<sup>+</sup>. Stronger acids, such as HCl, react almost completely with water, whereas weaker acids, such as acetic acid (CH<sub>3</sub>CO<sub>2</sub>H), ... moles per liter.</para>
<equation class="unnumbered" id="eq-00001"><label/><m:math display="block">
  <m:mrow>
  <m:mtext>HA</m:mtext><m:mo>+</m:mo><m:msub>
  <m:mtext>H</m:mtext>
  <m:mn>2</m:mn>
  </m:msub>
  <m:mtext>O </m:mtext><m:munder>
  <m:mo stretchy="true">⇄</m:mo>
  <m:mrow>
  <m:msub>
  <m:mi>K</m:mi>
  <m:mtext>a</m:mtext>
  </m:msub>
 ...
  </m:mrow>
  </m:math></equation>
```
This is tagging from Chemistry 2e
```
<para id="fs-idp89436016">For purposes of this brief introduction, we will consider only the more common types of acid-base reactions that take place in aqueous solutions. In this context, an <term id="term-00007">acid</term> is a substance that will dissolve in water to yield hydronium ions, H<sub>3</sub>O<sup>+</sup>. As an example, consider the equation shown here:</para>
<equation id="fs-idm54028336" class="unnumbered"><m:math><m:mrow><m:mtext>HCl</m:mtext><m:mo stretchy="false">(</m:mo><m:mi>a</m:mi><m:mi>q</m:mi><m:mo stretchy="false">)</m:mo><m:mo>+</m:mo><m:msub><m:mtext>H</m:mtext><m:mn>2</m:mn></m:msub><m:mtext>O</m:mtext>
...
</m:mrow></m:math></equation>
```
## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** All block-level mathML equations; the screenshot is from chapter 02 / Section 2.8 / Module m00025
- **surrounding text:**

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2023-01-27 at 10.23.26.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/982e905b-dd60-4f16-bb60-be2bc5362e95)
