### ISSUE TITLE
contemporary math - answer key folio missing

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4940]
# Brief Description of Scenario
![Screen Shot 2023-01-09 at 1 02 43 PM](https://user-images.githubusercontent.com/11299125/211387246-e4e31b76-ddd7-4727-81ae-e4ea26aaca6d.png)

Folio missing for Answer Key (it should say Answer Key) like the other titles and not just the page number

# Pattern of Occurrence 
All in the Answer Key...i suspect it might cover other corn theme books as well as the same issue is in calculus but priority is to fix contemporary math

# Acceptance Criteria
Folio should have the words Answer Key
  
# Sample Mark-Up
```
N/A
```

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-contemporary-math
- **collection slug:** contemporary-math
- **ref/branch:** main
- **chapter/section:** answer key
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-01-24 16-44-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cc37e059-2783-45db-8c34-96abf8d7ebe5)

**Comment by MartaSztuka** [comment]
##### EDIT: previous comment was missing calculus books
###### Calculus 1
![Screenshot from 2023-01-30 14-18-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cd372cae-e8c7-4b12-a1d1-ac42f4f726ed)

###### Calculus 2
![Screenshot from 2023-01-30 14-24-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/31bbb794-a9e7-46d5-967a-e8952ebb5fe7)

###### Calculus 3
![Screenshot from 2023-01-30 14-25-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/80ad7c68-f307-4a65-b664-4ecd8b63b9cd)

###### Cálculo 1
![Screenshot from 2023-01-30 14-28-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c0a3eb02-1e48-48f2-b5ec-9946a9427c6a)

###### Cálculo 2
![Screenshot from 2023-01-30 14-29-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b80c003a-2f13-4b35-a5c4-70d436a74366)

###### Cálculo 3
![Screenshot from 2023-01-30 14-45-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4c82e9ce-063a-4394-af95-d9b00c636243)
