### ISSUE TITLE
:bug: Empty `id=""` attribute on Mathy Note titles (intro-statistics, prealgebra, ...)

### ISSUE THREAD

**Issue by philschatz** [openstax/cnx-recipes#4941]
# Brief Description of Scenario

Some note titles get a superfluous `id=""` attribute added to them. This is causing the EPUB/XHTML validator to fail.

# Pattern of Occurrence 

It only occurs _very rarely_, only once per book even though the books have many notes with titles in them.

# Acceptance Criteria

The following content no longer has an `id=""` attribute added to it:

# Location(s)

- [ ] [college-physics-ap-courses](https://rex-web.herokuapp.com/books/8d04a686-d5e8-4798-a27d-c608e4d0e187@1aa3e7a/pages/d1df5bf8-e6f7-4e8c-a2af-8b3e8ff58e32?archive=https://openstax.org/apps/archive/20221109.213337#fs-id2736712)
- [ ] [elementary-algebra](https://rex-web.herokuapp.com/books/55931856-c627-418b-a56f-1dd0007683a8@97c23b7/pages/7dabdf2f-b279-41b5-8346-2c7f5e9341a7?archive=https://openstax.org/apps/archive/20221109.213337#eip-345) (This one's a `<table class="unnumbered">`)
- [ ] [introduccion-estadistica](https://rex-web.herokuapp.com/books/e53d6c8b-fd9e-4a28-8930-c564ca6fd77d@dc4550b/pages/b5743be1-228f-419c-a947-e5737622c8aa?archive=https://openstax.org/apps/archive/20221109.213337#eip-id1168998191288)
- [ ] [introductory-statistics](https://rex-web.herokuapp.com/books/30189442-6998-4686-ac05-ed152b91b9de@b2d6c72/pages/b5743be1-228f-419c-a947-e5737622c8aa?archive=https://openstax.org/apps/archive/20221109.213337#eip-id1168998191288)
- [ ] [statistics](https://rex-web.herokuapp.com/books/394a1101-fd8f-4875-84fa-55f15b06ba66@fb75e63/pages/a3009cb3-5fb6-4464-99c1-29312f4c830b?archive=https://openstax.org/apps/archive/20221109.213337#fs-idp12863088)

refs https://github.com/openstax/ce/issues/1966

**Comment by philschatz** [comment]
Fixed!

**Comment by lwtchu** [comment]
Phil thinks this is fixed. Closing.
