### ISSUE TITLE
Organic Chemistry - Selecting MathML in PDF - Inconsistent "White Boxes" 

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4942]
# Brief Description of Scenario
In the PDF we would like to determine what has been tagged as MathML. We noticed that when selecting text in the PDF some instances of MathML are enclosed in a white box and other instances of MathML are NOT enclosed in a white box (see screenshots below). Why is this?
Is there a way in the PDF to determine what has been tagged as MathML?

**Screenshot of PDF with selected text**
![image](https://user-images.githubusercontent.com/89537088/211590047-5fd8622e-c078-4a9a-b758-6818d467132c.png)

**Screenshot of POET XML of two paras in screenshot above**
![image](https://user-images.githubusercontent.com/89537088/211592502-16a81579-197f-4ee3-8ae6-752f5b99e282.png)

# Pattern of Occurrence 
NO discernable pattern of occurrences.

# Acceptance Criteria

  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Screenshot is from Section 2.2 / Module m00019
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax The MathML is set as an SVG (image) so it won't highlight. Adobe Acrobat can make some assumptions and highlight single letters. Below is a screenshot from the Google Chrome PDF reader where the single letters aren't highlightable. Unfortunately at the moment, we can't enable highlight for the text in math as it isn't possible yet in the pipeline.

![Screen Shot 2023-01-10 at 10 39 54 AM](https://user-images.githubusercontent.com/11299125/211610238-a1e9c45d-bafd-4e27-85f1-dd9952b76b03.png)
