### ISSUE TITLE
Organic Chemistry -- EOC Assessments -- add new sections

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4943]
# Context
There is tagging for "Visualizing Chemistry" questions section in EOC assessments (see row 41 of tagging legend)
But we have another section that is entitled "Mechanism Problems" and there are many other sections in other chapters.
Would it be possible to create a generic section that captures the heading from the `<title>` tag

# New specifications or link to documentation cards
Add new EOC sections (working on content right now)
- Mechanism Problems
- General Problems
- Energy Diagrams and Reaction Mechanisms

## Impact 

# Acceptance Criteria
- EOC sections should not autopopulate. Some sections do not have these. 
- They contain embedded exercises.

# Content
## Sample Mark-Up
```
<section class="visualizing-chemistry" id="sect-00004">
  <title>Visualizing Chemistry</title>
  <exercise id="exer-00002">
    <problem id="prob-00002">
      <para id="para-00019"><link class="os-embed" url="#exercise/02-99-OC-VC20"/></para>
    </problem>
  </exercise>
  <exercise id="exer-00003">
    <problem id="prob-00003">
      <para id="para-00020"><link class="os-embed" url="#exercise/02-99-OC-VC21"/></para>
    </problem>
  </exercise>
  <exercise id="exer-00004">
    <problem id="prob-00004">
      <para id="para-00021"><link class="os-embed" url="#exercise/02-99-OC-VC22"/></para>
    </problem>
  </exercise>
  <exercise id="exer-00005">
    <problem id="prob-00005">
      <para id="para-00022"><link class="os-embed" url="#exercise/02-99-OC-VC23"/></para>
    </problem>
  </exercise>
  </section>
  <section id="sect-00005" class="visualizing-chemistry">
  <title>Mechanism Problems</title>
  <exercise id="exer-00006">
    <problem id="prob-00006">
      <para id="para-00023"><link class="os-embed" url="#exercise/02-99-OC-MP24"/></para>
    </problem>
  </exercise>
  <exercise id="exer-00007">
    <problem id="prob-00007">
      <para id="para-00024"><link class="os-embed" url="#exercise/02-99-OC-MP25"/></para>
    </problem>
  </exercise>
  <exercise id="exer-00008">
    <problem id="prob-00008">
      <para id="para-00025"><link class="os-embed" url="#exercise/02-99-OC-MP26"/></para>
    </problem>
  </exercise>
  <exercise id="exer-00009">
    <problem id="prob-00009">
      <para id="para-00026"><link class="os-embed" url="#exercise/02-99-OC-MP27"/></para>
    </problem>
  </exercise>
  </section>
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 02 / EOC Assessments / module m00029 /
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax I don't think we can create generic sections. I did look through the 9e version of the book and found two additional sections that we can add: Mechanism Problems and General Problems. If that's okay, we can add the two...unless there are some other planned sections to add.

**Comment by lwtchu** [comment]
@caylaeagon in the organic-chemistry/larissa-test branch (make sure you're on the larissa branch) please add the following sections with the corresponding class (like an EOC section) to ONLY ONE chapter and place 1 or 2 exercises in there.  Let me know when you're finished and I can move this into the backlog

Mechanism Problems `mechanism-problems`
General Problems `general-problems`
Energy Diagrams and Reaction Mechanisms `energy-reaction`

**Comment by lwtchu** [comment]
CONTENT SHOULD BE READY on `larissa-test` branch. Please implement like the other EOC sections in Organic Chemistry

**Comment by Stackblocks** [comment]
The sections exist, but it looks like number styling isn't properly configured.

![CleanShot 2023-01-26 at 16.10.44.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/150df3bb-d701-4ea9-965d-4873235d6161)

![CleanShot 2023-01-26 at 16.14.00.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/83d619d9-04c0-47bd-8ec2-37a3d8461355)

**Comment by lwtchu** [comment]
@Stackblocks i'll open a new card for it.
