### ISSUE TITLE
objectives and outline refactoring - lists

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4944]
- Move lists components to `lists-components` file
- Standardize components names

**Comment by wilkus27** [comment]
There are no changes in output.

**Comment by MartaSztuka** [comment]
#### PASSED
##### philosophy
![Screenshot from 2023-01-18 09-49-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8d8e5fe3-f1f3-4076-a251-2d26e0736438)

##### political science
![Screenshot from 2023-01-18 10-03-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c116b689-fda6-43f5-86af-bb4171b36979)

##### precalculo
![Screenshot from 2023-01-18 10-05-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/682d9a13-6edd-484b-b6e1-11496f2f881a)

##### mikroekonomia
![Screenshot from 2023-01-18 10-06-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/912ab699-b25b-4136-8129-fade181fe208)

##### astronomia
![Screenshot from 2023-01-18 10-07-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/52c9363a-7747-4586-a933-261ce0b08a3b)

##### managerial accounting
![Screenshot from 2023-01-18 10-09-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ecff4690-0f4b-4bbd-b69b-9eba6755c603)
