### ISSUE TITLE
Organic Chemistry - Figures in Exercises - "scaled-down" class

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4945]
# Context
We want to scale down figures that are in Exercises in webview
There is a scale-down class in the cnXML `<figure class="scaled-down">`  (Row 29 in Tagging Legend)
`<figure class="scaled-down">` does not work in Exercises. Is there an HTML class for webview scaling-down of figures that are in Exercises? Or is their other tagging that we can use to scale down figures in Exercises?

![image](https://user-images.githubusercontent.com/89537088/212093133-6169c800-84b1-48d8-926e-a1240bf385cc.png)
# New specifications or link to documentation cards

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:**  Chapter 02 / EOC Assessments / module m00029 /  Exercises editor tool
- **surrounding text:**

**Comment by lwtchu** [comment]
# Acceptance Criteria

We need to enable the `scaled-down` and `scaled-down-30` classes on `<img>`s on webview. I've added it to Chapter 2 Additional Problems > questions 60 and 61

**Comment by lwtchu** [comment]
New temporary content to get around the enki error until broken links are resolved within content: https://github.com/openstax/osbooks-organic-chemistry/tree/larissa-test

**Comment by LostMojo** [comment]
Two things of note for later:

Sometime since the original screenshot was taken, it seems the numbering format has changed. I don't know if that was intentional or not.

![Screen Shot 2023-01-20 at 1.56.00 PM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/a64e41cb-68bc-44db-a077-e477d95c59e2)

Second, There's a lot of image styling in a shape that's just called "figureShape" we might want to refactor this later so it's a little clearer.

**Comment by Stackblocks** [comment]
Displays OK with current code & content

![CleanShot 2023-01-26 at 16.02.30.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5135282e-2656-422b-899e-559ca03a99a4)![CleanShot 2023-01-26 at 16.01.18.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/22b5d73f-1b66-4132-8c48-b042d92bea75)
