### ISSUE TITLE
Organic Chemistry - Exercises - Link to in-text image formatting fix

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4948]
# Context
For Exercises: the link generated from attaching an Element ID to a question needs a formatting fix.
Please remove the return and close up the text and the period. See screenshot below.

# New specifications or link to documentation cards
![image](https://user-images.githubusercontent.com/89537088/212730381-f47c87ae-6662-4623-aea4-3fb6afea66d4.png)

## Impact 
All books

# Acceptance Criteria
Period should not longer be on a separate line.

# Content
## Sample Mark-Up
![image](https://user-images.githubusercontent.com/89537088/212733964-24fc655e-a604-4ff9-81d1-d61a2b5c27d3.png)

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** screenshot is from ch02 / section 2.1 / module 00018 Exercise Nickname:02-01-OC-P03 ID:36114@9
- **surrounding text:**

**Comment by lwtchu** [comment]
Global decision: Please set all links in **embedded exercises** as plain text. OpenStax acknowledges that this goes against our rules, but we will only do this for the embedded exercises for this title. We will have to investigate again when we make further improvements to the pipeline.
