### ISSUE TITLE
Organic Chemistry - Inline Image - Need Art Specifications

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4949]
# Context
For inline images (tagging legend row 27), we need art specifications -- max width/height. Open Guide Art Guidelines does not provide specifications for inline images.

![image](https://user-images.githubusercontent.com/89537088/212906260-d4008c1a-c065-409c-81a6-3648398e2f96.png)

![image](https://user-images.githubusercontent.com/89537088/212903231-75cc8497-5361-4558-b4af-38af8d0b2f25.png)

## Impact 

# Acceptance Criteria

# Content
## Sample Mark-Up
```
 <media alt="Alt text placeholder" display="inline"><image mime-type="image/jpg" src="../../media/OChem_02_01_004.jpg"/></media>
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** ch02 / section 2.1 / module 00018 / Line 33
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax I added a paragraph on this page https://www.opengui.de/organic-chemistry in opengui.de. Please let me know if you need anything else.
