### ISSUE TITLE
[Waiting for Enki fix] contemporary math webview - Add styling to Answer Key

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4950]
# Brief Description of Scenario
The current styling of solution in Contemporary Math makes it hard to tell what's what.

# Pattern of Occurrence 
All solution sections of book.

# Acceptance Criteria
Maybe some tabs here, some bolds there. You know how it goes. 
  
# O.O
![Screenshot 2023-01-17 at 10.16.08 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/98b8d1ac-5472-4d22-84d0-7291ceed9e1d)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-contemporary-math
- **collection slug:** contemporary-math
- **ref/branch:** main
- **chapter/section:** Answer Key
- **surrounding text:** Answer Key

**Comment by lwtchu** [comment]
# Acceptance Criteria
Can we bold the numbering? The 1.1, 1.2, etc so it stands out more. 

If this is labeled specifically and won't impact other books, can we also bump up the font scale on this one line.

**Comment by wilkus27** [comment]
There is a problem with validation:

![image](https://user-images.githubusercontent.com/40228854/222074022-35f26930-9125-4b0d-bb8c-a3158c112ea5.png)

**Comment by wilkus27** [comment]
@lwtchu This is what it looks like:

![image](https://user-images.githubusercontent.com/40228854/232056447-7dd068e5-1532-4603-8797-529f604a0fc3.png)

Do you want me to change something?

**Comment by lwtchu** [comment]
@wilkus27 is that what it looks like now? 🤔

**Comment by wilkus27** [comment]
This is after my changes. I changed only styles for 1.1 etc.

**Comment by lwtchu** [comment]
@wilkus27 AH okay sorry for the confusion. In colby's original screenshot, the links aren't underlined - is there a way to remove that?

**Comment by lwtchu** [comment]
@wilkus27 ah yeah - might be good to set it in our style sheet too to reduce inconsistencies for now. when we switch over later it will be less things to fix. 🙏 thank you

**Comment by wilkus27** [comment]
### Information for tester

I still had problems in Enki to generate rex preview. I'm getting errors like here https://github.com/openstax/cnx-recipes/issues/4950#issuecomment-1449488499. 

Because of that I used rex preview from Corgi and applied there styles from my PR.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-17 17-09-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e163acc9-56f1-4e09-b5d6-d46aa9b5e231)
