### ISSUE TITLE
Organic Chemistry - Exercises - Linking Exercise Question to: in-text figures, other exercises, appendix

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4951]
# Context
We tested linking Exercise Questions to 1) figures in other modules, 2) other Exercise Questions, 3) Appendix -- all using the Element ID tag in the Exercises tool. All tests failed.  

1) In Exercises tool, when linking Exercise Question to figures, the value of attribute data-id is not unique across the book. For example, there are multiple data-ids with the value "fig-00001". This means that we cannot link to a figure in different module from the Exercise Question. See Screenshot 1

2) In Exercises tool, when linking Exercise Question to another Exercise Question, the Question does not output and an empty [link] outputs instead. See Screenshot 2

3) In Exercises tool, when linking Exercise Question to Appendix, the Question does not output and an empty [link] outputs instead. No data-id attribute exists on any element in the appendix. We tested with id attribute instead.  (Note the test tried to link to existing Appendix A because Appendix B does not yet exist.) See Screenshot 3.

**Screenshot 1**
![image](https://user-images.githubusercontent.com/89537088/213037758-63e9513d-dc6a-45bb-9144-958907327850.png)

**Screenshot 2**
![image](https://user-images.githubusercontent.com/89537088/213037961-cf98f3da-83e7-4d06-b393-4d550674319a.png)

**Screenshot 3**
![image](https://user-images.githubusercontent.com/89537088/213038207-40783bf3-adb6-4cfb-bf15-d837885f7790.png)

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Exercises Nickname:02-99-OC-AP59, Nickname:02-99-OC-AP45, Nickname:02-99-OC-AP64
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax For the first instance (linking to an image in another module), it's not possible in our platform. While the issues listed in 2 and 3 are possible to resolve, they will have an inconsistent design with the linking. I've discussed with Alina and our current proposal is to leave it hard-coded to have it resemble the 9e and to keep the design across all links in the exercises consistent. 

We can discuss this on the production call tomorrow morning!

**Comment by ww-openstax** [comment]
@lwtchu For "linking to an image in another module" this is especially important for EOC questions which are in the last module but refer to images in other modules, so we'll need to discuss.

Yes, let's discuss this on the production call tomorrow morning. Thanks!

**Comment by lwtchu** [comment]
Global decision: Please set all links in **embedded exercises** as plain text. OpenStax acknowledges that this goes against our rules, but we will only do this for the embedded exercises for this title. We will have to investigate again when we make further improvements to the pipeline.
