### ISSUE TITLE
Organic Chemistry - Add "Chemistry Matters" feature to TOC

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4952]
# Context
The author would like the "Chemistry Matters" feature box to be listed in the TOC. In the Chapter 02 case, author would like it to say:
**Chemistry Matters – Alkaloids: From Cocaine to Dental Anesthetics**

# New specifications or link to documentation cards
![image](https://user-images.githubusercontent.com/89537088/213271491-7c695aba-7644-4af5-a01b-9b3200603902.png)

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<note class="chemistry-matters" id="note-00001">
  <title>Alkaloids: From Cocaine to Dental Anesthetics</title>
  <para id="para-00008">Just as ammonia (NH<sub>3</sub>) is a weak base, there are a large number of nitrogen-containing organic compounds called <emphasis effect="italics">amines</emphasis> that are also weak bases. In the early days of organic chemistry, basic amines derived from natural sources were known as vegetable alkali, but they are now called <term id="term-00008">alkaloids</term>. More than 20,000 alkaloids are known. Their study provided much of the impetus for the growth of organic chemistry in the nineteenth century and remains today an active and fascinating area of research.</para>
...
</note>
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** ch02/ Section 2.12 / Chemistry Matters Feature Box / Module m00029 / line 52
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax Our system doesn't currently allow for notes to be populated in the TOC. I'll make a note to discuss with Alina, David and Anthony since this request came from the author.

**Comment by openstaxalina** [comment]
After talking with OpenStax Editorial - preference is for this to be an EOC, unnumbered section, retaining some design from the original feature.

Backup is to make this a numbered section right before the EOC - again retaining as much design of the original feature box as possible.

**Comment by lwtchu** [comment]
@kswanson33 Tagging you to review since it's a bit more complicated. On this branch, I've changed the note into a section https://github.com/openstax/osbooks-organic-chemistry/tree/larissa-test

Can we set it as a collating EOC section? In the TOC it should pull in the words "Chemistry Matters - Alkaloids: From Cocaine to Dental Anesthetics". This deviates from the current title setting. Please let me know if this causes any issues.

Also question - is there a way to add styling to just this section?

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-02-02 14-57-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/29b4d27e-cd71-4724-a858-dcc5ac25d201)

![Screenshot from 2023-02-02 14-58-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3f6f3cf5-9454-4a1d-bbd9-77a0db27d20c)

**Comment by lwtchu** [comment]
@MartaSztuka is the feature also styled :eyes:
