### ISSUE TITLE
common refactoring - custom paragraphs

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4954]
- Create files for `customPara`. Move there shapes from `common`, `annotation` and `citationPara` files. Rename shapes. For exmaple:

   a) ParagraphItalicShape
b) ParagraphWithIconShape
c) ParagraphIconShape
d) ParagraphWithIndentationShape
e) ParagraphWithBorderShape
f) ParagraphWithBorderAndIndentationShape
or something like that.

- Remove `PublicDomainText` shape from `common`. It's not used anywhere.

**Comment by wilkus27** [comment]
After deeper investigation, here are types of custom paragraphs shapes:

### `ParaAnnotationItalic`

Paragraph with `annotation-text` class, style with italic property:

![image](https://user-images.githubusercontent.com/40228854/213433430-80e6381f-f3e6-41a5-a409-ec9f6d24f66e.png)

### `ParaAnnotationWithIcon`

Paragraph with `annotation` class. Contains spans with different icons.

![image](https://user-images.githubusercontent.com/40228854/213434225-1e0adf0f-e1ca-4996-b16e-dbad9b62b66a.png)

### `ParaWithLeftBorder`

Paragraph with left border. Doesn't have one common class. For now, it's added for elements with classes `public-domain` and `student-sample`.

![image](https://user-images.githubusercontent.com/40228854/213435069-43aebaa8-0d3a-4343-b834-065cfdd12afd.png)

![image](https://user-images.githubusercontent.com/40228854/213435244-374c1144-85dc-4f06-be06-1dead55ee1f9.png)

### `ParaCitation`

Paragraph with `citation` class, style with indent.

![image](https://user-images.githubusercontent.com/40228854/213435712-26a0401d-28a6-4464-be96-1e6acc353afd.png)

### `ParaCitationWithLeftBorder`

Paragraph with `citation` class and class of other element (for now `public-domain` and `student-sample`), style with indent and left border.

![image](https://user-images.githubusercontent.com/40228854/213436942-28788672-46ec-47ab-9e10-2f70b02c8dcb.png)

![image](https://user-images.githubusercontent.com/40228854/213437308-e7e55b0c-9ede-4f4f-8d8b-fe54c3abed5e.png)

**NOTE** All these elements appear only in english composition/writing guide book.

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content
![CleanShot 2023-01-20 at 11 42 25](https://user-images.githubusercontent.com/12678235/213768602-04e774b0-e8b0-4e7a-b074-42e2274002fc.png)
---
![CleanShot 2023-01-20 at 11 42 47](https://user-images.githubusercontent.com/12678235/213768630-5ed64ee6-18db-4f7d-9776-e0d9a8d629c9.png)
---
![CleanShot 2023-01-20 at 11 41 53](https://user-images.githubusercontent.com/12678235/213768664-4321d824-85ed-4cda-814c-7cc569e63dea.png)
---
![CleanShot 2023-01-20 at 11 40 42](https://user-images.githubusercontent.com/12678235/213768696-a5345008-09c6-4b4f-b4bd-4e7f2ea98341.png)
