### ISSUE TITLE
[pending ch2 review] Organic Chemistry -- Headings above "section problems"

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4957]
# Context
Note:
In the Answer Key, the 9e answer key does not separate by section
In the in-chapter problems,  headings above section problems do not appear in 9e

# New specifications or link to documentation cards
![image](https://user-images.githubusercontent.com/89537088/213455139-00ff079f-deec-4eaf-9531-9bc7b4667c43.png)

![image](https://user-images.githubusercontent.com/89537088/213454075-3571d956-737c-403d-99fb-e40d8ababdb4.png)

## Impact 

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Answer Key,  In-chapter exercise questions   
- **surrounding text:**

**Comment by lwtchu** [comment]
Note: Scheduling for a later spring pending chapter 2 review with John.
