### ISSUE TITLE
College Success Concise - PDF converting issue in CORGI [URGENT]

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4960]
We have faced the below issue when converting to PDF in CORGI, and the PDF was not converted. Kindly check and resolve this issue ASAP.

![corgi error](https://user-images.githubusercontent.com/86622862/213634583-7f1592db-2316-4787-b36b-a7bd6e9ab6ff.png)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-college-success
- **collection slug:** college-success-concise
- **ref/branch:** https://openstax-osbookscollege-nynhu8x6s6z.ws-us83.gitpod.io/
- **chapter/section:** Chapter 3

**Comment by openstaxalina** [comment]
@ne-newton could you & team look into this? Please prioritize as this is blocking the creation of a PDF for print samples (needed for a conference).

**Comment by openstaxalina** [comment]
thank you @lwtchu -- @ne-newton please disregard.

@srm-openstax I've reassigned the issue to you to resolve the content/tagging error and regenerate the PDF. Please close this issue to confirm it's resolved.

**Comment by srm-openstax** [comment]
Thanks for your guidance. Working fine now. PDF converted successfully.
