### ISSUE TITLE
Enable class="unnumbered" on equations 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4961]
# Brief Description of Scenario
I'm trying to hide equation numbering but the unnumbered class doesn't look to be enabled. 

# Acceptance Criteria
numbers on equations do not get generated when the unnumbered class is applied. 
  
# Sample Mark-Up
```
<equation class="unnumbered" id="eq-00001"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mfrac><mrow><mtext>maximum</mtext><mo>-</mo><mtext>minimum</mtext></mrow><mrow><mtext># of bins</mtext></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>4.00</mn><mo>-</mo><mn>1.20</mn></mrow><mn>8</mn></mfrac><mo>=</mo><mn>0.35</mn><mtext>.</mtext></mrow></math></equation>
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-contemporary-math
- **collection slug:** contemporary-math
- **ref/branch:** main
- **chapter/section:** various
- **surrounding text:** equation class="unnumbered"

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-01-24 16-49-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0977bf95-4892-4463-98c5-088e8b9440f7)

![Screenshot from 2023-01-24 16-50-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7daf2978-5f23-43d9-90bf-4f2d52fe6af8)
