### ISSUE TITLE
Organic Chemistry - Error in CORGI [Urgent]

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4962]
# Context
**Processing in CORGI results in error.**
Last successful CORGI job for Org Chem at approximately 12pm.
Edits before running Job in CORGI included creating an Appendix B in POET via TOC editor
Content Push via POET caused error in "organic-chemistry.collection.xml"  -- missing content-id tag
I added <md:content-id>col12345</md:content-id> -- the value is something I made up
This fix to "organic-chemistry.collection.xml" resulted in successful content push
Running CORGI at this point returns Error.
Added "collection-id="col12345"" to <book> in book.xml configuration 
Run CORGI again returns Error.

I see that part of the error involves "enki" directory and I saw in comments on other issue there is a possible problem with enki. 

I ran Validate Content in POET and NO errors detected

[docker-entrypoint.sh:42] die 'ERROR: could not run [/workspace/enki/cookbook/bake -b organic-chemistry -i assembled/organic-chemistry.assembled.xhtml -o baked/organic-chemistry.baked.xhtml]' 112
++ [docker-entrypoint.sh:38] yell 'ERROR: could not run [/workspace/enki/cookbook/bake -b organic-chemistry -i assembled/organic-chemistry.assembled.xhtml -o baked/organic-chemistry.baked.xhtml]'
++ [docker-entrypoint.sh:35] echo -e '/dockerfiles/docker-entrypoint.sh: ERROR: could not run [/workspace/enki/cookbook/bake -b organic-chemistry -i assembled/organic-chemistry.assembled.xhtml -o baked/organic-chemistry.baked.xhtml]'
/dockerfiles/docker-entrypoint.sh: ERROR: could not run [/workspace/enki/cookbook/bake -b organic-chemistry -i assembled/organic-chemistry.assembled.xhtml -o baked/organic-chemistry.baked.xhtml]
++ [docker-entrypoint.sh:39] exit 112

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:**

**Comment by lwtchu** [comment]
Changing `<link>Appendix B</link>` to `<link document="m00030"/>` in two spots and added the `class="appendix" ` to the `<document>` tag. Alerted Mike that both 8828/8829 Corgi jobs have succeeded with these changes.
