### ISSUE TITLE
College Success Concise - Summary section title hidden issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4963]
We have coded the summary section title as per the tagging legend, but wasn't shown in both outputs (PDF and WebView). Kindly check and resolve this issues.

**Input MS:**
![ch3-summary-input](https://user-images.githubusercontent.com/86622862/213869406-f683401f-eef3-411a-ae89-eae9a2fc4629.png)

**Tagging Legend:**
![summary-tagging-legend](https://user-images.githubusercontent.com/86622862/213869463-e9748038-77ee-4e70-846a-914c44f07aea.png)

**PDF View:**
![ch3-summary-output](https://user-images.githubusercontent.com/86622862/213869411-401aa6c9-be68-4c46-b6d0-69f8b20aec62.png)

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-college-success
- **collection slug:** college-success-concise
- **ref/branch:** https://openstax-osbookscollege-nynhu8x6s6z.ws-us83.gitpod.io/
- **chapter/section:**  Chapter 3/Section 4
- **surrounding text:** Reading and note-taking are part of the foundation

**Comment by lwtchu** [comment]
@srm-openstax Hello! I spoke to Anthony about this and we would like to keep the section as is. If there were more specific "next steps" pieces of content, please add a separate paragraph within the summary and denote it with a nested section and title.

**Comment by srm-openstax** [comment]
Noted. Thanks for your guidance.
