### ISSUE TITLE
common refactoring - add/remove elements

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#4966]
- Move `Narrow Table` to `tables` file (Cosmos, used in `economics` and `pl-economics`).
- Move `Punctuation Emphasis` (selector: `span.emphasis-punctuation`) to `common` files (used in `english-composition`).
- Move `Calculator Button` (selectors: `.primary-function`, `.secondary-function`) to `common` files (used in `finance`).

**Comment by MartaSztuka** [comment]
#### PASSED
###### Mikroekonomia
![Screenshot from 2023-01-24 10-45-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/95c0affe-84ef-4265-b413-b020efcc496e)

###### English Composition
![Screenshot from 2023-01-24 10-58-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/17443c19-b85d-4893-b624-fcf5b4fae287)

###### Finance
![Screenshot from 2023-01-24 11-15-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b047a33b-1fad-42bb-b769-aa5af847eae0)
