### ISSUE TITLE
Inconsistent pading on some section lists

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4967]
# Brief Description of Scenario

![Screenshot 2023-01-23 at 9.30.03 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/6f8ac3d2-bde9-4073-93b7-8df880f2d44e)

![Screenshot 2023-01-23 at 9.54.50 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/6ee17bf8-62c5-4c2a-bcd1-eea9dc3df7ca)
In this example, the list under Check Your Understanding looks like it's left even beyond the title. 

# Pattern of Occurrence 
It looks like numbered lists are pushed a bit further to the right than other numbered lists when they follow a para to provide instructions for the next few questions.

# Acceptance Criteria
numbered lists line up nicely 
  
# Sample Mark-Up
n/a, the list is created from multiple questions from a single embedded exercise. In this example, the exercise is: CM-C03-M7-Q015

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-contemporary-math
- **collection slug:** contemporary-math
- **ref/branch:** main
- **chapter/section:** various, this example is from 3.7 Exercises
- **surrounding text:** use clock arithmetic (mod 12)

**Comment by lwtchu** [comment]
This is why design to differentiate multi part and single embedded questions.
