### ISSUE TITLE
organic chemistry - dedication isn't showing up on corgi 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4968]
# Brief Description of Scenario
Original card: https://github.com/openstax/cnx-recipes/issues/4931
![CleanShot 2023-01-17 at 12 04 41](https://user-images.githubusercontent.com/12678235/212977185-bf8c5477-e163-456b-b995-f68766cb9894.png)

A couple of things are off when [generated on CORGI](https://openstax-sandbox-cops-artifacts.s3.amazonaws.com/organic-chemistry-dedication-test-git-5395.pdf), but there may be a number of reasons why. Marking this in the issue for the time being, but since the other elements of the release have gone out OK i'll re-close this for the time being and we can open a new card for continuing work.

1. Not sure if it was intended for the folio to change to match the new title
2. Styling missing on the image caption
3. Section-end stroke missing

# Pattern of Occurrence 
in the preface

# Acceptance Criteria
Please see above
  

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-organic-chemistry/tree/dedication-test 
- **collection slug:** organic-chemistry
- **ref/branch:** dedication-test
- **chapter/section:** preface
- **surrounding text:**

**Comment by wilkus27** [comment]
I've found what's wrong. Style in repo should be set to `organic-chemistry`:

![image](https://user-images.githubusercontent.com/40228854/214536410-a64103be-1102-4546-a308-300399a5b1a4.png)

I tried to change it manually in CORGI and it's working: https://openstax-cops-artifacts.s3.amazonaws.com/organic-chemistry-dedication-test-git-8858.pdf

**Comment by lwtchu** [comment]
@wilkus27 good catch!!! we changed it on main but i forgot dedication-test was created before then. closing!
