### ISSUE TITLE
🅱️🅰️🅿️ BAP - script for big a pipeline

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4969]
# Context
Would love to have a script on enki that can generate all the books at once to check for broken things and to compare content.

## Impact 
It should have a big impact. Jk - it will make it easier for devs to do testing across the entire library

# Acceptance Criteria
- Can use the ABL as a source of truth for all the books that are out and live
- Option to have someone, or people, add books that aren't out but in production onto the list

**Comment by lwtchu** [comment]
Should also help with this card https://github.com/openstax/enki/pull/197

**Comment by lwtchu** [comment]
Kendra ask questions at RT

**Comment by kswanson33** [comment]
from RT:

- [ ] use ruby scripting but dockerize to make dependencies portable
- [ ] log end-of-run report

**Comment by lwtchu** [comment]
Dear Diary,

Today Kendra helped me install this and enki and test ran it. We think it can be launched as is. Larissa to write feature brief for v2 and 3. Need to figure out where to log change requests.

Love u bye,
Larissa

**Comment by lwtchu** [comment]
https://docs.google.com/document/d/18SnX20OMlpmIdgCLL016Fw0NqW8WXLT9HaM0irxxX5M/edit# feature brief

**Comment by kswanson33** [comment]
implemented in [enki/cross-lib](https://github.com/openstax/enki/tree/main/cross-lib). [readme](https://github.com/openstax/enki/blob/main/cross-lib/README.md) contains some user info.

demo available ask kendra

**Comment by Stackblocks** [comment]
Ran steadily for 19 hours until my 2017 Macbook Pro overheated and died / battery drained while plugged in on slow-charge; the output completed up to that point is all cleanly set up in the destination directory and appears to be fully formed. Able to pick back up from where it crashed by adjusting the AUTO_books.txt.
