### ISSUE TITLE
Number positioning on exercise images

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#4970]
# Brief Description of Scenario
Numbering on embedded exercises that begin or only contain an image have the number set at the bottom left corner of the image. This does not follow the style of other numbered elements and can be confusing. 

![Screenshot 2023-01-26 at 9.00.47 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/a28edb30-bc27-4cad-a902-29e788e29417)

# Acceptance Criteria

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-contemporary-math
- **collection slug:** contemporary-math
- **ref/branch:** main
- **chapter/section:** 1.3 Exercises is a good example
- **surrounding text:** For the following exercises, use the Venn diagram to determine the members

**Comment by lwtchu** [comment]
Not going to fix for now....evaluate later since it might be a big departure. Putting in backlog

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-24 17-19-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f61cc1b4-7167-4884-bcf6-6cc0ee8abe25)
