### ISSUE TITLE
organic chemistry - superscript and subscript font sizing change

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4972]
![Screen Shot 2023-01-27 at 12 15 43 PM](https://user-images.githubusercontent.com/11299125/215163370-4edcbc9c-f029-4344-8ba3-565ca3adbadb.png)

# Context
We've gotten a request from the author to bump up the font size for the sub/sup because it's too difficult to read. Is this possible? 

# New specifications or link to documentation cards
Can you give me the current font size and I'll say what it needs to be. 
- currently it is 75%; might impact line height.

## Impact 
- elements tagged as sub/sup might benefit from this change but I'd like to investigate possibility first then gauge impact.
- this will also affect footnotes
- this will affect everything 

# Acceptance Criteria
- please increase the percentage to 85%; which will change the sizing from 6.75pt to 7.5pt (for a 9pt base font...i can help do the math for the smaller base font)

# Testing
- let's test biology and chemistry and statistics and entrepreneurship and psychology and fizyka vol 2 to be safe. please note page count increase if there are any

# Content
## Sample Mark-Up
```
<sup> ... </sup>
<sub> ... </sub>
```
Some are in figure captions and other notes/para.

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-organic-chemistry/tree/main
- **collection slug:** organic-chemistry
- **ref/branch:** main
- **ce-styles branch:** subscript-size
- **chapter/section:** everywhere all at once
- **surrounding text:**

**Comment by Stackblocks** [comment]
## Status
The change is displaying in the content at a base level so i'll generate the test content and share it out for regression and special-case testing.

## Subscript
![CleanShot 2023-02-02 at 15.04.29.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/2c4e2ea4-2dcf-4213-8ca8-292efff80e68)
---
![CleanShot 2023-02-02 at 15.03.47.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/9667e35e-44d7-4abc-abdb-dee72cba933a)

## Superscript
![CleanShot 2023-02-02 at 15.08.26.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/11d8ccb0-da29-48ff-9dc7-b6d1d5986ee1)
---
![CleanShot 2023-02-02 at 15.09.06.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ff9b586c-d7dd-46bd-8c5d-45c6de0bba65)

**Comment by lwtchu** [comment]
Biology - no page count change
Statistics went from 861 to 887. 
Eship - no change
Psychology - no change
Fizyka - page count went from 772 to 768 (???) 
Chemistry - waiting

**Comment by lwtchu** [comment]
Confirmed with Alina that this is an acceptable risk that we are willing to take. Please go ahead and merge the changes!! @LostMojo 🎉
