### ISSUE TITLE
organic chemistry - move table titles, number, caption to the top

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4973]
![Screen Shot 2023-01-27 at 3 36 35 PM](https://user-images.githubusercontent.com/11299125/215205371-a132756c-9d0e-471a-bfa0-299dfe40292f.png)

# Brief Description of Scenario
Change request to move the table number, caption and title to the top of the table so that it is more in alignment with the 9e.

# Pattern of Occurrence 
All tables with a title, and number. Please move the whole chunk to above the table. I do not believe the tables in this title has a caption, so it'll just be the title and number visible.

# Acceptance Criteria
![Screen Shot 2023-01-27 at 3 37 53 PM](https://user-images.githubusercontent.com/11299125/215205474-f672f211-63ce-459c-9ab8-4f9907736bbb.png)

- title moved to the top, left align to the table

  
# Sample Mark-Up
```
<table id="OChem_01_03_001" summary="Ground-State Electron Configurations of Some Elements">
      <title>Ground-State Electron Configurations of Some Elements</title>
      <tgroup cols="7">
        <thead>
          <row>
            <entry>Element</entry>
            <entry>Atomic number</entry>
            <entry>Configuration</entry>
            <entry>Element</entry>
            <entry>Atomic number</entry>
            <entry>Configuration</entry>
          </row>
        </thead>
        <tbody>
          <row>
            <entry>Hydrogen</entry>
            <entry>1</entry>
            <entry><media alt="MISSING"><image mime-type="image/jpg" src="../../media/OChem_01_03_001a.jpg"/></media></entry>
            <entry>Phosphorus</entry>
            <entry>15</entry>
            <entry><media alt="MISSING"><image mime-type="image/jpg" src="../../media/OChem_01_03_001c.jpg"/></media></entry>
          </row>
          <row>
            <entry>Carbon</entry>
            <entry>6</entry>
            <entry><media alt="MISSING"><image mime-type="image/jpg" src="../../media/OChem_01_03_001b.jpg"/></media></entry>
            <entry/>
            <entry/>
            <entry/>
          </row>
        </tbody>
      </tgroup>
    </table>
```

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:** main
- **chapter/section:**  1.3 Atomic Structure: Electron Configurations
- **surrounding text:** Ground-State Electron Configurations of Some Elements

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-02-03 13-19-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cb4d883c-5c60-43e3-ac8b-74b59bd44cce)
