### ISSUE TITLE
organic chemistry - bold distractors for embedded exercises

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4974]
![Screen Shot 2023-01-27 at 3 49 30 PM](https://user-images.githubusercontent.com/11299125/215207692-f504407c-3231-44ce-86d3-c41efe4d4c40.png)
Top = before; bottom = ideally, after

# Brief Description of Scenario
Please bold the distractors for embedded exercises.

# Pattern of Occurrence 

# Acceptance Criteria
The distractors = (a) (b) (c) (d) etc are all bolded. No other change.
  
# Sample Mark-Up
```
<exercise id="exer-00001">
        <problem id="prob-00001">
          <para id="para-00006"><link class="os-embed" url="#exercise/OrgChem_C01_Q001"/>
          </para>
        </problem>
      </exercise>
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:** main
- **chapter/section:** end of each section 
- **surrounding text:** (a) or look for the word Problems

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2023-02-01 at 13.17.40.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5ca83f52-7472-4f8e-9ce0-913f63ba2fbd)
