### ISSUE TITLE
nursing-external - generic things to pull in for carnival theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4976]
documentation: #4736

color: `#00819A`

**Comment by MartaSztuka** [comment]
1. Bullets are sticking in all 3 books
2. Some headers are not styled

##### NUTRITION
![Screenshot from 2023-03-06 12-43-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1b615bb4-e6e0-4462-b555-275adbd925e9)

##### PHARMACOLOGY
![Screenshot from 2023-03-06 12-46-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/acf808e4-727f-418c-aa88-fa0a4aacafe4)

##### COMMUNITY POPULATION HEALTH
![Screenshot from 2023-03-06 12-53-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c5cc9dc7-8fa6-43d3-88d3-64394499d34c)

**Comment by lwtchu** [comment]
@jbwilson8 if you are able, can we boop the lists back into the margins
