### ISSUE TITLE
organic chemistry - add styling to newly added EOC sections

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4977]
# Brief Description of Scenario
The sections exist, but it looks like number styling isn't properly configured.

![CleanShot 2023-01-26 at 16.10.44.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/150df3bb-d701-4ea9-965d-4873235d6161)

![CleanShot 2023-01-26 at 16.14.00.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/83d619d9-04c0-47bd-8ec2-37a3d8461355)

_Originally posted by @Stackblocks in https://github.com/openstax/cnx-recipes/issues/4943#issuecomment-1405743232_
            

# Pattern of Occurrence 
In the newly added sections 
Mechanism Problems `mechanism-problems`
General Problems `general-problems`
Energy Diagrams and Reaction Mechanisms `energy-reaction`

# Acceptance Criteria
- styling for EOC embedded exercises is applied
- `exercise-block` class is also enabled for them
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:** larissa-test 
- **chapter/section:**  Noncovalent Interactions between Molecules 
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-02-02 16-02-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bfd02a89-32ee-4043-b91b-5a1c853435c2)
