### ISSUE TITLE
nursing-external - toc table of contents

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4978]
Documentation: #4730 
DOES contain Units

**Comment by MartaSztuka** [comment]
#### PASSED

##### NUTRITION
![Screenshot from 2023-03-06 12-29-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/298e185b-5533-4811-8a39-dbf90d62bf75)

##### PHARMACOLOGY
![Screenshot from 2023-03-06 12-29-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/507fbdb6-d393-4cc5-93e5-f7ebae87fa80)

##### COMMUNITY POPULATION HEALTH
![Screenshot from 2023-03-06 12-30-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3c1ba67a-95e4-49c1-90a2-fcde051ce944)
