### ISSUE TITLE
nursing-external - figure and table captions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4980]
documentation: #1081

**Comment by MartaSztuka** [comment]
#### PASSED

##### NUTRITION
![Screenshot from 2023-03-06 12-14-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f0e2bcdb-284b-4986-a561-04143cd8ec3d)![Screenshot from 2023-03-06 12-15-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/42a2c66b-4e30-4d5a-8de2-c00831bfd9cf)

##### PHARMACOLOGY
![Screenshot from 2023-03-06 12-16-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/88a388e3-d683-4f1f-92f8-1059facb2371)![Screenshot from 2023-03-06 12-16-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/533939fd-01b5-4d6c-a5bf-dfea24eebec7)

##### COMMUNITY POPULATION
![Screenshot from 2023-03-06 12-17-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/619a95e6-9bf1-4f3a-9549-f70c11d9c36e)
