### ISSUE TITLE
nursing-external - learning outcomes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4983]
documentation #1077
title: Learning Outcomes
please use the numbering schema but can we do #.#.# like in some of the math books (calculus)?

For example section 4.1 will have LO 4.1.1, 4.1.2, etc

**Comment by MartaSztuka** [comment]
#### PASSED
##### PHARMACOLOGY
![Screenshot from 2023-03-21 12-52-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0f4bcf6f-22fa-4230-8e7c-1c31d9e91ed7)

##### NUTRITION
![Screenshot from 2023-03-21 12-53-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7673e375-d78e-4dfb-ab4d-5fba0e5358bb)

##### COMMUNITY POPULATION
![Screenshot from 2023-03-21 12-55-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/584e1e84-de68-4c3a-b0f4-7d04db7b2040)
