### ISSUE TITLE
nursing-external - generic tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4984]
Documentation #1080
Table bottom line: B2: `#0074BC`

**Comment by MartaSztuka** [comment]
##### COMMUNITY POPULATION
There is only one table and it's missing caption
![Screenshot from 2023-03-06 12-01-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/edabf584-19e3-45a3-9ea8-a924abe2aa0c)

#### PASSED

##### NUTRITION
![Screenshot from 2023-03-06 11-56-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bb797afb-18eb-4dbc-be5c-5f2faa783ef3)

##### PHARMACOLOGY
![Screenshot from 2023-03-06 11-57-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/873fabba-57b1-45ef-86ae-680cca696818)
