### ISSUE TITLE
World History - Exercises - Student Drawing on Image for Answer?

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4985]
# Context
In Exercises, does the platform support students drawing on a supplied image to indicate the answer to a question?
If "no", then is it possible to have images as answer choices and have students label each one A, B, etc.
See screenshot:
![image](https://user-images.githubusercontent.com/89537088/216380374-d190e0f0-991c-4461-91d7-9bba78aa9ad9.png)

# New specifications or link to documentation cards

## Impact 

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-world-history
- **collection slug:**
- **ref/branch:**
- **chapter/section:** Exercises
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax We currently do not have a way to have students submit images. It's either the multiple-choice options or open-ended answers. I would go with the labeled image for the question and maybe set it as an open-ended question.

**Comment by ww-openstax** [comment]
WW followed suggestion
