### ISSUE TITLE
Contemporary Math: Unnumbered Tables with Captions/Credits - Caption Appears Above Table

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#4989]
# Context
Contemporary Math uses data from external sources in some tables. Per OpenStax guidelines, we need to credit the original data source. We also asked them to make tables unnumbered when possible since there are a ton of tables in this book. When an unnumbered table has a caption/credit, it's appearing _above_ the table:

<img width="504" alt="Screenshot 2023-02-01 at 6 16 01 PM" src="https://user-images.githubusercontent.com/7863733/216455242-26b22e1a-1664-4119-934f-344f34b2bed2.png">
<img width="500" alt="Screenshot 2023-02-01 at 6 16 10 PM" src="https://user-images.githubusercontent.com/7863733/216455244-319e963c-f64c-439a-8d7f-08f5ff114e50.png">

Note: both of these examples happen to be in exercises. I think that's the only content with unnumbered, credited tables.

# New specifications or link to documentation cards
Larissa will determine priority and exact change, but the general request is for the captions to be moved _under_ the table.

## Impact 
We only specifically saw this issue in Contemporary Math, but if other books have unnumbered tables with captions, they should probably also be included and tested.

# Acceptance Criteria
- please move caption below table and make it consistent with the other default table caption placement 

# Content
## Sample Mark-Up
```
<table class="unnumbered">
<caption>(source: https://data.ed.gov)</caption>
<thead>
<tr><th>Campus</th>
<th>Admission Rate</th>
<th>Cost ($)</th></tr>
</thead>
<tbody>
<tr><td>Berkeley</td>
<td>0.1484</td>
<td>43,176</td></tr>
<tr><td>Davis</td>
<td>0.4107</td>
<td>43,394</td></tr>
<tr><td>Irvine</td>
<td>0.2876</td>
<td>42,692</td></tr>
<tr><td>Los Angeles</td>
<td>0.1404</td>
<td>42,218</td></tr>
<tr><td>Merced</td>
<td>0.6617</td>
<td>42,530</td></tr>
<tr><td>Riverside</td>
<td>0.5057</td>
<td>42,819</td></tr>
<tr><td>San Diego</td>
<td>0.3006</td>
<td>43,159</td></tr>
<tr><td>Santa Barbara</td>
<td>0.322</td>
<td>43,383</td></tr>
<tr><td>Santa Cruz</td>
<td>0.4737</td>
<td>42,952</td>
</tr>
</tbody>
</table>
```

## Location(s)
- **osbooks repo:** osbooks-contemporary-mathematics
- **collection slug:** contemporary-mathematics
- **ref/branch:** main
- **chapter/section:** 8.2 Visualizing Data 
- **surrounding text:** "The following are data on the admission rates of the different branch campuses in the University of California system, along with the out-of-state tuition and fee cost:" [note: this is in Exercises]

**Comment by Stackblocks** [comment]
Titles are showing under the table now.

_Side note: the tables in the book are pretty well crammed up on the preceding line but that may be a necessity for space saving or have some other reason. Noting because it looks awkward._

![CleanShot 2023-02-15 at 14.30.10.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/17681d12-5060-4a7a-a10b-a95b9014e0b9)
---
![CleanShot 2023-02-15 at 14.29.01.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/22a00a7b-0f8b-41f2-a45a-304fcfa8f192)
