### ISSUE TITLE
nursing-external - healthy people 2030 feature (nutrition and population health only)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4990]
#3966

class: `healthy-people`
title: Healthy People 2030
color: B2: `#0074BC`
no subtitle, contains text/links
icon: [cosmos-group.svg](https://drive.google.com/file/d/1FpP7B3T_RpgtH5T0tMgfWTwKKdQwSuk-/view?usp=sharing)

**Comment by MartaSztuka** [comment]
#### PASSED
##### COMMUNITY POPULATION ![Screenshot from 2023-03-21 12-37-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b1cbea9d-9729-4039-9f69-e92563fb1c48)

##### NUTRITION
![Screenshot from 2023-03-21 12-39-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/adabb5d7-7e2d-4af5-a91e-4ae608180f88)
