### ISSUE TITLE
nursing-external - client teaching guidelines feature (nutrition and pharmacology only)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4991]
Documentation #4746

Class: `client-teaching`
Title: Client Teaching Guidelines
Subtitle: Yes
Contains a lot of text and lists - need to check spacing 
Color: P2: `#651C72`

**Comment by MartaSztuka** [comment]
#### PASSED
##### NUTRITION
![Screenshot from 2023-03-21 10-53-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/40d2ab4a-a278-4d08-9ef8-ef71df19cacd)

##### PHARMACOLOGY
![Screenshot from 2023-03-21 10-53-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bcb947e9-1adf-48e6-af51-e525d822d4c3)
