### ISSUE TITLE
nursing-external - trending today (nutrition and pharmacology only)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4993]
class: `trending-today`
documentation #3966
title: Trending Today
has a subtitle; 
icon: [carnival-newspaper.svg](https://drive.google.com/file/d/1AqMNIuS9DLNaBdKPrq_XcfKuFPyw8If-/view?usp=share_link)
color: R2: `#B10069`
mostly text and some links. maybe open-ended questions

**Comment by MartaSztuka** [comment]
#### PASSED
##### NUTRITION
![Screenshot from 2023-03-21 12-00-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/833695bb-b603-469a-adee-4516ba066b1e)

##### PHARMACOLOGY
![Screenshot from 2023-03-21 12-02-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9c3ea4fe-8b9c-445d-91c3-d67f3e6bc459)
