### ISSUE TITLE
nursing-external - safety alert feature (pharmacology and nutrition only)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4994]
- class: `safety-alert`
- uses #3235
- title: Safety Alert
- has a subtitle 
- icon: [carnival-alert.svg](https://drive.google.com/file/d/1S-qYNSVCSNhKBocvyjcQoPCZac3uRVj4/view?usp=share_link)
- color: R1: `#C31427`

**Comment by MartaSztuka** [comment]
#### PASSED
##### PHARMACOLOGY
![Screenshot from 2023-03-21 12-49-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/679fcb69-6011-4dbc-a9a9-df76b7c8a013)
##### NUTRITION
![Screenshot from 2023-03-21 12-47-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c8acb566-226f-49ed-80e9-014c561d6414)
