### ISSUE TITLE
nursing-external - clinical tip (nutrition and pharmacology only)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4995]
- class: `clinical-tip`
- uses #3235
- title: Clinical Tip
- has a subtitle 
- icon: [carnival-scientific.svg](https://drive.google.com/file/d/1OkkZLvn5qH3lsGbbyjZ2NHBzE5vcHgeu/view?usp=share_link) **NOTE** can we resize this with the CSS? if not, let me know and i can make it smaller. trying to recycle and reuse ♻️ 
- color: B1:`#0DC0DC`

**Comment by MartaSztuka** [comment]
#### PASSED
##### PHARMACOLOGY
![Screenshot from 2023-03-21 13-24-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7451daff-cccd-4462-89bd-4ed18fc132e7)

##### NUTRITION
![Screenshot from 2023-03-21 13-26-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6b5103b4-c61f-42fb-9f3b-d9f952ebf5b5)
