### ISSUE TITLE
nursing-external - practice problems feature (pharmacology only)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4997]
Documentation #4746

Class: `practice-problems`
Title: Practice Problems
Subtitle: No
Contains a list and some text
Color: O2: `#CE472C`

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `fiscal.fontology` & content from `design-chapters`

![CleanShot 2023-03-20 at 16.16.33.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7b1c996d-39d4-455d-94b8-008d48683f54)
