### ISSUE TITLE
nursing-external - the roots of health inequities feature (pop health only)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4998]
- class: `health-alert`
- uses #3235
- title: The Roots of Health Inequities
- has a subtitle 
- icon: [carnival-check.svg](https://drive.google.com/file/d/101zf9gMdbH6vfg_jTb3zJhqTa7O0uvyR/view?usp=share_link)
- color: O1: `#F37541`

**Comment by MartaSztuka** [comment]
#### PASSED
##### COMMUNITY POPULATION
![Screenshot from 2023-03-21 12-40-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6cee01e1-8f45-46a7-bba7-0637b97d71c4)
