### ISSUE TITLE
nursing-external - media feature (nutrition only)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4999]
class: `media-feature`
documentation #3966
title: can this be pulled in by `<title>`
icon: [cosmos-media.svg](https://drive.google.com/drive/u/0/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2)
color: G2:` #1E9575`
mostly text and some links. maybe open ended questions

**Comment by MartaSztuka** [comment]
#### PASSED
##### NUTRITION
![Screenshot from 2023-03-21 12-25-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3a8e0f67-5f7e-441c-b43f-c2ceff9cf4ee)

![Screenshot from 2023-03-21 12-27-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e6021076-10fd-4930-8b28-de8756d3c5f2)
