### ISSUE TITLE
nursing-external - various case studies

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5000]
All of these will use this styling but with various titles and content within the feature
documentation #3966

They may or may not have subtitles.

Title of feature and class. 
- [ ] Unfolding Case Study `unfolding-casestudy`
This will have embedded exercises. Please have them number through the chapter and reset with every chapter. Answers will go into the answer key. 
color: R1: `#C31427`
icon: [carnival-example.svg](https://drive.google.com/file/d/16IZ-M4-fsrDr4iPwHCEm1AEPrdQIsjd9/view?usp=share_link)
subtitle: yes

- [ ] Case Study `single-casestudy` (nutrition only)
This will have embedded exercises. Please have them number through the chapter and reset with every chapter. Answers will go into the answer key. 
icon2: [carnival-exampleblue.svg](https://drive.google.com/file/d/1Zj_iTq6XApkFWK1vd5NMkvJJ5vlJ8lL3/view?usp=share_link)
color: B2: `#0074BC`
subtitle: yes

- [ ] Case Reflection `case-reflection` (pop health only)
 icon2: [carnival-exampleblue.svg](https://drive.google.com/file/d/1Zj_iTq6XApkFWK1vd5NMkvJJ5vlJ8lL3/view?usp=share_link)
color: B2: `#0074BC`
subtitle: no

**Comment by MartaSztuka** [comment]
#### PASSED
@lwtchu Case Reflection icon is a bit crooked and seems to be in two different shades of blue. 
![Screenshot from 2023-03-21 16-21-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/459ab713-3c22-47d6-b085-3e978cfd5cbe)
##### PHARMACOLOGY
![Screenshot from 2023-03-21 16-11-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9a60a38a-e555-4746-b41b-e570395208b5)

##### NUTRITION
![Screenshot from 2023-03-21 16-16-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8ba3de79-bc3c-4669-b3a3-46d8ec22a6fd)

##### COMMUNITY POPULATION
![Screenshot from 2023-03-21 16-17-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ae7d1721-f49c-4ab4-b838-c710e44f422b)

**Comment by lwtchu** [comment]
added the icon fix in this issue https://github.com/openstax/cnx-recipes/issues/5049
