### ISSUE TITLE
contemporary mathematics - splash image white bar

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5001]
# Brief Description of Scenario
![Screen Shot 2023-02-06 at 4 27 22 PM](https://user-images.githubusercontent.com/11299125/217101728-9e628df8-be3f-4e0d-a94e-5066186dafe5.png)
This white bar should not be there.

# Pattern of Occurrence 
It's on every splash image

# Acceptance Criteria
It should look like the example in here with no white bar at the top #1752
  
# Sample Mark-Up
```
    <figure id="fig-00001" class="splash">
      <media alt="A drawer with three types of silveware in a wooden case.">
      <image mime-type="image/png" src="../../media/CS_Photo_01_00_001.jpg"/>
      </media>
      <caption>A flatware drawer is like a set in that it contains distinct objects. (credit: modification of work “silverware” by Jo Naylor/Flickr, CC BY 2.0)</caption>
      </figure>
```

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-contemporary-mathematics
- **collection slug:** contemporary-mathematics
- **ref/branch:** main
- **chapter/section:**  all chapter openers
- **surrounding text:**

**Comment by lwtchu** [comment]
@wilkus27 yes i'm reviewing the splash images today in this title and fixing anything that looks weird.

**Comment by wilkus27** [comment]
My changes are not merged yet, I'm going to move them to code review. Please use my branch `corn-splash-figure` if my fix don't be merged before you start working on it.

**Comment by wilkus27** [comment]
### Information for tester

It has an impact on all books from Corn theme.

Most of the images should display ok, but there might be a problem with some of them.

@lwtchu Should tester make a list of them during testing?

**Comment by lwtchu** [comment]
Note: this might be due to some images not exported at the right size. When this goes to Prod, larissa to test a few with the right image dimensions.
