### ISSUE TITLE
nursing-external - end of chapter

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5003]
If there is no content, please make sure it doesn't auto-populate a header. If you need content - please contact Larissa or Cayla.

# Key Terms
- uses `<glossary>`
- documentation #4752
- set to two column

# Summary
There are two versions. One that requires NO section headers and one that does.

Title (for both): Chapter Summary

## No Section Header Summary
- `class="chapter-summary"`
- documentation #4753
- divided by sections/module? NO
- set to two column
- may contain a list or paragraph

## Section Header Summary
- `class="section-summary"`
- documentation #4753
- divided by sections/module?  YES
- set to two column
- may contain paragraphs

# Review Questions
- `class="review-questions"`
- multiple choice lists in exercises should not have a double line break between question and choices
list follows standard list indentation
- two column
- numbering starts at 1 and resets every chapter
- divided by sections/module? NO
- answer goes to the answer key with the detailed solution

# Suggested Readings
- `class="suggested-reading"`
- mostly text
- divided by sections/module? NO
- set to 1 column
- not present in every section

**Comment by MartaSztuka** [comment]
@lwtchu there are several problems in end of chapter: 
###### 1. Headers are black not blue
###### 2. Chapter Summary is set in one column in Nutrition and Pharmacology
###### 3. Double header in Pharmacology
###### 4. Review Questions are in one column in all 3 books
##### Key terms
###### PHARMACOLOGY
![Screenshot from 2023-03-21 15-13-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/94157894-8f0e-4f96-b8fb-10662111e4f3)
###### NUTRITION
![Screenshot from 2023-03-21 15-15-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/02767718-ca6c-45a3-915f-30535f1778b6)
###### COMMUNITY POPULATION
![Screenshot from 2023-03-21 15-16-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/efb69f09-693d-4b8c-8866-69b61cfc519a)

##### Summary
###### PHARMACOLOGY
![Screenshot from 2023-03-21 15-17-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/549f2159-9a98-4aa1-9ccf-f1ea91505bac)
###### NUTRITION
![Screenshot from 2023-03-21 15-19-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a31cd704-6a00-4d78-b62f-c42c6f61e7ab)
###### COMMUNITY POPULATION
![Screenshot from 2023-03-21 15-19-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/05cdbb91-e678-4ac2-afe0-f053a2a36e3d)


##### Review Questions
###### PHARMACOLOGY
![Screenshot from 2023-03-21 15-22-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3f79d35b-74fd-4f85-b33e-d5fda0194244)
###### NUTRITION
![Screenshot from 2023-03-21 15-22-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/87e672d8-5736-46b0-b17a-145d32fa65f1)
###### COMMUNITY POPULATION
![Screenshot from 2023-03-21 15-24-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2a5f3793-4518-4e23-9fb8-edb4c12819ca)

##### Suggested Reading
###### NUTRITION
![Screenshot from 2023-03-21 15-39-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f7b398bd-c709-4ed5-950d-3775eaa949f5)

**Comment by MartaSztuka** [comment]
@lwtchu there are several problems in end of chapter: 
###### 1. Headers are black not blue
###### 2. Chapter Summary is set in one column in Nutrition and Pharmacology
###### 3. Double header in Pharmacology
###### 4. Review Questions are in one column in all 3 books
##### Key terms
###### PHARMACOLOGY
![Screenshot from 2023-03-21 15-13-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/94157894-8f0e-4f96-b8fb-10662111e4f3)
###### NUTRITION
![Screenshot from 2023-03-21 15-15-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/02767718-ca6c-45a3-915f-30535f1778b6)
###### COMMUNITY POPULATION
![Screenshot from 2023-03-21 15-16-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/efb69f09-693d-4b8c-8866-69b61cfc519a)

##### Summary
###### PHARMACOLOGY
![Screenshot from 2023-03-21 15-17-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/549f2159-9a98-4aa1-9ccf-f1ea91505bac)
###### NUTRITION
![Screenshot from 2023-03-21 15-19-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a31cd704-6a00-4d78-b62f-c42c6f61e7ab)
###### COMMUNITY POPULATION
![Screenshot from 2023-03-21 15-19-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/05cdbb91-e678-4ac2-afe0-f053a2a36e3d)


##### Review Questions
###### PHARMACOLOGY
![Screenshot from 2023-03-21 15-22-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3f79d35b-74fd-4f85-b33e-d5fda0194244)
###### NUTRITION
![Screenshot from 2023-03-21 15-22-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/87e672d8-5736-46b0-b17a-145d32fa65f1)
###### COMMUNITY POPULATION
![Screenshot from 2023-03-21 15-24-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2a5f3793-4518-4e23-9fb8-edb4c12819ca)

##### Suggested Reading
###### NUTRITION
![Screenshot from 2023-03-21 15-39-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f7b398bd-c709-4ed5-950d-3775eaa949f5)
