### ISSUE TITLE
nursing-external - index

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5005]
#4755 - please add indentation for 2+ line (hanging indent)

**Comment by MartaSztuka** [comment]
#### PASSED


##### NUTRITION

![Screenshot from 2023-03-06 11-51-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/011207cf-f29b-4443-9b6a-9ee892953684)

##### PHARMACOLOGY
![Screenshot from 2023-03-06 11-48-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4e568109-2b5f-4af5-9b5c-c31e49f65b40)

##### COMMUNITY POPULATION
![Screenshot from 2023-03-06 11-50-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/eeca34de-01db-4e23-add1-bd8c5e72043f)
