### ISSUE TITLE
nursing-external - blue text

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5006]
Please leave the text style and size the same.

`<span class="blue-text">` = B2: `#0074BC`

**Comment by Stackblocks** [comment]
Blue text not displaying with content from `design-chapters` and current code from `f.f.`

![CleanShot 2023-03-21 at 09.24.22.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/fbc180d8-e98d-46ed-8b61-9ab55efc482a)

![CleanShot 2023-03-21 at 09.25.15.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e9903618-d853-483d-a5d1-9111bb12c95b)
