### ISSUE TITLE
nutrition-external - alternating table (nutrition only)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5008]
![Screen Shot 2023-02-07 at 4 07 07 PM](https://user-images.githubusercontent.com/11299125/217384848-cb75550e-5612-42dd-bc0a-70c0304cbfee.png)

`class="alternate-shading"`
Styling should still follow generic tables: 
Documentation #1080
Table bottom line: B2: `#0074BC` 
Only difference is that there is alternating shading starting at the second row of each `<tbody>` and uses B6: `#EFF3FA`

**Comment by MartaSztuka** [comment]
#### PASSED
##### NUTRITION
![Screenshot from 2023-03-21 11-49-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ae7d6f42-aef4-40bc-b60c-d1c3c8c98aab)
