### ISSUE TITLE
ppml2svg to MathJax and/or assistance with the BakedPDF pipeline

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#501]
@brittweinstein commented on [Thu Jul 26 2018](https://github.com/Connexions/content-managers/issues/167)

Related: https://trello.com/c/duyOneP6/359-make-a-mathml-problem-test-module

Helene sent Aiwenar the results of moving from ppml2svg --> mathjax in the recipes for stats (because it has some math and has recipe). This is the first step in figuring out how to remove ppml2svg from the pipeline. The goal is to move to BakedPDF and to not use ppml in the BakedPDF.

**Comment by openstaxalina** [comment]
This card is old and the work is no longer relevant.  Closing.
