### ISSUE TITLE
Organic Chemistry - "no class" Feature Box

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5012]
# Context
We have encountered a new "Box" in Chapter 07 of 9e. We are not sure if this is a one-off or recurring. Can you confirm that the tagging needed for these types of boxes is the tagging in Row 36 of the tagging legend? And can you confirm that the output for these "no class" feature boxes should be like in the screenshot below?
Thanks 

![image](https://user-images.githubusercontent.com/89537088/217605566-d5fc23c2-ecab-4550-b086-93642c8d3346.png)

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<note id="test-ch07-featbox">
  <title>TESTING: Writing Organic Reactions</title>
  <para id="test-ch07-featbox-01">TESTING This is a good time to mention that organic-reaction equations are sometimes written in different ways to emphasize different points. In describing a laboratory process, for instance, the reaction of 2-methylpropene with HCl might be written in the format A 1 B n C to emphasize that both reactants are equally important for the purposes of the discussion. The solvent and notes about other reaction conditions such as temperature are written either above or below the reaction arrow.</para>
  <figure class="unnumbered" id="test-ch07-featbox-fig-00001"><media alt="Placeholder">
    <image mime-type="image/jpeg" src="../../media/OChem_01_12_009.jpg"/>
  </media></figure>
  <para id="test-ch07-featbox-02">TESTING Alternatively, we might write the same reaction in a format to emphasize that 2-methylpropene is the reactant whose chemistry is of greater interest. The second reactant, HCl, is placed above the reaction arrow together with notes about solvent and reaction conditions.</para>
</note>
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:** 
- **chapter/section:** Module m00014 line 176
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax confirmed. please us this tagging for the single titled feature boxes that are with the green banner throughout the 9e
