### ISSUE TITLE
organic chemistry - glossary appendix

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5013]
Similar to #1339

These are lists within a section that has the class `column-container`. 

- The lists should not have bullets or anything. 
- The base font should be smaller: font-scale(-1) 
- This feature is usually in 3 column - could we make is 2 for this title. If it's a global change, we can keep it at 3. And text should go from top to bottom, then left to right.
- The section titles should function as intended within the scale/header documentation.

Content: https://github.com/openstax/osbooks-organic-chemistry/tree/larissa-test 
Please use the larissa-test branch! Search for "glossary"

**Comment by Stackblocks** [comment]
Displays OK with current code & content from `larissa-test`

![CleanShot 2023-02-15 at 16.49.59.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/85edd3df-65f4-4b70-abde-209d2c251390)
