### ISSUE TITLE
nursing-external - references

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5014]
- `class="references"`
- similar to #3244 - Unnumbered references (Economics/Psychology) - goes to the end of the book
- not numbered
- paragraphs with hanging indent
- divided by chapter? YES
- set to 1 column

**Comment by MartaSztuka** [comment]
Hi, @lwtchu :) 
I couldn't test the books, there is a problem with figure fig_02_05_006.png.
![Screenshot from 2023-03-17 10-18-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0e41ec49-9744-4e24-afa4-dd123dc0ab18)

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `fiscal.fontology` & content from `design-chapters`

![CleanShot 2023-03-20 at 14.50.30.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/acc87a37-8e79-4d18-b049-6d37f3d0e0b7)
