### ISSUE TITLE
Organic Chemistry - Add class=scaled-down for <image> in tables?

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5015]
# Context
From the "OrgChem Jan 2023 Items and Decisions Query List Table"
Please add class=scaled-down and class=scaled-down-30 to `<image>` tag in order to support webview scaling down of images inside tables.
**BUT**
Maybe we don't need to add this class to `<image>`. The vendor has tagged the images in the table as unnumbered figures with`<figure class="unnumbered scaled-down" id="fig-00029">` with output in screenshot below. So maybe this is the solution?
This is different from how OSX tagged images in tables in Sample Chapter 01. Also using unnumbered figure means image will be centered in cell. 

See tagging below in Sample Mark-up

![image](https://user-images.githubusercontent.com/89537088/218343020-9009b4d3-f69a-4591-8b01-8b5c717f4fab.png)

# Acceptance Criteria
- [ ] `scaled-down` and `scaled-down-30` has the same effect on `<image>`s as it does on `<figure>`s

# Content
## Sample Mark-Up
```
<row>
    <entry valign="top" align="left">Amide</entry>
    <entry valign="top" align="left"><figure class="unnumbered scaled-down" id="fig-00029">
    <media alt="Alt Text Placeholder">
    <image mime-type="image/jpeg" src="../../media/OChem_03_01_003u.jpg"/>
    </media>
    </figure>
    </entry>
    <entry valign="top" align="left"><emphasis effect="italics">-amide</emphasis></entry>
    <entry valign="top" align="left"><figure class="unnumbered scaled-down" id="fig-00030">
    <media alt="Alt Text Placeholder">
    <image mime-type="image/jpeg" src="../../media/OChem_03_01_003ac.jpg"/>
    </media>
    </figure>
    </entry>
    </row>
    <row>
    <entry valign="top" align="left">Acid chloride</entry>
    <entry valign="top" align="left"><figure class="unnumbered scaled-down" id="fig-00031">
    <media alt="Alt Text Placeholder">
    <image mime-type="image/jpeg" src="../../media/OChem_03_01_003v.jpg"/>
    </media>
    </figure>
    </entry>
    <entry valign="top" align="left"><emphasis effect="italics">-oyl chloride</emphasis></entry>
    <entry valign="top" align="left"><figure class="unnumbered scaled-down" id="fig-00032">
    <media alt="Alt Text Placeholder">
    <image mime-type="image/jpeg" src="../../media/OChem_03_01_003ad.jpg"/>
    </media>
    </figure>
    </entry>
    </row>
    <row>
    <entry valign="top" align="left">Carboxylic acid anhydride</entry>
    <entry valign="top" align="left"><figure class="unnumbered scaled-down" id="fig-00033">
    <media alt="Alt Text Placeholder">
    <image mime-type="image/jpeg" src="../../media/OChem_03_01_003w.jpg"/>
    </media>
    </figure>
    </entry>
    <entry valign="top" align="left">-<emphasis effect="italics">oic anhydride</emphasis></entry>
    <entry valign="top" align="left"><figure class="unnumbered scaled-down" id="fig-00034">
    <media alt="Alt Text Placeholder">
    <image mime-type="image/jpeg" src="../../media/OChem_03_01_003ae.jpg"/>
    </media>
    </figure></entry>
    </row>
    </tbody>
    </tgroup>
    </table>
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:** larissa-test
- **chapter/section:** Screenshot is from Module m00032 Row 292
- **surrounding text:** 

Note from larissa for tester: here's the places where i added the tags https://github.com/openstax/osbooks-organic-chemistry/commit/bf98221d730eec203093586a4934e62f48e1aec7

**Comment by lwtchu** [comment]
@ww-openstax I'd still opt for it to be in an image tag. Figure tagging will center the image to the space that they're in. It might look fine in the table, but if it were in a list, it would move the image to the center and the list item labels would be left aligned. Would you mind editing the content so we'll have something to test for enabling?

**Comment by ww-openstax** [comment]
@lwtchu We will follow your suggestion to tag with `<image>` in tables. We will not use `<figure>`.  We have edited the XML in the table in Module m00032 to remove the `<figure>` tag.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-03-08 10-08-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/989f63fa-a539-4c43-851e-400a5808926b)

![Screenshot from 2023-03-08 10-06-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4ce1da2b-660d-4890-80a3-220fe9f01c82)

**Comment by lwtchu** [comment]
@MartaSztuka :eyes: could you check webview this card is for webview styles

**Comment by Stackblocks** [comment]
Looks good in WebView

![CleanShot 2023-03-08 at 12.00.41.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/65061084-9a54-48aa-b4ae-f21cc4db04e6)
---
![CleanShot 2023-03-08 at 12.01.09.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/bc2c8ddb-52df-456b-88e6-cad5e935015f)
---
![CleanShot 2023-03-08 at 12.01.40.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b25d3e6a-ea55-434e-89c1-9382fc53f870)

**Comment by Stackblocks** [comment]
As a heads-up, `scale-down-30` can be pretty potent in a table

![CleanShot 2023-03-13 at 16 35 46](https://user-images.githubusercontent.com/12678235/224837621-8f4fd8cc-af71-4e0a-8ff9-c0c2e4b29fb2.png)

**Comment by lwtchu** [comment]
@Stackblocks good to know. good thing this is only test content
