### ISSUE TITLE
[FREEZE FOR RELEASE FEB 15] TOC Labeling finalizing naming convention 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5016]
Copied from #4918 
The suggested changes:

- [x] tell CE the connecting tissue bit is ready to be worked on
- [x] `unit-intro`, `chapter-intro` -> `intro`
- [x] `numbered-section-page` -> `numbered-section`
- [x] `answer-key`, `eoc-chapter`, `eob-chapter` -> `sub-book-tree`
- [x] `answer-key-chapter` -> `answer-key`
- [x] `eoc-page`, `references`, `handbook` -> `composite-page`
- [x] `data-toc-type="link"` -> `data-toc-type="book-content"`

**Comment by kswanson33** [comment]
labeling `handbook` as `appendix` instead of `composite-page` because after looking at it again, `handbook` is an authored page, not a collated page. since it comes at the end of the book, it's similar to appendix.

this is only relevant to writing guide

**Comment by kswanson33** [comment]
for QA: full specs for this change are in #4918.
