### ISSUE TITLE
college success - List margin padding and chapter outline in introduction

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#5017]
# Brief Description of Scenario
Lists bullets in top level sections are aligned outside of the left alignment of all other content. 

![Screenshot 2023-02-13 at 11.23.47 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/5bf19b5c-1867-4776-82be-414ab9fc50c5)

Additionally I've just noticed that the "Chapter Outline" is missing, and fonts/font size/heading colors appear to be different in newly generated PDFs compared to the currently published version. For example, in this screenshot we have the currently published and printed PDF on the left, and the newly generated PDF on the right. Things are just a bit off in many small ways where id' expect them to be identical. 

![Screenshot 2023-02-13 at 1.26.59 PM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/50bdedc2-ce3f-4f66-8450-afed04113cad)

# Acceptance Criteria
- [x] list is no longer in margin
- [x] chapter outline is present

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-college-success-bundle
- **collection slug:** college-success
- **ref/branch:** main
- **chapter/section:**  various

**Comment by Stackblocks** [comment]
- Displays OK with updated code & content from distinguished.dragonology

![CleanShot 2023-02-20 at 13.07.40.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/21971b9d-4bb6-42b9-ae12-740f7f1b1606)

![CleanShot 2023-02-20 at 13.11.37.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b7f69341-fedf-4084-8374-715f8be18a13)

**Comment by openstaxalina** [comment]
thanks for catching this @yblock and for the fix and testing @wilkus27 and @Stackblocks -- the authors also asked about this in their review (of a PDF generated just before this code went out) and it's awesome that it's already resolved!
