### ISSUE TITLE
college success - support for multi-child lists (nested lists)

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#5018]
# Brief Description of Scenario
There is a list with a few nested lists that isn't being tabbed properly. This list renders well in POET preview/Web and appears to be marked up correctly, so I'm leaning toward a style issue.

![Screenshot 2023-02-13 at 12.32.16 PM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/4e5607d2-b62a-4efa-8aef-243b2dbd85a4)

# Pattern of Occurrence 
It's just this one list that has a few nested lists

# Acceptance Criteria
Each layer of nesting needs to be indented. 
  
# Sample Mark-Up
```
<list id="fs-idm334884800" list-type="enumerated" number-style="upper-roman">
<item>Dogs <emphasis effect="italics">(main topic–usually general)</emphasis>
<list id="fs-idm367263648" list-type="enumerated" number-style="upper-alpha">
<item>German Shepherd <emphasis effect="italics">(concept related to main topic)</emphasis>
<list id="fs-idm366785952" list-type="enumerated">
<item>Protection <emphasis effect="italics">(supporting info about the concept)</emphasis></item>
<item>Assertive</item>
<item>Loyal</item>
</list>
</item>
<item>Weimaraner <emphasis effect="italics">(concept related to main topic)</emphasis>
<list id="fs-idm363368064" list-type="enumerated">
<item>Family-friendly <emphasis effect="italics">(supporting info about the concept)</emphasis></item>
<item>Active</item>
<item>Healthy</item>
</list>
</item>
</list>
</item>
<item>Cats <emphasis effect="italics">(main topic)</emphasis>
<para id="fs-idm369671056">Siamese</para></item>
</list>
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-college-success-bundle
- **collection slug:** college-success
- **ref/branch:** main
- **chapter/section:** 5.3
- **surrounding text:** The following formal outline example shows the basic pattern:

**Comment by Stackblocks** [comment]
- Displays OK with current code & content from main.

![CleanShot 2023-02-17 at 14.40.26.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/935249a3-8d84-4289-ac7b-eaaa25f64447)

**Comment by yblock** [comment]
Interesting.
