### ISSUE TITLE
college success - top-titled table style

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#5019]
# Brief Description of Scenario
Unnumbered and numbered top-titled tables are styled differently.

![Screenshot 2023-02-14 at 12.53.42 PM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/f84f19e7-3e89-4c7c-8195-115c24d83d5a)![Screenshot 2023-02-14 at 12.53.26 PM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/22719caf-5d07-4674-9e73-42dd4f9b9985)

# Pattern of Occurrence 
From what I can tell the only difference in code between the two tables is one is classed as unnumbered and the other is not.

# Acceptance Criteria
- [ ] enable top-titled styles in this title for unnumbered tables - the titles shouldn't have styling in the first row

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-college-success-bundle
- **collection slug:** college-success
- **ref/branch:** main
- **chapter/section:** 6.2
- **surrounding text:**  you would study a little bit each day

**Comment by LostMojo** [comment]
Hey, it looks cookbook is wrapping numbered top-titled titles in a `div.os-table-title` , but the same isn't happening to unnumbered tables, thus, the in-table styling.

![Screenshot 2023-02-21 at 3.51.39 PM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/16017d8f-0766-4be3-b908-ab51867d77da) 

![Screenshot 2023-02-21 at 3.52.08 PM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/5bc6f01c-6333-456e-820c-9a0c8cb30510)

@lwtchu would you want all top-titled unnumbered (across all books) to have their titles separated out into a `div.os-table-title` before the table?

**Comment by Stackblocks** [comment]
- Displays OK with updated code & content from main

![CleanShot 2023-02-22 at 19.26.35.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/50c4e5b1-abf0-47c9-b287-78c9be82a68a)
---
![CleanShot 2023-02-22 at 19.26.58.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/23102bc4-cf35-4c30-933e-308a8bf38705)
