### ISSUE TITLE
college success - review heading styling 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#5021]
# Brief Description of Scenario
Heading styling get confusing the further down you go, where eventually subheadings are larger than the parent headings. In the example below, the black sub-heading at the bottom of the page is also larger than the blue one above it.

Old style on left, new style with issue on right

![Screenshot 2023-02-14 at 10.10.48 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/a4d14ba0-296b-4653-b1b6-6d7791edb419)

# Pattern of Occurrence 
I think all heading styles should be reviewed to make sure they are displaying as we intend. 

# Acceptance Criteria
- [ ] Using #2644, can we bump everything up by 1 EXCEPT the H5 and Base Font. Additional spec for font-scale(4): 18.66pt, 25.2px, 2.1rem
- [ ] PLEASE DO NOT MERGE THE CHANGE can you locally generate an accounting, business ethics, college success PDF for me so I can see? 

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-college-success-bundle
- **collection slug:** college-success
- **ref/branch:** main
- **chapter/section:** various
- **surrounding text:** n/a

**Comment by lwtchu** [comment]
After reviewing:
- set introduction headers to font-scale(3)
- set roboto condensed to bold
- center the number in the box for module titles
- larissa to update specs once everything is through

**Comment by lwtchu** [comment]
Updated the specs on https://github.com/openstax/cnx-recipes/issues/2644 to match the changes - for testing please test College Success, Accounting and Principles of Management

**Comment by Stackblocks** [comment]
- Displays OK with updated code from eldritch.etymology & content from larissa-test

![CleanShot 2023-03-07 at 16.48.03.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ed626e20-9291-4408-8621-98b9dff650d0)
---
![CleanShot 2023-03-07 at 16.48.46.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c27e326f-8e7b-4102-8801-efbf9f06e18f)
---
![CleanShot 2023-03-07 at 16.48.58.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ddb7f0d3-585e-4747-94eb-8f1b39ff10de)
---
![CleanShot 2023-03-07 at 16.50.05.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3de43d19-1e34-4562-ae6a-cc19321ac938)
---
![CleanShot 2023-03-07 at 17.03.35.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/52205d76-2656-42d4-8647-b989c6bab561)
