### ISSUE TITLE
Organic Chemistry - span class="magenta-text" not available in MathML

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5022]
# Context
There is magenta text in MathML but `<span class="magenta-text">` is not available in MathML. We have used `<m:mtext style="color: magenta">` but the color is not the same. See screenshot. How can we achieve magenta text in MathML?

![image](https://user-images.githubusercontent.com/89537088/218918310-56e6eb74-7462-4cd6-9d2a-8528b0d2e8ac.png)

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<entry valign="top" align="left"><m:math><m:mrow><m:msub><m:mrow><m:mtext>CH</m:mtext></m:mrow><m:mn>3</m:mn></m:msub><m:msub><m:mrow><m:mtext style="color: magenta">OPO</m:mtext></m:mrow><m:mn style="color: magenta">3</m:mn></m:msub><m:msup><m:mrow></m:mrow><m:mrow><m:mn style="color: magenta">2</m:mn><m:mo style="color: magenta">&#x2212;</m:mo></m:mrow></m:msup></m:mrow></m:math> <newline />Methyl phosphate</entry>
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:**  Chapter 03 Section 3.1 Module m00032 line 110
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax the classes for CNXML typically aren't interchangeable with mathml. For the colors, please use the HEX values provided under the ["Changing colors" section on opengui.de](https://www.opengui.de/organic-chemistry). For magenta it'll be `#E00087`

**Comment by lwtchu** [comment]
Closing since this should be addressed in the content!
