### ISSUE TITLE
Organic Chemistry - emphasis class="centered-text" is not working

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5023]
# Context
`<emphasis class="centered-text">` is not working (at least not inside `<example>`)

![image](https://user-images.githubusercontent.com/89537088/218922257-2b2e1046-00dd-4e5d-8566-7bc977101b4f.png)

# Acceptance Criteria
- [ ] make sure centered text is enabled within notes and examples and sections

# Content
## Sample Mark-Up
```
<example id="exam-00002">
    <title>Converting a Chemical Name into a Structure</title>
    <para id="para-00033">Draw the structure of 3-isopropyl-2-methylhexane.</para>
    <para id="para-00034"><title><span class="red-text">Strategy</span></title> This is the reverse of <link target-id="exam-00001"/> and uses a reverse strategy. Look at the parent name (hexane), and draw its carbon structure.</para>
    <para id="para-00035"><emphasis class="centered-text">C–C–C–C–C–C <emphasis effect="bold">Hexane</emphasis></emphasis></para>
    <para id="para-00036">proNext, find the substituents (3-isopropyl and 2-methyl), and place them on the proper carbons.</para>
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 03 Section 3.4 Module m00035 line 123
- **surrounding text:**

**Comment by Stackblocks** [comment]
- Displays OK with updated code from eldritch.etymology & content from main

![CleanShot 2023-02-27 at 15.36.53@2x.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/32113c38-cace-433e-873d-2e7d48b4c6a3)
