### ISSUE TITLE
organic chemistry - empty [link] crashes and explodes the pdf 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5025]
# Brief Description of Scenario
Empty links used to just be filled with `[link]` anchor text and point to nowhere. However, with our recent changes to the way links are pulling in titles and various other things, this is causing stuff to explode and crash the PDF. Please have it not explode and just continue to error out.

# Pattern of Occurrence 
Every time there is an empty link

# Acceptance Criteria
- [ ] Please have it not explode and have it just issue a warning
  
# Sample Error
```
-----+ /workspace/enki/cookbook/lib/recipes/organic-chemistry/bake -----
  191|   BakeCompositeChapters.v1(book: book)
  192|   BakeToc.v1(book: book)
  193|   BakeLinkPlaceholders.v1(book: book)
  194|   BakeFolio.v1(book: book)
  195|   BakeLinks.v1(book: book)

Encountered on line 4295 in the input document on element:
<a xmlns="http://www.w3.org/1999/xhtml" href="" class="autogenerated-content">...</a>
```

# Sample Mark Up
```
<link document="">
<link/>
<link target-id="">
<link document="" target-id="">
```
# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-organic-chemistry
- **collection slug:** organic-chemistry 
- **ref/branch:** https://github.com/openstax/osbooks-organic-chemistry/tree/test-empty-link
- **chapter/section:** 
- **surrounding text:**

**Comment by Stackblocks** [comment]
- Successfully doesn't explode with updated code & content from the `test-empty-link` branch

![CleanShot 2023-02-22 at 18.48.11@2x.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0a2a60b9-9b3c-47e5-ae16-dd4ea0dfc02b)
