### ISSUE TITLE
college success - table width discrepancy 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#5026]
# Brief Description of Scenario
Table width is more compressed in the new style which doesn't leave room for the student to fill out the cells in cases like this appendix item which is intended to be printed out and written in:

![Screenshot 2023-02-16 at 10.30.08 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/202674d1-cb44-4438-867e-de11b9e4c32d)
 
# Pattern of Occurrence 
This is only an issue for tables who's contents don't already expand them horizontally based on their header contents. This goes for both top-titled and non classed types.

# Acceptance Criteria
- [ ] i added the `full-width` class on the main branch
- [ ] please have the class force the width of the table to span the page
 

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-college-success-bundle
- **collection slug:** college-success
- **ref/branch:** main
- **chapter/section:** Appendix C
- **surrounding text:** Activities and Artifacts From the Book

**Comment by lwtchu** [comment]
@yblock can you see if the table mark up has the colwidth stuff defined

**Comment by yblock** [comment]
no colwidth defined here

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-03-09 16-36-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/088a1ae8-1eed-4d6b-ba5c-221a2504e0f5)
