### ISSUE TITLE
Organic Chemistry - Answer Key -- Change layout to 2 columns

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5028]
# Context
Should the Answer Key layout be two columns like Glossary?
![image](https://user-images.githubusercontent.com/89537088/221467138-c19fd6f8-8d3c-4ea1-9110-cbd8ebfcc694.png)

# Acceptance Criteria
- [ ] Answer Key is set to 2 columns

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Answer Key
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax we can test it - I'll open a separate for the distractors.

**Comment by Stackblocks** [comment]
- Displays OK with updated code from eldritch.etymology & content from main
![CleanShot 2023-03-02 at 10.52.22@2x.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/76fd317a-9727-4b87-b50a-f6ab2e83f7f5)
