### ISSUE TITLE
Organic Chemistry - Index -- alphabetization not consistent with chapters and 9e

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5029]
# Context
 In the chapters, we are alphabetizing items like the one indicated in the screenshot per the 9e since those lists are static/hard coded. The Index is auto-generated through the platform, so the content output will be different. 
<img width="337" alt="image" src="https://user-images.githubusercontent.com/89537088/221471624-6d8066cd-18c9-42d2-91d7-1b81fed7672a.png">

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Index
- **surrounding text:**

**Comment by lwtchu** [comment]
Because we cannot manually set the index, we cannot target a different letter within the term. This would require a major pipeline change. Opting for a no change at this moment. The rest of our library does the same and we haven't received any major or critical feedback from users.
