### ISSUE TITLE
Organic Chemistry - Create white text inside red circles in figure caption

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5030]
# Context
How can we create white text in red circles as shown in screenshot below?
From 9e 31-5
<img width="504" alt="image" src="https://user-images.githubusercontent.com/89537088/221584533-75419611-84a7-4fe8-adf5-ac1ee651d169.png">

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** 9e 31-5
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax could you test using ➊ ➋ ➌ ➍ ➎ ➏ with the magenta-text span?

**Comment by ww-openstax** [comment]
@lwtchu suggestion worked and output was approved by WW editorial team. Thanks!
