### ISSUE TITLE
Organic Chemistry - Bulleted list with red bullets?

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5032]
# Context
Is there a ways to create a bulleted list with bullets that are a different color (e.g. magenta or red)? Please see screenshot below from 9e

<img width="463" alt="image" src="https://user-images.githubusercontent.com/89537088/221634661-143e1ec9-1d94-4d3e-a5fb-bbadffca7830.png">

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** 9e Chapter 7 / Section 10 and other instances
- **surrounding text:**

**Comment by lwtchu** [comment]
Not pursuing this fix at this time.

**Comment by lwtchu** [comment]
Not pursuing this fix at this time due to platform limitations.
