### ISSUE TITLE
Organic Chemistry - how to tag table that looks like it was set as image in 9e

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5034]
# Context
See screenshot below from 9e. How can we tag this as a table?
Note: This issue also has been logged in "Production-type OSX-WW items in progress" table in OSX/WW Weekly Meeting Notes.

![image](https://user-images.githubusercontent.com/89537088/222997165-413e67fd-8995-478c-9281-467f820a484a.png)

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** 9e Section 13-4; Table 13-2
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax It will be a little weird, but could you place the image into a single-cell table?
