### ISSUE TITLE
Business Computer Application -- change feature box from "Checkpoint" to "Mac Tip"

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5035]
# Context
See screenshot below and tagging legend Row 33. Change "CHECKPOINT" to "MAC TIP"

![image](https://user-images.githubusercontent.com/89537088/222998182-7930b26f-b279-42d1-9bb4-924636bde7de.png)

# Acceptance Criteria
- [ ] change class from `check-point` to `mac-tip`
- [ ] change title to `Mac Tip`
- [ ] DO NOT CHANGE STYLING for the feature

Test content available here https://github.com/openstax/osbooks-computer-applications/tree/test-content-new-issues

# Content
## Sample Mark-Up
```
<note class="check-point" id="note-00002">
    <exercise class="unnumbered" id="exer-00001">
      <problem id="prob-00001">
    <para id="para-00016">On a Mac, you can simply double-click on the cross and the formula will copy down the column to the last row that contains data.</para>
  </problem>
    </exercise>
    </note>
```

## Location(s)
- **osbooks repo:** osbooks-computer-applications
- **collection slug:** computer-applications
- **ref/branch:** test-content-new-issues
- **chapter/section:** Chapter 1 / Section 1; Module m00002 lines 60-66
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax I've updated the at-at regarding the class change - the styling wont go in effect until this goes to production though, so depending on your QA process, you might want to implement the change after this goes out

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-03-14 15-02-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e5229746-9e6f-4b27-8968-9ad144d87e17)
