### ISSUE TITLE
Business Computer Applications -- change heading from "Written Exercises" to "Written Questions" 

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5036]
# Context
See screenshot below and tagging legend Row 42. Change "Written Exercises" to "Written Questions"

![image](https://user-images.githubusercontent.com/89537088/222999454-718f5253-ea09-4526-91cb-2ae174f9f632.png)

# Acceptance Criteria
I added content on this branch https://github.com/openstax/osbooks-computer-applications/tree/test-content-new-issues

- [ ] update the section class from `written-exercises` to `written-questions` 
- [ ] change the title to `Written Questions`

# Content
## Sample Mark-Up
```
<section class="written-exercises" id="sect-00009">
    <title>Written Exercises</title>
    <exercise id="exer-00005">
    <problem id="prob-00005">
    <para id="para-00035"><link class="os-embed" url="#exercise/09-01-BCA-WQ01"/></para>
    </problem>
    </exercise>
...
</section>
```

## Location(s)
- **osbooks repo:** osbooks-computer-applications
- **collection slug:** computer-applications
- **ref/branch:** test-content-new-issues
- **chapter/section:** Chapter 1 / Section 1; Module m00002 lines 178-184
- **surrounding text:**

**Comment by lwtchu** [comment]
We should change the class to `written-questions` @ww-openstax I'll update the tagging legend
