### ISSUE TITLE
Organic Chemistry - Exercise distractors now outputting as "stacked"

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5038]
# Brief Description of Scenario
Distractors for all Exercise questions are now outputting as "stacked". See screenshot. 
Is this expected? Change to distractor output was not indicated in 2/28 code release notes.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/89537088/223430099-6ef9d002-3435-4e55-aa6b-10426f5384ae.png">

# Pattern of Occurrence 
Every instance

# Acceptance Criteria
- [ ] please have the items inline how they were before 
- [ ] i think there was some confusion regarding the `exercise-block` class. they are only present on 3 exercises in modules m00006, m00012, m00023 - this class should prompt items to be displayed "stacked" or in "block"
  
# Surrounding texts for exercises with class
m0006: Write line-bond structures for the following substances, showing all nonbonding electrons:
CH3CH2OH, ethanol

m00012: Identify all nonbonding lone pairs of electrons in the following molecules, and tell what geometry you expect for each of the indicated atoms.
The oxygen atom in dimethyl ether, CH3―O―CH3.

m00023: Draw the indicated number of resonance forms for each of the following substances:
The methyl phosphate anion, CH3OPO32– (3)

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** all exercises
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
[Uploading... Screenshot from 2023-03-20 16-18-17.png]
