### ISSUE TITLE
Organic Chemistry - link to Section 6.11 outputting as "Section 6.1"

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5039]
# Brief Description of Scenario
The `<link document="m00087"/>` is outputting as "Section 6.1" and it should output as "Section 6.11." See screenshots.
It's possible that this bug is related to Chapter 6 sections currently having only "placeholder" content.

### SCREENSHOT
![image](https://user-images.githubusercontent.com/89537088/223434794-f0d0503d-18fb-4343-a8b3-771d66806c08.png)

### CODE
<img width="555" alt="image" src="https://user-images.githubusercontent.com/89537088/223435122-1bf0ff14-652d-4cbe-92fa-0ba41d30438f.png">

### MODULE m00087
<img width="398" alt="image" src="https://user-images.githubusercontent.com/89537088/223435677-68a23930-ce86-489f-bcb7-3fea768d9ad9.png">

### TOC
<img width="380" alt="image" src="https://user-images.githubusercontent.com/89537088/223436258-b2d10f8c-557b-45a6-8cf9-2db432fc187d.png">

### CHAP 6 ONLY PLACEHOLDER CONTENT
<img width="324" alt="image" src="https://user-images.githubusercontent.com/89537088/223436798-51373723-6262-4c7d-a696-2e8d214a7306.png">

# Pattern of Occurrence 
Only links to Section 6.10 and 6.11 were tested. Section 6.10 had same bug result.

# Acceptance Criteria

  
# Sample Mark-Up
```
<para id="para-00007">In describing a biological process, the reaction is almost always written to show only the structures of the primary reactant and product, while abbreviating the structures of various biological “reagents” and by-products with a curved arrow that intersects the straight reaction arrow. As discussed in <link document="m00087"/><!--Section 6.11-->, the reaction of glucose with ATP to give glucose 6-phosphate plus ADP would then be written as</para>
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 7 / Section 7; module m00069, line 45
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-03-23 16-49-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c171fb97-bc34-4a07-99f0-99c9071b326c)
