### ISSUE TITLE
Organic Chemistry - feature box "no class" is outputting in wrong position on page

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5040]
# Brief Description of Scenario
No Class Feature Box `<note> ... </note>` is outputting in incorrect position on page. The `<note> ... </note>` is tagged to appear after the "Summary" section but is outputting above the "Chemistry Matters" feature.
See screenshot.
See tagging legend Row 37

![image](https://user-images.githubusercontent.com/89537088/223449289-09637df9-69c6-4a03-ab45-6c583f0e5ced.png)

### OUTPUT
<img width="345" alt="image" src="https://user-images.githubusercontent.com/89537088/223444493-e3fefd9e-209e-44e3-b694-873191e1b52e.png">

# Pattern of Occurrence 
This is the first instance of "no class" feature box

# Acceptance Criteria

  
# Sample Mark-Up
```
<note id="note-00001">
    <title>Learning Reactions</title>
    <para id="para-00019">What’s seven times nine? Sixty-three, of course. You didn’t have to stop and figure it out; you knew the answer immediately because you long ago learned the multiplication tables. Learning the reactions of organic chemistry requires the same approach: reactions have to be learned for quick recall if they are to be useful.</para>
    <para id="para-00020">Different people take different approaches to learning reactions. Some people make flashcards; others find studying with friends to be helpful. To help guide your study, most chapters in this book end with a summary of the reactions just presented. In addition, the accompanying <emphasis effect="italics">Study Guide and Solutions Manual</emphasis> has several appendixes that organize organic reactions from other perspectives. Fundamentally, though, there are no shortcuts. Learning organic chemistry does take effort.</para>
    </note>
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 8 / Section 13; module m00101 lines 105-109
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax can you put that feature within the `<section class="summary">`? The recipe doesn't know to target it so it won't go with the summary.

**Comment by ww-openstax** [comment]
@lwtchu your suggestion fixed the issue. Thanks!
