### ISSUE TITLE
organic chemistry - changing numbering schema for all exercises to add the word problem

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5043]
# Brief Description of Scenario
There's been a request to change the numbering to add the word PROBLEM and the chapter number.
![Screenshot 2023-03-08 at 11 21 56 AM](https://user-images.githubusercontent.com/11299125/223784854-8f258e3f-ffa4-46f2-80c2-e219a397f4e0.png)
(screenshot is from an edit in adobe, spacing might be a bit wonky as a result)

# Pattern of Occurrence 
Anywhere there is an exercise - EOS sections, EOC, and answer key

# Acceptance Criteria
- [ ] add the word PROBLEM in all caps
- [ ] add a line break between the PROBLEM and number
- [ ] add the chapter number as a prefix to the exercise number with a dash `#-#`
- [ ] all of the numbering bit should be right aligned like the screenshot
- [ ] NO period after PROBLEM or NUMBER
- [ ] It is acceptable that this goes throughout the whole book (including answer key)
- [ ] in the end of section problems, REMOVE the `Section #.# Problems` title
- [ ] For tester: when testing in webview, we might have to open a separate card for the styling changes
  

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:** main
- **chapter/section:** 
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-03-16 15-05-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/36e1b1ca-9571-4da4-b323-49b242cb444d)
