### ISSUE TITLE
organic chemistry - revert answer key back to 1 column

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5046]
![image](https://user-images.githubusercontent.com/11299125/225371775-926e5015-0838-4782-b0b5-b0ac963f81d0.png)

# Brief Description of Scenario
Due to #5043, the answer key is now super squashed and cluttered. We will revert the change made in #5028. 

# Pattern of Occurrence 
Answer Key

# Acceptance Criteria
- [ ] answer key is back to 1 column. I'm sorry
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:** main
- **chapter/section:**  Answer Key
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-03-16 15-07-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/54ce0575-7eae-420f-89e2-667212cf6ed3)
