### ISSUE TITLE
College Success Concise - Sub level list indentation

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5047]
We have received the below corrections from customer. Kindly check and resolve this issue.

![Sublevel-list](https://user-images.githubusercontent.com/86622862/225616933-ae5c669c-c3f2-49b1-99aa-fb53c391a46b.png)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-college-success-bundle
- **collection slug:**college-success-concise
- **ref/branch:**https://openstax-osbookscollege-m47en3dy7va.ws-us90.gitpod.io/
- **chapter/section:** Chapter 3/Section 4
- **surrounding text:** The following formal outline example shows the basic pattern

**Comment by lwtchu** [comment]
![Screenshot 2023-03-20 at 1 48 29 PM](https://user-images.githubusercontent.com/11299125/226437507-0ede7207-a729-45ee-9379-0c3007f488f1.png)
Screenshot from PDF generated today. Fixed with https://github.com/openstax/cnx-recipes/issues/5018
