### ISSUE TITLE
nursing-external - some features that should be regular iconned notes are set as condensed iconned notes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5049]
# Brief Description of Scenario

<img width="736" alt="Screenshot 2023-03-16 at 11 35 10 AM" src="https://user-images.githubusercontent.com/11299125/225689467-b2513887-af8d-4d1f-b4b3-aa6d78dd9936.png">

The screenshot above should be like this screenshot below ...

<img width="845" alt="Screenshot 2023-03-16 at 11 39 10 AM" src="https://user-images.githubusercontent.com/11299125/225690461-7e111bb2-4291-47bb-a124-479808cbb050.png">

Note the icon is larger and has another line under the main title.

##  Documentation #3966
- [ ] Healthy People 2030 `healthy-people` 
- [ ] Trending Today `trending-today` 
- [ ] Media `media-feature` 
- [ ] Conversations About Culture `culture-conversations` 
- [ ] Theory in Action `theory-action` 
- [ ] Case Reflection `case-reflection` 
- [ ] Unfolding Case Study `unfolding-casestudy` 
- [ ] Case Study `single-casestudy` 
- [ ] Update the icon for the blue [carnival-exampleblue.svg](https://drive.google.com/file/d/1Zj_iTq6XApkFWK1vd5NMkvJJ5vlJ8lL3/view?usp=share_link) please

# Pattern of Occurrence 
happens to features within this list

# Acceptance Criteria
- [ ] features listed above are set as REGULAR iconned notes
 

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** nursing-external-combined
- **ref/branch:** design-chapters

**Comment by Stackblocks** [comment]
It looks like the input is pulling the referenced icon, so the output having a different hex is probably an Adobe rendering issue.

I think with @lwtchu's blessing we could let this through (unless i'm misunderstanding the concern).

#### Source Icon
![CleanShot 2023-04-18 at 10.52.45.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1b8dcaa8-bd91-422a-a955-bce737b2573c)

#### Sourcing in Code
![CleanShot 2023-04-18 at 10.54.59.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/295e1a4d-6f9f-4a28-92c5-a48578e37989)
---
![CleanShot 2023-04-18 at 10.54.20.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c6a7d8ad-4ecb-418b-8bf0-6abab26d4c74)

### Icon in Output
![CleanShot 2023-04-18 at 10.53.20.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/cf90e374-29f2-45a0-8492-42e9332f79ec)
