### ISSUE TITLE
nursing-external - clinical tip note icon a little larger

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5050]
# Brief Description of Scenario
![Screenshot 2023-03-16 at 12 51 47 PM](https://user-images.githubusercontent.com/11299125/225716698-efe68adb-a4d0-46cd-9647-b084f120e6aa.png)

^^ Icon is a bit small. Should be a bit larger than the text (documentation https://github.com/openstax/cnx-recipes/issues/3235) 

![Screen Shot 2020-12-18 at 4 30 38 PM](https://user-images.githubusercontent.com/11299125/102667172-63a5d900-414e-11eb-8f9b-297791f68318.png)

Could pull specs from the Link to Learning feature or Safety Alert - both of these look ok. If you need a new icon too I can make one.

Currently only impacting - class: `clinical-tip`

# Pattern of Occurrence 
- [ ] All Clinical Tip `clinical-tip`

# Acceptance Criteria
- [ ] icon is a smidge bitter like in Link to Learning
  

# Location(s)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** nursing-external-combined
- **ref/branch:** design-chapters
- **chapter/section:** 
- **surrounding text:** Clinical Tip

**Comment by lwtchu** [comment]
@LostMojo new icon [carnival-scientificsmall.svg](https://drive.google.com/file/d/1fSCF-Rpr-b_xrQgxzbQnRr1m7turMjsS/view?usp=share_link)

**Comment by Stackblocks** [comment]
Icon now appears to be in line with the other feature icons with content from `design-chapters` and code from g.g

![CleanShot 2023-03-30 at 14.37.43.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/bb733b8d-99ce-4196-8470-6ea99b90446a)
