### ISSUE TITLE
nursing-external - client teaching guidelines should be a boxed note

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5051]
# Brief Description of Scenario
![Screenshot 2023-03-16 at 1 23 22 PM](https://user-images.githubusercontent.com/11299125/225717294-0b097c52-e4cd-44f1-8bcc-2a44f7c9b4db.png)

# Pattern of Occurrence 
All Client Teaching Guidelines

# Acceptance Criteria
Should look like a boxed note with purple color (https://github.com/openstax/cnx-recipes/issues/4991)

![Screenshot 2023-03-16 at 1 30 00 PM](https://user-images.githubusercontent.com/11299125/225718945-3fdfd4b4-1c06-465c-8844-50371cdb7c15.png)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** nursing-external-combined
- **ref/branch:** design-chapters

**Comment by MartaSztuka** [comment]
#### PASSED
##### Pharmacology
![Screenshot from 2023-03-23 16-31-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e7d69c6c-1f99-466e-b413-f34fa6e03846)

##### Nutrition
![Screenshot from 2023-03-23 16-42-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9109db62-0ebe-4e7d-8332-7ab9abbc6cfb)
