### ISSUE TITLE
nursing-external - unfolding case study, single case study exercises should be styled

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5052]
# Brief Description of Scenario
![image](https://user-images.githubusercontent.com/11299125/225724999-23089733-31f8-4a4e-a903-2d31f5bcf235.png)

# Pattern of Occurrence 
All exercises in Unfolding Case Study and Single Case Study

# Acceptance Criteria
- [ ] they should look like the EOC, no line break, no link underline, black, bold 
- [ ] works in Unfolding Case Study
- [ ] Works in Single Case Study

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** nursing-external-combined
- **ref/branch:** design-chapters
- **chapter/section:** 
- **surrounding text:** Unfolding Case Study, Single Case Study

**Comment by MartaSztuka** [comment]
@lwtchu note looks fine, but top lines are missing, is that ok?
![Screenshot from 2023-04-12 16-01-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f55801b4-9afa-4bc2-aa09-5f6212b2d2c2)

![Screenshot from 2023-04-12 15-55-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f51cebcf-7479-496f-80d8-f03b732aa359)
