### ISSUE TITLE
nursing-external - enabling `no-cellborder` tables 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5055]
# Brief Description of Scenario
![Screenshot 2023-03-17 at 2 31 33 PM](https://user-images.githubusercontent.com/11299125/226002586-00201542-69df-4e1a-8401-475b47c91f09.png)
This table has the `no-cellborder` class and I do not think the design made it into the prototype. (Documentation here: #5009) 

# Pattern of Occurrence 
Just in the nutrition book - there's 2 in the book

# Acceptance Criteria
- [ ] no-cellborder more or less looks like the design in #5009 
  

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** nutrition
- **ref/branch:** design-chapters
- **chapter/section:** 
- **surrounding text:**

**Comment by MartaSztuka** [comment]
@lwtchu, I think space between those could be wider:
![Screenshot from 2023-04-18 10-55-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7b2bc1a1-5c36-4977-aa46-a107efb3cd80)

**Comment by Stackblocks** [comment]
Resolved as part of #5007 

![CleanShot 2023-04-20 at 15 05 53](https://user-images.githubusercontent.com/12678235/233476329-a74459d5-7a23-4d0a-bb47-3149dda7ad45.png)
