### ISSUE TITLE
Business Computer Applications -- change learning objectives from numbering to bullet

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5056]
# Context
For Learning Objectives: the rest of the business/"cardboard" titles use bullets instead of a numbering scheme. Should the numbering format in BCA be changed to bullets for consistency across titles and coding?

![image](https://user-images.githubusercontent.com/89537088/226658511-8c054ff9-72a8-4ed0-8948-0ddd3c479928.png)

# Acceptance Criteria
- [ ] Please change the numbers to bullets like in the "Unnumbered Bullets" section in this documentation card #2711 

# Content
## Sample Mark-Up
```
<section class="learning-objectives" id="sect-00001">
    <title>Learning Objectives</title>
    <para id="para-00001">By the end of this section, you will be able to:</para>
    <list id="list-00001">
    <item>Identify common uses for <term class="no-emphasis" id="term-00001">Excel</term> spreadsheets</item>
    <item>Use basic features of Excel</item>
    <item>Describe the essential functions of each tab on the Ribbon</item>
    <item>Differentiate between worksheets and workbooks</item>
    <item>Create worksheets and navigate existing files</item>
    <item>Print a workbook and a worksheet</item>
    </list>
    </section>
```

## Location(s)
- **osbooks repo:** osbooks-computer-applications
- **collection slug:** computer-applications
- **ref/branch:**
- **chapter/section:** screenshot is from m00002 lines 9-20
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax This was by design - I'm not sure if SMEs/Content would be okay with removing the Learning Objective numbering?

**Comment by openstaxalina** [comment]
Mike & team verifying SMEs' preference here

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-18 16-41-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9601c61d-2ad0-4327-9f25-d594af3f73fc)
