### ISSUE TITLE
[webview styles and a11y] contemporary math - enable too wide equations to scroll

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5060]
# Brief Description of Scenario
Related to #5059 - would be good to test together

https://github.com/openstax/rex-web/pull/1896#issuecomment-1467781007 - scenario number 3 in this comment

# Pattern of Occurrence 
All block equations (`[data-type="equation"]`) - please make your screen too small and see if a scroll bar appears

# Acceptance Criteria
Equations can scroll if it's too wide in webview
  

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-contemporary-mathematics
- **collection slug:** contemporary-mathematics
- **ref/branch:** main
- **chapter/section:**  see above
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-03-22 17-24-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/52aff08f-979b-4d42-b108-6565659e7e44)

![Screenshot from 2023-03-22 17-24-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fdc9e5d0-fbc2-4543-a5aa-6dae639f8931)

**Comment by openstaxalina** [comment]
reopening this - observed with @lwtchu on our call today that the horizontal scrolling seems no longer to be enabled. ([example](https://openstax.org/books/contemporary-mathematics/pages/3-8-exponents) - above "All of the work above confirmed what...")

There is also a **new acceptance criteria** that the horizontal scroll bar should take the Text Resizer feature on REX into account, and add the horizontal scroll when use of that feature causes math to fall off the page (screenshot below - [reported by Level Access](https://github.com/openstax/unified/issues/2795))
![Screenshot 2024-03-11 at 4 51 44 PM](https://github.com/openstax/cnx-recipes/assets/7863733/34edddc1-72a3-4cee-b312-34c248fa8544)

**Comment by wilkus27** [comment]
### Information for tester
Please, test also numbered equations. Could be found in finance for example.

**Comment by Stackblocks** [comment]
Both the standard and numbered equations are scrolling properly in a reduced-width window.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/02b08476-f5fd-4d1d-a22f-b1de0bc90bba)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/c3516b59-5150-4b27-a0e3-b3658dd16ff2)
