### ISSUE TITLE
nursing-internal - splash image

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5062]
documentation: #1075

**Comment by MartaSztuka** [comment]
##### Splash image is not displayed, however there is 'OSX_Ethics_05_00_WorldMap.jpg' and 'OSX_Ethics_02_00_Justice.jpg' in media folder.
![Screenshot from 2023-04-03 11-47-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/696c532e-c96e-43c0-aedb-93dcbaab4150)

**Comment by wilkus27** [comment]
@lwtchu There are still some problems with splash images :thinking:

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-05 17-40-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4f6e1cd5-e9b5-4902-9b47-34bb9930a4da)

![Screenshot from 2023-04-05 17-41-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/61a8ef3e-80bd-45e2-9115-4432b30aa5ec)
