### ISSUE TITLE
nursing-internal - chapter outline and introduction

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5065]
Documentation #4738 please use version 2

**Comment by MartaSztuka** [comment]
##### image is not displayed, but beside that it's ok.
![Screenshot from 2023-04-03 11-42-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/93e3ad34-3e7f-41f2-a773-b0a0ba72ff50)
