### ISSUE TITLE
nursing-internal - learning objectives

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5066]
documentation #1077
title: Learning Objectives
please use the numbering schema but can we do #.#.# like in some of the math books (calculus)?

For example section 1.1 will have LO 1.1.1, 1.1.2, etc

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-03 12-07-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3d089a44-2393-41fa-9921-72e2f6505e11)
