### ISSUE TITLE
nursing-internal - link to learning

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5069]
- class: `link-to-learning`
- uses #3235
- title: Link to Learning
- no subtitle
- icon: [carnival-linktolearning.svg](https://drive.google.com/file/d/1jm3US-spU6F3BwURhHDY5Emxpe5vmyOr/view?usp=sharing)
- color: G1: `#78B042`

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `groovy.garbology` & content from `nursing-test` on`testcontent`

![CleanShot 2023-04-03 at 16.06.13.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f834a7db-05e8-4327-8d5e-fbc1d304fea5)
