### ISSUE TITLE
nursing-internal - unfolding case study feature

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5070]
class: `unfolding-casestudy`
documentation #3966
title: Unfolding Case Study
subtitle: yes
icon: [carnival-example.svg](https://drive.google.com/file/d/16IZ-M4-fsrDr4iPwHCEm1AEPrdQIsjd9/view?usp=share_link)
color: R1: `#C31427`
mostly text. will include critical thinking questions as bulleted items at the end of the feature.

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `groovy.garbology` & content from `nursing-test` on`testcontent`

![CleanShot 2023-04-03 at 16.15.54.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/934ee2ba-db3d-4a81-b44a-5176038083d8)
