### ISSUE TITLE
nursing-internal - clinical safety and procedures (QSEN)

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5071]
class: `clinical-safety`
documentation #3966
title: Clinical Safety and Procedures (QSEN)
subtitle: yes
icon: [carnival-check.svg](https://drive.google.com/file/d/101zf9gMdbH6vfg_jTb3zJhqTa7O0uvyR/view?usp=share_link)
color: O1: `#F37541`
text with step-by-step procedures. may come in many forms and will often include diagrams or images.

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `groovy.garbology` & content from `nursing-test` on`testcontent`

![CleanShot 2023-04-03 at 16.14.57.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ae0b4ee6-1c75-40d5-a599-bf4b4ffa02ea)
