### ISSUE TITLE
nursing-internal - real rn stories

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5072]
class: `rn-stories`
documentation #3966
title: Real RN Stories
has a subtitle: yes
icon: [carnival-rn-stories.svg](https://drive.google.com/drive/u/0/folders/1zA3DPstc7Cx1BqtdMYCEB_NGXn1D0XXw)
color: R1: `#C31427`
mostly text (vignettes from actual nurses). include information about nurse including credentials, years in practice, and state.

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `groovy.garbology` & content from `nursing-test` on`testcontent`

![CleanShot 2023-04-03 at 16.15.28.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/664be4fb-2e33-4c09-8048-85358c75d79d)
