### ISSUE TITLE
nursing-internal - life-stage and cultural context

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5073]
class: `cultural-context`
documentation #3966
title: Life-stage and Cultural Context
has a subtitle: yes
icon: [carnival-lifestageculture.svg](https://drive.google.com/drive/u/0/folders/1zA3DPstc7Cx1BqtdMYCEB_NGXn1D0XXw)
color: G3: `#007A49`
mostly text. 1–5 paragraphs.

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `groovy.garbology` & content from `nursing-test` on`testcontent`

![CleanShot 2023-04-03 at 16.14.00.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d4fe5458-bed3-4bba-832f-3327a84b8af8)

**Comment by lwtchu** [comment]
@caylaeagon might need a new icon where the circle is filled with white so the horizontal line doesn't come thru

**Comment by caylaeagon** [comment]
I updated the icon in the assests folder with a white fill in the circle: [carnival-lifestageculture.svg](https://drive.google.com/drive/u/0/folders/1zA3DPstc7Cx1BqtdMYCEB_NGXn1D0XXw)

**Comment by lwtchu** [comment]
@wilkus27 should i create a new issue for the new icons ?
