### ISSUE TITLE
nursing-internal - pharmacology connections (maternal only)

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5075]
class: `pharma-connections`
documentation #3966
title: Pharmacology Connections
has a subtitle: yes
icon: [carnival-pharmacology.svg](https://drive.google.com/drive/u/0/folders/1zA3DPstc7Cx1BqtdMYCEB_NGXn1D0XXw)
color: R2: `#B10069`
text and images.

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `groovy.garbology` & content from `nursing-test` on`testcontent`

![CleanShot 2023-04-03 at 16.10.24.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/fe56a90c-82f1-4adc-963d-ebf7ab9eb1c1)
