### ISSUE TITLE
nursing-internal - legal and ethical issues (maternal only)

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5076]
class: `legal-ethical`
documentation #3966
title: Legal and Ethical Issues
has a subtitle: no
icon: [carnival-homestaticimbalance.svg](https://drive.google.com/drive/u/0/folders/1zA3DPstc7Cx1BqtdMYCEB_NGXn1D0XXw)
color: O1: `#F37541`
contains text and likely tables with art.

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `groovy.garbology` & content from `nursing-test` on`testcontent`

![CleanShot 2023-04-03 at 16.07.33.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/2339556a-a37e-4d4e-9df0-65808b7e4e9b)
