### ISSUE TITLE
nursing-internal - multidisciplinary plan of care (med-surge only)

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5077]
class: `multi-disciplinary`
documentation #3966
title: Multidisciplinary Plan of Care
has a subtitle: yes
icon: [carnival-microconnections.svg](https://drive.google.com/drive/u/0/folders/1zA3DPstc7Cx1BqtdMYCEB_NGXn1D0XXw)
color: B1: `#0DC0DC`
contains text and likely tables with art.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-03 16-45-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/20305036-fae9-46be-98ed-d93d83c3830e)
