### ISSUE TITLE
nursing-internal - clinical judgment measurement model

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5078]
class: `clinical-judgment`
documentation #4746
title: Clinical Judgment Measurement Model
has a subtitle: yes
color: P2: `#651C72`

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-03 16-39-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4013302e-1e2c-465d-860f-049519e8770b)
