### ISSUE TITLE
nursing-internal - read the electronic health record (med-surge only)

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5079]
class: `electronic-hr`
documentation #4746
title: Read the Electronic Health Record
has a subtitle: yes
color: B5: `#0078a3`

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-03 16-41-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1841aeab-319a-4b7c-968e-66417cb15630)
