### ISSUE TITLE
nursing-internal - psychosocial considerations (psychiatric only)

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5080]
class: `psychosocial-considerations`
documentation #4746
title: Psychosocial Considerations
has a subtitle: yes
color: B2: `#0074BC`

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-03 16-43-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d0769808-652b-4061-9815-fba006ddec1c)
