### ISSUE TITLE
nursing-internal - end of chapter

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5081]
If there is no content, please make sure it doesn't auto-populate a header. If you need content - please contact Larissa or Cayla.

# Glossary
- Title: Glossary
- uses `<glossary>`
- documentation #4752

# Summary
- Title: Section Summary
- `class="summary"`
- documentation #4753
- divided by sections/module? YES
- may contain paragraphs

# Assessments
There are 6 different types of assessments. They should collate to the end of the chapter by assessment type, then by module order (then by number) under each type. Not all modules will contain all question types.

## Review Questions
- `class="review-questions"`
- multiple choice lists in exercises should not have a double line break between question and choices
- list follows standard list indentation
- numbering starts at 1 and resets every chapter
- divided by sections/module? YES
- answer goes to the answer key with the detailed solution

## Check Your Understanding
- `class="check-understanding"`
- short answer type question
- numbering starts at 1 and resets every chapter
- divided by sections/module? YES
- answer goes to the answer key with the detailed solution

## Critical-Thinking Questions about Case Studies
- `class="critical-thinking"`
- short answer type question
- may include images
- numbering starts at 1 and resets every chapter
- divided by sections/module? YES
- answers will vary. answer goes to the answer key with rubric notes.

## Competency-Based Assessment
- `class="competency-based"`
- short answer type question
- numbering starts at 1 and resets every chapter
- divided by sections/module? YES
- answers will vary. answer goes to the answer key with rubric notes.

## Reflection Questions
- `class="reflection-questions"`
- short answer type question
- numbering starts at 1 and resets every chapter
- divided by sections/module? YES
- answers will vary.

## What Should the Nurse Do?
- `class="what-nurses-do"`
- short answer type question
- numbering starts at 1 and resets every chapter
- divided by sections/module? YES
- answers will vary. answer goes to the answer key with rubric notes.

# References
- Documentation: #3214
- Title: References
- `class="references"`
- divided by sections/module? NO
- unnumbered references collate to end of chapter (NOT end of book).

**Comment by MartaSztuka** [comment]
@wilkus27 
When there's figure in the list number drops down:
![Screenshot from 2023-04-04 10-03-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e627bb87-90ff-4426-8a6a-b12b618db41c)
#### PASSED
##### Key Terms
![Screenshot from 2023-04-04 09-51-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/39866797-ae4e-402a-90e5-4b1d9408886b)

##### Section Summary
![Screenshot from 2023-04-04 09-53-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f2c575e8-a872-44c0-a639-e41f6e64de15)

##### Review Questions
![Screenshot from 2023-04-04 09-54-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8ac5f2a3-f2fa-406e-b29b-a78fd71696cf)

##### Check Your Understanding Questions
![Screenshot from 2023-04-04 09-54-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a5ece088-7138-461d-9c31-30ac1c9c70c9)

##### Critical-Thinking Questions about Case Studies
![Screenshot from 2023-04-04 09-56-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3ce68305-1894-46cb-882a-5cd00bb70a84)

##### Competency-Based Assessment
![Screenshot from 2023-04-04 09-57-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cca4845d-d9ac-42c2-9959-d5732011b6e3)

##### Reflection Questions
![Screenshot from 2023-04-04 09-58-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/16339977-198e-4f78-8ba3-d544c0941415)

##### "What Should the Nurse Do?" Questions
![Screenshot from 2023-04-04 09-59-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/263ef5cb-541e-4c07-be55-8a5ed6145258)

##### References
![Screenshot from 2023-04-04 09-59-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/373e0539-53f2-445b-a0a6-fbb853c96943)
