### ISSUE TITLE
nursing-internal - answer key

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5082]
- documentation #4757
- Please pull correct answer and detailed question
- Separate by Chapter
- Other headers for answers should be
  - Review Questions
  - Check Your Understanding Questions
  - Critical-Thinking Questions about Case Studies
  - Competency-Based Assessment
  - Reflection Questions
  - "What Should the Nurse Do?" Questions

**Comment by lwtchu** [comment]
@wilkus27 @MartaSztuka thank you! i couldn't find an optimal way to enable these answers to show up on the content side. I'll have to rework some of the assessments
