### ISSUE TITLE
nursing-internal - indented text

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5084]
Tagging `<emphasis class="indented-text">Indented text.</emphasis>`

For the text in this tag, please:
- remove the bold set by `<emphasis>`
- indent string of text (even if it runs over 1 or more line) by 0.5" (or whatever the list indent is)

**Comment by wilkus27** [comment]
@lwtchu Additional ce-tech work is needed for transformation xml to xhtml. This is what we are getting now:

xml
![image](https://user-images.githubusercontent.com/40228854/229780535-10420ddd-4db6-4745-8745-1b0d026cd3f9.png)

xhtml
![image](https://user-images.githubusercontent.com/40228854/229780691-33211caa-7d20-4338-a361-a455fb32af52.png)

Class `indented-text` doesn't show up in assembled file.

**Comment by wilkus27** [comment]
@lwtchu I'm not sure which repo is used for such changes. We should probably ask Phil.

**Comment by lwtchu** [comment]
@wilkus27 talked to phil and he thinks we should try adding a class on the para since it will make more sense semantically 🤔 - do you mind seeing if that might work better for you? we might need to change the centered-text later but <emphasis> doesn't seem like the right way to go.

**Comment by wilkus27** [comment]
@lwtchu This is what it looks now:

![image](https://user-images.githubusercontent.com/40228854/232475539-c18d4a0e-8639-4a33-8d9b-adad692384a3.png)

I applied list indentation h-spacing(3) (24px).

**Comment by lwtchu** [comment]
@wilkus27 this looks great thank you - does the para class work better? it might be good to set the centered text that way

**Comment by wilkus27** [comment]
@lwtchu Yes, I think it might be a good approach. We have in styles files for custom paragraphs so it will be more consistant.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-18 10-37-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/22f17810-11b7-4500-87e5-027fa338b734)
