### ISSUE TITLE
nursing-internal - centered text

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5085]
Documentation #3654

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-03 12-08-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e9cfa0dc-bad3-4594-9cb7-2fda5fd2a24c)![Screenshot from 2023-04-03 12-11-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bf569ddd-0d67-4825-9adc-120285ffdc64)
