### ISSUE TITLE
all books - change 'Click to view content' to 'View multimedia content'

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5086]
# Brief Description of Scenario
![Screenshot 2023-03-28 at 1 07 46 PM](https://user-images.githubusercontent.com/11299125/228329086-25846593-73bf-48e9-b98f-9940721bb591.png)

"Click to view content" doesn't make much sense when the PDF is printed. Please change the autogenerated text to say `View multimedia content`

# Pattern of Occurrence 
In any and all embedded iframes - we can probably just test in Biology, Finance and World History

# Acceptance Criteria
- [ ] update locales yml file for `Click to view content` to `Access multimedia content`
- [ ] update for Polish and Spanish w `Przejdź do treści multimedialnej` and `Accede a contenidos multimedia` respectively 
- [ ] link now says `Access multimedia content (link)` and other languages do too
  
# Sample Mark-Up
```
 <media alt="LingIong">
    <iframe src="https://openstax.org/l/77LingIong" width="560" height="384"/></media>
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-world-history
- **collection slug:** world-history
- **ref/branch:** world-history-volume-1
- **chapter/section:** Resistance, Civil Rights, and Democracy
- **surrounding text:** The site includes a feature that will read the content aloud in Mandarin.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Word history 1
![Screenshot from 2023-04-14 16-08-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/48c089ee-5905-4ef9-a943-20f5ebea7fbc)
##### Word history 2
![Screenshot from 2023-04-14 16-19-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d775849b-9d5b-48fb-b4bd-f9f118611598)
