### ISSUE TITLE
nursing-external: Blue text not displaying 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5087]
## Issue 
              Blue text not displaying with content from `design-chapters` and current code from `f.f.`

![CleanShot 2023-03-21 at 09.24.22.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/fbc180d8-e98d-46ed-8b61-9ab55efc482a)

![CleanShot 2023-03-21 at 09.25.15.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e9903618-d853-483d-a5d1-9111bb12c95b)

_Originally posted by @Stackblocks in https://github.com/openstax/cnx-recipes/issues/5006#issuecomment-1477937136_

## Acceptance Criteria
- [ ] I believe the work is done somewhere cause it was displaying in the sample book but please have blue text appear again

## Location
https://github.com/openstax/osbooks-nursing-external-bundle
branch: design-chapter

**Comment by MartaSztuka** [comment]
#### PASSED

![Screenshot from 2023-04-12 08-59-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9518c336-7ccd-41dc-80cd-a70814c8ce9a)

**Comment by MartaSztuka** [comment]
#### PASSED

![Screenshot from 2023-04-12 08-59-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9518c336-7ccd-41dc-80cd-a70814c8ce9a)
