### ISSUE TITLE
nursing-external - headers should have color

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5088]
# Brief Description of Scenario
![Screenshot 2023-03-29 at 3 53 10 PM](https://user-images.githubusercontent.com/11299125/228664700-2891b297-3b46-4d6c-88c8-afb8f39b90c0.png)

I think because the styles were copied from OChem (which is an exception), the header colors are missing. Please follow #4732 

# Pattern of Occurrence 
- all EOC headers

# Acceptance Criteria
- EOC headers have colors
  

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** nursing-external
- **ref/branch:** design-chapters

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-12 16-57-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/12662076-4050-4177-ba66-ad9858b4fffa)
