### ISSUE TITLE
nursing-external - answer key exercises need styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5089]
## Summary of Issue
 Number and answer text should be inline, also there is problem with spacing between header and number.

 ![Screenshot from 2023-03-21 14-14-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/572b19dd-9ed3-404b-8829-6e8fe6cbfdb6)

_Originally posted by @MartaSztuka in https://github.com/openstax/cnx-recipes/issues/5004#issuecomment-1477833776_
 

## Acceptance Criteria 
- numbering is black, bold and answers are pulled in line 

## Content
https://github.com/openstax/osbooks-nursing-external-bundle
slug: nursing-external
branch: design-chapters

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-18 10-44-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/56446a2a-6fc3-44fc-aa51-8e9cda3e11ee)
