### ISSUE TITLE
[webview] computer applications - problem orphaned from number

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5090]
# Brief Description of Scenario
New line character present between question # and the question (I think this happens on questions with figures)

<img width="1290" alt="Screenshot 2023-03-23 at 10 12 28 AM" src="https://user-images.githubusercontent.com/40276461/227271307-4fcbd208-204e-41ae-b433-6a6e55b1b327.png">
<img width="1225" alt="Screenshot 2023-03-23 at 11 11 10 AM" src="https://user-images.githubusercontent.com/40276461/227271310-1508c3d7-b2e4-437a-841d-5e1b3162274b.png">
<img width="1289" alt="Screenshot 2023-03-23 at 11 17 54 AM" src="https://user-images.githubusercontent.com/40276461/227271318-acf3d4c1-0b0c-42e8-aeeb-49ededc7f020.png">

# Pattern of Occurrence 
Malar believes this only happens when there is an image

# Acceptance Criteria
- paragraph stays with the number
  

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-computer-applications
- **collection slug:** computer-applications
- **ref/branch:** main
- **chapter/section:**  Practice Exercises 
- **surrounding text:** Please see screenshots above.

**Comment by wilkus27** [comment]
To fix this I applied styling approach from PDFs. For now I added it just for injected exercises. During refactoring we will apply it to all kinds of exercises.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Review Questions
![Screenshot from 2023-04-14 10-06-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fbff0406-1562-4738-9915-0be675aecfa6)

##### Practice Exercises
![Screenshot from 2023-04-14 10-07-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9346fc3d-d5be-463b-bd35-bc7f9e263279)

##### Case Exercises
![Screenshot from 2023-04-14 10-08-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f5fc34c4-06cb-4777-8c5d-14f17d8efa1d)
