### ISSUE TITLE
College Success Concise - table text hidden issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5091]
We have coded the table 1.2 as per the tagging legend, but we have faced column contents hidden issue in both outputs (PDF and WebView). Kindly check and resolve this issues.

![Chapter 1 2-table](https://user-images.githubusercontent.com/86622862/229491632-d06b0a1e-087b-4833-81a7-9044b497c0ae.png)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-college-success
- **collection slug:** college-success-concise
- **ref/branch:** https://openstax-osbookscollege-3m2pu9kawbo.ws-us93.gitpod.io/
- **chapter/section:** Chapter 1/Section 2
- **surrounding text:** Students will take a more active role in their learning than they

**Comment by lwtchu** [comment]
@srm-openstax If we compress the table more, it might become illegible. Could you explore the option of rotating the table so that the headers are "What Is It?" and "Students exhibit it when they:" That way the text has room to take up space and it'll mostly be a vertically long table.

**Comment by lwtchu** [comment]
Since we're in Final QA, we'll have Colby make the change
