### ISSUE TITLE
Organic Chemistry - create em-dash-length double bonds and em-dash-length triple bonds

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5093]
# Context
We need a way to create em-dash-length double bonds and em-dash-length triple bonds in both text and in Exercises

### Screenshot from Chapter 11.3. Module m00124; line 32 and from Chapter 11 EOC Exercises
![image](https://user-images.githubusercontent.com/89537088/230100050-2edc4814-eee1-4867-80cc-251af3e17d64.png)

### Screenshot from 9e Chapter 11-3
<img width="546" alt="image" src="https://user-images.githubusercontent.com/89537088/230100949-71d48f16-a171-49b7-a939-ddf6fbb11052.png">

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 11 / Section 3  //  Module m00124; line 32  //  Nickname:11-99-OC-AP03 //  Nickname:11-99-OC-AP04
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax The math will always have space around it, so the best way to remove space is to set the whole thing in math so it can reference the other elements in the same string. 

`\text{H}_2\text{C=CHBr}` for the first example - note the double dash is still inside the text tag 
`\text{H}_2\text{C=CH}_2\text{Br}` for the second part

**Comment by ww-openstax** [comment]
@lwtchu Is the double dash in your provided code em-dash-length?

**Comment by lwtchu** [comment]
@ww-openstax i've edited my comment above to include `＝`
