### ISSUE TITLE
Organic Chemistry - table class="unnumbered unstyled" // valign issues

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5095]
# Context
For `<table class="unnumbered unstyled">` default valign is middle and `<entry valign="top" align="left">` has no effect.

<img width="535" alt="image" src="https://user-images.githubusercontent.com/89537088/230163321-43d635eb-83a6-475f-b678-7645085a8f66.png">

# Acceptance Criteria
- [ ] valign is enabled for tables across this title (only OChem)
- [ ] should be similar functionality to align=left/right/center, etc
- [ ] add 0.7rem padding in cells
- [ ] at the very end - do you think this would be feasible to implement across the library? if so please let me know your thoughts or put on card

# Content
## Sample Mark-Up
```
<table class="unnumbered unstyled" summary="" id="table-00001">
    <title/>
    <tgroup cols="2">
    <colspec colnum="1" colname="c1"/>
    <colspec colnum="2" colname="c2"/>
    <tbody>
    <row valign="top">
    <entry valign="top" align="left"><emphasis effect="bold">Substrate</emphasis></entry>
    <entry valign="top" align="left">The best substrates yield the most stable carbocations. As a result, S<sub>N</sub>1 reactions are best for tertiary, allylic, and benzylic halides.</entry>
    </row>
    <row valign="top">
    <entry valign="top" align="left"><span class="red-text"><emphasis effect="bold">Leaving group</emphasis></span></entry>
    <entry valign="top" align="left">Good leaving groups increase the reaction rate by lowering the energy level of the transition state for carbocation formation.</entry>
    </row>
    <row>
    <entry valign="top" align="left"><span class="cyan-text"><emphasis effect="bold">Nucleophile</emphasis></span></entry>
    <entry valign="top" align="left">The nucleophile must be nonbasic to prevent a competitive elimination of HX (<link document="m00128">Section 11.7</link>), but otherwise does not affect the reaction rate. Neutral nucleophiles work well.</entry>
    </row>
    <row valign="top">
    <entry valign="top" align="left"><span class="green-text"><emphasis effect="bold">Solvent</emphasis></span></entry>
    <entry valign="top" align="left">Polar solvents stabilize the carbocation intermediate by solvation, thereby increasing the reaction rate.</entry>
    </row>
    </tbody>
    </tgroup>
    </table>
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 11 / Section 5; module m00126; lines 93 - 117
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-18 11-24-24](https://user-images.githubusercontent.com/47241114/232735397-047ee1a2-3b9a-4389-9002-4e8bf5218210.png)
![Screenshot from 2023-04-18 11-34-14](https://user-images.githubusercontent.com/47241114/232736131-1c982593-64ae-4063-9a87-b7a11030ce1c.png)
