### ISSUE TITLE
organic chemistry - toc bolding due to link changes - need to unbold

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5097]
# Brief Description of Scenario
![Screenshot 2023-04-11 at 9 55 44 AM](https://user-images.githubusercontent.com/11299125/231203206-eee0419b-4f60-4972-9ce3-970a7c2d993c.png)

# Pattern of Occurrence 
In the TOC the links to modules and EOC pages are bolded due to some of the link changes we did across the book. Could we unbold it please? 

# Acceptance Criteria
![Screenshot 2023-04-11 at 9 55 47 AM](https://user-images.githubusercontent.com/11299125/231203354-741cccf0-6386-4a5c-94db-5a4682f52fbd.png)
It should resemble Biology (ignore the units)  where the items in IBM Plex Sans are not bolded. 

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-organic-chemistry
- **collection slug:**  organic-chemistry
- **ref/branch:** main
- **chapter/section:**  TOC
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED

![Screenshot from 2023-04-14 16-39-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2ba47fbf-e77c-4158-97cb-b72429acd93c)

**Comment by MartaSztuka** [comment]
#### PASSED

![Screenshot from 2023-04-14 16-39-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2ba47fbf-e77c-4158-97cb-b72429acd93c)
