### ISSUE TITLE
Organic Chemistry - Justification in chapter titles results in bad breaks and awkward appearance 

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5102]
# Brief Description of Scenario
The justification settings of chapter titles results in some chapter titles having:
- bad break in TOC
- awkward appearance in chapter

![image](https://user-images.githubusercontent.com/89537088/233364809-3f8ce3eb-a778-4ea5-99e8-afc524e4b6ec.png)

# Pattern of Occurrence 

# Acceptance Criteria
- [ ] justified text should only be applied to the root/base text and not titles
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter titles
- **surrounding text:**

**Comment by ww-openstax** [comment]
@lwtchu Adding to this card that awkward appearance from justification also affects some section headings e.g. 7.11, 19.7
<img width="443" alt="image" src="https://user-images.githubusercontent.com/89537088/234339807-b00400d0-61ac-4b0c-ac0a-4caf6100c948.png">

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-26 10-43-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9c788eac-b61c-4941-8130-e316bb517144)
![Screenshot from 2023-04-26 10-43-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/57a5d626-57c2-4f34-84d5-982f038430c4)
![Screenshot from 2023-04-26 10-43-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fc8f27b4-e21a-4941-b39e-69d267c63535)
![Screenshot from 2023-04-26 10-44-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6c4076da-fd53-449f-a9ed-bafd3a85ee0d)

###### In section titles space is still too wide
![Screenshot from 2023-04-26 10-45-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9c0d1298-3118-4776-be29-ca0167f9b84f)

**Comment by wilkus27** [comment]
Problem with section titles will be fixed in another PR.
