### ISSUE TITLE
[BABBy] build books by repo, not book slug

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#5103]
## User story: 

As a builder of books through enki, I want to be able to run cross-library builds (BABBy) in less time. One way to increase speed of batch building with BABBy is by building books by repo instead of by book slug.

## Context: 

[link to recent issue which has made this possible](https://github.com/openstax/ce/issues/1971)

When Enki is called to build a book by its repo + book slug, it has to build all the books in the repo up to the last step because of intermodule linking; eg. it isn't functionally possible to build less than a whole repo of books. Since BABBy builds batches of books, it makes more sense to build by repo and not by slug (by slug -> processing over the repo is repeated for each book in the repo; by repo -> processing over the repo just happens once).

Note: A repo may have some slugs in the ABL and some slugs that are not yet approved. This change will mean that if a repo has any slugs in the ABL, all of its books, approved or unapproved, will be built. (However, this behavior already happens anyway because of how enki handles intermodule linking.)

## Acceptance Criteria:

- [x] `update_books` adds repo names without slugs to `AUTO_books.txt`
- [x] `run_enki_on_all` only expects to read a repo name, not a slug, from `AUTO_books.txt`
- [x] logging from `run_enki_on_all` lists the book slugs as the repos are built
- [x] successes and failures are logged on a per-repo basis

**Comment by kswanson33** [comment]
When one book in the repo fails, the whole repo fails to build. This is regardless of whether slug is provided or not (i.e. if calc vol2 is broken but calc 1&3 are fine, enki won't be able to build vol1 even if it's been given the slug for vol1).

I've updated the AC to change error logging to a per-repo basis, not per slug.

**Comment by kswanson33** [comment]
For testing: this is all under-the-hood optimizations for speed :zap:

**Comment by Stackblocks** [comment]
Appears to be working fine!

![CleanShot 2023-05-24 at 11.23.07@2x.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4a289614-52fa-471a-8b25-adfcc961eead)
