### ISSUE TITLE
[BABBy] add an optional --data-dir argument to run_enki_on_all

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#5104]
## User Story

As a QA analyst, I want to be supported in comparing batches of the same books built with different versions of the content/pipeline.

## New Specifications

Currently, `run_enki_on_all` writes books to `/data/<slug>-<command>` by default. This change would allow users to optionally specify a different parent directory, eg. providing `--data-dir /data/v1` would prompt enki to write all books to `/data/v1/<slug>-<command>`. 

This will support QA analysts in keeping track of different builds.

## Acceptance Criteria

- [ ] `run_enki_on_all` can be optionally told which parent directory to write books to
- [ ] without this argument provided, `run_enki_on_all` writes books to `/data`

**Comment by Stackblocks** [comment]
Looking good!

![CleanShot 2023-05-01 at 17.47.55@2x.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3a37ef3f-98e2-4496-b245-3c6a69aa4661)

![CleanShot 2023-05-01 at 17.49.21@2x.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/182ab30f-8314-4f53-8df7-2bd8cad370be)
