### ISSUE TITLE
college success high school - student story feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5107]
- Documentation #2737
- color option 2
- Class: `<note class="student-story">`
- title: Student Story
- icon - [cardboard-conversation.svg](https://drive.google.com/file/d/1hopWxNQi1hfZSXmyf-hyXsTA7WzbtOHv/view?usp=sharing) new!
- contains text, no subtitle and is in the introduction

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-05-17 15-50-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/85841a58-9904-4518-930e-e58d127356a9)
