### ISSUE TITLE
college success / college success high school - high school feature suppression

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5109]
Suppress the following classes (similar to technique used for `class="coreq-skills"` in the precalculus recipe;) for the `college-success` recipe 

- [ ] Student Story `student-story`  (note)
- [ ] Real Deal `real-deal` (note)
- [ ] Family & Friends Matter `family-friends`  (section)
- [ ] Checking In: Your College Readiness Checklist `checking-in` (section)

Make sure to check numbering.

Check w/ college-success-concise and college-success-high-school to make sure things are falling ok and maybe to compare the two
 Content like this in the REGULAR college-success book should be missing
![image](https://github.com/openstax/cnx-recipes/assets/11299125/c12b7a5f-9dbc-46e5-aae9-2fc961a810f1)

**Comment by MartaSztuka** [comment]
#### PASSED
##### College Success High School
###### Student Story
![Screenshot from 2023-05-31 15-44-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3c3121d3-0408-40c5-811f-baac690c5e48)

###### Real Deal
![Screenshot from 2023-05-31 15-46-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4b6b8b0a-5808-43e9-aeb6-9d4367d83a17)

###### Family & Friends Matter
![Screenshot from 2023-05-31 15-47-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/55073dcc-b84c-4d9f-9f4c-033b5844de89)

###### Checking In
![Screenshot from 2023-05-31 15-48-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cb3b8664-ab39-42b5-89d2-0ceed00dbf3f)

##### College Success - notes from College Success High School are missing here
![Screenshot from 2023-05-31 15-51-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e4453390-e5fa-483b-a6a3-cc3b68c329c4)
