### ISSUE TITLE
Organic Chemistry - Column rule separator not appearing for entry morerows=1

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5112]
# Brief Description of Scenario
column rule separator is not appearing:
- for a table with two consecutive cells of "morerows", 
- second cell contains no content

![image](https://user-images.githubusercontent.com/89537088/234341460-9482370e-d16d-4659-b7b1-79b2a90ebaf2.png)

# Pattern of Occurrence 

# Acceptance Criteria
- the content looks right to me - is there a way to make sure the line appears when there's a more row. 
  
# Sample Mark-Up
```
      <row valign="top">
      <entry valign="top" align="left" morerows="1">Aromatic ring</entry>
      <entry valign="top" align="left" morerows="1"> </entry>
      <entry valign="top" align="center">1660–2000</entry>
      <entry valign="top" align="left">Weak</entry>
      </row>
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 12 / Section 7 / Table 12.1 / Module m00141 / lines 84 - 89
- **surrounding text:**

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `jovial.jinology` & content from `organic-chemistry`

![CleanShot 2023-05-16 at 14.19.12.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d697c083-adad-41b7-9604-4302a4ef4871)
