### ISSUE TITLE
Organic Chemistry - Formatting of running heads does not match formatting of section titles

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5113]
# Brief Description of Scenario
The formatting applied to section titles like `<sup>` and `<emphasis>` is not outputting in running heads

![image](https://user-images.githubusercontent.com/89537088/234347822-453b3e2d-864c-4f0f-b79d-2bab2d38b2e2.png)

# Pattern of Occurrence 
every instance

# Acceptance Criteria
- please make sure super/sub scripts and italics are enabled in the running head/folio
  
# Sample Mark-Up
```
<title><emphasis effect="italics">sp</emphasis><sup>3</sup> Hybrid Orbitals and the Structure of Methane</title>
  <metadata xmlns:md="http://cnx.rice.edu/mdml">
    <md:title>sp3 Hybrid Orbitals and the Structure of Methane</md:title>
    <md:content-id>m00163</md:content-id>
    <md:uuid>22d6666a-d39e-4c15-8190-5adc7844867a</md:uuid>
  </metadata>
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 1 / Section 6 / and all section titles with formatting
- **surrounding text:**

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `jovial.jinology` & content from `organic-chemistry`. 

![CleanShot 2023-05-16 at 14.22.13.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/94ad0a85-d906-47bb-a937-8e2dbc3a3006)
