### ISSUE TITLE
Organic Chemistry - Links to Appendix not outputting correctly

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5115]
# Brief Description of Scenario
Based on info in issue #4965 links to appendix should output as: Appendix D
See screenshot for current output

![image](https://user-images.githubusercontent.com/89537088/234693878-585896f4-5706-48a3-8d4e-4a98336501f8.png)

# Pattern of Occurrence 
every instance

# Acceptance Criteria
- [ ] i think this might've gotten overridden by old link change to `Section #.#` but for links to `document class="appendix"` files, can we please put in `Appendix #` as the anchor text? 
  
# Sample Mark-Up
```
Atomic weights of all elements are given in the periodic table in <link document="m00228"/>.</para>
    </content>
</document>
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 1 / section 1 / Module m00158 line 18
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-05-09 10-02-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3598fe2a-6051-49d9-840b-50ac91f49cb5)
