### ISSUE TITLE
nursing-internal - table designs lost their lines

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5117]
# Brief Description of Scenario
![Screenshot 2023-04-26 at 4 53 38 PM](https://user-images.githubusercontent.com/11299125/234711591-32442998-2f38-4684-be3b-0bf904623ccd.png)

# Pattern of Occurrence 
All the tables

# Acceptance Criteria
- [ ] ideally we restore the work done in natalia's pr here: https://github.com/openstax/ce-styles/pull/203 
- [ ] lists and stuff are contained within tables
- [ ] lines are there
  

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-internal-bundle
- **collection slug:** nursing-test
- **ref/branch:** testcontent

**Comment by jbwilson8** [comment]
@lwtchu As mentioned earlier the table styling is fixed, however the paragraph ("Hand in hand with finding causation...") and Table 1.2 are not positioned inside of the "LIFE-STAGE AND CULTURAL CONTEXT" note. This causes the bottom border to appear out of place.  (See screenshots) 


<img width="1722" alt="Screenshot 2023-05-08 at 1 33 14 PM" src="https://user-images.githubusercontent.com/26155528/236904195-44f9f107-e5ab-464e-b0fb-4acae49a07af.png">


<img width="1216" alt="Screenshot 2023-05-08 at 1 34 22 PM" src="https://user-images.githubusercontent.com/26155528/236904199-c393daa3-2cbc-4bd4-b67e-215a78699919.png">

**Comment by lwtchu** [comment]
Note - content should have one table in the note and one outside to make sure they look the same in both instances (in note, outside note)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-05-10 15-35-15](https://github.com/openstax/cnx-recipes/assets/47241114/9a3f0dfc-1c94-4b1f-b22b-0374179e5565)

![Screenshot from 2023-05-10 15-35-32](https://github.com/openstax/cnx-recipes/assets/47241114/53fa01c9-02eb-497c-8b93-22ed07f93dea)
