### ISSUE TITLE
nursing-internal - support centered-text class on para

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5119]
# Brief Description of Scenario
We did similar for #5084 and think it'll be a good idea to implement centered-text the same way as it'll make semantic sense.

# Acceptance Criteria
- [ ] `<para class="centered-text">` will center text
- [ ] eventually this should impact the whole library - see if there's a way to add centered and indented text into the whole library
  
# Sample Mark-Up
```
<para class="centered-text">This whole line should be centered.</para>
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-internal-bundle/tree/testcontent
- **collection slug:** nursing-test
- **ref/branch:** testcontent
- **commit with content change:** https://github.com/openstax/osbooks-nursing-internal-bundle/commit/703ec57cbb739fbb9574414eb322d81bd29642e7

**Comment by Stackblocks** [comment]
Looking OK with content from nursing internal and code from iconic.iconology

**Markup**
![CleanShot 2023-04-28 at 15.10.24@2x.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/eefaad66-75d2-4220-845c-66ea2aec7821)

**PDF**
![CleanShot 2023-04-28 at 15.07.42.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/50cabeff-a90b-466e-8377-ec5bb70c80bb)
