### ISSUE TITLE
Organic Chemistry - Answer Key -- wrap answers so that a, b, and c are on the same line? 

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5120]
# Context
In the Answer Key, should the answers with distractors wrap in a similar way that distractors wrap in the main text?
From Production Meeting notes: 
"Revisit once all content is in -- this is a setting OpenStax can undo if needed. Need to determine how many pages this would save and also if this causes art crashing."
<img width="429" alt="image" src="https://user-images.githubusercontent.com/89537088/235522221-78c97485-d510-4c9b-9030-65025d188fdf.png">

# New specifications or link to documentation cards

## Impact 

# Acceptance Criteria
- [ ] we have the choice inline wrapping code in the exercises within the book content - can we add it to the answer key also?

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Answer Key
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-05-09 10-00-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/88568e82-6f44-45ff-966c-b4101aef5c74)
