### ISSUE TITLE
Organic Chemistry - Change output of Chemistry Matters section in TOC to include em dash with no spaces 

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5121]
# Brief Description of Scenario
In TOC, change output of Chemistry Matters section to include em dash with no spaces 

![image](https://user-images.githubusercontent.com/89537088/235527510-94eb04c0-3f17-47c7-82bd-0e12e5643230.png)

# Pattern of Occurrence 

# Acceptance Criteria
- [ ] the small dash is replaced with an `—` em dash with no spaces 

HTML codes 
```
&#8212;
&#x2014;
&mdash;
```
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** TOC 
- **surrounding text:**

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `jovial.jinology` & content from `organic-chemistry`

![CleanShot 2023-05-16 at 14.20.57.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8f52857c-63a0-42bf-99bc-475d686ac15b)
