### ISSUE TITLE
nursing-external - reduce spacing between end of book items in TOC

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5122]
# Brief Description of Scenario
<img width="544" alt="Screenshot 2023-05-02 at 10 39 19 AM" src="https://user-images.githubusercontent.com/11299125/235715610-d009c708-6df8-40d3-8735-39b5f11ab71f.png">

# Pattern of Occurrence 
table of contents

# Acceptance Criteria
- [ ] it's ok if this hits across theme
- [ ] can we remove the double spacing in the EOB TOC stuff (in the pink box above)
- [ ] we can keep the space between the last chapter content and the end of book stuff
  

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** nursing-external-combined
- **ref/branch:** design-chapters
- **chapter/section:** TOC
- **surrounding text:** Contents

**Comment by wilkus27** [comment]
### Information for tester
There is some problem with nursing-external. Styles shows up in baked html, but not in PDF. Devs are trying to figure out that.
Other books from Carnival theme can be tested.

**Comment by MartaSztuka** [comment]
##### nursing external (to be tested when baking problem is solved)

##### fizyka 1
![Screenshot from 2023-05-17 10-15-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/facbf474-6fb6-408e-bb45-4a3923adee97)
![Screenshot from 2023-05-17 10-51-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/718b3e40-6ecf-4230-968b-81d12211ad63)

##### anatomy and physiology
![Screenshot from 2023-05-17 10-18-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1d0d7f28-632b-4360-a8a6-6cdfd14aeb7e)

##### microbiology
![Screenshot from 2023-05-17 10-37-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e57aed2a-5651-450f-8f26-c27f2a0219b6)

##### pharmacology
![Screenshot from 2023-05-17 10-46-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d80fe67c-956f-4773-958d-02a62292468f)

##### nutrition
![Screenshot from 2023-05-17 10-47-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3f883d82-98b3-480d-b366-829839b16ca7)

##### university physics 2
![Screenshot from 2023-05-17 11-13-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2a5dadb0-c662-4a49-afd8-d4224994523b)
