### ISSUE TITLE
Preparing for College Success - Figure/Caption support for preface

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#5124]
# Brief Description of Scenario
The Academic Integrity feature includes a figure with a caption that is currently not supported, causing no figure text and the caption rendering above the image. 

![Screenshot 2023-05-08 at 10.10.55 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/23efbfcf-4580-40f9-ad15-3a4b7a7a56ad)

# Pattern of Occurrence 
Preface

# Acceptance Criteria
The image in the preface should support figure and caption. 
Is this possible to enable in most of the books? 
  
# Sample Mark-Up
```
<figure id="fig-00001">
    <media alt="A graphic divides nine items into three categories. The items &quot;Your Original Work&quot; and &quot;Quoting &amp; Crediting Another's Work&quot; are in the &quot;Approved&quot; category. The items &quot;Checking Your Answers Online&quot;, &quot;Group Work&quot;, &quot;Reusing Past Original Work&quot;, and &quot;Sharing Answers&quot; are in the &quot;Ask Instructor&quot; category. The items &quot;Getting Others to Do Your Work&quot;, &quot;Posting Questions &amp; Answers&quot;, &quot;Plagiarizing Work&quot;, and &quot;Artificial Intelligence, Chatbot Apps&quot; are in the &quot;Not Approved&quot; Category.">
        <image mime-type="png" src="../../media/AcademicIntegritySliderv2-1-column.png"/>
    </media>
    <caption>attribution: Copyright Rice University, OpenStax, under CC BY 4.0 license</caption>
</figure>
```

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-college-success-bundle
- **collection slug:** preparing-for-college-success
- **ref/branch:** main
- **chapter/section:** preface
- **surrounding text:** attribution: Copyright Rice University, OpenStax, under CC BY 4.0 license

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-06-07 10-47-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dd721695-aeaa-4819-873b-a81e3875951d)
