### ISSUE TITLE
nursing-external - tables in notes to be max 75% width of the space

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5130]
![Screenshot 2023-05-11 at 10 11 50 AM](https://github.com/openstax/cnx-recipes/assets/11299125/6cdfa93a-81ed-4f8f-9f2e-b3eeb2879744)

With the various lines, it's confusing as to where the feature ends. Could tables take up 80% or 75% of the feature box width?

## Acceptance Criteria
- [ ] table is smaller in width by a ##% in feature boxes

**Comment by MartaSztuka** [comment]
##### @lwtchu Table would look nicer if we align text to the top, or put bold text in table head, what you think?
![Screenshot from 2023-05-22 16-54-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1758cc7d-dd0e-4a35-b7f6-b05ef40a9fc6)

![Screenshot from 2023-05-22 16-49-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0cd38bc8-acb1-4744-893b-7b81fc0dbed3)

**Comment by lwtchu** [comment]
@MartaSztuka yeah - we can look into that when i have time to adjust the tables in the content but we can pass the issue if it's 75% width of the feature
