### ISSUE TITLE
carnival theme and cosmos theme - reduce padding in iconned notes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5131]
![Screenshot 2023-05-11 at 3 06 52 PM](https://github.com/openstax/cnx-recipes/assets/11299125/822226c2-7d3e-4461-9e6c-8731dc53cc25)

This padding in the pink box is a tad too big and thus confusing at times as to when the feature ends.

Can we reduce the padding by half? Will this impact the iconned note shape in other themes? If not, we could maybe do this for the two nursing series?

**Comment by wilkus27** [comment]
@lwtchu We are using now new shape (icon boxed) in nursing external. This is a note from above:

![image](https://github.com/openstax/cnx-recipes/assets/40228854/f766c4b5-719c-4457-a204-c153a090ec2a)

Should I remove padding from new shape or new and old shape?

**Comment by lwtchu** [comment]
@wilkus27 ah sorry - is there a way to match the bottom padding with the top? it seems a little wider at the bottom

**Comment by wilkus27** [comment]
@lwtchu tables and lists yes, about images - for figures we are adding margin to caption, `[data-type="media"]` doesn't have any padding/margin

**Comment by lwtchu** [comment]
@wilkus27 would it be easier to add padding to media elements inside of notes? and then we can remove the padding from the bottom of  a note

**Comment by wilkus27** [comment]
@lwtchu Yes, that might be a faster fix :+1:

**Comment by MartaSztuka** [comment]
#### PASSED
##### nursing external
![Screenshot from 2023-06-05 16-58-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e98f9dc1-124a-4e28-8c61-9c1f5ea1871d)
![Screenshot from 2023-06-05 16-57-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/765a8e42-9baf-4296-ace3-0d946e059939)

##### anatomy
![Screenshot from 2023-06-05 17-31-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6e03fa50-6b78-47ff-ada4-da49458297d4)

##### fizyka 1
![Screenshot from 2023-06-05 17-32-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ad71b102-ab2a-4003-863c-8758f5a47ca7)

##### philosophy
![Screenshot from 2023-06-05 17-37-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ee1adaf5-b21a-4c64-a815-3ccaba7eb433)

##### sociology
![Screenshot from 2023-06-05 18-07-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/09c7153f-3e14-453f-a0b9-503523dd30f3)
