### ISSUE TITLE
nursing-external - table caption adjustments

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5132]
![Screenshot 2023-05-11 at 3 31 44 PM](https://github.com/openstax/cnx-recipes/assets/11299125/4277eca1-919a-4024-8f08-6d46c3bb53a8)

I think this was a copy over from when the ochem styles were copied over. But could we put the table number, caption and title back at the bottom of the table? 

Can we also adjust the leading in the caption? It does not match figure leading.
![Screenshot 2023-05-11 at 3 37 14 PM](https://github.com/openstax/cnx-recipes/assets/11299125/7fac0e41-441a-4a4c-94f4-46669b537f41)
![Screenshot 2023-05-11 at 3 37 19 PM](https://github.com/openstax/cnx-recipes/assets/11299125/0e11aac1-e254-4dd4-9141-83fe75c4fb39)
Two screenshots comparing table vs figure captions. Can we have this match the figure captions. I think we did it recently ...but I can't find the issue.

**Comment by Stackblocks** [comment]
Captions have been shifted to the bottom, the letting has been adjusted, and caption title color has been fixed.

![CleanShot 2023-05-17 at 09.49.13.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/163c149d-4627-4c7d-9311-29262f21cb94)
---
![CleanShot 2023-05-17 at 09.49.30.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7fd529f9-cc39-4edc-9865-11e45a11c1f3)
