### ISSUE TITLE
nursing-external - set review questions and suggested reading to two columns

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5133]
# Brief Description of Scenario
![Screenshot 2023-05-12 at 9 39 31 AM](https://github.com/openstax/cnx-recipes/assets/11299125/60089738-1b48-4245-9c0b-417c79dc2817)
![Screenshot 2023-05-12 at 9 39 40 AM](https://github.com/openstax/cnx-recipes/assets/11299125/fcb5f6d6-3890-4612-931b-d0c7ab30edd3)

# Acceptance Criteria
- [ ] suggested reading and review questions are in two columns (the other two EOC sections are in two columns)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-05-19 09-46-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/24716d4c-cf54-4195-935a-d40d882d213b)

![Screenshot from 2023-05-19 09-47-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d304780d-ae2f-49ac-86cc-67d501e1b316)
