### ISSUE TITLE
Concepts of Biology chapter outline box

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5135]
# Brief Description of Scenario
It looks bad
<img width="734" alt="Screenshot 2023-05-12 at 3 38 21 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/6a4e6dfc-db55-4e3b-ac19-e0200b58c6de">

# Pattern of Occurrence 
everywhere

# Acceptance Criteria
- [ ] it's time to retire this shape- can we set it to version 2 https://github.com/openstax/cnx-recipes/issues/1076
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:**  osbooks-biology-bundle
- **collection slug:** concepts-of-biology
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-06-07 10-38-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b4ed4686-1f73-444f-9a1c-cbd218bf6836)
