### ISSUE TITLE
organic chemistry - webview fix for formatting of running heads

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5138]
# Brief Description of Scenario
Extra text was introduced in #5113 - we should suppress it in webview 
![image](https://github.com/openstax/cnx-recipes/assets/11299125/3dc5c41c-11f6-4529-8e7f-00da9b21f7a0)
![image](https://github.com/openstax/cnx-recipes/assets/11299125/3a7cb580-499a-43f1-82b1-9f4fb2f426a1)

# Pattern of Occurrence 
Only in Organic Chemistry

# Acceptance Criteria
- [ ] the above text is suppressed in WEBVIEW
  
# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 1 / Section 6 / and all section titles with formatting
- **surrounding text:**

**Comment by ww-openstax** [comment]
@lwtchu additionally errata text is showing up and the beginning of each section in webview

![image](https://github.com/openstax/cnx-recipes/assets/89537088/b1f663bb-a905-4077-ac42-0f66f3c80bf2)

**Comment by lwtchu** [comment]
@ww-openstax no this is what the card is fixing - we needed that so that the folio could capture `<sup> <sub>` tagging

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-05-31 10-03-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/37f0b53a-acd1-4832-9958-5b3d25231f79)
![Screenshot from 2023-05-31 10-04-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9ad24ab5-6f8b-4136-a166-1ebe5c718dcd)
