### ISSUE TITLE
Organic Chemistry -- Index - set alignment in the index to be left-aligned in the columns

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5140]
# Brief Description of Scenario
Set alignment in the index to be left-aligned in the columns. See screenshot for a good example of the output being confusing for students
![image](https://github.com/openstax/cnx-recipes/assets/89537088/a11bc3bd-c483-4276-98a1-fe81f926e82e)

# Pattern of Occurrence 

# Acceptance Criteria
- [ ] remove justify text alignment in the index
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Index
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-05-25 16-13-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/40fa810e-6683-4162-be0d-b2b7b64974f3)
