### ISSUE TITLE
high school physics - mathspace issues in injected exercises

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5142]
# Brief Description of Scenario
![Screenshot 2023-05-19 at 9 04 30 AM](https://github.com/openstax/cnx-recipes/assets/11299125/49623949-3319-4286-8fa4-838e4e2e7107)
![Screenshot 2023-05-19 at 9 05 08 AM](https://github.com/openstax/cnx-recipes/assets/11299125/6b47f2de-9e15-47cf-be12-138f961062b4)

The circled areas should be a list (a b c d) cause it's a multiple-choice question.

I have a sneaking suspicion that it's impacting math ? maybe in webview https://openstax.slack.com/archives/CH5514N57/p1684443210700909  but would be good to fix this and then test again

# Pattern of Occurrence 
Only injected exercises. 

# Acceptance Criteria
- [ ] injected exercises are baked and styled
  
# Sample Mark-Up
```
<exercise id="fs-id1167065016153" class="os-exercise">
<problem id="fs-id1167066170448">
<para id="fs-id1167064896029">
<link class="os-embed" url="#ost/api/ex/k12phys-ch16-ex018"/>
</para>
</problem>
</exercise>
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-physics
- **collection slug:** physics
- **ref/branch:** main
- **chapter/section:** 8.3, 16.1 (and others) 
- **surrounding text:** see above

**Comment by wilkus27** [comment]
There is something wrong with math. Previously it was generated into spans with `data-math` attribute:

![image](https://github.com/openstax/cnx-recipes/assets/40228854/2ad2bc36-427d-40fa-a921-85bedf714035)

Now it shows up in `<math>` tag:

![image](https://github.com/openstax/cnx-recipes/assets/40228854/5842f050-1466-4d91-ae23-74c7239b0a97)

And for some reason operations that we are using in Ruby to bake exercises, like cutting and pasting, are moving namespace from `<math>` tag into its parent. If parent contains only math it looks ok, but if there is also a text or other elements, then it breaks.

**baked file**
![image](https://github.com/openstax/cnx-recipes/assets/40228854/f4105985-bbb1-4441-882d-3670cc01394f)

**PDF**
![image](https://github.com/openstax/cnx-recipes/assets/40228854/54951d67-3974-4d1a-b958-0737b0ab526b)

**assembled file**
![image](https://github.com/openstax/cnx-recipes/assets/40228854/2bdfd9d0-b253-44ce-aba9-f32457052c83)


(Screenshots are from Contemporary Math, section 5.2)

**Comment by lwtchu** [comment]
@wilkus27 do you have insight as to why the list isn't being styled :eyes: i double checked the math and...it's marked up the same as the contemporary math ones 🤔 i'll do a bit more snooping

**Comment by wilkus27** [comment]
### UPDATE
Thread with more informations: https://katalysteducation.slack.com/archives/C022NETP39N/p1685465891141629

#### Summary
ce-tech team is checking if conversion from TeX into MathMl form can be done after baking step, so it won't affect Ruby's methods that are used during baking.

**Comment by TylerZeroMaster** [comment]
Something in cookbook causes namespaces to be moved up the tree. Converting TeX math before baking caused cookbook to move the MathML namespace to the math element's parent. This caused lists to break because `ol` and `li` do not mean anything within the MathML namespace.

I made a [PR](https://github.com/openstax/enki/pull/269) to move the conversion from `prebake` into `postbake`.

**Comment by philschatz** [comment]
It sounds like this is a bug in cookbook... has that been looked into? I'm worried that moving the conversion to later would just make it harder to find the cookbook bug when it crops up later

**Comment by wilkus27** [comment]
### Information for tester

Please test all kinds of namespaces that appears within books.

- math elements with namespace prefix (`<m:math/>`) **hs-physics**
- math elements without namespaces prefix (`<math xmlns=http://www.w3.org/1998/Math/MathML">`) **hs-physics**
- footnotes (`<a href="#foo" role="doc-noteref" epub:type="noteref">`, `<aside role="doc-footnote" epub:type="footnote" id="foo">`) **accounting**
- terms from Index and Key Terms (`<dt xmlns:cmlnle="http://katalysteducation.org/cmlnle/1.0" cmlnle:reference="something">`, `<span xmlns:cxlxt="http://katalysteducation.org/cxlxt/1.0" data-type="term" cxlxt:index="foreign">`) **pl-psychology**

**Comment by MartaSztuka** [comment]
#### PASSED
##### Physics
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/e43b3ff4-80d6-497a-a7f6-c82b842d395b)

![Image](https://github.com/openstax/cnx-recipes/assets/47241114/9c15bc7e-15d1-4f46-b9c6-802b3658afa9)

##### Accounting
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/fa3cc9ec-f3c6-43a1-8b51-eb7bf47120f5)

![Image](https://github.com/openstax/cnx-recipes/assets/47241114/2a2b4d07-739f-46d4-9930-e4b4fd0f6c9a)

![Image](https://github.com/openstax/cnx-recipes/assets/47241114/07fae91d-2bd1-4637-983b-b227c6832860)

##### Psychologia
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/d756aa3f-1f4a-4b7f-896a-11cffb4c2b51)
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/7a6cf01e-5db1-4162-8ffa-832737ec785e)
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/963afeb9-5202-4970-b6cc-8b60340da217)
