### ISSUE TITLE
Organic Chemistry - table class="unnumbered unstyled" -- reduce padding between rows

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5143]
# Brief Description of Scenario
Related to #5095. For unstyled unnumbered tables reduce the amount of padding between rows. See screenshot.

![image](https://github.com/openstax/cnx-recipes/assets/89537088/61eaa4d3-4fec-41e2-a023-408cd0ea0a86)
 

# Pattern of Occurrence 

# Acceptance Criteria
- [ ] remove padding between rows - can i take a look at the table before it goes to QA just so i can make sure it looks right
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 11 / Section 3; module m00124; lines 227 - 251 --- Chapter 12 / Section 0; module m00134; lines 17 - 40
- **surrounding text:**

**Comment by wilkus27** [comment]
@lwtchu This is what it looks like:

### Current view

![image](https://github.com/openstax/cnx-recipes/assets/40228854/6909b06d-e955-46de-ad3a-99b67ad48536)

### With bottom padding removed from `<td>`

![image](https://github.com/openstax/cnx-recipes/assets/40228854/c5df27dd-9047-4533-aa17-0c92b299876c)

### With bottom and top paddings removed from `<td>`

![image](https://github.com/openstax/cnx-recipes/assets/40228854/e7c3d2c5-14bc-42f2-b036-8be24e80d36b)

Which version do we want to apply? Should it be done only for organic chemistry or is it ok if it affects Carnival theme?

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-05-31 15-57-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5757ee88-b232-470d-b54d-a18ee99a21de)

![Screenshot from 2023-05-31 15-58-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0f3295ba-9de9-4fa0-80f2-115dce80be0a)
