### ISSUE TITLE
Organic Chemistry - webview - Exercise Problems not displaying correctly 

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5144]
# Brief Description of Scenario
In webview, for Exercise Problems:

- "Problem-##" needs space after
- the way Problem # breaks to new line does not match PDF output
- distractor letters do not align with distractor text or distractor art
- EOC distractor letters are empty links

![image](https://github.com/openstax/cnx-recipes/assets/89537088/c044e4de-cbf6-49e9-9233-fb3d8e76a518)

# Pattern of Occurrence 
Every instance of Problems in WebView

# Acceptance Criteria
- [ ] remove the link style
- [ ] line break between problem and numbers
- [ ] distractors should align with art
- [ ] distractors should have bold styling
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** All Exercises
- **surrounding text:**

**Comment by ww-openstax** [comment]
@lwtchu WiseWire is reopening this issue because the Exercise problems are not displaying correctly
<img width="848" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/33aea86d-a41d-4b2c-ae8f-fd0dd3f8e747">

**Comment by lwtchu** [comment]
@ww-openstax I'll open another card based on these comments
