### ISSUE TITLE
Organic Chemistry - webview - colored text is not displaying as colored

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5145]
# Brief Description of Scenario
In webview, text coded with span color tags (i.e. `<span class="cyan-text">`) is not displaying as colored.

<img width="678" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/fbb60704-30d8-4c6c-b23e-3f85be5ce98f">
<img width="541" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/a91e45bf-8c9e-4e9e-8f20-536dce6b5575">

# Pattern of Occurrence 
every instance of colored text in webview

# Acceptance Criteria
- [ ] enable color text for the following classes - reuse the colors set in the PDF 
 ```
<span class="cyan-text">
<span class="magenta-text">
<span class="green-text">
<span class="gray-text">
<span class="red-text">
<span class="yellow-text">
<span class="purple-text">
```
  
# Sample Mark-Up
```
<para id="para-00005">Note also in <link target-id="fig-00003"/> that calculated charge distributions in molecules can be displayed visually with what are called <term id="term-00004">electrostatic potential maps</term>, which use color to indicate electron-rich (red; <emphasis effect="italics">δ</emphasis>–) and electron-poor (blue; <emphasis effect="italics">δ</emphasis>+) regions. In methanol, <span class="magenta-text">oxygen</span> carries a partial negative charge and is colored red, while the <span class="cyan-text">carbon</span> and <span class="cyan-text">hydrogen</span> atoms carry partial positive charges and are colored blue-green. In methyllithium, <span class="cyan-text">lithium</span> carries a partial positive charge (blue), while <span class="magenta-text">carbon</span> and the <span class="magenta-text">hydrogen</span> atoms carry partial negative charges (red). Electrostatic potential maps are useful because they show at a glance the electron-rich and electron-poor atoms in molecules. We’ll make frequent use of these maps throughout the text and will see many examples of how electronic structure correlates with chemical reactivity.</para>
```

# Location(s)
- **osbooks repo:**  osbooks-organic-chemistry
- **collection slug:**  organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 2 / Section 1 ; module m00018; line 34
- **surrounding text:**

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `legit.logology` & content from `main`

![CleanShot 2023-06-09 at 15.48.58.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/544df8a7-0f4c-4fe0-a8dd-c6474a3b076f)

![CleanShot 2023-06-09 at 15.43.19.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/facb7790-de94-427f-bb92-f5b276820ddb)

![CleanShot 2023-06-09 at 15.42.21.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/984a0f58-27af-412b-a830-3701f0cec6cb)
