### ISSUE TITLE
Organic Chemistry - Exercises Editor - HTML-coded MC questions - adjust output to top-align distractor letter

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5146]
# Brief Description of Scenario
In Exercises tool, for workaround of HTML-coding of MC questions: adjust output of html to top-align distractor letter 
The workaround affects the following Problems:
In-chapter: 2-9, 2-14, 4-11, 5-1, 5-13, 5-16, 5-17, 7-9, 9-9, 10-9 
End-of-chapter: 2-37, 2-56, 2-63, 5-26, 5-31, 6-36, 8-30, 8-52, 9-56
WiseWire will adjust this list to include IDs by 5/31 in comments below

![image](https://github.com/openstax/cnx-recipes/assets/89537088/5ae4090f-8648-412f-a8bb-92d274988e4b)

# Pattern of Occurrence 

# Acceptance Criteria
- [ ] is it possible to align text in paragraphs to the top of the image in paragraphs?
  
# Sample Mark-Up
```
<p>Which of the following structures represent meso compounds?</p>
<p><b>(a)</b><img class="scaled-down-30" src="https://exercises.openstax.org/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakVSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2ada88837bcb901ea75c61a429d16056debff03a/OChem_05_07_005a.jpg" alt="Alt Text Placeholder">
<b>(b)</b><img class="scaled-down-30" src="https://exercises.openstax.org/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaklSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--707d068a624667ffd268bb51cf46fe2172ffc2ec/OChem_05_07_005b.jpg" alt="Alt Text Placeholder">
<b>(c)</b><img class="scaled-down-30" src="https://exercises.openstax.org/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBak1SIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7061e73b0ce52bfd5f00bbb0e6468934958419c5/OChem_05_07_005c.jpg" alt="Alt Text Placeholder">
<b>(d)</b><img class="scaled-down-30" src="https://exercises.openstax.org/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalFSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--85eb5269d7fa91364fbc1b41cb63af4d10979eaf/OChem_05_07_005d.jpg" alt="Alt Text Placeholder"></p>
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Nickname: 05-07-OC-P16; ID: 36508
- **surrounding text:**

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `m.m` & content from `main`

![CleanShot 2023-06-20 at 13.51.14.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0c543402-0598-4d3d-9b55-9115024dbba9)
![CleanShot 2023-06-20 at 13.51.57.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b09bf845-6f36-4598-b5ca-f147561e3b50)

**Comment by Stackblocks** [comment]
Putting this back in CORGI testing, the regression is going to be fixed as part of https://github.com/openstax/cnx-recipes/issues/5167
