### ISSUE TITLE
Organic Chemistry - Appendix Glossary - Reduce indent

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5147]
# Brief Description of Scenario
Reduce Indent to align with heading "Glossary" in order to reduce wasted space

![image](https://github.com/openstax/cnx-recipes/assets/89537088/3e116cda-3d0a-4563-84fe-a7260d7df1cc)

# Pattern of Occurrence 

# Acceptance Criteria
- [ ] can the content within the section be flush with the margin on the left?
  
# Sample Mark-Up
```
<content class="appendix">
<section class="column-container" id="sect-00001">
<section id="sect-00002">
<list id="list-00001">
<item><emphasis effect="bold">Absolute configuration</emphasis> (<link document="m00054"/>): The exact three-dimensional structure of a chiral molecule. Absolute configurations are specified verbally by the Cahn–Ingold–Prelog <emphasis effect="italics">R</emphasis>,<emphasis effect="italics">S</emphasis> convention.</item>

</list>
</section>
</section>
</content>
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Appendix C Glossary
- **surrounding text:**

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `m.m` & content from `main`

![CleanShot 2023-06-20 at 13.55.08.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4f097943-0d4f-41ba-b566-94dcc3620457)
