### ISSUE TITLE
Introduction to Python Programming - Enable detailed resolution

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#5151]
# Brief Description of Scenario
We want detailed resolution information to display in the answer key in the PDF and Web.

Currently it's just the letter answers:
![Screenshot 2023-06-02 at 9.04.30 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/8a2d8d58-2d6d-438f-b1db-887f7920a37e)

# Pattern of Occurrence 
n/a

# Acceptance Criteria
- [ ] the answer will be the answer choice. period, the correct answer period and then the detailed answer
- [ ] For one of Colby's examples below:` a. reading. Whereas much digital content still teaches mostly through text and then use questions afterwards as a form of homework, quiz, or self-assessment, this textbook uses questions as a form of interactive reading – akin to having a dialogue between an instructor and learner. `
  
# Sample Mark-Up

## Some examples of exercises and their detailed answers:

Nickname: prog-py-001
Answer: A) reading
Detailed answer:
Whereas much digital content still teaches mostly through text and then use questions afterwards as a form of homework, quiz, or self-assessment, this textbook uses questions as a form of interactive reading – akin to having a dialogue between an instructor and learner. 

Nickname: prog-py-002
Answer: A) multiple choice
Detailed answer:
Multiple choice questions allow for distractors that capture common mistakes or misconceptions, and avoid issues around typing an answer. 

Nickname: prog-py-015
Answer: C) "I know you'll answer correctly!"
Detailed answer: 
Note that the enclosing single quotes (') are not part of the string but the double quotes (") are. 

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:** main is empty now, can use be710b9c719f6df71bb6db2e06f6324c8a12683f for testing
- **chapter/section:** 
- **surrounding text:** Answer Key

**Comment by lwtchu** [comment]
Note: we did something similar in https://github.com/openstax/cnx-recipes/issues/5151

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-07-07 10-15-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/35f013e4-7612-4caf-89c0-444e34afc68d)
![Screenshot from 2023-07-07 10-15-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e5d03a26-0942-40a1-8749-1c0f3714a323)
