### ISSUE TITLE
Organic Chemistry [does not affect chs1-12] - emphasis type=smallcaps not outputting small caps

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5152]
# Brief Description of Scenario
`<emphasis effect="smallcaps">` is not outputting small caps. Note: this issue does not affect chs1-12

![image](https://github.com/openstax/cnx-recipes/assets/89537088/a8932204-be54-45eb-87e3-3f7d61e49b6f)

# Pattern of Occurrence 
every instance

# Acceptance Criteria
- [ ] enable smallcaps use case - letters should still be uppercase and set to `font-scale(-1): 7.5pt, 9.6px, 0.8rem`
- [ ] please build in a way that applies to whole library this should be a standard offering
  
# Sample Mark-Up
```
<para id="para-00001">Soap has been in use for nearly 5000 years. As early as 2800 <emphasis effect="smallcaps">BC</emphasis>, the Babylonians boiled fats with ashes to create a soap-like substance. Ancient Egyptian medical papyri dating from 1550 <emphasis effect="smallcaps">BC</emphasis> reveals that Egyptians bathed regularly with soap made from a mixture of animal fats, vegetable oils, and alkaline salts. Chemically, soap is a mixture of the sodium or potassium salts of the long-chain fatty acids produced by hydrolysis (<term id="term-00001">saponification</term>) of animal fat with alkali. Wood ash was used as a source of alkali until the early 1800s, when the LeBlanc process for making Na<sub>2</sub>CO<sub>3</sub> by heating sodium sulfate with limestone became available.</para>
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 27 / Section 2; module00266 line 9
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-06-28 17-48-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f1742509-ae76-4366-abc2-3ed25571c064)

**Comment by wilkus27** [comment]
@lwtchu Sorry :sweat_smile: I totally misunderstood what it should be done here. New PR is ready :wink:

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-06-29 17-08-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fe381c08-5247-4531-90e9-790c3ff7de77)
