### ISSUE TITLE
preparing for college success (hs-college-success): change family and friends matter and checking in features to EOC sections

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5155]
# Context
#5126 #5125 - these are actually going to be EOC 

Can we move them into the EOC with this order
Family & Friends Matter `family-friends`
Summary (already in EOC)
Checking In: Your College Readiness Checklist `checking-in`

They won't be in every chapter. Make sure a header isn't generated if it's not in a chapter

# New specifications or link to documentation cards
- [ ] Friends & Family Matter will have the icon [cardboard-managegroup.svg](https://drive.google.com/file/d/169_IQ6DAi8qsAGZv152QHVtSerJIp1z_/view?usp=drive_link)
- [ ] Checking In: Your College Readiness Checklist Will have the icon [cardboard-multiplechoice.svg](https://drive.google.com/file/d/1Oz3Ej81o-JVLC75amloQ3m-YPDH-hoCN/view?usp=drive_link)
- [ ] Please change title of family-friends to `Friends & Family Matter`
- [ ] Title for the other section should remain `Checking In: Your College Readiness Checklist`

## Impact 
- just college-success for the suppression (if that needs work) and hs-college-success recipes

# Acceptance Criteria
- [ ] Please ensure that the sections are STILL suppressed in College Success
- [ ] these sections are moved to the EOC and in the correct order
- [ ] title for Family & Friends Matter changed to `Friends & Family Matter`
- [ ] title is `Checking In: Your College Readiness Checklist` for the other section
- [ ] icons show up
- [ ] if the section is not in a chapter, it shouldn't show up in the TOC or eoc wth a header

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-college-success-bundle
- **collection slug:** preparing-for-college-success
- **ref/branch:** main
- **Checkin In locations:** chapter 2.4, chapter 4.4, chapter 6.3, chapter 8.4 
- **Friends & Family Matter locations:** chapter 1.4, chapter 2.4, chapter 3.5, chapter 4.4, chapter 5.5, chapter 6.3, chapter 7.6, chapter 8.4, chapter 9.4

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `legit.logology` & content from `main`

![CleanShot 2023-06-14 at 11.24.44.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/683808df-dd63-473b-827f-34cfd679bf8c)

![CleanShot 2023-06-14 at 11.25.10.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/18178533-7bc1-43f9-a73c-9d40d944a964)

**Comment by openstaxalina** [comment]
@Stackblocks would you be able to provide additional screenshots that also include the Checking In feature in ToC and EOC? I would love to share with the authors who have inquired about how the final designs will look.

Thank you!

**Comment by Stackblocks** [comment]
@openstaxalina 

Sure thing! Here's a photo of `Checking In` in the ToC. 

There's a minor regression with image handling that is causing the icons in the EOC view to be over-large which is distorting the table, but as soon as we get that resolved i'll add a screenshot of the EOC view. 

![CleanShot 2023-06-14 at 12.51.04.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/380d0db4-ecb2-4d6f-a2cd-9ea1389c872d)

**Comment by openstaxalina** [comment]
excellent; thank you @Stackblocks ! sending to authors now
