### ISSUE TITLE
[devcontainers] Remove unnecessary Cookbook components

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#5156]
Remove components from `devcontainer.json` and `Dockerfile` that are not used anymore.

- [x]  `git` - we are not installing it in styles devcontainer and there are no noticeable differences in using it within these two devcontainers
- [x] `vim` - none of the developers is using it; the alternative for it is `nano`
- [x]  `openssh-server` - probably it was needed for different way of using devcontainers (https://code.visualstudio.com/docs/devcontainers/containers#_open-a-folder-on-a-remote-ssh-host-in-a-container) at the beginning of creating evnironment. We can try to remove it.
- [x]  `build-essential` - it contains the dependencies used to help out several packages on Debian-based systems (https://itslinuxfoss.com/build-essential-package-ubuntu-install/). We can try to remove it, but it's hard to predict what impact it'll have. Test it very carefully.
- [x] `wget` - we are using it only to install Live Share, which we are going to remove as well
- [x] `libicu-dev` - it was installed together with cnx-easybake which is not used anymore, so it might be a leftover. We can try to remove it, but it will be good to test it carefully.
- [x] `live share` - it was helpful at the beginning of creating environment, when new developers were introduced. It's not used anymore, beside that there are some problems with this tool. If we need similar features in the future, we will probably try different extension.

**Comment by LostMojo** [comment]
Removing build-essential causes kitchen codecov specs to fail, leaving it for now.

**Comment by Stackblocks** [comment]
Tested by @jbwilson8, no issues found.

[[Link to Slack discussion](https://openstax.slack.com/archives/C022NETP39N/p1693420942894539)]
