### ISSUE TITLE
[devcontainers] Add useful components to Cookbook Devcontainer

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#5159]
Add `shellcheck` to Cookbook Devcontainer. It's used in Styles.

More information: https://github.com/koalaman/shellcheck

**Comment by LostMojo** [comment]
Hm, running into problems trying to mimic the way ce-styles adds shellcheck. [Posted about it in ce-tech channel](https://openstax.slack.com/archives/C0LA54Q5C/p1693581363925749). Putting back for now.

**Comment by lwtchu** [comment]
Not very easy. Will put into milestone backlog.

**Comment by wilkus27** [comment]
### Information for developers

To be able to use it rebuild your devcontainer. 
To check whether it's working run `shellcheck shell_script_name` in your terminal. For example, `shellcheck bake`.

**Comment by wilkus27** [comment]
@jbwilson8 @kswanson33 since this is a change for devcontainer I'll asign you both for testing. Let me know if everything is working properly for you :wink:

**Comment by wilkus27** [comment]
Tested by all developers. Everything is fine :+1:
