### ISSUE TITLE
Introduction to Python Programming - coderunner feature does not display in webview

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5163]
# Brief Description of Scenario

Coderunner feature does not display in webview.
![Screen Shot 2023-06-15 at 1 42 46 PM](https://github.com/openstax/cnx-recipes/assets/89537088/03e20f01-33e3-4412-95e5-ccee297ba487)
![Screen Shot 2023-06-15 at 1 58 21 PM](https://github.com/openstax/cnx-recipes/assets/89537088/11d7926e-ed07-45a3-99e3-9faa6a97c375)

# Pattern of Occurrence 

# Acceptance Criteria

  
# Sample Mark-Up
```
<media alt="favorite_song_program">
    <iframe width="660" height="371.4" src="../../media/interactive/coderunner/ch1/CodeRunner_01_02_01_Favorite-song.html"/>
</media>
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** chapter01/section 01/m00002/lines 111-113
- **surrounding text:**

**Comment by openstaxalina** [comment]
@yblock could you please take a look at the markup here and see if anything is different from your test chapter?

**Comment by yblock** [comment]
It is different yes. previously we were linking to the externally hosted coderunner, and these are the first instances of trying it with our hosted version to my knowledge.

**Comment by openstaxalina** [comment]
We expect to have this resolved ~Monday and will update this card accordingly! cc @lwtchu @ww-openstax @yblock

**Comment by openstaxalina** [comment]
@ww-openstax this was resolved by @ne-newton 's team. please retest and close if this looks good on y'all's end now.
