### ISSUE TITLE
Organic Chemistry - Ch 18 "Preview of Carbonyl Chemistry" section - move output to end of chapter

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5164]
# Brief Description of Scenario
Adjust output of `<section class="preview-carbonylchemistry">...</section` so that "Preview of Carbonyl Chemistry" section outputs at the very end of the chapter, after the Ch 18 Additional Exercises section

<img width="386" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/d9e5a897-9d2c-4e68-bd1b-e4fda588eb0b">

# Pattern of Occurrence 

# Acceptance Criteria
- [ ] create a new EOC section for `Preview of Carbonyl Chemistry`
- [ ] it should go LAST (after Additional Problems)
- [ ] numbering for assessment should follow through
- [ ] when this goes  to testing please ping me so i can take a look also
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 18 / Section 8 / module 00255 / "Preview of Carbonyl Chemistry" section / line 443
- **surrounding text:**

**Comment by MartaSztuka** [comment]
Hi, @ww-openstax you wanted to take a look at it.
Header is black, unlike on the first picture but looks ok.
![Screenshot from 2023-07-10 11-24-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/daa42db0-6489-4092-847a-5fa6f65bf779)

**Comment by wilkus27** [comment]
@MartaSztuka There is a seperate card for that :wink:
