### ISSUE TITLE
Organic Chemistry - Ch 18 "Preview of Carbonyl Chemistry" section - H4 heading - remove space below

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5165]
# Brief Description of Scenario
For the H4 headings in the Ch 18 "Preview of Carbonyl Chemistry" section, remove space below heading

![image](https://github.com/openstax/cnx-recipes/assets/89537088/1c9e47dd-0805-4bc0-81fa-ad3941bde0a9)

# Pattern of Occurrence 
H4 headings in the Ch 18 "Preview of Carbonyl Chemistry" section

# Acceptance Criteria

  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 18 / Section 8 / module 00255 / "Preview of Carbonyl Chemistry" section / line 570
- **surrounding text:**

**Comment by lwtchu** [comment]
Closing this card since a lot of changes has happened to this section since then. We can reopen if needed.
