### ISSUE TITLE
organic chemistry & carnival theme - injected page break change

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5166]
# Brief Description of Scenario
#5161 result of this card -- need to change due to regressions and larger cases
avoiding a page break for injected exercise will cause too many issues across the library for books with injected exercises. best case is to focus on the `os-prefix` portion of organic chemistry so we can target that specific use case where we do not want special numbering to break across pages

# Pattern of Occurrence 
![Screenshot 2023-06-22 at 4 05 09 PM](https://github.com/openstax/cnx-recipes/assets/11299125/33415b20-373a-4ac2-b550-b4c28065c062)
this is a good place to check. i can also test this if needed

# Acceptance Criteria
- [x] undo the injected exercise `page-break-inside: avoid` that's applied to all injected exercises
- [x] ONLY target the `os-prefix` 
- [ ] sample fix (??) i don't think this works 100% 
```
.os-eos {
  > section.section-exercises [data-type="injected-exercise"] [data-type="os-prefix"] > span.os-label {
    break-after: avoid;
  }
}
```

# Location(s)
- **osbooks repo:*organic-chemistry* 
- **collection slug:*organic-chemistry*
- **ref/branch:*main*
- **chapter/section:*Chapter 3 EOC, Section 8.5* 
- **surrounding text:*See screenshots above*

**Comment by lwtchu** [comment]
@MartaSztuka @Stackblocks let me know if you need help testing this one! I basically search for "problem" and make sure they don't have too much white space before and they break and make sure it's not orphaned from the numbers

**Comment by LostMojo** [comment]
This change effects all books!

There's also a little weirdness in Organic Chemistry-- it looks like with this spacing, the section header is separated from the questions, but it's breaking in the problems where it's supposed to now!

![Screenshot 2023-06-26 at 4.24.03 PM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/74a4c137-55d3-428b-aa0f-91445453c7c7)

![Screenshot 2023-06-26 at 4.24.25 PM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/a175eeee-a52f-4980-a232-a5d0a08e738a)

**Comment by MartaSztuka** [comment]
@lwtchu  Some of the problems doesn't look right, here is a list of them and all instances I've found with pictures.

#### Problems:
- breaking between problem and number (ch. 3, 5, 6, 7, 8, 12, 13, 15, 16, 17, 18, 19, 20, 29)
- problems look weird (ch. 2, 8, 23, 25)
- breaking before problem (ch. 7, 19, 21)
- big space (ch. 1, 21)
- image it too wide (ch. 2)

#### Chapter 1 
##### 1. this one is breaking where it should
![Screenshot from 2023-06-28 11-19-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ec2081ae-25cb-4473-8b84-23779d1d7944)
##### 2. it's not supposed to break between problem and numbers![Screenshot from 2023-06-28 11-21-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3df5ce58-6b2e-4640-a5fb-ab2ff5895b4f)

#### Chapter 2
##### 1. there it bigger space and break before the figure
![Screenshot from 2023-06-28 11-15-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/93480754-4a4b-407c-be39-ffa8caea115a)

##### 2. this image it too wide (content issue probably)
![Screenshot from 2023-06-28 11-26-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e7d25495-555c-4eb7-93ea-f8ec26e4c78b)

#### Chapter 3
##### 1. breaking before a figure
![Screenshot from 2023-06-28 11-29-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a8f4c9d9-4cde-49f5-842e-42275697ee23)

##### 2. breaking between problem and number
![Screenshot from 2023-06-28 11-33-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0ac26376-3ad7-4d24-9eec-6ac64d216fb4)

#### Chapter 5
##### 1. breaking between problem and number
![Screenshot from 2023-06-28 11-35-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7abe7443-c8bd-4362-9a5b-76c0ab1ee177)

#### Chapter 6
##### 1. breaking between problem and number
![Screenshot from 2023-06-28 11-37-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/78fd5f69-a7c6-4fb0-8119-12a41196183f)

#### Chapter 7
##### 1. breaking before problem
![Screenshot from 2023-06-28 11-41-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d7733510-3e64-4d7c-99a8-8b01d9f3dd68)

##### 2. breaking between problem and number
![Screenshot from 2023-06-28 11-42-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2cd7639e-a88c-4d5e-9394-ad417bef9d31)

#### Chapter 8
##### 1. breaking between problem and number
![Screenshot from 2023-06-28 11-44-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4dc26552-9e65-44c6-96bc-8802efb346f6)

##### 2. this one just looks weird
![Screenshot from 2023-06-28 11-46-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c588860d-56f2-4fe8-a73a-55c77f100e0b)

#### Chapter 12
##### 1. breaking between problem and number
![Screenshot from 2023-06-28 11-49-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5b641d9e-4340-499d-b6fd-6e2e84981a73)

##### 2. breaking between problem and number
![Screenshot from 2023-06-28 11-51-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c9896fa3-b42e-48c5-9ef8-8a92da54ceae)

#### Chapter 13
##### 1. breaking between problem and number
![Screenshot from 2023-06-28 11-52-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a29dc97e-c8f1-46ac-8538-56b3e1093974)

##### 2. breaking between problem and number
![Screenshot from 2023-06-28 11-52-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f6612f4a-c544-41fa-ac71-aaef86aac1cc)

##### 3. breaking between problem and number
![Screenshot from 2023-06-28 11-53-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9b685c57-db32-408a-9f13-b2a87597c29d)

#### Chapter 15
##### 1. breaking between problem and number
![Screenshot from 2023-06-28 11-54-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/82a03d71-a887-471c-9ca9-466fc3d2e711)

#### Chapter 16
##### 1. breaking between problem and number
![Screenshot from 2023-06-28 11-56-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0e75b4da-ea4e-4036-9c97-1bc2dc7e893f)

##### 2. breaking between problem and number
![Screenshot from 2023-06-28 11-57-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5854fdd5-30c8-436c-a89e-f617fc61a085)

#### Chapter 17
##### 1. breaking between problem and number
![Screenshot from 2023-06-28 11-58-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2014572f-edec-40e6-bdb7-7057287dd74e)

##### 2. breaking between problem and number
![Screenshot from 2023-06-28 11-59-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ea8e5d16-1f49-495b-9682-f44adc903ebb)

#### Chapter 18
##### 1. breaking between problem and number
![Screenshot from 2023-06-28 12-00-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e03e0f8a-0ac4-4c4c-8a22-ff8e5e98fab2)

#### Chapter 19
##### 1. breaking between problem and number
![Screenshot from 2023-06-28 12-02-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e0dd38a4-e604-4bc1-9ff7-3ce961df8485)

##### 2. breaking before problem
![Screenshot from 2023-06-28 12-02-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b3339a39-2986-4a58-836e-a2a1329964f0)

#### Chapter 20
##### 1. breaking between problem and number
![Screenshot from 2023-06-28 12-03-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/aa65eaeb-af15-4d0c-b61e-a344c0e5df02)

##### 2. breaking between problem and number
![Screenshot from 2023-06-28 12-04-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/075b3713-3043-4b3e-b6c9-784fda0d7513)

#### Chapter 21
##### 1. big space (with figure it might be hard to fix)
![Screenshot from 2023-06-28 12-06-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/11d2ff29-eb69-4e78-8db5-aebef4598f9a)

##### 2. breaking before problem
![Screenshot from 2023-06-28 12-07-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bcf416cd-2785-4a2a-a840-7fec15733c8b)

#### Chapter 23
##### 1. there is break and numbering should be top aligned with figure
![Screenshot from 2023-06-28 12-10-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d48d7d40-1650-4c8d-9f47-d6e68abb98a3)

#### Chapter 25
##### 1. this problem looks wrong, like column overlap on one another
![Screenshot from 2023-06-28 12-14-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3a9773e2-5c82-43db-add9-afd19590d0ea)

#### Chapter 29
##### 1. breaking between problem and number
![Screenshot from 2023-06-28 12-16-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1463c593-59ab-4f98-a27d-b67affe1b896)

**Comment by Stackblocks** [comment]
- Displays mostly OK with updated code from `m.m` & content from `main` as of 2023-06-28

## Before
![cleanshot_2023-06-28_at_09.11.01.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/9e83badd-0e0a-474a-81f4-311cbfb5a002)
---
![cleanshot_2023-06-28_at_09.16.34.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/98242dab-4b66-40fe-88e9-cdb36993ca14)
---
## After
![CleanShot 2023-06-28 at 11.23.17.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0a17cc50-e308-423a-8212-f06f6d2f6926)
---

![CleanShot 2023-06-28 at 11.27.48.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8f24c0ab-bc71-40f7-9f9d-a14c94f1dea0)

## Other 'Problem' problems, possibly content related
- 1.14 seems split between one and two column display
![CleanShot 2023-06-28 at 09.10.18.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/21ea32c7-25dd-4108-bbda-d771b2db39de)
- 5.31 probably shouldn't be going over/under like this
![CleanShot 2023-06-28 at 09.14.43.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b1636eec-19a6-4cdb-bb56-3f48b732a31a)
- 1.56 may be fine, but having this break location feels weird
![CleanShot 2023-06-28 at 09.11.37.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/bac43e46-90b7-459c-8777-585d26280512)

**Comment by lwtchu** [comment]
@MartaSztuka i think some of the issues are resolved by alan's later test. 
@Stackblocks for 5.31 I'll look into making a content change 

the rest should be ok?
