### ISSUE TITLE
organic chemistry - top-align distractor letter regression

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5167]
# Brief Description of Scenario
Regression introduced here #5146. Table solution is overriding `<br>` tags within the injected exercise. 
A few examples:
![Screenshot 2023-06-22 at 4 18 55 PM](https://github.com/openstax/cnx-recipes/assets/11299125/3cfd5c30-db06-44ce-afa6-bbb362d069b4)
![Screenshot 2023-06-22 at 4 19 35 PM](https://github.com/openstax/cnx-recipes/assets/11299125/503903ca-3b2b-413d-b280-c9df6a0f87ae)
![Screenshot 2023-06-22 at 4 19 29 PM](https://github.com/openstax/cnx-recipes/assets/11299125/def35f3c-3029-490f-a760-3dd9b101a5e7)

# Pattern of Occurrence 
Whenever there is a `<br>`, it is ignored in an injected exercise.

# Acceptance Criteria
- [ ] need a new solution to align to top of the selectors in #5146 

Examples above should look like but with the images aligned to the top of the letter. 
![Screenshot 2023-06-22 at 4 22 26 PM](https://github.com/openstax/cnx-recipes/assets/11299125/4306109f-ecc5-4194-bb7d-c11339e6a733)
![Screenshot 2023-06-22 at 4 23 06 PM](https://github.com/openstax/cnx-recipes/assets/11299125/4ab2c821-e26a-4687-83d1-179fe1878a8c)
![Screenshot 2023-06-22 at 4 23 23 PM](https://github.com/openstax/cnx-recipes/assets/11299125/03e8bc7e-f638-410e-b387-36823cb30c3d)

IF there needs to be a mark up change, please let me know.

 

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry

**Comment by wilkus27** [comment]
### Information for tester

In my solution I change an alignment of images that are siblings of `<b>` elements within all types of exercises and their solutions. It affects all Carnival books, but such case appears probably only in Organic Chemistry.

**Comment by MartaSztuka** [comment]
#### PASSED
##### 1.
![Screenshot from 2023-06-28 15-46-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/eacb8ef5-27f0-487d-8427-ef8e7c4b9aa3)

##### 2.
![Screenshot from 2023-06-28 15-49-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a8d1c7c1-9965-4713-93db-a1bf2458a78a)

##### 3.
![Screenshot from 2023-06-28 15-53-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f9222404-9821-4e71-b2d5-228fe8058990)

**Comment by Stackblocks** [comment]
We may need to revisit this, it looks like the selectors are still bottom-aligned and floating at the top of the diagrams, rather than being aligned on the baseline with the images rising up like in the acceptance criteria.

![CleanShot 2023-07-18 at 13.41.04.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b7566a7e-1213-42a8-a788-1b500f7e9c9c)

![CleanShot 2023-07-18 at 13.39.35@2x.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e7d8e6a2-9039-43d8-b9e3-4940cba84da5)
