### ISSUE TITLE
Introduction to Python Programming - MC Questions: Placement of question mark after equation

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5168]
# Context
When a question ends with an equation, the question mark is being placed on its own line after the equation. This alignment could be confusing to a student. The question mark appears isolated from the question text.
![Screen Shot 2023-06-27 at 12 00 07 PM](https://github.com/openstax/cnx-recipes/assets/89537088/73a551e9-68e6-422a-9fe4-e5cf20a72138)

![Screen Shot 2023-06-27 at 11 38 58 AM](https://github.com/openstax/cnx-recipes/assets/89537088/afc7e9c8-52cb-43d2-a455-5c9f366c90fb)

# New specifications or link to documentation cards

## Impact 
Affects all questions coded similarly across book.

# Acceptance Criteria

# Content
## Sample Mark-Up
```
What is the value of <pre class="python">4 * 3 ** 2 + 1</pre>?
```

## Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** chapter01/section 01/ screenshot is exercise nickname: CPL-ch01-m05-p09
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax We've added some clarification on the tagging legend on lines 39 and 40. Please change inline code in the Exercises platform to have the tag  `<code>`

**Comment by ww-openstax** [comment]
@lwtchu Thanks! I've verified the fix to "CPL-ch01-m05-p09" and applied the same fix to other MC question stems in which we're depicting inline code.
