### ISSUE TITLE
nursing-internal - eoc subheader, rename and reorder eoc items

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5170]
# Brief Description of Scenario
![Screenshot 2023-06-28 at 2 25 07 PM](https://github.com/openstax/cnx-recipes/assets/11299125/d641bfb1-e02c-4149-80a9-d1aeb7fc28b6)
Request came to change the order of EOC sections and add a subheader like we have in Calculus and Contemporary Math
- please change the order of assessments to: Review Questions, Check Your Understanding Questions, Reflection Questions, Critical Thinking Questions About Case Studies, What Should the Nurse Do? Questions, Competency-Based Assessment
- please also remove the words "Questions" and "Assessments" and quotations from the titles of the various EOC sections so they read: Review, Check Your Understanding, Reflection, Critical Thinking about Case Studies, What Should the Nurse Do?, Competencies
- please also put the assessments above into an additional header called `Assessments`

# Acceptance Criteria
- [x] TOC EOC order reads: Summary, Key Terms, Assessments, References
- [x] Assessments in the EOC go in the following order: Review Questions, Check Your Understanding, Reflection, Critical Thinking About Case Studies, What Should the Nurse Do?, Competency-Based Assessment 
- [x] Review Questions now say `Review`
- [x] Check Your Understanding Questions now say `Check Your Understanding`
- [x] Reflection Questions now say `Reflection`
- [x] Critical-Thinking Questions about Case Studies now say `Critical Thinking about Case Studies`
- [x] Competency-Based Assessment now say `Competencies`
- [x] Reflection Questions now say `Reflection`
- [x] "What Should the Nurse Do?" Questions should now say `What Should the Nurse Do?`

 

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-internal-bundle
- **collection slug:** nursing-test
- **ref/branch:** testcontent

**Comment by MartaSztuka** [comment]
#### PASSED

![Screenshot from 2023-07-10 12-01-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dc74effc-9fe5-48a5-8be5-a42156a59068)
![Screenshot from 2023-07-10 12-03-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/75742a00-dc2b-4bc3-b451-09d38dc763e8)
![Screenshot from 2023-07-10 12-03-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cf589016-2937-4302-84da-4eb6e706b463)
![Screenshot from 2023-07-10 12-03-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ed6449c9-a58b-44c8-a90a-d25b101c69e5)
![Screenshot from 2023-07-10 12-03-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f550c956-536b-4e84-b4ef-d318ff8957b9)
