### ISSUE TITLE
nursing-internal - change LOs to a bulleted list

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5171]
# Brief Description of Scenario
![Screenshot 2023-06-29 at 9 15 53 AM](https://github.com/openstax/cnx-recipes/assets/11299125/e0767c7a-048a-4911-8d51-9d4d207731b5)

Please follow bulleted style from this documentation https://github.com/openstax/cnx-recipes/issues/1077 

# Pattern of Occurrence 
All learning objectives

# Acceptance Criteria
- [ ] numbers changed to colored bullets

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-internal-bundle
- **collection slug:** nursing-test
- **ref/branch:** testcontent
- **chapter/section:** learning objectives (beginning of every section)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-07-14 10-22-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8a184fe7-51e1-4f62-8169-1cb6838f85ba)
