### ISSUE TITLE
nursing-internal - feature design changes to iconned notes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5172]
# Brief Description of Scenario
Set the following class/features to #3966 style.

- [ ] Link to Learning `"link-to-learning"` - was condensed, please change icon to [carnival-linktolearningbig.svg](https://drive.google.com/file/d/1r5QuBGlwM9J454RcNjtEvswXk3In6q62/view?usp=drive_link) and keep the color color G1: `#78B042`
- [ ] `cultural-context` - KEEP style and icon and color, change title to CULTURAL CONTEXT
- [ ] **NEW FEATURE** `lifestage-context` - COPY the `cultural-context` feature (same color/icon) and set the title to Life-Stage Context
- [ ] **NEW COLOR & ICON** Patient Conversations `patient-conversations` - same shape, different color [carnival-conversation.svg](https://drive.google.com/file/d/1TUk51g_O1BKmosg10igBqe4PhpkkZ6Y-/view?usp=drive_link) same icon as before but different color -- change feature to Y2: `#DCB83D`
- [ ] **NEW ICON** Legal and Ethical Issues `legal-ethical` - same shape, different color [carnival-homestaticimbalancebrown.svg](https://drive.google.com/file/d/1Ch1_fyThrnIUyOmwnhb_DJQzsQ-jQpaA/view?usp=drive_link) same icon as before but different color -- change feature to BR1: `#B05E36 `
- [ ] **NEW ICON** Pyschosocial Considerations `psychosocial-considerations` - was a boxed feature, please change to iconned with [carnival-brain.svg](https://drive.google.com/file/d/1b_k8pdtN7ZZW0k12es7sXMJYM54W9hmr/view?usp=drive_link) - set to color R3: `#E00087`
- [ ] **NEW COLOR & ICON** Read the Electronic Health Record `electronic-hr` - was a boxed feature, please change to iconned with [carnival-healthrecord.svg](https://drive.google.com/file/d/1bnv9dHizvxo7VJA2EK-lyohdKmls0aJX/view?usp=drive_link) and set color to B2: `#0074BC`

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-internal-bundle
- **collection slug:** nursing-test
- **ref/branch:** testcontent

**Comment by MartaSztuka** [comment]
#### PASSED
##### LINK TO LEARNING
![Screenshot from 2023-07-14 10-33-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6829ee4a-a8e6-4946-8170-32130de291f5)

##### LIFE-STAGE AND CULTURAL CONTEXT
![Screenshot from 2023-07-14 10-35-47.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d18b9590-2fb2-4e4b-bff2-228acaa920fc)

##### PATIENT CONVERSATIONS
![Screenshot from 2023-07-14 10-38-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e366e016-355e-47fc-ace2-257bd1f5d284)

##### LEGAL AND ETHICAL ISSUES
![Screenshot from 2023-07-14 10-39-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/28b8f08d-cbe0-44a5-810d-1347b09d81fe)

##### PSYCHOSOCIAL CONSIDERATIONS
![Screenshot from 2023-07-14 10-40-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9cde626c-63af-4c55-9edf-c8d8a616c79c)

##### READ THE ELECTRONIC HEALTH RECORD
![Screenshot from 2023-07-14 10-41-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cd443435-463c-4a32-89ee-e64a35ecc66a)
