### ISSUE TITLE
nursing-internal - feature design change for unfolding case study to boxed notes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5173]
# Brief Description of Scenario
Set the following class/features to #4746 style.

- [ ] Unfolding Case Study `unfolding-casestudy` - was an iconned note please set to boxed with color Y1: `#8F7200`

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-internal-bundle
- **collection slug:** nursing-test
- **ref/branch:** testcontent

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-07-14 11-31-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5ed4433a-f7c7-4643-90c0-9033dd5b4ca0)
