### ISSUE TITLE
nursing-internal - remove two column formatting for key terms and summaries

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5174]
# Brief Description of Scenario

![Screenshot 2023-06-29 at 2 44 09 PM](https://github.com/openstax/cnx-recipes/assets/11299125/e90bd49e-2b16-4743-aec2-20e0a595fb23)
Please remove the two column treatment in the Key Terms and Summaries EOC sections

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-internal-bundle
- **collection slug:** nursing-test
- **ref/branch:** testcontent

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-07-14 10-24-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1eb4a04b-c1b6-4de0-90fa-ce186c413387)
![Screenshot from 2023-07-14 10-24-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dbc57049-fb1e-4fa0-b050-dfd814c9fe20)
