### ISSUE TITLE
organic chemistry - "preview of a carbonyl" section with h5 and h6

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5177]
![Screenshot 2023-07-10 at 9 06 09 AM](https://github.com/openstax/cnx-recipes/assets/11299125/63a8770b-6603-4fb3-8b08-9aaa234072e3)

# Brief Description of Scenario
Related to #5164 - Could we potentially bump up the headers in this EOC (it's standalone and should be okay) so that we don't have to style these h6's(?) 

# Pattern of Occurrence 
Only in this section `class="preview-carbonylchemistry"`

# Acceptance Criteria
- [ ] header titled Nucleophilic Addition Reactions of Aldehydes and Ketones (Chapter 19) is styled with a IBM plx sans title
- [ ] headers are all bumped up one in this specific EOC section
  

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:** main
- **chapter/section:** chapter 18 - section should be tagged as preview-carbonylchemistry 
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-07-14 11-24-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/70ea308a-3e9d-4cda-956e-3d3b93583b8a)

![Screenshot from 2023-07-14 11-29-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6c9691fe-cb74-4f5d-b885-31b5e95547c4)

![Screenshot from 2023-07-14 11-28-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/69fbc48f-5a92-4583-aeda-b09ee63d1107)

![Screenshot from 2023-07-14 11-29-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1beeece9-61fe-4125-abe1-aad321ee0953)
