### ISSUE TITLE
nursing-internal - enable column-header tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5180]
# Brief Description of Scenario
Documentation #1080 type 3 - please add this table type
 
# Acceptance Criteria
- [ ] first column has header like styling (bold mulish font and a thicker right line

# Location(s)
![Screenshot 2023-07-13 at 12 11 00 PM](https://github.com/openstax/cnx-recipes/assets/11299125/e6503d96-e91c-4e58-bccf-119daca33698)

- **osbooks repo:** https://github.com/openstax/osbooks-nursing-internal-bundle
- **collection slug:** nursing-test
- **ref/branch:** testcontent
- **chapter/section:** look for table above should have the text column-header in the caption
- **surrounding text:** should have the class="column-header"

**Comment by LostMojo** [comment]
Testing Note: The 1.1 table _looks_ like it should be a header-column table, but it's doesn't have that class. The 1.2 table has the correct class though.

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `nursing-test` & content from `main`

![CleanShot 2023-07-20 at 15.28.00.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ac7f81de-39ab-4e29-87e1-b8e289e0ef25)

**Comment by LostMojo** [comment]
Table 1.1, 1.3, 1.5, 1.9, and 1.10 don't have the relevant class in the xhtml, even though they're an exact copy of the type of table that SHOULD have the class-- but Table 1.2 DOES have the class? I think the test data is just... weird here.
All of the basic os-tables are getting a BasicTable styling which makes the top row bolded & header-ized right now I think as well.

![Screenshot 2023-07-20 at 5 14 33 PM](https://github.com/openstax/cnx-recipes/assets/5740972/267f53ee-af6e-4886-ac7e-18af0be23fba)

**Comment by Stackblocks** [comment]
Chalking this up to test data for the time being, if we need to follow up a new card can be created.
