### ISSUE TITLE
cardboard theme - splash image shape not centered to page

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5181]
# Brief Description of Scenario
![Screenshot 2023-07-07 at 1 45 44 PM](https://github.com/openstax/cnx-recipes/assets/11299125/321e6b8d-4288-4b98-a673-ad18181cc4ce)
![Screenshot 2023-07-07 at 1 46 02 PM](https://github.com/openstax/cnx-recipes/assets/11299125/a00cd13d-5f56-4ae9-9291-93ec91c37e85)

This was discovered when we added crop marks to the books. You'll notice the screenshot with the ruler that the entire splash shape is a little off center - left side is about .1inch too far

# Pattern of Occurrence 
So far I only see splash. I believe it's trying to align to the number so we might have to move it a little?

# Acceptance Criteria
- [ ] splash image is centered 
- [ ] low priority - if we can't fix it's ok but good to see if there's a solution
  

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-college-success-bundle
- **collection slug:** preparing-for-college-success
- **ref/branch:** main

**Comment by LostMojo** [comment]
The image in question is controlled by the FigureSplashShape, and the figure.splash styling inside of it is using translate3d to move it exactly one inch to the left. 

I have a PR for the 5181-splash-image-branch with the image moved .9 inches to the left instead? It's hard for me to spot the difference on the pdf, but it's there for testing now.

**Comment by LostMojo** [comment]
After talks for Larissa, found that -0.95 is the closest, but still not quite centered. Good enough for now, but if there's an exact amount the image should be moved by, we maybe could it exactly centered.

Good enough for now though!

**Comment by lwtchu** [comment]
@Stackblocks you can use this documentation to test a few of the cardboard themed books - it's not super centered, but we were able to settle it on something a little closer to centered https://openstax.atlassian.net/wiki/spaces/CT/pages/2260074526/Book+Production#Prepping-PDF-for-print 

let me know if you need any help.

**Comment by Stackblocks** [comment]
Here are some examples generated with the fix along with the measurements between the splash and the page edge; like you said, they aren't perfectly centered but appear to be within a reasonable margin of error. 

lmk if I can move this one to CORGI testing or if you have any additional comments.

## College Success
![CleanShot 2023-07-24 at 15.28.53.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/fd7320f6-409d-4ab2-b51a-226cc3ba11af)

![CleanShot 2023-07-24 at 15.30.28.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0e1f527c-f722-4df8-85b1-1349990b5ed4)

## Astronomy
![CleanShot 2023-07-24 at 15.35.22.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4385ae78-bb8a-4b94-b5fe-880b33d316c8)

![CleanShot 2023-07-24 at 15.36.43.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/70cd64eb-d07f-4fd0-892c-bd40502ef1fb)

## Eship

![CleanShot 2023-07-24 at 15.53.13.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f9400af5-62fb-4c11-9d9d-52400f06bc56)

![CleanShot 2023-07-24 at 15.53.46.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/98c26c54-b08c-43c3-97d4-c077f1ea1d96)
