### ISSUE TITLE
[waiting for baked web to fully merge] Fix Shorten Script

### ISSUE THREAD

**Issue by LostMojo** [openstax/cnx-recipes#5183]
Since the resources update to cookbook, the shorten script hasn't been functional.

![Screenshot 2023-07-17 at 10.23.33 AM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/b4ebf146-8cda-458d-97d6-158090bd389f)

The shorten scripts should be tweaked to use the no resources option. It looks like the individual shorten scripts for each book might have to be updated as well.

**Comment by Stackblocks** [comment]
This was classed as an "optional/nice to have" that would require focused re-investigation since the work on the shorten script has been stalled out for a while and the team has changed since the work was started.
