### ISSUE TITLE
create bake-web step in pipeline and run BakeImages during this step

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#5184]
Context: #5162 #4917 openstax/unified#2485

## User story: 
As a developer, I want an easy way to support small changes that only need to be present in the web output format, i.e. the image dimensions issue (context linked above).

## Approach: 
This issue requires changes in both cookbook and enki. 

- On the cookbook side, a one-size-fits-all web recipe should be created to hold any small web-only bake steps. 
- Within the web recipe, the only step to add is (currently) BakeImages; BakeImages should be taken out of all book recipes.
- On the enki side, `all-pdf` should call `step-bake` with just the book recipe, while `all-web` should call a new step, `step-bake-web`, which runs the book recipe & the web recipe on the content (instead of `step-bake`). 

## AC:
- [ ] `height` and `width` attributes are added to image html in content that goes to the web output format only
- [ ] Infrastructure for web-only recipe changes exists
- [ ] enki documentation graphic is updated to show the new progression of steps

**Comment by kswanson33** [comment]
For QA: This is testable on enki branch [302](https://github.com/openstax/enki/pull/302).

**Comment by Stackblocks** [comment]
Add'l testing info for posterity:
- Enki branch: `add-step-bake-web`
- Cookbook branch: `separate-web-baking`

**Comment by Stackblocks** [comment]
Tested a variety of outputs for both web and PDF and the new setup worked properly across all of them. Didn't spot any irregularities in the generated output.
