### ISSUE TITLE
organic chemistry - webview - exercises numbering are not formatted properly

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5185]
![image](https://github.com/openstax/cnx-recipes/assets/11299125/e7ce3f75-7a8f-4147-b89a-8d4059f5f180)
![image](https://github.com/openstax/cnx-recipes/assets/11299125/8cbb66ea-054d-4b3c-ae87-4b6af515ced8)

# Brief Description of Scenario
Related #5144 - this was fixed but for some reason it's broken again. 

# Pattern of Occurrence 
This was fixed some time ago but a regression was introduced: https://github.com/openstax/cnx-recipes/issues/5144#issuecomment-1578903704

# Acceptance Criteria
- [ ] the problem #-# should be on top of each other and like the original fix
- [ ] the question should align with the problem (next to the number) like the pdf
- [ ] could this have been introduced by the no breaking rule?
  

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:**  all exercises
- **surrounding text:** located at the end of each module and in Additional Problems section

**Comment by wilkus27** [comment]
This is a regression from these two PRs: https://github.com/openstax/ce-styles/pull/279 and https://github.com/openstax/ce-styles/pull/264.

I was trying to find a solution that fixes previous problems and the one from this card.

@RoyEJohnson could you recommend which books should we check? Based on the https://github.com/openstax/unified/issues/1959 I checked Problems and Multiple Choice from Principles of Finance and section 8.1 from Contemporary Math. Is there anything else we should check on?

**Comment by ww-openstax** [comment]
@lwtchu adding that the fix for the distractor letters should also apply to the Answer Key

<img width="752" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/ef7ff76f-0135-4efd-ac64-6498900d8f6d">

**Comment by ww-openstax** [comment]
@lwtchu there is an additional issue for Answer Key so I opened a separate card for Answer Key https://github.com/openstax/cnx-recipes/issues/5207

**Comment by RoyEJohnson** [comment]
This is why they're called problems, I guess.
I'll be investigating this today across multiple books. It looks like different problem sets have somewhat different layouts and fixing one might break another. For a start, I note that [Principles of Finance](https://openstax.org/books/principles-finance/pages/9-problems) has a space between the problem number and the dot after it.
SInce this issue is specifically with Organic Chemistry, I guess I need to look at something in development or staging. Is there a staging server to look at this on, or do I need to set up locally?

**Comment by wilkus27** [comment]
Here is a content repo for ochem: https://github.com/openstax/osbooks-organic-chemistry

You can do this locally, by fetching webview version in Enki, but I think you can also generate it on CORGI. Then (in both cases) in the URL you need to add `&content-style=[url_with_new_styles]`.

To get `url_with_new_styles` you should change branch to the one with new styles, go to `webview-generic.css` file and click on the raw

![image](https://github.com/openstax/cnx-recipes/assets/40228854/02a6a8a6-690a-44a3-a4a8-3fcb2b559e21)

And then copy an URL

![image](https://github.com/openstax/cnx-recipes/assets/40228854/ff8b5575-1294-4718-a78f-dc9840e34564)

My branch with fixes is called `ochem-web-exercises-regression`. Here is a PR: https://github.com/openstax/ce-styles/pull/293

Let me know if you need any help with that :wink:

**Comment by RoyEJohnson** [comment]
@wilkus27 Issue #279 was just to fix tables not being constrained to the page width. It should be unrelated to this issue.
#264 addressed multiple issues, of which I think [issue #5](https://github.com/openstax/ce-styles/pull/264/commits/ba9babda6134d8ebb73c5e959bc21905b1f1a762) could be relevant. _Principles of Finance_ was the example for that issue. It looks ok [with the content style applied](https://openstax.org/books/principles-finance/pages/9-problems?content-style=https%3A%2F%2Fraw.githubusercontent.com%2Fopenstax%2Fce-styles%2Fmain%2Fstyles%2Foutput%2Fwebview-generic.css) but as I noted above has an extraneous space after the number in Production.

**Comment by wilkus27** [comment]
About _Principles of Finance_, this is what it looks like with my changes

![image](https://github.com/openstax/cnx-recipes/assets/40228854/facce99c-b5d7-4a86-8817-43eb2cb67b9c)

Is it ok?

**Comment by RoyEJohnson** [comment]
That looks fine to me. No extra space.

**Comment by lwtchu** [comment]
@wilkus27 @RoyEJohnson thank you both 🎉 i think this also solves another issue that i have scheduled in a later sprint https://github.com/openstax/cnx-recipes/issues/5194

**Comment by RoyEJohnson** [comment]
It seems I do not have permission to see the openstax/osbooks-organic-chemistry repo.

**Comment by lwtchu** [comment]
@RoyEJohnson i just asked staxly to give you access - try refreshing and lmk if it doesn't work

**Comment by Stackblocks** [comment]
Problem numbering now showing properly throughout the webview version.

![CleanShot 2023-08-09 at 18.23.54.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d602e317-f71b-4f8d-a554-fdf7c4f92faf)
![CleanShot 2023-08-09 at 18.26.04.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/40f1ed9b-1050-4a8f-86a3-b2d4ff48562f)
![CleanShot 2023-08-09 at 18.24.58.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/13c0d5e7-908b-4d24-be11-af30db94f731)
