### ISSUE TITLE
Organic Chemistry - increase leading in figure captions to increase space between subscripts and superscripts

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5186]
# Brief Description of Scenario
Increase leading in figure captions to increase space between subscripts and superscripts
This was done for Mechanism Figure captions in issue #5139 but not for "regular" figure captions

![image](https://github.com/openstax/cnx-recipes/assets/89537088/01495a51-3df9-4b3d-8dbf-27dc01895a9a)

# Pattern of Occurrence 

# Acceptance Criteria
- [ ] please double check that the line height is the same size as the font size for figure/table captions. that was the issue for the mechanism figure captions
  

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 12 / Section 2 / Figure 12.5
- **surrounding text:**

**Comment by lwtchu** [comment]
@kswanson33 i think so-- if i recall correctly captions were smallened (made smaller) and line-height wasn't adjusted so this will be an overall improvement for the entire theme

**Comment by lwtchu** [comment]
@kswanson33 scaling by font size works - what was it set to before? i think in the mechanism art it was set to the same size as the font which is not ideal. i THINK 1.2 is what we usually set it at but somehow it escaped this book

**Comment by kswanson33** [comment]
it was set to `1rem` before

**Comment by lwtchu** [comment]
@kswanson33 ah okay - anyway 1.2 looks good let's go with that

**Comment by Stackblocks** [comment]
- Appears to be OK judging from that one example and a pass through the figure captions across the rest of the book. Tables still look OK and no regressions were spotted. Tested with updated code from `prosperous.paleontology` & content from `main`

![No collision in the caption.](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/407a95df-e6de-4eb7-a457-f4e3f675d05f)
---
![Tables are OK, too.](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/00c58350-18b1-4b53-ba50-bfbf0a8f05b7)
