### ISSUE TITLE
Organic Chemistry - webview - top-align distractor to letters not working in webview

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5188]
# Brief Description of Scenario
Related to issue #5146 
The fix to adjust output of html to top-align distractor letter is not working in webview
See screenshot below of top-align distractor letter **in PDF** for desired output

### Webview
<img width="879" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/4c6eb825-53ed-472f-acd1-325d4e9d6808">

### PDF
<img width="477" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/a5811790-cd84-4a8b-954f-ac7c82dd9a69">

# Pattern of Occurrence 

# Acceptance Criteria
- [ ] solution should match the fix in #5146 
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 5 / Section 7 / Problem 5-16
- **surrounding text:**

**Comment by Stackblocks** [comment]
Distractors now displaying as top-aligned in webview.

![CleanShot 2023-08-09 at 18.27.44.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1bf8e954-bbd5-4cbd-b026-991a457bbc83)
![CleanShot 2023-08-09 at 18.29.59.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a49e0181-f3c7-414f-adb6-673037eb714f)
