### ISSUE TITLE
Organic Chemistry - webview - add Chemistry Matters title at the top of the page?

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5190]
# Context
From a content perspective, WiseWire team thinks it would be ideal to have the Chemistry Matters sections with `class="chemistry-matters"` output the title at the top of the page as we do with feature boxes on other titles. 
Is it possible to output Chemistry Matters title at the top of the page in webview?
![image](https://github.com/openstax/cnx-recipes/assets/89537088/3465fb78-152f-4cd1-9ed8-a19f34491578)

## Impact 
All Chemistry Matters sections in Organic Chemistry

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<section class="chemistry-matters" id="sect-00002">
    <title>Organic Foods: Risk versus Benefit</title>
    <para id="para-00014">Contrary to what you may hear in supe
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** All Chemistry Matters sections
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax Closing this card - since the way it's set structurally (it's technically a separate page) we can't have it be treated like a typical feature box. If in the future there's a change in how we want it to appear in the TOC, we can revisit.
