### ISSUE TITLE
anthropology - webview - exercise numbering has a space

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5194]
![Screenshot 2023-08-01 at 3 01 34 PM](https://github.com/openstax/cnx-recipes/assets/11299125/b886a693-6715-41a1-aa34-0446cc6c3715)

# Brief Description of Scenario
Please remove the space between the number and the period

# Pattern of Occurrence 
happens in all the critical thinking questions in anthropology

# Acceptance Criteria
- [ ] space between # and period (.) is removed. should look like 1. Insert questions here.
- [ ] i believe these are due to injected exercises
- [ ] can we double check the non injected exercises styling and make sure it matches

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introduction-anthropology
- **collection slug:** introduction-anthropology
- **ref/branch:** main

**Comment by wilkus27** [comment]
It's already fixed

![image](https://github.com/openstax/cnx-recipes/assets/40228854/718db953-a93f-4838-85d7-575498f4a960)

**Comment by wilkus27** [comment]
@lwtchu About non injected exercises, I checked in Chemistry and they are not styled

![image](https://github.com/openstax/cnx-recipes/assets/40228854/c428a8cf-dc12-41b2-a408-9a7cf7e2d28d)

Do we want to resolve it within this issue or is it better to open a separate card?

**Comment by wilkus27** [comment]
I noticed that such issue is already created https://github.com/openstax/cnx-recipes/issues/5198. I'm closing this one.
