### ISSUE TITLE
anatomy & physiology (maybe other books) - webview - headers not supported in preface

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5197]
![Screenshot 2023-08-01 at 4 05 50 PM](https://github.com/openstax/cnx-recipes/assets/11299125/ad936786-e946-4d66-b63b-5f5d63a86a03)

# Brief Description of Scenario
Need to go through header options in webview CSS 

# Pattern of Occurrence 
TBD

# Acceptance Criteria
- [ ] audit header styling in the webview CSS
- [ ] come up with consistent styling for headers across preface, appendix pages, eoc, and in book content
  

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-anatomy-physiology
- **collection slug:** anatomy-physiology
- **ref/branch:** main
- **chapter/section:**  preface
- **surrounding text:**

**Comment by lwtchu** [comment]
Similar in Astronomy 
![image](https://github.com/openstax/cnx-recipes/assets/11299125/a706c94e-3a5a-474b-be6f-a3c8e19d4a5d)

**Comment by wilkus27** [comment]
@lwtchu It's already fixed

![image](https://github.com/openstax/cnx-recipes/assets/40228854/1c44884d-30a1-4f1e-9e56-e0a9ec0ff7a3)
