### ISSUE TITLE
business ethics - webview - assessment question links

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5198]
![Screenshot 2023-08-01 at 4 45 00 PM](https://github.com/openstax/cnx-recipes/assets/11299125/aa525153-0cd5-4cb5-8d76-fd29a660c786)
(Generic is our stylesheet)

# Brief Description of Scenario
Can we make the numbering style consistent? Set it as bold and not underlined (blue can be there since it's a link)

# Pattern of Occurrence 
assessment questions in business ethics

# Acceptance Criteria
- [x] remove underline
- [ ] set number as bold

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-business-ethics
- **collection slug:** business-ethics
- **ref/branch:** main 
- **chapter/section:**  assessment questions
- **surrounding text:**

**Comment by lwtchu** [comment]
![image](https://github.com/openstax/cnx-recipes/assets/11299125/c071b74c-2213-47c7-a751-002e3910d1a9)


Similar issue in Chemistry 2e

**Comment by Stackblocks** [comment]
Displays OK with code from `quiet.quinology` and content from `main`

## Business Ethics
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/153aa2c6-933c-4a7c-8b1d-dc8d72418a27)

## Chemistry 2e
_The alternating numbers are linked properly and consistently styled between the linked and non-linked versions_

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/e71dc8ff-386f-4f30-ad71-01c54a30846b)
