### ISSUE TITLE
entrepreneurship - webview - case questions numbering not bold

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5199]
![Screenshot 2023-08-01 at 4 56 09 PM](https://github.com/openstax/cnx-recipes/assets/11299125/4e6567c0-ab26-4f67-ad71-e1e48e6a9761)

# Brief Description of Scenario
in order to be consistent, we should bold these numbers

# Acceptance Criteria
- [ ] bold case questions in entrepreneurship
  

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-entrepreneurship
- **collection slug:** entrepreneurship
- **ref/branch:** main

**Comment by lwtchu** [comment]
Similar issue in Review Questions in Astronomy
![image](https://github.com/openstax/cnx-recipes/assets/11299125/097428cd-bdba-4629-ad15-f328b492231c)

**Comment by jbwilson8** [comment]
Issue has been addressed (no code change) 

![Image](https://github.com/openstax/cnx-recipes/assets/26155528/299da1a1-6080-42f5-825e-41da4c79eee9)
![Image](https://github.com/openstax/cnx-recipes/assets/26155528/9fc5290b-034e-4e94-a85a-d2f46941f066)
