### ISSUE TITLE
end of book references - webview - redesign

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5200]
![image](https://github.com/openstax/cnx-recipes/assets/11299125/bd8e74af-1714-4a98-af18-8ee9883a553b)

This example is from PoM

# Acceptance Criteria
- [ ] remove the note styling in REFERENCES only (remove grey box and grey stroke styling)
- [ ] please set them closer together, like a list (line height padding between each reference note)

**Comment by Stackblocks** [comment]
The grey box styling has been removed and replaced with a more normal works cited structure.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/734fc279-f037-4af9-a7e5-6212fe90e9a7)
