### ISSUE TITLE
accounting - webview - answer key number styling is off

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5201]
![image](https://github.com/openstax/cnx-recipes/assets/11299125/23b4a7d8-cee9-439b-8f12-0229257fbf8a)
Right is our webview generic styles

# Brief Description of Scenario
Please keep it the consistent no underline, bold number style. 

# Pattern of Occurrence 
Answer Key in Accounting - could impact other books not sure

# Acceptance Criteria
- [ ] underline removed
- [ ] bold number 

# Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-principles-accounting-bundle
- **collection slug:** principles-financial-accounting
- **ref/branch:** main
- **chapter/section:** answer key 
- **surrounding text:**

**Comment by lwtchu** [comment]
![Screenshot 2023-08-01 at 5 06 30 PM](https://github.com/openstax/cnx-recipes/assets/11299125/44bd71bb-3873-4a61-bea3-884f6976ddcb)
Similar issue in College Physics/AP College Physics

**Comment by jbwilson8** [comment]
Issue has been addressed. No update needed.

![Image](https://github.com/openstax/cnx-recipes/assets/26155528/17d4fc44-cb5c-468e-a283-a71693fb7565)
![Image](https://github.com/openstax/cnx-recipes/assets/26155528/3de08fcb-75a8-40f9-a54e-cbcb2833c739)
