### ISSUE TITLE
Organic Chemistry - webview - Mechanism Figure Captions do not output inside of mechanism images like in PDF

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5204]
# Brief Description of Scenario
In WebView, Mechanism Figure Captions do not output inside of mechanism images like in PDF
### Webview
<img width="736" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/5d5d506e-eda1-47d7-aad5-288b881c13db">

### PDF
<img width="362" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/60e59aa9-9d4d-4297-9406-14a667462ede">

# Pattern of Occurrence 
All Mechanism Figures

# Acceptance Criteria
- [ ] is it possible that figures with the mechanism class have the caption wrap and be contained with the image on webview?
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 6 / Section 4 / Figure 6.4
- **surrounding text:**

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `quiet.quinology` & content from `main`
- There was one instance of a mechanism figure loading in with a lighter green than its caption but when I refreshed the page they matched so i'm logging it but going to chalk it up to browser / local content issue. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEViIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7f2ccd5c6c9cf4c4804aaaf66515c270fb9f401b/CleanShot%202023-08-18%20at%2013.27.27.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEliIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--58f1e407b9d88fc5a4d350d6c9eb50854fed6d52/CleanShot%202023-08-18%20at%2013.28.59.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaE1iIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6fcb894c66c77b0a3e609429a20c5c2981a87772/CleanShot%202023-08-18%20at%2013.30.09.png)
