### ISSUE TITLE
Organic Chemistry - PDF - smallcaps not outputting correctly inside <caption> 

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5206]
# Brief Description of Scenario
smallcaps not outputting correctly inside `<caption> ` in PDF
### PDF
![image](https://github.com/openstax/cnx-recipes/assets/89537088/93294139-2a70-46ee-831b-818e5673c428)

# Pattern of Occurrence 
`<emphasis effect="smallcaps">` inside `<caption>`

# Acceptance Criteria

  
# Sample Mark-Up
```
<caption><emphasis effect="bold">Configurations of <emphasis effect="smallcaps">D</emphasis> aldoses.</emphasis> The structures are arranged from left to right so that the –OH groups on C2 alternate right/left (R/L) across each series. Similarly, the –OH groups at C3 alternate two right/two left (2R/2L), the –OH groups at C4 alternate 4R/4L, and the –OH groups at C5 are to the right in all eight (8R). Each <emphasis effect="smallcaps">D</emphasis> aldose has a corresponding <emphasis effect="smallcaps">L</emphasis> enantiomer that is not shown.</caption>
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 25 / Section 4 / Figure 25.4; moudule m00302 line 17
- **surrounding text:**

**Comment by ww-openstax** [comment]
Related to issues https://github.com/openstax/cnx-recipes/issues/5152 https://github.com/openstax/cnx-recipes/issues/5189

**Comment by lwtchu** [comment]
@ww-openstax We should discuss this issue tomorrow. Any smaller text in the caption will lead it to be not accessible. I see there's a high priority label on this, but we should talk through some options to see what would be good for everyone.

**Comment by lwtchu** [comment]
Decision: Leave the design and content as is. Only happens in about 2 captions in 2 chapters. Small caps will work on webview but any smaller on PDF will render the text inaccessible.
