### ISSUE TITLE
Organic Chemistry - webview - smallcaps not outputting correctly in caption

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5212]
# Brief Description of Scenario
Related to #5189 
In webview, following 8/14 code release, small caps outputs correctly in all instances EXCEPT captions.

<img width="565" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/c805aa48-c15e-49b2-a3a6-ad289201460b">

<img width="583" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/b56898c6-ab53-443a-9e5e-04a86eec3743">

# Pattern of Occurrence 
small caps in captions

# Acceptance Criteria
- [ ] #5189 - please use these specs and apply to figure and table captions
  
# Sample Mark-Up
```
<caption><emphasis effect="bold">Configurations of <emphasis effect="smallcaps">D</emphasis> aldoses.</emphasis> The structures are arranged from left to right so that the –OH groups on C2 alternate right/left (R/L) across each series. Similarly, the –OH groups at C3 alternate two right/two left (2R/2L), the –OH groups at C4 alternate 4R/4L, and the –OH groups at C5 are to the right in all eight (8R). Each <emphasis effect="smallcaps">D</emphasis> aldose has a corresponding <emphasis effect="smallcaps">L</emphasis> enantiomer that is not shown.</caption>
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 25 / Section 4 / Figure 25.4
- **surrounding text:**

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `quiet.quinology` & content from `main`
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzhiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d6e9e8a82a741f56926c57da223916491a0f9101/CleanShot%202023-08-18%20at%2013.25.39.png)
