### ISSUE TITLE
Organic Chemistry - webview - Exercises - spacing between the distractor letter and the text is inconsistent

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5213]
# Brief Description of Scenario
In Webview, in Exercises, when distractor letter precedes text (as opposed to image) the spacing between the distractor letter and the text is inconsistent

<img width="874" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/d2eba77e-12e9-4597-bd1d-858c76c69468">

# Pattern of Occurrence 
when distractor letter precedes text

# Acceptance Criteria
- [ ] could we have the content in that box space be left aligned? -- is there any reason why it's left aligned? 
- [ ] i think this is the distractor letters + text alignment fix that is affecting this, but please make sure the #5188 #5207 issues are not compromised
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 1 / Section 3 / Problem 1-1 / Nickname: 01-03-OC-P01
- **surrounding text:**

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `quiet.quinology` & content from `main`

![CleanShot 2023-08-16 at 15 08 44](https://github.com/openstax/cnx-recipes/assets/12678235/42b0a40f-b01f-4477-9ab9-f565083904b5)
