### ISSUE TITLE
Nutrition - Key terms section placement

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5214]
We have received the below correction. Kindly check and resolve this issue.

**Move Key Terms, etc. to this page. No need for Chapter Summary to be its own page.** 

![keyterm](https://github.com/openstax/cnx-recipes/assets/86622862/3230cc21-44d6-4a18-aee8-55cbae10551c)

# Acceptance Criteria
- [ ] is there a rule where Key Terms cannot break? please double check the composite pages for this book (there's a larger than normal gap between Summary and Key Terms)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:**nutrition
- **ref/branch:**https://openstax-osbooksnursing-om7p9xrw6yq.ws-us103.gitpod.io/
- **chapter/section:** Chapter 4/Section 1(EOC Chapter)
- **surrounding text:** the process of cells taking in digested

**Comment by lwtchu** [comment]
**For OpenStax devs:** 

![Screenshot 2023-08-17 at 11 13 01 AM](https://github.com/openstax/cnx-recipes/assets/11299125/00606893-5aac-4b6e-99f9-6488b16a938d)
Adding additional context - the gap is larger than what would be expected -- I checked the page break rules and didn't see anything that would indicate this would force the Key Terms to stay together or break post Chapter Summary. Please discuss with me different options if you find anything.

**Comment by wilkus27** [comment]
@lwtchu Using Prince we are defining group of pages, in this case EOC pages, to add to them some specific printing properties, like starting new section on left or right side of the page. To do this we need to add information about first page of the group. Previously Key Terms section was the first one. Later in recipe we changed an order, but styles were not fixed. These settings are book specific, so my fix won't affect other textbooks.

**Comment by lwtchu** [comment]
@wilkus27 thank you for explaining!

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `quiet.quinology` & content from `main`
![CleanShot 2023-08-18 at 17 34 21](https://github.com/openstax/cnx-recipes/assets/12678235/8f5f47c9-93c1-4ebe-b00d-d7fb28e0e09e)
