### ISSUE TITLE
Nutrition - Chapter number and link missing in Reference Section

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5217]
We have received the chapter number and label missing correction in Reference section. This headings are generated automatically in CORGI. So, please check and resolve this issue.

![reference_Chapter-heading](https://github.com/openstax/cnx-recipes/assets/86622862/f4722f57-3286-4f1e-a039-a95b62e4e203)

And also, we received link missing issue.

![reference_section-chapterheading-link](https://github.com/openstax/cnx-recipes/assets/86622862/4c4b3cb9-8ed0-4c3a-bdae-060e1b174ce7)

# Acceptance Criteria
- [ ] please add the chapter number to EOB references
- [ ] link should go to the Introduction module of each chapter
- [ ] it is okay if the link takes them to the middle of the page on the PDF
- [ ] Please put the text Chapter 1, 2, 3, 4 with no colon
- [ ] For testing - please test in webview also

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** nutrition
- **ref/branch:** https://openstax-osbooksnursing-om7p9xrw6yq.ws-us103.gitpod.io/
- **chapter/section:** Chapter 4/EOC Section
- **surrounding text:** Afzaal, M., Saeed, F., Shah, Y., Hussain., M., Rabail, R., Socol, C., Hassoun

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `relatable.runology` & content from `main`

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/81e33f37-29c3-47d5-b1e8-728dde328e5f)

**Comment by lwtchu** [comment]
Moving to the new sprint. We need new requirements since this version of solution broke the web output. Larissa to do some additional requirements gathering.

**Comment by Stackblocks** [comment]
Titles are displaying, the colon has been removed, and the link works correctly in the PDF and Web.


### PDF
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/c6b5b49c-eca6-4d34-8242-e75ddcbe7654)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/67369635-d4f0-4749-8652-e59c152ffd89)

### Web


![Image](https://github.com/openstax/cnx-recipes/assets/12678235/3cf5566e-0b92-458d-8616-3f0f58eb423b)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/f837d6a9-84c6-4fa7-b37b-f79d58f85a6a)
