### ISSUE TITLE
Anatomy and Physiology: Support embedded exercises styling

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#5221]
# Brief Description of Scenario
This will go for all books eventually, as we move more and more EoC exercises out of CNXML and into the exercises platform for embedding. 
Currently, when adding an embedded exercise they are not numbered or counted in with the other EoC content. 

<img width="864" alt="Screenshot 2023-08-16 at 1 12 04 PM" src="https://github.com/openstax/cnx-recipes/assets/5865292/c9b6341f-4e82-4cb8-b411-8523fffcd036">

# Pattern of Occurrence 
All embedded exercises.

**Note**: numbering is continuous through individual EoC pages, and resets back to 1 in each chapter.

# Acceptance Criteria
Embedded exercises should be numbered and counted with other surrounding EoC content. (In A&P, that looks like bold numerical list.)

  
# Sample Mark-Up
```
<exercise id="fs-id2662649">
        <problem id="fs-id2652614">
          <para id="fs-id2278300">
            <link class="os-embed" url="#exercise/anat-and-phys-0001"/></para>
        </problem>
      </exercise>
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-anatomy-physiology
- **collection slug:** anatomy-and-physiology-2e
- **ref/branch:** https://github.com/openstax/osbooks-anatomy-physiology/tree/converting-to-exercises
- **chapter/section:** look in chapter 1 Review Questions for examples where I've already implemented the conversion from CNXML to embedded exercises.
- **surrounding text:** "anat-and-phys-0001" in code, "Which of the following specialties might focus on studying all of the structures of the ankle and foot?" in rendered web/pdf.

**Comment by Stackblocks** [comment]
# PDF

There's some weirdness with the PDF output where the question is split across two columns before returning to being a single column item for the answers

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/08cdb34e-95b9-4eb9-9492-65acf36cd7d6)

# Web

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/ac46c4e0-ea67-47e1-96de-408fc3e6b80e)

**Comment by lwtchu** [comment]
@Stackblocks we might need to make another issue to remove these from two column - currently as it stands injected exercises don't do page breaks

**Comment by lwtchu** [comment]
![Screenshot 2023-09-11 at 3 01 29 PM](https://github.com/openstax/cnx-recipes/assets/11299125/a483e437-10b8-498a-9e9f-e2be84626e05)
Verified on staging
