### ISSUE TITLE
Statistics - Unwanted space issue after the link

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5222]
We have received the below correction. Please check and resolve this issue.

**Check spacing after ALL Table and Figure references in html in the practice/homework/bringing it together sections. there are extra spaces after many of them.** 

**PDF View:**
![Table_Link_Spacing_Issue](https://github.com/openstax/cnx-recipes/assets/86622862/72e34262-4794-4ff1-b663-13f9802f6cad)

**Web View:**
![Table_Link_Spacing_Issue_webview](https://github.com/openstax/cnx-recipes/assets/86622862/dbe1db66-eac0-4041-b3a3-0fe919f367c7)

# Acceptance Criteria
- [ ] remove space after link - this is very similar to some other issues we've had with links on web but for figures? might be able to find something in an old issue 

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introductory-statistics-bundle
- **collection slug:** introductory-statistics-2e/introductory-business-statistics-2e
- **ref/branch:** https://openstax-osbooksintrodu-rxj25jbp2zu.ws-us104.gitpod.io/
- **chapter/section:** Practice/Homework/Bringing it together
- **surrounding text:** contains the total number of deaths worldwide as a result of earthquakes over a 13-year

**Comment by wilkus27** [comment]
@lwtchu This problem doesn't appear on quiet.quinology branch

![image](https://github.com/openstax/cnx-recipes/assets/40228854/f917d284-be5d-4011-8801-bcbe37b5894a)
 
I'm closing the issue.
