### ISSUE TITLE
Statistics - Empty page issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5223]
We have received the following correction "**Get rid of empty page**". Please check and resolve this issue.

![Empty_Page_Chapter6](https://github.com/openstax/cnx-recipes/assets/86622862/a27d7686-e799-445f-a9c2-598ffbf5eac1)
![Screenshot 2023-08-23 at 11 33 56 AM](https://github.com/openstax/cnx-recipes/assets/11299125/882aa855-8c17-4980-bb27-ee4f534a895b)

# Acceptance Criteria
- [ ] Is there a way to not have the design line be orphaned? - investigate a fix for no more than 2-3 days

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introductory-statistics-bundle
- **collection slug:** introductory-statistics-2e
- **ref/branch:** https://openstax-osbooksintrodu-rxj25jbp2zu.ws-us104.gitpod.io/
- **chapter/section:** Chapter 6/Section 4
- **surrounding text:** collected give a close approximation to the theoretical distribution? In complete sentences and

**Comment by Stackblocks** [comment]
While the line is no longer orphaned the page is still mostly blank.
 
@wilkus27 Is this what you were seeing in your output?

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/a0bba4e4-9804-41f0-9c1f-a0642a70a7de)

**Comment by lwtchu** [comment]
@Stackblocks That's okay - the main thing was for the line to not be orphaned. The Key Terms are supposed to start on the next page.

**Comment by lwtchu** [comment]
![Screenshot 2023-09-11 at 2 32 48 PM](https://github.com/openstax/cnx-recipes/assets/11299125/536746be-7dc4-478b-a1e2-972a53aa75fd)
Verified on staging
