### ISSUE TITLE
Statistics - Number missing in Try it section 

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5225]
We have coded as per the tagging legend. But Try it section number missing in this occurrence. Please check and resolve this issue.

**PDF View:**
![Tryit-12 5-PDF](https://github.com/openstax/cnx-recipes/assets/86622862/5f47b239-335b-42a8-a239-414696adfb18)

**CNXML View:**
![Tryit-12 5](https://github.com/openstax/cnx-recipes/assets/86622862/4007590d-e772-40d9-8155-5c534c8899f0)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introductory-statistics-bundle
- **collection slug:** introductory-business-statistics-2e
- **ref/branch:** https://openstax-osbooksintrodu-rxj25jbp2zu.ws-us104.gitpod.io/
- **chapter/section:** Chapter 12/Section 3
- **surrounding text:** Another fourth grader also grew bean plants, but this time in a jelly-like mass. The

**Comment by lwtchu** [comment]
@srm-openstax Try It's take on the numbering of the Example that immediately precedes it. Please move the Try It to right after the Example.

**Comment by srm-openstax** [comment]
Thanks for your support. This issue resolved.
