### ISSUE TITLE
restructure recipes to use centralized executable

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#5226]
## User story 

As a developer, I want to be able to make changes to the setup for executing recipes if needed (in a more agile way).

## Context

Currently, each book has its own executable file, containing the definition of its recipe & the setup for execution. This second part is boilerplate that is duplicated in every recipe. Recent setup changes have involved modifying all recipe files. Ideally, since the setup is the same in all recipes (and we want it to stay that way), this would be consolidated.

One approach is to change the way recipes are executed, from using an executable book-specific bake file. In the new way, there would be one main executable file which handles the command-line args and the call to `Oven#bake`, and conditionally chooses a recipe based on the given recipe keyword. Book-specific `bake` files would become `recipe.rb` files, only containing the definition of their recipes (& not the execution logic).

## Acceptance Criteria

- [x] Move execution logic to central file
- [x] Top-level `bake` script uses same syntax, but calls central executable instead
- [x] Double check that timing stays about the same for recipes tests

**Comment by kswanson33** [comment]
dear QA, this is a "test that there have been no changes" situation, sincerely kendra

**Comment by Stackblocks** [comment]
After a week of testing both PDF and Web output everything seems OK from a QA perspective.
