### ISSUE TITLE
Support Blue Text in Web View (for Nutrition)

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5228]
# Context
The design for the nursing-external books uses blue text for the heads in tables; however, this design is not currently supported in web view.

# New specifications or link to documentation cards
Allow `<span class="blue-text">` to render blue text in web view (as it does in the PDF).
![Image](https://github.com/openstax/cnx-recipes/assets/99201272/9244acf5-341e-46e9-b483-fc555c563909)

## Impact 
For Nursing-External books

# Acceptance Criteria
The class `"blue-text"` should render blue text in web view.
- [ ] set to B2: `#0074BC`

# Content
## Sample Mark-Up
```
 <table class="vertically-tight" id="table-00002">
    <tgroup cols="2">
    <thead>
    <row>
    <entry><span class="blue-text">Disease</span></entry>
    <entry><span class="blue-text">Impact</span></entry>
    </row>
    </thead>
```

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** nutrition
- **ref/branch:** main
- **chapter/section:** whole book
- This example is in the last module in Chapter 4

**Comment by Stackblocks** [comment]
Currently blocked by "Link points to nowhere: href='#chapTitle18'" error when trying to bake web output.

**Comment by lwtchu** [comment]
Verified blue text shows up ✨ 

![Image](https://github.com/openstax/cnx-recipes/assets/11299125/0192bdb4-ffa7-45b2-88c4-1faaa0a42d57)

**Comment by lwtchu** [comment]
![Screenshot 2023-09-11 at 2 41 45 PM](https://github.com/openstax/cnx-recipes/assets/11299125/4a7f88ab-9234-47f1-8a81-3170233c4a12)
Verified on Staging
