### ISSUE TITLE
nursing-external - nutrition - safety alert font color change

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5230]
![Screenshot 2023-08-29 at 8 45 47 AM](https://github.com/openstax/cnx-recipes/assets/11299125/92eb553a-70c0-4944-9aa2-b598aba36269)

# Brief Description of Scenario
The `#000000` font color in the title `SAFETY ALERT` is not nearly as accessible as `#FFFFFF` 

# Pattern of Occurrence 
For Safety Alert feature `class="safety-alert"`

# Acceptance Criteria
- [ ] SAFETY ALERT is now set in white `#FFFFFF`
  

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** nutrition
- **ref/branch:** main
- **chapter/section:** ch 4 
- **surrounding text:**  search for safety alert

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `sappy.symbology` & content from `main`

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/e709ddc3-442e-4f8c-87ed-f505915733e8)
