### ISSUE TITLE
statistics - webview - adjust margin for inline list type in exercise

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5231]
![image](https://github.com/openstax/cnx-recipes/assets/11299125/b3186b89-5cbc-4c30-8410-297c82af920a)

# Brief Description of Scenario
`<list list-type="labeled-item" display="inline">` isn't aligning to other content within an `<exercise>`

# Pattern of Occurrence 

# Acceptance Criteria
- [ ] list starts under the paragraph above it in the problem (see pdf screenshot below)
![Screenshot 2023-08-30 at 4 38 56 PM](https://github.com/openstax/cnx-recipes/assets/11299125/f67a9232-c33e-49f0-be96-3fe509528922)

  
# Sample Mark-Up
```
<para id="fs-idm42775552"><emphasis effect="italics">Use the following information to answer the next four exercises:</emphasis> A study was done to determine the age, number of times per week, and the duration (amount of time) of residents using a local park in San Antonio, Texas. The first house in the neighborhood around the park was selected randomly, and then the resident of every eighth house in the neighborhood around the park was interviewed.</para><exercise id="fs-idm67132096">
<problem id="fs-idm60885840">
<para id="fs-idm58359376">The sampling method was</para>
<para id="fs-idm13619408"><list list-type="labeled-item" display="inline" id="list-00002">
<item>a. simple random</item>
<item>b. systematic</item>
<item>c. stratified</item>
<item>d. cluster</item>
</list>
</para>
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introductory-statistics-bundle
- **collection slug:**  introductory-statistics-2e
- **ref/branch:** main
- **chapter/section:** ch 1 / practice section 
- **surrounding text:**  class="practice" -- Use the following information to answer the next four exercises:

**Comment by wilkus27** [comment]
### Information for tester

To fix this I had to change totally the way how regular exercises are styled. I applied approach from PDF styling.
Since we have one style for webview there might be regression in many different books.

**Comment by MartaSztuka** [comment]
@wilkus27 list in business statistics have deeper indentation than statistics.


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/e93cea2a-f916-4ddf-90e1-5b9468ffc3ac)

![Image](https://github.com/openstax/cnx-recipes/assets/47241114/c84dc6fc-d6bb-48f5-b4a2-93ba0c989f75)

##### Introductory statistics 

![Image](https://github.com/openstax/cnx-recipes/assets/47241114/5b2d4531-7888-4110-bf03-21cf15cccfea)

**Comment by wilkus27** [comment]
This is because they are different elements. Lists with indentation are actuall lists. These without - are just paragraphs.
