### ISSUE TITLE
anatomy & physiology - remove two column for 'review questions'

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5232]
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/08cdb34e-95b9-4eb9-9492-65acf36cd7d6)

# Brief Description of Scenario
Injected exercises by design allow for page breaks. In order to avoid confusion, can we ONLY have 'Review Questions' questions removed from two column? `class="multiple-choice"` -- referenced here https://github.com/openstax/cnx-recipes/issues/5221#issuecomment-1697620795 

# Pattern of Occurrence 
Sections marked with `class="multiple-choice"`

# Acceptance Criteria
- [ ] Review Questions (`class="multiple-choice"`) are no longer in 2 column
  
# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-anatomy-physiology
- **collection slug:** anatomy-and-physiology-2e
- **ref/branch:** main
- **chapter/section:** Review Questions 
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED

![Image](https://github.com/openstax/cnx-recipes/assets/47241114/d808f595-610e-4a57-b1ab-24eba1021ac1)


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/f0e4d373-8fba-4149-96a2-33d3cb928485)

**Comment by lwtchu** [comment]
![Screenshot 2023-09-11 at 3 00 04 PM](https://github.com/openstax/cnx-recipes/assets/11299125/9ae6d703-9527-4456-9a7b-3bd4d17fa9be)
Verified on staging
