### ISSUE TITLE
Introduction to Python Programming - Exercises - choice-level feedback displaying in output

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5234]
# Brief Description of Scenario
For all assessment items: choice-level feedback is displaying in output. 
This is a recent error. Error did not occur with earlier composed pages. See CORGI ID 5075 for example. 

<img width="861" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/edffdcdf-b37b-4f85-b5a7-dce614556876">

### Exercises Tool
<img width="922" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/65dc14fe-e716-44b9-9f38-720d4da0533c">

# Pattern of Occurrence 

# Acceptance Criteria
- [ ] i think this was introduced with this #5151 
- [ ] detailed solution SHOULD remain (in answer key)
- [ ] choice level feedback should be suppressed everywhere else - if you need help parsing the data and labels, please let me know
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** all assessment items with choice-level feedback
- **surrounding text:**

**Comment by Stackblocks** [comment]
Displays OK with updated code from `sappy.symbology` & content from `main`

### In Content
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/f14a967b-0eec-47be-a734-8fffe2a2b9d3)

### In Answer Key

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/e201ab6a-d4cd-44ec-beec-75949f53fe1f)
