### ISSUE TITLE
Nursing Pharmacology - Shaded table web view issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5235]
We have coded as per the tagging legend for the shaded table. But, Tables with alternate shading appear in PDF view only, not in web view. Kindly check and resolve this issue.

**PDF Output:**
![image](https://github.com/openstax/cnx-recipes/assets/86622862/c3487015-cca8-4be5-a528-db31897d624f)

**Web view output:**
![image (1)](https://github.com/openstax/cnx-recipes/assets/86622862/22626e55-c2e9-4ae7-8b28-2720a08e6961)

# Acceptance Criteria
- [ ]  please apply the same functionality to tables with the `class="alternate-shading"` and use `#ededed` color (should be same as notes on webview-generic.css sheet

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** pharmacology
- **ref/branch:**https://openstax-osbooksnursing-om7p9xrw6yq.ws-us104.gitpod.io/
- **chapter/section:** chapter 18/Section 1
- **surrounding text:** The American College of Cardiology and American Heart Association Categories for

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `sappy.symbology` & content from `main`

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/e9a4fc29-77a4-4dc8-a28e-979933735728)
