### ISSUE TITLE
Business Computer Applications -- add shading to two columns in Table 2.4?

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5236]
# Brief Description of Scenario
Is there a way to add shading to the two columns in Table 2.4 indicated in the screenshot.?

![image](https://github.com/openstax/cnx-recipes/assets/89537088/fad2336e-6d9d-41a1-98d1-08149652c6da)

# Pattern of Occurrence 
Only needed for Table 2.4

# Acceptance Criteria

  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-workplace-software-skills
- **collection slug:** computer-applications
- **ref/branch:**
- **chapter/section:** Chapter 2 / Section 4 / Table 2.4
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax There isn't anything currently that can easily enable this feature and we haven't done something like this before - how prevalent is this table type?

**Comment by lwtchu** [comment]
@ww-openstax I think what you have right now should be fine. In other titles like Statistics, it'd just be a 6 column table and we haven't had any reported confusion with regards to following the content

**Comment by ww-openstax** [comment]
WiseWire fixed with vertical merging suggested solution
