### ISSUE TITLE
Business Computer Applications -- Exercises -- Multipart question not outputting correctly

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5237]
# Brief Description of Scenario
Exercise 04-02-BCA-CE01 is coded as a multipart question, each part is outputting as its own question with its own question number. 

![image](https://github.com/openstax/cnx-recipes/assets/89537088/0f0d1925-4fe6-4002-bf4a-999ae476caf7)

# Pattern of Occurrence 
This the first multipart question in BCA and so far the only multipart question in BCA.

# Acceptance Criteria
- [ ] can we adjust multi-part questions in this title to match OChem's where the stem is numbered and the parts are lettered (a, b, c, d)?
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-workplace-software-skills
- **collection slug:** computer-applications
- **ref/branch:**
- **chapter/section:** Chapter 4 / Case Exercises / Nickname 04-02-BCA-CE01
- **surrounding text:**

**Comment by wilkus27** [comment]
@lwtchu Checked with current main on `cookbook` and s.s branch on `styles`. It's already fixed:

![image](https://github.com/openstax/cnx-recipes/assets/40228854/e2027512-90aa-473f-9275-eefba12eaa63)

**Comment by wilkus27** [comment]
Example from above doesn't work. It needs more investigation. I'm moving issue back to the backlog.

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `sappy.symbology` & content from `main`


### Ch. 4
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/babf422a-3feb-40b5-bb7a-e173b4845b6a)

### Ch. 5


![Image](https://github.com/openstax/cnx-recipes/assets/12678235/e20c7841-ff93-4375-8cbb-00cec89bc78f)
