### ISSUE TITLE
Nursing Nutrition - Appendix A - URL should not display (PDF view)

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5239]
We received the following corrections
**GLOBAL for Table A1 on both pages: In the first column, the URL should not display.  The name of the app or website should display as a hyperlink, but the URL should not.** 

**PDF View:**
 ![Appendix_PDF_View](https://github.com/openstax/cnx-recipes/assets/86622862/981ba747-8019-490a-a1df-8be658239f2b)

**Web View:**
![Appendix_Web_view](https://github.com/openstax/cnx-recipes/assets/86622862/658e7a8e-1053-41ce-b025-4b97b8284060)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:**nutrition
- **ref/branch:**https://openstax-osbooksnursing-om7p9xrw6yq.ws-us104.gitpod.io/
- **chapter/section:** Appendix A
- **surrounding text:** Develops nutritionally sound meal plans with associated

**Comment by lwtchu** [comment]
@srm-openstax The URL displays due to the fact that the PDF goes to print so that folks who are reading the hard copy will have a URL to reference.
