### ISSUE TITLE
Introduction to Python Programming - code class="python inline-code" outputs new line in tables 

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5240]
# Brief Description of Scenario
`<code class="python inline-code">` outputs with new line break in` table//row/entry`

<img width="884" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/f417be09-b5ad-4161-a9ee-71a7e1dc98b7">

<img width="627" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/1ab7f264-58df-44b5-adaf-20fbddbeb2b8">

# Pattern of Occurrence 

# Acceptance Criteria

  
# Sample Mark-Up
```
 <table summary=" " id="table-00001">
    <title>Chapter 2 reference</title>
    <tgroup cols="2">
    <thead>
    <row>
    <entry>Function</entry>
    <entry>Description</entry>
    </row>
    </thead>
    <tbody>
    <row>
    <entry>abs(x)</entry>
    <entry>Returns the absolute value of <code class="python inline-code">x</code>.</entry>
    </row>
    <row>
    <entry>int(x)</entry>
    <entry>Converts <code class="python inline-code">x</code> (a string or float) to an integer.</entry>
    </row>
    <row>
    <entry>float(x)</entry>
    <entry>Converts <code class="python inline-code">x</code> (a string or integer) to a float.</entry>
    </row>
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** Chapter 02 / Section 9 / Module m00019 line 32
- **surrounding text:**

**Comment by lwtchu** [comment]
![Screenshot 2023-09-07 at 11 58 03 AM](https://github.com/openstax/cnx-recipes/assets/11299125/0b1e6163-4cf0-44c4-bf16-cb43e86fbeb5)
Issue present in PDF as well.

**Comment by yblock** [comment]
It looks like this when inspecting in web
<img width="495" alt="Screenshot 2023-09-07 at 12 56 20 PM" src="https://github.com/openstax/cnx-recipes/assets/5865292/0dfaefcc-0b48-493e-b96c-cbe240c62bac">

Table HTML:
`<td>Returns the absolute value of <pre data-type="code" class="python inline-code" data-lang="python">x</pre>.</td>`

List HTML:
`<li>Returns the absolute value of <code data-type="code" class="python inline-code" data-lang="python">x</code>.</li>`

There is also a ::marker:: on the list when previewing the inspected HTML, but not when editing it:
<img width="508" alt="Screenshot 2023-09-07 at 12 58 38 PM" src="https://github.com/openstax/cnx-recipes/assets/5865292/0b62c0d3-4af9-4b88-b845-7781267b59cb">


Para HTML:
`<p id="para-00011">Returns the absolute value of <code data-type="code" class="python inline-code" data-lang="python">x</code>.</p>`

Here's a link to the webview where I made these test changes:
https://rex-web-production.herokuapp.com/books/8d08a72f-5463-4856-b05c-58b0d65f5e61@6e0cb39/pages/2-9-chapter-summary?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20230828.164620

**Comment by ww-openstax** [comment]
@lwtchu We added the `<para>` container and that fixed it in webview and PDF. Please update the tagging legend.
<img width="403" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/b65e7899-8662-47d2-badd-790c9aa64460">

**Comment by lwtchu** [comment]
@ww-openstax Updated in the notes section in row 39
