### ISSUE TITLE
Introduction to Python Programming - Try It feature box - "Full Screen" link not functioning

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5241]
# Brief Description of Scenario
In the Try It feature box, clicking on the  "Full Screen" link has no effect on the page

![image](https://github.com/openstax/cnx-recipes/assets/89537088/b87f6443-9e6e-4063-b664-eac29d7f024e)

# Pattern of Occurrence 
All "Try It" feature boxes
 
# Acceptance Criteria

  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** Screenshot from Chapter 2 / Section 2
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax I believe they're supposed to take that off of the code runners - but I'll double check with @openstaxalina when she is back!

**Comment by openstaxalina** [comment]
Thank you both - OpenStax should be removing the full screen option via this card: https://github.com/openstax/ce/issues/2085

I will follow up with @ne-newton about this at our meeting later today. I defer to @lwtchu about whether to keep this card open.

**Comment by openstaxalina** [comment]
Full screen option has been removed - closing this issue.

<img width="782" alt="Screenshot 2023-09-14 at 5 17 18 PM" src="https://github.com/openstax/cnx-recipes/assets/7863733/1e162c48-d3fa-4dfc-8d54-c379d9b457d7">
