### ISSUE TITLE
Pharmacology for Nurses - Chapter 18 - Unfolding Case Studies

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5242]
Please fix column spacing in Unfolding Case Studies. First column should be horizontally flush with left margin of page; "Vital Signs" header should vertically be flush at top of column.  "Physical Assessment/Signs and Symptoms" header should be vertically flush at top of column (horizontally aligned with "Vital Signs' header. A horizontal rule/lign should be visible above the header text (as in the Word manuscript supplied to Production.)

**PDF view:**
![Chapter_18](https://github.com/openstax/cnx-recipes/assets/86622862/643899a9-b621-4fde-a891-5833a4be9be6)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:**pharmacology
- **ref/branch:**https://openstax-osbooksnursing-om7p9xrw6yq.ws-us104.gitpod.io/
- **chapter/section:** chapter 18/section 18.1
- **surrounding text:** Ms. Tran, what diagnosis should the nurse anticipate from

**Comment by lwtchu** [comment]
@srm-openstax This was a request to make the tables smaller due to the potential confusion with regards to the lines inside of the Unfolding Case Studies. 

As for the Vital Signs and Physical Assessment/Signs and Symptoms headers - those will need to be placed into a `<thead>` row.

**Comment by srm-openstax** [comment]
Thanks for your support
