### ISSUE TITLE
Introduction to Python Programming - code inside list/item not outputting correctly

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5245]
# Brief Description of Scenario
`<code>` inside of `<list><item>` does not output correctly in webview and in PDF

### Webview
![image](https://github.com/openstax/cnx-recipes/assets/89537088/7645959f-29c0-4f06-bc29-8d28ad62f252)

### PDF
<img width="497" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/fd6c9910-c008-466a-9001-172c689e220e">

# Pattern of Occurrence 

# Acceptance Criteria
- [ ] larissa added a `display="block"` in the CNXML which should add a `data-display="block"` to the XHTML
- [ ] please use that to enable block style tagging 
- [ ] i ONLY added it to the first example on the `colby` branch - please test with that. the`a = 1 b = 2` etc code should have line breaks
  
# Sample Mark-Up
```
<note class="practice-program" id="note-00008">
    <title>Different types</title>
    <list list-type="enumerated" id="list-00005">
    <item>Draw a memory diagram for the following code.
    <code class="python" lang="python">
    name = "Chocolate"
    length = len(name)
    price = 1.99
    lower = min(length, price)
    product = name
    name = name * 2
    </code></item>
    <item>Run the code on <link url="https://pythontutor.com/visualize.html#heapPrimitives=true">Python Tutor</link> to check your answer.</item>
    <item>Based on your diagram, answer these questions:
    <list list-type="bulleted" id="list-00006">
    <item>What <span class="blue-code">is</span> the type and value of each object?</item>
    <item>Which object does each variable reference?</item>
    </list></item>
    </list>
    </note>
```

# Location(s)
- **osbooks repo:**  osbooks-introduction-python-programming
- **collection slug:**  introduction-python-programming
- **ref/branch:**
- **chapter/section:** chapter 3 / section 3
- **surrounding text:**

**Comment by lwtchu** [comment]
![Screenshot 2023-09-15 at 12 13 00 PM](https://github.com/openstax/cnx-recipes/assets/11299125/274bc451-f2ed-475b-a2c4-70c76c682151)
Changing the HTML to` <pre>` works - need to figure out how to either override XSLT or put a class on it to have cookbook change the tag.

**Comment by Stackblocks** [comment]
List is displaying properly using updated code and the content from the colby branch."

# PDF
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/e4a52278-527d-47b0-adff-29e5073c4fc1)

# WEB
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/0c03c8c9-bc1c-4c2c-a873-ab54ee6d87c7)
