### ISSUE TITLE
In Drug Prototype tables - set both columns as equal / fixed width

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5246]
We received the below corrections. Please fix and suggest us.
In Drug Prototype tables, define/set both columns as equal / fixed width. (So, on a printed 8"x11" page, the vertical rule dividing the two columns should come at approximately the 3.125" (inch) point, because the horizontal rule is approximately 6.25" inches wide.  Table 18.13 (Drug Prototype) on p. 70 is currently the best example in this PDF proof of the most evenly divided Drug Prototype table

**Incorrect align Screenshot:**
![p55](https://github.com/openstax/cnx-recipes/assets/86622862/c3707d97-a53e-4f29-8dfa-d627c2f67a1c)

**correct align Screenshot - Table 18.13 (Drug Prototype) on p. 70**
![p70](https://github.com/openstax/cnx-recipes/assets/86622862/ee4c6357-229f-4da0-80e5-70204edc495f)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:**pharmacology
- **ref/branch:** testing-width (use this to avoid baking issue)
- **chapter/section:** Chapter 18 (Global)
- **surrounding text:** Drug Prototype Table: Enalapril (source: https://dailymed.nlm.nih.gov/dailymed/)

**Comment by lwtchu** [comment]
@srm-openstax  You will have to add the `<colspec>` 

```
 <colspec colname="col1" colnum="1" colwidth="2*"/>
 <colspec colname="col2" colnum="2" coldwidth="2*"/>
```

**Comment by lwtchu** [comment]
Message for developer: I'd like to maintain the proportion approach due to the various output formats that might not work well with pixel specific requirements. Please make sure the proportional colspec data is being taken into consideration in the styling of the table widths (might need to check if overall table widths are define in some way)

**Comment by srm-openstax** [comment]
Please find the additional table width issue examples.

**Ch_18_1Pharma_Table-18.9_CNXML**
![Ch_18_1Pharma_Table-18 9_CNXML](https://github.com/openstax/cnx-recipes/assets/86622862/08bb548e-b86c-4bc4-a945-7072a757be35)

**Ch_18_Pharma_Table-18.9 PDF view**
![Ch_18_1Pharma_Table-18 9](https://github.com/openstax/cnx-recipes/assets/86622862/7a0bf61b-dbc4-4662-8a80-08d9fcbdd16e)

**Ch_18_Pharma_Vital_Sign_CNXML**
![Ch_18_Pharma_Vital_Sign_CNXML](https://github.com/openstax/cnx-recipes/assets/86622862/a39f8201-1af8-455f-a29b-bc5edbb25a89)

**Ch_18_Pharma_Vital_Sign PDF view:**
![Ch_18_Pharma_Vital_Sign](https://github.com/openstax/cnx-recipes/assets/86622862/ed7bb1d3-a52c-43f8-8c91-b816b5d40663)

**Comment by wilkus27** [comment]
@lwtchu To be able to set proportion (in %) we need more information, not just ratio for single column. Is it possible to add additional attributes to `table` tag? I was thinking about `data-columns` and `data-ratio`.

For example:

**Table with two equal columns**
```
<table data-columns="2" data-ratio="1,1">
  <colgroup>
     <col data-width="1*" />
     <col data-width="1*" />
  </colgroup>
</table>
```

**Table with two columns, one is two times wider then another one**

```
<table data-columns="2" data-ratio="1,2">
  <colgroup>
     <col data-width="1*" />
     <col data-width="2*" />
  </colgroup>
</table>
```

**Comment by lwtchu** [comment]
@wilkus27 Those attributes wouldn't be allowed in the CNXML. We did something similar here https://github.com/openstax/cnx-recipes/issues/2776 - is there a discrepancy between this issue and the one from college success?

**Comment by wilkus27** [comment]
@lwtchu In College Success all tables, with defined proportions, have 4 columns, so what we did, we actually hard coded that `<col data-width="1*"/>` should have 25% width. Now, when we have other variations, we need to create a function in sass that will count width. To do that we need information how many columns are in table, and what are the proportions for each of them.

I thougth that maybe we can put these informations in the content, but it's ok, I am able to extract that data using cookbook and add proper attributes there.

**Comment by wilkus27** [comment]
@lwtchu There are two content problems.

1. `data-sm="./modules/m00095/index.cnxml:162:15"` - has empty `col` tag, without `data-width` defined
2. `data-sm="./modules/m00288/index.cnxml:71:7"` - `data-width` is set to 3 and 3 for two columns, it should be 1 and 1, since it gives the same effect

**Comment by lwtchu** [comment]
@wilkus27 okay - the 3 and 3 I think I set to test - if you're in the testing-width branch, that wouldn't be an issue in the main.

There's some other proportions in the book - are those widths also set?

**Comment by wilkus27** [comment]
@lwtchu I found and set:
- 1,1
- 1,3
- 2,3
- 1,2,1

Please, let me know if any other combination is needed

**Comment by lwtchu** [comment]
@wilkus27 sounds good. I'll let the vendor know that if there are more w'ell have to enable it. I didn't know it was that involved. Thank you for the context!

**Comment by MartaSztuka** [comment]
There is problem with content, issue can't be tested until it's fixed.
![Screenshot from 2023-09-25 10-43-13](https://github.com/openstax/cnx-recipes/assets/47241114/e8612345-d5c5-4355-8cbe-35603ef56db3)

**Comment by wilkus27** [comment]
Details are here: https://github.com/openstax/cnx-recipes/issues/5246#issuecomment-1731208518

**Comment by Stackblocks** [comment]
I'm also still getting an error response when I try and bake Pharmacology with `cookbook` and `ce-styles` set to the branches linked above. Bakes fine when both repos are on the main branch so there may be an issue with the suggested fix.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/19d7dc46-a83e-42b3-86fe-3c9ccbfda4cb)

**Comment by lwtchu** [comment]
@Stackblocks could you try with the testing-width branch - i think they added some more content in the main one that's causing it to break

**Comment by Stackblocks** [comment]
Still getting the error with the `testing-width` branch
 
https://github.com/openstax/cnx-recipes/assets/12678235/51a29d31-bcfb-416a-aa0b-de43cd171984

**Comment by lwtchu** [comment]
@wilkus27 we can park this on monday -- might be something missing in the content that the new fix might be needing

**Comment by wilkus27** [comment]
@lwtchu I think the first problem from here https://github.com/openstax/cnx-recipes/issues/5246#issuecomment-1731208518 is causing error.

**Comment by lwtchu** [comment]
@wilkus27 ah sorry i just saw that x___x ill fix

**Comment by lwtchu** [comment]
@Stackblocks i fixed the issue in the testing-width branch

**Comment by Stackblocks** [comment]
Was able to bake successfully with the updated data and the center line of the table is now properly centered.

![success](https://github.com/openstax/cnx-recipes/assets/12678235/f05f99d0-26e8-426b-93e3-385b14d9271d)
---
![CleanShot 2023-10-09 at 16 32 05](https://github.com/openstax/cnx-recipes/assets/12678235/72d70c25-156d-49fd-85a2-b5bb03e026c9)
