### ISSUE TITLE
Introduction to Python Programming - PDF & WEB - para class=centered-text not outputting centered text

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5247]
# Brief Description of Scenario
`<para class="centered-text">` was recently added to the tagging legend. It is not outputting centered text.

![image](https://github.com/openstax/cnx-recipes/assets/89537088/711d61ec-e6d6-4d19-a930-4f95410b12bc)

# Pattern of Occurrence 

# Acceptance Criteria
- [ ] we enabled the para level centered-text class a while back - can we make sure it's working in the PDF and webview as well? 
- [ ] text above is centered in PDF
- [ ] text above is centered in webview
  
# Sample Mark-Up
```
<para id="para-00011" class="centered-text">print("The unanimous Declaration of the thirteen united States of America, When in the Course of human events, it becomes necessary for one people to dissolve the political bands which have connected them with another, and to assume among the powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation.")</para>
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** Chapter 02 / Section 07 / Module m00017 
- **surrounding text:**

**Comment by lwtchu** [comment]
![Screenshot 2023-09-15 at 9 22 07 AM](https://github.com/openstax/cnx-recipes/assets/11299125/2a776404-dc73-489e-8ddc-0c23f96eddda)
Appears in PDF as well.

**Comment by wilkus27** [comment]
@lwtchu I'm wondering what effect do you expect. `centered-text` class is used to align text lines to the center, so it looks like that:

![image](https://github.com/openstax/cnx-recipes/assets/40228854/26d7cb75-8195-4f3a-8157-cce7e90357b3)

I'm assuming that what you want is to display entire code in the center, so something like that:

![image](https://github.com/openstax/cnx-recipes/assets/40228854/bb329fc1-9a6e-4bdb-bd47-16f4aeeb4627)

Am I right? If yes, first I think it's better to put this code in `pre` tag. `code` tag is used for inline code that is displayed within regular text. Here we have only code. And we need to create a new class to be able to display a whole block at the center.

Let me know, which solution is expected.

**Comment by lwtchu** [comment]
@wilkus27 I'll ask 🤔 I think you're correct that this is more of a display style vs centered text. We'll need the display attribute to work first which i think will be fixed by this https://github.com/openstax/cnx-recipes/issues/5245

**Comment by lwtchu** [comment]
@ww-openstax Hello! Can you look at Natalia's comment - centered text will display the way it does in the first screenshot, but I am not sure if that is correct. If we can get the "display" attribute working, it might do what is more correct (the second screenshot)

**Comment by openstaxalina** [comment]
@wilkus27 is correct - the second solution is expected. Here is the same content displaying as-desired in zyBooks' platform:

![Screenshot 2023-09-29 at 2 37 38 PM](https://github.com/openstax/cnx-recipes/assets/7863733/0f87ad65-95ab-4737-8945-432d37792c6c)

**Comment by lwtchu** [comment]
@wilkus27 if possible, could we apply this centered style to all code snippets inside of a `<para class="centered-text">`

**Comment by wilkus27** [comment]
@lwtchu As I mentioned in my previous comment, class `centered-text` is reserved for different type of styling. We need here another attribute. Issue #5245 is done and it looks like `data-display` is working properly, so maybe we can use it also here, as you suggested. But set it to `data-display="center"`.

**Comment by lwtchu** [comment]
@wilkus27 I cannot place data-display as an attribute in the CNXML - do you think it would be better if it was a `<div>`?

**Comment by lwtchu** [comment]
@ww-openstax Hello! Since there's only two instances, we're making the decision to set as regular code. Please remove centered tagging on the code snippet and leave it as a display block/regular code. Thanks!

**Comment by ww-openstax** [comment]
WiseWire removed centered tagging on the code snippet and left it as a display block/regular code.
