### ISSUE TITLE
[devcontainers] Apply new Ruby extension to Cookbook Devcontainer

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#5248]
Current Ruby extension has been archived https://github.com/rubyide/vscode-ruby/. It doesn't work with the newest (https://code.visualstudio.com/updates/v1_82) VSCode version. 

![image](https://github.com/openstax/cnx-recipes/assets/40228854/1754054b-7048-4c05-a57e-07781e1d5dae)

In Ruby extension repository there are recomendations for new extensions https://github.com/Shopify/ruby-lsp and https://github.com/Shopify/vscode-ruby-lsp. Try to apply them to Cookbook devcontainer. If they don't work, find other that will suit better with our project.

**Comment by wilkus27** [comment]
### Conclusions from investigation

`ruby-lsp` extension has most of the features from `vscode-ruby` and `solargraph`. So it's seems to be a good replacement.
There are some differences.

1. `Go to definition` feature

They are still working on it. For now only classes, modules and required files are supported. They have in plans adding also support for methods. Here are some disscusions about it:
- https://github.com/Shopify/ruby-lsp/issues/199
- https://github.com/Shopify/ruby-lsp/issues/899

It looks like it might be difficult to obtain. The goal of the `ruby-lsp` team is to use only Ruby to create their extesion, but this language has some limitations, e.g there is no type checking, so they have to create some workaround to make `Go to definition` work.

Here is also some explenation from one of the author https://remoteruby.com/221#t=0h17m37s

2. `YARD`documentation

`solargraph` provide `YARD` for code intelligence and type checking, and also for creating documentation (https://solargraph.org/guides/yard). I'm not sure how much do we need this :thinking: We are using YARD tags only in a small part of our project, mostly in files that were created at the beggining. 

Example 

![image](https://github.com/openstax/cnx-recipes/assets/40228854/b5656b42-5e9e-480f-94fa-94ef8637ee9f)

So we are not consequent in using it. I tried to run `yard server --reload`. Over 50% of methods are not documented :grimacing: 

```
[info]: No yardoc db found in .yardoc, parsing source before starting server...
[warn]: @param tag has unknown parameter name: node 
    in file `lib/kitchen/element.rb' near line 28
[warn]: @param tag has unknown parameter name: css_or_xpath 
    in file `lib/kitchen/element_enumerator_base.rb' near line 119
Files:         253
Modules:        95 (   71 undocumented)
Classes:       137 (   63 undocumented)
Constants:      56 (   50 undocumented)
Attributes:     64 (    0 undocumented)
Methods:       584 (  236 undocumented)
 55.13% documented
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require': cannot load such file -- webrick (LoadError)
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
        from /usr/local/bundle/gems/yard-0.9.34/lib/yard/server/webrick_adapter.rb:2:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
        from /usr/local/bundle/gems/yard-0.9.34/lib/yard/cli/server.rb:73:in `rescue in select_adapter'
        from /usr/local/bundle/gems/yard-0.9.34/lib/yard/cli/server.rb:66:in `select_adapter'
        from /usr/local/bundle/gems/yard-0.9.34/lib/yard/cli/server.rb:48:in `run'
        from /usr/local/bundle/gems/yard-0.9.34/lib/yard/cli/command.rb:14:in `run'
        from /usr/local/bundle/gems/yard-0.9.34/lib/yard/cli/command_parser.rb:72:in `run'
        from /usr/local/bundle/gems/yard-0.9.34/lib/yard/cli/command_parser.rb:54:in `run'
        from /usr/local/bundle/gems/yard-0.9.34/bin/yard:13:in `<top (required)>'
        from /usr/local/bundle/bin/yard:25:in `load'
        from /usr/local/bundle/bin/yard:25:in `<main>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require': cannot load such file -- rack (LoadError)
Did you mean?  racc
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
        from /usr/local/bundle/gems/yard-0.9.34/lib/yard/cli/server.rb:70:in `select_adapter'
        from /usr/local/bundle/gems/yard-0.9.34/lib/yard/cli/server.rb:48:in `run'
        from /usr/local/bundle/gems/yard-0.9.34/lib/yard/cli/command.rb:14:in `run'
        from /usr/local/bundle/gems/yard-0.9.34/lib/yard/cli/command_parser.rb:72:in `run'
        from /usr/local/bundle/gems/yard-0.9.34/lib/yard/cli/command_parser.rb:54:in `run'
        from /usr/local/bundle/gems/yard-0.9.34/bin/yard:13:in `<top (required)>'
        from /usr/local/bundle/bin/yard:25:in `load'
        from /usr/local/bundle/bin/yard:25:in `<main>'
```

I'm note sure whether we are using other features of YARD. If we decide that we need this, I think we can either install solargraph anyway, but disable most of its features, so it won't have conflicts with `ruby-lsp` or use YARD independently. There is a seperate extension for it https://marketplace.visualstudio.com/items?itemName=pavlitsky.yard, but as I see last update was done 2 years ago, so I'm not sure about it. Of course we can use it also without any extension (https://yardoc.org/).

**Comment by kswanson33** [comment]
hey! thanks for doing such a deep dive, this is awesome. 

regarding YARD, i wonder if we cared more about it back when kitchen was its own registered ruby package? [this](https://www.rubydoc.info/gems/openstax_kitchen/17.1.0/toplevel) is where YARD docs are/were generated. i don’t think they’ve been updated since we merged kitchen & recipes into cookbook. 

on one hand, it’s not bad idea for us to keep writing documentation comments in YARD-compatible markdown, since 1) it’s a clear format, and 2) it sets us up for more success if we find a use for YARD again.

on the other hand, unless we decide to ship kitchen as a library again, documentation isn't a priority. you're right that coverage is low, and i can't think of a strong reason to prioritize increasing it right now. additionally, the YARD generation process is one of the most time-consuming steps of building the container, and it doesn’t have anything to do with supporting what we usually use the container for (i.e. development). so overall i would say we can stop/pause maintaining the way we generate YARD docs as a regular part of our workflow, while continuing to write YARD-compatible comments for base kitchen changes.

**Comment by wilkus27** [comment]
@kswanson33 Thank you for your feedback! It's a really good point :+1: In this case, do you think we need any extension that will support YARD? Uninstalling solargraph. doesn't unistall YARD, I think it is also a part of rake gem

![image](https://github.com/openstax/cnx-recipes/assets/40228854/944eb1f8-f400-4e40-9d04-2c0ed23796fe)
(https://www.rubydoc.info/gems/yard/file/README.md)

So we can still use it, but do we need any extra helpful features that extensions might provide for us?

**Comment by wilkus27** [comment]
But also, as I mentioned in my first comment, I can try to install `solargraph` together with `ruby-lsp`. My only concern is that they have common features. We can disable some of them, but I'm afraid that even then there might be some conflicts and at the end of the day none of the extension will be working fully properly.

**Comment by lwtchu** [comment]
@jbwilson8 @LostMojo adding both to the assignee field so that yall can review before we park this on thursday

**Comment by lwtchu** [comment]
Notes from parking lot
@jbwilson8 has always had issues with solargraph and would comment out - would prefer ruby-lsp
@kswanson33 is fine giving up with the half that ruby-lsp is missing anyway cause it wasn't always working

**Comment by Stackblocks** [comment]
No issues reported by the developers following the change. Closing out the issue.
