### ISSUE TITLE
Update CE-Styles Node version to Node 20

### ISSUE THREAD

**Issue by LostMojo** [openstax/cnx-recipes#5249]
[CE-Style's node version (14.16.1)](https://github.com/openstax/ce-styles/blob/main/Dockerfile#L43) is no longer being supported! It's very old, and Node is currently on version 20. Six versions ahead of where we're at.

Node 20 isn't 100% backwards compatible, so this will need to be **_thoroughly tested_**.

**Comment by kswanson33** [comment]
node just supports the linter, so we only need to confirm that that still works. it won't affect how styles build 🎉

**Comment by LostMojo** [comment]
Tested! Branch builds main book styles, webview, and builds in enki as well
