### ISSUE TITLE
organic chemistry - webview - support inline media in examples

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5250]
# Brief Description of Scenario
![image](https://github.com/openstax/cnx-recipes/assets/11299125/5e1ea7de-e561-4e19-ad81-19814c052f5a)

I think this is due to inline images not being supported in examples specifically so it orphans the period

# Pattern of Occurrence 
Inline media works elsewhere, just not working in examples

# Acceptance Criteria
- [ ] in line image works in example
- [ ] period and image will no longer be orphaned
  
# Sample Mark-Up
```
<example id="exam-00001">
<title>Drawing Resonance Forms for an Anion</title>
...
<para id="para-00007"><title><span class="red-text">Strategy</span></title> Look for three-atom groupings that contain a multiple bond next to an atom with a <emphasis effect="italics">p</emphasis> orbital. Then exchange the positions of the multiple bond and the electrons in the <emphasis effect="italics">p</emphasis> orbital. In the carbonate ion, each singly bonded oxygen atom with three lone pairs and a negative charge is adjacent to the <m:math><m:mrow><m:mtext>C=O</m:mtext></m:mrow></m:math> double bond, giving the grouping <media alt="Condensed structure of O with two nonbonding pairs double-bonded to C, which is single-bonded to another O with three nonbonding pairs and a negative charge." display="inline"><image mime-type="image/jpeg" src="../../media/OChem_02_06_006.jpg"/></media>.</para>
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:** main
- **chapter/section:** Ch. 2.6 - Worked Example 2.2 
- **surrounding text:**

**Comment by Stackblocks** [comment]
Media displaying inline in worked example 2.2 with the code from the fix PR.



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/f20ea43d-c28f-4b87-b4a1-7e9af4000996)
