### ISSUE TITLE
community population health - pdf - missing rule for this column

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5251]
We are coding as per the tagging legend guideline but the column rule missing issue is not resolve at our end.

**PDF view**
![rule](https://github.com/openstax/cnx-recipes/assets/86622862/482cdeab-a072-445c-bdb2-aadd297397e5)

**Web view**
![Webview](https://github.com/openstax/cnx-recipes/assets/86622862/b600b954-61b4-4d91-9282-b2a59d6e52d7)

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:**community-population
- **ref/branch:**https://openstax-osbooksnursing-om7p9xrw6yq.ws-us104.gitpod.io/
- **chapter/section:** Chapter 15 /Table: 15.10
- **surrounding text:** reinforcing factors related to following health guidance.

**Comment by lwtchu** [comment]
# Acceptance Criteria 
The mark up appears correct on my end, please double check table styling and if there's a way to account for cells that span multi rows

**Comment by Stackblocks** [comment]
Displaying OK with the content from `main` and the code from `5251-missing-rule`

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/4c27ede3-1683-4579-8c86-9510c93a32f2)

**Comment by srm-openstax** [comment]
Thanks, This issue has been resolved.
