### ISSUE TITLE
Polish books - add lang attribute to index terms

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#5252]
# Brief Description of Scenario

Foreign terms that appear within modules have attribute `lang` that helps screen readers read words properly depends on the language.

![image](https://github.com/openstax/cnx-recipes/assets/40228854/63ea6ffd-2596-4b1c-9762-dc11d8d8fe56)

When index with foreign terms is created only text of the term is copied. Add `lang` attribute to index terms.

![image](https://github.com/openstax/cnx-recipes/assets/40228854/41f4eb67-1eb2-4119-b817-cf77eec3b83a)

# Pattern of Occurrence 

Appears in all Polish books. (Note: in Fizyka terms within modules don't have `lang` attribute yet. It'll be added in the future. But functionality should be applied there as well).

# Acceptance Criteria

Screen reader reads terms in index with foreign terms in a proper way based on their language.
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-mikroekonomia, https://github.com/openstax/osbooks-psychologia
- **collection slug:**
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
##### Mikroekonomia
![Screenshot from 2023-10-02 15-29-16](https://github.com/openstax/cnx-recipes/assets/47241114/2ae36ef7-e1df-4947-817c-8c681ec959bc)
##### Psychologia
![Screenshot from 2023-10-02 15-32-16](https://github.com/openstax/cnx-recipes/assets/47241114/7e3ff638-da90-4cc2-9275-4ff248179e89)
##### Makroekonomia

![Screenshot from 2023-10-02 15-38-30](https://github.com/openstax/cnx-recipes/assets/47241114/da764c10-c3e3-463a-8bb3-998c4371228b)
