### ISSUE TITLE
nursing-external - pdf - remove two column formatting for Review Questions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5253]
![Screenshot 2023-09-20 at 12 22 06 PM](https://github.com/openstax/cnx-recipes/assets/11299125/1fb111e6-9ebd-4d12-91eb-2f2f79c3c716)

# Brief Description of Scenario
Review Questions have MC questions that are injected - those are allowed to break for space savings in contemporary math. so please remove from two column as it's a bit confusing

# Pattern of Occurrence 
ONLY review questions section needs to be 1 column

# Acceptance Criteria
- [ ] `class="review-questions"` section is 1 column
  

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** nutrition, pharmacology
- **ref/branch:** main
- **chapter/section:**  review questions
- **surrounding text:**

**Comment by Stackblocks** [comment]
Review questions showing as a single column following update, I do want to get some of these breaks checked out by LC when she's back from vacation but that can be a separate issue.

# Nutrition

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/ba5c6048-f0f2-4e94-8f4d-9be610229cc1)

# Pharma

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/613f2d38-ff7c-4bad-9dda-2c879671a892)

---

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/b49f56ec-f42a-40bd-aecd-0017613cdd11)

**Comment by lwtchu** [comment]
@Stackblocks unfortunately, we can't have page break rules at a more granular level at the moment - injected exercises also cannot break as it'll cause widespread white space issues in contemporary math and other titles w multi part questions

**Comment by srm-openstax** [comment]
issues has been resolved
