### ISSUE TITLE
nursing-external (possibly other books) - Link Attributes Not Being Added Automatically to External Links

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#5255]
# Context

SRM let us know that external links are not opening in a new window in webview. External links should automatically be getting ` target="_blank"` and `rel="noopener nofollow"` per https://github.com/openstax/cnx-recipes/issues/4319.

# New specifications or link to documentation cards
See link above

## Impact 
This was noted by SRM for all three of their nursing books, but might be happening in all nursing titles (including Wisewire's 5).

15.4 in Pop Health
Search "South-East Asian Healthy Cities Network"
[Web View](https://rex-web-production.herokuapp.com/books/9331ec14-7ea7-4415-a8dd-ee34f0c5f9c4@1b32891/pages/15-4-barriers-and-opportunities-for-health-promotion-and-disease-prevention?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20230925.141344)

18.1 in Pharmacology 
Search "interactive library on the anatomy of blood pressure"
[Web View](https://rex-web-production.herokuapp.com/books/2f805b43-bce4-4379-add2-4fbf46700e4c@adcc62c/pages/18-1-hypertension-and-angina?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20230925.141344)
 
11.2 Nutrition
Search "BMI Calculator"
[Web View](https://rex-web-production.herokuapp.com/books/7db4d55f-5c0e-4c05-8b72-841685444165@956af6b/pages/11-2-plan-nutritional-strategies-to-impact-cardiovascular-wellness?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20230911.175418)

# Acceptance Criteria
- [ ] properly formed external links automatically get the attributes `target="_blank"` and `rel="noopener nofollow"` during baking/generating web previews on CORGI

## Content
Please see links above

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:**
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:**

**Comment by srm-openstax** [comment]
Thanks for your support. External links issues resolved.
