### ISSUE TITLE
Introduction in polish books

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#5258]
Introduction isn't translated should be Wprowadzenie do rozdziału. Issue is visible only in first chapters in both books, due to lenght of the modules.
Makroekonomia
![Screenshot from 2023-09-28 10-48-06](https://github.com/openstax/cnx-recipes/assets/47241114/c6aed999-7c6c-4838-8cd8-8fdae52dcb24)
Mikroekonomia
![Screenshot from 2023-09-28 11-30-02](https://github.com/openstax/cnx-recipes/assets/47241114/e1ecfd06-399f-4a5c-9593-a11567733dee)

**Comment by wilkus27** [comment]
@openstaxalina we discussed this with team. This is a quite small problem, so we decided to publish PDF as is, and fix it in the next release.

**Comment by openstaxalina** [comment]
Noted, thank you @wilkus27 !

**Comment by MartaSztuka** [comment]
#### PASSED
##### Makroekonomia
![Screenshot from 2023-10-02 15-59-05](https://github.com/openstax/cnx-recipes/assets/47241114/2d4f883e-b139-4bc1-82c0-8808a39a57e9)
##### Mikroekonomia
![Screenshot from 2023-10-02 16-01-09](https://github.com/openstax/cnx-recipes/assets/47241114/72ea2217-a88c-405d-afb6-a3e2045e36a2)
