### ISSUE TITLE
Introduction to Python Programming - code class="python inline-code" outputs new line in section/title

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5259]
# Brief Description of Scenario
`<code class="python inline-code">` outputs with new line break in `section/title`

![image](https://github.com/openstax/cnx-recipes/assets/89537088/dfaae911-cb56-44bd-af02-be98198efd12)

# Pattern of Occurrence 
only one instance so far

# Acceptance Criteria
- I think this is semi related to #5240 but since this is in a title, I can't nest this further in order for the inline to kick in. 
- Please enable `inline-code` in titles.
  
# Sample Mark-Up
```
<section id="sect-00003">
    <title>Using <code class="python inline-code">sort()</code> and <code class="python inline-code">reverse()</code></title>
    <para id="para-00007">Python provides functions for arranging elements in a list.
    <list id="list-00002">
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** Chapter 09 / Section 3 / Module m00068 line 47
- **surrounding text:**

**Comment by kswanson33** [comment]
![Image](https://github.com/openstax/cnx-recipes/assets/26280712/f658d365-872b-47e7-a78e-4cc6daf5c0f6)

**Comment by lwtchu** [comment]
@kswanson33 is there a way to retain the code typography for these?

**Comment by kswanson33** [comment]
the fix in this PR is not related to code typography -- here's how the book displays without a typography fix

<img width="435" alt="image" src="https://github.com/openstax/cnx-recipes/assets/26280712/f16b6c1c-ff05-4ebd-8c6f-32968eaf70da">


here it is in web styles

<img width="711" alt="image" src="https://github.com/openstax/cnx-recipes/assets/26280712/8e8ab7f4-0646-4548-962e-3688f559092a">

if the typography is a problem, it might either be a quirk of my browser, or a separate bug

**Comment by MartaSztuka** [comment]
#### Passed
##### PDF
![Zrzut ekranu z 2023-10-20 11-07-09](https://github.com/openstax/cnx-recipes/assets/47241114/bdb9cdba-c47a-4ee9-b0c8-1e9e92ff74ac)
##### webview
![Zrzut ekranu z 2023-10-20 11-17-18](https://github.com/openstax/cnx-recipes/assets/47241114/16856b82-fd41-4cec-b032-0116393477b2)
