### ISSUE TITLE
nursing-external - population health - box style

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5260]
We received box style in chapter 17 from population health. We reviewed entire tagging legend there is no coding instruction about **"BOX"**

Creation of Box text for Population Health.
Similar style to College Physics but using the Nursing style guidelines.
Black or blue box is okay

**Input view:**

![box](https://github.com/openstax/cnx-recipes/assets/86622862/cde89ab3-6a78-4c66-8684-14d74d2bc88c)

## Acceptance Criteria
- [ ] please use #4746
- [ ] color B3: `#00819A` 
- [ ] title will come from `<title>` 
- [ ] class `<note class="boxed-feature">`
- [ ] DO NOT put numbering

## Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** community-population
- **ref/branch:** new-feature
- **chapter/section:** 1.2 is where the sample is
- **surrounding text:** search for "Lorem ipsum"

**Comment by kswanson33** [comment]
![image](https://github.com/openstax/cnx-recipes/assets/26280712/9c96bba8-e6e8-4be2-aece-0285acd4dadd)

**Comment by kswanson33** [comment]
for QA: changes are on both cookbook & styles. the branch name is `boxed-feature-nursing` in both places.

**Comment by MartaSztuka** [comment]
@kswanson33  book can't be tested due to content issue. 
In Nutrition w in table `data-sm="./modules/m00006/index.cnxml:32:1"` there is column without `data-width`

**Comment by lwtchu** [comment]
@MartaSztuka i adjusted the tgroup number to 2 so it doesn't think there's one missing. can you try again :eyes:

**Comment by Stackblocks** [comment]
New box matches up with the specs from https://github.com/openstax/cnx-recipes/issues/4746.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/17113763-6b30-4b0a-83a0-bdf926a91996)

**Comment by srm-openstax** [comment]
Thankyou, This issue has been resolved.
