### ISSUE TITLE
pl-marketing - create recipe

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#5261]
Create recipe for Polish version of Marketing textbook.
Epic: https://github.com/openstax/cnx-recipes/issues/5269

**Comment by wilkus27** [comment]
### Information for tester

PRs with recipe and style will be merged without testing now.
Please test it when one Unit of content be ready.

**Comment by wilkus27** [comment]
Content is ready for testing https://github.com/openstax/osbooks-pl-marketing

**Comment by MartaSztuka** [comment]
#### PASSED

##### Preface
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/2763f34d-f344-46f7-8836-e94c0a29eb52)

##### Unit
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/da8a1d3c-c6ec-4f6b-9f4e-9ea044aebb9a)

##### Wprowadzenie
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/14c559f5-dc84-4a54-9884-92f085170f59)


##### Moduł
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/34e21cb8-9707-4e65-92cc-dc91f3a5c53e)

##### Notatka
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/8a323d4d-0f84-4a38-a6c0-21681c68ec50)

##### Ilustracja
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/0b61e21e-efe2-44a9-8e63-b740c10a80fa)

##### Tabela
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/9f8a0400-68e7-4345-ad8d-72a0022cc9e2)

##### Sprawdź wiedzę
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/a0e8d5e5-7f79-4a66-99e0-1a256cd3d4fd)

##### Podsumowanie
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/158de3a4-c6f0-44d6-83db-fc7182f34666)

##### Kluczowe pojęcia
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/bd5b54ce-3916-422e-b922-054ed4044917)

##### Sekcje na końcu rozdziału
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/9dfe4c8b-b953-4dc1-b697-b6e7cdc0a2b8)
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/8c9a6536-9b27-480d-bc90-0406b9f43bc7)
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/0b1b9cae-f2f6-47c1-925e-40e85416588f)

##### Bibliografia
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/44b50836-933c-4de0-8999-200ae08f5666)

##### Rozwiązania zadań
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/ebf9e8d2-2fee-470c-bebe-26feae0401e2)

##### Skorowidz
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/bf0b5d65-86b7-424d-a7ec-6acca7abcf67)
