### ISSUE TITLE
Introduction to Python Programming - Ch15 images inside tables output too small in webview too big in PDF

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5265]
# Brief Description of Scenario
For 15.3, 15.4, 15.5 the images provided by zybooks need to be processed by OSX in order to output correctly inside tables.
This issue was referenced in 10/10 OSX/WW weekly status meeting
This issue was referenced in the 9/20 email from Alina to Jordan "Content Queries on Chapter 15"
### Webview
![image](https://github.com/openstax/cnx-recipes/assets/89537088/8bb43daa-1734-431c-871b-5b13bf8e1c04)
### PDF
<img width="596" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/9a6fba0b-abb9-49e0-b1ba-f531bc1e96d3">

# Pattern of Occurrence 
Images in 15.3, 15.4, 15.5

# Acceptance Criteria

  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** Chapter 15 / Section 3; Chapter 15 / Section 4; Chapter 15 / Section 5;
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax Could you set these as a regular CNXML table like the other tables in the other tables in the ch 15.

**Comment by ww-openstax** [comment]
Yes, we have now set these as a regular CNXML table. We have logged #5268 to fix formatting issues. Closing this ticket.
