### ISSUE TITLE
Business Computer Applications -- Runninghead outputs on chapter opener page

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5266]
# Brief Description of Scenario
Runninghead outputs on chapter opener page. Remove runninghead from chapter opener pages.

### PDF
![image](https://github.com/openstax/cnx-recipes/assets/89537088/bb173240-0dd4-4841-848a-cc315349fd83)

# Pattern of Occurrence 
All chapter openers

# Acceptance Criteria
- [ ] is it possible to only remove this on the intro page (first page where the splash is?) if it's too difficult (more than 5 hours of work), please let me know.
- [ ] apply to entire theme - we don't need this to be book specific

# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-workplace-software-skills
- **collection slug:** computer-applications
- **ref/branch:**
- **chapter/section:** all chapter opener pages
- **surrounding text:**

**Comment by Stackblocks** [comment]
Displays OK with the updated code from openstax/ce-styles#344



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/ad4d8312-4bc3-4b3a-bf57-617a6ca0c90e)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/292f4209-f229-4b08-bfce-a7bed9ba2ea0)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/39642c1f-488d-4f9b-bb2b-2bedb531c135)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/8f86e432-2c99-4304-b029-b1acf65cbc0c)
