### ISSUE TITLE
community population (nursing-external) - Item List After (9) Alignment

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5267]
Please fix in web view so that feedback for item 10 lines up with feedback for the other items (in current web view, there is an awkward indent). Align by decimal.

**WEB View:**
![RVQ](https://github.com/openstax/cnx-recipes/assets/86622862/e2b79563-1a2c-479e-a343-a0e8e9fba80c)

## Acceptance Criteria
- align by periods, numbers are right aligned to the periods
- right text should be aligned together (left aligned) and evenly spaced from periods

## Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** community-population
- **ref/branch:**  https://openstax-osbooksnursing-om7p9xrw6yq.ws-us105.gitpod.io/
- **chapter/section:**  review-questions
- **surrounding text:** verbal lecture, discussion, music, podcasts, and reading aloud

**Comment by kswanson33** [comment]
<img width="862" alt="image" src="https://github.com/openstax/cnx-recipes/assets/26280712/96c29307-58b1-474a-ac70-7300f9335560">

added specs:

- increased width of exercise number to `30px`
- exercise numbers are right-aligned

impact: webview exercises and solutions with linked numbers

**Comment by kswanson33** [comment]
branch: ce-styles `web-number-align`

**Comment by Stackblocks** [comment]
Displaying correctly with updated code from openstax/ce-styles#351

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/810e530e-b0ed-44b9-ace1-527142861473)
