### ISSUE TITLE
Introduction to Python Programming - Ch15 unnumbered tables inside tables / PDF output needs formatting

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5268]
# Brief Description of Scenario
Related to #5265 
For Ch 15 tables inside table:

- See screenshots of PDF output `<table class="unnumbered">`
- Table 15.4 in Section 15.3 is bleeding off page

![image](https://github.com/openstax/cnx-recipes/assets/89537088/21950d8f-02c9-412a-851d-3827f58783b3)

# Pattern of Occurrence 

# Acceptance Criteria
- [ ] Please enable generic table styling for nested tables
- [ ] We will rework the content if it falls off the page, but please just enable table styling for now
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:**  introduction-python-programming
- **ref/branch:**
- **chapter/section:** Chapter 15 / Section 3
- **surrounding text:**

**Comment by kswanson33** [comment]
![Image](https://github.com/openstax/cnx-recipes/assets/26280712/549d3a18-478d-4ad2-8c6e-ecb2077e11ee)

**Comment by kswanson33** [comment]
hello QA: the fix is on cookbook branch `unnumbered-table-python`

**Comment by Stackblocks** [comment]
The nested lists are now showing properly, but 15.4 is still overflowing the right side of the page in the PDF. 

@kswanson33 Is the table overflow something that can easily be fixed as part of this issue or should it be spun off into its own?

# Resolved
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/52bd6c66-c26b-4212-9f2a-8727b8cb1848)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/0bed41a8-955b-4704-8e4d-e1d76484b9a5)

# Errors
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/81605931-f587-42af-b4f3-20e67cd84530)

**Comment by lwtchu** [comment]
@Stackblocks I'll open a separate card later for the overflowing tables.
