### ISSUE TITLE
Polish Marketing - references

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#5270]
Apply new type of references. They are built like footnotes, but has additional class "reference".
Styles should be the same as for endnotes https://github.com/openstax/cnx-recipes/issues/2745.

Epic: https://github.com/openstax/cnx-recipes/issues/5269

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2023-10-24 16-56-18](https://github.com/openstax/cnx-recipes/assets/47241114/bf23715d-6221-4663-bb2a-f9dba658ba9e)
