### ISSUE TITLE
neuroscience - splash image

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5273]
documentation: #1075

**Comment by jbwilson8** [comment]
Accidentally merged issue into main after code review. Code change has been reverted nd will be re-commited to ensure it goes through the QA testing.

**Comment by MartaSztuka** [comment]
#### PASSED


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/12209203-7462-483d-b472-2b870bb4c78e)
