### ISSUE TITLE
neuroscience - table and figure caption/title/number

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5274]
documentation: #1081

**Comment by MartaSztuka** [comment]
@lwtchu Table caption should have bigger top margin
##### Tables
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/7413c359-118d-4375-81a6-7e719c04ff3b)
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/6020c128-03b0-493e-8f7f-94a6bff34d7a)

##### Figures
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/d43b858c-d2f3-48f4-8d45-09c3bd48b628)

**Comment by jbwilson8** [comment]
@MartaSztuka the padding/margins for the tables will be handled with [this card](https://github.com/openstax/cnx-recipes/issues/5278).
