### ISSUE TITLE
neuroscience - table (generic) design

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5278]
Documentation #1080
Table bottom line: B2: `#0074BC`

**Comment by ckline-tryptic** [comment]
@lwtchu style is correct (see screenshot), but the [content table](https://github.com/openstax/osbooks-neuroscience/blob/74b95fb9f451e22510f364d5dbaa567fb56b1cdc/modules/m00002/index.cnxml#L56-L61) seems to be missing a header

**Comment by lwtchu** [comment]
@ckline-tryptic thanks! i'll let a cm know ✨ and we'll get it fixed

**Comment by Stackblocks** [comment]
Tables displaying as styled in PDF with this change.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/185b3e9a-473d-4a10-b920-068e5ae3842b)

**Comment by lwtchu** [comment]
@ckline-tryptic 👋 hello! this is ready to merge
