### ISSUE TITLE
neuroscience - neuroscience across species feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5280]
class: `across-species`
documentation #3966
title: Neuroscience Across Species
has a subtitle: yes
icon: [carnival-biodiversity.svg](https://drive.google.com/file/d/1aC8sSRKgup2O05IT2u5XQ892geEK4pw3/view?usp=sharing)
color: O1: `#F37541`
mostly text, might have a figure

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2023-11-10 10-04-08](https://github.com/openstax/cnx-recipes/assets/47241114/e3299889-8c31-4426-9c44-b19b00e282bf)
