### ISSUE TITLE
neuroscience - neuroscience in the lab feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5281]
class: `inthe-lab`
documentation #3966
title: Neuroscience in the Lab
has a subtitle: yes
icon: [carnival-scientific.svg](https://drive.google.com/file/d/1OkkZLvn5qH3lsGbbyjZ2NHBzE5vcHgeu/view?usp=share_link)
color: B1: `#0DC0DC`
mostly text, might have a figure

**Comment by MartaSztuka** [comment]
#### PASSED


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/c7338ad6-e1ce-432e-b80c-99d7f1f1c458)
