### ISSUE TITLE
neuroscience - developmental perspective feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5282]
Documentation #4746

Class: `developmental-perspective`
Title: Developmental Perspective
Subtitle: Yes
Color: P2: `#651C72`

**Comment by MartaSztuka** [comment]
note isn't styled, is it on different ref branch than main?

![Image](https://github.com/openstax/cnx-recipes/assets/47241114/0cc9d7f0-7006-4aef-9ef5-57ad2c210087)

**Comment by jbwilson8** [comment]
@MartaSztuka Yes, the styles changes should be on the `5282-developmental-perscpective-feature` branch

**Comment by jbwilson8** [comment]
Issue has been resolved. Feature is now styled properly: 

![Image](https://github.com/openstax/cnx-recipes/assets/26155528/7a86aae1-f4d0-4b7a-990f-9ebdc0eb06fa)

**Comment by Stackblocks** [comment]
Element showing up with proper spacing.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/1f7e4497-dc11-4203-a61c-2c9b522e2e26)
