### ISSUE TITLE
Business Computer Applications -- In PDF, URL outputs as a link but NOT coded as a link

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5287]
# Brief Description of Scenario
The following URL: "`www.yourwebsite.com`" outputs in PDF as a clickable link. But it is not coded as a link and it is not intended to be a clickable link. Is there some way to suppress the linking? 
In Webview it is not a clickable link -- as intended.
![image](https://github.com/openstax/cnx-recipes/assets/89537088/c127bd52-ff58-4954-b57e-e123008a35a2)

# Pattern of Occurrence 
Only one instance

# Acceptance Criteria

  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-workplace-software-skills
- **collection slug:** workplace-software-skills
- **ref/branch:**
- **chapter/section:** Chapter 2 / Section 2 
- **surrounding text:** The website will need to be published, a domain name purchased (e.g., `www.yourwebsite.com`), and it hosted through a paid service such as GoDaddy.

**Comment by lwtchu** [comment]
@ww-openstax This is usually done by the PDF reader -- we don't have control over it as it detects would-be links and makes them clickable. So long as they're not encoded as links, I think it'll be okay as it won't show up as clickable on the web or in other less sophisticated readers.
