### ISSUE TITLE
neuroscience - generic boxed feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5288]
Documentation #4746

Class: `boxed-feature`
Title: pulled from `<title>`
Subtitle: NO
Color: B2: `#0074BC`

**Comment by MartaSztuka** [comment]
#### PASSED


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/bca3656c-e34e-4c17-817d-9e5939f2cb0d)
