### ISSUE TITLE
Business Computer Applications -- Multi-part assessment webview outputs A. B. C. as link to nothing

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5289]
# Brief Description of Scenario
Related to #5237 
Multi-part assessment outputs A. B. C. as link to answer key but there is no answer key
Also, they should NOT output as Bold text. They should output as Roman text to match formatting of other assessments.
Nickname: 04-02-BCA-CE01
### Webview
![image](https://github.com/openstax/cnx-recipes/assets/89537088/9e5800e6-80a8-4194-a254-80993bd439de)

# Pattern of Occurrence 
All multi-part assessments

# Acceptance Criteria
- leave the letters as bold for now
- remove the links
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-workplace-software-skills
- **collection slug:** workplace-software-skills
- **ref/branch:**
- **chapter/section:** Chapter 4 / Case Exercises 43 / Nickname: 04-02-BCA-CE01
- **surrounding text:**

**Comment by wilkus27** [comment]
### Information for tester

Has impact also on Organic Chemistry

**Comment by MartaSztuka** [comment]
ABCs are not links, but still are bold
![Zrzut ekranu z 2023-11-09 12-11-04](https://github.com/openstax/cnx-recipes/assets/47241114/f4a2a39f-f3ae-415b-8040-53a52d0516db)

**Comment by wilkus27** [comment]
@lwtchu Just to make sure. This will have an impact on Organic Chemistry:

![image](https://github.com/openstax/cnx-recipes/assets/40228854/358e2580-691e-4d92-a1ca-5ab3f12da475)

Is it ok to remove bold in both places?

**Comment by lwtchu** [comment]
@wilkus27 Let's keep it as bold for now - I'll update the A/C

**Comment by ww-openstax** [comment]
Final full-book PDF delivered to OSX on 11/9/23
