### ISSUE TITLE
nursing external - add warning for columns

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#5290]
Nursing External contains tables with fixed width. The proportion is set by `colwidth` attribute 

```
<colspec colname="col1" colnum="1" colwidth="1*"/>
```

If attribute is missing error appears in the process of baking and PDF can't be built.
Set a warning instead in recipe, so it won't break PDFs.

~~It also breaks when `<tgroup col="2">` is declared with no `<colspec>` at all~~ Larissa confirmed this should be ok. But we can test.

Previous issue for tables with fixed width: https://github.com/openstax/cnx-recipes/issues/5246

**Comment by lwtchu** [comment]
Test content
branch: https://github.com/openstax/osbooks-nursing-external-bundle/tree/testing-broken-tables
surrounding text: American College of Cardiology and American Heart Association’
has a table with colspec w no colwidth

surrounding text: lists common nitrates and typical routes and dosing for adult clients.
has tables with no colspec at all

**Comment by Stackblocks** [comment]
PDF completes baking and has no visual irregularities, warning displays properly in the bake log. 🎉

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/c18b70b8-0c72-40a0-bc11-eef3dfe2ebc6)
