### ISSUE TITLE
Nursing Internal -- EOC collation of References // remove duplicates

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5291]
# Brief Description of Scenario
For the end of chapter collation of References, output includes duplicate References. If a Reference is included in more than one module, each instance of the Reference is being output in the EOC References collation. This results is duplicate References in the collation.
<img width="494" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/62129ae7-7a00-4ef7-ba71-d59332bee2cd">

# Pattern of Occurrence 

# Acceptance Criteria

  
# Sample Mark-Up
```
<section class="references" id="sect-00025">
    <title>References</title>
    <para id="para-00057">McCance, K. L., &amp; Huether, S. E. (2018). Pathophysiology-E-book: the biologic basis for disease in adults and children. Elsevier Health Sciences.</para>
    <para id="para-00058">Purves, D., Augustine, G. J., Fitzpatrick, D., Hall, W., LaMantia, A. S., &amp; White, L. (2019). Neurosciences. De Boeck Supérieur.</para>
    <para id="para-00059">Stahl, S. M. (2021). Stahl's essential psychopharmacology: neuroscientific basis and practical applications. Cambridge university press.</para>
    </section>
```

# Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** psychiatric-mental-health
- **ref/branch:**
- **chapter/section:** Chapter 4 / EOC References collation
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax We currently don't have functionality for this - would it be possible to do what we have done in other titles where all the References for the chapter are in a `<section class="references">` in the last module?

**Comment by ww-openstax** [comment]
@lwtchu Yes, WiseWire will put all the References for the chapter in a <section class="references"> in the last module

**Comment by ww-openstax** [comment]
Tested: all the References for the chapter in a <section class="references"> in the last module. Output as expected.
