### ISSUE TITLE
Nursing Internal -- TOC has no formatting

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5292]
# Brief Description of Scenario
TOC needs formatting applied
<img width="551" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/9f334814-0db0-4192-b108-517ce7c6eef3">

# Pattern of Occurrence 

# Acceptance Criteria

  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** psychiatric-mental-health
- **ref/branch:**
- **chapter/section:** Table of Contents
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax This recipe is expecting Units, which is why the TOC isn't formatted correctly. Is this no longer the case? If so, it will apply to all five books.

**Comment by ww-openstax** [comment]
WiseWire added Units and now TOC is formatting correctly
