### ISSUE TITLE
Nursing Internal -- Exercises - output of link from assessment to in-text object needs correction

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5293]
# Brief Description of Scenario
In Exercises, when an assessment is linked to an in-text object with Element ID Tag, the system-generated output needs a correction.
The correction is: close-up period to object name. See screenshot.
This occurs only in PDF. The Webview output is correct, so match Webview output.

### PDF
![image](https://github.com/openstax/cnx-recipes/assets/89537088/fba0840e-1217-4a46-a6ab-004c4f451189)
### Webview
<img width="562" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/dd387ff0-42ef-45be-ac58-9c86f74843a1">

# Pattern of Occurrence 

# Acceptance Criteria
- This happens pretty frequently, are there some specs to apply for required context functionality to remove this spacing? Perhaps this needs to be implemented on a theme by theme basis? Can discuss on scrum call.
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** psychiatric-mental-health
- **ref/branch:**
- **chapter/section:** Chapter 4 / Assessments / Competencies / 2 / Nickname:04-02-PMH-CB01
- **surrounding text:**

**Comment by wilkus27** [comment]
### Information for tester

Changes has an impact on all books from Carnival.

**Comment by Stackblocks** [comment]
Displays correctly with the updated code from openstax/ce-styles#348.



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/00d3e4a2-837b-47ba-96bb-95c034e9525e)
