### ISSUE TITLE
Nursing Internal -- Answer Key - output order of assessment sections does not match output order of in-text assessments

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5294]
# Brief Description of Scenario
In the Answer Key, the output order of assessment sections does not match output order of in-text assessment sections
In PDF and Webview.

### Webview
![image](https://github.com/openstax/cnx-recipes/assets/89537088/5618e3d3-67e0-4920-8eb2-3c6e785054cf)

# Pattern of Occurrence 

# Acceptance Criteria
- Answer Key output matches what is currently in the EOC/TOC collation order
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** psychiatric-mental-health
- **ref/branch:**
- **chapter/section:** Chapter 4 / Answer Key
- **surrounding text:**

**Comment by Stackblocks** [comment]
- Displays OK with updated code from openstax/cookbook#287

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/e9d251cb-b47d-4385-961f-b8f1fecf6611)
