### ISSUE TITLE
college physics 2e - webview - equation numbering falling off line

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5297]
![image](https://github.com/openstax/cnx-recipes/assets/11299125/a706c7c1-f375-4e15-8f0a-80350f1c77ab)

# Context
Similar issue here: https://github.com/openstax/cnx-recipes/issues/4925 
I thought this was fixed? In any case, can the equation numbers be on the same line as the equation

# New specifications or link to documentation cards
Confirmed in latest generation that this isn't fixed or got undone again: https://rex-web-production.herokuapp.com/books/a31df062-930a-4f46-8953-605711e6d204@51ec01a/pages/preface?archive=https://openstax.org/apps/archive-preview/20231023.154131

## Impact 
Should impact majority of the books with numbered equations(?) - but let's focus on college physics

# Acceptance Criteria
- equation number in the box is on the same line as the equation

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-college-physics-bundle/
- **collection slug:** college-physics-2e
- **ref/branch:** main
- **chapter/section:** any - there's stuff in chapter 9.1 and example above is from 8.1

**Comment by kswanson33** [comment]
<img width="868" alt="image" src="https://github.com/openstax/cnx-recipes/assets/26280712/fd6d893c-a853-475b-9e1c-8fb3f0eb0665">

For QA: branch is ce-styles `equation-display-webview`

**Comment by Stackblocks** [comment]
Equation numbering looks good in testing.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/1f402034-9cfa-4254-b2a4-68331bad9c02)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/1391d53f-4861-498a-9a55-4bd04cc13a49)
