### ISSUE TITLE
Nursing Internal -- EOC Summary does not contain links or identifiers to individual sections

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5299]
# Brief Description of Scenario
The output of the the EOC Summary section does not contain any links or identifiers to the individual sections. 
In PDF and Webview.

<img width="526" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/39e58f7a-3333-40ed-994e-fc21516776fd">

# Pattern of Occurrence 

# Acceptance Criteria
- add section titles and links 
   
# Sample Mark-Up
```
<section class="summary" id="sect-00034">
    <title>Section Summary</title>
    <para id="para-00077">The nursing role when it comes to <term class="no-emphasis" id="term-00146">psychopharmaceutical</term>s is to assess for mental health symptoms and medications, collaborate with the client to recognize medication barriers and engage in nursing interventions to combat them, and identify <term class="no-emphasis" id="term-00147">side effect</term>s and adverse events of psychopharmaceutical agents. This section provided knowledge for skills associated with medications used to treat a variety of mental health disease states and the indications, risks, and population considerations related to these medications.</para>
    </section>
```

# Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** psychiatric-mental-health
- **ref/branch:**
- **chapter/section:** Chapter 4 / EOC Summary collation
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax Just wanted to make sure this will be okay - but the section dividers will be set to every single book using this theme, would that be okay?

**Comment by ww-openstax** [comment]
@lwtchu Yes, it is okay that the section numbers and titles will be set to every single book using this theme,

**Comment by MartaSztuka** [comment]
#### PASSED

##### PDF
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/12de8224-d2ca-456e-925a-d5bf90c2892b)

##### Webview
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/f4f58b8e-f7cd-46ea-8364-b7dcebdbee43)
