### ISSUE TITLE
Nursing Internal -- Feature Box class="lifestage-context" not outputting correctly in PDF

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5300]
# Brief Description of Scenario
The Feature Box for `<note class="lifestage-context" id="note-00006">` is not outputting correctly in PDF. The Webview output is correct. See screenshots
### PDF
![image](https://github.com/openstax/cnx-recipes/assets/89537088/838830a7-d486-4e78-8f16-7df1aa3d7409)

### Webview
![image](https://github.com/openstax/cnx-recipes/assets/89537088/b1d0bff5-aba6-4db8-93e1-485bb5650883)

# Pattern of Occurrence 

# Acceptance Criteria
- i think the fix for this was missed here https://github.com/openstax/cnx-recipes/issues/5172
- please make sure the two following changes are reflected - i believe the cultural context issue was also not implemented
- cultural-context - KEEP style and icon and color, change title to CULTURAL CONTEXT
- lifestage-context - COPY the cultural-context feature (same color/icon) and set the title to LIFE-STAGE CONTEXT
  
# Sample Mark-Up
```
    <note class="lifestage-context" id="note-00006">
    <title>Medications for Elderly People</title>
    <para id="para-00059">The American Geriatric Society publishes a guideline called the Beers Criteria for Potentially Inappropriate Medication Use in Older Adults, most often referred to as the Beers List. This evidenced-based approach provides information to healthcare providers on the safe management of medications of adults ages 65 and older. The list is divided into categories of medications that might cause adverse effects or have limited effectiveness, and those medications that are contraindicated with certain disease states.</para>
    <para id="para-00060">Assessment of medications for those 65 and older begins with medication reconciliation: obtaining a list of client medications, asking the client about current medications – including over the counter and supplements -- and changes to prescribed medications. Assessment continues with identifying medications listed in the Beers List and the potential complications: drug-drug interactions, potential for adverse events, or contraindications with current disease states. The next step is to educate clients on the potential for adverse events. For example, if the client has impaired mobility and the medication causes CNS depressant effects like dizziness, the situation warrants educating the client on managing falls. Ensure health literacy of client education through return communication of the education received. Assessment and management of medications for those over the age of 65 is part of client safety and best practices for which nurses are responsible.</para>
    </note>
```

# Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** psychiatric-mental-health
- **ref/branch:**
- **chapter/section:** Chapter 4 / Section 2 / Module m00003; line 381
- **surrounding text:** Medications for Elderly People

**Comment by MartaSztuka** [comment]
#### PASSED
##### PDF


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/26d8e2a0-1a20-49c5-b7e4-bc0024663119)

##### Webview
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/4150cb8f-df30-4ad3-8f45-9dd6109fb16e)

**Comment by lwtchu** [comment]
@MartaSztuka can you pull up the Cultural Context one to make sure it says Cultural Context? Thank you
