### ISSUE TITLE
Nursing Internal -- Assessment Section Heading output doesn't match kitchen sink

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5301]
# Brief Description of Scenario
Please revise Assessment Section Heading output to match revisions in screenshot.   
In PDF and Webview.
![image](https://github.com/openstax/cnx-recipes/assets/89537088/36c6e9ec-860d-4936-879a-e52928c54f2b)

# Pattern of Occurrence 
All Assessment Section Headings

# Acceptance Criteria
- please make changes to the following classes to reflect the new titles 
  
# Sample Mark-Up
```    <section class="review-questions" id="sect-00035">
    <title>Assessment: Review Questions</title>
    <exercise id="exer-00001">
    <section class="check-understanding" id="sect-00036">
    <title>Assessments: Check Your Understanding Questions</title>
    <exercise id="exer-00009">
    <section class="reflection-questions" id="sect-00037">
    <title>Assessments: Reflection Questions</title>
    <exercise id="exer-00012">
    <section class="critical-thinking" id="sect-00038">
    <title>Assessments: Critical-Thinking Questions about Case Studies</title>
    <exercise id="exer-00014">
    <section class="competency-based" id="sect-00039">
    <title>Assessments: Review Questions</title>
    <exercise id="exer-00017">

```

# Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** psychiatric-mental-health
- **ref/branch:**
- **chapter/section:** Chapter 4 / EOC Assessment collation
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
##### PDF


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/3ab4c9d9-b51c-4350-8c14-207270781dc4)



![Image](https://github.com/openstax/cnx-recipes/assets/47241114/9a11c0bf-e7bf-4be8-8564-24162eb66198)



![Image](https://github.com/openstax/cnx-recipes/assets/47241114/b1501d0f-9f4c-4ba8-8837-104f4326131c)



![Image](https://github.com/openstax/cnx-recipes/assets/47241114/88c1b0f2-6793-4b4c-ad16-59c288ae5c57)
