### ISSUE TITLE
Add support for running ce-styles in GitPod

### ISSUE THREAD

**Issue by philschatz** [openstax/cnx-recipes#5303]
# Context

To make these repositories more approachable to other developers and to quickly try out changes it is sometimes useful to be able to open the repository in GitPod.

Also, ce-styles uses dart but according to [their documentation](https://dart.dev/guides/libraries/private-files) some files created by dart should not actually be committed so they should be removed.

# New specifications or link to documentation cards

## Impact 

This should affect non-design developers and maybe design devs too

# Acceptance Criteria

When I open the ce-styles repo in GitPod I should be able to run `./script/build-styles` and it should build all the styles. Additionally, I should be able to edit a book.scss file (e.g. astronomy), Run `./script/build-styles astronomy`, and see the changes in the CSS file.

## Happy-path test

This confirms that folks can build the styles:

1. Open this repo in GitPod (clicking the link on the page is probably the easiest. see screenshot)
2. Once VSCode opens up, in the Terminal panel type `./script/build-styles`

![image](https://github.com/openstax/ce-styles/assets/253202/074ff78e-b469-4686-a853-4720ba99ada1)

## Confirm that we really do build the styles

1. Edit one of the books (e.g. `styles/books/anatomy/book.scss`) by changing one of the `_selectors` (e.g. add PHIL somewhere in the string)
2. Run `./script/build-styles anatomy`
3. Confirm that the "Changes" section in the "Source Control" panel includes `styles/output/anatomy-pdf.css`

![image](https://github.com/openstax/ce-styles/assets/253202/93d9b922-70ff-43d0-a8e1-133026b20ec9)

**Comment by lwtchu** [comment]
@philschatz 👀 would you like to merge this

**Comment by lwtchu** [comment]
@jbwilson8 to talk to Phil about getting a test plan

**Comment by Stackblocks** [comment]
Currently getting a dart error when I run `./script/build-styles` on main in a ce-styles gitpod instance 

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/0dbb9cc8-897e-43ae-a45d-c52224ede7d4)


I also tried using the fix branch that had worked when testing [a previous version of this change](https://github.com/openstax/ce-styles/pull/319#issuecomment-1790964220) and it also exploded with a dart error.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/a1f9d016-74fe-4b81-a782-71b96e5d5bf3)

**Comment by philschatz** [comment]
Can you try a new gitpod instance using the fix-gitpod-and-.... branch? Here's a link that should work:

https://gitpod.io/#https://github.com/openstax/ce-styles/pull/347

And a screenshot (the neuroscience book fails for a different reason but books build):

![image](https://github.com/openstax/cnx-recipes/assets/253202/9238a057-9b8e-463c-93a8-a0b8e807508b)

**Comment by philschatz** [comment]
Oh yeah, the gitpod scripts (which install dart) run when VSCode starts up, not when branches switch. I should've given a better link for testing.
