### ISSUE TITLE
nursing-external - enable column width for 1,1,1,1 (four column) tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5305]
# Brief Description of Scenario
Examples of tables with col width set but PDF output ignores: 
Nutrition:
![Nutrition_Chapter-4-column (1)](https://github.com/openstax/cnx-recipes/assets/11299125/8aa4e16b-3a2c-4904-a919-0e4559a519d5)
![Nutrition_Chapter_15_4-Column](https://github.com/openstax/cnx-recipes/assets/11299125/606ff3b6-64ad-4540-9a0e-880a00dd43f4)

Pharmacology:
![unnamed](https://github.com/openstax/cnx-recipes/assets/11299125/3b3c5696-1bba-4fb0-8ed4-7a2f27f36950)

# Pattern of Occurrence 
https://github.com/openstax/cnx-recipes/issues/5246#issuecomment-1731510819
We need to enable colwidth functionality from the issue above to include four column tables that have a 1:1:1:1 ratio

# Acceptance Criteria
- column width supported for four column tables
 

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** nutrition and pharmacology (last screenshot is in pharmacology)
- **ref/branch:** main
- **chapter/section:** please search text around screenshots
- **surrounding text:**

**Comment by Stackblocks** [comment]
- The four column tables from Pharmacology and Nutrition are now displaying properly with a 1:1:1:1 ratio. 
- The "Clients with CKD" example is a five-column table and is not addressed.

![Image](https:

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/cc921e75-2acb-4352-a972-20f4e99fe305)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/8be9cd6e-8591-45de-b0c7-e5d35d7b1c1a)



- There is also a bad table break on the "Colloidal Intravenous Solutions" table in Pharmacology, but that is likely outside of the scope of this card and will need to be addressed separately.



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/9ce4fe61-50a1-483e-810c-f05a54e6979a)

**Comment by wilkus27** [comment]
@Stackblocks Thank you for noticing this :wink: I added additional commit for five columns. It's ready for testing.
About a bad table break, I agree this should be fixed in another card.

**Comment by Stackblocks** [comment]
Thanks @wilkus27! The five-column addition works as expected and i'll spin off a card for the bad break.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/cf360b79-92d0-4f27-8398-fbe890ebb39e)
