### ISSUE TITLE
nursing-external - population health - enable full-width table class

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5306]
# Brief Description of Scenario
![Pop_Health_Chapter-15_2Column-table](https://github.com/openstax/cnx-recipes/assets/11299125/3084605f-1ef9-4ca7-9eb6-58bc9c9995db)

# Pattern of Occurrence 
~~These two tables essentially has the same mark up - is there a reason why the second one isn't going to full width? It might be worth implementing the table https://github.com/openstax/cnx-recipes/issues/5246 rules to this table if it hasn't yet.~~

After discussing with SRM, we will be implementing the full-width class to target tables to go full-width. It should not impact the colwidth or any other class properties.

# Acceptance Criteria
- add a full-width class
- tables with a full-width class go the full width of the page of the PDF 
- does not interfere with any other class (vertically-tight, alternate-shading, etc)
  
# Sample Mark-Up
They both have the same specs.
```
<table class="alternate-shading" id="table-00003">
  <title>Concepts in Diffusion of Innovations</title>
  <tgroup cols="2">
    <colspec colnum="1" colname="c1" colwidth="1*"/>
    <colspec colnum="2" colname="c2" colwidth="1*"/>
```
```
 <table class="alternate-shading" id="table-00004">
  <title>Key Attributes Affecting an Innovation’s Diffusion</title>
  <tgroup cols="2">
    <colspec colnum="1" colname="c1" colwidth="1*"/>
    <colspec colnum="2" colname="c2" colwidth="1*"/>
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** community-population
- **ref/branch:** full-width-test (added class to second table)
- **chapter/section:** please search content in table in screenshot 
- **surrounding text:**

**Comment by wilkus27** [comment]
@lwtchu Table width depends on its content. In Table 15.7 there is just less text then in Table 15.6. That's why it's shorter.

**Comment by lwtchu** [comment]
@wilkus27 do you know how it is determined? 🤔 either way I'll talk to them about it

**Comment by wilkus27** [comment]
@lwtchu If width is not declared in styles then it's determined automatically by Prince, like page breaks.

**Comment by lwtchu** [comment]
@wilkus27 we're approved to implement the full-width class. i updated the card and added new test content on the full-width-test branch

**Comment by Stackblocks** [comment]
Displaying properly with content from `full-width-test` and code from `nursing-external-full-width`

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/39732a07-26be-4293-b029-1ce461adee5e)
