### ISSUE TITLE
Nursing-external - Nutrition - Change from current 2-column format to 1-column format

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5307]
Based on the feedback, we have decided to make a change from the current 2-column format to a 1-column format for the PDF view. But its shows perfectly single column in WEB view.

**PDF View**
![image001](https://github.com/openstax/cnx-recipes/assets/86622862/1275cc54-7f34-4789-aad0-ad76b4af835a)
**WEB view:**
![WEB-view](https://github.com/openstax/cnx-recipes/assets/86622862/b421a3cf-11b4-4028-b3a9-707a693e93cc)

# Acceptance Criteria
- please set this to 1 column format

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:**nutrition
- **ref/branch:**https://openstax-osbooksnursing-om7p9xrw6yq.ws-us106.gitpod.io/
- **chapter/section:**Chapter 15/Suggested Reading 
- **surrounding text:** Amin, R., Thalluir, C., Docea, A., Sharifi-Rad, J., & Calina, D. (2022).

**Comment by Stackblocks** [comment]
Suggested Reading displaying in one column with updated code.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/0461628c-3fdc-40fc-bfee-0b22dce3fc02)
