### ISSUE TITLE
WEB VIEW - image stretching issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5308]
we are facing when viewing the web version all the images are stretching and losing their original proportions the same images appear perfectly in the PDF version (For all nutrition courses).

WEB view:

![WEBVIEW-1](https://github.com/openstax/cnx-recipes/assets/86622862/a83f8fef-e3c9-4901-aa05-68be717d9d84)

PDF View:

![PDFVIEW-1](https://github.com/openstax/cnx-recipes/assets/86622862/859806e8-ce17-4a86-951d-f6582cac7210)

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:**pharmacology
- **ref/branch:**https://openstax-osbooksnursing-om7p9xrw6yq.ws-us106.gitpod.io
- **chapter/section:** chapter 27/introduction
- **surrounding text:** The endocorine system regulates all biological processes related

**Comment by lwtchu** [comment]
More detailed card here: https://github.com/openstax/cnx-recipes/issues/5309 as this issue impacts all books.

**Comment by lwtchu** [comment]
The hot fix was deployed last week.
