### ISSUE TITLE
webivew - image height in css needs to be set to auto to prevent stretching

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5309]
![image](https://github.com/openstax/cnx-recipes/assets/11299125/ccaf35b8-b082-4d0d-b92e-0a09434958eb)

# Brief Description of Scenario
Full context in thread here https://openstax.slack.com/archives/C022NETP39N/p1699456269558529

# Pattern of Occurrence 
All images in figures that are wider than 825px. Approach is we're going to pursue the CSS heigh:auto; fix. If not, we will roll back the bakeimages in bake web.

# Acceptance Criteria
- images should scale proportionately
- https://rex-web-production.herokuapp.com/books/world-history-volume-2@6d1ce8c/pages/6-1-european-colonization-in-the-americas?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20231106.165630
![image](https://github.com/openstax/cnx-recipes/assets/11299125/c63f21a3-f130-4ee2-881b-95dfcf17a399)
this image shouold be 825px x 550px NOT 825x801. (you might have to remove the scaled-down class in the inspect window to see - but shouldn't be elongated anymore)
- Other images are also not squished beyond recognition please check the following books
- Python, Nursing external (pick one), BCA (most important) 
  

# Location(s)
https://rex-web-production.herokuapp.com/books/world-history-volume-2@6d1ce8c/pages/6-1-european-colonization-in-the-americas?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20231106.165630
- **osbooks repo:** https://github.com/openstax/osbooks-world-history
- **collection slug:** world-history-volume-2
- **ref/branch:** main
- **chapter/section:**  6.1 
- **surrounding text:**

**Comment by kswanson33** [comment]
hi QA, fix is on ce-styles `img-height-auto` branch

**Comment by Stackblocks** [comment]
# World History Vol. 2
With `class="scaled-down"` removed the image has the expected dimensions / aspect ratio.

![CleanShot 2023-11-08 at 13 39 41](https://github.com/openstax/cnx-recipes/assets/12678235/e5626867-6a34-4074-af9d-665e91310992)

**Comment by Stackblocks** [comment]
# BCA
Charts looking much improved.

![CleanShot 2023-11-08 at 14 24 54](https://github.com/openstax/cnx-recipes/assets/12678235/3a9d9733-d535-4b5f-b4ea-122ba81646ca)
![CleanShot 2023-11-08 at 14 23 44](https://github.com/openstax/cnx-recipes/assets/12678235/0bd30bb7-1edd-4e08-b82f-7a020891f7d7)
