### ISSUE TITLE
lifespan development - headers

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5312]
Documentation #3164

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2023-11-17 16-37-43](https://github.com/openstax/cnx-recipes/assets/47241114/77ceb297-4413-416e-b76b-65858d937e9f)
![Zrzut ekranu z 2023-11-17 16-37-09](https://github.com/openstax/cnx-recipes/assets/47241114/7ddda74f-f2e3-405f-9696-1f9732bff54a)
![Zrzut ekranu z 2023-11-17 16-39-06](https://github.com/openstax/cnx-recipes/assets/47241114/c44b0fb5-275d-4b9e-b467-09053ab67266)
