### ISSUE TITLE
Python book: add color to code snippets (outside of code runner)

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#5315]
# Context
Reviewers have requested that the python code snippets in _Introduction to Python Programming_ have some color to help intro-level learners understand the material. Please see two examples below:

## Example 1: Current display
<img width="1002" alt="OS feedback" src="https://github.com/openstax/cnx-recipes/assets/7863733/9155d4d2-e761-4956-8859-3cc19a75a826">

### Example 1: Desired display (does **not** have to exactly match these colors)
<img width="327" alt="zyB screenshot" src="https://github.com/openstax/cnx-recipes/assets/7863733/1ec9295a-c107-4d55-b23c-5e2ec3fca6a2">

## Example 2: Current display
<img width="1060" alt="image003" src="https://github.com/openstax/cnx-recipes/assets/7863733/e30d0865-6f32-47e3-b7eb-89286e4b8395">

### Example 2: Desired display (does **not** have to exactly match these colors)
<img width="923" alt="image005" src="https://github.com/openstax/cnx-recipes/assets/7863733/e2d7fa22-0f8d-4ee3-a66b-5711e9af249d">

# New specifications or link to documentation cards

## Impact 
Only _Introduction to Python Programming_

# Acceptance Criteria

# Content
## Sample Mark-Up - Example 1 above
```
 <code class="python" lang="python">
    # Statements before<newline/>
    if condition:
      # Body
    else:
      # Body<newline/>
    # Statements after
    </code>
```

## Sample Mark-Up - Example 2 above
```
<table summary=" " id="table-00001">
    <title>Calculating miles-per-gallon and checking for division by zero</title>
    <tgroup cols="1">
    <tbody>
      <row>
    <entry>
    <code class="python" lang="python">
    <span class="blue-code">def</span> calc_mpg(miles, gallons):
      <span class="green-code">if gallons > 0:</span>
        mpg = miles/gallons
        <span class="blue-code">return</span> mpg
      else:
        print("Gallons can't be 0")
        return -1<newline/>
    car_1_mpg = calc_mpg(448, 16)
    print("Car 1's mpg is", car_1_mpg)
    car_2_mpg = calc_mpg(300, 0)
    print("Car 2's mpg is", car_2_mpg)
    </code></entry>
    <entry><code class="python" lang="python">
    Car 1's mpg is 28.0
    Gallons can't be 0
    Car 2's mpg is -1
    </code></entry>
  </row>
    </tbody>
    </tgroup>
    </table>
```

## Location(s)
- **osbooks repo:** github.com/openstax/osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:** main
- **chapter/section:** 
- **surrounding text:** "If-else statement template" ; "used to indicate a problem"

**Comment by lwtchu** [comment]
Duplicate https://github.com/openstax/cnx-recipes/issues/5351
