### ISSUE TITLE
Python book: style code comments in italics (in code snippets outside of code runner)

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#5316]
# Context
Authors/zyBooks have requested that the python code comments in _Introduction to Python Programming_ be styled in italics to help intro-level learners understand the material. Please see example below:

## Example 1: Current display
<img width="1002" alt="OS feedback" src="https://github.com/openstax/cnx-recipes/assets/7863733/9155d4d2-e761-4956-8859-3cc19a75a826">

### Example 1: Desired display (note the italics -- there is a separate card for the code colors)
<img width="327" alt="zyB screenshot" src="https://github.com/openstax/cnx-recipes/assets/7863733/1ec9295a-c107-4d55-b23c-5e2ec3fca6a2">

# New specifications or link to documentation cards

## Impact 
Only _Introduction to Python Programming_

# Acceptance Criteria

# Content
## Sample Mark-Up - Example 1 above
```
 <code class="python" lang="python">
    # Statements before<newline/>
    if condition:
      # Body
    else:
      # Body<newline/>
    # Statements after
    </code>
```

## Location(s)
- **osbooks repo:** github.com/openstax/osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:** main
- **chapter/section:** 
- **surrounding text:** "If-else statement template"

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2024-01-04 10-31-57](https://github.com/openstax/cnx-recipes/assets/47241114/6cda472c-4513-4947-9745-4bc7246f2ff7)
![Zrzut ekranu z 2024-01-04 10-36-37](https://github.com/openstax/cnx-recipes/assets/47241114/6ce093ab-9aee-4931-bfc9-1fa4c7de0c0c)

**Comment by lwtchu** [comment]
context: html tags in code is causing issues #5405 #5403 - might need to just set <span class="hljs-comment"> to italics but need to find instances in content first
