### ISSUE TITLE
nursing-internal - maternal newborn - remove page break between summary and key terms

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5318]
![Screenshot 2023-11-13 at 2 43 39 PM](https://github.com/openstax/cnx-recipes/assets/11299125/dc9d3f6e-55a7-4bd6-b11b-242ac9609bca)

# Brief Description of Scenario
There is a page break between the Summary and Key Terms (likely because Summary is going first). If possible, can the page break be removed for this instance?

# Acceptance Criteria
- [ ] page break removed between summary and key terms
- [ ] impacts all books in this repo but can check maternal newborn and psychiatric mental health
  
# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-internal-bundle
- **collection slug:** maternal-newborn
- **ref/branch:** main
- **chapter/section:**  EOC
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED

![Image](https://github.com/openstax/cnx-recipes/assets/47241114/8f61662b-a0aa-43df-8096-4ea7726756e2)
