### ISSUE TITLE
lifespan development - introduction

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5320]
documentation #3191

**Comment by MartaSztuka** [comment]
@lwtchu Introduction looks fine, but there's content problem (it's written twice)


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/3cddf093-0e3b-498f-9f77-4520ef2f9cd8)

**Comment by lwtchu** [comment]
@MartaSztuka @wilkus27 fixed the extra title

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2023-11-21 09-49-34](https://github.com/openstax/cnx-recipes/assets/47241114/a9921ddd-91cb-4d14-a06e-f0a128d22ff8)
