### ISSUE TITLE
lifespan development - tables and table titles caption

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5322]
Documentation https://github.com/openstax/cnx-recipes/issues/3185

type 1 - use type 1

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2023-11-21 10-00-43](https://github.com/openstax/cnx-recipes/assets/47241114/79614396-ff80-4ee1-91d4-7fbb4073f02b)
