### ISSUE TITLE
lifespan development - vertically tight tables with a header row 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5323]
![Screenshot 2023-11-15 at 12 28 40 PM](https://github.com/openstax/cnx-recipes/assets/11299125/839fa108-e68a-4af7-98a6-29166e785b26)

We've done something similar in Finance #4294 and Nursing #5007
`class="vertically-tight"`
Set padding to 0.16rem which is equivalent to 2px
Styling should still follow generic tables: 
Documentation #3185 

This will also utilize `<row class="header-row">` please make sure font is set bold like the header styling

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2023-11-20 17-09-08](https://github.com/openstax/cnx-recipes/assets/47241114/5398cf83-fb5b-4f20-a178-a34f9ccfe977)

**Comment by wilkus27** [comment]
@MartaSztuka I think this should be added to this card: https://github.com/openstax/cnx-recipes/issues/5322. Table from your screenshot is a regular table, not vertically tight or with a header row :thinking:

**Comment by MartaSztuka** [comment]
##### class="vertically-tight"
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/8af161e3-76f2-49e8-922b-fdc051cdf040)
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/52c19852-f54e-4cbb-8b96-5e8fff5547ed)

##### row class="header-row"
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/c97d696d-2256-430e-a666-e2ba35989e08)
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/13a8b53e-d2dc-438e-a404-f9707b0be901)
