### ISSUE TITLE
lifespan development - link to learning

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5324]
- class: `link-to-learning`
- uses #3235
- title: Link to Learning
- no subtitle
- icon: [carnival-linktolearning.svg](https://drive.google.com/file/d/1jm3US-spU6F3BwURhHDY5Emxpe5vmyOr/view?usp=sharing)
- color: G1: `#78B042`

**Comment by Stackblocks** [comment]
Link to Learning displaying correctly with these changes.





![Image](https://github.com/openstax/cnx-recipes/assets/12678235/21129cff-b98b-44c0-a445-648dc647ae9d)
