### ISSUE TITLE
lifespan development - it depends feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5325]
- class: `class="it-depends"`
- uses #3194
- title: It Depends
- has `<title>`
- uses alternate color schema 4 (yellow)
- might contain image, mostly text

**Comment by Stackblocks** [comment]
`It Depends` feature displaying properly with these changes.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/683eea3a-da8a-4dbe-9be5-d68d805734f1)
