### ISSUE TITLE
lifespan development - life hacks

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5326]
- class: `class="life-hacks"`
- uses #3194
- title: Life Hacks
- has `<title>`
- uses alternate color schema 5 (purple)
- might contain image, mostly text

**Comment by Stackblocks** [comment]
`Life Hacks` note showing properly with these changes.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/39dd5622-1695-4859-8955-533b1f9735cb)
