### ISSUE TITLE
lifespan development - what have you heard?

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5327]
class: `what-heard`
documentation https://github.com/openstax/cnx-recipes/issues/3193
title: What Have You Heard?
has a subtitle: yes
icon: [cosmos-debate.svg](https://drive.google.com/file/d/1gf0keZTY1ePMqbT7jB_OM53lYIHLrJfg/view?usp=sharing)
color: G1: `#1E9575`

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2023-11-27 17-06-15](https://github.com/openstax/cnx-recipes/assets/47241114/2bf5dd1a-4995-4c68-b9c3-4a9247a1050b)
