### ISSUE TITLE
lifespan development - intersections and context

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5328]
- class: `class="intersections-contexts"`
- uses #3194
- title: Intersections and Context
- has `<title>`
- uses alternate color schema 3 (green)
- might contain image, mostly text

**Comment by Stackblocks** [comment]
`Intersections and Context` note showing properly with these changes

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/733d2f35-2702-400b-8e85-b199737ac8a0)
