### ISSUE TITLE
Pharmacology - Arabic list item not indent correctly

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5329]
PDF view

1. In between the paragraphs, the Arabic list item with the bullet list does not match with the WEB view. It seems to be set as flush left instead.
2. The bullets under a numbered list are solid, the current output is an outlined bullet.

**PDF VIEW** ![Chapter19](https://github.com/openstax/cnx-recipes/assets/86622862/6948265d-73b7-4a4a-829f-4f6c987f32b2)
**WEB VIEW**
![Chapter_19_WEB-VIEW](https://github.com/openstax/cnx-recipes/assets/86622862/9c269375-18a7-4433-83bc-1ff2c1793aac)

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:**pharmacology
- **ref/branch:**https://openstax-osbooksnursing-om7p9xrw6yq.ws-us106.gitpod.io/
- **chapter/section:** Chapter 19/Section 19.1
- **surrounding text:** Another goal is to decrease the cardiac workload and the heart’s demand for oxygen.

**Comment by lwtchu** [comment]
@srm-openstax Hello! The bullets are hollow due to it being nested in another list. The indentations will also not match 100% across web and PDF. How critical is this fix for your team?

**Comment by srm-openstax** [comment]
We checked with our Editorial team and confirmed the request is not critical. We are okay to leave the nesting “as is”.

Please close the ticket request.
