### ISSUE TITLE
lifespan development - end of chapter 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5330]
# Key Terms
- Documentation #3206
- Set by `<glossary>`
- Set as one column

# Section Summary
- `class="summary"`
- Does include chapter breaks
- Documentation #3209 

# References
- `class="references"`
- Documentation #3214

# Assessments
- All assessments are sequential and reset per chapter
- No section breaks!! DO NOT include chapter/module headers
- Not all chapters contain sections
- Documentation #3211

## Review Questions
- `class="review-questions"`

## Check Your Understanding Questions
- `class="check-understanding"`

## Reflection Questions
- `class="reflection-questions"`

## Media Questions
- `class="media-questions"`

## Thought Provokers
- `class="thought-provokers"`

## Case Study Questions
- `class="case-study"`

**Comment by MartaSztuka** [comment]
#### PASSED
##### Key Terms
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/dae34e2f-bf1b-4862-8bc5-c8fb7735a40e)

##### Section Summary
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/c64dbead-7820-4017-80e4-7d961fb5f5c3)

##### References
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/6db4fa58-346f-4d32-91b0-34a371243730)

##### Review Questions
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/3901c144-11a5-4400-b210-af22d958215f)

##### Check Your Understanding Questions
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/fe2bc316-6743-4695-aae7-679e6f0ad1e2)

##### Reflection Questions
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/ab9c952b-b1db-4bf1-ae05-c1f9a6990f4f)

##### Media Questions
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/24763760-371e-4158-bc19-07cc90fdaa72)

##### Thought Provokers
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/5e8629dd-1e0e-493e-a211-ca106f38e882)

##### Case Study Questions
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/cbb99d5a-9ba4-4bd6-8507-914591c31508)
