### ISSUE TITLE
lifespan development - glossary appendix

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5333]
Similar to #1339

These are lists within a section that has the class `column-container`. 

- The lists SHOULD NOT have bullets or anything. 
- The base font should be smaller: font-scale(-1) 
- The text should be in 3 columns! And text should go from top to bottom, then left to right.
- The section titles should function as intended within the scale/header documentation.

**Comment by MartaSztuka** [comment]
#### PASSED


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/b2e18de6-c42b-415a-9aae-bce43538f395)



![Image](https://github.com/openstax/cnx-recipes/assets/47241114/aad98007-e01d-4043-8a67-26d667e932bc)
