### ISSUE TITLE
Nursing Internal -- XML tagging for Strikethrough formatting?

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5334]
# Context
We have  multiple instances of text in manuscript that requires strikethrough formatting like in screenshot below. Is there XML tagging and styling available for strikethrough formatting? How can we render strikethrough formatting?

<img width="702" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/3174f6df-c7b8-424f-9b39-b53f21fbbb85">

# New specifications or link to documentation cards

## Impact 
All books in theme.

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** clinical-nursing
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax You can use the `<m:menclose>` tag. [You can read more about it here if you want a technical explanation.](https://www.w3.org/TR/MathML/chapter3.html#presm.menclose).

[I also found an example in Chemistry on line 320](https://github.com/openstax/osbooks-chemistry-bundle/blob/2b2a5decf8ee6777a0d5a49f621f97cda4ed3001/modules/m68709/index.cnxml#L320).  

If you would like more examples, let me know!

**Comment by ww-openstax** [comment]
@lwtchu <m:menclose> tag works great for strikethrough. Thanks!
