### ISSUE TITLE
data science - generic things

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5338]
Documentaton/list #2712

**Comment by wilkus27** [comment]
### Information for tester
Check also equations and references

**Comment by Stackblocks** [comment]
**PASSED**

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/53370117-54d8-401a-b5f3-f7ff846270fd)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/6c9cd938-f2ef-48bb-b450-4af05067265f)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/361557cc-e698-411b-9997-980dd7a8c459)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/e1c36571-ddbd-44f4-a44d-4ae9109dd004)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/2844e8e3-4248-4f4c-9b72-d05ad2008914)
