### ISSUE TITLE
neuroscience module numbering counts intro as 1

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5339]
I just generated a test pdf of what's currently in the Neuroscience collection and it's numbering the introduction modules of every chapter as #.1 instead of #.0 or nothing. Manuscript has intros numbered as 0.

# Context
![Screenshot 2023-11-27 at 12 21 01 PM](https://github.com/openstax/cnx-recipes/assets/11299125/4a2416d3-f7e4-4e50-8dd3-f0574c99dd47)

# New specifications or link to documentation cards
Please unnumber introduction modules

## Impact 
Neuroscience introduction modules

# Acceptance Criteria
![Screenshot 2023-11-27 at 12 21 59 PM](https://github.com/openstax/cnx-recipes/assets/11299125/d67c13a8-e463-4a29-9539-aec820ec1f5e)
- example from a nursing title
- introduction should not be numbered

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-neuroscience
- **collection slug:** osbooks-neuroscience
- **ref/branch:**
- **chapter/section:** all
- **surrounding text:**

**Comment by wilkus27** [comment]
It's because changes for introduction page are not merged yet https://github.com/openstax/cnx-recipes/issues/5276

**Comment by jbwilson8** [comment]
[Chapter Intro changes](https://github.com/openstax/cnx-recipes/issues/5276) have been merged. 



![Image](https://github.com/openstax/cnx-recipes/assets/26155528/780874f6-e200-436a-aa77-532b64bee10f)
