### ISSUE TITLE
data science - figure and table caption styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5342]
Documentation: https://github.com/openstax/cnx-recipes/issues/2643

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2023-12-08 16-04-55](https://github.com/openstax/cnx-recipes/assets/47241114/07ed7947-2d05-4768-a6ae-7755f80a269f)
![Zrzut ekranu z 2023-12-08 16-04-27](https://github.com/openstax/cnx-recipes/assets/47241114/36938313-34cf-4a7d-9f7a-3bdf91c2c9a1)

**Comment by MartaSztuka** [comment]
#### PASSED


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/71f890b3-bb22-4859-a482-ca4cecd2b6ed)
