### ISSUE TITLE
nursing-external - community population nursing - table width enabling in appendix

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5349]
APPENDIX C: The reviewing the layout, we have observed that the 4-column table is not consistent and remains narrow. We tried a few more proportion values of the colspec, but unfortunately, it is not supported in CORGI-generated PDF. Refer to the attached screenshots.

**PDF View:**
![PDF_view_Appendix_c](https://github.com/openstax/cnx-recipes/assets/86622862/ab885687-6c89-4c66-ab6c-b99aa0831175)
![PDF_view_Appendix_c_1](https://github.com/openstax/cnx-recipes/assets/86622862/1d0bb685-dcde-4fe5-9149-8ffb2a66ad0f)

# Acceptance Criteria
- table width functionality is set in appendix 

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** community-population
- **ref/branch:** https://openstax-osbooksnursing-om7p9xrw6yq.ws-us106.gitpod.io/
- **chapter/section:**  Appendix C
- **surrounding text:** patient cannot perform these functions independently.
Nurses support and protect the patient.

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2023-12-07 14-43-15](https://github.com/openstax/cnx-recipes/assets/47241114/3c98af60-6bc5-43a2-84f0-3f0f08fd4510)
![Zrzut ekranu z 2023-12-07 14-43-20](https://github.com/openstax/cnx-recipes/assets/47241114/4e5a3264-d948-447e-9b9f-c20325afac64)
