### ISSUE TITLE
introduction to python - web & pdf - line numbers to code snippets

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5350]
Discussed in this thread: https://openstax.slack.com/archives/C022NETP39N/p1701204067404419
Stackoverflow resource: https://stackoverflow.com/questions/41306797/html-how-to-add-line-numbers-to-a-source-code-block

If possible, I'd like to add code line numbering to items tagged with `<code class="line-numbering">` or `<pre class="line-numbering">` 

# Brief Description of Scenario
On certain code snippets, we would like to add line numbering for assessment purposes or to draw attention to certain lines of code. 

# Acceptance Criteria and Specs
![Screenshot 2023-11-29 at 11 04 17 AM](https://github.com/openstax/cnx-recipes/assets/11299125/beca9b7e-2a2c-493c-aa0c-ec5260d84f7b)

NOTE sometimes text wraps and the line might extend past  (see line 7)

 text font: courier prime
 size: same as the base size (9pt 1rem)
 please right align the numbers
 add a 1pt width black #000000 line between the numbers and code

### please do this for WEB AND PDF

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introduction-python-programming/
- **collection slug:** introduction-python-programming
- **ref/branch:** https://github.com/openstax/osbooks-introduction-python-programming/tree/line-number
1. Chapter 5.6, two of the code snippets in table 5.5
2. Chapter 6.1, first embedded exercise in Concepts in Practice (Which line has a function call?)

**Comment by lwtchu** [comment]
Issue for accessibility to open up separately once this is implemented. 

@openstaxalina to ask for guidance on A11Y if zyBooks has any insights (are they using any aria labels to identify that it's a line number?)

**Comment by openstaxalina** [comment]
@jbwilson8 I spoke with zyBooks today about the a11y approach for this. Here is their response:

Critical aspect is that the line number be read separately from the code. 
On zyBooks platform, the snippets end up being organized into a table, with line numbers as one column, and code as the corresponding column.  

Yamuna (zyBooks lead) also has a query out to their a11y team for any other advice on handling. 

Do you think the table structure is feasible...? I'm thinking this might be a major change...

**Comment by openstaxalina** [comment]
Oh - there's an example of this on the zyBooks platform here: https://learn.zybooks.com/zybook/OpenStaxPythonDev/chapter/13/section/3?content_resource_id=98048390

Link for access: https://share.1password.com/s#rkgeLJz5zGRgcTCWHPSikUCN9vVj-dvi3Ro-7M1sh1A

**Comment by jbwilson8** [comment]
@openstaxalina The highlight.js line number plugin that we're using aligns with what zyBooks is doing.  The code snippet is organized into a table with the line number in the first column and the code text in the corresponding column. So we're good here.  (See image for reference).



![Image](https://github.com/openstax/cnx-recipes/assets/26155528/d397b018-b6bc-4ed3-9ae3-140acc06f57d)

**Comment by openstaxalina** [comment]
@jbwilson8 that is great news! 
yes, that is the only a11y requirement I am aware of. as long as it is organized into a table, it should be properly read by the screen reader. 

@Stackblocks would you be able to test this (when it gets to you)? the critical thing is that the line number **not** be read as part of the code snippet.

**Comment by Stackblocks** [comment]
Initial feature testing has the line numbers displaying properly! Going to run an accessibility test and report back if the code is being read out properly on screen readers and update the comment.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/8b810548-10cc-400c-85a4-5cdba7a09720)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/277e0ab2-5b3e-4cfd-9c18-f71ab9856b76)

**Comment by jbwilson8** [comment]
A separate card will be for accessibility.

**Comment by jbwilson8** [comment]
**Problem**: Screenreader loops through highlight.js code snippet table more than once before moving on to the next section.

**Notes:**

A solution has not been determined at this time. Below are a few things that have been tried:

**- Un-nest the code snippet table**
    - This produces less looping, but is not an optimal solution
- **Try use cases with raw html (including line number code snippet)**
    - The following code variations were tested with screen readers, however, looping did not occur.
    - @Stackblocks  found the following findings when testing the use cases: [view](https://openstax.slack.com/archives/C022NETP39N/p1708011785972549  )
    - [Use case variations](https://openstax.slack.com/files/U04JELAS3GR/F06K0FS58TU/python-accessibility.html)
 
- This article was also discovered (scroll to number 5 under the “How to Make a Good Table” section)
    - This could explain why the screenreader is having a hard time navigating the content

**Additional things to try:**

1. Based on this article: https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced#tables_for_visually_impaired_users  there may be an opportunity to manipulate the content via cookbook to make it more accessible.)

2. Determine if the screen reader can read code snippets successfully without the highlight.js line numbers plugin.
