### ISSUE TITLE
data science - example problem

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5352]
# Design Summary
Documentation #2899 (but please use the fonts for the business series, use roboto condensed and not dosis)

![Screen Shot 2022-12-21 at 9 38 56 AM](https://user-images.githubusercontent.com/11299125/208943895-a7e79e80-2aee-411f-bf60-92c5f916e83f.png)

New color scheme
Top bar: G1: `#1E9575`
Bottom box: G2: `#F2F2F2`
Text: Black `#000000`

Numbering: #.#
Subtitle from `<title>`

We did the same thing on the Python book if you want to copy that.

**Comment by MartaSztuka** [comment]
#### PASSED


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/1b68a952-9915-49bc-9967-a29ad4718dba)
