### ISSUE TITLE
data science - downloadable file feature

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5356]
- Documentation #3680
- Icon: https://drive.google.com/file/d/1ZqeP98tN9321oLO0zp5Z07jet9eZ8543/view?usp=drive_link
- Class: `<note class="download-file">`
- should have no subtitle and no title

**Comment by MartaSztuka** [comment]
#### PASSED


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/8ac9db4e-eb5d-452c-8d56-4f80b077bceb)
