### ISSUE TITLE
data science - end of chapter content

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5357]
## Key Terms
- documentation #2742
- title: Key Terms
- targeted by `<glossary>` tag

![image](https://github.com/openstax/cnx-recipes/assets/11299125/ddfa3346-176e-4e81-a4b4-7f6ab1c8a517)

## Group Project
- title: Group Project
- class: group-project
- should contain mostly text
- icon: [cardboard-managegroup.svg](https://drive.google.com/file/d/169_IQ6DAi8qsAGZv152QHVtSerJIp1z_/view?usp=sharing)

## Chapter Problems and Data Sets
- resets every chapter
- numbers are bold w a period
- title: Chapter Problems and Data Sets
- class: chapter-problems
- contains sub sections (for data set and problems)
- icon: [cardboard-suggested.svg](https://drive.google.com/file/d/1Ltc0whfkE49KScYfgJ_72T7f99_T7Brk/view?usp=sharing)

**Comment by lwtchu** [comment]
@wilkus27 The exercises has been added in -- as for the section, i think it's intentional for it to go together since the data sets inform the exercises 🤔 but I might have to talk to alina about this...

**Comment by MartaSztuka** [comment]
#### Key Terms - there's content problem; big gap after title
![Zrzut ekranu z 2023-12-14 15-51-40](https://github.com/openstax/cnx-recipes/assets/47241114/437552ef-6971-4d94-b885-0f10b38414a3)
#### Group Project
![Zrzut ekranu z 2023-12-14 15-52-21](https://github.com/openstax/cnx-recipes/assets/47241114/1edfc500-60ac-4257-90c8-39d2ed7ce37c)
#### Chapter Problems and Data Sets
![Zrzut ekranu z 2023-12-14 15-52-32](https://github.com/openstax/cnx-recipes/assets/47241114/39e956de-be1d-4d33-9663-e31b40f7386b)

**Comment by wilkus27** [comment]
@MartaSztuka Blank space in Key Terms it's a content issue.
@caylaeagon There is a bunch of empty terms. Here is a list:

```
<dl id="auto_bf4b6343-4997-42a5-9afd-31c113d33426_def-00004" data-sm="./modules/m00001/index.cnxml:54:5">
            <dt data-sm="./modules/m00001/index.cnxml:55:7"></dt>
            <dd data-sm="./modules/m00001/index.cnxml:56:7"></dd>
          </dl>
          <dl id="auto_bf4b6343-4997-42a5-9afd-31c113d33426_def-00005" data-sm="./modules/m00001/index.cnxml:59:5">
            <dt data-sm="./modules/m00001/index.cnxml:60:7"></dt>
            <dd data-sm="./modules/m00001/index.cnxml:61:7"></dd>
          </dl>
          <dl id="auto_bf4b6343-4997-42a5-9afd-31c113d33426_def-00006" data-sm="./modules/m00001/index.cnxml:64:5">
            <dt data-sm="./modules/m00001/index.cnxml:65:7"></dt>
            <dd data-sm="./modules/m00001/index.cnxml:66:7"></dd>
          </dl>
          <dl id="auto_bf4b6343-4997-42a5-9afd-31c113d33426_def-00007" data-sm="./modules/m00001/index.cnxml:69:5">
            <dt data-sm="./modules/m00001/index.cnxml:70:7"></dt>
            <dd data-sm="./modules/m00001/index.cnxml:71:7"></dd>
          </dl>
          <dl id="auto_bf4b6343-4997-42a5-9afd-31c113d33426_def-00008" data-sm="./modules/m00001/index.cnxml:74:5">
            <dt data-sm="./modules/m00001/index.cnxml:75:7"></dt>
            <dd data-sm="./modules/m00001/index.cnxml:76:7"></dd>
          </dl>
          <dl id="auto_ef698593-f9d6-4377-acfd-343ab3db943c_def-00005" data-sm="./modules/m00004/index.cnxml:382:5">
            <dt data-sm="./modules/m00004/index.cnxml:383:7"></dt>
            <dd data-sm="./modules/m00004/index.cnxml:384:7"></dd>
          </dl>
          <dl id="auto_ef698593-f9d6-4377-acfd-343ab3db943c_def-00006" data-sm="./modules/m00004/index.cnxml:387:5">
            <dt data-sm="./modules/m00004/index.cnxml:388:7"></dt>
            <dd data-sm="./modules/m00004/index.cnxml:389:7"></dd>
          </dl>
          <dl id="auto_ef698593-f9d6-4377-acfd-343ab3db943c_def-00007" data-sm="./modules/m00004/index.cnxml:392:5">
            <dt data-sm="./modules/m00004/index.cnxml:393:7"></dt>
            <dd data-sm="./modules/m00004/index.cnxml:394:7"></dd>
          </dl>
          <dl id="auto_ef698593-f9d6-4377-acfd-343ab3db943c_def-00008" data-sm="./modules/m00004/index.cnxml:397:5">
            <dt data-sm="./modules/m00004/index.cnxml:398:7"></dt>
            <dd data-sm="./modules/m00004/index.cnxml:399:7"></dd>
          </dl>
          <dl id="auto_ef698593-f9d6-4377-acfd-343ab3db943c_def-00009" data-sm="./modules/m00004/index.cnxml:402:5">
            <dt data-sm="./modules/m00004/index.cnxml:403:7"></dt>
            <dd data-sm="./modules/m00004/index.cnxml:404:7"></dd>
          </dl>
          <dl id="auto_ef698593-f9d6-4377-acfd-343ab3db943c_def-00010" data-sm="./modules/m00004/index.cnxml:407:5">
            <dt data-sm="./modules/m00004/index.cnxml:408:7"></dt>
            <dd data-sm="./modules/m00004/index.cnxml:409:7"></dd>
```

**Comment by caylaeagon** [comment]
@wilkus27 @MartaSztuka Fixed! Should be good now.

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2023-12-15 10-51-27](https://github.com/openstax/cnx-recipes/assets/47241114/5511bc65-8c40-4d1f-a790-dfa846495d6f)
