### ISSUE TITLE
Nursing Internal -- Webview & PDF -- Exercises -- Bulleted list in multipart stimulus is not indented

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5359]
# Brief Description of Scenario
In multi-part Exercises -- Bulleted list in stimulus is not indented. 
In PDF only. Webview is correct.
Applies to all Nursing-internal titles

### PDF
![image](https://github.com/openstax/cnx-recipes/assets/89537088/b7077894-87b6-4077-8d4e-cc5daa2d8510)

### Webview
![image](https://github.com/openstax/cnx-recipes/assets/89537088/6f359744-f64f-494a-a754-7e0d2c48b9ca)

# Pattern of Occurrence 

# Acceptance Criteria
- please make sure list styling is enabled in EOC assessment content
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** clinical-nursing
- **ref/branch:**
- **chapter/section:** Chapter 11 / Exercises Nickname:11-01-Skills-CT01
- **surrounding text:**

**Comment by Stackblocks** [comment]
Pass

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/b7cc35c2-01ea-4b49-8ae5-cfc8ca91a19d)
