### ISSUE TITLE
Chinese characters

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5361]
Chinese characters does not shows correctly in PDF View. But it's showed perfectly in WEB view. Here with attached screenshot FYR.. Kindly check and resolve this issue.
**PDF VIEW:**
![PDF_View](https://github.com/openstax/cnx-recipes/assets/86622862/df87e5c7-2e90-48bb-b01e-cba636ed0f42)

**WEB View:**
![WEB_View](https://github.com/openstax/cnx-recipes/assets/86622862/72f6152c-f923-4a3f-918f-492e886d43f8)

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** community-population
- **ref/branch:** https://openstax-osbooksnursing-om7p9xrw6yq.ws-us106.gitpod.io/
- **chapter/section:**  Chapter 24/section 24.3
- **surrounding text:** practices. (credit: “Apothecary mixing traditional Chinese medicine

**Comment by lwtchu** [comment]
@srm-openstax Please remove the Chinese characters as they are just direct translations of the title (Chinese medicine pharmacy) and (Nanjing) respectively.

**Comment by srm-openstax** [comment]
Ok. Issue resolved. Kindly close the ticket.
