### ISSUE TITLE
information systems - generic things

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5363]
Documentation/list #2712

**Comment by kswanson33** [comment]
QA - please test that links are the right color, base font & spacing looks good, page bands are in the right place 🙏 should be on main

**Comment by MartaSztuka** [comment]
##### @kswanson33 lists are not styled yet
![Zrzut ekranu z 2024-01-08 17-10-10](https://github.com/openstax/cnx-recipes/assets/47241114/d267d414-a7a7-4dad-9963-55bb56ae824d)
#### PASSED
##### term
![Zrzut ekranu z 2024-01-08 16-58-25](https://github.com/openstax/cnx-recipes/assets/47241114/43c8c23a-040c-46d4-ba75-88f11a101a20)
##### table
![Zrzut ekranu z 2024-01-08 17-00-20](https://github.com/openstax/cnx-recipes/assets/47241114/db2beb45-45d6-4714-a82f-0e6422fd2e1a)
##### folio structure
![Zrzut ekranu z 2024-01-08 17-01-17](https://github.com/openstax/cnx-recipes/assets/47241114/f104d22b-d864-4067-9380-e3884c1bcecc)
##### link
![Zrzut ekranu z 2024-01-08 16-58-25](https://github.com/openstax/cnx-recipes/assets/47241114/43c8c23a-040c-46d4-ba75-88f11a101a20)

##### side bar in EOC/Answer Key
![Zrzut ekranu z 2024-01-08 17-11-40](https://github.com/openstax/cnx-recipes/assets/47241114/a69a589d-2653-4cf1-aefb-af5b38de237f)
##### images
![Zrzut ekranu z 2024-01-08 17-13-04](https://github.com/openstax/cnx-recipes/assets/47241114/2517908f-f90c-4505-91aa-d88899a89fdd)

**Comment by kswanson33** [comment]
<img width="642" alt="image" src="https://github.com/openstax/cnx-recipes/assets/26280712/49592e52-9f58-4174-a9e6-454b81b21b9e">

<img width="439" alt="image" src="https://github.com/openstax/cnx-recipes/assets/26280712/0d611c7a-8c22-4cd3-87d0-3462efb51bdf">

<img width="349" alt="image" src="https://github.com/openstax/cnx-recipes/assets/26280712/3d747569-29b8-492c-b26c-4d8549c6aa2d">

branch: styles `infosys-lists`

**Comment by Stackblocks** [comment]
Confirming that lists look good now.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/1a1cce37-233d-4ce6-b8bd-79de2512dba0)
