### ISSUE TITLE
information systems - table of contents

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5364]
Documentation #1740 
CONTAINS UNITS!!! **<-- Confirm this with Larissa.**

**Comment by MartaSztuka** [comment]
#### PASSED
**Unit 1** is duplicated, but it's content.


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/468e2b6c-04d6-482c-89f5-86f0e3f47c98)
