### ISSUE TITLE
information systems - figure and table caption styling

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5366]
Documentation: #2643

**Comment by wilkus27** [comment]
### Information for tester
Test only figures, tables will be handled within other issue.

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2024-01-05 16-55-35](https://github.com/openstax/cnx-recipes/assets/47241114/38c30409-47da-4494-b11c-7f8f20b4bcd6)
