### ISSUE TITLE
information systems - headers

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5367]
Documentation: #2644 

Follow blue color scheme.

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2024-01-05 17-00-41](https://github.com/openstax/cnx-recipes/assets/47241114/9eb0892d-783a-4d89-970c-979e8622909d)
![Zrzut ekranu z 2024-01-05 17-01-32](https://github.com/openstax/cnx-recipes/assets/47241114/c77d12f4-a91f-4756-b860-337037742c69)
