### ISSUE TITLE
information systems - chapter outline and introduction

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5368]
Documentation: #2655 
Blue version

**Comment by MartaSztuka** [comment]
@wilkus27 Second line in Chapter Outline isn't indented. Shouldn't it start with text not he numbers?
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/b85a1d8a-77bd-4ee4-9105-64980083ae51)

**Comment by wilkus27** [comment]
@lwtchu Should we fix problem that Sztuka mentioned?

**Comment by wilkus27** [comment]
If we decide to change that I will create separate card to not block work on the recipe.

**Comment by lwtchu** [comment]
@wilkus27 let's leave it as is. 🤔 we can open a card if they flag it I'm not sure what the norm usually is but we haven't had a lot of instances where titles are super long

**Comment by wilkus27** [comment]
Ok, thank you! I'm moving card to Corgi Testing in that case.
