### ISSUE TITLE
information systems - default tables

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5371]
Documentation #2741 
Need default tables and text heavy table

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2024-01-08 16-34-29](https://github.com/openstax/cnx-recipes/assets/47241114/1dfd4fce-999f-4dec-873d-1d63d387649f)
![Zrzut ekranu z 2024-01-08 16-36-37](https://github.com/openstax/cnx-recipes/assets/47241114/7ac8655e-fef8-4ed5-b593-a2b0fca95beb)
