### ISSUE TITLE
information systems - link to learning

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5376]
- Documentation: #2737 
- Color option 1
- Class: `<note class="link-to-learning">`
- Title: Link to Learning

**Comment by Stackblocks** [comment]
Link to learning displaying correctly on infosys-notes branch.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/81d0c4eb-5abb-43f6-b289-a1d3aab36a4d)
