### ISSUE TITLE
information systems - IS Future Tech

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5378]
- Documentation: #2737 
- `<note class="future-tech">`
- Color scheme option 2

**Comment by kswanson33** [comment]
<img width="500" alt="image" src="https://github.com/openstax/cnx-recipes/assets/26280712/aa0949f4-eacc-4af1-a8c5-873578e17d1c">

branch: `infosys-notes` on both styles and cookbook

**Comment by Stackblocks** [comment]
IS Future Tech displaying correctly on infosys-notes branch.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/0c8bd10b-c14f-4cf6-915c-9e421ac3be77)
