### ISSUE TITLE
information systems - IS Global Connect

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5379]
- Documentation: #2737 
- `<note class="global-connect">`
- Color scheme option 7

**Comment by kswanson33** [comment]
<img width="499" alt="image" src="https://github.com/openstax/cnx-recipes/assets/26280712/3ae9f1c2-5fef-4126-8391-2597745ca3aa">

branch: `infosys-notes` on both styles & cookbook

**Comment by Stackblocks** [comment]
IS Global Connect displaying correctly on infosys-notes branch.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/b220ee7e-bd69-40d9-b7f3-0e80dda9f240)
