### ISSUE TITLE
Feature Flag Epic

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#538]
Feature Flags should be all enabled and the feature flag should be removed for books upon release. 

This epic keeps track of the progress for each book and each feature flag. 

Currently enabled feature flag:
Link to spreadsheet: https://github.com/Connexions/cnx-recipes/blob/master/FEATURES.md

**Comment by brittweinstein** [comment]
Connexions/oer.exports#3724 
Connexions/cnx-recipes#537

**Comment by Stackblocks** [comment]
Feature Flags enabled for all of KatAW 1.0, Still need to be enabled across the business series.

**Comment by tomjw64** [comment]
@brittweinstein Is this epic still being updated? Looks like a lot has happened on release flags that isn't noted here

**Comment by brittweinstein** [comment]
@tomjw64 please link issues to this epic.
