### ISSUE TITLE
information systems - IS Ethics

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5380]
- Documentation: #2737 
- `<note class="is-ethics">`
- Color scheme option 3

**Comment by kswanson33** [comment]
<img width="499" alt="image" src="https://github.com/openstax/cnx-recipes/assets/26280712/755ac489-3aaa-4756-bad6-9731c82b5f40">

branch: `infosys-notes` on both styles and cookbook

**Comment by Stackblocks** [comment]
IS Ethics displaying correctly on infosys-notes branch.
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/2a04e79d-91c5-4b89-b10e-e6b159d5c910)
