### ISSUE TITLE
information systems - IS Careers

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5381]
- Documentation: #2737 
- `<note class="is-careers">`
- Color scheme option 6 (no icon)

**Comment by kswanson33** [comment]
<img width="495" alt="image" src="https://github.com/openstax/cnx-recipes/assets/26280712/0a54810f-ba21-4dc0-ba7d-6c555b60dd6a">

branch: `infosys-notes` on both styles and cookbook

**Comment by Stackblocks** [comment]
IS Careers displaying correctly on infosys-notes branch.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/3c95eab8-ffe0-4996-9f04-0939207045b0)
