### ISSUE TITLE
information systems - eoc assessment sections

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5382]
There are 4 assessment sections that all basically look the same.
![image](https://user-images.githubusercontent.com/11299125/112520529-83f6bc80-8d69-11eb-9b23-4cc3cbbed802.png)

- standard multiple choice exercise and will be pulled from exercises.tutor.org
- exercise number is bolded with period
- spacing between each exercise is the same as business ethics: 0.7rem
- numbering resets after every composite page

# Review Questions `review-questions`
icon: https://drive.google.com/file/d/1Ltc0whfkE49KScYfgJ_72T7f99_T7Brk/view?usp=sharing
title: Review Questions

# Check Your Understanding `check-understanding`
icon: https://drive.google.com/file/d/1Oz3Ej81o-JVLC75amloQ3m-YPDH-hoCN/view?usp=sharing
title: Check Your Understanding

# Reflection Questions `reflection-questions`
icon: https://drive.google.com/file/d/1-IA4Gbm1OlPC2bg8lSedIUUIrjvZdBrB/view?usp=sharing
title: Reflection Questions

# Media Questions `media-questions`
icon: https://drive.google.com/file/d/1MqJSaztF5LZ41-6LZvKhV8OXQC2asCPy/view?usp=sharing
title: Media Questions

**Comment by MartaSztuka** [comment]
#### PASSED
##### Review questions
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/d068705f-5ff1-4ed4-bf42-62145814e985)
##### Check Your Understanding
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/c37fb181-fd74-4850-bee7-6ef6807cf3d1)
##### Reflection Questions
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/da3e839b-9ec4-4512-b96d-75e4ded64dab)
##### Media Questions
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/d4e0157e-833f-46ce-a60d-ba032bf0f743)
