### ISSUE TITLE
Nursing external - pdf - Number list Alignment issue in Answer Key

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5383]
Number list alignment after 9th item does not shows correctly in PDF View for **all nursing courses**. The answer is slightly bumped to the right. Here with attached screenshot FYR. Kindly check and resolve this issue.

**Pharmology:**
![Pharm](https://github.com/openstax/cnx-recipes/assets/86622862/8834d665-eb7f-4b6a-8ac0-04fdb2074000)

**Nutrition:**
![Nut](https://github.com/openstax/cnx-recipes/assets/86622862/ade695f4-56e5-4b59-97e5-059e89fc103f)

**Pop Health:**
![PopHealth](https://github.com/openstax/cnx-recipes/assets/86622862/87ed13ef-36c0-440e-9ec7-9bc9d483763a)

# Acceptance Criteria
- Please check the alignment of question stem/answers in two digit numbered exercises
- It should be aligned with the other answers from the single digit numbered exercises
- Web view has a more accurate display - not sure if we want to use that approach 

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** community-population, Nutrition, Pharmology
- **ref/branch:** https://openstax-osbooksnursing-om7p9xrw6yq.ws-us106.gitpod.io/
- **chapter/section:** review-questions
- **surrounding text:**

**Comment by lwtchu** [comment]
@kswanson33 i think this is good. we won't go past 3-digit numbers i don't think

**Comment by Stackblocks** [comment]
Alignment looking good with the new changes.

## Nutrition

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/8043c39d-6071-42d3-b9fb-1968364778bf)

## Pharmacology

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/f3e3293f-d5df-427c-a2d5-d59c94de7e96)

## Community Population

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/69fbad47-8a09-4893-b848-ab4bf78b57df)
