### ISSUE TITLE
Statistics/Business Statistics - Webview - Space after "Problem" Header in Examples missing

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#5384]
# Brief Description of Scenario
This was not an issue in the 1e or in previous corgi jobs of the 2e; however, now when Intro Stats 2e or Biz stats 2e is generated, the new line disappears after "Problems" in Examples, smooshing the text together. See screenshot.

![Screenshot 2023-12-06 at 3 03 45 PM](https://github.com/openstax/cnx-recipes/assets/47189012/4746b0c2-f048-4331-9d3e-f9157256e3c5)

# Pattern of Occurrence 
It happens in all examples, from what i can tell

# Acceptance Criteria

A new line styling should occur after the "Problems" header to appear like this: 

![Screenshot 2023-12-06 at 3 38 07 PM](https://github.com/openstax/cnx-recipes/assets/47189012/243f71aa-b0fc-472b-b9df-99cde5ec78a8)
  
# Sample Mark-Up

```
<example id="fs-idm70107152"><exercise id="fs-idm53269072">
<problem id="fs-idm41679344">
<para id="fs-idm53163856">Determine what the key terms refer to in the following study.</para><para id="fs-idm19702944">As part of a study designed to test the safety of electric automobiles, the National Transportation Safety Board collected and reviewed data about the effects of an automobile crash on  test dummies. Here is the criterion they used:</para>
<table id="ch01_mod01_tbl003" summary="---">
<tgroup cols="2"><colspec colnum="1" colname="c1"/>
<colspec colnum="2" colname="c2"/>
<tbody>
<row>
<entry><emphasis>Speed at which cars crashed</emphasis></entry>
<entry><emphasis>Location of “drive” (i.e. dummies)</emphasis></entry>
</row>
<row>
<entry>35 miles/hour</entry>
<entry>Front Seat</entry>
</row>
</tbody>
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introductory-statistics-bundle
- **collection slug:** `introductory-statistics-2e` `introductory-business-statistics-2e`
- **ref/branch:** main
- **chapter/section:** all chapters
- **surrounding text:** Example

**Comment by Stackblocks** [comment]
Line break after `Problem` in Examples shows as restored with this fix.

## Stats 2e
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/bf2710e0-a9bc-4e05-88cd-5e7f5ee825d2)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/6f59cc26-9ef8-4879-91c9-d9d179ed00de)

## Intro Business Stats

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/76237992-1b15-49e6-a0e0-5e45afef13b3)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/117db0f4-e9c4-4112-85b3-56f40acf75b7)

**Comment by lwtchu** [comment]
Reopening this issue as we need to revert in #5458. Need to have a different approach for exercises labeled with a number vs a word

**Comment by MartaSztuka** [comment]
#### PASSED
##### Introductory statistics
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/766d7301-585b-4ec6-b2ea-f0e64ea27e82)
##### Introductory business statistics
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/d2ed0b0a-2bca-410f-b150-5eb4c9ed96ab)
