### ISSUE TITLE
Nursing Internal -- Revise Output in Chapter Opener to "INTRODUCTION"

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5385]
# Brief Description of Scenario
Revise Output in Chapter Opener to "INTRODUCTION" 
See screenshot below 
Applies to all titles in the Nursing Bundle
![image](https://github.com/openstax/cnx-recipes/assets/89537088/60ca8b56-929f-4515-b2ad-3ab5869b92fe)

# Pattern of Occurrence 
Every chapter opener in the Nursing Bundle
# Acceptance Criteria

  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** psychiatric-mental-health
- **ref/branch:**
- **chapter/section:** Chapter 4 / Section 0
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax Please change this in the module title. 
![Screenshot 2023-12-12 at 10 30 22 AM](https://github.com/openstax/cnx-recipes/assets/11299125/6db36a73-d0de-43be-9f3c-f09db83bfd48)

**Comment by ww-openstax** [comment]
changing this in the module title worked. Resolved.
