### ISSUE TITLE
information systems - section summary

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5387]
Documentation https://github.com/openstax/cnx-recipes/issues/2743
`class="summary"`
use blue option

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2024-01-11 16-35-26](https://github.com/openstax/cnx-recipes/assets/47241114/ea23129b-cf44-4f85-b2ef-9ab13c3040a4)
