### ISSUE TITLE
webview - image overflow issue impacting lazy loading/scroll

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5389]
# Context
https://github.com/openstax/unified/issues/2673

This card is to make sure we track for release purposes and documentation purposes.

## Impact 
Should impact all books since it's web styles

# Acceptance Criteria
Test criteria from Roy in PR
The issue is that some pages ([example](https://rex-web-production.herokuapp.com/books/workplace-software-skills@c795d5f/pages/preface?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20231109.173216)) in Rex have images down the page that have large `width` values, which causes the main content section to be horizontally-scrollable (hold shift and scroll the mouse wheel).
When you scroll down to them, they lazy-load, and once loaded, they are constrained to the normal page area. It's a weird artifact of the images not being loaded.
The test is that the page loads and is not horizontally-scrollable, and also that nothing looks weird about the images (like, they shouldn't have scroll bars).

## Location(s)
- Could try Entrepeneurship

**Comment by MartaSztuka** [comment]
#### PASSED
Tested on Entrepeneurship, everything loads properly and generally looks fine.
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/f5ba0ad2-2624-4a21-8b93-83239a4c9777)

**Comment by Stackblocks** [comment]
In the Workplace Skills Preface page that is used as the example currently as you scroll through the page you are unable to side-scroll with shift, but once the page has sat on any point for a while (~3 seconds on my machine / connection) you are able to side-scroll.

On Workplace Skills 1.1 you are able to side scroll from the jump. It's possible that whatever fix is in the pipe for this requires a new pipeline and as such (to the best of my understanding) will not be testable until that new pipeline is in place. 

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/1c0db4b7-96d9-44be-b6fe-f3c028de838a)

**Comment by Stackblocks** [comment]
Appears to be working fine with latest changes.

![CleanShot 2024-01-10 at 13 49 03](https://github.com/openstax/cnx-recipes/assets/12678235/0fef6c44-2788-4751-9821-0756bbaebb86)
