### ISSUE TITLE
carnival theme - subtitle in feature boxes discrepancy

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5392]
![image](https://github.com/openstax/cnx-recipes/assets/11299125/64450f0d-b24d-4343-908e-a6436fb9bf54)

![image](https://github.com/openstax/cnx-recipes/assets/11299125/1d1e97ff-73fb-4023-ba51-295f54a396df)

# Brief Description of Scenario
One is IBM Plex Sans bold and the other is Mulish medium. 

# Pattern of Occurrence 
Likely will impact carnival and cosmos themes

# Acceptance Criteria
Need to determine when and how to reconcile disrepancy. 

I think we should set it all to Mulish 
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** See any carnival theme books. Example comes from Nursing-External series
- **collection slug:**
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:**

**Comment by wilkus27** [comment]
@lwtchu Here are specs for notes titles:

#### Carnival
1. BoxedNoteShape (e.g. nursing-external - black-box)
  - title: Mulish
  - subtitle: IBM Plex Sans
 2. BoxCondensedNoteShape (e.g. hs-physics - tips-for-success)
  - title: Mulish
  - subtitle: IBM Plex Sans
 3. IconNoteShape (e.g. nursing-external - unfolding-casestudy)
  - title: Mulish
  - subtitle: IBM Plex Sans
 4. IconBoxedNoteShape (nursing-external - link-to-learning)
   - title: Mulish
  - subtitle: Mulish
 5. IconCondensedShape (anatomy - interactive)
   - title: Mulish
  - subtitle: IBM Plex Sans
 6. LogoNoteBoxedShape (microbiology - eye-on-ethics)
   - title: Mulish
  - subtitle: IBM Plex Sans


#### Cosmos
1. BoxedNoteWithSubtitleShape (american-government - milestone)
  - title: Archivo Black
  - subtitle: Archivo
2. CondensedIconNoteWithSubtitleShape (philosophy - media-video)
  - title: Archivo Black
  - subtitle: Archivo
3. IconFullPageNoteShape (english-composition - narrative-trailblazer)
  - title: Archivo
  - subtitle: Archivo
4. IconnedNoteWithSubtitleShape (american-government - get-connected)
  - title: Archivo Black
  - subtitle: Archivo

What changes do we want to make?

**Comment by lwtchu** [comment]
@wilkus27 let's change the carnival theme subtitles to mulish 

and for cosmos theme can we change the 3 - archivo title to archivo black?

**Comment by MartaSztuka** [comment]
#### PASSED
##### Pharmacology for nurses
![Zrzut ekranu z 2024-03-20 16-40-15](https://github.com/openstax/cnx-recipes/assets/47241114/cf212764-4069-4621-8469-24502c32fbda)
![Zrzut ekranu z 2024-03-20 16-39-53](https://github.com/openstax/cnx-recipes/assets/47241114/f861d64a-05be-4468-a119-f90fef5b05d8)
