### ISSUE TITLE
nursing-external - pdf - header-row entry table heads needs repeating 

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5394]
For this issue, We tried to modify the coding but the end result was not valid as per the Tagging legend and it was showed as error. We have updated the coding as two thead and differentiate the column headings but this coding was not accepted.
Kindly check and resolve this issue for all courses.
Here with attached screenshot FYR...

**The below example shows repeating heads when only column headers are present. This is the intended outcome.**
<img width="1250" alt="image001" src="https://github.com/openstax/cnx-recipes/assets/86622862/e1fb6eb6-bbce-4bd1-bc30-3458c5f9a4fd">
The below examples show row headings within a table and the row headings are not repeating. I believe this is only outcome due to the variations in the row headings. 
**First page:**
![image002](https://github.com/openstax/cnx-recipes/assets/86622862/5c6d38c4-b096-4395-b427-f66e94129bc9)
**Subsequent page**
![image003](https://github.com/openstax/cnx-recipes/assets/86622862/8869be69-5bc5-4de0-9174-02c693a3c744)
Another example with row headings that are not repeating on the subsequent page.
**First page**
![image004](https://github.com/openstax/cnx-recipes/assets/86622862/45035406-f3b8-49b7-8271-265db0c3231d)
**Subsequent page**
![image005](https://github.com/openstax/cnx-recipes/assets/86622862/d11153a3-9c40-41f2-92e5-27a81bb91ddc)

# Acceptance Criteria
- items tagged with `<row class="header-row">` need to transform to a `<th>` in the XHTML
- test to see if proper header styling gets applied
- test to see if headers will repeat
- please test with nutrition book first 
- hypothesis is prince XML will repeat `<th>` only; `<th>` in the middle of table should be supported in HTML https://www.w3.org/WAI/tutorials/tables/multi-level/
- it's ok if both headers repeat (any headers should repeat)

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** All Courses
- **ref/branch:** https://openstax-osbooksnursing-om7p9xrw6yq.ws-us106.gitpod.io/
- **chapter/section:**  All Courses
- **surrounding text:**

**Comment by lwtchu** [comment]
Email from Cindy Jan 4: Only Tables 13.2, 19.6, 10.9, and 20.2 have row headings, and there is currently no issue with any of these tables. However, we will keep a watch out during our full book QA in case any rewrapping of pages would cause these tables to split differently.

**Comment by kswanson33** [comment]
Questions:

1. what should repeat? in the case of two headers (eg. Table 5.2 "Colloidal Intravenous Solutions" & "Solution Classifications | Fluid Names | ...") i could see both headers repeating to the second page / just the first header (single table cell for the row) / just the second header (contains headers for each column)
    1. the Table 26.2 case is flipped  --> first header = headers for each column & second header = single table cell for the row. how should this work?
1. re: [above comment](https://github.com/openstax/cnx-recipes/issues/5394#issuecomment-1917702763) does this mean there is no test data application for this card currently?

i found this example -- table 5.2 in pharmacology:

![image](https://github.com/openstax/cnx-recipes/assets/26280712/8e1d7886-608a-46a8-96c2-491f50b161d6)

however, `class="header-row"` is not present in the cnxml nor xhtml

**Comment by srm-openstax** [comment]
We have included the header-row tag as per you instruction in the column header but it's not supported in the CORGI generated PDF.

CNXML coding screenshot:

![CNXML](https://github.com/openstax/cnx-recipes/assets/86622862/81d175ce-bda2-4d3f-9287-efe87b33e306)

PDF screenshot:

![ticket1](https://github.com/openstax/cnx-recipes/assets/86622862/de42bf4b-edd5-4b31-b7c6-c9b1715d98db)

**Comment by kswanson33** [comment]
further investigated this. the `thead` element (different from `th`), which [allows table headers to repeat](https://stackoverflow.com/a/274161), is only allowed [once per table](https://html.spec.whatwg.org/multipage/tables.html#the-thead-element), and must be ahead of the `tbody` elements

one way to get this effect could be to use multiple tables. a pseudocode outline:

```html
<table>
  <thead>
    <tr>
      <th>Header cell 1</th>
      <th>Header cell 2</th> 
      ...  # as many cells as needed
    </tr>
  <tbody>
    <tr>    
      <td colspan="all"><table>... Inner table 1 with subheader in its `thead` ... </table></td> # just one cell per row in the outer table
    </tr>
    <tr>
      <td colspan="all"><table>... Inner table 2 ...</table></td>
    </tr>
   ... # more tables
  </tbody>
</table>
```
