### ISSUE TITLE
statistics 2e - if a title goes to two lines, it adds a white space to the splash

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5395]
![Screenshot 2023-12-15 at 10 06 08 AM](https://github.com/openstax/cnx-recipes/assets/11299125/a17d4fc6-0eb1-4303-b77e-80b8b7e69f64)

# Brief Description of Scenario
I think this is only happening to chapters where the titles are long and goes to the second line. Chapter 9, 10 and 12

# Acceptance Criteria
- [ ] white space is removed 
  

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introductory-statistics-bundle
- **collection slug:** introductory-statistics-2e
- **ref/branch:** main
- **chapter/section:**  chapter 9 splash
- **surrounding text:**

**Comment by wilkus27** [comment]
### Information for tester

Changes for this issue have impact on all books from Corn Theme

**Comment by Stackblocks** [comment]
Splashes displaying properly with the new change.

## Stats 2e
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/ff1d7cfb-9154-4266-8338-60d47d1f8a08)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/7218ef38-0341-4afe-9d3b-9a1db96ad122)

## Precalc
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/d7ec1f71-3aee-452b-bdf2-20578ebd956d)
