### ISSUE TITLE
Reference link break issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5396]
We did not provide any extra space in the reference URL link. Based on the text content, it will go to the next line in the PDF. Refer to the attached screenshot (CNXML). We can’t manually adjust the spacing in the workspace. We have noticed a similar issue in pharmacology as well. Could you please resolve this issue?

**Population Health:** **Chapter 9:**
**PDF:**
![Reflink](https://github.com/openstax/cnx-recipes/assets/86622862/2e3dbcfb-2c06-4f10-922b-2737945abc77)
**CNXML**
![CNXML](https://github.com/openstax/cnx-recipes/assets/86622862/094864a5-4e50-417e-a800-e3063ee47555)
**Pharmacology** **Chapter 05**
**PDF:**
![Chapter_5](https://github.com/openstax/cnx-recipes/assets/86622862/338b6a84-9ed5-4d5f-a423-4a3076581329)
**CNXML:**
![Chapter_5(CNXML)](https://github.com/openstax/cnx-recipes/assets/86622862/a75030de-505f-4f5b-91af-c26081c6f090)

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** community-population, Pharmacology
- **ref/branch:** https://openstax-osbooksnursing-om7p9xrw6yq.ws-us107.gitpod.io/
- **chapter/section:** Reference section
- **surrounding text:** --

**Comment by lwtchu** [comment]
@srm-openstax The link is auto-generated by the PDF reader and will vary depending on what tool is used to view the PDF. We purposefully do not hyperlink the links in references from a design and usability standpoint. Please leave as is.
