### ISSUE TITLE
nursing-external - pdf - table rules/lines disappearing with merged cells

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5398]
We noticed that the ruler of the table "Appendix B" is not properly aligned in the PDF version. It seems to be slightly misaligned and the same table ruler perfectly fixed in the web view. (Refer to the current version PDF and WEB view screenshot)
In the previous version PDF, we did not encounter any problems with the table ruler, which makes us believe that the code release "Dec 19" might be responsible for the current issues. (Refer to the previous version PDF screenshot)
Note: Additionally, we completely checked the tagging structure there are no issues at our end.

![Appendix_B_WEB-VIEW1](https://github.com/openstax/cnx-recipes/assets/86622862/a3681099-ad9a-4e4a-8ab9-856ee3e068a0)
![Appendix_B_1_PDF](https://github.com/openstax/cnx-recipes/assets/86622862/91a2465a-1104-4c61-8eda-7a21ddb9df24)
![Appendix_B_WEB-VIEW2](https://github.com/openstax/cnx-recipes/assets/86622862/c4999b4c-1159-4785-9184-e82338d0a1b3)

Please check with concern and advise.

# Acceptance Criteria
- might be related to #5251
- this is in the appendix so those fixes might not have populated through

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** Pharmology
- **ref/branch:** https://openstax-osbooksnursing-om7p9xrw6yq.ws-us107.gitpod.io/
- **chapter/section:**  Appendix B
- **surrounding text:**

**Comment by wilkus27** [comment]
### Information for tester

In my PR I'm adding right border to all columns except the last one. Previously we were adding border to particular cells (actually we still do, I just override this with new property). This change affects all books from Carnival.

**Comment by Stackblocks** [comment]
Alignment issue appears to be fixed with the new changes. 
Going to test additional carnival books to check extended impact.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/eebeac4d-e3e3-43f9-8c11-3a531fb88606)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/102a4e70-2fae-4665-bb94-cfc22a09300f)
