### ISSUE TITLE
nursing-external - webview - links from answer key back to Unfolding Case study section does not go to right location

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5399]
**SRM Editorial Comments:** Check the link back from answer key to BOTH questions in web view. It's not going to the right place.
**SRM PRODUCTION Comments:**  The problem lies with the 1st section questions link. Currently, when we click on the UNFOLDING questions link, it correctly takes us to the ANSWER KEY 1st section answer. However, if we try to access the ANSWER KEY from the UNFOLDING 1st section questions, it takes us to the wrong place. We suspect these issues occurred in the background process.
 
We analysing the other chapters 7, 8 & 10 found that the after-1st section links both question and answer reference links are working perfectly. However, we identified the issues specifically with the 1st section link.

 We thoroughly checked the tagging it's not in our issue. Please check and resolve this issue. Here with attached screenshot FYR...

**Unfolding Case-study (Question-Answer)**
![Sectionlevel_1](https://github.com/openstax/cnx-recipes/assets/86622862/e8da2761-ae32-4269-be63-2b5a5bee23fe)

**Section1(unfoldingcasestudy_forwardlink)**
![section1(unfoldingcasestudy_forwardlink)](https://github.com/openstax/cnx-recipes/assets/86622862/3932a8d2-1a3d-42c1-8671-187dbb0cea2e)

**Section1(anserkey-reverselink)**
![section1(anserkey-reverselink)](https://github.com/openstax/cnx-recipes/assets/86622862/c71fc3c1-128e-46c2-8807-a0d87c82fc7b)

# Acceptance Criteria
- this is likely related to lazy loading - QA please retest once that fix goes out

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** community-population, Nutrition, Pharmology
- **ref/branch:** https://openstax-osbooksnursing-om7p9xrw6yq.ws-us107.gitpod.io/
- **chapter/section:** Unfolding-case study
- **surrounding text:**

**Comment by lwtchu** [comment]
Notes for OS: This might be related to image lazy loading. Propose to check again once the fix for it goes out. URL is correct and the issue is not always replicable depending on the loading speed of the page and browser.

**Comment by kswanson33** [comment]
unable to reproduce 2/1/24, could the above fix have gone out?

**Comment by lwtchu** [comment]
@kswanson33 yeah - we were pretty sure the lazy loading issue would've fixed this. we can close the card.
