### ISSUE TITLE
Introduction to Python Programming - "New colors" comment in production revisions spreadsheet from ZyBooks

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5400]
# Brief Description of Scenario
This is a comment from ZyBooks in the Python Production Revisions Google Sheet
https://docs.google.com/spreadsheets/d/1iLZhWxVY_n06ac_QDSzkrdGlGUeoQPP6sChw-1uGjeo/edit?usp=sharing
### Spreadsheet
![image](https://github.com/openstax/cnx-recipes/assets/89537088/22f28c44-b5b5-4e89-9e27-b83c10273a51)
### PDF with Reviewer Comment
![image](https://github.com/openstax/cnx-recipes/assets/89537088/db4142d6-0b96-419f-ad99-472cddbbb329)

# Pattern of Occurrence 

# Acceptance Criteria

  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** Chapter 10 / Section 4
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax These are the standard colors for the no class note, example and Concepts in Practice. It might just be weird to see it all together? Closing since I don't think there's an issue. If something else is expected, please let me know.

**Comment by openstaxalina** [comment]
(We will communicate to zyBooks that no action will be taken based on this comment.)
