### ISSUE TITLE
Introduction to Python Programming - "Replace image " comment in production revisions spreadsheet from ZyBooks

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5401]
# Brief Description of Scenario
Please create and deliver to WW new image as indicated in Python Production Revisions Google Sheet from ZyBooks
https://docs.google.com/spreadsheets/d/1iLZhWxVY_n06ac_QDSzkrdGlGUeoQPP6sChw-1uGjeo/edit?usp=sharing
### Spreadsheet
![image](https://github.com/openstax/cnx-recipes/assets/89537088/9fa96c73-ac4e-4697-8975-87bb1fdd0bb6)

# Pattern of Occurrence 

# Acceptance Criteria

  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** Chapter 13 / Section 5
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax Here's the updated image https://drive.google.com/file/d/1ANIm8j2eBjqyXGNoCHuk1yLpCCpX9RIM/view?usp=drive_link

**Comment by ww-openstax** [comment]
WiseWire has successfully replaced image
