### ISSUE TITLE
Introduction to Python Programming - "Code Runner revision notes" tab in production revisions spreadsheet from ZyBooks

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5402]
# Brief Description of Scenario
FYI: There is a tab in the production revisions spreadsheet from ZyBooks labelled "Code Runner revision notes"
![image](https://github.com/openstax/cnx-recipes/assets/89537088/2f15c0cb-33f4-41c2-aa46-51b31c0dd75b)

# Pattern of Occurrence 

# Acceptance Criteria

  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:**

**Comment by openstaxalina** [comment]
@ww-openstax I'm working with zyBooks to finalize this, and will deliver to WW when changes are ready. This will be one batch of trailing edits along with some updated code runner files for replacement in the repo (mentioned last week). 

I'm going to close this card.
