### ISSUE TITLE
[blocked content fix permission] Introduction to Python Programming - code/emphasis tagging results in duplicating output issues

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5405]
# Brief Description of Scenario
`<emphasis effect="bold">` inside of `<code class="python" lang="python">` results in output issues

### output with code/emphasis tagging
![image](https://github.com/openstax/cnx-recipes/assets/89537088/e8c7420b-a1a9-4805-a1ee-63a3936aa019)

### output without code/emphasis tagging
![image](https://github.com/openstax/cnx-recipes/assets/89537088/f7f13850-90a1-464b-81d7-b99c10821e9f)

# Pattern of Occurrence 

# Acceptance Criteria
Related to https://github.com/openstax/cnx-recipes/issues/5403. HTML tags are prompting highlight.js to duplicate content. Need to figure out how to make at the VERY LEAST italic and bold tagging to work. Work around for line breaks is to just have a line break in the code text. 

- must have italics working
- must have bold working 
- must have no duplicate text

Ideally code shouldn't repeat 
  
# Sample Mark-Up
```
    <note class="practice-program" id="note-00007">
    <title>Name and likes</title>
    <para id="para-00015">Write a program that asks the following two questions (example input in bold):</para>
    <code class="python" lang="python">
    What is your name? <emphasis effect="bold">Shakira</emphasis>
    What do you like? <emphasis effect="bold">singing</emphasis>
    </code>
    <para id="para-00016">Output a blank line after reading the input. Then output the following message based on the input:</para>
    <code class="python" lang="python">
    <emphasis effect="bold">Shakira</emphasis> likes <emphasis effect="bold">singing</emphasis>
    </code>
    <media alt="name_likes_program">
    <iframe width="660" height="371.4" src="../../media/interactive/coderunner/ch1/CodeRunner_01_03_03_Name-likes.html"/>
    </media>
    </note>
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:** 
- **chapter/section:** Chapter 1 / Section 2
- **surrounding text:**

**Comment by ww-openstax** [comment]
@lwtchu it looks like this issue was introduced with a code release. Output was as expected 26 days ago.
See CORGI Job 8523. Section 2.5
![image](https://github.com/openstax/cnx-recipes/assets/89537088/d0c210bd-82ad-414b-b748-510544ff6cd2)
![image](https://github.com/openstax/cnx-recipes/assets/89537088/6575b250-f95a-40c7-97bd-247f668d5e98)

**Comment by lwtchu** [comment]
I think there's two issues - one is bold isn't consistently coming through in Google Chrome but does in the PDF/Firefox.

Another issue is the duplication of content 

First to check if highlight.js accepts emphasis tags. Second is to see if the Chrome issue is a browser isolated issue

**Comment by lwtchu** [comment]
Holding this pending Larissa's content fix ideas - getting permission

**Comment by openstaxalina** [comment]
Update sent to WW with 1/16 and 1/31 release emails:

#5405 - code/emphasis tagging results in duplicating output - OpenStax plans to not use highlight.js when the bold tag is present in code. This matches the treatment on the zyBooks platform. OpenStax will make this change after Wisewire delivers your final content.

**Comment by lwtchu** [comment]
This should be fixed with the content fixes that Colby did for final content
