### ISSUE TITLE
custom PDF request - LLM - generate one off PDFs with headers for assessment sections

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5406]
Hello! I would like to add in section headers for EOC assessments that point back to the modules that they came from. Format can be simple `#.# Title of Module`

# Context
This is to aid WW in their assessment work 

# New specifications or link to documentation cards
Books that need this
- Business Law 
- Intellectual Property

## Impact 
DO NOT MERGE THESE CHANGES. I just need a locally generated PDF

# Acceptance Criteria
- 2 new PDFs sent to Larissa w module headers for collated assessments in the EOC

Locations
https://github.com/openstax/osbooks-business-law - slug: business-law-i-essentials
https://github.com/openstax/osbooks-introduction-intellectual-property - slug: introduction-intellectual-property
please use the main branch with most up to date content

both uses business-ethics recipe

both have assessments tagged to the section with the `class="assessment-questions"`

**Comment by lwtchu** [comment]
Related to previously done work here https://github.com/openstax/cnx-recipes/issues/5397

**Comment by kswanson33** [comment]
header code published on [draft branch](https://github.com/openstax/cookbook/pull/335) (not for merge)

**Comment by lwtchu** [comment]
Delivered
