### ISSUE TITLE
Introduction to Python Programming - pdf - Remove extra padding between distractors 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#5409]
# Brief Description of Scenario and Screenshots

some exercises have more space between distractors than others 
the ones with extra space have `<code class="python">`

<img width="474" alt="Screenshot 2024-01-05 at 1 47 17 PM" src="https://github.com/openstax/cnx-recipes/assets/5865292/f7fc9290-113b-49f8-a4cb-35b528917866">

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
In distractors with code, it seems

# Acceptance Criteria
- is there a way to reduce padding to have it look like the other mc questions (not double space between distractors)

# Sample mark up if applicable
```
<code class="python" lang="python">2.0 &lt;class 'int'&gt;</code>
```

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-introduction-python-programming
collection slug (if applicable): introduction-python-programming
chapter/section: various
surrounding text:

**Comment by Stackblocks** [comment]
Distractors now showing with correct spacing

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/e35a8ccb-ebbe-4513-85b0-48452c083ad7)
