### ISSUE TITLE
Python - Add Highlight.js to web view

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#5410]
# Context

During Colby's review, we noted that the color does not appear to be added to code snippets in web view. See example screenshots of the same content in PDF and web preview:

![Screenshot 2024-01-17 at 9 42 01 AM](https://github.com/openstax/cnx-recipes/assets/7863733/0de70668-c72f-433c-ada9-29365367034f)

![Screenshot 2024-01-17 at 9 52 09 AM](https://github.com/openstax/cnx-recipes/assets/7863733/4db521a4-f661-4d3a-a007-0953beaa03fc)

# New specifications or link to documentation cards
Please implement highlight.js for the web view (has already been implemented for PDF with #5351 )

## Impact 
Python book. Likely also needed for Introduction to Computer Science and Principles of Data Science. Deferring to Larissa whether to make them all part of this card.

# Acceptance Criteria
- [ ] when a code snippet in the Python book has colors in the PDF, it displays the same colors on the web

# Content
## Sample Mark-Up
```
 <code class="python" lang="python">
    import math
    
    x1 = float(input("Enter x1: "))
    y1 = float(input("Enter y1: "))
    x2 = float(input("Enter x2: "))
    y2 = float(input("Enter y2: "))
    
    distance = math.sqrt((x2-x1)**2 + (y2-y1)**2)
    print("The distance is", distance)
    </code>
```

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:** main
- **chapter/section:** varies, but above example is from 2.6 
- **surrounding text:** "Calculating the distance between two points"

**Comment by MartaSztuka** [comment]
#### PASSED


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/86028bc5-847d-4e2a-b5f3-77c7c14b8ded)
