### ISSUE TITLE
nursing-external - webview and pdf - Suggested Reading list is not in alphabetical order

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5412]
# Context
The end-of-chapter Suggested Reading section does not sort entries into alphabetical order or include a hanging indent.
![Screenshot 2024-01-18 at 12 13 20 PM](https://github.com/openstax/cnx-recipes/assets/99201272/dc46fb2e-12e8-4779-80e5-90688c3ab21b)

# New specifications or link to documentation cards
Sort paragraphs in the EOC Suggested Reading section alphabetically and implement a hanging indent, like sources appear in the References section (documentation https://github.com/openstax/cnx-recipes/issues/5014) (see example below).
![Screenshot 2024-01-18 at 12 15 15 PM](https://github.com/openstax/cnx-recipes/assets/99201272/fe35a9a4-6065-4d00-9484-286bccfa6b95)

## Impact 
All nursing-external books

# Acceptance Criteria
The entries under Suggested Reading should appear in alphabetical order the way sources do in References shown above.

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** All
- **ref/branch:** Main
- **chapter/section:** All chapters
- **surrounding text:**

**Comment by openstaxalina** [comment]
Thank you! Putting this in the c.c. sprint to start January 29. Meanwhile, I emailed the Nursing-external lead editors to confirm the change is acceptable and if they would have any related requests.

**Comment by openstaxalina** [comment]
Confirmed w/ SRM Nursing leads: "These changes would be most welcome. Terrific suggestions!"
Thank you, @caylaeagon !

**Comment by MartaSztuka** [comment]
#### PASSED
##### Nutrition
###### PDF
![Zrzut ekranu z 2024-01-31 11-14-43](https://github.com/openstax/cnx-recipes/assets/47241114/650662ee-f670-4178-ae49-4dd45c4636aa)
###### webview
![Zrzut ekranu z 2024-01-31 11-12-50](https://github.com/openstax/cnx-recipes/assets/47241114/eb1bf83c-5820-47dd-a164-e049dc162d4c)
