### ISSUE TITLE
Econ custom PDF request - LLM - generate one off PDFs with headers for assessment sections

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#5413]
Hello! I would like to add in section headers for EOC assessments that point back to the modules that they came from. Format can be simple `#.# Title of Module`

# Context
This is to aid WW in their assessment work 

# New specifications or link to documentation cards
Books that need this
- Principles of Economics 3e

## Impact 
DO NOT MERGE THESE CHANGES. We just need a locally generated PDF

# Acceptance Criteria
- 1 new PDF ~sent to Alina~ delivered [**here**](https://drive.google.com/drive/u/0/folders/10ME2jAqjIRJboC655gTh8sNBOiZiIKsp) with notification to Alina w module headers for collated assessments in the EOC

Locations
https://github.com/openstax/osbooks-principles-economics-bundle 
book slug: principles-economics-3e
please use the main branch with most up to date content

uses `economics` recipe

there are 4 question types that were input with their respective modules and collate to EOC. the classes are:
`self-check-questions`
`review-questions`
`critical-thinking`
`problems`

**Comment by openstaxalina** [comment]
@kswanson33 here is another of these. would it be possible to provide this PDF by Wednesday 1/24?
the other two issues for the same type of thing were #5397 and #5406

**Comment by kswanson33** [comment]
yessir! i'll get to it first thing monday

**Comment by kswanson33** [comment]
![image](https://github.com/openstax/cnx-recipes/assets/26280712/890b438b-2bb6-44fe-b3d4-d00ca8ec8180)

**Comment by openstaxalina** [comment]
Thank you @kswanson33 ! Delivered to WW; closing ✅
