### ISSUE TITLE
nursing-external - Third level bullet list (Pharmacology)

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5414]
In the PDF, the third level of bullets should be further indented, and the black squares are too large compared to the other bullets. This looks fine in both respects in the web view, but not in the PDF.
**PDF VIEW:**
![Pharmology](https://github.com/openstax/cnx-recipes/assets/86622862/cef043f8-26c4-41f7-9f83-10353e0f61b9)
**WEB VIEW:**
![WEB VIEW](https://github.com/openstax/cnx-recipes/assets/86622862/5de58446-cc68-4845-bd69-1474641502c9)

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** Pharmacology
- **ref/branch: **https://openstax-osbooksnursing-om7p9xrw6yq.ws-us107.gitpod.io/
- **chapter/section:** Chapter 02 / Section 03
- **surrounding text:** When drawing up medications into syringes that are not insulin or tuberculin syringes:

**Comment by openstaxalina** [comment]
Putting in c.c., but since this is **not** Nutrition, could go to d.d. or later if needed (once those are created)

**Comment by wilkus27** [comment]
### Information for tester
Changes have impact on all books from Carnival.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Pharmacology
###### PDF
![Zrzut ekranu z 2024-01-30 15-23-53](https://github.com/openstax/cnx-recipes/assets/47241114/416b43ae-4fc3-4030-b19a-c82bc7dc2824)
###### webview
![Zrzut ekranu z 2024-01-30 15-46-13](https://github.com/openstax/cnx-recipes/assets/47241114/0029b078-e23d-4a3a-bbe1-8dac728ee39e)

**Comment by lwtchu** [comment]
@wilkus27 the bullets in the pdf doesn't seem to be centered on the line
![Screenshot 2024-01-30 at 8 59 14 AM](https://github.com/openstax/cnx-recipes/assets/11299125/d5ab3d1a-f3be-4091-b60d-6db722f4cf82)
