### ISSUE TITLE
Nursing Internal -- Splash image -- output in PDF is different from output in Webview

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5415]
# Brief Description of Scenario
The splash image is not outputting in the same way in PDF versus Webview. 
WiseWire believes the source image has been processed correctly. Can OSX provide some guidance on whether the source image (OSX_Fund_03_00_HCDeliver.jpg) is created correctly, please? If the source image is OK then troubleshooting is needed to correct the PDF output.
### PDF 
![image](https://github.com/openstax/cnx-recipes/assets/89537088/9e1295de-0e5a-43b9-928f-8c1e771032da)

### Webview
![image](https://github.com/openstax/cnx-recipes/assets/89537088/d48e374a-ca50-421e-b455-4f85e1f03579)

# Pattern of Occurrence 

# Acceptance Criteria

  
# Sample Mark-Up
```
<content class="introduction">
    <figure class="splash" id="fig-00001">
      <media alt="A collage showing an ambulance, a provider examining a child, researchers using a microscope, a physical therapist stretching a patient’s arm, and a nurse sitting with a patient.">
      <image mime-type="image/jpeg" src="../../media/OSX_Fund_03_00_HCDeliver.jpg"/>
      </media>
      <caption>Healthcare delivery systems include all aspects of public and private health, wellness, and prevention and must include a culture of cooperation and collaboration. Nurses have an active role in the healthcare delivery system and directly impact it. (credit upper-left: “American Medical Response Ambulance” by Raymond Wambsgans/Wikimedia Commons, CC BY 2.0; credit upper-right: “US Navy 070919-N-6278K-056 Lt. Cmdr. Mary Gracia, a pediatric nurse practioner attached to Military Sealift Command hospital ship USNS Comfort (T-AH 20)” by U.S. Navy/Wikimedia Commons, public domain; credit center: “Researcher looks through microscope (2)” by National Cancer Institute/Wikimedia Commons, public domain; credit lower-left: “USMC-100804-M-3909A-294” by US Marine Corp/Wikimedia Commons, public domain; credit lower-right: “Close up of nurse comforting ill patient in hospital ward” by DCStudio/FreePik, free license)</caption>
      </figure>
```

# Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** nursing-fundamentals
- **ref/branch:**
- **chapter/section:** Chapter 3 / Section 0 / Splash Image
- **surrounding text:**

**Comment by openstaxalina** [comment]
Putting this in c.c., but since this is **not** Nutrition, it could go to d.d. or further if needed (once those are created)
