### ISSUE TITLE
Astronomy splash page number missing

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5416]
# Brief Description of Scenario
New Astronomy pdf does not show page numbers on splash images

# Pattern of Occurrence 
every splash page
<img width="1642" alt="Screenshot 2024-01-23 at 1 10 02 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/46c97a1e-0165-4262-96a1-b86a6905fbda">

# Acceptance Criteria

  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-astronomy
- **collection slug:** astronomy-2e
- **ref/branch:**
- **chapter/section:** all
- **surrounding text:**

**Comment by openstaxalina** [comment]
assigning to c.c., but may move to d.d. or beyond since the priority for c.c. is **Nutrition**.

**Comment by jbwilson8** [comment]
Decision was made to remove page numbers from splash images.
