### ISSUE TITLE
Astronomy splash captions now double-spaced

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5417]
# Brief Description of Scenario
New (left) Astronomy chapter splash image captions are double-spaced instead of single.
<img width="1600" alt="Screenshot 2024-01-23 at 1 21 16 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/aced14ef-d7d0-4dee-bed3-f1e5e06e93fb">

# Pattern of Occurrence 
Every instance

# Acceptance Criteria

  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** 
- **collection slug:**
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:**

**Comment by openstaxalina** [comment]
assigning to c.c., but may shift later since the priority for c.c. is **Nutrition**.

**Comment by jbwilson8** [comment]
Please check against theme specs

**Comment by wilkus27** [comment]
@lwtchu It looks like it was done unintentionally. Ania added such comment to her changes: https://github.com/openstax/ce-styles/pull/43#discussion_r927679099

![image](https://github.com/openstax/cnx-recipes/assets/40228854/ae543b7b-5bed-42d5-9e31-d1d08d498d48)


but based on the issue description (https://github.com/openstax/cnx-recipes/issues/4703) I think she meant margin, and line height was removed by accident. Also captions for regular figures and tables still have this property, so I will add it back for splash image caption as well.

**Comment by wilkus27** [comment]
### Information for tester
It has an impact on all books from Cardboard.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Astronomy
![Zrzut ekranu z 2024-02-07 14-36-24](https://github.com/openstax/cnx-recipes/assets/47241114/3a4bb489-9cae-4a7d-bb57-e97c8f2a0d26)
![Zrzut ekranu z 2024-02-07 15-10-14](https://github.com/openstax/cnx-recipes/assets/47241114/c18a7d7d-9609-48d9-ba07-a72438ba2154)


##### Finance
![Zrzut ekranu z 2024-02-07 14-51-20](https://github.com/openstax/cnx-recipes/assets/47241114/79493c7f-ecbf-4700-bc2a-00c3b1d0adc5)

##### Marketing
![Zrzut ekranu z 2024-02-07 15-08-29](https://github.com/openstax/cnx-recipes/assets/47241114/4353edbf-a45a-45c8-bed4-d2efd351b209)
