### ISSUE TITLE
Astronomy index terms in Learning Objectives misalign formatting

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5419]
# Brief Description of Scenario
When there are `<term class="no-emphasis">` tags in a learning objectives section in Astronomy, they switch the formatting to some kind of 2- or 3-column mess (new on the left)
<img width="639" alt="Screenshot 2024-01-23 at 1 52 48 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/033f7bea-6ece-4de5-a0e4-d3d424e09088">
<img width="1561" alt="Screenshot 2024-01-23 at 1 50 39 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/3c929f04-e013-442e-a920-358d9b785ad6">

<img width="1538" alt="Screenshot 2024-01-23 at 2 31 53 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/f6394d75-e398-4963-8daf-8aca05cb8578">
<img width="1564" alt="Screenshot 2024-01-23 at 2 28 03 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/3634f4dc-d7d4-4a64-aad2-48f1c4ecc91e">

![Uploading Screenshot 2024-01-23 at 2.34.00 PM.png…]()

If it doesn't make an entirely new line out of the term, it might delete a space before it:
<img width="1506" alt="Screenshot 2024-01-23 at 2 29 25 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/5902f4b5-ed7a-4d06-80fb-c8eb09c2dfed">

# Pattern of Occurrence 
every time there is a term tag in the learning objectives

# Acceptance Criteria

  
# Sample Mark-Up
```
<section id="fs-id1168047344108" class="learning-objectives">
<title>Learning Objectives</title>
<para id="fs-id1168583236844">By the end of this section, you will be able to:</para>
<list id="fs-id1168047248886">
<item>Explain how star clusters help us understand the stages of <term class="no-emphasis" id="term-00001">stellar evolution</term></item>
<item>List the different types of <term class="no-emphasis" id="term-00002">star cluster</term>s and describe how they differ in number of stars, structure, and age</item>
</list>
</section>
```

# Location(s)
- **osbooks repo:** osbooks-astronomy
- **collection slug:** astronomy-2e
- **ref/branch:**
- **chapter/section:** for example, ch 22.2 Star Clusters
- **surrounding text:** Explain how star clusters help us understand the stages of

**Comment by openstaxalina** [comment]
assigning to c.c., but may shift later since the priority for c.c. is **Nutrition**.

**Comment by Stackblocks** [comment]
LO spacing and structure look consistent following the update.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/95da5dd3-c4f5-4477-a453-c6764b0741e6)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/7b9114f1-b7f8-4143-80b4-30cfe41076e3)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/25d9d099-181a-4623-bfcf-06af6774901d)
