### ISSUE TITLE
Astronomy Appendix header size change

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5420]
# Brief Description of Scenario

H2 and H3 header sizing has changed in the Astronomy appendices
New on the left (note the line break)
<img width="1517" alt="Screenshot 2024-01-23 at 2 45 45 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/afcd4d41-0f4c-4bcd-a835-21a46aa2eae6">
# Pattern of Occurrence 
<img width="1517" alt="Screenshot 2024-01-23 at 2 45 45 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/afcd4d41-0f4c-4bcd-a835-21a46aa2eae6">

# Acceptance Criteria

  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** 
- **collection slug:**
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:**

**Comment by openstaxalina** [comment]
assigning to c.c., but may move to d.d. or beyond since the priority for c.c. is **Nutrition**.

**Comment by lwtchu** [comment]
We made a decision to bump up header sizing to accommodate smaller headers -- how big of a page count difference did this result in @oscryan

**Comment by oscryan** [comment]
Not appreciable.
