### ISSUE TITLE
Introduction to Python Programming - Python Code output in PDF indenting wrong in some instances; doesn't match output in Webview

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5425]
# Brief Description of Scenario
There are some instances where the indenting and other output of the Python Code is not correct in the PDF. It is correct in Webview
This is a new issue and occurred after the fix for https://github.com/openstax/cnx-recipes/issues/5351

### WebView
<img width="567" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/b42e2b25-cb88-49bb-b550-890ac8a8a231">

### PDF
<img width="468" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/e745d857-2857-409e-89c8-f70912210814">

### WebView
<img width="568" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/8e67da93-be14-4773-bb0e-7c7edaa0b2e4">

### PDF
<img width="464" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/45bc0098-a748-4400-a573-997a66ff4be2">

# Pattern of Occurrence 
Not every instance of Python code has this issue. Only some instances. Not every instance has been included here.

# Acceptance Criteria

  
# Sample Mark-Up
```
<code class="python" lang="python">
    # Initializing the first two Fibonacci numbers
    f = 1
    g = 1
    print (f, end = ' ')

    # Running the loop while the last Fibonacci number is less than 20
    while g &lt; 20:
      print(g, end = ' ')
      # Calculating the next Fibonacci number and updating the last two sequence numbers
      temp = f
      f = g
      g = temp + g
    </code>

<!-- Note: not tagged as <ol> because not <ol> in source -->
<code class="python" lang="python">
    1. "If you're talking about Java in particular, Python is about the best fit you can get amongst all the other languages. Yet the funny thing is, from a language point of view, JavaScript has a lot in common with Python, but it is sort of a restricted subset."
    2. "The second stream of material that is going to come out of this project is a programming environment and a set of programming tools where we really want to focus again on the needs of the newbie. This environment is going to have to be extremely user-friendly."
    3. "I have this hope that there is a better way. Higher-level tools that actually let you see the structure of the software more clearly will be of tremendous value."
    4. "Now, it's my belief that Python is a lot easier than to teach to students programming and teach them C or C++ or Java at the same time because all the details of the languages are so much harder. Other scripting languages really don't work very well there either."
    5. "I would guess that the decision to create a small special purpose language or use an existing general purpose language is one of the toughest decisions that anyone facing the need for a new language must make."
    </code>
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** Chapter 5 / Section 1; Chapter 2 / Section 7
- **surrounding text:**

**Comment by Stackblocks** [comment]
Investigation into the issue is ongoing.

Notes:
- Content appears in standard text then is duplicated in with hljs styling.
- Possibly related to the `//for code snippets - stops text overflow` chunk of [_common-styles.scss](https://github.com/openstax/ce-styles/blob/da9a46cf0b09d0f5e345abd159972cf03dfe25ce/styles/designs/common/pdf/_common-styles.scss#L33) starting at Line 33

**Comment by kswanson33** [comment]
the issue in the first case appears to be with how the comment is wrapping (`inline-block` element breaks before element when overflowing)

i changed the `display` to `inline` and got this:

![Image](https://github.com/openstax/cnx-recipes/assets/26280712/37be96f1-a54a-4e5f-b274-ba851b15bc84)

same situation with second case:

![Image](https://github.com/openstax/cnx-recipes/assets/26280712/1c92190a-50ed-465b-8063-09ba4bf32e5b)

does this look ok? @lwtchu

**Comment by lwtchu** [comment]
@kswanson33 i think this is ok given the constraints of text wrapping in a PDF format

**Comment by kswanson33** [comment]
hello! code is on ce-styles `pre-span-display-common` and impacts all books with `pre` tags. should mainly impact how lines in `pre` blocks wrap.

**Comment by Stackblocks** [comment]
Code snippets are wrapping properly with the change.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/6a5b0158-57a1-43dc-8fff-a96f5c5791d2)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/afcf8f8d-ee65-41fe-93a1-a3d687c6d340)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/192f62ad-fce0-490f-8789-699b6fa0b8c4)
