### ISSUE TITLE
Information Systems - PDF/Webview - Answer Key Not Showing Up

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5426]
# Brief Description of Scenario

There is no end-of-book Answer Key section for this book in the PDF or the Webview. The questions that have public solutions have the solution showing up to the right of the question.
<img width="941" alt="Screenshot 2024-01-25 at 4 56 32 PM" src="https://github.com/openstax/cnx-recipes/assets/99201272/5ec1bd71-a8c1-45c5-8877-351b5261111b">

![Screenshot 2024-01-26 at 12 50 22 PM](https://github.com/openstax/cnx-recipes/assets/99201272/c6c9a05d-a9d4-41dd-9ac7-dcabc0283f62)

# Pattern of Occurrence 

This seems to happen for all the questions that have a public solution.

# Acceptance Criteria

There should be an Answer Key section, and answers should not appear beside the corresponding question.
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-foundations-of-information-systems/tree/design-chapters
- **collection slug:** foundations-of-information-systems
- **ref/branch:** design-chapters
- **chapter/section:** EoC Questions/Answer Key
- **surrounding text:**

**Comment by jbwilson8** [comment]
Answer Key was not included in release. It is present now. No additional development is required.

**PDF:**

![Image](https://github.com/openstax/cnx-recipes/assets/26155528/18d23209-1c81-4d62-8da1-d53e8a5ae23f)


**Webview:**


![Image](https://github.com/openstax/cnx-recipes/assets/26155528/0eac7fbb-3802-4081-83c1-7e0f4252e2d2)
