### ISSUE TITLE
AP Biology Preface 2-column

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5427]
# Brief Description of Scenario

I think this particular preface table necessitates single-column layout
<img width="1565" alt="Screenshot 2024-01-24 at 10 11 56 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/a1051f45-c43c-4ddd-aaa6-873d7256a6e5">

# Pattern of Occurrence 
Preface

# Acceptance Criteria
- remove two column lay out in preface for ap-biology recipe
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-biology-bundle
- **collection slug:** biology-ap-courses
- **ref/branch:** main
- **chapter/section:** preface 
- **surrounding text:**

**Comment by wilkus27** [comment]
@lwtchu ap biology styles are created based on the styles for biology. What I mean is that biology styles are imported in file for ap biology and then only things typical for ap biology are added there (like notes and eoc sections). Settings for Preface are in biology file. So we have two options here:

1. I can remove that setting, but it will affect both biology and ap biology.
2. I can add some additional code to ap biology file that will override setting from biology, but it won't be a conventional way to style things in our project (which is not a very big problem)

Which solution do you want me to apply? Do we want to keep ap biology and biology similar as much, as we can or should I change only ap biology?

**Comment by lwtchu** [comment]
@wilkus27 let's remove for both biology and ap-biology -- I'll update the labels

**Comment by Stackblocks** [comment]
Curriculum Framework table in the preface now shows as one column while Glossary and Chapter Summary still in two columns for both AP Bio & Bio 2e. ✅ 

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/8ebca78c-5679-4aea-8240-7dfb8f1c21a9)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/c0f2d727-4b93-432f-a6dd-d8021cbce55b)
