### ISSUE TITLE
AP Biology Teacher Support elements are not suppressed

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5428]
# Brief Description of Scenario

For the PDF, Teacher Support elements (tagged with the class `class="os-teacher"`) should be suppressed.
(new pdf on the left)
<img width="1605" alt="Screenshot 2024-01-27 at 12 46 25 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/b3e369e7-d8ee-45fc-89e2-12d9f3fc5fe0">

# Pattern of Occurrence 

Every instance
# Acceptance Criteria
Please suppress content with `class="os-teacher"`
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-biology-bundle
- **collection slug:**biology-ap-courses
- **ref/branch:**
- **chapter/section:** all
- **surrounding text:** Introduce the concept of unity and diversity of life. There are so many varieties of organisms

**Comment by wilkus27** [comment]
Blocked by https://github.com/openstax/cnx-recipes/issues/5438

**Comment by lwtchu** [comment]
![Image](https://github.com/openstax/cnx-recipes/assets/11299125/44ad3682-a197-4794-9ff2-ce6ccb10c683)

No teacher support in new PDF. Closing.
