### ISSUE TITLE
AP Biology - injected exercises in notes referencing itself

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5430]
# Brief Description of Scenario

The recipe seems to be adding nonfunctional link text `refer to []` when the Exercises question imported into the book has a feature-id in the tags. There is no "refer to" in the exercise on the platform or in the markup of the book. The link refers to the question itself in the book and therefore does not seem to go anywhere when clicked.

<img width="1511" alt="Screenshot 2024-01-27 at 12 59 35 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/c8fb1945-0373-425e-b78c-41c5f1ac5333">

- this is a result of the cnx id reference ID in the injected exercises originally designed for questions at the end of the chapter
- now questions tied to notes are repeating the note in a weird way (`Refer to [link]` text)
- is there a way to skip pulling this in for exercises in certain features? if so i can pull features and find 

# Pattern of Occurrence 

all occurrences
# Acceptance Criteria

- Remove required context if it’s within a note within AP Biology
- Only in AP Biology for now to limit scope of changes we are doing to required context as it should fundamentally change once we migrate to the new assessments system
  
# Sample Mark-Up
```
<note id="fs-idp13108800" class="interactive ost-assessed-feature ost-tag-lo-apbio-ch02-s02-lo01 ost-tag-lo-apbio-ch02-s02-aplo-2-8"><label>Link to Learning</label>

<para id="fs-idm102716096">Click <link window="new" url="http://openstax.org/l/ice_lattice2">here</link> to see a 3-D animation of the structure of an ice lattice.</para><exercise id="fs-id1167067049025" class="os-exercise unnumbered"><label/>
<problem id="fs-id1167063459135">
<para id="fs-id1167063520397">
<link class="os-embed" url="#ost/api/ex/apbio-ch02-ex014"/>
</para>
</problem>
</exercise>


</note>
```

# Location(s)
- **osbooks repo:** osbooks-biology-bundle
- **collection slug:** biology-ap-courses
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:**

**Comment by oscryan** [comment]
Looks like it shows up in webview also

**Comment by lwtchu** [comment]
We can remove the "Refer to [link]" text but the duplicate text is content issue where the question stem and the CNXML both have similar content. We will have to open a card later for CMs to remove duplicate content (preferably from the CNXML).

**Comment by kswanson33** [comment]
branch: cookbook `exercise-context-apbio`

**Comment by Stackblocks** [comment]
The fake link has been removed. ✂️


![CleanShot 2024-02-28 at 16 48 29](https://github.com/openstax/cnx-recipes/assets/12678235/e9873aed-6cb9-4990-96d4-1895a6ef95de)
