### ISSUE TITLE
AP Biology has minimal styling for Everyday Connection questions

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5432]
# Brief Description of Scenario

It's there, but it's just a line. Is that what we intend?

<img width="1000" alt="Screenshot 2024-01-27 at 1 09 48 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/cc789f2b-25bd-44a1-8e29-7f8b45bb21b8">
# Pattern of Occurrence 

# Acceptance Criteria
Found the old specs here: https://github.com/openstax/cnx-recipes/issues/1191 

It looks a little half baked so might've been missed when we refactored -- it's been a long time. 
See #1087 for specs for a BOXED NOTE 

Title: Everyday Connection for AP® Courses
Class: `ap-everyday`
Color: BR1: `#B05E36`
** Please make sure the registered trademark symbol is in superscript.
  

# Location(s)
- **osbooks repo:** osbooks-biology-bundle
- **collection slug:** biology-ap-courses
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:** Phylogenetic trees can represent traits that are derived or lost due to evolution.

**Comment by wilkus27** [comment]
Blocked by https://github.com/openstax/cnx-recipes/issues/5438

**Comment by lwtchu** [comment]
![Image](https://github.com/openstax/cnx-recipes/assets/11299125/09d5767c-65c6-4185-b08f-75d8913d3f77)

Styling exists but can we fix the title color to match? BR1: #B05E36

**Comment by MartaSztuka** [comment]
#### PASSED


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/9999b534-f73c-4ccd-865d-5be0f152d943)



![Image](https://github.com/openstax/cnx-recipes/assets/47241114/4616e2a7-c3cc-462a-9f62-caa763633a86)



![Image](https://github.com/openstax/cnx-recipes/assets/47241114/15ea4bfa-2d9c-439c-b517-ed4e392f5bae)
