### ISSUE TITLE
AP Biology equations no longer centered

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5434]
# Brief Description of Scenario
recipe does not center equations (new on the left)
<img width="1006" alt="Screenshot 2024-01-27 at 3 35 02 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/f11b3b42-b495-4913-8253-8fccb9a34124">

# Pattern of Occurrence 

everywhere
# Acceptance Criteria
- please center equations in the ap-biology/biology recipes
  
# Sample Mark-Up
```
<equation id="eip-3" class="unnumbered"><m:math display="block">
<m:mrow>
<m:mn>2</m:mn><m:mtext>H + O </m:mtext><m:mrow><m:mo stretchy="false">→</m:mo></m:mrow><m:msub>
<m:mrow>
<m:mtext> H</m:mtext>
</m:mrow>
<m:mn>2</m:mn>
</m:msub>
<m:mtext>O</m:mtext>
</m:mrow>
</m:math></equation>
```

# Location(s)
- **osbooks repo:** osbooks-biology-bundle
- **collection slug:** biology-ap-courses
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:** Even though all of the reactants and products of this reaction are molecules

**Comment by wilkus27** [comment]
@lwtchu Styles for equations are already applied. They work in biology. In ap-bio they're not centered because they're missing `unnumbered` class.

**Comment by lwtchu** [comment]
Ok closing this issue
