### ISSUE TITLE
Assessment Ingestion -- request to left-align images in Exercises to match Webview

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5439]
# Brief Description of Scenario
We would like to left-align the images in Calculus Vol. 2 to match how they appear in webview. Is there a class available that we can apply to the `<img>` tag for left-alignment? 

For example, here is how item 01-02-CalV2-SE03 appears currently:
<img width="681" alt="Screenshot 2024-02-01 at 17 56 00" src="https://github.com/openstax/cnx-recipes/assets/89537088/2d0110fe-07f0-451d-b14f-2efb81c3e730">

And here is how it appears when I add `align="left"` to the `<img>` tag: 
<img width="646" alt="Screenshot 2024-02-01 at 17 56 37" src="https://github.com/openstax/cnx-recipes/assets/89537088/7b5be88c-9eea-43d1-a1b7-cc833631cfe6">

# Pattern of Occurrence 
Images always appear centered when they are uploaded via the Assets tab in Exercises.

# Acceptance Criteria

  
# Sample Mark-Up
```
<img src="https://exercises.openstax.org/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2djIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6174ad5cc374b84d2bc803d5c888e6fb811f68c0/01-02-CalV2-SE03-a.jpg" alt="A graph containing the upper half of three circles on the x axis. The first has center at (1,0) and radius one. It corresponds to the function sqrt(2x – x^2) over [0,2]. The second has center at (4,0) and radius two. It corresponds to the function sqrt(-12 + 8x – x^2) over [2,6]. The last has center at (9,0) and radius three. It corresponds to the function sqrt(-72 + 18x – x^2) over [6,12]. All three semi circles are shaded – the area under the curve and above the x axis." align="left">
```

# Location(s)
- **osbooks repo: book:stax-calc
- **collection slug:**
- **ref/branch:**
- **chapter/section: Nickname:01-02-CalV2-SE03
- **surrounding text:**

**Comment by ww-openstax** [comment]
Changed priority to "low" -- this does not affect content, only appearance once nicknamed items are linked in the XML

**Comment by lwtchu** [comment]
We likely won't fix since it won't impact PDF/web and this is only a display issue in the exercises platform.
