### ISSUE TITLE
Pharmacology - nursing-external - removing Single from Single Case Study

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5440]
To make a change to the current Feature from “Single Case Study” to “Case Study” (removing “Single”) in both the in chapter feature and the heading in the answer key. Here with attached screenshot FYR. Please check and resolve this issue.

This ticket is for Pharmacology only.

**Chapter Feature**
![image001 (1)](https://github.com/openstax/cnx-recipes/assets/86622862/be2e315c-177c-4f55-a6b8-deeef8d0c181)
**Answer Key**
![image002 (1)](https://github.com/openstax/cnx-recipes/assets/86622862/6b35ee73-0f2f-4d91-82c1-739863fead59)

# Acceptance Criteria
- do not change the class, just change the titles for `note class="single-casestudy"`

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** Pharmacology
- **ref/branch:** https://openstax-osbooksnursing-om7p9xrw6yq.ws-us107.gitpod.io/
- **chapter/section:** Chapter 07/Section 7.5
- **surrounding text:** Mark Janson is a 36-year-old White client who presents to the emergency department

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2024-02-07 15-31-40](https://github.com/openstax/cnx-recipes/assets/47241114/1e112344-57fb-404b-a2f0-a8e5648d48a4)
![Zrzut ekranu z 2024-02-07 15-32-56](https://github.com/openstax/cnx-recipes/assets/47241114/556267f7-4319-4c68-84cd-d98207bf849c)
