### ISSUE TITLE
Calculus: Checkpoint font color

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#5441]
# Brief Description of Scenario
Checkpoints have very faint grey font color

![image](https://github.com/openstax/cnx-recipes/assets/11299125/b31ccade-5b4e-4ad9-9993-e8277550855e)

# Pattern of Occurrence 
all checkpoints

# Acceptance Criteria
should probably be darker so they are noticed and easier to read
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-calculus-bundle
- **collection slug:** calculus-volume-2
- **ref/branch:** main
- **chapter/section:** various
- **surrounding text:**

**Comment by lwtchu** [comment]
This is on purpose for the new design.
