### ISSUE TITLE
Calculus: Overflowing tables not indicated with (continued)

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#5442]
# Brief Description of Scenario
Overflowing tables not indicated with (continued) in exercises

![image](https://github.com/openstax/cnx-recipes/assets/11299125/fd6ae688-fbc2-4c71-9c09-d21031ce66fe)

# Pattern of Occurrence 
When a table overflows multiple pages from exercises

# Acceptance Criteria
some indication that a table split over multiple pages is a continuation of the same table.
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-calculus-bundle
- **collection slug:** calculus-volume-2
- **ref/branch:** main
- **chapter/section:** Chapter 1 
- **surrounding text:** "consider the historic average"

**Comment by lwtchu** [comment]
Currently there's not a functionality in place to add a "continued" for tables that are broken up by page breaks
