### ISSUE TITLE
Calculus: remove 3 column in answer key

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#5444]
# Brief Description of Scenario
Some images in exercise solutions are scaling very small

![image](https://github.com/openstax/cnx-recipes/assets/11299125/c8b31c4b-c6eb-45a2-bfec-dc2d0bbe703c)

# Pattern of Occurrence 
In end of book exercise solutions 

# Acceptance Criteria
- remove 3 column styling in answer key
  
# Sample Mark-Up
```
<para id="fs-id1170572622439">The left-endpoint approximation is 0.7595. The right-endpoint approximation is 0.6345. See the below <link target-id="fs-id1170572216462"/>.<newline/>
<media id="fs-id1170572216462" alt="Two graphs side by side showing the left-endpoint approximation ad right-endpoint approximation of the area under the curve f(x) = 1/x from 1 to 2 with endpoints spaced evenly at .25 units. The heights of the left-endpoint approximation one are determined by the values of the function at the left endpoints, and the height of the right-endpoint approximation one are determined by the values of the function at the right endpoints.">
<image mime-type="image/jpeg" src="../../media/CNX_Calc_Figure_05_01_012.jpg"/>
</media>
</para>
```

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-calculus-bundle
- **collection slug:** 
- **ref/branch:** main
- **chapter/section:** Chapter 1.1
- **surrounding text:** The left-endpoint approximation is 0.7595

**Comment by MartaSztuka** [comment]
Hi :) @jbwilson8 Answer key is in one column, but tekst is in new line
![Zrzut ekranu z 2024-02-28 12-46-36](https://github.com/openstax/cnx-recipes/assets/47241114/9173aad5-24c5-4d4c-8b2d-9cecd3ccffac)

**Comment by Stackblocks** [comment]
Answer key is now in one column and the numbers are properly inline and styled.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/03b7927a-d239-4e8f-a81c-08cc4e5d4c5a)
