### ISSUE TITLE
Introduction to Python Programming - instance of hash character interpreted as code comment when it isn't code comment

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5446]
# Brief Description of Scenario
In at least one instance, the '#' character is being interpreted and styled as the beginning of a comment when it is actually part of the output text in the code block. Is there a way to escape the # character so that it isn't interpreted as a comment?
Reported by Copyeditor.
![image](https://github.com/openstax/cnx-recipes/assets/89537088/ad9e9687-6b80-4be7-b39f-71f20770d5a8)

# Pattern of Occurrence 
This is the only instance encountered

# Acceptance Criteria

  
# Sample Mark-Up
```
<para id="para-00026">The output is:</para>
    <code class="python" lang="python">
    Passenger Jules Laurent departs on flight # 2121 at 11:45 from KEF D22B in seat 12B
    </code>
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** Chapter 11 / Section 2 / Module m00082 / Line 183 / 
- **surrounding text:** TRY IT -- Creating a class for an airline's flight tickets

**Comment by lwtchu** [comment]
@ww-openstax can you remove the class and the lang attributes? That way it'll just be regular code and highlight.js doesn't have to parse it

**Comment by ww-openstax** [comment]
removing attributes worked
