### ISSUE TITLE
Nursing external - Community Population - webview - Chapter Summary Sections links disappeared

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5447]
In WEB view the Chapter Summary section links have disappeared for all chapters for this course (Pop. Health).

Previous version WEB VIEW:
![image001](https://github.com/openstax/cnx-recipes/assets/86622862/2f778f98-4b21-42b4-b143-2fe875cbf064)

Current version WEB VIEW:

![Untitled](https://github.com/openstax/cnx-recipes/assets/86622862/10865d94-43e3-4d5b-88c4-6d3d35a328cd)

# Acceptance Criteria
There's two ways Chapter Summaries are marked up. For ones that are tagged `section-summary` please include the headers. 

# Content
## Sample Mark-Up
```
<section class="section-summary" id="sect-00006">
<title>Chapter Summary</title>
<para id="para-00014">Nurses in health care settings are crucial to promoting health and preventing diseases. Collaborative efforts are necessary to promote the health status of populations. Nursing practice should prioritize a holistic approach, considering the client’s family and community context. This entails recognizing the social, political, and economic factors that affect health; prioritizing well-being; fostering compassionate relationships; and respecting personal dignity and choice.</para>
</section>
```

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** community-population
- **ref/branch:** main
- **chapter/section:** 
- **surrounding text:**

**Comment by kswanson33** [comment]
the fix for `population-health` only involves the `section-summary` class. if the `chapter-summary` class needs headers, this is not included in the current fix

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2024-02-22 16-23-30](https://github.com/openstax/cnx-recipes/assets/47241114/fb370f04-9dd3-41a2-8f15-1da9d6788acd)

**Comment by lwtchu** [comment]
@Stackblocks Additional locations reported by CS that we can test in CORGI when this goes out

A customer noted that the chapter headings for the Summaries in the US History book (ex. [Chapter 1](https://openstax.org/books/us-history/pages/1-summary)) are no longer on the page. On a deeper dive, we found that this is true for all of the textbooks we opened ([World History](https://openstax.org/books/world-history-volume-1/pages/1-section-summary), [Workplace Software](https://openstax.org/books/workplace-software-skills/pages/1-summary), [Chemistry](https://openstax.org/books/chemistry-2e/pages/1-summary), etc.). Is this a recent change?
