### ISSUE TITLE
Lifespan Development - Remove EOC Sections

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5448]
![Screenshot 2024-02-07 at 11 03 46 AM](https://github.com/openstax/cnx-recipes/assets/11299125/68694dda-a62f-4628-af99-84c385038205)
These sections will not be needed:
- References `<section class="references">`
- Reflection Questions `<section class="reflection-questions">`
- Media Questions `<section class="media-questions">`
- Thought Provokers `<section class="thought-provokers">`
- Case Study `<section class="case-study">`

# Context
Requirements have changed. Please remove sections!

# Acceptance Criteria
These are removed from the recipes

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-lifespan-development/tree/design-chapter
- **collection slug:** lifespan-development
- **ref/branch:** design-chapter
- **chapter/section:** 
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/26a80b3f-e211-4328-ad4c-641cc4259ea8)



![Image](https://github.com/openstax/cnx-recipes/assets/47241114/20706fbc-e68a-4ede-a417-d1b7bd241fca)



![Image](https://github.com/openstax/cnx-recipes/assets/47241114/f05dd024-b2eb-4b7a-af63-3cf715099f3f)
