### ISSUE TITLE
Lifespan Development - 2 new EOC sections

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5449]
![Screenshot 2024-02-07 at 11 03 46 AM](https://github.com/openstax/cnx-recipes/assets/11299125/68694dda-a62f-4628-af99-84c385038205)
New sections
- Personal Application Questions `<section class="personal-application">`
- Essay Questions `<section class="essay-questions">`

# Acceptance Criteria
Follows the normal styles #5330
Removal of section issue #5448 here

Order of assessments should be 
- Review Questions
- Check Your Understanding Questions
- Personal Application Questions
- Essay Questions

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-lifespan-development/tree/design-chapter
- **collection slug:** lifespan-development
- **ref/branch:** design-chapter
- **chapter/section:** 
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/4b502aaa-a846-44d9-a05d-c2a8d65b22ca)


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/3d298217-e1ed-4afa-ad88-3388da8ab50f)



![Image](https://github.com/openstax/cnx-recipes/assets/47241114/ff9b21b6-1557-4a12-a19c-251c996b54a6)
