### ISSUE TITLE
Lifespan Development - reduce padding between Learning Objectives title and learning objectives list

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5450]
![Screenshot 2024-02-07 at 1 05 38 PM](https://github.com/openstax/cnx-recipes/assets/11299125/85172bab-bcf2-4595-9c43-fa40dc5bb552)

# Acceptance Criteria
Please reduce space between Learning Objectives title and the list. There's an awkward gap - should be like the next line

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-lifespan-development
- **collection slug:** lifespan-development
- **ref/branch:** design-chapter
- **chapter/section:** 
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/a71e87f5-ebb6-4e67-9cc2-e8c1ab60b4b1)
