### ISSUE TITLE
Lifespan Development - It Depends feature color change from yellow to blue

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5452]
Original issue #5325

# Brief Description of Scenario
Please change color schema to color schema 1 (blue) from #3194 

# Pattern of Occurrence 
notes tagged with - class: `class="it-depends"`

# Acceptance Criteria
- it depends feature is now blue
  
# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-lifespan-development
- **collection slug:** lifespan-development
- **ref/branch:** design-chapter 
- **chapter/section:** 
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2024-02-20 17-17-49](https://github.com/openstax/cnx-recipes/assets/47241114/733b66eb-6d01-4b96-8dcc-807e2669b3ce)
