### ISSUE TITLE
Lifespan Development - enable centered text

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5453]
![Screenshot 2024-02-07 at 2 29 05 PM](https://github.com/openstax/cnx-recipes/assets/11299125/7936fde2-8a73-4f0a-8dc9-35994d9ff536)

# Brief Description of Scenario
Items with `<para class="centered-text">` should be centered in normal text and Appendix

# Pattern of Occurrence 
There's about 3 spots in the sample book that has the class

# Acceptance Criteria
Items with `<para class="centered-text">` should be centered in normal text and Appendix
  
# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-lifespan-development
- **collection slug:** lifespan-development
- **ref/branch:** design-chapter
- **chapter/section:** Appendix B and sections 1.2 and 2.2
- **surrounding text:**

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2024-02-20 17-21-39](https://github.com/openstax/cnx-recipes/assets/47241114/f1345ad2-f719-4416-a330-6a69a3188a22)
