### ISSUE TITLE
Nursing-exernal - Nutrition - 2nd level indent in tables

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5455]
For Nutrition & Population Health 2nd level bullet indents does not shown perfectly in PDF View, But shown correctly in WEB View. Please check and resolve this issue.

Here with attached screenshot FYR.

**Nutrition: PDF view – 2nd level bullet not indenting properly.**
![image1](https://github.com/openstax/cnx-recipes/assets/86622862/21b88bfe-1b27-4531-b066-b2fbe4f76815)
**Web view – 2nd level bullet indenting correctly.**
![image2](https://github.com/openstax/cnx-recipes/assets/86622862/ebbad43d-6d0b-45c2-9443-7516e5ba43ad)

**Population: Table 32.2 has this same issue in the right column:**
<img width="757" alt="image3" src="https://github.com/openstax/cnx-recipes/assets/86622862/fb49a9ed-e5bb-46cc-830c-33dd861cf903">
**Web view – 2nd level bullet indenting correctly.**
![image6](https://github.com/openstax/cnx-recipes/assets/86622862/aacc18f8-f759-49c0-a840-0dadd0bc1437)
**A similar problem occurs in Table C2:**
<img width="750" alt="image4" src="https://github.com/openstax/cnx-recipes/assets/86622862/288c37c3-33a7-425f-986c-e1b753c0b721">
**Web view – 2nd level bullet indenting correctly.**
![image5](https://github.com/openstax/cnx-recipes/assets/86622862/e47c4f6c-0f87-417d-9308-1505bcde9114)
# Acceptance Criteria
- please make sure 2nd level list styling is also applied to tables

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** Nutrition, community-population
- **ref/branch:** https://openstax-osbooksnursing-om7p9xrw6yq.ws-us108.gitpod.io/
- **chapter/section:** **Nutrition**: Chapter19/Section19.1; **Population Health:** Chapter 32/ Section 32.2, Appendix C
- **surrounding text:** **Nutrition**: Abnormal Objective Findings in the Musculoskeletal System; **Population Health:** Person-to-person: Communicable diseases such as smallpox; Collaboration with the community

**Comment by wilkus27** [comment]
### Information for tester

These problems occurred because in Carnival we applied smaller margin for lists from tables. We didn't do this for other themes. Now, I added the same margin as lists have in other parts of book. It has an impact on all books from carnival.

cc @lwtchu

**Comment by Stackblocks** [comment]
## Nutrition
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/94b01390-9d20-45b5-b197-046f7e3fc37c)

## Community Population
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/da20fc01-c364-4096-9868-6c7cdeca4b86)
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/8fa0252f-5c98-4691-b267-4a6450bec87b)
