### ISSUE TITLE
Introduction to Python - webview - line break between assessment question and number

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5458]
![image](https://github.com/openstax/cnx-recipes/assets/11299125/36f5e60c-f782-45a4-b914-a78615a49570)

# Brief Description of Scenario
This was introduced with the code roll out on Feb 12. There is now a line break between the question stem and number

# Pattern of Occurrence 
ALL ASSESSMENTS

# Acceptance Criteria
- please have question stem next to the number
  

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-introduction-python-programming
collection slug (if applicable): introduction-python-programming
chapter/section: various
surrounding text:

**Comment by lwtchu** [comment]
I believe this was introduced from https://github.com/openstax/cnx-recipes/issues/5384 

We need to figure a different way to solve the Statistics problem

**Comment by lwtchu** [comment]
For tester: Can we check Nutrition also? It's impacting that book. And we should check a few more books once we go to CORGI testing (another issue wrt terms in headers can be a good candidate for more robust testing)

**Comment by MartaSztuka** [comment]
#### PASSED
##### Python
![Zrzut ekranu z 2024-02-14 10-06-55](https://github.com/openstax/cnx-recipes/assets/47241114/b7877055-e5b9-4f82-bfea-77a754d9cde2)
##### Nutrition
![Zrzut ekranu z 2024-02-14 10-23-42](https://github.com/openstax/cnx-recipes/assets/47241114/c7e64e14-0e9c-4abb-ab09-1e0eed2b656a)
##### Population Health for Nurses
![Zrzut ekranu z 2024-02-14 10-26-00](https://github.com/openstax/cnx-recipes/assets/47241114/e862452e-0d4f-408c-8b0d-79e259dda2c5)
