### ISSUE TITLE
Introduction to Python Programming - regression - new line in section title with code tag

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5459]
# Summary & Screenshots

![Screenshot 2024-02-13 at 1 50 13 PM](https://github.com/openstax/cnx-recipes/assets/11299125/6d122234-0c20-443e-90ed-81c99a464f52)
It is working correctly in PDF - only broken in web. 

![Screenshot 2024-02-13 at 1 51 28 PM](https://github.com/openstax/cnx-recipes/assets/11299125/921b6178-c084-4503-999c-828be3c4b80b)

# Sample Mark-Up
```
<section id="sect-00003">
    <title>Using <code class="python inline-code">sort()</code> and <code class="python inline-code">reverse()</code></title>
    <para id="para-00007">Python provides functions for arranging elements in a list.
    <list id="list-00002">
```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:** main
- **chapter/section:** Chapter 09 / Section 2 / Module m00068 line 47
- **surrounding text:** 

# Acceptance Criteria

## PDF
- make sure the title remains as is 

## Web
- the fix was done in https://github.com/openstax/cnx-recipes/issues/5259 but there was a regression at some point?
- please remove line breaks between code in title of section

**Comment by kswanson33** [comment]
![image](https://github.com/openstax/cnx-recipes/assets/26280712/35aab223-f09c-4639-a429-11ec299a15b0)

**Comment by kswanson33** [comment]
branch: ce-styles `inline-pre-webview`

**Comment by MartaSztuka** [comment]
#### PASSED


![Image](https://github.com/openstax/cnx-recipes/assets/47241114/29d238c3-483c-4bff-9831-b4888bac75db)
