### ISSUE TITLE
Introduction to Python Programming - code inside caption causing line break

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5460]
# Summary & Screenshots
`<code class="python inline-code" lang="python">` inside `<caption>` causing line breaks

Affects both figure captions and table captions.

Issue in Webview. 
PDF OK

Reporting late in the process because this only became an issue after additional `<code class="python inline-code" lang="python">` tags were added in latest round of revisions. Previously there were no instances of caption/code 

There are three instances 
![image](https://github.com/openstax/cnx-recipes/assets/89537088/5771a358-f97d-4851-a839-80616f230d63)

### Webview
![image](https://github.com/openstax/cnx-recipes/assets/89537088/7bdb562e-ede2-4924-933f-29c7ae6dbea3)
### PDF
![image](https://github.com/openstax/cnx-recipes/assets/89537088/54575859-adc4-4592-84f1-4dc18aee6209)

# Sample Mark-Up
```
<caption>If both <code class="python inline-code" lang="python">Dessert</code> and <code class="python inline-code" lang="python">BakedGood</code> override a <code class="python inline-code" lang="python">Food</code> method, the overridden <code class="python inline-code" lang="python">Food</code> method that <code class="python inline-code" lang="python">ApplePie</code> inherits is ambiguous. Thus, diamond shaped inheritance should be avoided.</caption>
```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** Section 13.5, Section 14.3
- **surrounding text:** 

# Acceptance Criteria

## PDF
- remains the same

## Web
- #5459 might be related to this
- please make sure code in captions don't produce a line break

**Comment by kswanson33** [comment]
![image](https://github.com/openstax/cnx-recipes/assets/26280712/df319f0b-da5c-41bc-b1b7-8fe283209f1b)

**Comment by kswanson33** [comment]
branch: ce-styles `inline-pre-webview`

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2024-02-15 11-54-25](https://github.com/openstax/cnx-recipes/assets/47241114/f6d4f6ee-a17f-40c3-8be1-270be3164798)
