### ISSUE TITLE
Nursing Internal -- PDF - Bad page breaks in TOC

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5461]
# Summary & Screenshots
Please adjust automated TOC output in PDF to eliminate bad breaks and widows.
See screenshots for examples
We didn't encounter any Chapter titles breaking across pages but please check for those too.
Affects all Nursing internal titles

### Screenshot 1
![image](https://github.com/openstax/cnx-recipes/assets/89537088/64919463-1b54-41f8-b890-0f33a009ee4a)

### Screenshot 2
![image](https://github.com/openstax/cnx-recipes/assets/89537088/5282e17a-56af-47ac-8a35-e281e07a4a9a)

### Screenshot 3
![image](https://github.com/openstax/cnx-recipes/assets/89537088/58ed76bf-4bb9-4603-b863-0531c9d19478)

### Screenshot 4
![image](https://github.com/openstax/cnx-recipes/assets/89537088/43e271d3-27cb-4539-b550-2a8df38f7822)

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [ ] At every instance of the content
- [x] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** medical-surgical
- **ref/branch:**
- **chapter/section:** TOC
- **surrounding text:** 

# Acceptance Criteria

## PDF
I think we can only fix maybe the line break between the Unit Title. Please make sure ONLY the title isn't orphaned or breaking. (Avoid break in Unit Title maybe? (Not after or before but in the middle of)

I am not sure if we can do anything about Orphaned EOC sections - let me know if we can.

For the page number falling to the next line, we cannot fix without introducing a bunch of issues (we've tried before) 

## Web
N/A

**Comment by wilkus27** [comment]
### Information for tester

Page breaks for Unit titles and orphaned EOC and EOB sections should be fixed. Changes have impact on all books.

Problem with page number falling to the next line, as it is said in Acceptance Criteria, can't be fixed without problems.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Clinical nursing skills
### Screenshot 1
![Zrzut ekranu z 2024-02-21 13-59-37](https://github.com/openstax/cnx-recipes/assets/47241114/c56ad9d8-887c-4ffc-aba2-7ed225018e09)
### Screenshot 2
![Zrzut ekranu z 2024-02-21 13-59-49](https://github.com/openstax/cnx-recipes/assets/47241114/619abf51-aa70-455c-8420-9290b06e5d92)

##### Psychiatric mental health
### Screenshot 3
![Zrzut ekranu z 2024-02-21 14-02-11](https://github.com/openstax/cnx-recipes/assets/47241114/bb0781df-5bc2-45ba-a53e-5b2d7989cb43)
### Screenshot 4
![Zrzut ekranu z 2024-02-21 14-14-02](https://github.com/openstax/cnx-recipes/assets/47241114/8adbf187-bfa1-4d44-a686-1968f297dd96)
### Screenshot 5
![Zrzut ekranu z 2024-02-21 14-01-59](https://github.com/openstax/cnx-recipes/assets/47241114/cf9f0437-efb7-4c0d-8ac2-461cb53e19a8)

##### Nursing fundamentals
### Screenshot 6
![Zrzut ekranu z 2024-02-21 14-03-53](https://github.com/openstax/cnx-recipes/assets/47241114/7f3cec9c-087b-488f-b1e9-a730f7cc8b99)
### Screenshot 7
![Zrzut ekranu z 2024-02-21 14-03-31](https://github.com/openstax/cnx-recipes/assets/47241114/cf7cddc4-0cd3-490a-bf0f-cde5e289365b)

##### Maternal newborn
### Screenshot 8
![Zrzut ekranu z 2024-02-21 14-05-57](https://github.com/openstax/cnx-recipes/assets/47241114/8b8add71-49e1-43a9-ad9d-4ad0a376a5a6)
### Screenshot 9
![Zrzut ekranu z 2024-02-21 14-05-19](https://github.com/openstax/cnx-recipes/assets/47241114/1e9171ce-fb0e-476b-a9b9-8be5b7f54495)

##### Medical surgical
### Screenshot 10
![Zrzut ekranu z 2024-02-21 14-08-27](https://github.com/openstax/cnx-recipes/assets/47241114/00ddcf21-9b24-4a8b-b313-16ab5a22be23)
### Screenshot 11
![Zrzut ekranu z 2024-02-21 14-08-14](https://github.com/openstax/cnx-recipes/assets/47241114/dae36e72-60db-48cc-80b0-3c1065eaa910)
### Screenshot 12
![Zrzut ekranu z 2024-02-21 14-08-05](https://github.com/openstax/cnx-recipes/assets/47241114/acc61db3-8a35-46f4-bbe4-b0a4ab7098fa)
### Screenshot 13
![Zrzut ekranu z 2024-02-21 14-07-44](https://github.com/openstax/cnx-recipes/assets/47241114/6301737f-19eb-4e43-8994-cc1624a901e0)
