### ISSUE TITLE
Column is breaking after the dash

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5463]
In web view, this column is breaking after the dash, can numbers be kept together so it breaks after 30–120 for example.
Same is happening in some instances in other columns
In PDF View shown correctly. Please check and resolve this issue. Here with attached screenshot FYR..

**PDF VIEW:**
![PDF_View](https://github.com/openstax/cnx-recipes/assets/86622862/0ce3ae41-9359-486e-a5f3-4835b87d68f7)
**WEB VIEW:**
![WEB_View](https://github.com/openstax/cnx-recipes/assets/86622862/7076b00e-3b58-4425-a4d4-e4725d5e533b)

# Content Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** Pharmacology
- **ref/branch:** https://openstax-osbooksnursing-om7p9xrw6yq.ws-us108.gitpod.io/
- **chapter/section:** Appendix B
- **surrounding text:** Note that the abbreviation for

# Acceptance Criteria

**Comment by lwtchu** [comment]
This would require significant markup changes to either tag elements that we do not want breaking or to implement special characters. This is not a clean or efficient strategy as it is difficult to enforce and test. Adding a technical fix to this would be too granular and compromise the integrity of our existing framework. If there are new approaches in the future we can revisit, but as it stands, the line breaking is different based on the browser and software that the PDF generator uses.
