### ISSUE TITLE
Nursing Internal -- Feature box breaks across pages in PDF

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5464]
# Summary & Screenshots
Can feature boxes be prevented from breaking across pages in the PDF? 

This one looks especially bad:
![image](https://github.com/openstax/cnx-recipes/assets/89537088/914f22d1-bbe8-44ca-a04a-d525e6b3efa8)

# Sample Mark-Up
```
   <note class="clinical-judgment" id="note-00002">
    <title>What Is the <term class="no-emphasis" id="term-00025">Clinical Judgment Measurement Model (CJMM)</term>?</title>
    <para id="para-00014">Designed by the <term class="no-emphasis" id="term-00026">National Council of State Boards of Nursing (NCSBN)</term>, the CJMM measures a nursing licensure candidate’s ability to exercise sound clinical judgment and decision-making. Grounded in the nursing process, the CJMM includes six components: (1) recognize cues, (2) analyze cues, (3) prioritize hypotheses, (4) generate solutions, (5) take actions, and (6) evaluate outcomes. Built in layers, the CJMM provides a framework for thought processes and actions to take in exercising clinical judgment in a nursing scenario.</para>
    </note>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [x] Other (Please describe below)
Occurs when feature box breaks across pages

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** psychiatric-mental-health
- **ref/branch:**
- **chapter/section:** Chapter 1 / Section 1
- **surrounding text:** 

# Acceptance Criteria

**Comment by lwtchu** [comment]
@ww-openstax We typically allow for page breaks across feature boxes to reduce the amount of white space that will occur. We cannot move up the orphaned line onto the previous page.
