### ISSUE TITLE
Introduction to Python Programming - no caption styling for some figures in PDF

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5465]
# Summary & Screenshots
**In PDF Only**
For `<figure class="unnumbered" > ` (unnumbered figure) there is no caption styling and no padding below
Three instances of  `<figure class="unnumbered" > `  all are in Preface

For `<figure>` (numbered figure not splash) there is no figure number styling, no caption styling, and no padding below
Five instances of  `<figure> `  

For `<figure class="splash">` (numbered splash) caption styling and figure number styling **working correctly** in both PDF and Webview

### unnumbered figure PDF
![image](https://github.com/openstax/cnx-recipes/assets/89537088/b70b41ae-1640-496e-89a4-e4e8e8dd1081)

### numbered figure not splash PDF
![image](https://github.com/openstax/cnx-recipes/assets/89537088/4f505d1f-23d8-4057-acba-0e619cca7002)

### splash figure PDF working correctly
![image](https://github.com/openstax/cnx-recipes/assets/89537088/3136ffa8-166c-49ed-a09c-e1391a861960)

# Sample Mark-Up
```
    <figure class="unnumbered" id="fig-00004">
    <media alt="">
    <image mime-type="image/png" src="../../media/OSX_Preface_AcademicIntegritySliderv3-1-column.jpg"/>
    </media>
    <caption>attribution: Copyright Rice University, OpenStax, under CC BY 4.0 license</caption>
    </figure>


    <figure id="fig-00001">
    <title/>
    <media alt="">
    <image mime-type="image/jpg" src="../../media/Python_13_05_001.png"/>
    </media>
    <caption><emphasis effect="bold">The diamond problem. </emphasis>If both <code class="python inline-code" lang="python">Dessert</code> and <code class="python inline-code" lang="python">BakedGood</code> override a <code class="python inline-code" lang="python">Food</code> method, the overridden <code class="python inline-code" lang="python">Food</code> method that <code class="python inline-code" lang="python">ApplePie</code> inherits is ambiguous. Thus, diamond shaped inheritance should be avoided.</caption>
    </figure>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** Preface; Sections 1.8 (x2), 3.3, 13.5, 14.3
- **surrounding text:** 

# Acceptance Criteria

## PDF
- can we make sure figure styling is enabled in sections and the preface
- documentation https://github.com/openstax/cnx-recipes/issues/2643

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2024-02-21 11-34-09](https://github.com/openstax/cnx-recipes/assets/47241114/7d896841-4a98-4a15-8ecf-eea149e49c44)
![Zrzut ekranu z 2024-02-21 11-34-50](https://github.com/openstax/cnx-recipes/assets/47241114/80748eac-3210-445c-8dc5-7ad36e5afba3)
![Zrzut ekranu z 2024-02-21 11-35-32](https://github.com/openstax/cnx-recipes/assets/47241114/efced51f-4b58-4083-8b5a-86f8eae896cf)
