### ISSUE TITLE
nursing-external - webview - Suggested Reading/References list hanging indent

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5466]
# Summary & Screenshots
Was missed from implementation here https://github.com/openstax/cnx-recipes/issues/5412 

![image](https://github.com/openstax/cnx-recipes/assets/11299125/3fd8aeb2-d9f3-4ae5-9a45-82d819f7e690)
(Suggested Reading) 

![Screenshot 2024-02-16 at 11 17 54 AM](https://github.com/openstax/cnx-recipes/assets/11299125/c3fb01ba-d074-45e4-8292-ff1ca3b46b43)
(References)
# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** all (can try nutrition or pharmacology for ease of use)
- **ref/branch:** main
- **chapter/section:** 
- **surrounding text:** References / Suggested Reading

# Acceptance Criteria

## Web
Please add hanging indent on References and Suggested reading in webview styles. Likely things tagged as "references" and "suggested-reading" can get the hanging indent styling.

**Comment by wilkus27** [comment]
### Information for tester
Applied for `suggested-reading`, `references` and `reference` classes.

There are a few types of references, but they have the same classes, so there might be some regression. For example, in `business-ethics` and `marketing` references are bunch of notes. I think they contain only spans, but if there are instances with paragraphs, changes from my PR might have an impact on them.

**Comment by Stackblocks** [comment]
Suggested Reading and References now showing a hanging indent in nursing-external books, there was no change in marketing between the main branch and the development branch.

## Nutrition
### Suggested Reading
![CleanShot 2024-02-21 at 16 46 18](https://github.com/openstax/cnx-recipes/assets/12678235/811a7ad3-ca45-44f8-9fa3-27a9f64dfa24)
![CleanShot 2024-02-21 at 16 47 00](https://github.com/openstax/cnx-recipes/assets/12678235/ad910ded-e84c-4655-9116-9f5d185ff236)
### References
![CleanShot 2024-02-21 at 16 48 43](https://github.com/openstax/cnx-recipes/assets/12678235/98caf26f-c883-4bb7-a884-4506743ebc33)

## Pharmacology
### References
![CleanShot 2024-02-21 at 16 50 57](https://github.com/openstax/cnx-recipes/assets/12678235/6762b950-98a3-4c6c-bed1-e8c1447448c0)
