### ISSUE TITLE
Nutrition - web view - tables with bullets are misaligned with other text in other cells

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5467]
In Web View extra space added in table bulleted lists, But in PDF View shown correctly. Kindly check nad resolve this issue.
Here with attached screenshot FYR..
**Population Health, the bulleted items are lower in the web view.**
<img width="912" alt="image001" src="https://github.com/openstax/cnx-recipes/assets/86622862/b5c69f79-e3b7-4153-b2e1-23949fcbf3df">

**Nutrition**
**In PDF view, alignment of bulleted items is the same as non-bulleted items:**
<img width="741" alt="image002" src="https://github.com/openstax/cnx-recipes/assets/86622862/529feb43-2480-4327-bfc7-27170e37e579">
**In web view, alignment of bulleted items is the lower than non-bulleted items:**
<img width="702" alt="image003" src="https://github.com/openstax/cnx-recipes/assets/86622862/5c0b4e1c-ca57-424f-9dac-f23b77ef69d4">
<img width="885" alt="image004" src="https://github.com/openstax/cnx-recipes/assets/86622862/99b04d63-f28e-4370-ad0e-db2e5672795c">

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [x] Other (Please describe below)
- This will likely impact all lists in all tables (and it should)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** Nutrition
- **ref/branch:** https://openstax-osbooksnursing-om7p9xrw6yq.ws-us108.gitpod.io/
- **chapter/section:** Chapter 06/section 6.3
- **surrounding text:** provides a list of common medications used to treat seizures.

# Acceptance Criteria

## PDF
N/A

## Web
![Screenshot 2024-02-16 at 12 58 22 PM](https://github.com/openstax/cnx-recipes/assets/11299125/a1d00848-8ebb-4223-a288-05fd0556003a)
- The default vertical alignment for lists might be center aligning in the cell - can we have it match with the rest of the cells unless it says otherwise in the cell alignment?
- Ideally, they should align with other text (top, left by default) 
- If there is specific alignment instructions in HTML, please let those override the default

**Comment by wilkus27** [comment]
### Information for tester
Problem wasn't related with alignment. Lists on webview have top and bottom margin set to `1rem`, that's why there was additional space over list. I removed top margin only from lists from tables. All others still should have it.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Nutrition
![Zrzut ekranu z 2024-02-23 17-39-14](https://github.com/openstax/cnx-recipes/assets/47241114/50e32876-f5ec-4f61-b6e3-9d9a6c7e2d74)
