### ISSUE TITLE
nursing-external - Table header rule missing in PDF

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5468]
For this chapter 13 table header rule is missing in PDF Table 13.1 & Table 13.2, But shown correctly in WEB View. Kindly check and resolve this issue.
Here with attached screenshot FYR..
**Web view**
![image001](https://github.com/openstax/cnx-recipes/assets/86622862/d59161fd-2776-4496-b8a3-de530efe3183)
**Table 13.2 PDF view – the header rule between column 3 and 4 header is missing but all others are present.**
![image002](https://github.com/openstax/cnx-recipes/assets/86622862/276ee210-4f56-4de9-9363-cbdc873bf8a2)

We have faced this similar issue partially for Nutrition course & Pharmacology also
**NUTRITION** : 
![image003](https://github.com/openstax/cnx-recipes/assets/86622862/3772daa1-7ee6-4605-8b51-86fd0bbed2d2)

**PHARMACOLOGY** : 
![image2](https://github.com/openstax/cnx-recipes/assets/86622862/12940cd9-d609-44aa-adf3-2b92a0987857)

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** Population Health
- **ref/branch:** https://openstax-osbooksnursing-om7p9xrw6yq.ws-us108.gitpod.io/
- **chapter/section:** Chapter 13/Section 13.1,13.2
- **surrounding text:** tis A and B can be prevented with safe, effective vaccines.

# Acceptance Criteria

## PDF
Due to inconsistent line issues from before, header separators should now be present to make things easier. Can we turn on internal borders for tables? This will hopefully eliminate inconsistencies and issues with merged cells

**Comment by kswanson33** [comment]
@lwtchu the inconsistency is being caused by `<colgroup>` styling. i've moved the colgroup styles to only applying to the table body, not the header. this causes the inconsistent rules to disappear.

![Image](https://github.com/openstax/cnx-recipes/assets/26280712/89f514fc-ac20-4f24-a0dd-8dac6527a62e)

if i were to add the rules instead, it would by default impact all basic tables in `carnival`. alternatively, i can add the rules in a way that only targets nursing.

**Comment by lwtchu** [comment]
@kswanson33 let me check the content - sorry i should've looked

**Comment by kswanson33** [comment]
additional note: the `<colgroup>` for this table spans 3 columns, and the table is 4 columns wide. if the `<colgroup>` spanned 4 columns, the original styles would cause separators to appear between all header columns without modification

**Comment by lwtchu** [comment]
@srm-openstax There's a mismatch of `<tgroup cols="3">` attributes with the number of actual columns in the tables in Pharmacology and Community Population health causing issues with the table styling.

Please double check the `<tgroup cols="3">` tags and make sure the cols numbers match with the actual amount of columns that are present on the table.

**Comment by srm-openstax** [comment]
Thank you for your suggestions. Issue was resolved.
