### ISSUE TITLE
computer programming python - code numbering table - remove table numbering

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5469]
# Summary & Screenshots
![image](https://github.com/openstax/cnx-recipes/assets/11299125/30ce22b0-ebe7-46d7-9dac-899677306e64)

# Sample Mark-Up
```
 <code class="python line-numbering" lang="python">
    # Setup a list of numbers
    num_list = [2, 3, 5, 9, 11]
    print(num_list)

    # Print the length of the list
    print("Length: ", len(num_list))

    # Print the 4th element in the list
    # The number 3 is used to refer to the 4th element
    print("4th element:", num_list[3])

    # The desired value of the 4th element is actually 7
    # Update the value of the 4th element to 7
    num_list[3] = 7

    # The list of the first 5 prime numbers
    print(num_list)
    </code>
    <para id="para-00012">The above code's output is:</para>
    <code class="python" lang="python">
    [2, 3, 5, 9, 11]
    Length: 5
    4th element: 9
    [2, 3, 5, 7, 11]
    </code>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [x] Other (Please describe below) - purely content - cookbook

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:** main
- **chapter/section:** https://github.com/openstax/osbooks-introduction-python-programming/blob/e0d2c0196cd744f4d617a5a6505d19659a523fea/modules/m00024/index.cnxml#L55 Section 3.4
- **surrounding text:** 

# Acceptance Criteria

## PDF & WEB
- it's likely a cookbook issue - but is it possible when the table gets created off of the line-numbering class, that the table also gets automatically added "unnumbered" class?
- table numbering needs to be removed on line numbered code snippets

**Comment by Stackblocks** [comment]
The table in question is now unnumbered and the following table becomes `Table 3.4` so it seems to be working properly.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/29b0f46e-5c05-4544-848f-413953ce9b15)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/bad71eeb-d771-4677-b75d-02c812bb1cc2)
