### ISSUE TITLE
data science - updates to EOC sections

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5470]
## REMOVE Chapter Problems and Data Sets
- class: chapter-problems

## ADD Chapter Review
- resets every chapter
- numbers are bold w a period
- title: Chapter Review
- class: chapter-review
- icon: [cardboard-casestudy.svg](https://drive.google.com/file/d/1tZDE2I5JPF6Ggo676xs79VSs4izviUKQ/view?usp=drive_link)

## ADD Critical Thinking
- resets every chapter
- numbers are bold w a period
- title: Critical Thinking
- class: critical-thinking
- icon: [cardboard-lightbulb.svg](https://drive.google.com/file/d/1lVezUadPa780bzW-XuOYTP_kbmi0_UmO/view?usp=drive_link)

## ADD Quantitative Problems
- resets every chapter
- numbers are bold w a period
- title: Quantitative Problems
- class: quantitative-problems
- icon: [cardboard-suggested.svg](https://drive.google.com/file/d/1Ltc0whfkE49KScYfgJ_72T7f99_T7Brk/view?usp=sharing)

### New EOC order
1. Key Terms
2. Group Project
3. Chapter Review
4. Critical Thinking
5. Quantitative Problems

## Content Location 
Repo: https://github.com/openstax/osbooks-data-science
Slug: principles-of-data-science
Branch: design-chapter

**Comment by wilkus27** [comment]
@lwtchu There is no spec for **Quantitative Problems**. By accident specs for Chapter Problems are added.

**Comment by lwtchu** [comment]
@wilkus27 updated!

**Comment by Stackblocks** [comment]
EOC sections look good. There is some irregularity with the Critical Thinking that i'm chalking up to there not being an answer key or suppression in place yet.


![CleanShot 2024-02-27 at 10 42 38](https://github.com/openstax/cnx-recipes/assets/12678235/c61538ea-6491-4819-941b-7d028508cbfb)
![CleanShot 2024-02-27 at 10 43 34](https://github.com/openstax/cnx-recipes/assets/12678235/33f1673f-5745-4225-8cf8-18d3f365ae88)
![CleanShot 2024-02-27 at 10 44 04](https://github.com/openstax/cnx-recipes/assets/12678235/66cce68d-1254-41d8-af04-c98e8aa23e42)
![CleanShot 2024-02-27 at 10 44 26](https://github.com/openstax/cnx-recipes/assets/12678235/34ff3d72-b32d-4da6-a63a-44f8c75d08dc)
