### ISSUE TITLE
computer programming python - pdf - line number tables in code snippets have too big of a left indent in exercises

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5471]
# Summary & Screenshots
![Screenshot 2024-02-22 at 12 47 10 PM](https://github.com/openstax/cnx-recipes/assets/11299125/28135be2-ea7f-430a-b4fb-fb7993590cd6)

Indent for `line-numbering` tables is too far in for exercises.

# Sample Mark-Up
```
 <exercise id="exer-00002">
    <problem id="prob-00002">
    <para id="para-00007"><link class="os-embed" url="#exercise/CPL-ch04-m02-p02"/></para>
    </problem>
    </exercise>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content: line number tables in exercises only
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** 
- **collection slug:**
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:** 

# Acceptance Criteria

## PDF
![Screenshot 2024-02-22 at 12 47 10 PM](https://github.com/openstax/cnx-recipes/assets/11299125/65e16e0f-1614-4ae8-a397-88415879a05e)

Can we bring it flush to the edge? Please let me know if there's any repercussions and we can adjust A/C

**Comment by wilkus27** [comment]
It's already fixed:

![image](https://github.com/openstax/cnx-recipes/assets/40228854/9eab0293-aea6-47fa-8861-e0d93af0f4ff)
