### ISSUE TITLE
data science - pdf - add bullet points to Learning Objective list

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5472]
![Screenshot 2024-02-22 at 1 12 58 PM](https://github.com/openstax/cnx-recipes/assets/11299125/8e93733b-5027-495f-88b4-a722836c6eb7)

Please add bullet points to the Learning Objective list.

```
 <section class="learning-objectives" id="sect-00001">
      <title>Learning Outcomes</title>
      <para id="para-00001">By the end of this section, you will be able to:</para>
        <list id="list-00001">
          <item>Define and calculate mean and trimmed mean and median for a data set.</item>
          <item>Define and calculate median for a data set.</item>
          <item>Determine the effect of outliers on mean and median.</item>
          <item>Use Python to calculate measures of center for a data set.</item>
        </list>
      </section>
```

## Location
Repo: https://github.com/openstax/osbooks-data-science
Slug: principles-of-data-science
Branch: design-chapter

**Comment by kswanson33** [comment]
hello QA i merged this on accident so the testable code is on ce-styles `main` 🙏 

(this was small enough potatoes that i decided reverting wasn't worth it, pls lmk if i should alter my processes)
