### ISSUE TITLE
data science - cookbook & pdf - changes to Python Feature 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5474]
![Screenshot 2024-02-22 at 1 55 52 PM](https://github.com/openstax/cnx-recipes/assets/11299125/48075f10-1594-46e1-944f-69167db6eb35)

- change title to Python Code
- class: `python-feature`
- add icon [cardboard-coding.svg](https://drive.google.com/file/d/1gJ5Wm_2PJxsJAe7NCPVj4XcOKSkxGi9N/view?usp=drive_link)
- icon specs can be found here https://github.com/openstax/cnx-recipes/issues/2737 

NOTE: This is a new icon. Please ping Larissa if SVG needs adjustments. 

Repo: https://github.com/openstax/osbooks-data-science
Slug: principles-of-data-science
Branch: design-chapter

**Comment by kswanson33** [comment]
@lwtchu hello! i've updated this feature with preexisting styles. seemingly there isn't an icon note that maps to the original note in all ways (peep the lack of borders) so let me know if this needs more styles. also let me know if the icon size looks off and i can resize. i used defaults.

![Image](https://github.com/openstax/cnx-recipes/assets/26280712/272920af-4f43-45ed-bbbf-61b46e04f3ff)

**Comment by lwtchu** [comment]
@kswanson33 is it possible to add icons to that color/style?

**Comment by kswanson33** [comment]
sure is

![Image](https://github.com/openstax/cnx-recipes/assets/26280712/9bcbfaa3-d6cc-44f9-9609-a100adc376c9)

**Comment by lwtchu** [comment]
@kswanson33 nit picking but is it also possible to reduce the spacing between the icon and the bottom border/line of the header box by like 1 px

**Comment by kswanson33** [comment]
![Image](https://github.com/openstax/cnx-recipes/assets/26280712/8e90e9dc-0356-4fa9-b0cb-4482a4436ce7)

**Comment by kswanson33** [comment]
changes on:
cookbook `ds-pycode-retitle`
ce-styles `ds-pynote-icon`

**Comment by MartaSztuka** [comment]
#### PASSED
##### PDF
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/4896a78a-98df-499d-a54e-7eaa20563c45)

##### webview
![Image](https://github.com/openstax/cnx-recipes/assets/47241114/f6be5c8e-e9c1-4d0d-b391-87f85fd1eebe)
