### ISSUE TITLE
data science - add an Answer Key

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5475]
Documentation https://github.com/openstax/cnx-recipes/issues/2748

**Comment by Stackblocks** [comment]
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/5d9ff7ec-0525-4663-a066-1ed8a8a26cca)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/cd3fb260-2546-4e59-8961-34815c3dfe8f)
