### ISSUE TITLE
data science - pdf - enable vertically tight tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5476]
We've done something similar in Finance https://github.com/openstax/cnx-recipes/issues/4294 and Nursing https://github.com/openstax/cnx-recipes/issues/5007
`class="vertically-tight"`
Set padding to 0.16rem which is equivalent to 2px
Styling should still follow generic tables for this theme

Repo: https://github.com/openstax/osbooks-data-science
Slug: principles-of-data-science
Branch: design-chapter
Table: Calculations for Sample Variance in m00003

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2024-02-26 16-07-46](https://github.com/openstax/cnx-recipes/assets/47241114/91002792-ce65-434e-92af-893a877b0277)
![Zrzut ekranu z 2024-02-26 16-10-39](https://github.com/openstax/cnx-recipes/assets/47241114/d42d1901-afcc-4898-8760-0283ad2b57c7)
