### ISSUE TITLE
data science - pdf - enable full width tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5477]
We've done similar here https://github.com/openstax/cnx-recipes/issues/5306

- `class="full-width"`
- table spans the full 6.5in width of content space
- does not interfere with additional styling -- merely should set the width of the table

Repo: https://github.com/openstax/osbooks-data-science
Slug: principles-of-data-science
Branch: design-chapter
Table: Data for S&amp;P 500 and Nike Stock Price over a 12-Month Period in m00007

**Comment by Stackblocks** [comment]
Table 1.8 in the current test content is now showing as full-width.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/53bff78d-74fc-4c94-8688-0cf728afe4d7)
