### ISSUE TITLE
nursing internal - pdf - bad alignment with number and period in exercises

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5479]
# Summary & Screenshots

Assessment numbering alignment in PDF is not correct. See screenshots

### PDF
![image](https://github.com/openstax/cnx-recipes/assets/89537088/a80a21ad-5122-47eb-9b2a-9e77f1d30e9c)

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** nursing-fundamentals
- **ref/branch:**
- **chapter/section:** All Assessments; See chapter 03
- **surrounding text:** 

# Acceptance Criteria

## PDF
- number and period to be together

**Comment by MartaSztuka** [comment]
#### PASSED
##### Clinical Nursing
![Zrzut ekranu z 2024-03-20 10-06-06](https://github.com/openstax/cnx-recipes/assets/47241114/2364fd72-0203-4cc4-985a-abe4215a74f8)
##### Psychiatric Mental Health
![Zrzut ekranu z 2024-03-20 10-05-04](https://github.com/openstax/cnx-recipes/assets/47241114/5752068e-c51a-49e2-aaa5-31429d648dd9)
##### Nursing Fundamentals
![Zrzut ekranu z 2024-03-20 10-36-44](https://github.com/openstax/cnx-recipes/assets/47241114/0aea91b7-7cb5-4acb-8c77-d6d8a21c69ed)
##### Maternal Newborn
![Zrzut ekranu z 2024-03-20 10-47-03](https://github.com/openstax/cnx-recipes/assets/47241114/1519ee22-988c-4882-ae5a-c374e6ee9352)
##### Medical Surgical
![Zrzut ekranu z 2024-03-20 11-20-28](https://github.com/openstax/cnx-recipes/assets/47241114/d5a050f2-9cb7-4d2c-8eff-5807db388b55)
