### ISSUE TITLE
data science - move references to end of chapter

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5480]
Originally it was added to end of the book https://github.com/openstax/cnx-recipes/issues/5337

Please move it to End of Chapter after the Assessments
icon: [cardboard-references.svg](https://drive.google.com/file/d/1COYw-42axWZWtonKiuHNoYMjdUEviB8q/view?usp=sharing)
class: class="references"
title: References
Should also have hanging indent and be alphabetized

Content updated here: https://github.com/openstax/osbooks-data-science/tree/design-chapter 
Slug: principles-of-data-science

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2024-03-01 17-01-52](https://github.com/openstax/cnx-recipes/assets/47241114/7e52c9e4-c1ca-4543-b6a3-b2ca27201ab6)
![Zrzut ekranu z 2024-03-01 17-02-06](https://github.com/openstax/cnx-recipes/assets/47241114/987382ee-d9e0-4966-95a1-466004d43eaf)
