### ISSUE TITLE
Microbiology - Image in preface too large

### ISSUE THREAD

**Issue by osiris001** [openstax/cnx-recipes#5481]
# Summary & Screenshots
![Screenshot 2024-02-26 at 2 37 46 PM](https://github.com/openstax/cnx-recipes/assets/43829253/ab33be1e-bcff-4e44-a04d-ffb92dff0243)

 pdf on the left (new) has an image that is overlapping other content in the text compared to pdf shown on the right (old) 

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [x] Other (Please describe below) Once

# Content Location(s)
- **osbooks repo:** osbooks-microbiology
- **collection slug:** microbiology
- **ref/branch:** main
- **chapter/section:** preface
- **surrounding text:** 

# Acceptance Criteria

**Comment by lwtchu** [comment]
Sent image via slack to update. Thanks!
