### ISSUE TITLE
Microbiology - header size changed

### ISSUE THREAD

**Issue by osiris001** [openstax/cnx-recipes#5482]
New header size difference throughout the text? Is this intended?
Screenshots below show the new PDF on the left and the old PDF on the right.

# Summary & Screenshots
![Screenshot 2024-02-26 at 2 38 46 PM](https://github.com/openstax/cnx-recipes/assets/43829253/48f7040a-fbc9-46c8-87f3-85e339efd34c)
Shown above is a section in the Preface. Title is no longer blue.
![Screenshot 2024-02-26 at 2 39 03 PM](https://github.com/openstax/cnx-recipes/assets/43829253/82f7eac3-2502-439b-9685-6422c9825e20)
another example in the Preface.
![Screenshot 2024-02-27 at 9 57 15 AM](https://github.com/openstax/cnx-recipes/assets/43829253/1dc99f3d-6f28-4fc0-88ed-62d28b1c1f15)
an example of the header size difference. Left side is new and right side is the old PDF. This is seen throughout the new PDF.

![Screenshot 2024-02-27 at 10 23 57 AM](https://github.com/openstax/cnx-recipes/assets/43829253/f28c3faa-9ae9-4385-af8e-cf8991ac33f5)
Appendix A is shown as an example

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-microbiology
- **collection slug:** microbiology
- **ref/branch:** main
- **chapter/section:** throughout text
- **surrounding text:** 

# Acceptance Criteria

**Comment by lwtchu** [comment]
Did some digging. We made them smaller with this issue #4733 -- so this is on purpose.
