### ISSUE TITLE
principles of finance - web - terms in titles not bold on web

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5483]
# Summary & Screenshots
As a result of testing from here: https://github.com/openstax/cnx-recipes/issues/5054

Everything was more or less fixed and behaving correctly except in Principles of Finance oddly enough
![Screenshot 2024-02-26 at 3 37 44 PM](https://github.com/openstax/cnx-recipes/assets/11299125/8cfe27d7-c47b-4331-b9fc-0ba10b19aa4f)
Video Activity Ch 16

![Screenshot 2024-02-26 at 3 40 02 PM](https://github.com/openstax/cnx-recipes/assets/11299125/c3db4217-b0cc-46d6-9f89-614f81decd55)
Link to Learning 15.3 - CAPM - broken here (should still be bold)

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [x] Other (Please describe below): might be issues in title for notes and EOC sections

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-finance/tree/main
- **collection slug:** principles-finance
- **ref/branch:** main
- **chapter/section:** see above 
- **surrounding text:** 

# Acceptance Criteria

## PDF
PDF should have headers that remain bold

## Web
For some reason this isn't matching the behavior of the fix from #5054 where the headers in the web should also be bold if it has a no-emphasis tag in a title

**Comment by wilkus27** [comment]
Checked with the code from main on ce-styles (03/04/2023). It's working:

![image](https://github.com/openstax/cnx-recipes/assets/40228854/c8885d08-8130-4750-9c6b-64cb9e303e1b)

![image](https://github.com/openstax/cnx-recipes/assets/40228854/47853aff-e44f-495a-b02a-32370c415a63)

**Comment by lwtchu** [comment]
@Stackblocks - we might have to double check on corgi one more time

**Comment by Stackblocks** [comment]
Could it possibly be something specific to the CORGI pipeline or some other part of the generation process? 

When I test locally with `&content-style=https://raw.githubusercontent.com/openstax/ce-styles/main/styles/output/webview-generic.css`as the style I see what @wilkus27 is seeing, but when generated with that same stuff deployed to CORGI it goes back to being busted.

![CleanShot 2024-03-11 at 13 34 44](https://github.com/openstax/cnx-recipes/assets/12678235/e5f1be70-8e78-4471-a73a-aafb3f4a5968)
![CleanShot 2024-03-11 at 13 32 34](https://github.com/openstax/cnx-recipes/assets/12678235/8ffc502b-595f-42b7-9902-f77e456cba92)

**Comment by lwtchu** [comment]
Just remembered baked styles for web isn't activated for Finance T_______T it should be ok
