### ISSUE TITLE
nursing-external - PDF - numbered list greater than two digits falling outside of margins

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5485]
# Summary & Screenshots
We have correctly coded the number list items. However, while the number list items after "9" display properly in the WEB view. But in PDF view it's shows outside the margin. Kindly check and resolve this issue. Here with attached Screenshots FYR..
**IN WEB VIEW:**
![WEB_View](https://github.com/openstax/cnx-recipes/assets/86622862/0d223435-4569-4f53-80a2-8fb4ff028a5c)

**IN PDF VIEW:**
<img width="837" alt="PDF_View" src="https://github.com/openstax/cnx-recipes/assets/86622862/ff86195c-0a10-40fb-99b6-b9a0b6ba9de0">

**IN PDF VIEW: - Pharmacology**
![Ch02_Pharma](https://github.com/openstax/cnx-recipes/assets/86622862/0ae4cfb5-32ce-4158-aeec-d53ab524b8f4)

**IN WEB VIEW:**
![Ch02_Pharma(WEB)](https://github.com/openstax/cnx-recipes/assets/86622862/9f9617be-752d-4716-bc91-eaee26bd5e03)

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location** 
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** Population-Health, Pharmacology
- **ref/branch:** https://openstax-osbooksnursing-om7p9xrw6yq.ws-us108.gitpod.io/
- **chapter/section:** Chapter 11/11.2;, Pharma - Ch02/Section 2.3
- **surrounding text:** The function of public health can be summarized as monitoring the health; Pharma: Position the client in an upright position or on side as condition

# Acceptance Criteria

## PDF
- I think some spacing work was done a while back to get the alignment to work with two digit lists - however now they're falling outside of the content space
- do not copy webview - it just needs to be in the margin and start on the edge

## Web
- don't do anything

**Comment by lwtchu** [comment]
@wilkus27 can i see the h-spacing(4)?

**Comment by lwtchu** [comment]
Reviewed the PDF @wilkus27 sent - we will increase the margin for first level lists from h-spacing(3) to h-spacing(4), and for second and third level lists from h-spacing(2) to h-spacing(3). Changes will have an impact on all books from carnival. Most impact for most books is the lists wont be aligned with the text anymore but at least double digit numbers will fit.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Pharmacology
![Zrzut ekranu z 2024-03-05 16-58-53](https://github.com/openstax/cnx-recipes/assets/47241114/72dd41ee-e09c-45b3-9d86-2e1de80bddec)
##### Population health
![Zrzut ekranu z 2024-03-05 17-05-43](https://github.com/openstax/cnx-recipes/assets/47241114/5facfc74-6851-4631-9434-e454daa5de01)
