### ISSUE TITLE
Nursing external - Tables breaking issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5486]
# Summary & Screenshots
Tables are randomly starting a new page instead of splitting across pages where there appears to be enough space on the previous page to include at least one row of table content.
 
This appears to be isolated to a few chapters.

 The content within the table row should not split across pages so it is important to keep the row grouped. This is especially important for the Drug Emphasis tables.
 
 Occurrences:
 
 **Population Health:**
Table 26.7
Table 26.9.

**Pharmacology :** 
Table 12.6
Table 12.8
Table 12.9
Table 12.11
Table 12.14

**"Population Health - Chapter 26: "**

**Table 26.9**
![Table26_9](https://github.com/openstax/cnx-recipes/assets/86622862/20f1044c-48a3-46fe-8a1f-562aa2aa9f3a)

**Pharmacology - Chapter 12**

**Table 12.11**
![Table12_11](https://github.com/openstax/cnx-recipes/assets/86622862/bc52e8b3-498b-43fb-8d78-67ce7e1cf5e1)

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** Population Health & Pharmacology 
- **ref/branch:** https://openstax-osbooksnursing-om7p9xrw6yq.ws-us108.gitpod.io/
- **chapter/section:** Chapter 26/section 26.3 & Chapter 12/Section 12.1
- **surrounding text:** influence their health and well-being (see Table 26.7). & therapeutic effects, drug and food interactions, adverse effects, and

# Acceptance Criteria

## PDF
Semi related card for page breaking: https://github.com/openstax/cnx-recipes/issues/5478 -- can tackle these two issues simultaneously

The table is pushed off even though tables should be able to break(?) and there's enough space for the row 

## Web
N/A

**Comment by openstaxalina** [comment]
Final list of tables this occurs in for Population Health (delivered by vendor with final content):
![image](https://github.com/openstax/cnx-recipes/assets/7863733/5ac93a64-8373-4782-abb3-8164c8317ff3)

**Comment by openstaxalina** [comment]
Final list of tables this occurs in for Pharmacology (delivered by vendor with final content):
![image](https://github.com/openstax/cnx-recipes/assets/7863733/f19ad865-088e-4e89-a18d-367f932b8398)

**Comment by openstaxalina** [comment]
This will become either a content issue or a "won't fix". Larissa is going to meet with @osiris001 tomorrow to see if there's anything we can do content-wise.
