### ISSUE TITLE
Nursing Internal -- PDF -- Exercises -- Add indent to bulleted lists in Answer Key

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5487]
# Summary & Screenshots
Add indent to bulleted lists in Exercises Answer Key

### PDF 
![image](https://github.com/openstax/cnx-recipes/assets/89537088/d8884d4d-39a5-444a-991c-eb1c313d2ac0)

### Webview looks good
![image](https://github.com/openstax/cnx-recipes/assets/89537088/c54b9920-2248-4685-8a09-363d0a65d575)

# Sample Mark-Up
```
<p>Multiple possible answers. Students must provide two answers for each. Examples of possible answers may include:</p>
<ul>
<li>Solitary play: a child looking at color pictures independently; a child interacting with a play gym independently</li>
<li>Parallel play: two children playing in a sandbox next to each other but not building the same castle; a child building a tower of blocks after the child next to them builds a different tower of blocks</li>
<li>Associative play: a group of children riding around one another on their bikes with no set path; two or more children engaging in noncompetitive dancing</li>
<li>Cooperative play: a group of children playing team games, puzzles, or board games</li>
<li>Onlooker play: children watching others play from a distance; a child making comments about other children playing but not engaging in the activity</li>
</ul>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** nursing-fundamentals
- **ref/branch:**
- **chapter/section:** Fundamentals Ch 38 / Nickname: 38-01-Fund-CU02
- **surrounding text:** 

# Acceptance Criteria

## PDF
- Please add indents to nested lists

## Web
N/A

**Comment by MartaSztuka** [comment]
#### PASSED
##### Nursing fundamentals
![Zrzut ekranu z 2024-03-22 14-08-44](https://github.com/openstax/cnx-recipes/assets/47241114/c6f06cf1-589c-4290-b0b3-f507aa55ae27)
##### Psychiatric mental health nursing
![Zrzut ekranu z 2024-03-22 14-11-45](https://github.com/openstax/cnx-recipes/assets/47241114/76f07df1-c7cb-4f02-b52f-7510f2d4be02)
##### Maternal newborn nursing
![Zrzut ekranu z 2024-03-22 14-16-43](https://github.com/openstax/cnx-recipes/assets/47241114/0493051a-f790-4fb2-9f4e-c9ee011c9687)
![Zrzut ekranu z 2024-03-22 14-17-04](https://github.com/openstax/cnx-recipes/assets/47241114/00be43a9-0892-40b1-a6f0-d9126e70dc3b)
##### Medical surgical nursing
