### ISSUE TITLE
Microbiology eoc questions spacing issue

### ISSUE THREAD

**Issue by osiris001** [openstax/cnx-recipes#5492]
# Summary & Screenshots

<img width="886" alt="Screenshot 2024-03-18 at 12 56 55 PM" src="https://github.com/openstax/cnx-recipes/assets/43829253/a2515486-932e-48f0-9654-38038e37fcb6">

There is extra space between the number and period
# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-microbiology
- **collection slug:**
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:** 

# Acceptance Criteria

## PDF
- a similar issue came in for #5479 - can we fix this for this title also since they're prepping for print?

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2024-03-20 11-37-19](https://github.com/openstax/cnx-recipes/assets/47241114/2c635d38-faf3-4cd6-a57d-9ba11fbf28eb)
