### ISSUE TITLE
Nursing Internal -- Confirming correct tagging for linking to Unfolding Case Study

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5493]
# Summary & Screenshots
The linking in the following two instances is working correctly. We just want to confirm that we are tagging it correctly.
1) in-text link to Unfolding Case Study (screenshot 1)
2) link from assessment item to Unfolding Case Study (screenshot 2)

### screenshot 1 Skills 4.1
![image](https://github.com/openstax/cnx-recipes/assets/89537088/fa9cc5bb-239a-4270-895b-cd9756b1070b)

### screenshot 2 Fundamentals Ch 06
![image](https://github.com/openstax/cnx-recipes/assets/89537088/8577b1a0-8454-4822-af12-af6e1b8b38e8)

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** nursing-fundamentals; clinical-nursing
- **ref/branch:**
- **chapter/section:** Skills 4.1, Module m00069, Line 259; Fundamentals Ch 06 / Nickname: 06-02-Fund-CT01
- **surrounding text:** 

# Acceptance Criteria

**Comment by lwtchu** [comment]
@ww-openstax I think this is correct. I'm not sure if there's any issue or something that looks odd for y'all? Is it the fact that it's pulling in the subtitle?

**Comment by ww-openstax** [comment]
@lwtchu  yes the pulling of the subtitle hasn't worked in past publications -- especially when linking from assessments. It is working in Nursing so I think all is good. We were just confirming that this is all expected behavior. Thanks.

**Comment by lwtchu** [comment]
@ww-openstax This is expected behavior - we typically didn't allow it in the past because the subtitles were usually not specific, but in this case, they are so we can make an exception for these titles
