### ISSUE TITLE
[reopened] Nursing Internal -- Header row in middle of table not outputting correctly

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5494]
# Summary & Screenshots
Header row in middle of table not outputting correctly in both PDF and Webview
See tagging legend row 27

### PDF
![image](https://github.com/openstax/cnx-recipes/assets/89537088/a028da6c-7f20-44d4-92a9-2cdf1ec09175)

### Webview
![image](https://github.com/openstax/cnx-recipes/assets/89537088/626a79fd-102e-47ca-bde7-8687dcd0d3ee)

### Tagging
![image](https://github.com/openstax/cnx-recipes/assets/89537088/90039b20-6e62-4fcb-b4c3-5e9ef89ff152)

# Sample Mark-Up
```
    <table id="table-00001" summary=" ">
    <title>Size and Diameter of Needles</title>
    <tgroup cols="3">
    <colspec colnum="1" colname="c1"/>
    <colspec colnum="2" colname="c2"/>
    <colspec colnum="3" colname="c3"/>
    <thead>
    <row class="header-row" valign="top">
    <entry valign="bottom" align="center" namest="c1" nameend="c3">Length of Required Needle</entry>
    </row>
    <row valign="top">
    <entry valign="bottom" align="center">Length of Needle</entry>
    <entry valign="bottom" align="center">Patient’s Weight</entry>
    <entry valign="bottom" align="center">Quantity of Adipose Tissue</entry>
    </row>
    </thead>
    <tbody>
    <row valign="top">
    <entry valign="top" align="left">5/8 in (13 mm)</entry>
    <entry valign="top" align="left">&lt; 130 lbs (59 kg)</entry>
    <entry valign="top" align="left">Minimal</entry>
    </row>
    <row valign="top">
    <entry valign="top" align="left">1 in (25.4 mm)</entry>
    <entry valign="top" align="left">130 to 260 lbs (59–118 kg)</entry>
    <entry valign="top" align="left">Normal</entry>
    </row>
    <row valign="top">
    <entry valign="top" align="left">1.5 in (38 mm)</entry>
    <entry valign="top" align="left">> 260 lbs (118 kg)</entry>
    <entry valign="top" align="left">Large or excessive</entry>
    </row>
    <row valign="top">
    <entry valign="top" align="left" namest="c1" nameend="c3">&#160;</entry>
    </row>
    <row class="header-row" valign="top">
    <entry valign="top" align="center" namest="c1" nameend="c3">Diameter of Required Needle</entry>
    </row>
    <row class="header-row" valign="top">
    <entry valign="top" align="center">Gauge of Needle</entry>
    <entry valign="top" align="center" namest="c2" nameend="c3">Medication Composition</entry>
    </row>
    <row valign="top">
    <entry valign="middle" align="left">20G to 25G</entry>
    <entry valign="top" align="left" namest="c2" nameend="c3">Aqueous solution</entry>
    </row>
    <row valign="top">
    <entry valign="middle" align="left">18G to 21G</entry>
    <entry valign="top" align="left" namest="c2" nameend="c3">Viscous or oil-based solution</entry>
    </row>
    </tbody>
    </tgroup>
    </table>
```

# Issue Occurrence(s)

 **Location**
- [X] In PDF
- [X] In Web

**Frequency**
- [X] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** clinical-nursing
- **ref/branch:**
- **chapter/section:** Skills 12.6, Table 12.2, Module m00102, lines 104 - lines 156
- **surrounding text:** 

# Acceptance Criteria

## PDF
- Should stay the same as the title row - I think the padding is off here

## Web
- Can we add header row styling to tables on web? Should be similar styling for the header row (bold text)

**Comment by ww-openstax** [comment]
@lwtchu I saw your comment above that the PDF should stay the same but just making sure that you noticed that in the PDF there is a different output for each of the header rows.

**Comment by lwtchu** [comment]
@ww-openstax Nice catch! I did not finish my train of thought there :joy: thank you

**Comment by Stackblocks** [comment]
In WebView, everything matches up across header rows.



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/14dae2e2-0970-46b8-b1d8-4ba161a48fca)


In the PDF, the header row of the sub-table now has the same text styling as the header row of the main table, but the height of the sub-table header row is still compressed. Is that acceptable, @lwtchu?

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/a4124abd-eea4-46b1-84ed-831e5d749c0b)

**Comment by lwtchu** [comment]
@Stackblocks we might have to send this back 👀

**Comment by jbwilson8** [comment]
Unable to replicate issue

Current PDF render:
![Image](https://github.com/openstax/cnx-recipes/assets/26155528/9fb71916-7e3f-40b7-9804-427b287b73b7)

**Comment by Stackblocks** [comment]
Showing correctly in PDF and Web Preview on CORGI so I assume it was an issue either with something at the time of testing or with my system.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/e244c64e-9e2b-48a7-9cd6-c9f9d5875d5d)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/0c973604-9c7a-4a10-aae5-c6ed693d40dc)

**Comment by ww-openstax** [comment]
For PDFs. the font weight in the header row in the middle of tables is not the same font weight for header rows at the top of the table. See screenshot
![image](https://github.com/openstax/cnx-recipes/assets/89537088/b94bda64-ed29-4dfd-959f-f13308267324)

**Comment by openstaxalina** [comment]
@jbwilson8 we just unearthed this card from awhile back 😅 I verified the font weight discrepancy is still occurring on the latest PDF from CORGI (see folio page 488 [here](https://openstax-cops-artifacts.s3.amazonaws.com/openstax-osbooks-nursing-internal-bundle-0142c9b992ee12f855ca7035917940994c8b948e-12011-clinical-nursing-skills.pdf) -- note that it's a very slight discrepancy that is difficult to notice).

**Comment by jbwilson8** [comment]
@openstaxalina looks like the default font (`IBM Plex Sans, sans-serif`) is being overwritten. should we keep the default or update the header in the middle of the table to be `Mulish, sans-serif`?



![Image](https://github.com/openstax/cnx-recipes/assets/26155528/96e50c15-7722-45a3-b036-fc03b5eed3e6)

**Comment by openstaxalina** [comment]
@jbwilson8 the header in the middle of the table should be `Mulish, sans serif`. Per the documentation here, the non-header content in Carnival tables is styled in `IBM Plex Sans`, but the *headers* should be `Mulish`. 

Do you know if other books in the theme are also using `IBM Plex Sans` in table headers? Trying to get a sense for the scope of this change.

**Comment by jbwilson8** [comment]
@openstaxalina it appears that most table header fonts are being set at the book level and, when not specified, default to `IBM Plex Sans`. I think this was the only instance/book where the font defaulted. I'm updating the styles to set the font to `Mulish` for headers that exist in the middle of tables.

**Comment by openstaxalina** [comment]
sounds good - thank you @jbwilson8 !

**Comment by openstaxalina** [comment]
@ww-openstax another query - does this affect _Maternal Newborn Nursing_? I see that label on the card but the only example is from Skills. We need to know whether to hold off on prepping the Maternal Newborn PDF until this change is done.

**Comment by ww-openstax** [comment]
@openstaxalina 
1) Yes `Gauge of Needle` and `Medication Composition` were intended to be styled as header rows
2) We re-checked Maternal Newborn Nursing for any instances of `class="header-row"` for rows in middle of tables and found 0 instances. This card does not affect Maternal Newborn Nursing.

**Comment by openstaxalina** [comment]
@caylaeagon can you please add the `header-row` class on the row with `Gauge of Needle` and `Medication Composition`?

**Comment by caylaeagon** [comment]
:white_check_mark: `class="header-row"` added to Table 12.2
![Screenshot 2024-06-17 at 2 59 16 PM](https://github.com/openstax/cnx-recipes/assets/99201272/b0f75868-3759-47f3-b368-b1571b5101b7)

**Comment by MartaSztuka** [comment]
Hi, @caylaeagon there is still problem with font weight in the header row
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/1c8fe1bb-e661-496f-a2dd-f58ce8a258f9)
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/9253846c-443f-4c65-aa4a-4d9bf2c79003)

**Comment by openstaxalina** [comment]
@jbwilson8 see above - does your fix need to be adjusted to apply to multiple mid-table header rows?

**Comment by openstaxalina** [comment]
assigning to @sparksam for code review

**Comment by omehes** [comment]
retested. both outputs look good


![Image](https://github.com/user-attachments/assets/60bc315b-d434-4d8d-8e38-cc3ecc8eba91)
![Image](https://github.com/user-attachments/assets/49de237e-cdac-4674-b9d2-bfe21ace68f2)
