### ISSUE TITLE
Nursing Internal -- Unfolding Case Study assessments -- enable support for injected exercises in case study 

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5495]
# Summary & Screenshots
In the Tagging Legend, no tagging exists for Unfolding Case Study assessments. If the tagging is the same as an EOC assessment then an adjustment to the output is needed.

The output should match the output for the Nursing-**External** template and include assessment numbering and answer should output in book Answer Key  

![image](https://github.com/openstax/cnx-recipes/assets/89537088/45a93214-1411-46c4-b0d8-f334c3b7c81e)

# Sample Mark-Up
```
    <note id="note-00002" class="unfolding-casestudy">
    <title>Unfolding Case Study #1: Part 4</title>
    <para id="para-00035">Refer to <link document="m00036">Patient Communication and Interviewing</link> for Unfolding Case Study Parts 1 to 3 to review the patient data. The nurse is providing care to a twenty-eight-year-old female patient who arrived at the walk-in medical clinic. The female patient speaks only Spanish and is accompanied by her bilingual, ten-year-old son. Following the initial assessment, the patient’s respiratory status begins to rapidly decline.</para>
    <table class="unnumbered" summary=" " id="table-00002">
    <!--<title>Female Patient</title>-->
    <tgroup cols="2">
    <colspec colnum="1" colname="c1"/>
    <colspec colnum="2" colname="c2"/>
    <tbody>
    <row valign="top">
    <entry valign="top" align="left">Past Medical History</entry>
    <entry valign="top" align="left">Patient is a mother of one, who cares for her child and mother in a small apartment. The mother is homebound and is not present at appointment. Patient cleans houses to support her family, but income is inconsistent. Patient has an eighth-grade education and speaks no English. Medical history includes seasonal allergies, sinusitis, and two episodes of COVID-19 in the past two years.<newline/>
    <emphasis effect="bold">Family History:</emphasis> Patient’s father is deceased, and patient’s mother has Alzheimer disease, stage II. Patient’s son is in good health, talkative, and attentive to his mother.<newline/>
    <emphasis effect="bold">Social History:</emphasis> Patient is primary caregiver for mother and adolescent. No other support systems available. Patient has difficulty shopping and making doctor’s appointments due to lack of care for mother. Patient has difficulty communicating in English, but son translates for his mother.<newline/>
    <emphasis effect="bold">No current medications and no known allergies.</emphasis></entry>
    </row>
   ...
    </tbody>
    </tgroup>
    </table>

    <exercise id="exer-01">
      <problem id="prob-01">
      <para id="para-66"><link class="os-embed" url="#exercise/04-01-Skills-UCS01"/></para>
      </problem>
    </exercise>
    <exercise id="exer-02">
      <problem id="prob-02">
      <para id="para-67"><link class="os-embed" url="#exercise/04-01-Skills-UCS02"/></para>
      </problem>
    </exercise>
</note>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** clinical-nursing
- **ref/branch:**
- **chapter/section:**  Skills 4.1, Module m00069, Line 172;
- **surrounding text:** 

# Acceptance Criteria

## Cookbook (PDF & Web Output)
- number the individual questions - reset every chapter (since Unfolding Case Studies aren't numbered on the feature box level)
- suppress choice level feedback
- answers and detailed solution should go to the answer key under Unfolding Case Studies and separated by chapter
-

**Comment by lwtchu** [comment]
@ww-openstax i don't think we enabled support for injected exercises in the unfolding case study - we can do that here. 
 
Please review the acceptance criteria and let me know if there's any changes you'd like to make.

**Comment by ww-openstax** [comment]
@lwtchu I am checking with the team to see if there is anything additional for the acceptance criteria.

In first bullet of Acceptance Criteria, I don't quite understand reference to "multi part questions"  The examples provided in the screenshots are two standalone questions. It's possible that UCS will have multi-part questions but unlikely.

Also worth noting is that there are often multiple Unfolding Case Studies feature boxes in a chapter. I'm checking with team if it's ok that the assessment numbering would _not_ restart with each UCS, otherwise the numbering in the Answer Key would look strange

**Comment by lwtchu** [comment]
@ww-openstax sounds good -- i thought the two questions in the screenshot were part of a MPQ but I've adjusted the requirements. it would be preferable that the numbering does not restart but I'll await feedback!

**Comment by ww-openstax** [comment]
@lwtchu confirming that the Acceptance Criteria looks good to WiseWire.
The numbering should restart with each chapter but numbering should _not_ restart with each UCS inside of a chapter

**Comment by kswanson33** [comment]
branches: cookbook `nursing-casestudy` & ce-styles `unfolding-exercise`

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `nursing-casestudy` + `unfolding-exercise` & content from `main`

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/56beee9c-bf9e-4f63-b87f-925654d0980d)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/09a2965f-247a-4007-8f8e-ceb9147cebc5)

**Comment by jbwilson8** [comment]
Unable to replicate issue

Current PDF 
![Image](https://github.com/openstax/cnx-recipes/assets/26155528/9fb71916-7e3f-40b7-9804-427b287b73b7)

**Comment by Stackblocks** [comment]
Unfolding case study showed correctly in both PDF and Web Preview on CORGI staging, so I think we're all set.
