### ISSUE TITLE
Assessment Conversion -- elements appearing above items in Exercises

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5496]
# Summary & Screenshots

Certain elements are appearing above the items in Exercises when an Element ID tag is added to the item. This only occurs inconsistently -- that is, it does not occur EVERY time an Element ID is added. We also only noticed this happening with this week's batches of Chemistry and Precalculus assessments, which is why the issue has not been raised sooner.

And by "above" I mean literally "above" the assessment. It appears to be floating above the assessment, and is not present in the assessment's code or as an asset. 

It occurs with any kind of element referenced in Element IDs: images/figures, tables, and other exercises. Here are some examples (please note: these are all draft assessments in Exercises and have not yet been delivered to OSX as of 3/20/24):

### **An image (11-03-Ch-Ex04)**
![Screenshot 2024-03-20 at 17 58 44](https://github.com/openstax/cnx-recipes/assets/89537088/706d3557-c61b-4f28-9105-e34ef88e4451)

### **A table (05-03-Ch-Ex06)**
![Screenshot 2024-03-20 at 18 00 05](https://github.com/openstax/cnx-recipes/assets/89537088/2e50c1dd-6ec8-4abb-9d94-a0a9739dd9f7)

### **An exercise (05-02-Ch-Ex15)**
![Screenshot 2024-03-20 at 18 02 44](https://github.com/openstax/cnx-recipes/assets/89537088/a16ec35e-c355-4730-91bc-2d772d9fd314)

### **Example of inconsistency (01-03-PC-RE03) - Element ID is present but does not appear above the item**
![Screenshot 2024-03-20 at 18 01 11](https://github.com/openstax/cnx-recipes/assets/89537088/c0bbc7af-9177-4c7c-a1e8-fc5edc474f42)

### Note
You probably noticed that all of the images being pulled were from the Spanish versions. I'm going to log another ticket about that because I think it is a separate issue.

# Sample Mark-Up
11-03-Ch-Ex04: Note that the code of the assessment itself does not contain any images.
```
Calculate the percent by mass of KBr in a saturated solution of KBr in water at 10 °C. See the figure for useful data, and report the computed percentage to one significant digit.

<span data-math="{\rm{ }}40\% "></span>

<p>At 10 °C, the solubility of KBr in water is approximately 60 g per 100 g of water.</p>
<p><span data-math="\% {\rm{\ KBr\ }} = {\rm{ }}\;\frac{{60\;{\rm{ g\ KBr}}}}{{\left( {60{\rm{\ }} + {\rm{\ }}100} \right)\;{\rm{ g\ solution}}}}{\rm{ }} = {\rm{ }}40\% "></span></p>

```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [ ] In Web
- [X] in Exercises

**Frequency**
- [ ] At every instance of the content
- [X] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** 
- **collection slug:** book-slug:chemistry-2e, book-slug:precalculus-2e
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:** 

This is only occurring in Exercises. 

# Acceptance Criteria

**Comment by lwtchu** [comment]
This is a feature in the exercise tool to preview the context-id elements and likely does not appear every time due to this feature not being maintained and updated with the library. This should not have any impact on the actual JSON/database itself.
