### ISSUE TITLE
Assessment Conversion -- Element IDs linking to Spanish-language versions in English-language titles

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5497]
# Summary & Screenshots

_This is related to issue [#5496](https://github.com/openstax/cnx-recipes/issues/5496)._ 

When the bug as noted in issue [#5496](https://github.com/openstax/cnx-recipes/issues/5496) occurs (an Element ID is added to an assessment, which causes the element to appear above the assessment in Exercises), the Element ID always seems to pull from the Spanish-language version of the element, instead of the intended English-language version.

### Example from 11-03-Ch-Ex04
![Screenshot 2024-03-20 at 17 58 44](https://github.com/openstax/cnx-recipes/assets/89537088/bdd07228-3216-4fa6-b847-c47924c331cb)

When I looked into this further, I found that the Spanish version of the page did indeed have the same Element ID as the English version.

### Chemistry, Chapter 11, Section 3, Figure 11.16 = CNX_Chem_11_03_solubility
![Screenshot 2024-03-20 at 18 20 06](https://github.com/openstax/cnx-recipes/assets/89537088/4326ecc9-a377-4817-a954-26769b225447)

### Química, Capítulo 11, Section 3, Figura 11.16 = CNX_Chem_11_03_solubility
![Screenshot 2024-03-20 at 18 22 23](https://github.com/openstax/cnx-recipes/assets/89537088/ae870f78-94cf-4dcc-91a3-1c673dc201ab)

I am wondering if this means that Exercises doesn't know which one to access, and simply defaults to the Spanish one for some reason.

I checked several other examples and they were all like this. Additionally, the reverse was not observed (English elements appearing above Spanish assessments). This only seems to occur in the most recent batches of Precalculus and Chemistry assessments (not delivered to OSX yet).

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [ ] In Web
- [X] in Exercises

**Frequency**
- [ ] At every instance of the content
- [X] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** 
- **collection slug:** book-slug:chemistry-2e, book-slug:precalculus-2e
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:** 

# Acceptance Criteria

**Comment by lwtchu** [comment]
There is currently no way to tie the specific UUID module to the ID to specify which image to pull. However, this is permissible due to the reason that the content that will be converted will almost always be delivered with the full book (whether in assignable, or in the textbook itself) and will have a reference. 

The rationale for why this isn't an issue is also described here #5496 - there's no impact to the actual database it's just the exercise tool that is not updated. 

Should not be an issue in new exercise tool in the future.
