### ISSUE TITLE
Data Science - Reactivate the "green-code" tag from Row 47

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5500]
It would be preferred if function references in the narrative text were indicated by a monospace typeface with the name highlighted in blue, (or a similar color). (The parentheses symbol can likely be left in monospace black, as function references are handled in the Python Programming text.)
![Img_01](https://github.com/openstax/cnx-recipes/assets/86622862/cffdbed8-bcd4-4a42-874e-c34a0ecc641b)

For this purpose, we will need to apply the manual “blue-code” tag from Row 47; could you please reactivate this?
![Img_02](https://github.com/openstax/cnx-recipes/assets/86622862/1e284307-78b8-4828-9663-d5e4e72b76cc)

## Acceptance Criteria
Please enable span class="green-code" in code snippets.

Test content location: https://github.com/openstax/osbooks-principles-data-science/commit/2ed58c11925c715710d234436da6bb9de0e901b6
Branch: design-chapter

Set to G2: `#006900` - should be the same color schema - make sure enabled in web also

**Comment by lwtchu** [comment]
@srm-openstax The automated tool that we have to apply color to the Python code is setting the functions to `#006900` - which would be the `green-code` -- will that work?

**Comment by srm-openstax** [comment]
Thank you @lwtchu We'll apply this green-color to the Python code. 
We'll have to wait and see how the final PDF displays this Python color coding. :) 
Best!

**Comment by wilkus27** [comment]
@lwtchu Do we want to use hljs here? If yes, it should be activated when correct format is added. For example, comment is working here 

![image](https://github.com/openstax/cnx-recipes/assets/40228854/230f7ead-b639-4fb5-9314-3f51918a5b98)

It has to start with "#"

**Comment by lwtchu** [comment]
@wilkus27 no this is a one off color coding in the text narrative

**Comment by Stackblocks** [comment]
Looks good!

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/32957d87-2c69-4f07-9332-4c64996f5806)
