### ISSUE TITLE
information systems - updates to EOC sections

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5501]
![Screenshot 2024-04-01 at 10 29 09 AM](https://github.com/openstax/cnx-recipes/assets/11299125/5334addb-27e9-4b68-b8c9-b7452b90a95b)

## Remove
Reflection Questions `class="reflection-questions"`
Media Questions `class="media-questions"`

## Change
`class="check-understanding"` 
Change the title to `Check Your Understanding Questions`

## Add
title: Application Questions
icon: https://drive.google.com/file/d/1Ltc0whfkE49KScYfgJ_72T7f99_T7Brk/view?usp=sharing
class="application-questions"

**Comment by Stackblocks** [comment]
Displaying OK

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/c83b018f-4f3f-4f2c-a432-e1312781f191)
