### ISSUE TITLE
class="meet-author" has "Introduction" in style

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5502]
The markup
 ```
 <note class="meet-author" id="note-00001">
      <title>Irina Calin-Jageman, PhD</title>
      <para id="para-00001">Meet the author</para>
    </note>
```
results in 
<img width="688" alt="Screenshot 2024-04-02 at 11 28 17 AM" src="https://github.com/openstax/cnx-recipes/assets/1895432/a554679c-8cdd-42fa-809b-41d10a9593a7">
 which contains "Introduction" that's not supposed to be there.

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-neuroscience
- **collection slug:** neuroscience
- **ref/branch:** all
- **chapter/section:** Chapter 1
- **surrounding text:**  Irina Calin-Jageman, PhD

# Acceptance Criteria

## PDF
Can we move the introduction header text out of the feature box?

**Comment by wilkus27** [comment]
@lwtchu This is what it looks like:

![image](https://github.com/openstax/cnx-recipes/assets/40228854/79c65a8b-9bec-4d65-bfa2-44a8b95292a6)

Since it's not inline header in this case, should it be styled differently, similar to other headers (blue, not uppercase etc.) or is it ok as it is?

**Comment by lwtchu** [comment]
@wilkus27 we can't move the introduction to the paragraph below? If not, we can style it similar to other headers 🤔 - i guess that makes sense cause there's something in between it

**Comment by wilkus27** [comment]
It should be possible. Let me try to apply it :wink:

**Comment by MartaSztuka** [comment]
#### PASSED
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/4f7f357a-4e38-4e62-b6f9-6a0ecf4d872b)
