### ISSUE TITLE
Neuroscience Key Terms lack formatting

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5504]
# Summary & Screenshots
the key terms, which are marked up as inline lists, do not have inline list formatting applied to them
<img width="599" alt="Screenshot 2024-04-02 at 12 27 23 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/4a235711-8532-4caf-8f3c-6e03a6c743a7">

# Sample Mark-Up
```
    <section class="key-terms" id="sect-00005">
      <title>Key Terms</title>
      <list display="inline" id="list-00002">
        <item>Autoimmune disorder</item>
        <item>Autoreceptors</item>
        <item>Backpropagate</item>
        <item>Flaccid paralysis</item>
        <item>Homeostasis</item>
        <item>Retrograde messengers</item>
        <item>Spastic paralysis</item>
      </list>
    </section>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-neuroscience
- **collection slug:** neuroscience
- **ref/branch:**
- **chapter/section:** all
- **surrounding text:** 

# Acceptance Criteria

## PDF
- please put inline list styling where items are separated by comma

## Web
- please check on web that this feature is also styled

**Comment by Stackblocks** [comment]
I'm still seeing the clumped key terms in Neuroscience using the code from `neuroscience-key-terms-list`.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/d6990aca-3127-48af-9009-c59c26009ba1)

**Comment by lwtchu** [comment]
@Stackblocks i think that's correct - it has the commas
