### ISSUE TITLE
information systems - learning objectives

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5505]
Can we make sure the title for this is 
title size: font-scale(1): 10.8pt, 14.4px, 1.2rem

![Screenshot 2024-04-02 at 12 33 25 PM](https://github.com/openstax/cnx-recipes/assets/11299125/65d7384c-1940-41f6-80e7-8763d3d39b1f)

It's currently at 12.96 which is a scale up one.

**Comment by wilkus27** [comment]
@lwtchu Font sizes of titles were increased within https://github.com/openstax/cnx-recipes/issues/5021. All H3 have now font-scale(2). Should I decrease a size only for Learning Objectives in this case?

**Comment by lwtchu** [comment]
@wilkus27 i think that would be good - LOs should be an h3 in that case because it's not as important.

**Comment by wilkus27** [comment]
### Information for tester
It has an impact on all books from Cardboard

**Comment by Stackblocks** [comment]
LOs in Information Systems and across the Cardboard theme are now at 10.80

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/afce92cd-d1bd-4c52-80f7-84b2177b32fb)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/a6b0bb4c-f895-4754-af70-8d2a089109f7)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/e3c698f1-7412-48e0-ae1c-b483e91454e8)
