### ISSUE TITLE
information systems - feature box design changes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5506]
## Title Changes
- [x] IS Ethics to `Ethics in IS`
- [x] IS Careers to `Careers in IS`
- [x] IS Global Connect to `Global Connections`
- [x] IS Future Tech to `Future Technology`

## Color changes
- [ ] Please change Future Technology (formerly IS Future Tech) to color option 5 https://github.com/openstax/cnx-recipes/issues/2737

**Comment by Stackblocks** [comment]
Future Technology note doesn't match the Color Option 5 swatch from https://github.com/openstax/cnx-recipes/issues/2737

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/0434f83c-d414-4fb9-b5b5-587e7dae2b96)

**Comment by Stackblocks** [comment]
Future Technology note now showing with the correct colors.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/15535b70-d9d7-4467-b80f-d348013d8b22)
