### ISSUE TITLE
information systems - enable vertically tight tables

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5507]
We've done something similar in Finance https://github.com/openstax/cnx-recipes/issues/4294 and Nursing https://github.com/openstax/cnx-recipes/issues/5007
`class="vertically-tight"`
Set padding to 0.16rem which is equivalent to 2px
Styling should still follow generic tables for this theme

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `info-systems-vertically-tight` & content from `design-chapters`



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/2fd8aa71-18db-41c3-affb-2f44fc44ff8a)



1. Vertically tight table
2. Standard table
