### ISSUE TITLE
entrepreneurship - web - remove bullet points in footnotes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5508]
# Summary & Screenshots
![Screenshot 2024-04-05 at 3 56 12 PM](https://github.com/openstax/cnx-recipes/assets/11299125/68bccf1a-8537-425f-900f-051c46daca97)

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-entrepreneurship
- **collection slug:** entrepreneurship
- **ref/branch:** main
- **chapter/section:** 1.1 
- **surrounding text:**  

# Acceptance Criteria

## PDF
N/A 

## Web
Please remove bullets since this is already numbered.

Ryan reported small font below - we should see if this is deliberate in the styles. If it is, we can leave it but let's make sure it's not cause of another reason...

**Comment by oscryan** [comment]
accounting footnote font sized changed (new on the left)
<img width="1426" alt="Screenshot 2024-04-25 at 11 32 57 AM" src="https://github.com/openstax/cnx-recipes/assets/1895432/37c48291-81ee-4d7f-bcaf-b2729acae6ee">

**Comment by kswanson33** [comment]
@lwtchu New styles added:

- `list-style: none`
- `line-height: 2.5 rem`

How does this look?



![Image](https://github.com/openstax/cnx-recipes/assets/26280712/dcf08150-09f3-40c1-bd61-f028031d2001)

**Comment by lwtchu** [comment]
@kswanson33 this looks good

**Comment by MartaSztuka** [comment]
#### PASSED
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/aae11a05-3896-45c3-9d31-af28534ec815)
