### ISSUE TITLE
Math display equations

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5509]
# Summary & Screenshots
We have noticed the math equations aligned centred in the WEB view. However, the same content is viewed in the PDF view the math equations appear to be left aligned.
As per the tagging legend we used the tagging **<m:math display="block">** for this instances.

**MANUSCRIPT:**
![manuscript](https://github.com/openstax/cnx-recipes/assets/86622862/55ef72c6-8f25-4214-9a9f-f58e188deeb6)
**PDF VIEW:**
![PDF_View](https://github.com/openstax/cnx-recipes/assets/86622862/5387c91a-8799-4669-b0db-88a7a62b2e2f)
**WEB VIEW:**
![WEB_View](https://github.com/openstax/cnx-recipes/assets/86622862/4885a604-69d6-4997-89d8-09d9b001705a)

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:** Chapter 03/3.1
- **surrounding text:** The sample mean can be calculated using the following formula

# Acceptance Criteria

**Comment by lwtchu** [comment]
@srm-openstax Hello - there's a specific way to mark these up; please use the just added `<equation>` tagging on row 76 on the tagging legend. If you do not want it numbered, please add the unnumbered class.

**Comment by srm-openstax** [comment]
As per your suggestion we used <equation> tag and alignment issues resolved.
