### ISSUE TITLE
data science - pdf - Quantitative Problems section

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5510]
# Summary & Screenshots
After number 9th in the Quantitative Problems section is not properly indented in the PDF view, although it is accurately displayed in the WEB view.
**PDF VIEW:**
![PDF_View2](https://github.com/openstax/cnx-recipes/assets/86622862/af5ef687-4165-41b9-92cc-26f737124bac)
**WEB VIEW:**
![WEB_View2](https://github.com/openstax/cnx-recipes/assets/86622862/1a4d3594-6ecf-435f-b0d6-cf053d5036a4)

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:** Quantitative Problems section
- **surrounding text:** A medical researcher collects statistical data as follows:

# Acceptance Criteria

## PDF
- we've made similar changes recently to lists - is it possible to implement here where the numbers are aligned to the right

**Comment by MartaSztuka** [comment]
#### PASSED
Exercises will be fixed with https://github.com/openstax/cnx-recipes/issues/5511
![Zrzut ekranu z 2024-04-30 09-58-14](https://github.com/openstax/cnx-recipes/assets/47241114/f80f61c7-779a-4d9b-84d8-58f73f431183)

**Comment by srm-openstax** [comment]
Issue resolved.
