### ISSUE TITLE
Nursing Internal -- colwidth attribute in tables has no effect

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5512]
# Summary & Screenshots
The colwidth attribute in `<colspec>` doesn't seem to be working as a way to manually adjust the column width. (see tagging legend row 26.)
We actually want the columns to be equal but 
```
<colspec colnum="1" colname="c1" colwidth="1*"/>
<colspec colnum="2" colname="c2" colwidth="1*"/>
<colspec colnum="3" colname="c3" colwidth="1*"/>
```
did not have the desired effect.

So we tried the tagging in the screenshot below without any effect

The tagging for for the screenshot 
![image](https://github.com/openstax/cnx-recipes/assets/89537088/4db0e626-c83f-490f-8117-92f68883ffe9)

![image](https://github.com/openstax/cnx-recipes/assets/89537088/2c680505-f1a9-414d-81bd-a6cc01ee7466)

# Sample Mark-Up
```
<table id="table-00001" summary=" ">
    <title>Therapeutic Nurse Skills in Court-Ordered Treatment</title>
    <tgroup cols="3">
    <colspec colnum="1" colname="c1" colwidth="1*"/>
    <colspec colnum="2" colname="c2" colwidth="3*"/>
    <colspec colnum="3" colname="c3" colwidth="2*"/>
    <thead>
    <row class="header-row" valign="top">
    <entry valign="top" align="left">Knowledge</entry>
    <entry valign="top" align="left">Skills</entry>
    <entry valign="top" align="left">Attitudes</entry>
    </row>
    </thead>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** psychiatric-mental-health
- **ref/branch:**
- **chapter/section:** Section 11.1; Module m00593 lines 23-35 
- **surrounding text:** 

# Acceptance Criteria

## PDF
Please enable colwidth settings -- i believe this was done for the other nursing recipe card

**Comment by MartaSztuka** [comment]
#### PASSED
##### Psychiatric Mental Health
![Zrzut ekranu z 2024-04-19 11-29-44](https://github.com/openstax/cnx-recipes/assets/47241114/a719a9d6-548b-4e1b-bdae-a6c85a62eeaf)
![Zrzut ekranu z 2024-04-19 11-37-29](https://github.com/openstax/cnx-recipes/assets/47241114/e4f2a927-d27e-4671-8caf-ee2871ab6482)
