### ISSUE TITLE
Nursing Internal -- Answer Key. Remove Chapter headings when chapter does not include in-book solutions to assessments

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5513]
# Summary & Screenshots
Only solutions to Unfolding Case Study assessments will appear in Answer Key.
Not all chapters will contain Unfolding Case Studies.
In Answer Key, remove chapter heading for chapters that contain zero solutions in the Answer Key. (chapters without Unfolding Case Study)

![image](https://github.com/openstax/cnx-recipes/assets/89537088/a5720813-bd25-4cbf-bb2f-5903592e8235)

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [x] Other (Please describe below) for chapters without Unfolding Case Study

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** psychiatric-mental-health
- **ref/branch:**
- **chapter/section:** Chapters 1-15 and others
- **surrounding text:** 

# Acceptance Criteria

## Cookbook
Please do not populate headers when there are no answers present. Or remove answer key if there's no answers present.

**Comment by Stackblocks** [comment]
Answer Key appears to be omitting empty chapters successfully.

![CleanShot 2024-05-02 at 10 09 20](https://github.com/openstax/cnx-recipes/assets/12678235/0b8f9ab6-611c-4855-a2af-666ae967f5df)
