### ISSUE TITLE
pl-marketing - add translations

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#5514]
Add translations for notes titles and EOC sections:

#### Notes:
- marketing-dashboard: Marketing Dashboard - Analityka marketingowa
- marketing-practice: Marketing in Practice - Z doświadczenia marketera
- companies-conscience: Companies with a Conscience - Etyczna firma
- link-to-learning: Link to Learning - Sięgnij po więcej

#### EOC sections
- knowledge-check: Knowledge Check - Sprawdź wiedzę
- chapter-summary: Chapter Summary - Podsumowanie rozdziału)
- marketing-discussion: ‘Applied Marketing Knowledge: Discussion Questions’ - Marketing w praktyce — przedyskutuj to
- critical-thinking: Critical Thinking Exercises - Ćwicz myślenie krytyczne
- marketing-plan: Marketing Plan Exercise - Plan marketingowy — ćwiczenia
- company-case: Closing Company Case - A na koniec — studium przypadku

**Comment by wilkus27** [comment]
#### BLOCKED

Waiting for fixes in content. Language in metadata is set to English instead of Polish, so translations are not visible for now.

**Comment by MartaSztuka** [comment]
#### PASSED
#### ToC
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/7514ec77-9eb6-466f-b7ae-8fbca69b360b)
#### Notes
##### Analityka marketingowa
![Zrzut ekranu z 2024-04-18 10-42-52](https://github.com/openstax/cnx-recipes/assets/47241114/4217fe3d-55f3-4811-aeb5-d1b28b608f24)
##### Z doświadczenia marketera
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/2eaea6c2-cbd8-4198-8533-4265545917cc)
##### Etyczna firma
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/c8f0da83-9935-4296-9c89-d4d620a4947e)
##### Sięgnij po więcej
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/0777715b-6246-4ca5-ba6f-b1c057a4940c)
#### EoC
##### Sprawdź wiedzę
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/7be1bd48-9f41-4cb8-b07a-76d6348618db)
##### Podsumowanie rozdziału
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/d8ac6e30-7a20-4962-87df-70dbc8d550a5)
##### Marketing w praktyce — przedyskutuj to
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/d4c28a76-7b3a-4d35-a3f5-4c620db8414e)
##### Ćwicz myślenie krytyczne
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/664bdcaa-ec41-491e-8102-077784dcc5d5)
##### Plan marketingowy — ćwiczenia
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/36301263-70c4-4fe7-bc82-9feb7ef47140)
##### A na koniec — studium przypadku
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/22c8d431-0714-4993-bf6f-cca339fa994e)
