### ISSUE TITLE
Nursing Internal -- PDF -- Broken linking in Critical-Thinking Questions about Case Studies assessments

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5515]
# Summary & Screenshots
In the PDF only, the EoC Critical-Thinking Questions about Case Studies section contains a reference to a previous module like this: Think back to [link]Unfolding Case Study: "Unfolding Case Study #3: Part 4[/link] presented in [Link:Section
17.1]Nutritional Concepts[/link]."

The links to these modules are not working. (The "thinking back" reference doesn't appear at all in web view).
![Screenshot 2024-04-10 at 2 47 15 PM](https://github.com/openstax/cnx-recipes/assets/99201272/9edd4581-4fc1-4438-9f93-3b07552d79cd)

# Sample Mark-Up
```
 <section class="critical-thinking" id="sect-00025">
    <title>Assessment: Critical Thinking Questions about Case Studies</title>
    <exercise id="exer-00009">
    <problem id="prob-00009">
    <para id="para-00073"><link class="os-embed" url="#exercise/17-01-Skills-CT01"/></para>
    </problem>
    </exercise>
    </section>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** clinical-nursing
- **ref/branch:**
- **chapter/section:** Critical Thinking Questions about Case Studies
- **surrounding text:** 

# Acceptance Criteria

## PDF
- fix linking to modules
## Web
- confirm that this feature should not be included on the web view.

**Comment by lwtchu** [comment]
@caylaeagon Does the blue link work? I think the content might not be 100% complete and the bracket links should be removed by WW

**Comment by caylaeagon** [comment]
@lwtchu You right. I just check a more recent PDF and they've already fixed this. Ignore this.
