### ISSUE TITLE
data-science - Python comment stylling in PDF

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5517]
# Summary & Screenshots
Updated with new issues from a comment below...

We've checked the mentioned option and still experiencing formatting issues in the WEB view, there are some colour discrepancy and unwanted formatting display issues. Could you please check and advise? Please find the attached screenshot FYR...
**PDF VIEW:**
![PDF_VIEW1](https://github.com/openstax/cnx-recipes/assets/86622862/1034d396-13a1-4962-94f0-9062fc91a9da)
**WEB VIEW:**
![WEB_VIEW1](https://github.com/openstax/cnx-recipes/assets/86622862/25bb3457-ac63-4da7-ba29-1d5621438550)

# Sample Code
``` <note class="python-feature" id="note-00002">
     <code>
    # from scipy.stats import binom
    from scipy.stats import binom
    
    # define parameters x, n, and p:
    x = 18
    n = 20
    p = 0.92
    
    # use binom.pmf() function to calculate binomial probability
    # use round() function to round answer to 3 decimal places
    round (binom.pmf(x, n, p), 3)
    
    0.271
    </code>
    </note>
```
# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:** Chapter 03/3.5
- **surrounding text:** The round() function is then used to round the probability result to 3 decimal places.

# Acceptance Criteria

## PDF
Previously we styled comments in the python book #5316 to have the comments be grey and italicised. Can we make sure this PDF also has that component. It is correct on the web.

**Comment by lwtchu** [comment]
@srm-openstax I've updated the tagging legend on row 40. Please add `lang="python"` as an attribute.

**Comment by srm-openstax** [comment]
We will check the attribute and get back to you.

**Comment by srm-openstax** [comment]
We recently tried to added the Python feature section as suggested, with the attribute **"lang=python"**. However, it seems that CNXML is not allowing this attribute.

Could you please advise on how we can proceed with this issue?

Please refer the screenshot.

![Python](https://github.com/openstax/cnx-recipes/assets/86622862/04e31d0f-ff15-4053-a0df-a54cf6a56a85)

**Comment by lwtchu** [comment]
@srm-openstax sorry I got confused for a moment due to both of the items being named python. Can you please put the class and lang attribute on the code box per line 44 of the tagging legend?

**Comment by srm-openstax** [comment]
We have coded as per your suggested tagging legend row 44, it seems to only work for PDF view. In the WEB view, there are some color discrepancy and unwanted formatting display issues. Could you please check and advise WEB view is ok?
Kindly refer the below screenshots.

**CNXML:**
![CNXML](https://github.com/openstax/cnx-recipes/assets/86622862/6ff20e15-4034-4861-806d-33c4dbd91fa6)
**PDF VIEW:**
![PDF_View](https://github.com/openstax/cnx-recipes/assets/86622862/52f198a0-b73c-4074-beb7-3b7eed759ba6)
**WEB VIEW:**
![WEB_View](https://github.com/openstax/cnx-recipes/assets/86622862/98af9625-b83b-485a-ad39-d7545fadba8c)

**Comment by lwtchu** [comment]
@srm-openstax We can now update the card to adjust the webview colors as the content is now up to date. Would that be alright with your team?

**Comment by srm-openstax** [comment]
The colour issue in the python code WEB view has been resolved based on the response we received from GitHub. In the WEB view, there are some colour discrepancy and unwanted formatting display issues. Could you please check and advise? Please find the attached screenshot FYR...
**PDF VIEW:**
![PDF_VIEW1](https://github.com/openstax/cnx-recipes/assets/86622862/1034d396-13a1-4962-94f0-9062fc91a9da)
**WEB VIEW:**
![WEB_VIEW1](https://github.com/openstax/cnx-recipes/assets/86622862/25bb3457-ac63-4da7-ba29-1d5621438550)

**Comment by lwtchu** [comment]
@srm-openstax The card has been updated to reflect the new issue for clarity and scheduled for the next sprint.
