### ISSUE TITLE
data science - web - Solution header too big in Example feature section

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5518]
# Summary & Screenshots
We noticed a discrepancy in the text display between the web view and PDF versions. Specifically, in EXAMPLE PROBLEM, we are using row 38 from the tagging legend. However, in the web view, the "Solution" text is displaying much larger than in the PDF, and the word "Problem" seems to have a different font size.
**PDF VIEW:**
![Solution_PDFView](https://github.com/openstax/cnx-recipes/assets/86622862/371a8d8b-ebb1-4e0c-a122-afadcebd0723)
**WEB VIEW:**
![Solution_WEBView](https://github.com/openstax/cnx-recipes/assets/86622862/18df9f80-636e-4a45-b4c9-ca69e221412a)

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:**  https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:** Chapter 03/3.1
- **surrounding text:** Add the 10 data values, and the sum is 748. Divide this sum by the number of data values, which is 10. The

# Acceptance Criteria

## Web
- can we check the headers for solutions in examples for all of the web? Is it a cookbook-specific/web bake step(maybe)?) issue where this is a higher heading level? - i think it should be the same as problem title

**Comment by kswanson33** [comment]
Looks like the problem title is formatted `<p><strong>Problem</strong></p>` while solution is formatted `<h3><span>Solution</span></h3>`.

If the solution were an h4 rather than h3 (with default styles for h4s), it looks a lot better. 

![Image](https://github.com/openstax/cnx-recipes/assets/26280712/00e409ee-b0f7-4550-b71b-88d1be56976e)

A few approaches:
1. Style Problem `<p>` title to have parity with Solution `<h3>`
2. Style Solution `<h3>` to have parity with Problem `<p>`
3. Change Problem `<p>` to header in HTML
4. Change Solution header to `<p>` in HTML

I favor 3 or 4 for the permanence/parallel structure factor. Which would you prefer @lwtchu ?

**Comment by lwtchu** [comment]
@kswanson33 hmmm if we do 3 (since they're titles) is it possible to make them an h4

**Comment by kswanson33** [comment]
@lwtchu bc of the accessibility update, the specific level of header on webview depends on what other headers are present in the page, so that would be hard to make happen in every case. the best way would probably be to make the Problem title a header at the same level as Solution in the content, then shrink them in the styles

**Comment by kswanson33** [comment]
& with the content changing, it may be necessary to update the pdf styles as well to make sure it still looks right

**Comment by kswanson33** [comment]
![Image](https://github.com/openstax/cnx-recipes/assets/26280712/2587ffb7-37bf-4632-8910-27ee8c3eddb0)

Adding a matching `Problem` title is supported in cookbook & easy to turn on. Unfortunately, it creates two titles as pictured above, as well as styling issues (for whatever reason, the `data-type=problem` is styled with `display: table` while `.os-problem-container` is styled with `display: table-cell`).

The second title pictured above appears [in the cnxml](https://github.com/openstax/osbooks-principles-data-science/blob/main/modules/m00021/index.cnxml#L37). 

Two possible paths to solving this are:

## Option 1

1. Take out the Problem title in the content
2. Add the Problem title in cookbook
3. Fix the styling for display & scale the titles to be smaller

(Would have to be careful about merge/release order, but doable).

## Option 2

1. Take out the existing Problem title in cookbook and re-add it the good way
2. Fix styling for display & scale the titles to be smaller

(Fewer places to change, fewer PRs, all changeable by CEDS, but perhaps less preferred to changing the base content?)

**Comment by lwtchu** [comment]
@kswanson33 Will option 1 will that impact all books - I'm thinking about the other web issues in the next sprint regarding the Statistics books. Alternatively - are there other ways the problem/solutions are being handled in examples like in the other science titles?

**Comment by lwtchu** [comment]
@kswanson33 Let me do some digging into all the examples everywhere so we can make sure what do won't impact other books and sets a standard.

**Comment by lwtchu** [comment]
@srm-openstax Can you remove the "Problem" text that is in a paragraph?

**Comment by kswanson33** [comment]
branches:
ce-styles `exercise-problem-title-web`
cookbook `ds-problem-title`

**Comment by Stackblocks** [comment]
The Problem and Solution are now a matched set of h3s (yay a11y compliance) and match in styling. As mentioned above, the extra Problem will be removed in content, and I didn't spot any unexpected changes or irregularities when testing.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/a3cd70a8-ac93-45c5-9b2a-3275727a0677)
