### ISSUE TITLE
data science - pdf - Python code indent issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5519]
# Summary & Screenshots
Python code is not aligned or indented correctly in PDF View in the Python Feature section. Kindly check and resolve this issue.
Here with attached screenshot for your reference.
**Manuscript:**
![manuscript1](https://github.com/openstax/cnx-recipes/assets/86622862/e094ac25-b23f-4761-bedb-243161d8bab9)
![Python(indent-alignment)_PDFView](https://github.com/openstax/cnx-recipes/assets/86622862/d1fc31c6-0ce6-41e3-94c9-fc90a22774da)

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:** Chapter 03/3.5
- **surrounding text:** standard_deviation = 7500

# Acceptance Criteria

## PDF
- we might need to approach this holistically and not do a one off for data science - is this something with highlight.js or something else? after doing some investigation, please get back to me

**Comment by MartaSztuka** [comment]
#### PASSED
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/bdfd8bf8-babc-43f4-9977-4ac4c24628c5)

**Comment by srm-openstax** [comment]
Issue resolved.
