### ISSUE TITLE
Neuroscience: Style "Neuroscience in the Lab" Features

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#5520]
# Summary & Screenshots
Neuroscience in the Lab doesn't seem to be styled, though it has the `in-the-lab` class applied (see markup below):
<img width="647" alt="Screenshot 2024-04-16 at 4 19 40 PM" src="https://github.com/openstax/cnx-recipes/assets/7863733/a0d40fdf-9074-4643-a4db-dda23252d53e">

# Sample Mark-Up
```
<note class="in-the-lab" id="note-00002"><title>Identifying Neural Inducers</title>
  <para id="para-00027">In 1924, Hans Spemann and Hilde Mangold performed <term id="term-00025">transplantation...
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-neuroscience
- **collection slug:** neuroscience
- **ref/branch:** main
- **chapter/section:** multiple; there should be 10 instances spread across the following chapters:  1, 5, 7 (2 instances), 13, 14, 16 (3 instances), 19
- **surrounding text:** "Hans Spemann and Hilde Mangold"...

# Acceptance Criteria

**Comment by lwtchu** [comment]
@openstaxalina It's my b - I can go in and do a mass replace for the class. There's a typo

**Comment by lwtchu** [comment]
![Screenshot 2024-04-18 at 9 40 11 AM](https://github.com/openstax/cnx-recipes/assets/11299125/72effd0a-1f1b-4307-b0ef-5f9a7da776a5)
Fixed w content change

**Comment by openstaxalina** [comment]
thank you Larissa!
