### ISSUE TITLE
Exercise Editor- Solution Box

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5521]
# Summary & Screenshots
Currently, there is only one option available in the exercise editor in the tag field, "Solution is public," to check or uncheck. However, in the manuscript we received, there are multiple questions, detailed solutions, and summaries.
 
We have option to create "multiple contain parts" in the exercise editor. We realized that there is not a separate option to check or uncheck "Solution is public" box for each question and answers.
 
We require the option for summary text should be public or for some summary should not be public. Please check and suggest us.

Kindly check and resolve this issue.
**Manuscript:**
![manuscript](https://github.com/openstax/cnx-recipes/assets/86622862/eca99417-940e-475c-a037-cde0c2e5db94)
![manuscript1](https://github.com/openstax/cnx-recipes/assets/86622862/0cb8320a-b1b9-49a4-a08a-e9aafe0c3b3f)
**Exercise Editor Template:**
![Answerkey1](https://github.com/openstax/cnx-recipes/assets/86622862/9e3c3b8c-8678-4c0d-a8d2-539228515746)
![Answerkey2](https://github.com/openstax/cnx-recipes/assets/86622862/10cca99e-8380-4b1e-905d-374b4fa56c27)
![Answerkey3](https://github.com/openstax/cnx-recipes/assets/86622862/e3b64178-d485-4dcf-b491-de4f96dbb6c6)

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:**  EXERCISES EDITOR /QUANTITATIVE PROBLEMS/DS_Ch03_Sec01_QP1
- **surrounding text:** For Dataset A, calculate the mean and a 10% trimmed mean 

# Acceptance Criteria

**Comment by openstaxalina** [comment]
@srm-openstax - the Summary field is **never** public - the "Solution is Public" field does not apply to it. 

Based on our discussions with Indra reflected in [this document](https://docs.google.com/document/d/1v2M8mjLD7CwvbWKD5zgrzeqBOoiIR7_YcjuWtB6J8Kc/edit#heading=h.30j0zll), Solution is Public should be checked for all Chapter Review and Quantitative Problems, and unchecked for all Critical Thinking questions. 

Please let us know if this resolves the query. cc @lwtchu

**Comment by srm-openstax** [comment]
This ticket will be closed to prevent confusion. For this problem, a new GitHub ticket will be created.
