### ISSUE TITLE
data science - Python Feature Output

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5522]
# Summary & Screenshots
In the “Python Code” feature boxes (Line 40 in tagging legend), could OpenStax add a horizontal rule/line above the Google Colab output (for example, above “0.143”  in the screenshot below), to visually distinguish it, as per the design feedback summary SRM received on 2/9/2024 from OpenStax,?

![image001](https://github.com/openstax/cnx-recipes/assets/86622862/1758b500-fed8-431a-b593-e19c2d11b9a1)

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:** Chapter 03/3.5
- **surrounding text:** function and subtract this area from 1 to then calculate the desired area to the right.

# Acceptance Criteria

**Comment by lwtchu** [comment]
@srm-openstax Hi! For accessibility reasons and ease of screenreader use with code snippets we figured content would be a better way to address this. Please place the paragraph above the code input. This will also be consistent with the way some of the output code text in the Python book

```
<para>The resulting output will look like this:</para>
<code>Add output here</code>
```

**Comment by srm-openstax** [comment]
We have coded as per the tagging instructions provided. However, we are a bit confused about where exactly we should place suggested below yellow highlighted tagging. Could you please advise us on the correct placement?

**<para>The resulting output will look like this:</para>
<code>Add output here</code>**

**CNXML coding:**
![CNXML1](https://github.com/openstax/cnx-recipes/assets/86622862/00c716e6-b484-4a20-9047-489970cd90d3)

Additionally, we cross checking the received design PDF with the CORGI generated PDF, we noticed some discrepancies in the Python code box heading.

We noticed in the design PDF with latest generated PDF. In the heading, it is labeled as "PYTHON FEATURE," but in our latest CORGI generated PDF, it is showing as "PYTHON CODE."

**Design PDF:**
![DesignPDF](https://github.com/openstax/cnx-recipes/assets/86622862/902e2906-2280-41f5-98c1-f023f96852db)

**PDF view:**
![Latest_PDFView](https://github.com/openstax/cnx-recipes/assets/86622862/b0b8a68c-4662-4ffd-ba7a-c6200739acbd)

**Comment by lwtchu** [comment]
@srm-openstax It was requested in the survey to change the Python Feature to Python Code. Would you like to change it back?

The note class sets the box styling and title. 
The class and lang attributes on the code snippet sets the color coding and styling of the code block.

**Comment by srm-openstax** [comment]
Apologies for the confusion, no please do not change the name back. The name should remain “as is” – Python Code.

**Comment by srm-openstax** [comment]
Please find the attached screenshot for this sentence above the number as per per the your suggestion,
0.143 using the coding tags for the sentence as shown in the below screenshot for reference.
**CNXML:**
![CNXML (1)](https://github.com/openstax/cnx-recipes/assets/86622862/fc0680ce-aa38-40db-ab41-1d8f6df1541b)
**PDF_VIEW:**
![PDF_VIEW](https://github.com/openstax/cnx-recipes/assets/86622862/34d63df7-ffdb-489a-82ff-aacf7cd7d702)
**WEB_VIEW:**
![WEB_VIEW](https://github.com/openstax/cnx-recipes/assets/86622862/3595c036-e0fc-4bca-a6f2-7cfa89eed7c5)
