### ISSUE TITLE
The Art of Necromancy - Unarchive Additive Manufacturing

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5523]
Looks like it was done with these PRs/commits for cookbook and ce-styles https://github.com/openstax/cookbook/commit/425100d7c6b7cbc47e2474de9fa20f030e8b0408 
https://github.com/openstax/ce-styles/pull/21

Please unarchive these! I'm not sure how to test :| cause we don't have any content. 

Skim old recipe/styles for major issues and see if we need to open cards to fix.

**Comment by Stackblocks** [comment]
Additive Manufacturing shows up in the output folder and the books section of cookbook, so I'm going to mark this down as a success. Once we get some content I can test further.
