### ISSUE TITLE
Python Text- Inline coding Color

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5527]
We coded as per the tagging legend and also tried row 45 from tagging legend. However, the color does not appear PDF and WEB view. Please check and resolve this issue.

Please refer the below screenshot for your reference.

**CNXML:**
![CNXML](https://github.com/openstax/cnx-recipes/assets/86622862/85ca8ad9-f033-48c0-a339-838914d3e386)

**PDF VIEW:**
![PDF_View](https://github.com/openstax/cnx-recipes/assets/86622862/a3317f28-15df-4aba-890d-e3e7c9d1996d)

**WEB VIEW:**
![WEB_View](https://github.com/openstax/cnx-recipes/assets/86622862/511bbe97-30fa-4e25-b00b-cbf85b74517b)

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:** Chapter 03/3.1
- **surrounding text:** We learned in What Are Data and Data Science? how the 

# Acceptance Criteria

**Comment by lwtchu** [comment]
@srm-openstax You will have to use the `<span class="green-code">` in line 48 for this as small short strings do not provide enough context for the tool to automatically apply color.
