### ISSUE TITLE
[wait for #5518] Statistics and HS Statistics - Spacing issue found in example questions

### ISSUE THREAD

**Issue by osiris001** [openstax/cnx-recipes#5530]
# Summary & Screenshots

![Screenshot 2024-04-25 at 10 29 42 AM](https://github.com/openstax/cnx-recipes/assets/43829253/846da21d-ce78-42c0-95df-fe91fb5d840e)
Spacing issue found in example questions HS Statistics. staging webview is on the left.

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-statistics
- **collection slug:** statistics
- **ref/branch:** main
- **chapter/section:** throughout
- **surrounding text:** 

# Acceptance Criteria

## Web
This might be due to the weird header thing baked step and the weird way the content is constructed in this title.
- Please make the headers be one level smaller 
- Please make sure there's a line break between the words Problem or Solution and the content following it - for some reason it's not working in Bus Stats out right
- Make sure this doesn't compromise other exercises or notes (across library in other places - please target only examples)

## For testing
- Please check HS Stats and regular Stats and Data Science
- Spot check EOC, EOB exercises to make sure they're not compromised

**Comment by lwtchu** [comment]
Also impacts Data Science (https://github.com/openstax/cnx-recipes/issues/5518)

**Comment by kswanson33** [comment]
May be resolved by ce-styles branch `exercise-problem-title-web`

**Comment by lwtchu** [comment]
@Stackblocks could you test just HS and regular stats with that branch for this card

**Comment by Stackblocks** [comment]
Example exercises now have the correct break in them in Intro Stats 2e and HS Stats. I didn't spot anything out of sorts in any of the EOC / EOB problem sections.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/47db71e8-0783-4cca-ae3c-6db63d6493bc)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/5dfe370b-d1be-437d-ba97-435983b22b4e)

**Comment by lwtchu** [comment]
@Stackblocks @kswanson33 yay love a two issue birds and one branch scone type of solution
