### ISSUE TITLE
Change in table sizes in HS Stats

### ISSUE THREAD

**Issue by osiris001** [openstax/cnx-recipes#5531]
# Summary & Screenshots

![Screenshot 2024-04-25 at 11 18 43 AM](https://github.com/openstax/cnx-recipes/assets/43829253/a47065f1-3b8c-4c0a-9d10-8720a7b8b5ac)
![Screenshot 2024-04-25 at 11 18 59 AM](https://github.com/openstax/cnx-recipes/assets/43829253/509a4c13-f156-446d-9ee9-3202bb7db5e7)
![Screenshot 2024-04-25 at 11 09 43 AM](https://github.com/openstax/cnx-recipes/assets/43829253/d431c179-5bfa-40d2-aaa2-37c750e3af67)
![Screenshot 2024-04-25 at 11 20 50 AM](https://github.com/openstax/cnx-recipes/assets/43829253/a573cc3f-0e50-4a5e-b983-e3774eb4a425)

Staging images are on the left. 
Table sizes do not match what is found on prod 
These were found throughout chapter 4. may exist in other chapters.
# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [x] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-statistics
- **collection slug:** statistics 
- **ref/branch:**main
- **chapter/section:** tested throughout chapter 4. possibly in other places
- **surrounding text:** 

# Acceptance Criteria

## Web
If there's nothing in a cell can we add padding?

**Comment by MartaSztuka** [comment]
#### PASSED
![image](https://github.com/openstax/cnx-recipes/assets/47241114/a841c3a6-b9a5-465b-9046-fc6e3e96bbdf)

![image](https://github.com/openstax/cnx-recipes/assets/47241114/63d4ef51-f4ba-44ed-aee9-60af7652922d)

![image](https://github.com/openstax/cnx-recipes/assets/47241114/22e82266-be2b-4f91-bead-4eadfd7ecf9a)
