### ISSUE TITLE
change in exercise number styling in HS Stats

### ISSUE THREAD

**Issue by osiris001** [openstax/cnx-recipes#5532]
# Summary & Screenshots

There is a change in the exercise number styling in HS Stats. They are not showing up bold and are underlined. Staging is on the left side of the screenshot. This is found throughout the text. 
![Screenshot 2024-04-25 at 11 22 29 AM](https://github.com/openstax/cnx-recipes/assets/43829253/8bc19306-106d-417a-8efd-252fd6f8dfc1)

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-statistics
- **collection slug:** statistics
- **ref/branch:** main 
- **chapter/section:** throughout
- **surrounding text:** 

# Acceptance Criteria

## Web
please change back to bold and not underlined

**Comment by MartaSztuka** [comment]
#### PASSED
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/0fac1331-059c-4165-bd83-ca6ac8c20a2f)
