### ISSUE TITLE
Accounting Exercise LO numbers missing space before exercise text

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5533]
The space is gone
# Summary & Screenshots
new on the left
<img width="1053" alt="Screenshot 2024-04-25 at 11 41 10 AM" src="https://github.com/openstax/cnx-recipes/assets/1895432/0ad804d2-2efc-4b88-a4ec-79c120fdae9e">

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** principles-accounting
- **collection slug:** principles-managerial-accounting
- **ref/branch:**
- **chapter/section:** all
- **surrounding text:** Identify the three primary classifications

# Acceptance Criteria

## Web
please add space so the text does not run into numbers

**Comment by MartaSztuka** [comment]
#### PASSED
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/d37876b3-4374-4a9a-bfaf-e156f377a704)

![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/8ca0e353-53c1-4cdc-be4f-434a05587c0f)
