### ISSUE TITLE
Writing Guide appendix bullet-style="none" does not disappear bullets

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5534]
The bullets are there
# Summary & Screenshots

<img width="1387" alt="Screenshot 2024-04-25 at 12 36 41 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/e9867b36-98cf-4bef-8976-2464145212be">

# Sample Mark-Up
```
    <list id="list-00013" list-type="bulleted" bullet-style="none">
    <item><emphasis effect="italics">Forcing the Spring: Inside the Fight for Marriage Equality</emphasis> (book)</item>
    <item><emphasis effect="italics">Judas and the Black Messiah</emphasis> (film)</item>
    <item>“American Military Performance in Vietnam: Background and Analysis” (article)</item>
    </list>
```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [x] Other (Please describe below)
in this appendix 
# Content Location(s)
- **osbooks repo:** osbooks-writing-guide
- **collection slug:** writing-guide
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:** 

# Acceptance Criteria

## Web
can we make sure bullet-style="none" is supported in web styles - and in the appendix, preface, introduction and regular pages

**Comment by caylaeagon** [comment]
Problem also occurs in Intermediate Algebra 2e in the preface (staging left, prod right).
![Screenshot 2024-04-25 at 2 40 31 PM](https://github.com/openstax/cnx-recipes/assets/99201272/7e3b3932-30bf-472e-9872-87acd83e8714)

**Comment by MartaSztuka** [comment]
#### PASSED
##### Writing guide
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/2a2d31e4-48ff-42e2-97d0-55f7e5443e78)
##### Intermediate Algebra 2e
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/d975c5ca-9962-4ac6-935a-10c0a3de51b3)
