### ISSUE TITLE
College Algebra 2e token lists are numbered

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5535]
Oh no numbers
# Summary & Screenshots

New on the left
<img width="1670" alt="Screenshot 2024-04-25 at 12 54 28 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/f0b3344d-c2e0-4f95-a7fd-47cc86378e54">

# Sample Mark-Up
```
<list id="fs-id2631707" list-type="enumerated" number-style="arabic" class="circled">
<item><span class="token">ⓐ</span>As of 1990, average annual income was $23,286.</item>
<item><span class="token">ⓑ</span>In the ten-year period from 1990–1999, average annual income increased by a total of $1,054.</item>
<item><span class="token">ⓒ</span>Each year in the decade of the 1990s, average annual income increased by $1,054.</item>
<item> <span class="token">ⓓ</span>Average annual income rose to a level of $23,286 by the end of 1999.</item></list>
```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-college-algebra-bundle
- **collection slug:** college-algebra-2e
- **ref/branch:** main
- **chapter/section:** Throughout - can be found in Try It 5.1 
- **surrounding text:** 

# Acceptance Criteria

## Web
- Remove numerated list for class="circled" lists. 
- Add space between token and the content
- Token lists should appear in the dev math books also - please check College Algebra first and we can go from there.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Collage algebra
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/7e3bc758-9032-47d8-9e4a-331d66068b09)
