### ISSUE TITLE
Calculo - Exercise numbering below image

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5537]
# Summary & Screenshots
Exercises with images are numbered below the image instead of above it (staging on left, prod on right). 

![Screenshot 2024-04-25 at 1 15 35 PM](https://github.com/openstax/cnx-recipes/assets/99201272/33c73cd3-197b-4ce4-aaad-1dbca786a348)

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [x] Other (Please describe below)
This only occurs in EoC Exercises, NOT in the Answer Key.

# Content Location(s)
- **osbooks repo:** osbooks-calculo-bundle
- **collection slug:** cálculo-volumen-1, cálculo-volumen-2, cálculo-volumen-3
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:** 

# Acceptance Criteria

## Web
- can we make sure the numbering is not underlined and bold (might be fixed via https://github.com/orgs/openstax/projects/40/views/6?pane=issue&itemId=63759421)
- and make sure images are aligned at the top with the number to avoid confusion

**Comment by oscryan** [comment]
Mikroekonomia got bold exercise numbers with no space (staging new on the left)
<img width="1604" alt="Screenshot 2024-04-25 at 4 11 32 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/98e9944a-9bec-4457-bf8a-f9326257391c">

**Comment by kswanson33** [comment]
Specs added:removed `margin-top` from `img`s in solutions

**Comment by kswanson33** [comment]
QA: change is on `fix-solutions-aligment-calculo` on ce-styles

**Comment by MartaSztuka** [comment]
#### PASSED
##### Cálculo 1
![image](https://github.com/openstax/cnx-recipes/assets/47241114/6088eda5-d896-45b2-9140-d8e5316868c3)

##### Cálculo 2
![image](https://github.com/openstax/cnx-recipes/assets/47241114/776e5467-ce94-47df-b5de-ded9c3e7e871)
