### ISSUE TITLE
Psychologia index got unbolded

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#5538]
Polish psychology book font at the end is different, no longer bold
# Summary & Screenshots
staging on the left
<img width="1541" alt="Screenshot 2024-04-25 at 3 39 02 PM" src="https://github.com/openstax/cnx-recipes/assets/1895432/c3924069-768c-4ff2-818c-5041f46b7d46">

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** 
- **collection slug:**
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:** 

# Acceptance Criteria

## Web
I'm not 100% sure if it's a cookbook issue (header levels due to the a11y change) or web styling... might need to discuss

**Comment by osiris001** [comment]
Fizyka Vol 3 also 
![Screenshot 2024-04-25 at 5 33 55 PM](https://github.com/openstax/cnx-recipes/assets/43829253/d34be9e2-3e96-40db-815e-4551fa2d57a3)

**Comment by openstaxalina** [comment]
@wilkus27 will research why the change appeared. @paulinaszczucinska is OK with bold OR non-bold.

**Comment by wilkus27** [comment]
As I checked, when we were moving styles from REX to ce-styles (https://github.com/openstax/cnx-recipes/issues/4853) we didn't add index selectors typical for Polish books, that's why it's not bold.

After discussion with Polish team we decided to keep this as is now.

I'm closing the issue.
