### ISSUE TITLE
Spacing issue found in HS Physics YouTube Video section -- webview

### ISSUE THREAD

**Issue by osiris001** [openstax/cnx-recipes#5539]
# Summary & Screenshots

![Screenshot 2024-04-25 at 12 18 14 PM](https://github.com/openstax/cnx-recipes/assets/43829253/8a0ba051-28bb-4e48-b40d-198b575baa07)
![Screenshot 2024-04-25 at 12 17 56 PM](https://github.com/openstax/cnx-recipes/assets/43829253/8d352bb3-c5ef-490e-8e4e-89687f37a04a)
left is new (staging). 
# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [x] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-physics
- **collection slug:** physics
- **ref/branch:** main
- **chapter/section:** 
- **surrounding text:** 

# Acceptance Criteria

## Web
We should check padding rules for webview before we implement more padding between iframes and their neighbors

**Comment by wilkus27** [comment]
### Information for tester
As I checked, for big elements, like figures, notes etc. we are applying `3rem` top and bottom margins, so this is what I added for iframes.

**Comment by MartaSztuka** [comment]
#### PASSED
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/432c1ab0-5437-4bbb-99cf-04a3bdc80bc9)
