### ISSUE TITLE
Nursing Internal -- Exercises. Link to multiple in-text elements from assessment

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5540]
# Summary & Screenshots
In Exercises, is there a way to link to multiple in-text elements from the assessment question? See screenshot

![image](https://github.com/openstax/cnx-recipes/assets/89537088/d40fe068-cbfe-4857-83b9-e6ef4f8578d2)

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** clinical-nursing
- **ref/branch:** 
- **chapter/section:** Chapter 05; Nickname: 05-01-Skills-CT01
- **surrounding text:** 

# Acceptance Criteria

**Comment by lwtchu** [comment]
@openstaxalina flagged to discuss on Monday meeting

**Comment by openstaxalina** [comment]
@ww-openstax what is the rough frequency of occurrence for this request? there's not currently a way to do this, and our threshold will be fairly high for adding this functionality.

**Comment by ww-openstax** [comment]
@openstaxalina I am checking with the team, but the anticipated frequency of occurrence is very low (like no more than three or four instances). I will report back by Monday.

**Comment by openstaxalina** [comment]
@ww-openstax given the low number of occurrences, we would like you all to implement a content workaround. For these cases only, you can ignore the Element ID field and set the related content as static text. The tradeoff is there will not be a link, however we think it is fine for just these cases. 

Please let us know if you have any questions or concerns.

**Comment by ww-openstax** [comment]
@openstaxalina OK. Got it. There are no more than 3 instances of this. WW editorial team believes they have a workaround for using only one link but good to have the OSX suggested option of static text.

Closing as Resolved
