### ISSUE TITLE
data science - python code feature changes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5541]
![python](https://github.com/openstax/cnx-recipes/assets/11299125/1da8c9de-2bc7-42f7-8817-206441729ccd)
- class: `python-feature`
- change icon to [cardboard-pythonicon.svg](https://drive.google.com/file/d/1EGL76moG4opbG8-Glg3GD4QVneU1N1p0/view?usp=drive_link)

NOTE: This is a new icon. Please ping Larissa if SVG needs adjustments. 

Change color bar to: B4: `#24739E` 
Repo: https://github.com/openstax/osbooks-data-science
Slug: principles-of-data-science

**Comment by MartaSztuka** [comment]
#### PASSED
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/b37f61cb-13eb-4664-8d86-91d1ed4d9420)
