### ISSUE TITLE
data science - monospace font for Python in-line code

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5542]
Python inline code font did not show properly both PDF & WEB view when applying the color. The font per OpenGuide should reflect the below

**For a monospace font (used frequently for code), please use Courier Prime**

Kindly check and resolve this issue.

**PDF VIEW:** 
![PDF_View](https://github.com/openstax/cnx-recipes/assets/86622862/074a0c01-a57c-420a-8ffd-16daeb899515)

**WEB VIEW:**
![WEB_View](https://github.com/openstax/cnx-recipes/assets/86622862/d5b55e5f-55c6-4190-9401-8203de173300)

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:**  Chapter 03/3.1
- **surrounding text:** used as an identifier of each item in the dataset, so the average and mean of this column

# Acceptance Criteria

**Comment by lwtchu** [comment]
@srm-openstax Apologies for the tagging legend not being clear. The span is meant to be used together with the code tag. I've updated the tagging legend `<code><span class="green-code">....</span></code>`

**Comment by srm-openstax** [comment]
Additionally, when we applied the "code" tagging in figure caption. The Python code text moving to its own line. Please check and resolve it.

**PDF view:**
![PDF-view](https://github.com/openstax/cnx-recipes/assets/86622862/ff00814f-5af8-487e-9348-0e0edc33c997)

**WEB view:**
![WEB-view](https://github.com/openstax/cnx-recipes/assets/86622862/acde7693-68b8-4f7d-b8e8-88eaa5161385)

**Comment by lwtchu** [comment]
@srm-openstax Can you add `class="python inline-code"` inline-code also to the class? Thanks

**Comment by srm-openstax** [comment]
As per the suggestion issue has been resolved.
