### ISSUE TITLE
Nursing Internal -- Index -- Symbols -- Tagging for words with quotation marks?

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5543]
# Summary & Screenshots
See screenshot. 
Is there a tagging strategy available so that "madcow" disease is placed under the letter 'M'?
![image](https://github.com/openstax/cnx-recipes/assets/89537088/a8bd3964-e45c-4e35-98f9-f192abcbdc92)

# Sample Mark-Up
```
<para id="para-00010">Commonly mistaken for <term class="no-emphasis" id="term-00025">“madcow” disease</term>, <term id="term-00026">Prion disease (Creutzfeldt-Jakob disease)</term> is a very rare form of dementia, affecting only one to two people per million worldwide in any year. This disease progresses rapidly and leads to death within one year. This disease is considered a transmissible form of spongiform encephalopathy (Centers for Disease Control and Prevention, 2021). This disease is believed to develop spontaneously when normal prion proteins become abnormal
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [x] Other (Please describe below)
Instances of words with quotation marks wrapped in `<term>`
# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** psychiatric-mental-health
- **ref/branch:**
- **chapter/section:** Index; Symbols; Section 14.3; Module m00611; line 81
- **surrounding text:** 

# Acceptance Criteria

**Comment by lwtchu** [comment]
@ww-openstax It's one of the few limitations for the Index - you could start the tagging after the first " but it might look weird. So it depends if you want the first " missing or have it be under Symbols
