### ISSUE TITLE
indent issue for both PDF & WEB View

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5544]
We have followed tagging as per the tagging legend, However we are not  uable to indent the line on our end. Please check and let us know which tag to use to fix this problem?

Here with attached screenshot FYR... 

![image003](https://github.com/openstax/cnx-recipes/assets/86622862/5369a009-8a56-468a-95e7-bb99f986b844)

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:** Chapter 03/3.1
- **surrounding text:** A real estate agent collects data on a sample of recently

# Acceptance Criteria

**Comment by lwtchu** [comment]
@srm-openstax If you're trying to indent the lines, I would suggest marking the `a. b. c. etc` parts as a list as opposed to separate paragraphs.

**Comment by srm-openstax** [comment]
Editorial has opted to leave the data set (numbers) as is and will add a line space above for separation.
