### ISSUE TITLE
data science - pdf - embedded Courier Prime font

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5546]
“Per the suggested fix for ticket 5542 we have applied the "&#60;code&#62;&#60;span class="green-code"&#62;....&#60;/span&#62;&#60;/code&#62;" from the tagging legend.

We have checked the Python green text and noticed that it is not in the embedded Courier Prime font as expected. Instead, it is showing up in the running text font **"Noto Sans"**. Please refer the screenshot for your reference.

![image001](https://github.com/openstax/cnx-recipes/assets/86622862/cf57e667-ac32-4d2c-8ef4-b047302f0e6e)

![image002](https://github.com/openstax/cnx-recipes/assets/86622862/dce3884f-d149-437b-b300-7df67611fae9)

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:** Chapter 3/Section 3.1 
- **surrounding text:** We learned in What Are Data and Data Science? how the

# Acceptance Criteria

## PDF
Can we check where fonts are embedded via prince. This is low priority though

**Comment by Stackblocks** [comment]
Green code now using Courier Prime

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/9939e7b8-ab82-453c-918e-c0cc66aa76da)
