### ISSUE TITLE
data science - pdf - column header row ruler is not supported in Tables

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5547]
Table Column heading row

The blue shading does not extend to the width of the non-shaded cells due to the cell borders. Please refer to the red circles in the screenshot. Could a blue border (matching the header row color) be added to align the width with the table body?

**PDF View:**
![PDF_View](https://github.com/openstax/cnx-recipes/assets/86622862/e1d1624a-6593-441a-bfbd-2329941f1bce)

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:** Chapter 03/3.1
- **surrounding text:**  A college professor records the ages of 25 students in a data science class as shown:

# Acceptance Criteria

## PDF
- is there a way to get the header to encompass the weighted lines if not we can add a border that is the same color as the bg 
- if this impacts the entire theme, that is fine

**Comment by wilkus27** [comment]
### Information for tester

It has an impact on all books from cardboard.

**Comment by Stackblocks** [comment]
It looks like the vast majority of the books impacted (the ones that use #0DC0DC) are working correctly, but Astronomy over there all on its own with #772949 isn't working quite right. 

@wilkus27 Any idea why Astronomy would be behaving differently?



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/d8fc7e4c-c37e-4758-b07a-8373a7866b9c)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/5b66d168-5e31-4efd-bf85-fb28f114b654)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/33562b77-0de6-46f8-95c5-c15b45272ba2)

**Comment by wilkus27** [comment]
@Stackblocks Thank you! Nice catch :wink: I applied wrong background color to border. It's fixed now and ready for retesting.

**Comment by Stackblocks** [comment]
✅ Astronomy's header now shows up with the correct border color. 

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/33f5da9d-c06e-4fbc-8134-e26a8a234ffb)
