### ISSUE TITLE
data science - web - set columns at equal width in examples on web

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5548]
Web View table width

In the web view, the 2nd column of the table is much wider than the first. Could this be changed to equal width as in PDF. The production team attempted various ratio adjustments but saw no change in the outcome.

**WEB View:**
![WEB_View](https://github.com/openstax/cnx-recipes/assets/86622862/7266f94e-35de-45cb-bb1c-cef2ddba04ac)

**Table 3.1:**
![WEB_View1](https://github.com/openstax/cnx-recipes/assets/86622862/7dd8142b-c13d-417f-b270-a334c03ec316)

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:**   https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:**  Chapter 03/3.1
- **surrounding text:** A college professor records the ages of 25 students in a data science class as shown:, customer surveys on the quality of the service of a restaurant,

# Acceptance Criteria

## Web
- enable proportional width settings for tables inside of examples on web

**Comment by MartaSztuka** [comment]
#### PASSED
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/85d7945f-f291-4a7e-889c-b8cd9aab329e)
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/cf75df00-65d6-4cc5-b5d3-11c998764562)
