### ISSUE TITLE
data science - cookbook - remove chapter headers for Group Project 

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5550]
Group Project, which appears at the end of the chapter currently has a hyperlink back to an H1 heading within the chapter. The request is to remove the hyperlink altogether both PDF & WEB View. There is no need for the Group Project to link back to an H1 head within the chapter.

Please check and resolve this issue.

**PDF VIEW:**
<img width="779" alt="image006" src="https://github.com/openstax/cnx-recipes/assets/86622862/86e567aa-592d-4383-bd3d-a623389d6782">

**WEB VIEW:**
![image004 (1)](https://github.com/openstax/cnx-recipes/assets/86622862/ac9199d9-4d9c-4c31-857d-34872455e141)

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:**  Group Project Section
- **surrounding text:** There are many sources of salary data where median salaries for a certain year are published by gender

# Acceptance Criteria

## PDF & Webview
Header should disappear for both instances of PDF/Web for the Group Project

**Comment by MartaSztuka** [comment]
#### PASSED
##### PDF
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/4a176647-aa59-4e62-ae31-f6d7061bf669)

##### webview
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/5d0f7d3f-deb5-47ea-bcfc-d22885f33f16)
