### ISSUE TITLE
Nursing Internal -- add to colwidth proportional values

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5551]
# Summary & Screenshots
In psychiatric-mental-health, there are five instances of tables that would benefit from an adjustment in column width. 
The five tables and their locations in [this PDF linked here](https://openstax-cops-artifacts.s3.amazonaws.com/openstax-osbooks-nursing-internal-bundle-7f38ad5027a2715ca716bc1f257dcb4f2cc68552-11640-psychiatric-mental-health.pdf) are listed below.

Table 15.3  -- PDF page 461; folio page 453 -- proportions needed 1*,2*,1*,1*
Table 15.5 -- PDF page 463; folio page 455 -- proportions needed 1*,2*,2*
Table 25.1 -- PDF page 856; folio page 848 -- proportions needed 1*,8*,8*
Unnumbered table -- PDF page 968; folio page 960   -- proportions needed 1*,2*,2*
Unnumbered table -- PDF page 969; folio page 961  -- proportions needed 1*,2*,2*

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [x] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** psychiatric-mental-health
- **ref/branch:**
- **chapter/section:** see list in summary above
- **surrounding text:** 

# Acceptance Criteria

## PDF & WEB
Please enable these proportions. We've done it in the past in various capacities: #5305 #5512 

PDF is higher priority - if that PR goes first, that's fine. Web can follow after. If that is the case I can open a separate card.

**Comment by ww-openstax** [comment]
Additional colwidth values needed for Clinical Nursing Skills and Maternal Newborn Nursing

Maternal Newborn Nursing
Table 7.3 -- proportions needed 1*,2*,2*,2*,2*
Table 7.6 -- proportions needed 1*,2*,2*,2*,2*
Table 11.5 -- proportions needed 1*,1*,2*,2*
Table 13.7 -- proportions needed 1*,3*
Table 18.1 -- proportions needed 1*,3*
Table 18.12 -- proportions needed 1*,2*,2*
Table 20.4 -- proportions needed 1*,2*,2*,2*
Table 23.2 -- proportions needed 1*,2*,2*

Clinical Nursing Skills
Table 5.2 -- proportions needed 1*,3*
Table 8.4 -- proportions needed 1*,2*,2*
Table 9.3 -- proportions needed 1*,2*
Table 9.5 -- proportions needed 1*,2*
Table 9.7 -- proportions needed 1*,2*
Table 10.4 -- proportions needed 1*,2*
Table 10.7 -- proportions needed 1*,2*
Table 13.1 -- proportions needed 1*,2*,2*,2*
Table 16.3 -- proportions needed 1*,3*,2*
Table 16.4 -- proportions needed 1*,2*,2*,2*
Table 18.3 -- proportions needed 1*,2*,2*,2*
Table 18.4 -- proportions needed 1*,3*,3*
Table 18.5 -- proportions needed 1*,3*,3*
Table 19.5 -- proportions needed 1*,2*,2*,2*
Table 19.6 -- proportions needed 1*,2*,2*,2*
Table 19.7 -- proportions needed 1*,2*,2*
Table 22.2 -- proportions needed 1*,2*,2*,2*
Table 24.3 -- proportions needed 1*,3*
Table 24.5 -- proportions needed 1*,2*,2*
Table 24.10 -- proportions needed 1*,2*,2*,2*
Table 25.1 -- proportions needed 1*,3*
Table 25.2 -- proportions needed 1*,3*
Table 25.3 -- proportions needed 1*,3*

Note: all colwidth values have already been entered in the XML
```
    <table summary=" " id="table-00003">
    <title>Sample PQRSTU Focused Questions</title>
    <tgroup cols="2">
    <colspec colnum="1" colname="c1" colwidth="1*"/>
    <colspec colnum="2" colname="c2" colwidth="3*"/>
    <thead>
```

**Comment by lwtchu** [comment]
@jbwilson8 i will open a separate card after you're done with the initial request

**Comment by Stackblocks** [comment]
## PDF
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/5b4d36f7-f661-4bf5-a95c-9214eb8db1eb)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/464a98fd-928d-4623-b926-47e2072c4581)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/eed10fb4-b3e6-49a6-9138-eb4383b00d45)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/1566eee4-888c-42e6-aadf-d561e3b0ebe0)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/3516a181-e3ac-4840-ab64-98b3b5a9bca1)

## Web
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/3f2c7618-de95-4d6e-a2da-2bdef39e9b3b)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/0313ba1d-a2f8-45dc-946e-6cee8617edca)

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/e98a36f9-6dbd-436c-9cad-f06312f8bdb8)
