### ISSUE TITLE
Number list Indentation

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5552]
We noticed when reviewing the PDF view of the document. The numbered list's indentation appears to be aligned to the left, whereas in the WEB view it is correctly indented.
 
Please look at this and correct the indentation in the PDF.

**PDF View:**
![PDF_View](https://github.com/openstax/cnx-recipes/assets/86622862/b595bff6-dd1c-4485-87e7-dcb8f4fb48c0)

**WEB View:**
![WEB_View](https://github.com/openstax/cnx-recipes/assets/86622862/32d7e147-bc9d-42e8-9980-2355075382b3)

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:**  Chapter 03/ Section 3.1
- **surrounding text:** A real estate agent collects data on a sample of recently sold homes

# Acceptance Criteria

**Comment by lwtchu** [comment]
@srm-openstax The web and pdf won't have a 100% match. We will not fix this as this is standard in the PDF for space saving reasons

**Comment by srm-openstax** [comment]
Thank for your information.

**Comment by srm-openstax** [comment]
thanks for your information
