### ISSUE TITLE
data science - pdf - Font size for header "Solution"

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5556]
After the code update to issue 5518, the font size is correctly displayed for both headers, "Problem" and "Solution," in the WEB view version. However, in the PDF view, the header “Solution” does not have the same font size. 

# Summary & Screenshots
**WEB View:**
![Web view](https://github.com/openstax/cnx-recipes/assets/86622862/361200d3-4930-4b7f-b1f6-5a708afdbedd)

**PDF view:**
![PDF VIEW](https://github.com/openstax/cnx-recipes/assets/86622862/6883e02f-4ba4-4bbb-bb33-f759334ac1a1)

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:**Principles-data-science
- **ref/branch:**https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:** Chapter 3/ Example 3.1
- **surrounding text:** this reduces to the previous formula given for the sample mean.

# Acceptance Criteria

## PDF
This might've been missed when we were adjusting the header schema in the HTML - can we make sure problem and solution both get the same styling

**Comment by kswanson33** [comment]
branch: ce-styles `problem-title-example`

impacts data science, astronomy, python (pdf only)
