### ISSUE TITLE
data science - pdf - code in figure caption not base aligning

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5559]
In the PDF view, the Python code within a figure caption does not align with the surrounding text.

**PDF View:**
![PDF_View1](https://github.com/openstax/cnx-recipes/assets/86622862/3c7d0615-fd1c-42b7-9916-f5acda1c2696)

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:** Chapter 03/Section 3.2
- **surrounding text:** standard deviation as well on each column of a dataset. The std lists the

# Acceptance Criteria

## PDF
- likely line height hasn't been adjusted for the font change/style for code in captions. please make the adjustments so that it aligns with the rest of the text

**Comment by lwtchu** [comment]
@openstaxalina Cayla found some mark up issues - we might have to wait for those fixes but it can be up to you!

**Comment by wilkus27** [comment]
@openstaxalina I'm not sure what should be fixed :thinking: From the code side everything looks good, normal text and green code have the same font size and line height. Differences in height of the specific letters might appear because there are two different fonts, but alignment looks pretty good to me still :eyes: 

![image](https://github.com/openstax/cnx-recipes/assets/40228854/1fe87dc6-fd3d-4d5b-82d4-c35576a2766e)

Am I missing something? :smile:

**Comment by openstaxalina** [comment]
On the call Natalia showed how her local PDF looks different from the PDF in the original screenshot. The alignment is better in Natalia's local PDF.

I reviewed the latest PDF (from 7 minutes ago) on CORGI, and the code text is up higher than the surrounding text when viewed in browser, Adobe Acrobat, and Preview -- just like the original screenshot.

To delve into this mystery, @kswanson33 and @jbwilson8 will generate Data Science locally and let us know what the Figure 3.2 caption looks like for y'all.

**Comment by wilkus27** [comment]
@openstaxalina I checked webview version on CORGI and realised that I have different content version locally. Sorry for the confusion :see_no_evil: 

So previously, there was just a span with class `green-code`. Now, we have a `pre` code element that contains this span

![image](https://github.com/openstax/cnx-recipes/assets/40228854/04e6b94f-8bb3-4f1d-b191-aef0c3b0ee59)

It's not a proper structure. Code elements should contain only code. On a prebake step highlight.js recognise what type of code it is and wrap it up with span with proper class. So we need a content change.

But probably also some styles change will be needed, when content is ready.

**Comment by kswanson33** [comment]
![Image](https://github.com/openstax/cnx-recipes/assets/26280712/4708f31d-1837-4dd3-851b-920fe424cdfa)

This is what I get with local enki, updated submodules (to latest tagged version, not latest on `main`). Is there a different version I should be using?

**Comment by wilkus27** [comment]
@kswanson33 I fetched a new version again today, to make sure nothing changed over the weekend, and for me code is green

![image](https://github.com/openstax/cnx-recipes/assets/40228854/f307f96b-e961-45b2-8d13-aa40f84b0b9d)

I did the same thing as you (update enki with submodules). On ce-styles I'm on the sha `c02deb5fb`

**Comment by openstaxalina** [comment]
@srm-openstax please update the tagging to use `<code>` elements, not `<pre>`, per the [tagging legend row 48 for setting green code](https://docs.google.com/spreadsheets/d/1rnXWjQYUHqs5h0KIr3nDtMJHofK4ZFrWQfhK6VzPrp4/edit#gid=0). Please re-test and confirm whether this resolves the display issue.

**Comment by wilkus27** [comment]
@openstaxalina I'm not very familiar with xml, but I remember that previously there were some problems with adding `<code>` tag, sometimes it has to be `<pre>` tag (I think in tables mostly :thinking: ). So I'm assuming that it might be the case also for `<caption>`. In my previous comment I meant to remove span with class `green-code`. `<code>` or `<pre>` should contain only text, in this case `DataFrame.describe()`.

**Comment by wilkus27** [comment]
@openstaxalina It moves to the next line, because it's transformed into `<pre>` anyway:

![image](https://github.com/openstax/cnx-recipes/assets/40228854/6d23002d-495c-4b7b-ae7b-75fd15d9d17f)

but now whithout `inline-code` class. 

I'm wondering why there is an information in tagging legend to put span inside `<code>` or `<pre>`. We don't need this for setting styles in PDF and webview. Is it possible that this form is necessary on other platforms?

**Comment by openstaxalina** [comment]
@wilkus27 the `<span>` is allowed so the vendor can manually set colors (e.g. `green-code`) on small snippets of code. 

@srm-openstax can you remove the class `python` and **leave** the class `inline-code`?

**Comment by srm-openstax** [comment]
@openstaxalina: The SRM team has followed the GitHub suggestion, but the original issue of the alignment was not resolved with the suggestion. Please see the screenshot.

CNXML:
![CNXML](https://github.com/openstax/cnx-recipes/assets/86622862/0a973dcd-7cb9-4369-ae68-3410718b4d20)

Output PDF:
![img1](https://github.com/openstax/cnx-recipes/assets/86622862/be20ea96-a2b4-4d60-8f71-d529b6878d27)

**Comment by openstaxalina** [comment]
thank you @srm-openstax. I am re-assigning this to @wilkus27 . Since she is out the rest of this week, this issue will slide to the next sprint.

**Comment by MartaSztuka** [comment]
#### PASSED
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/2dd31260-8e52-4dc6-b7a2-b915ff436875)
