### ISSUE TITLE
Data Science - update color for table and figure captions

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#5560]
# Summary & Screenshots
In the first produced chapter review, editorial noted the color for table and figure captions is very light. While the issue was noted specifically for tables and figures in shaded feature boxes, for simplicity we will update the color for all table and figure captions. 

This will affect the entire Cardboard theme.

Per https://github.com/openstax/cnx-recipes/issues/2643, current color is: Grey2: `#757474`

The new color will be: Grey 5: `#5C5C5C`

# Sample Mark-Up
```
<table>
... 
<caption>Result of Three Random Coin Flips</caption>
    </table>

---

<figure>
 <caption>Poisson Distribution for <m:math><m:mi>µ</m:mi><m:mo>=</m:mo><m:mn>7</m:mn></m:math></caption>
    </figure>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** principles-data-science
- **ref/branch:** main
- **chapter/section:** multiple
- **surrounding text:** see markup samples above

# Acceptance Criteria

## PDF
- [ ] figure captions have color value `#5C5C5C`
- [ ] table captions have color value `#5C5C5C`
- [ ] Alina to update documentation card (linked above) with final color and screenshot
[unsure if I should include testing of other books in the theme / any regression testing? to discuss Monday]

**Comment by MartaSztuka** [comment]
#### PASSED
##### Figure
![Zrzut ekranu z 2024-06-10 16-21-41](https://github.com/openstax/cnx-recipes/assets/47241114/1469f822-db68-4721-a5f6-559e5706f343)
##### Table
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/4e1f0871-19e5-4879-aa2c-886110b765de)
