### ISSUE TITLE
Nursing internal - add colwidth proportional values - Clinical Skills & Maternal-Newborn

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#5561]
# Summary & Screenshots

This is the same work that was done for #5551 except for 2 other books:

Additional colwidth values needed for Clinical Nursing Skills and Maternal Newborn Nursing

Maternal Newborn Nursing
Table 7.3 -- proportions needed 1*,2*,2*,2*,2*
Table 7.6 -- proportions needed 1*,2*,2*,2*,2*
Table 11.5 -- proportions needed 1*,1*,2*,2*
Table 13.7 -- proportions needed 1*,3*
Table 18.1 -- proportions needed 1*,3*
Table 18.12 -- proportions needed 1*,2*,2*
Table 20.4 -- proportions needed 1*,2*,2*,2*
Table 23.2 -- proportions needed 1*,2*,2*

Clinical Nursing Skills
Table 5.2 -- proportions needed 1*,3*
Table 8.4 -- proportions needed 1*,2*,2*
Table 9.3 -- proportions needed 1*,2*
Table 9.5 -- proportions needed 1*,2*
Table 9.7 -- proportions needed 1*,2*
Table 10.4 -- proportions needed 1*,2*
Table 10.7 -- proportions needed 1*,2*
Table 13.1 -- proportions needed 1*,2*,2*,2*
Table 16.3 -- proportions needed 1*,3*,2*
Table 16.4 -- proportions needed 1*,2*,2*,2*
Table 18.3 -- proportions needed 1*,2*,2*,2*
Table 18.4 -- proportions needed 1*,3*,3*
Table 18.5 -- proportions needed 1*,3*,3*
Table 19.5 -- proportions needed 1*,2*,2*,2*
Table 19.6 -- proportions needed 1*,2*,2*,2*
Table 19.7 -- proportions needed 1*,2*,2*
Table 22.2 -- proportions needed 1*,2*,2*,2*
Table 24.3 -- proportions needed 1*,3*
Table 24.5 -- proportions needed 1*,2*,2*
Table 24.10 -- proportions needed 1*,2*,2*,2*
Table 25.1 -- proportions needed 1*,3*
Table 25.2 -- proportions needed 1*,3*
Table 25.3 -- proportions needed 1*,3*

**Note: all colwidth values have already been entered in the XML**

# Sample Mark-Up
```
    <table summary=" " id="table-00003">
    <title>Sample PQRSTU Focused Questions</title>
    <tgroup cols="2">
    <colspec colnum="1" colname="c1" colwidth="1*"/>
    <colspec colnum="2" colname="c2" colwidth="3*"/>
    <thead>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [x] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** maternal-newborn-nursing, clinical-nursing or clinical-nursing-skills 
- **ref/branch:** main
- **chapter/section:** see list in summary above
- **surrounding text:** varies but can search based on table number

# Acceptance Criteria

## PDF & Web
- [ ] the designated proportions are reflected in the display

**Comment by openstaxalina** [comment]
@jbwilson8 please add points when you get the chance, then this can be moved to Backlog. thank you!

**Comment by openstaxalina** [comment]
@omehes would you be available to test this? (Sztuka is out through Monday.) cc @Brooke-Fail

**Comment by omehes** [comment]
testing:

Maternal Newborn Nursing
Table 7.3 -- proportions needed 1*,2*,2*,2*,2* - incorr
Table 7.6 -- proportions needed 1*,2*,2*,2*,2* - incorr
![Image 6-14-24 at 11 33 AM](https://github.com/openstax/cnx-recipes/assets/44207656/f74c8dea-1982-415b-870c-412bf750cec6)
![Image 6-14-24 at 11 31 AM](https://github.com/openstax/cnx-recipes/assets/44207656/dbbe7eff-4b00-4330-8766-39ba0e504316)

**Comment by omehes** [comment]
Retest after fixes and changes to test process:
1st book - all tables ok, only 11.5 is incorrect - fixed
2nd book - all tables OK, only table 9.3, 9.5, 9.7, 10.4, 10.7 look more like 2, 3 than 1,2 -
