### ISSUE TITLE
Lifespan -- Feature box contains incorrect title

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5564]
# Summary & Screenshots
Title of the feature box "Intersections and Contexts" is showing up incorrectly as "Intersections and Context" (singular)

![Screenshot 2024-06-06 at 17 06 12](https://github.com/openstax/cnx-recipes/assets/89537088/4acae61c-05d6-4cb1-890a-687742a5c3ca)

Tagging in XML is correct. 

# Sample Mark-Up
```
<note class="intersections-contexts">
```

# Issue Occurrence(s)

 **Location**
- [X] In PDF
- [X] In Web

**Frequency**
- [X] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-lifespan-development
- **collection slug:**
- **ref/branch:**
- **chapter/section:** Chapter 6
- **surrounding text:** 

# Acceptance Criteria

## PDF
- [ ] add an "s" on "context" so the title reads "Intersections and Contexts"

## Web - let me know if we need a separate card for web!
- [ ] add an "s" on "context" so the title reads "Intersections and Contexts"

**Comment by kswanson33** [comment]
QA: the changes for this update are on cookbook branch `fix-locale-ld`

**Comment by MartaSztuka** [comment]
#### PASSED
##### PDF
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/de40cf46-7720-465c-b460-b4f4ca4e15ae)

##### webview
![Zrzut ekranu z 2024-06-19 11-12-11](https://github.com/openstax/cnx-recipes/assets/47241114/cb075fda-e4a6-4184-97b1-1da004f3458a)
