### ISSUE TITLE
Lifespan -- References section not collating correctly

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5565]
# Summary & Screenshots
The References section is not collating correctly at the end of the chapter. (ISSUE 1) And it looks like the correct tagging is missing from the tagging legend. (ISSUE 2)

**ISSUE 1: Location and appearance of the References section**
The References section SHOULD:
- appear at the end of each chapter, after all of the other end-of-module content (Summary, Key Terms, Assessments, etc.).
- contain linkable section headers dividing all of the references up by module
- automatically collate from each module into one large list at the end of the chapter (exactly like the Summary section).
- appear in the TOC along with the other EOC content

It currently:
- is appearing directly at the end of the chapter immediately after the chapter content, before the Summary section
- does not contain linkable section dividers
- is missing from the TOC

AS IT CURRENTLY APPEARS (INCORRECT):
![Screenshot 2024-06-06 at 17 26 36](https://github.com/openstax/cnx-recipes/assets/89537088/c1ef9d3d-12ef-4122-b3f3-a1a4732b1fe7)

AS IT APPEARED IN THE KITCHEN SINK (CORRECT):
![Screenshot 2024-06-06 at 17 27 49](https://github.com/openstax/cnx-recipes/assets/89537088/fd36cf0c-07b5-4fb8-9e3f-c2067e5b0bda)

**ISSUE 2: Tagging legend**
The tagging legend appears to contain tagging for the References section as an Appendix at the end of the chapter. This is not the desired output; it should appear at the end of each chapter. I believe our production team tried to tag the References section like they did for Nursing, which also has an EOC References section, but because that tagging did not exist for this title, the References section did not collate or appear properly.

# Sample Mark-Up
In Tagging Legend:
```
"<section class=""indent-container"">
  <para> ... </para>
</section>"
```
In XML:
```
 <section class="references" id="sect-00009">
      <title>References</title>
      <section id="sect-00010">
        <title>Social and Emotional Development</title>
          <para id="para-00023">American Psychiatric Association. (2022).
...
</section>
    </content>
```

# Issue Occurrence(s)

 **Location**
- [X] In PDF
- [X] In Web

**Frequency**
- [X] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-lifespan-development
- **collection slug:**
- **ref/branch:**
- **chapter/section:** Chapter 6
- **surrounding text:** 

# Acceptance Criteria

## PDF
- [ ] references appear at the end of each chapter, after all of the other end-of-module content (Summary, Key Terms, Assessments, etc.).
- [ ] the References section contains linkable chapter-section headers dividing all of the references up by module
- [ ] appear in the TOC along with the other EOC content

## Web - let me know if you need a separate card for web
- [ ] same as the a/c under "PDF"

**Comment by openstaxalina** [comment]
@ww-openstax I've updated the [tagging legend](https://docs.google.com/spreadsheets/d/1gcDW_NeptLKUE53kT9s5aDfjM1LSdlwdyXNfSzaDmNY/edit#gid=0) (row 51) with instructions for marking up references. Currently the references are all sitting at the end of the last chapter-section, which was correct for nursing but is not correct for Lifespan. Can the production team please move each chapter-section's references to the end of that chapter-section instead of all in the final chapter-section? And they should set the `<title>` as "References" rather than the chapter-section title. Please then re-test and see if this produces the desired result. Thank you!

**Comment by ww-openstax** [comment]
@openstaxalina We moved the references to the end of each module/section and tagged as below.
The references are NOT collating at the end of the chapter and instead are [outputting at the end of each section](https://openstax-cops-artifacts.s3.amazonaws.com/openstax-osbooks-lifespan-development-c216e9135ca709049c890175695d386a155246af-12155-lifespan-development.pdf). 
The desired output is for the references to collate at the end of the chapter as shown in the screenshot above as it appeared in the kitchen sink     
```
    </exercise>
    </section>

    <section class="references" id="sect-0015">
      <title>References</title>
          <para id="para-023">American Psychiatric Association. (2022). ....</para>
          <para id="para-024">Autistic Self Advocacy Network (n.d.). ...</para>
          <para id="para-025">Behavior Analyst Certification Board. (2020). ...</para>
    </section>
    </content>
    <glossary>
    ...
   </glossary>
   </document>

```

**Comment by openstaxalina** [comment]
thank you @ww-openstax -- we'll look into this during the sprint starting next week.

**Comment by kswanson33** [comment]
QA: the changes for this update are on cookbook branch `references-ld`

**Comment by MartaSztuka** [comment]
@kswanson33 References looks ok, but shouldn't lines after the first one be indented?
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/df7d7e18-1a5b-4267-8df7-7e7890b3ee4e)

**Comment by kswanson33** [comment]
thanks! pls test with additional PR ce-styles `refs-ld`

**Comment by MartaSztuka** [comment]
#### PASSED
![obraz](https://github.com/openstax/cnx-recipes/assets/47241114/9325a3d1-9801-489d-8da1-28342304252f)
