### ISSUE TITLE
Nursing Internal -- Missing vertical rule from table

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5566]
# Summary & Screenshots
Missing vertical rule from table
![image](https://github.com/openstax/cnx-recipes/assets/89537088/c47dd72b-082b-454f-9487-8a9b9d37a56f)

# Sample Mark-Up
```
<row valign="top">
    <entry valign="top" align="left">Pronation</entry>
    <entry valign="top" align="left">Movement of the forearm so the hand faces backward</entry>
    </row>
    <row valign="top">
    <entry valign="top" align="left">Dorsiflexion</entry>
    <entry valign="top" align="left">Movement of the ankle joint so the top of the foot moves toward the front of the leg</entry>
    <entry valign="top" align="left" morerows="1">These movements are specific to the ankles; they are the only movements of the ankle joints.</entry>
    <entry valign="top" align="left" morerows="1">
    <figure id="fig-00016" class="unnumbered">
    <media alt="Diagram showing dorsiflexion and plantar flexion of ankle">
    <image mime-type="image/jpeg" src="../../media/OSX_Fund_22_01_dorsiplant_img.jpg"/>
    </media>
    <caption>(credit: modification of work from <emphasis effect="italics">Anatomy and Physiology 2e</emphasis>. attribution: Copyright Rice University, OpenStax, under CC BY 4.0 license)</caption>
    </figure></entry>
    </row>
```

# Issue Occurrence(s)

 **Location**
- [X] In PDF
- [X] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [X] Other (Please describe below)
Happens when there is a column that spans multiple rows

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** fundamentals-nursing
- **ref/branch:**
- **chapter/section:** Chapter 22/Section 22.1/Table 22.3
- **surrounding text:** 

# Acceptance Criteria

**Comment by openstaxalina** [comment]
@ww-openstax can you please put in the markup for the table from the screenshot?

**Comment by ww-openstax** [comment]
@openstaxalina Here is the markup: 

```
<row valign="top">
    <entry valign="top" align="left">Pronation</entry>
    <entry valign="top" align="left">Movement of the forearm so the hand faces backward</entry>
    </row>
    <row valign="top">
    <entry valign="top" align="left">Dorsiflexion</entry>
    <entry valign="top" align="left">Movement of the ankle joint so the top of the foot moves toward the front of the leg</entry>
    <entry valign="top" align="left" morerows="1">These movements are specific to the ankles; they are the only movements of the ankle joints.</entry>
    <entry valign="top" align="left" morerows="1">
    <figure id="fig-00016" class="unnumbered">
    <media alt="Diagram showing dorsiflexion and plantar flexion of ankle">
    <image mime-type="image/jpeg" src="../../media/OSX_Fund_22_01_dorsiplant_img.jpg"/>
    </media>
    <caption>(credit: modification of work from <emphasis effect="italics">Anatomy and Physiology 2e</emphasis>. attribution: Copyright Rice University, OpenStax, under CC BY 4.0 license)</caption>
    </figure></entry>
    </row>
```

**Comment by openstaxalina** [comment]
@yblock could you review the markup above to verify this isn't a content issue?

**Comment by yblock** [comment]
Funny, I just took a screenshot of other places where this is happening to open a card for it later and hadn't checked if it was already reported yet! It's not content, it's something to do with how text overflows in a cell when there is an image nearby. There are many cases of it in the big tables throughout the text.

**Comment by openstaxalina** [comment]
thank you - putting this in CE DS's next sprint

**Comment by MartaSztuka** [comment]
#### PASSED
##### PDF
![image](https://github.com/openstax/cnx-recipes/assets/47241114/40e30509-a7a4-4a01-bc2b-88626fdaa381)

##### webview
![image](https://github.com/openstax/cnx-recipes/assets/47241114/b31eb01f-4f18-4d2a-b548-726de390cc8e)
