### ISSUE TITLE
osbooks-introduction-computer-science > introduction-computer-science > CORGI ERROR

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5568]
# Summary & Screenshots
When generating a PDF or Webview within Corgi we get an job ERROR.  See Corgi for error.

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [x ] In PDF
- [x ] In Web

**Frequency**
- [x ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-introduction-computer-science 
- **collection slug:** introduction-computer-science
- **ref/branch:**
- **chapter/section:**  Chapter 03
- **surrounding text:** 

# Acceptance Criteria

**Comment by openstaxalina** [comment]
@ww-openstax for CORGI errors, please open a Work Stoppage issue by emailing wisewire@openstax.org
