### ISSUE TITLE
computer science - table of contents should not have a numbered list

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5570]
# Summary & Screenshots
TABLE CONTENT NUMBER LIST SHOULD NOT BE OUTPUTING
![ComputerSci_TableContent_Numbering_issue](https://github.com/openstax/cnx-recipes/assets/89537088/0077e09a-2cdc-4cf4-b76b-824fe0a2e63a)

# Sample Mark-Up
```
N/A built automatically
```

# Issue Occurrence(s)

 **Location**
- [X ] In PDF

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-introduction-computer-science
- **collection slug:** introduction-computer-science
- **ref/branch:**
- **chapter/section:** Table of Contents 
- **surrounding text:** 

# Acceptance Criteria

## PDF
- [ ] Table of Contents design should look like this (pulled from Preparing for College Success which is also in the cardboard theme)

![Screenshot 2024-06-18 at 4 22 38 PM](https://github.com/openstax/cnx-recipes/assets/7863733/ab6a7e06-ba1b-489b-a692-9c6fefd6e773)

**Comment by openstaxalina** [comment]
@ww-openstax can you please fill in the information under 
## Content Location(s)
?

**Comment by openstaxalina** [comment]
meanwhile @yblock can you please take a peek in the repo and make sure there's nothing weird going on with markup? I think it would be in the module title and/or collection tree

**Comment by openstaxalina** [comment]
Update: issue does **not** occur in [web preview](https://rex-web-production.herokuapp.com/books/4f06ce31-1d04-410f-8328-ac4e02c4f217@a4aa1ae/pages/1-2-algorithm-design-and-discovery?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20240618.142006)

**Comment by yblock** [comment]
markup looks normal to me

**Comment by ww-openstax** [comment]
@openstaxalina - Information has been updated.

**Comment by openstaxalina** [comment]
This title has units. @ww-openstax is going to add at least one unit (can be a placeholder title) so the book structure in POET/GitHub matches expectations. Re-test the PDF and let us know if the numbered list is gone.

**Comment by ww-openstax** [comment]
@openstaxalina - We added the unit as you had suggested.  Please see the attached screenshot. All looks good on our end. 

![image](https://github.com/openstax/cnx-recipes/assets/89537088/a0138fe8-d9c7-4af8-8e90-463426e0aaab)

**Comment by omehes** [comment]
tested in released n.n - OK
