### ISSUE TITLE
Information Systems: table of contents should not have a numbered list - remove support for units?

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5572]
### This title does not have units. Jenn or Kendra when you look at this, can you see if the code is expecting units?

# Summary & Screenshots
Table of Content Numbering list should not be outputting.
![Info_Sys_TOC_number_list_should_not_output](https://github.com/openstax/cnx-recipes/assets/89537088/4c247f40-b651-4503-9bfc-f17153dce353)

# Sample Mark-Up
```
N/A built automatically

```

# Issue Occurrence(s)

 **Location**
- [X] In PDF
- [ ] In Web

**Frequency**
- [X] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-foundations-information-systems
- **collection slug:** foundations-information-systems
- **ref/branch:**
- **chapter/section:** Table of Contents
- **surrounding text:** 

# Acceptance Criteria

## PDF
- [ ] no numbered list
- [ ] it should look like this (example from College Success in the same theme)

![ToCInfoSys](https://github.com/openstax/cnx-recipes/assets/7863733/18094fe0-d235-4958-b235-a0aa5655d925)

**Comment by kswanson33** [comment]
to QA: pls test on `toc-infosys`

**Comment by omehes** [comment]
tested on ce-styles branch: toc-infosys
looks good

![Image](https://github.com/user-attachments/assets/f8c646a8-8ed0-4c2e-bf00-8beb1abd5806)

**Comment by omehes** [comment]
tested on corgi - ok
