### ISSUE TITLE
Computer Science - make learning objectives unnumbered

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5574]
Note from Alina: we made the same change here for another title in the cardboard theme: https://github.com/openstax/cnx-recipes/issues/5056

# Summary & Screenshots

Per Editorial, LOs should be a bulleted listed, NOT numbered as shown below:

![Screenshot 2024-06-24 084219](https://github.com/openstax/cnx-recipes/assets/89537088/897ceb98-5ec4-4b20-a10d-bdc3d628452e)

# Sample Mark-Up
```
<section class="learning-objectives" id="sect-00001">
    <title>Learning Objectives</title>
    <para id="para-00001">By the end of this section, you will be able to:</para>
    <list id="list-00001">
    <item>Understand the difference between algorithms and <term class="no-emphasis" id="term-00002">program</term>s</item>
    <item>Relate <term class="no-emphasis" id="term-00003">data structure</term>s and <term class="no-emphasis" id="term-00004">abstract data type</term>s</item>
    <item>Select the data structure that is appropriate to solve a given problem practically</item>
    </list>
    </section>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:**  osbooks-introduction-computer-science
- **collection slug:** introduction-computer-science
- **ref/branch:**
- **chapter/section:** Ch 1.1 
- **surrounding text:** 

# Acceptance Criteria

## PDF
- [ ] LOs are a bulleted list (unnumbered)

## Web
- [ ] LOs are a bulleted list (unnumbered)

**Comment by openstaxalina** [comment]
Yes, per the [original designs ](https://drive.google.com/file/d/1KAYqs-YThVNw9uGrMbUW1NPflsnERDHF/view) the LOs are a numbered list. (And no changes were suggested in the [design round feedback](https://docs.google.com/document/d/1sUUjtELim7pp3uwXHta2ekGPwtw0IxE4HJv0P82fU0c/edit#heading=h.eu9bht6kd9ps).) If a change is needed please re-open this card.

**Comment by ww-openstax** [comment]
Re-open Ticket #5574 - The Learning Objectives should NOT be numbered in the book. (Per Editorial/RA)

**Comment by ww-openstax** [comment]
Re-open Ticket https://github.com/openstax/cnx-recipes/issues/5574 - The Learning Objectives should NOT be numbered in the book. (Per Editorial/RA)

**Comment by omehes** [comment]
tested on ce-styles branch 5574-cs-unnumbered-lo and cookbook branch 5574-cs-unnumbered-lo - OK


![Image](https://github.com/user-attachments/assets/c78b0876-a946-4a14-9dea-3f72aee047f8)

**Comment by omehes** [comment]
staging: 20240729.172215
looks good

**Comment by omehes** [comment]
looks good in corgi prod - 20240729.172215
