### ISSUE TITLE
Computer Science - "Your Turn" heading output is too big

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5575]
# Summary & Screenshots
"Feature subheads here are confusing re: hierarchy, 'Your Turn' is more prominent in treatment than the feature title header."

![Screenshot 2024-06-24 090514](https://github.com/openstax/cnx-recipes/assets/89537088/52036b7e-425b-4985-87f6-426ef203ae77)

This also applies to the "Think It Through"-type boxes.

# Sample Mark-Up
```
<exercise class="your-turn" id="exer-00001"><problem id="prob-00001"><para id="para-00024">If we instead add all the place names to a binary search tree, what are the steps for the autocomplete algorithm? How does this choice affect additions, changes, and removals?</para></problem>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-introduction-computer-science
- **collection slug:** introduction-computer-science
- **ref/branch:**
- **chapter/section:**  Ch 1.2
- **surrounding text:** 

# Acceptance Criteria

**Comment by openstaxalina** [comment]
Will not change -- this was present in the [original designs ](https://drive.google.com/file/d/1KAYqs-YThVNw9uGrMbUW1NPflsnERDHF/view)and was not part of the [design round feedback](https://docs.google.com/document/d/1sUUjtELim7pp3uwXHta2ekGPwtw0IxE4HJv0P82fU0c/edit#heading=h.u3dmjxyyype).
