### ISSUE TITLE
allow computer science to bake without math elements

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#5579]
probably need to remove BakeMathInParagraph from recipe

AC: computer-science bakes without errors and without an empty math tag in the content

**Comment by openstaxalina** [comment]
@yblock sometime today, can you remove the empty mathml element (the one you found yesterday) **on a branch** so that we can test this PR? 

(please only remove it on a branch because if removed on `main`, WW will be back to not being able to build the book in CORGI)

**Comment by yblock** [comment]
Sure, here you go

https://github.com/openstax/osbooks-introduction-computer-science/tree/removed-mathml-tag

**Comment by kswanson33** [comment]
QA: can you please test on cookbook `main` and the computer science branch linked above? thanks!

**Comment by openstaxalina** [comment]
@omehes pinging here in case you don't see this moved to the Ready for Testing column

**Comment by omehes** [comment]
@kswanson33 as I understand, I should run an enki job to see that it succeeds (all-web and/or all-pdf)? something like:
`./enki --command all-web --data-dir ./data5/icompsc --repo osbooks-introduction-computer-science --ref math-cs --book-slug introduction-computer-science --clear-data` with cookbook folder on main

**Comment by omehes** [comment]
testing:
updated cookbook and ce-styles main branches
./enki --command all-web --data-dir ./data6/icompsc3 --repo osbooks-introduction-computer-science --ref removed-mathml-tag --book-slug introduction-computer-science --clear-data
and all-web

both jobs succeeded
checked the pdf doc - looks good

**Comment by kswanson33** [comment]
thank you!
