### ISSUE TITLE
Comment IN Additive Manufacturing Book Features

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#5582]
# Summary & Screenshots
Symptom: Additive Manufacturing fails to bake in CORGI
[Diagnosis](https://openstax.slack.com/archives/C0LA54Q5C/p1720639483432129?thread_ts=1720624913.830269&cid=C0LA54Q5C) thanks to @jbwilson8 : "It looks like code to enable those book features were commented out in the Additive Manufacturing Recipe because there was no content at the time"
PR thanks to @sparksam: https://github.com/openstax/cookbook/pull/384

# Sample Mark-Up
```
N/A
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** github.com/openstax/osbooks-additive-manufacturing
- **collection slug:** `additive-manufacturing-essentials`
- **ref/branch:** `main`
- **chapter/section:** N/A
- **surrounding text:** N/A

# Acceptance Criteria

## PDF
- [ ] PDF can be generated using enki
- [ ] PDF can be generated using CORGI

## Web
- [ ] Web preview can be generated using enki
- [ ] Web preview can be generated using CORGI

**Comment by kswanson33** [comment]
QA: pls test on `sk-fix-additive-manufacturing` on cookbook

**Comment by omehes** [comment]
enki jobs on sk-fix-additive-manufacturing on cookbook succeeded

**Comment by omehes** [comment]
tested in corgi 20240716.213135 - ok
