### ISSUE TITLE
Neuroscience: Enable Answer Key

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#5584]
# Summary & Screenshots
Please enable the Answer Key at the back of the book for _Introduction to Behavioral Neuroscience._

# Sample Mark-Up
```
N/A
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-neuroscience
- **collection slug:** neuroscience
- **ref/branch:** main
- **chapter/section:** chapter 5, chapter 9 (end of book)
- **surrounding text:** `Which of the following is not an example of sensory enrichment during early development that can promote synaptic connectivity?` (Multiple Choice question from 5.3) and `Free nerve endings transmit pain signals related to mechanical, thermal, or chemical sources. They are called ________.`(Fill in the blank question from 9.1)

# Acceptance Criteria

## PDF
- [ ] Answer Key appears in ToC
- [ ] Answer Key appears at EOC, styled to match https://github.com/openstax/cnx-recipes/issues/4757
- [ ] For purposes of testing, answers to the 2 questions above appear in the Answer Key (more will be marked Public once this feature is released)

## Web
- [ ] Answer Key appears in ToC
- [ ] Answer Key appears at EOC
- [ ] For purposes of testing, answers to the 2 questions above appear in the Answer Key (more will be marked Public once this feature is released)

**Comment by openstaxalina** [comment]
@TylerZeroMaster I think you were working on this -- I assigned you and put it in progress. Please let us know if you won't be able to finish this before the freeze on 7/26 and I think @kswanson33 or @jbwilson8 could take over.

**Comment by omehes** [comment]
testing staging - 20240729.172215
ok

**Comment by omehes** [comment]
looks good in corgi prod - 20240729.172215
