### ISSUE TITLE
Lifespan Development: Reduce References Page Count

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#5585]
# Summary & Screenshots
References are projected to occupy ~230 pages (~4,000 references) of the Lifespan Development book. We need to reduce the page count of References, ideally without removing content. Suggestions to improve:
- adjust leading (adjusted by line height)
- adjust font size (we need to keep font at at least 8 pts)
- adjust margins (last resort) 

_**Suggestions already considered but rejected:**_
- don't list references at the module level. this was rejected because it is the market standard to list references at the module level in this course. anything else will be confusing to students and instructors.
- adjust columns - vendor thinks adjusting columns would worsen rather than improve (URLs)]

# Sample Mark-Up
```
<section class="references" id="sect-0015">
      <title>References</title>
          <para id="para-023">American Psychiatric Association. (2022). <emphasis effect="italics">Diagnostic and statistical manual of mental disorders</emphasis> (5<sup>th</sup> ed., text rev.) doi.org/10.1176/appi.books.9780890425787</para>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-lifespan-development
- **collection slug:** lifespan-development
- **ref/branch:** main
- **chapter/section:** most/all
- **surrounding text:** see sample markup above

# Acceptance Criteria

## PDF
- [ ] References occupy fewer pages by implementing one or more of the strategies above, or a new strategy. Discuss with the team on Tue 7/16 (goal to reduce page count by 50 pages)

**Comment by openstaxalina** [comment]
This is the highest priority card for the sprint -- @kswanson33 picking this one up.

**Comment by kswanson33** [comment]
@openstaxalina Seeing references show up as a `<section>` element at the end of each `<page>` 

![Image](https://github.com/user-attachments/assets/5e904974-7776-45f7-ab5d-b1bb4c681acc)

Double-checking that this is expected (not EOC or EOB)

**Comment by openstaxalina** [comment]
@kswanson33 yes, that is expected

**Comment by kswanson33** [comment]
Here is what the references look like with the following specs:

```css
.references p {
  font-size: 0.667rem;  /* equivalent to 8px */
  line-height: 0.8rem;
  margin-bottom: 0;
}
```

![Image](https://github.com/user-attachments/assets/ab535381-db97-41dd-811b-d5cea40f5605)

And here with what I think is the very smallest option, using `line-height: 0.667rem`:

![Image](https://github.com/user-attachments/assets/fd8b066a-1cf4-4740-b829-27931641a5c5)

Sample content started at 65 pages, and went down to 59 pages for both cases.

@openstaxalina any preferences?

**Comment by openstaxalina** [comment]
@kswanson33 let's go with the first option above!

**Comment by kswanson33** [comment]
Awaiting merge on https://github.com/openstax/ce-styles/pull/543 for go-ahead on specs from @openstaxalina

**Comment by openstaxalina** [comment]
@kswanson33 I just got the go-ahead from Editorial. OK to merge!

**Comment by kswanson33** [comment]
QA: please test on ce-styles `lsd-references`

**Comment by omehes** [comment]
Tested: font OK, but references are not at each section end. New PR coming.

![Image](https://github.com/user-attachments/assets/38eac6d6-1401-461b-80f8-d7dae75a0fc4)
