### ISSUE TITLE
Lifespan Development: Move References to End of Section

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#5590]
# Summary & Screenshots

_Please note this is a **change** from the specs here:_ https://github.com/openstax/cnx-recipes/issues/5565

As part of the discussion in https://github.com/openstax/cnx-recipes/issues/5585, we decided to move References to the end of their respective non-intro chapter-section. This saves some space by not having us repeat the chapter-section header at the end of the chapter.

# Sample Mark-Up
```
<section class="references" id="sect-0015">
      <title>References</title>
          <para id="para-023">American Psychiatric Association. (2022). <emphasis effect="italics">Diagnostic and statistical manual of mental disorders</emphasis> (5<sup>th</sup> ed., text rev.) doi.org/10.1176/appi.books.9780890425787</para>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-lifespan-development
- **collection slug:** lifespan-development
- **ref/branch:** main
- **chapter/section:** most/all
- **surrounding text:** see sample markup above

# Acceptance Criteria

## PDF
- [ ] References appear at the end of their chapter-section, immediately before the header for the next chapter-section (or for the Key Terms, if it's the last section of the chapter) - NOT at EOC or EOB
It should look like this:
![Screenshot 2024-07-31 at 11 13 03 AM](https://github.com/user-attachments/assets/f50470a9-3c7f-480a-9ca2-634e58962017)

## Web
- [ ] References appear at the end of their chapter-section, NOT at EOC or EOB

**Comment by kswanson33** [comment]
QA: please test on cookbook `revert-refs-lsd`

**Comment by omehes** [comment]
tested:
cookbook - revert-refs-lsd
ce-styles - lsd-references

pdf and preview looks good


![Image](https://github.com/user-attachments/assets/8e894676-1fda-4fcd-b8d6-ee87018ae419)
