### ISSUE TITLE
Nursing Internal > Fundamentals > Unable to center align the equation

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5591]
# Summary & Screenshots
 
Unable to center align the equation. We have placed the MathML code inside <equation> tag, as per the guidelines

![Screenshot 2024-07-31 115557](https://github.com/user-attachments/assets/88ea2d98-5808-494f-9df5-f12d76557759)

# Sample Mark-Up
```

<equation id="eq-00001" class="unnumbered">
    <m:math>
    <m:mrow>
    <m:mtext>Anion gap</m:mtext><m:mo>=</m:mo><m:mtext>Sodium</m:mtext><m:mo>–</m:mo><m:mfenced>
    <m:mrow>
    <m:mtext>Chloride</m:mtext><m:mo>+</m:mo><m:mtext>Bicarbonate</m:mtext></m:mrow>
    </m:mfenced></m:mrow>
    </m:math>
    </equation>
```

# Issue Occurrence(s)

 **Location**
- [X] In PDF
- [X] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [X] Other (Please describe below)
This is the only instance 

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:**  fundamentals-nursing
- **ref/branch:**
- **chapter/section:** Chapter 20/Section 20.2
- **surrounding text:** A normal anion gap ranges from 4 to 12 mmol/L. Therefore, having a gap greater than 12 mmol/L indicates that the
patient has a large number of additional anions in the plasma, indicating an acid has been added to the system. A
common cause of an anion gap metabolic acidosis is an elevated lactate level. However, there are many other
causes. A useful mnemonic to help a nurse remember the causes of an anion gap is the acronym CAT MUDPILES.
Each letter in CAT MUDPILES stands for a specific acid that could be ingested or produced to cause a metabolic
acidosis.

# Acceptance Criteria

## PDF
- [ ] Element `<equation>` should be centered.

## Web
- [ ] Element `<equation>` should be centered.

**Comment by openstaxalina** [comment]
@yblock could you double-check the markup here? I thought `<equation>` would be automatically centered. It could be the `unnumbered` class making it not. But wanted to get your expert review to ensure nothing is wrong with the markup.

**Comment by yblock** [comment]
Markup looks correct, even unnumbered it should be centered. I think this is a valid style request.

**Comment by openstaxalina** [comment]
Thank you, @yblock ! Moving into the CE DS project.

**Comment by yblock** [comment]
If I might piggy back on this issue, the Python style has an issue with equation centering as well that might be easy to knock out with this one. They seem to be right-aligned in Introduction to Python Programming instead of centered. Let me know if it would be better to have its own issue. 

https://openstax.org/books/introduction-python-programming/pages/2-6-the-math-module
Surrounding text: "Quadratic formula"

<img width="803" alt="Screenshot 2024-07-31 at 1 11 27 PM" src="https://github.com/user-attachments/assets/7e568a2f-06b5-407a-a469-c5423a63b564">

**Comment by kswanson33** [comment]
update: web looks okay, PDF styles have been changed

Web:

![image](https://github.com/user-attachments/assets/676897c9-cb22-4a53-b418-be692a357a06)

PDF:

![image](https://github.com/user-attachments/assets/f1231441-e4b3-4c5e-a717-d5d0f1e4a248)

QA: pls test on ce-styles `carnival-equations-nursing`

**Comment by omehes** [comment]
testing: 
ce-styles carnival-equations-nursing
nursing internal/fundamentals

pdf - OK
web - cannot open



![Image](https://github.com/user-attachments/assets/4cc70217-05f1-44ba-93bb-08d608ae1b2c)
