### ISSUE TITLE
Nursing Internal - Fundamentals - Unable to adjust colwidth> CLINICAL SAFETY AND PROCEDURES (QSEN)

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5592]
# Summary & Screenshots

Unable to adjust colwidth> CLINICAL SAFETY AND PROCEDURES (QSEN)

Chapter 20.2 CLINICAL SAFETY AND PROCEDURES (QSEN) > QSEN Competency: How to Draw a Capillary Blood Gas Sample
![Screenshot 2024-07-31 115322](https://github.com/user-attachments/assets/7d60f22f-cd44-466f-8837-5c729ba37821)

Chapter 20.3 CLINICAL SAFETY AND PROCEDURES (QSEN)> QSEN Competency: What To Do If Your Patient Has Dilutional Hyponatremia
![Screenshot 2024-07-31 115639](https://github.com/user-attachments/assets/0ccf590a-a7e9-4b12-a084-3db072029557)

    <table summary=" " id="table-00003">
    <title>Sample PQRSTU Focused Questions</title>
    <tgroup cols="2">
    <colspec colnum="1" colname="c1" colwidth="1*"/>
    <colspec colnum="2" colname="c2" colwidth="3*"/>
    <thead>

```

```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:**fundamentals-nursing
- **ref/branch:**
- **chapter/section:** 20.2 & 20.3
- **surrounding text:** 

# Acceptance Criteria

## PDF
Add the following new proportions:
TABLE 1.2, 37.4, 41.8 proportions needed 2*,3*
TABLE 8.4 proportions needed 1*,2*,2*,2*,2*,2*

## Web
Add the following new proportions:
TABLE 1.2, 37.4, 41.8 proportions needed 2*,3*
TABLE 8.4 proportions needed 1*,2*,2*,2*,2*,2*

**Comment by openstaxalina** [comment]
@ww-openstax what proportions are you attempting to set? The available proportions are listed in the following 2 cards: https://github.com/openstax/cnx-recipes/issues/5551, https://github.com/openstax/cnx-recipes/issues/5561. 

If you are requesting a proportion not listed there, we will need to add it. 

Please also input the table markup in the "Sample markup" header. Currently we can't see any of the actual markup, only the table text.

**Comment by ww-openstax** [comment]
colwidth values needed for Nursing Fundamentals

TABLE 1.2 proportions needed 2*,3*
TABLE 2.3 proportions needed 1*,2*,2*,2*,2*
TABLE 8.4 proportions needed 1*,2*,2*,2*,2*,2*
TABLE 14.5 proportions needed 1*,2*,2*,2*
TABLE 17.3 proportions needed 1*,2*,2*,2*
TABLE 18.4 proportions needed 1*,2*,2*,2*

CLINICAL SAFETY AND PROCEDURES (QSEN) for 20.2 proportions needed 2*,3*
CLINICAL SAFETY AND PROCEDURES (QSEN) for 20.3 proportions needed 2*,3*

TABLE 23.3 proportions needed 2*,3*
TABLE 23.5 proportions needed 2*,3*
TABLE 23.7 proportions needed 2*,3*
TABLE 26.5 proportions needed 1*,2*,2*
TABLE 27.1 proportions needed 1*,2*,2*

TABLE 29.7 proportions needed 1*,2*,2*
TABLE 33.4 proportions needed 2*,3*
TABLE 33.5 proportions needed 1*,2*
TABLE 34.1 proportions needed 1*,3*
TABLE 34.3 proportions needed 1*,2*,2*,2*,2*
TABLE 35.2 proportions needed 1*,2*,2*,2*
TABLE 35.3 proportions needed 1*,2*,2*,2*
TABLE 35.4 proportions needed 1*,2*,2*
TABLE 37.1 proportions needed 1*,2*,2*
TABLE 37.4 proportions needed 2*,3
TABLE 40.2 proportions needed 1*,2*,2*,2*
TABLE 41.8 proportions needed 2*,3
TABLE 42.1 proportions needed 1*,3*
TABLE 42.2 proportions needed 1*,3*
TABLE 43.2 proportions needed 1*,3*

Note: all colwidth values have already been entered in the XML

**Comment by openstaxalina** [comment]
@jbwilson8 here are the NEW proportions that were not already implemented for the other Nursing titles:

TABLE 1.2, 37.4, 41.8 proportions needed 2*,3*
TABLE 8.4 proportions needed 1*,2*,2*,2*,2*,2*

@ww-openstax I found all other values already listed in the linked PMH and Skills/MNB cards. **Are those tables displaying properly in the current PDFs?**

**Comment by sparksam** [comment]
@openstaxalina I tested building the nursing book in enki and the proportions listed below are properly shown in the book
``` 
TABLE 1.2, 37.4, 41.8 proportions needed 2*,3*
TABLE 8.4 proportions needed 1*,2*,2*,2*,2*,2*
```

**Comment by openstaxalina** [comment]
@sparksam thank you -- did you build that locally? If so could you attach here and/or send me a screenshot of Table 8.4? That one still looks off to me in the latest PDF from CORGI:
![Screenshot 2024-08-13 at 2 35 00 PM](https://github.com/user-attachments/assets/7224fc0d-5c37-46e4-97ef-4d9ded226deb)

**Comment by openstaxalina** [comment]
This looks good, Sam! Moving to Code Review for @TylerZeroMaster when available.

**Comment by omehes** [comment]
tested on ce-styles main as it was merged and this still seems to be incorrect
@openstaxalina 

![Image](https://github.com/user-attachments/assets/7b086114-a726-446c-a638-4dc9eafc1ead)

**Comment by openstaxalina** [comment]
hmmm @omehes where are you pulling content from? can you use the latest content from `main` in the repo?

**Comment by omehes** [comment]
@openstaxalina all from main
enki repo updated
./enki --command all-pdf --data-dir ./DATA444/nursifun2 --repo osbooks-nursing-internal-bundle --ref main --book-slug fundamentals-nursing --clear-data

**Comment by openstaxalina** [comment]
hmmm... @yblock would you be able to review the Fundamentals content on `main` - specifically Table 8.4 to see if the table proportions are set correctly in the content?

**Comment by yblock** [comment]
The colwidths all look to be set correctly. The only thing I could think of that would cause the second column to be larger would be the greater size of text in the example for **S**pecific and maybe there's code somewhere trying to keep the table from overflowing to the next page?

**Comment by omehes** [comment]
OK. Seems like it could be due to the long text... the columns look like 1, 3, 2, 2, 1, 1

**Comment by yblock** [comment]
Yeah it does, i think the long text is a logical culprit to suspect next. The colwidth is set 1, 2, 2, 2, 2, 2

**Comment by omehes** [comment]
retested. looks good

![Image](https://github.com/user-attachments/assets/dbbe4fae-8f47-4d93-a5b9-054c93db78ee)

**Comment by omehes** [comment]
20240826.140602 - looks good in prod
