### ISSUE TITLE
table link opens in a new window

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5598]
In the WEB view, when we click the highlighted table link opens in a new window instead of navigating to the table.

The new tab problem occurs only with the links provided by the Exercise Editor. Please check and advise.

# Summary & Screenshots
**WEB view:**
![Table_Link](https://github.com/user-attachments/assets/2b13f5c5-25a5-47d0-a7b8-cf36d7f04fae)

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo: https://github.com/openstax/osbooks-principles-data-science 
- **collection slug: Principles-data-science
- **ref/branch: https://openstax-osbooksprincip-yfsw5fi31u6.ws-us115.gitpod.io/
- **chapter/section: Critical Thinking
- **surrounding text: A random sample of 60 students is selected from each group and asked to rate

# Acceptance Criteria

**Comment by openstaxalina** [comment]
This does not need to be a link since the table is in the same exercise. Please change the last sentence of the stem to something like "The results are shown in the table below." or "The results are shown in the table".

**Comment by srm-openstax** [comment]
Thankyou for the update.
