### ISSUE TITLE
Lifespan Development: Live links appear to be generating automatically

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5601]
# Summary & Screenshots
Production noticed that live linking appears to be generating automatically since we are not using any tagging.

Lord, C. (2023, Nov 6). The controversy around ABA: Why some autism parents and advocates find fault with the therapy. The Child Mind Institute. https://childmind.org/article/controversy-around-applied-behavior-analysis/

![Screenshot 2024-08-20 103527](https://github.com/user-attachments/assets/cf9141e2-7899-4fba-870d-46d222091dba)

# Sample Mark-Up
```
<para id="para-040">Lord, C. (2023, Nov 6). The controversy around ABA: Why some autism parents and advocates find fault with the therapy<emphasis effect="italics">. The Child Mind Institute</emphasis>. https://childmind.org/article/controversy-around-applied-behavior-analysis/</para>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-lifespan-development
- **collection slug:**lifespan-development
- **ref/branch:**main
- **chapter/section:** Ch 6/6.1
- **surrounding text:** see sample markup above

# Acceptance Criteria

**Comment by openstaxalina** [comment]
This is happening because of the PDF reader used and is not something we can adjust. Closing as won't fix.
