### ISSUE TITLE
Footnotes appear in wrong sections

### ISSUE THREAD

**Issue by uskka** [openstax/cnx-recipes#566]
Footnotes in webview appear in wrong section of the book. Footnotes 1,2,3 refer to the "Homework" content, in PDF these footnotes are in Homework section. 4 is in proper section but should have 1 number because it should appear as first footnote in this module, than 5 should be in "Chapter Review".

(1,2,3) https://katalyst01.cnx.org/contents/tWu56V64@34.15:PhCRzjQp@15/12-Data-Sampling-and-Variation

(4,5) https://katalyst01.cnx.org/contents/tWu56V64@34.15:3UZ5oaPG@6/14-Experimental-Design-and-Eth

Webview
![screenshot-katalyst01 cnx org-2018 08 20-18-58-23](https://user-images.githubusercontent.com/40228918/44354803-15fc0180-a4ab-11e8-83c3-53b5a5baca87.png)

Webview
![screenshot-katalyst01 cnx org-2018 08 20-18-45-05](https://user-images.githubusercontent.com/40228918/44354300-c0732500-a4a9-11e8-90b0-acb4015c859c.png)

PDF(Homework)
<img width="855" alt="screen shot 2018-08-20 at 18 45 46" src="https://user-images.githubusercontent.com/40228918/44354304-c406ac00-a4a9-11e8-96aa-71560629a856.png">

### QA Testing (added 5.20.20)

1.  run neb publish on each book with a trivial change in each module so that the version of each module changes.

example change: `</md:title>` to `</md:title>(add space)`

**Then we should:**

2. test that the previous version of each book (representative sample) still has old-style footnotes

3. test that the new version of each book has the new-style footnotes (representative sample)

**Potentially broken elements to look for:**

- disappearing footnotes (medium likelihood)
- pages that end abruptly (low likelihood)
- broken link between the footnote and the footnote marker in the content (low likelihood)

**Likely places a footnote will disappear:** 
inside a table header, a list, a table caption, a figure caption, a term definition, an exercise. (I'm not sure they occur in all of those places but I recall footnotes in table headers being a surprise)

**Comment by wilkus27** [comment]
The same problem in Introductory Statistics:

1) https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:CY4aJuYS@17/12-Data-Sampling-and-Variation -> **1,2,3** lead to **Homework**

2) https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:Ph_ExrCQ@9/14-Experimental-Design-and-Eth -> **7** leads to **Chapter Review**

**Comment by openstaxalina** [comment]
Footnotes in collating sections are being left in the original module where the collating section was.
The collating section moves, but the footnote stays in the module.  Causes major issues with numbering.

The footnotes are part of the module, not part of the section.  Helene does not know of a way to make these collate. 

Helene is following up with Phil to figure out how this was done in DocBook/PDF.

**Comment by philschatz** [comment]
I believe that in `oer.exports` the footnotes were kept with the content (this is allowed in the Docbook schema). Example:

`<para>some text <footnote id="example-footnote"> 
    Alan Davidson, Oxford Companion to Food,
    s.v. cheesecake: "Cheesecake, not a
    cake in the ordinary sense, is really a
    kind of tart."
  </footnote> some more text</para>`

the CNXML->XHTML conversion moved them into the module for 2 reasons:

- we wanted the raw HTML to be usable by others and have it appear "decent" on webview
- XHTML does not allow blockish elements in a `<p>`

It seems like we could do 2 things (might have to do both if not all books will be baked at the same time):

1. Could **all** books have the footnotes collate to the end of the chapter? (likely does not require changing the CNXML->XHTML conversion)
2. Put the footnotes back into the content (not sure if that breaks the **valid-XHTML** rule)

Or, we could extend recipes so they look up the footnote (since there is a link in the content) and move it (and create a **Footnotes** section if one does not yet exist at the destination

**Comment by reedstrm** [comment]
Met w/ @openstaxalina @philschatz and @helenemccarron re: this issue. Decided that the best solution, if possible, is to leave the footnotes "in place" with the other content, until the last possible moment - _i.e._ move them via recipe, not the xhtml transform. The problem with that is the cnxml footnotes formally allow for block level elements that would not be valid in the typical html text context (inside a `p`). Option would be to leave footnotes in place _when possible_ and provide a markup means to point to "extended content" for more complex cases. Action item: @reedstrm will survey the existing published footnotes to determine if any such block-containing footnotes already exist, and if so, what books they are in.

**Comment by reedstrm** [comment]
Report:
1780 modules contain 7861 footnote tags. Of those, 6263 contain a child element. The distribution of tag names for those children:
 ```
tagname | count 
-----------+-------
 newline   |     4
 footnote  |     5
 list      |     5
 sub       |    11
 quote     |    12
 equation  |    15
 term      |    17
 sup       |    47
 code      |   111
 cite      |   111
 foreign   |   112
 para      |   434
 m:math    |   690
 link      |  1319
 emphasis  |  3370
(15 rows)
```
Of those, `para` is blockish, code, equation, and m:math _can_ be,  - `newline` is odd.

The 434 paras appear in 54 modules.  Of those, some are clearly in CNX Biology. The one I looked at closely was an unneeded `para` wrapping what is formally a citation.

Full list:
m27796,m34082,m34310,m34315,m43482,m43682,m44469,m44935,m45024,m45025,m45027,m45028,m45029,m45064,m45250,m45878,m46164,m47738,m48617,m49643,m49654,m49679,m49965,m51805,m51990,m52675,m52676,m52677,m52679,m52683,m53268,m56089,m56645,m56647,m56836,m57704,m57787,m60120,m60482,m61618,m61972,m62003,m62813,m62817,m62822,m62825,m63524,m63527,m63832,m63839,m63841,m63848,m63900,m64935

**Comment by philschatz** [comment]
RE the para ones, can you count the number of `cnx:footnote[cnx:para][count(*) > 1]` ? If the ones with a `<para>` only contain the `<para>` then we _could_ just unwrap the para during the CNXML->HTML transform

**Comment by reedstrm** [comment]
Of the 434 `para` tag containing footnotes, only 8 (in 6 modules) contain more than a single `para`. By visual inspection, the single `para` footnotes all seem to be a `para` nested directly inside the footnote. 

Those six modules are: 
```
               ?column?                |                                            name                                            
---------------------------------------+--------------------------------------------------------------------------------------------
 https://cnx.org/content/m27796/latest | Introduction
 https://cnx.org/content/m64935/latest | Central Limit Theorem - MRU - C Lemieux
 https://cnx.org/content/m34315/latest | As Transparent as Infrastructure: On the research of cyberinfrastructure in the humanities
 https://cnx.org/content/m44935/latest | The Sustainable City
 https://cnx.org/content/m51990/latest | NATURAL CAPITAL: ENERGY
 https://cnx.org/content/m34310/latest | Response to ROTUNDA: a university press starts a digital imprint
(6 rows)
```

**Comment by reedstrm** [comment]
The list cases are slightly more interesting. There are some there that clearly cannot be "inlined", so we will need a model for 'extended footnote', but I think most/all of the openstax production books look to be of the "single blockish tag nested just inside the footnote" or something that can easily be replaced w/ a `newline` to separate the footnote into two parts.

**Comment by reedstrm** [comment]
Before @philschatz get's _too_ excited, we'll still need to survey pretty much all of the above, and design the appropriate transform, and matching recipe changes. :-)

**Comment by openstaxalina** [comment]
*Outcome from today's call:*
-Phil to create a PR against Rhaptos/cnxmlutils so Helene can see the HTML when footnotes are left with their parent content (will not handle blockish elements).
-Phil to create a PR against ### that handles blockish elements.
-Helene to make recipe changes against this issue.

@philschatz @reedstrm @helenemccarron

**Comment by openstaxalina** [comment]
New plan is to handle this in content for Assignable Webview for Half (releasing September 2018) and make a long-term fix in future sprints.

**Comment by philschatz** [comment]
I updated https://github.com/Connexions/rhaptos.cnxmlutils/pull/169 to unwrap `<para>` elements that are children of footnotes. From the comments above, I _think_ that fixes the OpenStax books.

As noted above, a different approach will need to be done for lists but, unless lists appear in footnotes of openstax books, we can defer fixing those cases until we create valid XHTML.

**Comment by brittweinstein** [comment]
moving into C.C. to discuss in planning CC @openstaxalina

**Comment by brittweinstein** [comment]
@helenemccarron is the footnote work complete and ready for testing?

**Comment by brittweinstein** [comment]
Need to discuss with @philschatz and @helenemccarron to see who will finish this, then test, then find fix for webview.

**Comment by therealmarv** [comment]
[copied from Slack](https://openstax.slack.com/archives/C0LA54Q5C/p1554998095016400?thread_ts=1554997218.013200&cid=C0LA54Q5C):
I’ve looked into this issue from a technical side: It seems it is a issue which needs minimum 3 steps:
1. fix transforms cnxmlutils (seems half way done by Phil)
2. cnx-recipes needs fixes (unclear how much work is done there already, maybe nothing yet because dependent on 1.)
3. Testing if 1+2 does not break anything.

Solving this issue means finishing 1 (half way done by Phil) and then start working on 2 (cnx-recipes).

**Comment by brittweinstein** [comment]
@brittweinstein  when Marvin's transform work is done, this will be ready for Helene's team to take over.

**Comment by brittweinstein** [comment]
This must go out with the transforms work that Marvin is working on.

**Comment by brittweinstein** [comment]
It is critical that this work be released at the same time as any footnote work related to transforms work the tech team will do. So, the tech side will make the transforms fix without releasing anything to production so nothing breaks. Phil's PR above will need to be tested to ensure nothing breaks. Then, the styles team will take over this issue--in the same sprint. Then the styles team will implement a fix and release all of the work at once.

**Comment by brittweinstein** [comment]
@omehes the next step here will be testing this on QA

**Comment by brittweinstein** [comment]
We will only test Bio 2e which has been rebaked today. Ryan will work with Otto on getting the URL to test -- vendor-qa.cnx.org.

**Comment by brittweinstein** [comment]
Another thing to keep an eye on is the web page ending abruptly.

**Comment by omehes** [comment]
Verified Bio 2e version 18.1 on qa.cnx.org (by searching for the book) with BJ (note that we don't have vendor-qa.cnx.org webpage implemented):
- checked footnotes on some modules - numbering looks good, no abrupt ending to pages (checked more pages w/wo footnotes)
 
![footn1.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/3fc16103-40f9-416d-aa8f-55e574db7c42)

![footn2.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/e1a5ef0a-6deb-4f60-97c6-ff96ad07f35d)

PASS

**Comment by omehes** [comment]
More testing:

Bio2e does not exercise all of the different places footnotes may occur. Lkely places where footnotes might disappear are in places other than a paragraph of normal text.
For example: inside a table header, a list, a table caption, a figure caption, a term definition, an exercise. (I'm not sure they occur in all of those places but I recall footnotes in table headers being a surprise)

Collections:

**Comment by philschatz** [comment]
In case it helps, here are some of the quirky places where footnotes occur:

- Books with footnote inside a table header: [th [data-type="footnote-number"]](http://content-finder.herokuapp.com/?books=all&element=th%20%5Bdata-type%3D%22footnote-number%22%5D)
- ... inside a list: `li [data-type="footnote-number"]` (only astronomy... and it has 1 in the whole book)
- ... inside a definition: `[data-uuid-key="glossary"] [data-type="footnote-number"]` (0)
- ... inside an exercise: `[data-type="exercise"] [data-type="footnote-number"]` (Microbiology has 119)
- ... inside a figure caption: `figcaption [data-type="footnote-number"]` (Microbiology has 312)
- ... inside a table caption: `caption [data-type="footnote-number"]` (US History has 6)

**Comment by omehes** [comment]
As per above notes, reverified on 3 books:
Astro, Micriobio, US Hist

Process: publish via legacy and set recipe without prod, neb get/publish the collection and verify footnotes (as per above steps).

New footnotes look like this:

![chapt6a.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/6a2c3de2-90e2-4bdb-b686-02966d2cc7b2)

- it is pink due to the tampermonkey/greasemonkey browser extension

ALL PASS!

**Comment by omehes** [comment]
To test on staging, follow steps above and also column K in https://docs.google.com/spreadsheets/d/1iq7PNoofroy1UDglLFlKzmCYjaOv5Ue6f0UzzjmNojA/edit#gid=0
