### ISSUE TITLE
Pipe before appendices numbers in Intro to business

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#666]
# What happened?
***This is not a pipe***
There is a pipe before the appendix number than needs to be removed.

# Reproducibility Details
- **Does it also happen in an incognito window?**: 
yes
- **Does this happen in one place, a few places, or everywhere?**:
happens everywhere

# Environment:

- **Book(s)**: intro to business
- **URL/Server**: all
- **Location (page number, chapter/section)**: appendix
- **Suggested nearby searchable text**: Understanding the Legal and Tax Environment
- **Browser**: all

# Screenshots
![2018-10-11_16-34-30](https://user-images.githubusercontent.com/8514591/46835437-cd0e4e00-cd73-11e8-9436-415ab20f39dd.png)

# Additional notes

Open the book, look at the appendix in the book.

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/9ea86ccd-be00-4f7e-bf19-e0f4c7106729)

**Comment by brittweinstein** [comment]
With bakedPDF, this should no longer be an issue.
