### ISSUE TITLE
TOC should not be numbered - start at preface with 1

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#667]
# What happened?
The page numbers should start after the TOC.
Fix the folio numbering to match oer.exports PDF numbering scheme for pages.

# Reproducibility Details

- **Does it also happen in an incognito window?**:  yes
- **Does this happen in one place, a few places, or everywhere?**:yes 

# Environment:

- **Book(s)**: all
- **URL/Server**:  everywhere
- **Location (page number, chapter/section)**: top of pages
- **Suggested nearby searchable text**: n/a
- **Browser**: all

# Screenshots

![2018-10-11_16-41-57](https://user-images.githubusercontent.com/8514591/46835694-984ec680-cd74-11e8-9641-3614f2bd3df4.png)

# Additional notes

**Comment by openstaxalina** [comment]
Confirmed: page numbering should start with the Preface with number "1".  (No roman numerals, etc.)

**Comment by openstaxalina** [comment]
Per Larissa - Page numbers should start at 1 and keep going on each page until the end.

**Comment by openstaxalina** [comment]
Currently the ToC pages are being counted, so the Preface is not starting at "1".
<img width="933" alt="Screen Shot 2020-01-07 at 4 15 17 PM" src="https://user-images.githubusercontent.com/7863733/71934042-29c00a80-3169-11ea-8050-0d8d249741fb.png">



**We should not count or number the ToC pages and the preface should start at 1.**

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-02-07 13-52-01](https://user-images.githubusercontent.com/47241114/74031153-0dee9500-49b1-11ea-90a3-77e600cfbcea.png)
