### ISSUE TITLE
Accounting - Images in webview are left justified

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/cnx-recipes#676]
content03
GLOBAL

**Images** are left justified instead of centered (figures are centered), these should be centered as in the PDF output.

![webviewimages_justification](https://user-images.githubusercontent.com/19212926/46980377-5e4a3100-d0a2-11e8-9433-4b0ad32c335a.png)

**Comment by openstaxalina** [comment]
Agree; I believe typically the only figures or images that are left-justified are in the answer key.

cc @lwtchu @helenemccarron @brittany-johnson

**Comment by openstaxalina** [comment]
Per 10/23 planning, we are holding on this change until we have UX input.

**Comment by openstaxalina** [comment]
See also: https://github.com/openstax/webview/issues/2202

**Comment by brittweinstein** [comment]
@lwtchu what is the priority/decision here?

**Comment by lwtchu** [comment]
Closing - not an issue. can revisit when we do the cardboard theme
