### ISSUE TITLE
Styling lists  based on options given in CNXML

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#684]
# What happened?

There are several list options in CNXML. We need to do the following:

1. Determine which ones we should decommission from CNXML due to the complexity of styling. 
2. Style the lists.

# Environment:

- **Book(s)**: Test content is in the FIRST chapter of Prealgebra on katalyst01.cnx.org. 
- **URL/Server**: 

  - On katalyst01 https://katalyst01.cnx.org/contents/yqV9q0HH@13.2:plLt9FYr@7/Introduction - it should show up after it is rebaked

  - On devb https://devb.cnx.org/contents/YnECIgLx@3.1:1uiHHSaC@1/1-4-List-Testing 

- **Location (page number, chapter/section)**: Chapter 1; section 6

# Additional notes

If you want to see what they are supposed to look like, please look at the legacy.cnx.org version of the collection (https://legacy-devb.cnx.org/content/m71404/latest/?collection=col23868/latest or https://legacy-katalyst01.cnx.org/content/m70720/latest/?collection=col11756/latest)

**Comment by brittweinstein** [comment]
@lwtchu can this be closed?

**Comment by lwtchu** [comment]
@brittweinstein sure...i think we just never got to it and all the test content is gone. it's a nice to have. we can re-open in the future when we need to
