### ISSUE TITLE
Include subsections in the ToC

### ISSUE THREAD

**Issue by philschatz** [openstax/cnx-recipes#688]
# What happened?

Webview wanted to have subsections listed in the ToC: https://github.com/Connexions/webview/pull/1566 .

The PDF might also benefit from these extra entries in the PDF sidebar ToC (not the ToC that shows up at the beginning of the book).

The Book viewer may also benefit from having these additional ToC items (since it replaces webview)

Slack discussion: https://openstax.slack.com/archives/C8V1XET1R/p1539974823000100

# Reproducibility Details

Not applicable. This is a new feature

# Environment:

Not applicable. This is a new feature

# Screenshots

Not applicable. This is a new feature

**Comment by brittweinstein** [comment]
Closing b/c this is super duper old.
