### ISSUE TITLE
Linked headers in Key Concepts

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#715]
Headers in **Key Concepts** sections should be linked as they are in **Review Exercises**:

katalyst01 (https://katalyst01.cnx.org/contents/CImQfPDv@3.15:hNruz03x@3.15/Key-Concepts)

![link_head](https://user-images.githubusercontent.com/40228854/48557701-c2e9ed00-e8e7-11e8-84d1-1fc46683759c.JPG)

https://katalyst01.cnx.org/contents/CImQfPDv@3.15:vKx2SjhT@3.15/Exercises

![link_rev](https://user-images.githubusercontent.com/40228854/48557745-dac17100-e8e7-11e8-8b22-5ed5af3eaa71.JPG)

**Comment by PatBoj** [comment]
@brittany-johnson @helenemccarron This issue is not related to the End of Section idea. Recipes don't add links to the section names in key term and in any page. Links to sections in the Review Exercises was added manually to the content, not by recipe. 

In the polish university of physics there is same situation. In the pdf there are links to section, but on the webview there are not.

**Comment by helenemccarron** [comment]
@openstaxalina  this looks like we would need to add linking back to the section title for all module separated EOC sections, is that something desirable?

**Comment by openstaxalina** [comment]
@helenemccarron yes, that would be a nice enhancement if this is feasible.

If this is going to cause a lot of work, we can live with the inconsistency @wilkus27 noted for now, and make this a future enhancement.  Please let me know if you have any questions or concerns.  cc @PatBoj @Adrianltd @wilkus27

**Comment by openstaxalina** [comment]
(One other note: what I'm understanding is that this will impact all baked books that use module headers in EOC sections.  I think that we should consider feature flagging this only to DevMath to break down the testing load.  Interested in @Stackblocks's input.)

**Comment by Stackblocks** [comment]
Depending on the overall weight of the list (books that use module headers in eoc sections) we could go either way. 

If we feature flag it we should also make sure we draw up a roadmap to getting all the applicable books tested with the feature enabled and not use the flag solely as a quarantine.

**Comment by openstaxalina** [comment]
Spoke with @helenemccarron --

This is a major change that would be complex to implement and involve significant testing.  Therefore, I am going to move this issue to the backlog as a possible future improvement.  We can release the DevMath books in Assignable Webview without this change.

cc @wilkus27 @Adrianltd @PatBoj

**Comment by helenemccarron** [comment]
Addressed in PR #837

**Comment by Stackblocks** [comment]
Linking correctly in the updated Econ and Biology
