### ISSUE TITLE
Integrate Polish University Physics recipe and template

### ISSUE THREAD

**Issue by aiwenar** [openstax/cnx-recipes#726]
This issue tracks progress of integrating recipe for Polish translation of _University Physics_ with cnx.org systems.

- [ ] ~#377 Create recipe for Polish University Physics~
- [ ] Implement functionality required for Polish recipe
  - [x] #1011 Translatable strings
  - [x] ~#1010  #1021 Multiple indices~
- [ ] Create a new recipe for Polish University Physics
   - [x] update books.txt
   - [x] update manifest.json
- [ ] (no issue yet) Create a PDF style(template) in oer.exports. This might be only uploading the CSS, not the Less.
   - [ ] add template to rhaptos.print (drop-down)
- [ ] create symlink in oer.exports

**Comment by MartaSztuka** [comment]
tested on katalyst01
one issue detected: https://github.com/openstax/cnx-recipes/issues/1252

**Comment by brittweinstein** [comment]
@wilkus27 can we close this? I believe this is going out to production tomorrow (Wed.) is that right?
