### ISSUE TITLE
WAITING (content team investigation) baked Astronomy figure numbers missing in staging preface

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#747]
Assignable webview (baked) Astronomy on staging has lost figure numbering in the preface; it's not content, since they are definitely numbered in legacy webview.

# Reproducibility Details

- **Does this happen in one place, a few places, or everywhere?**: happens on staging.cnx.org where I am testing

# Environment:

- **Book(s)**: Astronomy 
- **URL/Server**: https://staging.cnx.org/contents/LnN76Opl@15.1:t5W09zMY@11/Preface
- **Location (page number, chapter/section)**: preface
- **Suggested nearby searchable text**: pluto close up
- **Browser**: Firefox

# Screenshots

staging.cnx.org:
<img width="1415" alt="screen shot 2018-12-10 at 3 07 07 pm" src="https://user-images.githubusercontent.com/1895432/49761686-6206c800-fc8d-11e8-8953-e9d792077ab2.png">

**Comment by Adrianltd** [comment]
@oscryan Can you rebake `astronomy` and make sure (https://staging.cnx.org/a/content-status/) it's baked with the correct recipe?
I have checked this on `katalyst01` and locally and `figures` in the `preface` are numbered.

**Katalyst01**
![image](https://user-images.githubusercontent.com/40228907/49820396-11b86480-fd78-11e8-8457-b5082bee52b4.png)
**Locally, straight from the master branch**
![image](https://user-images.githubusercontent.com/40228907/49820366-fd746780-fd77-11e8-839c-f2ba5e37fba7.png)

If that's not the case, maybe the content on `katalyst01` and on `staging` is different? 
cc: @helenemccarron

**Comment by oscryan** [comment]
rebaked and it's definitely the right recipe, still no figure numbers in the preface

**Comment by Adrianltd** [comment]
@oscryan have you cleared the cache on the server?

**Comment by oscryan** [comment]
No, but version history in webview confirms the content was rebaked twice today.

**Comment by openstaxalina** [comment]
@Adrianltd This is the first time we've baked this book on staging, and the other recipe changes **are** showing.  I am not sure why the figure numbers in the preface are **not** showing.  Are you sure the PR for that was merged to webview before December 7?

**Comment by helenemccarron** [comment]
A quick look at the content shows that both images are different: 
![2018-12-11_16-43-52](https://user-images.githubusercontent.com/8514591/49835185-0c511f00-fd64-11e8-9d78-830854a89d4d.png)

The fig. on Katalyst has a title vs a caption on staging. I don't know which one is right but it seems that the recipes are expecting a title. I am inclined to say that Katalyst's content is newer than staging but I might be wrong.

**Comment by helenemccarron** [comment]
Staging:
```<figure id="OSC_Astro_23_04_Pulsar"><media id="fs-id1163975737628" alt="Model of a Pulsar. In this illustration the Earth is drawn below center, in the path of an approaching &#x201C;Beam of particles and radiation&#x201D;. The pulsar, labeled &#x201C;Neutron star&#x201D;, is drawn at upper right as a blue sphere. Its rotation axis is drawn vertically upward, with a counter-clockwise arrow around it indicating the direction of rotation. The magnetic field lines are drawn in a plane perpendicular to the rotation axis as concentric red ellipses on either side of the star. The field lines intersect the surface of the star at the &#x201C;North magnetic pole&#x201D;, which faces Earth, and the &#x201C;South magnetic pole&#x201D;, which faces toward upper right. The beam of radiation is emitted from the poles of the magnetic field, and extend toward upper right and lower left.">
<image mime-type="image/jpeg" src="OSC_Astro_23_04_Pulsar.jpg"/>
</media>
<caption>How a Pulsar Beam Sweeps over Earth.</caption></figure>```

katalyst01:
```<figure id="OSC_Astro_23_04_Pulsar"><title>How a Pulsar Beam Sweeps over Earth.</title><media id="fs-id1163975737628" alt="Model of a Pulsar. In this illustration the Earth is drawn below center, in the path of an approaching &#x201C;Beam of particles and radiation&#x201D;. The pulsar, labeled &#x201C;Neutron star&#x201D;, is drawn at upper right as a blue sphere. Its rotation axis is drawn vertically upward, with a counter-clockwise arrow around it indicating the direction of rotation. The magnetic field lines are drawn in a plane perpendicular to the rotation axis as concentric red ellipses on either side of the star. The field lines intersect the surface of the star at the &#x201C;North magnetic pole&#x201D;, which faces Earth, and the &#x201C;South magnetic pole&#x201D;, which faces toward upper right. The beam of radiation is emitted from the poles of the magnetic field, and extend toward upper right and lower left.">
<image mime-type="image/jpeg" src="OSC_Astro_23_04_Pulsar.jpg"/>
</media>
</figure>```

**Comment by Adrianltd** [comment]
@openstaxalina can you confirm which content is more up to date (katalyst01 vs staging)? If staging is newer, I will need an update on katalyst before I'll deliver a new way of numbering figures.

**Comment by openstaxalina** [comment]
@Adrianltd This issue is challenging to track down.  I'm moving this to the backlog until I can talk with the team.

**Comment by openstaxalina** [comment]
Links for reference:
preface on staging: https://staging.cnx.org/contents/LnN76Opl@17.1:t5W09zMY@11/Preface
preface on katalyst01: https://katalyst01.cnx.org/contents/LnN76Opl@14.24:t5W09zMY@10/Preface
preface on production: https://cnx.org/contents/LnN76Opl@14.33:t5W09zMY@12/Preface

closed Astronomy issues in content-managers: https://github.com/Connexions/content-managers/issues?q=is%3Aissue+label%3Abook%3Aastronomy+is%3Aclosed
closed Astronomy issues in webview: https://github.com/Connexions/webview/issues?q=is%3Aissue+label%3Abook%3Aastronomy+is%3Aclosed
open and closed Astronomy issues in cnx-recipes: https://github.com/Connexions/cnx-recipes/issues?q=is%3Aissue+label%3Abook%3Aastronomy+is%3Aopen

**Comment by brittweinstein** [comment]
@oscryan will migrate the preface from production to staging and katalyst to check this.

**Comment by openstaxalina** [comment]
I think that if we change the figure captions to figure titles, this issue will be resolved.  Moving to content-managers.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #596](https://github.com/openstax/content-managers/issues/596) via [**ZenHub**](https://www.zenhub.com/)
