### ISSUE TITLE
[american_government] References

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#749]
On katalyst01 (https://katalyst01.cnx.org/contents/W8wOWXNF@18.8:PZqKd1ie@18.8/References) all references are created as a notes:

![refer](https://user-images.githubusercontent.com/40228854/49934121-cc0db000-fecd-11e8-8d54-e4374c6801f0.JPG)

This is how it looks in PDF:

![refer_pdf](https://user-images.githubusercontent.com/40228854/49934144-d9c33580-fecd-11e8-887c-b4c52ede0011.JPG)

Probably it is related with https://github.com/Connexions/webview/issues/2124.
In PDF references from modules are linked and lead to the page from above.
Should it works in the same way on webview? And should items from https://katalyst01.cnx.org/contents/W8wOWXNF@18.8:PZqKd1ie@18.8/References be also linked and lead to the sections? (There is no such option in PDF).

**Comment by openstaxalina** [comment]
@wilkus27 thanks for asking this.  Here is my feedback:

- The appearance of the references in webview is okay as-is.
- In the module content, users should be able to click the reference number (for example, "1" for the Paul A. Samuelson reference in module **1.1 What is Government**), as in the PDF.
- Users do not need to be able to click the references at the end of the book and go back to the module content.  This imitates the behavior (or lack of behavior) in the PDF.

cc @PatBoj Please let me know of any questions!

**Comment by PatBoj** [comment]
@openstaxalina @wilkus27 All fixed :), ready for test.

**Comment by wilkus27** [comment]
Verified on katalyst01. 
Linked references numbers in modules lead to the right places in section **References**.
They are numbering continuously through the chapters. All is consistant with PDF.

There is one change in displaying notes in **References** section:

![ref](https://user-images.githubusercontent.com/40228854/50282433-07225d00-0453-11e9-9e3a-a7861abc9133.JPG)

Numbers are not in header of note like before. @openstaxalina is it ok? If I may I would suggest one change. I think it will look better with dot after number, e.g. `1. _text_`.

**Comment by openstaxalina** [comment]
@wilkus27 I like that idea.  _If possible_, we should also bold the numbers so that they stand out even more and the styles match more closely between webview and PDF.  I am going to return this to In Progress.

Ideal:
**1.** Paul A. Samuelson...

Also acceptable:
1. Paul A. Samuelson...

**Comment by wilkus27** [comment]
These problems could be resolved by webview, so I created a new issue for that: https://github.com/openstax/webview/issues/2155.

In this case I'm going to close this issue.
