### ISSUE TITLE
Broken equations

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#759]
On katalyst01 after deployment from master and baking from dev-math recipe branch (status code from 2018.12.20.) appears problem with mathematical objects in Prealgebra, Intermediate Algebra and Elementary Algebra.

e.g. https://katalyst01.cnx.org/contents/CImQfPDv@3.19:SadrhUaw@3/6-1-Add-and-Subtract-Polynomials 

![math](https://user-images.githubusercontent.com/40228854/50294995-65613700-0477-11e9-9f5d-eb8ba6d0234e.JPG)

**Comment by PatBoj** [comment]
I think it's not dev-math recipe issue. I've baked _Intermediate Algebra_ using recipe from master and the problem with math still appears. cc @helenemccarron 

## **Should be:**
https://katalyst01.cnx.org/contents/AndhM9Sd@4.12:QlYg2VHd@5/1-3-Fractions
![image](https://user-images.githubusercontent.com/20907906/50514352-e9ca4000-0a9d-11e9-946d-7de32d0b8b2b.png)

## **Is now:**
https://katalyst01.cnx.org/contents/AndhM9Sd@4.13:QlYg2VHd@5/1-3-Fractions
![image](https://user-images.githubusercontent.com/20907906/50514357-ef278a80-0a9d-11e9-8b3c-fae9ec38797b.png)

**Comment by wilkus27** [comment]
Verified on katalyst01.

Examples:

**Elementary Algebra**

![elem](https://user-images.githubusercontent.com/40228854/51390573-fa675680-1b2f-11e9-99ba-5086c278dfde.JPG)

**Prealgebra**

![pre](https://user-images.githubusercontent.com/40228854/51390596-06ebaf00-1b30-11e9-9ff1-65ea3b469cbf.JPG)

**Intermediate Algebra**

![inter](https://user-images.githubusercontent.com/40228854/51390645-2551aa80-1b30-11e9-9cfc-eda0820e931c.JPG)
