### ISSUE TITLE
Additional abstract in Preface

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#762]
On katalyst01 (https://katalyst01.cnx.org/contents/FPtK1zmh@12.1:fEI3C8Ot@14/Preface) in Preface there is additional abstract at the beggining of the page.

**webview:**

![abstract](https://user-images.githubusercontent.com/40228854/50681784-0241d980-100d-11e9-988d-d7e94e307d1f.JPG)

**PDF:**

![abstract_pdf](https://user-images.githubusercontent.com/40228854/50681975-9dd34a00-100d-11e9-863a-933ce32f36ae.JPG)

**Comment by wilkus27** [comment]
@openstaxalina Is it added intentionally? Or we should remove it to be consistent with PDF?

**Comment by openstaxalina** [comment]
@Adrianltd is it possible **not** to pull the abstract into the content for the **_Preface only_**?

**Comment by helenemccarron** [comment]
@Adrianltd I think you might have to add a custom trash call to remove it from the Preface, otherwise, we might have to alter the abstract mixin selector, which would mean full regression for all the books using abstracts. cc @openstaxalina

**Comment by wilkus27** [comment]
Verified on katalyst01

![abstract](https://user-images.githubusercontent.com/40228854/51113302-dccd8080-1801-11e9-920c-ab9274282a90.JPG)
