### ISSUE TITLE
Remove numbering of figures from Preface

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#763]
On katalyst01(https://katalyst01.cnx.org/contents/FPtK1zmh@12.1:fEI3C8Ot@14/Preface) in Preface all images shouldn't be numbered.

webview:

![images](https://user-images.githubusercontent.com/40228854/50696950-25867c00-1041-11e9-8953-f8d62988a677.JPG)

PDF:

![images_pdf](https://user-images.githubusercontent.com/40228854/50696976-333c0180-1041-11e9-813b-a6f99656ea65.JPG)

This problem need to be solved by recipes and by content. More informations about it could find here: https://github.com/openstax/content-managers/issues/307.

**Comment by wilkus27** [comment]
Related issue from content-manager repo: https://github.com/openstax/content-managers/issues/536

**Comment by Adrianltd** [comment]
I think that disabling the feature-flag `preface-has-captions` should do the job. I'll create a PR with that to test.

**Comment by wilkus27** [comment]
Verified on katalyst01:

![fig_pref](https://user-images.githubusercontent.com/40228854/51113563-ac3a1680-1802-11e9-8e26-d2813db1620f.JPG)

Title from above the figure will be removed by content: https://github.com/openstax/content-managers/issues/536
