### ISSUE TITLE
Missing headers in Chapter Review

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#765]
On katalyst01 (e.g. https://katalyst01.cnx.org/contents/FPtK1zmh@12.1:8_LDnQLE@12.1/Chapter-Review) **Chapter Review** sections should contain headers:

webview

![chapter_rev](https://user-images.githubusercontent.com/40228854/50767898-d29a0800-127e-11e9-9293-f3fe4ea7b83b.JPG)

PDF:

![chapter_rev_pdf](https://user-images.githubusercontent.com/40228854/50767908-d9287f80-127e-11e9-93ab-30dfb817c451.JPG)

**Comment by openstaxalina** [comment]
@helenemccarron will review this.

**Comment by helenemccarron** [comment]
Please remove the answer altogether for now.

**Comment by openstaxalina** [comment]
@helenemccarron is that comment on the proper issue?  I think it's meant for #771 -- I made a comment to the same effect on that one.

**Comment by helenemccarron** [comment]
Oops, indeed, thank you!

**Comment by wilkus27** [comment]
Verified on katalyst01:

![headers](https://user-images.githubusercontent.com/40228854/51385023-4ad5b880-1b1e-11e9-84f8-28658b0d8d3e.JPG)
