### ISSUE TITLE
all solutions displayed, some with extraneous text, in baked Soc2e collated section quiz

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#771]
# What happened?

- All solutions to the section quiz are collated in baked Soc2e instead of half of them
- Some have text besides the solution letter.

# Reproducibility Details

- **Does this happen in one place, a few places, or everywhere?**: Every chapter collates all solutions, but a few chapters do not have extra text on all answers (all chapters have extra text on at least some answers).

# Environment:

- **Book(s)**: Sociology 2e
- **URL/Server**: staging.cnx.org
- **Location (page number, chapter/section)**: https://staging.cnx.org/contents/AgQDEnLI@14.1:Wy0drNlC@14.1/Solutions
- **Suggested nearby searchable text**: 
- **Browser**: firefox

# Screenshots
<img width="1373" alt="screen shot 2019-01-09 at 1 02 02 pm" src="https://user-images.githubusercontent.com/1895432/50922013-04da6f80-140f-11e9-8b94-36018281f0fe.png">
<img width="1401" alt="screen shot 2019-01-09 at 1 00 22 pm" src="https://user-images.githubusercontent.com/1895432/50922014-05730600-140f-11e9-9bd9-5d380f8990f8.png">
<img width="1384" alt="screen shot 2019-01-09 at 12 55 48 pm" src="https://user-images.githubusercontent.com/1895432/50922016-060b9c80-140f-11e9-8be4-528c69b00217.png">

**Comment by wilkus27** [comment]
Verified on katalyst01. There is no more sections **Solutions** in EOC.

![solution](https://user-images.githubusercontent.com/40228854/51381636-fb3ebf00-1b14-11e9-853c-c6b7b8239051.JPG)
