### ISSUE TITLE
Missing References section

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#777]
On katalyst01 (e.g. https://katalyst01.cnx.org/contents/FPtK1zmh@12.1:5q0_ONB9@7/5-3-Functions-of-the-Integumentary-System) all **References** are inside the sections: 

![ref](https://user-images.githubusercontent.com/40228854/51022632-18a7e200-1585-11e9-9c89-9f7fe6d67969.JPG)

They should be put in one section called **References** in EOB, before section **Index**.

![index](https://user-images.githubusercontent.com/40228854/51022742-57d63300-1585-11e9-96da-c409214cb793.JPG)

This is how it looks in PDF:

![ref_pdf](https://user-images.githubusercontent.com/40228854/51022762-691f3f80-1585-11e9-8166-2dd162ba3cfb.JPG)

**Comment by wilkus27** [comment]
cc @helenemccarron 

After commit **be396b7** in References section appeared headers with names of all chapters:

![ref_chapter](https://user-images.githubusercontent.com/40228854/51049644-c12e6400-15ce-11e9-8cca-cdfbcb2a6fa7.JPG)

There should be headers of some (not all) sections:

![ref_section](https://user-images.githubusercontent.com/40228854/51049709-f63ab680-15ce-11e9-9a89-a9883b90144c.JPG)

PDF:

![ref_pdf](https://user-images.githubusercontent.com/40228854/51049726-05216900-15cf-11e9-94bf-bde00381b766.JPG)

After commit **5c56035** section References disappeared from EOB:

![ref_end](https://user-images.githubusercontent.com/40228854/51049851-62b5b580-15cf-11e9-9448-e4c185201df9.JPG)

And inside sections there are now such headings:

![ref_2](https://user-images.githubusercontent.com/40228854/51049920-80831a80-15cf-11e9-8ab5-68b6f03cd129.JPG)

**Comment by helenemccarron** [comment]
@wilkus27 and @Adrianltd It looks like there was a bug in the recipes, I pushed my change, can you try with it, it was working better locally.

**Comment by uskka** [comment]
Looks good. Tested on katalyst01.
<img width="1316" alt="screenshot 2019-01-30 at 12 47 31" src="https://user-images.githubusercontent.com/40228918/51979422-63828e80-248d-11e9-8601-58015b87efe7.png">
