### ISSUE TITLE
Broken Index

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#778]
On katalyst01 (https://katalyst01.cnx.org/contents/FPtK1zmh@12.1:rfFNe2Cf@12.1/Index) header **Symbols** is duplicated a few times with different phrases:

![symbols](https://user-images.githubusercontent.com/40228854/51025585-c2d73800-158c-11e9-839c-e0c37fe9cbc5.JPG)

This is how it looks in PDF:

![symbols_pdf](https://user-images.githubusercontent.com/40228854/51025608-cff42700-158c-11e9-84f6-f79cd712a361.JPG)

All those phrases should be inside other parts. Now they are missing. For example:

**Organic compound**

![organic](https://user-images.githubusercontent.com/40228854/51025675-fb771180-158c-11e9-8f7d-9c9b563a0167.JPG)

PDF:

![organic_pdf](https://user-images.githubusercontent.com/40228854/51025689-016cf280-158d-11e9-8823-d9a3bfcd00c8.JPG)

**Disulfide bond**

![disulfide](https://user-images.githubusercontent.com/40228854/51025693-06ca3d00-158d-11e9-9335-fcb82c070774.JPG)

PDF:

![disulfide_pdf](https://user-images.githubusercontent.com/40228854/51025709-0d58b480-158d-11e9-8eec-a426d77f3dcf.JPG)

**Comment by openstaxalina** [comment]
This  is most likely due to spaces at the beginning of those terms, or other unsupported characters.  (See https://github.com/openstax/content-managers/issues/276.)  I am going to move this to content-managers to address before publishing the book.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #578](https://github.com/openstax/content-managers/issues/578) via [**ZenHub**](https://www.zenhub.com/)
