### ISSUE TITLE
Headers in Index

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#783]
On katalyst01 (https://katalyst01.cnx.org/contents/FPtK1zmh@12.1:rfFNe2Cf@12.1/Index) after last baking and deployment headers look like items:

![head_index](https://user-images.githubusercontent.com/40228854/51117146-39826880-180d-11e9-97ae-fa018a22cfd5.JPG)

That's how it used to display:

![symbols](https://user-images.githubusercontent.com/40228854/51117172-4d2dcf00-180d-11e9-891f-408f9db18934.JPG)

**Comment by openstaxalina** [comment]
Confirmed that terms listed under SYMBOLS begin with spaces or punctuation:

**inorganic compound**
location: https://katalyst01.cnx.org/contents/FPtK1zmh@12.1:5ORVCb_A@5/2-4-Inorganic-Compounds-Essential-to-Human-Functioning
![screen shot 2019-01-17 at 11 07 46 am](https://user-images.githubusercontent.com/7863733/51335668-45a63a00-1a48-11e9-9c4f-69431baf18fb.png)

**disulfide bond**
location: https://katalyst01.cnx.org/contents/FPtK1zmh@12.1:Z3NTbD77@9/2-5-Organic-Compounds-Essential-to-Human-Functioning
![screen shot 2019-01-17 at 11 13 50 am](https://user-images.githubusercontent.com/7863733/51335966-fdd3e280-1a48-11e9-9b85-35e631e31fe3.png)

**steroid**
location: https://katalyst01.cnx.org/contents/FPtK1zmh@12.1:Z3NTbD77@9/2-5-Organic-Compounds-Essential-to-Human-Functioning 
![screen shot 2019-01-17 at 11 14 14 am](https://user-images.githubusercontent.com/7863733/51335984-0c21fe80-1a49-11e9-92e2-5ed333377f86.png)

**intermediate filament**
location: https://katalyst01.cnx.org/contents/FPtK1zmh@12.1:fV7KwqTE@6/3-2-The-Cytoplasm-and-Cellular-Organelles
![screen shot 2019-01-17 at 11 16 38 am](https://user-images.githubusercontent.com/7863733/51336119-63c06a00-1a49-11e9-85df-748996093236.png)

**intracellular fluid**
location: https://katalyst01.cnx.org/contents/FPtK1zmh@12.1:q2X995E3@13/3-1-The-Cell-Membrane
![screen shot 2019-01-17 at 11 18 53 am](https://user-images.githubusercontent.com/7863733/51336260-b39f3100-1a49-11e9-94d9-70dd61de38e7.png)

**obturator externus**
location: https://katalyst01.cnx.org/contents/FPtK1zmh@12.1:y9_gDy74@6/11-6-Appendicular-Muscles-of-the-Pelvic-Girdle-and-Lower-Limbs
![screen shot 2019-01-17 at 11 21 22 am](https://user-images.githubusercontent.com/7863733/51336395-0bd63300-1a4a-11e9-9a68-68d8d46004fa.png)

**gene expression**
location: https://katalyst01.cnx.org/contents/FPtK1zmh@12.1:lyDdZqp4@7/3-4-Protein-Synthesis
![screen shot 2019-01-17 at 11 23 31 am](https://user-images.githubusercontent.com/7863733/51336523-58ba0980-1a4a-11e9-8f30-732f089ad387.png)

**Comment by openstaxalina** [comment]
**Organic compound** 
location: https://katalyst01.cnx.org/contents/FPtK1zmh@12.1:5ORVCb_A@5/2-4-Inorganic-Compounds-Essential-to-Human-Functioning
I am not sure why it was listed above the first Symbols header, but the markup had the same problem:
![screen shot 2019-01-17 at 11 25 14 am](https://user-images.githubusercontent.com/7863733/51336651-b5b5bf80-1a4a-11e9-8aac-f7ca9efb04b3.png)

**Comment by openstaxalina** [comment]
@helenemccarron @Adrianltd @wilkus27 
I confirmed this issue is resolved by content.  The Index matches the PDF after I made the content changes above:
![screen shot 2019-01-17 at 12 05 51 pm](https://user-images.githubusercontent.com/7863733/51338735-4347de00-1a50-11e9-92a8-65462d9b26c1.png)

https://katalyst01.cnx.org/contents/FPtK1zmh@12.8:rfFNe2Cf@12.8/Index

**Comment by openstaxalina** [comment]
Closing; this will be resolved by content: https://github.com/openstax/content-managers/issues/578

**Comment by wilkus27** [comment]
I think that all of the comments from above are related with issue: https://github.com/openstax/cnx-recipes/issues/778. This one is about styling of the terms. But after testing I confirme that both of these issues (778 and 783) are solved:

![terms](https://user-images.githubusercontent.com/40228854/51382774-f8919900-1b17-11e9-8026-bcfc0977949c.JPG)
