### ISSUE TITLE
collation order broken in Accounting

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#784]
# What happened?

key terms and summary are collating in opposite order in accounting on staging when I compare baked webview and pdf

# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: everywhere

# Environment:

- **Book(s)**: Managerial Accounting
- **URL/Server**: https://staging.cnx.org/contents/kg0cimBs@1.78:c8mjNH4C@1.78/Summary
- **Location (page number, chapter/section)**: all chapter collation
- **Suggested nearby searchable text**: 
- **Browser**: firefox

# Screenshots

<img width="158" alt="screen shot 2019-01-14 at 11 55 27 am" src="https://user-images.githubusercontent.com/1895432/51130726-501bc600-17f3-11e9-95e8-87f9be72fec5.png">
<img width="600" alt="screen shot 2019-01-14 at 11 55 23 am" src="https://user-images.githubusercontent.com/1895432/51130727-501bc600-17f3-11e9-8802-0e1455ef89cb.png">
<img width="1369" alt="screen shot 2019-01-14 at 11 55 09 am" src="https://user-images.githubusercontent.com/1895432/51130729-501bc600-17f3-11e9-8e30-ae929ed36175.png">

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment]
Order should be:
Key Terms
Summary

@tomjw64 to re-test after crit sit fix makes it to content03

**Comment by tomjw64** [comment]
![screenshot_16](https://user-images.githubusercontent.com/1285308/51562242-f5b3e280-1e4e-11e9-95d3-8334d1996e30.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/adc0b41b-e55f-40f2-9eaa-300095e8c1c5)
