### ISSUE TITLE
Missing Index in Managerial Accounting ToC

### ISSUE THREAD

**Issue by tomjw64** [openstax/cnx-recipes#792]
![screenshot_14](https://user-images.githubusercontent.com/1285308/51402543-6091b080-1b13-11e9-9cc6-dda60febb111.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8da58e6e-1ab8-4ba9-bccd-80fc0d223337)

**Comment by openstaxalina** [comment]
confirmed fixed in final Managerial Accounting webview:
<img width="1222" alt="screen shot 2019-02-12 at 11 18 58 am" src="https://user-images.githubusercontent.com/7863733/52654637-05f03800-2eb8-11e9-90f8-93640cee7e06.png">
