### ISSUE TITLE
US History => Encoding issue on the dash between two years on Presidents appendix module

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-recipes#795]
# What happened?

When comparing the appendices of US History I found the appendix `Presidents of the United States of America` that the Election Year of George Washington dash separating the date has what appears to be an encoding problem.

# Reproducibility Details

- **Does it also happen in an incognito window?**:
Yes
 
- **Does this happen in one place, a few places, or everywhere?**:
This seems to only affect this page.

# Environment:

- **Book(s)**: US History
- **URL/Server**: https://staging.cnx.org/contents/p7ovuIkl@6.16:stXtbRwc@9/Presidents-of-the-United-States-of-America
https://staging.cnx.org/contents/p7ovuIkl@7.1:stXtbRwc@13/Presidents-of-the-United-States-of-America
- **Location (page number, chapter/section)**: Presents of the United States of America Appendix Module
- **Suggested nearby searchable text**: 
- **Browser**: Chrome

# Screenshots

![image](https://user-images.githubusercontent.com/8730430/51407627-0a783980-1b22-11e9-9245-ef013afc3afe.png)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment]
This is no longer appearing in the baked book on production: https://cnx.org/contents/p7ovuIkl@7.1:stXtbRwc@9/C-Presidents-of-the-United-States-of-America

This was likely the result of some kind of Batch tool test on staging.

Closing.
