### ISSUE TITLE
Changed headers in Appendieces

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#796]
On katalyst01 in new version (https://katalyst01.cnx.org/contents/W8wOWXNF@18.8:51LlKvlb@4/B-The-Constitution-of-the-United-States) headers in Appendieces are bigger than in the old version:

New version:

![header_new](https://user-images.githubusercontent.com/40228854/51546673-fbb4be00-1e64-11e9-9530-74db027cc22d.JPG)

Old version: (https://katalyst01.cnx.org/contents/W8wOWXNF@18.7:51LlKvlb@4/B-The-Constitution-of-the-United-States)

![header_old](https://user-images.githubusercontent.com/40228854/51546706-0bcc9d80-1e65-11e9-9d2e-dc3920dd179c.JPG)

That's how it look in PDF:

![header_pdf](https://user-images.githubusercontent.com/40228854/51546951-8b5a6c80-1e65-11e9-8eb2-a6dd21441b71.JPG)

**Comment by openstaxalina** [comment]
Confirm that this header should be an H2, not an H3.  Closing this issue.
