### ISSUE TITLE
Principles of Management: Quote para not displays as blockquote style in Web view

### ISSUE THREAD

**Issue by clteam18** [openstax/cnx-recipes#800]
# What happened?

Quote para not displays as block quote style in Web view, but it displays correctly in PDF view.

# Environment:

- **Book(s)**: Principles of Management
- **URL/Server**: 
- **Location (page number, chapter/section)**: Chapter 17 - m10590
- **Suggested nearby searchable text**: Managers should plan formally, but do they? Some observers

# Screenshots
**Web view:**
![image](https://user-images.githubusercontent.com/39794953/51747858-ac72c580-20d0-11e9-892c-3405f8ccfc4f.png)

**PDF view:**
![image](https://user-images.githubusercontent.com/39794953/51747912-cd3b1b00-20d0-11e9-8e68-8e55515c5a2b.png)

**Comment by lwtchu** [comment]
@clteam18 after some investigation we've determined that the `<para>` tag should be nested within the `<quote>` tag for the CNXML

It should be ` <quote> <para> ... <para> </quote>`

**Comment by clteam18** [comment]
After updating as <quote><para>...</para></quote>, now the paragraph has been indented.

![image](https://user-images.githubusercontent.com/39794953/51969871-7d2ad280-249b-11e9-89a2-0f24a0b4962a.png)

Hence closing this issue.
