### ISSUE TITLE
Add headers "Multiple Choice", "Questions" in Answer Key

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#803]
# What happened?
The Answer Key in the webview version of Accounting does not have headers indicating the question type; this is confusing to users because the numbering appears to randomly start over and it's not clearly indicated which answer is associated with each question type (unless you click on the number and navigate away from the answer key).

# Reproducibility Details

- **Does it also happen in an incognito window?**:  Yes
- **Does this happen in one place, a few places, or everywhere?**: Throughout the Accounting Answer Key.

# Environment:

- **Book(s)**: Accounting
- **URL/Server**: production (cnx.org) https://cnx.org/contents/kg0cimBs@5.1:qGrnK59M@5.1/Answer-Key
- **Location (page number, chapter/section)**: Answer Key
- **Suggested nearby searchable text**: "Chapter 1"
- **Browser**: all

# Screenshots
PDF (desired behavior -- has headers)
<img width="583" alt="screen shot 2019-01-29 at 1 25 04 pm" src="https://user-images.githubusercontent.com/7863733/51935341-4eddc200-23cb-11e9-81be-127d9cbc81b7.png">

Webview (undesired behavior -- does not have headers distinguishing question types)
![accountinganswerkeywebview](https://user-images.githubusercontent.com/7863733/51935329-45545a00-23cb-11e9-84c7-5d781255c6e8.png)

**Comment by tomjw64** [comment]
![screenshot from 2019-02-05 11-54-14](https://user-images.githubusercontent.com/1285308/52293564-cc11b580-293c-11e9-9c76-ae4bf42e8a92.png)

**Comment by Stackblocks** [comment]
Regenerated content, verified that Thomas's changes are visible in the Git Log, still seeing a non-separated answer key in the [test content](https://easyvm5.cnx.org/contents/kg0cimBs@6.1:qGrnK59M@6.1/Answer-Key)

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/fe1dda07-e207-44d7-9e39-7cda86992f3a)

Also double-checked archive to make sure it wasn't only appearing there for some reason and got the same results.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/807d9423-4805-4d27-bc26-188a9962980a)

**Comment by openstaxalina** [comment]
aaaanny chance at all that it could be a caching issue?  🤔 @Stackblocks

**Comment by Stackblocks** [comment]
@openstaxalina Tested in multiple browsers (incognito & not) and did a devtools cache clear so it is unlikely.

Regenerated the test collection using both the enqueue command and by republishing, both yield the same result.

**Comment by Stackblocks** [comment]
Resolved! Tried directly injecting the recipe into the collection and the issue resolved.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0470d104-a13b-4d2d-8816-d824665b2a8a)
