### ISSUE TITLE
Migrate Jenkins Styleguide tests to run using Jenkinsfile

### ISSUE THREAD

**Issue by philschatz** [openstax/cnx-recipes#805]
# What happened?

The styleguide was not building on Jenkins which caused people to not be able to merge Pull Requests. See [Slack Discussion](https://openstax.slack.com/archives/C0LA54Q5C/p1548795572554500)

# Reproducibility Details

All new Pull Requests

# Environment:

GitHub

# Screenshots

![image](https://user-images.githubusercontent.com/253202/51952294-8e250680-23fd-11e9-8ef2-f0981aa71317.png)

# Additional notes

**Comment by tomjw64** [comment]
@philschatz does concourse build the styleguide now instead?

**Comment by brittweinstein** [comment]
@philschatz please create an issue card for this
