### ISSUE TITLE
Principles of Management: unwanted comment line or processing instruction appears in between paragraph

### ISSUE THREAD

**Issue by clteam18** [openstax/cnx-recipes#806]
# What happened?

In Chapter 14, under module **Process Theories of Motivation** unwanted comment line or processing instruction appears in between the paragraph as shown in screenshot.

# Environment:

- **Book(s)**: Principles of Management
- **URL/Server**: https://content02.cnx.org/contents/kAvMZRJp@3.1:uEJByd-U@2/1-3-Process-Theories-of-Motivation
- **Location (page number, chapter/section)**: Chapter 14 - m10639
- **Suggested nearby searchable text**: We may consider a 10 percent pay increase desirable until we find out that it was the lowest raise given in our work group.

# Screenshots

(_attach here (please clearly label what environment each screenshot came from)_)
![image](https://user-images.githubusercontent.com/39794953/51981857-4f08bb00-24ba-11e9-8ad7-cf0922d8adc4.png)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment]
@marcjeannott this likely needs dev input, but could you please take a look at the markup and copy either the markup or a screenshot of the markup into this issue?

**Comment by marcjeannott** [comment]
The module seems to be fine now? @openstaxalina I don't see the NOT_CONVERTED_YET: para

![2019-01-30_12-24-31](https://user-images.githubusercontent.com/33228728/52003646-c32b6a80-248a-11e9-8b20-64f69224560f.jpg)

**Comment by marcjeannott** [comment]
Ryan and I both couldn't see anything in the related paras `<emphasis effect="bold"><link target-id="ch14fig13" document=""/></emphasis> summarizes the three core concepts of expectancy theory. The theory states that our perceptions about our surroundings are essentially predictions about “what leads to what.” We perceive that certain effort levels result in certain performance levels. We perceive that certain performance levels result in certain outcomes. Outcomes can be <term>extrinsic</term>, in that others (our supervisor) determine whether we receive them, or <term>intrinsic</term>, in that we determine if they are received (our sense of achievement). Each outcome has an associated valence (outcome A’s valence is <m:math display="inline"><m:mrow><m:msub><m:mtext>V</m:mtext><m:mtext>a</m:mtext></m:msub></m:mrow></m:math>). Expectancy theory predicts that we will exert effort that results in the maximum amount of positive-valence outcomes.<footnote id="fs-idm406051536"><para id="fs-idm409782048">It can also be expressed as an equation:</para><equation id="fs-idm408251040" class="unnumbered"><label/><m:math display="block"><m:mrow><m:mtable columnalign="left"><m:mtr columnalign="left"><m:mtd columnalign="left"><m:mrow><m:mi>F</m:mi><m:mi>o</m:mi><m:mi>r</m:mi><m:mi>c</m:mi><m:mi>e</m:mi><m:mtext> </m:mtext><m:mtext>to</m:mtext></m:mrow></m:mtd><m:mtd columnalign="left"><m:mrow/></m:mtd><m:mtd columnalign="left"><m:mrow/></m:mtd></m:mtr><m:mtr columnalign="left"><m:mtd columnalign="left"><m:mrow><m:mtext>Choose</m:mtext></m:mrow></m:mtd><m:mtd columnalign="left"><m:mtext>=</m:mtext></m:mtd><m:mtd columnalign="left"><m:mrow><m:mtext>E1</m:mtext><m:mo>×</m:mo><m:mstyle displaystyle="true"><m:mo>∑</m:mo> <m:mrow><m:mrow><m:mo>(</m:mo><m:mrow><m:msub><m:mrow><m:mtext>E2</m:mtext></m:mrow><m:mtext>o</m:mtext></m:msub><m:mo>×</m:mo><m:msub><m:mtext>V</m:mtext><m:mtext>o</m:mtext></m:msub></m:mrow><m:mo>)</m:mo></m:mrow></m:mrow></m:mstyle></m:mrow></m:mtd></m:mtr><m:mtr columnalign="left"><m:mtd columnalign="left"><m:mrow><m:mtext>A level of Effort</m:mtext></m:mrow></m:mtd><m:mtd columnalign="left"><m:mrow/></m:mtd><m:mtd columnalign="left"><m:mrow/></m:mtd></m:mtr></m:mtable></m:mrow></m:math></equation><para id="fs-idm403642288">Where <m:math display="inline"><m:mrow><m:msub><m:mtext>V</m:mtext><m:mtext>o</m:mtext></m:msub></m:mrow></m:math> is the valence of a given outcome (o), and <m:math display="inline"><m:mrow><m:msub><m:mtext>E2</m:mtext><m:mtext>o</m:mtext></m:msub></m:mrow></m:math> is the perceived probability that a certain level of performance (e.g., Excellent, average, poor) will result in that outcome. So, for multiple outcomes, and different performance levels, the valence of the outcome and its associated performance➔outcome expectancy (E2) are multiplied and added to the analogous value for the other outcomes. Combined with the E1 (the amount of effort required to produce a level of performance), the effort level with the greatest <emphasis effect="italics">force</emphasis> associated with it will be chosen by the individual.</para></footnote> If our E1 or E2 is weak, or if the outcomes are not sufficiently desirable, our motivation to exert effort will be low. Stated differently, an individual will be motivated to try to achieve the level of performance that results in the most rewards.`

I also noticed that there's an emphasis tag on figure tags, this isn't necessary they're already bold.

**Comment by openstaxalina** [comment]
Republished the module, collection rebaked, and confirming I still see the not converted yet message.

@helenemccarron @brittany-johnson @tomjw64 This is a new issue that came in after sprint planning yesterday.  This may be symptomatic of a larger issue.  We've seen these messages before; Ross is even working on quashing some now, so it would be good to coordinate with him:

*original issue:* https://github.com/openstax/rhaptos.cnxmlutils/issues/162
*PR fix for original issue:* https://github.com/openstax/rhaptos.cnxmlutils/pull/166
*similar issue; unsure how this was resolved, but it looks like the resolution was part of the crit sit fix:* https://github.com/openstax/webview/issues/2124
*similar issue that Ross is working on now:* https://github.com/openstax/webview/issues/2100

**Comment by brittweinstein** [comment]
This is being resolved by another team.

**Comment by marcjeannott** [comment]
@openstaxalina good point! I've edited my comment above to show both paragraphs before and after the error.

**Comment by openstaxalina** [comment]
Thanks - confirming that there is no content actually missing here.  The error message seems to appear even though no content is actually missing.

**Comment by openstaxalina** [comment]
The decision is to **hide the `NOT_CONVERTED_YET` message** for now, since content is not actually missing.
cc @helenemccarron @reedstrm

**Comment by brittany-johnson** [comment]
Issue moved to [openstax/webview #2186](https://github.com/openstax/webview/issues/2186) via [**ZenHub**](https://www.zenhub.com/)

**Comment by brittany-johnson** [comment]
closing issue; moved to webview
