### ISSUE TITLE
Unstyled header in Review Questions

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#808]
On katalyst01 (https://katalyst01.cnx.org/contents/5CvTdmJL@5.8:7AAa2Rr2@5.8/Review-Questions) header **Art Connection** should be styled as other headers from Review Questions.

webview:

![unstyled](https://user-images.githubusercontent.com/40228854/51986666-04c71000-24a1-11e9-8599-5ffaeefc04de.JPG)

PDF:

![unstyled_pdf](https://user-images.githubusercontent.com/40228854/51986676-0b558780-24a1-11e9-982a-83830a47c129.JPG)

This is an only place whith such header.

**Comment by Adrianltd** [comment]
@openstaxalina 

In the content the `Art Connection` is a subtitle inside `Short Answer`.
![art-connection](https://user-images.githubusercontent.com/40228907/51992726-d56ad000-24ad-11e9-9208-344c2a32c0bc.png)
Shouldn't it be a separate feature? The difference between `Short Answer` header and `Art Connection` header is also that the first one is `h3` and the other one is `span`.

**Comment by openstaxalina** [comment]
I agree, this can be addressed in content.  I will move this issue over.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #588](https://github.com/openstax/content-managers/issues/588) via [**ZenHub**](https://www.zenhub.com/)
