### ISSUE TITLE
Footnotes in Review Questions

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#809]
In Microbiology list of references from module is placed at the bottom of the section in part called **Footnotes**. The problem occurs when sections **Review Questions** from EOC also have references.
I have found two cases.

1. Chapter 9

https://katalyst01.cnx.org/contents/5CvTdmJL@5.8:BmNSSmUC@5.8/Review-Questions

![ref](https://user-images.githubusercontent.com/40228854/51988634-76a15880-24a5-11e9-921a-b6947320208f.JPG)

It leads to section 9.6 (https://katalyst01.cnx.org/contents/5CvTdmJL@5.8:rWUqIvDC@3/9-6-Media-Used-for-Bacterial-Growth#footnote1)

![ref_lead](https://user-images.githubusercontent.com/40228854/51988695-9f295280-24a5-11e9-8261-0f48d4daf281.JPG)

In PDF the reference is on the same page:

![ref_pdf](https://user-images.githubusercontent.com/40228854/51988741-b7996d00-24a5-11e9-9f3f-454dc10c2311.JPG)

2. Chapter 15

https://katalyst01.cnx.org/contents/5CvTdmJL@5.8:92siotQR@5.8/Review-Questions

![ref2](https://user-images.githubusercontent.com/40228854/51988870-09da8e00-24a6-11e9-97b1-b12da0c4aed7.JPG)

This case is more complicated. First of all, number of reference is different than in PDF:

![ref2_pdf](https://user-images.githubusercontent.com/40228854/51988919-31315b00-24a6-11e9-9c3d-c17ca55a0d25.JPG)

Next, it leads to the section 15.1 (https://katalyst01.cnx.org/contents/5CvTdmJL@5.8:5hg9B7dw@3/15-1-Characteristics-of-Infectious-Disease#footnote4)

![ref2_lead](https://user-images.githubusercontent.com/40228854/51989013-650c8080-24a6-11e9-8016-e64af14e7911.JPG)

But in PDF in this section there are only 3 references:

![ref2_lead_pdf](https://user-images.githubusercontent.com/40228854/51989053-79e91400-24a6-11e9-9557-3f8712404255.JPG)

The 4th one in PDF is in section 15.2:

![ref3_pdf](https://user-images.githubusercontent.com/40228854/51989078-8bcab700-24a6-11e9-9bc0-d12197ede152.JPG)

On webview in this place reference has number 5:

![ref3](https://user-images.githubusercontent.com/40228854/51989129-a2710e00-24a6-11e9-8e90-9719667c9b39.JPG)

**Comment by openstaxalina** [comment]
1) Confirmed that the instance in Chapter 9, Review Questions (final review question) can be addressed in content by making it a parenthetical reference, similar to what we did here: https://github.com/openstax/content-managers/issues/313.  This is the last footnote in the chapter; it won't throw other footnote numbering off.

2) Confirmed that the instance in Chapter 15, Critical Thinking (question 31) can be addressed in content by making it a parenthetical reference, similar to what we did here: https://github.com/openstax/content-managers/issues/313.  This is the last footnote in the chapter; it won't throw other footnote numbering off.

3) This will be automatically resolved when 2) is resolved.

@wilkus27 I am going to move this to content managers.  Above, you noted 4 cases, but I only saw 3.  Please open a new issue if there is a fourth case.  Thank you!

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #602](https://github.com/openstax/content-managers/issues/602) via [**ZenHub**](https://www.zenhub.com/)
