### ISSUE TITLE
Clinical Focus before Learning Objectives

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#812]
On katalyst01(https://katalyst01.cnx.org/contents/5CvTdmJL@5.8:5XZItubD@3/13-1-Controlling-Microbial-Growth) note **Clinical Focus** appears above Learning Objectives. It should be right after that.

![order](https://user-images.githubusercontent.com/40228854/51998284-a0b04600-24b8-11e9-81ac-1aed458eeb40.JPG)

**Comment by Adrianltd** [comment]
That is because `Clinical Focus` is before the `Learning Objectives` in the RAW file.
![clinical-before-lo](https://user-images.githubusercontent.com/40228907/52049824-0a7b2f00-254f-11e9-9b99-8756254c6ca6.png)

cc: @openstaxalina

**Comment by openstaxalina** [comment]
Moving to content-managers so that the feature can be adjusted to be encoded after the learning objectives.
