### ISSUE TITLE
Remove release flags applied to all books

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#814]
it may have been `appendix-has-numbered-examples`

**Comment by tomjw64** [comment]
We should probably use a round table or set up a meeting to decide what is superfluous

**Comment by tomjw64** [comment]
I'm going to repurpose this issue since we determined that no release flags did not need to be release flags. The new purpose of this issue will be to remove feature flags that are already applied to all books and can finally be retired.
