### ISSUE TITLE
Microbiology Clinical Focus features snap to the top in #.1 modules

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#816]
# What happened?
Clinical Focus features are jumping to the tops of modules in the first module (not Intro module, the first real module) of each chapter I examined, and not in any other modules of the chapter:
Chapter 1
1.1 (NOT 1.2 or 1.3, where it stays in the right place)
6.1 (only the first one; there are two in this module. the other one stays where it is) (NOT 6.3 or 6.4)
7.1 (NOT 7.3 or 7.5)
8.1 (NOT 8.4, 8.5, 8.7)
9.1 (NOT 9.2, 9.4)

# Reproducibility Details

- **Does it also happen in an incognito window?**:  yes
- **Does this happen in one place, a few places, or everywhere?**: only the first non-intro module in every chapter

# Environment:

- **Book(s)**: Microbiology
- **URL/Server**: https://staging.cnx.org/contents/5CvTdmJL@6.1:6UoGDInj@5/1-1-What-Our-Ancestors-Knew
- **Location (page number, chapter/section)**: 1.1, 6.1, 7.1, 8.1, 9.1
- **Suggested nearby searchable text**:
- **Browser**: Firefox

# Screenshots
<img width="1376" alt="screen shot 2019-02-04 at 11 46 12 am" src="https://user-images.githubusercontent.com/1895432/52230416-e8e6b400-287c-11e9-9cee-24c196b7e4f2.png">

**Comment by openstaxalina** [comment]
Confirmed with Anthony that this is acceptable as-is.
