### ISSUE TITLE
Timeline appearing in different places in PDF vs Web View

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#817]
# What happened?

The timeline image in all opening modules (ex: 1.1, 2.1, 3.1) appears in differing places in the PDF vs Web View. In web view, the image always comes in after the "Learning Objectives" section, whereas in the PDF, the image may appear several paragraphs later.

# Reproducibility Details

- **Does it also happen in an incognito window?**: Yes
- **Does this happen in one place, a few places, or everywhere?**: Yes; This happens in all opening modules (ex: 1.1, 2.1, 3.1, etc.)

# Environment:

- **Book(s)**: US History
- **URL/Server**: https://staging.cnx.org/contents/p7ovuIkl@7.1:MTE_nlGh@7/10-1-A-New-Political-Style-From-John-Quincy-Adams-to-Andrew-Jackson
- **Location (page number, chapter/section)**: All starting modules 
- **Suggested nearby searchable text**: "The decline of federalism"
- **Browser**: Chrome

# Screenshots

![Screen Shot 2019-02-04 at 11.28.29 AM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/3a88eea3-ca49-493d-ba74-6cbb36cfaae7)

# Additional notes

n/a

**Comment by brittweinstein** [comment]
Link to Slack discussion about similar Clinical Focus in Microbiology: https://katalysteducation.slack.com/archives/CBW9DFKGF/p1548779989214100

**Comment by openstaxalina** [comment]
This is acceptable as is.  The content is appearing conceptually around the same place (first page of PDF, near top of webview page).
