### ISSUE TITLE
Read React doc (prof dev)

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#823]
# What happened?

(_Briefly but clearly describe the issue_)

# Reproducibility Details

- **Does it also happen in an incognito window?**: 
- **Does this happen in one place, a few places, or everywhere?**:

# Environment:

- **Book(s)**:
- **URL/Server**: 
- **Location (page number, chapter/section)**:
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots

(_attach here (please clearly label what environment each screenshot came from)_)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by brittany-johnson** [comment]
- [ ] [Read this article on ES6](https://hackernoon.com/es6-for-beginners-f98120b57414)
