### ISSUE TITLE
Enable `numbering-continuously` release flag for physics

### ISSUE THREAD

**Issue by tomjw64** [openstax/cnx-recipes#830]
It appears to be the only book that would be affected by enabling the flag

**Comment by lwtchu** [comment]
Tentatively putting this in crusty cronut. Will need Alan's input during sprint planning.

**Comment by openstaxalina** [comment]
Problem: The DevMath books use weird numbering, so we implemented numbering-continuously with a feature flag.  

We need to enable the feature flag everywhere; however, it should only affect physics.  We need to:

1. enable the flag everywhere
2. test  _College Physics_
3. ensure this did not cause changes in _College Physics_

We are positive that _College Physics_ is the only book impacted; Thomas ran compile.css and that was the only file that was changed.
