### ISSUE TITLE
Principles of Management: Managerial Decision Exercises

### ISSUE THREAD

**Issue by clteam18** [openstax/cnx-recipes#834]
# What happened?

Just noticed the title **Managerial Decisions Exercises** is differed from the PDF **Managerial Decision Exercises**. The word (Decision) has the singular meaning in PDF and (Decisions) plural meaning in Web view. Not sure, which is the correct one. Please advise.

# Environment:

- **Book(s)**: Principles of Management
- **URL/Server**: https://content02.cnx.org/contents/Oo8B9L0j@2.1:QYC_tZru@2.1/Managerial-Decisions-Exercises
- **Location (page number, chapter/section)**: All chapters

# Screenshots

PDF View:
![image](https://user-images.githubusercontent.com/39794953/52479674-70128f80-2bcf-11e9-8cf9-fb89a330207f.png)

Web View:
![image](https://user-images.githubusercontent.com/39794953/52479650-5bce9280-2bcf-11e9-9c3f-819180b13535.png)

**Comment by openstaxalina** [comment]
This should be "Decision".  We will adjust webview to make this change.

**Comment by brittany-johnson** [comment]
![screen shot 2019-02-21 at 3 40 04 pm](https://user-images.githubusercontent.com/24909007/53203717-8bc65e80-35ef-11e9-87cc-f75982886fe9.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/bdf45581-2c73-4c5b-bcd6-8a812e1bf88c)
