### ISSUE TITLE
U.S. History Answer Key Contains Too Many Answers

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#853]
# What happened?
The U.S. History recipe includes all answers to review questions.
The PDF only contains odd (every-other) answers.

# Reproducibility Details

- **Does it also happen in an incognito window?**: Yes
- **Does this happen in one place, a few places, or everywhere?**: Everywhere in the U.S. History Answer Key

# Environment:

- **Book(s)**: U.S. History
- **URL/Server**: https://cnx.org/contents/p7ovuIkl:zJpHYHIc/Answer-Key
- **Location (page number, chapter/section)**: Answer Key
- **Suggested nearby searchable text**: N/A
- **Browser**: All

# Screenshots
![ushistoryawak](https://user-images.githubusercontent.com/7863733/52881653-c5e4bb80-312a-11e9-88d6-2482f4a78dae.png)

**Comment by openstaxalina** [comment]
@helenemccarron FYI on this - 
I think that in this case, we _could_ display every-other, because there is only one question type with answers in the Answer Key (review questions).  From my understanding, displaying every-other would result in displaying only odd answers in this case.

If we don't want to implement displaying every-other, then we will need to suppress the Answer Key.  

We can definitely discuss at sprint planning or the next Katalyst meeting!

**Comment by MartaSztuka** [comment]
![screenshot from 2019-02-26 12-35-46](https://user-images.githubusercontent.com/47241114/53410157-475a0a80-39c3-11e9-9c6a-9719ec448098.png)
Now it's only odd numbers, however all the answers shows on one page, shall we leave it like this? If so, I'll close the issue.

**Comment by openstaxalina** [comment]
The Answer Key should be separated pages by chapter now.  @helenemccarron looked at the recipe that you baked _U.S. History_ with, and it does not have the composite chapters code.  @Adrianltd may be able to help ensure that you are able to bake the book with the most recent code.

**Comment by openstaxalina** [comment]
cc @MartaSztuka ^  thank you for testing this!

**Comment by MartaSztuka** [comment]
Great! Thanks :)

**Comment by MartaSztuka** [comment]
Answer Key works just fine; devides in separated chapters and answers in webview matches pdf.

![screenshot from 2019-02-28 17-04-43](https://user-images.githubusercontent.com/47241114/53580125-3bb14400-3b7b-11e9-81c6-78460ce4ade9.png)
