### ISSUE TITLE
Missing Key Equation subsections

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#856]
In PDF at the end of chapters (exept for 4th), after 'Key Terms' there is 'Key Equations', in webview it's missing.

https://katalyst01.cnx.org/contents/mwjClAV_@8.1:53MvscdH@8.1/Key-Terms

PDF:
![screenshot from 2019-02-18 13-02-06](https://user-images.githubusercontent.com/47241114/52955673-8b2e8d80-338d-11e9-9b92-91c8e2ea6f37.png)

This should be there in separated subsection. Thanks!

**Comment by MartaSztuka** [comment]
It's working, now, I've tested :)
![screenshot from 2019-02-20 11-25-03](https://user-images.githubusercontent.com/47241114/53084987-37918080-3502-11e9-8636-917d72709685.png)

**Comment by Adrianltd** [comment]
@MartaSztuka This issue does not exists.
