### ISSUE TITLE
Standardize padding and margin for elements

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#858]
@brittany-johnson commented on [Thu Feb 07 2019](https://github.com/openstax/oer.exports/issues/3876)

# What happened?
Spacing issues pop up almost every milestone, if we can account for how much margin/padding elements should have and which elements margin/padding shouldn't be directly added to, etc. I think it could save us a lot of pain in the future (baked-pdf, unified, etc.) 

Possible brainstorming ideas:
- we only use margin, wherever possible, since margin can be collapsed.
- we never use padding/margin top
- we apply padding/margin bottom to inline elements
- we remove bottom padding/margin to block elements (containing inline elements) unless they follow another block element?

# Additional notes
Past margin/padding issues: 
https://github.com/openstax/oer.exports/issues/3866

---

@brittany-johnson commented on [Mon Feb 18 2019](https://github.com/openstax/oer.exports/issues/3876#issuecomment-464806043)

Issue Example: https://github.com/openstax/oer.exports/pull/3883

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #772](https://github.com/openstax/content-managers/issues/772) via [**ZenHub**](https://www.zenhub.com/)
