### ISSUE TITLE
Webview missing rules (squers)

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#863]
I PDF Functions (and not functions) are drawn on ruled field, in webview it's on plain.

PDF:
![screenshot from 2019-02-19 09-28-25](https://user-images.githubusercontent.com/47241114/53000858-9636fb80-3429-11e9-884e-2d16159f38be.png)

Webview:
![screenshot from 2019-02-19 09-28-14](https://user-images.githubusercontent.com/47241114/53000868-9b944600-3429-11e9-89da-9aa188051a36.png)

I don't know wether it's important, or not, but feels like this should be unified, Thanks!

**Comment by Adrianltd** [comment]
This is probably an enhancement in webview, I don't think it's an issue. cc @openstaxalina

**Comment by openstaxalina** [comment]
Similar to #866, this looks to be an update to the webview that did not make it to PDF yet.  I am closing this issue.
