### ISSUE TITLE
Missing space between numbers and text.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#864]
In PDF we have 'Try It #10' and task:

![screenshot from 2019-02-19 09-42-16](https://user-images.githubusercontent.com/47241114/53002056-19595100-342c-11e9-8235-ee6550b1be90.png)

In webview Its 'Try' and additionally 'Exercise 10Evaluate the following' without space.

![screenshot from 2019-02-19 09-42-35](https://user-images.githubusercontent.com/47241114/53002221-78b76100-342c-11e9-8ff5-ddd1bc576234.png)

This issue occures in all book, needs to be fixed altogether with other 'try it' issues

**Comment by helenemccarron** [comment]
@Adrianltd there's a way to number Try Its in the config file, see dev math or statistics.

**Comment by MartaSztuka** [comment]
It's fixed
