### ISSUE TITLE
Equations and captions misplaced

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#865]
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:EyqJ6FuE@5/A-Basic-Functions-and-Identities

1. In PDF, equations are on the left upper corner of coordinate system, in webview it's in various places.
2. In PDF, caption 'Figure A1, A2, A3' etc is in the middle bellow, in webview its on the left.
3. In PDF it's 'A1 Graphs of the Parent Functions' in webview 'A1' part is missing.
4. In PDF, Table A1 has titles: Identities&Equations, in webview it;s missing.

PDF:
![screenshot from 2019-02-19 10-45-54](https://user-images.githubusercontent.com/47241114/53007275-321b3400-3437-11e9-954e-82007b859298.png)

ad.4
![screenshot from 2019-02-19 11-20-13](https://user-images.githubusercontent.com/47241114/53007869-6b07d880-3438-11e9-9d92-54efc8867563.png)

webview:
![screenshot from 2019-02-19 10-45-44](https://user-images.githubusercontent.com/47241114/53007305-44956d80-3437-11e9-8fa1-cf2902170ca0.png)

Caption should be centerd, and equations fixed in one place.

**Comment by Adrianltd** [comment]
@MartaSztuka 
Ad 1. If that's an issue (I believe not), it's a matter of changing the image 
Ad 2. Also not an issue, webview version is correct.
Ad 3. Could you check if that's the only spot missing or all headings need that?
Ad 4. Could you provide a link & screenshots of that spot?

cc @openstaxalina for the ad 1 and ad 2.

**Comment by Adrianltd** [comment]
Ad 4. that table has no title nor caption in the RAW.
![precalc-table](https://user-images.githubusercontent.com/40228907/53019540-41a97580-3455-11e9-9006-b71f028af38c.png)

**Comment by openstaxalina** [comment]
Issues 3 and 4 are a result of the PDFs being created in InDesign, and the creators applying special labels ("A1, A3" etc.) by hand.  We will have to live with this discrepancy.  I am closing this issue.
