### ISSUE TITLE
Missing 'f' and and lowercase 'Y'

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#866]
In webview y is lowercase, in PDF it's uppercase, also in webview curve has 'f', in PDF it doesn't.

PDF:
![screenshot from 2019-02-19 11-44-51](https://user-images.githubusercontent.com/47241114/53010151-6e519300-343d-11e9-9787-25c5b7540549.png)

webview:
![screenshot from 2019-02-19 11-44-30](https://user-images.githubusercontent.com/47241114/53010167-76113780-343d-11e9-8ac3-54ce6b7c3e14.png)

'Y' should be uppercase for sure, however I don't really know weather this 'F' should be there or not, might be content issue.

https://katalyst01.cnx.org/contents/_VPq4foj@8.1:n0GR2nhc@7/12-1-Finding-Limits-Numerical-and-Graphical-Approaches

**Comment by Adrianltd** [comment]
Not an issue. cc @openstaxalina

**Comment by openstaxalina** [comment]
Agree with @Adrianltd that this was a content change, likely to fix errata.  The webview is correct. Unfortunately, the PDF is not updated as frequently as the webview.  

Therefore, I am going to close this issue.
