### ISSUE TITLE
Composite End of Chapter Pages

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#870]
When an EOC is using a container for the EOC sections, the TOC should break them down into composite chapters and composite pages (extra TOC intro and individual pages)

Books affected:
- u-physics
- astronomy
- dev-math
- microbiology
- ap-physics
- american-government
- ap-biology
- chemistry
- history
- econ
- accounting
- entrepreneurship
- business-ethics

**Comment by helenemccarron** [comment]
Addressed in PR https://github.com/openstax/cnx-recipes/issues/870

**Comment by MartaSztuka** [comment]
@helenemccarron  on Friday and today I've been testing books from your list, here's how it looks:
![screenshot from 2019-02-25 13-33-19](https://user-images.githubusercontent.com/47241114/53338173-57121a00-3903-11e9-812d-2f28a4ed640a.png)

as you can see not bad :) I'll doble check today, all those 'problematic' ones, Thanks!

**Comment by helenemccarron** [comment]
I think it's working. on https://easyvm5.cnx.org/contents/kg0cimBs@9.1:t3c50VLA@9.1/Chapter-1
![2019-02-26_15-27-19](https://user-images.githubusercontent.com/8514591/53447605-138adf00-39db-11e9-9717-52ff7a5d5c6e.png)

**Comment by Stackblocks** [comment]
I'm also seeing it working on easyvm5.cnx.org. Closing this and will double check during regression testing.
