### ISSUE TITLE
Exercises number 0

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#873]
1. In every chapter first subsection has exercise number 0 only
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:lSD_nZ3v@13/2-1-Linear-Functions

Webview:
![screenshot from 2019-02-20 16-51-48](https://user-images.githubusercontent.com/47241114/53105999-73443e80-3532-11e9-8824-29cc2427e36c.png)
![screenshot from 2019-02-20 16-52-01](https://user-images.githubusercontent.com/47241114/53106009-77705c00-3532-11e9-9843-59b8a07b4fef.png)

PDF:
![screenshot from 2019-02-20 16-53-23](https://user-images.githubusercontent.com/47241114/53105981-6cb5c700-3532-11e9-841d-5e2859efe572.png)

**Comment by Adrianltd** [comment]
Another duplicate of https://github.com/openstax/cnx-recipes/issues/846

**Comment by MartaSztuka** [comment]
Now it's all good!
