### ISSUE TITLE
baked Astronomy figure numbers missing in staging preface

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#879]
@openstaxalina commented on [Fri Feb 01 2019](https://github.com/openstax/content-managers/issues/596)

@oscryan commented on [Mon Dec 10 2018](https://github.com/openstax/cnx-recipes/issues/747)

Assignable webview (baked) Astronomy on staging has lost figure numbering in the preface; it's not content, since they are definitely numbered in legacy webview.

# Reproducibility Details

- **Does this happen in one place, a few places, or everywhere?**: happens on staging.cnx.org where I am testing

# Environment:

- **Book(s)**: Astronomy 
- **URL/Server**: https://staging.cnx.org/contents/LnN76Opl@15.1:t5W09zMY@11/Preface
- **Location (page number, chapter/section)**: preface
- **Suggested nearby searchable text**: pluto close up
- **Browser**: Firefox

# Screenshots

staging.cnx.org:
<img width="1415" alt="screen shot 2018-12-10 at 3 07 07 pm" src="https://user-images.githubusercontent.com/1895432/49761686-6206c800-fc8d-11e8-8953-e9d792077ab2.png">

---

@Adrianltd commented on [Tue Dec 11 2018](https://github.com/openstax/cnx-recipes/issues/747#issuecomment-446303399)

@oscryan Can you rebake `astronomy` and make sure (https://staging.cnx.org/a/content-status/) it's baked with the correct recipe?
I have checked this on `katalyst01` and locally and `figures` in the `preface` are numbered.

**Katalyst01**
![image](https://user-images.githubusercontent.com/40228907/49820396-11b86480-fd78-11e8-8457-b5082bee52b4.png)
**Locally, straight from the master branch**
![image](https://user-images.githubusercontent.com/40228907/49820366-fd746780-fd77-11e8-839c-f2ba5e37fba7.png)

If that's not the case, maybe the content on `katalyst01` and on `staging` is different? 
cc: @helenemccarron 

<blockquote><div><strong><a href="https://staging.cnx.org/a/content-status/">GOB - staging.cnx.org</a></strong></div></blockquote>

---

@oscryan commented on [Tue Dec 11 2018](https://github.com/openstax/cnx-recipes/issues/747#issuecomment-446334396)

rebaked and it's definitely the right recipe, still no figure numbers in the preface

---

@Adrianltd commented on [Tue Dec 11 2018](https://github.com/openstax/cnx-recipes/issues/747#issuecomment-446352588)

@oscryan have you cleared the cache on the server?

---

@oscryan commented on [Tue Dec 11 2018](https://github.com/openstax/cnx-recipes/issues/747#issuecomment-446353246)

No, but version history in webview confirms the content was rebaked twice today.

---

@openstaxalina commented on [Tue Dec 11 2018](https://github.com/openstax/cnx-recipes/issues/747#issuecomment-446389011)

@Adrianltd This is the first time we've baked this book on staging, and the other recipe changes **are** showing.  I am not sure why the figure numbers in the preface are **not** showing.  Are you sure the PR for that was merged to webview before December 7?

---

@helenemccarron commented on [Tue Dec 11 2018](https://github.com/openstax/cnx-recipes/issues/747#issuecomment-446393748)

A quick look at the content shows that both images are different: 
![2018-12-11_16-43-52](https://user-images.githubusercontent.com/8514591/49835185-0c511f00-fd64-11e8-9d78-830854a89d4d.png)

The fig. on Katalyst has a title vs a caption on staging. I don't know which one is right but it seems that the recipes are expecting a title. I am inclined to say that Katalyst's content is newer than staging but I might be wrong.

---

@helenemccarron commented on [Tue Dec 11 2018](https://github.com/openstax/cnx-recipes/issues/747#issuecomment-446396064)

Staging:
```
<figure id="OSC_Astro_23_04_Pulsar"><media id="fs-id1163975737628" alt="Model of a Pulsar. In this illustration the Earth is drawn below center, in the path of an approaching &#x201C;Beam of particles and radiation&#x201D;. The pulsar, labeled &#x201C;Neutron star&#x201D;, is drawn at upper right as a blue sphere. Its rotation axis is drawn vertically upward, with a counter-clockwise arrow around it indicating the direction of rotation. The magnetic field lines are drawn in a plane perpendicular to the rotation axis as concentric red ellipses on either side of the star. The field lines intersect the surface of the star at the &#x201C;North magnetic pole&#x201D;, which faces Earth, and the &#x201C;South magnetic pole&#x201D;, which faces toward upper right. The beam of radiation is emitted from the poles of the magnetic field, and extend toward upper right and lower left.">
<image mime-type="image/jpeg" src="OSC_Astro_23_04_Pulsar.jpg"/>
</media>
<caption>How a Pulsar Beam Sweeps over Earth.</caption></figure>
```

katalyst01:
```
<figure id="OSC_Astro_23_04_Pulsar"><title>How a Pulsar Beam Sweeps over Earth.</title><media id="fs-id1163975737628" alt="Model of a Pulsar. In this illustration the Earth is drawn below center, in the path of an approaching &#x201C;Beam of particles and radiation&#x201D;. The pulsar, labeled &#x201C;Neutron star&#x201D;, is drawn at upper right as a blue sphere. Its rotation axis is drawn vertically upward, with a counter-clockwise arrow around it indicating the direction of rotation. The magnetic field lines are drawn in a plane perpendicular to the rotation axis as concentric red ellipses on either side of the star. The field lines intersect the surface of the star at the &#x201C;North magnetic pole&#x201D;, which faces Earth, and the &#x201C;South magnetic pole&#x201D;, which faces toward upper right. The beam of radiation is emitted from the poles of the magnetic field, and extend toward upper right and lower left.">
<image mime-type="image/jpeg" src="OSC_Astro_23_04_Pulsar.jpg"/>
</media>
</figure>
```

---

@Adrianltd commented on [Thu Dec 13 2018](https://github.com/openstax/cnx-recipes/issues/747#issuecomment-446933935)

@openstaxalina can you confirm which content is more up to date (katalyst01 vs staging)? If staging is newer, I will need an update on katalyst before I'll deliver a new way of numbering figures.

---

@openstaxalina commented on [Fri Dec 14 2018](https://github.com/openstax/cnx-recipes/issues/747#issuecomment-447479378)

@Adrianltd This issue is challenging to track down.  I'm moving this to the backlog until I can talk with the content team.

---

@openstaxalina commented on [Fri Dec 14 2018](https://github.com/openstax/cnx-recipes/issues/747#issuecomment-447479898)

Links for reference:
preface on staging: https://staging.cnx.org/contents/LnN76Opl@17.1:t5W09zMY@11/Preface
preface on katalyst01: https://katalyst01.cnx.org/contents/LnN76Opl@14.24:t5W09zMY@10/Preface
preface on production: https://cnx.org/contents/LnN76Opl@14.33:t5W09zMY@12/Preface

closed Astronomy issues in content-managers: https://github.com/Connexions/content-managers/issues?q=is%3Aissue+label%3Abook%3Aastronomy+is%3Aclosed
closed Astronomy issues in webview: https://github.com/Connexions/webview/issues?q=is%3Aissue+label%3Abook%3Aastronomy+is%3Aclosed
open and closed Astronomy issues in cnx-recipes: https://github.com/Connexions/cnx-recipes/issues?q=is%3Aissue+label%3Abook%3Aastronomy+is%3Aopen

<blockquote><div><strong><a href="https://staging.cnx.org/contents/LnN76Opl@17.1:t5W09zMY@11/Preface">OpenStax CNX</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://katalyst01.cnx.org/contents/LnN76Opl@14.24:t5W09zMY@10/Preface">OpenStax CNX</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://cnx.org/contents/LnN76Opl@14.33:t5W09zMY@12/Preface">OpenStax CNX</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://github.com/Connexions/content-managers/issues?q=is%3Aissue+label%3Abook%3Aastronomy+is%3Aclosed">Page not found · GitHub</a></strong></div></blockquote>
<blockquote><img src="https://avatars2.githubusercontent.com/u/772455?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/Connexions/webview">Connexions/webview</a></strong></div><div>Connexions web site. Contribute to Connexions/webview development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars2.githubusercontent.com/u/772455?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/Connexions/cnx-recipes">Connexions/cnx-recipes</a></strong></div><div>The extended CSS recipes for cooking openstax books - Connexions/cnx-recipes</div></blockquote>

---

@brittweinstein commented on [Mon Dec 17 2018](https://github.com/openstax/cnx-recipes/issues/747#issuecomment-447915071)

@oscryan will migrate the preface from production to staging and katalyst to check this.

---

@openstaxalina commented on [Fri Feb 01 2019](https://github.com/openstax/cnx-recipes/issues/747#issuecomment-459783404)

I think that if we change the figure captions to figure titles, this issue will be resolved.  Moving to content-managers.

---

@openstaxalina commented on [Fri Feb 01 2019](https://github.com/openstax/content-managers/issues/596#issuecomment-459783818)

Please change the figure captions to figure titles in the Astronomy preface, wait for the book to rebake and ensure that figures are numbered in the preface.

---

@oscryan commented on [Thu Feb 07 2019](https://github.com/openstax/content-managers/issues/596#issuecomment-461621528)

I put the text from captions into titles. No change: still no figure numbers.
https://staging.cnx.org/contents/LnN76Opl@18.3:t5W09zMY@15/Preface

<blockquote><div><strong><a href="https://staging.cnx.org/contents/LnN76Opl@18.3:t5W09zMY@15/Preface">OpenStax CNX</a></strong></div></blockquote>

---

@openstaxalina commented on [Thu Feb 21 2019](https://github.com/openstax/content-managers/issues/596#issuecomment-466047336)

@oscryan would you be able to make the same content adjustment on katalyst01 so that Katalyst developers can replicate and test this?  (cc @lwtchu )

---

@oscryan commented on [Thu Feb 21 2019](https://github.com/openstax/content-managers/issues/596#issuecomment-466057719)

They are already like that on katalyst01.

---

@openstaxalina commented on [Fri Feb 22 2019](https://github.com/openstax/content-managers/issues/596#issuecomment-466431239)

Need to talk with Katalyst devs about this.

**Comment by openstaxalina** [comment]
@Adrianltd FYI - this is the issue we discussed at the meeting on Thursday. Ryan double-checked that the figure markup on production matches katalyst01.

**Comment by Adrianltd** [comment]
@wilkus27 has just rebaked Astronomy on `katalyst01`
Still I can't see the issue on this server:
https://katalyst01.cnx.org/contents/LnN76Opl@14.24:t5W09zMY@10/Preface
How can I make sure that the content has changed? Latest Revision date is `Nov 22, 2018` on katalyst01.

https://staging.cnx.org/contents/LnN76Opl@17.1:t5W09zMY/Preface the numbering of figure's exists
if you look at the newer content it disappears
https://staging.cnx.org/contents/LnN76Opl@19.1:t5W09zMY@16/Preface

This is how example figure looks like in a RAW on `katalyst01` and how it should look like in order to work properly:
![figure-astronomy](https://user-images.githubusercontent.com/40228907/53337389-8c1d6d00-3901-11e9-8ddd-fc9457e36013.png)

cc: @openstaxalina @helenemccarron @oscryan

**Comment by helenemccarron** [comment]
I believe this is due to the `preface` class missing on staging:
![2019-02-26_16-49-08](https://user-images.githubusercontent.com/8514591/53452307-8a79a500-39e6-11e9-8aba-b2ab098cb200.png)

vs katalyst
![2019-02-26_16-49-22](https://user-images.githubusercontent.com/8514591/53452304-89487800-39e6-11e9-844d-df2e0a88f4e5.png)


cc @Adrianltd @openstaxalina  and @oscryan

**Comment by lwtchu** [comment]
<img width="870" alt="screen shot 2019-02-26 at 6 47 15 pm" src="https://user-images.githubusercontent.com/11299125/53457184-05e35280-39f7-11e9-9074-98445dd46f39.png">
Missing `preface` class in the document tag. Verified fix on Production.
