### ISSUE TITLE
Figure numbering is wrong

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#880]
# What happened? In PDF examples that refers to Figure 6 have caption: Figure 6a, and Figure 6b
In webview Figure numbers are always one ahead; there is Figure 7 with examples Figure 8.7a and Figure 8.7b, also they are linked to the picture right below.

- **Browser**: https://katalyst01.cnx.org/contents/mwjClAV_@8.1:mdOHcEnH@11/8-1-The-Ellipse#Figure_10_01_005

# Screenshots
PDF:
![screenshot from 2019-02-26 13-29-19](https://user-images.githubusercontent.com/47241114/53417410-d112d380-39d5-11e9-9847-09d7f90db1d0.png)

webview:

![screenshot from 2019-02-26 13-30-12](https://user-images.githubusercontent.com/47241114/53417529-16370580-39d6-11e9-8258-5dd4cd57588f.png)
![screenshot from 2019-02-26 13-30-23](https://user-images.githubusercontent.com/47241114/53417541-1afbb980-39d6-11e9-881f-cd360ade3324.png)

**Comment by brittweinstein** [comment]
@theresamasciale please put points on this when you can

**Comment by oscryan** [comment]
This is a difference in XYZ pdf numbering and current webview numbering. Katalyst is apparently already working on removing the chapter prefix (the first number in #.# of figure numbers) from webview for the XYZ books; the next step would be to determine what is numbering in webview that's not in the pdf that makes this figure 7 instead of 6. Let's not forget to check collating material.

**Comment by theresamasciale** [comment]
Issue seems to be with the PDF -- The figure numbering restarts with module 1, so there are two "figure 1's" for each chapter (one in the intro and one in the regular chapter). 

PDF:

![Screen Shot 2019-03-04 at 3.56.16 PM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/0c96b377-a51b-44ac-9646-127caa8bd4e4)

![Screen Shot 2019-03-04 at 3.56.25 PM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/7b62a9e2-2b5e-4b24-8845-7d35ecc675cf)

**Comment by openstaxalina** [comment]
@theresamasciale could you post the markup when you get a chance?  it should include the markup that contains the link to the figure as well as the markup for the figure itself.

**Comment by theresamasciale** [comment]
Here is the markup for the initial splash image:

![Screen Shot 2019-03-05 at 9.19.19 AM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/64d4d47a-9664-4e05-b0f9-7d8184941935)

And here is the markup for the following figure (first in the initial module)

![Screen Shot 2019-03-05 at 9.19.58 AM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/138f5fce-4b7b-4d9d-bd2d-a36f92009589)

**Comment by openstaxalina** [comment]
We also confirmed that where "Figure 8.7a" displays, it **is** correctly targeting Figure 7 (with the figure ID).  Therefore, this seems to be a bug where the correct anchor text is not being generated.

**Comment by openstaxalina** [comment]
**Decision:** Do not number the figure in the introduction module (it will have class="splash") _**in the config file only**_ - do not make this change for any books besides _Precalculus_, _College Algebra_, _Algebra & Trigonometry_.  

For the links to figures, look at whether it's possible to remove the chapter number to display only the figure number.

**Comment by MartaSztuka** [comment]
At first glance it's fixed, will check again before closing.
![asdfghjk](https://user-images.githubusercontent.com/47241114/55172454-5f67aa00-517a-11e9-8ecd-f56247c0bf5e.jpeg)

**Comment by uskka** [comment]
Precalculus looks good, I found only one problem in one section but its related to one of the figures being unnumbered in webview, I created an issue in content-managers repository about it. Screen from 10.8 
https://katalyst01.cnx.org/contents/_VPq4foj@8.4:NcxRNUfa@8/10-4-Rotation-of-Axes

Webview
<img width="674" alt="Screenshot 2019-04-04 at 17 33 43" src="https://user-images.githubusercontent.com/40228918/55568480-124a8180-5700-11e9-99c4-e899387aceec.png">

PDF
<img width="668" alt="Screenshot 2019-04-04 at 17 33 34" src="https://user-images.githubusercontent.com/40228918/55568488-14144500-5700-11e9-9ec0-90a309394d0b.png">

Algebra and Trigonometry looks good too. Screen from 10.4. https://katalyst01.cnx.org/contents/E6wQevFf@11.1:pj7U1aMb@10/10-4-Polar-Coordinates-Graphs

Webview

<img width="570" alt="Screenshot 2019-04-04 at 17 56 28" src="https://user-images.githubusercontent.com/40228918/55570215-3e1b3680-5703-11e9-9fba-b1de55adf08f.png">

PDF

<img width="748" alt="Screenshot 2019-04-04 at 17 56 23" src="https://user-images.githubusercontent.com/40228918/55570234-48d5cb80-5703-11e9-95ec-49fccdfcace5.png">
