### ISSUE TITLE
Remove feature flags that are enabled for all books

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#883]

**Comment by brittweinstein** [comment]
@tomjw64 is this ready for testing?

**Comment by tomjw64** [comment]
@brittweinstein Not necessary to regression test. CSS was left unchanged. Just needs review before it can ship to the milestone branch

**Comment by tomjw64** [comment]
@brittweinstein Not necessary to regression test. CSS was left unchanged. Just needs review before it can ship to the milestone branch
