### ISSUE TITLE
Wrong captions

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#888]
In Learning Objectivies in whole book captions are different i PDF and webview.
https://katalyst01.cnx.org/contents/i4nRcikn@3.7:MM9PEdsz@4/5-1-Approximating-Areas

PDF:
![screenshot from 2019-02-27 12-45-54](https://user-images.githubusercontent.com/47241114/53488148-bd2aa880-3a8d-11e9-9a32-1ae4da582ac3.png)

webview:
![screenshot from 2019-02-27 12-47-02](https://user-images.githubusercontent.com/47241114/53488185-ddf2fe00-3a8d-11e9-881f-d732230c65fb.png)

Same issue occures in every chapter, every subsection at the begining.

**Comment by wilkus27** [comment]
@helenemccarron I'm not sure in which way it should be resolved. The list in abstract is just a regular `<ul>` without any data-type or class: 

![calculus_lo](https://user-images.githubusercontent.com/40228854/53955503-7403d580-40d9-11e9-95e5-1ddfbb1a11d9.JPG)

I've checked and I didn't find any other book with numbered list in abstract. Probably Calculus is the only one textbook with such case.

I guess there are two ways to resolve it.

1. First one:
- maybe  `<ul>` lists should be changed to `<ol>` list with `type=1` and some class (e.g `class="abstractList"`) in content
- then we could use Patryks mixin:

![list_mixin](https://user-images.githubusercontent.com/40228854/53956137-18d2e280-40db-11e9-9b83-9c101f092146.JPG)

Probably it would have to be modified a bit, I'm not sure at this moment how much.

2. Second one:
- maybe new mixin should be created only for lists in abstract
- it could change the container to `<ol>` and add some class (if it is needed)
- what kind of output we want to get then? Similar to output from the mixin above:

![stepwise](https://user-images.githubusercontent.com/40228854/53956716-a7942f00-40dc-11e9-80fb-f09e8554f99b.JPG)

So `<ol>` with `os-class` and `<li>` with additional `<span>'s` inside?

**Comment by openstaxalina** [comment]
**Decision:** Try to target the list by its place within the Learning Objectives.  If not, may need to add a class in the content.

**Comment by MartaSztuka** [comment]
Issue is fixed
![Screenshot from 2019-03-29 14-37-08](https://user-images.githubusercontent.com/47241114/55236742-eecf9480-5230-11e9-9882-9197904e6937.png)
![Screenshot from 2019-03-29 14-38-37](https://user-images.githubusercontent.com/47241114/55236748-f2631b80-5230-11e9-82bf-ff0132488c3d.png)
![Screenshot from 2019-03-29 14-39-11](https://user-images.githubusercontent.com/47241114/55236752-f42cdf00-5230-11e9-8ae1-8dcbc9f657bc.png)

**Comment by uskka** [comment]
I am unable to test volume 1 because of a problem with baking this book on katalyst01. But it works on volume 2 and 3. 
@helenemccarron  approved that testing on two volumes is enough before regression testing.
 I created a new issue for removing the bullet list that can be tracked here https://github.com/openstax/webview/issues/2247


<img width="992" alt="Screenshot 2019-04-12 at 12 18 38" src="https://user-images.githubusercontent.com/40228918/56030449-294f2c00-5d1d-11e9-8a8f-ce1614264a4f.png">

<img width="1188" alt="Screenshot 2019-04-12 at 12 11 57" src="https://user-images.githubusercontent.com/40228918/56030132-6666ee80-5d1c-11e9-8ab6-d593b46a5ebf.png">

**Comment by MartaSztuka** [comment]
Volume 1 looks good too. Tested on katalyst01
![Screenshot from 2019-04-18 16-55-11](https://user-images.githubusercontent.com/47241114/56370110-f44e4800-61fa-11e9-8912-4f5d3d1d2c8d.png)
