### ISSUE TITLE
Headline in Examples aren't bold

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#889]
In webwiev in Example section headline is written same style as text below. In PDF it's it's thicken.
https://katalyst01.cnx.org/contents/i4nRcikn@3.7:MM9PEdsz@4/5-1-Approximating-Areas

PDF:
![screenshot from 2019-02-27 13-06-01](https://user-images.githubusercontent.com/47241114/53491990-0b44a980-3a98-11e9-8766-6184c5dacb4f.png)
 webview:
![screenshot from 2019-02-27 13-06-10](https://user-images.githubusercontent.com/47241114/53492012-1566a800-3a98-11e9-8345-74c8dcfe3929.png)

Problem occures in whole book

**Comment by openstaxalina** [comment]
If it's possible to target them -- likely in a title element-  headers should be bold as @MartaSztuka suggested.  cc @wilkus27

**Comment by openstaxalina** [comment]
It seems like these can be targeted using `data-type="title":`
![Screen Shot 2019-03-25 at 1 19 53 PM](https://user-images.githubusercontent.com/7863733/54944098-b82c0e00-4f00-11e9-98e3-ac5c5dce6f51.png)

**Comment by openstaxalina** [comment]
If markup is inconsistent, we need to standardize the markup for Example titles.

**Comment by uskka** [comment]
Looks good. Tested on katalyst01.

<img width="958" alt="Screenshot 2019-04-03 at 12 23 11" src="https://user-images.githubusercontent.com/40228918/55471973-50b24480-560b-11e9-9719-329b2d74fed3.png">
