### ISSUE TITLE
Missing equation numbers

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#893]
In webview equations don't have numbers.
https://katalyst01.cnx.org/contents/i4nRcikn@3.7:blZd_oDf@5/1-3-Trigonometric-Functions

![screenshot from 2019-03-04 11-46-59](https://user-images.githubusercontent.com/47241114/53731329-ae236c00-3e7a-11e9-8c0f-dcb0e6ee7af4.png)

**Comment by wilkus27** [comment]
@MartaSztuka Ready for test.

**Comment by MartaSztuka** [comment]
I've tested all examples where numbers were missing, looks great, thanks!
https://katalyst01.cnx.org/contents/i4nRcikn@3.7:blZd_oDf@5/1-3-Trigonometric-Functions
![equations](https://user-images.githubusercontent.com/47241114/53869153-e7cdb180-3ff7-11e9-88f5-dd5a85a66569.jpeg)
