### ISSUE TITLE
WAITING (resolve in content) Accounting footnote problems

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#896]
# What happened?

Footnote in table fake title does not render or link properly in webview. The footnote numbering also does not match the pdf.

# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: at least one place

# Environment:

- **Book(s)**: Managerial Accounting
- **URL/Server**: https://staging.cnx.org/contents/kg0cimBs@7.1:c1rkI4iy@3/10-4-Evaluate-and-Determine-Whether-to-Keep-or-Discontinue-a-Segment-or-Product
- **Location (page number, chapter/section)**: 10.4
- **Suggested nearby searchable text**: examples of company segments
- **Browser**: Firefox

# Screenshots

screenshot is from https://staging.cnx.org/contents/kg0cimBs@7.1:c1rkI4iy@3/10-4-Evaluate-and-Determine-Whether-to-Keep-or-Discontinue-a-Segment-or-Product but the issue is also present on production:
<img width="1006" alt="screen shot 2019-03-05 at 3 04 47 pm" src="https://user-images.githubusercontent.com/1895432/53837411-201db300-3f58-11e9-854c-c67793958df9.png">

**Comment by openstaxalina** [comment]
In this case, we will move the footnote into the table caption.  This type of issue will be resolved with #566; however, this is out-of-scope for the current sprint.

**Comment by oscryan** [comment]
You want me to do that now?
