### ISSUE TITLE
Check Your Understanding unstyled

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#897]
# What happened?

Check Your Understanding features were never styled.

# Reproducibility Details

- **Does it also happen in an incognito window?**:  yes
- **Does this happen in one place, a few places, or everywhere?**: everywhere

# Environment:

- **Book(s)**: College Physics
- **URL/Server**: https://staging.cnx.org/contents/Ax2o07Ul@15.1:S7pqHKDm@11/1-3-Accuracy-Precision-and-Significant-Figures
- **Location (page number, chapter/section)**: all
- **Suggested nearby searchable text**: a high school track coach
- **Browser**:

# Screenshots
<img width="568" alt="screen shot 2019-03-05 at 3 54 44 pm" src="https://user-images.githubusercontent.com/1895432/53840156-05027180-3f5f-11e9-91c0-5013c9ce7e43.png">

**Comment by openstaxalina** [comment]
The Check Your Understanding is an `exercise` with` div data-type="title"`.

**Comment by wilkus27** [comment]
@openstaxalina  I did small investigation. **Check Your Understanding** in `College Physics` and `College Physics for AP Courses` looks exactly the same in PDF:

**College Physics**

![image](https://user-images.githubusercontent.com/40228854/57919008-31f4ce00-7898-11e9-8855-2e5960382b25.png)

**College Physics for AP Courses**

![image](https://user-images.githubusercontent.com/40228854/57919056-4f299c80-7898-11e9-8870-44bb4a6ca8e8.png)

This is how this part of book is styled on webview for `AP Physics`:

![image](https://user-images.githubusercontent.com/40228854/57919177-9b74dc80-7898-11e9-9156-e6a63d65c59c.png)

As you can see, for this textbook header **Check Your Understanding** is styled, but also additional header **Solution** is added. 

So based on this, in PR: https://github.com/openstax/cnx-recipes/pull/1067 I've added both of those changes also for `College Physics`.  cc @helenemccarron

**Comment by openstaxalina** [comment]
@wilkus27 thank you very much for the investigation and the changes.  I agree that we should style this feature the same in College Physics as was done in AP Physics.  Thank you again!

**Comment by MartaSztuka** [comment]
Issue is fixed. Tested on katalyst01
![Screenshot from 2019-05-23 10-47-52](https://user-images.githubusercontent.com/47241114/58238933-707f0280-7d48-11e9-9282-d4fdfaa709f3.png)
