### ISSUE TITLE
Summary subjects off by one

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#898]
# What happened?

The first section summary is not titled, and numbering starts at the second section of the book. 

# Reproducibility Details

The first section missing the title pushes the summaries off by one throughout the entire book, pushing the last section summary into the next chapter's summary page. 

# Environment:

- Microbiology
- https://staging.cnx.org/contents/5CvTdmJL@7.1:asacLXqx@7.1/Summary
- Every chapter Summary

**edit: it looks like this issue is widespread across all applicable books that we've baked for this testing.** 

# Screenshots

![898](https://user-images.githubusercontent.com/5865292/53892929-d3d38100-3ff2-11e9-8a4e-df5a7bdb9114.png)

**Comment by yblock** [comment]
This appears to be happening in Anatomy and Physiology as well in the "Chapter Review" sections
https://staging.cnx.org/contents/FPtK1zmh@16.1:8_LDnQLE@16.1/Chapter-Review

**Comment by Stackblocks** [comment]
Happening in Psychology too. Chapter 1's summary has 1.1, 1.2, & 1.3, while 1.4 gets placed in chapter 2's summary and so on.

[Chapter 1 Summary](https://staging.cnx.org/contents/Sr8Ev5Og@11.1:LCRHHMk-@11.1/Summary)
[Chapter 2 Summary](https://staging.cnx.org/contents/Sr8Ev5Og@11.1:Nz_LnJk7@11.1/Summary)

**Comment by oscryan** [comment]
All books on staging.

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image](https://user-images.githubusercontent.com/12678235/53976147-0f8e4980-40cc-11e9-8304-478e20f76e83.png)
---
![image](https://user-images.githubusercontent.com/12678235/53976150-1452fd80-40cc-11e9-9dc7-f73851274729.png)
