### ISSUE TITLE
References titles off by one

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#899]
# What happened?

Similar to issue 898, the first entry in references is not titled. This pushes numbering off by one and moves the last item of the chapter to the first item of the next. 

# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: all references sections in the book

# Environment:

- **Book(s)**: Introductory Business Statistics (possibly more)
- **URL/Server**: https://staging.cnx.org/contents/tWu56V64@36.1:aOJne9uV@36.1/References
- **Location (page number, chapter/section)**: references sections
- **Browser**: Firefox

# Screenshots

![899.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/7d05e364-bc3a-4d71-a3d9-f29bd3343fd2)

# Additional notes

appears to be related to: https://github.com/openstax/cnx-recipes/issues/898

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.
![image](https://user-images.githubusercontent.com/12678235/53976088-ec639a00-40cb-11e9-9392-cb5443bcec11.png)
