### ISSUE TITLE
Try It Numbering Does Not Match PDF

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#903]
# What happened?
Try It numbering restarts with each section in the PDF.  On webview is it currently continuous.

# Reproducibility Details

- **Does it also happen in an incognito window?**: Yes
- **Does this happen in one place, a few places, or everywhere?**: Try Its everywhere

# Environment:

- **Book(s)**: _College Algebra_ (likely also _Precalculus_, _Algebra & Trigonometry_)
- **URL/Server**: https://katalyst01.cnx.org/contents/mwjClAV_@8.1:Blwxgq2s@10/1-2-Exponents-and-Scientific-Notation 
- **Location (page number, chapter/section)**: Multiple; example is from section 1.2
- **Suggested nearby searchable text**: "Write each of the following products with a single base. Do not simplify further."
- **Browser**: Chrome

# Screenshots
![catryitnumbering](https://user-images.githubusercontent.com/7863733/53993474-1aa99f80-40f5-11e9-9c4e-fed892f5e13e.png)

**Comment by MartaSztuka** [comment]
Same issue occurs in Algebra&Trigonometry, and Precalculus
![try](https://user-images.githubusercontent.com/47241114/54040355-6fb4e680-41c5-11e9-9899-06fb6036fd52.jpeg)

**Comment by helenemccarron** [comment]
This has been addressed with PR # #934 which was merged into the Precalculus branch and will go out with it . Should we close this issue? cc @openstaxalina @MartaSztuka  . (edit: I am not sure about state of testing at this point)

**Comment by openstaxalina** [comment]
@helenemccarron I put this back in the 3/26 release.

Here is what I understand from the above:

- The Precalculus recipe was created and merged.
- The Precalculus recipe will be available in the dropdown in the next release (3/26).
- However, the Precalculus recipe is not ready for regression testing yet.
- Therefore, we will not select the Precalculus recipe for our books on production until it's been through regression testing, resolved any bugs, and also once we've made relevant content updates.

If this is accurate, I recommend that @MartaSztuka verify this issue once we have code on staging early next week.  If the fix can be verified, this issue can be closed.

**Comment by MartaSztuka** [comment]
I've tested all 3, it's good
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:O5iKX5Vm@11/1-3-Rates-of-Change-and-Behavior-of-Graphs
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:9ZKq0BnY@14/3-7-Inverse-Functions
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:LKVQKWmT@7/9-2-Sum-and-Difference-Identities
![web](https://user-images.githubusercontent.com/47241114/54823251-908e3900-4ca7-11e9-9842-0b1ce6eaeb17.jpeg)

**Comment by uskka** [comment]
I retested this issue and it is fixed in all 3 books. Tested on katalyst01.
 
<img width="749" alt="Screenshot 2019-04-05 at 17 25 10" src="https://user-images.githubusercontent.com/40228918/55638589-d8dd4900-57c7-11e9-867c-3d61e94506f1.png">
<img width="887" alt="Screenshot 2019-04-05 at 17 24 56" src="https://user-images.githubusercontent.com/40228918/55638590-d8dd4900-57c7-11e9-91ae-aa857e455f78.png">
