### ISSUE TITLE
Figure numbering

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#904]
In PDF Figure numbering reset every subsection #.#. and starts with Figure 1.
In webview Figure numbering starts over every chapter.
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:95eK2O0n@11/1-4-Polynomials

![domki](https://user-images.githubusercontent.com/47241114/54023626-b7237e80-4195-11e9-9508-724c019cd23f.jpeg)
![figi](https://user-images.githubusercontent.com/47241114/54283276-f854cd80-459d-11e9-9ca2-cc61638bc9ef.jpeg)

https://katalyst01.cnx.org/contents/_VPq4foj@8.1:IkN3_myo@9/1-6-Absolute-Value-Functions

https://katalyst01.cnx.org/contents/E6wQevFf@11.1:rqFRa9y4@12/10-1-Non-right-Triangles-Law-of-Sines

**Comment by MartaSztuka** [comment]
It's good now
https://katalyst01.cnx.org/contents/mwjClAV_@8.2:Sc8taR03@9/1-5-Factoring-Polynomials
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:IkN3_myo@9/1-6-Absolute-Value-Functions
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:83kZ17SW@10/3-3-Rates-of-Change-and-Behavior-of-Graphs

![figr](https://user-images.githubusercontent.com/47241114/54824740-16ac7e80-4cac-11e9-80d0-ab5e5a13b25c.jpeg)

**Comment by MartaSztuka** [comment]
Fixed in all 3 books
![aaaaaaaaaa](https://user-images.githubusercontent.com/47241114/55245889-622ed180-5244-11e9-82e0-937f38a4d148.jpeg)

**Comment by uskka** [comment]
Numbering of figures is now reseted in every chapter, but not in the EOC. Figure numbering in EOC needs to be reseted too in order to match PDF numbering.
