### ISSUE TITLE
Section Exercises numbering 

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#905]
In PDF at the end of every subsection in Section Exercises numbering starts with 1.
In webview Section Exercises numbering resets every chapter.
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:95eK2O0n@11/1-4-Polynomials

![exercises](https://user-images.githubusercontent.com/47241114/54024172-3ebdbd00-4197-11e9-9f3a-f543e2e8c7be.jpeg)

https://katalyst01.cnx.org/contents/E6wQevFf@11.1:RZEC2R_o@6/9-4-Sum-to-Product-and-Product-to-Sum-Formulas
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:bVz-NYId@12/2-2-Graphs-of-Linear-Functions

**Comment by MartaSztuka** [comment]
@openstaxalina 
Issue is fixed, tested on katalyst01
May I close?
![Screenshot from 2019-04-08 09-46-21](https://user-images.githubusercontent.com/47241114/55707373-be7fb700-59e3-11e9-8c90-efaaef2bf8c3.png)

**Comment by openstaxalina** [comment]
@MartaSztuka I agree it can be closed.  Thank you!
