### ISSUE TITLE
WAITING (content investigation) Missing 'Section Exercises'  headline

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#907]
In webview, in subsections 1.1 and 1.5 headline 'Section Exercises' is missing.
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:Sc8taR03@9/1-5-Factoring-Polynomials

![ekserc](https://user-images.githubusercontent.com/47241114/54030908-6586ee00-41ad-11e9-970b-bc1a85445444.jpeg)

In AlgebraAndTrigonometry 1.1 and 1.5 headline is also missing
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:0KhpF2RH@22/1-1-Real-Numbers-Algebra-Essentials

**Comment by openstaxalina** [comment]
This might be content-related.  We will investigate and update this issue accordingly.

**Comment by openstaxalina** [comment]
This was resolved in content (https://github.com/openstax/content-managers/issues/651); closing.
