### ISSUE TITLE
Subsection Number Section Exercises

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#908]
In PDF Section Exercises has Section numbers #.#, in webview it's missing.
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:IkN3_myo@9/1-6-Absolute-Value-Functions

![exerc](https://user-images.githubusercontent.com/47241114/54034197-93246500-41b6-11e9-9b02-781b819f6e18.jpeg)

https://katalyst01.cnx.org/contents/E6wQevFf@11.1:RZUxkOcn@9/1-6-Rational-Expressions

https://katalyst01.cnx.org/contents/mwjClAV_@8.1:xJt0U6vR@11/2-3-Models-and-Applications

**Comment by openstaxalina** [comment]
I know that this was a challenge; however, I think that we were able to do something similar for DevMath: https://cnx.org/contents/yqV9q0HH@17.2:gUzCHLwU@17/1-1-Introduction-to-Whole-Numbers.

**Comment by MartaSztuka** [comment]
@openstaxalina issue is fixed, tested on katalyst01
![Screenshot from 2019-04-08 13-40-43](https://user-images.githubusercontent.com/47241114/55721591-09112b80-5a04-11e9-8dee-568391b24465.png)

**Comment by openstaxalina** [comment]
@MartaSztuka I agree we can close.  Thank you!
