### ISSUE TITLE
Review exercises number and text isn't alined.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#909]
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:Gpe7eALU@8.1/Review-Exercises
![siedem](https://user-images.githubusercontent.com/47241114/54117241-a15dc580-43f0-11e9-8029-60ca7ce78fd4.jpeg)

I've found one case this far, update if there's more.

**Comment by openstaxalina** [comment]
I _believe_ this can be resolved in content - moving to content repo.

**Comment by openstaxalina** [comment]
@MartaSztuka please open a new issue if you do find more instances of this.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #664](https://github.com/openstax/content-managers/issues/664) via [**ZenHub**](https://www.zenhub.com/)
