### ISSUE TITLE
Mismatched headers in Review Exercises and Practice Test

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#910]
Last subsection's name and number appears as a header in Review Exercises and Practice Test at the end of each chapter.
Happens in all Precalculus trio and probabbly should be reaplced with 'Chapter # Review Exercises',
or 'Chapter # Practice Test'.
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:87by3Mj4@8.1/Review-Exercises
![chap](https://user-images.githubusercontent.com/47241114/54193478-76d83f00-44ba-11e9-8521-abe2a257ceda.jpeg)

https://katalyst01.cnx.org/contents/_VPq4foj@8.1:Q0dD29cN@8.1/Review-Exercises
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:12rynwH0@11.1/Review-Exercises

**Comment by openstaxalina** [comment]
We can live without "Chapter #" since we do have the header "Review Exercises", but the 1.6 Rational Expressions header looks like a true bug.

**Comment by MartaSztuka** [comment]
Bug is gone, all 3 books looks good, @openstaxalina do we close?
![Screenshot from 2019-04-05 14-41-01](https://user-images.githubusercontent.com/47241114/55628583-63667e00-57b1-11e9-83a5-ce00823e9be7.png)

**Comment by openstaxalina** [comment]
I agree this can be closed, @MartaSztuka.
