### ISSUE TITLE
Odd word in Answer Key

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#911]
In Answer Key there's one unnecessary word, which might have elope from other paragraph, but I haven't find where it's missing. And answer is not inline with number.
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:fSX_7vJ6@8.1/Chapter-2
![solution](https://user-images.githubusercontent.com/47241114/54122916-ad508400-43fe-11e9-835c-e39dcaa738ec.jpeg)

**Comment by openstaxalina** [comment]
We should be able to resolve this in content; moving there.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #663](https://github.com/openstax/content-managers/issues/663) via [**ZenHub**](https://www.zenhub.com/)
