### ISSUE TITLE
Text Should Not Wrap Around Images

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#913]
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:z1lgUlD3@8.1/Chapter-3

![ukłądrownan](https://user-images.githubusercontent.com/47241114/54125880-7bdbb680-4406-11e9-83ad-55a936088695.jpeg)

It's same as #892

**Comment by openstaxalina** [comment]
There might be two different issues here -

In the first case, **I think that we should remove text wrapping around images.**
In the second case, the spacing might be being added by the math being in a table... @oscryan or @lwtchu could you potentially advise? (We're looking at Example 4 - or 72 depending when the content was baked - here: https://katalyst01.cnx.org/contents/_VPq4foj@8.1:IkN3_myo@9/1-6-Absolute-Value-Functions) 
<img width="914" alt="Screen Shot 2019-03-13 at 12 07 56 PM" src="https://user-images.githubusercontent.com/7863733/54299381-c2591e80-4588-11e9-873f-abbe016284e4.png">

**Comment by oscryan** [comment]
The first case can be solved by adding a line return before the image. The second case is a math table that should be a cnxml table with some math in it.

**Comment by openstaxalina** [comment]
Thanks @oscryan.  I am going to leave transform this issue so that we do not let text wrap around images (will solve the first case).

I will create a content issue for the second item.

**Comment by Adrianltd** [comment]
Issue moved to [openstax/webview #2232](https://github.com/openstax/webview/issues/2232) via [**ZenHub**](https://www.zenhub.com/)
