### ISSUE TITLE
Hint in Checkpoint note

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#914]
On katalyst01 (https://katalyst01.cnx.org/contents/i4nRcikn@3.7:fP4FUrwS@7/1-1-Review-of-Functions) there are hints in Checkpoint notes:

![checkpoint](https://user-images.githubusercontent.com/40228854/54134045-82265e80-4417-11e9-8f9a-a9a7c3895178.JPG)

In PDF there is no such part inside that note:

![checkpoint_pdf](https://user-images.githubusercontent.com/40228854/54134134-a71ad180-4417-11e9-9524-4a2cb39168ad.JPG)

I checked if it appears in PDF in Answer Key, but it's not:

![answer_pdf](https://user-images.githubusercontent.com/40228854/54134705-bc443000-4418-11e9-870f-1ae4632b0eee.JPG)

I also didn't find it in any other place in PDF.

**Comment by wilkus27** [comment]
@openstaxalina should hints on webview be trashed? Or maybe they will be added to PDF?

**Comment by openstaxalina** [comment]
@wilkus27 thanks for noticing this - hints should be trashed as we do not have plans to add these to the PDF.

**Comment by MartaSztuka** [comment]
No Hints in Checkpoints anymore, all three books checked
![Screenshot from 2019-03-29 13-22-30](https://user-images.githubusercontent.com/47241114/55232446-e2920a00-5225-11e9-988e-e627ab5722e5.png)
![Screenshot from 2019-03-29 13-21-41](https://user-images.githubusercontent.com/47241114/55232450-e58cfa80-5225-11e9-9578-56f92edaefc2.png)
![Screenshot from 2019-03-29 13-21-52](https://user-images.githubusercontent.com/47241114/55232454-e756be00-5225-11e9-8f46-bdf5a6bf0960.png)

**Comment by uskka** [comment]
Looks good. Tested on katalyst01.
