### ISSUE TITLE
Unnecessary 'Tables#' in Key Equations

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#916]
In Key Equations at the end of chapter equations are in tables.
Problem occurs wherever Key Equations are, in all three books.
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:SXjiAlpU@8.1/Key-Equations
![keyeq](https://user-images.githubusercontent.com/47241114/54186959-c6177300-44ac-11e9-9841-1cd4dc4d5e12.jpeg)
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:JOTy616V@8.1/Key-Equations
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:oHadYzFR@11.1/Key-Equations

**Comment by openstaxalina** [comment]
The Key Equations were encoded as tables to achieve the desired alignment/appearance.

This can probably be resolved in content by giving the tables the `unnumbered` class and `</label>`.  Currently those markup elements aren't there:
<img width="982" alt="Screen Shot 2019-03-13 at 11 52 19 AM" src="https://user-images.githubusercontent.com/7863733/54298297-7ad19300-4586-11e9-95c5-b408e0f0778a.png">

Moving to content repo.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #661](https://github.com/openstax/content-managers/issues/661) via [**ZenHub**](https://www.zenhub.com/)
