### ISSUE TITLE
Headers in Key Concepts are missing

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#917]
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:YxQRPRmE@11.1/Key-Concepts
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:FZqSljqG@8.1/Key-Concepts
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:WWmnx_o-@8.1/Key-Concepts
![header](https://user-images.githubusercontent.com/47241114/54191717-c61c7080-44b6-11e9-9bcd-733870633103.jpeg)

Issue occurs in Precalculus Trio, everywhere in Key Concept. 
Issue #715 was similar.

**Comment by MartaSztuka** [comment]
Issue is fxed, tested on katalyst01, @openstaxalina do we close?
![Screenshot from 2019-04-08 13-29-12](https://user-images.githubusercontent.com/47241114/55721048-a1a6ac00-5a02-11e9-83c1-0341932cc994.png)

**Comment by openstaxalina** [comment]
@MartaSztuka I agree we can close.  Thank you!
