### ISSUE TITLE
Something weird occurs in Index

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#918]
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:cmIyTn21@8.1/Index
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:FTy-KW6O@8.1/Index
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:8EgMc1pO@11.1/Index
![symb](https://user-images.githubusercontent.com/47241114/54194679-18f92680-44bd-11e9-96d2-07b20969ff29.jpeg)
Looks odd. Happens in all 3 books.

**Comment by openstaxalina** [comment]
This is most likely a content issue where there is a leading space in all those terms. Moving to content repo.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #660](https://github.com/openstax/content-managers/issues/660) via [**ZenHub**](https://www.zenhub.com/)
