### ISSUE TITLE
Header in Theorem note

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#919]
On katalyst01 (e.g. https://katalyst01.cnx.org/contents/i4nRcikn@3.7:dKCfyV9u@5/2-2-The-Limit-of-a-Function) Theorem notes have subtitles. They should display in the header of these notes:

![theorem](https://user-images.githubusercontent.com/40228854/54195950-4f847080-44c0-11e9-8931-2da77260b867.JPG)

PDF:

![theorem_pdf](https://user-images.githubusercontent.com/40228854/54195976-62974080-44c0-11e9-82f9-54ef6a23c666.JPG)

**Comment by openstaxalina** [comment]
I think that this is fine as-is; I recommend closing this unless you have concerns @wilkus27 or @helenemccarron ?

**Comment by helenemccarron** [comment]
I agree, this is display, the information is visible and can styled.
