### ISSUE TITLE
Leading between number and answer in Key.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#920]
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:-S_QNurU@11.1/Chapter-1
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:UZVwLjju@8.1/Chapter-1
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:t6htDPpE@8.1/Chapter-8
In all 3 books leadings in Answer Key is messy
![lead](https://user-images.githubusercontent.com/47241114/54196629-2cf35700-44c2-11e9-890c-d71a4d379e12.jpeg)

**Comment by Adrianltd** [comment]
Issue moved to [openstax/webview #2234](https://github.com/openstax/webview/issues/2234) via [**ZenHub**](https://www.zenhub.com/)
