### ISSUE TITLE
Wrong name of the links to the Theorem notes

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#921]
On katalyst01(e.g. https://katalyst01.cnx.org/contents/i4nRcikn@3.7:dKCfyV9u@5/2-2-The-Limit-of-a-Function) links to the Theorem notes take name of the other elements (like figure or table). But they lead to the proper places.

webview:

![theorem_link](https://user-images.githubusercontent.com/40228854/54196819-9ecba080-44c2-11e9-88ec-0929b8199de3.JPG)

PDF:

![theorem_link_pdf](https://user-images.githubusercontent.com/40228854/54196830-a7bc7200-44c2-11e9-9bdf-0b100d34f71e.JPG)

**Comment by MartaSztuka** [comment]
Issue occurs in all 3 books
https://katalyst01.cnx.org/contents/HTmjSAcf@3.4:rn4DsBBU@7/1-3-The-Fundamental-Theorem-of-Calculus#fs-id1170571704350
https://katalyst01.cnx.org/contents/oxzXkyFi@3.7:1TskJjp2@5/2-4-The-Cross-Product#fs-id1163724130388

**Comment by tomjw64** [comment]
@wilkus27 You will need to append to the targetlabel list (inside the calculus config file) with an entry for theorem notes. For example, something similar to:
```
$Config_TargetLabels: append($Config_TargetLabels,
  (selector: 'div[data-type="chapter"] [data-type="note"].theorem', labelText: "Theorem" counter(chapter} "." counter(theorem))
);
```
Once you have that line in your config, if it is not working properly, confirm if the theorem counter is initialized on the targetlabel pass, as well as if the selector value is indeed targeting your theorem notes. Happy hunting!

**Comment by MartaSztuka** [comment]
Fixed in all 3 books. Tested on katalyst01
![Screenshot from 2019-05-21 13-30-21](https://user-images.githubusercontent.com/47241114/58092566-b6af5700-7bcc-11e9-8a95-a433e26c183f.png)

**Comment by MartaSztuka** [comment]
Issue fixed, tested on katalyst01
![Screenshot from 2019-05-21 13-59-00](https://user-images.githubusercontent.com/47241114/58094302-a39e8600-7bd0-11e9-9833-ff21a35a798e.png)
