### ISSUE TITLE
Sections numbers in Try It, Answer Key

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#922]
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:N2wS6bar@8.1/Chapter-1
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:bt4ic590@11.1/Chapter-7
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:z1lgUlD3@8.1/Chapter-3

![sections](https://user-images.githubusercontent.com/47241114/54198809-afcae080-44c7-11e9-93b5-90ec28b53586.jpeg)
In Answer Key answers should be devided by Sections. Occurs in all 3 books.

**Comment by openstaxalina** [comment]
@MartaSztuka is there also an issue for the numbers starting over with each section?

**Comment by openstaxalina** [comment]
Ah - found it (created by me!) https://github.com/openstax/cnx-recipes/issues/903

**Comment by uskka** [comment]
Looks good. Tested on katalyst01.
<img width="988" alt="Screenshot 2019-04-25 at 16 18 16" src="https://user-images.githubusercontent.com/40228918/56742881-da21e600-6775-11e9-98d0-11244947fb4e.png">

**Comment by openstaxalina** [comment]
Closing per @uskka's comment above.
