### ISSUE TITLE
Learning Objectives caption

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#924]
At the begining of each Section there is caption 'Learning Ojectives'.
In webview it is not. 
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:lO46ARyo@10/11-3-Geometric-Sequences
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:Sc8taR03@8/1-5-Factoring-Polynomials
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:95eK2O0n@11/1-4-Polynomials
![lo](https://user-images.githubusercontent.com/47241114/54207456-7c458180-44da-11e9-8851-70e78aad0828.jpeg)

**Comment by openstaxalina** [comment]
If it's possible to target this section and add a **Learning Objectives** header, we should. 
We did something similar in DevMath: https://cnx.org/contents/yqV9q0HH@18.1:gUzCHLwU@17/1-1-Introduction-to-Whole-Numbers

**Comment by MartaSztuka** [comment]
It's fixed, but in Algebra&Trigonometry still can't bake.
![Screenshot from 2019-03-29 17-32-27](https://user-images.githubusercontent.com/47241114/55247804-cf446600-5248-11e9-98dd-ac3301c50e9b.png)

**Comment by uskka** [comment]
All of the books look good. Tested on katalyst01.
<img width="647" alt="Screenshot 2019-04-05 at 17 01 14" src="https://user-images.githubusercontent.com/40228918/55637108-9d8d4b00-57c4-11e9-9ad5-5bbfe85e4209.png">
<img width="847" alt="Screenshot 2019-04-05 at 17 01 50" src="https://user-images.githubusercontent.com/40228918/55637172-bd247380-57c4-11e9-8052-197b589782b9.png">

<img width="699" alt="Screenshot 2019-04-05 at 17 01 19" src="https://user-images.githubusercontent.com/40228918/55637110-9e25e180-57c4-11e9-9f7b-257d6c8f7d24.png">
