### ISSUE TITLE
[Security Alerts] Update Dependencies 

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#927]
[Link to security alerts](https://github.com/openstax/cnx-recipes/network/alerts)
As of the creation of this issue, there are 5 high severity, 4 medium severity, and 2 low severity alerts.

**Comment by brittany-johnson** [comment]
@brittweinstein Assigning you so that you can prioritize!

**Comment by brittweinstein** [comment]
putting @openstaxalina on this for prio!

**Comment by openstaxalina** [comment]
This may be resolved with #901.  @brittany-johnson will check this again once #901 is merged.

**Comment by openstaxalina** [comment]
#901 resolved all but 2 security alerts.  @brittany-johnson pinged @philschatz about these remaining 2.

**Comment by openstaxalina** [comment]
@philschatz is using 3.0 Beta of KSS in another repo, and this version fixes the dependencies.  The next step on this card is to update the version of KSS used in cnx-recipes.  However, this may break some tests.  Another option would be to reevaluate to use of KSS for testing.

**Comment by philschatz** [comment]
The Pull Request that upgrades KSS is #973

**Comment by brittweinstein** [comment]
Verified
