### ISSUE TITLE
Figure number is missing

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#931]
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:VfLo7KmC@15/3-1-Functions-and-Function-Notation
In Example's Solution some of the Figures don't have number.
![fig](https://user-images.githubusercontent.com/47241114/54272586-48269b00-4584-11e9-983f-920b676d399f.jpeg)

**Comment by openstaxalina** [comment]
I think this is a content issue; these are `<image>`s, which are not numbered.  Moving to content repo.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #659](https://github.com/openstax/content-managers/issues/659) via [**ZenHub**](https://www.zenhub.com/)
