### ISSUE TITLE
Headers in Example aren't bold

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#933]
In Examples headlines should be emphesized and aline with 'Example#' not regular below it.
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:weepUiqV@9/10-3-Polar-Coordinates

Same thing occurs in Calculus, #889 
![exmp](https://user-images.githubusercontent.com/47241114/54276278-3f869280-458d-11e9-9108-f5409227eea6.jpeg)

**Comment by openstaxalina** [comment]
We do not have to align the title with the *Example #.#" header, **but the title does need styling.  Suggest bolding the title as Marta also suggested above.**  
Is this feasible?  
cc @MartaSztuka @Adrianltd

**Comment by helenemccarron** [comment]
See https://github.com/openstax/cnx-recipes/issues/945 for details

**Comment by MartaSztuka** [comment]
Issue is fixed, baked in 2 books.
Algebry&Trigonometry couldn't have been baked, however most probably is also fixed.
![Screenshot from 2019-04-12 17-47-10](https://user-images.githubusercontent.com/47241114/56050110-4ef32a00-5d4b-11e9-9ba9-d0342ac36303.png)
![Screenshot from 2019-04-12 17-46-28](https://user-images.githubusercontent.com/47241114/56050114-51558400-5d4b-11e9-8489-c096ca651e6a.png)

**Comment by uskka** [comment]
Algebra and Trigonometry looks good. Tested on katalyst01.
<img width="908" alt="Screenshot 2019-04-17 at 14 25 25" src="https://user-images.githubusercontent.com/40228918/56289034-4e2e0f80-6120-11e9-8167-15d013bbd7ca.png">
