### ISSUE TITLE
Section Titles Missing From Introduction to Business Summaries

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#936]
# What happened?

The section titles do not display above each section summary in this book in webview, although they do in PDF (and in every other textbook in webview).

# Reproducibility Details

- **Does it also happen in an incognito window?**: Yes
- **Does this happen in one place, a few places, or everywhere?**: Every **Summary of Learning Outcomes** section in every chapter

# Environment:

- **Book(s)**: _Introduction to Business_
- **URL/Server**: https://cnx.org/contents/Tgl3H6iq@8.5:G1VGocIw@8.5/Summary-of-Learning-Outcomes
- **Location (page number, chapter/section)**:
- **Suggested nearby searchable text**: N/A 
- **Browser**: Chrome

# Screenshots
![IBSummarySectionTitlesMissing](https://user-images.githubusercontent.com/7863733/54315215-81becc80-45ab-11e9-9c1a-159b1ce90782.png)
(Shows current behavior on **production** in each format.)

**Comment by openstaxalina** [comment]
Noted also by @theresamasciale  :-)

**Comment by MartaSztuka** [comment]
Issue is gone. Tested on katalyst01.
![Screenshot from 2019-05-22 17-04-31](https://user-images.githubusercontent.com/47241114/58185678-cd7ca900-7cb3-11e9-9f22-2635214ab94b.png)
