### ISSUE TITLE
Extra numbers appeared

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#938]
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:NcxRNUfa@8/10-4-Rotation-of-Axes
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:RZUxkOcn@9/1-6-Rational-Expressions
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:lO46ARyo@12/9-3-Geometric-Sequences
![wildnumbers](https://user-images.githubusercontent.com/47241114/54369206-c878f900-4675-11e9-885e-f9767f2fde24.jpeg)

P.S. If it's not issue, sorry, looks like one.

**Comment by openstaxalina** [comment]
I agree that this is a bug, and a potentially very confusing issues for users.  These numbers should be removed as they do not appear in Examples or Try Its in the PDF:
![Screen Shot 2019-03-14 at 2 54 49 PM](https://user-images.githubusercontent.com/7863733/54387369-35d25d00-4669-11e9-9a12-daaaa84d9117.png)
![Screen Shot 2019-03-14 at 2 54 55 PM](https://user-images.githubusercontent.com/7863733/54387374-3834b700-4669-11e9-8d81-1c712ad5a879.png)

**Comment by MartaSztuka** [comment]
Problem's gone, I'm closing issue
![Screenshot from 2019-03-29 17-15-39](https://user-images.githubusercontent.com/47241114/55246832-61973a80-5246-11e9-8a47-246ed4d4eeec.png)
