### ISSUE TITLE
Structure of Examples should be standardized

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#945]
Textbooks have different structure of the Examples. It is causing inconsistency in display titles inside Examples. They should be styling in one way.

<h3>1. type of structure</h3>

Titles are in spans with `data-type="title"` inside the paragraphs. They're styled to be bold in webview.

 <img src="https://user-images.githubusercontent.com/40228854/54428770-cae35d80-471e-11e9-908f-90474732aba8.png" width=45%> 

For example:
<img src="https://user-images.githubusercontent.com/40228854/54428758-bf903200-471e-11e9-88c1-8fa5f265affc.png" width=70%>

**Books with such structure:**

- Astronomy (https://katalyst01.cnx.org/contents/LnN76Opl@14.24:R1I6B4Ht@4/3-1-The-Laws-of-Planetary-Motion)
- Chemistry (https://katalyst01.cnx.org/contents/havxkyvS@12.1:qSyRr69l@12/1-6-Mathematical-Treatment-of-Measurement-Results#16746)
- University Physics (https://katalyst01.cnx.org/contents/1Q9uMg_a@11.29:gE8grRKS@16/2-2-Coordinate-Systems-and-Components-of-a-Vector)
- Fizyka dla szkół wyższych (https://katalyst01.cnx.org/contents/TqqPA4io@1.98:BCyy0w3Y@3/2-4-Mno%C5%BCenie-wektor%C3%B3w)

<h3>2. type of structure</h3>

Titles are in `<p>` without any selector such class or data-type, inside `<strong>`.

<img src="https://user-images.githubusercontent.com/40228854/54431268-409ef780-4726-11e9-9522-89334416b219.png" width=50%>

For example:
<img src="https://user-images.githubusercontent.com/40228854/54431252-37158f80-4726-11e9-99f5-75b433bdd75f.png" width=70%>

**Books with such structure:**

- College Physics for AP Courses (https://katalyst01.cnx.org/contents/jQSmhtXo@20.1:Vocdt1Hp@6/2-4-Acceleration)
- College Physics (https://katalyst01.cnx.org/contents/Ax2o07Ul@14.2:YCO4fVoo@9/2-4-Acceleration)

<h3>3. type of structure</h3>

There is only one title **Solution** in div with `data-type="title"` inside div with `data-type="solution"`. It's added by content. Such structure occurs in dev-math books. Some examples don't have those titles. There is an issue about it: https://github.com/openstax/content-managers/issues/485.

<img src="https://user-images.githubusercontent.com/40228854/54431812-ab9cfe00-4727-11e9-8c72-e04858310f86.png" width=50%>

<img src="https://user-images.githubusercontent.com/40228854/54431823-b192df00-4727-11e9-971c-f4a3ff03cc8c.png" width=70%>

**Books with such structure:**

- Prealgebra (https://katalyst01.cnx.org/contents/yqV9q0HH@13.3:p8Ut5CsA@20/2-2-Evaluate-Simplify-and-Translate-Expressions)
- Elementary Algebra
- Intermediate Algebra

<h3>4. type of structure</h3>

This structure is very similar to structure from above, but solution title is added by recipe. So it is in div with `data-type="solution-title"`.

<img src="https://user-images.githubusercontent.com/40228854/54432671-2109ce00-472a-11e9-95ec-db47467fe769.png" width=50%>

For example:
<img src="https://user-images.githubusercontent.com/40228854/54432687-2cf59000-472a-11e9-884e-cc98e8cde562.png" width=70%>

**Books with such structure:**

- Introductory Statistics (https://katalyst01.cnx.org/contents/MBiUQmmY@23.1:CY4aJuYS@20/1-2-Data-Sampling-and-Variation-in-Data-and-Sampling)
- Introductory Business Statistics

<h3>5. type of structure</h3>

Here are three titles, each of them have parent container with different selector: `data-type="problem"`, `data-type="solution"` and `data-type="commentary"`. What is more title **Solution** is added by recipe like in Statistics, so it is in div with `data-type="solution-title"`.

<img src="https://user-images.githubusercontent.com/40228854/54433384-00db0e80-472c-11e9-8ed9-294854b3b4d2.png" width=50%>

For example:
<img src="https://user-images.githubusercontent.com/40228854/54433400-07698600-472c-11e9-920d-39f9350c7e12.png" width=70%>

**Books with such structure:**

- Calculus vol1 (https://katalyst01.cnx.org/contents/i4nRcikn@3.7:FH3fJfnQ@7/3-5-Derivatives-of-Trigonometric-Functions)
- Calculus vol2, vol3
- Precalculus (https://katalyst01.cnx.org/contents/_VPq4foj@8.1:bVz-NYId@12/2-2-Graphs-of-Linear-Functions)
- College Algebra
- Algebra and Trigonometry

**Comment by wilkus27** [comment]
Below I paste comment of Helene from discussion on Slack (https://katalysteducation.slack.com/archives/CBW9DFKGF/p1552319295121200) about **Solution** title in Calculus trio:

> I did some research on the examples’ solution titles. I think there is a bug in recipes in `_modify.scss`
```
 [data-type="solution"] {
          .solution-title {
            container: h4;
          }
        }
```
>`.solution-title`  doesn’t target anything (I couldn’t find `.solution-title` anywhere in the CSS output. I think it needs to be changed to  `[data-type="solution-title"]`. Alternatively you could target both: `.solution-title [data-type="solution-title"] {,,,}`. This will convert the title into an h4 and produce the desired output. This will affect all books with examples but hopefully solve all the issues. We can discuss tomorrow if we think we need a release flag.

So, based on description of Example structures from above, such solution will impact only statistics, calculus and precalculus textbooks.

**Comment by helenemccarron** [comment]
Mostly for my understanding, @openstaxalina please correct me if I'm wrong:
1. type of structure doesn't use a solution wrapper, has a  `<para>` title in CNXML
2. type of structure doesn't use a solution wrapper, has a`<para>` with no title, just bold Solution text
3. type of structure uses a solution container with title in CNXML
4. type of structure uses a solution with title generated in the recipes (uses `data-type="solution-title`, recipes have a bug that skips that element and doesn't convert it to an `h4`
5. type of structure seems similar to type 4, but with the full exercises components: problem, solution and commentary. That example makes me think that we may want to make sure that all three pieces titles are handled in an identical fashion. 

As a conclusion, I think ideally, we need to:
 - For cases  type 1 and 2: clean the CNXML. If we do not want to use a problem/solution structure, we should define what the structure should be and how the title should be handled for consistency. 
- For cases type 3 and 4: fix the bug to make sure the recipes support the data-type="solution-title` but also add support for `data-type="problem-title` and `data-type="commentary-title`, which is a significant change in the code.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #758](https://github.com/openstax/content-managers/issues/758) via [**ZenHub**](https://www.zenhub.com/)
