### ISSUE TITLE
floppy.flan: Enable all release flags for three books #884

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#947]
# What happened?
This sprint, we will enable ALL release flags for _College Physics_, _College Physics for AP Courses_, and  _Biology for AP Courses_.

**Comment by tomjw64** [comment]
We have one release flag waiting only on `physics`, `ap-physics`, and `ap-biology`. So I would recommend some combination of these books for this release.

**Comment by openstaxalina** [comment]
@tomjw64 this release we successfully regression tested 3 books in a short time (about a half-day), so I updated the description above to reflect enabling the release flags for all three of the books you proposed.
