### ISSUE TITLE
Missing letter headers in Index

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#952]
# What happened?

Index does not have letter organized headers 

# Reproducibility Details

- **Does it also happen in an incognito window?**: Yes
- **Does this happen in one place, a few places, or everywhere?**: Just the Index on staging

# Environment:

- **Book(s)**: Business Ethics, Introduction to Business
- **URL/Server**: 
https://staging.cnx.org/contents/kUrGbuHs@7.1:nqyXHPD_@7.1/Index
https://staging.cnx.org/contents/Tgl3H6iq@12.1:7xUnRhsy@12.1/Index
- **Location (page number, chapter/section)**: Index
- **Suggested nearby searchable text**: n/a
- **Browser**: FF

# Screenshots

![2019-03-20_08-12-59](https://user-images.githubusercontent.com/5865292/54686907-5591d700-4ae8-11e9-96e0-86d899498623.png)

# Additional notes

Located during regression testing for issue 680

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f4242f5a-f6cb-4384-a65e-e0e83e9f5704)
