### ISSUE TITLE
[HOLDING until requirements are clear] Allow page properties to be used as units on pdf platform

### ISSUE THREAD

**Issue by tomjw64** [openstax/cnx-recipes#955]
Being able to use some syntax like
`margin: unit(-1, page-margin)` might be pretty handy in some cases, such as splash images.

**Comment by openstaxalina** [comment]
We won't have a consistent margin for the entire book - the intro pages, for example, will have different margins.  We won't know how to proceed on this until we start implementing styles.

**Comment by brittweinstein** [comment]
@openstaxalina I'd suggest closing this b/c these problems are resolved elsewhere -- is that OK?

**Comment by openstaxalina** [comment]
@brittweinstein that is okay by me - closing.
