### ISSUE TITLE
Asterisks in bookmarks tab of pdf reader

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#956]
# What happened?

Some unexpected asterisks have been showing up in the titles on the bookmarks of our pdfs (NOT the content, or the TOC, just the bookmarks). We never cared before, but it just confused some teachers. Can we take them off?

# Reproducibility Details

- **Does this happen in one place, a few places, or everywhere?**: Every book

# Environment:

- **Book(s)**: All
- **URL/Server**: All
- **Location (page number, chapter/section)**: All

# Screenshots

![2019-03-20_09-47-18.png](https://images.zenhubusercontent.com/5b572ec492e09f0d21193829/cf0c416b-0bf3-465f-8c77-1acb0983c0cf)

**Comment by openstaxalina** [comment]
Issue moved to [openstax/oer.exports #3912](https://github.com/openstax/oer.exports/issues/3912) via [**ZenHub**](https://www.zenhub.com/)
