### ISSUE TITLE
Review exercises number and text isn't alined.

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#959]
@openstaxalina commented on [Wed Mar 13 2019](https://github.com/openstax/content-managers/issues/664)

@MartaSztuka commented on [Mon Mar 11 2019](https://github.com/openstax/cnx-recipes/issues/909)

https://katalyst01.cnx.org/contents/mwjClAV_@8.1:Gpe7eALU@8.1/Review-Exercises
![siedem](https://user-images.githubusercontent.com/47241114/54117241-a15dc580-43f0-11e9-8029-60ca7ce78fd4.jpeg)

I've found one case this far, update if there's more.

---

@openstaxalina commented on [Wed Mar 13 2019](https://github.com/openstax/cnx-recipes/issues/909#issuecomment-472535500)

I _believe_ this can be resolved in content - moving to content repo.

---

@openstaxalina commented on [Wed Mar 13 2019](https://github.com/openstax/cnx-recipes/issues/909#issuecomment-472535608)

@MartaSztuka please open a new issue if you do find more instances of this.

---

@openstaxalina commented on [Wed Mar 13 2019](https://github.com/openstax/content-managers/issues/664#issuecomment-472536352)

Please investigate/resolve in markup if possible when there is downtime.

---

@yblock commented on [Wed Mar 20 2019](https://github.com/openstax/content-managers/issues/664#issuecomment-474013006)

@openstaxalina  The markup is no different than surrounding questions except the fact that there is a mixture of mathML and text. It appears that this isn't a content issue but a styling one where the text and math are not wrapping porperly.

**Comment by openstaxalina** [comment]
We determined this cannot be resolved in content.  Could this be resolved in code?  If not, this issue can be closed as this is a low-priority difference.

**Comment by Adrianltd** [comment]
@openstaxalina this is caused by the change I did recently to fix this issue:
https://github.com/openstax/webview/issues/2201

This is the change that I've made:
https://github.com/openstax/webview/commit/135b4b4607f11bf5021c026419c5952703afa5f3

So one way or another, one of these issues will exist.

**Comment by openstaxalina** [comment]
@Adrianltd thanks for the update.  openstax/webview#2201 is a higher priority fix because it occurs in multiple cases in a common browser.
Therefore, I would not like to make a change for the one issue noted above.

I will close this issue.
