### ISSUE TITLE
Tables numbering

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#966]
In webview Table numbering starts from 1.1, in PDF from 1.7.
https://katalyst01.cnx.org/contents/oxzXkyFi@3.7:RAdKNUjT@6/1-5-Conic-Sections
![tabs](https://user-images.githubusercontent.com/47241114/54997077-305f0600-4fcb-11e9-9148-7a0565aa8e1c.png)
Some of Tables are unnumbered.
https://katalyst01.cnx.org/contents/oxzXkyFi@3.7:TqHmrLMw@7/6-1-Vector-Fields#fs-id1167793610554
![tbl](https://user-images.githubusercontent.com/47241114/54998228-e3c8fa00-4fcd-11e9-8595-3607326a056c.jpeg)

**Comment by wilkus27** [comment]
About first part, it's known issue, will be solved by https://github.com/openstax/oer.exports/issues/3895.

About second part, I think it could be similar issue to https://github.com/openstax/webview/issues/2035 and can be resolved by content cc @openstaxalina

**Comment by openstaxalina** [comment]
Thank you for finding this, @MartaSztuka !  I agree with @wilkus27 about the solutions.  I will move this issue to content-managers so that we can change the link in the second instance to simply say, "The table below..."

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #694](https://github.com/openstax/content-managers/issues/694) via [**ZenHub**](https://www.zenhub.com/)
