### ISSUE TITLE
Mitigate Technical Debt on Recipes

### ISSUE THREAD

**Issue by tomjw64** [openstax/cnx-recipes#968]
@philschatz 

- CREATE NEW CARD IF NOT DONE ALREADY: Remove unused languages (Ruby, since the switch to node-sass): https://github.com/openstax/cnx-recipes/issues/1056
- CREATE NEW CARD IF NOT DONE ALREADY: Remove unused nodejs dependencies: https://github.com/openstax/cnx-recipes/issues/1057
- CREATE NEW CARD [BrittanyJ, Thomas, Hélène discuss] Decide on yarn vs npm: https://github.com/openstax/cnx-recipes/issues/1058
- CREATE NEW CARD [BrittanyJ] normalize building and testing scripts between styles and recipes: https://github.com/openstax/cnx-recipes/issues/1059
- DONE ~Update nodejs version to LTS~

# Makefile

This is possible but we would need to generate a `Makefile` based on the SASS files. Extracting the dependency tree for SASS files is possible with https://github.com/dependents/node-dependency-tree or maybe in [node-sass directly](https://github.com/sass/node-sass/blob/master/README.md#result-object) but:

**Note:** specifying the platform as an environment variable **would make this approach impossible.**

<details>

<summary>Click me to see the dependency tree for a book</summary>

```js
'books/intro-business/book.scss': {
  'framework/_import-config.scss': {
    'framework/config/_constants.scss': {},
    'framework/config/_color-scheme.scss': {},
    'framework/config/_color-map.scss': {},
    'framework/config/_font-map.scss': {},
    'framework/config/_icon-map.scss': {},
    'framework/config/_settings.scss': {}
  },
  'themes/theme3/_import-config.scss': {
    'themes/theme3/config/_color-scheme.scss': {},
    'themes/theme3/config/_color-map.scss': {},
    'themes/theme3/config/_font-map.scss': {},
    'themes/theme3/config/_icon-map.scss': {},
    'themes/theme3/config/_settings.scss': {},
    'themes/theme3/config/_notes-schemes.scss': {}
  },
  'books/intro-business/_import-config.scss': {
    'books/intro-business/config/_color-scheme.scss': {},
    'books/intro-business/config/_color-map.scss': {},
    'books/intro-business/config/_font-map.scss': {},
    'books/intro-business/config/_icon-map.scss': {},
    'books/intro-business/config/_settings.scss': {}
  },
  'framework/_import-mixins.scss': {
    'framework/mixins/_functions.scss': {},
    'framework/mixins/_typography.scss': {},
    'framework/mixins/_titles.scss': {},
    'framework/mixins/_notes.scss': {},
    'framework/mixins/_links.scss': {},
    'framework/mixins/_captions.scss': {},
    'framework/mixins/_tables.scss': {}
  },
  'framework/_update-config.scss': {},
  'themes/theme3/import-style.scss': {
    'themes/theme3/style/toc.scss': {},
    'themes/theme3/style/preface.scss': {},
    'themes/theme3/style/figures.scss': {},
    'themes/theme3/style/splash.scss': {},
    'themes/theme3/style/chapter-title.scss': {},
    'themes/theme3/style/appendices.scss': {},
    'themes/theme3/style/tables.scss': {},
    'themes/theme3/style/references.scss': {},
    'themes/theme3/style/eob.scss': {},
    'themes/theme3/style/index.scss': {},
    'themes/theme3/style/footnotes.scss': {}
  }
}
```

</details>

**Comment by openstaxalina** [comment]
This has been broken out into separate cards, linked above.  Closing
