### ISSUE TITLE
Analysis subtitle in Example

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#974]
@wilkus27 commented on [Tue Mar 12 2019](https://github.com/openstax/webview/issues/2218)

On katalyst01 (e.g. https://katalyst01.cnx.org/contents/i4nRcikn@3.7:jSsxLwzE@4/2-5-The-Precise-Definition-of-a-Limit) subtitle **Analysis** in Examples notes should be bolded.

webview:

![analysis_bold](https://user-images.githubusercontent.com/40228854/54197933-814c0600-44c5-11e9-9c15-368686ae6cb1.JPG)

PDF:

![analysis_bold_pdf](https://user-images.githubusercontent.com/40228854/54197940-87da7d80-44c5-11e9-87ec-512532812157.JPG)

---

@openstaxalina commented on [Mon Mar 25 2019](https://github.com/openstax/webview/issues/2218#issuecomment-476322753)

Can these be targeted using `data-type="title"`?
![Screen Shot 2019-03-25 at 1 27 15 PM](https://user-images.githubusercontent.com/7863733/54944545-be6eba00-4f01-11e9-974e-7d2d96d67397.png)

---

@openstaxalina commented on [Mon Mar 25 2019](https://github.com/openstax/webview/issues/2218#issuecomment-476389110)

If markup is inconsistent, we need to standardize the markup for the Analysis header in Examples to use `data-type="title"`.

---

@wilkus27 commented on [Thu Mar 28 2019](https://github.com/openstax/webview/issues/2218#issuecomment-477570333)

Will be resolved in recipes. I move it to this repo.

**Comment by uskka** [comment]
Looks good. Tested on katalyst01.
<img width="859" alt="Screenshot 2019-04-03 at 12 28 19" src="https://user-images.githubusercontent.com/40228918/55472310-139a8200-560c-11e9-91bb-80381556a3c6.png">
