### ISSUE TITLE
Solution in Example isn't bold

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#975]
@MartaSztuka commented on [Thu Feb 28 2019](https://github.com/openstax/webview/issues/2203)

In each chapter's subsection 'Exercise' should have bolded 'Solution'
https://katalyst01.cnx.org/contents/i4nRcikn@3.7:DSFrV7ZX@4/6-1-Areas-between-Curves

PDF:
![screenshot from 2019-02-28 13-35-06](https://user-images.githubusercontent.com/47241114/53567157-9ee0ad80-3b5e-11e9-8b59-694c7b865383.png)

webview:
![screenshot from 2019-02-28 13-34-51](https://user-images.githubusercontent.com/47241114/53567173-aef88d00-3b5e-11e9-8a8b-1116ca3d1484.png)

This should be bold

---

@staxly[bot] commented on [Thu Feb 28 2019](https://github.com/openstax/webview/issues/2203#issuecomment-468257872)

The maintainers of this repository would appreciate it if you could provide more information.

---

@openstaxalina commented on [Mon Mar 25 2019](https://github.com/openstax/webview/issues/2203#issuecomment-476322167)

Can these be targeted using `data-type="solution-title"`?
![Screen Shot 2019-03-25 at 1 25 08 PM](https://user-images.githubusercontent.com/7863733/54944456-82d3f000-4f01-11e9-89ac-288cffc33004.png)

---

@openstaxalina commented on [Mon Mar 25 2019](https://github.com/openstax/webview/issues/2203#issuecomment-476389065)

If markup is inconsistent, we need to standardize the markup for the Solution header in Examples to use `data-type="solution-title"`.

---

@wilkus27 commented on [Thu Mar 28 2019](https://github.com/openstax/webview/issues/2203#issuecomment-477572067)

Will be resolved in recipe. I move it to this repo.

**Comment by uskka** [comment]
Looks good. Tested on katalyst01.
<img width="851" alt="Screenshot 2019-04-03 at 12 31 34" src="https://user-images.githubusercontent.com/40228918/55472466-768c1900-560c-11e9-8d3c-865df13863d5.png">
