### ISSUE TITLE
Chapter outline missing 

### ISSUE THREAD

**Issue by uskka** [openstax/cnx-recipes#990]
In Webview there is no such thing in introduction chapters as Chapter Outline. It should be added. https://katalyst01.cnx.org/contents/_VPq4foj@8.4:eSE3vUlJ@4/Introduction-to-Linear-Functions

PDF

<img width="794" alt="Screenshot 2019-04-05 at 17 09 54" src="https://user-images.githubusercontent.com/40228918/55637746-0aedab80-57c6-11e9-880d-340f6ae85ca4.png">

Webview

<img width="849" alt="Screenshot 2019-04-05 at 17 10 40" src="https://user-images.githubusercontent.com/40228918/55637748-0aedab80-57c6-11e9-8e7a-42195f55ed04.png">

How it looks like in other books.
https://katalyst01.cnx.org/contents/i4nRcikn@4.1:H2TLb2-S@4/Introduction

<img width="1259" alt="Screenshot 2019-04-05 at 17 07 54" src="https://user-images.githubusercontent.com/40228918/55637750-0d500580-57c6-11e9-860f-96a892277f82.png">

**Comment by openstaxalina** [comment]
I assigned @Adrianltd - if this is incorrect, someone else can be assigned.

**Comment by uskka** [comment]
Looks good. Padding between figure and chapter outline will be added here: https://github.com/openstax/webview/issues/2242. Tested on katalyst01.
<img width="947" alt="Screenshot 2019-04-08 at 16 58 31" src="https://user-images.githubusercontent.com/40228918/55734620-29e77a00-5a20-11e9-9a63-9d5e63981cbe.png">
