### ISSUE TITLE
Inline equations in new line

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#995]
@openstaxalina commented on [Wed Mar 27 2019](https://github.com/openstax/content-managers/issues/695)

@wilkus27 commented on [Tue Mar 12 2019](https://github.com/openstax/webview/issues/2216)

On katalyst01 (e.g. https://katalyst01.cnx.org/contents/i4nRcikn@3.7:blZd_oDf@5/1-3-Trigonometric-Functions) sometimes inline equations display separately in new line:

![inline](https://user-images.githubusercontent.com/40228854/54189164-830bce80-44b1-11e9-853d-fcaa6b619fdf.JPG)

This is how it looks in PDF:

![inline_pdf](https://user-images.githubusercontent.com/40228854/54189181-8e5efa00-44b1-11e9-94bc-f3783ac41c7c.JPG)

---

@openstaxalina commented on [Wed Mar 13 2019](https://github.com/openstax/webview/issues/2216#issuecomment-472559217)

Is this a bug?  It looks like the math is tagged to be inline:
<img width="1332" alt="Screen Shot 2019-03-13 at 1 55 02 PM" src="https://user-images.githubusercontent.com/7863733/54306592-ac068f00-4597-11e9-8c0d-65df019150bf.png">

---

@wilkus27 commented on [Wed Mar 27 2019](https://github.com/openstax/webview/issues/2216#issuecomment-477157305)

This problem occurs also in unbaked raw-html file. Equation is in new line, because it is in separate `<p>`. I think it is a content issue.  cc @openstaxalina 

![equation](https://user-images.githubusercontent.com/40228854/55079871-5654db00-509d-11e9-85d4-fe0bd5a8992f.png)

---

@openstaxalina commented on [Wed Mar 27 2019](https://github.com/openstax/webview/issues/2216#issuecomment-477208913)

@wilkus27 thank you for the investigation!  I will move this to the content managers repo so that inline math in separate paragraphs can be taken out of those separate paragraphs.

---

@openstaxalina commented on [Wed Mar 27 2019](https://github.com/openstax/content-managers/issues/695#issuecomment-477209565)

The suggested change here is to remove the `<para>`s around math that is supposed to be inline.  We may want to discuss as a team to figure out how to locate and resolve these issues.  

---

@openstaxalina commented on [Thu Mar 28 2019](https://github.com/openstax/content-managers/issues/695#issuecomment-477626804)

@oscryan is investigating to confirm that removing the para tags resolves this issue.
Is so, we may ask Katalyst testers to help find all instances of this issue.

---

@openstaxalina commented on [Fri Mar 29 2019](https://github.com/openstax/content-managers/issues/695#issuecomment-478030555)

@oscryan waiting for this content to generate a PDF so she can confirm the markup change does not affect the PDF.

---

@oscryan commented on [Tue Apr 02 2019](https://github.com/openstax/content-managers/issues/695#issuecomment-479062240)

Confirmed. Removing the enclosing para tags fixes the online formatting, and does not change the PDF rendering.

---

@openstaxalina commented on [Tue Apr 02 2019](https://github.com/openstax/content-managers/issues/695#issuecomment-479140711)

thanks @oscryan - we will ask Katalyst if they can help compile all instances of this.

---

@openstaxalina commented on [Mon Apr 08 2019](https://github.com/openstax/content-managers/issues/695#issuecomment-480858901)

I am copying this to cnx-recipes so that Marta and Stefan can help us locate these instances.  CMs will remove the para tags around equations that are supposed to be inline, based on Katalyst's list of locations.

**Comment by openstaxalina** [comment]
As discussed in the team meeting today, if possible by May 17, please provide a list of all the locations where this issue occurs in _Calculus_ (all three volumes.)

**Comment by openstaxalina** [comment]
(Please provide chapter and section number and some other way to identify the location, such as an exercise number, example number, searchable nearby text, etc.)

**Comment by uskka** [comment]
@openstaxalina Here is a complete list of links to pages with elements ids, where it appears.

Calculus vol 1

id: fs-id1170572542966
Section: https://katalyst01.cnx.org/contents/i4nRcikn@4.1:Ib8OK9lb@6/1-4-Inverse-Functions

id: fs-id1170572551558
 Section: https://katalyst01.cnx.org/contents/i4nRcikn@4.1:Ib8OK9lb@6/1-4-Inverse-Functions

id: fs-id1170572545179
Section: https://katalyst01.cnx.org/contents/i4nRcikn@4.1:Ib8OK9lb@6/1-4-Inverse-Functions

id: fs-id1170572545252 
Section: https://katalyst01.cnx.org/contents/i4nRcikn@4.1:Ib8OK9lb@6/1-4-Inverse-Functions

id: fs-id1170572169132 
Section: https://katalyst01.cnx.org/contents/i4nRcikn@4.1:Ib8OK9lb@6/1-4-Inverse-Functions

id: fs-id1170572296560 
Section: https://katalyst01.cnx.org/contents/i4nRcikn@4.1:TjgBKRr3@9/1-5-Exponential-and-Logarithmic-Functions

id: fs-id1169738220862 
Section: https://katalyst01.cnx.org/contents/i4nRcikn@4.1:QP7ySueQ@6/3-9-Derivatives-of-Exponential-and-Logarithmic-Functions

Calculus vol 2

id: fs-id1170571095069 
Section: https://katalyst01.cnx.org/contents/HTmjSAcf@3.4:ofH2WYqc@6/4-2-Direction-Fields-and-Numerical-Methods

Calculus vol 3

id: fs-id1167793515856 
Section: https://katalyst01.cnx.org/contents/oxzXkyFi@3.7:94PKCMov@6/5-2-Double-Integrals-over-General-Regions

id: fs-id1167793603766 
Section: https://katalyst01.cnx.org/contents/oxzXkyFi@3.7:69B1kMnK@6/5-5-Triple-Integrals-in-Cylindrical-and-Spherical-Coordinates

**Comment by openstaxalina** [comment]
@uskka and @MartaSztuka this is excellent - thanks so much!

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #801](https://github.com/openstax/content-managers/issues/801) via [**ZenHub**](https://www.zenhub.com/)
