### ISSUE TITLE
 Implement feature control/feature flags in the framework

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#997]
# What happened?

(_Briefly but clearly describe the issue_)

# Reproducibility Details

- **Does it also happen in an incognito window?**: 
- **Does this happen in one place, a few places, or everywhere?**:

# Environment:

- **Book(s)**:
- **URL/Server**: 
- **Location (page number, chapter/section)**:
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots

(_attach here (please clearly label what environment each screenshot came from)_)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment]
I think this is a duplicate of #951.  @tomjw64 could you confirm when you get a chance?  Feel free to close this one if it is a duplicate.

**Comment by tomjw64** [comment]
@openstaxalina That is correct. The issues are duplicates.
