### ISSUE TITLE
Table numbering in EOC

### ISSUE THREAD

**Issue by uskka** [openstax/cnx-recipes#999]
Table numbering needs to be reseted after every section. It works correctly in normal sections but not in the EOC.
https://katalyst01.cnx.org/contents/_VPq4foj@8.4:JpxRbtW4@8.4/Review-Exercises

Webview

<img width="1197" alt="Screenshot 2019-04-10 at 14 53 41" src="https://user-images.githubusercontent.com/40228918/55880301-b5881480-5ba0-11e9-9161-278bed488a6e.png">

PDF

<img width="752" alt="Screenshot 2019-04-10 at 14 53 47" src="https://user-images.githubusercontent.com/40228918/55880302-b620ab00-5ba0-11e9-86c7-92b43ad88761.png">

**Comment by uskka** [comment]
Looks good. I can not test it in Algebra and Trigonometry because of a problem with baking on katalyst01. @helenemccarron approved that I can close it and leave this book for regression testing.

<img width="1241" alt="Screenshot 2019-04-12 at 16 38 11" src="https://user-images.githubusercontent.com/40228918/56046346-54e50d00-5d43-11e9-89e2-213b4517ad0d.png">

<img width="1117" alt="Screenshot 2019-04-12 at 16 51 14" src="https://user-images.githubusercontent.com/40228918/56046347-557da380-5d43-11e9-8e8d-e621fb80b9f0.png">

**Comment by MartaSztuka** [comment]
Looks good in Algebry&Trigonometry too, tested on katalyst01.
![Screenshot from 2019-04-18 16-04-31](https://user-images.githubusercontent.com/47241114/56366598-c9142a80-61f3-11e9-8ebb-9099efb2b029.png)
